### ISSUE TITLE
Out of Memory error for the  BLOB table

### ISSUE THREAD

**Issue by kirandba-hub** [darold/ora2pg#1001]
Hi Darold,

Migrated the BLOB table from the Oracle to Postgres,the table has "3857747" rows,and RAM is 15GB.when i give select * from table; it uses all 15GB memory and throwing Out of Memory.But Same query is working Oracle.
Can you please let me know what action need to be taken.

Thanks and Regards,
Kiran

**Comment by darold** [comment]
Hi, you should reduce the number of rows processed at a time by using `-L 50` or lower for example.
