### ISSUE TITLE
Ora2pg v21 bad output data encoding

### ISSUE THREAD

**Issue by gp4git** [darold/ora2pg#1002]
Hello,

*** the same configuration works well with version 20 ***

Linux Environment 
==============
locale
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=

ora2pg -t SHOW_ENCODING
Current encoding settings that will be used by Ora2Pg:
	Oracle NLS_LANG AMERICAN_AMERICA.AL32UTF8
	Oracle NLS_NCHAR AL32UTF8
	Oracle NLS_TIMESTAMP_FORMAT YYYY-MM-DD HH24:MI:SS.FF6
	Oracle NLS_DATE_FORMAT YYYY-MM-DD HH24:MI:SS
	PostgreSQL CLIENT_ENCODING UTF8
	Perl output encoding ''
Showing current Oracle encoding and possible PostgreSQL client encoding:
	Oracle NLS_LANG AMERICAN_AMERICA.WE8MSWIN1252
	Oracle NLS_NCHAR WE8MSWIN1252
	Oracle NLS_TIMESTAMP_FORMAT YYYY-MM-DD HH24:MI:SS.FF6
	Oracle NLS_DATE_FORMAT YYYY-MM-DD HH24:MI:SS
	PostgreSQL CLIENT_ENCODING WIN1252

BINMODE is commented out in ora2pg.conf and defaults to UTF8.

But when I export data, output files from tables containing non ascii characters are not encoded in UTF8.
For ex, when I execute file command on these, I get : 
<TABLE_NAME>_data.sql:       ISO-8859 text 
or even <TABLE_NAME>_data.sql:  Non-ISO extended-ASCII text, with very long lines  (exactly like in issue #885)

As emphasised at the beginning, when I revert to version 20, there is no encoding problem whatsoever.
Regression ?

Thank in advance for any tip that may solve this issue

Best regards

**Comment by darold** [comment]
On Oracle 12c and system I have the same default as you:
```
$ ora2pg -t SHOW_ENCODING -c config/ora2pg.conf
Current encoding settings that will be used by Ora2Pg:
        Oracle NLS_LANG AMERICAN_AMERICA.AL32UTF8
        Oracle NLS_NCHAR AL32UTF8
        Oracle NLS_TIMESTAMP_FORMAT YYYY-MM-DD HH24:MI:SS.FF6
        Oracle NLS_DATE_FORMAT YYYY-MM-DD HH24:MI:SS
        PostgreSQL CLIENT_ENCODING UTF8
        Perl output encoding ''
Showing current Oracle encoding and possible PostgreSQL client encoding:
        Oracle NLS_LANG AMERICAN_AMERICA.AL32UTF8
        Oracle NLS_NCHAR AL32UTF8
        Oracle NLS_TIMESTAMP_FORMAT YYYY-MM-DD HH24:MI:SS.FF6
        Oracle NLS_DATE_FORMAT YYYY-MM-DD HH24:MI:SS
        PostgreSQL CLIENT_ENCODING UTF8

$ locale
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

If I connect to sqlplus insert a row with french accent and run an export with Ora2Pg I have the same problem as you, data are not well encoded.

To fix that I need to set NLS_LANG before inserting the row in sqlplus:
```
export NLS_LANG=AMERICAN_AMERICA.AL32UTF8
```
then connect to the database and insert the row:
```
SQL> INSERT INTO T3 VALUES (1000, 'être à été où');

1 row updated.

SQL> COMMIT;
```

Now the export in and other computer with Ora2Pg, BINMODE, NLS_LANG and NLS_NCHAR are not defined in ora2pg.conf:
```
$ locale
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=

$ ora2pg -t DATA -c config/ora2pg.conf -a T3 -b tmp/
[========================>] 1/1 tables (100.0%) end of scanning.
[========================>] 1/1 rows (100.0%) Table T3 (1 recs/sec)
[========================>] 1/1 total rows (100.0%) - (1 sec., avg: 1 recs/sec).
[========================>] 1/1 rows (100.0%) on total estimated data (1 sec., avg: 1 recs/sec)

$ file tmp/T3_table.sql 
tmp/T3_table.sql: ISO-8859 text

$ cat tmp/T3_table.sql 
SET client_encoding TO 'latin1';
SET synchronous_commit TO off;

TRUNCATE TABLE t3;

COPY t3 (id,lbl) FROM STDIN;
1	�tre � �t� o�
\.
```
Here I have changed the client_encoding to latin1 in respect of the encoding output and data are well inserted in the destination database with the right encoding:
```
$ psql -f tmp/T3_table.sql
SET
SET
TRUNCATE TABLE
COPY 1

$ psql -c "SELECT * FROM t3;"
 id |      lbl      
----+---------------
  1 | être à été où
(1 row)
```

I was expecting that setting NLS_LANG in ora2pg.conf to AMERICAN_AMERICA.AL32UTF8 or executing `export NLS_LANG=AMERICAN_AMERICA.AL32UTF8` before running Ora2Pg will produce an UTF8 output but this is not the case. No need to say what I think about Oracle.

**Comment by darold** [comment]
I confirm that it is a regression, the utf8 output is working with v20.0 whatever are my local or environment variables. I will dig into the commits tomorrow.

**Comment by darold** [comment]
Ok, the regression was introduced in commit fa8e9de, I've just push commit 8792f3e that might fix the problem. Thanks for the report and please confirm that it works for you too.

**Comment by gp4git** [comment]
Forgot to write that it works also for me !
Thanks and regards for your good job.
