### ISSUE TITLE
PG_NUMERIC_TYPE

### ISSUE THREAD

**Issue by xinjirufen** [darold/ora2pg#1004]
Hi darold,
Parameter PG_ NUMERIC_ Type can only be used with ora2 pg.conf Configuration file?
How to make PG_ NUMERIC_ Type is used as a parameter in the ora2pg command?

**Comment by darold** [comment]
You can not, it can only be defined in the configuration file. This parameter is only used for TABLE export type so if you want to use a different value for some tables you will have to use two different configuration file.

**Comment by xinjirufen** [comment]
Thanks Darold for infromation
