### ISSUE TITLE
Default argument in procedure not converted

### ISSUE THREAD

**Issue by unrandom123** [darold/ora2pg#1006]
Hello.

I have a oracle procedure with a parameter

    x varchar2 default sysdate

(yeah, looks funny)
and it was converted to

    text default sysdate

but sysdate is not available in PG. Should it not have been converted to something else?

**Comment by darold** [comment]
This was not supported yet, commit ccd6015 adds this feature.

**Comment by unrandom123** [comment]
Thanks, will try as soon as Oracle issue is resolved.
