### ISSUE TITLE
Package specification is not exporting using ora2pg.

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#1008]
Package specification is not exporting using ora2pg. There is a package in oracle without a body. The variables in this package are calling from some other package. How we can migrate package specification only?

**Comment by darold** [comment]
Please use latest development code, commit e8da506 fix this problem. Thanks for the report.

**Comment by naveenjul29** [comment]
Thank you Darold. can you please share the path to download the latest development code and instructions to use the code?

**Comment by darold** [comment]
```
wget https://github.com/darold/ora2pg/archive/master.zip
unzip master.zip
cd ora2pg-master/
perl Makefile.PL
make
sudo make install
```

**Comment by naveenjul29** [comment]
thank you Darold.

**Comment by naveenjul29** [comment]
Issue is not resolved with the latest code. Below is the example:

**Oracle package code:**
create or replace PACKAGE       Employee_pkg  as
g_phone varchar2(50) := '12345' ;
c_Hiredate constant date := '10-JAN-10';
CURSOR employees_cursor IS  
    SELECT EMPLOYEE_ID,
          FIRST_NAME,
           SALARY
    FROM  EMPLOYEES;
CURSOR c_salary (low_salary NUMBER, high_salary NUMBER)
    IS
        SELECT *
        FROM EMPLOYEES
        WHERE SALARY BETWEEN low_salary AND high_salary;
TYPE emp_det is RECORD
(
EMP_NO NUMBER := 1,
EMP_NAME VARCHAR2(150):='aa',
MANAGER NUMBER:= 3,
SALARY NUMBER :=100 
);
TYPE emp_id IS TABLE OF number;
END Employee_pkg;

**ora2pg output:**
Looking global declaration in package pkg_globla_types...

then nothing is happend. package is not exported.

Please assist further.
