### ISSUE TITLE
Partition BY clause not generated with ora2pg 21.0

### ISSUE THREAD

**Issue by aymanadou** [darold/ora2pg#1010]
Hello,
export script for partitioned table doesn't generate PARTITION by clause correctly.
```
psql:./schema/tables/table.sql:149: ERROR:  syntax error at or near "("
LINE 20: ) PARTITION BY  () ;
```
PS : i 'am using PREFIX_PARTITION        1 

![image](https://user-images.githubusercontent.com/7149200/96256095-ede78a80-0faf-11eb-8f25-3547d19697a7.png)

**Comment by darold** [comment]
I can not reproduce, can you post the Oracle DDL for this partitioning?

**Comment by aymanadou** [comment]
[export.zip](https://github.com/darold/ora2pg/files/5415240/export.zip)
Hello Gilles,
here it is !

**Comment by darold** [comment]
Ok got it. Commit 246c47d might fix this issue, thanks for the export.

**Comment by aymanadou** [comment]
Hello,
Problem Solved . Thanks Gilles
