### ISSUE TITLE
MySQL Migration issues with Ora2pg

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#1015]
while exporting user defined types from MySQL to PostgreSQL, I got the below error:

**Can't call method "prepare" on an undefined value at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 11503.**

While exporting Materialized views from MySQL to PostgreSQL, got the below error:

**DBD::mysql::st execute failed: Table 'sakila.dba_mviews' doesn't exist at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 10879.
DBD::mysql::st execute failed: Table 'sakila.dba_mviews' doesn't exist at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 10879.**

Please assist me further.

**Comment by naveenjul29** [comment]
Darold, can you please help me on this?

**Comment by darold** [comment]
Commit 3e6db80 fixes this. Actually MySQL do not support materialized view so the export should return nothing.
