### ISSUE TITLE
cannot display all schemas in the report 

### ISSUE THREAD

**Issue by declare2006** [darold/ora2pg#1016]
I use Ora2PG v21 to generate a report of Oracle 12C in Linux: 
ora2pg -t SHOW_REPORT

I have configured the ora2pg.conf ,comment out the directive  of "Schema"
```
# Oracle schema/owner to use
# SCHEMA  IX
```

**Comment by darold** [comment]
If you want a report not limited to a single schema you have to unset the SCHEMA configuration directive:
`#SCHEMA   IX

**Comment by darold** [comment]
Sorry I had not understood that you had already disable the SCHEMA configuration directive. If the report doesn't include the object from the other schema this is because you don't use a DBA role to connect to the database. You will also have to disable USER_GRANTS.
