### ISSUE TITLE
Fail on unique index

### ISSUE THREAD

**Issue by unrandom123** [darold/ora2pg#1017]
I have an oracle index in order to make sure there is only one row in the table

    CREATE UNIQUE INDEX "MY_SCHEMA"."MY_INDEX" ON "MY_SCHEMA"."MY_TABLE" (1)

and ora2pg tries to create the following index

    CREATE UNIQUE INDEX my_index ON my_table ("1");

And that fails with

    ERROR: column "1" does not exist
    
There is of course not a column called "1" in my_table.

How can this be solved?

**Comment by darold** [comment]
@unrandom123  can you explain what this syntax is used for? Does 1 mean the column at position 1?

**Comment by unrandom123** [comment]
It's for a "singleton" table, i.e. a table with only one row.
The index is a function based index i.e. it the index value for a value is calculated with a function, it could be a hash or anything, but in this case the "function" is a constant value. And that means more than one row, then you will have an index key conflict.

Here is a better explaination of it
https://stackoverflow.com/questions/5477936/simple-constraint-to-limit-an-oracle-table-to-a-single-row

**Comment by darold** [comment]
Commit d2e17ac fixes this issue. Thanks.
