### ISSUE TITLE
Null in Clob col

### ISSUE THREAD

**Issue by orenbouni** [darold/ora2pg#1019]
Hello I have a table with CLOB, in that table i have120M row.
out of that i have 14M row tat have NULL value in the CLOB.
Id like to migrate the tables Data and ignore all the CLOB null value, what is the option to to do it?

**Comment by darold** [comment]
Do you mean exclude from data export rows where your CLOB column is a null value?

**Comment by orenbouni** [comment]
Yes,
if that table has 100 row and out this 100 15 has NULL in the CLOB, then I'll have 85 row in my export.
I will export only the Row with the CLOB data

**Comment by darold** [comment]
Then add a WHERE clause in the ora2pg.conf. See explanation in the configuration file or documentation.
