### ISSUE TITLE
Assess 100 Oracle DB

### ISSUE THREAD

**Issue by orenbouni** [darold/ora2pg#1021]
Hello,
can the CONF file can be tweak so i can enter let say 1000 DB of Oracle and run an Assessment and get a report for all the 1000 DB I'm planning to migrate and the schemas with in this DB

the only way an can think about it now is having 1000 CONF file and I'd like to avoid it.

**Comment by darold** [comment]
Look at ora2pg_scanner it is provided for that.

**Comment by orenbouni** [comment]
Thanks for that, i was looking at the Ora2PG_scanned and could not understend where do you set the Oracle Info,
do i need on CONF file per each DB/Schema or i can list them all in a CONF file or TXT file?

**Comment by darold** [comment]
How about "ora2pg_scanner --help"? I think the usage is well described otherwise please let me know what is not well explained.
