### ISSUE TITLE
Format issue : invalid input syntax for type oid

### ISSUE THREAD

**Issue by helmichamsi10** [darold/ora2pg#1025]
Hi,

I faced an error during migrating our DB from oracle to postgres11 using the last version ora2pg-21

below the issue:
DBD::Pg::db pg_putcopyend failed: ERROR:  invalid input syntax for type oid: "\x5b7b226b6579223a2264657374696e6174696f6e5f6f7574707574446576696365227d2c7b226b6579223a22666c6f77496e5f696e707574446576696365227d2c7b226b6579223a22666c6f77496e5f73656e646572227d2c7b226b6579223a2264657374696e6174696f6e5f72656365697665725f6964656e746966696572222c226f70657261746f72223a223d3d227d2c7b226b6579223a2264657374696e6174696f6e5f666c6f774f7574436f6e66696775726174696f6e5f6d657373616765466f726d61745f6d657373616765466f726d6174222c226f70657......

Any help ?

Cordially ,

**Comment by darold** [comment]
What is the description of the Oracle table and PostgreSQL migrated table, also point the column that is failing.

**Comment by helmichamsi10** [comment]
Hi darold,

You can find on the link  the description of the table on oracle and postgres DB
https://gofile.io/d/Zb821n

the failed column is PRESENTATIONCRITERIA_

Cordially,

**Comment by darold** [comment]
Why did you convert column into `presentationcriteria_` into oid data type, this should be a bytea ?

**Comment by helmichamsi10** [comment]
Our developers choose type oid , I think is supported by postgres !

**Comment by helmichamsi10** [comment]
if i change it to bytea did it works ?

**Comment by darold** [comment]
Type oid is like a bigint not a like bytea, I guess that this is not numbers that you have in the BLOB column. Yes it will work if you alter the column data type.

**Comment by helmichamsi10** [comment]
just change the type to bytea , their is nothing to change on file ora2pg.conf ?

**Comment by darold** [comment]
unless you have set `BLOB:oid` in the DATA_TYPE configuration directive instead of the default `BLOB:bytea`, no.

**Comment by helmichamsi10** [comment]
I didn't put anything on DATA_TYPE about blob .
I have just change the type from oid to bytea and it works !

**Comment by helmichamsi10** [comment]
Hi darold,

Is it the only solution to change to type from oid to bytea ? cause in my situation i have arround 100 table to change their column from oid to bytea 

Cordially,

**Comment by darold** [comment]
Well perhaps the developers that have chosen the oid data type know why they have done that but in my knowledge of the situation you can not insert BLOB into an integer, but I'm probably missing something. However this is quite easy to change all the column data type using a SQL script.

**Comment by helmichamsi10** [comment]
Yes , i'll see about it else i have this problem when i added DATA_TYPE BLOB:oid
COPY g_jasperreportingconfig, line 28, column workingfile_: "PK" at /usr/local/share/perl5/Ora2Pg.pm line 15116.
FATAL: ERROR:  invalid input syntax for type oid: "PK"

**Comment by darold** [comment]
:-)

**Comment by helmichamsi10** [comment]
Hi darold ,

I have changed all the types from oid to bytea and during the deploying of our application i have faces this error
                                    ServiceException: ERROR: column "flowcontent_" is of type bytea but expression is of type bigint
2020-11-03 13:47:54,545 INFO  [stdout]  Hint: You will need to rewrite or cast the expression.
2020-11-03 13:47:54,545 INFO  [stdout] Position: 671
2020-11-03 14:50:11,176 INFO  [stdout] (default task-1) Caused by: org.postgresql.util.PSQLException: Cannot convert the column of type BYTEA to requested type long.
Caused by: com.palmyra.arch.exception.ServiceException: org.hibernate.exception.SQLGrammarException: could not execute query
	at com.palmyra.arch.service.AbstractServiceDriver.invokeMethod(AbstractServiceDriver.java:72) [service-core-12.6.3.35.15.jar:]
	at com.palmyra.arch.service.AbstractServiceDriver.invokeService(AbstractServiceDriver.java:57) [service-core-12.6.3.35.15.jar:]
	at com.palmyra.arch.service.AbstractServiceDriver.callInstance(AbstractServiceDriver.java:22) [service-core-12.6.3.35.15.jar:]
	at com.palmyra.arch.service.facade.ejbs.sef.FacadeBean$2.run(FacadeBean.java:159) [service-ejb-12.6.3.35.jar:]
	at java.security.AccessController.doPrivileged(Native Method) [rt.jar:1.8.0_161]
	at javax.security.auth.Subject.doAs(Subject.java:422) [rt.jar:1.8.0_161]
	at com.palmyra.arch.security.SecurityManager.runAs(SecurityManager.java:515) [security-12.6.3.35.4.jar:]
	... 162 more

Do you have an idea ?

Cordially,

**Comment by darold** [comment]
looks like this column must be a bigint not a bytea at the origin this should not be a BLOB, do you have the Oracle description of this table?

**Comment by helmichamsi10** [comment]
all the columns have the origin type BLOB (Oracle) and oid (Postgres)
this is the oracle description : 
STATUSNOTIFICATION" 
   ( 	"TYPE_" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"RELATEDSTATUS_" VARCHAR2(255 CHAR), 
	"CREATIONDATE_" TIMESTAMP (6) NOT NULL ENABLE, 
	"CREATORUSERID_" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"RELATEDREFERENCE_" VARCHAR2(255 CHAR), 
	"FLOWCONTENT_" BLOB
)

**Comment by darold** [comment]
Well I don't know the query used but the application is doing the wrong thing following the column data type. The application must be fixed.

**Comment by helmichamsi10** [comment]
Hi Darold,

i have migrate the data from oracle to postgres using bytea and my question is it any way to convert the data from bytea to oid using a procedure ?

Best Regards

**Comment by helmichamsi10** [comment]
Hi Darold,

I have migrated the data from oracle to postgres using bytea and my question is it any way to convert the data from bytea to oid using a procedure ?

Best Regards
