### ISSUE TITLE
Oracle Index Migration : double quote missing 

### ISSUE THREAD

**Issue by traxverlis** [darold/ora2pg#1028]
When migrating indexes from an Oracle database, double quotes are missing.

Oracle source code
`CREATE INDEX "IX_NextConsommationNormale_001" ON "NextConsommationNormale" ("CodeCollectivite", "CodeNature", "NumeroRefMandat", SUBSTR("Identifiant",5,4), SUBSTR("Identifiant",10,1)) `
  

translated code version 21.0 :
CREATE INDEX "IX_NextConsommationNormale_001" ON "NextConsommationNormale" ("CodeCollectivite", "CodeNature", "NumeroRefMandat", SUBSTR("Identifiant",5,4), SUBSTR(**Identifiant**,10,1));

**Comment by darold** [comment]
This look to have already been fixed, can you confirm by using latest development code?
