### ISSUE TITLE
Oracle Index Migration : missing bracket with ||

### ISSUE THREAD

**Issue by traxverlis** [darold/ora2pg#1029]
Hi

When I have the ||   on Index the translation  doesn't add the brackets

source Code from Oracle SQL dev
CREATE INDEX"IX_POPM_001" ON "POPM" ("COLLCOD", "OPEGANN", "OPEGNUM", "OBJECODNAT", "OPEILIG", TO_CHAR("BUDGEXE")||"OPPMTYP")

Translated Code
CREATE INDEX "IX_POPM_001" ON "POPM" ("COLLCOD", "OPEGANN", "OPEGNUM", "OBJECODNAT", "OPEILIG", ("BUDGEXE"::varchar)||"OPPMTYP");

Error : 
ERREUR:  erreur de syntaxe sur ou près de « || »

Correct  Code
CREATE INDEX "IX_POPM_001" ON "POPM" ("COLLCOD", "OPEGANN", "OPEGNUM", "OBJECODNAT", "OPEILIG", (("BUDGEXE"::varchar)||"OPPMTYP"));

**Comment by darold** [comment]
Fixed in commit 8a8d72c, thanks for the report.
