### ISSUE TITLE
Tables not considered in migration

### ISSUE THREAD

**Issue by soypabloangel** [darold/ora2pg#1030]
Hi Darold! 
Which oracle tables do you not consider by default ora2pg in your migration?. Thank you for your attention.

**Comment by darold** [comment]
```
$ grep "our @EXCLUDED_TABLES" lib/Ora2Pg.pm
our @EXCLUDED_TABLES = ('USLOG\$_.*', 'MLOG\$_.*', 'RUPD\$_.*', 'MDXT_.*', 'MDRT_.*', 'MDRS_.*', 'DR\$.*', 'CLI_SWP\$.*', 'LOGMNR\$.*', 'REPCAT\$.*', 'JAVA\$.*', 'AQ\$.*', 'BIN\$.*', 'SDO_GR_.*', '.*\$JAVA\$.*', 'PROF\$.*', 'TOAD_PLAN_.*', 'SYS_.*\$', 'QUEST_SL_.*');
our @EXCLUDED_TABLES_8I = ('USLOG$_%', 'MLOG$_%', 'RUPD$_%', 'MDXT_%', 'MDRT_%', 'MDRS_%', 'DR$%', 'CLI_SWP$%', 'LOGMNR$%', 'REPCAT$%', 'JAVA$%', 'AQ$%', 'BIN$%', '%$JAVA$%', 'PROF$%', 'TOAD_PLAN_%', 'SYS_%$', 'QUEST_SL_%');
```

**Comment by soypabloangel** [comment]
Thank you Darold for your answer. However, I also note that there are tables that do not migrate them and are not in the filter such as tables OPS_OOOIMSG, TOAD_FREE_SPACE (consider that it is not TOAD_PLAN_%) o SQL_EXPLAIN_PLAN.
Please, if you can tell me if any other filter exists.

**Comment by darold** [comment]
The other filters are the OWNER (the value you set to SCHEMA configuration directive), the tables you have set to ALLOW or EXCLUDE  configuration directives, the tables that are related to materialized views and the table that do not respect this filters:
```
AND A.TEMPORARY='N' AND (A.NESTED != 'YES' OR A.LOGGING != 'YES') AND A.SECONDARY = 'N'
AND (A.IOT_TYPE IS NULL OR A.IOT_TYPE = 'IOT')
```
The query to retrieve table list is computed in function `_table_info()` in file lib/Ora2Pg.pm at line 11834.
