### ISSUE TITLE
SRID extraction not working for VIEWs

### ISSUE THREAD

**Issue by SebAlbert** [darold/ora2pg#1032]
For Geometry columns in a view, ora2pg in type `COPY` gives me WKT of the form `SRID=;LINESTRING`....., but empty SRID is invalid.

After investigating ora2pg code and hand-issuing SQL queries to Oracle, I found that the SRID detection in `sub _column_attributes`  does not work for VIEWs. I am exporting data with `VIEW_AS_TABLE` from a database that I don't own and am merely given VIEWs in to get my data. Also, with type `TABLE` ora2pg fell back to the configured `DEFAULT_SRID`.

The basic problem is that I cannot see the metadata in Oracle's `ALL_SDO_GEOM_METADATA` for the views. (And if I could, the `OWNER` column there would be only the one of the underlying table, not of the view, which is what I am exporting as `SCHEMA` directive in ora2pg.)

However, connecting via DBeaver, I can see the SRID in the data in the rows. Could we add an "SRID detection from data" (similar to the possible data-based detection of geometry types by looking at 50,000 rows)?

Or, as a quicker workaround for me, could we add manual configuration of SRIDs for specific columns? I'm using `INTERNAL` mode, so the `Ora2Pg::GEOM` must know the correct type.

Or even better, could the `Ora2PG::GEOM` thing read the SRID from every data item individually instead of putting general column info in the EWKT string?

**Comment by darold** [comment]
I think we can limit this implementation to case 3 (per data detection) if the performances lost is limited. For huge number of rows I think we will need to implement case 2 to preserve performances gain.

**Comment by SebAlbert** [comment]
Ah, this looks easier than I had thought. But I don't understand the meaning of https://github.com/darold/ora2pg/blob/master/lib/Ora2Pg/GEOM.pm#L192 - why are you comparing the uninitialised field (hash entry) with an empty string, and based on that you use the `srid` from metadata (probably always) or from the data itself (probably never)?

**Comment by darold** [comment]
Honestly I don't remember but reading the line I guess that it means that we set the srid only once if it has not already been set, but today I don't have a table with geometry at my hand to test the code. Maybe if you want to override the srid value for each row you just have to remove the condition.

**Comment by darold** [comment]
I finally found the time before publishing a new release to look at it and I think that last commits allow to take the SRID from each data read. At least in my test it does. Available for geometry extraction type INTERNAL only in COPY mode and also in WKT mode with the INSERT data export mode. Thanks.
