### ISSUE TITLE
Option TEST: Errors in  [PRIMARY KEYS] and [UNIQUE CONSTRAINTS] counts 

### ISSUE THREAD

**Issue by dlc75** [darold/ora2pg#1033]
Hello,
In the Oracle DB, I have 3 schemas RBSB, RBSBVABF, Z014327 with same definitions of tables and constraints (PK, UK) 
If I launch ora2PG TEST on one schema (RBSB, for example) with the following ora2pg configuration :
EXPORT_SCHEMA   1
SCHEMA RBSB
PG_SCHEMA RBSB

I got 
...
[ERRORS UNIQUE CONSTRAINTS COUNT]
Table RBSB.rbsbtrefarbo doesn't have the same number of unique constraints in source database (1) and in PostgreSQL (3).
Table RBSB.batch_job_instance doesn't have the same number of unique constraints in source database (1) and in PostgreSQL (3).
...

[ERRORS PRIMARY KEYS COUNT]
Table RBSB.rbsbtstat doesn't have the same number of primary keys in source database (1) and in PostgreSQL (3).
Table RBSB.batch_step_execution doesn't have the same number of primary keys in source database (1) and in PostgreSQL (3).
...
In the PostgreSQL DB , I have 3 definitions of the same UK and PK (one per schema) 
It seems that the Schema is not taken into account on the PostgreSQL DB during the comparison of UK and PK.
Thanks in advance for your response
Dominique

**Comment by darold** [comment]
Please use last development code, I've just pushed commit 9cd661c that should fix this issue. Actually all schema defined in PG_SCHEMA was turned lower case and I guess that you have created RBSB upper case. Let me know.

**Comment by dlc75** [comment]
Hi, 
I Download and re-test with the new release. 
I always have the same problems.
I send you two documents to explain the problem about PK et UK with same definition (and name) defined in several schemas.
[Ora2pg_PK_Comparison.txt](https://github.com/darold/ora2pg/files/5582371/Ora2pg_PK_Comparison.txt)
[Ora2pg_UK_Comparison.txt](https://github.com/darold/ora2pg/files/5582372/Ora2pg_UK_Comparison.txt)
Thanks in advance for your response
Dominique

**Comment by darold** [comment]
Commit 30d2a4a fixes this issue.
