### ISSUE TITLE
Installation in windows with different install directory

### ISSUE THREAD

**Issue by selvakumarmurugaiah** [darold/ora2pg#1034]
Hi Team

Since I dont have permission to create directory in C drive, I am using prefix to give different directory path in windows installation, but it fails. I could notice from error it is appending PREFIX and also the perl/site/bin directory path as well

perl Makefile.PL PREFIX=C:\Oraclemigration\ora2pg

gmake && gmake install

ERROR: Can't create 'C:\Oraclemigration\ora2pgC:\Oraclemigration\strawberry-perl-5.32.0.1-64bit\perl\site\bin'
mkdir C:\Oraclemigration\ora2pgC:\: Invalid argument; The filename, directory name, or volume label syntax is incorrect at C:/Oraclemigration/strawberry-perl-5.32.0.1-64bit/perl/lib/ExtUtils/Install.pm line 489.

**Comment by darold** [comment]
Actually you don't have to install anything for what you want to do, just move the Ora2Pg source directory under `C:\Oraclemigration\`, if I recall well `move` is the equivalent to `mv` on Linux so I guess the following is enough:
```
move ora2pg C:\Oraclemigration\ora2pg
```

Then when you call the ora2pg command use the following:
```
cd C:\Oraclemigration\ora2pg
perl -I. ora2pg -c .....
```
or from any other directory:
```
perl -IC:\Oraclemigration\ora2pg ora2pg -c .....
```
so that ora2pg can found its own libraries. That should works.

**Comment by selvakumarmurugaiah** [comment]
Thanks Darold for the reply.

Instead of moving then I will directly use the extracted source folder, assuming can use the ora2pg_dist.conf file directly,  available in source folder, tried like below, getting below error. I also notice that ora2pg.bat is created in this location C:\Oraclemigration\strawberry-perl-5.32.0.1-64bit\perl\site\bin.  Should I move the ora2pg.bat from perl\site\bin to ora2pg-21.0 folder and try? Please advice

C:\Oraclemigration\ora2pg-21.0>perl -I. ora2pg -t SHOW_VERSION -C ora2pg_dist.conf
Can't open perl script "ora2pg": No such file or directory

Downloaded source from below link
https://github.com/darold/ora2pg/archive/v21.0.zip

**Comment by darold** [comment]
in this case the command will be:
```
perl -I. scripts/ora2pg -t SHOW_VERSION -c ora2pg_dist.conf
```
Note the minus `-c` option for config file and as you certainly noticed there is no ora2pg script directly in the source directory but it resides in the `scripts/` sub directory.

**Comment by selvakumarmurugaiah** [comment]
Thanks Darod for the reply.

Now I am receiving the connection error, but it is a valid connection string to connect to remote database, ORACLE_HOME environment variable is also set to instantclient-19.8.0. We don't have service id hence given service_name hope it is not an issue. Please advice

perl -I. scripts/ora2pg -t SHOW_VERSION -c ora2pg_dist.conf
[2020-11-20 16:49:10] Ora2Pg version: 21.0
[2020-11-20 16:49:10] Trying to connect to database: dbi:Oracle:host=hostname;service_name=servicename;port=1622
[2020-11-20 16:49:11] FATAL: -1 ... ERROR OCIEnvNlsCreate. Check ORACLE_HOME (Linux) env var or PATH (Windows) and or NLS settings, permissions, etc.
Aborting export...

**Comment by darold** [comment]
Looks like you have not set the environment variables ORACLE_HOME and PATH correctly.

**Comment by selvakumarmurugaiah** [comment]
Thanks Darold for quick response.

I have downloaded below oracle clients and extracted all of them into single folder C:\Oraclemigration\strawberry-perl-5.32.0.1-64bit\instantclient_19_8. PFA screenshot of the extracted folder location. I have pointed to the screenshot root location, for the ORACLE_HOME and appended to the PATH variable as well, and was able to print the same in $ENV({ORACLE_HOME}),$ENV({PATH}). Please advice

ORACLE_HOME  =  C:\Oraclemigration\strawberry-perl-5.32.0.1-64bit\instantclient_19_8
PATH = XXX;YYY;C:\Oraclemigration\strawberry-perl-5.32.0.1-64bit\instantclient_19_8

<img width="594" alt="oracleclient" src="https://user-images.githubusercontent.com/74726736/99798677-6addc500-2b57-11eb-9447-d9b8f34d5aa6.png">


instantclient-basic-windows.x64-19.8.0.0.0dbru.zip
instantclient-jdbc-windows.x64-19.8.0.0.0dbru.zip
instantclient-sdk-windows.x64-19.8.0.0.0dbru.zip
instantclient-sqlplus-windows.x64-19.8.0.0.0dbru.zip

**Comment by darold** [comment]
Well unfortunately I can not help more on Windows installation I don't use it, I hope someone else can help you to go further.

**Comment by selvakumarmurugaiah** [comment]
Thanks Darold. Could you please help me with the link containing steps to be followed for linux setup. Perl version 5.8.8 is okay for linux setup?

**Comment by selvakumarmurugaiah** [comment]
Hi Darold Issue got resolved ORACLE_HOME it was expecting at system level rather than account level. Thanks for your help.
