### ISSUE TITLE
ora2pg_scanner mysql fails with  Unknown column DATA_TYPE

### ISSUE THREAD

**Issue by zejeanmi** [darold/ora2pg#1037]
Hello

We run ora2pg_scanner on a 5.1.73 mysql database and get :
`DBD::mysql::st execute failed: Unknown column 'DATA_TYPE' in 'where clause' at /usr/local/share/perl5/Ora2Pg/MySQL.pm line 1411.
`

This issue is very similar to issue #746. (commit 2adeb67)
DATA_TYPE does not exists in table INFORMATION_SCHEMA.ROUTINES before MySQL 5.5.0. Replace it with column
DTD_IDENTIFIER for prior version

The correction should probably  be applied in other parts of the script referencing DATA_TYPE.
On lines 955 , 1409 (our current problem) and 1417.

Thank you !

**Comment by darold** [comment]
Commit 9949c0f fixes this issue.
