### ISSUE TITLE
Support regexp in VIEW_AS_TABLE config option [request]

### ISSUE THREAD

**Issue by lflobo** [darold/ora2pg#104]
would be very useful if you could set:
```bash
VIEW_AS_TABLE MY_PREFIX_.*
```

regards,
LL

**Comment by darold** [comment]
Hi,

This is already the case. Please use latest code from github there was lot of code rewrite with directive ALLOW/EXCLUDE/VIEW_AS_TABLE.

Using your VIEW_AS_TABLE directive, use the following command to extract table definition:

    ora2pg -c [...]/ora2pg.conf -t TABLE

then to extract data:

    ora2pg -c [...]/ora2pg.conf -t COPY

together with all real tables.

Regards,
