### ISSUE TITLE
column name is kept lowercase when -J is used

### ISSUE THREAD

**Issue by Code-UV** [darold/ora2pg#1040]
when column name is lowercase and I set "-j 5 -J 5",  它会报错 It will report an error：FATAL: ORA-00904: "ID": invalid identifier (DBD ERROR: error possibly near <*> indicator at char 55 in 'SELECT "id","name" FROM "GTEST"."TEST" a WHERE ABS(MOD(<*>id, 5)) = :p1')

I Think it should be SELECT "id","name" FROM "GTEST"."TEST" a WHERE ABS(MOD(<*>"id", 5)) = :p1

**Comment by darold** [comment]
Please use a short title for the issue, this is not the place to write the comment.

Las commit 13b9693 might solve this issue.

**Comment by Veka** [comment]
Same error again if column name is lowercase and preserve_case=0.
Removing this condition check helps:
` if ($self->{preserve_case}) {`
