### ISSUE TITLE
Connection failed for Oracle cloud Autonomous Transaction Processing database

### ISSUE THREAD

**Issue by deepakp555** [darold/ora2pg#1041]
Hello Sir,

I want to connect with Oracle cloud Autonomous Transaction Processing database using ora2pg tool. Although i can connect the same database with my client PC using and also able to connect other databases sql plus utility with ora2pg tool  but when running the 
ora2pg -t SHOW_VERSION -c C:\ora2pg\Project_Name\config\ora2pg.conf.
it say TNS connection closed.
Do we need some different setting.

**Comment by darold** [comment]
Probably, I guess that there is some additional API function to be called to connect to the cloud database. This is not supported until now.
