### ISSUE TITLE
when column name is lowercase and I set "-j 5 -J 5", It will report an error

### ISSUE THREAD

**Issue by Code-UV** [darold/ora2pg#1042]
when column name is lowercase and I set "-j 5 -J 5", It will report an error：FATAL: ORA-00904: "ID": invalid identifier (DBD ERROR: error possibly near <*> indicator at char 55 in 'SELECT "id","name" FROM "GTEST"."TEST" a WHERE ABS(MOD(<*>id, 5)) = :p1')

**Comment by darold** [comment]
Duplicate of #1040 , fixed with commit 13b9693
