### ISSUE TITLE
export synonyms

### ISSUE THREAD

**Issue by dlc75** [darold/ora2pg#1043]
Hello, 

Even if I konw that the preferred method to translate Oracle synonym is setting search_path,
I detect the following problem during conversion of Oracle synonyms into PosgreSQL views

### In the Oracle database
SELECT * FROM dba_synonyms WHERE table_owner='BUM_DEV_2';
OWNER |SYNONYM_NAME      |TABLE_OWNER|TABLE_NAME        |DB_LINK|
---------|------------------------|--------------|----------------------|-------|
PUBLIC |TBUMT_BANDEAU        |BUM_DEV_2  |TBUMT_BANDEAU     |          |

### Script .../schema/synonyms/synonym.sql

CREATE VIEW **public.public.tbumt_bandeau** AS SELECT * FROM bum_dev_2.tbumt_bandeau;
ALTER VIEW **public.public.tbumt_bandeau** OWNER TO bum_dev_2;
GRANT ALL ON **public.public.tbumt_bandeau** TO public;
RATHER THAN 
CREATE VIEW **public.tbumt_bandeau** AS SELECT * FROM bum_dev_2.tbumt_bandeau;
ALTER VIEW **public.tbumt_bandeau** OWNER TO bum_dev_2;
GRANT ALL ON **public.tbumt_bandeau** TO public;

Thanks in advance for your response

**Comment by darold** [comment]
Commit 0422295 fixes this issue.
