### ISSUE TITLE
Question : Ongoing transactions migrate

### ISSUE THREAD

**Issue by kirandba-hub** [darold/ora2pg#1044]
Hi Darold, 

Is there anyway to migrate the ongoing transactions also. Suppose on oracle I started the data conversation meanwhile a new data is inserted. It is possible to convert those new transactions also. 
Or else we need to perform the migration during downtime only. 

Thanks, 
Kiran

**Comment by darold** [comment]
Usually the migration is done during downtime. But some "dead data" or archived data can be imported later using the WHERE configuration directive following a filter. You can also have a look the DATADIFF configuration directive to more advanced capabilities. But now there is no ongoing transaction migration feature yet, some commercial product might help.
