### ISSUE TITLE
Migrate new data to exist postgres table

### ISSUE THREAD

**Issue by Montego** [darold/ora2pg#1045]
It's a cool tools for migrations and I migrated few tables already. But now, one of them have a new data. So,i would like to migrate this new data from oracle to postgres without clearing data,which i already migrated. Is it possible with ora2pg?How?

**Comment by darold** [comment]
If you are lucky to only have new record and that there is a column that you can use to filter the rows then the WHERE configuration directive of ora2pg.conf is your friend.
 
This is kind of duplicate of #1044.

**Comment by Montego** [comment]
Thank you very much, but it didn't work for me. Myabe i did something wrong.In ora2pg.conf was:
-first migration:
    TYPE           COPY
    ALLOW           PLAT_WS
    WHERE PLAT_WS[ID_>='12761878']
as result are 1606298 rows in postgres. 
-second migration:
    TYPE           COPY
    ALLOW           PLAT_WS
    WHERE PLAT_WS[ID_='49']
as result is 1 row with id 49. Other was deleted.
I need some advice.

**Comment by darold** [comment]
You must disable TRUNCATE_TABLE in ora2pg.conf before running the second migration. You should output to file to check what Ora2Pg will execute.

**Comment by Montego** [comment]
yeap, i missed it. It works now!Awersome!Thank you. You did a cool tool:)
