### ISSUE TITLE
partition table problem

### ISSUE THREAD

**Issue by xinjirufen** [darold/ora2pg#1048]
hi，
  Partition table ddl sql have problem。Error info：PRIMARY KEY constraint on table "fxf_partition_test" lacks column "create_month" which is part of the partition key。
[oracle_ddl.txt](https://github.com/darold/ora2pg/files/5663340/oracle_ddl.txt)
[pg_ddl.txt](https://github.com/darold/ora2pg/files/5663344/pg_ddl.txt)

**Comment by darold** [comment]
Commit 78937b0 fixes this issues.
