### ISSUE TITLE
Client encoding ignored when PG_DSN used

### ISSUE THREAD

**Issue by thleblond** [darold/ora2pg#105]
When PG_DSN is set, the CLIENT_ENCODING  is ignored and is always set to default UTF8. This produces errors "invalid byte sequence" when dumping data to pg database.

I fixed the issue by forcing the client_encoding in the _dump_to_pg function.

# Connect to PostgreSQL if direct import is enabled
	my $dbhdest = undef;
	if ($self->{pg_dsn}) {
		$dbhdest = $self->_send_to_pgdb();
		$self->logit("Dumping data from table $rname into PostgreSQL...\n", 1);
		$self->logit("Disabling synchronous commit when writing to PostgreSQL...\n", 1);
		if (!$self->{synchronous_commit}) {
			my $s = $dbhdest->do("SET synchronous_commit TO off") or $self->logit("FATAL: " . $dbhdest->errstr . "\n", 0, 1);
		}
		my $s = $dbhdest->do( "SET client_encoding TO '\U$self->{client_encoding}\E';") or $self->logit("FATAL: " . $dbhdest->errstr . "\n", 0, 1); // I added that line.
	}

So it works, but not sure it is the best fix.
Perharps, it should be set in the cmd_head part attribute, before calling _dump_to_pg .
 
I am currently using ora2pg-14.0 .

**Comment by darold** [comment]
Hi,

Thanks for the report, please use latest code from github I just applied your patch in commit 058c06c. There's also several fixes since 14.0.

Best regards,
