### ISSUE TITLE
ORA-08177 can't serialize access for this transaction

### ISSUE THREAD

**Issue by xinjirufen** [darold/ora2pg#1051]
Hello,
 In four tables migration process，i get this error "ORA-08177 can't serialize access for this transaction"，but i don't DML the same table in the migration process。

Run environment info：ora2pg version is v21.0， oracle12c，postgres12
one of four tables ora2pg.conf 
[ora2pg.txt](https://github.com/darold/ora2pg/files/5694320/ora2pg.txt)

**Comment by darold** [comment]
You can try to export your data with setting TRANSACTION to readonly in ora2pg.conf.
