### ISSUE TITLE
export_schema.sh output inconsistent for TABLEs (unqualified) and VIEWs (qualified)

### ISSUE THREAD

**Issue by otterrisk** [darold/ora2pg#1052]
When running `ora2pg` with the `--init_project` argument and calling the resulting `export_schema.sh` script TABLE definitions in the `schema/tables/table.sql` output include unqualified table names (e.g. TABLE_NAME), while VIEW definitions in the `schema/views/view.sql` output include qualified table names (e.g. SCHEMA.TABLE_NAME). This results in errors similar to:

    $ ./import_all.sh -d <database> -f -h <host> -n <schema> -o <owner> -U <user> -x
    [...]
    Would you like to import VIEW from ./schema/views/view.sql? [y/N/q] y
    Running: psql --single-transaction  -h <host> -U <user> -d <database> -f ./schema/views/view.sql
    SET
    SET
    CREATE VIEW
    psql:./schema/views/view.sql:X: ERROR:  relation "schema.table_name" does not exist
    LINE 3:  FROM SCHEMA.TABLE_NAME i
                  ^
    ERROR: an error occurs when importing file ./schema/views/view.sql.

when running the `import_all.sh` script the way presented above, although importing TABLEs from `schema/tables/table.sql` one step before works fine.

How can I make the `export_schema.sh` behavior consistent for TABLEs and VIEWs?

**Comment by darold** [comment]
Does EXPORT_SCHEMA is activated in your ora2pg.conf?

**Comment by otterrisk** [comment]
No, it's not, i.e. I don't set it explicitly. I assume that the default value of `0` is taken from `/etc/ora2pg/ora2pg.conf`. My target schema in PostgreSQL is different than the original Oracle schema.

**Comment by darold** [comment]
Soory for the response delay, I guess that you have found the solution. But yes EXPORT_SCHEMA must be enabled and a value corresponding to the schema in PostgreSQL must be set using PG_SCHEMA.
