### ISSUE TITLE
Data migration issues

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#1053]
**First Issue**

I got the below error while copying the data:

**DBD::Pg::db pg_putcopyend failed: ERROR:  duplicate key value violates unique constraint "bkp_emp_pkey"
DETAIL:  Key (empno)=(7839) already exists.
CONTEXT:  COPY bkp_emp, line 1 at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 15116.
FATAL: ERROR:  duplicate key value violates unique constraint "bkp_emp_pkey"
DETAIL:  Key (empno)=(7839) already exists.
CONTEXT:  COPY bkp_emp, line 1
Aborting export...**

1.	We don't have the primary key in bkp_emp table in PostgreSQL, still it is giving error
2.	In the source also we don't have duplicate data, still it is giving error

**below is the table definition in postgresql:**
-- Table: bkp_emp

-- DROP TABLE bkp_emp;

CREATE TABLE bkp_emp
(
    empno numeric(38,0) NOT NULL,
    ename text COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE bkp_emp
    OWNER to postgres;

**Second issue**

**ERROR:  column "job" of relation "emp" does not exist at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 15101.
FATAL: ERROR:  column "job" of relation "emp" does not exist
Aborting export...**

1.     "job" column is there in "emp" table, still it is giving error

CREATE TABLE otv2.emp
(
    empno smallint NOT NULL,
    ename character varying(10) COLLATE pg_catalog."default",
    job character varying(9) COLLATE pg_catalog."default",
    mgr smallint,
    hiredate date,
    sal double precision,
    comm double precision,
    deptno smallint
)

TABLESPACE pg_default;

ALTER TABLE otv2.emp
    OWNER to postgres;

Please help me in resolving these issues

**Comment by darold** [comment]
What are the output of the following commands executed in psql:
* `\d bkp_emp`
* `\d otv2.emp`

**Comment by naveenjul29** [comment]
can you please give me the full command to execute and give it to you?

**Comment by darold** [comment]
You don't have access to the psql command? If you have access connect it to your database and just type the lines from previous note.

**Comment by naveenjul29** [comment]
![emp](https://user-images.githubusercontent.com/67134199/102634460-e1320f00-4177-11eb-8e0c-dad606df81e0.PNG)
![bkp_emp](https://user-images.githubusercontent.com/67134199/102634486-e8591d00-4177-11eb-9eb6-d1a14e29c504.PNG)

**Comment by darold** [comment]
For the bkp_emp table I would like to have the full output because it complains about a primary key: bkp_emp_pkey so the description of the table might show that a PK exists.

About  column "job" of relation "emp" do you have an other table "emp" in an other schema?

**Comment by naveenjul29** [comment]
yes emp table is there in other schemas.  that's why I gave schemaname.tablename like otv2.emp table. seriously i don't have primary key in bkp_emp table.

**Comment by darold** [comment]
in this case you have an another table with the same name:
```
DBD::Pg::db pg_putcopyend failed: ERROR: duplicate key value violates unique constraint "bkp_emp_pkey"
DETAIL: Key (empno)=(7839) already exists.
CONTEXT: COPY bkp_emp ...
```
this message doesn't allow any ambiguity, there is a table named bkp_emp that have a primary key and this is the one you are inserting data.

In psql: `\d *.bkp_emp` might list all the tables with this name.

Does the emp table is the other schemas have the job column? Ora2pg doesn't prefix the table name with schema name during direct data import if you have not set PG_SCHEMA in ora2pg.conf

**Comment by naveenjul29** [comment]
I will look into it once again and come back to you in case of any help needed. Thank you for your help !!
