### ISSUE TITLE
Issues with Table Partitions

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#1059]
Happy New Year Darold !!

below is my oracle script and when I ran the ora2pg command with -t TABLE and -i inputfile, partitions are not created in the output file.

![tablescode](https://user-images.githubusercontent.com/67134199/103439738-81526280-4c65-11eb-9afb-31a17c47e4dd.PNG)

**Comment by darold** [comment]
Partitions are exported using `-t PARTITION`, export type TABLE will only export the partitioned table definition.
