### ISSUE TITLE
syntaxe en entrée invalide pour le type numeric:  8,76  when PARALLEL_TABLES > 1

### ISSUE THREAD

**Issue by thleblond** [darold/ora2pg#106]
When setting PARELLEL_TABLES to a value higher than 1, le NLS_NUMERIC_CHARACTERS is not set properly, and numeric values contain comma instead of dot , when using NLS_LANG = FRENCH_FRANCE.WE8ISO8859P1

It appears that when cloning  dbh  in   _extract_data function, the session parameters are "lost".

To fix that I had to add this call : 
$self->_numeric_format($dbh);
after cloning dbh

And adapt the _numeric_format function : 

sub _numeric_format
{
	my ($self,$dbh) = @_;
	$dbh = $self->{dbh}  if (! $dbh) ;

	my $sth = $dbh->do("ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,'") or $self->logit("FATAL: " . $dbh->errstr . "\n", 0, 1);
}

Maybe it should be necessary to also call  _datetime_format ;  But not an issue for me today.

I am using ora2pg 14.0 and oracle 10g database

**Comment by darold** [comment]
Ok, good catch again. Last commit 907aae9 should fix the issue.

Best regards,
