### ISSUE TITLE
ora2pg ignores EXCLUDE config parameter when doing a TEST comparison between Oracle and PostgreSQL

### ISSUE THREAD

**Issue by yonisade** [darold/ora2pg#1061]
When running ora2pg -t TEST , it doesn't apply the EXCLUDE table filter from the config file on the Oracle source, hence generating false object differences between the source and target environments, instead of ignoring those tables.

**Comment by darold** [comment]
Actually it does, I just had the case, but you need to specify the type of object. For example:
```
ora2pg -t TEST --count_rows -c config/ora2pg.conf -e 'TABLE[employees]'
```
The reason is that the TEST action looks at different object types so the filter must be set.

**Comment by yonisade** [comment]
But can't you just use the values of the EXCLUDE list in the config file to apply on the type mentioned in the config file (TABLE)? To be consistent with the export behavior.

**Comment by darold** [comment]
I can probably apply by default the filter to the table object yes.

**Comment by yonisade** [comment]
Would be awesome, thanks.

**Comment by darold** [comment]
Done in commit 0a2ce9d.
