### ISSUE TITLE
Ora2pg does not correctly convert oracle triggers with when clause To PostegresSQL

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1062]
Good afternoon Mr Darold,

I hope you are having a good start to the year,

I hereby come into contact with the sense of whether you can help me with the problem related to the non-correct conversion of Triggers that contain the WHEN clause from Oracle to PostegreSql?

I use version 21 of ora2pg and installed the ‘master’ code but it wasn’t successful.

 Once again I confirm that my new configuration file does not have PG_SUPPORTS * and changed the version of PG_VERSION to 12.4. 

An example of the specific problem follows:

Original DDL:
________________________________________
CREATE OR REPLACE TRIGGER trg_seq_cfg_modelo_res_steps
BEFORE INSERT ON cfg_modelo_resolucao_steps
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
SELECT seq_cfg_modelo_resolucao_steps.NEXTVAL INTO :new.id FROM dual;
END;
________________________________________
Result:
________________________________________
-- Generated by Ora2Pg, the Oracle database Schema converter, version 21.0
-- Copyright 2000-2020 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.112.83.15;sid=mgsigo;port=1521
SET client_encoding TO 'UTF8';
DROP TRIGGER IF EXISTS trg_seq_cfg_modelo_res_steps ON cfg_modelo_resolucao_steps CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_trg_seq_cfg_modelo_res_steps() RETURNS trigger AS $BODY$
BEGIN
SELECT nextval('seq_cfg_modelo_resolucao_steps') INTO STRICT NEW.id;
RETURN NEW;
END
$BODY$
LANGUAGE 'plpgsql';
CREATE TRIGGER trg_seq_cfg_modelo_res_steps
WHEN ((NEW.ID IS NULL))
EXECUTE PROCEDURE trigger_fct_trg_seq_cfg_modelo_res_steps();

Thank you in advance for any help given.

 As best regards,

 Rui Pereira.

**Comment by darold** [comment]
This is duplicate from #1058 and related to #1055.
 
Sorry for the delay I was thinking that this issue was fixed. Please use latest development code, commit f2d3d68 solves this issue. Also you might precise that this was the translation from a file that was failing because my tests with export from an Oracle database outputs correct result. 

Here is the trigger translation with the new code
```
[...]
CREATE TRIGGER "trg_seq_cfg_modelo_res_steps"
BEFORE INSERT ON cfg_modelo_resolucao_steps FOR EACH ROW
        WHEN ((NEW.ID IS NULL))
        EXECUTE PROCEDURE trigger_fct_trg_seq_cfg_modelo_res_steps();
```
