### ISSUE TITLE
export oracle  ST_GEOMETRY type column with ora-03135 error

### ISSUE THREAD

**Issue by changmao01** [darold/ora2pg#1064]
I used ora2pg(version: 21.0) to export oracle(version: 11.2.0) table with ST_GEOMETRY type column to text file.
After two hours elapsed, it failed with bellow error:
[root@test tmp]# ora2pg -c /etc/ora2pg/ora2pg.conf -a 'TABLE[TEST]'
[========================>] 1/1 tables (100.0%) end of scanning.
[>                        ] 0/1 tables (0.0%) end of scanning.
[========================>] 1/1 tables (100.0%) end of table export.

FATAL: 3135 ... ORA-03135: connection lost contact (DBD ERROR: OCISessionBegin)
Aborting export...
Killed

By the way, the target table has only 4 rows. 
ora2pg can export some common tables without ST_GEOMETRY type column.
I checked oracle database that both SDO_UTIL.TO_WKTGEOMETRY() and SDO_UTIL.TO_WKBGEOMETRY() is valid.

**Comment by changmao01** [comment]
I used below command to get debug.log.
ora2pg -d -c /etc/ora2pg/ora2pg.conf -a 'TABLE[TEST]' >./debug.log 2>&1
Currently it's running. However, I extracted some debug logs as attached file:
[ora2pg_debug.log](https://github.com/darold/ora2pg/files/5828081/ora2pg_debug.log)

**Comment by darold** [comment]
The problem is probably related to SDO_UTIL.TO_WKBGEOMETRY() call which is know to be broken with complex geometries. You should set GEOMETRY_EXTRACT_TYPE to INTERNAL in ora2pg.conf, see comment above this configuration directive. INTERNAL is normal the default, why have you changed it to WKB? Does the problem is the same with INTERNAL or the exported geometries are broken?

**Comment by changmao01** [comment]
Hi darold,

Thanks for your quick reply.
Just now, I changed backup GEOMETRY_EXTRACT_TYPE to INTERNAL in ora2pg.conf. Below attached is latested logs.
[ora2pg_debug.log](https://github.com/darold/ora2pg/files/5828381/ora2pg_debug.log)

**Comment by darold** [comment]
I'm surprised by the amount of Oracle connection attempt traced in the log. I think there is redundant calls to get column types, I will check that.

**Comment by changmao01** [comment]
Hi darold, 

Just now I used ora2pg(v20.0) to do the same test with below errors:
[root@test perl5]# ora2pg -c /etc/ora2pg/ora2pg.conf -a test
[========================>] 1/1 tables (100.0%) end of scanning.
[>                        ] 0/1 tables (0.0%) end of scanning.
[========================>] 1/1 tables (100.0%) end of table export.
DBD::Oracle::db prepare failed: ORA-01756: quoted string not properly terminated (DBD ERROR: OCIStmtPrepare) [for Statement "SELECT DISTINCT OBJECT_NAME,OWNER,OBJECT_ID FROM ALL_OBJECTS WHERE OBJECT_TYPE='TYPE' AND STATUS='VALID' AND OBJECT_NAME=''||spref_r.srid||' AND GENERATED='N'AND OWNER='SDE' "] at /root/perl5/lib/perl5/Ora2Pg.pm line 11290.
FATAL: ORA-01756: quoted string not properly terminated (DBD ERROR: OCIStmtPrepare)
Aborting export...

I copied the lines ( about the function sub _get_types with the variable $str) from ora2pg (v21.0). However, it reported the same error after re-run it.

By the way, any progress with ora2pg(v21.0)?

**Comment by darold** [comment]
Can you give a try to latest development code and send me the debug output. Commit 960699a tries to limit special behavior for geometry columns to SDO_GEOMETRY. Here you have ST_GEOMETRY which can not be processed the same way.

**Comment by changmao01** [comment]
Hi darold,

Just now I only updated the file Ora2Pg.pm from your commit 960699a.
Download URL is as below:
https://raw.githubusercontent.com/darold/ora2pg/960699a9fdcd7abff813686ba5a002b233235227/lib/Ora2Pg.pm
[root@test ~]# md5sum /root/perl5/lib/perl5/Ora2Pg.pm
e01fcc2328016fa24acc08ffa101e4b3  /root/perl5/lib/perl5/Ora2Pg.pm

However, I run the command "ora2pg -c /etc/ora2pg/ora2pg.conf -a test", and got the same errors as before:
[root@test ~]# grep -c ST_GEOMETRY debug.log
380
[root@test ~]# grep -c ST_GEOMETRY debug.log
886

Was there some wrong steps?

**Comment by darold** [comment]
Ok, there was some regexp in lowercase that passed outside my scope, commit 20b07d5 might solve this. The objective of this patches is to prevent processing the ST_* data like SDO_GEOMETRY and see what is exported. Actually ST_* data types are not supported yet but this should not be a problem if we can obtain a WKT representation.

New commit 124e316 adds a first attempt to support ST_* ArcGis geometry data type but I'm a blind man on this work because I don't have such object in a database. It may takes several tries before having something working.

Once you have updated Ora2Pg.pm with latest development code change GEOMETRY_EXTRACT_TYPE to WKB as INTERNAL is not supported with ST_* data type for the moment. You can also try with WKT but un this case use export type INSERT instead of COPY. But for the moment post the same output file as above with this new run to see if we use the correct function SDE.ST_ASBINARY() or SDE.ST_ASTEXT() in the query to export the data.

**Comment by changmao01** [comment]
Hi Darold,

I tested the commit 20b07d5.
Download URL is as below:
https://raw.githubusercontent.com/darold/ora2pg/20b07d5a0b96f81d8511b624d78fa70855696731/lib/Ora2Pg.pm
[root@test soft]# md5sum /root/perl5/lib/perl5/Ora2Pg.pm
0964b7002b73bf9749917cfed863f81a  /root/perl5/lib/perl5/Ora2Pg.pm

However, I run the command "ora2pg -c /etc/ora2pg/ora2pg.conf -a test", and got the same errors as before:
[root@test soft]# grep -c 'Found Type: ST_GEOMETRY' /root/debug.log
3979

so I think the new commit 20b07d5 did NOT fix this problem.

**Comment by darold** [comment]
You don't have the right version, you must download https://raw.githubusercontent.com/darold/ora2pg/master/lib/Ora2Pg.pm to obtain the last code.

**Comment by changmao01** [comment]
Hi  darold,
I tried the new version as you mentioned above URL.
There's same error as before.
[root@test soft]# md5sum /root/perl5/lib/perl5/Ora2Pg.pm
6134f1c433d25c54d2859b1cf2faecd7  /root/perl5/lib/perl5/Ora2Pg.pm
[root@test soft]# md5sum Ora2Pg.pm.txt
6134f1c433d25c54d2859b1cf2faecd7  Ora2Pg.pm.txt

[root@test ~]#  grep -c 'Found Type: ST_GEOMETRY' /root/debug.log
1457
[root@test ~]# head -2000 /root/debug.log
[debug_2k.log](https://github.com/darold/ora2pg/files/5870375/debug_2k.log)

**Comment by darold** [comment]
Thanks, I have pushed some improvement in looking for user defined data type and overall I have removed schema SDE from the export to avoid looking at ArcGis object and especially their geometry data type. Please give an other try to latest code bydownloading https://raw.githubusercontent.com/darold/ora2pg/master/lib/Ora2Pg.pm to override your installed file and report the new debug output.

**Comment by changmao01** [comment]
Hi Darold,

I tested latested version of Ora2Pg.pm as you mentioned above.
Below attached is debug.log
[ora2pg_debug.log](https://github.com/darold/ora2pg/files/5883860/ora2pg_debug.log)

**Comment by darold** [comment]
Hi,

In one of my previous notes I mention this "change GEOMETRY_EXTRACT_TYPE to WKB as INTERNAL is not supported with ST_* data type for the moment. You can also try with WKT but un this case use export type INSERT instead of COPY". Your geometry export use the INTERNAL method which must be change. If you are using INSERT export set GEOMETRY_EXTRACT_TYPE to WKT and if you use COPY set it to WKB. Please post an other report with this configuration..

However I will fix this problem to force internally the geometry export type with ST_* geometry.

**Comment by changmao01** [comment]
Hi Darold,

I tried GEOMETRY_EXTRACT_TYPE to WKT with INSERT type. It reported the same error as before.
Below is abstact of errors:
[2021-01-29 07:59:48] Isolation level: SET TRANSACTION READ ONLY
[2021-01-29 07:59:48] Retrieving partitions information...
[2021-01-29 07:59:53] Looking how to retrieve data from TEST...
[2021-01-29 07:59:53] DEGUG: Query sent to Oracle: SELECT "OBJECTID","ID",CASE WHEN "SHAPE" IS NOT NULL THEN SDE.ST_ASTEXT("SHAPE") ELSE NULL END,"AA","BB" FROM "SDE"."TEST" a
[2021-01-29 07:59:53] Fetching all data from TEST tuples...
[2021-01-29 07:59:53] DEBUG: number of rows 6 extracted from table TEST
[2021-01-29 07:59:53] DEBUG: Formatting bulk of 10000 data (real: 6 rows) for PostgreSQL.
Can't use string ("POLYGON  (( -15456.23880000 8814"...) as an ARRAY ref while "strict refs" in use at /root/perl5/lib/perl5/Ora2Pg/GEOM.pm line 163.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(HOST=47.104.237.190)(PROTOCOL=tcp)(PORT=1521))(CONNECT_DATA=(SID=orcl))) at/root/perl5/lib/perl5/Ora2Pg/GEOM.pm line 163.

Please check attached file for details.
[debug.log](https://github.com/darold/ora2pg/files/5890753/debug.log)

**Comment by darold** [comment]
Ok, I have fixed the unwanted call to parse_sdo_geometry() in last commit e90bc86, please proceed to an other test.

**Comment by changmao01** [comment]
Hi darold,

with the commit e90bc86, I can export sde.st_geometry type data and generate INSERT script as below:
more /var/tmp/INSERT_output.sql
SET search_path = sde,public;
BEGIN;
SET search_path = sde,public;

INSERT INTO test (objectid,id,shape,aa,bb) OVERRIDING SYSTEM VALUE  VALUES (1,1,ST_GeomFromText('POLYGON  (( -15456.23880000 88144.65490000, -90801.93540000 88220.85080000, -92120.20980000
-74269.27140000, 78676.08180000 -74384.27710000, 77223.51640000 88050.92920000, 51217.75610000 88077.22840000, -15456.23880000 88144.65490000))', ),4,6);

.....

That's big good news.
However, I can not load the INSERT script into PG with below command:
psql -U xxx -d sdetest -h 47.104.237.x -p 5432 -f /var/tmp/INSERT_output.sql
It failed with below errors:
SET
BEGIN
SET
psql:/var/tmp/INSERT_output.sql:6: ERROR:  syntax error at or near "OVERRIDING"
LINE 1: INSERT INTO test (objectid,id,shape,aa,bb) OVERRIDING SYSTEM...
...

Is there some errors with my config file(/etc/ora2pg/ora2pg.conf)?
By the way, 
my psql version is 9.2, and server version is 9.4.

**Comment by darold** [comment]
Have you set PG_VERSION in ora2pg.conf to 9.4? Looks like Ora2Pg detect an identity column in this table but I have also fixed a possible bug for this OVERRIDE SYSTEM VALUE clause in commit 823dced.

There is an other issue in the export, the `ST_GeomFromText('POLYGON (..., ...)` doesn't include the SRID as second parameter, commit 305c4bf tries to fix it.

**Comment by changmao01** [comment]
Darold,

I set the PG_VERSION    in ora2pg.conf to 9. Just now, I tested commit 823dced. It fixed the bug for  OVERRIDE SYSTEM VALUE clause.
However, there's still error with insert as below:

sdetest=# INSERT INTO sde.test (objectid,id,shape,aa,bb)  VALUES (1,1,ST_GeomFromText('POLYGON  (( -15456.23880000 88144.65490000, -90801.93540000 88220.85080000, -92120.20980000 -74269.27140000, 78676.08180000 -74384.27710000, 77223.51640000 88050.92920000, 51217.75610000 88077.22840000, -15456.23880000 88144.65490000))', ),4,6);
ERROR:  syntax error at or near ")"
LINE 1: ...0 88077.22840000, -15456.23880000 88144.65490000))', ),4,6);

sdetest=# INSERT INTO sde.test (objectid,id,shape,aa,bb)  VALUES (1,1,ST_GeomFromText('POLYGON  (( -15456.23880000 88144.65490000, -90801.93540000 88220.85080000, -92120.20980000 -74269.27140000, 78676.08180000 -74384.27710000, 77223.51640000 88050.92920000, 51217.75610000 88077.22840000, -15456.23880000 88144.65490000))' ),4,6);
ERROR:  function st_geomfromtext(unknown) does not exist
LINE 1: ...O sde.test (objectid,id,shape,aa,bb)  VALUES (1,1,ST_GeomFro...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

I tried with new function st_geometry to insert values with below errors.                                                                ^
sdetest=# INSERT INTO sde.test (objectid,id,shape,aa,bb)  VALUES (1,1,st_geometry('POLYGON  (( -15456.23880000 88144.65490000, -90801.93540000 88220.85080000, -92120.20980000 -74269.27140000, 78676.08180000 -74384.27710000, 77223.51640000 88050.92920000, 51217.75610000 88077.22840000, -15456.23880000 88144.65490000))' ),4,6);
ERROR:  ESRI: error generating shape [-112]:
LINE 1: ...objectid,id,shape,aa,bb)  VALUES (1,1,st_geometry('POLYGON  ...

**Comment by changmao01** [comment]
Hi Darold,

I can use below SQL to insert PG correctly.
INSERT INTO sde.test (objectid,id,shape,aa,bb)  VALUES (1,1,ST_geometry('POLYGON  (( -15456.23880000 88144.65490000, -90801.93540000 88220.85080000, -92120.20980000 -74269.27140000, 78676.08180000 -74384.27710000, 77223.51640000 88050.92920000, 51217.75610000 88077.22840000, -15456.23880000 88144.65490000))',21481 ),4,6);

so above failed SQL, missed somethings as below:
1. use the function st_geometry  to replace ST_GeomFromText function
2. missed the coordinate information from GIS data.  About the coordinate data from Oracle sde.st_geometry, I can get it with below function.
select id,  sde.st_astext(shape) from sde.test;

**Comment by darold** [comment]
Well PostGis accept the form:
```
geometry ST_GeomFromText(text WKT);

geometry ST_GeomFromText(text WKT, integer srid);
```
so the second query should not complain but I'm not a specialist of PostGis perhaps it need a cast. Or perhaps you are also using ArcGis column in PG, in this case I think only form `ST_GeomFromText(text WKT, integer srid)` is allowed. I am right?

**Comment by darold** [comment]
Ok thanks for the last information I will add the SRID and use function st_geometry instead of ST_GeomFromText. I will do that later today or this weekend.

**Comment by darold** [comment]
Hi,

Sorry for the delay. I have added autodetection of geometry type, srid and dimension for ArcGis geometry in last two commit and replaced ST_GeomFromText by ST_Geometry. As I don't have ArcGis it is just a draft so let we know what is wrong with it.

Only lib/Ora2Pg.pm has changed.

**Comment by darold** [comment]
Forgot to say that spatial index definition on ArcGis column are still missing, I will work on it after.

**Comment by darold** [comment]
Any update? Have yo been able to test the last changes?

**Comment by darold** [comment]
Anyway, next issue related to arcgis object export will fix the next remaining problems. Thanks.
