### ISSUE TITLE
subquery

### ISSUE THREAD

**Issue by xinjirufen** [darold/ora2pg#1065]
Hi,darold.
 Dose  'WHERE DIRECTIVE' support subquery ? 
for example：
```
where test_fk[id in (select id from test_fk where name='Jordan')]
```
I've tried, but failed,error info:
```
DBD::Oracle::db prepare failed: ORA-00942: table or view does not exist (DBD ERROR: error possibly near <*> indicator at char 95 in 'SELECT "ID","SYN_ORG_REG_INFO_ID","NAME" FROM "FFDEV"."TEST_FK" a WHERE (id in (select id from <*>test_fk where name ='Jordan'))') [for Statement "SELECT "ID","SYN_ORG_REG_INFO_ID","NAME" FROM "FFDEV"."TEST_FK" a WHERE (id in (select id from test_fk where name ='Jordan'))"] at /usr/local/share/perl5/Ora2Pg.pm line 14043.
WARNING: table TEST_FK is not yet physically created and has no data.
```

**Comment by darold** [comment]
Why not simply use: `WHERE    TEST_FK[name = 'Jordan']` ? Or perhaps this is not the same table. Otherwise have you tried by prefixing with schema?:
```
 WHERE   TEST_FK[id in (select id from ffdev.test_fk where name='Jordan')]
```
Actually if you use the right subquery it should works.

**Comment by xinjirufen** [comment]
> Why not simply use: `WHERE TEST_FK[name = 'Jordan']` ? Or perhaps this is not the same table. Otherwise have you tried by prefixing with schema?:
> 
> ```
>  WHERE   TEST_FK[id in (select id from ffdev.test_fk where name='Jordan')]
> ```
> 
> Actually if you use the right subquery it should works.

Thanks, it is right by prefixing with schema.
