### ISSUE TITLE
export blob from oracle to postgres unsuccessful

### ISSUE THREAD

**Issue by SamsonHui** [darold/ora2pg#1066]
HELLO

Two methods "copy" and "insert" to transfer the blob data,but got different results in postgres.
For example,
COPY
![image](https://user-images.githubusercontent.com/32662062/106115863-335d4b80-618c-11eb-9c77-0e05f27368d5.png)
INSERT
![image](https://user-images.githubusercontent.com/32662062/106115909-407a3a80-618c-11eb-8720-e1ae9dfa7b5f.png)
 What`s the "decode(E"
THX

Best Regards.

**Comment by darold** [comment]
This is normal, the INSERT method use the hexadecimal representation for a bytea and COPY use the escape method. The decode() function is used to transform the hex string into a bytea during the insert. Take care to use latest development code as there was a recent fix about BLOB export.
```
wget https://github.com/darold/ora2pg/archive/master.zip
unzip master.zip
cd ora2pg-master/
perl Makefile.PL
make
sudo make install
```

**Comment by SamsonHui** [comment]
My Friend,
I have updated the latest version,but the same mistake as before.
![image](https://user-images.githubusercontent.com/32662062/106225329-e034d880-621f-11eb-8c75-5d0e0401f3df.png)

PS:
1. XLS files in THE Oracle BLOB column .
2.Files by <COPY>  r available but not available by <INSERT>.
3.By <COPY> cause another mistake : "\r"  can not be LF

**Comment by darold** [comment]
What is the error reported by PG when you try to insert the data and do you have the same error when using COPY export?

**Comment by SamsonHui** [comment]
![image](https://user-images.githubusercontent.com/32662062/106250305-6c5df480-624e-11eb-8b86-5b18be67e988.png)
Ora2pg errors using COPY in the image above.
No ora2pg errors using INSERT but the content is not what we expect.

**Comment by darold** [comment]
Current call to pg_putcopyend is at line 15341, I think you are not using the last Ora2Pg code. What you can do is download latest master and override the lib with `cp lib/Ora2Pg.pm /usr/local/share/perl5/Ora2Pg.pm`

**Comment by darold** [comment]
I'm closing this issue because it looks that the Ora2Pg version is not up to date.
