### ISSUE TITLE
Export of subpartions failed

### ISSUE THREAD

**Issue by schleb1309** [darold/ora2pg#1067]
Dear all,

I try to export a oracle schema but it fails when it comes to the point where a subpartion should be exported.
I receive the following error message:

`FATAL: _extract_data() ORA-14251: Specified subpartition does not exist (DBD ERROR: error possibly near <*> indicator at char 487 in 'SELECT "SOURCE","DATA_RIF","BPS_SHIFT",<more_columns>" FROM "."TABLENAME" SUBPARTITION(<*>"19000101_**rai_i_0000**") a')`

If I run the command manually see that the partition exists but the partition name is in capital letters:

SELECT ..... FROM ..... SUBPARTITION("19000101_**RAI_I_0000**") a

Is there any configuration or workaround how I can change this behavior?

Thanks and Regards
Benjamin

**Comment by schleb1309** [comment]
Think the setting PRESERVE_CASE	1 will solve the issue.

**Comment by darold** [comment]
Hum yes, but PRESERVE_CASE should only be effective for PG side. I guess that if you have enabled it this is because you want to keep the case on PG side otherwise yes it is better to disable it. Let me know if this need to be fixed and reopen the issue.

**Comment by schleb1309** [comment]
Thanks for your feedback. With the PRESERVE_CASE setting to 1 the export continues. So seems to be also effective fon the oracle side.

**Comment by schleb1309** [comment]
So with PRESERVE_CASE 1 the export works but then as you already mentioned you have case sensitivity on PG side. Think it would be good to solve this.

**Comment by darold** [comment]
Commit 20f12d5 suppress the Oracle side effect of PRESERVE_CASE for parttition export.
