### ISSUE TITLE
ora2pg wrong char encoding 

### ISSUE THREAD

**Issue by mmuehlbeyer** [darold/ora2pg#1069]
Hi,

we're currently testing ora2pg for migrating data from Oracle 19c to Postgres.

The export works fine but for one table the exported data has a wrong enconding:

e.g. instead of `'ò'` we get an `'<F2>'` in the export file.

Any advice how to overcome this?

Regards,
Michael

**Comment by darold** [comment]
What does `-t SHOW_ENCODING` reports?

**Comment by mmuehlbeyer** [comment]
![error](https://user-images.githubusercontent.com/12482802/107017729-cd7e4e80-679f-11eb-8c07-af7041acaaf7.png)

**Comment by darold** [comment]
What does the `Iocale` command reports on the Ora2Pg host?

If you are exporting to a file, try to export directly into PG to see if the problem persist.

**Comment by mmuehlbeyer** [comment]
![locale](https://user-images.githubusercontent.com/12482802/107027396-61561780-67ac-11eb-9cc8-6de780a971fc.png)

thanks will try direct import also
