### ISSUE TITLE
EXCLUDE ignored with type COPY or INSERT

### ISSUE THREAD

**Issue by thleblond** [darold/ora2pg#107]
In case of type COPY or INSERT only, the EXCLUDE parameter seems ignored.

Probably because of the initialisation of the $self->{excluded}  in  _init function (around line 733)

foreach my $i (@{$self->{excluded}{ALL}}) {
                my $typ = $self->{type} || 'TABLE';
                $typ = 'TABLE' if ($self->{type} =~ /(SHOW_TABLE|SHOW_COLUMN|FDW|KETTLE|COPY|INSERT)/);
                push(@{$self->{excluded}{$typ}}, $i);
print STDERR "init exclude $typ $i when $self->{type}";
        }

I suggest to add |COPY|INSERT  in the regexp.

There is probably the same issue  $self->{limited} (just above) , but not sure how it works.

**Comment by darold** [comment]
Yes that's right. There was lot of rewriting on this part I don't know how I miss that in my test. Commit d215b1d applied your patch.

Regards,
