### ISSUE TITLE
Error: Package: ora2pg-21.0-1.rhel7.noarch (pgdg-common)

### ISSUE THREAD

**Issue by bagafoot** [darold/ora2pg#1071]
I try to install ora2pg on Centos7, but getting dependencies error.

```
Error: Package: ora2pg-21.0-1.rhel7.noarch (pgdg-common)
           Requires: perl(DBD::Oracle)
```

İt says there is no perl package bu its installed

```
Reading '/root/.cpan/Metadata'
  Database was generated on Mon, 08 Feb 2021 03:17:03 GMT
DBD::Oracle is up to date (1.80).
```
installed oracle packages
rpm -qa|grep oracle

oracle-instantclient19.5-devel-19.5.0.0.0-1.x86_64
oracle-instantclient19.5-jdbc-19.5.0.0.0-1.x86_64
oracle-instantclient19.5-sqlplus-19.5.0.0.0-1.x86_64
oracle-instantclient19.5-basic-19.5.0.0.0-1.x86_64

what Im doing wrong?

**Comment by darold** [comment]
I think this is because DBD::Oracle have not been installed from a RPM package, you should install Ora2Pg from sources:
```
wget https://github.com/darold/ora2pg/archive/master.zip
unzip master.zip
cd ora2pg-master/
perl Makefile.PL
make
sudo make install
```
See README file for more information on installation instruction.

**Comment by bagafoot** [comment]
Thaks, its work for me
