### ISSUE TITLE
Getting "FATAL: _column_attributes() ORA-03135: connection lost contact" when using parallel copy

### ISSUE THREAD

**Issue by yonisade** [darold/ora2pg#1072]
ora2pg v21.0 over docker on Azure VM (RHEL 7)
Oracle client: v12.1.0.2.0
psql: v9.5.10

Source DB: On-premise Oracle 11.2.0.4
Target DB: Azure PostrgreSQL v11

ora2pg.conf:
JOBS=2
PARALLEL_TABLES=2

When running:
`time ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg.conf &> ora2pg_copy.log`

Getting this error in the middle of COPYing a 15 million rows table:

_FATAL: _column_attributes() ORA-03135: connection lost contact%) - (3428 sec., avg: 8344 recs/sec), BIG_TABLE in progress.
Process ID: 25083
Session ID: 807 Serial number: 20871 (DBD ERROR: OCIStmtExecute/Describe)
Aborting export..._

**Comment by darold** [comment]
A quick google search give me some interesting links like http://www.dba-oracle.com/t_ora_03135_connection_lost_contact.htm

When there is an ORA-XXXXX number do not hesitate to look at the reason by yourself, the problem is not related to Ora2Pg in itself but to your Oracle parameters.

**Comment by longwa** [comment]
I'm getting the same issue with parallel copy only. My Oracle is scaled to handle 100's of connections and I see no errors on the Oracle side which is interesting.
