### ISSUE TITLE
Precision and exactness missunderstanding.

### ISSUE THREAD

**Issue by SebastienCaunes** [darold/ora2pg#1073]
In several places (doc, conf file) we see confusion between precision and exactness.

Precision is the size of the gap between two consecutive values.
Exactness define if the value stored is exactly the one displayed.

A float is much more precise than a Numeric(38,2) but it is not exact.

-----
French version for the author :
Il y a à plusieurs endroit une confusion entre exactitude et précision. 
La précision est l'écart entre deux valeurs consécutives.
L'exactitude c'est quand la valeur stockée sur disque et en ram est exactement la valeur montrée à l'écran.

Un flottant est bien plus précis qu'un Numeric(38,2) mais il n'est pas exact.

Exemple dans la doc :
_S’il s’agit de données de type monétaire, comme des tarifs ou montants de facture, ou tout autre donnée pour laquelle une grande précision est demandée, il est impératif d’utiliser le type numérique pour éviter les effets de bord des arrondis._

On ne demande pas une grande précision sur le montant d'une facture, il est d'ailleurs toujours arrondi au centime près. Par contre on demande qu'il soit exact. On peut payer 123,45 € mais on peut pas payer 10,333333333333 €.

**Comment by darold** [comment]
Right I found one occurrence of this confusion, commit 5a800b1 fix it in all documentation related file. I will update the online documentation when next release will be published.
