### ISSUE TITLE
SCHEMA_ONLY, DATA_ONLY, CONSTRAINTS_ONLY confusion

### ISSUE THREAD

**Issue by SebastienCaunes** [darold/ora2pg#1074]
In import_all.sh there are those 3 lines :
```
SCHEMA_ONLY=0
DATA_ONLY=0
CONSTRAINTS_ONLY=0
```

What append if we set all values to 1 ? it could not export only data and only schema at the same time.

Theses should be renamed as :
```
IMPORT_SCHEMA=0
IMPORT_DATA=0
IMPORT_CONSTRAINTS=0
```

**Comment by darold** [comment]
I agree, these names have not changed when the script evolved and they don't reflect their real use. Commit 7cd06e5 fixes that.
