### ISSUE TITLE
Reordering columns completely mess up with columns

### ISSUE THREAD

**Issue by SebastienCaunes** [darold/ora2pg#1075]
The reordering column feature completely mess up with columns it should move the minimum and retain names order.

This Oracle code
```
CREATE TABLE "my_table" 
   (	"STATID" VARCHAR2(30 BYTE), 
	"TYPE" CHAR(1 BYTE), 
	"VERSION" NUMBER, 
	"FLAGS" NUMBER, 
	"C1" VARCHAR2(30 BYTE), 
	"C2" VARCHAR2(30 BYTE), 
	"C3" VARCHAR2(30 BYTE), 
	"C4" VARCHAR2(30 BYTE), 
	"C5" VARCHAR2(30 BYTE), 
	"N1" NUMBER, 
	"N2" NUMBER, 
	"N3" NUMBER, 
	"N4" NUMBER, 
	"N5" NUMBER, 
	"N6" NUMBER, 
	"N7" NUMBER, 
	"N8" NUMBER, 
	"N9" NUMBER, 
	"N10" NUMBER, 
	"N11" NUMBER, 
	"N12" NUMBER, 
	"D1" DATE, 
	"R1" RAW(32), 
	"R2" RAW(32), 
	"CH1" VARCHAR2(1000 BYTE), 
	"CL1" CLOB
   ) 
```
Gets translated to this :
```
CREATE TABLE my_table(
        n10 bigint,
        n9 bigint,
        flags bigint,
        n3 bigint,
        n2 bigint,
        n8 bigint,
        n5 bigint,
        n12 bigint,
        n1 bigint,
        n6 bigint,
        n7 bigint,
        d1 timestamp,
        n11 bigint,
        version bigint,
        n4 bigint,
        r1 bytea,
        c1 varchar(30),
        c2 varchar(30),
        statid varchar(30),
        c5 varchar(30),
        cl1 text,
        c4 varchar(30),
        ch1 varchar(1000),
        c3 varchar(30),
        r2 bytea,
        type char(1)
) ;
```

In french for the author :
La fonction reordering_column mélange tout, il faudrait qu'elle garde au maximum l'ordre initial. J'ai regardé un peu le code (qui est vraiment alambiqué. Je pense qu'il serait plus simple de créer une copie du tableau et le trier en dehors de la boucle for. J'aurais bien voulu aider mais le code me semble pas clair du tout.

**Comment by darold** [comment]
Cette fonction ordonne les colonnes en fonction de leur position dans la table originale sauf si REORDERING_COLUMNS est activé. Dans ce cas les colonnes sont ordonnées selon l'alignment de leur type (1, 2, 4 ou 8 octets). Mais je suis d'accord qu'une amélioration pourrait etre apportée en triant aussi par position pour les colonnes de même alignement ce qui permettrait d'avoir un export avec un ordre stable. L'autre amélioration que je vois serait d'ordonner les alignements à 8 octets en fonction de la longueur max du type, les bytea en dernier.

**Comment by SebastienCaunes** [comment]
J'ai fait une fonction qui fait ça sous excel. Il suffit de trouver quelle taille les champs occupent en mémoire et de trier avec les plus petits d'abord et les variables à la fin.

**Comment by darold** [comment]
C'est bien ce que fait le code du tri minus les améliorations qui pourraient être apportées :-)

**Comment by darold** [comment]
Fixed with commit 8873beb.
