### ISSUE TITLE
Source code in several files and tests

### ISSUE THREAD

**Issue by SebastienCaunes** [darold/ora2pg#1076]
I tried to edit code but there are two big problems. The code is in one huge file and there are no tests so we don't know if something is broken.

I think splitting the code in several small files will make it more easy for the community to help dev.

I leave this as an issue for the backlog.

**Comment by darold** [comment]
Yes, historically Ora2Pg starts as a single small script and was quickly developed for my needs and features asked by users on this basis. It is developed on my spare time and unfortunately refactoring the code is a very huge work and I don't have time for that. I have a regular job and a life too. Several major companies are using Ora2pg intensively to sale migration but until know no one offer to hire me to develop and improve this useful tool. This is a shame but I'm not surprised. In other terms, don't expect major code rewrite based on my spare time.

**Comment by SebastienCaunes** [comment]
Stop being so french, dare to ask donations and even money. Make a free version for first 1GB of data, then 1$ per GB. You'll get money to rewrite everything.
