### ISSUE TITLE
Handling of strange syntax for triggers

### ISSUE THREAD

**Issue by SebastienCaunes** [darold/ora2pg#1077]
When a trigger start with this strange syntax
```
create or replace TRIGGER myTrigger AFTER UPDATE OF valeur OR INSERT ON myTable
```

Source get exported as this 

CREATE TRIGGER myTrigger AFTER INSERT OR UPDATE OF **"valeur or insert"** ON myTable FOR EACH ROW

So it is then badly converted

**Comment by darold** [comment]
Can you please send to my private email the Oracle code of this trigger?

**Comment by SebastienCaunes** [comment]
You got the line with the problem
This works fine :
create or replace TRIGGER myTrigger AFTER **INSERT OR** UPDATE OF valeur ON myTable

This does not :
create or replace TRIGGER myTrigger AFTER UPDATE OF valeur **OR INSERT** ON myTable

**Comment by darold** [comment]
Yes, I ask that because having an example same me time.

**Comment by SebastienCaunes** [comment]
<french>prends n'importe quel trigger et rajoute le OR INSERT après la valeur et t'auras le bug. Si tu mets le INSERT OR avant le UPDATE, c'est plus lisible et ça passe</french>

**Comment by darold** [comment]
oui, merci je saurai faire :-D c'est juste que fournir un use case aurait permis une résolution plus rapide.

**Comment by darold** [comment]
Commit be0964a might solve this issue.
