### ISSUE TITLE
Updates types and their size

### ISSUE THREAD

**Issue by SebastienCaunes** [darold/ora2pg#1078]
I checked the types and their length in memory. I put 1000 for all variable lengths.
I split Aliases and deprecated in another section.

line 170
```
our %TYPALIGN = (
# Types and size, 1000 = variable
'boolean' => 1,
'smallint' => 2,
'smallserial' => 2,
'integer' => 4,
'real' => 4,
'serial' => 4,
'date' => 4,
'oid' => 4,
'macaddr' => 6,
'bigint' => 8,
'bigserial' => 8,
'double precision' => 8,
'macaddr8' => 8,
'money' => 8,
'time' => 8,
'timestamp' => 8,
'timestamp without time zone' => 8,
'timestamp with time zone' => 8,
'interval' => 16,
'point' => 16,
'tinterval' => 16,
'uuid' => 16,
'circle' => 24,
'box' => 32,
'line' => 32,
'lseg' => 32,
'bit' => 1000,
'bytea' => 1000,
'character varying' => 1000,
'cidr' => 1000,
'json' => 1000,
'jsonb' => 1000,
'numeric' => 1000,
'path' => 1000,
'polygon' => 1000,
'text' => 1000,
'xml' => 1000,
# aliases
'bool' => 1,
'timetz' => 12,
'char' => 1000,
'decimal' => 1000,
# deprecated
'int2' => 2,
'abstime' => 4,
'bpchar' => 4,
'int4' => 4,
'reltime' => 4,
'float4' => 4,
'timestamptz' => 8,
'float8' => 8,
'int8' => 8,
'name' => 63,
'inet' => 1000,
'varbit' => 1000,
'varchar' => 1000
)
```

**Comment by darold** [comment]
I'm very surprised by some old values that was used, however I have applied your definition minus cidr and inet values that have a 19 bytes length. I have also kept your logic about the weight of 1000 for the variable length data type even if I think this can be improved. Actually variable length columns could be placed with 8 bytes data types when data is toasted but the difficulty is to know when it is the case or not. Applied in commit 8873beb.

**Comment by SebastienCaunes** [comment]
We just care for length under 8 bytes and for tables with only fixed length fields.
If you put 1000 for anything above 8 bytes, it will give a good enough result.

**Comment by darold** [comment]
If you take a char(2) for example it takes only 3 bytes. I think we can improve a bit more this algorithm. For what I know it is not widely used, most of users prefer to keep the original structure of the table. But I agree that this is good enough for the moment.

**Comment by SebastienCaunes** [comment]
Yes but char can be aligned wherever you want so you can just stack them at the end in any order. Alignement is especially important for numbers because CPU cannot load them if they are not properly aligned.

**Comment by darold** [comment]
Right
