### ISSUE TITLE
Table copy migration fails at end

### ISSUE THREAD

**Issue by arun-022** [darold/ora2pg#1079]
Hi, First of all, thanks for the wonderful tool you have developed ! 

We are trying to migrate an oracle DB where-in every table more or less has a blob column. We were getting an ORA-01555 error for some of the big tables which we fixed by increasing the undo_retention period. This seemed to solve the problems however towards the end of the export we again got the ORA-01555 error but this time with a very long query trying to do something with sequences. Please find attached the query in the attachment. 

Can you please shed some light on why this is happening. We are only trying to move the tables with the copy instruction directly from oracle to postgres.

Many thanks !

[ORA-01555.txt](https://github.com/darold/ora2pg/files/5990102/ORA-01555.txt)

**Comment by darold** [comment]
What value for TRANSACTION in pra2pg.conf? If this is `serializable` try with `committed`.

**Comment by arun-022** [comment]
The TRANSACTION value was set to readonly, i am going to try now with the committed value.

To speed up the migration process, i also tried the command 
ora2pg -c bulktables.conf  -T /migration_data/tmp/job5 -b /migration_data -J 4 -j 4 -P 2 -L 50000

However i get these errors then

Error: cannot fork: Cannot allocate memory
Error: cannot fork: Cannot allocate memory

Also tried using just the -J 2 and -j 2, it still throws the cannot allocate memory error at some point during the process.

Thanks !

**Comment by darold** [comment]
I don't know how much memory you have on your host but this is not enough for the parameters given to ora2pg, first you should reduce DATA_LIMIT to 5000 for example. Also you must choose between -J and -P, in your case only -P will be used.

**Comment by darold** [comment]
I guess there is some BLOBs in these tables otherwise this should not take so long time. The answer is not obvious, I would say that it depends of the design of these tables. Most of the time this problem can be solved by importing only the "live" data at migration time. The "dead" data can be loaded at any time before or after the migration. For example let's say that your application use 99% of the time the data from the last month or the last last year, other data are use only for searching in "archived" data. In this case the real time spent for the migration is for the live data. Of course this implies that there is a datetime column that allow to filter from live and dead data. Is this is the case the WHERE configuration directive in ora2pg.conf is you friend.

**Comment by arun-022** [comment]
Yes, all these tables have blobs .. based on your performace tests .. with a machine of 4 CPU and 16GB memory what kind of parallelism can we achieve ? Also can you elaborate a bit on the -j -J parameters and would using those in combination with -P help to make the process faster .. Would increasing the infrastructure of the machine where ora2pg is running improve the migration time ?

**Comment by darold** [comment]
With such configuration I don't think you will be able to have better performances beyond `-P 2 -j 2` or `-J 2 -j 2`.

* The -J parameter is used to use several processes to export a single table, it is mainly used for huge tables with BLOB.
* The -P parameter is use to export several tables in parallel, generally used to export data from all tables except those containing BLOB.
* The -j parameter is used to write data in parallel to PostgreSQL or into a file. Usually a value of 2 or 3 is enough.
* You can not use -J and -P together, in this case this is -P that is taking precedence.
* The number of CPU used is the result of the multiplication of -P (or -J) with -j values

The data migration performances are directly dependent of the resources as the above parameters shown. About memory, the DATA_LIMIT value is per processes. So if it is set to 10000 it will export 10000 rows at a time on each processes specified by -P or -J and the amount of memory taken depends of the row size.

Before migrating I used to test what are the best values for those parameters for the tables that do not have BLOB and the one with BLOB.
