### ISSUE TITLE
Bug exporting LONG datatypes

### ISSUE THREAD

**Issue by DavidSanMar** [darold/ora2pg#108]
Hi, 

    I’ve found a bug in Ora2Pg v14.1, with original LONG datatype exporting in TYPE COPY (and
 TYPE INSERT), it doesn’t shows up with schema export (TYPE TABLE)

    The error it spits when it founds the table with Oracle LONG datatype (it should then 
be exported to text datatype in pgsql)

Out of memory!
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle <PLACEHOLDERFORMYORACLECONNECTION> at /usr/local/lib64/perl5/DBD/Oracle.pm line 348.

    Steps to reproduce:

    1.- Set an Oracle database with a table with a LONG field.
    2.- Configure an Ora2Pg v14.1 export with the TYPE COPY or TYPE INSERT to export that.
    3.- Ora2pg fails with the above error.

More information:

    Tested in:

    Ora2pg v14.1  PERL v5.10.1 (*) built for x86_64-linux-thread-multi  (CentOS 6 64bit)
    
  Oracle database:

   Oracle Database 10g Release 10.2.0.3.0 in CentOS 5 32bits

Any workaround?
   
PS: Ora2Pg v13.0 doesn’t show this behaviour ( it works flawlessly )

**Comment by darold** [comment]
Hi,

Thanks for the report, please download and use latest code from github and let me know if you still have the issue.

If you still going OOM, could you post here the ora2pg command line you are using, the quantity of RAM on the machine where Ora2Pg is run and the value of DATA_LIMIT used in 13.0 and 14.1 configuration file.

Regards,

**Comment by DavidSanMar** [comment]
Yes, it's the latest version.

The size of RAM seems irrelevant, since it OOMs with even a small small table, but I tried with 1GB and 2GB VM's ( it breaks at the same point ).

An example of table that breaks:

SQL> select count(*) from l0217_oferta;

  COUNT(*)
----------
       653

SQL> desc l0217_oferta
 Name                                      Null?    Type
 ----------------------------------------- -------- ----------------------------
 COD_OFERTA                                NOT NULL NUMBER(38)
 DESCRIPCION                                        LONG
 VERSION_BEAN                                       NUMBER(38)

I'm pretty sure if it has 1 row it breaks too.

DATA_LIMIT      10000  ( the default ) in the same configuration ( I use the same for both versions )

Command line is ora2pg -c configuration.conf, and directives are pretty much the default in the sample file ( except for PG_NUMERIC_TYPE 0 )

**Comment by darold** [comment]
Ok, can you post here the output of the ora2pg command using debug output?

    ora2pg -c configuration.conf -d -a l0217_oferta -t COPY

**Comment by DavidSanMar** [comment]
Using character set: NLS_LANG=AMERICAN_AMERICA.AL32UTF8, NLS_NCHAR=AL32UTF8.
        Using Perl output encoding :utf8.
        Using PostgreSQL client encoding UTF8.
Trying to connect to database: dbi:Oracle:host=<IPADDRESS>;sid=ORA1
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
        Found Package: EBROKER_ENTES
        Found Package: MD_META
        Found Package: MIGRATION
        Found Package: MIGRATION_REPORT
        Found Package: MIGRATION_TRANSFORMER
Looking at package MIGRATION...
Looking at package MIGRATION_TRANSFORMER...
Looking at package EBROKER_ENTES...
Looking at package MD_META...
Looking at package MIGRATION_REPORT...
Retrieving table information...
[1] Scanning table L0217_OFERTA (626 rows)...
Trying to connect to database: dbi:Oracle:host=<IPADDRESS>;sid=ORA1
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
Retrieving partitions information...


Looking how to retrieve data from L0217_OFERTA...
Out of memory!
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle <PLACEHOLDERFORMYORACONNECTION> at /usr/local/lib64/perl5/DBD/Oracle.pm line 348.

**Comment by darold** [comment]
Ok, I've removed package lookup when not needed this should save some memory. Could you download latest code and try again. First with the same command and if it failed with this one:

    ora2pg -c configuration.conf -d -a l0217_oferta -t COPY -L 50

Also do you know the real size of table l0217_oferta?

**Comment by DavidSanMar** [comment]
Original extract fails, but with -L 50 works but with a strange warning, here's the output:

        Using character set: NLS_LANG=AMERICAN_AMERICA.AL32UTF8, NLS_NCHAR=AL32UTF8.
        Using Perl output encoding :utf8.
        Using PostgreSQL client encoding UTF8.
Trying to connect to database: dbi:Oracle:host=(IPADDRESS);sid=ORA1
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
Retrieving table information...
[1] Scanning table L0217_OFERTA (626 rows)...
Trying to connect to database: dbi:Oracle:host=(IPADDRESS);sid=ORA1
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
Retrieving partitions information...


Looking how to retrieve data from L0217_OFERTA...
Fetching all data from L0217_OFERTA tuples...
DEBUG: Formatting bulk of 50 data for PostgreSQL.
DEBUG: Creating output for 50 tuples
Extracted records from table L0217_OFERTA: 50 (50.0 recs/sec)
DEBUG: Formatting bulk of 50 data for PostgreSQL.
DEBUG: Creating output for 50 tuples
Extracted records from table L0217_OFERTA: 50 (50.0 recs/sec)
DEBUG: Formatting bulk of 50 data for PostgreSQL.
DEBUG: Creating output for 50 tuples
Extracted records from table L0217_OFERTA: 50 (50.0 recs/sec)
DEBUG: Formatting bulk of 50 data for PostgreSQL.
DEBUG: Creating output for 50 tuples
Extracted records from table L0217_OFERTA: 50 (50.0 recs/sec)
DEBUG: Formatting bulk of 50 data for PostgreSQL.
DEBUG: Creating output for 50 tuples
Extracted records from table L0217_OFERTA: 50 (50.0 recs/sec)
DEBUG: Formatting bulk of 50 data for PostgreSQL.
DEBUG: Creating output for 50 tuples
Extracted records from table L0217_OFERTA: 50 (50.0 recs/sec)
DEBUG: Formatting bulk of 50 data for PostgreSQL.
DEBUG: Creating output for 50 tuples
Extracted records from table L0217_OFERTA: 50 (50.0 recs/sec)
DEBUG: Formatting bulk of 50 data for PostgreSQL.
DEBUG: Creating output for 50 tuples
Extracted records from table L0217_OFERTA: 50 (50.0 recs/sec)
DEBUG: Formatting bulk of 50 data for PostgreSQL.
DEBUG: Creating output for 50 tuples
Extracted records from table L0217_OFERTA: 50 (50.0 recs/sec)
DEBUG: Formatting bulk of 50 data for PostgreSQL.
DEBUG: Creating output for 50 tuples
Extracted records from table L0217_OFERTA: 50 (50.0 recs/sec)
DEBUG: Formatting bulk of 50 data for PostgreSQL.
DEBUG: Creating output for 50 tuples
Extracted records from table L0217_OFERTA: 50 (50.0 recs/sec)
DEBUG: Formatting bulk of 50 data for PostgreSQL.
DEBUG: Creating output for 50 tuples
Extracted records from table L0217_OFERTA: 50 (50.0 recs/sec)
DEBUG: Formatting bulk of 50 data for PostgreSQL.
DEBUG: Creating output for 50 tuples
Extracted records from table L0217_OFERTA: 50 (50.0 recs/sec)
DEBUG: Formatting bulk of 50 data for PostgreSQL.
DEBUG: Creating output for 50 tuples
Extracted records from table L0217_OFERTA: 3 (3.0 recs/sec)

[========================>] 626/626 rows (100.0%) on total data (avg: 625.9 recs/sec)
Restarting sequences
Extracted sequence information for sequence "SEQ_SIAPOL_LIMIT_COBER"
Extracted sequence information for sequence "ID_TARIF_INCID"
Extracted sequence information for sequence "SEQ_SIAPOL_ACCESORIO"
Extracted sequence information for sequence "SEQ_SIAPOL_COMISION"
Extracted sequence information for sequence "ID_PLAN_PRJ"
Extracted sequence information for sequence "SEQ_SIAPOL_DET"
Extracted sequence information for sequence "SEQ_SIAPOL_COBERTURA"
Extracted sequence information for sequence "SEQ_SIAPOL_FRANQ_COBER"
Extracted sequence information for sequence "SEQ_SIAPOL_MAQUINA"
Extracted sequence information for sequence "SEQ_SIAPOL_CAB_DET_PRO"
Extracted sequence information for sequence "ID_POL_GARANTIA"
Extracted sequence information for sequence "SEQ_SIAPOL_CONDUCTORES"
Extracted sequence information for sequence "ID_VALORES_PLANTILLA"
Extracted sequence information for sequence "SEQ_CC_RECIBOS"
Extracted sequence information for sequence "SEQ_SIAPOL_CAB"
Extracted sequence information for sequence "SEQ_SIAPOL_SUPLEMENTO"
Extracted sequence information for sequence "ID_POL_SUBGARANTIA"
Extracted sequence information for sequence "SEQ_HISTORICO"
Extracted sequence information for sequence "SEQ_SIAPOL_SUSPENSION"
Extracted sequence information for sequence "SEQ_SIAPOL_RIESGO"
Extracted sequence information for sequence "SEQ_SIAPOL_BENEFICIARI"
Extracted sequence information for sequence "SEQ_SIAPOL_REHABILITAC"
Extracted sequence information for sequence "SEQ_SIAPOL_ORI_CONTRA"
Extracted sequence information for sequence "NUM_SEGURAUTO"
Extracted sequence information for sequence "DBOBJECTID_SEQUENCE"
Extracted sequence information for sequence "SEQ_SIAPOL_FIGURAS"
Extracted sequence information for sequence "SEQ_SIAPOL_OTROS_DATOS"
Extracted sequence information for sequence "SEQ_SIAPOL_PROTECCION"
Extracted sequence information for sequence "SEQ_SIAPOL_VEHICULO"

WARNING: an error occurs during data export. Please check what's happen.

( and no more information )

**Comment by darold** [comment]
Ok, you don't have enough memory and the warning shows that the OOM Killer has killed one ora2pg process so your data export may be incomplet. I think you might increase memory, starting at 4GB at least.

I will check what's changed from 13.0 to 14.1 on this part.

Regards
