### ISSUE TITLE
Double negative configuration variables

### ISSUE THREAD

**Issue by RonJohn2** [darold/ora2pg#1080]
NO_LOB_LOCATOR  1
NO_BLOB_EXPORT   0

Please consider making config variables positive so that "Disable this if you don't want" can be avoided.  It can get very confusing.

**Comment by darold** [comment]
I agree that this is confusing, I would like to change this for a long time but I'm stuck on preserving backward compatibility. But as I've just broken this compatibility wth EMPTY_LOB_NULL this is probably time to do so with these directives.

**Comment by darold** [comment]
This is fixed in latest commits.

- NO_LOB_LOCATOR is renamed into USER_LOB_LOCATOR and default value set to 1
- NO_BLOB_EXPORT is renamed into ENABLE_BLOB_EXPORT and default value is set to 1.

Thanks.
