### ISSUE TITLE
DATA_EXPORT_ORDER sorting by name, not size

### ISSUE THREAD

**Issue by RonJohn2** [darold/ora2pg#1081]
Hello,

$ ora2pg --version
Ora2Pg v21.0

Even though this is set in the config file, the tables are extracted by name.
DATA_EXPORT_ORDER       size

Is this being overridden by the ALLOW directive?

**Comment by darold** [comment]
Commit 86c870d should solve the issue. Please confirm.

**Comment by RonJohn2** [comment]
Thanks for the quick fix.
I'll try and get it installed, but the sysadmins won't be too keen on grabbing something off of github (especially since it would require installing git and a bunch of dev packages on a critical production server).  Still, I'll see what I can do.
