### ISSUE TITLE
Table/view not found when containing geometry

### ISSUE THREAD

**Issue by edwardbrownga** [darold/ora2pg#1082]
Hi there,

I have a similar issue to [Issue #82](https://github.com/darold/ora2pg/issues/82)

When exporting a table with geometry, I get the **table or view does not exist** error and my schema is not pre-pended to the table name. Exporting tables without geometry works fine. I checked the change that fixed #82, it doesn't seem to be in 21.0's source code anymore but making the re-adding it myself didn't seem to fix the issue.

Error message below

ora2pg -c C:\W10Dev\ora2pg\ora2pg-13.0\ora2pg.conf -d -l C:\W10Dev\ora2pg\ora2pg-13.0\debug.log -o C:\W10Dev\ora2pg\ora2pg-13.0\output.sql

DBD::Oracle::db prepare failed: ORA-00942: table or view does not exist (DBD ERROR: error possibly near <*> indicator at char 38 in 'SELECT DISTINCT c.GEOM.SDO_GTYPE FROM <*>COORDINATES c') at C:/W10Dev/Strawberry/strawberry-perl-5.22.2.1-32bit/perl/site/lib/Ora2Pg.pm line 5065.
DBI::db=HASH(0x33eeb1c)->disconnect invalidates 1 active statement handle (either destroy statement handles or call finish on them before disconnecting) at C:/W10Dev/Strawberry/strawberry-perl-5.22.2.1-32bit/perl/site/lib/Ora2Pg.pm line 7122.

My config below

[ora2pg - credentials remove.txt](https://github.com/darold/ora2pg/files/6007307/ora2pg.-.credentials.remove.txt)

**Comment by darold** [comment]
Version 13 of ora2Pg is more than 6 years old, please update to latest development code.

**Comment by edwardbrownga** [comment]
Apologies, not sure where I got this version, I'll try updating.
