### ISSUE TITLE
Questions about migrating BLOBs and reducing memory consumption.

### ISSUE THREAD

**Issue by RonJohn2** [darold/ora2pg#1083]
(We need to extract many large tables with large blobs and XML columns, so this is critical for us.)

My questions only relate to "TYPE COPY", not to actually loading the data into Postgres 12.5.

1. If NO_LOB_LOCATOR is **enabled**, then "you must take care of the value of LONGREADLEN."  But what if it is **disabled**?  In that case, does it matter what size I make LONGREADLEN?  Is LONGREADLEN even relevant if NO_LOB_LOCATOR is disabled?
2. Are DATA_LIMIT and BLOB_LIMIT related?  Is BLOB_LIMIT used when blob columns are detected (but DATA_LIMIT is mentioned in the LOB_CHUNK_SIZE speed tests), or is it only the "commit count" inside the [table]_output.sql files?

**Comment by darold** [comment]
1. If NO_LOB_LOCATOR is disable Ora2Pg will use the LOB locator to retrieve the data by chunk and in this case LOB_CHUNK_SIZE can be adjusted following the size of the BLOB. By default it is set to 512000 but if you have very small BLOB you might want to reduce this chunk size. 
2. When exporting a table with BLOB by default Ora2Pg will divide the value of DATA_LIMIT by ten until DATA_LIMIT reach a value < 1000. Most of the time the value obtained is too high for a hist with few resources so it is possible to use BLOB_LIMIT. It will override the value of DATA_LIMIT for table with BLOB.

I hope this is more clear.

**Comment by RonJohn2** [comment]
1. Does LONGREADLEN matter when NO_LOB_LOCATOR is disabled?
2. When DATA_LIMIT is 10,000 and exporting a BLOB table, it will divide by 10 twice, to be 100.
3. Does ora2pg decide when BLOB_LIMIT overrides DATA_LIMIT?  (I set DATA_LIMIT 10000 and  BLOB_LIMIT 900; instead of seeing COMMIT every 100 records, I see it every 900 records.

**Comment by darold** [comment]
1. When NO_LOB_LOCATOR is disabled Ora2Pg retrieved the BLOB value in a single pass up to LONGREADLEN bytes. If LONGTRUNCOK is enabled and the BLOB size is upper than LONGREADLEN, the BLOB value will simply be truncated. If LONGTRUNCOK is disabled an error will be thrown. This is the classic Oracle behavior.So yes it matter.
2. Yes
3. No, BLOB_LIMIT always override the auto adjustment of DATA_LIMIT this is all the interest of this directive.

**Comment by RonJohn2** [comment]
So LOB_CHUNK_SIZE is only for speed?

**Comment by darold** [comment]
Yes, this correspond to ora_lob_chunk_size on DBD::Oracle. For more information on Oracle BLOB performances see http://download.oracle.com/docs/cd/B28359_01/appdev.111/b28393/adlob_performance.htm#i1007089 for example.
