### ISSUE TITLE
There is a bug in the import_all.sh file that came out after executing the ora2pg command.

### ISSUE THREAD

**Issue by jjune235** [darold/ora2pg#1085]
![ora2pg bug](https://user-images.githubusercontent.com/11729808/109103322-05106300-776e-11eb-8bf5-239c1cd58216.png)

There is a bug in the import_all.sh file that came out after executing the ora2pg command. (version 21) 
In the other lines in import_all.sh, $DB_OWNER is written as the username, 
whereas in the 'GRANT' part, the user name is fixed as 'postgres'.

This seems to need to be fixed.

**Comment by darold** [comment]
Actually to apply GRANT and CREATE TABLESPACE DDL you need superuser privilege and this should not be the case for the database owner. But maybe the script can look first at PostgreSQL to see if the owner has superuser privilege.

**Comment by darold** [comment]
Commit 2971fdb makes import_all.sh to use the database owner to look at privileges and tablespaces when it is a superuser.
