### ISSUE TITLE
Data not getting migrated for all tables

### ISSUE THREAD

**Issue by selvakumarmurugaiah** [darold/ora2pg#1086]
Hi Team

When we run data migration for around 134 tables, it does not move all tables, some times it moves 69, sometimes it moves 35 and exits. On one occasion it moved all the 134 tables. Though on launch it recognizes 134 tables and shows row count for each of them. 

We are using Jobs 10 and parallel_tables parameter 10. Please advice is there any other parameter we need to optimize.

Thanks in advance

**Comment by darold** [comment]
So you just run 10 parallel tables extraction (PARALLEL_TABLES) as JOBS is not taken in account in this case. That mean that you have more that 10 cpus to run the export which is good but you could probably have better performances using `-P 5 -j 2`.
 
Is there is any error message reported by Ora2Pg or an OOM entry reported by the dmesg command? What is the value of DATA_LIMIT and your amount of memory?

**Comment by selvakumarmurugaiah** [comment]
Thanks Darold for the reply.

DATA_LIMIT is 2000
Memory 62GB
CPU 8 

We do not see any error reported. where to check the OOM entry?

**Comment by darold** [comment]
"OOM entry reported by the dmesg command" or see /var/log/kernel.log of course I suppose that your are using Linux.

**Comment by selvakumarmurugaiah** [comment]
Hi Darold we checked kernel log do not see any error. After reducing the number P 5 J 2, it stops at 5 tables itself out of them one table has 50 millon rows.  If I exclude the top table, able to transfer around 50 tables and then stops again.

**Comment by selvakumarmurugaiah** [comment]
Hi Darold We changed to P1 and J1, it runs for some 1.5 hours and fails with below ORA error. Tried twice it failed with same error. Do we need to check any settings in oracle end?

FATAL: ORA-01555: snapshot too old: rollback segment number 10 with name "_SYSSMU10_4223344295$" too small (DBD ERROR: OCIStmtExecute)

**Comment by darold** [comment]
Yes you can tune Oracle but you can also try with TRANSACTION set to readonly in ora2pg.conf it could helps. But exporting data in single process mode will take too much time to export data.
