### ISSUE TITLE
RANGE partitionning with a multi-columns partition key

### ISSUE THREAD

**Issue by beaud76** [darold/ora2pg#1088]
Hi Gilles,
Here is a problem detected in the PARTITION.sql script generated by Ora2Pg when using RANGE partitionning with a multi-columns partition key.
Let's take an example, with a table created like this:

CREATE TABLE d_expedition_dwh (
	aaepnpvu smallint,
	mmepnpvu smallint,
	dtepnpvu timestamp,
	cosoccomcli char(3),
...
) PARTITION BY RANGE (aaepnpvu, mmepnpvu) ;

In the PARTITION.sql file, the partitions are generated like this:

CREATE TABLE d_expedition_dwh_p_201201 PARTITION OF d_expedition_dwh
FOR VALUES FROM (MINVALUE) TO (2012) FROM (MINVALUE) TO (02);
CREATE TABLE d_expedition_dwh_p_201202 PARTITION OF d_expedition_dwh
FOR VALUES FROM (MINVALUE) TO (2012) FROM (MINVALUE) TO (03);
CREATE TABLE d_expedition_dwh_p_201203 PARTITION OF d_expedition_dwh
FOR VALUES FROM (MINVALUE) TO (2012) FROM (MINVALUE) TO (04);
CREATE TABLE d_expedition_dwh_p_201204 PARTITION OF d_expedition_dwh
FOR VALUES FROM (MINVALUE) TO (2012) FROM (MINVALUE) TO (05);
...

instead of :
CREATE TABLE d_expedition_dwh_p_201201 PARTITION OF d_expedition_dwh
  FOR VALUES FROM (MINVALUE, MINVALUE) TO (2012, 02);
CREATE TABLE d_expedition_dwh_p_201202 PARTITION OF d_expedition_dwh
  FOR VALUES FROM (2012, 02) TO (2012, 03);
CREATE TABLE d_expedition_dwh_p_201203 PARTITION OF d_expedition_dwh
  FOR VALUES FROM (2012, 03) TO (2012, 04);
CREATE TABLE d_expedition_dwh_p_201204 PARTITION OF d_expedition_dwh
  FOR VALUES FROM (2012, 04) TO (2012, 05);
...

Ora2Pg has been cloned from github Feb the 23rd, and we are currently using a Postgres 10 version.
I presume that the problem is located in the Ora2Pg.pm module near line #6209

Best regards. Philippe.

**Comment by darold** [comment]
I see thanks for the report Philippe, I will fix that asap.

**Comment by darold** [comment]
Commit 1265b57 might fix this issue.

**Comment by beaud76** [comment]
Your commit effectively fixes the problem.
Thanks a lot for your quick answer.
