### ISSUE TITLE
Partitionned index when RANGE partitionning with a multi-columns partition key

### ISSUE THREAD

**Issue by beaud76** [darold/ora2pg#1089]
Hi Gilles,
Here is another problem related to RANGE partitionning with a multi-columns partition key. This time, it deals with the PARTITION_INDEXES_PARTITION.sql script. Some indexes are created several times.

Let's take an example, with a table created like this:

CREATE TABLE d_expedition_dwh (
aaepnpvu smallint,
mmepnpvu smallint,
dtepnpvu timestamp,
cosoccomcli char(3),
...
) PARTITION BY RANGE (aaepnpvu, mmepnpvu) ;

For this table, in the PARTITION_INDEXES_PARTITION.sql file, the indexes are generated like this (here for the first 2 partitions):

-- Create indexes on each partition of table D_EXPEDITION_DWH
CREATE INDEX d_expedition_dwh_p_201201_aaepnpvu1 ON d_expedition_dwh_p_201201 (aaepnpvu);
-- Reproduce partition indexes that was defined on the parent table
CREATE INDEX d_expedition_dwh_p_201201_i11 ON d_expedition_dwh_p_201201 (dtepnpvu);
CREATE INDEX d_expedition_dwh_p_201201_i101 ON d_expedition_dwh_p_201201 (cotypcmd);
-- Reproduce partition unique indexes / pk that was defined on the parent table
ALTER TABLE d_expedition_dwh_p_201201 ADD PRIMARY KEY (cosit,nocmd,noligcmdunq,nocoi,noligcis,aaepnpvu,mmepnpvu);

CREATE INDEX d_expedition_dwh_p_201201_mmepnpvu1 ON d_expedition_dwh_p_201201 (mmepnpvu);
-- Reproduce partition indexes that was defined on the parent table
CREATE INDEX d_expedition_dwh_p_201201_i11 ON d_expedition_dwh_p_201201 (dtepnpvu);
CREATE INDEX d_expedition_dwh_p_201201_i101 ON d_expedition_dwh_p_201201 (cotypcmd);
-- Reproduce partition unique indexes / pk that was defined on the parent table
ALTER TABLE d_expedition_dwh_p_201201 ADD PRIMARY KEY (cosit,nocmd,noligcmdunq,nocoi,noligcis,aaepnpvu,mmepnpvu);

CREATE INDEX d_expedition_dwh_p_201202_aaepnpvu2 ON d_expedition_dwh_p_201202 (aaepnpvu);
-- Reproduce partition indexes that was defined on the parent table
CREATE INDEX d_expedition_dwh_p_201202_i12 ON d_expedition_dwh_p_201202 (dtepnpvu);
CREATE INDEX d_expedition_dwh_p_201202_i102 ON d_expedition_dwh_p_201202 (cotypcmd);
-- Reproduce partition unique indexes / pk that was defined on the parent table
ALTER TABLE d_expedition_dwh_p_201202 ADD PRIMARY KEY (cosit,nocmd,noligcmdunq,nocoi,noligcis,aaepnpvu,mmepnpvu);

CREATE INDEX d_expedition_dwh_p_201202_mmepnpvu2 ON d_expedition_dwh_p_201202 (mmepnpvu);
-- Reproduce partition indexes that was defined on the parent table
CREATE INDEX d_expedition_dwh_p_201202_i12 ON d_expedition_dwh_p_201202 (dtepnpvu);
CREATE INDEX d_expedition_dwh_p_201202_i102 ON d_expedition_dwh_p_201202 (cotypcmd);
-- Reproduce partition unique indexes / pk that was defined on the parent table
ALTER TABLE d_expedition_dwh_p_201202 ADD PRIMARY KEY (cosit,nocmd,noligcmdunq,nocoi,noligcis,aaepnpvu,mmepnpvu);

...

As you can see, the indexes on columns not in the partition key are created several times, as well as the PRIMARY KEY.

Ora2Pg has been cloned from github Feb the 23rd, and we are currently using a Postgres 10 version.

Best regards. Philippe.

**Comment by darold** [comment]
I think this issue is also fixed by commit 1265b57 from issue #1088

Partitioning before PostgreSQL 12 is not really useful especially if you have expressions in the partition key, but you know so I guess that the PG version is not a choice.

**Comment by beaud76** [comment]
I can confirm that the commit 1265b57 also fixes the problem.
Regarding your comment about the Postgres version, we are aware of all the functional and performance limitations with this very first major version providing the declarative partitionning. But we currently have strong constraints of supported PG version by a very third part vendor. And convincing the biggest vendors to support recent major versions is sometimes like moving the mountains (knowing where you live, I am sure you know what I mean ;-))
Thanks again.
Philippe.
