### ISSUE TITLE
ORA2PG Data Export wrong char encoding need help

### ISSUE THREAD

**Issue by axbl** [darold/ora2pg#109]
Hi,
I have a Oracle Database with German Charset (üöäÜÖÄ...).
In Oracle I have NLS_LANG GERMAN.GERMANY.WE8ISO8859P15
In Postgres I have WIN1252.

In ora2pg.conf I have tried with 
NLS_LANG	GERMAN_GERMANY.WE8ISO8859P15
NLS_NCHAR	WE8MSWIN1252

But in the sql-result File I get Ãœ instead of Ü.

What is going wrong ?
Thank you, Axel

**Comment by darold** [comment]
Hi,

Please download an use latest code from github and comment NLS_LANG, NLS_NCHAR and CLIENT_ENCODING ora2pg configuration directives. Verify that the corresponding environment variables are unset then execute ora2pg again.

Now Ora2Pg should works well by default using UTF8 encoding, if not, please report errors with all those parameters disabled.

Let us now,

**Comment by axbl** [comment]
Hi, thank you for your quick answer.

I yesterday downloaded the last version from GitHub.
No enviroment is set.
I have commented out (#) the 3 directives.

But it is the same error.

SELECT * FROM NLS_DATABASE_PARAMETERS:
NLS_LANGUAGE	AMERICAN
NLS_TERRITORY	AMERICA
NLS_CURRENCY	$
NLS_ISO_CURRENCY	AMERICA
NLS_NUMERIC_CHARACTERS	.,
NLS_CHARACTERSET	WE8MSWIN1252
NLS_CALENDAR	GREGORIAN
NLS_DATE_FORMAT	DD-MON-RR
NLS_DATE_LANGUAGE	AMERICAN
NLS_SORT	BINARY
NLS_TIME_FORMAT	HH.MI.SSXFF AM
NLS_TIMESTAMP_FORMAT	DD-MON-RR HH.MI.SSXFF AM
NLS_TIME_TZ_FORMAT	HH.MI.SSXFF AM TZR
NLS_TIMESTAMP_TZ_FORMAT	DD-MON-RR HH.MI.SSXFF AM TZR
NLS_DUAL_CURRENCY	$
NLS_COMP	BINARY
NLS_LENGTH_SEMANTICS	BYTE
NLS_NCHAR_CONV_EXCP	FALSE
NLS_NCHAR_CHARACTERSET	AL16UTF16
NLS_RDBMS_VERSION	11.2.0.1.0

Toad export to flat file is ok.

SqlPlus with NLS_LANG=GERMAN_GERMANY.WE8PC850 enviroment is ok to.

Best regards, Axel

**Comment by darold** [comment]
Can you post the ora2pg command line and the output of this command using -d parameter?

**Comment by axbl** [comment]
Hi,
its funny.
I have changed to export only one table.
Now it works.
But Import runs in conversion Error:

PSQL:D:/ORA2PG.sql:4952385: FEHLER:  Zeichen mit Byte-Folge 0xc2 0x81 in Kodieru
ng Ã¢â'¬Å¾UTF8Ã¢â'¬Å" hat keine Entsprechung in Kodierung Ã¢â'¬Å¾WIN1252Ã¢â'¬Å"
KONTEXT:  COPY sg_sw, Zeile 1106

So I enabled the settings in the conf file.
NLS_LANG GERMAN_GERMANY.WE8ISO8859P15
NLS_NCHAR WE8MSWIN1252
CLIENT_ENCODING	WIN1252

It works too with the one table.
Then I exported all tables, error with encoding.

One question: May there be a problem if the Output file exists ?

**Comment by axbl** [comment]
If I export one table the export file is opend in my text editor (Ultraedit) showing "UTF8" in the status line and the values are ok.
I I export all Tables it shows "1252 ANSI Latin I" and I get wrong encoding.

**Comment by darold** [comment]
Oh you are running Ora2pg on Windows, ok. The Windows console is not able to handle unicode characters correctly, at least the last time I use it.

You can try to force incoding in your ora2pg.conf file using:

    NLS_LANG GERMAN_GERMANY.WE8MSWIN1252
    NLS_NCHAR WE8MSWIN1252
    CLIENT_ENCODING WIN1252

If that still not workks, you might install DBD::Pg and try direct import into your PostgreSQL database by setting the PG_DSN, PG_USER and PG_PWD configuration directives. I guess in this case, data will not go through the cmd console to a file. Keep all encoding parameters as default UTF8 as explain in my first response. 

Let me know if one or none of these solutions solve your issue.

**Comment by axbl** [comment]
Hi, thank you.

As I wrote the 
NLS_LANG GERMAN_GERMANY.WE8MSWIN1252
NLS_NCHAR WE8MSWIN1252
CLIENT_ENCODING WIN1252

works inly for one table. See above !

**Comment by darold** [comment]
I understand that you use

    NLS_LANG GERMAN_GERMANY.WE8ISO8859P15

not 

    NLS_LANG GERMAN_GERMANY.WE8MSWIN1252

which is différent. Is that a typo?

**Comment by axbl** [comment]
No, there is no diference. Tried both.

**Comment by darold** [comment]
Ok, your last chance is using Perl Module DBD::Pg for direct import or install Ora2Pg in a linux box. I'm not a Windows user so I'm afraid I can't help much more on this operating system.

**Comment by axbl** [comment]
Ok, Thank you.
DBD::Pg works....
Best regards, Axel

**Comment by darold** [comment]
Great news,

The problem really comes from the Windows CMD console that do not support unicode characters, there's nothing we can do for that. I will not develop a GUI just to fix the terminal Windows leak of unicode support :-)

Thanks for your feed back.

**Comment by axbl** [comment]
But why when I select only one table it works ?

**Comment by darold** [comment]
Yes, at least it should. Just like dumping data to file, if that's not the case there must be a bug.
