### ISSUE TITLE
Constraint "CHECK <column_name> IS JSON" is failing schema migration

### ISSUE THREAD

**Issue by marie-joechahine** [darold/ora2pg#1090]
Hello again,

I have a table on Oracle which has a CLOB column with a CHECK constraint IS JSON, it is being converted to PostgreSQL as "ADD CONSTRAINT <table_name> CHECK (<column_name> IS JSON)", which is failing with a syntax error on JSON.

Should this column maybe be converted to the JSON type available in PostgreSQL?

**Comment by darold** [comment]
Yes, this problem must be handled manually and it doesn't need a check constraint as PostgreSQL json data type only accept valid json input.

**Comment by marie-joechahine** [comment]
Okay makes sense, thank you.

**Comment by darold** [comment]
Commit b5f7763 replace IS JSON in check constraints by `(CASE WHEN <colname>::json IS NULL THEN true ELSE true END)`
