### ISSUE TITLE
Duplicate name on partitions index with sub-partitionning

### ISSUE THREAD

**Issue by beaud76** [darold/ora2pg#1091]
Hi Gilles,
Having applied the latest 1265b57 commit, we get another problem in the the PARTITION_INDEXES_PARTITION.sql script. We have duplicate name on indexes for our table that has sub-partitionning.

The table and its partitions are created with:

CREATE TABLE d_fin_ecriture_dwh (
	chect bigint NOT NULL,
	aacpb smallint NOT NULL,
	mmcpb smallint NOT NULL,
	cobra varchar(3) NOT NULL,
	codom varchar(10),
...
) PARTITION BY RANGE (aacpb, mmcpb) ;

and for the first partitions:

CREATE TABLE d_fin_ecriture_dwh_p2006_01 PARTITION OF d_fin_ecriture_dwh
FOR VALUES FROM (MINVALUE,MINVALUE) TO (2006, 2)
PARTITION BY LIST (cobra);
CREATE TABLE d_fin_ecriture_dwh_p2006_01_p2006_01_pcos PARTITION OF d_fin_ecriture_dwh_p2006_01
FOR VALUES IN ('COS');
CREATE TABLE d_fin_ecriture_dwh_p2006_01_p2006_01_pmed PARTITION OF d_fin_ecriture_dwh_p2006_01
FOR VALUES IN ('MED');
CREATE TABLE d_fin_ecriture_dwh_p2006_01_p2006_01_phol PARTITION OF d_fin_ecriture_dwh_p2006_01
FOR VALUES IN ('HOL');
CREATE TABLE d_fin_ecriture_dwh_p2006_02 PARTITION OF d_fin_ecriture_dwh
FOR VALUES FROM (2006, 2) TO (2006, 3)
PARTITION BY LIST (cobra);
CREATE TABLE d_fin_ecriture_dwh_p2006_02_p2006_02_pcos PARTITION OF d_fin_ecriture_dwh_p2006_02
FOR VALUES IN ('COS');
CREATE TABLE d_fin_ecriture_dwh_p2006_02_p2006_02_pmed PARTITION OF d_fin_ecriture_dwh_p2006_02
FOR VALUES IN ('MED');
CREATE TABLE d_fin_ecriture_dwh_p2006_02_p2006_02_phol PARTITION OF d_fin_ecriture_dwh_p2006_02
FOR VALUES IN ('HOL');
...

In the PARTITION_INDEXES_PARTITION.sql file, we get:

-- Create indexes on each partition of table D_FIN_ECRITURE_DWH
CREATE INDEX d_fin_ecriture_dwh_p2006_01_p2006_01_pcos_cobra1 ON d_fin_ecriture_dwh_p2006_01_p2006_01_pcos (mmcpb,cobra);
-- Reproduce subpartition indexes that was defined on the parent table
CREATE INDEX idw_d_fin_ecriture_dwh1 ON d_fin_ecriture_dwh_p2006_01_p2006_01_pcos (codev, coitc, coterimp, cosocimp, coprjimp, coproimp, cofonimp, cocpt, cobra);
CREATE INDEX idx_fait_cobra1 ON d_fin_ecriture_dwh_p2006_01_p2006_01_pcos (cobra);
-- Reproduce subpartition unique indexes / pk that was defined on the parent table
ALTER TABLE d_fin_ecriture_dwh_p2006_01_p2006_01_pcos ADD PRIMARY KEY (aacpb,mmcpb,chect,cobra,cobraint);

CREATE INDEX d_fin_ecriture_dwh_p2006_01_p2006_01_pmed_cobra2 ON d_fin_ecriture_dwh_p2006_01_p2006_01_pmed (mmcpb,cobra);
-- Reproduce subpartition indexes that was defined on the parent table
CREATE INDEX idw_d_fin_ecriture_dwh2 ON d_fin_ecriture_dwh_p2006_01_p2006_01_pmed (codev, coitc, coterimp, cosocimp, coprjimp, coproimp, cofonimp, cocpt, cobra);
CREATE INDEX idx_fait_cobra2 ON d_fin_ecriture_dwh_p2006_01_p2006_01_pmed (cobra);
-- Reproduce subpartition unique indexes / pk that was defined on the parent table
ALTER TABLE d_fin_ecriture_dwh_p2006_01_p2006_01_pmed ADD PRIMARY KEY (aacpb,mmcpb,chect,cobra,cobraint);

CREATE INDEX d_fin_ecriture_dwh_p2006_01_p2006_01_phol_cobra3 ON d_fin_ecriture_dwh_p2006_01_p2006_01_phol (mmcpb,cobra);
-- Reproduce subpartition indexes that was defined on the parent table
CREATE INDEX idw_d_fin_ecriture_dwh3 ON d_fin_ecriture_dwh_p2006_01_p2006_01_phol (codev, coitc, coterimp, cosocimp, coprjimp, coproimp, cofonimp, cocpt, cobra);
CREATE INDEX idx_fait_cobra3 ON d_fin_ecriture_dwh_p2006_01_p2006_01_phol (cobra);
-- Reproduce subpartition unique indexes / pk that was defined on the parent table
ALTER TABLE d_fin_ecriture_dwh_p2006_01_p2006_01_phol ADD PRIMARY KEY (aacpb,mmcpb,chect,cobra,cobraint);

CREATE INDEX d_fin_ecriture_dwh_p2006_02_p2006_02_pcos_cobra1 ON d_fin_ecriture_dwh_p2006_02_p2006_02_pcos (mmcpb,cobra);
-- Reproduce subpartition indexes that was defined on the parent table
CREATE INDEX idw_d_fin_ecriture_dwh1 ON d_fin_ecriture_dwh_p2006_02_p2006_02_pcos (codev, coitc, coterimp, cosocimp, coprjimp, coproimp, cofonimp, cocpt, cobra);
CREATE INDEX idx_fait_cobra1 ON d_fin_ecriture_dwh_p2006_02_p2006_02_pcos (cobra);
-- Reproduce subpartition unique indexes / pk that was defined on the parent table
ALTER TABLE d_fin_ecriture_dwh_p2006_02_p2006_02_pcos ADD PRIMARY KEY (aacpb,mmcpb,chect,cobra,cobraint);

CREATE INDEX d_fin_ecriture_dwh_p2006_02_p2006_02_pmed_cobra2 ON d_fin_ecriture_dwh_p2006_02_p2006_02_pmed (mmcpb,cobra);
-- Reproduce subpartition indexes that was defined on the parent table
CREATE INDEX idw_d_fin_ecriture_dwh2 ON d_fin_ecriture_dwh_p2006_02_p2006_02_pmed (codev, coitc, coterimp, cosocimp, coprjimp, coproimp, cofonimp, cocpt, cobra);
CREATE INDEX idx_fait_cobra2 ON d_fin_ecriture_dwh_p2006_02_p2006_02_pmed (cobra);
-- Reproduce subpartition unique indexes / pk that was defined on the parent table
ALTER TABLE d_fin_ecriture_dwh_p2006_02_p2006_02_pmed ADD PRIMARY KEY (aacpb,mmcpb,chect,cobra,cobraint);

CREATE INDEX d_fin_ecriture_dwh_p2006_02_p2006_02_phol_cobra3 ON d_fin_ecriture_dwh_p2006_02_p2006_02_phol (mmcpb,cobra);
-- Reproduce subpartition indexes that was defined on the parent table
CREATE INDEX idw_d_fin_ecriture_dwh3 ON d_fin_ecriture_dwh_p2006_02_p2006_02_phol (codev, coitc, coterimp, cosocimp, coprjimp, coproimp, cofonimp, cocpt, cobra);
CREATE INDEX idx_fait_cobra3 ON d_fin_ecriture_dwh_p2006_02_p2006_02_phol (cobra);
-- Reproduce subpartition unique indexes / pk that was defined on the parent table
ALTER TABLE d_fin_ecriture_dwh_p2006_02_p2006_02_phol ADD PRIMARY KEY (aacpb,mmcpb,chect,cobra,cobraint);

...

As you can see, some indexes on the sub-partitions are created with the same name (idw_d_fin_ecriture_dwh1, idx_fait_cobra1).

Best regards. Philippe.

**Comment by darold** [comment]
Commit 892b42d might solve this issue.

**Comment by beaud76** [comment]
Thanks a lot, Gilles.
