### ISSUE TITLE
Double column renaming in select statements

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1092]
Good afternoon,

I hereby come into contact because when converting an oracle trigger to postegresql via ora2pg I noticed an error related to the double renaming of columns in the select statement, visible below:

Oracle
SELECT COLUMN_VALUE c2,  **ROWNUM r2** FROM
                (SELECT COLUMN_VALUE c, **ROWNUM r** FROM TABLE(desagrega_strings(:NEW.equipamento,'|')) b) a,
                TABLE(desagrega_strings(a.c))
                WHERE r = 1

Postegresql
SELECT COLUMN_VALUE C2, row_number() OVER () AS **ROWNUM R2** FROM (SELECT COLUMN_VALUE C, row_number() OVER () AS **ROWNUM R** FROM DESAGREGA_STRINGS(NEW.EQUIPAMENTO,'|')) B A,
                DESAGREGA_STRINGS(A.C) ALIAS9
                WHERE R = 1

In this sense I come to ask, if possible, that in the conversion carried out via ora2pg when a certain select statement is already being renamed in the oracle statement that it is not renamed when converted to postegresql.

I hope you have explained me correctly and that you have understood the problem that I am exposing?, otherwise I will be communicated in order to explain myself better.

Thanks in advance for any help given.

Best regards,

Rui Pereira.

**Comment by darold** [comment]
Commit e57b254 might fix this issue.
