### ISSUE TITLE
Importing an index containing "to_char(value, format_mask)" fails 

### ISSUE THREAD

**Issue by marie-joechahine** [darold/ora2pg#1093]
I have an index containing a function with 4 uses of to_char in oracle as follows:

CASE  WHEN ("ROOM_ID"<>(-1) AND "BENEFIT_PROVIDER_ID"<>(-1)) THEN TO_CHAR("ROOM_ID")||','||TO_CHAR("BENEFIT_PROVIDER_ID")||','||TO_CHAR("DATE_FROM",'DD-MON-RR')||','||TO_CHAR("DATE_TO",'DD-MON-RR') ELSE NULL END 

It is translated to this:

case when (room_id<>(-1) and benefit_provider_id<>(-1)) then (room_id::varchar)||','||(benefit_provider_id::varchar)||','||to_char(date_from,'DD-MON-RR')||','||to_char(date_to,'DD-MON-RR') else null end

to_char in the third and fourth instance i guess were not converted because they have the format argument filled, which should work in PostgreSQL, but it is failing with the following error because to_char needs to be immutable: functions in index expression must be marked IMMUTABLE SQL state: 42P17.

Some researching led me to a solution which would be to create my own to_char function as immutable, do you think there is a better or easier solution for this?

**Comment by darold** [comment]
Yes, this is usually what is done if the index is really useful.
