### ISSUE TITLE
Issues with Assessment Report

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#1094]
when I run the assessment report, I see the below screen:
![assess_report1](https://user-images.githubusercontent.com/67134199/109823380-e3c3e100-7c5d-11eb-871b-05bbdf811747.PNG)

but when I open the output HTML file, there are no complete objects. 
![assess_report2](https://user-images.githubusercontent.com/67134199/109823505-01914600-7c5e-11eb-8c2b-5a67623260de.PNG)

not sure where is the discrepancy. Please help me on this.

**Comment by naveenjul29** [comment]
Darold, can you please look into this?

**Comment by darold** [comment]
Same answer as with #1096, This is not a problem I can solve without being able to reproduce it. I recommend you to use Ora2Pg on Linux to see if the problem is not related to Windows port.

**Comment by naveenjul29** [comment]
Thank you Darold.
