### ISSUE TITLE
Error when using the when clause within a trigger function

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1095]
Goodnight,

I hereby come into contact because when converting an oracle trigger to postegres, using ora2pg, which contains the when clause an error occurs, probably related to the closing parenthesis of the case clause, can you verify and resolve it?

Trigger body in Oracle:
----------------------------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER tr_indic_ttk_reg_registo
BEFORE INSERT OR UPDATE ON reg_registo
FOR EACH ROW
when (NVL(new.dispara_triggers,1) = 1)
BEGIN
	INSERT INTO TRA_INDICADORES_TTK (ID, REFERENCIA_TTK, REFERENCIA_REG, ID_TIPO_TICKET,ID_REGISTO)
	VALUES (NULL, :NEW.referencias, :NEW.referencia, (CASE WHEN :NEW.referencia LIKE 'P%' THEN 2 WHEN :NEW.referencia LIKE 'I%' THEN 3 WHEN :NEW.referencia LIKE 'U%' THEN 4 END),:NEW.ID);  
EXCEPTION
	WHEN OTHERS THEN
	/*CALL*/ logger.error('TR_INDIC_TTK_REG_REGISTO','SQLERRM: ' || SQLERRM);
END;
/

Postgres trigger body:
----------------------------------------------------------------------------------------------------------------------------------------
DROP TRIGGER IF EXISTS tr_indic_ttk_reg_registo ON reg_registo CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tr_indic_ttk_reg_registo() RETURNS trigger AS $BODY$
BEGIN
	INSERT INTO TRA_INDICADORES_TTK(ID, REFERENCIA_TTK, REFERENCIA_REG, ID_TIPO_TICKET,ID_REGISTO)
	VALUES (NULL /*só será gerado pelo job após commit*/
, NEW.referencias, NEW.referencia, **(CASE WHEN NEW.referencia LIKE 'P%' THEN 2 WHEN NEW.referencia LIKE 'I%' THEN 3 WHEN NEW.referencia LIKE 'U%' THEN 4 END)**,NEW.ID)
$BODY$
 LANGUAGE 'plpgsql';
CREATE TRIGGER tr_indic_ttk_reg_registo
BEFORE INSERT OR UPDATE ON reg_registo FOR EACH ROW
	WHEN ((coalesce(new.dispara_triggers,1) = 1))
	EXECUTE PROCEDURE trigger_fct_tr_indic_ttk_reg_registo();

I would like to thank you for any help or answer given in solving this problem, if the problem explained by me is not explicit, please, if possible, please inform me so that I can explain the issue better.

Best regards,

Rui Pereira.

**Comment by darold** [comment]
Commit 86b91d7 fixes this issue.
