### ISSUE TITLE
Add ora2pg client identifier to DB sessions #enhancement

### ISSUE THREAD

**Issue by yonisade** [darold/ora2pg#1097]
Can you please set ora2pg client identifier for DB sessions so admins can identify them easily?

### For Oracle use:
my $dbh = DBI->connect($self->{oracle_dsn}, $self->{oracle_user}, $self->{oracle_pwd},
		{
			ora_envhp => 0,
			LongReadLen=>$self->{longreadlen},
			LongTruncOk=>$self->{longtruncok},
			AutoInactiveDestroy => 1,
			PrintError => 0,
			ora_session_mode => $ora_session_mode,
                        **ora_client_info => 'ora2pg ' || $VERSION**
		}
	);

### For MySQL:
my $dbh = DBI->connect("$self->{oracle_dsn}", $self->{oracle_user}, $self->{oracle_pwd}, { 'RaiseError' => 1, AutoInactiveDestroy => 1, mysql_enable_utf8 => 1, **mysql_conn_attrs => { program_name => 'ora2pg ' || $VERSION }** });

### For PostgreSQL:
**$ENV{PGAPPNAME} = 'ora2pg ' || $VERSION;**

**Comment by darold** [comment]
Thanks, patch applied in commit b03d737
