### ISSUE TITLE
Script import.sh

### ISSUE THREAD

**Issue by joguess** [darold/ora2pg#1099]
Hello.
While executing the script import.sh in a project context...
I would like to suggest you to create a response file including the commands (psql ones) that ora2pg provides while answering yes to the prompt. 
So we could create a shell script from the response file easy. And I could deploy the script in puppet master for exemple...
Thanks for your work.
Regards,
Josselin.

**Comment by darold** [comment]
If you use the debug mode `-D` the script will print the commands that will be executed but doesn't execute them (dry run)
