### ISSUE TITLE
Migrating schema fails when directive PG_INTEGER_TYPE is set to 0 and IDENTITY columns exist in Oracle

### ISSUE THREAD

**Issue by marie-joechahine** [darold/ora2pg#1100]
Hello! Thank you again for this amazing tool, I've been experimenting with it over the past 2 weeks.

I encountered a small issue, not sure if it can be considered a bug. IDENTITY columns need to be either smallint, int or bigint. So number(10) columns convert to numeric(10), so when these columns are identity columns in Oracle, migration fails. Not sure if a directive needs to be added for the type of identity columns, or if only for those columns the type should instead be transformed to smallint, int or bigint, ignoring the PG_INTEGER_TYPE directive.

**Comment by darold** [comment]
Good catch, I will add this exception for identity column.

**Comment by darold** [comment]
This commit have been fixed by commit 990e2b6, by forcing a column with an identity clause to be exported as bigint, this is the only type supported by PostgreSQL.
