### ISSUE TITLE
Problem with sequences when EXPORT_SCHEMA is enabled

### ISSUE THREAD

**Issue by marie-joechahine** [darold/ora2pg#1101]
When EXPORT_SCHEMA is enabled, the output when generating schema contains the command to create the schema. When we have sequences and this schema depends on them (for example a column "id bigint NOT NULL DEFAULT nextval('seq_name')" , we need to import the sequences first, but when importing the sequences first, the schema is not created yet. I think we need to add "CREATE SCHEMA IF NOT EXISTS schema_name" to the sequence output.
Also in the schema output file, the sequences are not being prefixed with the schema name which also causes an issue even when the sequences are imported first (in the example above, the column should be "id bigint NOT NULL DEFAULT nextval('schema_name.seq_name')" ).

**Comment by darold** [comment]
Commits 31b0f01 and aa04848 might fix these issues. Thanks for the feedback.
