### ISSUE TITLE
How to adapt ora2pg.conf for huge table to be migrated

### ISSUE THREAD

**Issue by joguess** [darold/ora2pg#1103]
Hello

We have huge tables to migrate from oracle to postgres.
We have several millions of rows on one specific table.
We are using ora2pg tool.
I would like to know how I can improve the process of migration ? 
How can I configure / optimize ora2pg.conf to be able to migrate as fast as ora2pg can the for big tables? 

Can you please help me ?

Regards,

Josselin

**Comment by darold** [comment]
You can look at https://www.darold.net/confs/ora2pg-performances.pdf it is a bit old but should still be applicable. It's in french but might be understandable.
