### ISSUE TITLE
Oracle table(s) are loaded not fully.

### ISSUE THREAD

**Issue by FedorFFF1** [darold/ora2pg#1104]
Hi Gilles Darold
Thanks for **GOOD** tool. 

I use ora2pg20 installed using docker.
Oracle 12 --> Postgres Azure 11.
Oracle 12 is DEV env. - updated very little during copy (mostly 5-10 records inserted in some tables).

docker-compose ${override} run ora2pg -d -J 8 -j 8 -t COPY   --pg_dsn ${PG_DSN} --pg_user ${PG_USER} --pg_pwd ${PG_PWD} -c config/orx_ora2pg.conf

When copying small DB-s all is OK 

Set in config :  **LOG_ON_ERROR		1**
I need process _Not stop if any error._

1?) for average Oracle DB (7 195 347 - max. record count in tables )
I got error : **DBD::Oracle::db disconnect failed: ORA-03113: end-of-file on communication channel**
trying to re-load 6-10 times (during times when Nobody work with Oracle )
No luck.
I m sure that connect to Oracle is stable. (At least I run from SQL developer queries for check)
Error is always  :  ORA-03113: end-of-file on communication channel
sometimes it can load more data but in 15-20 minutes it fail
Any suggestions ?

2) As workaround I tried to load by sub-sets of tables :
partner.* , t.*
docker-compose ${override} run ora2pg -d -J 8 -j 8 -t COPY -a partner.*  
--pg_dsn ${PG_DSN} --pg_user ${PG_USER} --pg_pwd ${PG_PWD} -c config/orx_ora2pg.conf > p1.log
Generally it works.
But today I checked counts in some target Oracle tables I have much less records ( most others were ok ) .
partneraddressvr 920228 :	**280228** (in postgres)
I run previous command but w/o > p1.log
I saved log from git bash console.
I can't see beginning of script but can see :
[2021-03-11 15:28:33] [2] Scanning table PARTNERADDRESSVR (919707 rows)...
....
[2021-03-11 15:34:04] Extracted records from table PARTNERADDRESSVR: total_records = 229297 (avg: 888 recs/sec)
[2021-03-11 15:34:05] Looking how to retrieve data from PARTNERCOMMUNICATIONID...

**!!! You see PARTNERADDRESSVR (919707 rows) is NOT copied fully**
... --> Next table 
[2021-03-11 15:34:05] DEGUG: Query sent to Oracle: SELECT "PARTNERCOMMUNICATIONID_ID","PARTNERADDRESSID_ID","ORDERNO","IS_ACTIVE","FIRSTVERSION_ID","LASTVERSION_ID","PARTNER_ID","KEYUI" FROM "ORX"."PARTNERCOMMUNICATIONID" a WHERE ABS(MOD(PARTNERCOMMUNICATIONID_ID, 4)) = ?
[2021-03-11 15:34:05] Creating new connection to database to extract data...
...
[2021-03-11 16:01:43] Total time to export data from 19 tables (0 partitions, 0 sub-partitions) and 24084531 total rows: 1987 wallclock secs ( 1.08 usr  0.56 sys + 1420.67 cusr 118.68 csys = 1540.99 CPU)
[2021-03-11 16:01:43] Speed average: 12121.05 rows/sec
[2021-03-11 16:01:43] Fixing function calls in output files...

No errors in log  ( error , ORA- , fail)
No .err files ( Target Postgres tables were empty)
Only assumption I have it can be connected with parallel load to Postgres 
-j | --jobs num   : Number of parallel process to send data to PostgreSQL.
-J | --copies num : Number of parallel connections to extract data from Oracle.
-l | --log file   : Set a log file. Default is stdout.

I removed -j8 and seems it works next time.

2a?) But question is why there is NO any indication that Table(s) was NOT loaded 
( when loaded t*. tables - I found many mismatches in counts )

2b) What you recommend for  - J , -j settings ?
( Azure : Postgres 11 : General Purpose, 2 vCore(s), 100 GB )
( w/o -J - it works very slowly even with average DB ) 

3) truncate table   PARTNERADDRESSVR
and reload it single with : -J 8 -j 8
docker-compose ${override} run ora2pg -d -J 8 -j 8 -t COPY -a partneraddressvr  
--pg_dsn ${PG_DSN} --pg_user ${PG_USER} --pg_pwd ${PG_PWD} -c config/orx_ora2pg.conf > partneraddressvr.log

Checked Count - it is correct.
Checked data is also seems correct ( max , min , average)
but exists err file : PARTNERADDRESSVR_error.log  with 380 000 rows !!
in console log : 
[2021-03-11 14:47:55] Disabling synchronous commit when writing to PostgreSQL...
DBD::Pg::db pg_putcopyend failed: ERROR:  duplicate key value violates unique constraint "partneraddressvr_pkey"
DETAIL:  Key (partneraddressvr_pk)=(54) already exists.
**84 such rows in Log.**

3a?) Do I suppose correct that in PARTNERADDRESSVR_error.log (380000 rows)
there are much more rows because if 1 row in batch fails 
that WHOLE batch of records is written in Log ?
( even so 84*10000 = 84000 , why 380000 ?)
If so how find really BAD records from PARTNERADDRESSVR_error.log 
only way to see console log   ?

3b?) This table was loaded correctly 
But when loaded all tables I need NO errors in log
to check that all is OK .
 
Does it mean that problem is in -j 8
and we need to load data in Postgres NOT parallel ?

**Comment by darold** [comment]
The base number of rows of each table is taken from Oracle statistics, if they are not up to date you will have wrong count. The other point in your ora2pg command is the number of processes, `-J 8 -j 8` means that Ora2Pg will use 64 cpu for the work. If you only have 2 vcpu then you will have problem of course. Also I don't recommend to use more than 4 cpus for `-j`, most of the time greater value doesn't helps for performances.
