### ISSUE TITLE
Missing partition scripts

### ISSUE THREAD

**Issue by sesref** [darold/ora2pg#1108]
Hi  I'm trying to create partitions of a schema but 14.7% of the partitions have scripts.  What could be causing this? 

PS C:\ora2pg\izcitest> ora2pg -c ora2pg.conf -t PARTITION -o partitions.sql -b schema/partitions/
[========================>] 2642/8 subpartitions (33025.0%) generating MON_INBOX_PROCESS/PMON_INBOX_PROCESS_2017_320/SYS
[========================>] 2643/8 subpartitions (33037.5%) generating MON_INBOX_PROCESS/PMON_INBOX_PROCESS_2017_320/SYS
[========================>] 2644/8 subpartitions (33050.0%) generating MON_INBOX_PROCESS/PMON_INBOX_PROCESS_2017_320/SYS
[========================>] 2645/8 subpartitions (33062.5%) generating MON_INBOX_PROCESS/PMON_INBOX_PROCESS_2017_320/SYS
[========================>] 2646/8 subpartitions (33075.0%) generating MON_INBOX_PROCESS/PMON_INBOX_PROCESS_2017_320/SYS
[========================>] 2647/8 subpartitions (33087.5%) generating MON_INBOX_PROCESS/PMON_INBOX_PROCESS_2017_320/SYS
[========================>] 2648/8 subpartitions (33100.0%) generating MON_INBOX_PROCESS/PMON_INBOX_PROCESS_2017_320/SYS
[========================>] 2649/8 subpartitions (33112.5%) generating MON_INBOX_PROCESS/PMON_INBOX_PROCESS_2017_320/SYS
[========================>] 2650/1 subpartitions (265000.0%) generating MON_INBOX_PROCESS/SYS_P244173/SYS_SUBP244152    
[===>                     ]  2727/18599 partitions (14.7%) end of output.
Fixing function calls in output files...

**Comment by darold** [comment]
Are you using latest development code?

**Comment by sesref** [comment]
version is Ora2Pg v21.0

**Comment by darold** [comment]
Please upgrade using:
```
wget https://github.com/darold/ora2pg/archive/master.zip
unzip master.zip
cd ora2pg-master
perl Makefile.PL
make
sudo make install
```
and run again the export. A recent commit fix the progress report for partitions.

**Comment by sesref** [comment]
Yess it worked. I also had a problem with partitioned table scripts and that problem is solved. Thank you!

**Comment by atlterry** [comment]
Hello; I'm having a similar issue with partitioned table...
psql:./schema/tables/table.sql:89: ERROR:  syntax error at or near "("
LINE 12: ) PARTITION BY  () ;
                         ^
ERROR: an error occurs when importing file ./schema/tables/table.sql.

CREATE TABLE hda_table (
...
) PARTITION BY  () ;

I upgraded as mentioned above and have Ora2Pg v21.0
Thanks

**Comment by darold** [comment]
Please download and install latest development code this have been already fixed.
```
wget https://github.com/darold/ora2pg/archive/refs/heads/master.zip
unzip master.zip
cd ora2pg-master
perl Makefile.PL
make
sudo make install
```
