### ISSUE TITLE
ora2pg doesn't find Oracle global temporary tables when running assessment

### ISSUE THREAD

**Issue by yonisade** [darold/ora2pg#1109]
ora2pg v21
Source DB: Oracle 11.2.0.4

ora2pg.conf:
USER_GRANTS is set to 0
DEBUG is set to 1 

ora2pg -t SHOW_REPORT --estimate_cost --dump_as_html -c config/ora2pg.conf > ora2pg_report.html
...
Looking at global temporary table...
        **Found 0 GLOBAL TEMPORARY TABLE.**
...

I can find the temp tables using:
select * from dba_tables where owner='XXXX'

**Comment by darold** [comment]
Global temporary tables are search using:
```
SELECT A.OWNER,A.TABLE_NAME,NVL(num_rows,1) NUMBER_ROWS,A.TABLESPACE_NAME,A.NESTED,A.LOGGING
    FROM DBA_TABLES A, ALL_OBJECTS O
    WHERE A.OWNER=O.OWNER AND A.TABLE_NAME=O.OBJECT_NAME AND O.OBJECT_TYPE='TABLE'
        AND A.OWNER='XXXX' AND A.TEMPORARY='Y' AND (A.DROPPED IS NULL OR A.DROPPED = 'NO'
        AND (A.IOT_TYPE IS NULL OR A.IOT_TYPE = 'IOT';
```
and they are well reported on my side.

**Comment by yonisade** [comment]
The issue is the query uses ALL_OBJECTS instead of DBA_OBJECTS.
It's also an issue when ora2pg is looking for regular tables.

**Comment by darold** [comment]
To make Ora2Pg looks at DBA_OBJECTS you must be DBA user and have USER_GRANTS set to 0 in ora2pg.conf.

**Comment by darold** [comment]
Hum after verification, I see several static calls to ALL_OBJECTS in joined tables, this should also be related to USER_GRANTS. I will fix that.

**Comment by yonisade** [comment]
Please re-open this issue then.
Thanks.

**Comment by darold** [comment]
Commit c5e5734 might fix this issue, please confirm.

**Comment by yonisade** [comment]
I see that in Ora2Pg.pm there are other hard-coded "ALL_" prefixes:

line 9765:      SELECT directory_path INTO l_path FROM all_directories WHERE directory_name = l_dir;

line 10150: 	my $spatial_srid = "SELECT SRID FROM ALL_SDO_GEOM_METADATA WHERE TABLE_NAME=? AND COLUMN_NAME=? AND OWNER=?";

line 10154: 		$spatial_srid = 'SELECT sdo_cs.map_oracle_srid_to_epsg(SRID) FROM ALL_SDO_GEOM_METADATA WHERE TABLE_NAME=? AND COLUMN_NAME=? AND OWNER=?';

line 10157: 	my $spatial_dim = "SELECT t.SDO_DIMNAME, t.SDO_LB, t.SDO_UB FROM ALL_SDO_GEOM_METADATA m, TABLE (m.diminfo) t WHERE m.TABLE_NAME=? AND m.COLUMN_NAME=? AND OWNER=?";

line 10374: 			$spatial_srid = "SELECT COALESCE(SRID, $self->{default_srid}) FROM ALL_SDO_GEOM_METADATA WHERE TABLE_NAME='\U$table\E' AND COLUMN_NAME='$row->[0]' AND OWNER='\U$self->{tables}{$table}{table_info}{owner}\E'";

line 10376: 				$spatial_srid = "SELECT COALESCE(sdo_cs.map_oracle_srid_to_epsg(SRID), $self->{default_srid}) FROM ALL_SDO_GEOM_METADATA WHERE TABLE_NAME='\U$table\E' AND COLUMN_NAME='$row->[0]' AND OWNER='\U$self->{tables}{$table}{table_info}{owner}\E'";
line :

**Comment by darold** [comment]
Yes, look like ALL_SDO_GEOM_METADATA doesn't have the DBA_SDO_GEOM_METADATA corresponding table so I have kept it untouched?

**Comment by darold** [comment]
I miss all_directories, I will fix it.
