### ISSUE TITLE
Windows, copy gives too many open files error

### ISSUE THREAD

**Issue by kazam** [darold/ora2pg#111]
Hi,
When I run ora2pg for a COPY, I get the following error message after sometime:

XXX: Could not create temp file C:\DOCUME~1\user1\LOCALS~1\Temp\tmp_ora2pgZHfxC3
: Too many open files at C:/Perl/site/lib/Ora2Pg.pm line 7785.

Thanks.

**Comment by darold** [comment]
Hi,

What's your version of Ora2Pg? This should have been fixed.

Regards,

**Comment by kazam** [comment]
Hi thanks for the reply.

I had version 14.1. I installed version 15.1 and it gives the same error but at a different line in code. 

Error in tempfile() using template C:\DOCUME~1\user\LOCALS~1\Temp\tmp_ora2pgXXX
XXX: Could not create temp file C:\DOCUME~1\user\LOCALS~1\Temp\tmp_ora2pgSc32pX
: Too many open files at C:/Perl/site/lib/Ora2Pg.pm line 8711.

**Comment by darold** [comment]
Well, I don't have Windows box at my hand right now to check what's going wrong, but as Ora2Pg under this operating system doesn't support multiprocess, the use of temporary files is not required. Please download latest development code from github I have removed the creation of temporary files when using Windows.

Let us know.

Best regards,

**Comment by kazam** [comment]
Thanks Darold.

I got the same error and went on to remove lines 8805 and 8965

	if ($^O =~ /MSWin32|dos/i) {
		push(@tempfiles, [ tempfile('tmp_ora2pgXXXXXX', SUFFIX => '', DIR => $TMP_DIR, UNLINK => 1 ) ]);
	}


if ($^O =~ /MSWin32|dos/i) {
		unlink($tempfiles[0]->[1]);
	}

Will report shortly on how that works out.

**Comment by darold** [comment]
Damn, sorry for this patch. I've inverted the condition on excluding temporary file with Windows OS, latest commit 35bc698 might fix that. Sorry for the inconvenient.

Best regards,

**Comment by kazam** [comment]
Thanks, that did resolve the issue.
