### ISSUE TITLE
Errors when converting Oracle sequences to postgresql

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1110]
Good afternoon Mr. Darold,

I am coming this way to get in touch again because in the conversion of the sequences from Oracle to postegresql I noticed that two errors were occurring, that if possible, I ask that they be seen.

Oracle sequence
------------------------------------------------------------------------------------------------------------------------------
--Create sequence 
create sequence SEQ_CFG_TTK_URGENCIA
minvalue 1
maxvalue 9999999999
start with 1
increment by 1
nocache;
CREATE SEQUENCE "SEQ_CFG_CAUSA_FECHO_FR" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

Postgres result:
-------------------------------------------------------------------------------------------------------------------------
CREATE SEQUENCE seq_cfg_causa_fecho_fr INCREMENT 1 NO MINVALUE NO MAXVALUE **START;**
CREATE SEQUENCE **create** INCREMENT 1 MINVALUE 1 MAXVALUE 9999999999 START 1;

In the sequence SEQ_CFG_TTK_URGENCIA the error occurs because the tool used to export the oracle script generates the comment –Create sequence, which prevents the sequences from being directly converted by ora2pg, as the word create appears before the word INCREMENT, instead of the sequence name, is it possible to correct ?.

In turn, in the second case, the sequence seq_cfg_causa_fecho_fr after being converted to postgres, does the sequence start value disappear after the word START, can you correct it?

I also inform you that I have already installed the latest version of ora2pg, according to the link
https://github.com/darold/ora2pg/tree/86b91d76d53c81ee35731c9853c7f0c9695439a2.

I thank you in advance for any help given.

Best regards,

Rui Pereira.

**Comment by darold** [comment]
Commit 5b640bb might solve this issue.
