### ISSUE TITLE
Data migration issues with Ora2pg

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#1111]
I set the schema name in PG_SCHEMA directive, still it is referring to PUBLIC schema in PostgreSQL. Please help me on this.

**Comment by naveenjul29** [comment]
also when i run the COPY command for the second time, it is not truncating the data in the tables, but i am getting the message on the screen saying that "Truncating the data in the table"

Please help me on how to truncate the data before writing it into the postgresql tables.

**Comment by darold** [comment]
This is in the documentation / configuration file:
```
EXPORT_SCHEMA    1
PG_SCHEMA              <your_pg_schema>
TRUNCATE_TABLE    1
```

**Comment by naveenjul29** [comment]
I already set these values but still it is writing into PUBLIC schema only ..

**Comment by naveenjul29** [comment]
one more thing is, migration speed is very low, Please find the below screenshots and suggest me on increasing the speed.

![Error 1](https://user-images.githubusercontent.com/67134199/111572908-87b99a80-87cf-11eb-822e-2f8376d2b668.PNG)
![Error 2](https://user-images.githubusercontent.com/67134199/111572924-8e481200-87cf-11eb-9e64-a948ff9393e5.PNG)
![Error 3](https://user-images.githubusercontent.com/67134199/111572928-90aa6c00-87cf-11eb-9c31-90ba9f52ef8a.PNG)

I gave the below command for data migration, it is not generated hrpaydata.sql file in /etc/ora2pg/data location, not sure why?
**ora2pg -d -c ora2pg_Migr.conf -J 4 -j 12 -t COPY -o hrpaydata.sql -b /etc/ora2pg/data**

Please help me further.

**Comment by naveenjul29** [comment]
Darold, can you please help me on my request?

**Comment by darold** [comment]
Using more than 4 cpu for `-j` most of the time is useless. Typically with the above settings, Ora2Pg prepend the following command before data import:
```
SET search_path = hr,public;

TRUNCATE TABLE jobs;

COPY jobs (job_id,job_title,min_salary,max_salary) FROM STDIN;
...
```
So it should truncate and import to the table in the right schema.

Please perform an export to file and reports the head of one data file to see if this is the same.
