### ISSUE TITLE
Objects included in the exclude directive which contain the dollar sign are not excluded

### ISSUE THREAD

**Issue by marie-joechahine** [darold/ora2pg#1112]
Hello, not sure if this issue was raised before but I did not encounter it. I have some sequences starting with ISEQ$$_ which are the sequences corresponding the IDENTITY columns in oracle, I am trying to ignore them by adding to the exclude directive but they are not being excluded and end up being migrated, not sure if there is something I can do to avoid that.

**Comment by darold** [comment]
You should try to use `ISEQ\$\$_`

**Comment by darold** [comment]
Commit 2e17011 exclude sequences starting with ISEQ$$_ from the export.
