### ISSUE TITLE
Wrong alias generation in outer join clauses

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1114]
Good afternoon Darold,

When converting view from oracle to postegres, using ora2pg, I verified that the attribute alias to columns used in the outer join clauses is being wrongly assigned, as shown in the example below, is it possible to analyze?
```
CREATE OR REPLACE VIEW gua_dbn0_ua_stock_online AS SELECT s.data_entrada_local AS DATA
  , s.n_serie N_SERIE
  , unm.modulo MOD_MODULO
  , unm.part_number MOD_PART_NUMBER
  , unm.cod_interno MOD_CODIGO_INTERNO
  , unm.dimensao_comprimento MOD_COMPRIMENTO
  , unm.dimensao_altura MOD_ALTURA
  , unm.dimensao_largura MOD_LARGURA
  , unm.peso MOD_PESO
  , unm.garantia_aquisicao MOD_GARANTIA_AQUISICAO
  , unm.garantia_repar MOD_GARANTIA_REPARACAO
  , unm.tempo_max_repar MOD_SLA_REPARACAO
  , forn.id ID_FORNECEDOR
  , forn.designacao FORNECEDOR
  , re.id ID_REPARADOR
  , re.designacao REPARADOR
  , l.id ID_LOCALIZACAO
  , l.localizacao LOCALIZACAO
  , le.id LOCAL_ID_EQUIPA
  , le.designacao LOCAL_EQUIPA
  , l.morada UR_LOCAL_MORADA
  , l.codigo UR_LOCAL_CODIGO
  , tl.id UR_LOCAL_ID_TIPO_LOCAL
  , tl.designacao UR_LOCAL_TIPO_LOCAL
  , e.id ID_ESTADO
  , e.designacao ESTADO
  , s.data_aquisicao DATA_AQUISICAO
  , s.ano_fabrico ANO_FABRICO
  , s.referencia_ua REFERENCIA_UA
  , s.quantidade QUANTIDADE
FROM gua_avaria g
    LEFT OUTER JOIN cfg_reparador re ON (g.id_reparador = re.id) **alias0**
    , gua_stock s
    LEFT OUTER JOIN cfg_localizacao l ON (s.id_localizacao = l.id)
    LEFT OUTER JOIN cfg_equipa le ON (l.id_equipa = le.id)
    LEFT OUTER JOIN cfg_tipo_localizacao tl ON (l.id_tipo = tl.id) **alias3**
		, gua_dd_estado_stock e, tra_dd_fornecedor forn, cfg_forn_un_metrica unm
WHERE (s.id_fornecedor, s.n_serie, s.id_localizacao, s.part_number, s.referencia_ua) IN (SELECT DISTINCT id_fornecedor, n_serie, id_localizacao, part_number, referencia_ua FROM tra_indicadores_ua_stock WHERE DATA > LOCALTIMESTAMP - INTERVAL '1' DAY)
  AND g.referencia = s.referencia_ua
  AND s.id_estado = e.id
  AND e.id_idioma::varchar = pck_tra_hash.f_valor('IDIOMA_SISTEMA')
  AND s.id_fornecedor = forn.id
  AND s.id_fornecedor = unm.id_fornecedor
  AND s.part_number = unm.part_number;
```
I also inform you that all the problems that i had opened up to now are solved, in case you detect something wrong I will inform you again.

Best regards,

Rui Pereira.

**Comment by darold** [comment]
Please post the original Oracle view definition so that I can check what's going wrong.

**Comment by RuiFilipeGoncalvesPereira** [comment]
Good afternoon Darold,

I really forgot to post the original oracle code on the ticket.

As I said when converting view from oracle to postegres, using ora2pg, I verified that the attribute alias to columns used in the outer join clauses is being wrongly assigned, as shown in the example below, is it possible to analyze?

**Original oracle view**
-------------------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE FORCE VIEW GUA_DBN0_UA_STOCK_ONLINE AS
SELECT s.data_entrada_local AS DATA
  , s.n_serie N_SERIE
  , unm.modulo MOD_MODULO
  , unm.part_number MOD_PART_NUMBER
  , unm.cod_interno MOD_CODIGO_INTERNO
  , unm.dimensao_comprimento MOD_COMPRIMENTO
  , unm.dimensao_altura MOD_ALTURA
  , unm.dimensao_largura MOD_LARGURA
  , unm.peso MOD_PESO
  , unm.garantia_aquisicao MOD_GARANTIA_AQUISICAO
  , unm.garantia_repar MOD_GARANTIA_REPARACAO
  , unm.tempo_max_repar MOD_SLA_REPARACAO
  , forn.id ID_FORNECEDOR
  , forn.designacao FORNECEDOR
  , re.id ID_REPARADOR
  , re.designacao REPARADOR
  , l.id ID_LOCALIZACAO
  , l.localizacao LOCALIZACAO
  , le.id LOCAL_ID_EQUIPA
  , le.designacao LOCAL_EQUIPA
  , l.morada UR_LOCAL_MORADA
  , l.codigo UR_LOCAL_CODIGO
  , tl.id UR_LOCAL_ID_TIPO_LOCAL
  , tl.designacao UR_LOCAL_TIPO_LOCAL
  , e.id ID_ESTADO
  , e.designacao ESTADO
  , s.data_aquisicao DATA_AQUISICAO
  , s.ano_fabrico ANO_FABRICO
  , s.referencia_ua REFERENCIA_UA
  , s.quantidade QUANTIDADE
FROM gua_avaria g
    **LEFT OUTER JOIN cfg_reparador re ON (g.id_reparador = re.id)**
    , gua_stock s
    LEFT OUTER JOIN cfg_localizacao l ON (s.id_localizacao = l.id)
    LEFT OUTER JOIN cfg_equipa le ON (l.id_equipa = le.id)
    **LEFT OUTER JOIN cfg_tipo_localizacao tl ON (l.id_tipo = tl.id)**
		, gua_dd_estado_stock e, tra_dd_fornecedor forn, cfg_forn_un_metrica unm
WHERE (s.id_fornecedor, s.n_serie, s.id_localizacao, s.part_number, s.referencia_ua) IN (SELECT DISTINCT id_fornecedor, n_serie, id_localizacao, part_number, referencia_ua FROM tra_indicadores_ua_stock WHERE DATA > SYSDATE - INTERVAL '1' DAY)
  AND g.referencia = s.referencia_ua
  AND s.id_estado = e.id
  AND to_char(e.id_idioma) = pck_tra_hash.f_valor('IDIOMA_SISTEMA')
  AND s.id_fornecedor = forn.id
  AND s.id_fornecedor = unm.id_fornecedor
  AND s.part_number = unm.part_number;

**Postegres view after convert in ora2pg**
-----------------------------------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW gua_dbn0_ua_stock_online AS SELECT s.data_entrada_local AS DATA
  , s.n_serie N_SERIE
  , unm.modulo MOD_MODULO
  , unm.part_number MOD_PART_NUMBER
  , unm.cod_interno MOD_CODIGO_INTERNO
  , unm.dimensao_comprimento MOD_COMPRIMENTO
  , unm.dimensao_altura MOD_ALTURA
  , unm.dimensao_largura MOD_LARGURA
  , unm.peso MOD_PESO
  , unm.garantia_aquisicao MOD_GARANTIA_AQUISICAO
  , unm.garantia_repar MOD_GARANTIA_REPARACAO
  , unm.tempo_max_repar MOD_SLA_REPARACAO
  , forn.id ID_FORNECEDOR
  , forn.designacao FORNECEDOR
  , re.id ID_REPARADOR
  , re.designacao REPARADOR
  , l.id ID_LOCALIZACAO
  , l.localizacao LOCALIZACAO
  , le.id LOCAL_ID_EQUIPA
  , le.designacao LOCAL_EQUIPA
  , l.morada UR_LOCAL_MORADA
  , l.codigo UR_LOCAL_CODIGO
  , tl.id UR_LOCAL_ID_TIPO_LOCAL
  , tl.designacao UR_LOCAL_TIPO_LOCAL
  , e.id ID_ESTADO
  , e.designacao ESTADO
  , s.data_aquisicao DATA_AQUISICAO
  , s.ano_fabrico ANO_FABRICO
  , s.referencia_ua REFERENCIA_UA
  , s.quantidade QUANTIDADE
FROM gua_avaria g
    LEFT OUTER JOIN cfg_reparador re ON (g.id_reparador = re.id) **alias0**
    , gua_stock s
    LEFT OUTER JOIN cfg_localizacao l ON (s.id_localizacao = l.id)
    LEFT OUTER JOIN cfg_equipa le ON (l.id_equipa = le.id)
    LEFT OUTER JOIN cfg_tipo_localizacao tl ON (l.id_tipo = tl.id) **alias3**
		, gua_dd_estado_stock e, tra_dd_fornecedor forn, cfg_forn_un_metrica unm
WHERE (s.id_fornecedor, s.n_serie, s.id_localizacao, s.part_number, s.referencia_ua) IN (SELECT DISTINCT id_fornecedor, n_serie, id_localizacao, part_number, referencia_ua FROM tra_indicadores_ua_stock WHERE DATA > LOCALTIMESTAMP - INTERVAL '1' DAY)
  AND g.referencia = s.referencia_ua
  AND s.id_estado = e.id
  AND e.id_idioma::varchar = pck_tra_hash.f_valor('IDIOMA_SISTEMA')
  AND s.id_fornecedor = forn.id
  AND s.id_fornecedor = unm.id_fornecedor
  AND s.part_number = unm.part_number;

I inform you that this problem also happens when using the syntax (+) in the development of outer joins, if desired, can I send an example of one of these cases as well?

I also inform you that all the problems that i had opened up to now are solved, in case you detect something wrong I will inform you again.

Best regards,

Rui Pereira.

**Comment by darold** [comment]
Commit 065e43a might solve the issue.
