### ISSUE TITLE
Ora2pg Migration

### ISSUE THREAD

**Issue by ujothi-clgx** [darold/ora2pg#1115]
Hi, Am  exploring on ora2pg ,Installed Ora2pg , DBD::Oracle and DBD::Pg
cpanm DBD::Oracle
cpanm DBD::Pg
Post updating the /etc/ora2pg/ora2pg.conf with Oracle DSN and Postgres DSN, I tried below at the root level
 ora2pg --project_base /app/migration/ --init_project test2_project  
Post this in the path /app/migration/test2_project the import_all.sh  and export_schema,sh were generated.
I could execute export_schema,sh
Then its said to execute 
ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg.conf
 That failed as I had updated ora2pg.conf with pg_dsn for direct migration.
I commented the same later
and tried 
/import_all.sh -U postgres -d test -p 5432 -o postgres
but this fails with an error  as 
ERROR: project directory '.' is not valid or is not readable.
Any clue?

**Comment by darold** [comment]
I guess that you are not inside the project directory when you run the command.
