### ISSUE TITLE
Wrong alias generation in outer join clauses, the problem persists

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1116]
Good afternoon,

I come by this means get in touch again because unfortunately after installing commit 065e43a, as suggested, I verified that this error persists in converting viwes from oracle to postegresql using ora2pg, as shown in the example below, is it possible to analyze?.

**Oracle view ddl**
-----------------------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE FORCE VIEW V_TTK_OT AS
  SELECT a.referencia REFERENCIA_OT, a.id_estado ID_ESTADO, e.designacao ESTADO
		, a.id_tipo_ne ID_TIPO_OT, tot.designacao TIPO_OT, a.titulo TITULO
		, a.data_estado DATA_ESTADO, a.data_execucao DATA_EXECUCAO
		, a.data_ne DATA_ABERTURA
		, (CASE WHEN (a.id_estado IN (8, 11)) THEN a.data_estado END) DATA_FECHO
		, (SELECT MAX(data_reg) FROM got_registo WHERE referencia = a.referencia) DATA_ULTIMO_REGISTO
		, (SELECT registo_exec FROM (SELECT referencia, data_reg, registo_exec FROM got_registo ORDER BY data_reg DESC) alias5 WHERE referencia = a.referencia AND ROWNUM < = 1) COMENTARIO_ULTIMO_REGISTO
	FROM got_ot a
LEFT OUTER JOIN got_dd_estado e ON (a.id_estado = e.id AND a.id_idioma = e.id_idioma)
**LEFT OUTER JOIN cfg_tipo_ot tot ON (a.id_tipo_ne = tot.id);**

**Postegre view  ddl**
----------------------------------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW v_ttk_ot AS SELECT a.referencia REFERENCIA_OT, a.id_estado ID_ESTADO, e.designacao ESTADO
		, a.id_tipo_ne ID_TIPO_OT, tot.designacao TIPO_OT, a.titulo TITULO
		, a.data_estado DATA_ESTADO, a.data_execucao DATA_EXECUCAO
		, a.data_ne DATA_ABERTURA
		, (CASE WHEN(a.id_estado IN (8, 11)) THEN a.data_estado END) DATA_FECHO
		, (SELECT MAX(data_reg) FROM got_registo WHERE referencia = a.referencia) DATA_ULTIMO_REGISTO
		, (SELECT registo_exec FROM (SELECT referencia, data_reg, registo_exec FROM got_registo ORDER BY data_reg DESC) alias5 WHERE referencia = a.referencia  LIMIT 1) COMENTARIO_ULTIMO_REGISTO
	FROM got_ot a
LEFT OUTER JOIN got_dd_estado e ON (a.id_estado = e.id AND a.id_idioma = e.id_idioma)
**LEFT OUTER JOIN cfg_tipo_ot tot ON(a.id_tipo_ne = tot.id) alias8;**

I also inform you that this problem also occurs when on the oracle side the syntax (+) is used for outer joins, if necessary I post an example of these as well?

I also inform you that I installed the latest version of ora2pg from the link 
https://github.com/darold/ora2pg/tree/065e43a1f2d9a91ff498b7a35f3d381a0479ba68

Best regards,

Rui Pereira.

**Comment by RuiFilipeGoncalvesPereira** [comment]
Good afternoon Darold,

I hope everything is fine with you, I would like to know if possible if there is any solution to the problem described above ?, I remember that when converting the outer joins from Oracle to Postegres, they are being created alias in the wrong way.

Best regards,

Rui Pereira.

**Comment by darold** [comment]
I have seen that there is still wrong aliases appended, I have too much work to fix it now but I don't forget it :-)

**Comment by darold** [comment]
Last commit b75f16c might fix this remaining incorrect alias.
