### ISSUE TITLE
Encountering issue while migrating BLOB column

### ISSUE THREAD

**Issue by kirandba-hub** [darold/ora2pg#1117]
Hi Darold,

i am migrating the BLOB column in a table,it encounters below error.

Wide character in print at /usr/lib64/perl5/IO/Handle.pm line 417.LINK_ATTACHMENT (13012 recs/sec)
Wide character in print at /usr/lib64/perl5/IO/Handle.pm line 417.LINK_ATTACHMENT (13132 recs/sec)
Wide character in print at /usr/lib64/perl5/IO/Handle.pm line 417.LINK_ATTACHMENT (13095 recs/sec)
Wide character in print at /usr/lib64/perl5/IO/Handle.pm line 417.LINK_ATTACHMENT (13058 recs/sec)
Wide character in print at /usr/lib64/perl5/IO/Handle.pm line 417.LINK_ATTACHMENT (13023 recs/sec)
Wide character in print at /usr/lib64/perl5/IO/Handle.pm line 417.LINK_ATTACHMENT (12988 recs/sec)

Can you please help to get rid of this error.

Thanks,
Kiran.

**Comment by RonJohn2** [comment]
What ora2pg version?
What blob configuration variables are used?

**Comment by darold** [comment]
The "Wide character" error is complicated to debug, use direct import to PostgreSQL you should not have this problem.
