### ISSUE TITLE
Check constraint clause containing the word 'PROCEDURE' is changed to 'FUNCTION'

### ISSUE THREAD

**Issue by marie-joechahine** [darold/ora2pg#1118]
I have encountered a strange behavior where I have a check constraint with the following clause:

REQUEST_NATURE IN ('EMERGENCY', 'NON-EMERGENCY', 'SPECIAL PROCEDURE')

When it is being exported to the CONSTRAINTS_output.sql, it is being converted to:

REQUEST_NATURE IN ('EMERGENCY', 'NON-EMERGENCY', 'SPECIAL FUNCTION')

The word PROCEDURE is being change to FUNCTION for no reason, any idea why this might be happening?

**Comment by darold** [comment]
Fixed in commit 7550303.
