### ISSUE TITLE
Primary keys added for columns that shouldn't, because they are used for partitions on Oracle

### ISSUE THREAD

**Issue by marie-joechahine** [darold/ora2pg#1119]
I have disabled partition in the config file and imported the data successfully, however when I am trying to import the constraints to the PostgreSQL database using the CONSTRAINTS_output.sql file, some primary keys are added which are not primary keys in Oracle but used for partitioning. Not sure why they are being added as primary keys.

**Comment by darold** [comment]
Do you have and example of the Ora2Pg output and the real PK defined in Oracle?

**Comment by marie-joechahine** [comment]
This is part of the SQL on Oracle:

```
  CREATE TABLE "CMS"."BP_PRICELIST_DETAIL" 
   (	"ID" NUMBER(10,0) DEFAULT "CMS"."SEQ_BP_PRICELIST_DETAIL"."NEXTVAL" NOT NULL ENABLE, 
	"BP_PRICELIST_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CODE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"SERVICE_ID" NUMBER(10,0), 
	"CURRENCY_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"COST_GROSS" NUMBER(10,2) DEFAULT (0) NOT NULL ENABLE, 
	"DISCOUNT_PCT" NUMBER(5,2) DEFAULT (0) NOT NULL ENABLE, 
	"COST_NET" NUMBER(10,2) DEFAULT (0) NOT NULL ENABLE, 
	"SOURCE_ID" VARCHAR2(400 BYTE), 
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(100 BYTE), 
	"FLAG" VARCHAR2(1 BYTE), 
	"VAT_PCT" NUMBER(5,2) DEFAULT (0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_BP_PRICELIST_DETAIL" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_CMS"  ENABLE, 
	 CONSTRAINT "FK_BP_PLST_DETAIL_CURRENCY" FOREIGN KEY ("CURRENCY_ID")
	  REFERENCES "CMS"."CURRENCY" ("ID") ENABLE, 
	 CONSTRAINT "FK_BP_PLST_DETAIL_SERVICE" FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "CMS"."SERVICE" ("ID") ENABLE, 
	 CONSTRAINT "FK_BP_PLST_DETAIL_BP_PRICE" FOREIGN KEY ("BP_PRICELIST_ID")
	  REFERENCES "CMS"."BP_PRICELIST" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_CMS" 
  PARTITION BY LIST ("FLAG")
```

As you can see the ID is set as a primary key, while FLAG is using in the end in PARTITION BY LIST("FLAG").

Ora2pg generated the following alter statement in the CONSTRAINTS_output.sql:

`ALTER TABLE bp_pricelist_detail ADD PRIMARY KEY (id,flag);
`

I am not sure if there is something I am not understanding, no idea why flag is being included here as a primary key.

**Comment by darold** [comment]
Yes, this is a recent fix. Actually the partition key must be part of the primary key in PostgreSQL, so this is expected.

**Comment by marie-joechahine** [comment]
Hello @darold, I forgot to mention that in my case I have disabled partition in the config file, and this causing the constraints to fail when added, I guess if partition is disabled, these should not be added? Sorry for not replying earlier.
