### ISSUE TITLE
ORA-12733: expression régulière trop longue

### ISSUE THREAD

**Issue by lpenet** [darold/ora2pg#112]
I recently tried to upgrade from ora2pg 13 to 15.

I was blocked when the following query was executed.

I use ora2pg with explicit selection of many tables.

It seems like REGEXP_LIKE find their list too long. :-)

A sample query :

SELECT A.TABLE_NAME,A.COMMENTS,A.TABLE_TYPE FROM ALL_TAB_COMMENTS A, ALL_OBJECTS O WHERE A.OWNER=O.OWNER and A.TABLE_NAME=O.OBJECT_NAME and O.OBJECT_TYPE='TABLE' AND A.OWNER='SENATEURS'  AND (A.OWNER, A.TABLE_NAME) NOT IN (SELECT OWNER, MVIEW_NAME FROM ALL_MVIEWS UNION ALL SELECT LOG_OWNER, LOG_TABLE FROM ALL_MVIEW_LOGS) AND (REGEXP_LIKE(A.TABLE_NAME,'^AUTORISATIONS,AUTORISATION_PROFIL,REQUETES_PROFIL,PROFIL_APPLICATIF,VALIDATION_PROFIL,VALIDATION_DEFVIEW_PROFIL,ETADEBMAN,ETAFINMAN,ETADEBMAN3R,ETAFINMAN3R,ETADEBMAN4R,ETAFINMAN4R,SENSIM,SEN,SENNOM,SENURL,MININD,GVT,TYPMIN,TITMIN,TEMVAL,ETASEN,PARPOL,TYPPARPOL,TENPOL,ELE,TYPURL,TERRIT,CATTERRIT,ELUCAN,ELUDEP,ELUDIV,ELUEUR,ELUREG,ELUSEN,ELUSEN4R,ELUSEN3R,ELUSEN2E,ELUTER,ELUTIT,ELUVIL,ELUMET,MET,TITELE,TYPMAN,TURELU,DPT,DPTELE,LISDPTELE,RESULTAT,RESLIS,VERRES,PARTICIPA,VALIDATION,ELE,TYPELE,QUA,CANDID,TYPCANDID,FONCANDID,ETARPM,CIRDEP,NATION,REG,ASSTER,UPLOADED_FILE,UPLOADED_FILE_TYPE,DPTELE_FILES,VERCAND,DPTELE_PROCESSING,DPTELE_PROCESSING_TYPE,CATPRO,CATPRO2E,SEC,CSP,CSPFAM,FONGRPPOL,GRPPOL,GRPPOL4R,LIBGRPPOL,MEMGRPPOL,FONMEMGRPPOL,COM,LIBCOM,FONCOM,MEMCOM,FONMEMCOM,DELEGA,LIBDELEGA,FONDELEGA,MEMDELEGA,FONMEMDELEGA,DESIGN,DESIGNORG,DESIGNOEP,SENBUR,SENBUR3R,SENBUR4R,BUR,BUR3R,BUR4R,TYPAPPPOL,ORG,LIBORG,FONORG,MEMORG,FONMEMORG,TYPORG,GRPSENAMI,GRPSENAMIADH,GRPSENAMIUNADH,GRPSENAMIADHREQ,GRPSENAMIADHREQETA,NATIONGRPSEN,LIBGRPSEN,MEMGRPSEN,FONMEMGRPSEN,FONGRPSEN,ORGEXT,MEMEXTPAR,PCS,DIV,ZONGEO,PLAIND,TYPGRPSEN,ETAPRR,STAJUR,ACTPRO,PCS8,PCS24,PCS42,CON,PER,ROL,PERROL,CAD,SRV,DISCOU,SYSEVT,ORGTHE,ETAPRR,RAP_THE,AUTGRPSEN,SECEXE,TYPPOICON,POICON,ADRESSE,TYPTEL,TELEPHONE,MEL,TYPVOI,TYPBISTER,MODDES,MIS,MISSEN,MISMIN,MISETAFIN,TITNOB$')) AND (  NOT REGEXP_LIKE(A.TABLE_NAME,'^USLOG\$_.*$') AND  NOT REGEXP_LIKE(A.TABLE_NAME,'^MLOG\$_.*$') AND  NOT REGEXP_LIKE(A.TABLE_NAME,'^RUPD\$_.*$') AND  NOT REGEXP_LIKE(A.TABLE_NAME,'^MDXT_.*$') AND  NOT REGEXP_LIKE(A.TABLE_NAME,'^MDRT_.*$') AND  NOT REGEXP_LIKE(A.TABLE_NAME,'^MDRS_.*$') AND  NOT REGEXP_LIKE(A.TABLE_NAME,'^DR\$.*$') AND  NOT REGEXP_LIKE(A.TABLE_NAME,'^CLI_SWP\$.*$') AND  NOT REGEXP_LIKE(A.TABLE_NAME,'^LOGMNR\$.*$') AND  NOT REGEXP_LIKE(A.TABLE_NAME,'^REPCAT\$.*$') AND  NOT REGEXP_LIKE(A.TABLE_NAME,'^JAVA\$.*$') AND  NOT REGEXP_LIKE(A.TABLE_NAME,'^AQ\$.*$'))

Thanks in advance.

**Comment by darold** [comment]
The problem may comes from the value of the ALLOW and EXCLUDE directives, they have changed.

What are those values?

**Comment by lpenet** [comment]
I do not use ALLOW or EXCLUDE. I use -a to indicate which tables to export.

So : 

-a autorisations,autorisation_profil,requetes_profil,profil_applicatif,validation_profil,validation_defview_profil,etadebman,etafinman,etadebman3r,etafinman3r,etadebman4r,etafinman4r,sensim,sen,sennom,senurl,minind,gvt,typmin,titmin,temval,etasen,parpol,typparpol,tenpol,ele,typurl,territ,catterrit,elucan,eludep,eludiv,elueur,elureg,elusen,elusen4r,elusen3r,elusen2e,eluter,elutit,eluvil,elumet,met,titele,typman,turelu,dpt,dptele,lisdptele,resultat,reslis,verres,participa,validation,ele,typele,qua,candid,typcandid,foncandid,etarpm,cirdep,nation,reg,asster,uploaded_file,uploaded_file_type,dptele_files,vercand,dptele_processing,dptele_processing_type,catpro,catpro2e,sec,csp,cspfam,fongrppol,grppol,grppol4r,libgrppol,memgrppol,fonmemgrppol,com,libcom,foncom,memcom,fonmemcom,delega,libdelega,fondelega,memdelega,fonmemdelega,design,designorg,designoep,senbur,senbur3r,senbur4r,bur,bur3r,bur4r,typapppol,org,liborg,fonorg,memorg,fonmemorg,typorg,grpsenami,grpsenamiadh,grpsenamiunadh,grpsenamiadhreq,grpsenamiadhreqeta,nationgrpsen,libgrpsen,memgrpsen,fonmemgrpsen,fongrpsen,orgext,memextpar,pcs,div,zongeo,plaind,typgrpsen,etaprr,stajur,actpro,pcs8,pcs24,pcs42,con,per,rol,perrol,cad,srv,discou,sysevt,orgthe,etaprr,rap_the,autgrpsen,secexe,typpoicon,poicon,adresse,typtel,telephone,mel,typvoi,typbister,moddes,mis,missen,mismin,misetafin,titnob

**Comment by darold** [comment]
ok, you need to replace the coma separator with a space. Here is the new syntax for the -a option:

    -a "TABLE[regex1 regex2 ...];VIEW[regex1 regex2 ...];TABLENAME1 TABLENAME2 ..."

In you case you migth use the following:

-a "autorisations autorisation_profil requetes_profil profil_applicatif validation_profil validation_defview_profil etadebman etafinman etadebman3r etafinman3r etadebman4r etafinman4r sensim sen sennom senurl minind gvt typmin titmin temval etasen parpol typparpol tenpol ele typurl territ catterrit elucan eludep eludiv elueur elureg elusen elusen4r elusen3r elusen2e eluter elutit eluvil elumet met titele typman turelu dpt dptele lisdptele resultat reslis verres participa validation ele typele qua candid typcandid foncandid etarpm cirdep nation reg asster uploaded_file uploaded_file_type dptele_files vercand dptele_processing dptele_processing_type catpro catpro2e sec csp cspfam fongrppol grppol grppol4r libgrppol memgrppol fonmemgrppol com libcom foncom memcom fonmemcom delega libdelega fondelega memdelega fonmemdelega design designorg designoep senbur senbur3r senbur4r bur bur3r bur4r typapppol org liborg fonorg memorg fonmemorg typorg grpsenami grpsenamiadh grpsenamiunadh grpsenamiadhreq grpsenamiadhreqeta nationgrpsen libgrpsen memgrpsen fonmemgrpsen fongrpsen orgext memextpar pcs div zongeo plaind typgrpsen etaprr stajur actpro pcs8 pcs24 pcs42 con per rol perrol cad srv discou sysevt orgthe etaprr rap_the autgrpsen secexe typpoicon poicon adresse typtel telephone mel typvoi typbister moddes mis missen mismin misetafin titnob"
