### ISSUE TITLE
Problems with data migration with the constraints active when the tables are placed in the correct order.

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1120]
Good afternoon Darold,

On ora2pg I had to migrate the data from two tables tra_dd_particularidade (parent table) and cfg_origem (daughter table) from oracle to postegresql with the active constraints (DROP_FKEY 0), but the following error occurred:

[========================>] 2/2 tables (100.0%) end of scanning.
DBD::Pg::db pg_putcopyend failed: ERROR:  insert or update on table "cfg_origem" violates foreign key constraint "cfg_origem_cfg_particula_fk"
DETAIL:  Key (id_particularidade)=(330) is not present in table "tra_dd_particularidade". at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 15688.
FATAL: ERROR:  insert or update on table "cfg_origem" violates foreign key constraint "cfg_origem_cfg_particula_fk"
DETAIL:  Key (id_particularidade)=(330) is not present in table "tra_dd_particularidade".
Aborting export... 

Table order:
ALLOW  tra_dd_particularidade  
ALLOW cfg_origem

Primary key:
ALTER TABLE TRA_DD_PARTICULARIDADE ADD CONSTRAINT TRA_DD_PARTICULARIDADE_PK PRIMARY KEY (ID) USING INDEX TABLESPACE  SIGO_I   ;

Foreign key:
ALTER TABLE CFG_ORIGEM ADD CONSTRAINT CFG_ORIGEM_CFG_PARTICULA_FK FOREIGN KEY (ID_PARTICULARIDADE) REFERENCES TRA_DD_PARTICULARIDADE (ID);

In ora2pg it is not possible to migrate information from tables with active constraints even placing them with the correct hieratic order ?,

I tried to do an experiment changing the order of the tables, as shown below, but the same error occurred, you can help to understand this problem?.

Table order:
ALLOW cfg_origem
ALLOW  tra_dd_particularidade  

I thank you in advance for your help.

Best regards,

Rui Pereira.

**Comment by darold** [comment]
If you don't want to use DROP_FKEYS (they will be restored at end of the data import) you can try DEFER_FKEY. THis works only if the constraints are deferable.
