### ISSUE TITLE
How do we insert table partition by partition?

### ISSUE THREAD

**Issue by sesref** [darold/ora2pg#1121]
Hi, we have a partitioned table with partition compression and 25 969 863 967 rows. 
Each partition contains approximately 160 000 000 rows and we want to insert table partition by partition.
When we run the command 
ora2pg -c ora2pg.conf -t INSERT -a 'TABLE[table_name]' it works but how we insert only specific partition?
We tried 
ora2pg -c ora2pg.conf -t INSERT -a 'TABLE[table_name]' 'PARTITION[partition_name]' --gets full db data
ora2pg -c ora2pg.conf -t INSERT -a  'PARTITION[partition_name]' --returns 0
ora2pg -c ora2pg.conf -t INSERT -a 'TABLE[partition_name]'  --returns 0
ora2pg -p -c ora2pg.conf -t INSERT  -a 'TABLE[table_name]' 'TABLE[partition_name]'  and ALLOW table_name --gets full table data
etc.
Is this possible in any way ?

**Comment by darold** [comment]
Have you tried to add a WHERE clause in ora2pg.conf that use the partition key? Something like:
```
ALLOW     table_name
WHERE    table_name[partition_key = value]
```
or any predicate that match the partitioning keys.

**Comment by sesref** [comment]
We have tried something like that but not the same :) It did work thank you.

**Comment by atlterry** [comment]
Gilles; keying off this thread ... my single partition of many partitions has over 400+ million records and I filled up my disk ;-) after 111 million records!!!

Is there a way to create multiple files for the data?
If I understand this right using 
FILE_PER_TABLE > 0 will still create 1 file per table 
OR
will this create multiple files per partition? in conjunction with
ALLOW    table_name 
WHERE    table_name[partition_key = value]

Could you recommend a strategy for very large data migrations?

Thanks

**Comment by darold** [comment]
Having one single big file or several smaller files will not solve your disk space issue, however  FILE_PER_TABLE shall be enabled. If you don't have enough space disk you can force ora2p to compress the output, see OUTPUT in configuration file or in the documentation. But best is to proceed with direct import to PostgreSQL.
