### ISSUE TITLE
All views scanned, when only some were specified

### ISSUE THREAD

**Issue by RonJohn2** [darold/ora2pg#1122]
Ora2Pg v21.0

My config file listed 28 views to export.  However, ora2pg spent seven minutes scanning all 1419 views, and then spent another 2.5 minutes rescanning the 28 views I want to export.  That seems a bit wasteful.  It might be a useful enhancement to only scan the relevant views (and whatever views they depend on).

```
PARALLEL_TABLES 4
NO_VIEW_ORDERING    1
EXCLUDE *
VIEW_AS_TABLE view_1 view_2 ... view_28

```

**Comment by darold** [comment]
What is your ora2pg command? I guess you are exporting data from views not the view definition?

**Comment by RonJohn2** [comment]
Correct about the COPY.
```
$ grep COPY ora2pg/ora2pg_common.conf    
TYPE            COPY

/usr/local/bin/ora2pg -c ora2pg/ora2pg_${CONFIG_ID}.conf \
        --debug \
        --basedir=${OUTDIR} \
        --temp_dir=${ORA2PG_TEMP} \
        --source=${ORACLE_DSN} 
```

**Comment by darold** [comment]
Ok, last commit b55d7fd fixes the issue with the NO_VIEW_ORDERING that was not taken in account. But for what you want to do here is what I will do:
```
PARALLEL_TABLES 4
NO_VIEW_ORDERING    1
ALLOW        TABLE[FAKE_TABLE];VIEW[view1 view2 ... view28]
EXCLUDE 
VIEW_AS_TABLE view_1 view_2 ... view_28
```

The `TABLE[FAKE_TABLE]` is to avoid scanning all tables, it will filter on a table that do not exists.

**Comment by RonJohn2** [comment]
Will that work in 21.0, or only with the latest patch?
Or would disabling NO_VIEW_ORDERING be just as effective?

**Comment by darold** [comment]
Should works with 21.0 the only thing is that extracting views will be slow due to NO_VIEW_ORDERING not effective.

**Comment by RonJohn2** [comment]
Out of curiosity, why do the view names need to be listed twice (in the ALLOW and VIEW_AS_TABLE lists)?

**Comment by darold** [comment]
Because otherwise they will not be taken in account for data export. The ALLOW directive is used to specify the objects you want to filter, in the example above `TABLE[FAKE_TABLE]` is used for export type TABLE and COPY whereas `VIEW[view1 view2 ... view28]` is only used for export type VIEW unless you specify VIEW_AS_TABLE.

**Comment by darold** [comment]
And thank you for the donation @RonJohn2 it is must appreciated. I want to drop you an answer in Paypal response but it ask me a double authentication and my mobile phone is broken, so I thank you here :-)
