### ISSUE TITLE
FATAL:ORA-20000 ORA-06512: at "SYS.DBMS_UTILITY", line 413

### ISSUE THREAD

**Issue by atlterry** [darold/ora2pg#1124]
After upgrading to ora2pg 21.0 I get these errors using ./export_schema.sh

![2021-03-31_15-10-50](https://user-images.githubusercontent.com/19489158/113198615-20223700-9234-11eb-9bd2-ce3773302423.jpg)

**Comment by darold** [comment]
Strange, I never seen this error, which version of Oracle are you using? And what is the value of ora2pg.conf SCHEMA directive, is it empty?

To avoid this problem I think you can disable COMPILE_SCHEMA in ora2pg.conf.

**Comment by atlterry** [comment]
The schema is set and I set COMPILE_SCHEMA 0 and I don't see the above error but I cannot connect now.
The oracle version is 11.2.0
The instance is on another VM
Since there are several VM's my tnsnames entry is EMS134 with a service name = EMS
And tnsping shows a successful connection 

Here's what I get... so now it's a question of how to get the DBI connect string right...
![image](https://user-images.githubusercontent.com/19489158/113205052-d50c2200-923b-11eb-8430-ba2dd9018b2b.png)

![image](https://user-images.githubusercontent.com/19489158/113204906-a1c99300-923b-11eb-8f8b-c22b49d85647.png)

**Comment by darold** [comment]
I have removed the private information from your post, I'm a bit paranoiac ;-) To fix the connection you migth try to use sqlplus to connect to your database then once it is successful you can use the connection information with Ora2Pg.

**Comment by atlterry** [comment]
Thanks - I thought I had redacted the key info; can't blame you for being paranoia. I'm in the process of exporting another schema to test - it has 400+ millions rows ;-) and 15% done so it will take a while. 

Will keep you posted.

**Comment by lrecknagel** [comment]
Maybe not related but want to share my finding here.
Had the same error (with `COMPILE_SCHEMA 1`) and setting:

```
NLS_LANG          <YOUR_LANG>
NLS_NCHAR       <YOUR_CHARSET>
```

fixed it for me.
