### ISSUE TITLE
Does Ora2pg converts NLSSORT to the equivalent Postegres Collate?

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1125]
Good afternoon Darold,

I hope you find yourself well,

I hereby come into contact with the sense of asking you, if you can answer me as soon as possible, if ora2pg already fully supports the conversion from NLSSORT to COLLATE?, or if that functionality is still being implemented?, I ask this because when converting with a View with nlssort from oracle to PG the conversion was not done in full as shown below:

Oracle view:
---------------------------------------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE FORCE VIEW V_AVARIAS_TIPOS_SERVICO AS
  SELECT t.ttk, t.agr
FROM
(
	SELECT ttk
		, r
		, agrega_strings(tipo) OVER (PARTITION BY ttk ORDER BY **NLSSORT(tipo,'NLS_SORT=WEST_EUROPEAN')) agr**
	FROM (
		SELECT ats1.referencia ttk
			, ts1.designacao tipo
			, ROW_NUMBER () OVER (PARTITION BY ats1.referencia ORDER BY **NLSSORT(ts1.designacao,'NLS_SORT=WEST_EUROPEAN')) r**
		FROM gtt_avaria a
					LEFT OUTER JOIN gtt_avaria_tipo_servico ats1 ON (a.referencia = ats1.referencia)
					LEFT OUTER JOIN cfg_tipo_servico ts1 ON (ats1.id_tipo_servico = ts1.id)
		WHERE a.data_avaria >= TO_DATE('01-01-2010','DD-MM-YYYY')
	) b
) t
,(
	SELECT ttk, MAX(r) r
	FROM (
		SELECT ats1.referencia ttk
			, ROW_NUMBER () OVER (PARTITION BY ats1.referencia ORDER BY **NLSSORT(tipo,'NLS_SORT=WEST_EUROPEAN'))r**
		FROM gtt_avaria a
		     LEFT OUTER JOIN gtt_avaria_tipo_servico ats1 ON (a.referencia = ats1.referencia)
			 LEFT OUTER JOIN cfg_tipo_servico ts1 ON (ats1.id_tipo_servico = ts1.id)
		WHERE a.data_avaria >= TO_DATE('01-01-2010','DD-MM-YYYY')
	)b1 GROUP BY ttk
) t1
WHERE t.ttk = t1.ttk
	AND t.r = t1.r
UNION ALL
SELECT ttk, agr FROM tra_avarias_tipos_servico;

Postegres Result:
--------------------------------------------------------------------------------------------------------------------------------------------

-- Generated by Ora2Pg, the Oracle database Schema converter, version 21.0
-- Copyright 2000-2020 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.112.84.59;sid=ptpsigo;port=1521

SET client_encoding TO 'UTF8';

CREATE OR REPLACE VIEW v_avarias_tipos_servico AS SELECT t.ttk, t.agr
FROM (
	SELECT ttk
		, r
		, agrega_strings(tipo) OVER (PARTITION BY ttk ORDER BY tipo COLLATE "WEST_EUROPEAN") agr
	FROM (
		SELECT ats1.referencia ttk
			, ts1.designacao tipo
			, ROW_NUMBER() OVER (PARTITION BY ats1.referencia ORDER BY **NLSSORT(ts1.designacao,'NLS_SORT=WEST_EUROPEAN')) r**
		FROM gtt_avaria a
					LEFT OUTER JOIN gtt_avaria_tipo_servico ats1 ON (a.referencia = ats1.referencia)
					LEFT OUTER JOIN cfg_tipo_servico ts1 ON(ats1.id_tipo_servico = ts1.id) alias6
		WHERE a.data_avaria >= TO_DATE('01-01-2010','DD-MM-YYYY')
	) b
) t
,(
	SELECT ttk, MAX(r) r
	FROM (
		SELECT ats1.referencia ttk
			, ROW_NUMBER() OVER (PARTITION BY ats1.referencia ORDER BY **NLSSORT(tipo,'NLS_SORT=WEST_EUROPEAN')**) r
		FROM gtt_avaria a
		     LEFT OUTER JOIN gtt_avaria_tipo_servico ats1 ON (a.referencia = ats1.referencia)
			 LEFT OUTER JOIN cfg_tipo_servico ts1 ON(ats1.id_tipo_servico = ts1.id) alias15
		WHERE a.data_avaria >= TO_DATE('01-01-2010','DD-MM-YYYY')
	)b1 GROUP BY ttk
) t1
WHERE t.ttk = t1.ttk
	AND t.r = t1.r
UNION ALL
SELECT ttk, agr FROM tra_avarias_tipos_servico;

I thank you in advance for the answer given,
Best regards,
Rui Pereira.

**Comment by darold** [comment]
Yes, it should translate NLSSORT. I'll look what's going wrong.

**Comment by darold** [comment]
I see only the first one is replaced, this should be trivial to fix.

**Comment by darold** [comment]
Commit 4b1fa10 fixes this issue.
