### ISSUE TITLE
ERROR:  geometry requires more points

### ISSUE THREAD

**Issue by sesref** [darold/ora2pg#1128]
Hi, I have an error :

DBD::Pg::db do failed: ERROR:  geometry requires more points
HINT:  "POLYGON ((29.0070741 41.0520015))" <-- parse error at position 35 within geometry at /usr/local/share/perl5/Ora2Pg.pm line 15674.
[2021-04-03 13:16:22] FATAL: ERROR:  geometry requires more points
HINT:  "POLYGON ((29.0070741 41.0520015))" <-- parse error at position 35 within geometry
DBI::db=HASH(0x37a9ef0)->disconnect invalidates 1 active statement handle (either destroy statement handles or call finish on them before disconnecting) at /usr/local/share/perl5/Ora2Pg.pm line 14751.
Aborting export...

I am not sure about this error. How can I fix this?
thank you for your help.

**Comment by darold** [comment]
Looks like you have invalid geometries in your Oracle database. You can enable LOG_ON_ERROR configuration directive to continue the import but log the failing lines, see documentation or configuration file for explanation.

**Comment by darold** [comment]
You should reduce DATA_LIMIT to reduce the number of rows in a failing block. Once you have check the failing geometry check the geometry in Oracle to see if this is an Ora2Pg problem. Also what is your value of  GEOMETRY_EXTRACT_TYPE in ora2pg.conf?

**Comment by sesref** [comment]
GEOMETRY_EXTRACT_TYPE INTERNAL and when we analyzed the logfile for this table, we noticed that there are two geometry type point and polygon that has an error. 
Column type in the table  sql is 
geoloc geometry(GEOMETRY,4326) and I think it's true for the tables that have mixed type.
There is no problem with tables that have only polygon type.
We have tried recreate table with column geoloc geometry(POLYGON,4326) and again we could not insert the row that gives an error.

**Comment by darold** [comment]
I see, actually when Ora2Pg found an Oracle SDO_GEOMETRY column it retrieve the first 50000 lines to see if a specific geometry type can be used. Looks like you only have polygons in this sample this is why the geometry constraint to POLYGON have been added. The right action is to remove the geometry constraint as you have done unless the points should not be a valid data for this column.

**Comment by sesref** [comment]
Actually, if a table have only one geometry type including polygons there is no problem for inserting.
But,  if a table have mixed geometry type (in this example, points and polygon) we got an error like this
HINT: "POLYGON ((29.0070741 41.0520015))" <-- parse error at position 35 within geometry at /usr/local/share/perl5/Ora2Pg.pm line 15674.

**Comment by sesref** [comment]
Actually, if a table has only one geometry type including polygons there is no problem for inserting.
But, if a table has mixed geometry type (in this example, points and polygon) we got an error like this
HINT: "POLYGON ((29.0070741 41.0520015))" <-- parse error at position 35 within geometry at /usr/local/share/perl5/Ora2Pg.pm line 15674.
and also if a table have only one type for example polygon then column type is (POLYGON,4326)(there is no problem with this) but it has mixed type then column type is (GEOMETRY,4326).

**Comment by darold** [comment]
Yes this is what I explain above, Ora2Pg are found that there is only polygon geometry in the column so it have declared it with a polygon constraint. You should declare the column as you've done: `geoloc geometry(GEOMETRY,4326)`.

You can instruct Ora2Pg to retrieve more than 50000 sample rows, see AUTODETECT_SPATIAL_TYPE configuration directive.
