### ISSUE TITLE
FATAL: Unknown export type: TRIGGER

### ISSUE THREAD

**Issue by atlterry** [darold/ora2pg#1129]
Hello Gilles; I'm getting this error even though the Export Section of config is defined...
TYPE TABLE PACKAGE COPY VIEW GRANT SEQUENCE TRIGGER FUNCTION PROCEDURE TABLESPACE TYPE PARTITION

The error I get is 
`Running: ora2pg -t TRIGGER -o trigger.sql -b ./sources/triggers -c ./config/ora2pg.conf
FATAL: Unknown export type: TRIGGER. Type supported: QUERY,LOAD,SEQUENCE,TABLE,PACKAGE,VIEW,GRANTTRIGGER,FUNCTION,PROCEDURE,TABLESPACE,PARTITION,TYPE,MVIEW,DBLINK,SYNONYM,DIRECTORY,SHOW_VERSION,SHOW_REPORT,SHOW_SCHEMA,SHOW_TABLE,SHOW_COLUMN,SHOW_ENCODING,INSERT,COPY,KETTLE,FDW,TEST,TEST_VIEW
`
Looks like TRIGGER is not found at runtime?

Thanks

**Comment by darold** [comment]
This was a typo introduced in the commit you've downloaded, it has been fixed. You can just edit script export_schema.sh and replace `GRANTTRIGGER` by `GRANT TRIGGER` at the beginning of the file.

**Comment by atlterry** [comment]
This is strange - I updated the script...
![image](https://user-images.githubusercontent.com/19489158/113600232-b035f700-960d-11eb-9e55-1e1c391f818e.png)

... and now GRANT & TRIGGER throw the same error
![image](https://user-images.githubusercontent.com/19489158/113600304-cc399880-960d-11eb-9f05-c3b34e72bcaf.png)

![image](https://user-images.githubusercontent.com/19489158/113600360-e5dae000-960d-11eb-8cb5-b5868950d69d.png)

**Comment by darold** [comment]
I fix it with commit 9b0f4a7,actually you must edit /usr/local/bin/ora2pg around line 90 with variable `@SCHEMA_ARRAY` it is used to generated the import_schema.sh script but also after to validate the export type used.

**Comment by atlterry** [comment]
That worked but when I inspect the folders... 
- procedure indicate 4 but only 3 created
- trigger folder is labeled granttriggers and is empty

![image](https://user-images.githubusercontent.com/19489158/113605506-c09da000-9614-11eb-8808-b7676a994504.png)

I updated  /usr/local/bin/ora2pg as explained above; doe the fix address the output?

Thanks

**Comment by darold** [comment]
the granttrigger directory have been created by during the call of ora2pg with `--init_project`, you should backup your config/ora2pg.conf and recreate the full project. You should also use the latest release 21.1 published last week there is some other interesting fixes.

**Comment by atlterry** [comment]
Got it... updated and conversion in progress. Will let you know. Thanks
