### ISSUE TITLE
Connect with load balancing

### ISSUE THREAD

**Issue by baul87** [darold/ora2pg#113]
Hello everyone,

I'm trying to connect to a server with load balancing, I tried to connect to a single server and it works.

How can I change the line DBI->connect?

I tried also to get the logs, ora2pg creates the log fine but it doesn't write on it.

I'm using win7.

Thanks for helping

**Comment by darold** [comment]
Hello,

I don't understand what you are trying to do. If you want to migrate your Oracle database, connecting to a single server migth be enough, no?

Regards,

**Comment by baul87** [comment]
Hello,

I would like to migrate from an Oracle RAC database to a Postgres database. I can't connect to the Oracle RAC. Currently I define the following parameters:

# Set Oracle database connection (datasource, user, password)
ORACLE_DSN	        dbi:Oracle:XXXSID (how can I define the RAC database and host?)
ORACLE_USER	USER
ORACLE_PWD	PASSWORD

In Java I connect using

jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=on)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=192.xxx.yyy.zz)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=192.xxx.yyy.z2)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=XXXSID)))
ORACLE_USER	USER
ORACLE_PWD	PASSWORD

The problem is that i don't know which ORACLE_DSN i have to define.

Thanks in advance

**Comment by baul87** [comment]
Hello again,

we changed the tnsnames.ora file adding this:

SIMPLE= 
  (DESCRIPTION=
   (LOAD_BALANCE=on)
   (ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)
						  (HOST=x.x.x.x)
                          (PORT=1521))
                 (ADDRESS=(PROTOCOL=TCP)
						  (HOST=x.x.x.Z)
                          (PORT=1521))
   )
   (CONNECT_DATA= 
		(SERVER = DEDICATED)
		(SERVICE_NAME=mzname))
  )


and it works. But we're getting a permission error from the db.

**Comment by darold** [comment]
Have you solved the issue?
