### ISSUE TITLE
Ora2PG Show_Version Command Fails

### ISSUE THREAD

**Issue by samparve** [darold/ora2pg#1130]
Hello , i have installed Ora2PG and Oracle 18 Express Edition on Windows 2019 Server. I can connect to oracle, set the following environment variables

ORACLE_HOME = C:\app\sqladmin\product\18.0.0\dbhomeXE
LD_LIBRARY_PATH = C:\app\sqladmin\product\18.0.0\dbhomeXE\bin

when i execute following command

ora2pg -t SHOW_VERSION -c ora2pg_dist.conf

It fails with below error message

C:\ora2pg>ora2pg -t SHOW_VERSION -c ora2pg_dist.conf
FATAL: -1 ... ERROR OCIEnvNlsCreate. Check ORACLE_HOME (Linux) env var or PATH (Windows) and or NLS settings, permissions, etc.
Aborting export...

Any idea on the error ? Any recommendation / fix.

Thanks
Sameer

**Comment by darold** [comment]
I'm not a Windows specialist but the following seems suspicious:
```
LD_LIBRARY_PATH = C:\app\sqladmin\product\18.0.0\dbhomeXE\bin
```
I think this is to be in the PATH environment variable, for LD_LIBRARY_PATH it is expecting the pat the the libraries, maybe something with \lib
