### ISSUE TITLE
tables.sql jumbled

### ISSUE THREAD

**Issue by mdanetzky** [darold/ora2pg#1131]
When I run ora2pg -p -t TABLE -o table.sql -b ./schema/tables -c ./config/ora2pg.conf
I get:
[========================>] 181/181 tables (100.0%) end of scanning.
[========================>] 181/181 tables (100.0%) end of table export.

content of table.sql:
xpression (
	qry_cond_id varchar(35) NOT NULL,
	qry_exp_id varchar(35) NOT NULL
) ;

CREATE TABLE qry_expression (
	qry_exp_id varchar(35) NOT NULL,
	qry_exp_operation varchar(35),
	qry_exp_value varchar(35),
	qry_exp_case char(1),
	qry_exp_internal char(1),
	dct_alias_id varchar(35)
) ;

CREATE TABLE qry_high_level (
	qry_hlq_id varchar(35) NOT NULL,
	qry_cond_id varchar(35)
) ;

CREATE TABLE qry_list (
	qry_hlq_id varchar(35) NOT NULL,
	qry_list_type varchar(10) NOT NULL,
	qry_list_seq bigint NOT NULL,
	dct_alias_id varchar(35)
) ;

CREATE TABLE qry_statement (
	qry_hlq_id varchar(35) NOT NULL,
	dct_lang varchar(35) NOT NULL,
	qry_stmt varchar(240),
	qry_stmt_seq bigint NOT NULL
) ;
rchar(1) NOT NULL,
	os_project_name varchar(16)
) ;

CREATE TABLE qry_boolean (
	qry_cond_id varchar(35) NOT NULL,
	qry_cond_child_id varchar(35),
	qry_cond_seq bigint NOT NULL
) ;

CREATE TABLE qry_condition (
	qry_cond_id varchar(35) NOT NULL,
	qry_boolean varchar(10),
	qry_internal char(1)
) ;

CREATE TABLE qry_condition_to_e

As you see sql is jumbled, cannot be used for import and is missing 90% of tables.

**Comment by darold** [comment]
look like there is several ora2pg running and writing to the same file no? What version of Ora2Pg are you use?

**Comment by mdanetzky** [comment]
First time I generated this file using ./export_schema.sh.
I repeated the export using 
```
 ora2pg -p -t TABLE -o table.sql -b ./schema/tables -c ./config/ora2pg.conf
```
With exactly same output - meaning that the output file looks exactly the same.
After reboot - exact same outcome
Version: Ora2Pg v21.0

**Comment by darold** [comment]
I don't remember of such problem in previous release, but please upgrade to latest release https://github.com/darold/ora2pg/releases/tag/v21.1

Can you also tell me what is your operating system?

**Comment by mdanetzky** [comment]
I used Centos 7 in Vagrant.
I followed these instructions to build it:
https://blog.crunchydata.com/blog/setup-ora2pg-for-oracle-to-postgres-migration

**Comment by darold** [comment]
How about with version 21.1?

**Comment by mdanetzky** [comment]
With 21.1 the output is exactly the same.
Is there maybe an instruction on building ora2pg using different operating system?

**Comment by darold** [comment]
In the past 2 weeks I have exported around 150 schemes,  using export_schema.sh or direct ora2pg call as you've done, I have never encountered this problem. The only possibility I see is that there is several process editing the file, as TABLE export doesn't use multi-process this can not be a bug in Ora2Pg.

**Comment by mdanetzky** [comment]
I use vagrant and a VM, which is running only ora2pg and only this one transformation, so it rules out multiple processes running ora2pg. It leaves either the specificity of the database being exported, or operating system/build. To rule out the build I will research other ways of installing ora2pg. If possible - please let me know where I could find a description on how to install ora2pg on some other system than centos 7.

**Comment by mdanetzky** [comment]
I found out the cause of the problem: When you use vagrant shared folder, tables.sql gets jumbled.
Solution: use vagrant internal folder for export and then copy outcome manually to shared folder.
