### ISSUE TITLE
Drop table before creating it

### ISSUE THREAD

**Issue by dherzhau** [darold/ora2pg#1133]
It would be helpful, if we could configure a “drop table” before creation of a new table. The reason for this feature-request is we are facing multiple migrations on a development box and therefore we have repeating migrations on the same postgres database. As this tables are under development the structure of the tables is changing and therefore it would make my life easier if I could automate this task.

**Comment by darold** [comment]
Commit 7f8864d adds this feature, see DROP_IF_EXISTS.
