### ISSUE TITLE
Calling a function within a View throws errors

### ISSUE THREAD

**Issue by atlterry** [darold/ora2pg#1134]
Hello Gilles; I have a view that calls a function as a column and I have tried various iterations to get the script to work...

Fuction imported fine...
`public | get_value                 | double precision            | in_num bigint, in_date timestamp without time zone, in_daylight text | func`

View that call function fails...
```
psql:./schema/views/XXXX_view.sql:19: ERROR:  syntax error at or near "select"
LINE 4: select cast(get_value(num, readingdate, daylight) as double precision) as tval
```

And I also tried these formats...
LINE 4: select cast(get_value(num, readingdate, daylight) as double precision) tval
LINE 4: select get_value(num, readingdate, daylight) as  tval
LINE 4: select get_value(num, readingdate, daylight) tval

Would appreciate your insights. Thanks

**Comment by darold** [comment]
What is the code before the select?

**Comment by atlterry** [comment]
CREATE OR REPLACE VIEW XXXX_view (tnum, tdate, tdaylight, tval) AS (
select num,
readingdate,
daylight,
select get_value(reading_num, readingdate, daylight) tval
FROM tbl_timestamp);

**Comment by atlterry** [comment]
Gilles; please close this ticket. I learned that there is no need to use the select ... just to use the function

CREATE OR REPLACE VIEW XXXX_view (tnum, tdate, tdaylight, tval) AS (
select num,
readingdate,
daylight,
get_value(reading_num::integer, readingdate::timestamp(0), daylight::char) tval
FROM tbl_timestamp);
