### ISSUE TITLE
Migration cost assessment with ora2pg

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#1135]
Can you please help me with the commands to do Migration cost assessment for the below scenarios?

1. Migration cost assessment of PL/SQL code from a file.
2. Migration cost assessment of Oracle SQL queries stored in a file.

**Comment by darold** [comment]
Something like `ora2pg -c config/ora2pg.conf --estimate_cost -t QUERY -i file_with_statements.sql` should do it no?

**Comment by naveenjul29** [comment]
Thank you Darold, will check that and let you know in case of any help needed.
