### ISSUE TITLE
`listagg()` conversion regex incomplete

### ISSUE THREAD

**Issue by avandras** [darold/ora2pg#1139]
https://github.com/darold/ora2pg/commit/d847810d0be0739e5de2f9af09d186a45787f009 introduced conversion from Oracle `listagg()` to Postgres `string_agg()`.  I found two minor issues with it.

1. When the first parameter to `listagg()` is a multiline expression, it doesn't match the regex.  A simple `/s` flag to the replacement helps it.
2. Oracle `listagg()` is perfectly fine with only one argument passed, in which case the delimiter (normally the second argument) becomes the empty string (or probably NULL in Oracle, but the result is the same).  Unfortunately, there is no `string_agg(<expression>)` in Postgres - that is, the delimiter always has to be passed, even when it's an empty string.  Unfortunately, I don't have a suitable regex for this (the idea was to use the `/e` flag and conditional replacement, but matching the `,\s*'<delimiter>' part reliably is beyond my Perl/regex skills - my problem is when the first argument contains something like   another function call, or anything that matches `,\s*'.*?'`)

**Comment by darold** [comment]
Please post the Oracle code.

**Comment by avandras** [comment]
For example:
       [...] 
       (SELECT listagg('['
          || this_column * 100
          ||','
          || that_column * 100
          ||']') within GROUP(
        ORDER BY one_column, another_column)
        FROM a_table
        [...]

**Comment by darold** [comment]
Commit fa2f32b solves this issues.
