### ISSUE TITLE
Default value of boolean types not converted

### ISSUE THREAD

**Issue by baul87** [darold/ora2pg#114]
Hello,

I have a problem executing the migration of a database from Postgres to Oracle. The Oracle default values aren't converted to valid Postgres values for booleans. For example:

-- ORACLE
CREATE TABLE
    P_ENDPOINT
    (
        ALLOWED_TO_TEST NUMBER(1) DEFAULT 0 NOT NULL
    )

-- POSTGRES (after migration with ora2pg)

CREATE TABLE p_endpoint (
	allowed_to_test boolean NOT NULL DEFAULT 0
) ;

The column allowed_to_test should be:

allowed_to_test boolean NOT NULL DEFAULT '0',

My configuration file contains:

REPLACE_AS_BOOLEAN	NUMBER:1
BOOLEAN_VALUES	1:0

I'm using the version 15.1

Thanks in advance

**Comment by darold** [comment]
Ok, thanks for the report. It has been fixed in latest commit, please download latest development code from github and override your installation.

Regards,
