### ISSUE TITLE
Specifying data_type as numeric(p,s)

### ISSUE THREAD

**Issue by atlterry** [darold/ora2pg#1140]
Hi Gilles; I'm tweaking my configuration for completeness and converting data_types  now but when I use this

DATA_TYPE float:numeric(20,6)

I get
numeric(20, 
as the generated DDL  - since this is of course a comma separated list of data types.

Is there a way to use an escape char (\ or something else) so that the comma in numeric(20,6) is outputted correctly in the DDL?

Thanks

**Comment by darold** [comment]
As you might have found using backslash to escape comma was the solution.
```
DATA_TYPE float:numeric(20\,6)
```
