### ISSUE TITLE
FATAL: _column_attributes() ORA-00604: error occurred at recursive SQL level 1ed data 

### ISSUE THREAD

**Issue by pymanny** [darold/ora2pg#1142]
[conversion-test]$ ora2pg --version
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Ora2Pg v21.0

 ora2pg
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
[========================>] 29/29 tables (100.0%) end of scanning.
Retrieving table partitioning information...
[>                        ]  0/29 tables (0.0%) end of scanning.
[========================>] 29/29 tables (100.0%) end of table export.
[========================>] 3/3 rows (100.0%) Table CAL_DISP_ALG (3 recs/sec)
[>                        ]         3/539929144 total rows (0.0%) - (1 sec., avg: 3 recs/sec).
[========================>] 3936/3936 rows (100.0%) Table FOOD (3936 recs/sec)
[>                        ]      3939/539929144 total rows (0.0%) - (2 sec., avg: 1969 recs/sec).
[========================>] 75/75 rows (100.0%) Table FOOD_GROUP (75 recs/sec)
[>                        ]      4014/539929144 total rows (0.0%) - (3 sec., avg: 1338 recs/sec).
[========================>] 420968/406632 rows (103.5%) Table FOOD_NUTRIENT_VALUE (14032 recs/sec)
[>                        ]    424982/539929144 total rows (0.1%) - (33 sec., avg: 12878 recs/sec).
[========================>] 4007/3809 rows (105.2%) Table FOOD_TO_FOOD_GROUP (4007 recs/sec)
[>                        ]    428989/539929144 total rows (0.1%) - (33 sec., avg: 12999 recs/sec).
[========================>] 175/169 rows (103.6%) Table NUTRIENT (175 recs/sec)
[>                        ]    429164/539929144 total rows (0.1%) - (34 sec., avg: 12622 recs/sec).
[========================>] 9218/9218 rows (100.0%) Table PRINTED_OFFER (9218 recs/sec)
[>                        ]    438382/539929144 total rows (0.1%) - (36 sec., avg: 12177 recs/sec).
[========================>] 24281/24123 rows (100.7%) Table PRINTED_OFFER_ITEM (12140 recs/sec)
[>                        ]    462663/539929144 total rows (0.1%) - (38 sec., avg: 12175 recs/sec).
[========================>] 684/684 rows (100.0%) Table PRODUCT (684 recs/sec)
[>                        ]    463347/539929144 total rows (0.1%) - (39 sec., avg: 11880 recs/sec).
[========================>] 28360/28347 rows (100.0%) Table PRODUCT_MASK (14180 recs/sec)
[>                        ]    491707/539929144 total rows (0.1%) - (42 sec., avg: 11707 recs/sec).
[========================>] 8385/8385 rows (100.0%) Table PRODUCT_MASK_TO_TOPPING (8385 recs/sec)
[>                        ]    500092/539929144 total rows (0.1%) - (43 sec., avg: 11630 recs/sec).
[========================>] 576/576 rows (100.0%) Table PRODUCT_TO_CAL_DISP_ALG (576 recs/sec)
[>                        ]    500668/539929144 total rows (0.1%) - (43 sec., avg: 11643 recs/sec).
[========================>] 505/503 rows (100.4%) Table PRODUCT_TO_FOOD (505 recs/sec)
[>                        ]    501173/539929144 total rows (0.1%) - (44 sec., avg: 11390 recs/sec).
[========================>] 684/638 rows (107.2%) Table PRODUCT_TO_SERVING_INFO (684 recs/sec)
[>                        ]    501857/539929144 total rows (0.1%) - (44 sec., avg: 11405 recs/sec).
[========================>] 347278/347158 rows (100.0%) Table PRODUCT_TO_STORE (17363 recs/sec)
[>                        ]    849135/539929144 total rows (0.2%) - (65 sec., avg: 13063 recs/sec).
[========================>] 29/29 rows (100.0%) Table PRODUCT_TYPE (29 recs/sec)
[>                        ]    849164/539929144 total rows (0.2%) - (66 sec., avg: 12866 recs/sec).
[========================>] 560213026/538937984 rows (103.9%) Table P_PRICE_STAGING (7771 recs/sec)
[========================>] 561062190/539929144 total rows (103.9%) - (72153 sec., avg: 7776 recs/sec).

`FATAL:` _column_attributes() `ORA-00604:` error occurred at recursive SQL level 1ed data (72153 sec., avg: 7480 recs/sec)
`ORA-08177:` can't serialize access for this transaction (DBD ERROR: error possibly near <*> indicator at char 109 in 'SELECT A.COLUMN_NAME, A.NULLABLE, A.DATA_DEFAULT, A.TABLE_NAME, A.OWNER, A.COLUMN_ID
FROM ALL_TAB_COLUMNS A, <*>ALL_OBJECTS O WHERE A.OWNER=O.OWNER and A.TABLE_NAME=O.OBJECT_NAME and O.OBJECT_TYPE='TABLE' AND A.TABLE_NAME='RECIPE_GROUP' AND A.OWNER='PRODUCT'
ORDER BY A.COLUMN_ID
')
Aborting export...

am exporting from oracle Version 19.7.0.0.0 into Postgres 12

Any help  would be greatly appreciated

**Comment by darold** [comment]
Set TRANSACTION to readonly in ora2pg.conf or fix it at Oracle side.

**Comment by pymanny** [comment]
Setting the transaction to readonly instead of anything else saved the day.
