### ISSUE TITLE
Can't export duplicated rows from Oracle

### ISSUE THREAD

**Issue by hunterhuang8810** [darold/ora2pg#1143]
Hi expert,

I'm new to user Ora2Pg, recently I found when I use Ora2Pg to export Oracle table rows, will fail to export duplicated rows

the case as below:

Ora2Pg version: Ora2Pg v21.1
Oracle version: 11g

I created a simple test table OPPOTB01 , and then insert duplicated rows via insert into select command ,
finally the table contain 33554432 rows ,all are duplicated.

SQL> select dbms_metadata.get_ddl('TABLE','OPPOTB01','HUNTER') from dual;

DBMS_METADATA.GET_DDL('TABLE','OPPOTB01','HUNTER')
--------------------------------------------------------------------------------

  CREATE TABLE "HUNTER"."OPPOTB01"
   (    "ID" NUMBER(*,0),
        "NAME" VARCHAR2(20

SQL> 

SQL> select count(*) from OPPOTB01;

  COUNT(*)
----------
  33554432

SQL> 

And I tried to export the data, and I expect can generate insert statement to insert all rows into PG,
but will only generate 1 rows in insert file, I tried to config PG_SUPPORTS_IDENTITY  to both 1 and 1, but the result is same.

 ora2pg -b /root/ora2pg/ -d -c /root/ora2pg/ora2pg.conf

[root@mysql5701 ora2pg]# ora2pg --version
Ora2Pg v21.1
[root@mysql5701 ora2pg]# cat ora2pg.conf
ORACLE_HOME /usr/lib/oracle/21/client64
ORACLE_DSN      dbi:Oracle:host=192.168.56.188;sid=oracledb;port=1521
ORACLE_USER     ora2pg
ORACLE_PWD      oracle
USER_GRANTS     1
LOGFILE /root/ora2pg/ora2pg.log
SCHEMA          hunter
TYPE            TABLE  DATA VIEW
OUTPUT          hunter_ora2pg.sql
PG_SUPPORTS_IDENTITY    0
[root@mysql5701 ora2pg]# 

--generated insert file:
[root@mysql5701 ora2pg]# cat INSERT_hunter_ora2pg.sql 

BEGIN;
INSERT INTO oppotb01 (id,name) OVERRIDING SYSTEM VALUE  VALUES (1,E'Hunter');

COMMIT;

[root@mysql5701 ora2pg]# 

How to solve this , I need to insert all rows into PG , i.e. all 33554432 rows

thanks advance!

**Comment by darold** [comment]
If you don't have enabled FILE_PER_TABLE the output is in file  hunter_ora2pg.sql otherwise it is in file OPPOTB01_hunter_ora2pg.sql but actually not in file INSERT_hunter_ora2pg.sql

**Comment by hunterhuang8810** [comment]
Hi darold, 

Thanks a lot for you response, I not enable FILE_PER_TABLE, below is my conf file and command:

[root@mysql5701 ora2pg]# cat ora2pg.conf 
ORACLE_HOME /usr/lib/oracle/21/client64
ORACLE_DSN      dbi:Oracle:host=192.168.56.188;sid=oracledb;port=1521
ORACLE_USER     ora2pg
ORACLE_PWD      oracle
USER_GRANTS     1
LOGFILE /root/ora2pg/ora2pg.log
SCHEMA          hunter
TYPE            TABLE  DATA VIEW
OUTPUT          hunter_ora2pg.sql
PG_SUPPORTS_IDENTITY    1
[root@mysql5701 ora2pg]# 

ora2pg -b /root/ora2pg/ -d -c /root/ora2pg/ora2pg.conf

All files generated:
[root@mysql5701 ora2pg]# ll
total 2557308
-rw-r--r--. 1 root root 2617245714 Apr 23 10:59 INSERT_hunter_ora2pg.sql
-rw-r--r--. 1 root root        282 Apr 23 10:48 ora2pg.conf
-rw-r--r--. 1 root root    1420924 Apr 23 10:59 ora2pg.log
-rw-r--r--. 1 root root        419 Apr 23 10:52 TABLE_hunter_ora2pg.sql
-rw-r--r--. 1 root root        325 Apr 23 10:59 VIEW_hunter_ora2pg.sql
[root@mysql5701 ora2pg]# 


[root@mysql5701 ora2pg]# cat TABLE_hunter_ora2pg.sql 
-- Generated by Ora2Pg, the Oracle database Schema converter, version 21.1
-- Copyright 2000-2020 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.56.188;sid=oracledb;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;


CREATE TABLE oppotb01 (
        id numeric(38),
        name varchar(20)
) ;

CREATE TABLE tb02 (
        id numeric(38),
        name varchar(20)
) ;
[root@mysql5701 ora2pg]#


I have 2 tables oppotb01  and tb02, but in INSERT file, only contain oppotb01, no  tb02:

[root@mysql5701 ora2pg]# cat INSERT_hunter_ora2pg.sql | grep -i tb02
[root@mysql5701 ora2pg]#

**Comment by darold** [comment]
Please use the following:
```
ora2pg -b /root/ora2pg/ -d -c /root/ora2pg/ora2pg.conf -o data.sql -t COPY 
```
you will normally have a file named /root/ora2pg/data.sql
