### ISSUE TITLE
DBD::mysql::st execute failed: Unknown column 'DTD_IDENTIFIER' in 'field list' at /usr/share/perl5/Ora2Pg/MySQL.pm line 316.

### ISSUE THREAD

**Issue by df7cb** [darold/ora2pg#1144]
9949c0faf4e40 (via #1037) seems to have broken the regression tests on Debian:
https://pgdgbuild.dus.dg-i.net/job/ora2pg-binaries/20/architecture=amd64,distribution=sid/console
```
17:11:49 Setting up ora2pg (21.1-1.pgdg+1) ...
17:11:49 Setting up mariadb-client-10.5 (1:10.5.9-1) ...
17:11:49 Setting up mariadb-server-10.5 (1:10.5.9-1) ...
[...]
17:11:53 CREATE TABLE empdata (emp_id int, emp_dat blob, PRIMARY KEY (emp_id))
17:11:53 --------------
17:11:53 
17:11:53 + ora2pg --source dbi:mysql:host=127.0.0.1;database=foo;user=foo;password=bar
17:11:53 DBD::mysql::st execute failed: Unknown column 'DTD_IDENTIFIER' in 'field list' at /usr/share/perl5/Ora2Pg/MySQL.pm line 316.
17:11:53 DBD::mysql::st execute failed: Unknown column 'DTD_IDENTIFIER' in 'field list' at /usr/share/perl5/Ora2Pg/MySQL.pm line 316.
```

Test script: https://salsa.debian.org/postgresql/ora2pg/-/blob/master/debian/tests/ora2pg

**Comment by darold** [comment]
Commit 9db1c41 might fix this issue. Thanks.

**Comment by df7cb** [comment]
I can't see that commit yet, is that in this repo?

**Comment by darold** [comment]
Sorry I forgot to push the commit, done.

**Comment by df7cb** [comment]
That fixes the problem, thanks! Will release the new packages shortly.

That said, shouldn't there be any mysql-vs-mariadb detection? The new code seems to work only because mariadb 10.5 is "lt" than the cutoff mysql version 5.5. If mariadb ever releases version 50, things will be weird. (Or maybe this is good enough and until then, the code would be different anyway.)

**Comment by darold** [comment]
Yes I have done a quick fix but the version comparison should be more robust, but I guess that the day mariadb get to version 50 no one will still used mysql 5.5 so that I can definitively remove the condition :-)
