### ISSUE TITLE
Migration Cutover

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#1145]
After the Initial full load is completed, I want to perform migration cutover. Please let me know how can I do this using ora2pg tool?

**Comment by darold** [comment]
What do you call cutover? I this is to switchover your application from Oracle to PostgreSQL then it is at your application side.

**Comment by naveenjul29** [comment]
I refer to migration cutover in terms of online data migration.

**Comment by darold** [comment]
Ora2Pg only supports full and unique data migration time. Once it is done you can switch your application to the PostgreSQL database. This require that you have enough possible downtime to migrate the data. If you want Change Data Capture to minimize the downtime you need to use Debezium, the Pentaho suite or any commercial tool.

**Comment by naveenjul29** [comment]
Thank you Darold.
