### ISSUE TITLE
Issue with check constraints starting with sys_

### ISSUE THREAD

**Issue by anvithaprabhu8** [darold/ora2pg#1147]
Hi Darold,

I have been using ora2pg to export just tables and I notice that out of two check constraints that have system generated name(sys_), one isn't getting exported. If check constraint has user defined name then it works absolutely fine. Could you please help me with this?

Thanks in advance!

**Comment by darold** [comment]
Do you have an example of Oracle check constraints that should be exported?

**Comment by anvithaprabhu8** [comment]
Oracle code:

CREATE TABLE test.test_table
( 
"TEST_ID" NUMBER(10,0) NOT NULL ENABLE,
 "TEST_TYPE" VARCHAR2(1 BYTE) NOT NULL ENABLE,
"TEST_STATUS_ID" NUMBER(2,0) NOT NULL ENABLE,
"TEST_YN" VARCHAR2(1 BYTE) NOT NULL ENABLE,
"TEST_CHECK" VARCHAR2(1 BYTE) NOT NULL ENABLE,
CONSTRAINT "XPKTESTTABLE" PRIMARY KEY("TEST_ID"),
CONSTRAINT "check1" CHECK (test_type IN ('Y','N')) ENABLE, 
CHECK (test_type IN ('A','B','C')) ENABLE,
CHECK (test_yn in ('Y','N')) ENABLE
) TABLESPACE "TEST" ;

Pg code exported by ora2pg:

CREATE TABLE test.test_table (
        test_id buying NOT NULL,
        test_type varchar(1) NOT NULL,
        test_status_id smallint NOT NULL,
        test_yn varchar(1) NOT NULL,
        test_check varchar (1) NOT NULL
) TABLESPACE TEST;
ALTER TABLE test.test_table ADD CONSTRAINT XPKTESTTABLE PRIMARY KEY (test_id);
ALTER TABLE test.test_table ADD CONSTRAINTora2pg_ckey_test_test_table CHECK (test_yn in ('Y','N'));
ALTER TABLE test.test_table ADD CONSTRAINT check1 CHECK (test_type in ('Y','N'));

So, ora2pg has ignored "CHECK (test_type IN ('A','B','C')) ENABLE," check constraint.

The two check constraints without name have names starting with SYS_............ in SQL developer and only one gets exported.

**Comment by anvithaprabhu8** [comment]
Hi Darold, 

I have added sample oracle code and Pg code generated by ora2pg. Could you please look into this and help me out with it

**Comment by darold** [comment]
Commit d9e1314 solves this issue.
