### ISSUE TITLE
Can't call method "finish" on an undefined value at /usr/local/share/perl/5.22.1/Ora2Pg.pm line 11048.

### ISSUE THREAD

**Issue by ganeshakorde** [darold/ora2pg#1148]
Hi Darold,

   Thanks for creating such wonderful utility. 
   I am facing issue while exporting BLOB. I have one row having BLOB size 750 MB. I am trying to export data with below configuration

LONGREADLEN     770047552
DATA_LIMIT 1
ALLOW   TEST_BLOB
TYPE INSERT

I am getting below error
Can't call method "finish" on an undefined value at /usr/local/share/perl/5.22.1/Ora2Pg.pm line 11048.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=x.x.x.x)(PORT=xxxx))(ADDRESS=(PROTOCOL=tcp)(HOST=x.x.x.x)(PORT=xxxx)))(CONNECT_DATA=(SERVICE_NAME=orclpdb1))) at /usr/local/share/perl/5.22.1/Ora2Pg.pm line 11048.

ora2pg-21.1
Oracle 19c

**Comment by darold** [comment]
Just pushed commit 617efee that will show the reason of this error.
