### ISSUE TITLE
Data migration issues with MySQL Sakila database

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#1149]
Darold, I kick off the data migration using the below command
ora2pg -d -t INSERT -c mysql.conf -o sakilainsert.sql

**Below are my concerns:**
1.	output file is not generated with the above ora2pg statement.
2.	In address table, location column is there with the data type geometry and we converted the column with point datatype.
	I got the below error, not sure how to resolve the issue here
![data migration issues 1](https://user-images.githubusercontent.com/67134199/116002037-4bbaf600-a615-11eb-9bbb-1c5d731003dd.PNG)

3.	Data migration is completed successfully, but for 2 tables(payment and rental tables) record count is not matching even though there are no errors in the data mmigration log, not sure why.
![rental table issue](https://user-images.githubusercontent.com/67134199/116002046-537a9a80-a615-11eb-8203-9387c57390a4.PNG)
![payment table issue](https://user-images.githubusercontent.com/67134199/116002049-570e2180-a615-11eb-9539-72be83cedf73.PNG)

Need your help to resolve these issues.

**Comment by naveenjul29** [comment]
Darold, can you please help me on this?

**Comment by naveenjul29** [comment]
Darold, can you please help me on this?

**Comment by darold** [comment]
Commit 92a87d6 fixes this issue.
