### ISSUE TITLE
FATAL: ORA-00904 when importing from Oracle 10g

### ISSUE THREAD

**Issue by kyiannis** [darold/ora2pg#115]
When importing from Oracle version 10g i get the following error:
DBD::Oracle::db prepare failed: ORA-00904: "OBJECT_TYPE": invalid identifier (DBD ERROR: error possibly near <*> indicator at char 88 in 'SELECT AUTHID,OBJECT_TYPE,OBJECT_NAME,OWNER FROM ALL_PROCEDURES WHERE OWNER = 'TPA' AND <*>OBJECT_TYPE='PACKAGE'  ORDER BY OBJECT_NAME') [for Statement "SELECT AUTHID,OBJECT_TYPE,OBJECT_NAME,OWNER FROM ALL_PROCEDURES WHERE OWNER = 'TPA' AND OBJECT_TYPE='PACKAGE'  ORDER BY OBJECT_NAME"] at /home/yiannis/perl5/lib/perl5/Ora2Pg.pm line 6322.
The above error arises when reading PACKAGES, TRIGGERS, FUNCTIONS and PROCEDURES.
The problem seems to be that the following line:
$self->{db_version} = $self->_get_version() if (!$self->{input_file});
is executed after the schema export and the db_version is not set.
I put the following line:
$self->{db_version} = $self->_get_version();
write below the oracle_connection, Ora2Pg.pm line 944, and the error is fixed.
Yiannis

**Comment by darold** [comment]
Hi,

Please upgrade to latest development code from github this issue might have been fixed in last commit 4ac7c39.

Thanks for the report.

**Comment by kyiannis** [comment]
Hi,
I upgraded to the latest development version as per your suggestion https://github.com/darold/ora2pg/commit/c9641198fdb6702e11582810be5f95b0d23b078b .
The fix to get the database version works perfectly.
Unfortunately there is a new error when trying to read views:
FATAL: ORA-32033: unsupported column aliasing (DBD ERROR: error possibly near <*> indicator at char 8 in '
```sql
WITH x (ITER, OWNER, OBJECT_NAME) AS
( SELECT 1 , o.OWNER, o.OBJECT_NAME FROM ALL_OBJECTS o WHERE OBJECT_TYPE = 'VIEW' AND o.OWNER='TPA' 
  AND NOT EXISTS (SELECT 1 FROM ALL_DEPENDENCIES d WHERE TYPE LIKE 'VIEW' AND REFERENCED_TYPE = 'VIEW'
  AND REFERENCED_OWNER = o.OWNER AND d.OWNER = o.OWNER and o.OBJECT_NAME=d.NAME)
UNION ALL
  SELECT ITER + 1, d.OWNER, d.NAME FROM ALL_DEPENDENCIES d
     JOIN x ON d.REFERENCED_OWNER = x.OWNER and d.REFERENCED_NAME = x.OBJECT_NAME
    WHERE TYPE LIKE 'VIEW' AND REFERENCED_TYPE = 'VIEW'
)
SELECT max(ITER) ITER, OWNER, OBJECT_NAME FROM x
GROUP BY OWNER, OBJECT_NAME
ORDER BY ITER ASC, 2, 3
```
'
This has probably something to do with this commit: https://github.com/darold/ora2pg/commit/33dc1516e52959a2cdcc7d8144b7b20de61eac18 .
It seems that Oracle 10g does not support column aliasing. I run a modified version of this query with the column aliases inside the 2 subqueries:
```sql
WITH x  AS
( SELECT 1 ITER, o.OWNER OWNER, o.OBJECT_NAME OBJECT_NAME FROM ALL_OBJECTS o WHERE OBJECT_TYPE = 'VIEW' AND o.OWNER = 'TPA'
  AND NOT EXISTS (SELECT 1 FROM ALL_DEPENDENCIES d WHERE TYPE LIKE 'VIEW' AND REFERENCED_TYPE = 'VIEW'
  AND REFERENCED_OWNER = o.OWNER AND d.OWNER = o.OWNER and o.OBJECT_NAME=d.NAME)
UNION ALL
  SELECT ITER + 1 ITER, d.OWNER OWNER, d.NAME OBJECT_NAME FROM ALL_DEPENDENCIES d
     JOIN x ON d.REFERENCED_OWNER = x.OWNER and d.REFERENCED_NAME = x.OBJECT_NAME
    WHERE TYPE LIKE 'VIEW' AND REFERENCED_TYPE = 'VIEW'
)
SELECT max(ITER) ITER, OWNER, OBJECT_NAME FROM x
GROUP BY OWNER, OBJECT_NAME
ORDER BY ITER ASC, 2, 3;
```
and i get a new error:
```
ORA-32031: illegal reference of a query name in WITH clause
32031. 00000 -  "illegal reference of a query name in WITH clause"
*Cause:    forward or recursive reference of a query name in WITH clause is not
           allowed.
```
Probably the above queries work only in Oracle 10g.

Yiannis

**Comment by kyiannis** [comment]
My mistake, the last line on my previous comment should have been:

Probably the above queries work only in Oracle 11gR2.

**Comment by darold** [comment]
Yes this was also my conclusion :-) Please download latest code it might be fixed now with last commit.

**Comment by kyiannis** [comment]
Thanks for the prompt fix. Now it works perfectly.
Best regards,
Yiannis
