### ISSUE TITLE
Error: cannot fork: Cannot allocate memory

### ISSUE THREAD

**Issue by highgozhangyc** [darold/ora2pg#1150]
Hi,
First, the ora2pg is an wonderful tool for migrating from oracle to postgresql.
I create a table like the example in the ora2pg.conf :
The table has 30120 rows with different size of BLOB (200x5Mb,19800x212k, 10000x942K, 100x17Mb, 20x156Mb).
My environment is a VM(memory:8GB),i use this command to migrate the table :
ora2pg -J2 -j1 -L 10 -c ora2pg.conf.blob
But, there was an error:
Error: cannot fork: Cannot allocate memory.
So i changed the command to ora2pg -J1 -j1 -L 10 -c ora2pg.conf.blob,then the error disappeared.
But ,it was too slow,this is the result:
1100/1 rows (110000.0%) Table ORA2PG_BLOB (9 recs/sec)

So, i don't how to migrate the table more quikly without error ,for example getting the result you show in the ora2pg.conf:
 #       no lob locator  : 22m46,218s (1365 sec., avg: 22 recs/sec)
#       chunk size 8k   : 15m50,886s (951 sec., avg: 31 recs/sec)
#       chunk size 512k : 1m28,161s (88 sec., avg: 342 recs/sec)
#       chunk size 4Mb  : 1m23,717s (83 sec., avg: 362 recs/sec)

Thanks very much.

**Comment by darold** [comment]
Add more memory and CPUs to be able to increase parallelism.
