### ISSUE TITLE
Perl Warning 

### ISSUE THREAD

**Issue by pymanny** [darold/ora2pg#1152]
When i initiate my ora2pg exports, it sends out this warning;

`$ ora2pg
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").`

Can this warning be a data validation killer. In other words should i be concerned about the quality of the data being imported from the oracle schema?

Does anyone know how to set the locales on a GCP(vm)

**Comment by darold** [comment]
Hi,
Sorry for the response delay. Normally you should not have problem with this warning, I guess since this time you have tried, what was the result?
