### ISSUE TITLE
ORA-12801,  ORA-01555

### ISSUE THREAD

**Issue by xinjirufen** [darold/ora2pg#1153]
Hi,darold.
  I got some error info: **ERROR: ORA-12801: error signaled in parallel query server P000, instance edwgxdb1:edwgxdb1 (1)
 ORA-01555: snapshot too old: rollback segment number 474 with name "_SYSSMU474_237676816$" too small (DBD ERROR: OCIStmtFetch)**
  Ora2pg version：v21.
  command: `ora2pg --no_header -T /home/f2pg_6b7592a7-6c4e-47c4-ae5d-0ee3e6cd70d4 -c common.conf -t COPY -a TABLE1 -s "dbi:Oracle:ccdba28d-6818-4374-a401-92bce88644a9" -u MKTG -w '123' -n WH --pg_dsn "dbi:Pg:dbname==app1;host=134.125.162.128;port=18921" --pg_user app --pg_pwd '123' -N wh`
cmmon.conf : 
STANDARD_CONFORMING_STRINGS 0
NO_LOB_LOCATOR 0
EMPTY_LOB_NULL 1
JOBS 5
ORACLE_COPIES 5
USE_RESERVED_WORDS 1 
COMPILE_SCHEMA 0 
EXPORT_INVALID 1 
PG_VERSION 12 
LOG_ON_ERROR 1 
DEBUG 1

Error ORA-12801, it occurs in the case of parallel queries，but directive DEFAULT_PARALLELISM_DEGREE default is disabled. I don‘t  know how did it happened.

**Comment by darold** [comment]
Try with TRANSACTION set to readonly instead of default serializable in ora2pg.conf.

**Comment by xinjirufen** [comment]
> Try with TRANSACTION set to readonly instead of default serializable in ora2pg.conf.

I tried,but it doesn't work. 
The mistake this time is ‘ERROR: ORA-12801: error signaled in parallel query server P009, instance edwgxdb1:edwgxdb1 (1)， ORA-01555: snapshot too old: rollback segment number 491 with name "_SYSSMU491_1159650477$" too small (DBD ERROR: OCIStmtFetch)’

**Comment by darold** [comment]
You need to fix that at Oracle side.
