### ISSUE TITLE
Migration is failed when there is no any whitespaces between bracket and keyword

### ISSUE THREAD

**Issue by attahard** [darold/ora2pg#1155]
I have some functions I need to export where there is no any whitespaces between keywords and brackets and migration is failed.

For example:

`create function getTest return integer as`
&nbsp;&nbsp;&nbsp;&nbsp;`latestID integer;`
`begin`
&nbsp;&nbsp;&nbsp;&nbsp;`select ID`
&nbsp;&nbsp;&nbsp;&nbsp;`into latestID`
&nbsp;&nbsp;&nbsp;&nbsp;`from`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`(`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`select 1 ID,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   `ROWNUM R`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`from (`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`select 1 ID`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`from dual`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`where 1 = 1)`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`ORDER BY ID DESC)`
&nbsp;&nbsp;&nbsp;&nbsp;`WHERE ID = R`
&nbsp;&nbsp;&nbsp;&nbsp;`;`
&nbsp;&nbsp;&nbsp;&nbsp;`return latestID;`
`end;`

where there is no whitespaces between DESC and ")" mark. The error message is:
`psql:./schema/functions/GETTEST_function.sql:47: ERROR:  subquery in FROM must have an alias`

 If I write a space between DESC keyword and ")" mark then the migration is executed successfully

**Comment by darold** [comment]
This have been fixed, here is the translation output for code above:
```
CREATE OR REPLACE FUNCTION gettest () RETURNS numeric AS $body$
DECLARE
    latestID numeric;
BEGIN
    select ID
    into STRICT latestID
    from (
            SELECT 1 ID,
                 row_number() OVER () AS R
            from (
                    SELECT 1 ID

                    where 1 = 1) alias0
            ORDER BY ID DESC) alias1
    WHERE ID = R ;
    return latestID;
end;
$body$
LANGUAGE PLPGSQL
 STABLE;
```
