### ISSUE TITLE
Migration slower down!

### ISSUE THREAD

**Issue by Code-UV** [darold/ora2pg#1157]
I have a 50 million row table. When it comes to 40 million, it starts to slow down. There is no lob column in this table

**Comment by darold** [comment]
I need additional information:

* Ora2Pg version
* Value of DATA_LIMIT and average of rows/second reported by ora2pg
* The value of JOBS ( -j ) and ORACLE_COPIES ( -J )
* The number of cores on the host an d the amount of memory
* and the operating system
* kind of data export: to file or direct PostgreSQL import
