### ISSUE TITLE
Incorrect [TEST SEQUENCE VALUES] from ora2pg -t TEST

### ISSUE THREAD

**Issue by gp4git** [darold/ora2pg#1158]
Hello,

in ora2pg migration assessment report (-t TEST), all sequences values are off by 1
between Oracle and PostgreSQL.

Tested on the last ora2pg-master

Regards

**Comment by darold** [comment]
Does your sequence cache is set to 1?

**Comment by gp4git** [comment]
Yes set to 1 (default value on PG)

Regards

**Comment by darold** [comment]
You can have difference between Oracle and PostgreSQL sequences last value +/- cache size, this is normal. You have to select the max value of the column using the sequence if you want to be sure.

**Comment by gp4git** [comment]
I verify again with nextval on Oracle and PostgreSQL after migration : all sequences restart on PG with +1 difference versus Oracle
Losing 1 number for each sequence is no big deal, but my problem is that the TEST count appears to be KO

Regards

**Comment by darold** [comment]
I know, this is why there is a warning in the test report about the cache size, I can not do much more. A possible automatic verification is to find where the sequences are used and execute a SELECT max() on the column, but finding the column that use a column is complicated.

**Comment by gp4git** [comment]
It seems to be related to a behaviour difference between "LAST_NUMBER" column in Oracle
and "start_value" column in PG.
Let's take an example with my hibernate sequence :

- in Oracle, just before migration (no more database activity) :
SQL> select LAST_NUMBER from seq where sequence_name = 'HIBERNATE_SEQUENCE';
LAST_NUMBER
-----------
      **10157**
- then after extracting data from Oracle to files, I see in data/data.sql :
ALTER SEQUENCE IF EXISTS hibernate_sequence RESTART WITH **10158**;

- after importing in PostgreSQL database :
SQL> select sequencename, start_value from pg_sequences where sequencename ='hibernate_sequence';
    sequencename     | start_value 
--------------------+-------------
 hibernate_sequence |      **10157**

Now, if I select nextval in Oracle :
SQL> select HIBERNATE_SEQUENCE.nextval from dual;
   NEXTVAL
----------
     **10157**
And in PG :
SQL> select nextval('hibernate_sequence');
 nextval 
---------
   **10158**

Maybe, should you compare last_number and start_value in your TEST count ?

Hope this helps

Regards

P.S. when did you add this new test count ? In V21, it was not there I think, and I couldn't find any mention in version history

**Comment by darold** [comment]
Use latest development code until next release will be published there is lot of improvement and bug fixes since v21.1.
