### ISSUE TITLE
Is Multi-schema export possible ?

### ISSUE THREAD

**Issue by pymanny** [darold/ora2pg#1159]
I have set my config file to copy a few schema not the entire instance, for some reason the process completes quickly with only oracle DB synonyms seeming to have been copied. Is Ora2pg now capable of doing multi-schema exports?

thoughts??

**Comment by darold** [comment]
Yes Ora2Pg can export all schemas is SCHEMA is not set in ora2pg.conf or one single schema that you set at the same configuration variable but you can not give a list of schema.

But it is possible to exclude some schemas by adding them to the SYSUSERS configuration variable. So don't set SCHEMA to export all schemes and add the schemes to exclude in SYSUSERS could probably achieve what you want but I have never tested this use.

**Comment by pymanny** [comment]
thank you, will run that test and update

**Comment by pymanny** [comment]
Including unwanted schema on the SYSUSERS list produce the desired results. Item being closed as resolved
