### ISSUE TITLE
Default value to new column in Postgres

### ISSUE THREAD

**Issue by Priyankat17** [darold/ora2pg#1161]
Hi,

How to add default column value while exporting data in ora2pg.

Scenario:  We are upgrading application to new version.
in oracle table we have 10 columns and in postgres DB it will be 11 columns, where the 11th columns by default is adding NULL value, we want to replace it with defaulted value while exporting.

**Comment by darold** [comment]
There is nothing to do, if the column is not present in Oracle then it will not be part of the SQL export statement so in PostgreSQL you will have the default value you've defined.

**Comment by Priyankat17** [comment]
As part of export activity, it has updated as NULL to the new column in Postgres DB. Suppose i want to add value like "100" as default value for the column, what is the parameter used in conf for this functionality.

**Comment by darold** [comment]
You can not do that in Ora2Pg but you can fix the column using PostgreSQL commands.
