### ISSUE TITLE
lob error

### ISSUE THREAD

**Issue by xinjirufen** [darold/ora2pg#1165]
Hello darold!
Error info: DBD::Oracle::db::ora_lob_chunk_size: locator is not of type OCILobLocatorPtr at /usr/local/share/perl/5.28.1/Ora2Pg.pm line 14723.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle 1667937f-4c9d-438b-81f6-5f48653f9c97 at /usr/local/share/perl/5.28.1/Ora2Pg.pm line 14723.
ora2pg version: v21.0
ora2pg.conf:
STANDARD_CONFORMING_STRINGS 0
NO_LOB_LOCATOR 0
EMPTY_LOB_NULL 1
JOBS 5
ORACLE_COPIES 5
USE_RESERVED_WORDS 1 
COMPILE_SCHEMA 0 
EXPORT_INVALID 1 
LOG_ON_ERROR 1 
DEBUG 1 
REORDERING_COLUMNS 1
PG_VERSION 9

table structure info as follows:
![QQ图片20210520164011](https://user-images.githubusercontent.com/44968246/118947611-168e9300-b98a-11eb-8fe8-06bfd4418075.png)

**Comment by darold** [comment]
Not reproducible with latest code. Closing.
