### ISSUE TITLE
Conversion error when invoking procedures

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1166]
Good afternoon Darold,

I hereby come into contact because in the conversion of an oracle package to postgres, more specifically in the invocation of some procedures that is carried out within that package, I noticed that some errors occur in its invocation namely the character is incorrectly placed **:=** and the expressions **_INTO STRICT_** and _**SELECT * FROM**_ when invoking this procedure, follow the example:

_Example1:_

Oracle:
  PROCEDURE sp_obtem_reincidencia_ref
	(
	preferencia IN VARCHAR2,
	pid_reincidencia OUT NUMBER,
	pcor_reincidencia OUT VARCHAR2
	)
	IS
  vid_ci PLS_INTEGER;
    vid_ci2 PLS_INTEGER;
    vid_ci3 PLS_INTEGER;
    vid_servico VARCHAR2(4000);
    vid_subcategoria PLS_INTEGER;
    vid_causa PLS_INTEGER;
	BEGIN
		SELECT e.id_equipamento, c.id_carta, p.id_porto, (SELECT agrega_strings(s.id_tipo_servico) FROM gtt_avaria_tipo_servico s WHERE s.referencia = a.referencia), a.ids_og, a.id_causa_avaria
		INTO vid_ci, vid_ci2, vid_ci3, vid_servico, vid_subcategoria, vid_causa
		FROM gtt_avaria a, tra_equipamento e, gtt_avaria_carta c, gtt_avaria_porto p WHERE a.id_equipamento = e.id(+) AND a.referencia = c.referencia (+) AND a.referencia = p.referencia (+) AND a.referencia = preferencia;
		sp_obtem_reincidencia(pid_ci => vid_ci,pid_ci2 => vid_ci2,pid_ci3 => vid_ci3,pid_servico => vid_servico,pid_subcategoria => vid_subcategoria,pid_causa => vid_causa,pid_reincidencia => pid_reincidencia,pcor_reincidencia => pcor_reincidencia);  END sp_obtem_reincidencia_ref;

Postgres:

CREATE OR REPLACE PROCEDURE pck_gtt_geral.sp_obtem_reincidencia_ref ( preferencia text, pid_reincidencia INOUT numeric, pcor_reincidencia INOUT text ) AS $body$
DECLARE
    vid_ci integer;
    vid_ci2 integer;
    vid_ci3 integer;
    vid_servico varchar(4000);
    vid_subcategoria integer;
    vid_causa integer;
BEGIN
SELECT e.id_equipamento, c.id_carta, p.id_porto, (SELECT agrega_strings(s.id_tipo_servico) FROM gtt_avaria_tipo_servico s WHERE s.referencia = a.referencia), a.ids_og, a.id_causa_avaria
		INTO STRICT vid_ci, vid_ci2, vid_ci3, vid_servico, vid_subcategoria, vid_causa
		FROM gtt_avaria a LEFT OUTER JOIN tra_equipamento e ON (a.id_equipamento = e.id)LEFT OUTER JOIN gtt_avaria_carta c ON (a.referencia = c.referencia)LEFT OUTER JOIN gtt_avaria_porto p ON (a.referencia = p.referencia)WHERE a.referencia = preferencia;
_**SELECT * FROM**_ pck_gtt_geral.sp_obtem_reincidencia(pid_ci => vid_ci, pid_ci2 => vid_ci2, pid_ci3 => vid_ci3, pid_servico => vid_servico, pid_subcategoria => vid_subcategoria, pid_causa => vid_causa, pid_reincidencia => pid_reincidencia, pcor_reincidencia => pcor_reincidencia) _**INTO STRICT pid_reincidencia => pid_reincidencia, pcor_reincidencia => pcor_reincidencia**_;  END;$body$ LANGUAGE PLPGSQL;

_Example2:_

Oracle:
            ELSIF n.id_tipo_escalamento = 4 THEN
              pck_gtt_geral.sp_eqp_prevencao(preferencia => t.referencia,pid_categoria => NULL,pid_equipamento => NULL, pid_servico => t.id_servico,pid_tipo_participacao => n.id_tipo_participacao, pdata => vdata,pid_equipa => vid_equipa_participar);

Postgres:
              ELSIF n.id_tipo_escalamento = 4 THEN
             _:=_ pck_gtt_geral.sp_eqp_prevencao(preferencia => t.referencia, pid_categoria => NULL, pid_equipamento => NULL, pid_servico => t.id_servico, pid_tipo_participacao => n.id_tipo_participacao, pdata => vdata, pid_equipa => vid_equipa_participar);

Is it possible to please validate these situations?

Best regards,

Rui Pereira.

**Comment by RuiFilipeGoncalvesPereira** [comment]
Good morning Sir Darold,

I would like to know as soon as possible if there is any solution to the problem described in the message above ?.

I already grate the answer given.

Best regards,

Rui Pereira.

**Comment by darold** [comment]
Hi,

You must fix this manually for the moment, I hope to have more time next week to work on it.

**Comment by darold** [comment]
Commit bb71d32 fixes this issue.
