### ISSUE TITLE
Error converting oracle instr to postgres position using ora2pg

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1167]
Good afternoon, Mr. Darold,

In the migration of an oracle package to postgres, more specifically in the migration of the functions of oracle instr to the position of postgres, I noticed that an extra parenthesis is being placed, which prevents the code from being successfully compiled, as you can see under.

Example:

Oracle:
FOR t1 IN
 (SELECT * FROM (SELECT a.codigo FROM tra_dd_area_rede a WHERE a.inactivo = 0 START WITH a.id = t.id_area_rede CONNECT BY PRIOR a.id_pai = a.id UNION SELECT NULL codigo FROM dual) ar WHERE INSTR(','||NVL(n.id_area_rede,NVL(ar.codigo,'-696969'))||',',','||NVL(ar.codigo,'-696969')||',') > 0)LOOP 

Postgres:
FOR t1 IN ((SELECT * FROM (WITH RECURSIVE cte AS (
SELECT a.codigo FROM tra_dd_area_rede a WHERE a.id = t.id_area_rede
  UNION ALL SELECT a.codigo FROM tra_dd_area_rede a JOIN cte c ON (c.id_pai = a.a.id )
) SELECT * FROM cte WHERE inactivo = 0 UNION  SELECT NULL codigo ;
) ar  WHERE position **_(_** (','||coalesce(ar.codigo,'-696969')||',' in ','||coalesce((n.id_area_rede,coalesce(ar.codigo,'-696969')))||',')) > 0 ) **_)_** LOOP

Is it possible to please validate and correct this situation?

Best regards,

Rui Pereira.

**Comment by RuiFilipeGoncalvesPereira** [comment]
Good morning Sir Darold,
I would like to know as soon as possible if there is any solution to the problem described in the message above ?.
I already grate the answer given.
Best regards,
Rui Pereira.

**Comment by darold** [comment]
Closing, I can not reproduce at least with the code provided. If you still have the problem please send me the stored procedure code.
