### ISSUE TITLE
Export of packages failed with 

### ISSUE THREAD

**Issue by just-doit** [darold/ora2pg#1168]
When exporting the packages, the following error occurs with one package:
`Unmatched ( in regex; marked by <-- HERE in m/\bsp_common_utl.strg.eval( <-- HERE l_assignment_rule,\b/ at /usr/local/share/perl5/Ora2Pg.pm line 18929.`

The cause is probably a global constant in the package body, which looks like the following:
`   c_err_out_of_single_chips   CONSTANT VARCHAR2(50 CHAR) := q'{Running out of single use chips}';`

If I delete the alternate quote characters, the error no longer occurs.

It seems that the function that determines the global variables of the package gets confused and thinks that the text `'sp_common_utl.strg.eval('` is a global variable, although it is part of a normal function call in one of the included procedures.

**Comment by darold** [comment]
Might have been fixed by a recent commit, I can not reproduce the issue.
