### ISSUE TITLE
Manage apostophe or single quote in export data file

### ISSUE THREAD

**Issue by lux7789** [darold/ora2pg#1169]
Is there a parameter in the config file to avoid this error when importing in PostgreSQL => 

psql:/home/equinoxe/scripts_migration_postgresql/Test_apostrophe.sql:53: ERREUR:  marqueur fin-de-copie corrompu 

This is an extract from my data file :

COPY imhisto (i_imhisto,i_inscrmatiere,i_detailinscrmatiere,i_personne,i_inscription,i_unite,i_utilisateur,d_histo,c_type,c_action,x_inscrmatiere,x_detailinscrmatiere,x_personne,x_inscription,x_utilisateur,x_description,i_reference) FROM STDIN;
137528	\N	\N	3240073	\N	2707	16721	2018-04-19 11:14:38	INSCRIPTION	DELETE	Didactique de la musique	\N	Achermann Laurène	HEP Fribourg,Diplôme d'enseignant-e préscolaire et primaire,Français,Tronc commun,Formation de base,2018-2019,Semestre 3	[SGUILLOD]	\N	3883062
\.

The error is raised because the field x_inscription contain a single quote (d'enseignement)!

**Comment by darold** [comment]
Hi,
No the problem comes from the final dot, it must be escaped for a COPY: `\. `

I don't know what have remove the backslash before the final COPY dot but I don't think this is Ora2Pg as it uses the pg_putcopyend() function from DBD::Pg.

**Comment by lux7789** [comment]
Hi,

Sorry, something wrong happens with the copy in github, my bad. But I confirm there is still an issue with the single quote because I removed it from the COPY command and the execution was ok.

**Comment by darold** [comment]
There must be a non printable character because the single quote can not be the problem with COPY, separator is the tabulation. For example:
```
CREATE TABLE public.test_copy (
    id integer,
    description text
);

COPY public.test_copy (id, description) FROM stdin;
1       Fribourg,Diplôme d'enseignant-e préscolaire et primaire,Français,Tronc commun,Formation de base,2018-2019,Semestre 3
\.
```
just works as expected.

Can you remove the single quote (that might not be a regular one) and insert one again from your text editor to see if there is an unexpected character?

**Comment by lux7789** [comment]
I confirm. It works. Visually it looks exactly the same. The issue might be coming from the character set ? Since I'm using an ora2pg on Windows and copying the export result file on Linux where my Postgres database is. My source Oracle database have NCHAR character set "AL16UTF16" and character set is "WE8MSWIN1252".  I just asking myself if I should replace all single quotes with Vi  on my postgres machine.

**Comment by darold** [comment]
Yes this is a solution, the other one is to perform the data export with Ora2Pg on Linux to see if the problem persists.

**Comment by lux7789** [comment]
Thanks for your help !
