### ISSUE TITLE
TEST migration report is not giving the row count comparison between oracle & postgresql information

### ISSUE THREAD

**Issue by gvijay07** [darold/ora2pg#1171]
Hi,

I have performed the migration from oracle to postgresql using the ora2pg. I am trying the compare the object count after the migration as per the information determined in"https://ora2pg.darold.net/documentation.html#Test-the-migration" section. I have enabled the EXPORT_SCHEMA to 1 and PG_SCHEMA to <schemaname> which I had performed the migration and updated the pg connection info.

"ora2pg -t TEST -c config/ora2pg.conf > migration_diff.txt"

I am able to generate the migration difference report but the row count information is not getting generated. I am getting the information regarding ddl's. Can anyone suggest if I am missing something to update in ora2pg.conf?

Thanks for your support on this.

**Comment by darold** [comment]
Hi, add `--count_rows` to your ora2Pg command.

**Comment by gvijay07** [comment]
Hi Darold,

This helped me. Thanks for the quick response on this.
