### ISSUE TITLE
Not Able to Connect to Oracle 19c standard edition

### ISSUE THREAD

**Issue by mahesh97chavan91** [darold/ora2pg#1173]
i have used 18c express edition and it worked fine but now i am trying to connect to Oracle 19c standard edition.
but getting error ORA-12637: Packet receive failed (DBD ERROR: OCIServerAttach).
it will be useful if you provide any inputs for this.

**Comment by darold** [comment]
You must have the 19C instant client  and at least DBD::Oracle 1.76 and DBI 1.643, use the following command for Perl modules versions:
```
perl -e 'use DBD::Oracle; print $DBD::Oracle::VERSION, "\n"; use DBI; print $DBI::VERSION, "\n";'
```

**Comment by mahesh97chavan91** [comment]
i have oracle instant client instantclient_19_8 , DBD::Oracle is 1.80 and DBI is 1.64.
i have doubt that for 19c standard edition 2 instant client is not working properly.
which instant client we should use instantclient_19_8  or anything else.

**Comment by luss** [comment]
I recommend that you determine if you can connect to your oracle database,
from your postgres server, with whatever instantclient you've got.  Start
by trying sqlplus with instantclient before you mess with trying to
OracleFDW connecting.

**Comment by mahesh97chavan91** [comment]
issue is resolved it was issue in oracle 19c std edition for getting connection
