### ISSUE TITLE
Primary key error

### ISSUE THREAD

**Issue by arun-022** [darold/ora2pg#1174]
Hi,

While doing a data load i get a primary key constraint error. This should theoretically be not possible as the source table in oracle has the same primary key, meaning that the row does not exist twice in oracle. Is it possible that ora2pg tries to copy it twice ?? I have also come across this issue with some other tables .. the way i proceed is truncate the table on the postgres side and try the export again  and somehow it works the second time .. I am moving data from source using a date wise where clause. Please assist

DBD::Pg::db pg_putcopyend failed: ERROR:  duplicate key value violates unique constraint "pc_history_rbg_rabo_scm_work_p2016q4_pkey"
DETAIL:  Key (pzinskey, pxtimecreated)=(HISTORY-RBG-RABO-SAM-SCM-WORK RBG-RABO-SAM-SCM-WORK SE-298111!20161231T145442.841 GMT, 2016-12-31 15:54:42) already exists.
CONTEXT:  COPY pc_history_rbg_rabo_scm_work, line 1: "System    tlw_prod        \N      \N      \N      RBG-RABO-SAM-COLLECTIONS-WORK RD-234957 \N      \N      RBG-RABO-SAM-SCM-WORK SE-2981..." at /usr/local/lib/perl5/site_perl/5.30.0/Ora2Pg.pm line 14497.
DBI::db=HASH(0x559fc2227028)->disconnect invalidates 1 active statement handle (either destroy statement handles or call finish on them before disconnecting) at /usr/local/lib/perl5/site_perl/5.30.0/Ora2Pg.pm line 13678.
FATAL: ERROR:  duplicate key value violates unique constraint "pc_history_rbg_rabo_scm_work_p2016q4_pkey"
DETAIL:  Key (pzinskey, pxtimecreated)=(HISTORY-RBG-RABO-SAM-SCM-WORK RBG-RABO-SAM-SCM-WORK SE-298111!20161231T145442.841 GMT, 2016-12-31 15:54:42) already exists.
CONTEXT:  COPY pc_history_rbg_rabo_scm_work, line 1: "System    tlw_prod        \N      \N      \N      RBG-RABO-SAM-COLLECTIONS-WORK RD-234957 \N      \N      RBG-RABO-SAM-SCM-WORK SE-2981..."

**Comment by darold** [comment]
If you have run ora2pg several time it is possible that some data have already been copied, you should enable TRUNCATE_TABLE in ora2pg.conf to truncate a table before data import.

**Comment by arun-022** [comment]
I have not enabled truncate as I am loading data per year from the source to the target. I got this error while loading data for the year 2017 and this was the first run for the year 2017.

**Comment by darold** [comment]
so in this case there is probably duplicates in the Oracle table, you should check.

**Comment by arun-022** [comment]
There are no duplicates in the oracle table as there is a primary key constraint on both the source and the target. For the row it throws an error, I can confirm that the source has ONLY one record. Is it possible that the program tries to copy the same row twice in any scenario ?

**Comment by darold** [comment]
What is your ora2pg command?

**Comment by arun-022** [comment]
ora2pg -c /config/ora2pg.conf

**Comment by darold** [comment]
then post your anonymized ora2pg.conf

**Comment by arun-022** [comment]
[ora2pg.txt](https://github.com/darold/ora2pg/files/6584955/ora2pg.txt)
attached

**Comment by darold** [comment]
You should remove data from your PostgreSQL failing table using the WHERE clause defined in ora2pg.conf:
```
DELETE FROM tablename WHERE pxtimecreated > '2016-12-31 00:00:00.00' and pxtimecreated  <= '2017-12-31 00:00:00.00'
```
Then run Ora2Pg again for this table only (-a tablename) to see if the problem persist. Normally Ora2Pg can not duplicate data by itself, it select the rows from oracle and send them at PostgreSQL side. Unless the same set of data is imported twice of course. Also please use latest development code this will help.

**Comment by arun-022** [comment]
ok thanks for the tip
