### ISSUE TITLE
ora2pg migrate more than one schema

### ISSUE THREAD

**Issue by njaf** [darold/ora2pg#1175]
In the configuration file is there a way i can specify more than one schema name for below directive. My goal is to migrate 2 or 3 schemas. However in the configuration i am unable to specify more than one schema, tried by separating them with "," or ";"

ex. 
ORACLE_USER     HR,ORDER, STOCKS

**Comment by darold** [comment]
Right, this is either the export of one schema or all schemas.

Hint: if you export all schemas and want to exclude a list of schema from the export you can use the SYSUSERS configuration directive. That should works.
