### ISSUE TITLE
ora2pg Healthcheck report

### ISSUE THREAD

**Issue by njaf** [darold/ora2pg#1176]
Once migration is complete is there a way to get the health check done  
1) Things which didnt get migrated ex. any type of indexes and how do we recreate those objects on the target instance?

**Comment by darold** [comment]
Yes there is the TEST action (option -t or TYPE configuration directive) that will check the differences between both database. Note that this require that you use latest development code there was several improvement and fix on this part.

**Comment by njaf** [comment]
Thankyou!
