### ISSUE TITLE
ORA-12557: TNS:protocol adapter not loadable

### ISSUE THREAD

**Issue by TimotheeWright** [darold/ora2pg#1177]
Hello,

I tried every tutorial, uninstall and reinstall etc. but always ends up on this error:
`C:\ora2pg-21.1\reveil_migration> ora2pg -t SHOW_VERSION -c config/ora2pg.conf
FATAL: 12557 ... ORA-12557: TNS:protocol adapter not loadable (DBD ERROR: OCIServerAttach)
Aborting export...`

There seems to be no documentation anywhere  about this error. Is there a quick fix?

Thanks for reading !

**Comment by darold** [comment]
A path environment variable issue? Perhaps http://www.dba-oracle.com/t_ora_12577.htm can help

**Comment by TimotheeWright** [comment]
Thanks for the answer Mr Darold !

I already ended up on this page and tried what was said there. Doesn't seems to work for me.

**Comment by darold** [comment]
Well I can not help more on Windows, you might want to use Linux anyway.
