### ISSUE TITLE
Problem with ora2pg 15.2 and Oracle 8i

### ISSUE THREAD

**Issue by sebastianfischer** [darold/ora2pg#118]
Heyo, I was using ora2pg v12.1 for the ongoing Migration of our Oracle 8i DB 
I thought I try upgrading ora2pg to v15.2. Now I get following error:

```

ORA-00942: table or view  does not exist (DBD ERROR: error possibly near <*> 
indicator at 
...
FROM <*>ALL_MVIEW_LOGS)
 ...

```

seems like the table ALL_MVIEW_LOGS doesn't exist in ancient Oracle DBs ;-)
I will go back to v12.1 for the time and don't necessarily need new features. So this is more of a FYI Issue. 
Best Regards and thanks for your work. Saved me a lot of time (and nerves)

**Comment by darold** [comment]
Hi,

Thanks for the report. You can download latest code from github, latest commit might solves this issue.

Best regards,
