### ISSUE TITLE
Issues with MySQL Assessment report

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#1182]
In assessment report for MySQL, both the procedures and functions are showing as functions only. Attaching the sample report for your reference. I am trying to generate assessment report for Sakila database where in we have 3 procedures and 3 functions. But in the assessment report, it is showing that there are 6 functions. 

Please help me further on this.
![MySQL Assessment](https://user-images.githubusercontent.com/67134199/120898792-28d72500-c64a-11eb-9df3-e065c916a4fc.PNG)

**Comment by darold** [comment]
Commit 33ee95a might fix this issue.

**Comment by naveenjul29** [comment]
Thank you Darold for quick help. Do I need to download latest code now?

**Comment by darold** [comment]
yes

**Comment by naveenjul29** [comment]
I downloaded latest MySQL.PM file and ran the assessment report, but procedures are not showing in the assessment report, still it is showing only functions.

**Comment by darold** [comment]
AH yes, sorry there was a confusion between DATA_TYPE and ROUTINE_TYPE. Commit 612bcce might fix the issue, please upgrade to latest development code.

**Comment by naveenjul29** [comment]
sorry Darold, no luck. Still I am seeing functions only in the assessment report. Please help me.

**Comment by naveenjul29** [comment]
Darold, can you please help me here?

**Comment by darold** [comment]
Please use latest development code, I'm not able to reproduce your issue.

![report](https://user-images.githubusercontent.com/538862/122286337-0964b580-cef0-11eb-8319-ae2170b8b650.png)

Both functions and procedures are reported and also exported.

**Comment by naveenjul29** [comment]
Thank you Darold. I already downloaded latest MySQL.PM file and ran the assessment report, let me try again.
