### ISSUE TITLE
facing problem to migrate data from oracle to postgres

### ISSUE THREAD

**Issue by mahesh97chavan91** [darold/ora2pg#1185]
Hi team,
  
i am migrating data from oracle to postgres i am able to migrate maximum tables.
but for some tables i am not able to migrate using ora2pg. not getting any error as well for those table.
for migrating blob column facing  problem as well.
for some table getting bellow error.
```
COPY sys_export_full_02, line 232, column dump_allocation: "" at /usr/local/share/perl/5.26.1/Ora2Pg.pm line 12761.
```
Regards,
Mahesh Chavan

**Comment by darold** [comment]
You should look at postgresql log file to see if there is more information about the error, here we have the COPY line that is failing but not the reason.
