### ISSUE TITLE
Error opening cursors.

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1186]
Good night Mr Darold,

When converting a procedure from oracle to postegres, ora2pg added the EXECUTE command to the following query, it adds this command to all queries:

-------------------------------------------------------------PG-----------------------------------------------------------------------------

OPEN plista FOR **EXECUTE** SELECT ID, designacao, inativo
			FROM (
			SELECT 0 ORDEM, -696969 ID, '<'||pck_tra_geral.f_obtem_label(pid_idioma, 1380)||'>' DESIGNACAO, 0 INATIVO	
UNION
      SELECT 1 ORDEM, u.id, coalesce(u.nome,u.username) DESIGNACAO, flag_apagado INATIVO
      FROM cfg_equipa_utilizador eus,tra_sca_utilizador u, gtt_avaria a
      WHERE (to_char(eus.id_equipa) IN (SELECT column_value FROM desagrega_strings(pid_equipas,',') alias3) OR pid_equipas = '0')
        AND eus.id_utilizador = u.id
        AND u.id = a.id_util
        AND a.id_estado <> 3
			) alias6
      order by inativo asc, ordem collate "az-Latn-AZ-x-icu" asc, designacao collate "west_european" asc;  

Sendo gerado o erro:

ERROR: syntax error at or near "SELECT" LINE 13: OPEN plista FOR EXECUTE SELECT ID, designacao, inativo

A query original em oracle é a seguinte:

---------------------------------------------------------------Oracle---------------------------------------------------------------------
    OPEN plista FOR
			SELECT ID, designacao, inativo
			FROM (
			SELECT 0 ORDEM, -696969 ID, '<'||pck_tra_geral.f_obtem_label(pid_idioma, 1380)||'>' DESIGNACAO, 0 INATIVO FROM dual
			UNION
      SELECT 1 ORDEM, u.id, NVL(u.nome,u.username) DESIGNACAO, flag_apagado INATIVO
      FROM cfg_equipa_utilizador eus,tra_sca_utilizador u, gtt_avaria a
      WHERE (eus.id_equipa IN (SELECT column_value FROM TABLE(desagrega_strings(pid_equipas,','))) OR pid_equipas = '0')
        AND eus.id_utilizador = u.id
        AND u.id = a.id_util
        AND a.id_estado <> pck_tra_def.cn_eliminado_avaria)
      ORDER BY inativo ASC, NLSSORT(ordem, 'NLS_SORT=WEST_EUROPEAN') ASC, NLSSORT(designacao, 'NLS_SORT=WEST_EUROPEAN') ASC;

I think that the addition of the execute command to the following query, developed in normal sql, this is an error, right?, from my point of view it should only be added to the quereis developed in dynamic sql, in these cases the same has to be present otherwise the query does not work when the procedure is invoked.

Thank you in advance for the answer given,

Best regards,

Rui Pereira.

**Comment by darold** [comment]
Commit 6b9fa9e might fix this issue.
