### ISSUE TITLE
Difference between ora2pg show_report and scanner

### ISSUE THREAD

**Issue by njaf** [darold/ora2pg#1187]
1) Would like to know the difference between the 
ora2pg -t SHOW_REPORT  
ora2pg_scanner

2) How are migration levels B and C defined? can you please list some scenerios.

Migration levels:
        A - Migration that might be run automatically
        B - Migration with code rewrite and a human-days cost up to 5 days
        C - Migration with code rewrite and a human-days cost above 5 days

Thankyou!

**Comment by darold** [comment]
This is explained in the documentation.
