### ISSUE TITLE
First_value clause conversion error 

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1190]
Good afternoon sir darold,

I hereby get in touch because in the migration of a function from a package via ora2pg, the right parenthesis associated with the first_value clause is being removed, which causes an error to be generated in the pg database.

Example of an excerpt of code in oracle:

to_clob(NVL2((SELECT _**first_value(co.ref_contrato)**_ OVER (ORDER BY co.data_fim DESC) FROM cfg_contrato_id_servico s, cfg_contrato co

Example of the same code excerpt in pg after the conversion made via ora2pg:
NVL2((SELECT **_first_value(co.ref_contrato_** OVER (ORDER BY co.data_fim DESC) FROM cfg_contrato_id_servico s, cfg_contrato co 

Is it possible to analyze and fix this problem?.

Best regards,

Rui Pereira.

**Comment by darold** [comment]
Commit 04dcc25 fixes the issue by fixing replacment of TO_CLOB() function. Unfortunately you will have to fix the call to NVL2, Ora2Pg can not do it automatically because of the subquery.

**Comment by darold** [comment]
Actually this is commit fa90892.
