### ISSUE TITLE
No tables are exported

### ISSUE THREAD

**Issue by laurenz** [darold/ora2pg#1192]
I am using ora2pg 21.1 with the following configuration:

```none
ORACLE_HOME	/path/to/oracle/home
ORACLE_DSN	dbi:Oracle:host=127.0.0.1;sid=orcl;port=1521
ORACLE_USER	system
ORACLE_PWD	something
SCHEMA		ADMPS_P
DEBUG		1
EXPORT_SCHEMA	1
CREATE_SCHEMA	1
COMPILE_SCHEMA	0
TYPE		TABLE
OUTPUT		output.sql
```

It shows this while running:

```
[2021-06-16 13:29:34] Ora2Pg version: 21.1
[2021-06-16 13:29:34] Export type: TABLE
[2021-06-16 13:29:34] Geometry export type: INTERNAL
[2021-06-16 13:29:34] ORACLE_HOME = /path/to/oracle/home
[2021-06-16 13:29:34] NLS_LANG = AMERICAN_AMERICA.AL32UTF8
[2021-06-16 13:29:34] NLS_NCHAR = AL32UTF8
[2021-06-16 13:29:34] Trying to connect to database: dbi:Oracle:host=127.0.0.1;sid=orcl;port=1521
[2021-06-16 13:29:34] Isolation level: SET TRANSACTION ISOLATION LEVEL READ COMMITTED
[2021-06-16 13:29:34] Looking forward functions declaration in schema ADMPS_P.
[2021-06-16 13:29:34] Retrieving table information...
[2021-06-16 13:29:35] Retrieving table partitioning information...
[2021-06-16 13:29:35] Exporting tables...
[2021-06-16 13:29:35] Fixing function calls in output files...
```

But the output file contains no tables:

```sql
-- Generated by Ora2Pg, the Oracle database Schema converter, version 21.1
-- Copyright 2000-2020 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=127.0.0.1;sid=orcl;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;

CREATE SCHEMA IF NOT EXISTS admps_p;
ALTER SCHEMA admps_p OWNER TO admps_p;

SET search_path = admps_p,public;
```

However, there are plenty of tables in that schema. What could be the problem?

**Comment by laurenz** [comment]
If I set `COMPILE_SCHEMA 1`, I get an error

```none
FATAL: ORA-20002: invalid schema
ORA-06512: at "SYS.DBMS_UTILITY", line 400
ORA-06512: at line 2 (DBD ERROR: OCIStmtExecute)
```

However, the schema exists, and user `oracle` can sucessfully run

```sql
DBMS_UTILITY.compile_schema(schema => 'ADMPS_P');
```

**Comment by laurenz** [comment]
The error was mine: I connected to the root container instead of the correct pluggable database.

Changing the connect string fixed the problem:

```none
ORACLE_DSN  dbi:Oracle://127.0.0.1/admp.lan
```

**Comment by rodraen** [comment]
I have the same problem, but connection string like this doesn't work. please, help (

`[root@ol8_migr]# ora2pg -p -t TABLE -o table.sql -b ./schema/tables -c ./config/ora2pg.conf
FATAL: ORA-20002: invalid schema
ORA-06512: at "SYS.DBMS_UTILITY", line 400
ORA-06512: at line 2 (DBD ERROR: OCIStmtExecute), SQL: BEGIN
DBMS_UTILITY.compile_schema(schema => 'CRMBPM', compile_all => FALSE);
END;
Aborting export...
[root@ol8_migr]#
`

# Set Oracle database connection (datasource, user, password)
ORACLE_DSN      dbi:Oracle:host=cv_agent_1;sid=MYDB;port=1521
#ORACLE_DSN     dbi:Oracle://cv_agent_1/MYDB.lan

**Comment by rodraen** [comment]
problem solved

`#dbi:Oracle://_host_/_service_name_
dbi:Oracle://127.0.0.1/MYPDB`
