### ISSUE TITLE
Can't open perl script "ora2pg": Permission denied

### ISSUE THREAD

**Issue by orenbouni** [darold/ora2pg#1193]
Hello,
When running the Ora2PG_Scanner I'm getting an error for each CSV row, The Error is "Can't open Perl script "ora2pg": Permission denied" What can be the issue I'm running with From CMD with Admin right.

**Comment by darold** [comment]
The ora2pg program is not executable. Don't know how to fix that on Windows, I guess that a right click might help to look at properties of the file.
