### ISSUE TITLE
Data export using --quiet with --parallel fails when the last writer sub-process is terminated prematurely by the main process

### ISSUE THREAD

**Issue by DavidHarper** [darold/ora2pg#1195]
I need to migrate a schema with several very large tables from Oracle to PostgreSQL, so I am using ora2pg with the --parallel option to copy multiple tables concurrently.  I am running this unattended, so I disable the progress reporting by adding the --quiet option.  The result is always that the dump file for the largest table in the schema is incomplete.  The last-modified timestamp of that file is always the same as for the dump file of the second-largest table.  When I investigated the lifecycles of all of the ora2pg processes using strace, I found that the parent ora2pg process sent a SIGUSR1 signal to the sub-process that was dumping the largest file, immediately after the sub-process dumping the second-largest file exited normally.

As of commit d05c7ca24992c3bf3987b4ed3a7e80c36bbe0b47, the bug is in line 8388 of lib/Ora2Pg.pm:

$numchild = 0 if ($self->{debug}); # in debug there is no progressbar

It is fixed by changing this line to:

$numchild = 0 if ($self->{debug} || $self->{quiet}); # in debug or quiet modes there is no progressbar

Many thanks for creating such a useful tool.  I hope you will continue to develop and support it.

**Comment by darold** [comment]
Good catch! This is the right fix, commit 86fb34c applies it. Thanks.
