### ISSUE TITLE
Error when migrating a function inside a package with the oracle to_clob function.

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1196]
Good afternoon Mr Darold.

I hereby get in touch because in the migration of a function inside a package from oracle to pg via ora2pg that contained the to_clob function, correctly removed by ora2pg, the following errors were registered, namely in some cases the parenthesis was not removed right associated with to_clob, as I noticed that in a specific situation the rownum clause was not converted to the limit of pg, as described below:

Oracle:
to_clob(CASE WHEN(SELECT equips_suportam FROM tra_glb_tmp_ligacao g WHERE g.num_geca = c.num_geca AND g.nome_tipo_servico = NVL(c.nome_tipo_servico,'-696969')
                _**AND rownum < 2) is not null then**_
                         '<tr>
                                         <td width="210px" class="TitleLabel" valign="top">'||(SELECT pck_tra_geral.f_obtem_label(pid_idioma,773) FROM dual) ||'</td>
                                         <td><input type="text" class="PlainTextRO" readonly value="'||(SELECT equips_suportam FROM tra_glb_tmp_ligacao g WHERE g.num_geca = c.num_geca AND g.nome_tipo_servico = NVL(c.nome_tipo_servico,'-696969') AND g.ocupacao = NVL(c.ocupacao,'-696969') AND rownum < 2)||'" style="width:99%"/></td>
                          </tr>' else '' END**)**||

PG:
        CASE WHEN(SELECT equips_suportam FROM tra_glb_tmp_ligacao g WHERE g.num_geca = c.num_geca AND g.nome_tipo_servico = coalesce(c.nome_tipo_servico,'-696969' ) _**is not null then**_
                         '<tr>
                                         <td width="210px" class="TitleLabel" valign="top">'||(SELECT pck_tra_geral.f_obtem_label(pid_idioma,773)  LIMIT 1) ||'</td>
                                         <td><input type="text" class="PlainTextRO" readonly value="'||(SELECT equips_suportam FROM tra_glb_tmp_ligacao g WHERE g.num_geca = c.num_geca AND g.nome_tipo_servico = coalesce(c.nome_tipo_servico,'-696969') AND g.ocupacao = coalesce(c.ocupacao,'-696969')  LIMIT 1)||'" style="width:99%"/></td>
                          </tr>' else '' END**)**||

Is it possible to validate that it really is an ora2pg error?, if so, it is possible to correct it.

Thank you in advance for any help given.

Best regards,

Rui Pereira.

**Comment by darold** [comment]
I  think commit fa90892 might fix this one too.
