### ISSUE TITLE
Double parentheses in procedures and functions within packages

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1198]
Good night darold,

I hereby get in touch because in the migration of a package from oracle to pg via ora2pg, double parentheses (()) are being placed in the declarations of procedures and functions, as shown below:

**Oracle code:**
 	FUNCTION f_estadoTTK2estadoCliente
	(
		preferencia IN VARCHAR2
	)
	RETURN NUMBER
	IS
		vid_estado gtt_dd_estado.id%TYPE;
	BEGIN
		SELECT ((CASE WHEN a.autorizacao_fecho IN (2,3) then 5 WHEN a.id_estado = 6 AND (SELECT DISTINCT FIRST_VALUE(tp.flag_excluir_sla) OVER (ORDER BY app.dh_inicio DESC) FROM gtt_avaria_periodos_pendencia app, cfg_tipo_pendencia tp 
WHERE app.referencia = a.referencia AND app.id_tipo_pendencia = tp.id) = 0 THEN 3
 WHEN a.id_estado = 2 AND a.data_estado > a.data_avaria THEN 3 ELSE a.id_estado END)) ID_ESTADO
		INTO vid_estado
		FROM gtt_avaria a WHERE a.referencia = preferencia;
		RETURN vid_estado;
  EXCEPTION
    WHEN OTHERS THEN
      /*CALL*/ LOGGER.ERROR('PCK_GTT_GERAL.F_ESTADOTTK2ESTADOCLIENTE',SQLERRM);
			RETURN NULL;
	END f_estadoTTK2estadoCliente;

**Código PG:**

CREATE OR REPLACE FUNCTION pck_gtt_geral.f_estadottk2estadocliente **((** preferencia text **) )** RETURNS numeric AS $body$
DECLARE
		vid_estado gtt_dd_estado.id%TYPE;
BEGIN
		SELECT (CASE WHEN a.autorizacao_fecho IN (2,3) then 5 WHEN a.id_estado = 6 AND (SELECT DISTINCT FIRST_VALUE(tp.flag_excluir_sla) OVER (ORDER BY app.dh_inicio DESC) FROM gtt_avaria_periodos_pendencia app, cfg_tipo_pendencia tp 
WHERE app.referencia = a.referencia AND app.id_tipo_pendencia = tp.id) = 0 THEN 3 
WHEN a.id_estado = 2 AND a.data_estado > a.data_avaria THEN 3 ELSE a.id_estado END) ID_ESTADO
		INTO STRICT vid_estado
		FROM gtt_avaria a WHERE a.referencia = preferencia;
		RETURN vid_estado;
  EXCEPTION
    WHEN OTHERS THEN
      CALL
 LOGGER.ERROR('PCK_GTT_GERAL.F_ESTADOTTK2ESTADOCLIENTE()',SQLERRM);
			RETURN NULL;
	END;
$body$
LANGUAGE PLPGSQL;

This problem didn't happen until then, so I think this is very strange, can you explain to me if this is an error?.´

I am using the version associated with the master with code 9a727d6.

Thank you in advance for any response given.

Best regards,

Rui Pereira.

**Comment by darold** [comment]
Got it, fixed in new release 22.0.
