### ISSUE TITLE
compile_schema break valid function based indexes (Oracle DB 12c and 19c)

### ISSUE THREAD

**Issue by PawelFengler** [darold/ora2pg#1199]
Hi Darold, 
Thank you for your hard work and very good tool ora2pg. 
We use ora2pg version 21.1 and we encountered the following problem:
https://dba.stackexchange.com/questions/41130/why-does-dbms-utility-compile-schema-break-function-based-indexes/41131 
According to the documentation of ora2pg: 
"When this directive is enabled and SCHEMA is set to a specific schema name, only invalid objects in this schema will be recompiled."
but in row 18139 Ora2pg.pm we see:
my $sth = $self->{dbh}->do("BEGIN\nDBMS_UTILITY.compile_schema(schema => '$schm');\nEND;")
Consequently this causes all objects to compile (not only in the INVALID status).
Function based indexes become DISABLED, what lead to sql statement error (for example ORA-30554)
We suggest that the line 18139 of Ora2pg.pm should have the form: 
my $sth = $self->{dbh}->do("BEGIN\nDBMS_UTILITY.compile_schema(schema => '$schm', compile_all => FALSE);\nEND;")

Best regards 
Paweł Fengler

**Comment by darold** [comment]
Ah ok, I was not aware of that. Thank you for the feedback I will add this fix.

**Comment by darold** [comment]
Fixed with commit 927b07d.
