### ISSUE TITLE
ora2pg data export warning

### ISSUE THREAD

**Issue by walpino** [darold/ora2pg#120]
Hello 
i installed the neweset ora2pg 15.2 
and got an Warning at the end of Oracle Data Export
but I can't see any errors or warnings before

Thanks

WARNING: an error occurs during data export. Please check what's happen.
 
[=======================> ] 54260699/54511012 rows (99.5%) on total data (avg: 15534.1 recs/sec)

**Comment by darold** [comment]
Hi,

Maybe you have reach the memory level where OOMKiller is triggered. You may have a log entry in dmesg or syslog. You may need to reduce the DATA_LIMIT value.

**Comment by walpino** [comment]
Thanks for your quick reply

but if the data_limit is the problem I get an error in your output just at the time 
but this time I get it just at the end of the report (export)

and there are no entries in the syslog or dmesg

**Comment by darold** [comment]
And the error message is ?

**Comment by walpino** [comment]
Hi 
as I wrote in the first post
this is the output of ora2pg 


......
[=======================> ] 54243922/54511012 rows (99.5%) on total data (avg: 15542.7 recs/sec)
[========================>] 34/34 rows (100.0%) Table VERWALTUNGS_SOFTWARE (34.0 recs/sec)
[=======================> ] 54243956/54511012 rows (99.5%) on total data (avg: 15533.8 recs/sec)
[========================>] 16743/16138 rows (103.7%) Table VISITATION (16741.3 recs/sec)
WARNING: an error occurs during data export. Please check what's happen.


[=======================> ] 54260699/54511012 rows (99.5%) on total data (avg: 15534.1 recs/sec)
[root@chbo1srv28 homegate_migration_prod]# ls-ltr


but there was no warning or error before in your output! so I don't know why it says 
WARNING: an error occurs during data export. Please check what's happen

**Comment by darold** [comment]
ora2pg is creating a temporary file each time it forks a process to export your data. At end of the process, just before the child exit the temporary file is removed. Then just before exiting ora2pg checks that all temporary file are removed, if there's still some of those files that mean that a process dies prematurely .

How many memory do you have on your computer? Have you tried using -L 1000 for example ?

**Comment by walpino** [comment]
okay I see that in /tmp there is 1 tmp_ora2pgFEuBVY

The Server has 8 CPU's and 16 GB of Ram 

I'm working with config files and there DATA_LIMIT ist set to:

DATA_LIMIT      100000
 
I know DATA_LIMIT such high in combination with blobs are critical 
but in this export there are no tables which containing blobs
and as I know from previous exports - when memory is a problem I get really an error in your Output 
which tells me that OOMKiller kills process caused by not enough memory

but here there is no such message

I will try now to export with DATA_LIMIT 10000

**Comment by darold** [comment]
Usually all fatal errors are logged by Ora2Pg so it can only happens with a SIGKILL on an ora2pg process or of course if there is a bug in ora2pg that prevent it to remove the temporary file. Then 
let's see the result using -L 10000 .

**Comment by darold** [comment]
Also note that you seems to be limited around 15000 tuples/seconds when using one process so it is recommended to use this value as your DATA_LIMIT otherwise you will fill your memory for nothing.

Then if you want to speed up the export you might use the multiprocess feature by using -j 4 for example and keep you DATA_LIMIT to 15000.

**Comment by walpino** [comment]
this time I didn't get any warnings or errors
so your right it has something to do with memory but there is no message

[========================>] 15/14 rows (107.1%) Table USER_ROLES (15.0 recs/sec)
[=======================> ] 54343922/54511012 rows (99.7%) on total data (avg: 18403.0 recs/sec)
[========================>] 34/34 rows (100.0%) Table VERWALTUNGS_SOFTWARE (34.0 recs/sec)
[=======================> ] 54343956/54511012 rows (99.7%) on total data (avg: 18396.7 recs/sec)
[========================>] 16743/16138 rows (103.7%) Table VISITATION (16741.3 recs/sec)
[=======================> ] 54360699/54511012 rows (99.7%) on total data (avg: 18390.0 recs/sec)


JOBS  7
ORACLE_COPIES 1
PARALLEL_TABLES 1
DATA_LIMIT 10000

with 8 CPU's and 16GB of RAM

on some tables I get 50000/s on some only 3000/s 
I guess I has also something to do with the count of fields in the table

**Comment by darold** [comment]
Yes, I've told you, this warning message is typically the result of an OOM killer :-)

Here maybe you can limit the JOBS value to 4 or 5, I don't think you win much more with 7. Are you loading directly into PostgreSQL or are using data file export ?

**Comment by walpino** [comment]
I'm using file export and than with copy 

Sometimes I see it uses 7 of 8 CPUS and on some tables only 1 CPU

We are trying to figure out whats the benefit because on the Production DB we have 16 CPUS and 100 GB of RAM 
we will see where the first bootleneck is (maybe IO?) and we will see how scaling is

**Comment by darold** [comment]
Yes in this case I/O is the bottleneck, If you want to be able to export data at a maximum speed and are sure that there will be no error during the import you might use direct import to pg.

In your production server, you can try with a DATA_LIMIT set to 25000, JOBS set to 4 and  PARALLEL_TABLES to 3. There is still a issue in the progress bar using PARALLEL_TABLES but if there's no import errors everything should works fine.

Regards
