### ISSUE TITLE
ora2pg V22.0 : FATAL: foreign data export requires that PG_DSN to be set

### ISSUE THREAD

**Issue by gp4git** [darold/ora2pg#1201]
Hello,

I just downloaded ora2pg V22.0 version.
ora2pg --version
==> Ora2Pg v22.0
When I launch the "data COPY" step i.e. ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg.conf,
I get : "FATAL: foreign data export requires that PG_DSN to be set"

In the release notes, I see that FDW export is a new V22 feature but even using FDW_SERVER directive
set to '', I still cannot obtained a pre-V22 bahaviour i.e. export data on flat files.

Suspecting something weird in my original config file, I also tried with original ora2pg.conf.dist file but got same result.

Thanks in advance for any help you may provide

Regards

**Comment by darold** [comment]
I am preparing a tutorial to describe exactly what must be done, this is will be more helpful. I will post the link here when ready.

**Comment by darold** [comment]
Here it is https://www.migops.com/blog/2021/07/01/ora2pg-now-supports-oracle_fdw-to-increase-the-data-migration-speed/

Note that in v22.0 there is a limitation for using oracle_fdw to migrate the data, EXPORT_SCHEMA and PRESERVE_CASE must be enable. This limitation has been removed in current development code and will be include in shot coming v22.1

**Comment by darold** [comment]
Version 22.1 have been released.
