### ISSUE TITLE
Empty Oracle blob to Postgresql empty blob

### ISSUE THREAD

**Issue by lux7789** [darold/ora2pg#1203]
Actually, I got an issue with empty blob since ora2pg convert an Oracle empty blob to null but the column doesn't allow null value. Is there a way to keep an empty value on Postgresql ?

**Comment by darold** [comment]
Look at EMPTY_LOB_NULL in ora2pg.conf

**Comment by lux7789** [comment]
It works ! Thanks.

**Comment by lux7789** [comment]
Perfect.
