### ISSUE TITLE
REATE INDEX and CREATE UNIQUE INDEX with the same Indexname are in Oracle allowed, but in PG not allowed.

### ISSUE THREAD

**Issue by ubironald** [darold/ora2pg#1205]
Hello Darold,

In Oracle-SQL you can create the following table:

CREATE TABLE "SYSADM"."PS_AAP_TBL_LNG" 
   (	"ESTABID" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"LANGUAGE_CD" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"DESCR" VARCHAR2(30 BYTE) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 80 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HRAPP" ;

  CREATE INDEX "SYSADM"."PS0AAP_TBL_LNG" ON "SYSADM"."PS_AAP_TBL_LNG" ("DESCR", "ESTABID", "LANGUAGE_CD") <-!
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSINDEX" ;

  CREATE UNIQUE INDEX "SYSADM"."PS_AAP_TBL_LNG" ON "SYSADM"."PS_AAP_TBL_LNG" ("ESTABID", "LANGUAGE_CD") <-!
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PSINDEX" ;
  

Please look at the lines with "CREATE INDEX..." and "CREATE UNIQUE INDEX...", at the end I mark
this lines with the sign: "<-!".

ora2pg convert this table defintion from Oracle-SQL to the following lines:

...
10473 CREATE TABLE ps_aap_tbl_lng (
  10474         estabid varchar(12) NOT NULL,
  10475         language_cd varchar(3) NOT NULL,
  10476         descr varchar(30) NOT NULL
  10477 ) ;
  10478 CREATE INDEX ps0aap_tbl_lng ON ps_aap_tbl_lng (descr, estabid, language_cd);
  10479 CREATE UNIQUE INDEX ps_aap_tbl_lng ON ps_aap_tbl_lng (estabid, language_cd);
...

Only for info: The numbers in the first column are from vi (editor), when you execute the command ":set number".

But when we execute ora2pg, we will get the following error:

...
CREATE TABLE
CREATE TABLE
CREATE INDEX
psql:db_LOBP_SCHEMA_SYSADM_output.sql:10479: ERROR:  relation "ps_aap_tbl_lng" already exists

It is not allowed in PostgreSQL to use the same Indexname in the line 10479, but in Oracle this is allowed.

Have you a solution for this problem?

Thank you very much forward!

Best regards
Ronald

**Comment by darold** [comment]
This is a know problem that is usually fixed manually if there is few duplicates but otherwise enabling INDEXES_RENAMING in ora2pg.conf will force Ora2Pg to not use the Oracle index name but the one autogenerated by PostgreSQL.
