### ISSUE TITLE
DEFAULT_PARALLELISM_DEGREE doesn't work (ora2pg v22.1)

### ISSUE THREAD

**Issue by yonisade** [darold/ora2pg#1207]
I have set in ora2pg.conf:
DEFAULT_PARALLELISM_DEGREE      4
PARALLEL_MIN_ROWS               100000

But when running "ora2pg -t COPY -b data/ -c config/ora2pg.conf"
ora2pg queries Oracle without the /*+parallel*/ hint in it even though the table has millions of rows (also all_tables.num_rows reflects that).

**Comment by darold** [comment]
You should have hint `/*+ FULL(a) PARALLEL(a, $self->{default_parallelism_degree}) */` in the SELECT statement.

If not try to set PARALLEL_MIN_ROWS to -1 to see if the hint is applied.

**Comment by yonisade** [comment]
When PARALLEL_MIN_ROWS is set to -1 the hints are added, but I still wonder why the previous setting doesn't apply it.

**Comment by darold** [comment]
The settings doesn't apply because there is less than 100000 rows in the table (taken from statistics).
