### ISSUE TITLE
Problem with OBJECT_TYPE at Oracle XE 10g

### ISSUE THREAD

**Issue by gabrielssoares** [darold/ora2pg#121]
Hi, my name is Gabriel and I'm using Ora2Pg to migrate my entire database. I faced a problem with the generation query to find structures FUNCTION|PROCEDURE|PACKAGE|TRIGGER. The final query is not compatible with Oracle XE 10g, because an column doesn't exists. 

The final query is [SELECT AUTHID,OBJECT_TYPE,OBJECT_NAME,OWNER FROM DBA_PROCEDURES WHERE OWNER = 'ICLASSFS' AND OBJECT_TYPE='PACKAGE'  ORDER BY OBJECT_NAME'] and Oracle returns an error: "FATAL: ORA-00904: "OBJECT_TYPE": invalid identifier (DBD ERROR: error possibly near <*> indicator at char 93 in 'SELECT AUTHID,OBJECT_TYPE,OBJECT_NAME,OWNER FROM DBA_PROCEDURES WHERE OWNER = 'ICLASSFS' AND <*>OBJECT_TYPE='PACKAGE'  ORDER BY OBJECT_NAME')", because the column 
OBJECT_TYPE does not exists in the table DBA_PROCEDURES .

What I missed here? Is this a real bug or I made a mistake?

Thanks a lot.

**Comment by darold** [comment]
Hi,

I'm not able to reproduce the issue using latest code from github. Could you post here the result of command:

    ora2pg -t SHOW_VERSION -c /path/to/config/ora2pg.conf

Regards,

**Comment by gabrielssoares** [comment]
Hi, 

Here the result:

[root@XXXXX]# ora2pg -t SHOW_VERSION -c config/ora2pg.conf
Oracle Database 10g Express Edition Release 10.2.0.1.0

**Comment by darold** [comment]
Please download latest development code from github, this must have been fixed as I'm not able to reproduce the issue. When reinstalling, be sure that perl libraries are well overriden.

**Comment by gabrielssoares** [comment]
Tks, I will try.
