### ISSUE TITLE
from_unixtime using in ora2pg

### ISSUE THREAD

**Issue by GerrMullers** [darold/ora2pg#1211]
Hi,
why from_unixtime using in ora2pg. This function is not supported by posgresql.
psql:./schema/views/V_CPU_view.sql:14: ERROR:  function from_unixtime(bigint) does not exist
LINE 1: ...ue_avg, value_min) AS SELECT h.host, k.dns, k.ip, from_unixt...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
ERROR: an error occurs when importing file ./schema/views/view.sql.

**Comment by darold** [comment]
Hi,

Normally it is translated into `to_timestamp()`, it looks like the translate fail to be applied. Can you please post the MySQL source code with this function call?

**Comment by GerrMullers** [comment]
Hi,
sorry I didn't write my migration from oracle to postgresql

**Comment by GerrMullers** [comment]
Why MySQL source code?

**Comment by GerrMullers** [comment]
or you mean the code from the sql file that was created

**Comment by darold** [comment]
Because from_unixtime() is a mysql function, not Oracle unless they have include it recently.

**Comment by darold** [comment]
About the source code you might have a corresponding file in the source directory: ./sources/views/V_CPU_view.sql

**Comment by GerrMullers** [comment]
this code from sql file created by ora2pg:
-- Generated by Ora2Pg, the Oracle database Schema converter, version 21.1
-- Copyright 2000-2020 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=kzabixapp01.alfa.bank.int;service_name=zabbdb_db.center.kiev.ua.alfabank;port=1521

SET client_encoding TO 'UTF8';

SET search_path = zabbix,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW v_cpu (host, dns, ip, vdate, value_max, value_avg, value_min) AS SELECT h.host, k.dns, k.ip, from_unixtime(a.clock) vdate,
 round((a.value_max)::numeric,2) VALUE_MAX, round((a.value_avg)::numeric,2) VALUE_AVG, round((a.value_min)::numeric,2) VALUE_MIN
FROM zabbix.trends a JOIN zabbix.items i on (a.itemid = i.itemid) join zabbix.hosts h on (i.hostid = h.hostid)
join zabbix.interface k ON (i.hostid = k.hostid)
WHERE i.name = 'Processor Utilization';

**Comment by GerrMullers** [comment]
when I just skipped views and started the migration got it: [2021-07-16 09:38:16] DEBUG: number of rows 90000 extracted from table ALERTS
[2021-07-16 09:38:16] Dumping data from table ALERTS into PostgreSQL table ALERTS...
[2021-07-16 09:38:16] Setting client_encoding to UTF8...
[2021-07-16 09:38:16] Disabling synchronous commit when writing to PostgreSQL...
[2021-07-16 09:38:16] DEBUG: Formatting bulk of 10000 data (real: 10000 rows) for PostgreSQL.
[2021-07-16 09:38:17] DEBUG: Creating output for 10000 tuples
[2021-07-16 09:38:17] DEBUG: Sending COPY bulk output directly to PostgreSQL backend
DBD::Pg::db do failed: ERROR: relation "alerts" does not exist at /usr/local/share/perl5/Ora2Pg.pm line 15766.
[2021-07-16 09:38:17] FATAL: ERROR: relation "alerts" does not exist
Aborting export...

**Comment by darold** [comment]
If I convert this code using the `-m` switch (for MySql code) the function is well converted into
```
to_timestamp("a"."clock")::timestamp without time zone
```
Maybe you have forgotten the -m option when you have run `ora2pg --init_project`, you can verify in the export_schema.sh script if the ora2pg commands have the `-m` option set.

**Comment by darold** [comment]
About your last note, remember that Ora2Pg can only export data directly to PostgreSQL, this means that you have to import the DDL definition from the files generated by ora2pg into your PostgreSQL database. You can also use the script import_all.sh that will do the work with your help.

**Comment by GerrMullers** [comment]
> If I convert this code using the `-m` switch (for MySql code) the function is well converted into
> 
> ```
> to_timestamp("a"."clock")::timestamp without time zone
> ```
> 
> Maybe you have forgotten the -m option when you have run `ora2pg --init_project`, you can verify in the export_schema.sh script if the ora2pg commands have the `-m` option set.

took from history
ora2pg -d -t COPY -o data.sql -b ./data -c ./config/ora2pg.conf

**Comment by GerrMullers** [comment]
> About your last note, remember that Ora2Pg can only export data directly to PostgreSQL, this means that you have to import the DDL definition from the files generated by ora2pg into your PostgreSQL database. You can also use the script import_all.sh that will do the work with your help.

thanks I remember, there were problems with serch_path to the new scheme.

**Comment by GerrMullers** [comment]
at first I used import_all.sh, when manually imported sql files everything looks acceptable

Thank you so much for your help
