### ISSUE TITLE
 ERROR:  cannot truncate a table referenced in a foreign key constraint

### ISSUE THREAD

**Issue by GerrMullers** [darold/ora2pg#1212]
Hi,
Help me please vith error:
[========================>] 151/151 tables (100.0%) end of scanning.
DBD::Pg::db do failed: ERROR:  cannot truncate a table referenced in a foreign key constraint
DETAIL:  Table "alerts" references "acknowledges".
HINT:  Truncate table "alerts" at the same time, or use TRUNCATE ... CASCADE. at /usr/local/share/perl5/Ora2Pg.pm line 3745.
FATAL: ERROR:  cannot truncate a table referenced in a foreign key constraint
DETAIL:  Table "alerts" references "acknowledges".
HINT:  Truncate table "alerts" at the same time, or use TRUNCATE ... CASCADE.
Aborting export...
FATAL: _column_attributes() ORA-03113: end-of-file on communication channel
Process ID: 2167
Session ID: 23 Serial number: 3790 (DBD ERROR: error possibly near <*> indicator at char 90 in 'SELECT A.COLUMN_NAME, A.NULLABLE, A.DATA_DEFAULT, A.TABLE_NAME, A.OWNER, A.COLUMN_ID
FROM <*>ALL_TAB_COLUMNS A, ALL_OBJECTS O WHERE A.OWNER=O.OWNER and A.TABLE_NAME=O.OBJECT_NAME and O.OBJECT_TYPE='TABLE' AND A.TABLE_NAME='ACTIONS' AND A.OWNER='ZABBIX'
ORDER BY A.COLUMN_ID
')
Aborting export...

**Comment by darold** [comment]
Why not enabling DROP_FKEY in ora2Pg.conf?

**Comment by GerrMullers** [comment]
Thank you very much
