### ISSUE TITLE
migration stops at 5.4 Gb

### ISSUE THREAD

**Issue by GerrMullers** [darold/ora2pg#1213]
Hi, 
I have the next problem, the oracle base for migration is 400GB, made several attempts migration always stops at 5.4GB. Tell me where to look for a solution

**Comment by darold** [comment]
Is there is any error message? You should check that the OOM Killer was not fire; use dmesg system command to see if ora2pg have been killed.

**Comment by GerrMullers** [comment]
i have error lice this:
DBD::Pg::db pg_putcopyend failed: ERROR:  no partition of relation "history" found for row
DETAIL:  Partition key of the failing row contains (clock) = (1626672322).
CONTEXT:  COPY history, line 1: "444412 1626672322      45.4689 852735892" at /usr/local/share/perl5/Ora2Pg.pm line 15781.
Aborting export...
ora2pg in memory
 230465 postgre+  20   0 2532148 174384   5076 R  59.0   1.1   0:01.77 ora2pg - sendin
 192408 postgre+  20   0 2508496 165836  20028 S  11.7   1.0   5:05.59 ora2pg - queryi

**Comment by darold** [comment]
Well why not starting the issue with this error message, it is much more obvious than your first post. The error message is explicit you have not imported the necessary partitions into your PG database.

**Comment by GerrMullers** [comment]
I've been unloading tables with this command
ora2pg -d -t TABLE -o data.sql -b ./data -c ./config/ora2pg.conf

**Comment by GerrMullers** [comment]
config parametr
DISABLE_PARTITION       1

**Comment by darold** [comment]
What does `\d history`  executed in psql reports?

**Comment by GerrMullers** [comment]
zabbdb_dn=# \d history
Did not find any relation named "history".

**Comment by darold** [comment]
well it must not be in the public schema, but look if your history table is partitioned or not.

**Comment by GerrMullers** [comment]
zabbdb_dn=# \d zabbix.history
             Partitioned table "zabbix.history"
 Column |     Type      | Collation | Nullable |   Default
--------+---------------+-----------+----------+-------------
 itemid | numeric(20,0) |           | not null |
 clock  | bigint        |           | not null | '0'::bigint
 value  | numeric(20,4) |           | not null | 0.0000
 ns     | bigint        |           | not null | '0'::bigint
Partition key: RANGE (clock)
Indexes:
    "alfa_history$itemid" btree (itemid)
    "history_1" btree (itemid, clock)
Number of partitions: 0

**Comment by darold** [comment]
Then you have a partitioned table but no partition defined. I you don't want to reproduce the partitioning you must enable DISABLE_PARTITION when exporting table. Verify the output file you might have a PARTITION BY clause.

**Comment by GerrMullers** [comment]
I want to try both options

**Comment by GerrMullers** [comment]
I have 4 partitioned table in my database. what i need in conf file  to reproduce the partitioning.

**Comment by darold** [comment]
Disable DISABLE_PARTITION and export using PARTITION action this might be what you are looking for.

**Comment by GerrMullers** [comment]
ora2pg -d -t PARTITION TABLE -o data_part.sql -b ./data -c ./config/ora2pg.conf

I'm right ?

**Comment by GerrMullers** [comment]
is it possible to skip some of the PARTITION during the transfer, and transfer them later

**Comment by darold** [comment]
See EXCLUDE directive.
