### ISSUE TITLE
More parentheses when migrating from oracle sysdate to clock_timestamp() of pg

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1215]
Boa tarde senhor Darold,

Good afternoon Mr Darold,

When migrating a package from oracle to PG using ora2pg, an extra parenthesis was placed in the following line of code that contains a clock_timestamp inside a data_trunc function:

In Pg:

v_tempo_fds:=pck_got_geral.f_obtem_tempo_fds_a_excluir((date_trunc(('minute', clock_timestamp(**()**))), date_trunc(('minute', clock_timestamp(**()**) + v.dias_acrescimo))));

The original line in oracle is as follows:

v_tempo_fds:=pck_got_geral.f_obtem_tempo_fds_a_excluir(TRUNC(SYSDATE,'MI'), TRUNC(SYSDATE + v.dias_acrescimo,'MI'));

Is it possible to validate that this is an error?, Is it possible to analyze only with the following line of code or is it necessary to send the entire function?.

Best regards,

Rui Pereira.

**Comment by darold** [comment]
It looks like it is fixed in current development code because a test give me this output:
```
v_tempo_fds:=pck_got_geral.f_obtem_tempo_fds_a_excluir(date_trunc('minute', clock_timestamp()), date_trunc('minute', clock_timestamp() + v.dias_acrescimo));
```
If you still see the same problem, please post the context if this statement because the issue might come from the lines above or after this one.
