### ISSUE TITLE
Add materialized views to be exported as tables (VIEW_AS_TABLE)

### ISSUE THREAD

**Issue by AwdotiaRomanowna** [darold/ora2pg#1216]
adding the option to export materialized views also not only normal views as tables would be super helpful

**Comment by darold** [comment]
If I understand well you want to export the materialized view as table and not the related tables and data that are used to refresh the materialized view. It need some work but this is doable. I will have a look.

**Comment by subhasniveus** [comment]
@darold was this done? It will be helpful if this was possible. thanks!

**Comment by darold** [comment]
Done now with commit 2a1c9d9.

**Comment by subhasniveus** [comment]
Thanks for the quick update and the feature @darold
