### ISSUE TITLE
Wrong table output in table files when COPY_FREEZE=1

### ISSUE THREAD

**Issue by yonisade** [darold/ora2pg#1218]
ora2pg v22.1

After I changed COPY_FREEZE  to 1 in the config file and ran:
ora2pg -t COPY -b data -c config/ora2pg.conf

at the end of the data export, I noticed that in every file the table name/data actually belonged to the next table in the fetched table list.
the last table file only had a "COMMIT;" command inside it.

output.sql had the proper ALTER TABLE and \i commands though.

**Comment by darold** [comment]
Commit f63c07f fix this issue.
