### ISSUE TITLE
Where clause not wrongly removed by ora2pg.

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1219]
Good afternoon Darold,

When migrating a querie inside a procedure in a package from oracle to pg, I found that ora2pg was not removing a where clause in the wrong way, as shown below:

Oracle code:

OPEN plista FOR
SELECT DISTINCT issue DESIGNACAO
FROM
	 (
          SELECT data_reg, n_avaria_pt ISSUE
          FROM reg_reg r, gtt_ticket_externo t, gtt_avaria_circuito ids
          WHERE r.referencia = t.referencia_sigo
            AND t.id_interface = 60
            AND t.id_ticket_externo is not NULL
            AND r.n_avaria_pt LIKE '%-%'
            AND r.referencia_ttk = ids.referencia(+)
            AND (INSTR(','||pid_servico||',', ','||NVL(r.circuito,ids.n_circuito)||',') > 0 or pid_servico is null) ORDER BY data_reg DESC ) WHERE ROWNUM < 10
        ORDER BY 1 ASC;

Pg Code:

      OPEN plista FOR
SELECT DISTINCT issue DESIGNACAO
FROM (
          SELECT data_reg, n_avaria_pt ISSUE
          FROM gtt_ticket_externo t, reg_reg r
LEFT OUTER JOIN gtt_avaria_circuito ids ON (r.referencia_ttk = ids.referencia)
WHERE r.referencia = t.referencia_sigo AND t.id_interface = 60 AND t.id_ticket_externo is not NULL AND r.n_avaria_pt LIKE '%-%'  AND (position(','||coalesce(r.circuito,ids.n_circuito)||',' in ','||pid_servico||',') > 0 or pid_servico is null) ORDER BY data_reg DESC
				) alias3 **_WHERE_**
        ORDER BY 1 ASC LIMIT 9;

Is it possible to analyze this problem as soon as possible? , the where clause is not needed in the pg query.

Best regards,

Rui Pereira.

**Comment by RuiFilipeGoncalvesPereira** [comment]
Good afternoon Sir Darold,

Can you confirm that this is really an ora2pg conversion error, if so is it possible to fix it?

Best regards,

Rui Pereira.

**Comment by darold** [comment]
Commit c7e8aa0 fixes this issue.
