### ISSUE TITLE
Synonym views with SECURITY DEFINER

### ISSUE THREAD

**Issue by someidiot** [darold/ora2pg#122]
When synonyms are created as views, they have the SECURITY DEFINER clause added. However, as far as I can see this is not a supported clause for CREATE VIEW. It fails for me eg

db=> CREATE VIEW eimuser.seq_teimr_index AS SELECT * FROM eimsysdb.seq_teimr_index SECURITY DEFINER;
ERROR:  syntax error at or near "DEFINER"
LINE 1: ... AS SELECT * FROM eimsysdb.seq_teimr_index SECURITY DEFINER;

PG v9.4.1 but I can't find any version where it is valid.

**Comment by darold** [comment]
Please use latest development code from github, commit 272998a might solve this issue. Thanks for the report.

Regards,

**Comment by someidiot** [comment]
Thanks, that worked.
