### ISSUE TITLE
Ora2pg : Mysql to Postgres DBD::mysql issue

### ISSUE THREAD

**Issue by kirandba-hub** [darold/ora2pg#1222]
Hi,

I'm getting below error while installing the DBD::mysql on Linux server.I downloaded the tar.gz file from cpan website
from the extracted folder i'm giving perl Makefile.PL

# perl Makefile.PL
Can't locate Devel/CheckLib.pm in @INC (@INC contains: /root/PERL_DBI_DBD/lib64/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at Makefile.PL line 12.
BEGIN failed--compilation aborted at Makefile.PL line 12.

Can you please help to resolve the issue.

Thanks,
Kiran

**Comment by darold** [comment]
I guess that since the creation of this issue you have found that Devel::CheckLib Perl module should be installed first. Please reopen the issue if this is not the case, sorry for the response delay.
