### ISSUE TITLE
make procedure sql

### ISSUE THREAD

**Issue by LEE-JONGBEOM** [darold/ora2pg#1224]
Hello I have problem when i make procedure with ora2pg
procedure changes into function
 I found  issue that using
"
        wget https://github.com/darold/ora2pg/archive/master.zip
        unzip master.zip
        cd ora2pg-master
        perl Makefile.PL
        make
        sudo make install
"
will help but it still change to function .
please help thanks

**Comment by darold** [comment]
What is the value of PG_VERSION and PG_SUPPORTS_PROCEDURE in your ora2pg.conf file?

**Comment by LEE-JONGBEOM** [comment]
I found that PG_VERSION was 9.6 and i changed it to 12 and it changes into procedure .
 I have additional questions.
1.  PG_VERSION  lower than 12 doesn't support procedures???
2.  I can not find 'PG_SUPPORTS_PROCEDURE' in  ora2pg.conf  where i can check it??
thanks so much

**Comment by darold** [comment]
I think support to procedure is PG 11 but you have to set PG_VERSION to the major version of the PostgreSQL database where the migration will be done.

**Comment by darold** [comment]
And to answer to your second question PG_SUPPORTS_PROCEDURE is deprecated since the introduction of PG_VERSION, I just want to verify that you was not using an old ora2pg.conf file.
