### ISSUE TITLE
TEXT broken when download procedure.sql

### ISSUE THREAD

**Issue by LEE-JONGBEOM** [darold/ora2pg#1227]
Hello.

I have problem when I use 'ora2pg -p -t PROCEDURE -o procedure.sql -b / -c /etc/ora2pg/ora2pg.conf.'
TEXT bloken like
" i_Ã­ÂÂÃ«Â¡ÂÃ¬Â ÂÃ­ÂÂ¸Ã«ÂªÂ text,    -- jobID
 i_Ã«Â¸ÂÃ«ÂÂ­Ã«ÂªÂ text,    -- jobBlock
 i_Ã¬ÂÂÃ¬ÂÂÃ¬ÂÂ¼ text,        -- Ã¬ÂÂÃ¬ÂÂÃ¬ÂÂ¼
"
Bloken works are korean, I used it in table names and columns.

And it doesn't happen when I use '-t Table'  

I tried to give '--nls_lang' and change ora2config nls_lang 
but still shows broken words 

is there anything i can do more? rather than change all into English?

Please help

Thanks every time

**Comment by darold** [comment]
Honestly using locale in object name is always a bad idea and with Ora2Pg this is the same. If possible post a procedure that I can import in Oracle to see what I can do.

**Comment by darold** [comment]
Commit 4937725 adds new configuration directive FORCE_PLSQL_ENCODING, set it to 0 to change the default behavior might fix this issue.
