### ISSUE TITLE
SDO_COORD_REF_SYS related error.

### ISSUE THREAD

**Issue by kazam** [darold/ora2pg#123]
While running the COPY command on my database I am getting the following error after procesing of most tables. 

DBD::Oracle::db prepare failed: ORA-01741: illegal zero-length identifier (DBD E
RROR: OCIStmtPrepare) [for Statement "SELECT  FROM ""."SDO_COORD_REF_SYS" a"] at
 C:/Perl/site/lib/Ora2Pg.pm line 8779.
FATAL: ORA-01741: illegal zero-length identifier (DBD ERROR: OCIStmtPrepare)
Aborting export...

Thanks much.

**Comment by darold** [comment]
Hi,

Could you please use the latest development code from github or latest 15.2 release and send me back the error message if there's still one?  I think there's no more use of SDO_COORD_REF_SYS for one or two releases now.

Best regards,

**Comment by kazam** [comment]
Hi Darold, 
I used the latest gitHub build and it gives the same error but on a different line (8679 instead of 8779).

DBD::Oracle::db prepare failed: ORA-01741: illegal zero-length identifier (DBD E
RROR: OCIStmtPrepare) [for Statement "SELECT  FROM ""."SDO_COORD_REF_SYS" t"] at
 C:/Perl/site/lib/Ora2Pg.pm line 8679.
FATAL: ORA-01741: illegal zero-length identifier (DBD ERROR: OCIStmtPrepare)

Thanks.

**Comment by darold** [comment]
Could you first set CONVERT_SRID to 0 in your configuration file and then retry the export. If it still fail, please set GEOMETRY_EXTRACT_TYPE value to INTERNAL in your ora2pg.conf file and try again.

Let me know the result.

**Comment by darold** [comment]
What is the value of DEFAULT_SRID in your configuration file or does the line is commented ?

**Comment by kazam** [comment]
It was set to 1 previously. It is currently running with a setting of 0 now.

**Comment by darold** [comment]
Ok, the reason may be that your spatial column has no SRID defined from ALL_SDO_GEOM_METADATA.

Please download latest development code from github, I've just push a commit 98a3630 to try to solve that issue. The error wil still be shown but a warning will be printed after:

    WARNING: Error retreiving SRID, no matter default SRID will be used: 4326

then ora2pg will continue using this value.

Does that fix your issue?

**Comment by kazam** [comment]
Running with new build, will keep you posted with the result. Thank you.

**Comment by kazam** [comment]
Still causing issues, at a different line now. I am going to try setting GEOMETRY_EXTRACT_TYPE value to INTERNAL now.

DBD::Oracle::db prepare failed: ORA-01741: illegal zero-length identifier (DBD E
RROR: OCIStmtPrepare) [for Statement "SELECT  FROM ""."SDO_COORD_REF_SYS" a"] at
 C:/Perl/site/lib/Ora2Pg.pm line 8802.
FATAL: ORA-01741: illegal zero-length identifier (DBD ERROR: OCIStmtPrepare)
Aborting export...

**Comment by darold** [comment]
I have fixed an other case where call to sdo_cs.map_oracle_srid_to_epsg() return an ORA-01741 error but I 'm not sure it will fix your case. Please use latest code again, but your case seems generated by the call to SDO_UTIL.TO_WKBGEOMETRY() where unfortunately I can't do anything. Using INTERNAL should fix the issue. An other simple fix is to add an SRID to the column in ALL_SDO_GEOM_METADATA, that seems to be mandatory.

**Comment by kazam** [comment]
INTERNAL didn't solve the issue. Still getting error as above at line 8802. Will try the latest code and see if I can get a DBA to add SRID to the column in ALL_SDO_GEOM_METADATA. thanks.

**Comment by kazam** [comment]
Now getting same error at different line

DBD::Oracle::db prepare failed: ORA-01741: illegal zero-length identifier (DBD E
RROR: OCIStmtPrepare) [for Statement "SELECT  FROM ""."SDO_COORD_REF_SYS" a"] at
 C:/Perl/site/lib/Ora2Pg.pm line 8808.
FATAL: ORA-01741: illegal zero-length identifier (DBD ERROR: OCIStmtPrepare)
Aborting export...

I have asked DBA to add SRID. Would setting it to Null work. Thanks.

**Comment by kazam** [comment]
It appears that both the table and the view have the SRID column in mdsys schema.

**Comment by darold** [comment]
Yes, this error is generated by the malformed statement "SELECT FROM ""."SDO_COORD_REF_SYS". Unfortunaltely this statement ca not be controled by Ora2Pg, it never use a query on SDO_COORD_REF_SYS, this is done by one of the Oracle function  sdo_cs.map_oracle_srid_to_epsg() or SDO_UTIL.TO_WKTGEOMETRY().  The other problem is that I'm not able to reproduce the issue so I can't look to find a workaround. If you have a dp dump that I can use to reproduce please send it to my private email.

Best regards,

**Comment by kazam** [comment]
Thanks Darold. The issue was resolved by giving some permissions.

**Comment by kennyjoseph** [comment]
Hey @kazam, could you provide a bit more information on what solved this problem, having the same issue  at #124  I believe
