### ISSUE TITLE
schema identification with stored procedure, function

### ISSUE THREAD

**Issue by NishanthBejgam** [darold/ora2pg#1232]
Hi,

requesting your comments about my understanding of this behavior... 

I'm able to perform the code migration for PL/SQL objects like view, procedures, function created with SET search_path='schema_name' using ora2pg.conf file settings and, I understood that with the seach_path set and execute from pgAdmin, the reference tables used in code are created without schema name. tablename for INSERT/SELECT/UPDATE statements... The problem I'm facing with this behavior is without the schema-name added, the logic by default searching at public schema during test runs from different SQL windows. So, I decided to generate the SQL statements by adding the schema name for tables, object calls in code. i.e. eg:  schema_name.tablename in every DML operation statement [ I'm able to achieve this using the tools like Ispirer, SCT .. ] please help how could I able to get this behavior with ora2pg.

attaching the sample code.. and the expectation is highlighted in BOLD case

CREATE OR REPLACE PROCEDURE **oracletopostgres**.select_emp(
	p_empno bigint)
LANGUAGE 'plpgsql'
AS $BODY$
DECLARE

    v_ename         oracletopostgres.employee.firstname%TYPE;
    v_hiredate      oracletopostgres.employee.hiredate%TYPE;
    v_title         oracletopostgres.employee.title%TYPE;
    v_reportsto     oracletopostgres.employee.reportsto%TYPE;
    v_disp_date     varchar(10);
	v_ins_count   bigint;
	city_from varchar(100);
	C record;

BEGIN
    SELECT firstname, hiredate,  coalesce(title, ''), reportsto
        INTO STRICT v_ename, v_hiredate, v_title, v_reportsto
        FROM **TESTSCHEMA.employee**
        WHERE employeeid = p_empno;
    v_disp_date:= TO_CHAR(v_hiredate, 'MM/DD/YYYY');
	
SELECT
    CASE WHEN CITY = 'Calgary' THEN
        'From City of Calgary'
    WHEN CITY = 'Edmonton' THEN
        'From City of Edmonton'
    WHEN CITY = 'Lethbridge' THEN
        'From City of Lethbridge'
    ELSE
        CITY
    END INTO STRICT city_from
FROM
    **TESTSCHEMA.employee**
WHERE
    employeeid = p_empno;

    RAISE NOTICE 'Number    : %', p_empno;
    RAISE NOTICE 'Name      : %', v_ename;
    RAISE NOTICE 'Hire Date : %', v_disp_date;
    RAISE NOTICE 'ReportsTo: %', v_reportsto;
	RAISE NOTICE '%', city_from;
	
	FOR C IN (SELECT A.EMPLOYEEID, A.CTID AS A_ROWID, B.EMPLOYEEID AS RPT_EMPLOYEEID,B.CTID AS B_ROWID
    FROM **TESTSCHEMA.EMPLOYEE** A,
      **TESTSCHEMA.EMPLOYEE** B
    WHERE A.EMPLOYEEID = B.REPORTSTO
    AND A.CTID <> B.CTID ORDER BY A.EMPLOYEEID,B.EMPLOYEEID FETCH FIRST 2 ROWS ONLY)
  LOOP
  	RAISE NOTICE 'id=% Rid= %  A_ROWID=% B_ROWID=%', c.EMPLOYEEID, c.RPT_EMPLOYEEID, c.A_ROWID, c.B_ROWID;
  END LOOP;
  
	DELETE FROM **TESTSCHEMA.employee**
	WHERE BONUS >= 10000000;
	
	INSERT INTO **TESTSCHEMA.employee**(EmployeeId, LastName, FirstName, Title, BirthDate, HireDate, Address, City, State, Country, PostalCode, Phone, Fax, Email,Bonus)
    SELECT DISTINCT E1.EmployeeId, E1.LastName, E1.FirstName, E1.Title, E1.BirthDate, E1.HireDate, E1.Address, E1.City, E1.State, E1.Country, E1.PostalCode, E1.Phone, E1.Fax, E1.Email, E1.Bonus
    FROM  **oracletopostgres.**employee  E1,
            (SELECT employeeid,reportsto,BONUS
    FROM **oracletopostgres.**employee ) E2 WHERE
    E1.employeeid = E2.REPORTSTO
	ON CONFLICT(EmployeeId)
	DO
		UPDATE SET BONUS = EXCLUDED.BONUS * 2;		
	GET DIAGNOSTICS v_ins_count = ROW_COUNT;
	RAISE NOTICE '% inserted/updated into Employee Table', v_ins_count;
	
EXCEPTION
    WHEN no_data_found THEN
        RAISE NOTICE 'Employee % not found', p_empno;
    WHEN OTHERS THEN
        RAISE NOTICE 'The following is SQLERRM:';
        RAISE NOTICE '%', SQLERRM;
        RAISE NOTICE 'The following is SQLSTATE:';
        RAISE NOTICE '%', SQLSTATE;
END;
$BODY$;

**Comment by darold** [comment]
Why not using `ALTER ROLE username SET search_path TO oracletopostgres, public;` or `ALTER DATABASE dbname SET search_path TO oracletopostgres, public;`? This is usually how I fix that.

**Comment by NishanthBejgam** [comment]
Thanks. But, we have the username that spread across multiple schema and some table are repeated among different schemas.. so the idea would be having the scope restricted at lower end for object scope.. please provide suggestions.

**Comment by darold** [comment]
Using sed or Perl you can achieve what you are looking for. Ora2pg use search _path changing to fqdn is too much work.

**Comment by NishanthBejgam** [comment]
Thanks DaroId for the feedback. and Sure, I will definitely give it a try.
