### ISSUE TITLE
bitmap_as_gin fix

### ISSUE THREAD

**Issue by NishanthBejgam** [darold/ora2pg#1233]
Hi Daroid,

I have a use case to convert BITMAP to GIN index, and I figured that bitmap_as_gin=1 is the setting I needed here. To my surprise, after having this set in the config and running ora2pg is not given the GIN index, so, I given a thought to find the reason by visiting Ora2pg.pm module and I found that to make it work the logic in ora2pg.pm requires a fix at line 9509; 

elsif ($self->{bitmap_as_gin} && $self->{$objtyp}{$tbsaved}{idx_type}{$idx}**{type_name}** eq 'BITMAP')

in above line code {type_name} does n't have the value with it, this should be {type} .. 

and the change that worked is - 
elsif ($self->{bitmap_as_gin} && $self->{$objtyp}{$tbsaved}{idx_type}{$idx}**{type}** eq 'BITMAP')

PL/SQL Index 
CREATE TABLE hr_employees (
	employee_id integer,
	first_name varchar(20),
	last_name varchar(25) NOT NULL,
	email varchar(25) NOT NULL,
	phone_number varchar(20),
	hire_date timestamp NOT NULL,
	job_id varchar(10) NOT NULL,
	salary double precision,
	commission_pct real,
	manager_id integer,
	department_id smallint,
	gender varchar(2)
) ;
-- Before Fix - 
CREATE INDEX idx_bitmap_emp_gen ON ot.hr_employees (gender);

--After Fix -
CREATE INDEX idx_bitmap_emp_gen ON ot.hr_employees USING gin(gender); 

 for SPATIAL_INDEX as well this can be changed to {type}

 if ($self->{$objtyp}{$tbsaved}{idx_type}{$idx}**{type}** =~ /SPATIAL_INDEX/) { #CHANGED BY NB

**Comment by darold** [comment]
Right, good catch. Fix with commit a2bbb0c.
