### ISSUE TITLE
Packages are converted to procedures and not functions

### ISSUE THREAD

**Issue by hoflz5** [darold/ora2pg#1237]
Why are my packages converted to Postgresql procedures and not functions?
It seems from the help text that they should be converted to functions.

**Comment by darold** [comment]
This is because they are procedures and they are supported by PG since version 11. If you want to transform procedures in functions you can add `PG_SUPPORTS_PROCEDURE 0` in your configuration file, it should work.

**Comment by hoflz5** [comment]
Excellent, thank you for the quick response. Migration is really good this far.
