### ISSUE TITLE
Issues with MDSYS tables

### ISSUE THREAD

**Issue by kennyjoseph** [darold/ora2pg#124]
Apologies for not being descriptive enough in advance - a perl and Oracle (11g) novice.

Trying to export a set of tables using the command line interface, using a command like:
```ora2pg -c my_dist.dist -t INSERT```

Everything seems to run well until I hit certain tables owned by the MDSYS user.  I then error out with something like the following:

```DBD::Oracle::db prepare failed: ORA-01741: illegal zero-length identifier (DBD ERROR: OCIStmtPrepare) [for Statement "SELECT  FROM ""."SDO_COORD_REF_SYS" a"] at /usr/lib/perl5/site_perl/5.8.8/Ora2Pg.pm line 8808.```

Where SDO_COORD_REF_SYS is owned by MDSYS (this happens with other mdsys tables as well, e.g. ```OLS_DIR_BUSINESSES```). It looks like somehow the mdsys user's name gets replaced, thus leading to the empty schema name, but I can't figure out why that would happen, as mdsys tables shouldn't be being tried to export anyway, right?

Any ideas/leads would be appreciated.

**Comment by darold** [comment]
Hi,

This seams to be the same issue than #123, I guess @kazam can help you to solve it. Have you tried the export using a DBA user? Also you might use COPY instead of INSERT to export your data, insert are very slow at loading time.

 Best regards,

**Comment by kennyjoseph** [comment]
Yes, sorry, opened the issue because #123 referred only to the one table whereas this seems to apply to all mdsys tables. As @kazam said it was a permissions thing I suspect using a dba user might s9lve. Dumb question,  but can you explain how to do so, that is,which user specifically to export with? Is the call something like

Ora2pg sysdba/<pwd> ... ?

**Comment by kennyjoseph** [comment]
Sorry, also, according to documentation shouldn't all mdsys tables be ignored anyway?

**Comment by darold** [comment]
You have some configuration directives called ORACLE_USER and ORACLE_PWD that are used to control the connection user. You must also set the SCHEMA directive to the name of the schema you want to export.For example:

    ORACLE_USER    system
    ORACLE_PWD     manager

The SDO_COORD_REF_SYS is not called directly by Ora2Pg but by Oracle spatial object extraction. Ora2Pg have no control about it and do not have any queries from that table.

**Comment by kennyjoseph** [comment]
Yeah, I was using the system user in the config file, i thought maybe using ```sysdba``` or something might be different. It does seem like ora2pg makes the query (if you look, the error is coming from ora2pg.pm, in the OCIStmtPrepare function, isn't it?) but somehow drops the name mdsys, hence resulting in the ```ORA-01741``` error because the selection contains ```""```.

In ```plsql.pm''' there is a comment ```# Remove any call to MDSYS schema in the code```, which appears to be relevant. In any case, I will be trying to track down a fix and will issue a pull request on the documentation if/when I find one, as #123 shows other people are having similar issues and no actual fix was given. Any other leads that you can think of would be much appreciated, but in the meantime, thank you already for your help!

**Comment by kazam** [comment]
For me specifying the schema value, and having dba permissions is what worked. I don't think you need dba permissions. Sorry, there is nothing more specific that comes to mind.

**Comment by kennyjoseph** [comment]
It looks like specifying the schema solved it for me as well. @darold would it be useful for me to add an emphasis on this to the troubleshooting section of the documentation?

**Comment by darold** [comment]
Yes, please submit a path.

**Comment by Zubeyd55** [comment]
hi,
To get full privilege for the export process. i am trying to connect oracle through ora2pg using sys as sysdba like this    
![ora2pg](https://user-images.githubusercontent.com/39626504/42620593-0994d436-85c4-11e8-9200-94f08ed82f7b.GIF)
but its not working any solution please??

**Comment by darold** [comment]
First of all do not use an old closed issue to post your own, just open a new one!

What you are trying is not possible, use:
```
ORACLE_USER     system
ORACLE_PWD       your_password
```

**Comment by Zubeyd55** [comment]
okay my bad i will remove it
