### ISSUE TITLE
Procedure export fails if it's defined without any parameters

### ISSUE THREAD

**Issue by dirkgently007** [darold/ora2pg#125]
Ora2Pg fails to export procedure from Oracle if Oracle procedure is created without a parameter. The output file contains only headers, but no plpgsql code.

e.g.
Following procedure conversion fails:

    CREATE OR REPLACE PROCEDURE my_proc AS ....

But the same procedure gets exported if it has at least one parameter:

    CREATE OR REPLACE PROCEDURE my_proc (dummy IN varchar2 default 'dummy') AS ....

It seems Ora2Pg expects a procedure to always have parameters or brackets, but it's not always needed in Oracle. It seems the problem exists with the following lines in `_lookup_function` in `Ora2Pg.pm`:

    10351:		if ( ($fct_detail{declare} =~ s/(.*?)\b(FUNCTION|PROCEDURE)\s+([^\s\(]+)\s*(\([^\)]*\))//is) || 
    10352:		($fct_detail{declare} =~ s/(.*?)\b(FUNCTION|PROCEDURE)\s+([^\s\(]+)\s+(RETURN|IS)/$4/is) ) {

**Comment by darold** [comment]
Thanks a lot for the report, commit 4523e60 fix that issue.

Regards,
