### ISSUE TITLE
How to dump 

### ISSUE THREAD

**Issue by Code-UV** [darold/ora2pg#1252]
I have a large table. I want to see whether it can be implemented according to the size of the table exported to different files. For example, when exporting, one file of 5MB can be used to generate multiple export files

**Comment by Code-UV** [comment]
I have a large table. I want to see whether it can be implemented according to the size of the table exported to different files. For example, when exporting, one file of 5MB can be used to generate multiple export files

**Comment by darold** [comment]
I don't understand your question but if you want a dump file per table enable FILE_PER_TABLE in ora2pg.conf
