### ISSUE TITLE
Convert data  type  raw to uuid

### ISSUE THREAD

**Issue by dbaexpertconsulting** [darold/ora2pg#1253]
Hello mister arold
 
I have a data type incompatibility problem when I want to create my foreign keys 
(a column in uuid to a column in bytea)
I used the modify_type parameter of ora2pg raw:uuid
but the script does not convert raw to uuid.
Is it possible to do this modification through ora2pg?
I'm using version 21 of ora2pg

thank you in advance for your feedback and also for your work

**Comment by darold** [comment]
Latest development code include automatic handling of RAW to uuid conversion. Any Oracle column defined as RAW(16) or RAW(32) will be exported as PostgreSQL uuid. This is also true for RAW columns that have SYS_GUID as default value.

The PostgreSQL destination database must have executed `CREATE EXTENSION "uuid-ossp" ;` before importing the objects.

For example Oracle the following definition:
```
CREATE TABLE test_rawtouuid (
        NOM     VARCHAR2(25),
        UID_COL1 RAW(32) DEFAULT SYS_GUID() NOT NULL,
        UID_COL2 RAW(16) NOT NULL,
        UID_COL3 RAW(32) NOT NULL,
        UID_COL4 RAW(255) NOT NULL
);

INSERT INTO test_rawtouuid (NOM, UID_COL2, UID_COL3, UID_COL4) VALUES ('A Name', SYS_GUID(), SYS_GUID(), SYS_GUID());
COMMIT;
```
will be exported by Ora2Pg as follow:
```
CREATE TABLE test_rawtouuid (
	nom varchar(25),
	uid_col1 uuid NOT NULL DEFAULT uuid_generate_v4(),
	uid_col2 uuid NOT NULL,
	uid_col3 uuid NOT NULL,
	uid_col4 bytea NOT NULL
) ;
```
and the data:
```
INSERT INTO test_rawtouuid (nom,uid_col1,uid_col2,uid_col3,uid_col4) 
   VALUES (E'A Name',
        E'CD8353C3F5211CFFE0530100007F8593',
        E'CD8353C3F5221CFFE0530100007F8593',
        E'CD8353C3F5231CFFE0530100007F8593',
        decode(E'CD8353C3F5241CFFE0530100007F8593', 'hex')
    );
```

which result in the following after import:
```
$ psql -d gilles
gilles=# CREATE EXTENSION "uuid-ossp" ;
CREATE EXTENSION
gilles=# \i tmp/table.sql 
SET
CREATE TABLE
ALTER TABLE
gilles=# \i tmp/data.sql 
BEGIN
ALTER TABLE
COMMIT
BEGIN
SET
SET
TRUNCATE TABLE
INSERT 0 1
COMMIT
BEGIN
ALTER TABLE
COMMIT

gilles=# SELECT * FROM test_rawtouuid;
-[ RECORD 1 ]----------------------------------
nom       | A Name
uid_col1 | cd8353c3-f521-1cff-e053-0100007f8593
uid_col2 | cd8353c3-f522-1cff-e053-0100007f8593
uid_col3 | cd8353c3-f523-1cff-e053-0100007f8593
uid_col4 | \xcd8353c3f5241cffe0530100007f8593
```
