### ISSUE TITLE
ORA2PG Export wrong char encoding in Chinese Charset

### ISSUE THREAD

**Issue by rynerisraid** [darold/ora2pg#1256]
Hello darold,
I have a Oracle Database with Chinese Charset, 
for example,
> select userenv('language') from dual;
SIMPLIFIED CHINESE_CHINA.ZHS16GBK

When I converted the structure data from oracle database to postgresql, I found that wrong chinese char encoding in the output *.sql files with right english words.
The perl Interpreter might open files with default encoding: utf-8 while the **Ora2pg.pm** that use the expression:
 **$row->[2] = encode('UTF-8', $row->[2]);** 
to renew the variables by text from query results of **ALL_SOURCE** or **DBA_SOURCE** table

```perl
while (my $row = $sth->fetch) {
  if (!$self->{schema} && $self->{export_schema}) {
    $row->[0] = "$row->[1].$row->[0]";
  }
  # Fix possible Malformed UTF-8 character
  # that might encode two times 
  $row->[2] = encode('UTF-8', $row->[2]);
  # Remove some bargage when migrating from 8i
  $row->[2] =~ s/\bAUTHID\s+[^\s]+\s+//is;
  if (exists $functions{"$row->[0]"}) {
    $functions{"$row->[0]"}{text} .= $row->[2];
  }
}
```

**Comment by darold** [comment]
Commit 4937725 adds new configuration directive FORCE_PLSQL_ENCODING, set it to 0 to change the default behavior might fix this issue. Please give it a try and let me know.

**Comment by rynerisraid** [comment]
it works!
