### ISSUE TITLE
ora2pg_scanner failed to scan mysql table when table name is using reserved word.

### ISSUE THREAD

**Issue by ssung-yugabyte** [darold/ora2pg#1257]
When running ora2pg_scanner against mysql db, we encountered an error when the table name is a reserved world. 

DBD::mysql::st execute failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'release FROM test' at line 1 at /usr/local/share/perl/5.26.1/Ora2Pg/MySQL.pm line 1408.

mysql> select count(*) from 'release';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''release'' at line 1
mysql> select count(*) from "release";
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"release"' at line 1
mysql> select count(*) from \`release\`;
+----------+
| count(*) |
+----------+
| 12000 |
+----------+
1 row in set (3.42 sec)

**Comment by darold** [comment]
Commit 9648d99 fixes this issue.
