### ISSUE TITLE
Ora2pg on SSL enabled PostgreSQL 

### ISSUE THREAD

**Issue by njaf** [darold/ora2pg#1258]
Can ora2pg connect to SSL enabled PostgreSQL databases. We are unable to connect using the tool so just wanted to verify if its supported at the moment. If not supported is there a roadmap?

**Comment by darold** [comment]
It is supported, you should just add sslmode=require to the connection string like follow:
```
ORACLE_DSN      dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521;sslmode=require
```
I will add a note to the documentation.

**Comment by njaf** [comment]
Thankyou for your response.

How do we supply the location of Certificates, are there any parameters?

**Comment by darold** [comment]
Sorry I use the wrong ora2Pg configuration directive, this is PG_DSN, I have fixed the note.

**Comment by darold** [comment]
Sorry I've missed your last note. DBD::Pg is like any libpq client, see https://www.postgresql.org/docs/current/libpq-ssl.html for more information about where certificates will be found at client side.
