### ISSUE TITLE
Error during show_report command

### ISSUE THREAD

**Issue by deepakp555** [darold/ora2pg#1259]
Hi Team,

When we run the show_version and show_report command we get below error. Need your kind attention to resolve it.

C:\ora2pg>ora2pg -t SHOW_VERSION  -c C:\ora2pg\TestSep2021_PMS\config\ora2pg.conf
FATAL: 12170 ... ORA-12170: TNS:Connect timeout occurred (DBD ERROR: OCIServerAttach)

C:\ora2pg>------------------------------Error Message---------------------------------------
WARNING: target PostgreSQL version must be set in PG_VERSION configuration directive. Using default: 11
DBI connect('host=XXXX;Service_Name=XXXX;port=1530','XXXX',...) failed: ORA-12170: TNS:Connect timeout occurred (DBD ERROR: OCIServerAttach) at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 1624.
Aborting export...

FATAL: ORA-03135: connection lost contact
Process ID: 28097
Session ID: 2661 Serial number: 425 (DBD ERROR: error possibly near <*> indicator at char 375 in 'SELECT
    CONS.TABLE_NAME,
    CONS.CONSTRAINT_NAME,
    COLS.COLUMN_NAME,
    CONS_R.TABLE_NAME R_TABLE_NAME,
    CONS.R_CONSTRAINT_NAME,
    COLS_R.COLUMN_NAME R_COLUMN_NAME,
    CONS.SEARCH_CONDITION,CONS.DELETE_RULE,CONS.DEFERRABLE,CONS.DEFERRED,
    CONS.OWNER,CONS.R_OWNER,
    COLS.POSITION,COLS_R.POSITION,
    CONS.VALIDATED
FROM ALL_CONSTRAINTS CONS
    LEFT JOIN <*>ALL_CONS_COLUMNS COLS ON (COLS.CONSTRAINT_NAME = CONS.CONSTRAINT_NAME AND COLS.OWNER = CONS.OWNER AND COLS.TABLE_NAME = CONS.TABLE_NAME)
    LEFT JOIN ALL_CONSTRAINTS CONS_R ON (CONS_R.CONSTRAINT_NAME = CONS.R_CONSTRAINT_NAME AND CONS_R.OWNER = CONS.R_OWNER)
    LEFT JOIN ALL_CONS_COLUMNS COLS_R ON (COLS_R.CONSTRAINT_NAME = CONS.R_CONSTRAINT_NAME AND COLS_R.POSITION=COLS.POSITION AND COLS_R.OWNER = CONS.R_OWNER)
WHERE CONS.CONSTRAINT_TYPE = 'R' AND CONS.OWNER = 'PMS'  AND (  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p1) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p2) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p3) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p4) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p5) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p6) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p7) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p8) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p9) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p10) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p11) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p12) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p13) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p14) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p15) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p16) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p17) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p18) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p19) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p20) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p21) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p22) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p23) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p24) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p25) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p26) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p27) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p28) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p29) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p30) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p31) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p32) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p33) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p34) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p35) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p36) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p37) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p38) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p39) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p40) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p41) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p42) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p43) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p44) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p45) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p46) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p47) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p48) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p49) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p50) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p51) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p52) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p53) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p54) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p55) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p56) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p57) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p58) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p59) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p60) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p61) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p62) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p63) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p64) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p65) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p66) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p67) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p68) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p69) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p70) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p71) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p72) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p73) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p74) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p75) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p76) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p77) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p78) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p79) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p80) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p81) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p82) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p83) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p84) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p85) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p86) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p87) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p88) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p89) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p90) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p91) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p92) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p93) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p94) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p95) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p96) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p97) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p98) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p99) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p100) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p101) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p102) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p103) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p104) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p105) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p106) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p107) 
AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p108) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p109) AND  NOT REGEXP_LIKE(UPPER(CONS.TABLE_NAME), :p110))
ORDER BY CONS.TABLE_NAME, CONS.CONSTRAINT_NAME, COLS.POSITION
')

**Comment by darold** [comment]
What version of ora2pg are you using?

**Comment by deepakp555** [comment]
ora2pg v 21.0

**Comment by darold** [comment]
Ok, it look like you can not connect to the Oracle database, maybe this is the wrong IP address or something wrong in the DSN. You should try to connect using `sqplus` with the same parameters to see if it works. `sqlplus` should be available within the Oracle InstantClient installation path.

You should use latest version v22.1 there is lot of bug fix an improvements.

**Comment by deepakp555** [comment]
We are able to connect with sqlplus. but when runs the ora2pg commnds then only face the error.

**Comment by darold** [comment]
Have you tried to use SID instead of service_name? Something like `ORACLE_DSN    dbi:Oracle:host=192.168.43.19;sid=orcl;port=1521`

**Comment by darold** [comment]
I guess that this has been solved, closing
