### ISSUE TITLE
Undefined subroutine &Ora2Pg::ReadMode called at /usr/local/share/perl/5.30.0/Ora2Pg.pm line 21491

### ISSUE THREAD

**Issue by mperdikeas** [darold/ora2pg#1260]
Using Ora2Pg v22.1 on Ubuntu 20.04, Perl5 (revision 5, version 30, subversion 0).
After running export schema:

    ./export_schema.sh ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg.conf

I run import_all which eventually fails at the last step (copying the actual data). The tables DDL is properly migrated to PostgreSQL, it is the actual data importation that fails at the last step of import_all:

    ora2pg -c config/ora2pg.conf -t COPY --pg_dsn "dbi:Pg:dbname=some_name;;port=5432" --pg_user some_user

The above fails with:

    Undefined subroutine &Ora2Pg::ReadMode called at /usr/local/share/perl/5.30.0/Ora2Pg.pm line 21491.

**Comment by darold** [comment]
The documentation says:
```
        If you do not supply a credential with ORACLE_PWD and you have
        installed the Term::ReadKey Perl module, Ora2Pg will ask for the
        password interactively. If ORACLE_USER is not set it will be asked
        interactively too.
```
when you don't provide a password to ORACLE_PWD Ora2Pg automatically switch to an interactive input that requires an additional Perl module. It is not installed this is why you have the error message of the undefined subroutine.
