### ISSUE TITLE
FATAL: ERROR:  date/time field value out of range: "2004-13-24 00:00:00"

### ISSUE THREAD

**Issue by dataeratr** [darold/ora2pg#1264]
Hi,
First 6-7 millions of rows imported without issue but on one of row facing following error and failed. 
I test many datestyle unfortunately having same result.

Do you have any opinion how can I solve this issue ?
Please note that we dont have any record '2004-13-24' like that.

_DBD::Pg::db pg_putcopyend failed: ERROR:  date/time field value out of range: "2004-13-24 00:00:00"
HINT:  Perhaps you need a different "datestyle" setting.
CONTEXT:  COPY tablename, line 990, column columnname: "2004-13-24 00:00:00" at /usr/share/perl5/Ora2Pg.pm line 16849.
[2021-10-13 12:49:26] FATAL: ERROR:  date/time field value out of range: "2004-13-24 00:00:00"
HINT:  Perhaps you need a different "datestyle" setting.
CONTEXT:  COPY tablename, line 990, column columnname: "2004-13-24 00:00:00"_

Sincerely,
Mehmed

**Comment by darold** [comment]
Maybe you have a corruption in the Oracle table, 2004-**13**-24 is not a valid month.

**Comment by dataeratr** [comment]
Thanks alot for help,
how can it be :)

![Selection_046](https://user-images.githubusercontent.com/74303819/137531605-ada0b371-d05d-4b6c-8bd9-5c02bf24408e.png)
