### ISSUE TITLE
import_all :: sequences/sequence.sql fails because schema is not created yet

### ISSUE THREAD

**Issue by mperdikeas** [darold/ora2pg#1270]
It would seem that there is something wrong in the ordering of tasks in the import_all script.

In the sequences/sequence.sql file I see statements like:

CREATE SEQUENCE schema_name.sequence_name INCREMENT 1 MINVALUE 1 NO MAXVALUE START 1 CACHE 20;

The above statements fail as the schemas have not been created yet by the time the import_all script calls sequence.sql. In my case I see the CREATE SCHEMA statements in file tables/table.sql which comes later in import_all.

**Comment by darold** [comment]
Hi,

Normally current Ora2Pg code adds the create schema statement on top of the sequence export if EXPORT_SCHEMA is enabled and that SCHEMA of PG_SCHEMA are set. I guess that this was not the case at export time. You should add the following on top of the `schema/sequences/sequence.sql` file:
```
CREATE SCHEMA IF NOT EXISTS myschema;
```

**Comment by duursma** [comment]
I am having the same issue.  Where EXPORT_SCHEMA is enabled.  But SCHEMA is not set (as I want 'all' non system schema's) and PG_SCHEMA is also not set as I don't want some default.
But I would still expect that an attempt is made to create a schema before creating a sequence in that schema.
