### ISSUE TITLE
Ora2pg - New Release

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1276]
Good morning Mr Darold,

I come here to contact you because I would like to know if possible when a new version of ora2pg will be released?, if possible, if a new release will still be released by the end of the current year 2021?

Is it possible to confirm also if the last version released was v22.0?	

Best regards,

Rui Pereira.

**Comment by darold** [comment]
Actually version 23.0 have been published.
