### ISSUE TITLE
ERROR: ORA-01555: snapshot too old: rollback segment number

### ISSUE THREAD

**Issue by gvijay07** [darold/ora2pg#1287]
Hi Darlod,

while extracting the data from oracle database using the ora2pg , I got the below error in log file and I see the job got completed. Can we ignore these errors and proceed with import to postgresql database? 

POSTMAN12>cat data.log
ERROR: ORA-01555: snapshot too old: rollback segment number 7 with name "_SYSSMU7$" too small (DBD ERROR: OCIStmtFetch)
ERROR: ORA-01555: snapshot too old: rollback segment number 2 with name "_SYSSMU2$" too small (DBD ERROR: ORA-03111 error on field 6 of 29, ora_type 96)
ERROR: ORA-01555: snapshot too old: rollback segment number 44 with name "_SYSSMU44$" too small (DBD ERROR: OCIStmtFetch)
ERROR: ORA-01555: snapshot too old: rollback segment number 43 with name "_SYSSMU43$" too small (DBD ERROR: ORA-03111 error on field 4 of 7, ora_type 1)
POSTMAN12>

Thanks for your support .

**Comment by darold** [comment]
No you can not ignore this error, you will not have all your data. You have to increase the size of the UNDO file or you can set TRANSACTION to readonly instead of serializable in ora2Pg.conf. You may also want to increase the speed of the data transfert by using multiprocess on a Linux box.

**Comment by gvijay07** [comment]
Sure Darlod. Thanks for the response on this.
