### ISSUE TITLE
Problems Migrating Packages Ora2pg - Conversion error when calling a procedure that is declared/created inside the package itself – problem still presists on version 23.0

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1289]
Good night darold,

I come here in contact because ora2pg is generating an error when invoking procedures created within the same packages in which they are called, probably they are being assumed wrongly with functions? because the select clause and the into clause are placed before and after its invocation receptively.

As I understand it should have already been resolved in the commit a334e50, however I have already installed and configured version 23.0 and as visible by the example below the problem remains:

**Package Oracle:**
```
CREATE OR REPLACE PACKAGE BODY pck_w_tra_con_consultas_wfm IS
	PROCEDURE sp_listas_seguranca
	(
		pcoderro OUT NUMBER,
		pmsgerro OUT VARCHAR2,
		pidutil IN NUMBER,
		pididioma IN NUMBER,
		psubsistema IN VARCHAR2,
		ppontocontrolo IN VARCHAR2,
    pexistencias IN NUMBER,
		plst_equipa OUT cursorType
	)
	IS
		vcoderro PLS_INTEGER;
		vmsgerro VARCHAR2(4000);
		verror_backtrace varchar2(4000);
	BEGIN
/*CALL*/ sp_equipa(pcoderro => vcoderro,pmsgerro => vmsgerro,pidutil => pidutil,pididioma => pididioma,psubsistema => psubsistema,ppontocontrolo => ppontocontrolo,pexistencias => pexistencias,plista => plst_equipa);
	EXCEPTION
    WHEN OTHERS THEN
      pcoderro := SQLCODE;
      pmsgerro := SQLERRM;
verror_backtrace := DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
      /*CALL*/ LOGGER.ERROR('PCK_W_TRA_CON_CONSULTAS_WFM.SP_LISTAS_SEGURANCA','ERRO; [SQLCODE]=' ||pcoderro ||' ; [SQLERRM]=' || pmsgerro|| '; [BACKTRACE]=' || verror_backtrace);  pcoderro := 2;
      pmsgerro := pck_tra_erros.f_msg_erro(pcoderro, pididioma);
	END sp_listas_seguranca;

	-- Obter lista de equipas
	-------------------------------------------------------------------------------------------------
	PROCEDURE sp_equipa
	(
		pcoderro OUT NUMBER,
		pmsgerro OUT VARCHAR2,
		pidutil IN NUMBER,
		pididioma IN NUMBER,
		psubsistema IN VARCHAR2,
		ppontocontrolo IN VARCHAR2,
		pexistencias IN NUMBER,
		plista OUT cursorType
	)
	IS
 vidioma_sistema PLS_INTEGER := pck_tra_hash.f_valor('IDIOMA_SISTEMA');
vid_subsistema tra_sca_subsistema.id%TYPE;
vid_pi tra_sca_ponto_intermedio.id%TYPE;
BEGIN
    	pcoderro :=0;
	pmsgerro :='OK';

IF (ppontocontrolo IS NOT NULL) THEN
SELECT ss.id INTO vid_subsistema FROM tra_sca_subsistema ss WHERE ss.designacao = psubsistema AND ss.id_idioma = vidioma_sistema;
SELECT DISTINCT pi.id INTO vid_pi FROM tra_sca_ponto_intermedio pi WHERE pi.designacao = ppontocontrolo AND pi.id_subsistema = vid_subsistema;
			-- Aplica-se segurança
OPEN plista FOR
	SELECT id, designacao, existencias, tudo
	FROM
	 (
	SELECT DISTINCT g.id, g.designacao, 1 existencias, cod_dg TUDO
	FROM cfg_equipa g,
            (
                SELECT cod_dg cod_dg
                  , COUNT(1) OVER (PARTITION BY cod_familia_dg, cod_dg) C
                  , COUNT(1) OVER (PARTITION BY cod_familia_dg) C1
                FROM tra_glb_tmp_util_acessos
                WHERE cod_familia_dg = 3
            ) sca
	WHERE( g.id_sca = sca.cod_dg
	OR
	 (sca.cod_dg = '-1' AND sca.c = sca.c1)))
	ORDER BY NLSSORT(designacao,'NLS_SORT=WEST_EUROPEAN') ASC;
		ELSE
-- Não se aplica segurança
OPEN plista FOR
SELECT g.id, g.designacao, 1 existencias, -1 TUDO
FROM cfg_equipa g
ORDER BY NLSSORT(g.designacao,'NLS_SORT=WEST_EUROPEAN') ASC;
END IF;
  EXCEPTION
WHEN OTHERS THEN
pcoderro:=SQLCODE;
pmsgerro:=SQLERRM;
/*CALL*/ LOGGER.ERROR('pck_w_tra_con_consultas_wfm.sp_equipa','Erro na query; [SQLCODE]=' ||pcoderro ||' ; [SQLERRM]=' || pmsgerro);
pcoderro := 2;
pmsgerro := pck_tra_erros.f_msg_erro(pcoderro, pididioma);
END sp_equipa;
END pck_w_tra_con_consultas_wfm;
/
```
**Package Postgres;**
```
create or replace procedure pck_w_tra_con_consultas_wfm.sp_listas_seguranca ( pcoderro inout numeric, pmsgerro inout text, pidutil numeric, pididioma numeric, psubsistema text, ppontocontrolo text, pexistencias numeric, plst_equipa inout refcursor ) as $body$
DECLARE
_ora2pg_r RECORD;
vcoderro numeric;
vmsgerro varchar(4000);
VERROR_BACKTRACE VARCHAR(4000);
BEGIN
CALL
 **SELECT * FROM pck_w_tra_con_consultas_wfm.sp_equipa**(pcoderro => vcoderro, pmsgerro => vmsgerro, pidutil => pidutil, pididioma => pididioma, psubsistema => psubsistema, ppontocontrolo => ppontocontrolo, pexistencias => pexistencias, plista => plst_equipa) **INTO STRICT _ora2pg_r; pcoderro => vcoderro := _ora2pg_r.pcoderro; pmsgerro => vmsgerro := _ora2pg_r.pmsgerro; plista => plst_equipa := _ora2pg_r.plista;**
EXCEPTION
    WHEN OTHERS THEN
      pcoderro := SQLSTATE;
      pmsgerro := SQLERRM;
GET STACKED DIAGNOSTICS VERROR_BACKTRACE = PG_EXCEPTION_CONTEXT;
 CALL
 LOGGER.ERROR('PCK_W_TRA_CON_CONSULTAS_WFM.SP_LISTAS_SEGURANCA()','ERRO; [SQLSTATE]=' ||PCODERRO ||' ; [SQLERRM]=' || PMSGERRO|| '; [BACKTRACE]=' || VERROR_BACKTRACE);
      pcoderro := 2;
      pmsgerro := pck_tra_erros.f_msg_erro(pcoderro, pididioma);
END;
$body$
LANGUAGE PLPGSQL;

create or replace procedure pck_w_tra_con_consultas_wfm.sp_equipa ( pcoderro inout numeric, pmsgerro inout text, pidutil numeric, pididioma numeric, psubsistema text, ppontocontrolo text, pexistencias numeric, plista inout refcursor ) as $body$
DECLARE
vidioma_sistema numeric := pck_tra_hash.f_valor('IDIOMA_SISTEMA');
vid_subsistema tra_sca_subsistema.id%TYPE;
vid_pi tra_sca_ponto_intermedio.id%TYPE;
BEGIN
pcoderro :=0;
pmsgerro :='OK';
IF (ppontocontrolo IS NOT NULL) THEN
SELECT ss.id INTO STRICT vid_subsistema FROM tra_sca_subsistema ss WHERE ss.designacao = psubsistema AND ss.id_idioma = vidioma_sistema;
SELECT DISTINCT pi.id INTO STRICT vid_pi FROM tra_sca_ponto_intermedio pi WHERE pi.designacao = ppontocontrolo AND pi.id_subsistema = vid_subsistema;
-- Aplica-se segurança
OPEN plista FOR
SELECT id, designacao, existencias, tudo
FROM
 (
SELECT DISTINCT g.id, g.designacao, 1 existencias, cod_dg TUDO
FROM cfg_equipa g,
            (
                SELECT cod_dg cod_dg
                  , COUNT(1) OVER (PARTITION BY cod_familia_dg, cod_dg) C
                  , COUNT(1) OVER (PARTITION BY cod_familia_dg) C1
                FROM tra_glb_tmp_util_acessos
                WHERE cod_familia_dg = 3
            ) sca WHERE (
g.id_sca = sca.cod_dg OR (sca.cod_dg = '-1' AND sca.c = sca.c1)
)) alias7
ORDER BY DESIGNACAO COLLATE "az-Latn-AZ-x-icu" ASC;
ELSE
-- Não se aplica segurança
OPEN plista FOR
SELECT g.id, g.designacao, 1 existencias, -1 TUDO
FROM cfg_equipa g
ORDER BY G.DESIGNACAO COLLATE "az-Latn-AZ-x-icu" ASC;
END IF;
  EXCEPTION
WHEN OTHERS THEN
pcoderro:=SQLSTATE;
pmsgerro:=SQLERRM;
CALL LOGGER.ERROR('PCK_W_TRA_CON_CONSULTAS_WFM.SP_EQUIPA()','ERRO NA QUERY; [SQLSTATE]=' ||PCODERRO ||' ; [SQLERRM]=' || PMSGERRO);
pcoderro := 2;
pmsgerro := pck_tra_erros.f_msg_erro(pcoderro, pididioma);
END;
$body$
LANGUAGE PLPGSQL
;
```
You can confirm that it is really an ora2pg error.

Best regards,

Rui Pereira.

**Comment by darold** [comment]
Commit f56d7e5 fixes the problem of named parameters used after procedure . The call is now translated into:
```
SELECT * FROM pck_w_tra_con_consultas_wfm.sp_equipa(pcoderro => vcoderro, pmsgerro => vmsgerro, pidutil => pidutil, pididioma => pididioma, psubsistema => psubsistema, ppontocontrolo => ppontocontrolo, pexistencias => pexistencias, plista => plst_equipa) INTO STRICT _ora2pg_r;
 vcoderro := _ora2pg_r.pcoderro; vmsgerro := _ora2pg_r.pmsgerro; plst_equipa := _ora2pg_r.plista;
```

**Comment by RuiFilipeGoncalvesPereira** [comment]
Good afternoon darold,

Considering your answer to this ticket, there is still one question that I would like to see clarified, after the f5d7e5 commit, the pck_w_tra_con_consultas_wfm.sp_equipa procedure call, to be converted to the following by ora2pg:

SELECT * FROM pck_w_tra_con_consultas_wfm.sp_equipa(pcoderro => vcoderro, pmsgerro => vmsgerro, pidutil => pidutil, pididioma => pididioma, psubsistema => psubsistema, ppontocontrolo => ppontocontrolo, pexistencias => pexistencias, plista => plst_equipa) INTO STRICT _ora2pg_r;
 vcoderro := _ora2pg_r.pcoderro; vmsgerro := _ora2pg_r.pmsgerro; plst_equipa := _ora2pg_r.plista;

However, wouldn't the conversion that had to be done be the following, since it was a procedure?

Call pck_w_tra_con_consultas_wfm.sp_equipa(pcoderro => vcoderro, pmsgerro => vmsgerro, pidutil => pidutil, pididioma => pididioma, psubsistema => psubsistema, ppontocontrolo => ppontocontrolo, pexistencias => pexistencias, plista => plst_equipa);

Because that's the only way to avoid the error.

ERROR: pck_w_tra_con_consultas_wfm.sp_equipa(pcoderro => numeric, pmsgerro => text, pidutil => integer, pididioma => integer, psubsistema => unknown, ppontocontrolo => unknown, pexistencias => integer, plista => refcursor) is a procedure LINE 1: SELECT * FROM pck_w_tra_con_consultas_wfm.sp_equipa(pcoderro... 

^ HINT: To call a procedure, use CALL. QUERY: SELECT * FROM pck_w_tra_con_consultas_wfm.sp_equipa(pcoderro => vcoderro, pmsgerro => vmsgerro, pidutil => 1, pididioma => 1, psubsistema => '14', ppontocontrolo => '22,23', pexistencias => 0, plista => plst_equipa) CONTEXT: PL/pgSQL function inline_code_block line 10 at SQL statement SQL state: 42809

Best regards,

Rui Pereira.

**Comment by darold** [comment]
Right, but unfortunately I still not have the time to add support to new PG 14 feature for procedure with out parameters. I think this is what you are reporting. I will try to work on this in the next weeks.

**Comment by RuiFilipeGoncalvesPereira** [comment]
Good evening Mr Darold,

The problem I'm trying to report is the following procedure pck_w_cfg_consultas_ot.sp_type_ot_papers_equipa visible in the code excerpt below in oracle, must be invoked with the call clause on the PG side, as procedures must be invoked with call in PG.
The problem is that when converted by ora2pg, it is invoked with the SELECT * FROM clause which is wrong from my point of view, do you agree?, In nowdays I still to using 12.4 pg version.
-------------------------------------------------ORACLE------------------------------------------------------------------
	PROCEDURE sp_dominios_re_oe_rv
	(
		pcoderro OUT NUMBER,
		pmsgerro OUT VARCHAR2,
		pid_util IN NUMBER,
		pid_idioma IN NUMBER,
		pidtipo_ot IN cfg_tipo_ot.id%TYPE,
		plistaoe OUT CURSORTYPE,
		plistare OUT CURSORTYPE,
		plistarv OUT CURSORTYPE
	)
	IS
    	vre_princ CURSORTYPE;
	vrv_princ CURSORTYPE;
	vlista_oe CURSORTYPE;
BEGIN
        pcoderro := 0;
        pmsgerro := 'OK';
    --Obtém REs,RVs,OEs
    pck_w_cfg_consultas_ot.sp_tipo_ot_papeis_equipa(pcoderro => pcoderro,
                                                  pmsgerro => pmsgerro,
                                                  pidutil => pid_util,
                                                  pididioma => pid_idioma,
                                                  pinactivos => pck_tra_def_ext.cn_inactivo,
                                                  pid_tipo_ot => pidtipo_ot,
                                                  plista_re_prin => vre_princ,
                                                  plista_re_sec => plistare,
                                                  plista_oe => vlista_oe,
                                                  plista_rv_prin => vrv_princ,
                                                  plista_rv_sec => plistarv);
  EXCEPTION
    WHEN OTHERS THEN
      pcoderro:=SQLCODE;
      pmsgerro:=SQLERRM;
      LOGGER.ERROR('PCK_W_CFG_CONSULTAS_OT.SP_DOMINIOS_RE_OE_RV','ERRO: [SQLCODE]=' || pcoderro || '; [SQLERRM]=' || pmsgerro || '; [BACKTRACE]=' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
      pcoderro := 2;
      pmsgerro := pck_tra_erros.f_msg_erro(pcoderro, pid_idioma);
  END sp_dominios_re_oe_rv;
-------------------------------------------POSTGRESQL--------------------------------------------------------------
create or replace procedure pck_w_cfg_consultas_ot.sp_dominios_re_oe_rv ( pcoderro inout numeric, pmsgerro inout text, pid_util numeric, pid_idioma numeric, pidtipo_ot cfg_tipo_ot.id%type, plistaoe inout refcursor, plistare inout refcursor, plistarv inout refcursor ) as $body$
DECLARE
ora2pg_r RECORD;
vre_princ refcursor;
vrv_princ refcursor;
vlista_oe refcursor;
VERROR_BACKTRACE VARCHAR(4000);
BEGIN
    pcoderro := 0;
    pmsgerro := 'OK';
    --Obtém REs,RVs,OEs
    SELECT * FROM pck_w_cfg_consultas_ot.sp_tipo_ot_papeis_equipa(pcoderro => pcoderro, pmsgerro => pmsgerro, pidutil => pid_util, pididioma => pid_idioma, pinactivos => 1, pid_tipo_ot => pidtipo_ot, plista_re_prin => vre_princ, plista_re_sec => plistare, plista_oe => vlista_oe, plista_rv_prin => vrv_princ, plista_rv_sec => plistarv) INTO STRICT _ora2pg_r; pcoderro => pcoderro := _ora2pg_r.pcoderro; pmsgerro => pmsgerro := _ora2pg_r.pmsgerro; plista_re_prin => vre_princ := _ora2pg_r.plista_re_prin; plista_re_sec => plistare := _ora2pg_r.plista_re_sec; plista_oe => vlista_oe := _ora2pg_r.plista_oe; plista_rv_prin => vrv_princ := _ora2pg_r.plista_rv_prin; plista_rv_sec => plistarv := _ora2pg_r.plista_rv_sec;
  EXCEPTION
    WHEN OTHERS THEN
      pcoderro:=SQLSTATE;
      pmsgerro:=SQLERRM;
GET STACKED DIAGNOSTICS verror_backtrace = PG_EXCEPTION_CONTEXT;
LOGGER.ERROR('PCK_W_CFG_CONSULTAS_OT.SP_DOMINIOS_RE_OE_RV()','ERRO: [SQLSTATE]=' || PCODERRO || '; [SQLERRM]=' || PMSGERRO || '; [BACKTRACE]=' || verror_backtrace);
 pcoderro := 2;
 pmsgerro := pck_tra_erros.f_msg_erro(pcoderro, pid_idioma);
  END;
$body$
LANGUAGE PLPGSQL;

Any other question I am available,

Best regards,

Rui Pereira.

**Comment by darold** [comment]
Ora2Pg now supports PG 14 feature for procedure with out parameters. It is automatically enabled using PG_VERSION set to 14 or by enabling PG_SUPPORTS_OUTPARAM. About the procedure above and the use in PG12 maybe you should rewrite this procedure as function. Here using CALL you will not be able to retrieve the out values.
