### ISSUE TITLE
Issues with Type and Sequence

### ISSUE THREAD

**Issue by Yasir1811** [darold/ora2pg#1291]
Hi Darold,
I am converting Oracle schemas to Postgres. I have few issues I am facing with ora2pg.

1) The ora2pg is skipping invalid objects. What is the way to include them also.
2) ora2pg is skipping some sequences by the name ISEQ$$_1234 (there are 24 of them), even in sql developer I can't fetch the ddl but the sequences are visible in user_sequences and user_objects
3) When ora2pg converts type from oracle to postgres, it did not remove oracle specific keywords that are not valid in postgres:

Oracle:
create or replace TYPE sql_varying IS VARRAY(4) OF VARCHAR2(20) NOT NULL;

Ora2PG Convertible:
CREATE TYPE sql_varying AS (sql_varying varchar(20) NOT NULL[4]);

As you see, NOT NULL in postgres is not supported still ora2pg adds it .

Can you please provide some solutions to my queries?

Regards,
Yasir

**Comment by darold** [comment]
1) Enable EXPORT_INVALID to also export invalid object.
2) this is probably sequences for auto generated columns like identity columns, they don't have to be exported.
3) Commit 39cd5f6 fixes the issue.
