### ISSUE TITLE
LOG_ON_ERROR not working as expected

### ISSUE THREAD

**Issue by herwigg** [darold/ora2pg#1292]
Hi 
I have a conf with LOG_ON_ERROR=1 but ora2pg fails anyway when selecting data from Oracle. The conf file excludes a few tables but copies alphabetically the data of all other tables ( a few dozen) to postgres. 
This is the error:
DEBUG: Query sent to Oracle: SELECT "ID","LAST_CHANGE","IS_DELETED","DECIDER_PER_ID","DECISION","DECISION_TIMESTAMP","ORIGINAL_BOX_NUMBER","ORIGINAL_CITY_ID","ORIGINAL_LAND_REG_CODE","ORIGINAL_STREET","ORIGINAL_STREET_NUMBER","PROPOSED_BOX_NUMBER","PROPOSED_CITY_ID","PROPOSED_LAND_REG_CODE","PROPOSED_STREET","PROPOSED_STREET_NUMBER","REAL_ESTATE_ID","REQUEST_TIMESTAMP","REQUESTER_PER_ID","ORIGINAL_ALLOTMENT_LOT_NUMBER","ORIGINAL_ALLOTMENT_NAME","PROPOSED_ALLOTMENT_LOT_NUMBER","PROPOSED_ALLOTMENT_NAME","CREATION_TS","HANDLE_ID","USER_COMMENT" FROM "NCTR_VLA_PRD_ADM"."REAL_ESTATE_MOD_REQ" a
[2021-11-19 11:57:31] Fetching all data from REAL_ESTATE_MOD_REQ tuples...
[2021-11-19 11:57:31] DEBUG: number of rows 723 extracted from table REAL_ESTATE_MOD_REQ
[2021-11-19 11:57:31] Dumping data from table REAL_ESTATE_MOD_REQ into PostgreSQL table REAL_ESTATE_MOD_REQ...
[2021-11-19 11:57:31] Setting client_encoding to UTF8...
[2021-11-19 11:57:31] Disabling synchronous commit when writing to PostgreSQL...
[2021-11-19 11:57:31] DEBUG: Formatting bulk of 10000 data (real: 723 rows) for PostgreSQL.
[2021-11-19 11:57:31] DEBUG: Creating output for 10000 tuples
[2021-11-19 11:57:31] DEBUG: Sending COPY bulk output directly to PostgreSQL backend
DBD::Pg::db do failed: ERROR:  column "original_land_reg_code" of relation "real_estate_mod_req" does not exist at /root/perl5/lib/perl5/Ora2Pg.pm line 14482.
[2021-11-19 11:57:31] FATAL: ERROR:  column "original_land_reg_code" of relation "real_estate_mod_req" does not exist
Aborting export...
DBD::Oracle::db prepare failed: ORA-03113: end-of-file on communication channel
Process ID: 40233
Session ID: 20 Serial number: 14265 (DBD ERROR: OCIStmtExecute/Describe) [for Statement "SELECT A.COLUMN_NAME, A.NULLABLE, A.DATA_DEFAULT, A.TABLE_NAME, A.OWNER, A.COLUMN_ID
FROM DBA_TAB_COLUMNS A, ALL_OBJECTS O WHERE A.OWNER=O.OWNER and A.TABLE_NAME=O.OBJECT_NAME and O.OBJECT_TYPE='TABLE' AND A.TABLE_NAME='REAL_ESTATE_RELATION' AND A.OWNER='NCTR_VLA_PRD_ADM'
ORDER BY A.COLUMN_ID
"] at /root/perl5/lib/perl5/Ora2Pg.pm line 9474.
[2021-11-19 11:57:33] FATAL: _column_attributes() ORA-03113: end-of-file on communication channel
Process ID: 40233
Session ID: 20 Serial number: 14265 (DBD ERROR: OCIStmtExecute/Describe)
Aborting export...
And that's it, I can start all over again... Which takes a lot of (elapsed) time. 

Now I presume by settings LOG_ON_ERROR=1 this directive is set meaning that ora2pg should continue on error.
I have following settings in my conf file:
 TYPE            COPY
TRUNCATE_TABLE  1
DATADIFF        0
SKIP    indexes
STOP_ON_ERROR           0
COPY_FREEZE             0
LOG_ON_ERROR            1
JOBS            2
ORACLE_COPIES   1
PARALLEL_TABLES 1
DEFAULT_PARALLELISM_DEGREE      0
PG_VERSION      11

All tables in Postgres are created beforehand. We only migrate data, no functions or indexes. 
Which parameter should I set to continue on this kind of error. 

Thank you,

Herwig

**Comment by darold** [comment]
Hi,

You can not continue, visibly you don't have the same columns on both sides. Can you post the description of table "real_estate_mod_req" in PostgreSQL (`\d real_estate_mod_req`)?

**Comment by herwigg** [comment]
Hi I see you have closed this issue but ora2pg is copying approx 100 tables. Surely ora2pg can continue with the next table in the list, Otherwise what is the use of LOG_ON_ERROR 
This is the table in Postgres:

ctr_vla_stg=# \d real_estate_mod_req
                           Table "nctr_vla_stg.real_estate_mod_req"
            Column             |            Type             | Collation | Nullable | Default
-------------------------------+-----------------------------+-----------+----------+---------
 id                            | bigint                      |           |          |
 last_change                   | timestamp without time zone |           |          |
 is_deleted                    | character(1)                |           |          |
 creation_ts                   | timestamp without time zone |           |          |
 handle_id                     | bigint                      |           |          |
 request_timestamp             | timestamp without time zone |           |          |
 decision                      | character varying(4000)     |           |          |
 decision_timestamp            | timestamp without time zone |           |          |
 user_comment                  | character varying(4000)     |           |          |
 real_estate_id                | bigint                      |           |          |
 requester_per_id              | bigint                      |           |          |
 decider_per_id                | bigint                      |           |          |
 original_allotment_lot_number | character varying(4000)     |           |          |
 original_allotment_name       | character varying(4000)     |           |          |
 original_box_number           | character varying(4000)     |           |          |
 original_city_id              | bigint                      |           |          |
 original_street               | character varying(4000)     |           |          |
 original_street_number        | character varying(4000)     |           |          |
 proposed_allotment_lot_number | character varying(4000)     |           |          |
 proposed_allotment_name       | character varying(4000)     |           |          |
 proposed_box_number           | character varying(4000)     |           |          |
 proposed_city_id              | bigint                      |           |          |
 proposed_street               | character varying(4000)     |           |          |
 proposed_street_number        | character varying(4000)     |           |          |


In Oracle there were two extra columns but these ahve been dropped in the mean time: (the columns zere not being used)

alter table REAL_ESTATE_MOD_REQ drop column ORIGINAL_LAND_REG_CODE;
alter table REAL_ESTATE_MOD_REQ drop column PROPOSED_LAND_REG_CODE;

I would like that ora2pg continues with the next table since the configuration files is used to copy data for the bulk of the tables and not stop on this error.

**Comment by darold** [comment]
The use of LOG_ON_ERROR is to write to file all chunk of data that was can not be imported into PostgreSQL. All other successful data import will continue, only the one failing are logged to the file so that you can look at it to find what is wrong or edit the file to import it manually. This only concern some data import failure, here you have a difference of structure so every import will fail and LOG_ON_ERROR is not useful at all.

In your case if I understand well you have dropped two column in PG so you need to instruct Ora2Pg that there is a difference in the table structure.  See MODIFY_STRUCT.
