### ISSUE TITLE
When exception occurs,  Date data  has multiple single quotes

### ISSUE THREAD

**Issue by xinjirufen** [darold/ora2pg#1296]
Hi，
When using insert statement, if an exception occurs, the Date type data in the generated insert statement has multiple single quotes
Ora2pg version: v23.0

[oracle_ddl.txt](https://github.com/darold/ora2pg/files/7594883/oracle_ddl.txt)
[oracle_dml.txt](https://github.com/darold/ora2pg/files/7594884/oracle_dml.txt)
[USER1_error.log](https://github.com/darold/ora2pg/files/7594886/USER1_error.log)
[ora2pg_conf.txt](https://github.com/darold/ora2pg/files/7594899/ora2pg_conf.txt)

**Comment by darold** [comment]
What does `perl -e 'use Ora2Pg; print $Ora2Pg::VERSION, "\n";'` return?

Actually with your samples to reproduce and the same configuration I'm unable to reproduce the issue. Here is the output:
```
$ ora2pg -c config/ora2pg.conf -t INSERT -b tmp -o data.sql -a USER1
[========================>] 1/1 tables (100.0%) end of scanning.    
[========================>] 9/1 rows (900.0%) Table USER1 (9 recs/sec)
[========================>] 9/1 total rows (900.0%) - (0 sec., avg: 9 recs/sec).
[========================>] 1/1 rows (100.0%) on total estimated data (1 sec., avg: 1 recs/sec)
gilles@gilles-MS-7A33:/home/git/test_ora2pg/test-db$ cat tmp/data.sql 

BEGIN;
ALTER TABLE "USER1" DISABLE TRIGGER USER;

SET client_encoding TO 'UTF8';
SET synchronous_commit TO off;

TRUNCATE TABLE "USER1";
INSERT INTO "USER1" ("ID","NAME","BIRTHDAY") VALUES (1,'1','2021-11-24 00:00:00');
INSERT INTO "USER1" ("ID","NAME","BIRTHDAY") VALUES (2,'2','2021-11-24 00:00:00');
INSERT INTO "USER1" ("ID","NAME","BIRTHDAY") VALUES (3,'3',NULL);
INSERT INTO "USER1" ("ID","NAME","BIRTHDAY") VALUES (11,'11',NULL);
INSERT INTO "USER1" ("ID","NAME","BIRTHDAY") VALUES (12,'12',NULL);
INSERT INTO "USER1" ("ID","NAME","BIRTHDAY") VALUES (13,'13',NULL);
INSERT INTO "USER1" ("ID","NAME","BIRTHDAY") VALUES (20,'20',NULL);
INSERT INTO "USER1" ("ID","NAME","BIRTHDAY") VALUES (23,'23',NULL);
INSERT INTO "USER1" ("ID","NAME","BIRTHDAY") VALUES (24,'24',NULL);

ALTER TABLE "USER1" ENABLE TRIGGER USER;
COMMIT;
```

**Comment by xinjirufen** [comment]
> perl -e 'use Ora2Pg; print $Ora2Pg::VERSION, "\n";'

 if an exception occurs，the Date type data in the errorlog file contains multiple single quotes. For example, ''2021-11-24 00:00:00''

**Comment by xinjirufen** [comment]
> What does `perl -e 'use Ora2Pg; print $Ora2Pg::VERSION, "\n";'` return?
> 
> Actually with your samples to reproduce and the same configuration I'm unable to reproduce the issue. Here is the output:
> 
> ```
> $ ora2pg -c config/ora2pg.conf -t INSERT -b tmp -o data.sql -a USER1
> [========================>] 1/1 tables (100.0%) end of scanning.    
> [========================>] 9/1 rows (900.0%) Table USER1 (9 recs/sec)
> [========================>] 9/1 total rows (900.0%) - (0 sec., avg: 9 recs/sec).
> [========================>] 1/1 rows (100.0%) on total estimated data (1 sec., avg: 1 recs/sec)
> gilles@gilles-MS-7A33:/home/git/test_ora2pg/test-db$ cat tmp/data.sql 
> 
> BEGIN;
> ALTER TABLE "USER1" DISABLE TRIGGER USER;
> 
> SET client_encoding TO 'UTF8';
> SET synchronous_commit TO off;
> 
> TRUNCATE TABLE "USER1";
> INSERT INTO "USER1" ("ID","NAME","BIRTHDAY") VALUES (1,'1','2021-11-24 00:00:00');
> INSERT INTO "USER1" ("ID","NAME","BIRTHDAY") VALUES (2,'2','2021-11-24 00:00:00');
> INSERT INTO "USER1" ("ID","NAME","BIRTHDAY") VALUES (3,'3',NULL);
> INSERT INTO "USER1" ("ID","NAME","BIRTHDAY") VALUES (11,'11',NULL);
> INSERT INTO "USER1" ("ID","NAME","BIRTHDAY") VALUES (12,'12',NULL);
> INSERT INTO "USER1" ("ID","NAME","BIRTHDAY") VALUES (13,'13',NULL);
> INSERT INTO "USER1" ("ID","NAME","BIRTHDAY") VALUES (20,'20',NULL);
> INSERT INTO "USER1" ("ID","NAME","BIRTHDAY") VALUES (23,'23',NULL);
> INSERT INTO "USER1" ("ID","NAME","BIRTHDAY") VALUES (24,'24',NULL);
> 
> ALTER TABLE "USER1" ENABLE TRIGGER USER;
> COMMIT;
> ```

if an exception occurs，the Date type data in the errorlog file contains multiple single quotes. For example, ''2021-11-24 00:00:00''

**Comment by darold** [comment]
Ah ok this is in the error output log, I will check that.

**Comment by darold** [comment]
Got it, commit 882f9cc fixes this issue.
