### ISSUE TITLE
bug when index names are suffixed with "_idx" (during importation)

### ISSUE THREAD

**Issue by mperdikeas** [darold/ora2pg#1297]
Using ora2pg v23.0 when importing from Oracle to Postgresql, after schema, tables etc have been created, upon importing data directly from Oracle I get a failure with the following trace:

Would you like to import MVIEW from ./schema/mviews/mview.sql? [y/N/q] 
Would you like to import SYNONYM from ./schema/synonyms/synonym.sql? [y/N/q] 
Would you like to import DIRECTORY from ./schema/directories/directorie.sql? [y/N/q] 
Would you like to process indexes and constraints before loading data? [y/N/q] y
Would you like to import TRIGGER from ./schema/triggers/trigger.sql? [y/N/q] 
Would you like to import GRANT from ./schema/grants/grant.sql? [y/N/q] 
Would you like to import TABLESPACE from ./schema/tablespaces/tablespace.sql? [y/N/q] 
Would you like to import data from Oracle database directly into PostgreSQL? [y/N/q] y
Running: ora2pg -c config/ora2pg.conf -t COPY --pg_dsn "dbi:Pg:dbname=anon;host=192.168.2.6;port=5432" --pg_user mperdikeas
WARNING: Enforcing KEEP_PKEY_NAMES to 1 as USE_TABLESPACE is enabled.
[========================>] 1061/1061 tables (100.0%) end of scanning.                              
DBD::Pg::db do failed: ERROR:  syntax error at or near "_idx"
LINE 7: ...NDEX IF EXISTS "crnt2020"."enst20_petype_nvl2(tsy,1,0)"_idx;
                                                                  ^ at /usr/local/share/perl/5.30.0/Ora2Pg.pm line 8305.
FATAL: ERROR:  syntax error at or near "_idx"
LINE 7: ...NDEX IF EXISTS "crnt2020"."enst20_petype_nvl2(tsy,1,0)"_idx;
                                                                  ^
Aborting export...
ERROR: an error occurs when importing data.

In my ora2pg.conf I have:

INDEXES_SUFFIX		_idx
INDEXES_RENAMING	1

**Comment by darold** [comment]
Can you post the Oracle DDL of the index please?

**Comment by mperdikeas** [comment]
Would you please accept it as an attachment? I am not sure I have the right
to post it online.
Curiously I couldnt find an index with the exact name on Oracle:

    DBD::Pg::db do failed: ERROR:  syntax error at or near "_idx"
    LINE 6: ...NDEX IF EXISTS "crnt2020"."enst20_petype_nvl2(tsy,1,0)"_idx;

The closest thing is a table crnt2020.ENST20_PETYPE whose DDL
(including indices) I attach.
Please accept my thanks and my apologies for being reluctant to post online.
Menelaos Perdikeas.

**Comment by darold** [comment]
Yes please sent it to my private email < gilles AT darold DOT net >

**Comment by darold** [comment]
The index name is probably wrong so find all the indexes related to the table and post their DDL

**Comment by darold** [comment]
Ok, got it. Commit 738ddb2 might fix this issue.

**Comment by mperdikeas** [comment]
[735ddb2](https://github.com/darold/ora2pg/commit/738ddb2c1fb38d8a8e95577349df5c59814931a0) indeed changes the behavior but a new, different failure occurs during the same phase of "import_all" (i.e. during direct importation from Oracle). I *think* the new failure occurs further down the road. I'll send you the original Oracle and the corresponding PostgreSQL DDL to your private email.

**Comment by darold** [comment]
Commit b7bf50e fixes the comma problem.

**Comment by mperdikeas** [comment]
I confirm that in my case, commit [b7bf50e](https://github.com/darold/ora2pg/commit/b7bf50efa5af766ca4b5b262901b8c14b1d94911) gets me past that point. There are additional failures of same broad type (mangled index names), further down the data importation attempt, but I am going to log them as new issue(s) unless you instruct me to the contrary.
