### ISSUE TITLE
mangled (?) index name causing direct importation from Oracle to fail

### ISSUE THREAD

**Issue by mperdikeas** [darold/ora2pg#1299]
This appears to be an issue similar to [1297](https://github.com/darold/ora2pg/issues/1297). The exact same circumstances and timing of the failure (during direct importation from Oracle). Oracle and PostgreSQL DDL files will be sent directly to the creator. Trace is:

Would you like to import MVIEW from ./schema/mviews/mview.sql? [y/N/q] 
Would you like to import SYNONYM from ./schema/synonyms/synonym.sql? [y/N/q] 
Would you like to import DIRECTORY from ./schema/directories/directorie.sql? [y/N/q] 
Would you like to process indexes and constraints before loading data? [y/N/q] y
Would you like to import TRIGGER from ./schema/triggers/trigger.sql? [y/N/q] 
Would you like to import GRANT from ./schema/grants/grant.sql? [y/N/q] 
Would you like to import TABLESPACE from ./schema/tablespaces/tablespace.sql? [y/N/q] 
Would you like to import data from Oracle database directly into PostgreSQL? [y/N/q] y
Running: ora2pg -c config/ora2pg.conf -t COPY --pg_dsn "dbi:Pg:dbname=anon;host=192.168.2.6;port=5432" --pg_user mperdikeas
WARNING: Enforcing KEEP_PKEY_NAMES to 1 as USE_TABLESPACE is enabled.
[========================>] 1061/1061 tables (100.0%) end of scanning.                              
DBD::Pg::db do failed: ERROR:  syntax error at or near "_idx"
LINE 4: DROP INDEX IF EXISTS "nphistory_'day'accesstime"_idx;
                                                        ^ at /usr/local/share/perl/5.30.0/Ora2Pg.pm line 8078.
FATAL: ERROR:  syntax error at or near "_idx"
LINE 4: DROP INDEX IF EXISTS "nphistory_'day'accesstime"_idx;
                                                        ^
Aborting export...
ERROR: an error occurs when importing data.

**Comment by darold** [comment]
Right, I should have though that other non numeric character could be present. Fixed with commit c3a6c05, thanks.

**Comment by mperdikeas** [comment]
I confirm it does fix it in my case.
