### ISSUE TITLE
The  priority for export table.

### ISSUE THREAD

**Issue by vu-bm** [darold/ora2pg#130]
Hi all,
When i import data to PostgresDB, some table have relation to another table, they must have data from other table if want to import.
Although understand but I have not figured out how to configure to export data to file *.sql which some table need to import data first and some after.
In that case I had make 2 file ora2pg.conf. First one export require data of table, and import it first.

So I wonder in ora2pg have configure of priority for export data table?

Thanks you so much.
I am special thanks to Mr Gilles Darold, ora2pg is wonderful project!

**Comment by darold** [comment]
Hi,

The better way is to import data and only after that create the constraint and indexes. See FILE_PER_CONSTRAINTS and FILE_PER_INDEXES directives. This will prevent the dependency issue and will improve data load speed.

If you don't want to restart from the begining you can enable DROP_FKEY and DROP_INDEXES for data import, they will be dropped before loading data and recreated after import is finished.

Best regards,

**Comment by vu-bm** [comment]
Hi Mr Darold,
Thanks you so much for your quick reply!

This is really useful directives. It help me solve the problem. 

Cause by I had find export CONSTRAINTS and INDEXES in export section. But it stay in import section. So I will read carefully all directives in configure file.

After all, 
I am thanks you about everything,
Vu-BM
