### ISSUE TITLE
"master" data importation files that don't exist in the case of partitioned tables.

### ISSUE THREAD

**Issue by mperdikeas** [darold/ora2pg#1300]
(the terminology I am using may be inaccurate)

I am using ora2pg version v23.0 commit c3a6c05

I created an Oracle to PostgreSQL migration project. I first created the project with:

`ora2pg -c ora2pg.conf --project_base . --init_project anon`

I then used the [export_schema.sh] script.
Following that, I did:

 `   ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg.conf`

... so as to have the data locally available on the hard disk; Finally I am trying to import the data into PostgreSQL using the [import_all.sh] script.

Now, the original Oracle database contains partitions and I have the following partition-related flags in my ora2pg.conf:
```
PREFIX_PARTITION	1
PREFIX_SUB_PARTITION	1
DISABLE_PARTITION	0
```

When trying to import the data I get failures because the top-level data/datal.sql script includes loading calls to files that don't exist at all. This happens once per partitioned table (in some cases AFAICS) and only for the master table (so to speak). E.g. in the top-level data/data.sql I will see calls like the following:
```

\i ./data/sometable_data.sql
\i ./data/sometable_data_ID_001.sql
\i ./data/sometable_data_ID_002.sql
\i ./data/sometable_data_ID_003.sql
\i ./data/sometable_data_ID_004.sql
( 96 more statements follow one for each of the remaining partition tables)
```

During importation the script fails because the top level file (sometable_data.sql) does not exist at all. The "partition-level" files all exist so what I end up doing is that I remove the line with the top-level table and run the process again. But I have too many tables to do that efficiently. I was hoping this is something that can be fixed, or perhaps I need to change something in my settngs.

**Comment by darold** [comment]
Got it, commit 839e36e might fix this issue.
