### ISSUE TITLE
pgsql conversion of SQL%ROWCOUNT when part of a string concatenation

### ISSUE THREAD

**Issue by boubou191911** [darold/ora2pg#1301]
Hello,

I am busy to convert some stored procedures.

I remarked than when ora2pg encounters something like:
```
iCntGuidUpdated := iCntGuidUpdated + SQL%ROWCOUNT;
```
This is converted by using an intermediary variable ora2pg_rowcount, which is very nice.
```
GET DIAGNOSTICS ora2pg_rowcount = ROW_COUNT;
 iCntGuidUpdated := iCntGuidUpdated +  ora2pg_rowcount;
```

However when the SQL%ROWCOUNT is part of a string concatenation this conversion does not occur.
```
serrormsg := SQL%ROWCOUNT || ' request timed out ; ';
```
is converted to:
```
GET DIAGNOSTICS serrormsg = ROW_COUNT || ' request timed out ; ';
```
which is a syntax error.

I agree the above statement is maybe not very nice but correct for Oracle.
Maybe it is something that can be improved.

Regards.

**Comment by darold** [comment]
Commit e35d447 might fix this issue.
