### ISSUE TITLE
Conversion of a type declaration inside the declare section of a plsql procedure

### ISSUE THREAD

**Issue by boubou191911** [darold/ora2pg#1302]
Hello,

In Oracle it is possible to define [a type inside the declare section of a procedure](https://docs.oracle.com/database/121/LNPLS/block.htm).
Something like:
```
TYPE SAVED_GUIDS_t IS VARRAY(100) OF VARCHAR2(40 BYTE);
```

I am very new to postgres but I don't see any equivalent in pgsql. 
ora2pg does not perform any conversion on this and this causes error at procedure creation (invalid type name).

I don't know if this issue is already known. It is certainly not straightforward to convert. At least this limitation could be mentioned in the doc (if not already done).

Regards.

**Comment by darold** [comment]
Before the procedure declaration Ora2Pg should have prepend a CREATE TYPE statement.

**Comment by boubou191911** [comment]
Ok. Apparently it did not perform the conversion, I see not CREATE TYPE and the TYPE..IS remains as is. I'll test further on to try to discover where it is blocking.

**Comment by darold** [comment]
If you want you sent me the DDL to my private email < gilles AT darold DOT net > so that I can check what's going wrong.

**Comment by darold** [comment]
Commit c77e586 fixes the issue.
