### ISSUE TITLE
Issue with EXTEND oracle method

### ISSUE THREAD

**Issue by Hanane-Amghar** [darold/ora2pg#1303]
Hello, 
In my oracle database , I have this function convert where I used oracle extend method : 
CREATE OR REPLACE FUNCTION convert (plst text, sym text) RETURNS STRTOTABLE AS $body$
DECLARE
        lString       varchar(35567) := plst || sym;
        lCommaIndex  integer;
        lIndex        integer := 1;
        lTab          StrToTable := StrToTable();

BEGIN
        LOOP
                lCommaIndex := INSTR(lString, sym, lIndex); 
                lTab.EXTEND;
                lTab(lTab.COUNT) := SUBSTR(lString, lIndex, lCommaIndex - lIndex);
                lIndex := lCommaIndex + 1;
        END LOOP;
        RETURN lTab;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;

**And while using ora2pg I had this error : 

 SET
psql:/tmp/data_function.sql:34: ERROR:  syntax error at or near "("
LINE 13:   lTab.EXTEND; 
                    
--> Is there any configuration I need to do so that ora2pg doesn't create this error aside from changing the function in oracle database ?

**Comment by darold** [comment]
I guess you can just remove the line with `lTab.EXTEND;` PostgreSQL automatically allocate the necessary memory to store at `lTab.COUNT`. Ora2Pg could probably do that automatically, I will have a look.

**Comment by Hanane-Amghar** [comment]
Okey, I'll wait for your reply. 
Thank you : )

**Comment by Hanane-Amghar** [comment]
This is not the only time I had this issue, I'm currently having a similar one with a procedure while trying to use UTL_FILE package: 

CREATE OR REPLACE PROCEDURE importsauvegarde (fic_name text) AS $body$
DECLARE

        nResource       varchar(200) := fic_name;
        nLog            varchar(200) := nResource||'_SQLEXEC.log';
        fResource       utl_file.file_type;
        fLog            utl_file.file_type;

        lResource       varchar(2000);
BEGIN
        -- ouverture du fichier ressources
        fResource := UTL_FILE.FOPEN('RFC2DIR', nResource, 'R', 32767);
        fLog := UTL_FILE.FOPEN('RFC2DIR', nLog, 'W');
        EXECUTE 'ALTER SESSION SET nls_date_format = ''YYYY-MM-DD''';
        SELECT TO_CHAR(clock_timestamp(),'DD-MM-YYYY HH24:MI:SS') INTO STRICT tmpVar2;
        UTL_FILE.PUT_LINE(fLog, '=== INJECTION DES DATA SAUVEGARDE MISS DANS RFC2 ===');
        UTL_FILE.PUT_LINE(fLog, '['||tmpVar2||'] debut du script pour le fichier '||nResource);

LOOP
        UTL_FILE.GET_LINE(fResource, lResource);

        -- augmentation du compteur
   .......

--> when I try to import this procedure , I'm getting this message : 
[opprqpra-b:postgres:pgserver01]$ psql -d providence -U postgres -f /tmp/data_RFC2_procedure.sql
SET
CREATE PROCEDURE
psql:/tmp/data_RFC2_procedure.sql:585: ERROR:  schema "utl_file" does not exist
LINE 6:  fResource       UTL_FILE.FILE_TYPE;
                         ^
--> Is there any configuration/solution I should do to avoid this error pls?

**Comment by darold** [comment]
I don't see call to EXTEND in the DDL code of your last post. It don't seems to be the same issue, the correct github use is to open an other issue to avoid confusion.

**Comment by Hanane-Amghar** [comment]
I deleted the line with EXTEND and I had an ERROR with STRTOTABLE  type , 
It appears that ora2pg doesn't know the type/package that belongs to ORACLE.

**Comment by darold** [comment]
I guess that STRTOTABLE is a custom data type so it must exist in the database first. But looking deeper at this procedure it seems that it should return a SETOF varchar and you should use RETURN NEXT in the LOOP it I have well understood. So you  can totally remove the use of an array.

**Comment by Hanane-Amghar** [comment]
Alright, I'll update the function.
Thank you

**Comment by Hanane-Amghar** [comment]
Hello , 
I createdd this type :  CREATE TYPE strtotable AS (strtotable varchar(500)[]);

And I updated the function : 

CREATE OR REPLACE FUNCTION convertstrtotable (p_list text, symbol text) RETURNS STRTOTABLE AS $body$
DECLARE

        lString       varchar(32767) := p_list || symbol;
        lCommaIndex  integer;
        lIndex        integer := 1;
        lTab          strtotable := strtotable();

BEGIN
        LOOP
                lCommaIndex := INSTR(lString, symbol, lIndex);
                EXIT WHEN lCommaIndex = 0;
                lTab(lTab.COUNT) := SUBSTR(lString, lIndex, lCommaIndex - lIndex);
                lIndex := lCommaIndex + 1;
        END LOOP;
        RETURN lTab;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION convertstrtotable (p_list text, symbol text) FROM PUBLIC;

But I still git this error: 
psql:/images/ora2pg/RFC2/data_RFC2_FUNCTION.sql:33: ERROR:  syntax error at or near "lTab"
LINE 13:   lTab(lTab.COUNT) := SUBSTR(lString, lIndex, lCommaIndex - ..

Could you help me with this ?

**Comment by darold** [comment]
You probably want to use array_length instead of COUNT to populate your array.

**Comment by Hanane-Amghar** [comment]
I updated the function : 
CREATE OR REPLACE FUNCTION convertstrtotable (p_list text, symbol text) RETURNS STRTOTABLE AS $body$
DECLARE

        lString       varchar(32767) := p_list || symbol;
        lCommaIndex  integer;
        lIndex        integer := 1;
        lTab          strtotable := strtotable();

BEGIN
        LOOP
                lCommaIndex := INSTR(lString, symbol, lIndex);
                EXIT WHEN lCommaIndex = 0;
                array_length(lTab,1) := SUBSTR(lString, lIndex, lCommaIndex - lIndex);
                lIndex := lCommaIndex + 1;
        END LOOP;
        RETURN lTab;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION convertstrtotable (p_list text, symbol text) FROM PUBLIC;

But I still have this error : 

$psql -d rfc2 -U postgres -f /images/ora2pg/RFC2/data_RFC2_FUNCTION.sql
SET
psql:/images/ora2pg/RFC2/data_RFC2_FUNCTION.sql:33: ERROR:  syntax error at or near "array_length"
LINE 13:   array_length(lTab,1) := SUBSTR(lString, lIndex, lCommaInde...
           ^
