### ISSUE TITLE
Issues while exporting the table ending with $ symbol.

### ISSUE THREAD

**Issue by mukesh3388** [darold/ora2pg#1306]
Hi Team, 

I have a oracle database which has a schema X and it has a lot of tables which ends with $ symbol. for Example the tablename in oracle -: 

MDRT_2069B0$
MDXT_1D9006$
MDXT_2069B0$
MDXT_487BC$

while using ora2pg tool , these tables has not been exported including the data. So i would like to know that whether it is possible to export these tables wusing the ora2pg tool from oracle to postgres.

Please help on this

**Comment by darold** [comment]
Hi,

Do you know what these tables are and are you really sure you want to export them? The Oracle optimizer creates these tables when gathering stats on spatial objects I think you don't want them in PG as they will not be used. This is the reason why Ora2Pg automatically exclude them from the export.
