### ISSUE TITLE
Data Sync after transferring the historical data

### ISSUE THREAD

**Issue by deepakp555** [darold/ora2pg#1307]
I have to migrate a oracle db to PostgreSQL. I am wondering how would i sync the data once the historical data has been transferred in PostgreSQL using ora2pg migration scripts. Does the ora2pg support the syncing of live data from oracle to PostgreSQL If not the n is there any way to sync the data.

**Comment by darold** [comment]
Normally you have imported the historic data using some WHERE clause so for live data you also have to use the correct WHERE clause to not load historical data again. Or if they were on dedicated table, just exclude these table from the export.
