### ISSUE TITLE
some (few) tables are not created at all in schema/tables/table.sql

### ISSUE THREAD

**Issue by mperdikeas** [darold/ora2pg#1308]
I am migrating an Oracle database to PostgreSQL using Ora2Pg v23.0.
My workflow is:

1. ora2pg -c ora2pg.conf --project_base . --init_project xfiles
2. cd xfiles && ./export_schema.sh

Out of approx 1000 Oracle tables, 16 end up not present at all in schema/tables/table.sql (I get 16 tables less in PostgreSQL).
It is not clear to me what is the crucial characteristic they all share that causes this behavior. I append below the Oracle DDL of one of them (anonymizing certain columns) and I'll be happy to email the full original DDL of all tables should the project maintainer so require.

So here's an Oracle table that was not present at all in schema/tables/table.sql

    CREATE TABLE "schemaname"."tablename" 
       (	"COLUMN_A" VARCHAR2(30), 
         	"COLUMN_B" VARCHAR2(9), 
                "COLUMN_C NUMBER(12,0)
        ) SEGMENT CREATION IMMEDIATE 
       PCTFREE 10 PCTUSED 0 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
       STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
      PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
     TABLESPACE "TABLESPACENAME" ;

**Comment by darold** [comment]
By default all tables matching the following regexp are not exported because they are kind of system tables. and will not be used in PostgreSQL What is the exact name of the table not exported?
```
@EXCLUDED_TABLES = ('USLOG\$_.*', 'MLOG\$_.*', 'RUPD\$_.*', 'MDXT_.*', 'MDRT_.*', 'MDRS_.*', 'DR\$.*', 'CLI_SWP\$.*', 'LOGMNR\$.*', 'REPCAT\$.*', 'JAVA\$.*', 'AQ\$.*', 'BIN\$.*', 'SDO_GR_.*', '.*\$JAVA\$.*', 'PROF\$.*', 'TOAD_PLAN_.*', 'SYS_.*\$', 'QUEST_SL_.*');
```

**Comment by mperdikeas** [comment]
I just emailed you the list of all (16) tables not exported. What puzzled
me is that these tables are located in a user-defined schema. TBH I wasn't
aware that system tables can exist in user defined schemas.

**Comment by darold** [comment]
Got it, some tables are excluded by the regexp above for the other ones I guess that they are either temporary table or tables auto-generated. Are you sure that there are tables used by your application?

**Comment by mperdikeas** [comment]
Hi, I 've a couple of questions:
In the documentation, there is no mention of an EXCLUDED_TABLES primitive, nor its default value. The closest thing I can find is the EXCLUDE primitive but it does not seem to be specific to tables. Also, in the ora2pg.conf file we read the following:

```
    # Set which object to exclude from export process. By default none. 
    ...
    #EXCLUDE	OTHER_TABLES

```

I.e. it is stated that the default value is none, and not the string of regexps you provided. Also, it is not clear to me what is the interplay between the ALLOW and the EXCLUDE primitives. If an object (table) matches both, is it exported or not?

Finally, there are definitely some tables that are neither system-related, nor temporary and they don't seem to match the regexps you provide above and yet, they are still not exported. I am going to sent you the DDL for a couple of them.
Thank you for your awesome support.

**Comment by mperdikeas** [comment]
Upon further investigation it turns out that the remaining tables which were neither system-related, nor temporary were actually materialized views and they were dropped in some earlier part of my custom pipeline (built on top of ora2pg) as they were using database links to remote database that I couldn't recreate in PostgreSQL. So apologies for the false alarm.
This being said, if there is any more clarity you can provide on my questions on the EXCLUDED_TABLES, ALLOW and EXCLUDE primitives that'd be very welcome but regardless, you can close this issue with my thanks.

**Comment by darold** [comment]
The ALLOW directive is tested first, if the same object is declared in EXCLUDE then the exclusion will not be taken in account. The @EXCLUDED_TABLES array is internally defined and can not be modified, it is always applied, obviously when ALLOW is not defined.
