### ISSUE TITLE
FATAL: ORA-03113: end-of-file on communication channel

### ISSUE THREAD

**Issue by first-leon** [darold/ora2pg#131]
Hello.

Where i use PARALLEL_TABLES 1 all ok, base dumping.
Where i set PARALLEL_TABLES more than 1 (between 2 and 12), i see in log this:
```
....
FATAL: ORA-01001: invalid cursor (DBD ERROR: OCIStmtExecute)
...
FATAL: ORA-03113: end-of-file on communication channel
...
FATAL: ORA-03135: connection lost contact 
...
FATAL: ORA-03135: connection lost contact 
...
```

I use:
* Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
* ora2pg-15.2
* Ubuntu 12.04 amd64
* Perl v5.14.2

It is bug?

**Comment by vu-bm** [comment]
Hi first-leon,

I'm new here, I don't have the answer of your question, but I see on [ora2pg document](http://ora2pg.darold.net/config.html) a explan about PARALLEL_TABLES directive:
> PARALLEL_TABLES
This directive is used to defined the number of tables that will be processed in parallel for data extraction. The limit is the number of cores on your machine. Ora2Pg will open one database connection for each parallel table extraction. This directive, when upper than 1, will invalidate ORACLE_COPIES but not JOBS, so the real number of process that will be used is PARALLEL_TABLES * JOBS.
Note that this directive when set upper that 1 will also automatically enable the FILE_PER_TABLE directive if your are exporting to files.


So how many cores on your machine?

Nice day,
Vu-bm

**Comment by first-leon** [comment]
Hello.
In have 2 machine for ora2pg.
In first machine i have 3 cernel (openvz container).
In second machine i have 12 core (openvz container).

**Comment by darold** [comment]
Sorry for the response delay, I'm travelling. To be honest, the PARALLEL_TABLE feature have not widely been tested be me so a bug is possible. Vu-bm has also pointed you to a problem that could be related to the number of core you are using. Could you post here the command line you are using and the value of PARALLEL_TABLES and JOBS from your configuration file?

Regards,

**Comment by first-leon** [comment]
Yes!
I install ora2pg to KVM virtual machine and all work Ok!
In the OpenVZ (Proxmox) container is not work, but it is not problem.
Please write this information in documentation for new users.

Thank you!
