### ISSUE TITLE
Question about BULK COLLECT

### ISSUE THREAD

**Issue by boubou191911** [darold/ora2pg#1311]
Hello,

This is more a question than an issue.

In oracle the BULK COLLECT operation can be applied on a SELECT or a FETCH.
There is no real equivalent in postgres and I understand this case is too complex to be handled automatically by ora2pg.
There are several articles explaining options to implement an equivalent in postgres.
I was just wondering if the ora2pg community already faced this kind of conversion and what is the best way to handle it after an ora2pg transformation.

Regards.

**Comment by darold** [comment]
You can easily replace BULK COLLECT by using arrays, there is plenty of examples available.
