### ISSUE TITLE
likely problem in Oracle 2 PostgreSQL translation of formula index

### ISSUE THREAD

**Issue by mperdikeas** [darold/ora2pg#1313]
Migrating an Oracle database to PostgreSQL using Ora2Pg v23.0

In Oracle I have an index on a table with the following DDL:

    CREATE INDEX "schema_name"."index_name" ON "schema_name"."table_name" (2020000000000000+"FOO_ID")

... where "FOO_ID" is a column on table "table_name" of type NUMBER(12,0)

After running 
    ora2pg -c ora2pg.conf --project_base . --init_project xfiles && cd xfiles
    ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg.conf

I see that the generated DDL in data/data.sql for this index is the following:

    CREATE INDEX table_name_2020000000000000foo_id_idx ON schema_name.table_name ("2020000000000000+foo_id") TABLESPACE tablespace_name;

... which fails when I run the ./import_all.sh script with:

    psql:./data/data.sql:10463: ERROR:  column "2020000000000000+foo_id" does not exist

I believe the DDL should be generated as follows:

    CREATE INDEX table_name_2020000000000000foo_id_idx ON schema_name.table_name ((2020000000000000+foo_id)) TABLESPACE tablespace_name;

**Comment by darold** [comment]
Commit ec58b68 might fix this issue.
