### ISSUE TITLE
Undefined subroutine &Ora2Pg::Oracle::min called at C:/Strawberry/perl/site/lib/Ora2Pg/Oracle.pm line 431.

### ISSUE THREAD

**Issue by nicscanna** [darold/ora2pg#1321]
Hi all,

As mentioned in subject, I'm trying to export an orcl schema but I get the following error:

**Undefined subroutine &Ora2Pg::Oracle::min called at C:/Strawberry/perl/site/lib/Ora2Pg/Oracle.pm line 431.**

```perl
if (($row->[7] || 0) > 10) {
			$tables_infos{$row->[1]}{fillfactor} = 100 - min(90, $row->[7]);
}
```

Did I miss any lib to install?
Thanks in advance for your support

**Comment by darold** [comment]
Which version of Ora2Pg are you running: `ora2pg -v`

**Comment by nicscanna** [comment]
Hi darold,

This is my version: Ora2Pg v23.0

**Comment by darold** [comment]
Ok got it, new commit aa4cf31 might fix this issue.

**Comment by nicscanna** [comment]
It works. Thanks a lot, darold
