### ISSUE TITLE
 FATAL: _column_attributes() ORA-00028: your session has been killed

### ISSUE THREAD

**Issue by IgorM12** [darold/ora2pg#1327]
Hi!

Copy to sql process abort via strange error:
[2021-12-11 00:37:49] FATAL: _column_attributes() ORA-00028: your session has been killed (DBD ERROR: error possibly near <*> indicator at char 103 in 'SELECT A.COLUMN_NAME, A.NULLABLE, A.DATA_DEFAULT, A.TABLE_NAME, A.OWNER, A.COLUMN_ID, A.DATA_TYPE
FROM <*>ALL_TAB_COLUMNS A, ALL_OBJECTS O WHERE A.OWNER=O.OWNER and A.TABLE_NAME=O.OBJECT_NAME and O.OBJECT_TYPE='TABLE' AND A.TABLE_NAME='LMS2_PATTERN' AND A.OWNER='MYUSER'
ORDER BY A.COLUMN_ID
')
Aborting export...

What does this error mean?

Thank  you!

Best Regards
Igor

**Comment by darold** [comment]
Someone or something kills the Ora2Pg query to scan the column attributes table on oracle side.

**Comment by IgorM12** [comment]
Thanx!

I found issue - PGA limit is exceeded in Oracle.
Message from alert.log: 
PGA memory used by the instance exceeds PGA_AGGREGATE_LIMIT of 4096 MB                                                                                                                        KILL SESSION for sid=(255, 38136):                                                                                                                                                              Reason = pga_aggregate_limit                                                                                                                                                                  Mode = KILL HARD SAFE -/-/-                                                                                                                                                                   Requestor = DBRM (orapid = 14, ospid = 2018, inst = 1)                                                                                                                                        Owner = Process: USER (orapid = 66, ospid = 30396)                                                                                                                                            Result = ORA-31                                                                                                                                                                             2021-12-11T00:37:46.943259+03:00                                                                  

Trying increase PGA ...

Thank you!
