### ISSUE TITLE
Incorrect syntax in CREATE TABLE (ERROR:  cannot use subquery in column generation expression)

### ISSUE THREAD

**Issue by IgorM12** [darold/ora2pg#1328]
Hello!

I have table in oracle:
```
CREATE TABLE MY_GROUP
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"PRESSMARK_SORT" NUMBER GENERATED ALWAYS AS (TO_NUMBER(NVL( REGEXP_SUBSTR ("PRESSMARK",'\d*'),'0'))*100000000000+TO_NUMBER(NVL( REGEXP_SUBSTR ( REGEXP_SUBSTR ("PRESSMARK",'\D+\d*'),'\d+'),'0'))*1000000000+TO_NUMBER(NVL( REGEXP_SUBSTR ( REGEXP_SUBSTR ("PRESSMARK",'\D+\d*',1,2),'\d+'),'0'))*10000000+TO_NUMBER(NVL( REGEXP_SUBSTR ( REGEXP_SUBSTR ("PRESSMARK",'\D+\d*',1,3),'\d+'),'0'))*100000+TO_NUMBER(NVL( REGEXP_SUBSTR ( REGEXP_SUBSTR ("PRESSMARK",'\D+\d*',1,4),'\d+'),'0'))*1000+TO_NUMBER(NVL( REGEXP_SUBSTR ( REGEXP_SUBSTR ("PRESSMARK",'\D+\d*',1,5),'\d+'),'0'))) VIRTUAL );
```

ORA2PG generated following syntax:

CREATE TABLE my_group(
	id bigint NOT NULL,
	pressmark_sort bigint GENERATED ALWAYS AS ((coalesce( (SELECT array_to_string(a, '') FROM regexp_matches(PRESSMARK, '\d*', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1)),'0')::numeric) *100000000000+(coalesce( (SELECT array_to_string(a, '') FROM regexp_matches((SELECT array_to_string(a, '') FROM regexp_matches(PRESSMARK, '\D+\d*', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1)), '\d+', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1)),'0')::numeric) *1000000000+(coalesce( (SELECT array_to_string(a, '') FROM regexp_matches((SELECT array_to_string(a, '') FROM regexp_matches(PRESSMARK, '\D+\d*', 'g') AS foo(a) LIMIT 1 OFFSET (2 - 1)), '\d+', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1)),'0')::numeric) *10000000+(coalesce( (SELECT array_to_string(a, '') FROM regexp_matches((SELECT array_to_string(a, '') FROM regexp_matches(PRESSMARK, '\D+\d*', 'g') AS foo(a) LIMIT 1 OFFSET (3 - 1)), '\d+', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1)),'0')::numeric) *100000+(coalesce( (SELECT array_to_string(a, '') FROM regexp_matches((SELECT array_to_string(a, '') FROM regexp_matches(PRESSMARK, '\D+\d*', 'g') AS foo(a) LIMIT 1 OFFSET (4 - 1)), '\d+', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1)),'0')::numeric) *1000+(coalesce( (SELECT array_to_string(a, '') FROM regexp_matches((SELECT array_to_string(a, '') FROM regexp_matches(PRESSMARK, '\D+\d*', 'g') AS foo(a) LIMIT 1 OFFSET (5 - 1)), '\d+', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1)),'0')::numeric)) STORED
) ;

PG cannot execute this DDL: 

**_psql:./schema/tables/table.sql:1053: ERROR:  cannot use subquery in column generation expression
СТРОКА 15: ...smark_sort bigint GENERATED ALWAYS AS ((coalesce( (SELECT ar...
                                                                ^
ERROR: an error occurs when importing file ./schema/tables/table.sql._**

**Comment by darold** [comment]
Fnnction REGEXP_SUBSTR doesn't exist yetr in PostgreSQL, its rewritting require a call to a subquery which is not supported in a CREATE TABLE statement. You shoud enable USE_ORAFCE in ora2pg.conf, I have implemented the REGEXP_*  functions in orafce recently.

**Comment by IgorM12** [comment]
Hi!

Thank you!

When I set USE_ORAFCE=1  in ora2pg.conf, generated DDL is now different:
CREATE TABLE my_group(
	id bigint NOT NULL,
	pressmark varchar(256) NOT NULL,
	pressmark_sort bigint GENERATED ALWAYS AS ((coalesce( REGEXP_SUBSTR(PRESSMARK,'\d*'),'0')::numeric) *100000000000+(coalesce( REGEXP_SUBSTR( REGEXP_SUBSTR(PRESSMARK,'\D+\d*'),'\d+'),'0')::numeric) *1000000000+(coalesce( REGEXP_SUBSTR( REGEXP_SUBSTR(PRESSMARK,'\D+\d*',1,2),'\d+'),'0')::numeric) *10000000+(coalesce( REGEXP_SUBSTR( REGEXP_SUBSTR(PRESSMARK,'\D+\d*',1,3),'\d+'),'0')::numeric) *100000+(coalesce( REGEXP_SUBSTR( REGEXP_SUBSTR(PRESSMARK,'\D+\d*',1,4),'\d+'),'0')::numeric) *1000+(coalesce( REGEXP_SUBSTR( REGEXP_SUBSTR(PRESSMARK,'\D+\d*',1,5),'\d+'),'0')::numeric)) STORED
) ;

But DDL stiil incorrect, error:

  _...smark_sort bigint GENERATED ALWAYS AS ((coalesce( REGEXP_SUB..._
                                                                ^
_No function matches the given name and argument types. You might need to add explicit type casts._

When I added prefix oracle for regexp_substr (Example: oracle.regexp_substr), DDL executed.
**Does ORA2PG can set prefix "oracle." automatically for oracle functions?**

Not I confuse with strange error: "ERROR:  generation expression is not immutable" ....


Best Regards
Igor Melnikov

**Comment by IgorM12** [comment]
I fixed problem.
I wroted my own immutable function and modified DDL generated from ora2pg.

Thanx!

**Comment by IgorM12** [comment]
Thank you!
