### ISSUE TITLE
problem in replace transformation

### ISSUE THREAD

**Issue by mperdikeas** [darold/ora2pg#1329]
ora2pg version 23, commit 404a8b8

The following Oracle check constraint:

```
    CREATE TABLE some_schema.some_table 
    ...
    CONSTRAINT "some_constraint" CHECK(
replace(replace(replace(replace(replace(replace(replace(replace(replace(some_column,'a'),'b'),'c'),'d'),'e'),'f'),'g'),','), ' ')  is null ) ENABLE
```

is transformed to:

```
ALTER TABLE some_schema.some_table ADD CONSTRAINT some_constraint CHECK (
replace(replace(replace(replace(replace(replace(replace(replace(replace(some_column, 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')
, 'g', ''),','), ' ', '')  is null);
```

Which is wrong on two grounds:
i) syntax error as it produces: ERROR:  function replace(text, unknown) does not exist
ii) the empty string does not equal null in PostgreSQL so the check will fail.

I think it should be transformed to:

```
ALTER TABLE some_schema.some_table ADD CONSTRAINT some_constraint CHECK (
replace(replace(replace(replace(replace(replace(replace(replace(replace(some_column, 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', '')
, 'g', ''), ',', ''), ' ', '') = '');
```

**Comment by darold** [comment]
Commit e10b069 fixes this issue when the table definition is retrieve from the database, when it is read from file it is still present but I have no solution for that.
