### ISSUE TITLE
Not Exporting all rows froma table

### ISSUE THREAD

**Issue by stegrahamGIT** [darold/ora2pg#133]
Sorry, this is probably not the best place to raise this - apologies! I am testing ora2pg - it's on a  Windows 7 PC using Activestate Perl. I have a table - which on the Oracle server side reports 259, 351 rows when I do a select count(*), but when I dump the data out of the DB using ora2pg it (I've tried copy and insert) I only get 153196 rows. The job seems to run OK and without errors. e.g.

153196/153196 rows (100.0%) on total data (avg: 3647.5 recs/sec)

If I export the data using Oracle SQL Developer then I get all 259,351 rows. I cannot work out why it is not exporting all rows? I tried another table which has more rows (689556) and this exported all records using ora2pg. Is there any extra ways of finding what is happening here. I'm already using the -d switch, but according to ora2pg everything is working ok.

Stephen

**Comment by darold** [comment]
Hi,

This is the right place to report an issue. Unfortunately I'm afraid I can't really help on Windows port, there is probably an OS limitation on what you are exporting. It doesn't seems to be related to the number of row but certainly more on the amount of data exported. Are you exporting to file or directly to a PostgreSQL database? Could you also post here the description of the table your are exporting?

Regards,

**Comment by stegrahamGIT** [comment]
sorry - ignore this. fixed.
