### ISSUE TITLE
problem in concatenation transformation

### ISSUE THREAD

**Issue by mperdikeas** [darold/ora2pg#1330]
Using Ora2Pg version 23.0
The following Oracle check constraint:

   CHECK ( column_a || column_b IS NOT NULL )

... where both columns are NULLABLE NUMBER(12, 0) on the table DDL

... is transformed to the below code in PostgreSQL:

    CHECK ( column_a || ((column_b IS NOT NULL AND column_b::text <> '') AND column_b::text <> ''));

The above produces:
    ERROR:  operator does not exist: boolean || boolean

Moreover, I think the semantics are not correct. There's symmetry between column_a and column_b in the original Oracle check, I think there should be symmetry in the generated PostgreSQL code as well.

Given that concatenation with NULL yields NULL in PostgreSQL whereas this may not be the case in Oracle, perhaps the correct transformation is:

    CHECK ( column_a::text<>'' OR column_b::text<>'');

(I think the above correctly maintains the outcome if either column is NULL)

**Comment by darold** [comment]
Unfortunately this kind of transformation use a logic that can not be implemented in Ora2Pg, this will stay a human rewriting.
