### ISSUE TITLE
VIEW_AS_TABLE seems not to work

### ISSUE THREAD

**Issue by jmoteka** [darold/ora2pg#1331]
I am using Ora2Pg version 23.0.

When trying to export views it does not export anything.
First I want to export the DDL of the view by setting ALLOW and VIEW_AS_TABLE with type of export 'TABLE':
`ALLOW		T_USER
VIEW_AS_TABLE	T_USER`

It does not export any DDL. The generated DDL says 

> -- Nothing found of type TABLE

Hint: This view is a view based on a view. I do not know if this is the issue or if I am just using the functionality wrongly.

Also does not work with other views.

**Comment by darold** [comment]
Fixed in commit 75c1893.

**Comment by jmoteka** [comment]
thanks a lot!
