### ISSUE TITLE
Why ora2pg generated data for virtual column?

### ISSUE THREAD

**Issue by IgorM12** [darold/ora2pg#1332]
Hello!
Why ora2pg generated data for virtual column?

Because data load process fail wirh error:
psql:/oradata/toPG/GROUP_RESOURCE_data.sql:7: ERROR:  column "pressmark_sort" is a generated column.

**It is somehow configured so that there is no data for virtual columns generated scripts?**

Thank you!

Best Regards
Igor

**Comment by darold** [comment]
You must set PG_VERSION to 13 in ora2pg.conf otherwise Ora2Pg will export the data.
