### ISSUE TITLE
problem in DECODE transformation

### ISSUE THREAD

**Issue by mperdikeas** [darold/ora2pg#1333]
Using Ora2Pg v23.0

The following Oracle code:

`CREATE UNIQUE INDEX ... ON ... ("column_a", DECODE(TO_CHAR("column_b"),NULL,"column_c","column_b")) 
`

Gets translated to PostgreSQL thus:

`CREATE UNIQUE INDEX ... ON ... (column_a, (case coalesce(when (column_b::varchar)::text, '') = '' then column_c else column_b end));`

Which produces:

    syntax error at or near "when"

Whereas, I think, the correct ought to be:

`CREATE UNIQUE INDEX ... ON ... (column_a, (case when coalesce(column_b::varchar, '') = '' then column_c else column_b end));
`

All columns involved (column_a, column_b, column_c) are NUMBER(12, 0)

**Comment by mperdikeas** [comment]
update.
I have also seen the following Oracle code:

`CREATE UNIQUE INDEX  ... ON ... ("column_a", DECODE(TO_CHAR("column_b"),NULL,"column_c","column_b")) 
`
get translated to the following in PostgreSQL:

`CREATE UNIQUE INDEX ... ON ... (column_a, (case when column_b::coalesce(varchar::text, '') = '' then column_c else column_b end));`

whereas the correct is, I think:

`CREATE UNIQUE INDEX ... ON ... (column_a, (case when coalesce(column_b::text, '') = '' then column_c else column_b end));       ` 

Again, all columns involved are NUMBER(12, 0) in Oracle

**Comment by darold** [comment]
I think that this have been fixed, please use latest development code here is the result for you first example:
```
CREATE UNIQUE INDEX bar_tb_column_a_column_b_idx ON bar_tb (column_a, (case when (column_b::varchar) is null then column_c else column_b end));
```
which is correct.
