### ISSUE TITLE
While copying data from oracle to postgreSQL using ora2pg, I am getting DETAIL:  ORA-12541: TNS:no listener at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 9352. error

### ISSUE THREAD

**Issue by chetan2211** [darold/ora2pg#1335]
E:\ora2pg-23.0>ora2pg -t copy -c ora2pg_employee.dist -l employee.log
WARNING: NO_LOB_LOCATOR is deprecated, use USE_LOB_LOCATOR instead see documentation about the logic change.
WARNING: NO_BLOB_EXPORT is deprecated, use ENABLE_BLOB_EXPORT instead see documentation about the logic change.
[========================>] 1/1 tables (100.0%) end of scanning.
NOTICE: user mapping for "employee" already exists for server "orcl", skipping
[========================>] 1/1 tables (100.0%) end of table export.
NOTICE: drop cascades to foreign table ora2pg_fdw_import.employee_details
DBD::Pg::db do failed: ERROR: connection for foreign table "employee_details" cannot be established
DETAIL: ORA-12541: TNS:no listener at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 9352.
[========================>] 71/71 rows (100.0%) on total estimated data (1 sec., avg: 71 recs/sec)

I tried every solution which is available on internet but not able to resolve this issue. Please let me know if you know the solution.
Thank you in advance.

**Comment by darold** [comment]
You have an issue with the foreign server definition, can you post the ORACLE_DSN value set in ora2pg.conf and the result of the following query form you PostgreSQL destination database:
```
SELECT * FROM pg_foreign_server ;
```

**Comment by chetan2211** [comment]
Hi Darold,
Thanks for reply.

ORACLE_DSN value set in ora2pg.conf is as below :

ORACLE_DSN	dbi:Oracle:host=192.168.45.102;sid=orcl;port=1521

And result of pg_foreign_server is as below :

postgres=# SELECT * FROM pg_foreign_server ;
 oid | srvname | srvowner | srvfdw | srvtype | srvversion | srvacl | srvoptions
-----+---------+----------+--------+---------+------------+--------+------------
(0 rows)

Note : my oracle and postgres server on diffrent machine with windows OS.

**Comment by darold** [comment]
Query `SELECT * FROM pg_foreign_server` must be executed in the database you are migrating not the postgres database. Also please report the FDW_SERVER value set in ora2Pg.conf

**Comment by chetan2211** [comment]
Result of pg_foreign_server in oracle  is as below :

SQL> SELECT * FROM pg_foreign_server ;
SELECT * FROM pg_foreign_server
              *
ERROR at line 1:
ORA-00942: table or view does not exist

And fdw_server in ora2pg.conf file is set as below :

FDW_SERVER	orcl

**Comment by darold** [comment]
pg_foreign_server is obviously a PG table so please execute the query in your PostgreSQL destination database!

**Comment by chetan2211** [comment]
Really sorry i read it in a wrong way.

Result of pg_foreign_server is as below :

postgres=# \c employee chetan
Password for user chetan:
You are now connected to database "ecgc_dump_14_12_21" as user "ecgc".
employee=# SELECT * FROM pg_foreign_server ;
  oid   | srvname | srvowner | srvfdw | srvtype | srvversion | srvacl |            srvoptions
--------+---------+----------+--------+---------+------------+--------+----------------------------------
 133049 | orcl    |    43688 | 133048 |         |            |        | {dbserver=//localhost:1521/orcl}
(1 row)

**Comment by darold** [comment]
Ok, you should drop the existing foreign server as it don't have the right ip address. This is localhost instead of 192.168.45.102. Ora2Pg will recreate it automatically.

**Comment by chetan2211** [comment]
Hi @darold ,
Issue is resolve by dropping foreign server in destination database of postgreSQL
Thank you so much for helping me.

**Comment by chetan2211** [comment]
Hi @darold ,
Getting same error when i am doing this on local windows machine. My oracle and postgreSQL both server on same window machine. I tried above solution for that, but it does not work, Please help me.

Thank you in advance.

**Comment by darold** [comment]
Sorry but I don't have much time in this moment to provide support on Ora2Pg so I will not even try to give support on Windows that I have not used for decades. If no other people can help you on this operating system I recommend you to use Linux.
