### ISSUE TITLE
Getting error of invalid byte sequence while copying data from oracle to postgres.

### ISSUE THREAD

**Issue by chetan2211** [darold/ora2pg#1336]
D:\ora2pg-23.0>ora2pg -t copy -c ora2pg_employee.dist -l employee.log
WARNING: NO_LOB_LOCATOR is deprecated, use USE_LOB_LOCATOR instead see documentation about the logic change.
WARNING: NO_BLOB_EXPORT is deprecated, use ENABLE_BLOB_EXPORT instead see documentation about the logic change.
[========================>] 1/1 tables (100.0%) end of scanning.
NOTICE:  user mapping for "employee" already exists for server "orcl", skipping
[========================>] 1/1 tables (100.0%) end of table export.
NOTICE:  drop cascades to foreign table ora2pg_fdw_import.employee_details
DBD::Pg::db do failed: ERROR:  invalid byte sequence for encoding "UTF8": 0x00
CONTEXT:  converting column "sql_query" for foreign table scan of "employee_details", row 1 at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 9352.
[========================>] 5832/5832 rows (100.0%) on total estimated data (1 sec., avg: 5832 recs/sec)

**Comment by darold** [comment]
Hi,

You have nul character in some data. Oracle allow storage of nul in string data type but not PostgreSQL even if most of the time this correspond to corrupted data in Oracle and they can be removed before migrating data. If they must be preserved then the destination data type must be bytea, nul characters will be escaped.

**Comment by chetan2211** [comment]
Thank you @darold for reply.
I understand your point but please can you provide me a solution for that.

**Comment by darold** [comment]
Search for how to replace nul character in oracle column.

FOr example, you can get the row that have nul characters by using a WHERE clause like `WHERE colname LIKE '%' || chr(0) || '%'` then you can use `REPLACE (colname, CHR(0), ' ')` to fix the content of the matching rows.

**Comment by chetan2211** [comment]
I run the below command but still getting invalid byte sequence error while migrating data.

select sql_query from employee WHERE sql_query LIKE '%' || chr(0) || '%';

select REPLACE (sql_query, CHR(0), ' ') from employee;

**Comment by darold** [comment]
Can you post the error message please, just to see if this is still on nul character.

**Comment by chetan2211** [comment]
The error message in ora2pg is as below :

DBD::Pg::db do failed: ERROR: invalid byte sequence for encoding "UTF8": 0x00
CONTEXT: converting column "sql_query" for foreign table scan of "employee_details", row 1 at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 9352.

**Comment by darold** [comment]
Then this time this is in table employee_details column sql_query.

**Comment by chetan2211** [comment]
Hi  @darold ,
Apologies for the delayed response.

When I run the following query of oracle in dbvisualizer I  get the result which is sharing in attached link because it showing some square in the result  :

select sql_query from employee_details WHERE sql_query LIKE '%' || chr(0) || '%';

![oracle result](https://user-images.githubusercontent.com/77317761/146964184-a188329f-ed83-4f2a-9908-0fa3630046e8.png)

And data type of sql_query  column is VARCHAR2(4000) in oracle and in postgres data type for sql_query  column is character varying(4000).

Any idea, what I can do?

**Comment by chetan2211** [comment]
Hi @darold 
I tried every solution please let me know if you know the solution.
Thanks in advance.
