### ISSUE TITLE
unterminated quoted identifier in generated code

### ISSUE THREAD

**Issue by mperdikeas** [darold/ora2pg#1339]
Using Ora2Pg v23.0

The following Oracle code:

`CREATE UNIQUE INDEX ... ON ... (CASE  WHEN "column_a" IS NULL THEN "column_b" ELSE NULL END ) 
`
Gets translated to the following PostgreSQL code:

`CREATE UNIQUE INDEX ... ON ...  (("case when coalesce(column_a::text, '') = '' then column_b else null end));`

Note the extra " in "case which causes havoc. If "case is changed to case, it works well.

**Comment by darold** [comment]
This have already been fixed but there was a remaining issue with missing parenthesis to enclose the expression. Commit d079f2f fixes that.
