### ISSUE TITLE
Auto add break line when export data

### ISSUE THREAD

**Issue by vu-bm** [darold/ora2pg#134]
Hi all,
When I import data to Postgres database, I got an error:
> ERROR:  value too long for type character varying(4000)

The data type of that column in oracle is "character varying(4000)" and pgdb had same type too.
So I find out, the data had change after export from oracle db.
In every break line in oracle data, it make a new break line (become 2 break line)
So that, string from 3986 to 4092 characters long.

May it is a bug or i do not configure a directives?
Thanks you so much.
Vu-BM

**Comment by darold** [comment]
Hi,

What export type are you using, INSERT or COPY ?
What is the version of your PostgreSQL database and the value of the following ora2pg configuration directives: NOESCAPE and STANDARD_CONFORMING_STRINGS?

Best regards,

**Comment by vu-bm** [comment]
Hi, 

I had using INSERT export type,
The PostgreSQL database is 9.3.9
directives: NOESCAPE 0 
and:          STANDARD_CONFORMING_STRINGS	1

I had try with NOESCAPE 1, and it still like that.
Vu-BM

**Comment by darold** [comment]
Please use COPY mode and let us know if you still have the issue. The INSERT mode should never be used unless you want to use the export with an other SGBD then PostgreSQL.

**Comment by vu-bm** [comment]
Hi,

I had use COPY mode and it already ok. 
I had think it will not different between 2 mode.
So that I had choose INSERT mode to easy review data.

Thanks you so much,
Yours sincerely,
Vu-BM

**Comment by darold** [comment]
Obviously this might not be different between the two mode. Can you please send me an INSERT statement that is breaking the length constraint and the same with the COPY statement ? You can send it to my private email for privacy gilles@darold.net . This will help me a lot to find the real reason of this issue.

Regards,

**Comment by vu-bm** [comment]
Hi,

I can't attach file here so I had send more information via email.
I hope it will help.

Yours sincerely,
Vu-BM

**Comment by darold** [comment]
This issue will be fixed within next major release. Thanks for the report.
