### ISSUE TITLE
Getting rollback due to DESTROY connection exporting schema

### ISSUE THREAD

**Issue by scapy11** [darold/ora2pg#1340]
Using Ora2Pg v23.0

When trying to run an REPORT gave the following error:
```
Undefined subroutine &Ora2Pg::Oracle::min called at /ora2pg/usr/local/share/perl5/Ora2Pg/Oracle.pm line 431.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(PORT=1523)(HOST=server1.domain.com))(CONNECT_DATA=(SERVICE_NAME=ORCL))) at /ora2pg/usr/local/share/perl5/Ora2Pg/Oracle.pm line 430.
```

I'm using ORACLE_USER with system user to export only one schema.
This is the content of conf file:

```
PG_VERSION      14
ORACLE_DSN      dbi:Oracle:host=server1.domain.com;port=1523;service_name=ORCL
ORACLE_USER     system
ORACLE_PWD      manager

TYPE TABLE
EXPORT_SCHEMA   1
SCHEMA          dev_test
EXPORT_INVALID  1
TRANSACTION     READONLY
OUTPUT dev_test_schema.sql
```

The SHOW_VERSION run fine:

```
ora2pg -t SHOW_VERSION -c conf/ora2pg.conf
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0
```

Debug:

```
ora2pg -t SHOW_REPORT --estimate_cost -c conf/ora2pg.conf.dist -d
Reporting Oracle Content...
Looking at Oracle server version...
Looking at Oracle database size...
Looking at Oracle defined objects...
        Found 2 valid and 0 invalid object DATABASE LINK
        Found 119 valid and 0 invalid object FUNCTION
        Found 1858 valid and 0 invalid object INDEX
        Found 2 valid and 0 invalid object JAVA CLASS
        Found 2 valid and 0 invalid object JAVA SOURCE
        Found 32 valid and 0 invalid object PACKAGE
        Found 31 valid and 0 invalid object PACKAGE BODY
        Found 13 valid and 1 invalid object PROCEDURE
        Found 998 valid and 0 invalid object SEQUENCE
        Found 1269 valid and 0 invalid object TABLE
        Found 16 valid and 0 invalid object TABLE PARTITION
        Found 2539 valid and 0 invalid object TRIGGER
        Found 26 valid and 0 invalid object TYPE
        Found 1 valid and 0 invalid object TYPE BODY
        Found 33 valid and 0 invalid object VIEW
Looking at table definition...
Undefined subroutine &Ora2Pg::Oracle::min called at /ora2pg/usr/local/share/perl5/Ora2Pg/Oracle.pm line 431.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(PORT=1523)(HOST=server1.domain.com))(CONNECT_DATA=(SERVICE_NAME=ORCL))) at /ora2pg/usr/local/share/perl5/Ora2Pg/Oracle.pm line 430.
```

**Comment by darold** [comment]
Please download last development code and install it, this might have been fixed.

**Comment by scapy11** [comment]
It's solved with latest install

**Comment by skizilbash** [comment]
hello @darold 

i am facing similar error on running below command. It throws this error after extracting a few tables and i am using the latest development code. however i used version 20.0 in another server and never saw this error.

$ ora2pg --version
Ora2Pg v23.1

$ ora2pg -t COPY -o data.sql -b ./data -c $HOME/Phycon_o2p/oracle_service_name/config/ora2pg.conf

Can't locate object method "errstr" via package "0" (perhaps you forgot to load "0"?) at /var/lib/pgsql/PERL_DBI_DBD/lib64/perl5/Ora2Pg.pm line 14371.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle //ed23db01-vip.uhc.com:1521/y03ts08.uhc.com at /var/lib/pgsql/PERL_DBI_DBD/lib64/perl5/Ora2Pg.pm line 14371.

Please advise.

**Comment by darold** [comment]
Please download latest development code using:
```
wget https://github.com/darold/ora2pg/archive/refs/heads/master.zip
unzip master.zip
cd ora2pg-master
perl Makefile.PL
make
sudo make install
```
then try again.

The line number reported here do not correspond to latest code, there is no call to errstr() at line 14371.

Report the new error here if it is still present.

**Comment by skizilbash** [comment]
Thanks for the quick reply. 
i was able to run it in another server using version 20.0. However it took too long and timed out. Do you know if ora2pg has a feature to bring the data in chunks date wise (partitioning) and also if the below can be run in the background using nohup. earlier i was running in screen -x mode but it still timed out after 6 hours.

ora2pg -t COPY -o data.sql -b ./data -c $HOME/Phycon_o2p/oracle_service_name/config/ora2pg.conf

**Comment by skizilbash** [comment]
i am also seeing errors in the below step. Any help would be appreciated :)

$ perl Makefile.PL PREFIX=$HOME/PERL_DBI_DBD
Configuring DBD::Pg 3.12.1
PostgreSQL version: 130006 (default port: 5432)
POSTGRES_HOME: /var/lib/pgsql
POSTGRES_INCLUDE: /usr/pgsql-13/include
POSTGRES_LIB: /usr/pgsql-13/lib
OS: linux
The value of POSTGRES_INCLUDE points to a non-existent directory: /usr/pgsql-13/include
Cannot build unless the directories exist, exiting.

**Comment by vimal-dharmalingam** [comment]
Hi,  IM facing the same below error 
using V23 ora2pg.

Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(PORT=1523)(HOST=server1.domain.com))(CONNECT_DATA=(SERVICE_NAME=ORCL)))

So whats the final solution for this.
