### ISSUE TITLE
problematic conversion of to_number(substr(..)) from Oracle to PostgreSQL

### ISSUE THREAD

**Issue by mperdikeas** [darold/ora2pg#1341]
This is using Ora2Pg v23.0
I have an index on a Oracle table declared like this:

`CREATE INDEX ... ON ... ("col_a", TO_NUMBER(SUBSTR("col_b",2,1))) `

This is converted in PostgreSQL as:

`CREATE INDEX ... ON ... USING btree (col_a, ((substr((col_b)::text, 2, 1))::numeric));`

The problem is that the expression TO_NUMBER(SUBSTR("col_b", 2, 1)) in Oracle yields NULL if the column has a value that is less than two characters wide. In contrast, the expression substr((col_b)::text, 2, 1))::numeric in PostgreSQL throws an error.

E.g. (using hard-coded values):
In Oracle:

```
select TO_NUMBER(SUBSTR('a',2,1)) FROM dual
null

```
In PostgreSQL:

```
select substr(('a')::text, 2, 1)::numeric;
ERROR:  invalid input syntax for type numeric: ""
```

So if the data has rows where the column is less than two characters wide, the loading fails.
I think the correct is for the index to be declared like this:

`CREATE INDEX IF NOT EXISTS... ON ... (col_b, (nullif(substr(col_a,2,1), '')::numeric));
`

**Comment by darold** [comment]
Commit 0083a2f adds this fix for TABLE export.
