### ISSUE TITLE
DROP_IF_EXISTS doesn't seem to work on all objects

### ISSUE THREAD

**Issue by jolsen71** [darold/ora2pg#1342]
Running ora2pg v23. My configuration file has `DROP_IF_EXISTS 1` in it. 

When I execute the export_schema script and look at the generated `sequence.sql` file, there is a `DROP SEQUENCE IF EXISTS` statement before every `CREATE SEQUENCE` statement, as expected with this configuration. 

However, when I look at the generated `INDEXES_table.sql`, `table.sql`, and `CONSTRAINTS_table.sql` files, there are no `DROP xxx IF EXISTS` statements, only the `CREATE`s, which is causing issues trying to re-import the schemas because it dies trying to create objects that already exists from previous imports. 

Is there something else I need to do to get the "drop if exists" statements added for all object types (not just sequences) or is this a bug in ora2pg? 

Thanks

**Comment by darold** [comment]
Commit 6b8c2fd fixes this issue.
