### ISSUE TITLE
yum install on rh7 raises 2 issues 

### ISSUE THREAD

**Issue by seadba** [darold/ora2pg#1343]
hello, i am insatlling ora2pg.noarch 0:23.0-1.rhel7 - i have installed DBD::Oracle and i dont have mysql so i skipped that dbd
DBD::Oracle is up to date (1.80).

ORACLE_HOME and LD_LIBARY_PATH are set  - my question is why is mysql mandatory and why cant it find dbd::oracle?  thanks

yum install ora2pg
Resolving Dependencies
--> Running transaction check
---> Package ora2pg.noarch 0:23.0-1.rhel7 will be installed
--> Processing Dependency: perl-DBD-MySQL for package: ora2pg-23.0-1.rhel7.noarch
--> Processing Dependency: perl(String::Random) for package: ora2pg-23.0-1.rhel7.noarch
--> Processing Dependency: perl(DBD::Oracle) for package: ora2pg-23.0-1.rhel7.noarch
--> Running transaction check
---> Package ora2pg.noarch 0:23.0-1.rhel7 will be installed
--> Processing Dependency: perl-DBD-MySQL for package: ora2pg-23.0-1.rhel7.noarch
--> Processing Dependency: perl(DBD::Oracle) for package: ora2pg-23.0-1.rhel7.noarch
---> Package perl-String-Random.noarch 0:0.25-1.el7 will be installed
--> Finished Dependency Resolution
Error: Package: ora2pg-23.0-1.rhel7.noarch (pgdg-common)
           Requires: perl(DBD::Oracle)
Error: Package: ora2pg-23.0-1.rhel7.noarch (pgdg-common)
           Requires: perl-DBD-MySQL
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by seadba** [comment]
# perl -MCPAN -e 'install DBD::MySQL'

Starting with version 2.29 of the cpan shell, a new download mechanism
is the default which exclusively uses cpan.org as the host to download
from. The configuration variable pushy_https can be used to (de)select
the new mechanism. Please read more about it and make your choice
between the old and the new mechanism by running

    o conf init pushy_https

Once you have done that and stored the config variable this dialog
will disappear.
Reading '/root/.cpan/Metadata'
  Database was generated on Wed, 22 Dec 2021 09:55:41 GMT
Warning: Cannot install DBD::MySQL, don't know what it is.
Try the command

    i /DBD::MySQL/

to find objects with matching identifiers.

**Comment by darold** [comment]
Actually package perl-DBD-MySQL should not be marked as required to install ora2pg package. But it looks mandatory so:
```
sudo yum install perl-DBD-MySQL
```
should fix the issue.

About the `Requires: perl(DBD::Oracle)` error, I don't know why it happen it you have already installed it.

However ora2pg-23.0 is a bit old now, a lot of bug have been fixed and feature added, best is to install it from sources. The other advantage with this installation is that it will not complain about missing required packages :-) Saying that if a used package is missing you will have an explicit error.

**Comment by seadba** [comment]
thanks for fast response - 
yum install of mysql fails no package available - i will download ora2pg source and test again

**Comment by seadba** [comment]
is this latest v? - i cloned from git

[root@linux2 ora2pg]# which ora2pg
/root/perl5/bin/ora2pg
[root@linux2 ora2pg]# ora2pg --version
Ora2Pg **v23.0**
[root@linux2 ora2pg

**Comment by darold** [comment]
yes, the version number is changed only when a new release is published, git clone always gets latest development code.

**Comment by seadba** [comment]
excellent thanks very much - great tool
