### ISSUE TITLE
Incorrect query after removing "from dual"

### ISSUE THREAD

**Issue by taptarap** [darold/ora2pg#1344]
Ora2pg removes "from dual" in all places. This causes a problem if it is followed by a "left join" (use this makes sense).
I changed my code, but maybe it will help someone later.

For example, in oracle:
```
CREATE OR REPLACE FUNCTION test_dual_join RETURN NUMBER AS
  l_result NUMBER;
BEGIN
  SELECT 1
    INTO l_result
    FROM dual;

  SELECT t.id
    INTO l_result
    FROM dual
    LEFT JOIN test_table t
      ON 1 = 1;

  SELECT t.id
    INTO l_result
    FROM test_table t
   RIGHT JOIN dual
      ON 1 = 1;

  RETURN l_result;
END;
```

And after converting:
```
CREATE OR REPLACE FUNCTION my_schema.test_dual_join () RETURNS bigint AS $body$
DECLARE

  l_result bigint;

BEGIN
  SELECT 1
    INTO STRICT l_result
;

  SELECT t.id
    INTO STRICT l_result

    LEFT JOIN test_table t
      ON 1 = 1;

  SELECT t.id
    INTO STRICT l_result
    FROM test_table t
   RIGHT JOIN dual
      ON 1 = 1;

  RETURN l_result;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
```

**Comment by darold** [comment]
Well I would like to see the original query because I don't see any reason/interest to use FROM DUAL with a JOIN. For the moment my opinion is that this is something marginal, I have never encountered that so I don(t think I will spend time fixing something that is never used. But I may be wrong.

**Comment by taptarap** [comment]
Using DUAL allows to skip data existence checks. 

Get results whether or not some table has any data:
```
SELECT coalesce(e.ename, '(No employees)') AS ename
  FROM dual
  LEFT JOIN emp e
    ON 1 = 1
```

With ROWNUM=1 it gives the same result as SELECT without STRICT in postgresql
> If STRICT is not specified in the INTO clause, then target will be set to the first row returned by the query, or to nulls if the query returned no rows.

```
SELECT t.id
      ,t.patient_id
      ,t.specimen_id
      ,t.collectdate
      ,t.status
      ,t.is_in_ws
  INTO l_r_rec
  FROM dual
  LEFT JOIN (SELECT is_research_in_ws(r.id) AS is_in_ws
                   ,r.*
               FROM research r
              WHERE r.ids = p_r_ids
              ORDER BY is_in_ws  DESC
                      ,r.regdate DESC) t
    ON 1 = 1
 WHERE rownum = 1;
```

> I have never encountered that so I don(t think I will spend time fixing something that is never used.
Of course, I will not insist on changes. This issue is simply a description of a rare but real case.

**Comment by darold** [comment]
Thanks for the explanation I understand now. I'm closing the issue.
