### ISSUE TITLE
When table fields have default values, migrating to PostgreSQL is always the default value

### ISSUE THREAD

**Issue by Code-UV** [darold/ora2pg#1345]
Oracle version: 12c
postgres version: 13.3
Source table :
create table TB_CITY
(
  city_id     VARCHAR2(6) default NULL not null,
  city_name varchar(6)
);
INSERT INTO TB_CITY(CITY_ID, CITY_NAME) values ('11', 'Fz');

When I set PG_VERSION 13, city_id is always nul, .log: DEGUG: Query sent to Oracle: SELECT "CITY_NAME" FROM "UV"."TB_CITY" a
When I set PG_VERSION 12, city_id is 11;

**Comment by Code-UV** [comment]
When I debug ,I found :
if ($self->{pg_version} >= 13) {
		$self->{pg_supports_virtualcol} = 1;
	}
next if ($f->[4] && $self->{pg_supports_virtualcol});
the code mean if the column has default value and pg_version >=13, will skip this column

**Comment by IgorM12** [comment]
Hi!

I have the same problem.
Oracle version: 19c
postgres version: 14

When column have default value in Oracle (NOT virtual column), ora2pg always export to COPY command this default value, NOT actual value. 

How resolve this problem?

Thank you!

Best Regards
Igor

**Comment by Code-UV** [comment]
You can set PG_VERSION 12.

**Comment by IgorM12** [comment]
When I set PG_VERSION 12, then ora2pg not understand virtual columns, and export virtual column in COPY command.

**Comment by darold** [comment]
Virtual columns are supported since PostgreSQL version 12 but actually Ora2Pg only enable the virtual column export if PG_VERSION is set to 13. Last commit 0eb362c change the required version to 12.

**Comment by Code-UV** [comment]
However, in 23.0, as long as the column has a default value and PG_ If the version is greater than 12, it will be determined as a virtual column, skipping the export of the actual value and using the default value instead

**Comment by darold** [comment]
Got it, I'm reviewing this code it looks like there is some regression here.

**Comment by darold** [comment]
Commit  daa2c95 might fix this issue.
