### ISSUE TITLE
Types are not exporting correctly in Ora2pg tool

### ISSUE THREAD

**Issue by mukesh3388** [darold/ora2pg#1346]
Hi Team, 

I am using the Ora2pg tool for migration from Oracle to postgres and there are 2 functions which are dependent on TYPES in Oracle.

I exported the Types from Ora2pg tool and it giving me this output in sql files

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

-- Unsupported, please edit to match PostgreSQL syntax
CREATE OR REPLACE TYPE           t_seamcodes                                          as table  of varchar2 (5000)
;
-- Unsupported, please edit to match PostgreSQL syntax
CREATE OR REPLACE TYPE           t_prodgensids                                          as table  of varchar2 (5000)
;_**

How o i create the above types in postgres and how to make it supported in postgres in order to create those functions.

Please help

**Comment by sgrinko** [comment]
You can see examples of type conversion here:
[cloud.google.com - postgresql-data-types](https://cloud.google.com/solutions/migrating-oracle-users-to-cloud-sql-for-postgresql-data-types)
Your option will probably look like this:
```
CREATE TYPE t_seamcodes as (record text[]);
CREATE TYPE t_prodgensids as (record text[]);
```
You need to see the type of use type in the procedure code to specify the details...
