### ISSUE TITLE
Not able migrate rowid datatype column table of oracle  in postgreSQL.

### ISSUE THREAD

**Issue by chetan2211** [darold/ora2pg#1347]
Hi @darold,
I am getting following error while migrating data. Please let me know the solution if you know.
Thanks in advance.

DBD::Pg::db do failed: ERROR:  column "head_rowid" of foreign table "student_details" cannot be converted to or from Oracle data type at D:\ora2pg-23.0\lib/Ora2Pg.pm line 9352.
DBD::Pg::db do failed: ERROR:  column "row_id" of foreign table "exceptions_handle" cannot be converted to or from Oracle data type at D:\ora2pg-23.0\lib/Ora2Pg.pm line 9352.

**Comment by darold** [comment]
Please post the description of the foreign table and the Oracle table.

**Comment by chetan2211** [comment]
Hi @darold ,
Apologies for the delayed response.

Oracle table description :
SQL> desc student_details;
 Name                                      Null?    Type
 ----------------------------------------- -------- ----------------------------
 ROW_ID                                             ROWID
 FIRST_NAME                                      VARCHAR2(30)
 LAST_NAME                                       VARCHAR2(30)
 
 
 Postgresql foreign table description :
 school_db=# \d student_details
                       Table "ecgc.student_details"
   Column   |         Type                     | Collation | Nullable | Default
------------+-----------------------+-----------+----------+---------
 row_id       | oid                                |              |                 |
 first_name | character varying(30)   |               |                |
 last_name  | character varying(30)   |              |                 |
 
Thanks in advance.

**Comment by darold** [comment]
This should be supported in last development code if you set `DATA_TYPE       rowid:oid` in ora2pg.conf but maybe without the use of the foreign table.

**Comment by darold** [comment]
Hum no sorry I have made a confusion with the RAW data type.  I guess that you must use a varchar or char(N) to store this rowid, what is a typical value. Personally I have never encountered such column data type.
