### ISSUE TITLE
Not really an issue but a remark

### ISSUE THREAD

**Issue by joguess** [darold/ora2pg#1348]
Hello,

In the ora2pg .conf, the value of 0 means disabled and the one of 1 means enabled right?

So for the parameter NO_LOB_LOCATOR "Default is enabled, it will not use LOB locators for backward compatibility."

Why do you put 0 instead of 1 ?
 
Regards.

**Comment by joguess** [comment]
Same remark for the parameter PLSQL_PGSQL, you said "Default enabled" and you put 0.
?
Can we have a standart for the 0 and 1 ?

Thanks.

**Comment by darold** [comment]
You are using an obsolete version of Ora2Pg or at least of the ora2Pg.conf file, NO_LOB_LOCATOR is not use anymore, it has been replaced by USE_LOB_LOCATOR. About PLSQL_PGSQL it is enabled by default now.

**Comment by joguess** [comment]
Thanks, I m going to update with the last version. 
I m using Ora2Pg v21.0.
Can we have an online ora2pg.conf  to be uploaded ?
Regards.

J.

**Comment by darold** [comment]
When you install Ora2Pg a default configuration file is saved under `/etc/ora2pg/ora2pg.conf.dist`
