### ISSUE TITLE
Packages containing only types are not exported in the ORA2PG tool

### ISSUE THREAD

**Issue by sgrinko** [darold/ora2pg#1349]
Oracle's projects have packages that contain only types of types.
There are no procedures in the package. Body pack blank.
```
CREATE OR REPLACE PACKAGE USERS.USERS_TYPES AS

  TYPE ONE_DATE_REC IS RECORD(
    DAT0 DATE);
    
  TYPE NUMBER_AND_DATE_REC IS RECORD(
    ID0 NUMBER,
    DAT1 DATE);
...
  TYPE MONITORING_PARAM_CUR IS REF CURSOR RETURN MONITORING_PARAM%ROWTYPE;

  TYPE MONITORING_CUR IS REF CURSOR RETURN MONITORING%ROWTYPE;

  TYPE MONITORING_SUB_CUR IS REF CURSOR RETURN MONITORING_SUB%ROWTYPE;
...
```
After exporting the ORA2PG tool in the `schema/packages` directory, there is no `USERS_TYPES` directory.
In the `schema/packages/package.sql` file there are no ads for these types.
In the `sources/packages` directory, there is also no `USERS_TYPES` directory and in the `package.sql` file there are no ads for these types.

My config file
[ora2pg.conf.txt](https://github.com/darold/ora2pg/files/7807619/ora2pg.conf.txt)

**Comment by darold** [comment]
Right, if there is no PACKAGE BODY the package header is not taken in account. I can fix that.

**Comment by sgrinko** [comment]
Thank you very much!

**Comment by darold** [comment]
Commit d0e6ca2 might fix this issue, the types are dumped to the main file.

**Comment by sgrinko** [comment]
Thanks!
