### ISSUE TITLE
Support for multiple Schemas 

### ISSUE THREAD

**Issue by Rokko11** [darold/ora2pg#135]
Hi!

Is there a support to export multiple Oracle-schemas at one time?

Following does not work:
```
# Oracle schema/owner to use
SCHEMA	FIRST SECOND
```

Regards,
Rokko

**Comment by darold** [comment]
Hi,

No each schema must be exported one at a time or, if schema doesn't matter, you can export all objects from all schemas by commenting this directive.

Regards,

**Comment by Rokko11** [comment]
Thank you.
I will create a readonly-user for all the schemas I want to export and will comment out the line.

Regards
