### ISSUE TITLE
ORA-00600 while extracting data

### ISSUE THREAD

**Issue by joguess** [darold/ora2pg#1350]
Hello,

I m running this query while I extract the data of an oracle database of 180 Go. 

ora2pg -t COPY -c config/ora2pg.conf 

I get the following errors : 

Can't prepare statement: ORA-00600: internal error code, arguments: [qksvcGetGuardCol:2], [688803], [0], [], [], [], [], [], [], [], [], [] (DBD ERROR: error possibly near <*> indicator at char 29 in 'SELECT * FROM "CMLI_REP_OWN".<*>"TB_CBC_CATEGORY" WHERE 1=0') at /usr/local/share/perl5/Ora2Pg.pm line 2325.
Can't prepare statement: ORA-00600: internal error code, arguments: [qksvcGetGuardCol:2], [688810], [0], [], [], [], [], [], [], [], [], [] (DBD ERROR: error possibly near <*> indicator at char 29 in 'SELECT * FROM "CMLI_REP_OWN".<*>"TB_CBC_CRITERIA" WHERE 1=0') at /usr/local/share/perl5/Ora2Pg.pm line 2325.

Indeed the query SELECT * FROM "CMLI_REP_OWN".<*>"TB_CBC_CRITERIA" WHERE 1=0 is not a good syntax of SQL ANSI and it can't be run on oracle side.
Instead of this we should have : 

SELECT * FROM "CMLI_REP_OWN"."TB_CBC_CRITERIA" WHERE 1=0

**It seams that ora2pg creates a wrong syntax of SQL query.**

(I don't have this issue with smallest databases...very strange)

This issue comes at the beginning of the data extraction.

Do you have any clue ?

Regards,

J.

[ora2pg.conf.txt](https://github.com/darold/ora2pg/files/7820298/ora2pg.conf.txt)
[common.conf.txt](https://github.com/darold/ora2pg/files/7820319/common.conf.txt)

**Comment by darold** [comment]
Hi,

This QUERY is used only to retrieve the columns data types and names. Normally a simple `SELECT * FROM table WHERE 1=0` should work in all case I am curios to know which kind of table it is.

Can you post the description of the Oracle table and the output of the following query:
```
SELECT * FROM ALL_TABLES A WHERE A.OWNER='CMLI_REP_OWN' AND A.TABLE_NAME='TB_CBC_CRITERIA';
```

**Comment by joguess** [comment]
Hello

Here you are : 

`SYS@> desc CMLI_REP_OWN.TB_CBC_CATEGORY
 Name                                                                                                              Null?    Type
 ----------------------------------------------------------------------------------------------------------------- -------- -----------------
 ID                                                                                                                         NUMBER(38)
 NAME                                                                                                                       VARCHAR2(500 CHAR)
 JUNCTION_METHOD                                                                                                            VARCHAR2(100 CHAR)
 PRIORITY                                                                                                                   NUMBER(38)
 CATEGORY_GROUP_ID                                                                                                          NUMBER(38)
 DESCRIPTION                                                                                                                VARCHAR2(500 CHAR)
 LIVE                                                                                                                       NUMBER(38)
 DISABLED                                                                                                                   NUMBER(38)
 LAST_UPDATE                                                                                                                DATE
 LAST_UPDATE_BY                                                                                                             VARCHAR2(10 CHAR)

SYS@> desc CMLI_REP_OWN.TB_CBC_CRITERIA
 Name                                                                                                              Null?    Type
 ----------------------------------------------------------------------------------------------------------------- -------- -----------------
 ID                                                                                                                         NUMBER(38)
 NAME                                                                                                                       VARCHAR2(100 CHAR)
 JUNCTION_METHOD                                                                                                            VARCHAR2(100 CHAR)
 ENTITY_CLASSNAME                                                                                                           VARCHAR2(50 CHAR)
 LAST_UPDATE                                                                                                                DATE
 LAST_UPDATE_BY                                                                                                             VARCHAR2(10 CHAR)
 LIVE                                                                                                                       NUMBER(38)

`
  1* SELECT * FROM ALL_TABLES A WHERE A.OWNER='CMLI_REP_OWN' AND A.TABLE_NAME='TB_CBC_CRITERIA'
SYS@CMLI02D> /

OWNER
--------------------------------------------------------------------------------------------------------------------------------
TABLE_NAME                                                                                                                       TABLESPACE_NAME
-------------------------------------------------------------------------------------------------------------------------------- ------------------------------
CLUSTER_NAME
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
IOT_NAME
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
STATUS                             PCT_FREE   PCT_USED  INI_TRANS  MAX_TRANS INITIAL_EXTENT NEXT_EXTENT MIN_EXTENTS MAX_EXTENTS PCT_INCREASE  FREELISTS FREELIST_GROUPS LOGGING      BACK   NUM_ROWS
-------------------------------- ---------- ---------- ---------- ---------- -------------- ----------- ----------- ----------- ------------ ---------- --------------- ------------ ---- ----------
    BLOCKS EMPTY_BLOCKS  AVG_SPACE  CHAIN_CNT AVG_ROW_LEN AVG_SPACE_FREELIST_BLOCKS NUM_FREELIST_BLOCKS DEGREE                                   INSTANCES
---------- ------------ ---------- ---------- ----------- ------------------------- ------------------- ---------------------------------------- ----------------------------------------
CACHE                TABLE_LOCK                       SAMPLE_SIZE LAST_ANALYZED                 PARTITIONED  IOT_TYPE                                         TEMP SECO NESTED
-------------------- -------------------------------- ----------- ----------------------------- ------------ ------------------------------------------------ ---- ---- ------------
BUFFER_POOL                  FLASH_CACHE                  CELL_FLASH_CACHE             ROW_MOVEMENT                     GLOBAL_STATS USER_STATS
---------------------------- ---------------------------- ---------------------------- -------------------------------- ------------ ------------
DURATION                                                     SKIP_CORRUPT                     MONITORING
------------------------------------------------------------ -------------------------------- ------------
CLUSTER_OWNER
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DEPENDENCIES                     COMPRESSION                      COMPRESS_FOR                                                                                                             DROPPED
-------------------------------- -------------------------------- ------------------------------------------------------------------------------------------------------------------------ ------------
READ_ONLY    SEGMENT_CREA RESULT_CACHE                 CLUSTERING   ACTIVITY_TRACKING
------------ ------------ ---------------------------- ------------ --------------------------------------------------------------------------------------------
DML_TIMESTAMP                                                                                        HAS_IDENTITY CONTAINER_DA INMEMORY                         INMEMORY_PRIORITY
---------------------------------------------------------------------------------------------------- ------------ ------------ -------------------------------- --------------------------------
INMEMORY_DISTRIBUTE                                          INMEMORY_COMPRESSION                                                 INMEMORY_DUPLICATE
------------------------------------------------------------ -------------------------------------------------------------------- ----------------------------------------------------
DEFAULT_COLLATION
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DUPL SHAR EXTERNAL     HYBRID       CELLMEMORY                                                                                       CONTAINERS_D CONTAINER_MA EXTENDED_DAT EXTENDED_DAT
---- ---- ------------ ------------ ------------------------------------------------------------------------------------------------ ------------ ------------ ------------ ------------
INMEMORY_SERVICE
------------------------------------------------
INMEMORY_SERVICE_NAME
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CONTAINER_MA MEMOPTIMIZE_READ                 MEMOPTIMIZE_WRITE                HAS_SENSITIV ADMIT_NULL   DATA_LINK_DM LOGICAL_REPLICATION
------------ -------------------------------- -------------------------------- ------------ ------------ ------------ --------------------------------
CMLI_REP_OWN
TB_CBC_CRITERIA                                                                                                                  CMLI_REP_D


VALID                                    10                     1        255         163840     1048576           1  2147483645                                         YES          N           787
         3            0          0          0          92                         0                   0          1                                        1
    N                ENABLED                                  787 07-OCT-2015 10:11:42          NO                                                            N    N    NO
DEFAULT                      DEFAULT                      DEFAULT                      DISABLED                         YES          NO
                                                             DISABLED                         YES

DISABLED                         DISABLED                                                                                                                                                  NO
NO           YES          DEFAULT                      NO
                                                                                                     NO           NO           DISABLED

USING_NLS_COMP
N    N    NO           NO                                                                                                            NO           NO           NO           NO


NO           DISABLED                         DISABLED                         NO           NO           NO           ENABLED

**Comment by joguess** [comment]
SYS@> SELECT * FROM ALL_TABLES A WHERE A.OWNER='CMLI_REP_OWN' AND A.TABLE_NAME='TB_CBC_CRITERIA';

OWNER
--------------------------------------------------------------------------------------------------------------------------------
TABLE_NAME                                                                                                                       TABLESPACE_NAME
-------------------------------------------------------------------------------------------------------------------------------- ------------------------------
CLUSTER_NAME
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
IOT_NAME
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
STATUS                             PCT_FREE   PCT_USED  INI_TRANS  MAX_TRANS INITIAL_EXTENT NEXT_EXTENT MIN_EXTENTS MAX_EXTENTS PCT_INCREASE  FREELISTS FREELIST_GROUPS LOGGING      BACK   NUM_ROWS
-------------------------------- ---------- ---------- ---------- ---------- -------------- ----------- ----------- ----------- ------------ ---------- --------------- ------------ ---- ----------
    BLOCKS EMPTY_BLOCKS  AVG_SPACE  CHAIN_CNT AVG_ROW_LEN AVG_SPACE_FREELIST_BLOCKS NUM_FREELIST_BLOCKS DEGREE                                   INSTANCES
---------- ------------ ---------- ---------- ----------- ------------------------- ------------------- ---------------------------------------- ----------------------------------------
CACHE                TABLE_LOCK                       SAMPLE_SIZE LAST_ANALYZED                 PARTITIONED  IOT_TYPE                                         TEMP SECO NESTED
-------------------- -------------------------------- ----------- ----------------------------- ------------ ------------------------------------------------ ---- ---- ------------
BUFFER_POOL                  FLASH_CACHE                  CELL_FLASH_CACHE             ROW_MOVEMENT                     GLOBAL_STATS USER_STATS
---------------------------- ---------------------------- ---------------------------- -------------------------------- ------------ ------------
DURATION                                                     SKIP_CORRUPT                     MONITORING
------------------------------------------------------------ -------------------------------- ------------
CLUSTER_OWNER
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DEPENDENCIES                     COMPRESSION                      COMPRESS_FOR                                                                                                             DROPPED
-------------------------------- -------------------------------- ------------------------------------------------------------------------------------------------------------------------ ------------
READ_ONLY    SEGMENT_CREA RESULT_CACHE                 CLUSTERING   ACTIVITY_TRACKING
------------ ------------ ---------------------------- ------------ --------------------------------------------------------------------------------------------
DML_TIMESTAMP                                                                                        HAS_IDENTITY CONTAINER_DA INMEMORY                         INMEMORY_PRIORITY
---------------------------------------------------------------------------------------------------- ------------ ------------ -------------------------------- --------------------------------
INMEMORY_DISTRIBUTE                                          INMEMORY_COMPRESSION                                                 INMEMORY_DUPLICATE
------------------------------------------------------------ -------------------------------------------------------------------- ----------------------------------------------------
DEFAULT_COLLATION
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DUPL SHAR EXTERNAL     HYBRID       CELLMEMORY                                                                                       CONTAINERS_D CONTAINER_MA EXTENDED_DAT EXTENDED_DAT
---- ---- ------------ ------------ ------------------------------------------------------------------------------------------------ ------------ ------------ ------------ ------------
INMEMORY_SERVICE
------------------------------------------------
INMEMORY_SERVICE_NAME
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CONTAINER_MA MEMOPTIMIZE_READ                 MEMOPTIMIZE_WRITE                HAS_SENSITIV ADMIT_NULL   DATA_LINK_DM LOGICAL_REPLICATION
------------ -------------------------------- -------------------------------- ------------ ------------ ------------ --------------------------------
CMLI_REP_OWN
TB_CBC_CRITERIA                                                                                                                  CMLI_REP_D


VALID                                    10                     1        255         163840     1048576           1  2147483645                                         YES          N           787
         3            0          0          0          92                         0                   0          1                                        1
    N                ENABLED                                  787 07-OCT-2015 10:11:42          NO                                                            N    N    NO
DEFAULT                      DEFAULT                      DEFAULT                      DISABLED                         YES          NO
                                                             DISABLED                         YES

DISABLED                         DISABLED                                                                                                                                                  NO
NO           YES          DEFAULT                      NO
                                                                                                     NO           NO           DISABLED

USING_NLS_COMP
N    N    NO           NO                                                                                                            NO           NO           NO           NO


NO           DISABLED                         DISABLED                         NO           NO           NO           ENABLED

what do you want to know

**Comment by joguess** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/e54425/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/e54425/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



CMLI_REP_OWN |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
TB_CBC_CRITERIA |   |   |   |   |   |  
CMLI_REP_D |   |   |   |   |   |  
  |   |   |   |   |   |  
  |   |   |   |   |   |  
VALID | 10 |   | 1 | 255 |   |  
163840 | 1048576 | 1 | 2,15E+09 |   |   |  
  | YES | N | 787 | 3 | 0 | 0
0 | 92 | 0 | 0 |   |   |  
1 |   |   |   |   |   |  
1 | N |   |   |   |   |  
ENABLED | 787 | 07-10-15 10:11 |   |   |   |  
NO |   | N | N |   |   |  
NO | DEFAULT | DEFAULT |   |   |   |  
DEFAULT | DISABLED | YES |   |   |   |  
NO |   |   |   |   |   |  
DISABLED | YES |   |   |   |   |  
  |   |   |   |   |   |  
DISABLED | DISABLED |   |   |   |   |  
  |   |   |   |   |   |  
NO | NO | YES | DEFAULT | NO |   |  
  |   |   |   |   |   |  
  |   |   |   |   |   |  
NO | NO | DISABLED |   |   |   |  
  |   |   |   |   |   |  
  |   |   |   |   |   |  
  |   |   |   |   |   |  
  |   |   |   |   |   |  
USING_NLS_COMP |   |   |   |   |   |  
N | N | NO | NO |   |   |  
  |   |   |   |   |   |  
NO | NO | NO | NO |   |   |  
  |   |   |   |   |   |  
  |   |   |   |   |   |  
NO | DISABLED | DISABLED |   |   |   |  
NO | NO | NO | ENABLED |   |   |  



</body>

</html>

**Comment by joguess** [comment]
[result.xlsx](https://github.com/darold/ora2pg/files/7829321/result.xlsx)

**Comment by darold** [comment]
Well there is no reason that this table can not be exported the only reason I see is that there is a problem at Oracle side like the error message indicate: ` ORA-00600: internal error code...`.  Actually if this was just a syntax error we will not have an ORA-00600 and `<*>` is added by Oracle to show where the problem is, it is not a string added by Ora2Pg.

You can try to use a DBA role with ORACLE_USER in ora2pg.conf and if this is the same perhaps you can try to copy the table using CREATE TABLE test (...) then INSERT INTO ... SELECT * FROM CMLI_REP_OWN.TB_CBC_CATEGORY and export the new table to see if the problem still occurs.

**Comment by darold** [comment]
Also please give a try to latest development code there were some important fixes recently.

**Comment by joguess** [comment]
Hello,
Thanks for your feedback.
Regards.

**Comment by joguess** [comment]
ok
