### ISSUE TITLE
VIEW_AS_TABLE regression for FILE_PER_TABLE on data export

### ISSUE THREAD

**Issue by SebAlbert** [darold/ora2pg#1351]
Today I found that in Version 23.0 the combination of the three directives `VIEW_AS_TABLE`, `FILE_PER_TABLE` and `TYPE COPY` (as well as `TYPE INSERT`) produces an empty main output file (only `BEGIN` and `COMMIT`, no psql includes) and no data files.

This may or may not be related or the same as #1331 

This is a regression. I can confirm that the very same configuration against the very same Oracle source database worked in both Version 19.0 and 21.0. It must have been introduced between 21.0 and 23.0.

**Comment by darold** [comment]
Thanks for the report, that's right actually there was two regression. Fixed in commit 75c1893.
