### ISSUE TITLE
Ora2pg datatransfer is very slow

### ISSUE THREAD

**Issue by prash2612** [darold/ora2pg#1352]
Hi , 

I am using ora2pg version 21.1 for transferring a table containing 160 million records. The speed is extremely slow i.e. 700 recs/per sec

    My db VM server configuration is 8 core / 16GB RAM 
    With this speed, it will take approx 5 days to complete data transfer for just one table. 
    This table has 400 columns with 2 RAW columns to be converted to bytea . 

Could you please advise how to improve the speed of this data transfer?

**Comment by joguess** [comment]
Hello,
Can you show the command you write please ?
have you set the following parameters : 
DATA_LIMIT
DEFAULT_PARALLELISM_DEGREE
JOBS
ORACLE_COPIES
PARALLEL_TABLES

you can also put on command lines 

-j
-J
-P <nummber>

"man ora2pg" will help also.

I suggest you to do a benchmark and to try some combination. 

You can also have a look on this performance tuning : https://www.darold.net/confs/ora2pg-performances.pdf

Regards,

J.

**Comment by darold** [comment]
Without answer from the author, I closing this issue.
