### ISSUE TITLE
Error while etracting data

### ISSUE THREAD

**Issue by kirandba-hub** [darold/ora2pg#1354]
Hi Darold,

Greetings for the day,

I'm receiving below FATAL message while extracting the data from Oracle
FATAL: Can't open tmp_EMPLOYEE_/projects/migration/Employee.txt : No such file or directory

Could you please suggest me what needs to done here to fix this

**Comment by joguess** [comment]
Hello, 
Can you show the command you wrote ?
Can you access the directory like this  : 
`ls -l tmp_EMPLOYEE_/projects/migration`  

Regards.
J.

**Comment by darold** [comment]
As @joguess suggest, please add you ora2pg command line and the value you have set to OUTPUT configuration directive.
The value for OUTPUT or -o option must not include a path, if you want to save the output files into a dedicated directory use option -b or OUTPUT_DIR to set the base directory.

**Comment by kirandba-hub** [comment]
Thank you @joguess @darold for response,followed your instructions and issue got resolved..
After command got executed,i'm getting below message

Wide character in print at /usr/lib64/perl5/IO/Handle.pm line 417.EMPLOYEE

extract was done,but i'm seeing the above message on-screen.what exact it means any action needs to take?
