### ISSUE TITLE
Data extracting is Slow

### ISSUE THREAD

**Issue by kirandba-hub** [darold/ora2pg#1358]
Hi,

I'm extracting the data and the extraction speed is very slow it is extracting 109 recs/sec.
Can you please suggest how to increase the extraction speed.

I'm using below command

ora2pg -n test -a Employee -J 4 -j 4 -o employee.txt

[========================>] 1/1 tables (100.0%) end of scanning.
[>                        ]     30075/147236741 rows (0.0%) Table P008 (275 sec., 109 recs/sec)
[>                        ]     30092/147236741 rows (0.0%) Table P004 (284 sec., 105 recs/sec)
[>                        ]     29957/147236741 rows (0.0%) Table P005 (282 sec., 106 recs/sec)
[>                        ]     29961/147236741 rows (0.0%) Table P003 (294 sec., 101 recs/sec)
[>                        ]     30137/147236741 rows (0.0%) Table P002 (282 sec., 106 recs/sec)
[>                        ]     29963/147236741 rows (0.0%) Table P001 (298 sec., 100 recs/sec)
[>                        ]     30041/147236741 rows (0.0%) Table P006 (277 sec., 108 recs/sec)
[>                        ]     30141/147236741 rows (0.0%) Table P007 (269 sec., 112 recs/sec)
[>                        ]     29854/147236741 rows (0.0%) Table P064 (274 sec., 108 recs/sec)
[>                        ]     29858/147236741 rows (0.0%) Table P063 (279 sec., 107 recs/sec)
[>                        ]    320099/147236741 total rows (0.2%) - (3006 sec., avg: 106 recs/sec), P062 in progress.

Please guide me on this

**Comment by darold** [comment]
How much CPU and memory do you have for Ora2Pg? Also I guess that there is BLOB on this table, can you post the Oracle description?

**Comment by kirandba-hub** [comment]
Yes,there is BLOB on this table and also partitions are about 170.I'm extracting the data year wise and moth wise

CPU : 4
memory : 8
swap : 4

Table count for 2018 is 201821647
Table columns : 150
No. of BLOB column : 1 
Jan Month count : 2583011
REPLACE_QUERY : select * from test.employee where extract(year from DATE)=2018 and extract(month from DATE)=1

**Comment by darold** [comment]
Well with only 4 CPU setting `-J 4 -j 4` is a very bad idea, Ora2Pg will try to use 16 CPU by forking 16 process and all will try to take 100% of their CPU. In your case I would only use `-J 4`.

You may also want to set BLOB_LIMIT to 100 in your ora2pg.conf.

You might also want to try to use the Oracle FDW to import this table. This can be done by installing oracle_fdw and by setting FDW_SERVER in ora2pg.conf.

**Comment by kirandba-hub** [comment]
Thanks @darold i will note the suggestions given by you.
Also,one more doubt if i don't comment the JOBS on ora2pg and i give- -J 4 in command,ora2pg will pick the parameter form configuaration or it will pick from command

**Comment by darold** [comment]
Parameters in command line always have precedence on the configuration file, so yes it will pick from command line.

**Comment by kirandba-hub** [comment]
Thanks @darold

**Comment by kirandba-hub** [comment]
I have set BLOB_LIMT to 100 and -J 4 ,but i didn't see significant performance in extraction,is there any configuaration need to change in ora2pg.conf for BLOB data type table.

Below is the extraction speed after setting the BLOB_LIMIT

30708/147236741 rows (0.0%) Table P029 (286 sec., 107 recs/sec)
[>                        ]     30305/147236741 rows (0.0%) Table P028 (289 sec., 104 recs/sec)
[>                        ]     30172/147236741 rows (0.0%) Table P027 (282 sec., 106 recs/sec)
[>                        ]     30349/147236741 rows (0.0%) Table P026 (289 sec., 105 recs/sec)
[>                        ]     30245/147236741 rows (0.0%) Table P025 (288 sec., 105 recs/sec)
[>                        ]     30251/147236741 rows (0.0%) Table P024 (295 sec., 102 recs/sec)
[>                        ]     29990/147236741 rows (0.0%) Table P023 (292 sec., 102 recs/sec)
[>                        ]   1519683/147236741 total rows (1.0%) - (14352 sec., avg: 105 recs/sec), P022 in progress.

It is exttracting approx 105 recs/sec,is there anyway to increase this extraction speed.

**Comment by darold** [comment]
In this case you should increase the amount of memory and cpu, the more core you have the more parallism you can use. Have you tried using oracle_fdw,?Ora2Pg is usually 3 time faster when used.

**Comment by kirandba-hub** [comment]
No, i didn't try oracle_fdw.

If i use -J is there any data inconsistency,because i see the difference in extraction count and different count in Oracle database

**Comment by darold** [comment]
It should not have a difference count unless there is writing into the Oracle database during the export. If not you may have some Ora2Pg process killed because of out of memory, in this case reduce LOB_LIMIT to 25 or 50. Ora2Pg with oracle_fdw for this table is a must try.

**Comment by kirandba-hub** [comment]
We are extracting the data into files and then we are importing those into postgres server,as we are importing the tables manually.
For only extracting oracle_fdw will help here?

**Comment by darold** [comment]
You should direct data import to PG this is more performant.

**Comment by kirandba-hub** [comment]
I have now Memory 16GB and CPU of 8 on server where ora2pg installed.Below command is using with BLOB_LIMT of 25

ora2pg -n test -a employee -J 3 -j 2 -o employee.txt

Also i'm executing above command 3 at a time with above BLOB_LIMT,will this fine to excute the parallel run on server with these configuation?
