### ISSUE TITLE
Can't connect to Oracle db 

### ISSUE THREAD

**Issue by Jrsnow8921** [darold/ora2pg#136]
I am trying to connect to my Oracle db, but for some reason I am unable to do so. Any help would be # greatly appreciated!(I changed my sid, username, and password for security reasons to display my issue)

# Here is the error --> 

programmer@snowserver:~$ ora2pg -u interact
DBI connect('host=172.16.1.139;sid=test;port=1521','interact',...) failed: ORA-01017: invalid username/password; logon denied (DBD ERROR: OCISessionBegin) at /usr/local/share/perl/5.18.2/Ora2Pg.pm line 1139.
FATAL: 1017 ... ORA-01017: invalid username/password; logon denied (DBD ERROR: OCISessionBegin)
Aborting export...

# I can however access my oracle db with the same credentials via sqlplus 

programmer@snowserver:/opt/oracle/instantclient_11_2$ ./sqlplus testuser/somepassword@test

SQL*Plus: Release 11.2.0.4.0 Production on Tue Sep 22 10:07:48 2015

Copyright (c) 1982, 2013, Oracle.  All rights reserved.

Connected to:
Oracle Database 11g Enterprise Edition Release 11.1.0.6.0 - Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options

SQL> 

I'm using Xubuntu 
Oracle db is 11g 

# Here is my bash---

export ORACLE_HOME=/opt/oracle/instantclient_11_2/
export ORACLE_SID=test   
export TNS_ADMIN=/opt/oracle/network/admin/tnsnames.ora

# Here is my tnsname.ora

test =
(DESCRIPTION =
 (ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.1.139)(PORT = 1521)
  )
 (CONNECT_DATA =
  (SERVICE_NAME= test)
  )
 )

# And here is my ora2pg.conf 

ORACLE_HOME     /opt/oracle/instantclient_11_2
####TNS_ADMIN       /opt/oracle/instantclient_11_2/network/admin/tnsnames.ora

ORACLE_DSN      dbi:Oracle:host=172.16.1.139;sid=test;port=1521
ORACLE_USER     testuser
ORACLE_PWD       somepassword

USER_GRANTS     1

DEBUG           0

ORA_INITIAL_COMMAND

**Comment by darold** [comment]
Hi,

Why are you using a tnsnames.ora? You don't need it when using instantclient and DBI. Everything is in the datasource.

Try to reset TNS_ADMIN and let me know.

Regards,

**Comment by Jrsnow8921** [comment]
Okay that worked thank you! @darold

**Comment by stirumala76** [comment]
The tool also fails to log in to your oracle DB  if your oracle user  password has $ as a special character in it.

![image](https://user-images.githubusercontent.com/4968423/200680325-b33515a6-b880-44e7-9ffe-65e841c98fb6.png)
