### ISSUE TITLE
Unable to find sources/tables in Ora2pg when create project

### ISSUE THREAD

**Issue by dilansalinda** [darold/ora2pg#1361]
Ora2pg Version: v21.0
Oracle version: 12c
 
Below is the project structure created by ora2pg using **ora2pg --init-project** command.

```
schema/
         dblinks/
         directories/
         functions/
         grants/
         mviews/
         packages/
         partitions/
         procedures/
         sequences/
         synonyms/
         tables/
         tablespaces/
         triggers/
         types/
         views/
```

```
sources/
         functions/
         mviews/
         packages/
         partitions/
         procedures/
         triggers/
         types/
         views/
```

sources and schema folders after export (after execute export_schema.sh).

The sources directory will contains the Oracle code and schema will contains the code ported to PostgreSQL.

Ora2pg does not create tables/table.sql file(sql file name may change) in sources directory(Oracle code).

Question is, Is there any option to export Oracle create tables DDL's

**Comment by darold** [comment]
No, actually the interest of the Oracle sources is on being able to compare the code translated by Ora2Pg with the original code to fix conversion issues.
