### ISSUE TITLE
Missing decode for hex blob 

### ISSUE THREAD

**Issue by pierre-yves-crutzen** [darold/ora2pg#1363]
Hello,

I have an error on INSERT and COPY commands when inserting/copying some parsed blob as bytea in Postgre.
 The reason is the following message : "ERROR: syntax error at or near « <hex code> ... "
 
I made a test by replacing the parsed blob hex code to the following for each row in insert command :
 
 INSERT INTO ... (...) VALUES (... , <hex> , ...
 to  
 INSERT INTO ... (...) VALUES (... , "decode('<hex-code>', 'hex') , ...
 
The problem was resolved as this but I didn't found if I missed something in the documentation. I'm surprised that nobody have already reported this kind of problem. It might appear in many cases..

It's a critical problem when people have very large sql files that couldn't be edited to replace it.

Thanks for the tool, it's a very good one.

**Comment by darold** [comment]
This is a regression introduced with commit 3076f022. Commit 4063f78 might fix this issue. Actually the INSERT action should never be used unless for special SQL compatibility case this is why there was no issue already opened. Use action COPY instead this is far more performant.
