### ISSUE TITLE
Extract fails with FATAL: _extract_data() ORA-00604: error occurred at recursive SQL level 1

### ISSUE THREAD

**Issue by kirandba-hub** [darold/ora2pg#1364]
we are extracting the data from Oracle archive DB, and there will be no transactions on this DB but still we are receiving below error

FATAL: _extract_data() ORA-00604: error occurred at recursive SQL level 1
ORA-08177: can't serialize access for this transaction (DBD ERROR: OCIStmtExecute/Describe)

We can't change the serialize on Oracle DB,if i change the TRANSACTION to readonly in ora2pg.conf,the extract is working but only few records only extracting from the table.

In some scenarios, when i got this error, we are re-running again and that time error is disappearing.

We are extracting year wise and month wise data,also table having 150 columns with BLOB data type and 125 partitions

Could you please suggest us why this error is coming.

Server  Specifications :

RAM : 16GB
CPU : 8

**Comment by darold** [comment]
If the table is not modified or that there is no coherence issue you should use readonly or committed for the TRANSACTION ora2pg configuration directive.  I don't really know what happen when an Oracle transaction is openned in READONLY mode, you should contact an Oracle DBA, but if it don't works too, use committed.
