### ISSUE TITLE
DEFAULT_PARALLELISM_DEGREE doesn't work because of wrong num_rows lookup

### ISSUE THREAD

**Issue by mpils** [darold/ora2pg#1365]
Hi,
using DEFAULT_PARALLELISM_DEGREE > 1 doesn't work in my environment.
Oracle Parallel hint is missing in generated SQLs.

Problem seams to be located in Ora2Pg.pm line 10561.
The lookup for '$self->{tables}{"\L$table\E"}{table_info}{num_rows}' looks for a lower case table name but the ' $self->{tables}' hash contains upper case table names.

So changed line 10561 from 
if ($self->{tables}{"\L$table\E"}{table_info}{num_rows} > $self->{parallel_min_rows}) {
to
if ($self->{tables}{$table}{table_info}{num_rows} > $self->{parallel_min_rows}) {

and now it works fine for me.

Is this a common bug or an issue related to my environment?
Ora2Pg::Oracle::_table_info returns upper case table names in my environment.

Regards,
Marcel.

**Comment by darold** [comment]
Right, I don't know why the lowercase was not removed here, this is the only place where it was used. Commit  5f22a4a  applies your patch.
