### ISSUE TITLE
Extracting single partition from a table

### ISSUE THREAD

**Issue by kirandba-hub** [darold/ora2pg#1368]
Hi,

In my table there are 130 partitons,in which i want to extract only selective partitions,for that i put an query in REPLACE_QUERY but when i execute ora2pg it is extracting all partitions in that table

Below is the query i'm using,same query in oracle it is giving output

select * from test.employee PARTITION(P001) where (extract year from DATE) = 2020 and (extract month from DATA) = 1;

is this correct way to extract partition from a table,Please help me here

**Comment by darold** [comment]
Extracting data from a specific partition is not supported yet, This need lot of development, the way tables are selected for data export must be reviewed which will take lot of time.

**Comment by kirandba-hub** [comment]
Thanks @darold
