### ISSUE TITLE
Effect of PARALLEL_TABLES setting on VIEW export

### ISSUE THREAD

**Issue by xinferum** [darold/ora2pg#1369]
Hello.

Today we discovered that the PARALLEL_TABLES parameter affects the VIEW export.
When PARALLEL_TABLES is set to 1, all views are exported from Oracle to one file schema/view/view.sql. But if you enable parallel processing by increasing PARALLEL_TABLES for example to 2, then views are exported to separate *.sql files in schema/view/.

The documentation https://ora2pg.darold.net/documentation.html#PARALLEL_TABLES says nothing about this parameter effect:
```
This directive is used to defined the number of tables that will be processed in parallel for data extraction. ...
```

Moreover, in the JOBS parameter associated with it, the impact on VIEW is also not indicated:
```
This configuration directive adds multiprocess support to COPY, FUNCTION and PROCEDURE export type ...
```

While the TABLES themselves are always exported to a single schema/table/table.sql file.
This parameter also has no effect on MVIEW.

**Comment by darold** [comment]
Actually enabling PARALLEL_TABLES force FILE_PER_TABLE to be activated and this is use when exporting table and views. I have updated the documentation in commit 84070b0

**Comment by xinferum** [comment]
Thank you!
