### ISSUE TITLE
DISABLE_TRIGGERS ALL not working?

### ISSUE THREAD

**Issue by Rokko11** [darold/ora2pg#137]
Hi darold,

I export some tables in the same schema `$1` via the command:

```
ora2pg -t COPY -c ${CONFIG_FILE} -n ${schema}
```
In my config-file I have specified `DISABLE_TRIGGERS ALL` and I'm running it as a superuser.

When I'm running this command, I have to change `TRUNCATE_TABLE	1` to 0. I guess, `DISABLE_TRIGGERS` runs after `TRUNCATE TABLE` and `TRUNCATE TABLE` runs without `CASCADE`-directive.

Regards,
Rokko

**Comment by darold** [comment]
SQL statements appears in this order:

BEGIN; 
ALTER TABLE t1 DISABLE TRIGGER ALL;
TRUNCATE TABLE t1;

COPY t1 (col1,clo2,...) FROM STDIN;
...
\.

ALTER TABLE t1 ENABLE TRIGGER ALL;

END;

Yes truncate does not use CASCADE.
