### ISSUE TITLE
AUTONOMOUS_TRANSACTION translation does not appear to work on triggers

### ISSUE THREAD

**Issue by bonesmoses** [darold/ora2pg#1373]
While testing ora2pg 23.0 on Oracle 18c, we saw that the following trigger was _mostly_ converted. This is the original DDL:

```sql
CREATE OR REPLACE TRIGGER AUDIT_SAL
   AFTER UPDATE OF salary ON employees FOR EACH ROW
DECLARE
   PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
-- bind variables are used here for values
   INSERT INTO emp_audit VALUES( :old.employee_id, SYSDATE,
                                 :new.salary, :old.salary );
  COMMIT;
END;
```

And this is the converted DDL:

```sql
DROP TRIGGER IF EXISTS audit_sal ON employees CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_audit_sal() RETURNS trigger AS $BODY$
DECLARE
   PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
-- bind variables are used here for values
   INSERT INTO emp_audit VALUES ( OLD.employee_id, LOCALTIMESTAMP,
                                 NEW.salary, OLD.salary );
  COMMIT;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_audit_sal() FROM PUBLIC;

CREATE TRIGGER audit_sal
        AFTER UPDATE OF salary ON employees FOR EACH ROW
        EXECUTE PROCEDURE trigger_fct_audit_sal();
```

Note that the trigger is properly split into a function and trigger declaration, but the `AUTONOMOUS_TRANSACTION` pragma is left as is without introducing the expected dblink syntax. The `AUTONOMOUS_TRANSACTION` option is enabled in `ora2pg.conf`

**Comment by darold** [comment]
Commit e3cd703 should add this feature, Note that all the trigger procedural code is moved to the function executed via dblink or pg_background so if some parts are behaviors that should be part of the trigger function itself this code must be manually
moved back to this function. Let me know if that's works as expected for you.

**Comment by bonesmoses** [comment]
It appears the syntax used here has a few issues:

1. You can't embed `NEW` and `OLD` into the `v_query` string because they are records. Currently this would only pass the liter text `NEW` and `OLD`. Perhaps passing them as JSONB with `row_to_jsonb` would work.
2. This may also apply to standard dblink calls, but calling `PERFORM` directly on a dblink call results in the following error:
    ERROR:  function returning record called in context that cannot accept type record
    CONTEXT:  SQL statement "SELECT dblink(v_conn_str, v_query)"

I haven't tested this with `pg_background` yet. I can see why these weren't converted until now.

**Comment by darold** [comment]
Yes, I try an other attempt to support this feature by sharing idea with you ( I have not though about row_to_jsonb option ), but there is serious limitation for that outside the huge performance issue for each DML.

**Comment by darold** [comment]
I have reverted the commit, I don't see a way to to have something really useful with automatic translation. This still need to be handled manually.
