### ISSUE TITLE
Encoding errors on data copy / insert

### ISSUE THREAD

**Issue by pierre-yves-crutzen** [darold/ora2pg#1375]
Hello,

Thanks for this very useful tool.

I encounter a problem I can't resolve instead of changing the config file :

**Context**
Speaking French, I have a database with some special characters "é", "è", "à", "ù", "ê".... on Windows. 
And here is the encoding context from the Oracle DB with the return from the following query : 
_SELECT * FROM NLS_DATABASE_PARAMETERS_ :

_NLS_RDBMS_VERSION	19.0.0.0.0
NLS_NCHAR_CONV_EXCP	FALSE
NLS_LENGTH_SEMANTICS	BYTE
NLS_COMP	BINARY
NLS_DUAL_CURRENCY	$
NLS_TIMESTAMP_TZ_FORMAT	DD-MON-RR HH.MI.SSXFF AM TZR
NLS_TIME_TZ_FORMAT	HH.MI.SSXFF AM TZR
NLS_TIMESTAMP_FORMAT	DD-MON-RR HH.MI.SSXFF AM
NLS_TIME_FORMAT	HH.MI.SSXFF AM
NLS_SORT	BINARY
NLS_DATE_LANGUAGE	AMERICAN
NLS_DATE_FORMAT	DD-MON-RR
NLS_CALENDAR	GREGORIAN
NLS_NUMERIC_CHARACTERS	.,
NLS_NCHAR_CHARACTERSET	AL16UTF16
NLS_CHARACTERSET	AL32UTF8
NLS_ISO_CURRENCY	AMERICA
NLS_CURRENCY	$
NLS_TERRITORY	AMERICA
NLS_LANGUAGE	AMERICAN_

**Problem**

After a copy export, and looking at the separated files exported (one by table), some errors are triggered because of encoding type :
_"ERROR:  ... value too long for type character varying(756)"_ . The reason is that the original string length is strictly 756, and after the conversion with ora2pg , special characters like "é" became "Ã©" when reading it in PSQL with windows.

So, according to another issue,  [https://github.com/darold/ora2pg/issues/109](https://github.com/darold/ora2pg/issues/109) , I need to change the CLIENT_ENCODING option with WIN1252 to get an encoding type "Western Europe"

I tried to force ora2pg to transform those wrong encoding characters with the following options :
_NLS_LANG	AMERICAN_AMERICA.AL32UTF8   # I also tried with FRENCH_FRANCE.AL32UTF8
NLS_NCHAR	AL32UTF8
CLIENT_ENCODING	 WIN1252 # and UTF8_

But, nothing changed.  I have the same results with both COPY and INSERT commands. 

**Observations**
After generating the files, if I open the output data scripts with some editing tools, I can see the encoding type is still UTF-8 even if a change the option CLIENT_ENCODING  to  WIN1252.

The only way I found to resolve little data files is to change it manually, but I can't resolve this error on very large files or on a huge DB.

**Question**

Did I miss something in the documentation ? 

If there are no bug, the answer could help some people. I saw I'm not the only one who encountered this kind of unresolved encoding config problem on other platforms (forums, Stackoverflow, ...).

Thanks for your help

**Comment by darold** [comment]
Have you tried without setting NLS_LANG and NLS_NCHAR in ora2pg.conf and importing data directly into PostgreSQL? Usually with direct data import there is no encoding issues. If you still want to export the data to files try to change the system locale to en_US.utf8.

**Comment by pierre-yves-crutzen** [comment]
Well, as you said, it worked with a direct data import. 


When the transfer is done on huge tables, it takes a very long time (3 recs/sec). Then, after the import, errors happen like : 
" FATAL: ORA-01555: snapshot too old: rollback segment number 10 with name "_SYSSMU10_3563521556$" too small (DBD ERROR: error possibly near <*> indicator at char ..." 

But the data look to have been successfully copied. I don't know if the DB integrity is  preserved.

However, thanks for your help!
