### ISSUE TITLE
DBD ERROR: OCIAttrGet OCI_ATTR_PARAM_COUNT

### ISSUE THREAD

**Issue by nkhemiri** [darold/ora2pg#1377]
Hi,
My env i s:
Oracle 12.1.0.2 on solaris x86 11
Postgres 13.4 on ubuntu 20
ora2pg 23.0 on ubuntu 20

I have this error : 
"FATAL: _column_attributes() ORA-24338: statement handle not executed (DBD ERROR: OCIAttrGet OCI_ATTR_PARAM_COUNT"

When i want to import data with -j 6 and -P 6, however No error raised when -j 4 and - P 4

As below :

ora2pg -j 6 -P 6 -c config/ora2pg.conf -t COPY --pg_dsn "dbi:Pg:dbname=...;host=...;port=5432" --pg_user postgres
[========================>] 212/212 tables (100.0%) end of scanning.
...
FATAL: _column_attributes() ORA-24338: statement handle not executed (DBD ERROR: OCIAttrGet OCI_ATTR_PARAM_COUNT)ogress.
FATAL: ORA-01012: not logged on
Process ID: 25792
Session ID: 855 Serial number: 6314 (DBD ERROR: OCIStmtExecute)
Aborting export...
Aborting export...
ERROR: an error occurs when importing data.

Thanks in advance.

Best regards,
Nabila

**Comment by darold** [comment]
How many processors do you have? Usually -j 3 or -j 4 is usually enough to have the best performances at PG writting, -P 6 is ok but you can use more than parallel table processing if you lot of CPUs. With -P 6 -j 4 Ora2pg will use 24 CPUs.

I have never encountered the DBD ERROR: OCIAttrGet OCI_ATTR_PARAM_COUNT maybe this is because you are trying to use more cores than you have and the systems is interrupting some fetch.

**Comment by nkhemiri** [comment]
Thanks for your answer.
I have 18 processors on solaris zone for oracle database.
16 processors on ora2pg Virtual machine 
16 processors on postgres virtual machine.

**Comment by darold** [comment]
Does -P 6 -j 2 and  -P 6 -j 3 produce the same error?

**Comment by nkhemiri** [comment]
with -j 4 and -P 5

[=====================>   ] 24286/26898 rows (90.3%) Table AUTOPROMO_CADRE (1 sec., 24286 recs/sec)
Can't call method "do" on an undefined value at /usr/local/share/perl/5.30.0/Ora2Pg.pm line 16510., AUTOPROMO_CADRE in progress.
Can't call method "do" on an undefined value at /usr/local/share/perl/5.30.0/Ora2Pg.pm line 16510.
Can't call method "do" on an undefined value at /usr/local/share/perl/5.30.0/Ora2Pg.pm line 16510.
Can't call method "do" on an undefined value at /usr/local/share/perl/5.30.0/Ora2Pg.pm line 16510., ABONNEMENT in progress.
Can't call method "do" on an undefined value at /usr/local/share/perl/5.30.0/Ora2Pg.pm line 16510.
Can't call method "do" on an undefined value at /usr/local/share/perl/5.30.0/Ora2Pg.pm line 16510.

**Comment by nkhemiri** [comment]
As i've said before Ok with j 4 -P 4
Is there any action to do to accelerate import Data with BLOB and CLOB ?
Thanks in advance.

**Comment by darold** [comment]
I think that the problem is related to Solaris, I have never encountered such error even with far more parallelism.

To improve BLOB export you must export the table separately from others using oracle_fdw, see Ora2Pg documentation.

**Comment by nkhemiri** [comment]
For your information, the error came from Oracle database profile restricted to 5 connexions.
Sorry for the inconvenience.

Regards,
Nabila
