### ISSUE TITLE
Importing invalid geometries

### ISSUE THREAD

**Issue by Rokko11** [darold/ora2pg#138]
Hi!

I have some non-closed polygons in my Oracle-db and want to transfer them to Postgres.

I use a DATA_LIMIT of 10000, but in every chunk there seems to be at least one invalid row.
```
HINT:  "...01616 49.123456, 9.123456 49.123456)," <-- parse error at position 2599 within geometry
ERROR (log error enabled): ERROR:  geometry contains non-closed rings
```

Is it possible to make them valid on runtime?
Is it possible to import them invalid and make them valid with sql

Or do I have to correct them in the source first?

Regards,
Rokko

**Comment by Rokko11** [comment]
Another option would be:
I have STOP_ON_ERROR disabled, but all the other valid records of my 10000-chunk do not get imported.

**Comment by darold** [comment]
You have to enable LOG_ON_ERROR, it will log the COPY statement to a file called TABLENAME_error.log in the output directory and continue to next bulk of data.

**Comment by darold** [comment]
Do you have any constraint type in your column definition, please join the definition of the table and the related indexes.

**Comment by Rokko11** [comment]
Hi!

No, there aren't any constraints on the table. Just one primary_key and one gist-index on the geometry-column.

My workaround now is:
- Dumping the copy-statements into a sql-File
- Transforming invalid geometries into valid ones via `sed`-command

  ```
sed -i 's/\((\)\([0-9. -]*\)\(, [^)]*\)/\1\2\3, \2/g' table_data.sql
Polygon (a,b,c,d,e,f) -> Polygon (a,b,c,d,e,f,a,b)
```
- Importing into postgres-Database.

Regards,
Rokko

**Comment by darold** [comment]
Thanks for the report. This is the problem with invalid geometries, they need to be rewritten.

Do you know a way to autodetect those invalid geometry in Oracle database so that Ora2Pg can close the polygon in automatic mode? And why are you adding a,b and not just a to close the polygon?

Regards,
