### ISSUE TITLE
Issue with v23.1: "Undefined subroutine &Ora2Pg::ReadLine"

### ISSUE THREAD

**Issue by simonpane** [darold/ora2pg#1381]
When `ORACLE_USER` is not defined in the `ora2pg.conf` file, the following error is encountered as of **v23.1**:

```
Enter Oracle username: Undefined subroutine &Ora2Pg::ReadLine called at /usr/local/share/perl5/Ora2Pg.pm line 19228.
```

Issus is specific to **v23.1** - does not occur with v23.0 or lower.

**Comment by darold** [comment]
This is because you are entering the interactive mode to set the username/password but you don't have installed the Perl module Term::ReadKey. I agree that a more explicit error should be fired in case the Perl module is not present, I will fix that.

**Comment by simonpane** [comment]
Sorry, @darold I should also confirm: yes installing `Term::ReadKey` does indeed resolve the original issue.  Though this requirement seems to be new with **v23.1** (did not require it previously).

But as mentioned, the ultimate goal is to have an empty string for the `{oracle_user}` and `{oracle_pwd}` and I'm not sure how to accomplish that.  So as a work around I use:

```
sudo sed -i '/DBI->connect($self->{oracle_dsn}/ s/$self->{oracle_user}, $self->{oracle_pwd},/"", "",/' /usr/local/share/perl5/Ora2Pg/Oracle.pm
```

And then it works (with the SEPS wallet).  Maybe there is a better way?  Thank you

**Comment by darold** [comment]
Hi Simon,

Commit 816ac21 remove the fail on Undefined subroutine &Ora2Pg::ReadLine" error to be able to continue without having specified an Oracle username and password. Thanks for the report.
