### ISSUE TITLE
Does it work on M1 Apple?

### ISSUE THREAD

**Issue by miyamoto-yosuke** [darold/ora2pg#1384]
Can it be worked on Apple Silicon (M1) environment?
If it doesn't work now, are there any plans to support it?

**Comment by darold** [comment]
I have never tested but I have never tried too. I don't have such environment so I can not think about such support.

**Comment by darold** [comment]
Actually after more though I will not send time to try to support MacOsX, I don't have enough time to dedicate to the project so adding support to an OS that I don't use will just be a lost of time. You should create a Linux VM on your Mac and install Ora2Pg on it.

**Comment by miyamoto-yosuke** [comment]
Sorry for the lack of explanation.

It worked on intel MAC Docker.
It didn't work with m1 mac docker.

I am using the following docker. 
https://hub.docker.com/_/perl

**Comment by miyamoto-yosuke** [comment]
I'm sorry again.
There was another cause. It worked correctly on m1 mac docker.

**Comment by sanyamsinghal** [comment]
Hi @miyamoto-yosuke can you share the steps you followed to install ora2pg on Mac Intel and M1 Mac both, mainly the steps to resolve the issues, because as far as i have experienced there are some issues/errors while installing the dependencies etc, on Mac
