### ISSUE TITLE
Carriage return during COPY export

### ISSUE THREAD

**Issue by Allure996** [darold/ora2pg#1387]
Hi, I'm facing a problem during data export with COPY.

In the export file, there are some `^M` characters that are not being escaped correctly: this ends with my COPY statement splitted on two different lines, and when I try to import the file with psql I have an errore dued to this fact.

The field which is giving me problems, is a `bytea` type, and In this case its value is `\\x^M`

How can I avoid this to happen? Is there any option or flag in the config file I can set to avoid this problem?

Thanks

**Comment by darold** [comment]
Can you please use latest development code, this issue could have been fixed with commit 481dba7. If not please give me the Oracle data type of the column.
