### ISSUE TITLE
Table partition schema generation issue.

### ISSUE THREAD

**Issue by deepakp555** [darold/ora2pg#1390]
Hi Darold, 

While i run the below command it generate nothing, Although there are table partitions created in my database. Please refer the ora2pg cost estimate attached report.

ora2pg -c config/ora2pg.conf -t PARTITION -o partition.sql -b schema/partitions/

![Ora2pg report](https://user-images.githubusercontent.com/64629858/158637348-4f7301a1-22a0-417e-bfce-baf95ea4ca65.PNG)

Please suggest.

**Comment by deepakp555** [comment]
I have also attached my conf file.

**Comment by darold** [comment]
You are using an obsolete version of Ora2Pg, please use latest development code and don't forget to set PG_VERSION to the target PostgreSQL database release in ora2pg.conf. This will helps Ora2Pg to know whatr should be activated, the PG_SUPPORTS_* configuration directives are obsoletes.
