### ISSUE TITLE
Ora2pg Compatibility and Supported version

### ISSUE THREAD

**Issue by jaehanchoi** [darold/ora2pg#1393]
Hi Darold,

I have two inquiries, so I left an action.

1. Currently on Github, Ora2pg version 23.1 has been released, and I would like to know which version of Oracle can support this version.

ex) Oracle 9i, 10g, 11g ...

2. I would like to know for sure or the compatibility range of Ora2pg 23.1 version only.

https://ora2pg.darold.net/documentation.html

I also searched for Features and Configuration of the address above, but I am curious for more detailed or accurate information.

Oracle and PostgreSQL object compatibility differences (or not supported) and

Data that quantifies the compatibility of objects converted during migration

Is there any organized information or reference material for Oracle object migration?

I thank you in advance for your help.

**Comment by darold** [comment]
Ora2Pg supports Oracle 8i to current, you must just use the Oracle client that allows to work with your Oracle database version. You should always use the latest development code or, if not possible, the latest Ora2Pg release.

About the documentation I agree that it needs lot of improvements especially on the points you have mentioned but for the moment, to answer to your question, you can state that Ora2Pg is doing his best to migrate all possible code and it is improved every days to support more translation automatically. For all that need manual editing you will find material on the Web on how to fix it. Using the assessment feature is also a good way to see the effort that should be provide for your migration.

If you or anyone have time to improve the documentation I will be please to review, contributions are always welcome.
