### ISSUE TITLE
Example of WHERE clause configuration 

### ISSUE THREAD

**Issue by joguess** [darold/ora2pg#1394]
Hello darold, 

Can  you please confirm the following syntax to be used for the WHERE clause inside the ora2pg.conf : 

WHERE  TABLE1[COLUMN1 in '1','2'] AND TABLE2[COLUMN2 in '1','2'] AND TABLE3[COLUMN3 in '1','2']

Regards,

joguess.

**Comment by darold** [comment]
Hi,

You must not use AND between the tables filter definition, something like the following should works:
```
WHERE      TABLE1[COLUMN1 in '1','2'] TABLE2[COLUMN2 in '1','2']  TABLE3[COLUMN3 in '1','2']
```

**Comment by joguess** [comment]
Thanks !
