### ISSUE TITLE
Can't set DBI::db=HASH(0x2ee1a28)->{AutoInactiveDestroy}: unrecognised attribute name or invalid value at /usr/lib64/perl5/DBI.pm line 708.

### ISSUE THREAD

**Issue by sttachoires** [darold/ora2pg#140]
```ORACLE_DSN	dbi:Oracle:host=lh-cappla-db.france.airfrance.fr;port=1547;sid=TEC07C```
since 16.0 I've got some errors...perhaps a bad configuration, but I can't figure out where...

```Can't set DBI::db=HASH(0x2ee1a28)->{AutoInactiveDestroy}: unrecognised attribute name or invalid value at /usr/lib64/perl5/DBI.pm line 708.```

**Comment by darold** [comment]
No, your configuration is ok, this is just that starting with version 16.0 you need DBI version upper than 1.614 . This solves lot of problem in multiprocess mode.

**Comment by sttachoires** [comment]
Ok. a complete cpan upgrade have done it :)
Brutal but efficient.
Thanks.
