### ISSUE TITLE
Stuck at "Retrieving table partitioning information..."

### ISSUE THREAD

**Issue by jolyonbrown** [darold/ora2pg#1404]
Hi

I'm attempting to export an old Oracle database running on Windows (Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - !) to a more secure permanent home (it's old audit data). 

ora2pg is running on a Linux client - no issues getting set up with the latest ora2pg release etc.  SHOW_VERSION and --estimate_cost work fine. But export attempts always get stuck at "Retrieving table partitioning information...". I've left it overnight in one case to no avail. Has anyone come across this issue before? 

In ora2pg.conf I've set TRANSACTION to readonly which reading some other issues I though might help, but to no avail. Any pointers welcome!

**Comment by jolyonbrown** [comment]
At the moment this looks like a super long query running on the Oracle side. Going to try and beef up the resources available there in an effort to speed this up.

**Comment by darold** [comment]
Please use latest development code, commits 87e6657 and 7ea7cac fix a bug that could be responsible of this slow query. Let me know.

**Comment by jolyonbrown** [comment]
No joy so far but I'll leave it a little while and I've got the resource additions to try as well. Will keep you posted. Thanks for letting me know about the commits!

**Comment by jolyonbrown** [comment]
I almost forgot - this worked! I've been a bit stop/start on this project, so apologies for the delay in updating. The fix definitely got me past the original place. The export_schema script then sat for an age (a couple of days!) at the next partition stage - I left it running (and admittedly went off to investigate the ora_migration fdw solution instead). Came back to it and the script had completed, exiting with the prompt to run the COPY step. All good so far with this next stage. Thank you!
