### ISSUE TITLE
Preserve case for TEST_COUNT

### ISSUE THREAD

**Issue by Veka** [darold/ora2pg#1406]
Hi!
Oracle table names aren't quted for TEST_COUNT, which lead to errors like:
> FATAL: ORA-00942: table or view does not exist (DBD ERROR: error possibly near <*> indicator at char 32 in 'SELECT COUNT(*) FROM A.<*>a')

I didn't really check it, but probably the same for schema names, too. There can be a table like "a"."a" in Oracle database.

**Comment by darold** [comment]
Commit 4f4e75b might fix the issue.
