### ISSUE TITLE
FATAL: _column_info() ORA-00911: invalid character (DBD ERROR: error possibly near <*> indicator at char 17 in 'SELECT ST_SRID(c.<*>%s) FROM %s c')

### ISSUE THREAD

**Issue by jieguolove** [darold/ora2pg#1408]
ora2pg -p -c xxx.conf -t TABLE -o table.sql

FATAL: _column_info() ORA-00911: invalid character (DBD ERROR: error possibly near <*> indicator at char 17 in 'SELECT ST_SRID(c.<*>%s) FROM %s c')
DBI::db=HASH(0x2ec0bb8)->disconnect invalidates 1 active statement handle (either destroy statement handles or call finish on them before disconnecting) at /usr/local/share/perl5/Ora2Pg.pm line 14893.
Aborting export...

error in all the versions from 21.1-23.1

**Comment by darold** [comment]
Please give a try to latest development code, commit b3ef5a8 might solve this issue.
