### ISSUE TITLE
Error while migrating data

### ISSUE THREAD

**Issue by sttachoires** [darold/ora2pg#141]
Got this error at the end of the transfert...doing a direct data transfert

Can't call method "disconnect" on unblessed reference at /usr/local/share/perl5/Ora2Pg.pm line 9998.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(HOST=lh-cappla-db.france.airfrance.fr)(PROTOCOL=tcp)(PORT=1547))(CONNECT_DATA=(SID=TEC07C))) at /usr/local/share/perl5/Ora2Pg.pm line 9998.

**Comment by darold** [comment]
This is fixed now in last commit 6dd0018, we were trying to close a database connexion handle that was only blessed in multiprocess mode.

Thanks for the report.
