### ISSUE TITLE
Can't use string ("POINT  ( 116.52600000 39.8032500") as an ARRAY ref while "strict refs" in use at /usr/local/share/perl5/Ora2Pg/GEOM.pm line 163.

### ISSUE THREAD

**Issue by jieguolove** [darold/ora2pg#1410]
ora2pg23.1,the lastest version:
the field type:ST_GEOMETRY, cannot copy??!!!!
when use **ora2pg -p -c sde.conf -t COPY -a 'TABLE[BACK_SITE_LOCATION]' -o BACK_SITE_LOCATION.sql -j 1**
the errors just look like :
[========================>] 1/1 tables (100.0%) end of scanning.                     
Can't use string ("POINT  ( 116.52600000 39.8032500") as an ARRAY ref while "strict refs" in use at /usr/local/share/perl5/Ora2Pg/GEOM.pm line 163.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(HOST=192.168.1.2)(PROTOCOL=tcp)(PORT=1521))(CONNECT_DATA=(SID=oradb))) at /usr/local/share/perl5/Ora2Pg/GEOM.pm line 163.
[========================>] 1/1 tables (100.0%) end of scanning.         
Can't use string ("POLYGON  (( 116.48583612 40.6728") as an ARRAY ref while "strict refs" in use at /usr/local/share/perl5/Ora2Pg/GEOM.pm line 163.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(HOST=192.168.1.2)(PROTOCOL=tcp)(PORT=1521))(CONNECT_DATA=(SID=oradb))) at /usr/local/share/perl5/Ora2Pg/GEOM.pm line 163.

descible BACK_SITE_LOCATION table:
create table BACK_SITE_LOCATION
(
  objectid                   INTEGER not null,
  fldtag                     NVARCHAR2(64),
  name                       NVARCHAR2(254),
  code                       NVARCHAR2(254),
  equipment_code             NVARCHAR2(254),
  location                   NVARCHAR2(254),
  longitude                  NUMBER(17,8),
  latitude                   NUMBER(17,8),
  longitude_baidu            NUMBER(17,8),
  latitude_baidu             NUMBER(17,8),
  station_type               NVARCHAR2(64),
  source_assets              NVARCHAR2(64),
  construction_state         NVARCHAR2(1024),
  construction_complete_time DATE,
  project_code               NVARCHAR2(254),
  maintenance_type           NVARCHAR2(254),
  maintenance_man            NVARCHAR2(254),
  area                       NVARCHAR2(254),
  district                   NVARCHAR2(254),
  polling_time               DATE,
  create_state               NVARCHAR2(254),
  fldid                      NVARCHAR2(32),
  project_state              NVARCHAR2(64),
  check_state                NVARCHAR2(64),
  tag                        NVARCHAR2(1),
  backremark                 NVARCHAR2(64),
  shape                      ST_GEOMETRY
)

how to fix it? thanks!

**Comment by gilles-migops** [comment]
Please try latest development, commit d5195d6 is an attempt to fix this issue.

**Comment by jieguolove** [comment]
> Please try latest development, commit [d5195d6](https://github.com/darold/ora2pg/commit/d5195d6ab659eaee964b9d66f8744f4f7df07bea) is an attempt to fix this issue.

thanks,Nice job!
