### ISSUE TITLE
Incorrect Synonyms count in Ora2pg Assessment Report

### ISSUE THREAD

**Issue by dilansalinda** [darold/ora2pg#1411]
Hi, Darold.

When I use **Ora2pg v21.1** to export synonyms for one schema, the schema has **63** synonyms, but reports found **6165** synonyms in other schemas (related to sys users schemas and other schemas) in that instance.

**Comment by darold** [comment]
I guess that this is because the owner of these synonym is PUBLIC. Commit f381241 might fix this issue.
