### ISSUE TITLE
ora2pg -t TEST --count_rows

### ISSUE THREAD

**Issue by nkhemiri** [darold/ora2pg#1412]
Hi,

I just ran the following command to compare rows number between oracle and postgres :
ora2pg -c config/ora2pg.conf -t TEST --count_rows

And i have this result, it seems there is no columns , no indexes , no trigger in postgres tables, 

[TEST COLUMNS COUNT]
ORACLEDB:ABONNEMENT:18
POSTGRES:.abonnement:0
ORACLEDB:ABONNE_ADEP:11
POSTGRES:.abonne_adep:0
ORACLEDB:ACCORD_TARIFAIRE_BENEFICIAIRE:13
POSTGRES:.accord_tarifaire_beneficiaire:0
ORACLEDB:ACCORD_TARIFAIRE_SIGNATAIRE:21
POSTGRES:.accord_tarifaire_signataire:0
ORACLEDB:ACTION:41
POSTGRES:.action:0
ORACLEDB:ACTIVITE:8
POSTGRES:.activite:0

[TEST INDEXES COUNT]
ORACLEDB:ABONNEMENT:5
POSTGRES:.abonnement:0

[TEST UNIQUE CONSTRAINTS COUNT]
ORACLEDB:ABONNEMENT:1

Ora2pg --version 
23.1

thanks in advance for your help.

**Comment by gilles-migops** [comment]
this is probably because PG_SCHEMA is not set to the right schema.

**Comment by nkhemiri** [comment]
Thanks it resolvs my problem, however in V22.1  it function  without PG_SCHEMA., It seem like ora2pg take schema from the search_path
Best regards,
Nabila
