### ISSUE TITLE
BLOB_LIMIT parameter is ignored

### ISSUE THREAD

**Issue by pavel-moskotin-db** [darold/ora2pg#1413]
Versions:
ora2pg = 23.1
Oracle = 12.1.0.2.0
postgres = 13

I am testing ora2pg performance for different values of BLOB_LIMIT and LOB_CHUNK_SIZE.

I am seeing BLOB_LIMIT parameter is being ignored and only DATA_LIMIT is taken into account when processing tables with LOB.

Example config:
DATA_LIMIT	10000                       - works on tables with no LOBs
BLOB_LIMIT	64                             - does not work
EMPTY_LOB_NULL		1               - now this works, means ora2pg understands that table has LOB

</body>
</html>

<html>
<body>

[2022-04-28 14:31:55] Truncating table NOTIFICATION...
--
  | [2022-04-28 14:31:55] Looking how to retrieve data from NOTIFICATION...
  | [2022-04-28 14:31:55] DEGUG: Query sent to Oracle: SELECT "NOTIFICATION_ID","EVENT_ID","EVENT_TYPE","DIRECTION",CASE WHEN dbms_lob.getlength("CONTENT") = 0 THEN NULL ELSE "CONTENT" END,"CREATED_TIMESTAMP","NAMESPACE_URI","DATA_SERVICE_URI","SNAPSHOT_CONTEXT" FROM "..."."NOTIFICATION" a
  | [2022-04-28 14:31:55] Fetching all data from NOTIFICATION tuples...
  | [2022-04-28 14:34:23] Dumping data from table NOTIFICATION into PostgreSQL table NOTIFICATION...
  | [2022-04-28 14:34:23] Setting client_encoding to UTF8...
  | [2022-04-28 14:34:23] Disabling synchronous commit when writing to PostgreSQL...
  | [2022-04-28 14:34:23] DEBUG: Formatting bulk of 10000 data (real: 10001 rows) for PostgreSQL.
  | [2022-04-28 14:34:27] DEBUG: Creating output for 10000 tuples
  | [2022-04-28 14:34:27] DEBUG: Sending COPY bulk output directly to PostgreSQL backend
  | [2022-04-28 14:34:29] Extracted records from table NOTIFICATION: total_records = 10001 (avg: 64 recs/sec)

....

  | [2022-04-28 14:37:13] Extracted records from table NOTIFICATION: total_records = 20002 (avg: 62 recs/sec)

</body>
</html>

Table LOB is defined as below:

CREATE TABLE "NOTIFICATION" 
   (	"NOTIFICATION_ID" NUMBER NOT NULL ENABLE, 
	"EVENT_ID" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"EVENT_TYPE" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"DIRECTION" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"CONTENT" CLOB NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE, 
	"NAMESPACE_URI" VARCHAR2(500 CHAR) NOT NULL ENABLE, 
	"DATA_SERVICE_URI" VARCHAR2(300 CHAR), 
	"SNAPSHOT_CONTEXT" TIMESTAMP (6), 
	 CONSTRAINT "PK_NOT_ID" PRIMARY KEY ("NOTIFICATION_ID")

**Comment by darold** [comment]
`BLOB_LIMIT` only concern BLOB data export, CLOB are exported as text. It doesn't concern CLOB because they can be exported directly using DATA_LIMIT. BLOB are usually bigger data that need processing by smaller chunks, by default this is DATA_LIMIT / 10 until the value returned is < 1000 or the value set in BLOB_LIMIT i f the directive is set.
