### ISSUE TITLE
Repetition of 'CALL' keyword in conversion of call to procecure within package

### ISSUE THREAD

**Issue by duursma** [darold/ora2pg#1417]
The conversion of of procedure in a package:
PROCEDURE when_others (p_text VARCHAR2) IS
BEGIN
  g_error_opgetreden := 1;
  write_log(p_text);
END;

where 'write_log' is a procedure in the same package, results in: 
-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=sol0847.gdnnet.lan;sid=DINO03TP;port=1532

SET client_encoding TO 'UTF8';
SET search_path = dino_dba,public;

CREATE OR REPLACE PROCEDURE bgm_upload.when_others (p_text text) AS $body$
BEGIN
  PERFORM set_config('bgm_upload.g_error_opgetreden', 1, false);
  CALL CALL CALL CALL CALL CALL bgm_upload.write_log(p_text);
END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE bgm_upload.when_others (p_text text) FROM PUBLIC;

**Comment by gilles-migops** [comment]
Please try latest development code this might have been fixed.

**Comment by duursma** [comment]
My conversion takes several days so is not finished yet, but in the schema/package section at least this seems indeed fixed.
