### ISSUE TITLE
Cannot add constant to an interval

### ISSUE THREAD

**Issue by duursma** [darold/ora2pg#1421]
The condition:
WHERE ADD_MONTHS (t1.start_date, 1) + 56 < SYSDATE

Gets transformed into:
WHERE t1.start_date + '1 month'::interval + 56 < statement_timestamp()

This does not compute.  The number added to a date should probably be converted to 'days 56'::interval

**Comment by darold** [comment]
Commit 2e2e33f fix this case as well as for LAST_DAY and TRUNC function. This is not applied in the following case:
```
last_prev_year_day = trunc(sysdate) - 1/24/60/60
```
the operation must concern a single digit, not an other operation.
