### ISSUE TITLE
do not showing me all the tables in schema

### ISSUE THREAD

**Issue by Argo64** [darold/ora2pg#1422]
Hello!

I am trying to migrate Tables from oracle to postgrsql. in the configuration file i use oracle user and password and i specify the schema i want to export tables from. like this
```
perl -v
This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-gnu-thread-multi

ora2pg -v
Ora2Pg v23.1

ora2pg -t SHOW_SCHEMA -c ./config/ora2pg.conf
SCHEMA XTBD_OMG
SCHEMA XTBD_UNITED

ORACLE_USER system
ORACLE_PWD ********
```
1 issue)
```
SCHEMA XTBD_OMG
```
when i list the tables in oracle using the SHOW_TABLE command ora2pg -t SHOW_TABLE -c ./config/ora2pg.conf it is not showing me all the tables in that schema
```
Total number of rows: 0

Global Temporary Tables:

Top 10 of tables sorted by number of rows:
Top 10 of largest tables:
[1] TABLE CURRENT_GDIS_VALUE: 600 MB ( rows)
[2] TABLE LIQUID_PROD: 512 MB ( rows)
[3] TABLE TELE_DATA_LP: 320 MB ( rows)
[4] TABLE WELL_EQUIP_FLEXDS_VALUE: 191 MB ( rows)
[5] TABLE SCAN_DOC_FILES: 144 MB ( rows)
[6] TABLE OFM_DATA: 104 MB ( rows)
[7] TABLE SCAN_DOC: 88 MB ( rows)
[8] TABLE TELE_DATA_BSW: 88 MB ( rows)
[9] TABLE BSW: 88 MB ( rows)
[10] TABLE WELL_STATUS: 72 MB ( rows)
```
2 Issue)
```
SCHEMA SCHEMA XTBD_UNITED
```
Errors:
```
Running: ora2pg -p -t TABLE -o table.sql -b ./schema/tables -c ./config/ora2pg.conf
FATAL: _column_info() ORA-00942: table or view does not exist (DBD ERROR: error possibly near <*> indicator at char 39 in 'SELECT DISTINCT c.SHAPE.SDO_GTYPE FROM <*>WELL_SPATIAL c WHERE ROWNUM < 50000')
DBI::db=HASH(0x558d1c432d70)->disconnect invalidates 1 active statement handle (either destroy statement handles or call finish on them before disconnecting) at /usr/local/share/perl/5.30.0/Ora2Pg.pm line 13830.
```
Any help please?

**Comment by darold** [comment]
Can you verify the table case sensitivity for WELL_SPATIAL please? Maybe Ora2Pg do not preserve the case when querying the Oracle table.

**Comment by Argo64** [comment]
here is the table definition:
 
CREATE TABLE "XTBD_UNITED"."WELL_SPATIAL" 
   (	"ID" NUMBER(19,0), 
	"UWI" NVARCHAR2(22), 
	"SHAPE" "MDSYS"."SDO_GEOMETRY" 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE INDEX "XTBD_UNITED"."WELL_SPATIAL_IDX" ON "XTBD_UNITED"."WELL_SPATIAL" ("SHAPE") 
   INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" ;

**Comment by Argo64** [comment]
Did you not see Issue the first question?

**Comment by darold** [comment]
The only reason I see is that the user used doesn't have the privilege to consult objects in the schema otherwise this is the only time I have heard of such problem and  I don't see any other cause.

**Comment by darold** [comment]
Finally I was able to reproduce the error on GEOM columns. Commit 3f7bf5b fixes this issue.
