### ISSUE TITLE
VIEW_AS_TABLE is not working

### ISSUE THREAD

**Issue by gautham-rao** [darold/ora2pg#1435]
I'm using Version 23.1

On running `ora2pg -c /etc/ora2pg/ora2pg.conf -t TABLE --view_as_table emp_details_view -o view.sql`

Or when `VIEW_AS_TABLE` is set in ora2pg.conf file. the command run's normally ignoring the `VIEW_AS_TABLE` condition.

**Comment by darold** [comment]
I'm not able to reproduce the issue. Do you have some settings at ALLOW or EXCLUDE configuration directives?
