### ISSUE TITLE
Calls to functions with a $ sign don't seem to be recognized

### ISSUE THREAD

**Issue by duursma** [darold/ora2pg#1437]
The code:
  IF ((v_format = 'las1.2') OR (v_format = 'las2.0')) THEN
    read_las(p_file_dbk, p_filename, p_file_size, p_user_nm, v_format);
  ELSE
    unknown_format(p_filename);      -- Onbekend fileformaat
    g_error_opgetreden := 1;
  END IF;
  IF (g_error_opgetreden = 1) THEN
    
    IF (g_bgm_imp_id IS NOT NULL) THEN
      Cg$bgm_Borehole_Msm_Imp.api_del(g_bgm_imp_id);
    END IF;

Get translated to:
  IF ((v_format = 'las1.2') OR (v_format = 'las2.0')) THEN
    CALL bgm_file_import.read_las(p_file_dbk, p_filename, p_file_size, p_user_nm, v_format);
  ELSE
    CALL bgm_file_import.unknown_format(p_filename);      -- Onbekend fileformaat
    PERFORM set_config('bgm_file_import.g_error_opgetreden', 1, false);
  END IF;
  IF (current_setting('bgm_file_import.g_error_opgetreden')::integer = 1) THEN
   
    IF (current_setting('bgm_file_import.g_bgm_imp_id')::numeric(38) IS NOT NULL) THEN
      Cg$bgm_Borehole_Msm_Imp.api_del(current_setting('bgm_file_import.g_bgm_imp_id')::numeric(38));
    END IF;

So the ' read_las' gets translated with a 'CALL' where 'CALL' or 'PERFORM' is missing for 'Cg$bgm_Borehole_Msm_Imp.api_del'

**Comment by darold** [comment]
Commit e92708 fixes this issue.
