### ISSUE TITLE
Indice names ignored

### ISSUE THREAD

**Issue by raqua** [darold/ora2pg#144]
Hi, 

I am attempting a migration and it seems like ora2pg is ignoring index names. 
Please see the attached file.
[missing_idx_name.zip](https://github.com/darold/ora2pg/files/61422/missing_idx_name.zip)

This happens with all my index names, is is not isolated issue.

**Comment by darold** [comment]
HI,

Thanks for the report, last commit 0b4b083 fixes this issue.

Regards

**Comment by raqua** [comment]
That solved the issue, thanks.
