### ISSUE TITLE
Data loading using ora2pg is very slow for LOB tables.

### ISSUE THREAD

**Issue by tilatali** [darold/ora2pg#1443]
Hi @darold  and Team , 

Hope you are doing good, Could you please help me in getting the speed up of LOB table data migration from oracle to postgres. 
I've used DATA_LIMIT =5000 and   LONGREADLEN=102400000,
I have 18G size of table having 1 crore 70 Lakhs of rows. It's taking very long time to load the data. it's been running for more than 3 hours and still 20 lakhs rows are not migrated yet. 

Please let me know if you need any other info on it.

Thanks in well advance for your assistance, 

Thanks,
Manoj

**Comment by darold** [comment]
You must use multi-process option `-J` for  a huge table with BLOB and if possible set FDW_SERVER to use oracle_fdw export.
