### ISSUE TITLE
 Getting this error with MySQL `WARNING: an error occurs during data export. Please check what's happen.`

### ISSUE THREAD

**Issue by sanyamsinghal** [darold/ora2pg#1447]
I am getting this error `WARNING: an error occurs during data export. Please check what's happen.` with MySQL only during data export.
This is not consistently reproducible, it occurs occasionally like 2 out of 3 times. Unable to understand/identify why this is coming.

Tried with `DATA_LIMIT` to be as low as `100`. Don't think it is a OOM issue.

Any kind of help will be highly appreciated.

**Comment by darold** [comment]
You should run Ora2Pg in debug mode and look at the output. To be sure that this is not an OOM you should execute `dmesg` just after the error occurs.

**Comment by websteruriel** [comment]
how do you run in debug mode

**Comment by darold** [comment]
```
-d | --debug      : Enable verbose output.
```
