### ISSUE TITLE
Geometry conversion fails due to not passed parameter

### ISSUE THREAD

**Issue by duursma** [darold/ora2pg#1448]
In the _column_attributes method in Ora2Pg.pm the actual processing is passed on the Oracle/MySQL.  At least in the Oracle variant the method tries to verify whether the column is a geometry type based on table and column name.  But the Ora2Pg version of the method doesn't pass the table name ('$table') to the underlying method.  So this always fails and no srid attribute wil be fetched.  And therefor the srid -> epsg mapping also fails.

**Comment by darold** [comment]
This have been fixed by commit 87e6657 in April.
