### ISSUE TITLE
INTERNAL conversion uses the srid from the object instead of the meta-data

### ISSUE THREAD

**Issue by duursma** [darold/ora2pg#1449]
On converting geometries from srid to epsg is seems that the correct epsg is found, but when using INTERNAL to convert, the conversion takes the srid from the geometry object instead.

**Comment by darold** [comment]
I am not a specialist of geometry data type so if you can provide an example with the expected PostgreSQL conversion it will be helpful.

**Comment by duursma** [comment]
And all I know is from reading your code :-(.  

As far as I can tell there is no need for a conversion as what actually happens is only a 'renaming' of of the srid from Oracle to EPSG.  In the Ora2Pg::format_data_row an effort is made to find the Oracle srid using parse_sdo_geometry.  The SRID comming from that should be converted to EPSG, but only Oracle know how to do that.  Fortunately the converted value has been retrieved earlier in the process and is stored in: 
$self->{colinfo}->{$table}{"GEOMETRY"}{spatial_srid}
(where 'GEOMETRY' is the hard-coded name of the column as I couldn't find how to get that from $idx quickly)
So if you change the line:
$row->[$idx] = 'SRID=' . $geom_obj->{geometry}{srid} . ';' . $row->[$idx];
using the EPSG value retrieved earlier,  it should just work (it worked for me in one use-case, verified with QGIS)
And it appears the parse_sdo_geometry is no longer needed.

**Comment by darold** [comment]
Commit ec400ad might fix this issue, can you confirm please?
