### ISSUE TITLE
SSL error when PARALLEL_TABLES > 1

### ISSUE THREAD

**Issue by pbe-axelor** [darold/ora2pg#145]
Hi,

I'm using ora2pg v16.1 (which is a wonderful project!), copying from oracle directly to postgresql. Everything works fine but if I try to improve migration times with PARALLEL_TABLES = 2, I get this following error : 

```
Creating new connection to Oracle database to export table AA...
Truncating table AA...
Creating new connection to Oracle database to export table BB...
Truncating table BB...
DBD::Pg::db do failed: SSL error: decryption failed or bad record mac at
/usr/local/share/perl/5.18.2/Ora2Pg.pm line 2744.
Looking how to retrieve data from BB...
FATAL: SSL error: decryption failed or bad record mac
DEBUG: cloning Oracle database connection.
Aborting export...
```
The process seems frozen.

I use:
 - Oracle Database 12c Standard Edition Release 12.1.0.2.0 - 64bit Production
 - PostgresSQL 9.3.10
 - ora2pg-16.1
 - Perl v5.18.2

Thanks for helping

**Comment by pbe-axelor** [comment]
I changed ORACLE_DSN from `dbi:Oracle:` to `dbi:Oracle:host=localhost;sid=<SIDNAME>` or `dbi:Oracle:<SIDNAME>`.
The process is no more frozen but fails for each table with this error : 
```
Truncating table AA...
DBD::Pg::db do failed: SSL SYSCALL error: EOF detected at 
/usr/local/share/perl/5.18.2/Ora2Pg.pm line 2744.
FATAL: SSL SYSCALL error: EOF detected
DBD::Oracle::db disconnect failed: ORA-03135: connection lost contact
Process ID: 0
Session ID: 263 Serial number: 22715 (DBD ERROR: OCISessionEnd) at
/usr/local/share/perl/5.18.2/Ora2Pg.pm line 9596.
Aborting export...
```

**Comment by darold** [comment]
Hi,

To force use of SSL with your PostgreSQL connection you may add sslmode=required to your PG_DSN entry.

    PG_DSN        dbi:Pg:dbname=test_db;host=localhost;port=5432;sslmode=required

or set PGSSLMODE environment variable may works too.

This also can be a timeout in SSL connection. You may want to change ssl_renegotiation_limit to 0 to disable the renegotiation.

Regards,

**Comment by darold** [comment]
The above comment will not solves the issue. Please disable use of SSL to import your data if you can, I will investigate the reason of this error which is reproducible.

**Comment by darold** [comment]
[ Remove previous post that was not solving anything and add confusion ]

Please upgrade to latest development code, commit 6a50da1 fixes this issues.

Best regards,

**Comment by pbe-axelor** [comment]
Hi,
Thanks for your quick feedback.
I just tested the fixe. No more SSL error but after 2 tables, the process seems "frozen" but still running. Same issue even if I remove truncate table instruction.

Here is the log : 
````
Creating new connection to Oracle database to export table AAA...
Creating new connection to Oracle database to export table BBB...
Looking how to retrieve data from AAA...
DEBUG: cloning Oracle database connection.
Looking how to retrieve data from BBB...
DEBUG: cloning Oracle database connection.
Fetching all data from AAA tuples...
Dumping data from table AAA into PostgreSQL...
Setting client_encoding to UTF8...
Disabling synchronous commit when writing to PostgreSQL...
DEBUG: Formatting bulk of 10000 data for PostgreSQL.
DEBUG: Creating output for 10000 tuples
DEBUG: Sending COPY bulk output directly to PostgreSQL backend
Extracted records from table AAA: total_records = 0 (avg: 0 recs/sec)
Fetching all data from BBB tuples...
Dumping data from table BBB into PostgreSQL...
Setting client_encoding to UTF8...
Disabling synchronous commit when writing to PostgreSQL...
DEBUG: Formatting bulk of 10000 data for PostgreSQL.
DEBUG: Creating output for 10000 tuples
DEBUG: Sending COPY bulk output directly to PostgreSQL backend
Extracted records from table BBB: total_records = 0 (avg: 0 recs/sec)
````

Regards,

**Comment by darold** [comment]
Removing the -d option (DEBUG) will enable the progress bar so you will see export in progress.

**Comment by pbe-axelor** [comment]
Here is the log without DEBUG mode :
```
[========================>] 860/860 tables (100.0%) end of scanning.                   
[========================>] 0/0 rows (100.0%) Table AAA (0 sec., 0 recs/sec)
[========================>] 0/0 rows (100.0%) Table BBB (0 sec., 0 recs/sec)
[>                        ] 0/78820116 rows (0.0%) on total estimated data (0 recs/sec)
```

**Comment by darold** [comment]
What ora2pg command line are your using and do you have any value defined in ALLOW / EXCLUDE / WHERE configuration directives ?

**Comment by pbe-axelor** [comment]
I use `ora2pg -c ora2pg.conf` command line. ALLOW / EXCLUDE / WHERE configuration directives are commented because not used. What is strange is that the same ora2pg.conf file with PARALLEL_TABLES = 1 works fine.

**Comment by darold** [comment]
Your export says that there is 860 tables to migrate, so I guess you have truncated the log output but what's looks strange is that it doesn't export any row. Here what it should looks:

```
gilles@devel:/home/devel/ora2pg/test_mysql$ ora2pg -t COPY -c config/ora2pg.conf -P 2 -j 2
[========================>] 22/22 tables (100.0%) end of scanning.                
[========================>] 200/200 rows (100.0%) Table actor (1 sec., 200 recs/sec)
[========================>] 603/603 rows (100.0%) Table address (1 sec., 603 recs/sec)          
[========================>] 16/16 rows (100.0%) Table category (1 sec., 16 recs/sec)          
[========================>] 600/600 rows (100.0%) Table city (1 sec., 600 recs/sec)             
[========================>] 109/109 rows (100.0%) Table country (1 sec., 109 recs/sec)        
[========================>] 599/599 rows (100.0%) Table customer (1 sec., 599 recs/sec)         
[========================>] 1000/1000 rows (100.0%) Table film (1 sec., 1000 recs/sec)        
[========================>] 5462/5462 rows (100.0%) Table film_actor (1 sec., 5462 recs/sec)     
[========================>] 1000/1000 rows (100.0%) Table film_category (1 sec., 1000 recs/sec)
[========================>] 1000/1000 rows (100.0%) Table film_text (1 sec., 1000 recs/sec)      
[========================>] 4581/4581 rows (100.0%) Table inventory (1 sec., 4581 recs/sec)   
[========================>] 6/6 rows (100.0%) Table language (1 sec., 6 recs/sec)                
[========================>] 16049/16049 rows (100.0%) Table payment (1 sec., 16049 recs/sec)  
[========================>] 16044/16044 rows (100.0%) Table rental (2 sec., 8022 recs/sec)        
[========================>] 2/2 rows (100.0%) Table staff (1 sec., 2 recs/sec)                
[========================>] 2/2 rows (100.0%) Table store (1 sec., 2 recs/sec)                
[========================>] 10000000/10000000 rows (100.0%) Table transac_part (181 sec., 55248 recs/sec)
[========================>] 10000000/10000000 rows (100.0%) Table transac (183 sec., 54644 recs/sec)  
[=======================> ] 20047273/20052950 rows (100.0%) on total estimated data (0 recs/sec)
[=======================> ] 20047273/20052950 rows (100.0%) on total estimated data (201 sec., avg: 99737 tuples/sec)
```

This is the automatic export/import of the MySQL sakila database but with an oracle database I have the same kind of output, aka everything is working well.

Maybe you have a table with huge BLOB that takes time to import, this is why you think it is freezing.
Can you post here the output of command: ```ps | grep ora2pg```  when you are waiting on last line with "0/78820116 rows (0.0%) on total estimated data (0 recs/sec)"?

**Comment by darold** [comment]
Sorry I mean output of command: ```ps auwx | grep ora2pg```

**Comment by pbe-axelor** [comment]
Yes, there is 860 tables to migrate. Table AAA and BBB have 0 rows.
As reported in #131, I have ora2pg, oracle and postgres on OpenVZ (Proxmox) container.
I installed ora2pg to KVM virtual machine and all work as expected!

Here is some more output : 
```
oracle@dev-ct:~/migration$ ora2pg -t COPY -c ora2pg.conf -P 2
[========================>] 860/860 tables (100.0%) end of scanning.
[========================>] 0/0 rows (100.0%) Table AAA (0 sec., 0 recs/sec)
[========================>] 0/0 rows (100.0%) Table BBB (0 sec., 0 recs/sec)              
[>                        ] 0/78820116 rows (0.0%) on total estimated data (0 recs/sec)
oracle@dev-ct:~/migration$ ps auwx | grep ora2pg
oracle    5663 47.4  2.0 301748 127588 pts/1   S    09:00   0:53 /usr/bin/perl /home/oracle/perl5/bin/ora2pg -t COPY -c ora2pg.conf -P 2
oracle    5702  0.0  1.8 301748 113512 pts/1   S    09:01   0:00 ora2pg logger
oracle    5720  0.0  0.0  10412   960 pts/1    S+   09:02   0:00 grep --color=auto ora2pg
```
Seems to be related to OpenVZ container. Have you ever seen a such issue ?

**Comment by darold** [comment]
How much memory was allocated to the Proxmox container ? Can you look at file /proc/user_beancounters and see if there's any failcnt?

**Comment by pbe-axelor** [comment]
6.00Go has been allocated to the container.
The file /proc/user_beancounters does not report any failcnt.

**Comment by darold** [comment]
Strange, it can also be a limit on number of opened FD. If you can try to use two separate container, one for Oracle and one for Ora2Pg+PostgreSQL and see if that's solves the issue.

**Comment by pbe-axelor** [comment]
Hi,

Yes, run ora2pg on a separate container works fine. I also tried to run it as root and this is working fine too. It seems to be related to a user limitation.

Thx for the fix and your help.
Regards,
