### ISSUE TITLE
With WTK conversion parse_sdo_geometry gets an OCILobLocatorPtr

### ISSUE THREAD

**Issue by duursma** [darold/ora2pg#1450]
On doing a geometry converstion using WTK I get an error because parse_sdo_geometry expects an array reference as an argument but gets an OCILobLocatorPtr.  This is probably caused by the ST_GeomFromText and SDO_UTIL.TO_WKTGEOMETRY functions which seem to return a CLOB instead of a geometry object.

**Comment by darold** [comment]
What is the value of USE_LOB_LOCATOR? DO you have the same error when it is set to 0?

Also please post the error reported.

**Comment by duursma** [comment]
If I set USE_LOB_LOCATOR to 0 and GEOMETRY_EXTRACT_TYPE = WKT,  the conversion succeeds for:
ora2pg -t COPY -c config/... 
So that seems to be a prerequisite.  Thanks for pointing that out.

For: 
ora2pg -t INSERT -c config/...
The command fails with:
Can't use string ("ST_GeomFromText('LINESTRING (194"...) as an ARRAY ref while "strict refs" in use 

Where it refers to the line containing:
 return undef if ($#{$sdo_geom} < 0); 
in GEOM::parse_sdo_geometry

**Comment by darold** [comment]
The two issue might have been fixed by commits 8d33ddf and e2aff42.
