### ISSUE TITLE
Suspicous use of index in getting indexes

### ISSUE THREAD

**Issue by duursma** [darold/ora2pg#1453]
On loading geometries a dummy table was introduced with the name of the schema in the list of tables to be loaded.
This seems to be introduced by Ora2Pg::Oracle::_get_indexes.  
A index information for a bogus name is introduced in the tables hash causing it to be added to the 'keys' and therefor the list of tables.

It seems that this is caused by:
 if ($row->[11] =~ /SPATIAL_INDEX/) {
                        $idx_type{$row->[8]}{$row->[0]}{type} = 'SPATIAL INDEX';
                        if ($row->[12] =~ /layer_gtype=([^\s,]+)/i) {
                                $idx_type{$row->[9]}{$row->[0]}{type_constraint} = uc($1);
                        }
                        if ($row->[12] =~ /sdo_indx_dims=(\d+)/i) {
                                $idx_type{$row->[8]}{$row->[0]}{type_dims} = $1;
                        }
                }
Note that one of the  $idx_type{$rows->[x]} references has the index 9 whereas the others have index 8.

**Comment by darold** [comment]
Good catch, commit 52b86e9 fixes this issue.
