### ISSUE TITLE
Unable to load efiles with a ')' character in their name with COPY

### ISSUE THREAD

**Issue by duursma** [darold/ora2pg#1454]
Ora2Pg gives an error (FATAL: ERROR:  malformed record literal) on loading an efile with a closing ')' in the filename.

This can be resolved by adding an handler for the 'efile' data_format in Ora2Pg::format_data_type in the 'COPY' branch like:

elsif ($data_type eq 'efile')
                {
       
        $col =~ s/\)(?=.)/\\\\)/g;
      
                }

The same seems to happen in de INSERT variant.  The fix for that seems to be a handler in the relevant branch as:

elsif ($data_type eq 'efile')
                {
       
        $col =~ s/\)(?=.)/\\)/g;
      
                }

**Comment by darold** [comment]
Commit 4a067e8 might fix this issue.

**Comment by duursma** [comment]
Unfortunately is is not correctly fixed.  There are two errors.  First the whole condition is changed.  But the test for 'isnum' is before 'isefile', but efile's are not excluded from being a num.  So the condition for efile is never hit.  Secondly the regular expression is changed by removing the lookbehind and also escapeing \(.  This means the last and first brackets are escape invalidating the efile expression.
