### ISSUE TITLE
Improved execution results of Ora2Pg

### ISSUE THREAD

**Issue by yano-rxa** [darold/ora2pg#1460]
Good evening Mr.Darold

We want to improve the following about Ora2pg.
* Problem
The conversion details(number of successes, failures, ignores, etc.) are not output to the execution result of Ora2Pg.
If the conversion fails, manual investigation such as getting a list of failed objects or identifying the cause of the error is required, which reduces the benefits as a tool.
To get a list of objects, it is necessary to check the results between the source Oracle and the destination PostgreSQL.
In addition, in order to identify the error, it is necessary to input the corresponding object into PostgreSQL and investigate the cause of the error and how to deal with it.

* Our Idea
When we run Ora2Pg, a list of conversion results should be displayed.
In addition, if the object fails to convert shows the reason to clarify what to do.

**Comment by darold** [comment]
I'm in favor of this enhancement.
