### ISSUE TITLE
Convert objects containing "$"

### ISSUE THREAD

**Issue by yano-rxa** [darold/ora2pg#1461]
Good evening Mr.Darold.

We want to improve the following about ORa2pg.

* Problem
Ora2Pg doesn't convert objects containing "$".
If there is an object containing "$", additional work such as temporarily rewriting the object name is required.
In Oracle, the use of "$" in the distinguished name of an object is deprecated, but it is not prohibited.
In addition, we faced the case customer use  the objects containing "$".

* Our Idea
We make it possible to convert objects containing "$".
The target is only general users.
Non-general users (e.g. SYS USER) are not considered because they use "V$" tables, etc.

**Comment by darold** [comment]
I think the easiest way to do that is to add a configuration directive, for example: REPLACE_DOLLAR_SIGN, that can be set to an alternate character (I vote for underscore). When this directive is set we can detect the dollar sign in the object name and append the new name with the character replacement into the hash build with REPLACE_TABLES. In a second time for other objects than tables we could add a RENAME_OBJECT directive.

**Comment by darold** [comment]
Commit e927080 fixes this issue, there is no replacement of the dollar sign, the name of the object is quoted.

**Comment by yano-rxa** [comment]
Mr.Darold 

Thank you for the community's correspondence to this issue.  
We confirmed the fix status in V23.2.  

<Confirmation results>  
A table of name containing "$" was created from a general user as follows and tried to convert using V23.2. 
As a result, table of name containing "$" could not be converted.  

* Table creation:  

CREATE TABLE AQ$test  
(  
empno VARCHAR2(10) NOT NULL,  
empname VARCHAR2(50),  
gender_f NUMBER(1,0)  
)   
;  

CREATE TABLE BIN$test   
(  
empno VARCHAR2(10) NOT NULL,  
empname VARCHAR2(50),  
gender_f NUMBER(1,0)  
)   
;  

* Execution Result:  

# ora2pg -c ora2pg.conf -o pg_table.sql -t table  
[========================>] 0/0 tables (100.0%) end of scanning.  
[========================>] 0/0 tables (100.0%) end of table export.  

<Our Requests>  
Oracle does not prohibit the use of "$" as the distinguished name of a table created by ordinary users.  
In addition, we have faced a case where a customer is using an object containing a "$".  

We think it would be better to make it convertible even if a table containing special characters such as "$" is defined by a general user.  

Therefore, after judging system user and general user, we want to modify it to convert user-defined table.  

The execution result should be as follows.  

* Execution Result:  
# ora2pg -c ora2pg.conf -o pg_table.sql -t table  
[========================>] 2/2 tables (100.0%) end of scanning.  
[========================>] 2/2 tables (100.0%) end of table export.
