### ISSUE TITLE
What all changes to expect when USE_ORAFCE is enabled

### ISSUE THREAD

**Issue by sanyamsinghal** [darold/ora2pg#1462]
I tried using ora2pg with Orafce enabled:
```
USE_ORAFCE      1
```

Afaik, ora2pg with Orafce enabled, makes use of all data and time-related functions provided by the extension which is great.

But when I checked for packages like `DBMS_OUTPUT` provided by Orafce, i expected Ora2pg to just `put_line` function directly, but it's converting to that `RAISE NOTICE` not:

forFor example:
1. In Oracle
```
CREATE OR REPLACE PROCEDURE add_numbers
(num1 NUMBER, num2 NUMBER)
AS
  sum_number NUMBER;
BEGIN
  sum_number := num1 + num2;
  DBMS_OUTPUT.PUT_LINE('The sum is ' || sum_number);
END;
```

2. After ora2pg conversion
```
CREATE OR REPLACE PROCEDURE add_numbers (num1 bigint, num2 bigint) AS $body$
DECLARE

  sum_number bigint;

BEGIN
  sum_number := num1 + num2;
  RAISE NOTICE 'The sum is %', sum_number;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
```

Since the Orafce extension provides the DBMS_OUTPUT package as a schema in Postgres, so I expected Ora2pg to use that if orafce is enabled. (so I believe it will be the same behaviors for other DBMS_* packages implementation provided by Orafce)

I am new to Oracle/Orafce, any help in understanding this will be appreciated and helpful.

**Comment by darold** [comment]
Hi,

Right, it should be kept untouched when USE_ORAFCE is enabled, I will fix that.

**Comment by sanyamsinghal** [comment]
Thanks @darold

**Comment by darold** [comment]
Commit a17e165 fixes this issue.
