### ISSUE TITLE
How to improve the performance of copying lots of small tables

### ISSUE THREAD

**Issue by heysky** [darold/ora2pg#1463]
It looks the current parallel related parameters like JOBS, ORACLE_COPIES are helpful for large tables. But I have a task to copy quite many small tables and these parameters dont work for me. Is there a way to start multiple processes to copy different tables in parallel?

Thanks.

**Comment by heysky** [comment]
Thanks, Darold. Does it work with PG_DSN? I'd like to copy data directly to PG. From the testing, I can see only one copy process was running when I used -P 4.

**Comment by darold** [comment]
Yes it works with PG_DSN and better if you have 8 cores on the system you can use `-P 4 -j 2`, Ora2Pg will also parallelize the writes to PG with 2 processes for each table export. This is only valuable if you have more rows in the table than the DATA_LIMIT value.

**Comment by heysky** [comment]
thanks, Darold.
