### ISSUE TITLE
OOM improvements that occur when converting specific objects in Ora2Pg

### ISSUE THREAD

**Issue by yano-rxa** [darold/ora2pg#1464]
Good morning Mr.Darold

We want to improve the following about Ora2pg.

* Problem
Ora2Pg v23.1 crashes in OOM when we convert objects of PROCEDURE, PACKAGE, and FUNCTION.
If OOM occurs, we should identify the object that is causing the error, delete it, and then restart the conversion process.

* Cause
There is a problem with the conversion process when PL/SQL of PROCEDURE, PACKAGE, and FUNCTION includes self-join using outer join.
In the functions of "subfind_associated_clauses", there is a problem with the place where the array containing SQL that correspond to self-joins is determined to be empty or not, so a recursive call can get stuck in an infinite loop.
Consequently, OS resources are exhausted (e.g. "out of memory") and Ora2Pg is forced to quit. 

* Our Idea
A process for determining whether the array containing SQL that correspond to self-joins is empty is added, and modify it so that conversion processing is called recursively if it is not empty.

**Comment by darold** [comment]
Can you post a query which is causing this issue so that I can reproduce the problem?

**Comment by darold** [comment]
@yano-rxa please post an Oracle code that I can use to reproduce. Thanks.

**Comment by darold** [comment]
Or perhaps you can check that fix for function `Ora2Pg::PLSQL::find_associated_clauses()`
```
sub find_associated_clauses
{
        my ($c, $output, $associated_clause, $final_outer_clauses) = @_;

        foreach my $f (@{$associated_clause->{$c}}) {
                for (my $j = 0; $j <= $#{$final_outer_clauses->{$f}{join}}; $j++) {
                        push(@$output, $final_outer_clauses->{$f}{join}[$j]);
                }
                delete $final_outer_clauses->{$f};
                if (scalar keys %{ $final_outer_clauses }) {
                        find_associated_clauses($f, $output, $associated_clause, $final_outer_clauses);
                }
        }
        delete $associated_clause->{$c};
}
```

**Comment by yano-rxa** [comment]
Good Morning Mr.Darold.
  
Sorry for the delay in contacting you.
We will provide a sample query around August 8th.

**Comment by yano-rxa** [comment]
Good Morning Mr.Darold.
Sorry for the delay in contacting you.

The sample data on Oracle and the steps to reproduce are as follows:
1.Create Table 
CREATE TABLE table1
( 
name1 VARCHAR2(10),
key1 VARCHAR2(50)
)
;

CREATE TABLE table2
(
name2 VARCHAR2(10),
key2 VARCHAR2(50) 
)
;

2. Create a function
CREATE OR REPLACE EDITIONABLE FUNCTION "AHK_TEST" (PRM_STR IN 
VARCHAR2) RETURN VARCHAR2 IS

  WK_STR VARCHAR2(30); 
  WK_DATA NUMBER:=0; 

CURSOR CUR_CHK_TEST 
  IS 
SELECT t1.key1, t1.name1, t2.name2 
FROM   table1 t1, table2 t2 
WHERE  t1.key1 = t2.key2(+) 
       and t1.key1 = t1.key1(+); 

ROW_CHK_TEST CUR_CHK_TEST%Rowtype; 

BEGIN 

WK_DATA:=0; 
WK_STR:='1'; 
RETURN WK_STR; 

END AHK_TEST;

3.Use Ora2Pg to convert the FUNCTION object. 
# ora2pg -c ora2pg.conf -o pg_fun.sql -t function

**Comment by darold** [comment]
Thanks a lot! I was able to reproduce using the outer join query. Commit 2c8ca41 fixes this issue.
