### ISSUE TITLE
Regression with REPLACE_AS_BOOLEAN in v23.1

### ISSUE THREAD

**Issue by j-be** [darold/ora2pg#1465]
When upgrading to v23.1 I noticed `REPLACE_AS_BOOLEAN` is now partly broken.

In detail:

* config states `REPLACE_AS_BOOLEAN NUMBER:1`
* In Oracle I have
```sql
create table ATTRIBUTETYPE (
  ID NUMBER(19) not null primary key,
  NAME VARCHAR2(255 char) not null constraint UK_QK02JBBU8F8AAJXRYC8ACAPCP unique,
  HIDDEN NUMBER(1) default 0 not null
)
```
* schema is correctly converted, i.e. `table.sql` says
```sql
CREATE TABLE attributetype (
	id bigint NOT NULL,
	name varchar(255) NOT NULL,
	hidden boolean NOT NULL DEFAULT 'f'
) ;
```
* but `ora2pg -t INSERT -o data.sql -b ./data -w "${ORACLE_PWD}" -c ./config/ora2pg.conf` yields the following in `ATTRIBUTETYPE_data.sql`:
```sql
INSERT INTO attributetype (id,name,hidden) VALUES (88224,E'Catering',0);
```

Up to including v23.0 it has been:
```sql
INSERT INTO attributetype (id,name,hidden)  VALUES (88224,E'Catering','f');
```

Current `master` at the time of writing is still affected.

**Comment by darold** [comment]
Right, commit e568770 fixes this issue.
