### ISSUE TITLE
Exporting types goes wrong when SCHEMA is not defined

### ISSUE THREAD

**Issue by fljdin** [darold/ora2pg#1467]
Hello Gilles,

I've figured out some query building errors when exporting types when SCHEMA is not defined and textcases are involved in typename. 

* Schema name is prefixed twice
* Case are not preserved with `PRESERVE_CASE=1`

My datasets are directly provided with quotes by a customer's Oracle Datapump (18c XE)

**On Oracle database**
```sql
CREATE OR REPLACE TYPE "APP"."TYPE1" -- similar to app.type1
    AS TABLE OF varchar2(100);
/
CREATE OR REPLACE TYPE "APP"."TYPE2" -- similar to app.type2
    AS VARRAY(10) OF NUMBER;
/
```

**Tests cases**

:heavy_check_mark:  When SCHEMA is defined with `PRESERVE_CASE=0`

```sh
ora2pg -c ora2pg.conf -n APP -t TYPE
```
```sql
CREATE SCHEMA IF NOT EXISTS app;
CREATE TYPE type1 AS (type1 varchar(100)[]);
CREATE TYPE type2 AS (TYPE2 bigint[10]);
```

:exclamation:  When SCHEMA is not defined with `PRESERVE_CASE=0`
```sh
ora2pg -c ora2pg.conf -t TYPE
```
```sql
CREATE TYPE app.app.type1 AS (type1 varchar(100)[]);
CREATE TYPE app.app.type2 AS (type2 bigint[10]);
```

:exclamation: When SCHEMA is defined with `PRESERVE_CASE=1`
```sh
ora2pg -c ora2pg.conf -n APP -t TYPE
```
```sql
CREATE SCHEMA IF NOT EXISTS "APP";
CREATE TYPE type1 AS (type1 varchar(100)[]);
CREATE TYPE type2 AS (TYPE2 bigint[10]);
```

:exclamation: When SCHEMA is not defined with `PRESERVE_CASE=1`
```sh
ora2pg -c ora2pg.conf -t TYPE
```
```sql
CREATE TYPE app.type1 AS (type1 varchar(100)[]);
CREATE TYPE app.type2 AS (TYPE2 bigint[10]);
```

**Not easy to patch**

I'm working on a patch (https://github.com/fljdin/ora2pg/commit/fcdbb5fc2527fee6490343671e55457f18885491) but it seems that textcase management need to be enhanced in `_get_types` and `_convert_type` subroutines. I'm not really convinced by my work, would you give me your feedback?

Regards, Florent

**Comment by darold** [comment]
Thanks, commit c2074c4 fixes this issue.

**Comment by darold** [comment]
Ah sorry, I just see that you want to provide a patch. Actually the case must be handled in function _convert_type().

**Comment by fljdin** [comment]
That’s fine! You know textcase management better than I do.
