### ISSUE TITLE
Sub _count_check_constraint does not exclude NOT NULL

### ISSUE THREAD

**Issue by fljdin** [darold/ora2pg#1470]
Hello,

We have noticed in an assessment report a erroneous number of CHECK constraints in table comment's cell.

The subroutine `_count_check_constraint()` has a standard loop that need to parse `$check_constraint->{notnull}` before performing `NOT NULL` exclusion. It seems that condition are never verified and `NOT NULL` constraints are counted.

`$check_constraint->{notnull}` is normally feed by `export_table()`, and not by `_show_infos()` in a SHOW_REPORT run. \
Am i right?

---

Here a simple patch to exclude `NOT NULL`

```diff
sub _count_check_constraint
{
  my ($self, $check_constraint) = @_;

  my  $num_chk_constr = 0;

  # Set the check constraint definition 
  foreach my $k (keys %{$check_constraint->{constraint}})
  {
    my $chkconstraint = $check_constraint->{constraint}->{$k}{condition};
    next if (!$chkconstraint);
+   next if (lc($chkconstraint) =~ lc("IS NOT NULL"));
+   $num_chk_constr++;
-   my $skip_create = 0;
-   if (exists $check_constraint->{notnull})
-   {
-     foreach my $col (@{$check_constraint->{notnull}})
-     {
-       $skip_create = 1, last if (lc($chkconstraint) eq lc("\"$col\" IS NOT NULL"));
-     }
-   }
-   if (!$skip_create)
-   {
-     $num_chk_constr++;
-   }
  }

  return $num_chk_constr;
}
```
Regards, Florent

**Comment by darold** [comment]
Actually I have found that there is more complex case that can give false positive. For example: `CHECK ("column_a" || "column_b" IS NOT NULL)` this is why I have a test that include the column name. Anyway the notnull array is not filled for SHOW_REPORT so the code is useless. For TABLE export it is filled but I have also simplify the test to pattern `$chkconstraint =~ /^[^\s]+\s+IS\s+NOT\s+NULL$/` which is enough. Commit 6a0aae0 fixes this issue.

**Comment by darold** [comment]
I have rewritten this patch, commits 9c88ac9 and a9c1f70 are a far better and reliable way to fix this issue.
