### ISSUE TITLE
Unable to load efiles with a ',' character in their name

### ISSUE THREAD

**Issue by duursma** [darold/ora2pg#1473]
Like with the ')' character, the ',' (comma) also needs to be escaped in efile names.

I was not successful to get a negative lookbehind working (limit to size of buffer) so my solution is to escape all comma's and to put the first one back:
INSERT: 
        $col =~ s/,/\\,/g;
        $col =~ s/\\,/,/;
 
(display shows 1 \\ char.  code has 2)

COPY:
        $col =~ s/,/\\\\,/g;
        $col =~ s/\\\\,/,/;
 
(display showsl 2 \\ char.  codes has 4)

**Comment by darold** [comment]
Commit 166c2cc applies your fix. Thanks.

**Comment by duursma** [comment]
It looks like this is not fixed.  The number of '\' characters should probably be doubled.  Issue with how this comments are formatted in github.
