### ISSUE TITLE
 Not able to configure  DBD::Pg

### ISSUE THREAD

**Issue by rksengee** [darold/ora2pg#1474]
[root@server DBD-Pg-3.10.0]# perl Makefile.PL
Configuring DBD::Pg 3.10.0
PostgreSQL version: 120009 (default port: 5432)
POSTGRES_HOME: /usr/pgsql-12
POSTGRES_INCLUDE: /usr/include
POSTGRES_LIB: /usr/pgsql-12/lib
OS: linux
Multiple copies of Driver.xst found in: /usr/local/lib64/perl5/auto/DBI/ /usr/lib64/perl5/vendor_perl/auto/DBI/ at Makefile.PL line 182.
Multiple copies of Driver.xst found in: /usr/local/lib64/perl5/auto/DBI/ /usr/lib64/perl5/vendor_perl/auto/DBI/ at Makefile.PL line 284.
Using DBI 1.636 (for perl 5.026003 on x86_64-linux-thread-multi) installed in /usr/local/lib64/perl5/auto/DBI/
Generating a Unix-style Makefile
Writing Makefile for DBD::Pg
Writing MYMETA.yml and MYMETA.json
[root@server DBD-Pg-3.10.0]#
[root@server DBD-Pg-3.10.0]#
[root@server DBD-Pg-3.10.0]#
[root@server DBD-Pg-3.10.0]# make
Skip blib/lib/DBD/Pg.pm (unchanged)
Skip blib/lib/Bundle/DBD/Pg.pm (unchanged)
Running Mkbootstrap for Pg ()
chmod 644 "Pg.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Pg.bs blib/arch/auto/DBD/Pg/Pg.bs 644
gcc -c  -I/usr/include -I/usr/local/lib64/perl5/auto/DBI -D_REENTRANT -D_GNU_SOURCE -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fwrapv -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DPGLIBVERSION=120009 -DPGDEFPORT=5432 -g  -DPERL_EXTMALLOC_DEF -Dmalloc=Perl_malloc -Dfree=Perl_mfree -Drealloc=Perl_realloc -Dcalloc=Perl_calloc -DVERSION=\"3.10.0\" -DXS_VERSION=\"3.10.0\" -fPIC "-I/usr/lib64/perl5/CORE"   Pg.c
In file included from Pg.xs:14:
Pg.h:33:10: fatal error: libpq-fe.h: No such file or directory
 #include "libpq-fe.h"
          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:357: Pg.o] Error 1
[root@server DBD-Pg-3.10.0]#

**Comment by rksengee** [comment]
Anyone please help me. Thanks

**Comment by darold** [comment]
PostgreSQL headers are not available you should install package postgresql and/or postgresql-dev
