### ISSUE TITLE
Issue in Multiprocess data export from windows machine

### ISSUE THREAD

**Issue by deepakp555** [darold/ora2pg#1477]
Hi Mr. darold,

Please see the below warning: **WARNING: multiprocess is not supported under that kind of OS.**
So just wanted to confirm is there any alternative to enable multi process data export from windows O/S .

C:\ora2pg\WBB>ora2pg -c config/ora2pg.conf -j 2 -t COPY -o data.sql -b data
WARNING: target PostgreSQL version must be set in PG_VERSION configuration directive. Using default: 11
WARNING: multiprocess is not supported under that kind of OS.
If you need full speed at data export, please use Linux instead.
[========================>] 2/2 tables (100.0%) end of scanning.
[>                        ]  0/22 rows (0.0%) Table FBB_COVERAGEAREA (0 recs/sec)
[>                        ]  0/79 total rows (0.0%) - (2 sec., avg: 0 recs/sec).
[========================>] 57/57 rows (100.0%) Table FBB_COVERAGEAREA_BUILDING (57 recs/sec)
[=================>       ] 57/79 total rows (72.2%) - (4 sec., avg: 14 recs/sec).
[========================>] 79/79 rows (100.0%) on total estimated data (4 sec., avg: 19 recs/sec)
Fixing function calls in output files...

**Comment by darold** [comment]
Yes, the alternative is to use a Linux VM running Ora2Pg. You could also probably find some docker instruction on Google.
