### ISSUE TITLE
search_path not in header if SCHEMA is not set causing tables with efile's to fail

### ISSUE THREAD

**Issue by duursma** [darold/ora2pg#1478]
I think I have a valid reason tot to set the SCHEMA (I want them all).  But the effect of not specifying a single SCHEMA results in the "set search_path" being dropped from the file header.
In this header was the external_file schema.  Causing the creation of tables with efiles in them to fail.

**Comment by darold** [comment]
The solution could be to set `DATA_TYPE       BFILE:external_file.EFILE` in ora2pg.conf but I have not tried.

If it don't work you should set the default search_path for the user or the database.
