### ISSUE TITLE
Can't locate strict.pm:   /usr/local/lib64/perl5/strict.pm: Permission denied at /usr/local/bin/ora2pg line 25.

### ISSUE THREAD

**Issue by rksengee** [darold/ora2pg#1479]
I have installed ora2pg with root user. It is not working with other user "o2padmin". Getting below:-

[o2padmin@xyz ora2pg-23.1]$ ora2pg --version
Can't locate strict.pm:   /usr/local/lib64/perl5/strict.pm: Permission denied at /usr/local/bin/ora2pg line 25.
BEGIN failed--compilation aborted at /usr/local/bin/ora2pg line 25.
[o2padmin@xyz ora2pg-23.1]$

Please suggest if it will work or not.

**Comment by rksengee** [comment]
Does anyone have any idea about it please?

**Comment by darold** [comment]
On what operating system you are working?

**Comment by rksengee** [comment]
It is Linux el8

**Comment by rksengee** [comment]
Is there any issue for PREL5LIB path ?

**Comment by darold** [comment]
I think you perl installation is missing some RPMs or there is some restriction for their use, I don't know exactly what is missing but maybe it will be simpler if you use Ubuntu.

**Comment by haroon-qureshi** [comment]
I'm having the same issue ... Was this issue ever resolved?

**Comment by darold** [comment]
Same answer, you might have a minimalist installation and need additional Perl packages to be installed.

**Comment by haroon-qureshi** [comment]
I figured out the issue.  I ran perl-V to list the directories in @INC.  I then checked the permissions on all the directoires listed and found that the permissions on some directories were set to 750.  I changed them to 755 and everything worked as expected.  I was able to run ora2pg as a non-root user.  It has nothing to do with missing perl packages.
