### ISSUE TITLE
Procedure with out parameter incorrect "returns" clause

### ISSUE THREAD

**Issue by raqua** [darold/ora2pg#148]
ORA:
```
create or replace procedure pn_chk_user_scope_deletion (
 po_check_result   out varchar2
) is
```
ora2pg:
```
CREATE OR REPLACE FUNCTION T205.pn_chk_user_scope_deletion ( po_check_result out text )  RETURNS  AS $body$
```

Should be:
```
CREATE OR REPLACE FUNCTION T205.pn_chk_user_scope_deletion ( po_check_result out text )  RETURNS text AS $body$
```

**Comment by darold** [comment]
Thanks for the report, latest commit b683a4a might solves this issue.

Best regards,

**Comment by raqua** [comment]
Fixed on the one occurrence I have in my use case.

p.s. Your level of support has been amazing, I am really impressed. I have never experienced such a prompt fixes of reported bugs. Thank you very much and have a good 2016!
