### ISSUE TITLE
Allow override of ora2pg_fdw_import schema name

### ISSUE THREAD

**Issue by Caffeine-01** [darold/ora2pg#1483]
If ora2pg is run by two different people with 2 different schemas at the same time then the global `ora2pg_fdw_import` SCHEMA will conflict.

I recommend a new FDW_SCHEMA variable that can override the hard coded `ora2pg_fdw_import` SCHEMA.

**Comment by darold** [comment]
Commit d8466e4 adds configuration variable FDW_IMPORT_SCHEMA to rename the schema. Thanks.

**Comment by Caffeine-01** [comment]
Thank you.  That was quick.
