### ISSUE TITLE
Check constraints not being migrated when exporting from MySQL

### ISSUE THREAD

**Issue by rahulb-yb** [darold/ora2pg#1488]
Hi team,
When we attempt to migrate a schema with check constraints from a MySQL source, we notice that the corresponding check constraints, if any, do not get migrated the same way they do in the case of an Oracle source:

Source schema:
```
create table check_constraint_test(
	ID int PRIMARY KEY, 
	Name varchar(255) NOT NULL, 
	Age int, 
	City varchar(255), 
	CONSTRAINT CHK_CONSTR CHECK (Age>=18 AND City='Bangalore')
);
```

Exported schema:
```
CREATE TABLE check_constraint_test (
	id integer NOT NULL,
	name varchar(255) NOT NULL,
	age integer,
	city varchar(255),
	PRIMARY KEY (id)
) ;
```

Thanks in advance!

**Comment by darold** [comment]
Commit 7e20a9b might fix this issue for MySQL >= 8.0, look like CHECK constraint was not supported before this version.
