### ISSUE TITLE
Improve mapping for certain numeric attributes

### ISSUE THREAD

**Issue by rahulb-yb** [darold/ora2pg#1489]
Hi team,
We exported the following schema from an Oracle source:
```
create table numeric_size(
	num_min number(1,-84),
	num_max number(38,127),
	numeric_min numeric(1,-84),
	numeric_max numeric(38,127),
	float_val FLOAT(5),
	dec_min_Val dec(1,-84),
	dec_max_Val dec(38,127),
	decimal_min_Val decimal(1,-84),
	decimal_max_Val decimal(38,127)
);
```

It gets converted to the following in PG syntax:
```
CREATE TABLE numeric_size (
	num_min real,
	num_max decimal(38,127),
	numeric_min real,
	numeric_max decimal(38,127),
	float_val double precision,
	dec_min_val real,
	dec_max_val decimal(38,127),
	decimal_min_val real,
	decimal_max_val decimal(38,127)
) ;
```

Can the explicit declaration of scale and precision be removed if the scale is higher than the precision? PG does not support any DDL for decimal/numeric attributes where the scale is explicitly higher than the precision. While `num_max decimal(38,127)` is not accepted, PG will accept `num_max decimal`, which also allows the exported data to be accepted into the exported schema as well.
 
Thanks in advance!

**Comment by darold** [comment]
Commit 70498fc adds this behavior.
