### ISSUE TITLE
Unsigned integers do not get exported appropriately from MySQL

### ISSUE THREAD

**Issue by rahulb-yb** [darold/ora2pg#1490]
Hi team,
When we export a schema containing unsigned integers from MySQL we observe the following:
Sample Schema:
```
CREATE TABLE int_types (
	tint_u tinyint unsigned zerofill,
	sint_u smallint unsigned zerofill,
	mint_u mediumint unsigned zerofill,
	int_u int unsigned zerofill,
	bint_u bigint unsigned zerofill
);
```

Exported Schema:
```
CREATE TABLE int_types (
	tint_u smallint,
	sint_u smallint,
	mint_u integer,
	int_u integer,
	bint_u bigint
);
```

While the conversion is appropriate for most data types, it does not suffice for `smallint`, `int` and `bigint` data types. Can we also upscale these data types to use a larger sized integer (or a numeric type in the case of bigint)?

Thanks in advance!

**Comment by darold** [comment]
Commit 7a78d79 fixes this issue.
