### ISSUE TITLE
Can't export view comment

### ISSUE THREAD

**Issue by gh-k-murata** [darold/ora2pg#1493]
hello.
In Ora2Pg v23.1, I set the TYPE directive to VIEW and export the view, but only the view comment is not exported.
Ora2Pg.pm's export_view has COMMENT ON VIEW output code, but I think the view comment cannot be obtained and the code is not executed.

**Comment by darold** [comment]
Commit e330b7b fixes this issue.

**Comment by gh-k-murata** [comment]
Confirmed that view comments are output correctly with the fix for e330b7b.
Thank you for the quick fix.
