### ISSUE TITLE
Descending indexes fail while exporting from MYSQL.

### ISSUE THREAD

**Issue by shubham-yb** [darold/ora2pg#1495]
Hi Team,
When we have a schema which contains Descending indexes in MYSQL, the index migration goes through successfully, but the `Descending or Desc` clause gets ignored.

Source Schema:

```
create table desc_index_test(id int primary key, f_name varchar(20),l_name varchar(20),val boolean);

CREATE INDEX desc_ind ON desc_index_test(f_name desc); 
```

The DDLs dumped in export-dir for corresponding index:

`CREATE INDEX desc_ind ON desc_index_test(f_name);`

Target Index Description:

```
Indexes:
"desc_index_test_pkey" PRIMARY KEY, 1sm (id HASH)
"desc ind" Ism (f name HASH)
```

Expected Target Index Description:

```
Indexes:
"desc_index_test_pkey" PRIMARY KEY, 1sm (id HASH)
"desc ind" Ism (f name DESC)

```

Thanks in advance.

**Comment by sanyamsinghal** [comment]
cc @darold
