### ISSUE TITLE
Sequences occasionally export wrong sequence restart value in MySQL

### ISSUE THREAD

**Issue by rahulb-yb** [darold/ora2pg#1496]
Hi team,
When we have AUTO_INCREMENT columns in MySQL, the DDL exported occasionally gets exported with `RESTART WITH 0`. This causes issues when attempting to import the schema DDL onto PG as 0 is an invalid restart value for sequences.
Some cases in which this can be consistently reproduced are:

- Empty tables (No data)
- Data entry into tables is done by attempting to insert the value '0' in the auto incremented field
- Data entry into tables is done by attempting to insert null value/default value  in the auto incremented field

There have been some instances where this has happened even in use cases not mentioned above, but are not consistently reproducible on our end.

Thanks in advance!

**Comment by darold** [comment]
How this have been called a database?!

The way to get the current value of the sequence for auto increment column is to execute the following SQL command: `AUTO_INCREMENT FROM INFORMATION_SCHEMA.TABLES`;
```
mysql> CREATE TABLE Insects (
    ->    Id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    ->    PRIMARY KEY (id),  
    ->    Name VARCHAR(30) NOT NULL,
    ->    Type VARCHAR(30) NOT NULL,  
    ->    Origin VARCHAR(30) NOT NULL
    -> );  
Query OK, 0 rows affected (0,03 sec)

mysql> 
mysql> INSERT INTO Insects (Name, Type, Origin) VALUES 
    ->     ('Cockroach', 'Crawling', 'Kitchen'),  
    ->     ('Mosquito', 'Flying', 'Driveway'),
    ->     ('Spider' ,'Crawling', 'Court yard'),
    ->     ('Grasshopper', 'Flying', 'Front yard'); 
Query OK, 4 rows affected (0,00 sec)
Records: 4  Duplicates: 0  Warnings: 0

mysql> 
mysql> SELECT * FROM Insects;
+----+-------------+----------+------------+
| Id | Name        | Type     | Origin     |
+----+-------------+----------+------------+
|  1 | Cockroach   | Crawling | Kitchen    |
|  2 | Mosquito    | Flying   | Driveway   |
|  3 | Spider      | Crawling | Court yard |
|  4 | Grasshopper | Flying   | Front yard |
+----+-------------+----------+------------+
4 rows in set (0,00 sec)

mysql> SELECT AUTO_INCREMENT FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Insects';
+----------------+
| AUTO_INCREMENT |
+----------------+
|              5 |
+----------------+
1 row in set (0,00 sec)
```
After reconnecting to the database, now deleting and inserting again:
```
mysql> DELETE FROM Insects;
Query OK, 4 rows affected (0,00 sec)

mysql> SELECT * FROM Insects;
Empty set (0,01 sec)

mysql> INSERT INTO Insects (Name, Type, Origin) VALUES 
    ->     ('Cockroach', 'Crawling', 'Kitchen'),  
    ->     ('Mosquito', 'Flying', 'Driveway'),
    ->     ('Spider' ,'Crawling', 'Court yard'),
    ->     ('Grasshopper', 'Flying', 'Front yard'); 
Query OK, 4 rows affected (0,00 sec)
Records: 4  Duplicates: 0  Warnings: 0

mysql> SELECT * FROM Insects;
+----+-------------+----------+------------+
| Id | Name        | Type     | Origin     |
+----+-------------+----------+------------+
|  5 | Cockroach   | Crawling | Kitchen    |
|  6 | Mosquito    | Flying   | Driveway   |
|  7 | Spider      | Crawling | Court yard |
|  8 | Grasshopper | Flying   | Front yard |
+----+-------------+----------+------------+
4 rows in set (0,00 sec)

mysql> SELECT AUTO_INCREMENT FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Insects';
+----------------+
| AUTO_INCREMENT |
+----------------+
|              5 |
+----------------+
1 row in set (0,00 sec)
```

I was expecting that the query returns 8 but this is definitively not the case and I don't want to know why.

Do not expect from me to give the right value where this piece of "software" is unable to return the right value.

If you know a magic query that could returns the right value I will be please to know it.

**Comment by darold** [comment]
Anyway, commit 9ec5c59 forces MySQL auto increment sequences to start at 1 when value is 0.
