### ISSUE TITLE
What is the best practice to dealing with CLOBs

### ISSUE THREAD

**Issue by sparktronics** [darold/ora2pg#1497]
hi there, 

We are having an issue with tables that have CLOB that slow down the export process. Is there a best practice on how to configure ora2pg to perform better with CLOB data?

Thanks,
Mario

**Comment by sparktronics** [comment]
at the end ora2pg was extremely fast in processing the CLOBs in the production environment. Great tool. We used the DEFINED_PK to process a table with millions of rows and CLOB fields.

**Comment by datvty4a** [comment]
Can you explain more how to use DEFINED_PK to improve speed extracting CLOB cloumns?
