### ISSUE TITLE
Bug with functions without parameters in query on PostgreSQL

### ISSUE THREAD

**Issue by IgorMelnikov71** [darold/ora2pg#1498]
Hi!

When I have function in Oracle without parameters:
```
create or replace function getId return number deterministic is
begin
  return 1;
end;
```
This function using in query (in view) without problem:
```
create table mydual 
 (dummy int);

insert into mydual values(1);

commit;

create or replace view test_bug1 as
select
  *
from 
  mydual
where
  dummy = getId;
```
```
_SQL> select * from test_bug1;

     DUMMY
----------
         1_
```

But after conversion to Postgres via ORA2PG, I have following source code for view:
```
CREATE OR REPLACE VIEW test_bug1 (dummy) AS select
  DUMMY
FROM
  mydual
where
  dummy = getId;

_ERROR:  column "getid" does not exist
LINE 6:   dummy = getId;_
```

**ORA2PG lost parentheses after function name.**
If I put parentheses manually:
```
CREATE OR REPLACE VIEW test_bug1 (dummy) AS select
  DUMMY
FROM
  mydual
where
  dummy = getId();
CREATE VIEW
```
Everything OK.

This problem only occurs with functions without parameters!

Thank you!

Best Regards
Igor Melnikov

**Comment by IgorMelnikov71** [comment]
Hi!

But we can resolve name by Oracle dictionary: for check it is column name or function name.
Why can't this be done?

**Comment by darold** [comment]
Because migration will takes much more time than editing by hand.
