### ISSUE TITLE
 FATAL: _column_info() ORA-00904: "ST_SRID": invalid identifier (DBD ERROR: error possibly near <*> indicator at char 7 in 'SELECT <*>ST_SRID(c.SHAPE) FROM GIS.YIJILU c')

### ISSUE THREAD

**Issue by 339131041** [darold/ora2pg#1499]
ora2pg -b /root/oracle2pg -d -c ora2pg_oracle.conf

FATAL: _column_info() ORA-00904: "ST_SRID": invalid identifier (DBD ERROR: error possibly near <*> indicator at char 7 in 'SELECT <*>ST_SRID(c.SHAPE) FROM GIS.YIJILU c')
DBI::db=HASH(0x1013c80)->disconnect invalidates 2 active statement handles (either destroy statement handles or call finish on them before disconnecting) at /usr/local/share/perl5/Ora2Pg.pm line 14084.
Aborting export...

error in  latest development code

**Comment by darold** [comment]
Sorry for the response delay, what is the datatype of the column? A DESC of the table could help. Thanks.

**Comment by Albert88373** [comment]
I faced a similar problem and the difference with tables that were successfully migrated is that the SHAPE field appears, the data type is ST_GEOMETRY.

**Comment by darold** [comment]
Might be fixed using instruction here https://github.com/darold/ora2pg/issues/1528#issuecomment-1294925035
