### ISSUE TITLE
Replace zero date also with prepared statement (online pg mode)

### ISSUE THREAD

**Issue by SebAlbert** [darold/ora2pg#150]
First of all, many kudos for this great and mature tool.

I've currently discovered a bug: Zero dates (0000-00-00) are only replaced in the sub "format_data_type," which is not called in case of direct online pg mode with prepared INSERT statement, i.e., if $sprep is set.

To reproduce:
* choose a table with zero date (in my case, from MySQL)
* set ora2pg options to TYPE INSERT (or -t INSERT on the command line) and use a direct pg connection, i.e., set PG_DSN (and PG_USER and PG_PWD if needed)

**Comment by darold** [comment]
Hi Sebastian,

Thanks for the report. Last commit 8231fb3 might solves the issue, let us know.

Best regards,

**Comment by SebAlbert** [comment]
Nope, a bit of debugging revealed that $row[$j] is empty so the regexp never matches. Maybe you'd have to dereference like using $row->[$j] instead of $row[$j] in all places of the fix?
