### ISSUE TITLE
Tables are exported by default as foreign tables

### ISSUE THREAD

**Issue by frost242** [darold/ora2pg#1501]
Hello,
I tested the master version of ora2pg with a project I'm working on. The config file was generated with ora2pg 23.0.

With the git version, the tables were all exported like :
`
CREATE FOREIGN  TABLE tabname (
) SERVER  OPTIONS(filename '', format 'csv', delimiter '');
`

With release 23.0, everything is fine and tables are exported as permanent tables.

Did I miss a new config key or is it a bug ?

Kind regards

**Comment by darold** [comment]
Hi Thomas,

Yes got it today, I have fixed this issue in commit 2a1c9d9, sorry for the inconvenience. The workaround was to disable EXTERNAL_TO_FDW but upgrading Ora2Pg will fix the issue.

**Comment by frost242** [comment]
Hi Gilles,
No worries, we switched back to release 2.30. We'll upgrade to latest ASAP.
Thanks a lot.
