### ISSUE TITLE
Error in Exporting data of the tables with table_name including quotes from MySQL 

### ISSUE THREAD

**Issue by priyanshi-yb** [darold/ora2pg#1504]
MySQL  has following tables -
```
MySQL [pk_missing]> show tables;
+----------------------+
| Tables_in_pk_missing |
+----------------------+
| "mock_data_COPY"     |
| MOCK_DATA            |
+----------------------+
```
Where `"mock_data_COPY"` is a copy of `MOCK_DATA` with same data but different name and name includes quotes. I am trying to export the data from MySQL and it is giving this error - 

```
DBD::mysql::st execute failed: Table 'pk_missing.mock_data_COPY' doesn't exist at /usr/local/share/perl5/Ora2Pg.pm line 14247.
DBD::mysql::st execute failed: Table 'pk_missing.mock_data_COPY' doesn't exist at /usr/local/share/perl5/Ora2Pg.pm line 14247.
```
Also, while exporting the schema it exported the quoted table without Quotes and converted the whole table name in lower-case as follows - 
```
CREATE TABLE mock_data_copy (
	id serial,
	first_name varchar(50),
	last_name varchar(50),
	email varchar(50),
	gender varchar(50),
	ip_address varchar(20),
	PRIMARY KEY (id)
) ;
```

CC: @darold

**Comment by darold** [comment]
I'm shared about how to handle this issue, but I think I will said that the problem must be fixed at MySQL side. Having a table with double quote in is name is surely an error that must be fixed, this is not the role of Ora2Pg to perpetuate such mistake.
