### ISSUE TITLE
Add --drop-if-exists command line argument

### ISSUE THREAD

**Issue by yonisade** [darold/ora2pg#1505]
It will be useful to be able to run ora2pg with the same config file for different object types but with the ability to drop only certain types before creation like sequences while keeping current structure like tables (with TRUNCATE_TABLE in conf file).

ora2pg -c config/ora2pg.conf -t TABLE
ora2pg -c config/ora2pg.conf -t SEQUENCE --drop-if-exists

**Comment by darold** [comment]
Commit 5be3e41 adds this feature.
