### ISSUE TITLE
While copying data from oracle to postgreSQL using ora2pg, I am getting DETAIL:  ORA-12514: TNS:listener does not currently know of service requested in connect descriptor at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 9309. error

### ISSUE THREAD

**Issue by chetan2211** [darold/ora2pg#1506]
D:\ora2pg-23.1>ora2pg -t copy -c ora2pg_students_conf.dist -l students_table_copy_19_09_22.log
[========================>] 1/1 tables (100.0%) end of scanning.
[========================>] 1/1 tables (100.0%) end of table export.
DBD::Pg::db do failed: ERROR:  connection for foreign table "students_details" cannot be established
DETAIL:  ORA-12514: TNS:listener does not currently know of service requested in connect descriptor at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 9309.
[========================>] 10/10 rows (100.0%) on total estimated data (1 sec., avg: 10 recs/sec)

Hello @darold ,
I'm getting the above error while copying data from oracle to the PostgreSQL server. Both servers has windows OS. Please let me know if anybody knows the solution.
Thank you in advance.

**Comment by darold** [comment]
Your DSN value in ORACLE_DSN is not correct.
