### ISSUE TITLE
Functions only get exported when written in a particular format in MYSQL

### ISSUE THREAD

**Issue by shubham-yb** [darold/ora2pg#1507]
Hi Team,
This was observed while exporting from MYSQL. The functions were getting exported only when defined in a particular format.

Let's take the example of a function to add two numbers.

A function defined like:

```
CREATE FUNCTION add_two(n1 int,n2 int)
  RETURNS int
    DETERMINISTIC
  RETURN n1+n2;
```

Won't export. i.e. It doesn't get dumped in the export dir, and therefore not imported as well.

But a function for the same task defined as:

```
delimiter /
CREATE FUNCTION add_two(n1 int,n2 int)
  RETURNS int
   DETERMINISTIC
    BEGIN
     DECLARE sum_two int;
       set sum_two=n1+n2;
     RETURN sum_two;
    END/
```
 
Gets exported.

**Comment by shubham-yb** [comment]
cc @darold @sanyamsinghal

**Comment by darold** [comment]
Commit e13ab16 might solve this issue.

**Comment by shubham-yb** [comment]
The export is working now!
Thanks @darold for the quick fix :)
