### ISSUE TITLE
ora2pg 23.1 does not export GRANT

### ISSUE THREAD

**Issue by did16** [darold/ora2pg#1508]
Oracle to PostgreSQL migration does not include **rights and privileges** (GRANT).
/depot/BRTCICERO/schema/grants directory is **empty**. 
I had to apply the rights manually. 
is this a bug or misuse ?
Thanks in advance
Best Regards

**Comment by darold** [comment]
This is probably because USER_GRANTS is enabled, otherwise on Oracle:
```
SQL> GRANT ALL ON employees TO scott;
```
then exporting grants returns the following:
```
$ ora2pg -c config/ora2pg.conf -t GRANT -b /tmp
$ cat /tmp/output.sql
...
SET client_encoding TO 'UTF8';

SET search_path = hr,public;
\set ON_ERROR_STOP ON

CREATE USER HR WITH PASSWORD 'change_my_secret' LOGIN;
CREATE USER SCOTT WITH PASSWORD 'change_my_secret' LOGIN;

-- Set priviledge on TABLE EMPLOYEES
ALTER TABLE hr.employees OWNER TO hr;
GRANT ALL ON  hr.employees TO hr;
REVOKE ALL ON hr.employees FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES ON hr.employees TO scott;
```

If USER_GRANT is disabled then your database is only using default privileges.

**Comment by did16** [comment]
Hi Gilles
I attach my anonymized ora2pg.conf file to show you that USER_GRANTS is not activated. However, the /depot/BRTCICERO/schema/grants folder is empty.

**Comment by did16** [comment]
[ora2pg_anonym.zip](https://github.com/darold/ora2pg/files/9651781/ora2pg_anonym.zip)

**Comment by darold** [comment]
How about if you set privilege on a table for an other user like above `GRANT ALL ON employees TO scott;`? Does Ora2Pg export something? What version of Ora2Pg are you using?
