### ISSUE TITLE
Extremely slow migration speed

### ISSUE THREAD

**Issue by iamjoos** [darold/ora2pg#1511]
Hi,

I'm trying to migrate a ~65Mb database from Oracle 19c to PostgreSQL 12 with ora2pg v23.1.
The process is extremely slow. This is the result of running it with the `--oracle_speed` argument:

```
[========================>] 66473/66473 rows (100.0%) on total estimated data (2385 sec., avg: 27 recs/sec)
```

Here's the parameter file in use:

```
# Source
ORACLE_DSN      dbi:Oracle:host=XXX;service_name=XXX;port=XXX
ORACLE_USER     XXX
ORACLE_PWD      XXX
USER_GRANTS     1
# Target
PG_DSN          dbi:Pg:dbname=XXX;host=XXX;port=XXX
PG_USER         XXX
PG_PWD          XXX
PG_SCHEMA       public
# Misc options
REORDERING_COLUMNS      0
PG_VERSION      12
DROP_FKEY       1
DROP_INDEXES    1
SYNCHRONOUS_COMMIT      1
LOG_ON_ERROR            1
TRANSACTION     SERIALIZABLE
DATA_EXPORT_ORDER       name
```

This might be a similar issue to #846 , but since I'm not sure about it, I decided to open a new one.
I also profiled the run, please see attachment: [ora2pg-profile.tar.gz](https://github.com/darold/ora2pg/files/9663558/ora2pg-profile.tar.gz)
Some of the tables have CLOBs, and most of the tables have `RAW(16)` columns which hold the UUID data and work as primary keys.

I can provide more information if needed. Thank you in advance!

**Comment by darold** [comment]
Most of the time is lost in fetch so I guess that the connection to the remote database is not very performant.

**Comment by iamjoos** [comment]
Hi, @darold. Thank you, that might be the issue. But I was also rather surprised that ora2pg did ~187K fetches to migrate ~66K rows. Did it switch to a single row fetching at some point?

**Comment by darold** [comment]
No, not single row fetch but when Ora2Pg encounter a table with BLOB column it switch to a slower mode by limiting the fetch size (DATA_LIMIT) < 1000 for this table, see BLOB_LIMIT for explanation and control.

**Comment by iamjoos** [comment]
Thank you, @darold. I will continue researching the connection problem then, and close this issue.
