### ISSUE TITLE
How to split data using ora2pg

### ISSUE THREAD

**Issue by skizilbash** [darold/ora2pg#1512]
Do you know if ora2pg has a feature to bring the data in chunks date wise (partitioning) and also if the below can be run in the background using nohup. earlier i was running in screen -x mode but it still timed out after 6 hours.

ora2pg -t COPY -o data.sql -b ./data -c $HOME/Phycon_o2p/oracle_service_name/config/ora2pg.conf

**Comment by darold** [comment]
Yes ora2pg can be run with nohup, I'm doing  that always when running it remotely. Example of use:
```
nohup ora2pg -c config/ora2pg.conf -t COPY -b data -o data.sql &
```
ora2pg output will appears in  file nohup.

I'm not sure to understand what you mean by "bring the data in chunks date wise (partitioning)". If you have partitioning in Oracle, ora2pg will reproduce the partitioning in PostgreSQL and will export data per partition.

**Comment by skizilbash** [comment]
Thank you!!

**Comment by skizilbash** [comment]
I have 3Tb data and want to know if there is a way to split the export using Ora2pg. Is there an option to do that?

Thanks!

**Comment by darold** [comment]
I guess what you should do is exporting "dead" or archived data first and then export live data when you will start your full migration to reduce the migration window time. In ora2pg.conf there is a configuration directive clause called WHERE that will help you to set a filter on the data you want to migrate in two step.

**Comment by skizilbash** [comment]
Thank you again for quick response. I will try that directive and let you know.

**Comment by darold** [comment]
The first error is probably because you can not create regular file on /var/tmp using -b is the solution.

About message "Skipping dumping data to file ..." normally you can forget it, data will not be exported twice but here I'm surprised that the INVOICES table look to be exported. Use latest development code and add the -d option to the command line to report the output if you still have the same behavior.

**Comment by skizilbash** [comment]
i am getting a different error now.

FATAL: _column_attributes() ORA-00604: error occurred at recursive SQL level 1
ORA-08177: can't serialize access for this transaction (DBD ERROR: error possibly near <*> indicator at char 122 in 'SELECT A.COLUMN_NAME, A.NULLABLE, A.DATA_DEFAULT, A.TABLE_NAME, A.OWNER, A.COLUMN_ID, A.DATA_TYPE
FROM ALL_TAB_COLUMNS A, <*>ALL_OBJECTS O

**Comment by darold** [comment]
Set the following in ora2pg.conf
```
TRANSACTION        readonly
```

**Comment by darold** [comment]
Because your Oracle database is not tuned for that, normally the right solution is to tuned Oracle but for testing it is simpler to use readonly transaction.

**Comment by skizilbash** [comment]
so i want to know what is the best possible way to utilize ora2pg for large database. We have a 3tb oracle database that we need to migrate to postgres. Can you please advise?

Thanks.

**Comment by darold** [comment]
multiprocess + WHERE clause + oracle_fdw is usually a good recipe if there is BLOB, otherwise multiprocess  + WHERE clause can be enough.
