### ISSUE TITLE
ENUM data type is not getting exported properly from MYSQL

### ISSUE THREAD

**Issue by ShivanshGahlot** [darold/ora2pg#1513]
Hey, I was trying to export the schema from my **mysql** instance and the **ENUM** data type is not getting exported properly. This is an issue with ora2pg built from commit hash:  **24a4761fdd2d0e6f167807e3fba0576c5f0af491**

Here is **DDL** of the original table:

```
CREATE TABLE `clothes` (
  `product_id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `fabric` text NOT NULL,
  `size` enum('small','medium','large') NOT NULL,
  PRIMARY KEY (`product_id`)
)
```

Exported table by using **ora2pg** built from commit hash: **24a4761fdd2d0e6f167807e3fba0576c5f0af491**

```
CREATE TABLE clothes (
        product_id bigserial,
        name varchar(255) NOT NULL,
        fabric text NOT NULL,
        size , 6 NOT NULL,
        PRIMARY KEY (product_id)
) ;
```
Exported table by using **ora2pg** built from **23.1** release (This is working fine):

```
CREATE TYPE clothes_size_t AS ENUM ('small','medium','large');

CREATE TABLE clothes (
        product_id serial,
        name varchar(255) NOT NULL,
        fabric text NOT NULL,
        size clothes_size_t NOT NULL,
        PRIMARY KEY (product_id)
) ;
```
cc: @darold

**Comment by darold** [comment]
Right commit f9b2f62 fixes this regression.
