### ISSUE TITLE
Wrong conversion of column alias “exec” to select in ora2pg

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1514]
Good Evening Mr Darold,
I hereby get in touch because in the conversion of a querie inside a package from oracle to postgres, the column alias “exec” was wrongly converted to the select command, as shown in the example below:

Oracle:

CREATE OR REPLACE PACKAGE BODY pck_gmp_ws_preventive_maint IS
	PROCEDURE sp_envia_mail_configuracoes
	(
	preferencia VARCHAR2,
	ppartic_categoria NUMBER,
	pid_estado_n NUMBER,
	ptrigger IN NUMBER DEFAULT 0
	) IS
BEGIN
  SELECT condicao, id_sala, item1, item2, item3, item4, item5, item6, valor, LEAD (item1,1,0) OVER (PARTITION BY id_sala ORDER BY id_sala, item1 NULLS FIRST, item2 NULLS FIRST, item3 NULLS FIRST, item4 NULLS FIRST, item5 NULLS FIRST, item6 NULLS FIRST) _EXEC_ FROM tra_glb_tmp_lim_pend
ORDER BY id_sala, item1 NULLS FIRST, item2 NULLS FIRST, item3 NULLS FIRST, item4 NULLS FIRST, item5 NULLS FIRST, item6 NULLS FIRST;
  EXCEPTION
    WHEN erro_devolvido THEN
      LOGGER.INFO ('sp_envia_mail_configuracoes - Devolvido', '(' || vcoderro || ' - ' || vmsgerro || ') : ');
    WHEN OTHERS THEN
      vcoderro := SQLCODE;
      vmsgerro := SQLERRM;
      LOGGER.ERROR ('sp_envia_mail_configuracoes - Excepção', '(' || vcoderro || ' - ' || vmsgerro || ') : ');
END sp_envia_mail_configuracoes; END pck_gmp_ws_preventive_maint;/

Postgres:

CREATE OR REPLACE PROCEDURE pck_gmp_ws_preventive_maint.sp_envia_mail_configuracoes ( preferencia varchar, ppartic_categoria numeric, pid_estado_n numeric, ptrigger numeric DEFAULT 0) AS $body$
BEGIN
-- Verifica se deve Gerar Pendência
   PERFORM condicao, id_sala, item1, item2, item3, item4, item5, item6, valor
	, LEAD(item1,1,0) OVER (PARTITION BY id_sala ORDER BY id_sala, item1 NULLS FIRST, item2 NULLS FIRST, item3 NULLS FIRST, item4 NULLS FIRST, item5 NULLS FIRST, item6 NULLS FIRST) SELECT
	FROM tra_glb_tmp_lim_pend
	ORDER BY id_sala, item1 NULLS FIRST, item2 NULLS FIRST, item3 NULLS FIRST, item4 NULLS FIRST, item5 NULLS FIRST, item6 NULLS FIRST;
  EXCEPTION
    WHEN erro_devolvido THEN
      LOGGER.INFO('sp_envia_mail_configuracoes - Devolvido', '(' || vcoderro || ' - ' || vmsgerro || ') : ');
    WHEN OTHERS THEN
      vcoderro := SQLSTATE;
      vmsgerro := SQLERRM;
      LOGGER.ERROR('sp_envia_mail_configuracoes - Excepção', '(' || vcoderro || ' - ' || vmsgerro || ') : ');
END;
$body$
LANGUAGE PLPGSQL;

Is it possible to validate?, can you confirm that this is an ora2pg conversion error?

Best regards,

Rui Pereira.

**Comment by darold** [comment]
Commit 5e4a311 might fix this issue.
