### ISSUE TITLE
Option TEST_DATA doesn't work 

### ISSUE THREAD

**Issue by cyberioio** [darold/ora2pg#1517]
Hi !

I use ora2pg v23.0 to migrate an Oracle database (11.2.0.3) to a PostgreSQL database (11) ; it works but when i try to use "TEST_DATA" option, i have the following message : 

[SERVER]$ ora2pg -t TEST_DATA -c ./config/ora2pg.conf
type option must be (TABLE, VIEW, GRANT, SEQUENCE, TRIGGER, PACKAGE, FUNCTION, PROCEDURE, PARTITION, TYPE, INSERT, COPY, TABLESPACE, SHOW_REPORT, SHOW_VERSION, SHOW_SCHEMA, SHOW_TABLE, SHOW_COLUMN, SHOW_ENCODING, FDW, MVIEW, QUERY, KETTLE, DBLINK, SYNONYM, DIRECTORY, LOAD, TEST, TEST_VIEW), unknown TEST_DATA

OS : CentOS Linux release 7.6.1810 (Core)
[SERVER]$ ora2pg -v
Ora2Pg v23.0

Other features of ora2pg work fine.
Could you help me please ?
Thanks in advance.

Lionel

**Comment by darold** [comment]
Please use latest development code for better support, or at least Ora2Pg 23.1.

**Comment by cyberioio** [comment]
Ok, thanks.
I'll try to use latest version of ora2pg next week.
