### ISSUE TITLE
Importing files with "\N" as NULL yields error.

### ISSUE THREAD

**Issue by fantasticle** [darold/ora2pg#1518]
Hi everyone,

So far I really enjoy ora2pg because it has made my life really easy. I was able to export data from my Oracle database and now I'm at the importing step.

My table has this layout:
```sql
CREATE TABLE my_table(
  column1 int8,
  column2 int8,
  column3 int2
)
```

My data looks like this:

```sql
-- myfile.sql
SET client_encoding TO 'UTF8';
SET synchronous_commit TO off;

TRUNCATE TABLE my_table;

COPY my_table(column1,column2,column3) FROM STDIN;
22  -91 \N
22  -92 \N
...
\.
```

When I type: `psql -d mydb -U myuser -W -f  myfile.sql` I get this error: 

`psql:myfile:lineno: error: invalid command \N`

I'm using PostgreSQL v14.5 on Ubuntu 22.04LTS. I could try and replace every "\N" with "NULL" but this does not seem feasible because some files contain millions of rows.
It also doesn't work when I use the "wrapper"-SQL-file: `data.sql` that is created by the `ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg.conf` command that followed `bash export_schema.sh`.

How would I proceed?

**Comment by darold** [comment]
With COPY the right value for NULL is \N, this is correct. Are you using latest development code? If not give it a try.

**Comment by fantasticle** [comment]
Thank you for your quick reply. 

I use ora2pg v23.1. For me this looks like a general issue that something is off with COPY FROM STDIN. Is there an option to export values as .csv and COPY FROM CSV instead?

**Comment by darold** [comment]
No, this is not a general issue, please upgrade to latest development code:
```
wget https://github.com/darold/ora2pg/archive/refs/heads/master.zip
unzip master.zip
cd ora2pg-master/
perl Makefile.PL
make
sudo make install
```
then try export again.

**Comment by fantasticle** [comment]
> No, this is not a general issue, please upgrade to latest development code:
> 
> ```
> wget https://github.com/darold/ora2pg/archive/refs/heads/master.zip
> unzip master.zip
> cd ora2pg-master/
> perl Makefile.PL
> make
> sudo make install
> ```
> 
> then try export again.

After updating, exporting the data and `psql -d mydb -U myuser -W -f data/data.sql` I still get the same results unfortunately :-(

**Comment by fantasticle** [comment]
Ok nevermind. It works if I use the `postgres`-User. *sigh*

Thank you for your answers! I love your program!
