### ISSUE TITLE
NULL_EQUAL_EMPTY generates invalid code

### ISSUE THREAD

**Issue by duursma** [darold/ora2pg#1519]
The null_equal_empty configuration currently generates  invalid code if the argument is a number.

some_dbk is not null 

gets translated to
(some_dbk  and some_dbk::text <> '')

This give the error that a numeric value cannot be used where a boolean is expected.

**Comment by darold** [comment]
Yes, this is expected as Ora2Pg doesn't maintain a map of column's datatype. Generally here is very few such predicate where a number is tested against null value  compared to string datatypes, so there should be just few false positive too.
