### ISSUE TITLE
Foreign keys not exported when schema directive commented

### ISSUE THREAD

**Issue by mkickax** [darold/ora2pg#152]
Version: 16.1
Source DB: Oracle
Type: TABLE

Making a system export using SCHEMA directive gives foreign keys in output file.
Making the same export and commenting SCHEMA directive doesn't ouputs foreign keys.

In both cases, logs give something like "Dumping RI TABLENAME" for each table.

Config file is the default file with the following changes:

ORACLE_DSN mydsn
ORACLE_PWD mypwd
EXPORT_SCHEMA 1
SCHEMA myschema (commented or not)
EXCLUDE ONETABLE
USE_TABLESPACE 1
KEEP_PKEY_NAMES 1

**Comment by darold** [comment]
Thanks for the report. Latest commit 78ea8eb might solve this issue. Please use latest development code and let me know.

Regards,

**Comment by mkickax** [comment]
It works fine with last commit (w/ or w/o SCHEMA directive).

**Comment by darold** [comment]
Please note that commit 47c06a4 fix an other issue with foreign key export, foreign keys on multiple columns was not exported at all. For example:
```
    ALTER TABLE products ADD CONSTRAINT fk_supplier_comp
        FOREIGN KEY (supplier_id,supplier_name) REFERENCES supplier(supplier_id,supplier_name)...
```
