### ISSUE TITLE
subtype Migration Issue

### ISSUE THREAD

**Issue by elangodba** [darold/ora2pg#1520]
Hi Seniors,

We are trying to migrate data from Oracle database where a column in a table is a user defined datatype which intern points to type as table. While trying to run ora2pg we encounter the following error.

![image](https://user-images.githubusercontent.com/100104288/194805942-fb38253d-c332-4612-a021-209ee3dff0d2.png)

Data is not getting loaded after that.

![image](https://user-images.githubusercontent.com/100104288/194806024-17cbfae4-118c-495b-99be-c187605bf4df.png)

Need some Expert advise.

**Comment by darold** [comment]
This should have been fixed in latest development code, closing.
