### ISSUE TITLE
Floating point types migrate unprecise values

### ISSUE THREAD

**Issue by shubham-yb** [darold/ora2pg#1524]
Hi Team,

When we have floating type datatypes in MYSQL, the fractional part of the values is lost and it is rounded off. But this didn't  happen earlier.

If we look at this schema:

```
drop table if exists floating_point_types;

create table if not exists floating_point_types(id int,float_type float, double_type double, real_type REAL);

insert into floating_point_types values (1,0.456,0.12313,0.9);
insert into floating_point_types values (2,123456.456,0.1246533,1.9);
insert into floating_point_types values (3,0,0,0);
insert into floating_point_types values (4,126.156,0.1,1.9999);

select * from floating_point_types;
```

**Using the latest version 23.2.**

The schema exports as:

```
CREATE TABLE floating_point_types (
	id numeric(10),
	float_type numeric(12),
	double_type numeric(22),
	real_type numeric(22)
) ;
```

And the values migrate as:

![](https://user-images.githubusercontent.com/65844208/196109949-eb08a08b-e70a-46db-a353-4c236b8240f0.png)

**Using version 23.1.**

The schema exports as:

```
CREATE TABLE floating_point_types (
	id integer,
	float_type double precision,
	double_type double precision,
	real_type double precision
) ;
```

And the values migrate to pg as:

![](https://user-images.githubusercontent.com/65844208/196110784-32203ddd-aee6-464f-a279-d4b69d332c83.png)

**Comment by shubham-yb** [comment]
cc: @sanyamsinghal

**Comment by sanyamsinghal** [comment]
thanks @shubham-yb
@darold is it some regression in with new `v23.2`release

**Comment by darold** [comment]
Yes this is a regression, please give a try to latest development code, commit 805bc55 might fix this issue.
