### ISSUE TITLE
For MySQL, "datetime" columns with default value don't export properly

### ISSUE THREAD

**Issue by shubham-yb** [darold/ora2pg#1525]
Hi Team,

If we have a schema in MYSQL which has a `default` value defined for a `datetime` column, it does not get exported properly and thus we face syntax errors while importing.

Consider this schema:

`create table m (date_status_changed datetime DEFAULT (curtime()));`

This gets exported as:

```
CREATE TABLE m (
	date_status_changed timestamp without time zone DEFAULT CURRENT_TIMESTAMP::(0)::timestamp without time zone(0)
) ;
```

Which is syntactically incorrect and we get the error.

Thank You for your help!

**Comment by darold** [comment]
Commit 23e01d5 fixes this issue.
