### ISSUE TITLE
"Nested quantifiers" error

### ISSUE THREAD

**Issue by durandm70** [darold/ora2pg#1526]
I have run the ora2pg **23.2** script "export_schema.ps1". I get the following error when at export of the Package phase (ora2pg -t PACKAGE ...) :
`Nested quantifiers in regex; marked by <-- HERE in m/(SELECT\s+(?:.*?)\s+)INTO\s+* <-- HERE /\s+([^;]+);/ at _path_/Oracle.pm line 1727.`
This has been experienced on both Windows 11 & Windows Server.

It seems to occure at the very end of the package retrieval (~900 packages). I was unable to find any log who could tell more. Any help would be very appreciated, thank you.

**Comment by darold** [comment]
Commit b58116c might fix this issue. Apparently there is star in the package name which brakes the regexp.

**Comment by durandm70** [comment]
Hi @darold , 
Thank you, it works !
When analyzing deeper the code, it seems that the cause was not having a star in a package name, but instead, having a star in the definition of the value assigned to an Oracle global variable (such as select _*_ in _globalvariable_ from (...)).
