### ISSUE TITLE
Converting ArcSDE geometry (ST_GEOMETRY) to Postgresql geometry, who has encountered and can help, please unsubscribe.

### ISSUE THREAD

**Issue by Albert88373** [darold/ora2pg#1528]
I am migrating the database from Oracle/ArcSDE (I also tried to connect ArcSDE to Postgresql, but it ended in failure).
Faced with a problem that has already been described below, but remained unanswered: 
(ora2pg -b /root/oracle2pg -d -c ora2pg_oracle.conf
FATAL: _column_info() ORA-00904: "ST_SRID": invalid identifier (DBD ERROR: error possibly near <> indicator at char 7 in 'SELECT <>ST_SRID(c.SHAPE) FROM GIS.YIJILU c')
DBI::db=HASH(0x1013c80)->disconnect invalidates 2 active statement handles (either destroy statement handles or call finish on them before disconnecting) at /usr/local/share/perl5/Ora2Pg.pm line 14084.
Aborting export...)
The launch of ora2pg ended with a similar error. This was due to the fact that the Data_Type of the SHAPE field was ST_GEOMETRY, if the query operator in st_spatial_srid was changed to "SELECT sde.ST_SRID(c.%s) FROM %s c" and st_spatial_dim "SELECT sde.ST_DIMENSION(c.%s) FROM %sc" in Oracle.pm , then it will generate an sql file to create tables. In the geometry field, SHAPE will be with the ST_GEOMETRY type, which is not good for Postgresql and Export data from table will also need to be corrected for ArcSDE geodata.
I think that such a functional has not yet been provided in ora2pg.
If someone has already finalized the conversion using ora2pg or was able to transfer the data in some other way, please help.

**Comment by darold** [comment]
Can you please give a try to latest development code with the correct settings in the ora2pg.conf for the following directives:
```
    Add four new configuration directive to be able to change or prefix
    the functions used to extract information from ST_Geometry object and
    values.
    
    - ST_SRID_FUNCTION
      Oracle function to use to extract the srid from ST_Geometry meta
      information. Default: ST_SRID, for example it should be set to
      sde.st_srid for ArcSDE.
    - ST_DIMENSION_FUNCTION
      Oracle function to use to extract the dimension from ST_Geometry
      meta information. Default: ST_DIMENSION, for example it should be
      set to sde.st_dimention for ArcSDE.
    - ST_ASBINARY_FUNCTION
      Oracle function to used to convert an ST_Geometry value into WKB
      format. Default: ST_ASBINARY, for example it should be set to
      sde.st_asbinary for ArcSDE.
    - ST_ASTEXT_FUNCTION
      Oracle function to used to convert an ST_Geometry value into WKT
      format. Default: ST_ASTEXT, for example it should be set to
      sde.st_astext for ArcSDE.
```
so in your case if I have well understood the problem you should have the following in your ora2pg.conf:
```
ST_SRID_FUNCTION    sde.st_srid
ST_DIMENSION_FUNCTION    sde.st_dimention
ST_ASBINARY_FUNCTION    sde.st_asbinary
ST_ASTEXT_FUNCTION    sde.st_astext
```

The ST_Geometry data type at table creation should also have been modified to PostGis Geometry data type automatically, please check this too.

**Comment by darold** [comment]
Also let me know the next error during data export if there is one and a possible solution.

**Comment by Albert88373** [comment]
> Also let me know the next error during data export if there is one and a possible solution.
Tried the latest development code.

You made a typo in the description of ST_DIMENSION_FUNCTION (ST_DIMENSION_FUNCTION sde.st_dimention -> dimension).

In Oracle.pm you need to change the line to get rid of the error
my $st_spatial_gtype =  'SELECT DISTINCT ST_GeometryType(c.%s) FROM %s c WHERE ROWNUM < ' . $max_lines;
 on 
my $st_spatial_gtype =  'SELECT DISTINCT sde.ST_GeometryType(c.%s) FROM %s c WHERE ROWNUM < ' . $max_lines;
After that, on the output to output.sql, we get a geometry of the type 
1...ST_Geometry('OCILobLocatorPtr=SCALAR(0x495c558)', ) 
I did not understand how to use this geometry as a PostGIS geometry, I did not find any information, and with a simple import it gives an error. Further, if GEOMETRY_EXTRACT_TYPE INTERNAL is replaced with WKT, the output will be in the form of 2...ST_Geometry('LINESTRING ( 2273574.65000000 6092216.55000000, 2273566.12000000 6092202.26000000, 2273565.68000000 6092200.66000000)', ) 
and this is the smallest geometry field in the resulting output. If you edit it and make it look like 3...ST_GeomFromText('LINESTRING ( 2273574.65000000 6092216.55000000, 2273566.12000000 6092202.26000000, 2273565.68000000 6092200.66000000)', 4326) 
then she sits down in the geometry field. Productivity is lost because it will be problematic to transfer the entire scheme at once in this way, given that when transferring one table with more than 20 thousand polygonal or linestring format records and the number of coordinates in them is much larger than in the example, it is already too hard for the system to work with so much information, given that the transfer will have to be carried out after editing.

**Comment by Albert88373** [comment]
It is possible that I am doing something wrong

**Comment by Albert88373** [comment]
I tried to change the formation of the output file by changing to Ora2pg.pm line 12150:

(
else {$row->[$idx] = "ST_Geometry('" . $row->[$idx] . "'
on
{$row->[$idx] = "ST_GeomFromText('" . $row->[$idx] . "', 4326)";}
)

and in output.sql, starting from Truncate table and ending with the last insert, it forms everything as it should, but when a given connection to postgri gives the following error:

[2022-11-02 10:41:58] DEBUG: Creating output for 2000 tuples
[2022-11-02 10:41:58] DEBUG: Sending INSERT bulk output directly to PostgreSQL backend
Wide character in subroutine entry at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 15251.
DBD::Pg::st execute failed: ð u ð and ð ø ð With a ð b ð R: parse error - invalid geometry
HINT: "ST" <-- parse error at position 2 within the geometry at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 15251.
Wide character in print at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 14169.
[2022-11-02 10:41:58] FATAL: ð u ð and ð ø ð With a ð b ð R: parse error - invalid geometry
HINT: "ST" <-- parse error at position 2 within geometry
DBI::db=HASH(0x4588ab0)->disconnect invalidates 1 active statement handle (either destroy statement handles or call finish on them before disconnecting) at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 14183.
Aborting export...

I also noticed that when trying to run the program without specifying a specific table, some schemes
get the following error:
ora2pg -p -d -t TABLE -c ora2pg.conf.dist

[2022-11-02 10:57:38] FATAL: ORA-20007: invalid shape typeentity: 16
ORA-06512: at "SDE.ST_GEOMETRY_OPERATORS", line 771 (DBD ERROR: OCIStmtExecute)
DBI::db=HASH(0x48a8960)->disconnect invalidates 2 active statement handles (either destroy statement handles or call finish on them before disconnecting) at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 14183.
Aborting export...

**Comment by darold** [comment]
Commit will help to fix the call to st_geometrytype through a configuration directive ST_GEOMETRYTYPE_FUNCTION like the other directive. It also fixes the type.

About the data exported you should keep using ST_Geometry() and try with USE_LOB_LOCATOR to 0, it should fix the `'OCILobLocatorPtr=SCALAR(0x495c558)',` error. If this works I will force it for geometry columns. You might need to play with LONGREADLEN in ora2pg.conf to avoid truncation error. Let me know.

**Comment by Albert88373** [comment]
In Oracle.pm (my $st_spatial_type = 'SELECT DISTINCT ST_GeometryType(c.%s) FROM %s c WHERE ROWNUM < ' . $max_lines;) you still need to add the sde prefix before ST_GeometryType to access the database.
Yes, using USE_LOB_LOCATOR 0 fixes the error 'OCILobLocatorPtr=SCALAR(0x495c558)', as does changing GEOMETRY_EXTRACT_TYPE from INTERNAL to WKT.
It is not correct to continue using ST_Geometry(), because I refuse to use ArcSDE in postgresql and I am not going to connect the ST_Geometry() library.

**Comment by Albert88373** [comment]
Also, when trying to move the structure of some tables, the following error appears, the reason for which I could not determine:

FATAL: _column_info() ORA-20003: st_geometry type must be a valid geometry type.
ORA-06512: at "SDE.ST_GEOMETRY_OPERATORS", line 872 (DBD ERROR: OCIStmtExecute)
DBI::db=HASH(0x3689560)->disconnect invalidates 1 active statement handle (either destroy statement handles or call finish on them before disconnecting) at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 14183.

Tables are also with st_geometry geometry, I don't see any differences in the data, what could be the problem?

**Comment by darold** [comment]
Commit 0341cf3 adds configuration directive ST_GEOMETRYTYPE_FUNCTION, it works as previous ST_* directives.

**Comment by darold** [comment]
For error "FATAL: _column_info() ORA-20003: st_geometry type must be a valid geometry type." I think that the problem could be an invalid entry in the column. Dose the following query returns an error too on Oracle?
```
SELECT DISTINCT sde.st_geometrytype(c.<colname>) FROM <tablename> c WHERE ROWNUM < 50000;
```
If it reports an error, I don't know how to avoid it.

**Comment by Albert88373** [comment]
Yes, I found the cause of the error "FATAL: _column_info() ORA-20003: st_geometry type must be a valid geometry type.", I had several fields with empty geometry, I'm already eliminating it
