### ISSUE TITLE
Not a HASH reference at ora2pg-16.1/lib/Ora2Pg.pm line 4852

### ISSUE THREAD

**Issue by Ahuri3** [darold/ora2pg#153]
Hello !

I encountered a problem today while using ora2pg (version 16.1)

When I tried to export the oracle partitions it failed on one Oracle database : 

```
$ ora2pg -t PARTITION -o partitions.sql -b schema/partitions -d
Ora2Pg version: 16.1
Trying to connect to database: dbi:Oracle:dddr0cor
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
Force Oracle to compile schema before code extraction
Retrieving partitions information...
........................................................................................................................................................................................................................................................................................................
Add partitions definition...
Not a HASH reference at /dlsgbddeva3250/product/postgres/ora2pg-16.1/lib/Ora2Pg.pm line 4852.
```
I would like to add that my Oracle partitions were only LIST or RANGE. No HASH partitions.

When I tried on another much much simpler Oracle database, with no partitions the command did not fail (they were no partitions to export but still, the command did not fail) : 

```
$ ora2pg -p -t PARTITION -o partitions.sql -b schema/partitions -d
Ora2Pg version: 16.1
Trying to connect to database: dbi:Oracle:duqz0syn
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
Force Oracle to compile schema before code extraction
Retrieving partitions information...

 
Add partitions definition...
```
Additional information : 

On the first Oracle database I was also unable to export functions. The html report with the estimate listed 4 valid functions (but 0 bytes of code), but the export didn't export any "
```
0/0 functions 100% end of output
```
On the second Oracle database the html report listed 4 valid functions ( with 430 bytes of code) and managed to export them properly.

Does anybody know what could cause this problem ? Ora2pg seems to work with well with my tiny tiny base but not on my big one.

**Comment by Ahuri3** [comment]
Found the solution ! I had multiple functions and partitions with the same name in different schemas.
Without the EXPORT_SCHEMA = 1 the export failed.

**Comment by darold** [comment]
Hi,

Yes, usually it is a good idea to export each schema at a time using the SCHEMA directive. If you want to export all schema from the database, you need to unset or comment the SCHEMA directive and enable EXPORT_SCHEMA. This will force Ora2Pg to export all objects prefixed with their respective schema name.

Ora2Pg does not make any distinction between tiny and big database, it is the same :-)

Best regards,
