### ISSUE TITLE
Wrong conversion of rownum clause.

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1530]
Good Mr Darold,

I hereby get in touch because in the migration of a package via ora2pg, I noticed that the native clause of oracle rownum was not converted to the clause row_number() over() of pg, thus causing the program to fail with error of execution.

Oracle Code Example:

CREATE OR REPLACE PACKAGE BODY pck_gmp_ws_preventive_maint IS  
	  PROCEDURE sp_trata_limites_pendencia
	(
		pcoderro OUT NUMBER,
		pmsgerro OUT VARCHAR2,
		pidutil IN NUMBER,
		pididioma IN NUMBER,
		pid_ficha IN NUMBER,
             )
	IS
	BEGIN
		pcoderro := 0;
		LOGGER.INFO('pck_w_int_criar_int_detalhes.sp_trata_limites_pendencia','Fim do processo TRATA PENDENCIAS');
		 WITH cte (id_sala, numero, designacao)  AS (
		     SELECT r.id ID_SALA,(ROWNUM-1) NUMERO
               ,CASE WHEN id_tipo = '11' THEN '[PI-SALA] - ' || r.designacao ELSE '[SITE] - ' || r.designacao  END FROM (SELECT id, id_pai, id_tipo, tipo, codigo, designacao, testes, path, id_sca, id_sca_pai, path_design, morada, codigo_postal, cp_descricao, id_pa,nome_pa, id_interface, inactivo, id_idioma FROM v_tra_dd_area_rede i
WHERE id_site = vid_site AND (id_tipo = '11' OR id_pai IS NULL)
) r WHERE id_pai IS NULL and id_interface = vid_interface UNION ALL		
SELECT r.id ID_SALA,(ROWNUM-1) NUMERO ,CASE WHEN id_tipo = '11' THEN '[PI-SALA] - ' 
|| r.designacao ELSE '[SITE] - ' || r.designacao  END
FROM (id, id_pai, id_tipo, tipo, codigo, designacao, testes, path, id_sca, id_sca_pai, path_design, morada, codigo_postal, cp_descricao, id_pa, nome_pa, id_interface, inactivo, id_idioma
FROM v_tra_dd_area_rede i
WHERE id_site = vid_site AND (id_tipo = '11' OR id_pai IS NULL)) r JOIN cte c ON (c.id_sala = r.id_pai)) SELECT * FROM cte  ORDER BY numero;   
EXCEPTION
WHEN OTHERS THEN
/*CALL*/ LOGGER.ERROR('PCK_GTT_GERAL.SP_OBTEM_ESCALAMENTO_FUNCIONAL',Sqlerrm||'-'||SQLERRM);
	END sp_trata_limites_pendencia;		
END pck_gmp_ws_preventive_maint;
/

Postgres code example:

DROP SCHEMA IF EXISTS pck_gmp_ws_preventive_maint CASCADE;
CREATE SCHEMA IF NOT EXISTS pck_gmp_ws_preventive_maint;
CREATE OR REPLACE PROCEDURE pck_gmp_ws_preventive_maint.sp_trata_limites_pendencia ( pcoderro INOUT numeric, pmsgerro INOUT varchar, pidutil numeric, pididioma numeric, preferencia varchar, pid_ficha numeric, pid_cfg_ficha numeric, pxml_bd xmltype, pxml_web xmltype, pip varchar, pid_particularidade numeric DEFAULT NULL) AS $body$
DECLARE
BEGIN
pcoderro := 0;
LOGGER.INFO('pck_w_int_criar_int_detalhes.sp_trata_limites_pendencia','Fim do processo TRATA PENDENCIAS');
vret:=REPLACE(to_char((to_timestamp(TO_CHAR(pdata,'YYYY-MM-DD')||' '||TO_CHAR(pdata,'HH24:MI:SS.FF3')||' '||vtz,'YYYY-MM-DD HH24:MI:SS.US:') AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS.FF3')||'Z',' ','T');
WITH cte(id_sala, numero, designacao)  AS (
SELECT r.id ID_SALA,(ROWNUM-1) NUMERO
,CASE WHEN id_tipo = '11' THEN '[PI-SALA] - ' || r.designacao ELSE '[SITE] - ' || r.designacao  END
FROM (SELECT id, id_pai, id_tipo, tipo, codigo, designacao, testes, path, id_sca, id_sca_pai, path_design, morada, codigo_postal, cp_descricao, id_pa,nome_pa, id_interface, inactivo, id_idioma FROM v_tra_dd_area_rede i
WHERE id_site = vid_site AND (id_tipo = '11' OR id_pai IS NULL)
) r WHERE id_pai IS NULL and id_interface = vid_interface
UNION ALL
SELECT r.id ID_SALA,(ROWNUM-1) NUMERO ,CASE WHEN id_tipo = '11' THEN '[PI-SALA] - ' 
|| r.designacao ELSE '[SITE] - ' || r.designacao  END
FROM (SELECT id, id_pai, id_tipo, tipo, codigo, designacao, testes, path, id_sca, id_sca_pai, path_design, morada, codigo_postal, cp_descricao, id_pa, nome_pa, id_interface, inactivo, id_idioma FROM v_tra_dd_area_rede i
WHERE id_site = vid_site AND (id_tipo = '11' OR id_pai IS NULL)) r JOIN cte c ON (c.id_sala = r.id_pai)) SELECT * FROM cte  ORDER BY numero;
	EXCEPTION
		WHEN OTHERS THEN
			/*CALL*/
 LOGGER.ERROR('PCK_GTT_GERAL.SP_OBTEM_ESCALAMENTO_FUNCIONAL',Sqlerrm||'-'||SQLERRM);
END;		
$body$
LANGUAGE PLPGSQL;

Is it possible to validate that this is an ora2pg error?, and is it possible to correct it?, I inform you that I have already installed version 23.2 of ora2pg, that is, the latest version.

Best regards,

Rui Pereira.

**Comment by darold** [comment]
Commit c8b9e04 fixes this issue.
