### ISSUE TITLE
Missing objects with ora2pg while extracting schema

### ISSUE THREAD

**Issue by balajithriller** [darold/ora2pg#1535]
When i run export_schema.sh using ora2pg it extracted the DDLs but many objects are missing

synonym - 1 missing
packages - All are missing
indexes -  many are missing (almost 300 out of 1700)
lob  -- all are missing

Oracle objects list

FUNCTION	8
INDEX	1679
JOB	4
LOB	220
PACKAGE	320
PACKAGE BODY	314
PROCEDURE	13
SEQUENCE	6
SYNONYM	3
TABLE	473
TRIGGER	540
TYPE	17
TYPE BODY	5

**Comment by balajithriller** [comment]
For indexes i included the primary key constraints as they will get created as part of alter table add primary key, still 300 are missing

$ /fidrds/ggadmin/balaji/ora2pg-23.2/ora2pg_base/balayuga/schema/tables > cat INDEXES_table.sql  | grep -i create | wc -l
894
$ /fidrds/ggadmin/balaji/ora2pg-23.2/ora2pg_base/balayuga/schema/tables > cat CONSTRAINTS_table.sql | grep -i primary | wc -l
461

1355 is the total indexes where as the actual index is 1679 - 324 indexes missing

ora2pg version - ora2pg-23.2
oracle : 19c

**Comment by balajithriller** [comment]
Missing index scripts

"
  CREATE UNIQUE INDEX "APEX_180200"."APEX$_WS_ROWS_UK1" ON "APEX_180200"."APEX$_WS_ROWS" ("WS_APP_ID", "DATA_GRID_ID", "UNIQUE_VALUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX" "

"
  CREATE UNIQUE INDEX "APEX_180200"."IG_REGION_UK" ON "APEX_180200"."WWV_FLOW_INTERACTIVE_GRIDS" ("REGION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" "

If unique index is the problem, i could see few unique indexes created by ora2pg

CREATE UNIQUE INDEX wwv_flow_stored_queries_uk1 ON wwv_flow_shared_queries (name, flow_id);

**Comment by darold** [comment]
All indexes DDL related to exported tables will be generated. If some are "missing" this is because of the following reasons:

* the related table is not in the list of the exported objects.
* this is an unsupported index type, Cluster, bitmap join, reversed and IOT indexes will not be exported at all.
* the index is defined on a partitioned table and will be automatically created on partition so only DDL on the partitioned table is present.

**Comment by darold** [comment]
An in your system command to check the number of indexes you should use:
```
$ cat CONSTRAINTS_table.sql | grep -E 'PRIMARY|UNIQUE" | wc -l
```
because defining a unique constraint will automatically create a unique index.
