### ISSUE TITLE
ERROR Generated columns cannot be used in COPY

### ISSUE THREAD

**Issue by rhollins** [darold/ora2pg#1538]
I get the following error on one of the tables that contain generated column: which in Oracle was DATA_DEFAULT:

Error Message:
------------------------

psql:./data/TABLE__NAME_data.sql:7: ERROR:  column "column_name" is a generated column
DETAIL:  Generated columns cannot be used in COPY.

Ora2Pg generated files:
-----------------------------------------

In generated files after export looks like schema will create generated column but data files still include it in the copy:

column_name varchar(50) NOT NULL GENERATED ALWAYS AS ('SOME_STRING') STORED,

COPY table_name (column_name) FROM STDIN;

Versions:
-----------------------

Ora2Pg v23.1
Oracle 12
Postgres 13.7
PG_VERSION is set to 13

**Comment by darold** [comment]
Commit 0df4dd7 fix the detection of the GENERATED clause in PostgreSQL output but with latest development code I was not able to reproduce the issue. A generated column is not exported with the COPY action.
