### ISSUE TITLE
Key partition with parameter exports wrong for MYSQL

### ISSUE THREAD

**Issue by shubham-yb** [darold/ora2pg#1539]
Hi Team,

When we have a key partition schema in MYSQL without any parameters, it exports fine,
ex:
`PARTITION BY key( )`

Gets exported as hash.

But if we have any parameters,
Consider this schema:

```
drop table if exists key_partition_test;

CREATE TABLE key_partition_test(
    a INT,
    b char ,
    c INT, primary key(b,c)
)
PARTITION BY key(b)
partitions 2;

INSERT INTO key_partition_test VALUES (5,"a",1),(3,"h",6), (5,"1",1), (5,"y",2);

SELECT PARTITION_NAME, TABLE_ROWS FROM INFORMATION_SCHEMA.PARTITIONS WHERE TABLE_NAME='key_partition_test';

```

We have `b char` as the key for the partition, but during the export, the entire primary key gets exported in the hash.

Exported schema:

```
CREATE TABLE key_partition_test(
	a numeric(10),
	b char(1) NOT NULL,
	c numeric(10) NOT NULL,
	PRIMARY KEY (b,c)
) PARTITION BY HASH (b, c) ;
```

The partition key includes both `b char` and `c numeric`.

Thank You for Your Help.

**Comment by darold** [comment]
Right, hash partitioning doesn't support a multi-column partition key. A solution could be to create a subpartition per additional column but my opinion is that this partitioning must be reviewed and fixed manually. What partitioning solution have you used for that?

**Comment by shubham-yb** [comment]
I was thinking one will have to manually change the partition key to a singular value for key partitioning, or create a parent partition using a key and a secondary subpartition using the other key(counter-intuitive).

But can't the key be picked up from the partition ddl and added as is when being converted to hash? Having the same logic as hash partitioning?
Just a query

**Comment by darold** [comment]
I've though more about this, there is not only HASH partitioning that does not support multi-column key partitioning but also LIST partitioning. I think the real fix is to use an expression instead like concat() between the two columns.

**Comment by shubham-yb** [comment]
Yes list does not support multi column partitioning, but hash with multiple columns is valid I guess. You'll have a better understanding as to how it works internally more than me but it does not error out and is shown when we describe the table. The exported schema i.e.

```
CREATE TABLE key_partition_test(
	a numeric(10),
	b char(1) NOT NULL,
	c numeric(10) NOT NULL,
	PRIMARY KEY (b,c)
) PARTITION BY HASH (b, c) ;
```

Is a valid syntax but it's just that the key itself is not the same. 

If we run this directly in postgres it goes through and if we describe it, we get:

```
Partitioned table "public.key_partition_test"
 Column |     Type      | Collation | Nullable | Default 
--------+---------------+-----------+----------+---------
 a      | numeric(10,0) |           |          | 
 b      | character(1)  |           | not null | 
 c      | numeric(10,0) |           | not null | 
Partition key: HASH (b, c)
Indexes:
    "key_partition_test_pkey" PRIMARY KEY, lsm (b HASH, c ASC)
```

**Comment by darold** [comment]
Ah right, don't know what was wrong in my test. Anyway I can fix that for hash partitioning and use concat for the list partition.

**Comment by shubham-yb** [comment]
Oh great! Thanks a lot

**Comment by darold** [comment]
Commit 4220916 fixes this issue.
