### ISSUE TITLE
_escape_lob function does not export BLOB source type values correctly for non COPY types

### ISSUE THREAD

**Issue by rballer** [darold/ora2pg#154]
I tested a data migration from Oracle 11.2.0.2 to Postgres 9.4.5.

The columns with BLOB source types were not getting imported into the Postgres bytea data type correctly.  I had generated INSERT sql scripts for the data migration.

I examined the Ora2Pg.pm library file and I found the _escape_lob function to be source of the problem.

That function will export the value for the 'INSERT' type as follows at line 12873 in v16.2 Ora2Pg.pm

                if ($src_type eq 'BLOB') {
                        #$col = escape_bytea($col);
                        $col = unpack("H*",$col);
                        if (!$self->{standard_conforming_strings}) {
                                $col = "'$col'";
                        } else {
                                $col = "E'$col'";
                        }
                        # RAW data type is returned in hex
                        $col = "decode($col, 'hex')" if ($src_type eq 'RAW');
                } .....

When I updated the code in the non COPY case to:

                if ($src_type eq 'BLOB') {
                        #$col = escape_bytea($col);
                        $col = unpack("H*",$col);
                        if (!$self->{standard_conforming_strings}) {
                                $col = "'$col'";
                        } else {
                                $col = "E'\\\\x$col'";  # Change I made
                        }
                        # RAW data type is returned in hex
                        $col = "decode($col, 'hex')" if ($src_type eq 'RAW');
                } .....
The data import of the BLOB data using INSERT statements into the bytea columns were processed successfully.

The original version of the value (before my change) would load into the bytea column, but the resulting value was not valid (icons and logos were corrupt in the bytea column value).

The other thing I noticed is the $src_type variable value can never be 'RAW' within that if block since that is the same variable being checked at the top of that if statement and the value is 'BLOB' so that last line in that chunk of code can never get executed.

**Comment by darold** [comment]
Thanks for the report, commit 94fa48c apply your change.

 I've also put a comment in front of the line with the RAW source type, this line was just here for future use, but I still not found a database to migrate with RAW data type.

Note that the use of INSERT export is not recommended if you want to load data at full speed in PostgreSQL, use COPY instead.

Best regards,
