### ISSUE TITLE
Automatic updating for TIMESTAMP and DATETIME in MySQL

### ISSUE THREAD

**Issue by heysky** [darold/ora2pg#1542]
Hi Gilles,

Mysql has a feature to update TIMESTAMP and DATETIME columns automatically like below. 
CREATE TABLE t1 (
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  dt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

https://dev.mysql.com/doc/refman/8.0/en/timestamp-initialization.html

This is currently ignored by ora2pg. Can we add support for this feature like adding a update trigger on the table?

Thanks.

**Comment by darold** [comment]
Commit 3590897 adds this clause translation.
