### ISSUE TITLE
Unsigned decimal types in MYSQL don't export properly

### ISSUE THREAD

**Issue by shubham-yb** [darold/ora2pg#1544]
Hi Team, when we have `unsigned decimal` types in mysql, in the exported files, `UNSIGNED` gets exported and the columns **lose their precision.**

Source schema:

```
create table if not exists fixed_point_types( 

                                             d_us decimal(10,2) unsigned,
					     dec_type dec(5,5) unsigned,
                                             numeric_type numeric(10,5) unsigned,
                                             fixed_type fixed(10,3) unsigned
);
```

Exported schema:

```
CREATE TABLE fixed_point_types (
        d_us DECIMAL UNSIGNED,
        dec_type DECIMAL UNSIGNED,
        numeric_type DECIMAL UNSIGNED,
        fixed_type DECIMAL UNSIGNED
) ;
```

To note:
Decimal types without the unsigned tag export fine and have their precision and scale.

ex:
`create table dec_check(d_us decimal(6,2) );`

Exports fine.

Thank You for your help!

**Comment by darold** [comment]
Commit f08d47a fixes this issue.
