### ISSUE TITLE
Procedures only get exported when written in a particular format in MYSQL

### ISSUE THREAD

**Issue by shubham-yb** [darold/ora2pg#1545]
Hi Team,
This was observed while exporting from MYSQL. The procedures were getting exported only when defined in a particular format.

This might be related to another issue regarding functions.

https://github.com/darold/ora2pg/issues/1507

For example:

Source:

```
drop table if exists view_table1;
​
create table view_table1 (
	id int,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	gender VARCHAR(50),
	ip_address VARCHAR(20)
);

delimiter //
CREATE PROCEDURE insert_data()
insert into view_table1 (id,first_name, last_name, email, gender, ip_address) values (7,'Milzie', 'Rohlfing', 'mrohlfing5@java.com', 'Female', '230.101.87.42');
//

delimiter ;
```

The procedure won't export. i.e. It doesn't get dumped in the export dir, and therefore not imported as well.

But the same procedure defined as:

```
delimiter //
CREATE PROCEDURE insert_data()
BEGIN
insert into view_table1 (id,first_name, last_name, email, gender, ip_address) values (7,'Milzie', 'Rohlfing', 'mrohlfing5@java.com', 'Female', '230.101.87.42');
END
//

delimiter ;
```

Gets exported.

Thank You for your help!

**Comment by shubham-yb** [comment]
cc: @priyanshi-yb

**Comment by darold** [comment]
Commit 8b64f1a might solve this issue.
