### ISSUE TITLE
Parsing of INT type in MYSQL

### ISSUE THREAD

**Issue by shubham-yb** [darold/ora2pg#1547]
Hi team,

While parsing the `integer` type in MySQL, this behaviour was observed while changing the parameter `PG_INTEGER_TYPE` in the ora2pg.conf.

|PG_INTEGER_TYPE| INT mapped to | Affect on sequences|
|-------------------|----------------|----------------------|
|            0                  |  numeric(10)     | Sequences don't export|
|            1                   |    bigint             | Sequences export     |

This is also regarding another ticket which I had put up regarding sequences.
https://github.com/darold/ora2pg/issues/1522

**Example:**

The source schema:

```
create table seq_check (
	id int primary key auto_increment,
	first_name VARCHAR(50)
);
```

Exported schema when parameter `PG_INTEGER_TYPE 0`

```
CREATE TABLE seq_check (
	id numeric(10) NOT NULL,
	first_name varchar(50),
	PRIMARY KEY (id)
) ;
```

Exported schema when parameter `PG_INTEGER_TYPE 1`

```
CREATE TABLE seq_check (
        id bigserial,
        first_name varchar(50),
        PRIMARY KEY (id)
) ;
ALTER SEQUENCE func_check_id_seq RESTART WITH 1;

```

I had another query

Since the range of signed integers is the same for MYSQL and POSTGRES, why do we map it to a larger datatype? This surely has an effect on the performance.

**Comment by darold** [comment]
Got it, thanks for the investigation of the problem. Commit da9dfd3 might fix this issue.

**Comment by darold** [comment]
About performances of serial vs bigserial there is no difference, it will just take more disk space but the advantage is that you will not reach the integer limit. I don't know the way MySQL handle sequence but remember that PostgreSQL can have holes in the sequences following the concurrency and the cache of the sequence.

**Comment by shubham-yb** [comment]
No no, I meant for simple signed integers without any `auto_increment/sequence` attached to them. I get that for sequences we might need this behaviour.
