### ISSUE TITLE
"DBD::Oracle::st fetch failed: ORA-12733: regular expression too long" when migrating from v13 to v16.2

### ISSUE THREAD

**Issue by lpenet** [darold/ora2pg#155]
Probably not a bug but an advice on upgrade.

I very often replicate a subset an Oracle DB in a postgres db, for development purpose. I use to select the tables to replicate using -a "<a very long, comma separated list, of tables>".

It worked fined with v13 I am actualling using but no more with 16.2 that I just tried.

I have the following error at various lines of ora2pg.pm

    "DBD::Oracle::st fetch failed: ORA-12733: regular expression too long"

For instance, line 8085  and following  :

                foreach my $t (sort {$tables_infos{$b}{num_rows} <=> $tables_infos{$a}{num_rows}} keys %tables_infos) {
                        $self->logit("\t[$i] TABLE $t has $tables_infos{$t}{num_rows} rows\n", 0);
                        $i++;
                        last if ($i > $self->{top_max});
                }

I remember having to change the syntax of my configuration when migrating to v13. What should I do this time ?

Thanks in advance, and many thanks for ora2pg.

**Comment by darold** [comment]
Hi,

I think you are using an obsolete syntaxe for the ALLOW and EXCLUDE directives. Please have a look to chapter "Limiting object to export" in documentation (README).

If you simply want to restrict export to some tables you need to use the following syntaxe:

    ora2pg -p -c ora2pg.conf -t TABLE -a 'TAB1 TAB2 MYTAB_.*'

the list separator is a space.

Best regards,
