### ISSUE TITLE
TEST_COUNT (and --count_rows) using default schema instead of PG_SCHEMA

### ISSUE THREAD

**Issue by mariuskh** [darold/ora2pg#1550]
Hi!
When running ora2pg with the `test_count` type, the Postgres schema (defined in `PG_SCHEMA`) is not included. This leads to an error `relation does not exist`.

I believe the schema is being set on this line: 
https://github.com/darold/ora2pg/blob/0df4dd7dd2e43a42768c794e9729834348cad898/lib/Ora2Pg.pm#L16567

I printed the values, and see that `$schema` is empty and `$both` only includes the table name. 

I see from `set_pg_relation_name` that I can include `EXPORT_SCHEMA 1`:
https://github.com/darold/ora2pg/blob/0df4dd7dd2e43a42768c794e9729834348cad898/lib/Ora2Pg.pm#L16529

I have tested that this works. However, we do not need this directive for any other purpose, so it would be better if it worked without this directive.

Any thoughts or help is appreciated.

**Comment by darold** [comment]
Commit 687ff89 fixes this issue.
