### ISSUE TITLE
X-Post: Extra DDL formations in PARTITION_INDEXES_partition.sql in MYSQL

### ISSUE THREAD

**Issue by shubham-yb** [darold/ora2pg#1551]
Hi Team,
Thank You for the quick fix on https://github.com/darold/ora2pg/issues/1537

I had also noticed this for another partition, i.e. `PARTITION BY RANGE COLUMNS`. An extra DDL gets formed even though there are no indexes on the source.

Source schema:

```
drop table if exists range_columns_partition_test;

CREATE TABLE range_columns_partition_test (
    a INT,
    b INT
)
PARTITION BY RANGE COLUMNS(a, b) (
    PARTITION p0 VALUES LESS THAN (5, 5),
    PARTITION p1 VALUES LESS THAN (MAXVALUE, MAXVALUE)
);

INSERT INTO range_columns_partition_test VALUES (5,5),(3,4), (5,11), (5,12),(4,3),(3,1);
```

The partition is exported fine but an extra DDL gets formed in `PARTITION_INDEXES_partition.sql`

```
-- Create indexes on each partition of table range_columns_partition_test
CREATE INDEX p1_b ON p1 (b);
```

This is syntactically correct but it is there any specific reason why it gets created or is it a bug?

Thank You

**Comment by darold** [comment]
Right, I had miss this report. Commit 7b8f018 fixes this issue.
