### ISSUE TITLE
Error converting %ROWCOUNT clause from oracle to pg

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1552]
Good morning Mr. Darold,

I come by this means to get in touch because in the migration of a package from oracle to pg, the native clause of the oracle %ROWCOUNT was wrongly converted, as visible in the code below:

**Example Oracle Code:**

CREATE OR REPLACE PACKAGE BODY pck_gmp_ws_preventive_maint IS  
	  PROCEDURE sp_trata_limites_pendencia
	(
		pcoderro OUT NUMBER,
		pmsgerro OUT VARCHAR2,
		pidutil IN NUMBER,
		pididioma IN NUMBER,
	)
	IS
		vret varchar2(100);
		vaux VARCHAR2(4000);
		vcondicao VARCHAR2(32767);
		vxml_bd SYS.XMLTYPE;
		TYPE varray_type IS VARRAY(3) OF PLS_INTEGER;
		pi    varray_type := varray_type();
	BEGIN
		    pck_w_got_ot.sp_gerir_ot_lista(pcoderro => pcoderro,
			pmsgerro => pmsgerro,
			pid_idioma => to_number(vidioma),
			pid_janela => replace('SIGO-INTERFACE([[INTERFACE]])', '[[INTERFACE]]', ''),
			pip => NULL,
			plista_erros => vlista_erros);
--Se a OT já não se encontra num estado possível para realizar a operação
IF vlista_erros%ROWCOUNT > 0 THEN
	pcoderro := 1005;
	 vparametro := vreferencia;
	RAISE EXCEPTION 'e_erro_interface' USING ERRCODE = '50001';
END IF;   
	EXCEPTION
		WHEN OTHERS THEN
LOGGER.ERROR('PCK_GTT_GERAL.SP_OBTEM_ESCALAMENTO_FUNCIONAL',Sqlerrm||'-'||SQLERRM);
	END sp_trata_limites_pendencia;		
END pck_gmp_ws_preventive_maint;
/  

**Example pg code:**

CREATE OR REPLACE PROCEDURE pck_gmp_ws_preventive_maint.sp_trata_limites_pendencia ( pcoderro INOUT numeric, pmsgerro INOUT varchar, pidutil numeric, pididioma numeric, ) AS $body$
DECLARE
		vret varchar(100);
		vaux varchar(4000);
		vcondicao varchar(32767);
		vxml_bd xmltype;
		pi    varray_type := varray_type();
	
BEGIN
	pck_w_got_ot.sp_gerir_ot_lista(pcoderro => pcoderro,
			pmsgerro => pmsgerro,
			pid_idioma => to_number(vidioma),
			pid_janela => replace('SIGO-INTERFACE([[INTERFACE]])', '[[INTERFACE]]', ''),
			pip => NULL,
			plista_erros => vlista_erros);

--Se a OT já não se encontra num estado possível para realizar a operação
IF vlista_erros%ROWCOUNT > 0 THEN
		pcoderro := 1005;
		vparametro := vreferencia;
		RAISE EXCEPTION 'e_erro_interface' USING ERRCODE = '50001';
END IF;
	EXCEPTION
		WHEN OTHERS THEN
LOGGER.ERROR('PCK_GTT_GERAL.SP_OBTEM_ESCALAMENTO_FUNCIONAL',Sqlerrm||'-'||SQLERRM);
	END;		
$body$
LANGUAGE PLPGSQL;

If it was cast correctly it should have stayed.

CREATE OR REPLACE PROCEDURE pck_gmp_ws_preventive_maint.sp_trata_limites_pendencia ( pcoderro INOUT numeric, pmsgerro INOUT varchar, pidutil numeric, pididioma numeric, ) AS $body$
DECLARE
		vret varchar(100);
		vaux varchar(4000);
		vcondicao varchar(32767);
		vxml_bd xmltype;
		pi    varray_type := varray_type();
	
BEGIN
		    pck_w_got_ot.sp_gerir_ot_lista(pcoderro => pcoderro,
			pmsgerro => pmsgerro,
			pid_idioma => to_number(vidioma),
			pid_janela => replace('SIGO-INTERFACE([[INTERFACE]])', '[[INTERFACE]]', ''),
			pip => NULL,
			plista_erros => vlista_erros);
--Se a OT já não se encontra num estado possível para realizar a operação
GET DIAGNOSTICS vlista_erros_count = ROW_COUNT;
IF vlista_erros_count > 0 THEN
	pcoderro := 1005;
	vparametro := vreferencia;
	RAISE EXCEPTION 'e_erro_interface' USING ERRCODE = '50001';
END IF;
EXCEPTION
WHEN OTHERS THEN
 LOGGER.ERROR('PCK_GTT_GERAL.SP_OBTEM_ESCALAMENTO_FUNCIONAL',Sqlerrm||'-'||SQLERRM);
END;		
$body$
LANGUAGE PLPGSQL;

vlista_erros_count(it's just the name of a variable and serves only as an example), can you confirm that it's an ora2pg conversion error?, ora2pg supposedly should correctly convert the %ROWCOUNT clause, right?

Best regards,

Rui Pereira.

**Comment by darold** [comment]
Commit 77d183f fixes this issue.
