### ISSUE TITLE
Errors that still persist after installing ora2pg version 23.2

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1553]
Good morning Mr. Darold,

I come in this way to get in touch with you because I have already installed the latest version of Ora2pg(23.2) that was released last October and after doing a general review of the problems that I discovered in ora2pg, I saw that the problems associated with the following tickets still persist:

https://github.com/darold/ora2pg/issues/1456

https://github.com/darold/ora2pg/issues/1391

Can you prove that these problems still persist today in the latest version of ora2pg?, if so is it possible to correct?

Best regards,

Rui Pereira.

**Comment by darold** [comment]
They are fixed.
