### ISSUE TITLE
Wrong conversion of XMLCDATA function in ora2pg

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1555]
Good afternoon Mr Darold,

I'm hereby getting in touch with you because when converting a package from oracle to PG, using ora2pg, the XMLCDATA function was converted incorrectly.

_Example of oracle code:_

CREATE OR REPLACE PACKAGE BODY pck_gmp_ws_preventive_maint IS  
	  PROCEDURE sp_trata_limites_pendencia
	(
		pcoderro OUT NUMBER,
		pmsgerro OUT VARCHAR2,
		pidutil IN NUMBER,
		pididioma IN NUMBER,
	)
	IS
		vret varchar2(100);
		vaux VARCHAR2(4000);
		vcondicao VARCHAR2(32767);
		vxml_bd SYS.XMLTYPE;
		TYPE varray_type IS VARRAY(3) OF PLS_INTEGER;
		pi    varray_type := varray_type();
	BEGIN
SELECT
          getClobVal(XMLAGG(
            XMLELEMENT(name "bodyRequest",
              XMLELEMENT( name "fr",
                XMLFOREST(
                  XMLCDATA(f.referencia) as "referenciaFR"
                  , (SELECT EXTRACT(
                              XMLAGG(
                                XMLELEMENT(name "Ficheiro",
                                 XMLFOREST(
                                   XMLCDATA(
                                      'http://'||(SELECT valor FROM tra_dd_constante WHERE chave = 'ttk_server')||'/download/download.jsp?mongoURI='
||(SELECT valor FROM tra_dd_constante WHERE chave = 'MongoDBURI')||CHR(38)
|| (CASE WHEN a.id_rep_externo IS NOT NULL AND a.id_rep_externo <> '-1' THEN
-- ID_REP_EXTERNO
'fileId='||a.id_rep_externo
ELSE
-- REFERENCIA/NOME_FICHEIRO
'mapQuery=true'||CHR(38)||'filterHex='||REGEXP_REPLACE(dump('{referencia:"'||REPLACE(f.referencia,':FR','_FR')||'",nomeFicheiro:"'||a.anexo||'"}',16),'Typ=[[:digit:]]+ Len=[[:digit:]]+: ')
END)) as "FileName")
  )),'*') FROM gfr_fr_ficheiro a
WHERE id_registo = f.id_registo AND a.tipo_registo = 'F'
                  ) "infos"
                ))
            )
          ))
		           INTO vxml
                  FROM (SELECT preferencia REFERENCIA, vid_registo ID_REGISTO FROM dual) f;
			END IF;   
	EXCEPTION
		WHEN OTHERS THEN
LOGGER.ERROR('PCK_GTT_GERAL.SP_OBTEM_ESCALAMENTO_FUNCIONAL',Sqlerrm||'-'||SQLERRM);
	END sp_trata_limites_pendencia;		
END pck_gmp_ws_preventive_maint;
/

_Postgres code example:_

CREATE OR REPLACE PROCEDURE pck_gmp_ws_preventive_maint.sp_trata_limites_pendencia ( pcoderro INOUT numeric, pmsgerro INOUT varchar, pidutil numeric, pididioma numeric, ) AS $body$
DECLARE
 vret varchar(100);
vaux varchar(4000);
vcondicao varchar(32767);
vxml_bd xmltype;
pi    varray_type := varray_type();	
BEGIN
SELECT
          getClobVal(XMLAGG(
            XMLELEMENT(name "bodyRequest",
              XMLELEMENT( name "fr",
                XMLFOREST(
                  '<![CDATA[' || f.referencia || ']]>' as "referenciaFR"
                  , (SELECT EXTRACT(
                              XMLAGG(
                                XMLELEMENT(name "Ficheiro",
                                 XMLFOREST(
                                   **_XMLCDATA(_**
                                      'http://'||(SELECT valor FROM tra_dd_constante WHERE chave = 'ttk_server')||'/download/download.jsp?mongoURI='||(SELECT valor FROM tra_dd_constante WHERE chave = 'MongoDBURI')||CHR(38) || (CASE WHEN a.id_rep_externo IS NOT NULL AND a.id_rep_externo <> '-1' THEN
-- ID_REP_EXTERNO
'fileId='||a.id_rep_externo
ELSE-- REFERENCIA/NOME_FICHEIRO
'mapQuery=true'||CHR(38)||'filterHex='||REGEXP_replace(dump('{referencia:"'||REPLACE(f.referencia,':FR','_FR')||'",nomeFicheiro:"'||a.anexo||'"}',16), 'Typ=[[:digit:]]+ Len=[[:digit:]]+: ', '') END)**_) as "FileName"_**))),'*')
FROM gfr_fr_ficheiro a
   WHERE id_registo = f.id_registo AND a.tipo_registo = 'F'
                  ) "infos"
                ))
            )
          )) INTO STRICT vxml
                  FROM (SELECT preferencia REFERENCIA, vid_registo ID_REGISTO ) f;
END IF;
EXCEPTION
WHEN OTHERS THEN		
 LOGGER.ERROR('PCK_GTT_GERAL.SP_OBTEM_ESCALAMENTO_FUNCIONAL',Sqlerrm||'-'||SQLERRM);
END;$body$
LANGUAGE PLPGSQL;

The line XMLCDATA( should have been converted to '<![CDATA[' || by ora2pg while the line ) as "FileName", should have been converted to || ']]>' as "FileName", but that didn't happen, can you please confirm, if possible, that this is an ora2pg error, if so is it possible to correct it?

Best regards,

Rui Pereira.

**Comment by darold** [comment]
This should be fixed, at least it is well translated with latest development code.
