### ISSUE TITLE
Greater than 500MB and less than 1GB BLOB DATA Migration Issues

### ISSUE THREAD

**Issue by youngbeenson** [darold/ora2pg#1556]
Good morning MR.Darold,

During 700MB single data migration while I was using ora2pg, the following phrase occurs and the data was not migrated.
(Oracle to PostgreSQL)

		[2022-11-24 16:27:37] DEGUG: Query sent to Oracle: SELECT "ID","DATETIME",CASE WHEN dbms_lob.getlength("DATA") = 0 THEN NULL ELSE "DATA" END,"DATA_NAME" FROM "TEST"."BLOB_TB1" a WHERE (ID=57)
		[2022-11-24 16:27:38] Fetching all data from BLOB_TB1 tuples...
		[2022-11-24 16:29:24] Dumping data from table BLOB_TB1 into PostgreSQL table BLOB_TB1...
		[2022-11-24 16:29:24] Setting client_encoding to UTF8...
		[2022-11-24 16:29:24] Disabling synchronous commit when writing to PostgreSQL...
		[2022-11-24 16:29:24] DEBUG: Formatting bulk of 10 data (real: 1 rows) for PostgreSQL.
		[2022-11-24 16:29:26] DEBUG: Creating output for 10 tuples
		[2022-11-24 16:29:26] DEBUG: Sending COPY bulk output directly to PostgreSQL backend
		DBD::Pg::db pg_putcopydata failed: server closed the connection unexpectedly
				This probably means the server terminated abnormally
				before or while processing the request. at /usr/share/perl5/vendor_perl/Ora2Pg.pm line 15130.
		[2022-11-24 16:29:28] FATAL: server closed the connection unexpectedly
				This probably means the server terminated abnormally
				before or while processing the request.
		Aborting export...

And, PostgreSQL LOG is as follows

		2022-11-24 16:29:28.109 KST [342835] LOG:  invalid message length
		2022-11-24 16:29:28.109 KST [342835] CONTEXT:  COPY blob_tb1, line 1
		2022-11-24 16:29:28.109 KST [342835] STATEMENT:
				COPY blob_tb1 (id,datetime,data,data_name) FROM STDIN
		
		2022-11-24 16:29:28.109 KST [342835] ERROR:  unexpected EOF on client connection with an open transaction
		2022-11-24 16:29:28.109 KST [342835] CONTEXT:  COPY blob_tb1, line 1
		2022-11-24 16:29:28.109 KST [342835] STATEMENT:
				COPY blob_tb1 (id,datetime,data,data_name) FROM STDIN

It is same to Greater than 500MB and less than 1GB blob data.

Data under 500MB perfroms well.

The DDL for Oracle TABLE is as follows,

		CREATE TABLE "TEST"."BLOB_TB1" 
		(	"ID" NUMBER(*,0) DEFAULT "TEST"."SEQ_BLOB"."NEXTVAL" NOT NULL ENABLE, 
			"DATETIME" DATE DEFAULT sysdate, 
			"DATA" BLOB, 
			"DATA_NAME" VARCHAR2(30), 
			CONSTRAINT "BLOB_TB1_PK" PRIMARY KEY ("ID")
		);
		
		CREATE SEQUENCE TEST.SEQ_BLOB INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;
		
		CREATE UNIQUE INDEX "TEST"."BLOB_TB1_PK" ON "TEST"."BLOB_TB1" ("ID") 
		PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
		STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
		PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
		BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
		TABLESPACE "TEST_BLOB_TBS" ;
		

Oracle BLOB data was created as follows,

		encoding : UTF8
		
		HOW TO CREATE BLOB DATA : Inserting a FILE(Created by text stitching) using a procedure
		
		PROCEDURE CONTENTS : CREATE OR REPLACE PROCEDURE TEST.PCD_BLOB_INSERT (V_FILENAME IN VARCHAR2, DATA_NAME IN VARCHAR2)
							 IS
							 V_SOURCE BFILE;
							 V_DEST BLOB;
							 V_LENGTH BINARY_INTEGER;
							 V_ID NUMBER;
							 
							 BEGIN
							 V_SOURCE := BFILENAME('BLOB_DIR1',V_FILENAME);
							 
							 INSERT INTO BLOB_TB1(ID, DATA, DATA_NAME)
							 VALUES (SEQ_BLOB.nextval, EMPTY_BLOB(),V_FILENAME)
							 RETURNING DATA INTO V_DEST;
							 
							 SELECT SEQ_BLOB.currval INTO V_ID FROM DUAL;
							 
							 SELECT DATA INTO V_DEST FROM BLOB_TB1 WHERE ID=V_ID FOR UPDATE;
							 
							 DBMS_LOB.fileopen (V_SOURCE, DBMS_LOB.file_readonly);
							 V_LENGTH := DBMS_LOB.getlength(V_SOURCE);
							 
							 DBMS_LOB.LOADFROMFILE(V_DEST,V_SOURCE,V_LENGTH);
							 
							 UPDATE BLOB_TB1 SET DATA=V_DEST WHERE ID=V_ID;
							 DBMS_LOB.CLOSE(V_SOURCE);
							 COMMIT;
							 END;

PG DDL is shown below.

		CREATE TABLE public.blob_tb1 (
			id numeric(38,0) DEFAULT nextval('public.seq_blob'::regclass) NOT NULL,
			datetime timestamp without time zone DEFAULT statement_timestamp(),
			data bytea,
			data_name character varying(30)
		);
		
		CREATE SEQUENCE seq_blob INCREMENT 1 MINVALUE 1 NO MAXVALUE START 20 CACHE 20;

The ora2pg parameters I set are as follows.

		DATA_LIMIT     100
		BLOB_LIMIT     10
		LONGREADLEN     1073741823
		#LONGTRUNCOK    0
		USE_LOB_LOCATOR 1
		LOB_CHUNK_SIZE  512000
		ENABLE_BLOB_EXPORT              1
		ALLOW BLOB_TB1
		WHERE BLOB_TB1[ID=57]
		
**57 is 600MB BLOB DATA's ID

and PostgreSQL Server is as follows.

		CPU : 8 cores
		MEM : 32GB
		DISK : 1TB
		
		PG_VERSION : 14
		shared_buffers=8096MB

It was said that < 1G blob data would be migrated, but I would like to know how to adjust the parameters.

Best regards,
youngbeen son

**Comment by gilles-migops** [comment]
Hi,

The problem here is that you have BLOB that exceed the max size for an object (1GB), remember that a binary data need to be escaped before being stored to a bytea which increased drastically its size. Unless using the binary format with COPY, the original data size could not exceed 500MB. You should consider using the large object capability of Ora2Pg using a large object column in PostgreSQL instead of bytea and the `--lo_import` command line option when exporting data. See documentation for more information.
