### ISSUE TITLE
Problem with trigger during second atempt when first failed because of active constraints

### ISSUE THREAD

**Issue by sttachoires** [darold/ora2pg#156]
First attempt goes:
postgres@tlstnpgrdb02:/tech/postgres/dba/ora2pg/GRM/STATS [stats] : ora2pg --type=COPY --conf=./config/ora2pg.conf
[========================>] 29/29 tables (100.0%) end of scanning.                         
[========================>] 0/0 rows (100.0%) Table QRTZ_BLOB_TRIGGERS (0 recs/sec)
[>                        ]        0/31066019 rows (0.0%) on total estimated data (1 sec., avg: 0 recs/sec)
[========================>] 0/0 rows (100.0%) Table QRTZ_CALENDARS (0 recs/sec)                            
[>                        ]        0/31066019 rows (0.0%) on total estimated data (1 sec., avg: 0 recs/sec)
DBD::Pg::db pg_putcopyend failed: ERROR:  insert or update on table "qrtz_cron_triggers" violates foreign key constraint "sys_c0036447"
DETAIL:  Key (trigger_name, trigger_group)=(sendAlertOnErrorTrigger, DEFAULT) is not present in table "qrtz_triggers". at /usr/local/share/perl5/Ora2Pg.pm line 10387.
FATAL: ERROR:  insert or update on table "qrtz_cron_triggers" violates foreign key constraint "sys_c0036447"
DETAIL:  Key (trigger_name, trigger_group)=(sendAlertOnErrorTrigger, DEFAULT) is not present in table "qrtz_triggers".
Aborting export...
postgres@tlstnpgrdb02:/tech/postgres/dba/ora2pg/GRM/STATS [stats] :

Then I change configuration:
/bin/sed --in-place=.$(date "+%Y.%m.%d_%H.%M.%S") '/^DROP_FKEY =/{s/.*/DROP_FKEY = 1/}/^DROP_INDEXES =/{s/.*/DROP_INDEXES = 1/}' ora2pg.conf

Then
postgres@tlstnpgrdb02:/tech/postgres/dba/ora2pg/GRM/STATS [stats] : ora2pg --type=COPY --conf=./config/ora2pg.conf
[========================>] 29/29 tables (100.0%) end of scanning.                         
NOTICE:  constraint "sys_c0036451" of relation "qrtz_blob_triggers" does not exist, skipping
NOTICE:  constraint "sys_c0036447" of relation "qrtz_cron_triggers" does not exist, skipping
NOTICE:  constraint "sys_c0036425" of relation "qrtz_job_listeners" does not exist, skipping
NOTICE:  constraint "sys_c0036442" of relation "qrtz_simple_triggers" does not exist, skipping
NOTICE:  constraint "sys_c0036435" of relation "qrtz_triggers" does not exist, skipping
NOTICE:  constraint "sys_c0036456" of relation "qrtz_trigger_listeners" does not exist, skipping
NOTICE:  constraint "fkcbd43dd799e8faf6" of relation "stats_accessright_xitilevel" does not exist, skipping
NOTICE:  constraint "fkcbd43dd75b174c4e" of relation "stats_accessright_xitilevel" does not exist, skipping
NOTICE:  constraint "fk1f8b37dfd77f12c" of relation "stats_computer_last_con_id" does not exist, skipping
NOTICE:  constraint "fk601d8b16cf65bc8d" of relation "stats_feature" does not exist, skipping
NOTICE:  constraint "fk601d8b16a85961c3" of relation "stats_feature" does not exist, skipping
NOTICE:  constraint "fkf0031fc2cf65bc8d" of relation "stats_ft_default_value" does not exist, skipping
NOTICE:  constraint "fk190ab56bce85a4d" of relation "stats_profil_mapping" does not exist, skipping
NOTICE:  constraint "fk190ab56ba817cb4d" of relation "stats_profil_mapping" does not exist, skipping
NOTICE:  constraint "fkb4d05a7474c8c68d" of relation "stats_to_xiti_step_fire" does not exist, skipping
NOTICE:  constraint "fkb4d05a74f029e727" of relation "stats_to_xiti_step_fire" does not exist, skipping
NOTICE:  constraint "fk6804eb1c5d8ad08c" of relation "stats_xiti_first_level" does not exist, skipping
NOTICE:  constraint "fkcc742cb536a29ed" of relation "stats_xiti_level" does not exist, skipping
NOTICE:  constraint "fk24e3a6925d8ad08c" of relation "stats_xiti_second_level" does not exist, skipping
NOTICE:  constraint "fk24e3a69293aecde7" of relation "stats_xiti_second_level" does not exist, skipping
[========================>] 0/0 rows (100.0%) Table QRTZ_BLOB_TRIGGERS (0 recs/sec)
[>                        ]        0/31066019 rows (0.0%) on total estimated data (1 sec., avg: 0 recs/sec)
[========================>] 0/0 rows (100.0%) Table QRTZ_CALENDARS (0 recs/sec)                            
[>                        ]        0/31066019 rows (0.0%) on total estimated data (1 sec., avg: 0 recs/sec)
[========================>] 2/2 rows (100.0%) Table QRTZ_CRON_TRIGGERS (2 recs/sec)                        
[>                        ]        2/31066019 rows (0.0%) on total estimated data (1 sec., avg: 2 recs/sec)
[========================>] 0/0 rows (100.0%) Table QRTZ_FIRED_TRIGGERS (0 recs/sec)                       
[>                        ]        2/31066019 rows (0.0%) on total estimated data (1 sec., avg: 2 recs/sec)
[========================>] 2/2 rows (100.0%) Table QRTZ_JOB_DETAILS (2 recs/sec)                          
[>                        ]        4/31066019 rows (0.0%) on total estimated data (1 sec., avg: 4 recs/sec)
[========================>] 0/0 rows (100.0%) Table QRTZ_JOB_LISTENERS (0 recs/sec)                        
[>                        ]        4/31066019 rows (0.0%) on total estimated data (1 sec., avg: 4 recs/sec)
[========================>] 5/5 rows (100.0%) Table QRTZ_LOCKS (5 recs/sec)                                
[>                        ]        9/31066019 rows (0.0%) on total estimated data (1 sec., avg: 9 recs/sec)
[========================>] 0/0 rows (100.0%) Table QRTZ_PAUSED_TRIGGER_GRPS (0 recs/sec)                  
[>                        ]        9/31066019 rows (0.0%) on total estimated data (1 sec., avg: 9 recs/sec)
[========================>] 2/2 rows (100.0%) Table QRTZ_SCHEDULER_STATE (2 recs/sec)                      
[>                        ]       11/31066019 rows (0.0%) on total estimated data (1 sec., avg: 11 recs/sec)
[========================>] 0/0 rows (100.0%) Table QRTZ_SIMPLE_TRIGGERS (0 recs/sec)                       
[>                        ]       11/31066019 rows (0.0%) on total estimated data (1 sec., avg: 11 recs/sec)
[========================>] 2/2 rows (100.0%) Table QRTZ_TRIGGERS (2 recs/sec)                              
[>                        ]       13/31066019 rows (0.0%) on total estimated data (1 sec., avg: 13 recs/sec)
[========================>] 0/0 rows (100.0%) Table QRTZ_TRIGGER_LISTENERS (0 recs/sec)                     
[>                        ]       13/31066019 rows (0.0%) on total estimated data (1 sec., avg: 13 recs/sec)
[========================>] 0/0 rows (100.0%) Table STATS_ACCESSRIGHT_XITILEVEL (0 recs/sec)                
[>                        ]       13/31066019 rows (0.0%) on total estimated data (1 sec., avg: 13 recs/sec)
[========================>] 0/0 rows (100.0%) Table STATS_ACCESS_RIGHT (0 recs/sec)                         
[>                        ]       13/31066019 rows (0.0%) on total estimated data (1 sec., avg: 13 recs/sec)
[========================>] 15100850/15057830 rows (100.3%) Table STATS_COMPUTER (32266 recs/sec)           
[===========>             ] 15057843/31066019 rows (48.5%) on total estimated data (469 sec., avg: 32106 recs/sec)
[========================>] 16032173/15994501 rows (100.2%) Table STATS_COMPUTER_LAST_CON_ID (42413 recs/sec)     
[=======================> ] 31052344/31066019 rows (100.0%) on total estimated data (848 sec., avg: 36618 recs/sec)
[========================>] 37/37 rows (100.0%) Table STATS_FEATURE (37 recs/sec)                                  
[=======================> ] 31052381/31066019 rows (100.0%) on total estimated data (848 sec., avg: 36618 recs/sec)
[========================>] 3/3 rows (100.0%) Table STATS_FEATURE_TYPE (3 recs/sec)                                
[=======================> ] 31052384/31066019 rows (100.0%) on total estimated data (848 sec., avg: 36618 recs/sec)
[========================>] 2/2 rows (100.0%) Table STATS_FT_DEFAULT_VALUE (2 recs/sec)                            
[=======================> ] 31052386/31066019 rows (100.0%) on total estimated data (848 sec., avg: 36618 recs/sec)
[========================>] 48/48 rows (100.0%) Table STATS_PROFIL_MAPPING (48 recs/sec)                           
[=======================> ] 31052434/31066019 rows (100.0%) on total estimated data (848 sec., avg: 36618 recs/sec)
[========================>] 3/3 rows (100.0%) Table STATS_PROJECT_PROPERTIES (3 recs/sec)                          
[=======================> ] 31052437/31066019 rows (100.0%) on total estimated data (848 sec., avg: 36618 recs/sec)
[========================>] 1957/1933 rows (101.2%) Table STATS_TO_XITI_LAUNCHED (1957 recs/sec)                   
[=======================> ] 31054370/31066019 rows (100.0%) on total estimated data (848 sec., avg: 36620 recs/sec)
[========================>] 6/6 rows (100.0%) Table STATS_TO_XITI_STEPS (6 recs/sec)                               
[=======================> ] 31054376/31066019 rows (100.0%) on total estimated data (848 sec., avg: 36620 recs/sec)
[========================>] 11742/11598 rows (101.2%) Table STATS_TO_XITI_STEP_FIRE (11742 recs/sec)               
[=======================> ] 31065974/31066019 rows (100.0%) on total estimated data (849 sec., avg: 36591 recs/sec)
[========================>] 0/0 rows (100.0%) Table STATS_WEL_MSGLIBELLE (0 recs/sec)                              
[=======================> ] 31065974/31066019 rows (100.0%) on total estimated data (849 sec., avg: 36591 recs/sec)
[========================>] 15/15 rows (100.0%) Table STATS_XITI_FIRST_LEVEL (15 recs/sec)                         
[=======================> ] 31065989/31066019 rows (100.0%) on total estimated data (849 sec., avg: 36591 recs/sec)
[========================>] 22/22 rows (100.0%) Table STATS_XITI_LEVEL (22 recs/sec)                               
[=======================> ] 31066011/31066019 rows (100.0%) on total estimated data (849 sec., avg: 36591 recs/sec)
[========================>] 7/7 rows (100.0%) Table STATS_XITI_SECOND_LEVEL (7 recs/sec)                           
[=======================> ] 31066018/31066019 rows (100.0%) on total estimated data (849 sec., avg: 36591 recs/sec)
[========================>] 1/1 rows (100.0%) Table WEL_ADDONS (1 recs/sec)                                        
[========================>] 31066019/31066019 rows (100.0%) on total estimated data (849 sec., avg: 36591 recs/sec)
DBD::Pg::db do failed: ERROR:  syntax error at or near ";"
LINE 1: ...RENCES qrtz_triggers(trigger_name,trigger_group) INITIALLY ;
                                                                      ^ at /usr/local/share/perl5/Ora2Pg.pm line 4820.
FATAL: ERROR:  syntax error at or near ";"
LINE 1: ...RENCES qrtz_triggers(trigger_name,trigger_group) INITIALLY ;
                                                                      ^
Aborting export...

**Comment by darold** [comment]
Hi Stephane,

Thanks for the report. Please give a try to latest development code, last commit  3be4c59 might solves this issue.

**Comment by sttachoires** [comment]
It works now.
You are "too much of the ball" :)
