### ISSUE TITLE
Ora2Pg: Error in default subpartition migration

### ISSUE THREAD

**Issue by elexus** [darold/ora2pg#1562]
I'm creating default subpartition in table.
![image](https://user-images.githubusercontent.com/14944095/206179924-0437ecc7-e166-4978-9efc-568cd352e2d3.png)

After migration by Ora2Pg it creates subpartiotions, but default refers not to partiotion, but to parent table:
![image](https://user-images.githubusercontent.com/14944095/206180337-a02bfae6-9371-4e5c-af15-363ae712bbad.png)

So if I have couple of partitions, every time creates not default subpartiotion, but default partition.

Maybe I do something wrong?

**Comment by darold** [comment]
Right, please download and use latest development code I just pushed commit 2b1ddfb7f that fixes that and completely rewrite the way partition and sub-partition are renamed. The PREFIX_PARTITION configuration directive have been renamed into RENAME_PARTITION.
