### ISSUE TITLE
Ora2Pg: Default subpartition migration error

### ISSUE THREAD

**Issue by elexus** [darold/ora2pg#1568]
Hi, Darold.
You said, that you fixed our problem, but it's still there:
The problem not is in naming of partitions and subpartitions, but in referencing on parent  table. 
For example:
"DEF" is partition of "ABC"
and we create subpartitions "DEF_1", "DEF_2" and "DEF_3" of "DEF"
And when we create default subpartition "DEF_default" it references not "DEF", but "ABC"!!

As the result, we expected to see a lot of partitions, each of them had subpartitions including default, however we got a lot of default partitions of main table, what caused an error.

Previous Issue:
https://github.com/darold/ora2pg/issues/1562

Here is the code-source and migrated code:

![image](https://user-images.githubusercontent.com/14944095/207024520-d82804ee-d182-4435-8297-82f0408ea231.png)

migrated to

![image](https://user-images.githubusercontent.com/14944095/207024939-0bc527d5-5b7e-4507-adca-c17452c0aa6e.png)

**Comment by darold** [comment]
Hi, if you want me to solve such issue, I need to be able to reproduce and screenshot doesn't really help. What I need is a copy/paste DDL to be able to create the objects in Oracle quickly, if I have to write a use case by myself there is chance that I will never do that. As you see with the response delay time is a huge problem for me. Thanks for your understanding.
