### ISSUE TITLE
DBD::Oracle::db prepare failed: ORA-00972:

### ISSUE THREAD

**Issue by ntlis** [darold/ora2pg#157]
Hi,

I am getting errors like:

`DBD::Oracle::db prepare failed: ORA-00972: identifier is too long (DBD ERROR: error possibly near <*> indicator at char 14 in 'SELECT * FROM <*>"self->{tables}{<table_name>}{owner}"."<table_name>" WHERE 1=0') [for Statement "SELECT * FROM "self->{tables}{<table_name>}{owner}"."<table_name>" WHERE 1=0"] at /usr/share/perl5/vendor_perl/Ora2Pg.pm line 1826.
Can't prepare statement: ORA-00972: identifier is too long (DBD ERROR: error possibly near <*> indicator at char 14 in 'SELECT * FROM <*>"self->{tables}{<table_name>}{owner}"."<table_name>" WHERE 1=0') at /usr/share/perl5/vendor_perl/Ora2Pg.pm line 1828.`

(https://github.com/darold/ora2pg/blob/master/lib/Ora2Pg.pm#L1818)
$realview = "\"self->{tables}{$view}{owner}\".\"$realview\"";

is missing a $ character.

Cheers,
Sirko

**Comment by darold** [comment]
Thanks for the report Sirko, last commit a5cfa05  fix that typo.

Cheers,

**Comment by ntlis** [comment]
Thank you for the quick turn around! :D
