### ISSUE TITLE
Ora2Pg bug: incompleteness in Grant type migration - grant usage on schema

### ISSUE THREAD

**Issue by elexus** [darold/ora2pg#1570]
While migrating privileges from Oracle to PosgreSQL loses 1 needed component in inheritance rights tree:
In Oracle there is no concept of "GRANT USAGE ON SCHEMA", but PostrgeSQL has this concept.
I think, that once Ora2Pg grants any privileges on tables in any schema, it should also grant usage of that schema.
This functionality works with granting privileges on packages (in postgre they become schemas), but doesn't work with tables.

Oracle code:
![image](https://user-images.githubusercontent.com/14944095/207088489-971b9d35-d1f1-47fa-80b0-3f223432bc67.png)

PosgreSQL code:
![image](https://user-images.githubusercontent.com/14944095/207088625-c2b6733c-6f58-4e0f-bfb3-1397b4219e4a.png)

PosgreSQL code should be like:
![image](https://user-images.githubusercontent.com/14944095/207090807-29d30e62-0eea-48ba-88c5-3a9a26f74658.png)

**Comment by darold** [comment]
Fixed in commit 128e709.
