### ISSUE TITLE
Error migrating float from Oracle to float8 in PostGre

### ISSUE THREAD

**Issue by helenaadi** [darold/ora2pg#1579]
Hello, 

We used ora2pg tool to migrate our database. 
We noticed a problem with the data in the source / target database. 
Oracle : 
RESULT
---------
value FLOAT 

PostGre
RESULT
---------
value float8 

When we launch this request (we the squirrel tool and also with a c# executable) we have the following results : 
select value from result; 

Oracle 
----------
0.5786113328013453
Postgre
----------
0.5786113328013452

Do you know how we can avoid this behavior ? 

Thank you for your help

**Comment by darold** [comment]
You can not avoid this behavior, if you need the exact value you should use numeric at PostgreSQL side. For example set:
```
DATA_TYPE    float:numeric
```
normally PG will stores the value as it has been exported from Oracle.
