### ISSUE TITLE
command line extra tables

### ISSUE THREAD

**Issue by ntlis** [darold/ora2pg#158]
Hi,

if I specify the table/views via command line switches -a --view_as_table ora2pg creates sql for extra unwanted talbes e.g.:

`ora2pg -c ora2pg.conf --view_as_table TOPO_CLIFFS_2500 -a 'VIEW[TOPO_CLIFFS_2500]' -t TABLE
[========================>] 3/3 tables (100.0%) end of scanning.                    
[========================>] 4/4 tables (100.0%) end of table export.          
-- Generated by Ora2Pg, the Oracle database Schema converter, version 16.2
-- Copyright 2000-2016 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:sid=sdb1prod

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE TABLE dummy (
	info char(77)
) ;

CREATE TABLE topo_cliffs_2500 (
	ufi bigint NOT NULL,
	sub_class varchar(50),
	name varchar(100),
	placename_id varchar(10),
	scale bigint,
	reliability_date timestamp,
	accuracy_horizontal varchar(20),
	accuracy_vertical varchar(20),
	source varchar(50),
	geometry geometry(LINESTRINGZ,4283)
) ;

CREATE TABLE tenure_reference_type (
	tenure_type varchar(4) NOT NULL,
	tenure_description varchar(100)
) ;
ALTER TABLE tenure_reference_type ADD PRIMARY KEY (tenure_type);

CREATE TABLE mscatalog (
	tablename char(32),
	entitynum bigint,
	screenform char(64),
	reporttable char(64),
	sqlreview char(240),
	fencefilter char(240),
	dastable char(32),
	formtable char(64)
) ;
`

If I specify the the view with ALLOW and VIEW_AS_TABLE in the ora2pg.conf all works as expected. e.g.:

`ora2pg -c ora2pg.conf  -t TABLE
[========================>] 0/0 tables (100.0%) end of scanning.
[========================>] 1/1 tables (100.0%) end of table export.      
-- Generated by Ora2Pg, the Oracle database Schema converter, version 16.2
-- Copyright 2000-2016 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:sid=sdb1prod

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE TABLE topo_cliffs_2500 (
	ufi bigint NOT NULL,
	sub_class varchar(50),
	name varchar(100),
	placename_id varchar(10),
	scale bigint,
	reliability_date timestamp,
	accuracy_horizontal varchar(20),
	accuracy_vertical varchar(20),
	source varchar(50),
	geometry geometry(LINESTRINGZ,4283)
) ;`

Also is there way to send the  '-t TALBE' create statement directly to the the PG db, I have the PG connections details in the ora2pg.conf and '-t COPY' is copying directly to the PG db?

Cheers,
Sirko

**Comment by ntlis** [comment]
It looks like the extra tables are the tables that are owned by the oracle users.

**Comment by darold** [comment]
When you use --view_as_table your views are converted as tables when using the TABLE action (-t). Here you need the following command line:

    ora2pg -c ora2pg.conf --view_as_table TOPO_CLIFFS_2500 -a 'TABLE[TOPO_CLIFFS_2500]' -t TABLE

You can not import the DDL directly into PostgreSQL, only data can be sent directly to PostgreSQL.

**Comment by ntlis** [comment]
Thank you for the clarification piping the output to psql works fine too.
