### ISSUE TITLE
Export table structure (without constraints, indexes, PK, FK)

### ISSUE THREAD

**Issue by tayalarun1** [darold/ora2pg#1582]
Hello Darold,

Hope you are doing good.
I have got a task to migrate big of Oracle 19c database to PostgreSQL. According to my experience with Oracle, if we do import of data to a table with just the structure (without constraints, indexes, PK, FK), importing is faster as compared to table with all constraints, etc.

Is there a way in Ora2pg, I export table structure in a file & all others (constraints, indexes, PK, FK) in separate file? I will import the structure then data & then all others (constraints, indexes, PK, FK). This will help me to reduce the manual work of dropping all these before the importing of data & then adding after data import is complete.

Thanks
Arun

**Comment by darold** [comment]
Yes, you just have to enable FILE_PER_CONSTRAINT, FILE_PER_INDEX and FILE_PER_FKEYS
