### ISSUE TITLE
Not able to generate schema.

### ISSUE THREAD

**Issue by chetan2211** [darold/ora2pg#1583]
Hi all,
When I'm trying to generate schema( table structure from oracle for postgres) I'm getting following error and we are unable to resolve it.

D:\ora2pg-23.0>ora2pg -t table -c ora2pg_hrd_section.dist -l hrd_section_table_export.log -o hrd_section_schema.sql

Can't locate Ora2Pg.pm in @INC (you may need to install the Ora2Pg module) (@INC contains: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at /c/Strawberry/perl/site/bin/ora2pg line 27.
BEGIN failed--compilation aborted at /c/Strawberry/perl/site/bin/ora2pg line 27.

Please can you provide the solution for that?. I'm using windows 10 OS 
Thank you in advance.

**Comment by tayalarun1** [comment]
I am not using Windows 10, but I am using Windows server with Ora2pg v23.2.
I searched my Ora2pg folder & I found Ora2Pg.pm in "c:\ora2pg\blib\lib" & "c:\ora2pg\lib" folders. For me its not an issue.
