### ISSUE TITLE
Oracle triggers issue

### ISSUE THREAD

**Issue by tayalarun1** [darold/ora2pg#1585]
Hello Darold,

I have a trigger in Oracle which gets migrated to PostgreSQL via Ora2pg v23.2 as below:

**Migrated code**
```
CREATE TRIGGER update_lotqty
	AFTER INSERT OR UPDATE  OR DELETE OF qty ON mms_lotitem FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_update_lotqty();

```	

**Migration should be like this**
```
CREATE TRIGGER update_lotqty
	AFTER INSERT OR DELETE OR UPDATE OF qty ON mms_lotitem FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_update_lotqty();

```

Update are on columns and delete are not on columns. Hence it should be "update of" instead of "delete of"

If you can incorporate the change in  next release, would be helpful.

Thanks
Arun

**Comment by darold** [comment]
Commit d03a1fa fixes this issue.
