### ISSUE TITLE
progress bar error

### ISSUE THREAD

**Issue by ntlis** [darold/ora2pg#159]
I see errors like this:

`ora2pg -c ora2pg.conf --view_as_table TOPO_CONTOURS_25000 -a 'VIEW[TOPO_CONTOURS_25000]' -e 'TABLE[*]' -t COPY -j4 -J4
[========================>] 0/0 tables (100.0%) end of scanning.
PROGRESS BAR ERROR (unrecognized line sent to pipe): TABLE EXPORT IN PROGESS: TOPO_CONTOURS_25000, start: 1454913777, rows 
[========================>] 1233746/1233746 rows (100.0%) Table TOPO_CONTOURS_25000 (1454917799 sec., 0 recs/sec)
[========================>] 1233746/0 rows (100.0%) on total estimated data (0 recs/sec)                         
[========================>] 1233746/0 rows (100.0%) on total estimated data (4022 sec., avg: 306 tuples/sec)`

looks like the the number of rows does not get passed on to the progress bar. All the data copying works fine, I can live with this very minor error. 

Cheers,
Sirko

**Comment by ntlis** [comment]
Looks like _table_info() does not work with views.

**Comment by darold** [comment]
Fixed in last release 17.0.
