### ISSUE TITLE
view_as_table bug

### ISSUE THREAD

**Issue by jeromegallinari** [darold/ora2pg#160]
I found an issue in ora2pg v16.1 when trying to export an Oracle view as a table.
The issue is also present in v16.2 as far as I can see.

The command I use is:

ora2pg --type COPY --namespace RATING_DB --out 2_data.sql --basedir rating_db --conf /etc/ora2pg/ora2pg.conf --exclude "ft_rated_cdr" --view_as_table "rt_error_cdr_country"

[========================>] 0/0 tables (100.0%) end of scanning.
DBD::Oracle::db prepare failed: ORA-00972: identifier is too long (DBD ERROR: error possibly near <*> indicator at char 14 in 'SELECT * FROM <*>"self->{tables}{RT_ERROR_CDR_COUNTRY}{owner}"."RT_ERROR_CDR_COUNTRY" WHERE 1=0') [for Statement "SELECT * FROM "self->{tables}{RT_ERROR_CDR_COUNTRY}{owner}"."RT_ERROR_CDR_COUNTRY" WHERE 1=0"] at /home/jerome/perl5/lib/perl5/Ora2Pg.pm line 1812.
Can't prepare statement: ORA-00972: identifier is too long (DBD ERROR: error possibly near <*> indicator at char 14 in 'SELECT * FROM <*>"self->{tables}{RT_ERROR_CDR_COUNTRY}{owner}"."RT_ERROR_CDR_COUNTRY" WHERE 1=0') at /home/jerome/perl5/lib/perl5/Ora2Pg.pm line 1814.
DBD::Oracle::db prepare failed: ORA-00936: missing expression (DBD ERROR: error possibly near <*> indicator at char 8 in 'SELECT  <*>FROM "RATING_DB"."RT_ERROR_CDR_COUNTRY" a') [for Statement "SELECT  FROM "RATING_DB"."RT_ERROR_CDR_COUNTRY" a"] at /home/jerome/perl5/lib/perl5/Ora2Pg.pm line 9872.
FATAL: ORA-00936: missing expression (DBD ERROR: error possibly near <*> indicator at char 8 in 'SELECT  <*>FROM "RATING_DB"."RT_ERROR_CDR_COUNTRY" a')
Aborting export...

The line in question (1812) is:

$realview = "\"self->{tables}{$view}{owner}\".\"$realview\"";

and the problem is: there is a dollar sign missing before self.

Regards,
jerome

**Comment by darold** [comment]
Hi Jerome,

Thanks for the report, this bug has been reported in issue #157 and fix with commit a5cfa05. Please uprade to latest develpment code.

Best regards,
