### ISSUE TITLE
Sequences referenced as indexes in grants.sql

### ISSUE THREAD

**Issue by EParisot** [darold/ora2pg#1604]
Hi !
First let me thank you for this awesome tool, really usefull !
I just had 2 issues with my grant.sql : 

First, it added users creation lines on top of file, it breaks the migration flow because they already exists... 
This is a minor issue, I just commented the corresponding lines...

Second problem is I found 3 blocs corresponding to INDEXES instead of SEQUENCES :

```sql
ALTER INDEX table1.rubric_pk_seq OWNER TO user1;
GRANT ALL ON  table1.rubric_pk_seq TO user1;
REVOKE ALL ON table1.rubric_pk_seq FROM PUBLIC;
GRANT SELECT ON table1.rubric_pk_seq TO user1;
```

I had to update it by hand. I ansolutely dont know why it happened...

Again thanks for this excellent tool !

**Comment by darold** [comment]
Hi,

This problem might have been fixed, I can not reproduce the issue. Here the kind of result I have with current code:
```
-- Set priviledge on SEQUENCE EMPLOYEES_SEQ
ALTER SEQUENCE hr.employees_seq OWNER TO hr;
GRANT ALL ON SEQUENCE hr.employees_seq TO hr;
REVOKE ALL ON SEQUENCE hr.employees_seq FROM PUBLIC;
GRANT SELECT ON SEQUENCE hr.employees_seq TO scott;
```
