### ISSUE TITLE
--blob_to_lo option apply lo_from_bytea(0, decode( twice when importing data

### ISSUE THREAD

**Issue by EParisot** [darold/ora2pg#1607]
Hi, I'm facing an issue with --blob_to_lo option.

I need to migrate blobs from Oracle to PG, and got errors stating that "l" is not a valid hex value... of course it is not !

When I look at the logs I see:

```
INSERT INTO MY_TABLE (pk,resource_version,description,file_name,data_lob,fk_doc_resource,status,version,create_user,modify_user,create_date,modify_date) VALUES (?,?,?,?,lo_from_bytea(0, decode(?, 'hex')),?,?,?,?,?,?,?)17439,5,E'v0.42',E'PSTL7070-Content.jrxml',lo_from_bytea(0, decode(E'6c6f5 ....
```

It seems to me that the transformation is applyed twice...

I tryed to comment lines 9267, 9268, 9269 and 9271 in Ora2Pg.pm in order to have VALUES (?, ?, ?, ?, ?) value1, value2, ..., lo_from_bytea(0, decode(E'6c6f5...

but then I got values directly without the (?, ?, ?, ?...), and got another error...

Some help please ?

**Comment by darold** [comment]
I'm not able to reproduce this issue with latest development code, if you can try it and still have the issue please post your 
ora2pg.conf file.

About your second fix, commit 6bbf29c allow use of --blob_to_lo with --init_project to have ora2pg command in script export_schema.sh using this option.

**Comment by EParisot** [comment]
Great thank I'll look at it next month !

**Comment by EParisot** [comment]
Well I installed the 24 version but still had to edit scripts to avoid the `ERROR:  invalid hexadecimal digit: "l"`

**Comment by darold** [comment]
Right, I forgot to change the the generation of the import_all.sh script too, commit 24a23ca should fix that.

**Comment by EParisot** [comment]
Ok I cloned the repo again but still got a different but related error: 

`ERROR:  invalid hexadecimal digit: "'"`
