### ISSUE TITLE
EXCLUDE table does not exclude table from TABLESPACE

### ISSUE THREAD

**Issue by EParisot** [darold/ora2pg#1608]
I needed to exclude a table from export, so `EXCLUDE MY_TABLE_NAME`, but this table is still exported in TABLESPACE.
So crash on TABLESPACE export

**Comment by darold** [comment]
It works with latest development code, I think the problem is that you are using global allow/exclude definition which will only filter on tablespace name. Use something like that to exclude on table:
```
EXCLUDE    TABLE[EMPLOYEES]
```
or at command line:
```
ora2pg -c config/ora2pg.conf -t TABLESPACE -b tmp -e "TABLE[EMPLOYEES]
```
