### ISSUE TITLE
Set schema search path again before copying data directly

### ISSUE THREAD

**Issue by SebAlbert** [darold/ora2pg#161]
Direct insertion with pg connection does not work with non-default schema. After some debugging, I found that although the schema search path is set in the first place, the actual copying happens on a new pg connection, without setting the search path again.

**Comment by darold** [comment]
Hi,

I'm not able to reproduce this issue. What version of Ora2Pg are you using and have you enabled  the EXPORT_SCHEMA configuration directive ? What is your ora2pg command line ?

**Comment by SebAlbert** [comment]
It's version 16.1, I have set export_schema to 1, schema (for oracle) is set, create_schema 0, compile_schema 0, pg_schema is set, and pg_dsn and pg_user are set, as well as some allow_tables.

Command line then was
ora2pg -c configfile -t COPY
or
ora2pg -c configfile -t INSERT

Both don't work and tell they can't find the tables in postgres although they exist.
It's important (for reproduction) that the target tables do not exist in the default schema (e.g. public), but only in the pg_schema specified.

As I said, it looks like the search_path is being set at first (in  _get_sql_data, line 4543 in current code), but the actual COPYing then happens on a new connection (in _dump_to_pg, line 10323 in current code)

**Comment by darold** [comment]
Ok, I had not tested with a different schema in PG_SCHEMA but now it is done and completed with success. Here the command passed to PostgreSQL by ora2pg by setting log_min_duration to 0:

```
2016-02-11 23:43:04 CET [31047]: [1-1]  LOG:  statement: SET client_encoding TO 'UTF8';
2016-02-11 23:43:04 CET [31047]: [2-1]  LOG:  statement: SET synchronous_commit TO off
2016-02-11 23:43:04 CET [31047]: [3-1]  LOG:  statement: SET search_path = hr1;
2016-02-11 23:43:04 CET [31043]: [4-1]  LOG: statement:  COPY table_test_1 (id,lbl) FROM STDIN
```
The ora2pg command was:

    ora2pg -c config/ora2pg.conf -t COPY -a TABLE_TEST_1 -j 2

This work in single and in multi process. Please use latest developement code from github and give it a try. I you still have the same issue, please report the ora2pg output.

**Comment by SebAlbert** [comment]
Sorry, I couldn't get back to this earlier. It's indeed working with the latest version; I also ran into issues with different perl installs on the same machine. Cheers!
