### ISSUE TITLE
Question: Is it possible to use a different/arbitrary DBI driver for ora2pg?

### ISSUE THREAD

**Issue by stoeffu** [darold/ora2pg#1616]
I successfully migrated Oracle databases to PostgreSQL by using ora2pg, a great tool!
I also have Ingres databases to migrate and I wonder if it's possible to use DBD::Ingres for this.
How is the metadata (table, field etc. information) read out from the source database?
If this is done by using higher level functions (not RDBMS/Oracle specific), it should possible to use ora2pg for different RDBMS types, isn't it?
If someone ever tried this, a short feedback would be great!

**Comment by darold** [comment]
Hi,

Ora2Pg supports database migration from Oracle, MySQL, SQL Server and coming soon Informix using the corresponding DBI Perl drivers. Ingres is not supported yet and unfortunately this is not just a question of changing the Perl DBD module. There is lot of adaptation to write, if your company need it you can sponsor this development. 

Regards,

**Comment by stoeffu** [comment]
Hi Gilles Darold,
thank you for your reply and yes, I can imagine that it needs a lot of customizing for each database type.
Regards
