### ISSUE TITLE
Is the DELETE option available from the command line?

### ISSUE THREAD

**Issue by ryanewtaylor** [darold/ora2pg#1625]
I have a use case where we're automating monthly migrations of tables and table data. The data we select to export and subsequently delete during import is dynamically driven/requires user input. 

We've created a PowerShell script that applies the appropriate command line options to supplement and/or override an existing ora2pg.conf file for many options, but it doesn't appear that there is a command line for selective DELETE.

Is select DELETE only available within the config file or is there a command line option for it?

**Comment by darold** [comment]
Commit f1e7e3b adds the `--delete` command line option to be able to dynamically set the DELETE clause. It works just like the `--where` clause.
