### ISSUE TITLE
Converts NUMBER(18,2) to double precision

### ISSUE THREAD

**Issue by alexign** [darold/ora2pg#163]
Hello!
I think that Oracle **NUMBER(18,2)** type not equal to Postgres **double precision** type and must convert to Postgres **numeric(18,2)**
Also i think that in general Oracle **NUMBER(s,p)** type must always convert to **numeric(s,p)**

Here is example:
```
postgres=# do $$
postgres$# declare
postgres$# n1 numeric(18,2)=9999999999999998.99;
postgres$# n2 double precision:=9999999999999998.99;
postgres$# begin
postgres$# raise notice '%',(n1+0.01)::numeric(18,2);
postgres$# raise notice '%',(n2+0.01)::double precision;
postgres$# end$$;
NOTICE:  9999999999999999.00
NOTICE:  1e+16
```

**Comment by darold** [comment]
If you want this behaviour, set PG_NUMERIC_TYPE to 0, it will always use decimal(p,s)

**Comment by alexign** [comment]
Oh ! Thanks!

Alex Ignatov




On Thu, Feb 11, 2016 at 9:11 AM -0800, "Darold" <notifications@github.com> wrote:












If you want this behaviour, set PG_NUMERIC_TYPE to 0, it will always use decimal(p,s)
