### ISSUE TITLE
pg_initial_command ignored when using TEST_DATA

### ISSUE THREAD

**Issue by petteja** [darold/ora2pg#1634]
It seems like PG_INITIAL_COMMAND is ignored when using -t TEST_DATA to do data verification between Oracle and PostgreSQL

Added the following to `ora2pg.conf`:
`PG_INITIAL_COMMAND set timezone to 'Europe/Oslo'`

Initially the log says:
`[2023-05-02 13:58:54] DEBUG: executing initial command to PostgreSQL: set timezone to 'Europe/Oslo'  `
But data verification fails with rows showing UTC timezone like  `2020-09-18 12:17:42+00`

**Comment by darold** [comment]
Commit dd092d4 might fix this issue.

**Comment by petteja** [comment]
Thanks! It did.
