### ISSUE TITLE
problem during execution of ora2pg -t TEST -c config/ora2pg.conf > migration_diff.txt -  part 2

### ISSUE THREAD

**Issue by franxav06** [darold/ora2pg#1635]
I have solved the preceding issue, but when I check the report I see that the other objects are not detected in Postgresql
for exemple :
[TEST COLUMNS COUNT]
ORACLEDB:ADOPTION_ALLOWANCES:6
POSTGRES:"fdt-mig-dev".adoption_allowances:0

or 

[TEST INDEXES COUNT]
ORACLEDB:ADOPTION_ALLOWANCES:2
POSTGRES:"fdt-mig-dev".adoption_allowances:0

Those objects are present into the tables
the problem is into function get_schema_condition
that return the following string :
 return " AND lower($attrname) in ('" . join("','", split(/\s*,\s*/, lc($self->{pg_schema}))) . "')";
instead of
return " AND lower($attrname) = quote_ident ('" . join("','", split(/\s*,\s*/, lc($self->{pg_schema}))) . "')";
I test a modification of the code
I keep you informed
Kind regards
Francesco

**Comment by darold** [comment]
Commit c51dd25 might fix this issue.
