### ISSUE TITLE
[Oracle] NOT NULL constraint shows twice in the exported schema

### ISSUE THREAD

**Issue by shubham-yb** [darold/ora2pg#1639]
Hi Team, 
If we have a `not null` constraint on any column in Oracle, the constraint shows up twice. Once in the table definition and once as an `alter table` statement.

Source schema:

```
CREATE TABLE not_null_check (
	id int ,
	first_name VARCHAR(50) not null,
	last_name VARCHAR(50) not null
);

```
Table.sql

```
CREATE TABLE not_null_check (
        id numeric(38),
        first_name varchar(50) NOT NULL,
        last_name varchar(50) NOT NULL
) ;
```
CONSTRAINTS_table.sql

```
ALTER TABLE not_null_check ALTER COLUMN FIRST_NAME SET NOT NULL;
ALTER TABLE not_null_check ALTER COLUMN LAST_NAME SET NOT NULL;

```

I understand that this does not affect the migration in any way. Adding the ticket just in case.

**Comment by darold** [comment]
Yes, this is intentional. The reason is to have the CONSTRAINT_table.sql  file containing all constraints.
