### ISSUE TITLE
not able to generate error free procedure migration from oracle to postgres

### ISSUE THREAD

**Issue by chetan2211** [darold/ora2pg#1640]
ora2pg -t PROCEDURE -c procedure_migratrion.dist -o procedure_migratrion.sql -l procedure_migratrion_log.sql

I used above command and generate all procedure sql file for postgres. But when i run that sql files it gives some error which i have 
to find out manullay and resolve. So is there any other way where i can migrate error free procedure using ora2pg or any other tool.

Thanks in advance.

**Comment by darold** [comment]
Hi @chetan2211, you can have an error free stored procedures migration with Ora2Pg or any other similar tools by using as much possible as standard SQL and compatible statements in your Oracle PL/SQL code, use of the orafce extension in PostgreSQL. Of course this could require rewriting procedures at Oracle side. Choose what you prefer.

**Comment by chetan2211** [comment]
Thank you for the quick response @darold. I’ll do it accordingly and will update once it is done.
