### ISSUE TITLE
When using relative path the generated relative path is relative to the supplied baseDir not the sql file

### ISSUE THREAD

**Issue by ryanewtaylor** [darold/ora2pg#1644]
# Configuration
I have the following directory structure. The `migration_data` template folder was generated by ora2pg.

```text
.ORA2PG_MIGRATION
├───migration_data
│   ├───config
|   │   └───ora2pg.conf
|   ├───data
|   ├───reports
|   ├───schema
|   │   ├───dblinks
|   │   ├───directories
|   │   ├───...
|   └───sources
|       ├───functions
|       ├───mviews
|       ├─── ...
└─── export-raw-data.ps1
```

In my org2pg.config I specify to use relative paths.

```ini
PSQL_RELATIVE_PATH	1
```

# Invocation
I have a custom PowerShell script, `export-raw-data.ps1` that calls ora2pg to create a data.sql file in the `migration_data/data`. My working directory is `ORA2PG_MIGRATION`. The precise invocation is

```powershell
PS C:\dev\ORA2PG_MIGRATION> .\export-raw-data.ps1
Invoking ora2pg...
ora2pg -c 'migration_data\config\ora2pg.conf' -t 'COPY' -o 'data.sql' -a 'MY_TABLE' -b 'migration_data\data'
```

This generates as I would expect `data.sql` and `MY_TABLE_data.sql` files in the `migration_data\data` folder.

```text
.ORA2PG_MIGRATION
├───migration_data
│   ├───config
|   │   └───ora2pg.conf
|   ├───data
|   │   ├───data.sql
|   │   └───MY_TABLE_data.sql
```

# Actual Result

When I inspect data.sql the `\ir command includes the baseDir supplied in the ora2pg call.

```sql
SET search_path = my_schema,public;
BEGIN;
ALTER TABLE MY_TABLE_data DISABLE TRIGGER USER;

\ir 'migration_data\data/MY_TABLE_data.sql'

ALTER TABLE MY_TABLE ENABLE TRIGGER USER;
COMMIT;
```

# Expected Result

I would have expected the relative path to be relative to the sql file, not to the baseDir. That is, I would have expected this.

```sql
SET search_path = my_schema,public;
BEGIN;
ALTER TABLE MY_TABLE_data DISABLE TRIGGER USER;

\ir 'MY_TABLE_data.sql'

ALTER TABLE MY_TABLE ENABLE TRIGGER USER;
COMMIT;
```

According to the [PostgreSQL documentation](https://www.postgresql.org/docs/current/app-psql.html)

> The \ir command is similar to \i, but resolves relative file names differently. When executing in interactive mode, the two commands behave identically. However, when invoked from a script, \ir interprets file names relative to the directory in which the script is located, rather than the current working directory.

# Question

How can I instruct ora2pg to generate a path relative to the script location rather than the baseDir provided in the ora2pg command?

**Comment by darold** [comment]
Right, that should be the case, there is a regression here.

**Comment by darold** [comment]
Commit 481787e fixes this issue.
