### ISSUE TITLE
DISABLE_PARTITION is ignored while creating indexes

### ISSUE THREAD

**Issue by pavel-moskotin-db** [darold/ora2pg#1647]
In ora2pg:23.2,
`DISABLE_PARTITION  1`

for table partitioned by range, like 
```
--ORACLE
CREATE TABLE TABLE_A
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TABLE_A" PRIMARY KEY ("ID")
   ) 
  PARTITION BY RANGE ("CREATED_TIMESTAMP") INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
```
data is copied in non-partitioned manner, but PK is unexpectedly converted to
```
-- Postgres
CONSTRAINT "PK_TABLE_A" PRIMARY KEY ("ID", "CREATED_TIMESTAMP")
```

Expectation would be that PK is converted without changes if DISABLE_PARTITION setting is set.

**Comment by darold** [comment]
Thanks for the report, commit 5b5e4f8 fixes this issue.
