### ISSUE TITLE
[Feature Request] Add ON CONFLICT [...] to INSERT statements

### ISSUE THREAD

**Issue by clemensrieder** [darold/ora2pg#1648]
Hi everyone,

I am in the process of exporting a really, really messy Oracle database via your fantastic tool. Unfortunately, the export takes quite some time. Since there is live data written to the database I get incongruencies when I try to add my foreign keys at the end. 

**An example:** _Table1.fk_ is linked to _Table2.pk_. _Table1_ is exported. The user deletes the corresponding _Table2.pk_. It seems there is no CASCADE setting in place. _Table2_ gets exported a bit later. Adding the foreign key constraint after importing the data will tell me that _Table1.fk_ cannot be set because there is no corresponding _Table2.pk_.

PostgreSQL's COPY statement seems somewhat limited to work with errors but I read that the INSERT statement has an ON CONFLICT clause.

It would be super interesting to see this clause implemented in the ora2pg.conf options. Although it is slower it would help a lot in importing such data. As of now, I will write a short Python script adding the clause to each statement 🙂 

What's your thought on that?

**Comment by darold** [comment]
Hi,

If I understand well, you are asking for a possibility to add an `ON CONFLICT DO NOTHING` clause at end of the insert?

**Comment by clemensrieder** [comment]
Thank you for your quick answer! I was thinking about that - yes!

**Comment by darold** [comment]
Commit c6a83c8 adds this feature.
```
    INSERT_ON_CONFLICT
        When enabled this instruct Ora2Pg to add an ON CONFLICT DO NOTHING
        clause to all INSERT statements generated for this type of data
        export.
```
