### ISSUE TITLE
CJK characters are removed from index names

### ISSUE THREAD

**Issue by vgwidt** [darold/ora2pg#1649]
CJK characters such as Japanese are stripped out of index names in the following code:
https://github.com/darold/ora2pg/blob/d03a1faa5f538519e2a71efb9554dea0030b8279/lib/Ora2Pg.pm#L10105

In my case this resulted in duplicate index names because they were originally differentiated using characters that were stripped.  

It looks like it was updated here as part of https://github.com/darold/ora2pg/issues/1299.

**Comment by darold** [comment]
Commit 17399ea removes this line. Please confirm that there is no side effect with index name.

**Comment by vgwidt** [comment]
Works great with the line removed, thanks!
