### ISSUE TITLE
Invalid LICENSE value 'GPLv3' ignored

### ISSUE THREAD

**Issue by rodraen** [darold/ora2pg#1650]
bro help please

[root@ol8_migr ora2pg-master]# perl Makefile.PL
Invalid LICENSE value 'GPLv3' ignored
Generating a Unix-style Makefile
Writing Makefile for Ora2Pg
Invalid LICENSE value 'GPLv3' ignored
Writing MYMETA.yml and MYMETA.json

**Comment by darold** [comment]
Commit 992b2a1 fixes this issue.
