### ISSUE TITLE
need document on list of partitions being supported in Ora2pg Ver 23.2/24.0 and other inputs

### ISSUE THREAD

**Issue by bharanisvng** [darold/ora2pg#1654]
Team
Can you please provide me
a) need document on list of partitions being supported in Ora2pg Ver 23.2
b) need document on list of partitions being supported in Ora2pg Ver 24.0
c) Do ora2pg Ver 23.2 Support PostgreSQL Ver 15.0
d) Do ora2pg Ver 24.0 Support PostgreSQL Ver 15.0
e) any known partitioning limitations w.r.to postgreSQL ver 14.0/Ver 15.0

**Comment by darold** [comment]
Ora2Pg exports all partitioning that is supported by PostgreSQL (range, list and hash) and yes, PostgreSQL version 15 is supported. For the last question there is no limitations.
