### ISSUE TITLE
REGEXP functions conversion with PG_VERSION 15

### ISSUE THREAD

**Issue by ElenaLopatskaya** [darold/ora2pg#1656]
Hi Darold,

At first, many thanks for developing such incredibly helpful migration tool!

I have a question regarding new REGEXP functions added in PostgreSQL 15 such as REGEXP_LIKE, REGEXP_SUBSTR. It means that these functions could be just moved as is from Oracle into PG 15..
But Ora2Pg still converts them via REGEXP_MATCH even if I set PG_VERSION 15 in config file. 

Would it be possible to tune Ora2Pg to not apply any conversion for this syntax when migrating to PG 15?

Best regards,
Elena

**Comment by okbob** [comment]
pá 14. 7. 2023 v 11:16 odesílatel ElenaLopatskaya ***@***.***>
napsal:

> Hi Darold,
>
> At first, many thanks for developing such incredibly helpful migration
> tool!
>
> I have a question regarding new REGEXP functions added in PostgreSQL 15
> such as REGEXP_LIKE, REGEXP_SUBSTR. It means that these functions could be
> just moved as is from Oracle into PG 15..
> But Ora2Pg still converts them via REGEXP_MATCH even if I set PG_VERSION
> 15 in config file.
>
> Would it be possible to tune Ora2Pg to not apply any conversion for this
> syntax when migrating to PG 15?
>
Attention - Postgres's REGEXP_LIKE and REGEXP_SUBSTR are not fully
compatible with Oracle,

**Comment by darold** [comment]
Hi Elena,

@okbob is right the PostgreSQL implementation is not 100% equivalent to the Oracle function, this is why there is still the replacement with regexp_match() even if PG15 have the same functions. If you want the exact same behavior for these regexp_* functions you should use the Orafce extension and enable USE_ORAFCE in ora2pg.conf. The function will be kept untouched by Ora2Pg.
