### ISSUE TITLE
Error when using insert statement in the input file

### ISSUE THREAD

**Issue by shiny55** [darold/ora2pg#1657]
Hi, 
I'm trying to convert input file with oracle queries to postgresql output file. I was able to get table queries by using type as TABLE. but could not convert Insert or Alter queries to respective postgresql.

<img width="520" alt="image" src="https://github.com/darold/ora2pg/assets/139561577/68894457-9b97-4bf1-a201-789c455d59da">

Can you please let me know what all objects can be used with input file option and also which will be the best option to use, input file or connecting to Oracle database to migrate complete data to Postgresql database.

**Comment by darold** [comment]
Any query, SELECT or INSERT statements should be parsed using the `-t QUERY` option but parsing INSERT from Ora2Pg should not be parsed correctly, it really depends of the values in the statement.
