### ISSUE TITLE
ENABLE_BLOB_EXPORT 0 doesn't increase speed

### ISSUE THREAD

**Issue by afalszowski** [darold/ora2pg#1658]
Hello,
I have a problem with the paramater ENABLE_BLOB_EXPORT. I set it to 0 (deactivated blob export) for a table which contains 6.000.000 rows and a blob column. With activated blob export the migration speed is at 70 rows/sec, which means, that migrating the table takes up to 30 hours. To save some time I thought I can disable the blob export (I don't really need the data in this column, because the data can be easily regenerated by the backend) and then the migration speed will be at the level of tables without blob columns, which is at nearly 6000 rows/sec.

Where do I have a mistake? Could someone of you help me? I can provide you more config parameters if you need.

Thank you for your help!

Adrian

**Comment by darold** [comment]
Hi Adrian, can you limit the export to this table and run ora2pg with the `-d` option to have debug output. It should show the Oracle query used to export data from this table. If ENABLE_BLOB_EXPORT is disabled the BLOB column should not appears in the target column list. Can you confirm?

**Comment by afalszowski** [comment]
Hi,

unfortunately the query contains the column: 
`DEGUG: Query sent to Oracle: SELECT [...],"FT_ABSTRACT",[...] FROM "DB_BACKUP"."TABLENAME" a`

But I saw that the column is not BLOB, but CLOB. Does it also work for CLOB types?

**Comment by darold** [comment]
Hi,

No it only works for BLOB but I have just pushed commit f568072 that will help you:
```
    Add ENABLE_CLOB_EXPORT configuration directive to have the same behavior
    as ENABLE_BLOB_EXPORT but with CLOB. Thanks to afalszowski for the feature
    request.
```
So after upgrading to latest development code add this directive to your configuration file and set it to 0.

Please confirm that it gives the appropriate behavior.

**Comment by afalszowski** [comment]
Hi darold,
implementation is working perfectly. CLOBs are exluded now and the migration performance is pretty good now.
Thank you very much for the quick change!

BR
Adrian
