### ISSUE TITLE
MySQL export fails to find tables

### ISSUE THREAD

**Issue by Morthy** [darold/ora2pg#166]
I'm having trouble getting tables in a MySQL database to be seen. The connection works fine, and it finds the database, but always reports that no tables could be found. When connecting with the same credentials in MySQL, the tables are visible.

```
root@translate:~# ora2pg --version
Ora2Pg v16.2

root@translate:~# ora2pg -s "dbi:mysql:host=localhost;dbname=translate" --user translate --password password -t SHOW_SCHEMA
DATABASE mysql
DATABASE translate

root@translate:~# ora2pg -s "dbi:mysql:host=localhost;dbname=translate" --user translate --password password -t SHOW_TABLE
----------------------------------------------------------
Total number of rows: 0

Top 10 of tables sorted by number of rows:
Top 10 of largest tables:

root@translate:~# mysql -h localhost -u translate -ppassword translate -ANBe "SHOW TABLES"
changelog
language
project
project_log
project_tag
user_rights
users
```

output.sql:

```
-- Generated by Ora2Pg, the Oracle database Schema converter, version 16.2
-- Copyright 2000-2016 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:mysql:host=localhost;dbname=translate

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

-- Nothing found of type TABLE
```

Is there anything I can do to find out why it's not recognizing the tables?

**Comment by darold** [comment]
Hi,

Have you set the SCHEMA configuration directive to translate ? The DSN should be:

    dbi:mysql:host=localhost;database=translate

to allow ora2pg to automatically detect the database/schema name. This is a bug solves in last development code but if you set the SCHEMA directive it should works.

Let me know if that's solves your issue.

Regards

**Comment by Morthy** [comment]
Setting the SCHEMA to translate fixed the issue, thank you for your quick help!
