### ISSUE TITLE
first row of file supplied to -a is skipped

### ISSUE THREAD

**Issue by johnrtian** [darold/ora2pg#1660]
When I supply a file containing a list of table names as the `-a` parameter, the first row of this file appears to be skipped by ora2pg. Have seen this behavior 3 ways so far:
* COPY: table name on first row is neither scanned nor copied
* SHOW_TABLE: table name on first row is not shown
* SHOW_TABLE: if I add a blank first row, all tables show as expected

Is this just a formatting mistake on my part? I didn't see explicit directions for how that file should look.

**Comment by darold** [comment]
Thanks, commit 1828391 fixes this issue.
