### ISSUE TITLE
Issues faced with ms sql server connectivity

### ISSUE THREAD

**Issue by SaravananNewt** [darold/ora2pg#1663]
Team, Ora2Pg version 24.0 is functioning correctly for Oracle connectivity. However, we have encountered connectivity issues when attempting to connect to MS SQL Server. 
[ver_1_0_mssqlserver-knowhow_with-ora2pg240.docx](https://github.com/darold/ora2pg/files/12312805/ver_1_0_mssqlserver-knowhow_with-ora2pg240.docx)

**Comment by bharanisvng** [comment]
Darold - per earlier issue suggestion , downloaded ora2pg ver 24.0 (dev version) and had followed readme instruction.
Can you help us in rectifying the error.

**Comment by darold** [comment]
In your /etc/odbcinst.ini file replace section
```
[ODBC Driver 18 for SQL Server]
```
by
```
[msodbcsql18]
```
it must correspond to what you use as the DSN driver value: `driver=msodbcsql18;server=...`

**Comment by SaravananNewt** [comment]
Team 
Please provide the solution for the error i have encountered 
[mssqlserver-postgres.docx](https://github.com/darold/ora2pg/files/12319633/mssqlserver-postgres.docx)

**Comment by darold** [comment]
Your file /etc/ofbc.ini should be empty, the definition are in /etc/odbcinst.ini

Also what is the purpose of `\SQLEXPRESS` after the server ip address? You should only have `host=xxx.xxx.xxx.xxx`

**Comment by SaravananNewt** [comment]
Team - Changes are made as per your suggestion, still facing some issue
[V_ _3 for mssqlserver with ora2pg24.0.docx](https://github.com/darold/ora2pg/files/12320795/V_._3.for.mssqlserver.with.ora2pg24.0.docx)

**Comment by SaravananNewt** [comment]
Team 
This is the updated file which has some issues in it. Please provide a solution
[V_ _3 for mssqlserver with ora2pg24.0.docx](https://github.com/darold/ora2pg/files/12320959/V_._3.for.mssqlserver.with.ora2pg24.0.docx)

**Comment by SaravananNewt** [comment]
Hi Team,

I hope this message finds you well. I'm writing to follow up on the recent updates made to our GitHub repository. Please the review my problem and provide a solution for the problem

**Comment by SaravananNewt** [comment]
Hi Team,

Please provide a solution for this problem to move further, where we have downloaded and checked the latest update in the community. I have attached the document for your reference
[V__4 for mssqlserver with ora2pg24.0.docx](https://github.com/darold/ora2pg/files/12358309/V__4.for.mssqlserver.with.ora2pg24.0.docx)

**Comment by darold** [comment]
Look like you have not provided the right Ip address or port or it is filtered. I can't help much more on this.
