### ISSUE TITLE
Feature suggestion: DELETE

### ISSUE THREAD

**Issue by SebAlbert** [darold/ora2pg#167]
In the same way that TRUNCATE_TABLE can be used to delete the entire contents of a table, I think it would be neat to have a similar feature (maybe DELETE) that uses the WHERE configuration parameter (or an own parameter that works with the same syntax) to only delete matching entries from the target tables in Postgres before the COPY or INSERT happens. Such a feature would enable regular "updates".

What do you think?

**Comment by darold** [comment]
Hi,

I think it is a good and useful idea. Please give a try to last development code, commit 0001d0c might add this feature. New ora2pg.conf.dist will haver the DELETE configuration directive that works just like the WHERE clause to replace the truncate call. If TRUNCATE is enable and there's no DELETE clause to apply on the table, the truncate will be applied.

Thanks for the feature request.

Best regards,

**Comment by SebAlbert** [comment]
It seems to work, thanks a lot. I appreciate your quick responses!
