### ISSUE TITLE
Can not export full table

### ISSUE THREAD

**Issue by alexign** [darold/ora2pg#168]
<pre>
Hello!
ora2pg version 16.2
I have some error while exporting one table :
CREATE TABLE "*****"."FGROUP" 
   (	"I*" NUMBER(18,0) NOT NULL ENABLE, 
	"VER**ON" NUMBER(15,0), 
	"OBJ**T_NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"BO**" CLOB, 
	"ALGO**THM" VARCHAR2(30 BYTE), 
	"CLAS**AME" VARCHAR2(255 BYTE), 
	"FGROU**EADER_ID" NUMBER(18,0) NOT NULL ENABLE, 
	"FG_VE**ION" NUMBER(18,0) NOT NULL ENABLE, 
	"FG_**TE" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "UQ_FG**UP" UNIQUE ("FGROU**EADER_ID", "FG_VE**ION")
	 CONSTRAINT "PK_FG**UP" PRIMARY KEY ("I*")
	 CONSTRAINT "FK_FG**UP_FGROUPHEADER" FOREIGN KEY ("FGROU**EADER_ID")
	  REFERENCES "*****"."FGROUPHEADER" ("I*") ENABLE
   )
 
After export :
-- oracle
select count(*) from *******.fg***up 
COUNT(*)
----------
       930
-- PG
COUNT(*)
----------
820

Here is the error(object and schema name masked by *):

 

[root@ol7g1 ***_project]# ora2pg --namespace ******* --type COPY -a 'TABLE[FGROUP]' -u system -w oracle -s 'dbi:Oracle:host=localhost;port=1524;sid=***' -o FGROUP_data.sql -l FGROUP_data.log --nls_lang 'AMERICAN_AMERICA.UTF8'

[========================>] 1/1 tables (100.0%) end of scanning.

DBD::Oracle::db prepare failed: ORA-24338: statement handle not executed (DBD ERROR: OCIAttrGet OCI_ATTR_PARAM_COUNT) [for Statement "SELECT DISTINCT OBJECT_NAME,OWNER FROM DBA_OBJECTS WHERE OBJECT_TYPE='TYPE' AND OBJECT_NAME='TIMESTAMP(6)' AND GENERATED='N'AND OWNER='*******'  ORDER BY OBJECT_NAME"] at /root/perl5/lib/perl5/Ora2Pg.pm line 8029.

DBD::Oracle::db prepare failed: ORA-01002: fetch out of sequence (DBD ERROR: OCIStmtExecute/Describe) [for Statement "SELECT DISTINCT OBJECT_NAME,OWNER FROM DBA_OBJECTS WHERE OBJECT_TYPE='TYPE' AND OBJECT_NAME='TIMESTAMP(6)' AND GENERATED='N'AND OWNER='*******'  ORDER BY OBJECT_NAME"] at /root/perl5/lib/perl5/Ora2Pg.pm line 8029.

DBD::Oracle::db disconnect failed: ORA-01013: user requested cancel of current operation (DBD ERROR: OCISessionEnd) at /root/perl5/lib/perl5/Ora2Pg.pm line 9643.

Aborting export...

DBD::Oracle::st execute failed: ORA-03113: end-of-file on communication channel

Process ID: 26524

Session ID: 249 Serial number: 50833 (DBD ERROR: OCIStmtExecute) [for Statement "SELECT DISTINCT OBJECT_NAME,OWNER FROM DBA_OBJECTS WHERE OBJECT_TYPE='TYPE' AND OBJECT_NAME='TIMESTAMP(6)' AND GENERATED='N'AND OWNER='*******'  ORDER BY OBJECT_NAME"] at /root/perl5/lib/perl5/Ora2Pg.pm line 8030.

DBD::Oracle::db prepare failed: ORA-03113: end-of-file on communication channel

Process ID: 26524

Session ID: 249 Serial number: 50833 (DBD ERROR: OCIStmtExecute/Describe) [for Statement "SELECT DISTINCT OBJECT_NAME,OWNER FROM DBA_OBJECTS WHERE OBJECT_TYPE='TYPE' AND OBJECT_NAME='TIMESTAMP(6)' AND GENERATED='N'AND OWNER='*******'  ORDER BY OBJECT_NAME"] at /root/perl5/lib/perl5/Ora2Pg.pm line 8029.

Aborting export...

Aborting export...

DBD::Oracle::db disconnect failed: ORA-03113: end-of-file on communication channel

Process ID: 0

Session ID: 249 Serial number: 50833 (DBD ERROR: OCISessionEnd) at /root/perl5/lib/perl5/Ora2Pg.pm line 9643.

Aborting export...

DBD::Oracle::st fetch failed: ORA-12152: TNS:unable to send break message (DBD ERROR: OCIStmtFetch) [for Statement "SELECT DISTINCT OBJECT_NAME,OWNER FROM DBA_OBJECTS WHERE OBJECT_TYPE='TYPE' AND OBJECT_NAME='TIMESTAMP(6)' AND GENERATED='N'AND OWNER='*******'  ORDER BY OBJECT_NAME"] at /root/perl5/lib/perl5/Ora2Pg.pm line 8034.

[========================>] 444/105 rows (422.9%) Table FGROUP (1 sec., 444 recs/sec)

[>                        ]    /114 rows (0.0%) Table FGROUP (1456399230 sec., 0 recs/sec)

[>                        ]    /122 rows (0.0%) Table FGROUP (1456399230 sec., 0 recs/sec)

[>                        ]    /103 rows (0.0%) Table FGROUP (1456399230 sec., 0 recs/sec)

[===========>             ] 444/930 rows (47.7%) on total estimated data (0 recs/sec)

[===========>             ] 444/930 rows (47.7%) on total estimated data (5 sec., avg: 88 tuples/sec)

DBD::Oracle::db disconnect failed: ORA-03135: connection lost contact

Process ID: 0

Session ID: 249 Serial number: 50833 (DBD ERROR: OCISessionEnd) at /root/perl5/lib/perl5/Ora2Pg.pm line 4750.

 

 
 </pre>

**Comment by darold** [comment]
What is your Oracle database version and are you using latest development code from github?

**Comment by darold** [comment]
If the error still occurs with latest code, please try again with NO_LOB_LOCATOR to 1 and LONGREADLEN to a high enough value to not trigger a LONGTRUNCOK error.

**Comment by darold** [comment]
Any feedback on this issue ?

**Comment by alexign** [comment]
We cant get stable repeating results with this issue. We thought that parallel extraction is the issue but it is not. We need to  get more statistics on this issue. I think you can close this issue for a while =)!
Thank you!

Alex Ignatov
Postgres Professional: http://www.postgrespro.com
Russian Postgres Company

**Comment by darold** [comment]
Hi Alex,

Issue 171 also report the same error and we were able to find the responsible code. Commit 8e56899 might fix the issue.

Best regards,

**Comment by alexign** [comment]
Oh, good! Shall try on a week!!! Thank you!

Alex Ignatov
Postgres Professional: http://www.postgrespro.com
Russian Postgres Company
