### ISSUE TITLE
ora2pg -c ora2pg.conf -t COPY -a tablename not working

### ISSUE THREAD

**Issue by 210981** [darold/ora2pg#1683]
Further updated to the below Post. Shortly question: 
- Saving data to file using the following Command is fine: 
ora2pg -c ora2pg.conf -t COPY -o data.sql schema/data/
- Direct copy data from Oracle to Postgres doesn't work(command: ora2pg -c ora2pg.conf -t COPY -a tablename). Everything Else works fine. Connection to Oracle and Postgres using DBD::Pg, DBD::Oracle are set correctly.

do i have to completely delete the Ora2pg and install it again!? or some other softaware running on the computer have prevented this transfer's process.

or Do you know the root cause of that?
Thanks
Hans

================
Hello Friends,

i have an very strange issue that i have tried to fix in hours but couldn't solve it. Could you please help me this case:

I have installed ora2pg to migrate oracle table to postgres, everything was working fine for several projects before
recently i started a new project to migrate tables from oracle to postgres again in the same computer, and i did the same process as the previous projects.
But when i copy the data from oracle table to postgres tabe by  following command, it doesn't work properly:
ora2pg -c ora2pg.conf -t COPY -a tablename
no data have been transfered to postgres. it shows: 0/0 tables(100%) end of scanning.
- connection to both database is correct.
- The tables are existing on source and on target( structure table )...
- i can create table structure from this config file

I have tried to fix it, but it didn't work, here are what i did:

- try to install ora2pg again -> not work
- try to transfer others tables -> have the same issue
- try to install ora2pg on other computer -> everything works fine
- Only one case when i transfered data to one specific table, it works but only some rows not all are transfered and not exactly what i want to transfer. Maybe this data is stored on the Cache memory not really from the source table...
Here ist my config file:
ORACLE_HOME          C:\Oracle\product\12.2.0\client_1

ORACLE_DSN  dbi:Oracle:host=xxx;sid=xx;port=1521

ORACLE_USER            system

ORACLE_PWD  xxx

SCHEMA                      Schemaname

ALLOW   TZV_DATA

TYPE                TABLE

PG_DSN                      dbi:Pg:dbname=xxxx;host=xxx;port=5432

PG_USER                     schemaname

PG_PWD                      xxx

LOG_ON_ERROR                    1

STOP_ON_ERROR                   0 

could you please recommend me the possible causes of this? it is possible, that perl does't work properly or in this computer has some other software running, which prevent this transfer....?. or something else that I really dont understand what happended

Thank you for you help in advance

**Comment by darold** [comment]
Your option `-a tablename` might not correspond to an existing table on Oracle or on PostgreSQL but if you don't have any error message then it doesn't exist on Oracle side.
