### ISSUE TITLE
export schema to differently named database

### ISSUE THREAD

**Issue by sttachoires** [darold/ora2pg#169]
Hi Gilles,

I'm trying to export Oracle schema AIRCOM in database FTEC01D to PostgreSQL schema aircomaf of database aircomaf. And things are not what I expected :(

./import_all.sh -d ${PGDB} -h ${PGHOST} -n aircomaf -o ${PGUSER} -U ${PGUSER} -s -I
Database owner aircomaf already exists, skipping creation.
Would you like to drop the database aircomaf before recreate it? [y/N/q] 
Would you like to create schema aircomaf in database aircomaf? [y/N/q] y
Running: psql -h lh-paircomaf01-db -U aircomaf -d aircomaf -c "CREATE SCHEMA aircomaf;"
CREATE SCHEMA
Would you like to change search_path of the database owner? [y/N/q] y
Running: psql -h lh-paircomaf01-db -U aircomaf -d aircomaf -c "ALTER ROLE miguser SET search_path TO aircomaf,public;"
ERROR:  role "miguser" does not exist
ERROR: can not change search_path.

Here is the ora2pg I used [ora2pg.zip](https://github.com/darold/ora2pg/files/150929/ora2pg.zip)

**Comment by darold** [comment]
Last commit 4d7d393 might fix this issue. Thanks Stephane.

**Comment by sttachoires** [comment]
Yes it do!
Thanks
