### ISSUE TITLE
Function JSON_ARRAYAGG does not get translated properly

### ISSUE THREAD

**Issue by shubham-yb** [darold/ora2pg#1692]
Hi Team,

The Oracle function `JSON_ARRAYAGG` is not supported by PG and Ora2pg dumps it as is. PG equivalent of this function is the `JSON_AGG` function. Can we please add this function mapping. 

Thank You for your help!

**Comment by darold** [comment]
The json_arrayagg() function is supported in PG 16, I have no plan to support the translation of this function for older version. Sorry.
