### ISSUE TITLE
name of a column is a reserved word in postgresql

### ISSUE THREAD

**Issue by didmicang** [darold/ora2pg#1693]
When migrating from Oracle to PostgreSQL with ora2pg v24.1 , I have the following problem :    
CREATE TABLE gestion_couleur (
	couleur_pas bigint NOT NULL,
	couleur_pas_correctif bigint NOT NULL,
	derniere_couleur varchar(10) NOT NULL,
	**offset** bigint NOT NULL,									<---- Reserved word 
	delta_minimal bigint NOT NULL
) ;
How to fix the problem ?

**Comment by faqsarg** [comment]
I had the same problem with a 'desc' column. I think this problem is beyond the scope of ora2pg.
I think you should fix it manually before performing the migration. If it is a possibility, modify the name of that column in your Oracle db.

**Comment by darold** [comment]
You should enable USE_RESERVED_WORDS in ora2pg.conf, the column will be double quoted in ora2pg export.

**Comment by darold** [comment]
I agree with @faqsarg that renaming the column could be a better solution otherwise each time you will use this column you will need to add double quote.
