### ISSUE TITLE
bad table creation operator

### ISSUE THREAD

**Issue by tbw777** [darold/ora2pg#1696]
FDW_output.sql:

```
-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.1
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: <hidden>

CREATE FOREIGN  TABLE  (
) SERVER  OPTIONS( table '', readonly 'true');
```

![image](https://github.com/darold/ora2pg/assets/15821889/8bef9ecd-779e-4238-b26d-9390d5399259)

> [42601] ERROR: syntax error at or near "("

All other CREATE blocks has equal syntax errors

**Comment by darold** [comment]
Hi, I'm not able to reproduce the problem with Oracle export. Are you using latest development code and can you tell me which RDBMS is the source database?

**Comment by tbw777** [comment]
I'm using latest version in docker image named as georgmoser/ora2pg

**Comment by darold** [comment]
Not reproducible without docker I guess the issue is related to docker execution of ora2pg.
