### ISSUE TITLE
There is no control for default values

### ISSUE THREAD

**Issue by tbw777** [darold/ora2pg#1697]
Can't change current_timestamp to now() and there is no control for default values (TYPE SECTION is useful, but not support this).

**Comment by darold** [comment]
Why do you want to replace current_timestamp by now()? This is the same. But if you want to do so this is pretty easy using a system command:
```
grep -rl current_timestamp schema/ | xargs -i perl -p -i -e 's/current_timestamp/now()/g' {}
```

Can you also elaborate more about "control for default values"?  What are you thinking about exactly?

**Comment by tbw777** [comment]
because now() is shortest form and used by liquibase
>What are you thinking about exactly?
I mean that can't change current_timestamp to now() in config
