### ISSUE TITLE
Invalid timestamp format conversion

### ISSUE THREAD

**Issue by tbw777** [darold/ora2pg#1698]
TIMESTAMP(3) type converted to TIMESTAMP on default DATA TYPES section in config instead direct TIMESTAMP(3)

**Comment by darold** [comment]
Which RDBMS are you using ? Oracle, MSSQL or MySQL?

**Comment by tbw777** [comment]
Oracle

**Comment by darold** [comment]
Commit c589700 fixes this issue.
