### ISSUE TITLE
add_months coversion

### ISSUE THREAD

**Issue by alexign** [darold/ora2pg#170]
Hello!
add_months(sysdate, - LEVEL+1) converted to 
LOCALTIMESTAMP               + - LEVEL + 1 * '1 month'::interval
but it should be
LOCALTIMESTAMP               + (- LEVEL + 1) * '1 month'::interval
lost parenthesis around  - LEVEL+1

version 16.2

**Comment by darold** [comment]
Thanks for the report. It might be fixed in commit a91304d.

Best regards,
