### ISSUE TITLE
is this tools supports mysql 8 default authentication as I want to migrate database from mysql v8 to postgres

### ISSUE THREAD

**Issue by Anilj2ee7** [darold/ora2pg#1700]
is this tools supports mysql 8 default authentication as I want to migrate database from mysql v8 to postgres

**Comment by darold** [comment]
I'm doing the Ora2Pg development on mysql v8.0.34, so I guess that it is supported.

**Comment by Anilj2ee7** [comment]
Thanks for confirming darold
