### ISSUE TITLE
SQL queries selecting NEXVAL from the sequence in the trigger are not translated

### ISSUE THREAD

**Issue by JosefMachytkaNetApp** [darold/ora2pg#1701]
Hello, I have a problem with ora2pg tool when I try to migrate app from Oracle to PostgreSQL. Original app in Oracle uses triggers to generate NEXTVAL for ID columns. Trigger function and creation of trigger are translated into pl/pgsql but the select from the sequence itself is untouched. I presume it could be by design, but is there some workaround for it?

Here is an example how it looks like in export file:
```
DROP TRIGGER IF EXISTS "...." ON "..." CASCADE;
CREATE OR REPLACE FUNCTION "trigger_....."() RETURNS trigger AS $BODY$
BEGIN
    SELECT ".....".NEXTVAL INTO STRICT NEW."ID";
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER "...."
        BEFORE INSERT ON "...." FOR EACH ROW
        EXECUTE PROCEDURE "trigger_...."();
```
Trigger is in PostgreSQL successfully created but of course fails when runs. Can I configure ora2pg to make it translate these selects from sequences into proper PostgreSQL version?

Thank you very much.

**Comment by JosefMachytkaNetApp** [comment]
Never mind, I found some other way.

**Comment by samueldc** [comment]
Hi @JosefMachytkaNetApp, I'm having the same problem, I think. Sequences are created, but I'm missing the alter column instructions to set default value to nextval. Have you workarounded that?

**Comment by darold** [comment]
There is a dedicated action for that : SEQUENCE_VALUES

`ora2pg -c config/ora2pg.conf -t sequence_values -o sequence_values.sql`
