### ISSUE TITLE
DROP_FKEY happens even during --oracle_speed, when >1 table

### ISSUE THREAD

**Issue by johnrtian** [darold/ora2pg#1702]
I'm on ora2pg v24.1.

I don't have a consequence-free PG environment to test this against so I don't know the true scope, but if I specify:
* `-t COPY` and `--oracle_speed`
* \>1 table via `-a`, either as a list or a file
*  invalid `--pg_dsn`
* `DROP_FKEY 1` in the config
 
I get the following error:
```
[2023-10-16 10:01:55] [========================>] 2/2 tables (100.0%) end of scanning.                                               
Can't call method "do" on an undefined value at /usr/local/share/perl5/Ora2Pg.pm line 9082.                                          
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle DEV at /usr/local/share/perl5/Ora2Pg.pm line 9081.
```

For v24.1, line 9082 is in the drop_fkey loop: [#9082](https://github.com/darold/ora2pg/blob/f1e3f2660959244b97577bece982f91ef8e5fdb4/lib/Ora2Pg.pm#L9082)

This doesn't happen when only specifying a single table via `-a`.

Seems undesirable for FKs to be dropped in PG when using `--oracle_speed` only.

**Comment by darold** [comment]
Commit 7d95e23 should fix this issue. Please confirm.

**Comment by johnrtian** [comment]
Unfortunately, I don't have the means to test a specific build at the moment, and I'm not particularly familiar with Perl. But those changes seem reasonable to me. Thank you!
