### ISSUE TITLE
error message : Unmatched ( in regex; marked by <-- HERE in m/\bg_grsamt(

### ISSUE THREAD

**Issue by bharanisvng** [darold/ora2pg#1703]
We are currently facing issue in running an " alpha" 
schema while exporting Package using Ora2Pg ver 24.0 in standalone. 

Below command fails in Linux,
ora2pg -c /var/lib/ora2pg/ora2pg-20.0/ora2pg.conf -s dbi:Oracle:host=".????? ; sid=?? ;port=1521" -u alphabeta -w '????' -n ALPHA -t PACKAGE
 
Unmatched ( in regex; marked by <-- HERE in m/\bg_grsamt( <-- HERE 20,\b/ at /usr/local/share/perl5/Ora2Pg.pm line 18937.
 
**But interesting part is, it is working in Windows.**  
it is one of the oracle package .

if you able to share your preferred email-id, i shall submit the package code

**Comment by bharanisvng** [comment]
Good morning.
Darold - Can you please share your preferred email-id, i shall submit the package code

**Comment by bharanisvng** [comment]
on 26-oct-2023, i have sent email to you on the problematic package . pl note,  using ora2pg ver 24.0, same package is working in Windows without any issues.
 issue exists with ora2pg ver 24.0 using linux based.

**Comment by darold** [comment]
Hi,

I have imported your package and exported it using ora2pg without any issue. You should upgrade to latest development code or v24.1 the problem might have already been fixed.
