### ISSUE TITLE
Ora2pg Migration assessment using sql file

### ISSUE THREAD

**Issue by mgole001** [darold/ora2pg#1709]
Hi 

Is there a way to do the migration assessment via Ora2PG without connecting to the source Oracle database?

I have the sql file extracted from the Oracle database (containing procedures, functions, other ddls etc), I want to generate the assessment report in html (show report, estimation) using this sql file as input.

Thanks

**Comment by darold** [comment]
Yes, import the DDL into a local Oracle database then connect Ora2pg to this local database.

**Comment by mgole001** [comment]
Thank you for your response
