### ISSUE TITLE
Encountering error when setting ORACLE_COPIES higher than 2

### ISSUE THREAD

**Issue by pawelbs** [darold/ora2pg#171]
Hello,

At first I want to say, that ora2pg is a great tool, keep up the good work! :)

I'm using:
- ora2pg 16.2
- Oracle 11.2.0.1.0
- Perl v5.18.2

I am, trying to speed up export process by using **ORACLE_COPIES** setting. When I set it to **1** or **2** everything is fine.
However when I set it to anything above **3 - 8**, I get errors for several tables, but not for every table.

The sample error I've got:
<pre> [========================>] 1/1 tables (100.0%) end of scanning.
DBD::Oracle::db prepare failed: ORA-01002: fetch out of sequence (DBD ERROR: OCIStmtExecute/Describe) [for Statement "SELECT DISTINCT OBJECT_NAME,OWNER FROM ALL_OBJECTS WHERE OBJECT_TYPE='TYPE' AND STATUS='VALID' AND OBJECT_NAME='TIMESTAMP(6)' AND GENERATED='N'AND OWNER='****'  ORDER BY OBJECT_NAME"] at /usr/local/share/perl/5.18.2/Ora2Pg.pm line 8029.
FATAL: ORA-01002: fetch out of sequence (DBD ERROR: OCIStmtExecute/Describe)
DBD::Oracle::db prepare failed: ORA-01013: user requested cancel of current operation (DBD ERROR: OCIStmtExecute/Describe) [for Statement "SELECT DISTINCT OBJECT_NAME,OWNER FROM ALL_OBJECTS WHERE OBJECT_TYPE='TYPE' AND STATUS='VALID' AND OBJECT_NAME='TIMESTAMP(6)' AND GENERATED='N'AND OWNER='****'  ORDER BY OBJECT_NAME"] at /usr/local/share/perl/5.18.2/Ora2Pg.pm line 8029.
FATAL: ORA-01013: user requested cancel of current operation (DBD ERROR: OCIStmtExecute/Describe)
DBD::Oracle::db prepare failed: ORA-24338: statement handle not executed (DBD ERROR: OCIAttrGet OCI_ATTR_PARAM_COUNT) [for Statement "SELECT DISTINCT OBJECT_NAME,OWNER FROM ALL_OBJECTS WHERE OBJECT_TYPE='TYPE' AND STATUS='VALID' AND OBJECT_NAME='TIMESTAMP(6)' AND GENERATED='N'AND OWNER='****'  ORDER BY OBJECT_NAME"] at /usr/local/share/perl/5.18.2/Ora2Pg.pm line 8029.
FATAL: ORA-24338: statement handle not executed (DBD ERROR: OCIAttrGet OCI_ATTR_PARAM_COUNT)
Aborting export...
DBD::Oracle::db disconnect failed: ORA-03113: end-of-file on communication channel
Process ID: 0
Session ID: 221 Serial number: 5172 (DBD ERROR: OCISessionEnd) at /usr/local/share/perl/5.18.2/Ora2Pg.pm line 9643.
Aborting export...</pre>

Do you have any hints, how could I solve this problem?

The other error I've noticed is when using **REPLACE_QUERY** and **ORACLE_COPIES** > 1 (I needed to add **ORDER BY ID** to a SQL query).

I get:
<pre>DBD::Oracle::st execute failed: called with 1 bind variables when 0 are needed [for Statement "SELECT * FROM ***** order by id"] at /usr/local/share/perl/5.18.2/Ora2Pg.pm line 9944.
FATAL: called with 1 bind variables when 0 are needed</pre>

Is it possible to use both settings?

Thanks in advance for your reply.

**Comment by darold** [comment]
Thanks for the report. Please use latest development code from github, last commit 8e56899 is an attempt to fix this issue. If you still have the same error, please execute ora2pg in debug mode and post here the output related to the error and the custom type search. 

Best regards,

**Comment by pawelbs** [comment]
Thank you for lightning-quick response! :) 
Your commit fixed the first error, now there are no "fetch out of sequence" errors and the export is much, much quicker.

I'm still getting the second error though. 
Here are the significant settings from the ora2pg.conf file:
<pre>
ORACLE_COPIES 2
ALLOW ****   #  - I am allowing only one table
REPLACE_QUERY ****[SELECT * FROM **** order by id]
</pre>

And here is the debug mode:
<pre>
Ora2Pg version: 17.1
Trying to connect to database: dbi:Oracle:host=****
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
Retrieving table information...
[1] Scanning table **** (158363 rows)...
Trying to connect to database: dbi:Oracle:host=****
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
Retrieving partitions information...
Dumping data from **** to file: ****ora2pg_output/****_output.sql
Written 276 bytes to ****ora2pg_output/****_output.sql
Looking how to retrieve data from ****...
Creating new connection to database to extract data...
DEBUG: cloning Oracle database connection.
Creating new connection to database to extract data...
DEBUG: cloning Oracle database connection.
Fetching all data from **** tuples...
DBD::Oracle::st execute failed: called with 1 bind variables when 0 are needed [for Statement "SELECT * FROM **** order by id"] at /usr/local/share/perl/5.18.2/Ora2Pg.pm line 10212.
FATAL: called with 1 bind variables when 0 are needed
Fetching all data from **** tuples...
DBD::Oracle::st execute failed: called with 1 bind variables when 0 are needed [for Statement "SELECT * FROM **** order by id"] at /usr/local/share/perl/5.18.2/Ora2Pg.pm line 10212.
FATAL: called with 1 bind variables when 0 are needed
Aborting export...
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(HOST=localhost)(PROTOCOL=tcp)(PORT=5555))(CONNECT_DATA=(SID=orcl))) at /usr/local/share/perl/5.18.2/Ora2Pg.pm line 9898.
Aborting export...
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(HOST=localhost)(PROTOCOL=tcp)(PORT=5555))(CONNECT_DATA=(SID=orcl))) at /usr/local/share/perl/5.18.2/Ora2Pg.pm line 9898.
DBD::Oracle::db disconnect failed: ORA-03113: end-of-file on communication channel
Process ID: 0
Session ID: 223 Serial number: 16568 (DBD ERROR: OCISessionEnd) at /usr/local/share/perl/5.18.2/Ora2Pg.pm line 4807.
Trying to connect to database: dbi:Oracle:host=localhost;sid=orcl;port=5555
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
Restarting sequences
</pre>

With ORACLE_COPIES 1 and with REPLACE_QUERY setting it works fine.
It also works fine without REPLACE_QUERY and with ORACLE_COPIES > 0 (but I need to use REPLACE_QUERY)

One more small glitch: after upgrade ora2pg started to look for ora2pg.conf file in /etc/ instead of /etc/ora2pg/. Had to launch ora2pg --conf /etc/ora2pg/ora2pg.conf option. Or did I do something wrong?

**Comment by darold** [comment]
Sorry I forgot the second issue with REPLACE_QUERY. Want you are expecting was not possible, the query defined in REPLACE_QUERY overwrite all other extraction query that can be defined internally in Ora2Pg. I'm agree that should not be the case with ORACLE_COPIES. Please upgrade to latest development code, commit 4ac7faa fix that issue.

An other commit fca0526 also fixes the issue on the default place to search for ora2pg.conf. Thanks for the report.

**Comment by pawelbs** [comment]
I've just tested it - looks like it's working like charm now! Thank you again!

**Comment by pawelbs** [comment]
I have just tried following SQL and it worked:

REPLACE_QUERY ****[SELECT * FROM (SELECT * FROM **** ORDER BY id)]

**Comment by pawelbs** [comment]
Hello, 
I've made some tests - it's not working as I hoped it would.
What I wanted to achieve is COPY/INSERT statements ordered by id in the generated file, but because of  ORACLE_COPIES the order is kept, but only among the subgroups of every thread (ABS(MOD(id, 8)) = N).
So for now I will have to skip multithreading for this table.

**Comment by darold** [comment]
Yes, it will not work like you want using multiprocess. I don't know why you want to do that but what you can do is "clusterize" the table after the import provide that you have an index on column id.

    CLUSTER table_name USING index_name;

I think this is the better solution for what you want to do.

Regards,

**Comment by pawelbs** [comment]
I have a situation a table has a ID column and a PARENT_ID column which refers to ID.  
That's why I needed the data to be inserted in a given order. 

But I thought of even simpler solution. I drop the constraint on PARENT_ID column, insert all the data and recreate the constraint. Therefore I can use ORACLE_COPIES without having to care about ordering the data.

I think this issue can be closed now. I really appreciate your help. Thank you!

**Comment by darold** [comment]
Oh ok, if you want to import data at full speed you have to import triggers, indexes and constraints after data import. There is an action, LOAD, that will allow you to parallelize the indexes and constraints import. Ora2Pg can also help you if you already have imported foreign keys and/or triggers, if you activate DROP_FKEY and DISABLE_TRIGGERS, they will be dropped and disabled before data import and recreated or enabled after data import.
