### ISSUE TITLE
Enhance DATA_EXPORT_ORDER with custom order of Tables.

### ISSUE THREAD

**Issue by dcgadmin** [darold/ora2pg#1710]
First a huge thanks for Awesome tool that is continuously getting enrich with new features.

One kind request to enhance below config
DATA_EXPORT_ORDER

Currently it only support based on Size/name, it would great to provide custom order or Source query that provide the order in which we would want to load.
It can be useful to accelerate Data load further.

**Comment by darold** [comment]
Commit fae6268 adds this feature.
```
Allow DATA_EXPORT_ORDER to take a filename at value to be able to give a custom table order.
The file must contain the ordered list of the tables. One table per line in upper case for Oracle. 
```
