### ISSUE TITLE
Unwanted NOT NULL constraint

### ISSUE THREAD

**Issue by fljdin** [darold/ora2pg#1711]
Hi Gilles,

Ora2Pg version: v24.1

When I use a `REPLACE_COLS` directive, I've got a partial support for my column renaming on the `NOT NULL` constraint statement. Given the following Oracle table:

```sql
CREATE TABLE "TEST" (
  "TEST_ID" NUMBER(22) PRIMARY KEY,
  "IS_ACTIVE" VARCHAR(1) DEFAULT 'N' NOT NULL 
);
```

```ini
# config/ora2pg.conf
REPLACE_COLS   TEST(TEST_ID:ID) TEST(IS_ACTIVE:ACTIVE)
```

```sh
ora2pg -c config/ora2pg.conf -t TABLE -a TEST -b schema/tables -o tables.sql
```

```sql
-- schema/tables/table.sql
CREATE TABLE test (
        id numeric(22) NOT NULL,
        active varchar(1) NOT NULL DEFAULT 'N'
) ;
ALTER TABLE test ADD PRIMARY KEY (id);
ALTER TABLE test ALTER COLUMN is_active SET NOT NULL;
```

The  `PRIMARY KEY` constraint statement is defined on renamed column, but `NOT NULL` is not.
As `NOT NULL` is already defined in `CREATE TABLE` statement, is the `ALTER COLUMN SET NOT NULL` statement necessary?

Regards, Florent

**Comment by darold** [comment]
Commit 69593ca fixes this issue.
