### ISSUE TITLE
Error in tempfile() using /tmp/tmp_ora2pgXXXXXX: Could not create temp file /tmp/tmp_ora2pg4CEPen: Too many open files at /usr/share/perl5/vendor_perl/Ora2Pg.pm line 8711

### ISSUE THREAD

**Issue by jcetchri** [darold/ora2pg#1713]
Hello
I am using Oa2Pg v15.1 on CentOS release 6.5  to extract date from a table of size 28 Go records 263 073 912. 
Ora2Pg begin well but i get an error where the output reach to 2,9 Go. 
The error is : "Error in tempfile() using /tmp/tmp_ora2pgXXXXXX: Could not create temp file /tmp/tmp_ora2pg4CEPen: Too many open files at /usr/share/perl5/vendor_perl/Ora2Pg.pm line 8711"

Any Help ?
JC

**Comment by darold** [comment]
This is not reproducible in my environment. When you have such error you should temporarily increase the limit to, for example, 2,048 files, with the command `ulimit -n 2048` and give another try.
