### ISSUE TITLE
Assessment report via ora2pg

### ISSUE THREAD

**Issue by mgole001** [darold/ora2pg#1714]
Hi,

I am trying to find out what and how to infer the cost of migration from the assessment report
For eg if the assessment report shows 
Stored Procedure - Number =10, Estimated costs =80

What does this mean?
Does it mean the schema that was assessed has 10 stored procedures and the total estimated cost to migrate these 10 stored procedures would be 80 estimated unit (each unit is 5 mins, total 400 mins effort) ? If I see all these 10 stored procedures noted in "details", does this mean all 10 stored procedures have to be reviewed and manually rewritten/refactored and ora2pg cannot automatically convert these stored procedures to postgresql compatibility?

Also sometimes I see table object also showing some estimated cost in the report like eg 1 estimated cost (even if there are no check constraint issues etc and details is blank), what does this 1 estimated cost signify? 

Where can I get details if a stored procedure or any other object like functions, views etc would be automatically converted to PGSQL format or specific stored procedures/objects would need manual refactoring 

Thanks

**Comment by mgole001** [comment]
Hi Darold/Team

Please review above query and would appreciate some guidance. Thanks.

**Comment by darold** [comment]
> Does it mean the schema that was assessed has 10 stored procedures and the total estimated cost to migrate these 10 stored procedures would be 80 estimated unit (each unit is 5 mins, total 400 mins effort) ? 

Yes

> If I see all these 10 stored procedures noted in "details", does this mean all 10 stored procedures have to be reviewed and manually rewritten/refactored and ora2pg cannot automatically convert these stored procedures to postgresql compatibility?

No, it doesn't mean that it must be rewritten. You have the details of the difficulties found in the procedures in the details.

 > Also sometimes I see table object also showing some estimated cost in the report like eg 1 estimated cost (even if there are no check constraint issues etc and details is blank), what does this 1 estimated cost signify?

You must see cost as a weight, the sum of the cost gives an idea of the migration effort. Let's say you can migrate everything automatically, the migration cost can not be 0, there are import time and tests.

 > Where can I get details if a stored procedure or any other object like functions, views etc would be automatically converted to PGSQL format or specific stored procedures/objects would need manual refactoring

At end of the report you have the difficulties found per stored procedure, triggers and view.
