### ISSUE TITLE
Schema for Default partition is not dumped while using the RENAME_PARTITION 

### ISSUE THREAD

**Issue by priyanshi-yb** [darold/ora2pg#1715]
Hi Team,

The schema of the default partition in MySQL is not getting generated with the latest and when I used this commit f08d47a4e5c20ff7d348e535ed05ab571b4bb350, it is getting dumped. 

Example schema of MySQL -
```
CREATE TABLE range_columns_partition_test (
    a INT,
    b INT
)
PARTITION BY RANGE COLUMNS(a, b) (
    PARTITION p0 VALUES LESS THAN (5, 5),
    PARTITION p1 VALUES LESS THAN (MAXVALUE, MAXVALUE)
);
```
Schema dumped with this commit f08d47a4e5c20ff7d348e535ed05ab571b4bb350 -
```
CREATE TABLE range_columns_partition_test (
	a integer,
	b integer
) PARTITION BY RANGE (a, b) ;

CREATE TABLE range_columns_partition_test_p0 PARTITION OF range_columns_partition_test
FOR VALUES FROM (MINVALUE,MINVALUE) TO (5,5);
CREATE TABLE range_columns_partition_test_p1 PARTITION OF range_columns_partition_test DEFAULT;
```
However, the schema dumped with the latest is - 
```
CREATE TABLE range_columns_partition_test (
	a integer,
	b integer
) PARTITION BY RANGE (a, b) ;

CREATE TABLE range_columns_partition_test_part1 PARTITION OF range_columns_partition_test
FOR VALUES FROM (MINVALUE,MINVALUE) TO (5,5);
```
Config parameters set are -
```
PREFIX_PARTITION 1
PREFIX_SUBPARTITION 1
```
(Assuming, that I have PREFIX_PARTITION set in the config, the RENAME_PARTITION will be set to 1 with the latest)

Please let me know if I am missing anything. 

Thank you for the help!

CC: @darold

**Comment by darold** [comment]
Commit 6782078 fixes this issue.
