### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by bharanisvng** [darold/ora2pg#1716]
a) W.r.to ora2pg 24.0, with disable_partition=0, do we have the limit of 4 billions rows as the limit and post that the partition logic will trigger
b) assume we have source - oracle- single schema with table count of 40000+ tables with huge size and conversion to target = postgresql ver 14.0 (target as single schema) using ora2pg 24.0, do we have known limitation's  with ora2pg which we should be aware of it. Due to the huge record count and huge # of tables, aware of the partition limitation's w.r.to postgresql ver 14.0
c) Is it possible to migrate data for only specific partition from oracle to postgres

**Comment by darold** [comment]
a) where does this limit to 4 billions rows come from? 
b) the only limitation I see if the time to parse the oracle catalog, but if it is acceptable for you then this is fine. To parallelize a maximum the data export to save time, you should have a lot of cores and memory on the hosts.
c) to only extract some partitions you should use a WHERE clause that uses the corresponding partition to extract.

**Comment by darold** [comment]
Ah ok, I was thinking of an Ora2Pg limitation.

If you want to export data from a particular partition just use the WHERE clause to gather data from this partition.
