### ISSUE TITLE
[NICE2HAVE] line-continuation character for config-file

### ISSUE THREAD

**Issue by nikodemusP** [darold/ora2pg#1718]
If you have many many tables to exclude or to change only one line within the config-file gets a bit confusing. A line-continuation character will be useful

i.e.

EXCLUDE TABLE_1 -
                  TABLE_2 -
                 TABLE_3

thx

**Comment by darold** [comment]
Hi,

You can use as many as EXCLUDE or ALLOW lines you want in the configuration file, they will all be concatenated in a single corresponding list.

Here is the list of ora2pg.conf directives that can be repeated in the configuration file without erasing the previous one:

- TABLES
- ALLOW
- EXCLUDE
- VIEW_AS_TABLE
- LOOK_FORWARD_FUNCTION
- ALLOW_PARTITION
- *_INITIAL_COMMAND
- SYSUSERS
- ORA_RESERVED_WORDS
- MODIFY_STRUCT
- EXCLUDE_COLUMNS
- REPLACE_AS_BOOLEAN

If there are directives that are not in this list and you want it to be used multiple time in ora2Pg.conf, just let me know.
