### ISSUE TITLE
psql:./schema/tables/table.sql:625: ERROR:  syntax error at or near what -- missing comma

### ISSUE THREAD

**Issue by kkettinger** [darold/ora2pg#1721]
After `export_schema.sh`, i'm trying to import the schema into the postgresql database.
It seems for the `table.sql` export, there are missing commas directly before a comment.

See this table for example:
```
CREATE TABLE test(
	proz_id bigint,
	zeitstempel timestamp(0) DEFAULT statement_timestamp()
-- Prozessname,
	what varchar(100),
	elasped bigint,
	add_info varchar(300),
	startstopp smallint DEFAULT 1,
	id bigint NOT NULL
) ;
```
After `statement_timestamp()`, there is a comma missing.

Command with output:
```bash
./import_all.sh -h postgres -s -U postgres -d test -o postgres -y
...
Running: psql --single-transaction  -h postgres -U postgres -d test -f ./schema/tables/table.sql
..
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
psql:./schema/tables/table.sql:614: ERROR:  syntax error at or near ""what""
LINE 5:  what varchar(100),
         ^
ERROR: an error occurs when importing file ./schema/tables/table.sql.
```

Postgres Client Version: `psql (PostgreSQL) 16.1 (Debian 16.1-1.pgdg110+1)`
Postgres Server Version: `psql (PostgreSQL) 16.1 (Debian 16.1-1.pgdg120+1)`
Ora2PG Version: `v24.1`

**Comment by darold** [comment]
It look like you have comment in the Oracle default value for this column. This should be very rare, but I will try to remove them automatically.

**Comment by darold** [comment]
Not reproducible, however this should be a very rare case, there is more priorities, closing.
