### ISSUE TITLE
Option for ALTER TABLE ADD CONSTRAINT being in a separate file

### ISSUE THREAD

**Issue by mgerhardy** [darold/ora2pg#1727]
We are having constraints that go over different schemas, and it's not possible to execute the resulting statements without taking the order into account, and even worse - we have a cycle here. So for us it would be great to get such an option to activate the constraints after all schemas and tables were imported without them before.

**Comment by darold** [comment]
Normally if the configuration directive FILE_PER_CONSTRAINT is set to 1 all constraints will be saved into a dedicated file.

**Comment by mgerhardy** [comment]
thanks - and sorry for the noise
