### ISSUE TITLE
1 instead of clob data

### ISSUE THREAD

**Issue by alexign** [darold/ora2pg#173]
Hello!
converting table with the following command:

`ora2pg --namespace ***** --type COPY -a 'TABLE[***PARAM]' -u system -w *** -s 'dbi:Oracle:host=192.168.***.***;port=1524;sid=***' -o ***PARAM_data.sql -l ***PARAM_data.log -c ora2pg.conf`

While converting with very simple ora2pg.conf:
`NO_LOB_LOCATOR  0`

After conversion I have any clob column  in the data file contains only '1' instead of clob data from oracle.

But with   ora2pg.conf (sorry have clob with length 12657054 =/) :
`LongReadLen 15000000`

clob column  data is ok in the date file after convertion

Thank you in advance!

PS There is no any references in documentation about NO_LOB_LOCATOR parameter is it intentionally ? Only default ora2pg.conf contains info about it =)

**Comment by alexign** [comment]
PPS Also i have one table with one row with clob length = 100001126. 
Dont know how to deal with it without NO_LOB_LOCATOR 0 except using LONGREADLEN= 100001126 and DATA_LIMIT~10-20 to overcome OOM  %)

**Comment by darold** [comment]
Please upgrade to latest development code this issue might have been fixed. The documentation in README file is up-to-date but documentation in web site have not been updated yet.

Disabling NO_LOB_LOCATOR correspond to the previous behavior, you need to set LONGREADLEN to a highest value to be able to extract your LOB not truncated. Enabling this configuration directive will slow down export but will not use LONGREADLEN or just 1MB to extract all LOB data.
