### ISSUE TITLE
Duplicate SQL On Create Trigger

### ISSUE THREAD

**Issue by carenswijaya01** [darold/ora2pg#1731]
Hi, i have an issue with ora2pg 24.1.

here's my ora2pg.conf
```
# ORACLE
ORACLE_DSN       dbi:Oracle:host=$ORACLE_HOST;port=$ORACLE_PORT;service_name=$ORACLE_SERVICE_NAME
ORACLE_USER	     $ORACLE_USERNAME
ORACLE_PWD	     $ORACLE_PASSWORD
SCHEMA           $ORACLE_USERNAME
# POSTGRES
PG_DSN           dbi:Pg:host=$PSQL_HOST;port=$PSQL_PORT;dbname=$PSQL_DB_NAME
PG_USER          $PSQL_USERNAME
PG_PWD           $PSQL_PASSWORD
PG_VERSION       15
CREATE_SCHEMA	   0
PG_SCHEMA        $PSQL_SCHEMA
# EXPORT TYPE
TYPE             TRIGGER
OUTPUT           TRIGGER_output.sql
STOP_ON_ERROR		 0
USE_RESERVED_WORDS	1
NULL_EQUAL_EMPTY	0
USE_ORAFCE	1

```
and some of sql trigger result become like this

```
CREATE TRIGGER my_trig
	BEFORE INSERT ON my_table my_schema.my_table
BEFORE INSERT
ON my_schema.my_table 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
 FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_my_trig();
```

not all of it, but most of it become like that

**Comment by carenswijaya01** [comment]
Another clue, i found it bug because i use referencing clause on oracle's trigger

**Comment by darold** [comment]
Please can you past an example of an Oracle trigger DDL that is failing? You can remove the body of the trigger (between the begin and final end).

**Comment by carenswijaya01** [comment]
> Please can you past an example of an Oracle trigger DDL that is failing? You can remove the body of the trigger (between the begin and final end).

Here my oracle trig
CREATE OR REPLACE TRIGGER SM.TRG_ABSENSI_ONLINE
BEFORE INSERT
ON SM.ABSENSI_ONLINE
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;
BEGIN
....
END TRG_ABSENSI_ONLINE;

And the result on ora2pg
DROP TRIGGER IF EXISTS trg_absensi_online ON absensi_online CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_trg_absensi_online() RETURNS trigger AS $BODY$
DECLARE
tmpVar bigint;
BEGIN
 ....
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_trg_absensi_online() FROM PUBLIC;

CREATE TRIGGER trg_absensi_online
	BEFORE INSERT ON absensi_online TRG_ABSENSI_ONLINE
BEFORE INSERT
ON SM.ABSENSI_ONLINE
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
 FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_trg_absensi_online();

**Comment by darold** [comment]
Commit fb6b0ad fixes this issue.

**Comment by carenswijaya01** [comment]
> Commit [fb6b0ad](https://github.com/darold/ora2pg/commit/fb6b0ad5472582d01e048d64d658300f7fba86d8) fixes this issue.

It still have bug on BEFORE INSERT, not just in FOR EACH ROW
