### ISSUE TITLE
partitioned tables copy statement with wrong name

### ISSUE THREAD

**Issue by mgerhardy** [darold/ora2pg#1732]
there is a table called history.foobar that is partitioned and the PARTITION_NAME is used for copy

suppose partition name is F_P0001 the table and schema name is not included in the copy statement - but only the partition name

`COPY F_P0001 ....`

**Comment by darold** [comment]
The schema is included in the main psql import file. Let's say you have used `-o data.sql` you must import the all tables data files from this main psql script.
