### ISSUE TITLE
Wrong procedure Name Generated

### ISSUE THREAD

**Issue by ladudu** [darold/ora2pg#1733]
My Package names like above
PKG_PRSP0210			<--package name 
--PRSP0221_AXXXXXXXXXXX  <--procedure name 
--AXXXXXXXXXXX	                <--procedure name 
The Ora2Pg Generate SQL file name like AXXXXXXXXXXX.sql，
This resulted in me actually having two procedures, but only one of them was generated.
I tried to create a package for Test，but the results were correct.

**Comment by darold** [comment]
I need the DDL to reproduce, you can remove the body of the procedure between the begin and last end.

**Comment by darold** [comment]
Ok, nested procedure are not supported, this is why the export is wrong. You must fix the nested procedure/function in Oracle prior export with Ora2Pg.

**Comment by ladudu** [comment]
> Ok, nested procedure are not supported, this is why the export is wrong. You must fix the nested procedure/function in Oracle prior export with c.
Thank you for your reply. 

1. Are there plans to support nesting? 
2. Will the package support optional export? There too many project packages , which is very time-consuming.

**Comment by darold** [comment]
> Are there plans to support nesting?
no, not for the moment. This is a huge work, I don't have free time for that.

> Will the package support optional export? There too many project packages , which is very time-consuming.
I don't understand this question. Can you please elaborate more?

**Comment by ladudu** [comment]
I want to export only one package，because it's takes too long to export all packages each time.Sometimes only one package changes.

**Comment by darold** [comment]
Yes, like tables or other export type using `-a "MYPACKAGE"` will only export this package.
