### ISSUE TITLE
Performance penalty doing ora2pg migration in tables with lobs througth WAN 

### ISSUE THREAD

**Issue by ayacopino** [darold/ora2pg#1735]
Hi Darold good morning.

We are using ora2pg to migrate from oracle to postgresql, oracle is in local network, and ora2pg and postgresql are in cloud.
Doing a local migration, we have performance of 200 to 600 rows in tables with lobs.
When doing the same migration throught WAN we have performance of 20rows/s with tables with lobs.
Tables without lobs are not a problem.

1) Can you recommend is there a way to deal with network delay (60ms) with lobs in ora2pg?

2) I have tried ora_fdw but didn't work, I have the error that the source schema can't be found (I have oracle database with schema and tables with uppercase/lowercase combination (with quotes). 
Can ora_fdw can help with this?

3) Can't use primary key, we have a PK with multiple fields with chars. I have tried executing multiple ora2pg at same time, filtering data with date in a field, I have ora2pg of 20rows/sec but this is not enough (108 jobs per 3 tables, 1 job per 5 days, have table of 25 millions rows)

Thanks any feedback will be welcome, and thanks for the tool.

**Comment by darold** [comment]
Maybe you could have more performances by exporting data locally in a PostgreSQL database then generate a dump that can be imported to the cloud. There is no miracle, the bottleneck is the network, maybe a transfer of a single file of a compressed dump could be more performant.

**Comment by ayacopino** [comment]
Hi Darold, yes thanks for the feedback. Yes we are thinking to do that, create local files and then transfer files to the cloud. Thanks.

**Comment by ayacopino** [comment]
Could be the performance much better, if we put ora2pg near the source database (in LAN)?
First tests we have done, it seems 10x faster, remote pg database in WAN and ora2pg near the oracle source database in same LAN network.
Thanks.

**Comment by darold** [comment]
Right, you can also try to parallelize more the ora2pg export to WAN using the `-P` and `-j` options.
