### ISSUE TITLE
Bug from commit cabd72a

### ISSUE THREAD

**Issue by carenswijaya01** [darold/ora2pg#1737]
Got it, commit cabd72a fix this issue with trigger input file.

_Originally posted by @darold in https://github.com/darold/ora2pg/issues/1736#issuecomment-1951868703_

Haha it still bug my friend, the output like this
```
CREATE TRIGGER trg_absensi_online
	BEFORE INSERT ON absensi_online TRG_ABSENSI_ONLINE
BEFORE INSERT
ON SM.ABSENSI_ONLINE
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
 	EXECUTE PROCEDURE trigger_fct_trg_absensi_online();
```

Look at BEFORE INSERT, there are 2 statements. For the FOR EACH ROW glad u fixed it, thanks. But for BEFORE INSERT, it still bug.

Thanks.

**Comment by darold** [comment]
I do not the same issue. Using Oracle code:
```
CREATE OR REPLACE TRIGGER SCHM_NAME.TRG_T_ENVOI
BEFORE INSERT
ON SCHM_NAME.T_ENVOI
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
declare
  v integer;
  json_str varchar2(30);
  mKOD VARCHAR2(128);
begin
  json_str := '{"code": 1}';
  SELECT FIELD_1 into v FROM TEST_TRIGGER;

  mKOD:= substr(:new.nazev,1,instr(:new.nazev,'-',1)-1);
  IF v = 0 then
    return;
  end if;

  SELECT FIELD_1 into v FROM TEST_TRIGGER;
end;
/
```
I have the following output
```
DROP TRIGGER IF EXISTS trg_t_envoi ON schm_name.t_envoi CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_trg_t_envoi() RETURNS trigger AS $BODY$
declare
  v integer;
  json_str varchar(30);
  mKOD varchar(128);
BEGIN
  json_str := '{"code": 1}';
  SELECT FIELD_1 into STRICT v FROM TEST_TRIGGER;

  mKOD:= substr(NEW.nazev,1,position('-' in NEW.nazev)-1);
  IF v = 0 then
    RETURN NEW;
  end if;

  SELECT FIELD_1 into STRICT v FROM TEST_TRIGGER;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER trg_t_envoi
	BEFORE INSERT ON schm_name.t_envoi  REFERENCING NEW AS New OLD AS Old
 FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_trg_t_envoi();
```
which look to be correct for me.

Please post the oracle DDL.

**Comment by darold** [comment]
Sorry got it, I still see the double "BEFORE INSERT" in export from database. I will fix that.

**Comment by darold** [comment]
Then how about commit 394399b ? :-)

**Comment by carenswijaya01** [comment]
> Then how about commit 394399b ? :-)

Wait, i'll check it tomorrow, because i already at home rn :D

**Comment by carenswijaya01** [comment]
> Then how about commit [394399b](https://github.com/darold/ora2pg/commit/394399bca41b98f87949199891112d10ad07be2f) ? :-)

Yup it works perfectly. Thanks darold :D
