### ISSUE TITLE
Section Migration cost assessment

### ISSUE THREAD

**Issue by fabrice636861** [darold/ora2pg#1738]
Hi,
The last line shows the total estimated migration **code** in man-days following the number of migration units estimated for each object
code should not be replaced by cost?
Fabrice

**Comment by darold** [comment]
Can you please show where this typo is present, a screenshot of the report can help if you can not point it in the Perl code.

**Comment by fabrice636861** [comment]
it is part of the documentation
Ora2Pg : Migrates Oracle to PostgreSQL (darold.net)
<https://ora2pg.darold.net/documentation.html#Ora2Pg-usage>

**Comment by darold** [comment]
Commit 271755d fixes that, online documentation will be updated when a new version will be published.
