### ISSUE TITLE
What is the Maximum size of Byeta in PostgreSQL 15

### ISSUE THREAD

**Issue by satam2007** [darold/ora2pg#1739]
What is the Maximum size of Byeta in PostgreSQL 15.

**Comment by darold** [comment]
This is not the right place to ask question about PostgreSQL itself and this question is easily self resolved by a search in Google.
If your question is more what is the maximum BLOB size that is supported during the migration in bytea to PostgreSQL? You should consider that the data need to be escaped in hexa before being insert to the bytea column, which can reduce de PostgreSQL max size for a bytea by 2. Which mean that it must be lower than 500MB.

If you have such huge BLOB you should export them as PostgreSQL large objects, Ora2Pg have the options to perform that.
