### ISSUE TITLE
High load on network interface

### ISSUE THREAD

**Issue by alexign** [darold/ora2pg#174]
Hello once again!
While converting table data with

got high load on network interface while  disk activity on machine with oracle and with ora2pg is near  1% (atop: KiB/r    150  | KiB/w      8  ). 
On machine with oracle got 22% cpu usage on oracle_xxxxx  process.
But network load from atop is 
`si 7807 Kbps  | so 5256 Kbps` on ora2pg machine and symmetrical usage on oracle machine.

While stracing ora2pg process got some strange info:
`
read(14, "\0\0\1\253\6\0\0\0\0\0\6\0\2\246\10\0\0\0\0\0\1\0\0\0\0\0\0\0000\202B\23"..., 8208) = 427
write(14, "\0\0\1\v\6\0\0\0\0\0\3`\363\376\377\377\377\377\377\377\377V\0\0\0\0\0\0\0\0\0\0"..., 267) = 267
read(14, "\0\0\0\371\6\0\0\0\0\0\10\0T\0\1\2\f\0\200\0\1\0\0\0\1\0\0\1\247\343\33\0"..., 8208) = 249
write(14, "\0\0\1\v\6\0\0\0\0\0\3`\364\376\377\377\377\377\377\377\377V\0\0\0\0\0\0\0\0\0\0"..., 267) = 267
read(14, "\0\0\0\371\6\0\0\0\0\0\10\0T\0\1\2\f\0\200\0\1\0\0\0\1\0\0\7\2618-\0"..., 8208) = 249
write(14, "\0\0\0\25\6\0\0\0\0\0\3\5\365\1\0\0\0\1\0\0\0", 21) = 21
read(14, "\0\0\1\254\6\0\0\0\0\0\6\0\2\246\6\0\0\0\0\0\1\0\0\0\0\0\0\0000\202B\23"..., 8208) = 428
write(14, "\0\0\1\v\6\0\0\0\0\0\3`\366\376\377\377\377\377\377\377\377V\0\0\0\0\0\0\0\0\0\0"..., 267) = 267
read(14, "\0\0\0\371\6\0\0\0\0\0\10\0T\0\1\2\f\0\200\0\1\0\0\0\1\0\0\1\247\343\36\0"..., 8208) = 249
write(14, "\0\0\1\v\6\0\0\0\0\0\3`\367\376\377\377\377\377\377\377\377V\0\0\0\0\0\0\0\0\0\0"..., 267) = 267
read(14, "\0\0\0\371\6\0\0\0\0\0\10\0T\0\1\2\f\0\200\0\1\0\0\0\1\0\0\7\2618.\0"..., 8208) = 249
write(14, "\0\0\0\25\6\0\0\0\0\0\3\5\370\1\0\0\0\1\0\0\0", 21) = 21`

Some stat from ora2pg:
` [======================>  ] 491799715/519717765 rows (94.6%) on total estimated data (833 recs/sec)`

Table which is converted is 
`
DO**MENT_ID          NUMBER(15)                             
D**PSTATUS_ID        NUMBER(15)                             
A**ION_NAME          VARCHAR2(64)                           
A**ON_DATA          CLOB          Y                        
O**_DISPSTATUS_ID    NUMBER(15)                             
TA**JOURNAL_ID       NUMBER(15)    Y                        
**                   NUMBER(15)                             
R**ARK               CLOB          Y                        
A**ACH_NAME          VARCHAR2(270) Y                        
P**DISPSTATUS_ID     NUMBER(15)    Y                        
O**_PARDISPSTATUS_ID NUMBER(15)    Y                        
W**K_DATE            DATE          Y  `

`A**ON_DATA    and R**ARK`      column is empty on all rows

ora2pg version is 16.2

**Comment by darold** [comment]
Hum, 833 recs/sec seems really slow if ON_DATA and RARK are really empty. Even without multiprocessing you should be at a higher throughput. The network throughput seems agree with my hypothesis. You can validate it by explicitly not returning the CLOB data with setting:

```
REPLACE_QUERY    TABLENAME[SELECT DO**MENT_ID, D**PSTATUS_ID, A**ION_NAME, 
O**_DISPSTATUS_ID,TA**JOURNAL_ID,A**ACH_NAME,P**DISPSTATUS_ID, O**_PARDISPSTATUS_ID,W**K_DATE FROM TABLENAME]
```

Please adjust the tablename, columns list and name to match your table definition without the CLOB column.

**Comment by alexign** [comment]
Hey without including clob in select it is another story!!!
I dont use LOB_LOCATOR and:

Without emtpy CLOB converting
[postgres@thunder2 tmp]$ ora2pg --namespace azk2015 --type COPY -a 
'TABLE[D**JOURNAL]' -u system -w oracle -s 
'dbi:Oracle:host=192.168.***.***;port=1524;sid=***' -o 
D**JOURNAL_data.sql -l D**JOURNAL_data.log -c ora2pg.conf
[========================>] 1/1 tables (100.0%) end of scanning.
[========================>] 61065505/61065505 rows (100.0%) Table 
DOCJOURNAL (665 sec., 91827 recs/sec)
[========================>] 61065505/61065505 rows (100.0%) on total 
estimated data (22752 recs/sec)
[========================>] 61065505/61065505 rows (100.0%) on total 
estimated data (665 sec., avg: 91827 tuples/sec)
vs
With emtpy CLOB converting
[========================>] 61065505/61065505 rows (100.0%) Table 
DOCJOURNAL (78115 sec., 781 recs/sec)


Without clob extracting is ~100 faster than with it %)!!!

After adding one clob A**ION_DATA in REPLACE_QUERY we have :
[>                        ]   130000/61065505 rows (0.2%) on total 
estimated data (1428 recs/sec) =(

It looks like something really bad happens with  converting  (even 
empty)? clob ( they not null, we  specially empty it with EMPTY_CLOB).
If you have any thoughts about it I can help you with some test or 
coding to resolve this issue.

Again converting LOBs is really pain. it extremly slow. Converting any 
table with CLOB is 2 magnitude slower than table not having it =/.

Thank you in advance and waiting yours considerations!!!

Alex Ignatov
Postgres Professional: http://www.postgrespro.com
The Russian Postgres Company

**Comment by darold** [comment]
Yes table with LOB are really slow because the content need to be escaped (since 17.0 it is converted in hexa), but also because usually this correspond to huge data. I use to export huge table with lob separately using -J parameter to use a maximum of parallelism at oracle and escaping side with a low DATA_LIMIT. For example recently I migrate two tables separately with 1 BLOB and 1 CLOB per table for a total of  380GB and it took 1h40 to complete.I use the following command:

    ora2pg -c ora2pg.conf -t COPY -J 4

And for the 80 other tables without LOB it took only 0h20m using command:

    ora2pg -c ora2pg.conf -t COPY -P 4 -j 3

The PostgreSQL with Ora2Pg virtual server has only 6 vCPU with multithreading and 8 GB of RAM.

About the EMPTY_CLOB() issue I will try to reproduce the issue later tonight.

Regards,

**Comment by darold** [comment]
I've updated the previous note about the server ressources, the same migration on a virtual server with PostgreSQL and Ora2Pg with 8 vCPU and 8 GB of RAM took 1h30 for the 78 tables with no LOB. The command used was:

    ora2pg -c config/ora2pg.conf -t COPY -P 4 -j 2

and the two tables with LOB took 3h20m with command:

    ora2pg -c config/ora2pg.conf.bytea -t COPY -J 4

The more CPUs and RAM you have, the more speed you get.

**Comment by alexign** [comment]
Yeah, using multiple cpu is great option!
And what about  your bytea config?

PS By the way, i profiled ora2pg execution on a last week and found that about 30% of exec time while converting  my test table with clob is escaping that clobs %).

Alex Ignatov
Postgres Professional: http://www.postgrespro.com
Russian Postgres Company

**Comment by darold** [comment]
My bytea config was everything from default configuration file generated by --ini_project and the following:
```
ALLOW    TABLEBYTEA1 TABLEBYTEA2
LONGREADLEN    120000000
BLOB_LIMIT    250
NO_LOB_LOCATOR    1
```
with direct import to PostgreSQL database.

I have done a test with emptying BLOB and BLOB data with the following query:

    UPDATE lob_example SET bindata=EMPTY_BLOB(),chardata=EMPTY_CLOB();

I have all BLOB anc CLOB values exported as NULL and no LOB garbage transfered. I use current development code because previous behavior was to export empty_lob as '\\x'::bytea, but NULL is a better choice.

I think that your CLOB fields are not really empty, have you performed a COMMIT after the UPDATE to emptying CLOB? Oracle is not in autocommit mode like PostgreSQL by default, so perhaps this is the reason of the network throughput, LOB data are still here.

The time wasted to convert BLOB in hexa is unfortunately not an option. I never found a satisfying solution to make this conversion at Oracle side, but worst I think it will be slowest.

**Comment by alexign** [comment]
I think that oci is the issue.
We have some trial java oracle to pg convertor and it is exporting table with clob much faster. About ~100 000/s on  D**JOURNAL table mentioned above.
Also i've tried oracle_fdw on that table. fdw working twice or much times slower than directly taking date from oracle with ora2pg in one thread.
Also found some info in inet about high number of round trip while using clob (with or without locator). That explains high load on network interface:
https://community.oracle.com/thread/2432675?start=0&tstart=0

Working on some tests to prove that oci(or dbd) is the issue when dealing with clobs from perl

**Comment by darold** [comment]
I guess you are using latest development code, there was some major changes on this part. But I do not understand what is slower than what? For oracle_fwd, yes it is definitively not a solution to migrate a high volume of data, but what does your java tool is doing?

Is it possible for you to dump the Oracle table using exp or expdp and send me a link to download it on my private email. Like that I will be able to test and understand what you are trying to bench.

Best regards,

**Comment by alexign** [comment]
Not tested latest code. Only 17.2.  oci based code( dbd in ora2pg and oracle_fdw) is slow on exporting tables with clob, even empty clob. my link about round trip number and my observation on high volume network traffic while exporting even empty lob is 95% proves that  while exporting clob oci driver is very inefficient . Thin Java jdbc driver dosent have that issue at all. Its based on testing ora2pg and this java prog on the same table.  Need some time to prove it and ill definitely test your new code!PS and about table - just try table with one empty clob column and about 100k rows. I have problem even with that on ora2pg and oracle_fdw- extremly slow exporting speed and high network traffic. throughput was 1000 row/s and 7.5 mbits network traffic and high cpu usage on oracle side. With empty clob...PPS ill test ill test yoru latest code but im really surprise about thin jdbc driver speed and  issue with oci %)

Alex Ignatov
Postgres Professional: http://www.postgrespro.com
Russian Postgres Company




On Thu, Apr 14, 2016 at 9:57 AM -0700, "Darold" <notifications@github.com> wrote:












I guess you are using latest development code, there was some major changes on this part. But I do not understand what is slower than what? For oracle_fwd, yes it is definitively not a solution to migrate a high volume of data, but what does your java tool is doing?



Is it possible for you to dump the Oracle table using exp or expdp and send me a link to download it on my private email. Like that I will be able to test and understand what you are trying to bench.



Best regards,

**Comment by darold** [comment]
I have made some tests on my computer this morning with around 100k empty clob. Here is the table:
```
SQL> DESC TESTCLOB
 Nom					   NULL ?   Type
 ----------------------------------------- -------- ----------------------------
 ID						    NUMBER(15)
 CREATE_DATE					    DATE
 DATA						    CLOB
```

When using current development code I get the following result with the query generated internally by Ora2Pg `SELECT "ID",to_char("CREATE_DATE", 'YYYY-MM-DD HH24:MI:SS'),"DATA" FROM "ADM"."TESTCLOB" a; `

```
ora2pg -c config/ora2pg.conf -t COPY -a TESTCLOB -j 6
[========================>] 100592/100592 rows (100.0%) Table TESTCLOB (13 sec., 7737 recs/sec)
ora2pg -c config/ora2pg.conf -t COPY -a TESTCLOB -J 2 -j 2
[========================>] 100592/100592 rows (100.0%) Table TESTCLOB (10 sec., 10059 recs/sec)
```

I modify the code to force Oracle to return NULL instead of empty clob with the followinf query used by Ora2Pg internally: `SELECT "ID",to_char("CREATE_DATE", 'YYYY-MM-DD HH24:MI:SS'),CASE WHEN dbms_lob.compare("DATA", empty_clob() ) = 0 THEN NULL ELSE "DATA" END FROM "ADM"."TESTCLOB" a`. Here the result:

```
ora2pg -c config/ora2pg.conf -t COPY -a TESTCLOB -j 6
[========================>] 100592/100592 rows (100.0%) Table TESTCLOB (12 sec., 8382 recs/sec)
ora2pg -c config/ora2pg.conf -t COPY -a TESTCLOB -J 2 -j 2
[========================>] 100592/100592 rows (100.0%) Table TESTCLOB (10 sec., 10059 recs/sec)
```

Then I modify the query to return NULL for the clob field: `SELECT "ID",to_char("CREATE_DATE", 'YYYY-MM-DD HH24:MI:SS'),NULL FROM "ADM"."TESTCLOB" a` and get these result:

```
ora2pg -c config/ora2pg.conf -t COPY -a TESTCLOB -j 6
[========================>] 100592/100592 rows (100.0%) Table TESTCLOB (4 sec., 25148 recs/sec)
ora2pg -c config/ora2pg.conf -t COPY -a TESTCLOB -J 2 -j 2
[========================>] 100592/100592 rows (100.0%) Table TESTCLOB (3 sec., 33530 recs/sec)
```

**Comment by alexign** [comment]
By the way

speed of dbms_lob.compare("DATA", empty_clob() ) = 0  < speed of 
dbms_lob.getlength|("DATA" ) = 0

compare and getlength return null when clob arg is null.


Example to test throughput of compare and getlength

create table test(id number,c clob);
declare
c clob:=empty_clob();
n number:=0;
begin
for i in 1..1000000
loop
if mod(i, 10) = 0 then
insert into test values (i,null);
else
insert into test values (i,'a');
end if;
end loop;
end;

select count(*) from test where dbms_lob.compare("C", empty_clob()) is null
time:4.021 sec

select count(*) from test where dbms_lob.getlength("C" ) is null
time:1.68 sec


|So I think we need to make such select on ora side:

|SELECT "ID",to_char("CREATE_DATE", 'YYYY-MM-DD HH24:MI:SS'),CASE WHEN 
dbms_lob.*getlengh*("DATA" ) = 0 THEN NULL ELSE "DATA" END FROM 
"ADM"."TESTCLOB" (but i think that to_char timing  is much bigger that 
getlegth so it may be not so important to use |||getlengh or 
|||||compare func) Round trip that's what makes everything slow think.||

And with that we have to deal with null clobs on the client side and 
make sure that lob locator be not in use while clob is null because it 
not possible locator with inititialized(null) clobs

By the way ||does|

  LOB initialised with EMPTY_CLOB() are also exported as NULL
     instead of \\x

| means my thought i mentioned above about nullifying |||empty_clob() on 
ora side|?


|||At least we'll not use lob locators with empty or null lobs (as i 
said that we have real table DO**OURNAL mentioned above with real data 
where count(*)~65 000 000 , only 6.5 GB in size and it has only ~10 rows 
with not nulls  in clob columns.  But exporting it lasts about 1 day 
over the network 8) ) so in this situation this hack may help.

PS I didnt try your latest code so far and may be all i mentioned above 
you have  already  implemented. Promise i'll try it on monday, cause 
today(or already yesterday) was out of the office =)

Alex Ignatov
Postgres Professional: http://www.postgrespro.com
The Russian Postgres Company

**Comment by darold** [comment]
Hi Alex,

I have added a new configuration directive called EMPTY_LOB_NULL to force the use of dbms_lob.getlength() to speed up export when it is possible to transform empty clob/blob into NULL. 

But to preserve emtpy string or \x witjh empty clob/blob right conversion it is disabled by default and will used dbms_lob.compare().

I will make some benchmarks to catch the speed gain.

Cheers

**Comment by darold** [comment]
By default and will **NOT** used dbms_lob.compare() because Oracle does not make difference between empty and NULL. Latest version 17.4 include those changes.

Looking at other improvements I think that the to_char() call for date and timestamp formating is no more needed. We are now forcing NLS_DATE_FORMAT and NLS_TIMESTAMP_FORMAT when opening a connection to Oracle using:

    ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS

and

    ALTER SESSION SET NLS_TIMESTAMP_FORMAT='YYYY-MM-DD HH24:MI:SS

A test over 10 million of rows report a gain from 188679 recs/sec to 196078 recs/sec on a table with two fields, NUMBER and DATE.

**Comment by darold** [comment]
Done in commit 1aa6177.
