### ISSUE TITLE
ora2pg table.sql ERROR:  syntax error at or near "char"

### ISSUE THREAD

**Issue by avmindestroy** [darold/ora2pg#1744]
Good afternoon!!!
I ask you how to solve the problem during migration from an oracle database to postgres
psql -d db -U postgres < schema/tables/table.sql
ERROR:  syntax error at or near "char"
LINE 14:  primary char(1) NOT NULL DEFAULT '0'

after exporting the table in the table.sql file itself the line is like this
primary char(1) NOT NULL DEFAULT '0',

**Comment by darold** [comment]
Look like `primary` is a reserved word in the create table DDL. If you want to preserve it you must enclosed it with double quote.

If you enable USE_RESERVED_WORDS in ora2pg.conf Ora2Pg will do that for you.

**Comment by avmindestroy** [comment]
thank you 
ERROR:  function ora_hash(text) does not exist
LINE 15:  responsecs numeric GENERATED ALWAYS AS (ORA_HASH(BulkEmailR...
                                                  ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by avmindestroy** [comment]
Спасибо
у нас OS Centos 
postgresSql v14
oracle v11
ora2pg v24
Установлен ora2pg где БД postgres 
общая обьем БД Oracle 300 ГБ 
наша задача с БД oracle перейтий целиком на БД postgressql.

Первый раз столкнулись о миграции БД с oracle to postgres
в документации много что написано 
здесь заблудилься, как мне сделать миграцию БД oracle на Постргесс 
после установки ora2pg проверил все соедениение с БД 
ora2pg -t SHOW_VERSION -c config/ora2pg.conf
ora2pg.conf настройки по умолчанию сделано 
DBI connect указыны 
 далее запускаю комманд 
1) ./export_schema.sh
2)  psql -d test_db -U postgres < schema/tables/table.sql
3) ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg.conf
4) psql -d test_db -U postgres < schema/data/data.sql
5) ./import_all.sh
Можете проверить для миграций БД правильно по порядку использую комманды?
Если сможете на ora2pg.conf какие настройки использовать чтобы все автоматический мигрировалься

**Comment by avmindestroy** [comment]
Sorry, I have different errors on different tables, what can I do to fix it myself?
ERROR:  function hextoraw(integer) does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts

**Comment by darold** [comment]
You can not migrate automatically if you have errors when importing SQL file to PostgreSQL. This is the case most of the time unless you don't have stored procedure and basic objects in your oracle database.

Ora2Pg do most of the conversion job but you will have to fix all that have not be converted or the order of the SQL files import. for example `ERROR: function ora_hash(text) does not exist` means that this function must be imported before.

You should use the psql command to import the file individually and fix the errors encountered.

**Comment by avmindestroy** [comment]
![Снимок](https://github.com/darold/ora2pg/assets/162557766/2d227ff6-d7f7-4040-9397-b548228ce0e2)
During export, this error appears, is this normal?
![show version ora2pg](https://github.com/darold/ora2pg/assets/162557766/897babc4-bede-43eb-86ad-95b0f93f74ad)

**Comment by avmindestroy** [comment]
Thank you

**Comment by avmindestroy** [comment]
HI,
![image](https://github.com/darold/ora2pg/assets/162557766/7680f39e-3348-41dd-a30b-82d562dbbed5)
[2024-03-11 08:58:07] [========================>] 2756/2756 tables (100.0%) end of scanning.
FATAL: ERROR:  out of shared memory
HINT:  You might need to increase max_locks_per_transaction.
Aborting export...

**Comment by darold** [comment]
The memory used by Ora2Pg is controlled by 3 parameters:

- DATA_LIMIT (or option -L)
- ORACLE_COPIES (option -J)
- PARALLEL_TABLES (option -P)

Depending on the number of CPU and RAM you have you might adjust these values.
