### ISSUE TITLE
Bug Issue migrating data in json column

### ISSUE THREAD

**Issue by gael-efluid** [darold/ora2pg#1745]
Hello,
We have an issue in our data from Oracle database using ora2pg (v24.1 [edit]reproduced also on the 24.2[/edit]).
We are currently using PG v14.8.

We found that data stored as key in json colums and with the text "borne**Inf**erieureIncluse" are changed by the tool to "borne**Infinity**erieureIncluse"

You can easily reproduce through the following steps

#creation of the test table
```
CREATE TABLE TEST_JSON
(
  ID                  VARCHAR2(25 BYTE),
  JSONDATA            CLOB
);
```

#insertion in the table of the data containing Inf
```
insert into TEST_JSON(id,jsondata) values(2,'{"valeurs":{"0":{"1111Inf2222":1}}}');
insert into TEST_JSON(id,jsondata) values(3,'{"valeurs":{"0":{"typeComparaison":1,"critere":"$CRITERE275155$3","borneSuperieureIncluse":false,"borneInferieureIncluse":true,"type":"INTERVALLE_QUANTITE","borneInferieure":{"valeur":0.0},"borneSuperieure":{"valeur":3.0}}},"description":"(&(0))"}');
commit;
```

#On ora2pg, you configure the file config/ora2pg.conf with 
`MODIFY_TYPE        TEST_JSON:JSONDATA:JSON`

#extraction of the table ddl through ora2pg
`ora2pg -p -t TABLE -o table.sql -b ./schema/tables -c ./config/ora2pg.conf -a TABLE[TEST_JSON]`

#creation of the table under PG playing the ddl of the table TEST_JSON
`psql -d **** -U ***-p 5432 -f schema/tables/table.sql`

#migration of the data through ora2pg
`ora2pg -c config/ora2pg.conf -t COPY -a TABLE[TEST_JSON]`

#Select the migrated data
```
select jsondata from TEST_JSON;
{"valeurs":{"0":{"1111Infinity2222":1}}}
{"valeurs":{"0":{"typeComparaison":1,"critere":"$CRITERE275155$3","borneSuperieureIncluse":false,"borneInfinityerieureIncluse":true,"type":"INTERVALLE_QUANTITE","borneInfinityerieure":{"valeur":0.0},"borneSuperieure":{"valeur":3.0}}},"description":"(&(0))"}
```

**Comment by darold** [comment]
Commit a5ae177 might fix this issue.
