### ISSUE TITLE
Ora2pg IMPORTING DATA ERROR: out of shared memory

### ISSUE THREAD

**Issue by avmindestroy** [darold/ora2pg#1746]
Hi,
![image](https://github.com/darold/ora2pg/assets/162557766/816f4aa1-1df0-4712-953d-a0e868f33984)

[2024-03-11 08:58:07] [========================>] 2756/2756 tables (100.0%) end of scanning.
FATAL: ERROR:  out of shared memory
HINT:  You might need to increase max_locks_per_transaction.
Aborting export...

**Comment by darold** [comment]
The memory used by Ora2Pg is controlled by 3 parameters:

- DATA_LIMIT (or option -L)
- ORACLE_COPIES (option -J)
- PARALLEL_TABLES (option -P)

Depending on the number of CPU and RAM you have you might adjust these values.

**Comment by avmindestroy** [comment]
The following error occurs en masse when importing a database
![image](https://github.com/darold/ora2pg/assets/162557766/ea211d28-0813-4156-a904-f03fd74a093a)

**Comment by avmindestroy** [comment]
hello
The following error occurs en masse when importing a database
![image](https://github.com/darold/ora2pg/assets/162557766/12ee6562-15be-477b-a7ef-f76ca95e00a0)

**Comment by darold** [comment]
You need to use another encoding.
