### ISSUE TITLE
Inserts Generation File (Export File)

### ISSUE THREAD

**Issue by hugobutos** [darold/ora2pg#176]
Hi !! When i try to generate export file i get the next

[1] Scanning table TABLE_NAME (3709447 rows)

but.......

Extracted records from table TABLE_NAME : total_records = 0 (avg: 0 recs/sec)

**Comment by darold** [comment]
Ora2Pg use Oracle statistic to retrieve the number of rows, perhaps your statistics are obsolete. What does the query `SELECT count(*) FROM TABLE_NAME` returns?

**Comment by hugobutos** [comment]
Thanks Darold !!!! 
After execute **EXEC dbms_stats.gather_database_stats;** the result was ok !

**[1] Scanning table TABLE_NAME(0 rows)...
Extracted records from table TABLE_NAME: total_records = 0 (avg: 0 recs/sec)
**
