### ISSUE TITLE
LEFT OUTER JOIN using (+) Bug

### ISSUE THREAD

**Issue by carenswijaya01** [darold/ora2pg#1761]
Hi Darold, i found new bug

When i tried to convert
```
-- q1
select * from tblA, tblB, tblC
where tblA.id = tblB.id (+) and tblA.ids = tblC.id (+);
```

The result is
```
-- q1
select 
  * 
FROM 
  tbla 
  LEFT OUTER JOIN tblb ON (tblA.id = tblB.id) 
  LEFT OUTER JOIN tblc ON (tblA.ids = tblC.id);
```

which seem perfectly fine

but when i tried to convert

```
-- q2
select * from tblA, tblB, tblC
where (tblA.id = tblB.id (+)) and (tblA.ids = tblC.id (+));
```

The result is
```
-- q2
select 
  * 
FROM 
  tbla, 
  (
    tbla 
    LEFT OUTER JOIN tblb ON (tblA.id = tblB.id) 
    LEFT OUTER JOIN tblc ON (tblA.ids = tblC.id);
```

It failed to convert

Even if i tried to put whitespace like this
```
-- q3
select * from tblA, tblB, tblC
where ( tblA.id = tblB.id (+) ) and ( tblA.ids = tblC.id (+) );
```

The result became
```
-- q3
select 
  * 
FROM 
  tblc, 
  tblb, 
  tbla;
```

Which it didn't successfully convert to postgres, just because i add white space ( tblA.id = tblB.id (+) )

There are so much pattern to try, but the problem i think because the `(`, `)`, and `(space)`

**Comment by darold** [comment]
Commit e148208 fixes this problem.

**Comment by carenswijaya01** [comment]
> Commit [e148208](https://github.com/darold/ora2pg/commit/e148208e7d12cc42e6b7913bc3a83a155c60f4f1) fixes this problem.

thanks darold
