### ISSUE TITLE
Does ora2pg support direct migration of data from Oracle, MySQL, and SqlServer to postgreSQL databases?

### ISSUE THREAD

**Issue by ruralqiu** [darold/ora2pg#1763]
Does ora2pg support direct migration of data from Oracle, MySQL, and SqlServer to postgreSQL databases? How should the ora2pg. conf file be configured so that database objects and data from the source library are not saved in the file?

**Comment by darold** [comment]
Yes it is supported and recommended to migrate data. See PG_DSN directive in ora2pg.conf, once it is set, Ora2Pg will send the data to the PostgreSQL database you have specified in the connection string and no more to files.
