### ISSUE TITLE
TRANFORM_VALUE produces invalid SQL

### ISSUE THREAD

**Issue by cchet** [darold/ora2pg#1766]
When we use the directive 'TRANSFORM_VALUE' then we et an error because of an invalid SQL.
We tried with : and , to separate the column from the actual SQL, and both produce the same error.

> TRANSFORM_VALUE     TBL_OFFER_ENTITY[OFFER,regexp_replace("OFFER",'\u0000', '')] 
TRANSFORM_VALUE TBL_OFFER_ENTITY[OFFER:regexp_replace("OFFER",'\u0000', '')]

The error we get:

> FATAL: ORA-00904: "A"."REGEXP_REPLACE": invalid identifier (DBD ERROR: error possibly near <*> indicator at char 83 in 'SELECT a."UUID",a."CAR_LIST_ID",a."UCID",a."EXTERNAL_ID",a."BRAND_CODE",a."SOURCE",<\*>a.regexp_replace("OFFER",'\u0000', ''),a."OFFERNUMBER",a."CREATEDAT",a."OFFERSTATUS",a."MARKET",a."BRAND_DESIGNATION",a."CARHUB_UUID" FROM "SOMAT"."TBL_OFFER_ENTITY" a')

ora2pg docker image: 24.3

**Comment by darold** [comment]
Commit b80d7aa fixes this issue. Just remember to prefix the column name used with the `a` alias used by ora2pg if necessary.

**Comment by cchet** [comment]
@darold Thank's for fixing this issue. When will be the next release, including the docker image, containing this fix?
