### ISSUE TITLE
Unsuppported BIT mysql datatype

### ISSUE THREAD

**Issue by jecuendet** [darold/ora2pg#177]
I have a table with a BIT datatype used as a boolean
ora2pg seems to not like it.
Error I have:
DBD::Pg::st execute failed: ERROR:  invalid input syntax for type boolean: "" at /home/jec/perl5/lib/perl5/Ora2Pg.pm line 10640.
FATAL: ERROR:  invalid input syntax for type boolean: ""
Here is the table DDL:
CREATE TABLE alf_access_control_entry
(
   id bigint PRIMARY KEY NOT NULL,
   version bigint NOT NULL,
   permission_id bigint NOT NULL,
   authority_id bigint NOT NULL,
   allowed bit NOT NULL,
   applies int NOT NULL,
   context_id bigint
)

I tried to set:
REPLACE_AS_BOOLEAN     alf_access_control_entry:allowed
without success.
After some debugging, I guess the problem is in the DBD mysql driver. The data is not queries correctly, the output data is always '' (empty string)

**Comment by darold** [comment]
Please update to latest development code and let me know if that's solves the issue, there was a regression in data export in previous release.

**Comment by jecuendet** [comment]
Tried with git from this morning (29 mars 2016), same problem.

**Comment by jecuendet** [comment]
I tried directly with DBD::mysql to get data from the table that has a BIT column:

use DBI;
use Data::Dumper;
use strict;
use warnings;
my $dsn = "dbi:mysql:alfmigr;host=slv1251v.etat-de-vaud.ch:3320";
my $dbh = DBI->connect($dsn, 'alfmigr', 'UGB7zwpPW', {RaiseError => 1});
#my $insert = "insert into test(a) value(3)";
my $select = "select * from alf_access_control_entry";
#my $insert_st = $dbh->prepare($insert);
my $select_st = $dbh->prepare($select);
#$insert_st->execute() or die $dbh->errstr;
$select_st->execute();

my $ref = $select_st->fetchall_arrayref();

print Dumper($ref);

Results:
$VAR1 = [
          [
            '1',
            '0',
            '1',
            '1',
            '',
            '0',
            undef
          ],
....
The 5th value (empty string) is the BIT column while the edata in the DB is true or false (0 or 1)
It seems that the DBD::mysql driver doesn't cope well with BIT datatype.

**Comment by darold** [comment]
Sorry I've miss that there was a bit() data type. Visibly it is not well supported by Ora2Pg, I test it right now and give you a feedback.

**Comment by darold** [comment]
Last commit 178bd7a might solves the BIT data type export into PostgreSQL bit varying data type. In you example, mysql declaration: `allowed bit(1) NOT NULL,` will be exported as `allowed bit varying(1) NOT NULL,`  in PostgreSQL.

**Comment by jecuendet** [comment]
Not better but different:
DEBUG: Sending INSERT bulk output directly to PostgreSQL backend
DBD::Pg::st execute failed: ERROR:  invalid input syntax for type boolean: "B'1'" at /home/jec/perl5/lib/perl5/Ora2Pg.pm line 10646.
FATAL: ERROR:  invalid input syntax for type boolean: "B'1'"

**Comment by darold** [comment]
Ah ok, you want to be able to convert them as boolean. This was originally not possible because mysql has boolean data type too, but ok that's an Ora2Pg behavior, I will fix that.

**Comment by jecuendet** [comment]
Great, that's exactly it

**Comment by darold** [comment]
New commit 9cea404 will allow that behavior for MySQL datatype.

**Comment by jecuendet** [comment]
REPLACE_AS_BOOLEAN     alf_access_control_entry:allowed
Then:
DBD::Pg::st execute failed: ERROR:  invalid input syntax for type boolean: "'t'" at /home/jec/perl5/lib/perl5/Ora2Pg.pm line 10646.
FATAL: ERROR:  invalid input syntax for type boolean: "'t'"

**Comment by darold** [comment]
Please use the COPY data export type instead of INSERT, I will fix that but the INSERT mode is given for debugging or export to other RDBMS through file output. Importing data on the fly using INSERT is very slow and not recommended.

**Comment by darold** [comment]
Commit d80f362 fix INSERT using on the fly data import with boolean values.

**Comment by jecuendet** [comment]
Working with COPY. Thanks.
