### ISSUE TITLE
Closing quotation mark missing for index creation on reserved keyword

### ISSUE THREAD

**Issue by moonbeamglitterblossom** [darold/ora2pg#1771]
I'm migrating an oracle table with reserved keywords, one of them being `end`.
When I run the `export_schema.sh` script for some reason the closing quotation mark is dropped in the create index statement causing `import_all.sh` to fail:
`CREATE INDEX i_x_end ON x ("end);`

Relevant config settings:
```
USE_RESERVED_WORDS	1
FILE_PER_INDEX	        0
```

**Comment by darold** [comment]
Do you have the Oracle DDL for creating this index?

**Comment by darold** [comment]
Commit 58944ae fixes this issue.
