### ISSUE TITLE
geometry wrongly exported when there is a "hole" in the geometry

### ISSUE THREAD

**Issue by carlos-guilherme-araujo-alb** [darold/ora2pg#1774]
Version tested: 24.3

Example of oracle geometry:
![imagem](https://github.com/darold/ora2pg/assets/25960143/ceba8277-0806-4b23-bedd-9d824589d9d9)

Example of the postgreSQL geometry exported using ora2pg 24.3:
![imagem](https://github.com/darold/ora2pg/assets/25960143/dae5d5e2-3925-42c5-a3bd-3de664cdfd56)

**Comment by 3ronco** [comment]
We are experiencing the same problem with our migration.

**Comment by darold** [comment]
A bit late :-D but in such case if you don't provide a set of Oracle DDL and data to reproduce I can not help. Feel ,free to reopen the issue with the steps to reproduce.
