### ISSUE TITLE
Mysql migration

### ISSUE THREAD

**Issue by mgole001** [darold/ora2pg#1775]
Hi, 

I have been trying to use ora2pg for mysql migration

Created initial configuration and template 
Updated ora2pg conf file with Mysql and PG DSN
Export_schema.sh runs ok
When I try to export data using ora2pg - t COPY -o data.sql -b ./data - c <conf file location> 

I get below error
FATAL: LDAP authentication failed for user "test_user"
Aborting export

Test_user is a valid db user in Postgresql and I can connect to Postgresql database using it

Secondly I get the below error when I run
./import_all.sh -U test_user -d testdb -p 5446 -n testschema -o test_user

When I try to import TABLE by selection Y

Error : no schema has been selected to create in LINE 1 : CREATE TABLE account ( 

Error : an error occurs when importing file ./schema/tables/table.sql

How do I resolve these 2 errors? Thanks

**Comment by darold** [comment]
You have LDAP authentication enabled in your pg_hba.conf so the user must be also declared in LDAP.

For the schema you probably have to enable EXPORT_SCHEMA.
