### ISSUE TITLE
OUT OF MEMORY EVEN THOUGH SERVER HAS OVER 16GB FREE RAM

### ISSUE THREAD

**Issue by NobleZirwaHara** [darold/ora2pg#1780]
Trying to convert from a dump with over 800 tables.

I have tried lowered the DATA_LIMIT all the way to 10 and it still doesn't work

My server has 12 Cores, 32GB of RAM. Is it because my dump has millions of records

**Comment by executed** [comment]
@darold even though it's not my question what do you think would be suitable parameters for this type of server based on requested parameters: JOB|PARALLEL_TAB|ORACLE_COPIES|DATA_LIMIT|BLOB_LIMIT ?
