### ISSUE TITLE
Reading the ora2pg assessment report 

### ISSUE THREAD

**Issue by mgole001** [darold/ora2pg#1782]
Hi, 

Wanted to ensure i am reading the ora2pg assessment rwport correctly. Please confirm if below is accurate -

1. If the assessment report shows
Procedure - Number =5, Estimated costs =100.00

What does this mean?
Does it mean the schema that was assessed has 5 stored procedures and the total estimated cost to refactor and migrate these 5 stored procedures would be 100 estimated unit (each unit is 5 mins, total 500 mins effort)? 
2. From the details i can find out how much estimated effort each procedure will take and which code constructs will take how much effort etc. But how do i find out which of these code constructs and/or procedure will be automatically converted by orq2pg during migration? 
3. Does this 500 mins effort include the effort needed for refactoring (if manual conversion) plus the migration effort (moving from source to target etc)
4. If technical level is 1, 2 or 3 that means no manual rewrite is needed and ora2pg will automatically convert most objects including procedures triggers etc but if technical level is 4 or 5 how do I know which procedures, triggers, packages would need manual rewrite vs which will be automatically converted by ora2pg? 
5. In real scenarios based on others experience do we know how accurate is the ora2pg assessment report estimates?  E.g. if Ora2pg assessment gives migration level as B5 and total estimated costs is approx 110 (total effort is 110x5=550 mins). During actual migration has the estimate of 550 mins been accurate, with minimal variance say +- 10%

Thanks

**Comment by mgole001** [comment]
Hi, any update on above query? Thanks

**Comment by darold** [comment]
>1.  Does it mean the schema that was assessed has 5 stored procedures and the total estimated cost to refactor and migrate these 5 stored procedures would be 100 estimated unit (each unit is 5 mins, total 500 mins effort)?
Yes that's exactly mean that.

> 2. From the details i can find out how much estimated effort each procedure will take and which code constructs will take how much effort etc. But how do i find out which of these code constructs and/or procedure will be automatically converted by ora2pg during migration?
You have a code converted by Ora2Pg, whatever is the code converted automatically when you will try to import it to PostgreSQL you have to fix the errors. Knowing which code is converted by ora2pg is useless IHMO.

> 3. Does this 500 mins effort include the effort needed for refactoring (if manual conversion) plus the migration effort (moving from source to target etc)
The effort assessment provided by Ora2Pg include fix, import and tests of the migrated object for an expert in migration. If you are new to this work you should at least double the time.

> 4. If technical level is 1, 2 or 3 that means no manual rewrite is needed and ora2pg will automatically convert most objects including procedures triggers etc but if technical level is 4 or 5 how do I know which procedures, triggers, packages would need manual rewrite vs which will be automatically converted by ora2pg?
In the details all stored procedure which have keywords other than SIZE and TEST can potentially need manual rewrite.

> 5. In real scenarios based on others experience do we know how accurate is the ora2pg assessment report estimates? E.g. if Ora2pg assessment gives migration level as B5 and total estimated costs is approx 110 (total effort is 110x5=550 mins). During actual migration has the estimate of 550 mins been accurate, with minimal variance say +- 10%
This is an automatic assessment, it gives you an idea of the effort. A review of the assessment, the architecture and the application by a migration expert will help to determine the exact migration effort. But yes, usually something reported B-5 by Ora2Pg is trivial to migrate.

**Comment by mgole001** [comment]
Thx for the update. Related to above item#2, does this mean that unless we run an import into Postgresql we will not know which procedures, packages, triggers etc can be automatically converted by ora2pg vs which need manual rewrite?

**Comment by darold** [comment]
Right, an automatic conversion, even imported successfully in PostgreSQL, doesn't means that there is no issues with non-existing objects or that ir returns different results for example. Only execution of the stored procedure and tests of the attended results can validate that the conversion was fully correct.

**Comment by mgole001** [comment]
> > 1. Does it mean the schema that was assessed has 5 stored procedures and the total estimated cost to refactor and migrate these 5 stored procedures would be 100 estimated unit (each unit is 5 mins, total 500 mins effort)?
> 
> Yes that's exactly mean that.
> 

So this estimate of 500 mins in the assessment report is assuming none of the code constructs would be automatically converted by ora2pg since we do not know unless we import if few or all procedures would be converted . This 500 mins is the time expected for import, review ora2pg converted code if any, manual conversion if any and testing?

**Comment by darold** [comment]
> This 500 mins is the time expected for import, review ora2pg converted code if any, manual conversion if any and testing?

Yes this is what it means but the report need to be analyzed and refined by a human. This is just a base of estimation.
