### ISSUE TITLE
Wrong argument "extra_param OPAQUE" in function with OUT arguments (regression in release 24.3)

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#1786]
Hello Darold,

I still use your -great- tool on a regular basis...

When I tried release 24.3, I saw a new way of translating procedures with OUT or "IN OUT" arguments: an extra argument is added and the generated function retuens record:  
The problematic added string is  :   ", OUT extra_param OPAQUE) RETURNS record " 

This makes my PostgreSQL 15 server complain with "ERROR:  type opaque does not exist".

I attach a small probe package zip with 3 files: Oracle, migrated with ora2pg 23.1 and migrated with ora2pg 24.3.

Is this addition required ?

Best Regards,
Eric
[PCK_PROBE-20240530.zip](https://github.com/darold/ora2pg/files/15500250/PCK_PROBE-20240530.zip)

**Comment by darold** [comment]
Hi Eric,

You have to set PG_VERSION to 15 in your ora2pg.conf. I guess it is set to a PG version <= 10
