### ISSUE TITLE
Wrong change in translation of "is not null" clause (regression in release 24.3)

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#1787]
Hello Darold,

When I tried release 24.3, I saw a new way of translating "IS NOT NULL" clause:
It once was "(myVar IS NOT NULL AND myVar::text <> '') 
Now I see "(myVar AND myVar::text <> '') 

It looks like a change linked to boolean variables or columns...

I attach a small probe package zip with 3 files: Oracle, migrated with ora2pg 23.1 and migrated with ora2pg 24.3.
(you will see that this sample code is common with my previous issue)

Best Regards,
Eric
[PCK_PROBE-20240530.zip](https://github.com/darold/ora2pg/files/15500392/PCK_PROBE-20240530.zip)

**Comment by darold** [comment]
This is a regression, commit 7e52fa7 solves this issue.
