### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by sttachoires** [darold/ora2pg#179]
I'm sure I missed something, but I can't figure what.

Fresh ora2pg download (master.zip)
Fresh perl install, cpan, dbi, dbd:oracle, mysql, pg

ora2pg --version
syntax error at /usr/local/share/perl5/Ora2Pg.pm line 14034, near "} elsif"
Unmatched right curly bracket at /usr/local/share/perl5/Ora2Pg.pm line 14040, at end of line
Can't use global @_ in "my" at /usr/local/share/perl5/Ora2Pg.pm line 14044, near "= @_"
syntax error at /usr/local/share/perl5/Ora2Pg.pm line 14060, near "}"
Can't use global @_ in "my" at /usr/local/share/perl5/Ora2Pg.pm line 14064, near "= @_"
syntax error at /usr/local/share/perl5/Ora2Pg.pm line 14080, near "}"
Compilation failed in require at /usr/local/bin/ora2pg line 27.
BEGIN failed--compilation aborted at /usr/local/bin/ora2pg line 27.

**Comment by darold** [comment]
Thanks for the report, fixed now. Visibly I've made an intensive use of dd under VI :-)

**Comment by sttachoires** [comment]
It works. Thanks.
