### ISSUE TITLE
Issue in migrating from SQL Server to CloudSQL Postgres

### ISSUE THREAD

**Issue by Pavithra2826** [darold/ora2pg#1794]
Hi,
I have installed all the pre-requisites to migrate from SQL Server to postgres. But got below error while trying to migrate  object(Procedure) from SQL Server to Postgres
Attached the sample conf file used for migration.
Could you please check and provide the correct sample conf file to migrate from MSSQL to postgres

@XXXX:~/$ ora2pg -c ora2pg.conf -t procedure -o sp.sql
FATAL: you must set ORACLE_DSN in ora2pg.conf or use a DDL input file.
Aborting export...

[ora2pg.txt](https://github.com/user-attachments/files/15814383/ora2pg.txt)

**Comment by darold** [comment]
Hi,

You cannot just invent the configuration directives and wish it can work. Where did you get these?
```
SOURCE   dbi:ODBC:driver=msodbcsql18;server=XXXXXXX;database=XXX;TrustServerCertificate=yes
USER     XXXXXXX
PASSWORD XXXXXX
```
you must use the following;
```
ORACLE_DSN      dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME;port=1521
ORACLE_USER     system
ORACLE_PWD      manager
```
I agree that the name is no more adapted to the multiple DBMS that Ora2Pg is able to migrate now, but this is historical.

**Comment by Pavithra2826** [comment]
I am trying to migrate SQLServer database, Can we use oracle configuration directives for SQLServer?
Should I change anything in the configuration directives to support SQL Server.

cp130630:~/mssql$ ora2pg -c ora2pg.conf -t procedure -o sp.sql
FATAL: 12537 ... ORA-12537: TNS:connection closed (DBD ERROR: OCIServerAttach)
Aborting export..

**Comment by Pavithra2826** [comment]
Could you please confirm

**Comment by darold** [comment]
You should have a look to the documentation for directive ORACLE_DSN.
