### ISSUE TITLE
Foreign server always generated with default port

### ISSUE THREAD

**Issue by aymanadou** [darold/ora2pg#1795]
Hello,
the foreign server declared when copying the data using oracle FDW is always declared with 1521 port even the configuration is using another port.

 select * from pg_catalog.pg_foreign_server ;
  oid   | srvname | srvowner | srvfdw | srvtype | srvversion | srvacl |                        srvoptions
--------+---------+----------+--------+---------+------------+--------+-----------------------------------------------------------
 413232 | orcl    |    16397 | 413231 |         |            |        | {dbserver=//xxxxx.fr:**1521**/XXX}
(1 row)

so to avoid the copy problem i should update the server option before the TNS error triggers :

alter server orcl options (SET dbserver '//xxx:**20300**/XXX');

**Comment by darold** [comment]
Hi,

The FDW server port is base on the ORACLE_DSN configuration value, what is this value? You should anonymize it but with respect to the syntax.

**Comment by aymanadou** [comment]
Hello,
ora2pg versions : 24.1 and 24.3 
ORACLE_DSN      dbi:Oracle:host=xxx;sid=PXXOR1;port=20300

**Comment by darold** [comment]
My bad, commit ece3b01 might fix this issue.
