### ISSUE TITLE
Export data with CLOB is too slow

### ISSUE THREAD

**Issue by frc372** [darold/ora2pg#1796]
Hi,
I have to do a data migration from oracle to postgres, using a Windows 10 machine. There are CLOBs data and the migration is too slow (about 10 records/sec). How can I improve it, mabye with different configuration or anything else?
Thank you for your attention.

**Comment by darold** [comment]
Use the `-J` option or consider using the FWD capability of Ora2Pg

**Comment by frc372** [comment]
ok thanks, If I started using a Linux machine, would I increase this speed a lot, instead using windows 10
?

**Comment by frc372** [comment]
Also, if I started using a Linux machine, would I increase this speed a lot?

**Comment by darold** [comment]
Yes, the -J or -P options, I mean multiprocess, doesn't work on Windows.

**Comment by frc372** [comment]
good morning 
and how can I use the FWD in ora2pg?

**Comment by darold** [comment]
Enable and set a name to FDW_SERVER configuration directive.

**Comment by frc372** [comment]
ok thank you for your time.
