### ISSUE TITLE
Oracle to Postgresql migration - issue with SECURITY DEFINER

### ISSUE THREAD

**Issue by mgole001** [darold/ora2pg#1799]
Hi

Working on a oracle to postgresql migration

Using ora2pg v24.3

Ora2pg conf file has PLSQL_PGSQL set to 1 for automated conversion
Pg_version 14

Export_schema.sh works fine

When I try to import the procedures it fails with error -
psql:./schema/procedures/xxx.sql:23:ERROR: syntax error at or near "SECURITY"
LINE 9: SECURITY DEFINER

Another issue is related to suffix for procedures names

I have a oracle schema "test" that I am trying to migrate
When I migrate to postgresql I am naming that schema "test_ora2pg" , following parameters are set in ora2pg.conf file 
PG_SCHEMA test_ora2pg

All works fine except if I go to the procedures sql it still reflect the oracle schema "test" instead of postgresql scheme "test_ora2pg" for procedures

Eg

Create or replace procedure test.xxx

Instead of it reflecting as 

Create or replace procedures test_ora2pg.xxx

Please provide guidance.
Thanks

**Comment by darold** [comment]
Commit 9b0c12c fixes this issue
