### ISSUE TITLE
RPM build of ora2pg fails because of buildroot reference in ora2pg script

### ISSUE THREAD

**Issue by calbiston** [darold/ora2pg#180]
This is an issue with ora2pg 17.2 but not 17.1.  I need 17.3 for the major bug fix in data export and if I go back to 16.2 to avoid the bug, I lose the support for the TEST type.

In **packaging/RPM/ora2pg.spec**:
    perl Makefile.PL \
    ...
    DESTDIR=%{buildroot} < /dev/null

In **Makefile.PL**:
    my $PREFIX = $ENV{DESTDIR} || $ENV{PREFIX} || $ENV{INSTALL_BASE} ||  '';
...
if ($PREFIX) {
	$CONFDIR = $PREFIX . $CONFDIR;
    ...
}
...
    my $tmp_conf = quotemeta($CONFDIR);
    `perl -p -e 's#my \\\$CONFIG_FILE .*#my \\\$CONFIG_FILE = "$tmp_conf\\\\ora2pg.conf";#' scripts\\ora2pg > scripts\\ora2pg.tmp`;

**Comment by darold** [comment]
Last commit 53ccb99 might solves the issue. Download latest development code from github and let me know.

Regards

**Comment by calbiston** [comment]
check-buildroot checks against $RPM_BUILD_ROOT rather than the string 'buildroot'.  In my case the string is BUILDROOT and the new code does not check that case.

**Comment by darold** [comment]
Can you report here the error and explaining more what's going wrong? If you think you can fix the code, please post here what need to be done or submit a pull request. Sorry but I don't have a RPM based distribution at my end to see what's happen.

**Comment by calbiston** [comment]
Essentially, Makefile.PL should be changed to insert the originally-passed-in CONFDIR location into ora2pg as $CONFIG_FILE when a new environment variable ($RPM) is set.

Details:
An RPM is a way of packaging a script and its associated files as a single module, keeping track of its dependencies, exports and installed files, somewhat like a cross between a linker for a compiled language and a installer for a binary executable.

The RPM build process sets up a fake root (the "buildroot") that contains all the files that will be installed on the real filesystem.  One of these files is the ora2pg script.  The RPM build process checks for circular references to the "buildroot" in these files with the script check-buildroot.  If these were allowed to remain, the installed ora2pg would be looking for files in the directory in which it was built instead of in the real filesystem.  

The new destination directory feature works fine when a person interactively invokes
perl Makefile.PL DESTDIR=%{someDestinationDirectory}
and
make install  DESTDIR=%{someDestinationDirectory}
as root and installs ora2pg interactively.

However, the RPM build process invokes
perl Makefile.PL CONFDIR=%{_sysconfdir} DESTDIR=%{buildroot}
make install  DESTDIR=%{buildroot}
as an unprivileged user to set up its fake root (buildroot) of files to be installed later by a privileged user with yum or rpm.  (See the file packaging/RPM/ora2pg.spec in the ora2pg source.  This is the configuration file for building an RPM.)

Makefile.PL uses DESTDIR to determine the location of the configuration file ora2pg.conf.dist (as of ora2pg 17.2) and inserts this location ($CONFIG_FILE) in the ora2pg script.  Then check-buildroot objects, because this location includes the fake "buildroot" as part of its path.  

You can check out this behavior yourself if you do the following (see https://rpmbuildtut.wordpress.com):

[root@localhost ~]$ sudo yum install rpmdevtools rpmlint
[user@localhost ~]$ rpmdev-setuptree
[user@localhost ~]$ cd rpmbuild/; ls
BUILD RPMS SOURCES SPECS SRPMS

Copy packaging/RPM/ora2pg.spec into SPECS
Copy ora2pg-16r0.tar.bz2 into SOURCES

[user@localhost ~/rpmbuild]$ rpmbuild -bb SPECS/ora2pg.spec

**Comment by calbiston** [comment]
I succeeded in building an ora2pg RPM by making a few changes in Makefile.PL and by replacing packaging/RPM/ora2spec (with a few changes).

1)  Makefile.PL needs to specify $PREFIX$CONFDIR and $PREFIX$DOCDIR in MY::postamble (instead of $CONFDIR and $DOCDIR)

2)  packaging/RPM/ora2pg.spec needs to be replaced with http://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob;f=rpm/redhat/9.2/ora2pg/EL-7/ora2pg.spec

3) The new ora2pg.spec needs to be revised:
a) Use CONFDIR=%{_sysconfdir}/%{name} (when calling perl Makefile.PL) 
b) Use %{_docdir}/%{name}-%{version}/* (in the %files section)

**Comment by darold** [comment]
Latest commits include replacement of ora2pg.spec with Devrim's spec file and apply all your advice in the points above. The Makefile have been adapted to these changes. I have also updated the version to 17.4 in the spec file, the global version change will be done later.

Let me know if there's others issue.

**Comment by devrimgunduz** [comment]
Hi Gilles,

What is the plan for 17.4? RPMs are waiting for this.

Cheers, Devrim

**Comment by darold** [comment]
Hi Devrim,

I still have to test some data export improvement but I have planed to publish 17.4 tonight. Does the ora2pg.spec file in ora2pg/packaging/RPM/ looks good for you ? I did not know that you are maintaining an ora2pg.spec file, so I have replaced my obsolete spec file with yours. By this way there will be one single spec file. Please do not hesitate to report issue related to this file.

Cheers

**Comment by devrimgunduz** [comment]
Hi Gilles,

I think you also patched Makefile.PL to fix this bug, right? The spec file looks ok, but I still need other improvements to fix builds.

I will need to maintain the spec file anyway, as this is needed by the community repo. 

Cheers, Devrim

**Comment by darold** [comment]
Yes, Makefile.PL have been patched and the build might works. What are the other improvements you are needing?  Let me know what to fix, I will apply them.

**Comment by devrimgunduz** [comment]
I can build the git master without issues. Thank you, I don't need anything else for now.

Cheers, Devrim

**Comment by darold** [comment]
Ora2Pg v17.4 have been published. Thanks for your work.

Cheers

**Comment by darold** [comment]
Release v17.4 have just been republished, a patch was missing. Sorry for the inconvenience.
