### ISSUE TITLE
Filenames created incorrectly when exporting using the COPY option and parameter RENAME_PARTITION=1

### ISSUE THREAD

**Issue by simonpane** [darold/ora2pg#1800]
Exporting from Oracle to disk using the command:
```bash
ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg.conf
```

Export includes a PARTITIONED table and consequently am including the Ora2Pg configuration parameter:
```
RENAME_PARTITION               1
```

After exporting, the `data/data.sql` file uses the renamed partitions.  Excerpt for example:
```
...
\i './data/SAMPLE_TABLE_data.sql'
\i './data/SAMPLE_TABLE_part1_data.sql'
\i './data/SAMPLE_TABLE_part2_data.sql'
\i './data/SAMPLE_TABLE_part3_data.sql'
\i './data/SAMPLE_TABLE_part4_data.sql'
...
```

But the actual files on disk do not use the new names, and instead use the old partition names in the filename.  Example:
```bash
ls -1 data/SAMPLE_TABLE*
SAMPLE_TABLE_data.sql
SAMPLE_TABLE_SYS_P72925_data.sql
SAMPLE_TABLE_SYS_P72926_data.sql
SAMPLE_TABLE_SYS_P72927_data.sql
SAMPLE_TABLE_SYS_P72929_data.sql
```

And consequently, when running `import_all.sh` the script will fail as it cannot find the properly named files on disk.

---

Even if exporting partitions with `RENAME_PARTITION=0` and using the **COPY** option to export to disk (and not to write directly into the PostgreSQL target), the exported files have an incorrect file name as they include the table name while the `data/data.sql` references to those files do not.

---

Ora2Pg version:
```bash
$ ora2pg --version
Ora2Pg v24.3
```

**Comment by darold** [comment]
Fixed by commit 0998e8d
