### ISSUE TITLE
dlltool error

### ISSUE THREAD

**Issue by srinilakshmi** [darold/ora2pg#1803]
I am installing Ora2pg on windows, and when done with prerequisites like strawberry perl, Oracle client, then setting up environment values for ORACLE_HOME and NLS_LANG, the next step is to run perl Makefile.pl from DBD-oracle folder, getting an error with dlltool

error is 'dlltool' is not recongnized as an internal or external command.
![WhatsApp Image 2024-07-30 at 16 40 51_5cc8e9a2](https://github.com/user-attachments/assets/b16c00a8-dcbe-4e8d-b2d8-4f0281b68e88)

Need help with this please

**Comment by darold** [comment]
I don't know the reason of this error. Please use a Linux box, things will be easier.

**Comment by srinilakshmi** [comment]
Doee the Oracle DAD module, makefile.pl woul need internet connectivity?

Srinivas Kollipara

**Comment by darold** [comment]
No, a command is missing. ddltool

**Comment by srinilakshmi** [comment]
I have a need for this to do on a windows box

Srinivas Kollipara

**Comment by srinilakshmi** [comment]
Is the command missing in DAD module or in Oracle installation or Perl? following the attached pdf for prereqs and needed some help on this.
[Step-by-Step guide to install ora2pg on Windows.pdf](https://github.com/user-attachments/files/16440616/Step-by-Step.guide.to.install.ora2pg.on.Windows.pdf)
