### ISSUE TITLE
some Foreign keys are not generated

### ISSUE THREAD

**Issue by aymanadou** [darold/ora2pg#1808]
Hello,
for ora2pg 24.3 i detected a missing foreign keys for some tables .

case 1 : with ALLOW  only tables (ERREOR, CATEGORYVALUE) 
![image](https://github.com/user-attachments/assets/c69db2d6-9ebc-4d59-8b89-50d8e1fdbc32)

case 2 without ALLOW ALLtables 
the foreign keys for tables (ERREOR, CATEGORYVALUE) are not genrerated 

case 3 with ALLOW tables (ERREOR, CATEGORYVALUE CONTEXT) 
![image](https://github.com/user-attachments/assets/76c638df-b11d-4e8e-a82f-6349b119d32b)

for the three cases i only change the ALLOW parameter

the state of foreign keys ; all of them are enabled, but some are validated some are not.

**Comment by darold** [comment]
I guess that the input was a file. Commit e848289 fixes that.
