### ISSUE TITLE
What is the meaning of WARNING - we should not be there ?

### ISSUE THREAD

**Issue by jprante** [darold/ora2pg#1809]
I'm getting a lot of messages 
```
/!\ WARNING /!\: we should not be there !!!
```
https://github.com/darold/ora2pg/blob/master/lib/Ora2Pg.pm#L13879

when executing
```
ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg.conf
```
and I don't know how to cope with it or how to track it down. What should I do?  Does it mean data loss? Undefined data types? Problems in DBD::Oracle? A logical misassumption in ora2pg? Or is it simply a neglectable warning?

Thanks in advance for any guidance.

**Comment by darold** [comment]
This mean unknown/unparsable geometry by Ora2Pg::GEOM. Can you post the RDBMS type and the geometry type of that column. If this is really a geometry, post also some data sample extracted using function SDO_UTIL.TO_WKTGEOMETRY()

**Comment by jprante** [comment]
No geometry column types and no geometry data here. I will try to extract some rows from the table for reproducing.

**Comment by darold** [comment]
Please, add the description of the table first.

**Comment by darold** [comment]
No follow up, closing
