### ISSUE TITLE
Enable unique timestamped log files for each ora2pg execution

### ISSUE THREAD

**Issue by interstellarigrok** [darold/ora2pg#1812]
Description:

I configured two directives in ora2pg:
`
DEBUG 1

LOGFILE .../log/LOGFILE ora2pg_job_$(date +%Y%m%d_%H%M%S).log
`

I expected the log files to be saved with a unique timestamp, such as ora2pg_job_20230220_142300.log.

However, this did not happen. Instead, the logs were not saved with the expected timestamp format.

Is it possible to configure ora2pg so that each log file is saved with a unique timestamp directly from within the configuration file?

**Comment by darold** [comment]
This must be handled by a meta script, it is quite easy to do.
