### ISSUE TITLE
[Question] How to generate ALTER COLUMN instructions to set default values to sequences nextval?

### ISSUE THREAD

**Issue by samueldc** [darold/ora2pg#1814]
Hi everyone,
I'm taking my first steps with this amazing tool. 
I'm trying to migrate an Oracle old database (of an old OTRS 5 instance). In this old database, that has almost 158 tables, most id fields (private keys) are autoincremented using sequences and triggers to insert a sequence nextval into the id field.
ora2pg is doing just fine generating the sequences and updating their current values. But I'm missing the alter column instructions to set default values to the sequences nextval in PostgreSQL (or, maybe, convert all this fields to type identity or serial). 
Is that in the scope of ora2pg? Any thoughts on that?
Thanks in advance!
Samuel

**Comment by samueldc** [comment]
Just to mention I've already looked for similar questions. The issues below seem to be related, but I don't think they address this question:

https://github.com/darold/ora2pg/issues/1438

https://github.com/darold/ora2pg/issues/1101

**Comment by darold** [comment]
Use `-t SEQUENCE_VALUES` to export the alter statements to set the latest value of each sequences
