### ISSUE TITLE
Got error about: WARNING: an error occurs during data export. Please check what's happen.

### ISSUE THREAD

**Issue by jasonchenTJ** [darold/ora2pg#1817]
Hi Darold,

am performing the data loading from ORACLE to PG just for 1 table with 4 parallel. 

But after the data loading finished 100%,  got below:

 WARNING: an error occurs during data export. Please check what's happen.

Seems this is not a OOM issue.  I guess that error probably due to multiple process running,  probably it's a bug. 

Log details:

[postgres@whdcpsql004 task3]$ tail -f ORA2PG_T_SMSSEND.log
[========================>] 1/1 tables (100.0%) end of scanning.        
[======>                  ] 102215568/408721785 rows (25.0%) Table T_SMSSEND-part-2 (10905 sec., 9373 recs/sec)                       
[======>                  ] 102215630/408721785 rows (25.0%) Table T_SMSSEND-part-3 (10905 sec., 9373 recs/sec)                       
[======>                  ] 102215648/408721785 rows (25.0%) Table T_SMSSEND-part-1 (10905 sec., 9373 recs/sec)                       
[======>                  ] 102215603/408721785 rows (25.0%) Table T_SMSSEND-part-0 (10905 sec., 9373 recs/sec)                       
[========================>] 408721785/408721785 rows (100.0%) Table T_SMSSEND (10906 sec., 37476 recs/sec)                            
[========================>] 408862449/408721785 rows (100.0%) on total estimated data (10909 sec., avg: 37479 tuples/sec)

WARNING: an error occurs during data export. Please check what's happen.

Thanks
Jason

**Comment by jasonchenTJ** [comment]
Probably I know the root cause: 

The code logic:   

![image](https://github.com/user-attachments/assets/e5f4e719-8a24-4c31-a20a-047cd992e053)

I have running 3 ora2pg dedicated process for 2 diff ora2pg.conf, so under the /tmp file have many tempfiles as below:

![image](https://github.com/user-attachments/assets/28847130-5462-45eb-b0ef-91fd25ba2fb3)

**Comment by darold** [comment]
yes, you probably reach a limit.

**Comment by jasonchenTJ** [comment]
@darold  Thanks for your quick reply!  

Will close this issue. Have a good day or night! 


Thanks
Jason
