### ISSUE TITLE
Facing issues in procedures which generated by ora2pg

### ISSUE THREAD

**Issue by nareneee** [darold/ora2pg#1818]
Hi Darold,

We are facing below error, please help us on this.

1) psql:/backend/migration/scripts/blob/procedure.sql:75: ERROR:  syntax error at or near ","
LINE 20:         SELECT EXTRACT[kpacDraft, '//@Contact'].getClobVal()...

As i observered In Oracle, EXTRACT is used to extract parts of XML, and getClobVal() converts it to a CLOB. PostgreSQL handles XML differently. we can use xpath() to query XML data in PostgreSQL.

2) psql:/backend/migration/scripts/blob/procedure.sql:112: ERROR:  syntax error at or near "table"
LINE 11:     select count(*) into STRICT row_count from table(xmlsequ...

In Oracle, TABLE() is used to treat the result of a subquery as a table. PostgreSQL does not have a direct equivalent, and this syntax must be adjusted depending on the context.
If we are  working with XML data and trying to count elements within XML, you can use xpath() to extract the elements, and array_length() to count them.

As we are building the automation tool , we are facing lot of error in procedure, function and triggers. is there any way to fix the issue by ora2pg conf level? or still do we need manual adjusments?

**Comment by darold** [comment]
You still need manual editing.

**Comment by nareneee** [comment]
Could you fix it in upcoming version?

**Comment by darold** [comment]
Without Oracle source code to reproduce the problem, the problem will not been solved.
