### ISSUE TITLE
Facing issues in trigger file which is generated by ora2pg

### ISSUE THREAD

**Issue by nareneee** [darold/ora2pg#1819]
Hi Darold

we are facing the below error, please help on this part

1)ERROR:  unexpected end of function definition at end of input
LINE 6: $BODY$

syntax
-------
```
CREATE OR REPLACE FUNCTION trigger_fct() RETURNS trigger AS $BODY$
declare
                BEGIN
                    if ( NEW.chooser_id IS NULL ) then
                      SELECT nextval('column_chooser_seq') into STRICT NEW.chooser_id
$BODY$
LANGUAGE 'plpgsql' SECURITY DEFINER;
```
the PostgreSQL function definition is incomplete. Specifically, the CREATE FUNCTION statement is missing the closing part of the function body. we need to add this END IF; RETURN NEW; END; to close function body.

2)ERROR:  syntax error at or near ""XPERT_VITALITY_TREND_TRIGGER""
LINE 2:         BEFORE INSERT ON xpert_vitality_trend "XPERT_VITALIT..

syntax
---------
```
CREATE TRIGGER xpert_vitality_trend_trigger
        BEFORE INSERT ON xpert_vitality_trend "XPERT_VITALITY_TREND_TRIGGER"
    before insert on XPERT_VITALITY_TREND REFERENCING NEW AS NEW for each row
     FOR EACH ROW
        EXECUTE PROCEDURE trigger_fct_xpert_vitality_trend_trigger();
```    
The table name should not be quoted or include any extra identifiers like "XPERT_VITALITY_TREND_TRIGGER". Just use the table name xpert_vitality_trend and repeating line in this syntax.
In PostgreSQL, triggers use EXECUTE FUNCTION to call the trigger function, not EXECUTE PROCEDURE.

These are the problem we are getting while executing triggers. is there any solution to fix the issue by ora2pg without manual intervention. As we are developing automation tool we need fix these error by ora2pg.

**Comment by KERERCVASD** [comment]
maybe this will help
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by darold** [comment]
Please post the Oracle source code of the trigger.

**Comment by nareneee** [comment]
See the oracle source code of mentioned errors
1)CREATE TRIGGER Trigger_name
	        on column_chooser for each row
	        declare
	        begin
	            if( :new.chooser_id IS NULL ) then
	              SELECT COLUMN_CHOOSER_SEQ.nextval into :new.chooser_id from dual
/

2)CREATE TRIGGER "TRIGGER_NAME"
    before insert on XPERT_VITALITY_TREND REFERENCING NEW AS NEW for each row
    begin
        select XPERT_VITALITY_TREND_0.nextval into :new.ID from dual;
    end;
/

**Comment by darold** [comment]
The first trigger is not syntactically correct, no END IF and not END at end of the definition.
The second definition look to be correctly translated by ora2pg : 
```
DROP TRIGGER IF EXISTS trigger_name ON xpert CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_trigger_name() RETURNS trigger AS $BODY$
BEGIN
select nextval('xpert_0') into STRICT NEW.ID;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql';

ALTER FUNCTION trigger_fct_trigger_name() OWNER TO gilles;

DROP TRIGGER IF EXISTS trigger_name ON xpert;
CREATE TRIGGER trigger_name
        before insert ON xpert FOR EACH ROW
        EXECUTE PROCEDURE trigger_fct_trigger_name();
```
Use latest development code.
