### ISSUE TITLE
Data export stops too soon on last table when using parallel tables and jobs

### ISSUE THREAD

**Issue by calbiston** [darold/ora2pg#182]
When the data export completes for the next to the last table, no more data is exported for the last table, even if more data remains to be exported.  This is especially noticeable when the last table is hugely larger than all the other tables.
Settings:  PARALLEL TABLES=4 and JOBS=4
Versions:  v16.2, v17.1, v17.3, master as of 4/5/16

**Comment by darold** [comment]
You may have an OOM, does ora2pg complain about something at end? What is the result of command:    `echo $?` run just after the ora2pg command?

**Comment by calbiston** [comment]
ora2pg complains about nothing and continues on to restore the foreign keys and indexes that it dropped at the beginning.  There is no problem when the hugely large (and last) table is exported by itself.  It is odd that it picks exactly the time that the next to the last table finishes to decide it is finished with the last table, too.

**Comment by darold** [comment]
I'm not able to reproduce the problem. How many RAM memory is available on the ora2pg machine

**Comment by darold** [comment]
And how hugely larger is the table in row and size? If you can send me the full output of the ora2pg execution using -d to my private email gilles@darold.net it could be a great help.

Best regards,

**Comment by darold** [comment]
Do you have any feedback on this isssue?

**Comment by calbiston** [comment]
It is not a memory issue.  The last table has 5 million rows and the next to the last table has 350 thousand rows.  I would expect the last table to be the largest one in bytes and the next to the last table to be the next largest one.  I am using Postgres 9.2 and Oracle 11.2.

data export log:
...
Dumping data from LAST_TABLE to file: ./init_project/data/LAST_TABLE_data.sql
Written 2000000 bytes to ./init_project/data/LAST_TABLE_data.sql
Extracted records from table LAST_TABLE: total_records = 273000 (avg: 1000 recs/sec)
DEBUG: Formatting bulk of 3000 data for PostgreSQL.
DEBUG: Creating output for 3000 tuples
Dumping data from NEXT_TO_LAST_TABLE to file: ./init_project/data/NEXT_TO_LAST_TABLE_data.sql
Written 1000000 bytes to ./init_project/data/NEXT_TO_LAST_TABLE_data.sql
Extracted records from table NEXT_TO_LAST_TABLE: total_records = 354000 (avg: 1000 recs/sec)
DEBUG: Formatting bulk of 3000 data for PostgreSQL.
DEBUG: Creating output for 3000 tuples
Dumping data from NEXT_TO_LAST_TABLE to file: ./init_project/data/NEXT_TO_LAST_TABLE_data.sql
Written 400000 bytes to ./init_project/data/NEXT_TO_LAST_TABLE_data.sql
Extracted records from table NEXT_TO_LAST_TABLE: total_records = 355211 (avg: 1000 recs/sec)
DEBUG: Formatting bulk of 3000 data for PostgreSQL.
DEBUG: Creating output for 3000 tuples
Dumping data from LAST_TABLE to file: ./init_project/data/LAST_TABLE_data.sql
Written 2000000 bytes to ./init_project/data/LAST_TABLE_data.sql
Extracted records from table LAST_TABLE: total_records = 276000 (avg: 1000 recs/sec)
Trying to connect to database: dbi:Oracle:MY_DB
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
Restoring foreign keys of table FIRST_TABLE...
Restoring indexes of table FIRST_TABLE...
...

ora2pg.conf settings:
FILE_PER_TABLE  1
DATA_LIMIT  3000
LONGREADLEN  7000000
JOBS  4
PARALLEL_TABLES  4

**Comment by darold** [comment]
If I understand well, the export of NEXT_TO_LAST_TABLE is ok but for table LAST_TABLE ora2pg reports the export of 276000 but you know that LAST_TABLE has 5 millions of rows. If you not use -d compmand line options what is the result of the progress bar on this table? I mean do you have a progress upper than 100%? And what is the real number og line in the exported file or PostgreSQL table? This could be an ANALYSE issue at Oracle side, Ora2Pg is looking for row count from statistics, not real count. Can you please perform a real row count on both side?

**Comment by calbiston** [comment]
I do not think it is a statistics issue because the output for the last table always stops on a boundary of 3000 records and always stops with the next dump of 3000 records after the next to the last table is finished.  (I rounded off the number of bytes written but not the running total of records written.)

**Comment by darold** [comment]
I think this is a bug on the progress bar, can you give me the result of a `select count(*) from table` on both side, Oracle and PostgreSQL?

**Comment by calbiston** [comment]
When I set JOBS to 1 and PARALLEL_TABLES to 1 the export (and import) of data is complete, and I get this output when using the TEST type and --count_rows:
ORACLEDB:LAST_TABLE:5128678
POSTGRES:last_table:5128678
ORACLEDB:NEXT_TO_LAST_TABLE:355259
POSTGRES:next_to_last_table:355259

The numbers for the next to the last table are essentially the same as in the unsuccessful export (and import), but the numbers for the last table are a factor of 18 more.  The Oracle data changed very little between runs.  It is also very suspicious that the number of records exported in the unsuccessful run is an exact multiple of 3000, which is the DATA_LIMIT.

The real name of NEXT_TO_LAST_TABLE immediately follows the real name of LAST_TABLE in dictionary order, so there is no table listed between them in the output.

**Comment by darold** [comment]
Sorry but I'm not really fluent with English speaking and I don't understand what you are explaining. Are you agree that this look to be a progress bar issue and that you have the same number of rows at both side, minus the life of the application between the counts and the migration, or are you explaining that there is a real rows count difference?

**Comment by calbiston** [comment]
There is a real difference between the number of rows.  There are rows missing that should be there, so the foreign key constraints cannot be enabled during the data import.  This occurs when I have parallel jobs and a file per table.  At the end, there are two jobs running, each dumping data for a different table.  When one of them is finished, the other one stops, even if it is not finished.

The two tables are named something like MY_TABLE_A and MY_TABLE_B.  It could be that when MY_TABLE_A is finished, its job looks for the next table to dump, which is MY_TABLE_B.  Since MY_TABLE_B is already being dumped by another job, it might get confused and stop MY_TABLE_B from dumping instead of letting it finish.

**Comment by darold** [comment]
I'm not able to reproduce this issue. All my tests using a huge table at end of export does not change anything. I have tested export to file and direct import to PostgreSQL, everything is working well. Ora2Pg has finished to export all tables and wait (several minutes for me) until the last table export is terminated too. There is 70 table exported and here is the last output:
```
[========================>] 10000000/10000000 rows (100.0%) Table TEST1 (50 sec., 200000 recs/sec)              
[========================>] 806555/806555 rows (100.0%) Table TEST2 (587 sec., 1374 recs/sec)     
[========================>] 36723118/36702401 rows (100.1%) on total estimated data (666 sec., avg: 55139 tuples/sec)
```

This does not appears to be an Ora2Pg issue but perhaps it is related to your operating system. What OS are you using? Do you have any messages reported by dmesg command?

Best regards,

**Comment by calbiston** [comment]
It only happens in debug mode.  It does not happen with the progress bar.

**Comment by darold** [comment]
Ok, I can confirm that debug mode doesn't wait the end of th last running table dump. Thanks a lot for your effort to be able to reproduce the issue, I've really appreciate your help. I will publish a patch asap.

Best regards,

**Comment by darold** [comment]
Last commit e03b031 might fix the issue. Let me know.

**Comment by calbiston** [comment]
While I cannot test this fix at the moment, I am sure that this commit fixes my issue.

**Comment by darold** [comment]
Ok, don't hesitate to reopen the issue if it is not solved.
