### ISSUE TITLE
Issues with Missing PK and FK Constraints.

### ISSUE THREAD

**Issue by nareneee** [darold/ora2pg#1822]
Hi Darold,

We are currently performing our migration in two phases: first for non-BLOB tables and then for BLOB tables, by specifying tables in the ALLOW parameter of the configuration file. However, we are encountering missing primary and foreign keys in PostgreSQL after the migration.
For instance, we generated the constraint files separately for non-BLOB and BLOB tables, and imported both files into PostgreSQL. Despite this, we still see mismatches in constraints on the Postgres side. When we disable the ALLOW parameter and run the migration for all tables together, the issue does not occur.

Could you please help us understand why PK and FK constraints are missing when we limit the tables using the ALLOW parameter?

Thank you for your support.

**Comment by darold** [comment]
Not reproducible in latest development code:
```
$ ora2pg -c config/ora2pg.conf -t TABLE -b tmp/ -a "COUNTRIES,REGIONS"
[2024-12-26 16:28:56] [========================>] 2/2 tables (100.0%) end of scanning.       
[2024-12-26 16:29:01] [========================>] 2/2 tables (100.0%) end of table export.S

$ cat tmp/CONSTRAINTS_output.sql 

ALTER TABLE countries ADD PRIMARY KEY (country_id);
ALTER TABLE countries ALTER COLUMN country_id SET NOT NULL;
ALTER TABLE regions ADD PRIMARY KEY (region_id);
ALTER TABLE regions ALTER COLUMN region_id SET NOT NULL;

$ cat tmp/FKEYS_output.sql 

ALTER TABLE countries DROP CONSTRAINT IF EXISTS countr_reg_fk;
ALTER TABLE countries ADD CONSTRAINT countr_reg_fk FOREIGN KEY (region_id) REFERENCES regions(region_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
```
