### ISSUE TITLE
[Question] Does the tool assess access to external schemas?

### ISSUE THREAD

**Issue by domedellolio** [darold/ora2pg#1823]
Team,

I'm currently reviewing the documentation to familiarize myself with the tool, and I have a couple of questions regarding its capabilities:

1. Does the tool detect if stored procedures or views are using external schemas within the same server?
2. Is it able to identify the use of DBLink?

Thank you for your help!

Best regards,

**Comment by darold** [comment]
Yes, ora2pg should mark any call to table@dblink as DBLINK in the assessment report details
