### ISSUE TITLE
Inner Query IN keyword is missing after converting Oracle procedure to Postgre procedure

### ISSUE THREAD

**Issue by rajatjha28** [darold/ora2pg#1824]
Sample Oracle query - 
CURSOR C_FACTURE_NEW IS SELECT * FROM FACTURE WHERE ACTIDGESTION = P_ACTIDGESTION AND 
     FACID IN (
    SELECT FACID FROM DOSRUBECHEANCIER WHERE **DOSID IN (**SELECT DOSID FROM DOSSIER WHERE ACTID = P_ACTIDGESTION) );

After converting to Postgre -
C_FACTURE_NEW CURSOR FOR SELECT * FROM FACTURE WHERE ACTIDGESTION = P_ACTIDGESTION AND
     FACID IN (
    SELECT FACID FROM DOSRUBECHEANCIER WHERE **DOSID(**SELECT DOSID FROM DOSSIER WHERE ACTID = P_ACTIDGESTION) );

**Comment by darold** [comment]
Commit 4b0e8c7 fixes this issue.
