### ISSUE TITLE
FTS_index issue

### ISSUE THREAD

**Issue by nareneee** [darold/ora2pg#1829]
Hello Darold,

We are currently migrating BLOB objects using the lo_import method, which results in the data type being OID. However, I am encountering difficulties in creating a full-text search (FTS) index on the OID data type. I couldn’t find any specific parameter in the ora2pg configuration file to address this issue.

Could you please help me with this?

**Comment by darold** [comment]
Usually BLOBs are binary objects so using FTS on it is probably useless. What type of document do you stored as large object? If they are text like documents and you want to use FTS on it, you can not do that with large objects. Large objects are stored in an internal table called pg_largeobject and with FTS you need to add a tsvector columns which is not possible here.
