### ISSUE TITLE
Error occuring during export with type COPY

### ISSUE THREAD

**Issue by angelcavina** [darold/ora2pg#184]
Hello
I'm exporting data from a oracle database and there is a table wich has 2 timestamp fields
here is the following error message:
_DEBUG: Sending COPY bulk output directly to PostgreSQL backend
FATAL: ERROR:  invalid input syntax for type timestamp: "lnegreiros"
CONTEXT:  COPY interface_file, line 110, column update_date: "lnegreiros"_

According with the message "lnegreiros" seems to be treated as a timestamp type but is just a value of a char field, not a field.

**Comment by darold** [comment]
Are you using latest development code? There was bugs fix on data export since latest release.

**Comment by angelcavina** [comment]
hm , yes I'm using the latest version.
I think I found the problem
In this table there is a char field wich has a path value "C:\development\ENG-Deploy\folders\eng_pfzt_in\" 
I changed "\" by "/" and its not throwing that error anymore

**Comment by darold** [comment]
Please use latest development code, I think this issue have been solved. You can get it as follow:
```
wget https://github.com/darold/ora2pg/archive/master.zip
```
Let us know.

**Comment by darold** [comment]
Do you have any feedback on this issue?
