### ISSUE TITLE
MySql Doubles are being set to bigint in PG15

### ISSUE THREAD

**Issue by SpootDev** [darold/ora2pg#1843]
ora2pg: v23.2
Percona Server: 8.0.36-28.1.el7

Using these settings in my conf file:
EXPORT_SCHEMA = YES
EXPORT_DATA = YES
TYPE = TABLE, VIEW
INDEXES_RENAMING = YES
DISABLE_PARTITION = YES
USE_UNACCENT 0
USE_LOWER_UNACCENT 0

MySql Doubles are being set to bigint in PG15.  Everything I read says that DATE_TYPE default is to do double precision, so I'm a bit confused on what I'm missing.

Currently using a very long MODIFY_TYPE variable to get around my issue.

**Comment by darold** [comment]
I can not reproduce. For exmaple:
```
CREATE TABLE actor (
  actor_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  price DOUBLE NOT NULL,
  PRIMARY KEY  (actor_id),
  KEY idx_actor_last_name (last_name)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
is well translated into
```
CREATE TABLE actor (
        actor_id smallserial,
        first_name varchar(45) NOT NULL,
        last_name varchar(45) NOT NULL,
        last_update timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        price double precision NOT NULL,
        "key" IDX_ACTOR_LAST_NAME
) ;
```
