### ISSUE TITLE
ora2pg cannot connect  to postgresql 

### ISSUE THREAD

**Issue by Neurozone** [darold/ora2pg#1846]
PG_DSN is set

`PG_DSN  dbi:Pg:dbname=xxxx;host=127.0.0.1;port=5432
PG_USER xxxx
PG_PWD  xxxx
`
but:

`postgres@postgres02-intern: [/var/lib/postgresql] 15:41:41$ ora2pg -t INSERT  --pg_dsn ${PG_DSN} --pg_user xxxx --pg_pwd=xxxx
[2024-12-06 15:43:24] [========================>] 44/44 tables (100.0%) end of scanning.
FATAL: 1 ... connection to server at "127.0.0.1", port 5432 failed: fe_sendauth: no password supplied
Aborting export...
`

Do I miss something ?

**Comment by darold** [comment]
I can not reproduce the problem, maybe you have characters in the password that are interpreted by the shell. You should enclose the parameter values with single quotes.
