### ISSUE TITLE
Exported indexes but did not import indexes to destination Postgres database.

### ISSUE THREAD

**Issue by babloo2642** [darold/ora2pg#1848]
I'm using ora2pg for a long period of time to convert tables only.  ora2pg made my life so easy!! : )
Now I would like to add indexes of those tables to export/import.

My environment details:
Linux 7.9
Ora2Pg version: 23.1
Source Database: Oracle 19c
Destination Database: Postgres 13

Directives that I did not change are:
EXPORT_SCHEMA                1
CREATE_SCHEMA	                1
COMPILE_SCHEMA	        0
TYPE 		                        TABLE, COPY
USE_TABLESPACE		0
FTS_INDEX_ONLY	                1
USE_UNACCENT		        0

Please find the changes that I made to include indexes to export/import.

I have enabled below directives:

CONTEXT_AS_TRGM           1
DROP_INDEXES                    1
USE_INDEX_OPCLASS        1
DEFER_FKEY                        1
FKEY_DEFERRABLE             1
PKEY_IN_CREATE                1
FKEY_ADD_UPDATE            always
KEEP_PKEY_NAMES            1
#SKIP fkeys pkeys ukeys indexes checks (I used this directive in the past to skip fkeys pkeys ukeys indexes checks but now I'm not skipping anything as shown )

After making the above changes, I see that indexes are being induced in export as shown below:

[2024-12-12 18:59:45] Dropping indexes of table MY_TABLE...
[2024-12-12 19:00:08] Restoring indexes of table MY_TABLE...
[2024-12-12 19:00:08] Total time to export data from 2 tables (0 partitions, 0 sub-partitions) and 58352 total rows: 40 wallclock secs ( 0.04 usr  0.03 sys + 13.59 cusr  2.25 csys = 15.91 CPU)
[2024-12-12 19:00:08] Speed average: 1458.80 rows/sec

Export completed without any errors but it only imported tables to destination Postgres database. I see indexes are empty.

Please help me if I miss anything here to import indexes to destination Postgres database.

Thanks in advance!

**Comment by darold** [comment]
Are you sure that the two tables have indexes in Oracle? Ora2Pg might export indexes in file /tmp/INDEXES_output.sql if you use the following command:
```
ora2pg -c config/ora2pg.conf -t TABLE -b /tmp -o output.sql
```
