### ISSUE TITLE
Tablespace issue with import_all

### ISSUE THREAD

**Issue by gleu** [darold/ora2pg#185]
The import_all.sh script, created by ora2pg, uses the --single-transaction CLI for psql. It usually works fine, except for tablespaces. You cannot embed a CREATE TABLESPACE statement in a transaction. Thus the script fails when it tries to execute the tablespace.sql script.

**Comment by darold** [comment]
This is now fixed in commit 3af11c2. Thanks Guillaume.

**Comment by gleu** [comment]
Thanks, I can confirm it's now working.
