### ISSUE TITLE
PK and UK issue with import_all

### ISSUE THREAD

**Issue by gleu** [darold/ora2pg#186]
ora2pg doesn't fetch the primary key index name, or at least, doesn't use it for the primary key creation on PostgreSQL. So PostgreSQL automatically generates the index name. That index name might not be the same than the one on Oracle. Unfortunately, the tablespace SQL script tries to move the indexes on the right tablespace, but it uses the Oracle name, making the script fails.

See both files from a migration of the HR example database:
[table.txt](https://github.com/darold/ora2pg/files/222308/table.txt)
[tablespace.txt](https://github.com/darold/ora2pg/files/222309/tablespace.txt)

**Comment by darold** [comment]
The behavior you are looking for is controlled by the KEEP_PKEY_NAMES configuration directive. When enabled, Ora2Pg use the index names used in Oracle.

**Comment by gleu** [comment]
Thanks. Completely overlooked that part.
