### ISSUE TITLE
any way to specify multiple schemas?

### ISSUE THREAD

**Issue by dlenski** [darold/ora2pg#190]
With the `-n` option or `SCHEMA` in the configuration file, it's possible to specify a *single* schema from which to extract data, but it doesn't seem to be possible to specify a *list* of multiple schemas to visit.

The database I am trying to convert has multiple schemas (let's say, `XYZ_STUFF`, `XYZ_ADMIN`, `XYZ_DATA`) and if I run `ora2pg -t SHOW_REPORT` without specifying a single schema, it takes an extremely long time to run, so instead I use:

```
ora2pg -t SHOW_REPORT -n XYZ_STUFF
ora2pg -t SHOW_REPORT -n XYZ_ADMIN
ora2pg -t SHOW_REPORT -n XYZ_DATA
```

This is not so ideal because all the schemas are basically one database and I would like to export them all together.

An alternative approach would be if I could list all of the objects in the `ALLOW` list with their fully qualified names (`XYZ_ADMIN.TABLE1 XYZ_STUFF.VIEW17 …`).

Is this possible to do with ora2pg currently?

**Comment by darold** [comment]
No it is not possible to choose a list of schema, you can just choose one schema or all schema.

To make a report on all schema, without system or Oracle module schema, just undefined the SCHEMA directive in the configuration file.

Best regards,
