### ISSUE TITLE
Wrong SELECT replacement with PERFORM in plsql

### ISSUE THREAD

**Issue by dezdechado** [darold/ora2pg#191]
Wrong SELECT replacement with PERFORM in statements like:
`INSERT INTO ... SELECT ... FROM ...;`

I'm not sure how to fix it in the right way but at the moment i just changed the line
`if ( ($class->{type} ne 'QUERY') && ($class->{type} ne 'VIEW') ) { `
with
`if ( ($class->{type} ne 'QUERY') && ($class->{type} ne 'VIEW') && ($str !~ /\bFROM\b/isg) ) {`
in file  lib\Ora2Pg\PLSQL.pm

**Comment by darold** [comment]
Hi,

Unfortunately this will solves the issue in your case but will break lot of other cases.  Last commit 07557ee might solves your issue and preserve other case.

Let me know,

**Comment by dezdechado** [comment]
Yes, it works. Thanks!
