### ISSUE TITLE
Wrong replacement of "= null" in pl/sql

### ISSUE THREAD

**Issue by dezdechado** [darold/ora2pg#192]
All "x = NULL" clauses are converted by ora2pg to "x IS NULL" ( line `$str =~ s/(?!:)(.)=\s*NULL/$1 IS NULL/igs;` in PLSQL.pm )
Hence, statement 
`UPDATE SOME_TABLE SET SOME_FIELD = NULL`
is mistakenly replaced with
`UPDATE SOME_TABLE SET SOME_FIELD IS NULL`
What the replacement has been intended for?

**Comment by darold** [comment]
Last commit b8053f4 might fix this issue.

**Comment by dezdechado** [comment]
Yes, it is. Thanks!
