### ISSUE TITLE
Wrong converting of procedures with out (or inout) arguments

### ISSUE THREAD

**Issue by dezdechado** [darold/ora2pg#195]
E.g.
`CREATE PROCEDURE  SomeFunc(arg1 OUT INTEGER) IS
BEGIN
END;
`
is converted to
`CREATE OR REPLACE FUNCTION somefunc (arg1 OUT integer)  RETURNS integer AS $body$
BEGIN
END;
$body$
LANGUAGE PLPGSQL
;`
Functions with out (or inout) arguments in PostgreSql shouldn't have RETURNS statement. Right conversion in our case would be:
`CREATE OR REPLACE FUNCTION somefunc (arg1 OUT integer)  AS $body$
BEGIN
END;
$body$
LANGUAGE PLPGSQL
;`

**Comment by darold** [comment]
Fixed in commit ebe3113.
