### ISSUE TITLE
Removing of 'TYPE IS RECORD' from output

### ISSUE THREAD

**Issue by dezdechado** [darold/ora2pg#196]
Let's we have in Oracle package
`CREATE PACKAGE MY_PKG AS
TYPE MyRecord IS RECORD
( Code INTEGER,
  Type INTEGER);
PROCEDURE MyProc( data MyRecord  )...`
Declaration of type MyRecord is complete removed from ora2pg output. It seems it could be easily converted as
 `CREATE TYPE MY_PKG.MyRecord AS
( Code INTEGER,
  Type INTEGER);`
If it's impossible by some reason, can it at least presents in the output to simplify manual modifications?

**Comment by darold** [comment]
Commit 1a37552 might solves this issue.

**Comment by darold** [comment]
Commit 9835be9 fix same issue from input file.
