### ISSUE TITLE
Varchar column containing numeric data

### ISSUE THREAD

**Issue by castle101** [darold/ora2pg#197]
Hi,

I have a table with a varchar column that contains numeric data, specifically a single zero. When ora2pg extracts this it replaces the numeric with a new line character. This then fails to import as the column has a NOT NULL constraint. The issue only occurs when a zero is used, other numeric values are fine. The following simple test case demonstrates the issue -

In Oracle

```
create table test_case(a number not null,b varchar2(10) not null, c number not null) ;

insert into test_case values (1,0,2);

commit ;
```

In Postgres

`create table test_case(a integer not null,b character varying(10) not null, c integer not null) ;
`

ora2pg fails with -

```
 Dumping data from table TEST_CASE into PostgreSQL...
Setting client_encoding to UTF8...
DEBUG: Formatting bulk of 10000 data for PostgreSQL.
DEBUG: Creating output for 10000 tuples
DEBUG: Sending COPY bulk output directly to PostgreSQL backend
DBD::Pg::db pg_putcopyend failed: ERROR:  null value in column "b" violates not-null constraint  
CONTEXT:  COPY test_case, line 1: "1	\N	2" at /usr/local/share/perl5/Ora2Pg.pm line 10577.
FATAL: ERROR:  null value in column "b" violates not-null constraint 
```

Thanks

**Comment by darold** [comment]
This issue have been fixed.
