### ISSUE TITLE
Restoring foreign keys fails after COPY from MySQL with direct Pg connection

### ISSUE THREAD

**Issue by SebAlbert** [darold/ora2pg#198]
I get the following error message when COPYing data from MySQL with a direct Pg connection using DROP_FKEY 1

```
Restoring foreign keys of table group_role...
DBD::Pg::db do failed: ERROR:  syntax error at or near "INITIALLY"
LINE 1: ...KEY (roleid) REFERENCES roles(role_id) ON UPDATE  INITIALLY ...
                                                             ^ at /usr/local/share/perl5/Ora2Pg.pm line 4861.
```

However, the initial creation of those foreign keys when copying the DDL via ora2pg had been successful. It seems that only in COPY mode this part of the FK info is not retreived correctly, so that the FK restauration misses the UPDATE_RULE from the information_schema.

**Comment by darold** [comment]
Hi,

Commit e3ff804 might solves this issue.

Best regards
