### ISSUE TITLE
Statement "commit" inside function's body should be commented

### ISSUE THREAD

**Issue by aleksaan** [darold/ora2pg#201]
Postgres doesn't support more one transaction in function.  The function is the one big transaction. In addition a syntax of oracle statement "begin" has differences from postgres-style.

**Comment by darold** [comment]
COMMIT call are not removed automatically by Ora2Pg, event if this is something easy to perform, because the logic of the function need to be changed. By keeping the keyword, you will be warn when you'll try to import the function.

**Comment by darold** [comment]
On the BEGIN syntax differences, please explain in detail what you mean, with some examples.

**Comment by aleksaan** [comment]
I mean BEGIN with a label. See syntax in a docs. 
Oracle: Begin <Label> 
Postgres:  <Label> Begin

**Comment by darold** [comment]
Can't find any example of labeled BEGIN statement or perhaps you was talking about named block? I you have an example things might be easiest to understand.
