### ISSUE TITLE
Wrogn conversion oracle timestamp-function

### ISSUE THREAD

**Issue by aleksaan** [darold/ora2pg#202]
Timestamp-function in a body of user-function converse to a localtimestamp postgres function. But localtimestamp isn't the same like timestamp in Oracle.  Localtimestamp contains time of commit transaction. So several localtimestamp in a different places in the same function will have the same value regardless of real time of their executions. The correct conversion is to clock_timestamp().
In example, behavior timestamp functions in Postgres:
INFO:  transaction_timestamp: 2016-05-31 14:29:05.844873+03
INFO:  statement_timestamp:   2016-05-31 14:29:05.844873+03
INFO:  clock_timestamp:       2016-05-31 14:29:05.844873+03
INFO:  timeofday:             Tue May 31 14:29:05.844873 2016 MSK
INFO:  now:                   2016-05-31 14:29:05.844873+03
INFO:  -------------5 seconds delay-------------
INFO:  transaction_timestamp: 2016-05-31 14:29:05.844873+03
INFO:  statement_timestamp:   2016-05-31 14:29:05.844873+03
INFO:  clock_timestamp:       2016-05-31 14:29:10.852473+03
INFO:  timeofday:             Tue May 31 14:29:10.852473 2016 MSK
INFO:  now:                   2016-05-31 14:29:05.844873+03

**Comment by darold** [comment]
SYSDATE is converted to LOCALTIMESTAMP
SYSTIMESTAMP  is converted to CURRENT_TIMESTAMP

Other functions, CURRENT_DATE, CURRENT_TIMESTAMP and LOCALTIMESTAMP are kept untouched. 

I don't know about a TIMESTAMP() function, can you point me to a link explaining this?

**Comment by aleksaan** [comment]
Sorry. its my mistake.  I mean SYSDATE-function.

**Comment by darold** [comment]
Commit 520252e fix this issue.
