### ISSUE TITLE
replacement of raise_apllication_error doesn't handle all variants

### ISSUE THREAD

**Issue by dezdechado** [darold/ora2pg#205]
`# Replace raise_application_error by PG standard RAISE EXCEPTION
$str =~ s/\braise_application_error\s*\(\s*[\-\+]*\d+\s*,\s*(.*?)\);/RAISE EXCEPTION $1;/igs;`
It is expected that code of error is number, but it could be a variable: `raise_application_error(error_code,error_msg);`
And, if the message is not direct text but variable, it would be awesome to automatically replace it like  `raise exception '%', var;`

**Comment by darold** [comment]
Commit 47009b9 might fix this issue.

**Comment by dezdechado** [comment]
Great! It seems to be right. Thanks!

**Comment by dezdechado** [comment]
Correction. It seems there is no need in block "# and then rewrite RAISE EXCEPTION concatenations" anymore

**Comment by darold** [comment]
Can you explain more the last comment and give en exemple?

**Comment by dezdechado** [comment]
Originally, `raise_application_error(-20000, 'here ' || ' could be ' || 'concatenations' )` was replaced with `raise exception 'here ' || ' could be ' || 'concatenations'` what is wrong for PG. So, there was need to rewrite raise exception with concatinations to make it work. 
Now it is replaced with `raise exception '%', 'here ' || ' could be ' || 'concatenations'`. And it works just fine. Hence there is no need to replace such concatenations anymore.

**Comment by darold** [comment]
That's right, commit 8b26f20 remove rewrite of concatenation in RAISE EXCEPTION.

Regards,
