### ISSUE TITLE
Value too long for char(1) field

### ISSUE THREAD

**Issue by barabaka** [darold/ora2pg#207]
Hi @darold, another issue that I found: I get the following error when exporting char(1) column that has value of "0".

DBD::Pg::st execute failed: ERROR:  value too long for type character(1) at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 10695.
FATAL: ERROR:  value too long for type character(1)

Oracle type: RECEIVE_ALERTS_P CHAR(1)
Postgresql type: receive_alerts_p character(1)

**Comment by darold** [comment]
It seems that one exported value is not a single character. Can you export this table to a file and check what is the value that is generating the error and report here the INSERT statement? Do you have the same behavior using COPY export type?

**Comment by barabaka** [comment]
This only happens for INSERT mode. I switched to using COPY now and it works well with it. 
For INSERT test case, there is only one row in my table and one char(1) column in it. Although there is no report from OraPg for exact column name in the error log, I don't think columns of other types can cause this. Here is the SQL export for this column from Oracle (from Oracle SQL Developer):
Insert into DG_USER (RECEIVE_ALERTS_P) values ('0');
Column is defined as RECEIVE_ALERTS_P CHAR(1);

**Comment by darold** [comment]
Thanks, I will try to reproduce the issue.

**Comment by darold** [comment]
Commit 7b2a3d3 fixes this issue.
