### ISSUE TITLE
FATAL: ERROR:  invalid input syntax for integer: "NULL"

### ISSUE THREAD

**Issue by kvnema** [darold/ora2pg#208]
While creating .sql file for exporting oracle data and migrating to postgresql we are facing below error for the first table.

Looking how to retrieve data from ARCHIVE_SOUP_CODE_TRNS...
Looking how to retrieve data from ARCHIVE_SOUP_CODE_TRNS...
Data type TIMESTAMP(6) is not native, searching on custom types.
Data type TIMESTAMP(6) is not native, searching on custom types.
Data type TIMESTAMP(6) is not native, searching on custom types.
Fetching all data from ARCHIVE_SOUP_CODE_TRNS tuples...
Dumping data from table ARCHIVE_SOUP_CODE_TRNS into PostgreSQL...
Setting client_encoding to UTF8...
Disabling synchronous commit when writing to PostgreSQL...
DEBUG: Creating output for 10000 tuples
DEBUG: Sending INSERT bulk output directly to PostgreSQL backend
DBD::Pg::st execute failed: ERROR:  invalid input syntax for integer: "NULL" at /opt/app/postgres/local/lib/perl5/site_perl/5.22.2/Ora2Pg.pm line 10683.
FATAL: ERROR:  invalid input syntax for integer: "NULL"
DBI::db=HASH(0x31d0f88)->disconnect invalidates 1 active statement handle (either destroy statement handles or call finish on them before disconnecting) at /opt/app/postgres/local/lib/perl5/site_perl/5.22.2/Ora2Pg.pm line 9935.
Aborting export...

**Comment by darold** [comment]
Thanks for the report, please use latest development code, last commit f497684 might solves this issue. Let me know.

Best regards,
