### ISSUE TITLE
DROP FKEY forgot to drop some foreign key

### ISSUE THREAD

**Issue by fguiet** [darold/ora2pg#212]
I am using DROP_FKEY option to drop foreign keys prior to load data.
Unfortunately, the export/import operation does not work because all foreign key are not dropped.

For instance (BGM_CONFIDENCE table) :
CREATE UNIQUE INDEX BGM_P.PK_CONFIDENCE ON BGM_P.BGM_CONFIDENCE
(NO_CAMPAGNE, NOM)
LOGGING
TABLESPACE BGM_D
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE SYNONYM BGM_S.BGM_CONFIDENCE FOR BGM_P.BGM_CONFIDENCE;

ALTER TABLE BGM_P.BGM_CONFIDENCE ADD (
  CONSTRAINT CK_CONFIDENTIALITE
  CHECK (CONFIDENTIALITE in ('C', 'D'))
  ENABLE VALIDATE,
  CONSTRAINT CK_NOM
  CHECK (NOM in ('CAMP', 'GEOL', 'SISM'))
  ENABLE VALIDATE,
  CONSTRAINT PK_CONFIDENCE
  PRIMARY KEY
  (NO_CAMPAGNE, NOM)
  USING INDEX BGM_P.PK_CONFIDENCE
  ENABLE VALIDATE);

ALTER TABLE BGM_P.BGM_CONFIDENCE ADD (
  CONSTRAINT FK_BGM_CONFIDENCE 
  FOREIGN KEY (NO_CAMPAGNE) 
  REFERENCES BGM_P.BGM_CAMPAGNE (NO_CAMPAGNE)
  ON DELETE CASCADE
  ENABLE VALIDATE);

I use the following command : ora2pg -t COPY -o datas.sql -b DATA/ -c ora2pg_bgm_update_data.conf
There is no DROP instruction in the script generated by ora2pg (datas.sql) for  FK_BGM_CONFIDENCE
NOTE : It does not occur to all the tables, some of them...

**Comment by darold** [comment]
What is the values of the ALLOW and EXCLUDE directives?

**Comment by fguiet** [comment]
ALLOW BGM_ANALYSE BGM_CAMPAGNE BGM_COMPOSITIONGEOL BGM_CONFIDENCE BGM_CONTACT BGM_CONTENUGEOL BGM_DOUBLON_CODES BGM_ECHANTILLON BGM_ELEMENT BGM_GEOLOGIE BGM_GEO_REFERENCEMENT BGM_GRANULO BGM_LAMES_MINCES BGM_LEXBENNE BGM_LEXCAROTTIER BGM_LEXCHALUT BGM_LEXCOMPOSITIONGEOL BGM_LEXCONTENUGEOL BGM_LEXCOULEUR BGM_LEXDRAGUE BGM_LEXELEMENT BGM_LEXFORAGE BGM_LEXGEOTECHNIQUE BGM_LEXGRAVIMETRE BGM_LEXIMPORTANCE_LITHO BGM_LEXLITHOLOGIE BGM_LEXLITHOTHEQUE BGM_LEXMAGNETOMETRE BGM_LEXMER BGM_LEXNAVIRE BGM_LEXORGANISME BGM_LEXPAYS BGM_LEXPLATEFORME BGM_LEXPLONGEE BGM_LEXPORT BGM_LEXPROJECTION BGM_LEXPROJET BGM_LEXQUALITE_DONNEES BGM_LEXRESPONSABILITE BGM_LEXSISMIQUE BGM_LEXSONAR BGM_LEXSONDEUSE BGM_LEXSTRATI BGM_LEXSYSTEME BGM_LEXTAMIS BGM_LEXTAMIS_SDN BGM_LEXUNITE BGM_LEXVIDEO BGM_LINEM BGM_LITHOLOGIE BGM_POINT BGM_STATION FG_BGM_LITHOLOGIE_AUDIT SISM_LEXDATA_PRODUCT SISM_LEXDIMENSION SISM_LEXFILTRE_FREQUENCE SISM_LEXFORMATSISMIQUE SISM_LEXMETHODE_SISMIQUE SISM_LEXOVERALL_QUALITY SISM_LEXRECEPTEUR SISM_LEXRESTRICTION SISM_LEXSUPPORT_ARCHIVAGE SISM_LEXTYPE_EQUIPEMENT SISM_LEXTYPE_SISMIQUE SISM_PROFIL SISM_PROFIL_DIFFU_ARCHIVAGE SISM_PROFIL_ENREGISTREMENT SISM_PROFIL_EQUIPEMENT SISM_SEADATANET_LINK

EXCLUDE PHD_.* FG_.* SAV_BGM_.*

**Comment by fguiet** [comment]
For information, just tried the following conf.

ALLOW BGM_CONFIDENCE

#EXCLUDE

Still no luck :(

**Comment by darold** [comment]
If the allowed/excluded object are all tables, use the object limitation syntax instead:

    OBJECT_TYPE[regex1 regex2 ...]

In you case:

```
ALLOW          TABLE[BGM_ANALYSE BGM_CAMPAGNE BGM_COMPOSITIONGEOL BGM_CONFIDENCE BGM_CONTACT BGM_CONTENUGEOL BGM_DOUBLON_CODES BGM_ECHANTILLON BGM_ELEMENT BGM_GEOLOGIE BGM_GEO_REFERENCEMENT BGM_GRANULO BGM_LAMES_MINCES BGM_LEXBENNE BGM_LEXCAROTTIER BGM_LEXCHALUT BGM_LEXCOMPOSITIONGEOL BGM_LEXCONTENUGEOL BGM_LEXCOULEUR BGM_LEXDRAGUE BGM_LEXELEMENT BGM_LEXFORAGE BGM_LEXGEOTECHNIQUE BGM_LEXGRAVIMETRE BGM_LEXIMPORTANCE_LITHO BGM_LEXLITHOLOGIE BGM_LEXLITHOTHEQUE BGM_LEXMAGNETOMETRE BGM_LEXMER BGM_LEXNAVIRE BGM_LEXORGANISME BGM_LEXPAYS BGM_LEXPLATEFORME BGM_LEXPLONGEE BGM_LEXPORT BGM_LEXPROJECTION BGM_LEXPROJET BGM_LEXQUALITE_DONNEES BGM_LEXRESPONSABILITE BGM_LEXSISMIQUE BGM_LEXSONAR BGM_LEXSONDEUSE BGM_LEXSTRATI BGM_LEXSYSTEME BGM_LEXTAMIS BGM_LEXTAMIS_SDN BGM_LEXUNITE BGM_LEXVIDEO BGM_LINEM BGM_LITHOLOGIE BGM_POINT BGM_STATION FG_BGM_LITHOLOGIE_AUDIT SISM_LEXDATA_PRODUCT SISM_LEXDIMENSION SISM_LEXFILTRE_FREQUENCE SISM_LEXFORMATSISMIQUE SISM_LEXMETHODE_SISMIQUE SISM_LEXOVERALL_QUALITY SISM_LEXRECEPTEUR SISM_LEXRESTRICTION SISM_LEXSUPPORT_ARCHIVAGE SISM_LEXTYPE_EQUIPEMENT SISM_LEXTYPE_SISMIQUE SISM_PROFIL SISM_PROFIL_DIFFU_ARCHIVAGE SISM_PROFIL_ENREGISTREMENT SISM_PROFIL_EQUIPEMENT SISM_SEADATANET_LINK]
```

```
EXCLUDE        TABLE[ PHD_.* FG_.* SAV_BGM_.*]
```

otherwise the regex will be applied to all object name.

**Comment by fguiet** [comment]
Not working :(

Here is the result with the following conf:

ALLOW TABLE[BGM_CONFIDENCE]
#EXCLUDE

-- Generated by Ora2Pg, the Oracle database Schema converter, version 17.4
-- Copyright 2000-2016 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:devboss.brgm.fr

SET client_encoding TO 'UTF8';

SET search_path = bgm_p, postgis, external_file;
\set ON_ERROR_STOP ON


SET search_path = bgm_p, postgis, external_file;
BEGIN;
ALTER TABLE bgm_confidence DISABLE TRIGGER USER;

\i DATA//BGM_CONFIDENCE_datas.sql

ALTER TABLE bgm_confidence ENABLE TRIGGER USER;
COMMIT;

**Comment by fguiet** [comment]
Another strange example if it can help : BGM_CAMPAGNE table has got 24 FK but only 23 are exported (missing FK_BGM_CAMPAGNE_PROJET...dunno why)

SET client_encoding TO 'UTF8';

SET search_path = bgm_p, postgis, external_file;
\set ON_ERROR_STOP ON


SET search_path = bgm_p, postgis, external_file;
BEGIN;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fl_campagne_lexqualite_donnee;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_systeme;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_stock_lexpays;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_stock_lexorgan;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_prelev_lexpays;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_prelev_lexorgan;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_pechant_lexpays;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_pechant_lexorgan;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_navire_lexnavire;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_lexplateforme;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_bh5_lexmer;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_bh4_lexmer;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_bh3_lexmer;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_bh2_lexmer;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_bh1_lexmer;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_anagra_lexpays;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_anagra_lexorgan;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_anaelmt_lexpays;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_anaelmt_lexorgan;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_anaelmj_lexpays;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_camp_anaelmj_lexorgan;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_campagne_port_depart;
ALTER TABLE bgm_campagne DROP CONSTRAINT IF EXISTS fk_bgm_campagne_port_arrivee;
ALTER TABLE bgm_campagne DISABLE TRIGGER USER;
ALTER TABLE bgm_confidence DISABLE TRIGGER USER;

\i DATA//BGM_CAMPAGNE_datas.sql
\i DATA//BGM_CONFIDENCE_datas.sql

ALTER TABLE bgm_campagne ENABLE TRIGGER USER;
ALTER TABLE bgm_campagne ADD CONSTRAINT fk_bgm_camp_anagra_lexpays FOREIGN KEY (pays_anagra) REFERENCES bgm_lexpays(code_pays) INITIALLY IMMEDIATE

**Comment by darold** [comment]
Looks like a bug, what is the result of the following query:

```
SELECT
    CONSTRAINT_NAME,R_CONSTRAINT_NAME
FROM DBA_CONSTRAINTS
WHERE CONSTRAINT_TYPE='R' 
    AND (REGEXP_LIKE(UPPER(TABLE_NAME),'^BGM_CONFIDENCE$'))
    AND STATUS='ENABLED'
```

it should export the name of all referential integrity constraints defined on table BGM_CONFIDENCE.

At least this is how Ora2Pg extract this information.

**Comment by fguiet** [comment]
CONSTRAINT_NAME                R_CONSTRAINT_NAME             
------------------------------ ------------------------------
FK_BGM_CONFIDENCE              PK_BGM_CAMPAGNE               
FK_BGM_CONFIDENCE              PK_BGM_CAMPAGNE               

2 rows selected.

**Comment by fguiet** [comment]
Remove a copy of the Oracle schema I try to export, now the query return one row :

BGM_P	FK_BGM_CONFIDENCE	R	BGM_CONFIDENCE	(WideMemo)	BGM_P	PK_BGM_CAMPAGNE	CASCADE	ENABLED	NOT DEFERRABLE	IMMEDIATE	VALIDATED	USER NAME			20/03/2013 16:50:54

**Comment by darold** [comment]
I have tried to reproduce your object definition and here are the results:

```
SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON


BEGIN;
ALTER TABLE bgm_confidence DROP CONSTRAINT IF EXISTS fk_bgm_confidence;

\i tmp/BGM_CONFIDENCE_data.sql

ALTER TABLE bgm_confidence ADD CONSTRAINT fk_bgm_confidence FOREIGN KEY (no_campagne) REFERENCES bgm_campagne(no_campagne) INITIALLY IMMEDIATE;
COMMIT;
```

What release of Ora2Pg are you using?
 
Please use latest development code from github and give it a try, I think you are using an old release of ora2pg. This may also fix the missing constraint (23 on 24).

**Comment by darold** [comment]
Here is the script I used:

```
CREATE TABLE BGM_CAMPAGNE (
	NO_CAMPAGNE NUMBER,
	LIBELE VARCHAR2(32)
);

CREATE TABLE BGM_CONFIDENCE (
	NO_CAMPAGNE NUMBER,
	CONFIDENTIALITE CHAR(1),
	NOM VARCHAR2(32)
);

CREATE UNIQUE INDEX PK_CONFIDENCE ON BGM_CONFIDENCE (NO_CAMPAGNE, NOM);
CREATE UNIQUE INDEX PK_CAMPAGNE ON BGM_CAMPAGNE (NO_CAMPAGNE);

ALTER TABLE BGM_CONFIDENCE ADD (
	CONSTRAINT CK_CONFIDENTIALITE CHECK (CONFIDENTIALITE in ('C', 'D')) ENABLE VALIDATE,
	CONSTRAINT CK_NOM CHECK (NOM in ('CAMP', 'GEOL', 'SISM')) ENABLE VALIDATE,
	CONSTRAINT PK_CONFIDENCE PRIMARY KEY (NO_CAMPAGNE, NOM) USING INDEX PK_CONFIDENCE ENABLE VALIDATE
);

ALTER TABLE BGM_CAMPAGNE ADD (CONSTRAINT PK_CAMPAGNE PRIMARY KEY (NO_CAMPAGNE) USING INDEX PK_CAMPAGNE ENABLE VALIDATE);
ALTER TABLE BGM_CONFIDENCE ADD (
	CONSTRAINT FK_BGM_CONFIDENCE FOREIGN KEY (NO_CAMPAGNE) REFERENCES BGM_CAMPAGNE (NO_CAMPAGNE)
	ON DELETE CASCADE
	ENABLE VALIDATE
);

```

**Comment by fguiet** [comment]
Ok my fault....sorry....ora2pg was using a connection the Oracle Development database (this database does not have the FK_BGM_CONFIDENCE constraint) and I was looking in the Oracle Production database....my mistake!!!

Sorry again! It works now

**Comment by darold** [comment]
That's ok, I have a test case now :-)
