### ISSUE TITLE
ora2pg breaks views with inplace views

### ISSUE THREAD

**Issue by dezdechado** [darold/ora2pg#213]
See line `$self->{views}{$view}{text} =~ s/\s*\bWITH\b\s+.*$//s;` in Ora2Pm.pm
For example, : `SELECT * FROM
(
  WITH TMP AS
  (
      SELECT 1 AS code FROM DUAL
  )
  SELECT * FROM TMP
) A`

**Comment by darold** [comment]
Commit 5a163a4 might fix this issue. Thanks.

**Comment by dezdechado** [comment]
It seems to work. Thanks!
