### ISSUE TITLE
wrong conversion of NCHAR

### ISSUE THREAD

**Issue by lgerlandsen** [darold/ora2pg#215]
I have an error in the creation of schema/tables/table.sql

NCHAR loses its length definition

In oracle columns are defined like this: (from (dba_tab_columns)

```
TABLE_NAME      COLUMN_NAME DATA_TYPE  DATA_LENGTH
--------------- ----------- ---------- -----------
FESTIVALER      AAR         CHAR                 4
PERSON          FDATO       NCHAR               24
PERSON          FMRK        NCHAR                3
PERSON          DDATO       NCHAR               24
PERSON          DMRK        NCHAR                3
PERSON          SJEKK       NCHAR                3
```

in table.sql the same columns appear like this

        aar char(4),

        fdato char,
        fmrk char,
        ddato char,
        dmrk char,
        sjekk char,

Oracle version 11.2.0.3
PostgreSQL version 9.5.3
ora2pg version 17.4 and latest from github july 29th 2016
DBD::Oracle 1.74

**Comment by darold** [comment]
Thanks for the report, last commit 38c6612 solves the issue.
