### ISSUE TITLE
Conversion of triggers: wrong inserting of `return new`;

### ISSUE THREAD

**Issue by dezdechado** [darold/ora2pg#216]
There is trigger in oracle: 
[Source_oracle_trigger.txt](https://github.com/darold/ora2pg/files/396879/Source_oracle_trigger.txt)

After conversion we have: 
[Converted_trigger.txt](https://github.com/darold/ora2pg/files/396881/Converted_trigger.txt)

The errors are obvious, I think ( there is shouldn't be the first `RETURN NEW;` and should be one more at the end of the body). 
Maybe, the simplest algorithm of inserting of `return new;` would be: 1) replace all of `return;` with `return new;`; 2) wrap all the body in one more `begin/end;` block; 3) add one more `return new;` at the end. For the example, it would be: 
[Proposed_conversion_trigger.txt](https://github.com/darold/ora2pg/files/396885/Proposed_conversion_trigger.txt)

**Comment by darold** [comment]
Commit 92477fe applies your solution. I've notice that parsing this trigger from file is broken, I will fix it later.

**Comment by dezdechado** [comment]
Good, but one correction. `$trig->[4]` starts with "DECLARE" block (I mean, "BEGIN" is not in it's first line). Hence there is should probably be `$trig->[4] =~ s/^\s*BEGIN/BEGIN\n  BEGIN/ism;` instead of `$trig->[4] =~ s/^\s*BEGIN/BEGIN\n  BEGIN/is;` (i.e. modifiers "m" should be applied to the regexp)

**Comment by dezdechado** [comment]
>  I've notice that parsing this trigger from file is broken, I will fix it later.

Well, yes, parsing of triggers from file is broken (issue #203). I thought you are not going to fix it. Have you changed your mind? It would be great! (I was going to try to do it myself sometime, but I'm not familiar with Perl, so...)

**Comment by darold** [comment]
It was on my todo list waiting on a work on triggers, this done now :-) I think it is fixed now, you will also no more lose the formatting with remove of newline. Your patch in previous note above have been applied to (m modifier).

**Comment by dezdechado** [comment]
Awesome! I will try it. Thanks!
