### ISSUE TITLE
Conversion of triggers: erasing of quotes from text

### ISSUE THREAD

**Issue by dezdechado** [darold/ora2pg#217]
If there is a string with quotes in trigger, the quotes are lost after the conversion. Eg: `CREATE OR REPLACE TRIGGER TAI_TEST_TABLE AFTER INSERT
ON TEST_TABLE FOR EACH ROW
declare
  json_str varchar2(30);
begin
  json_str := '{"code": 1}';
end;
/`
is converted as: `CREATE OR REPLACE FUNCTION trigger_fct_tai_test_table() RETURNS trigger AS $BODY$
declare
  v varchar(30);
BEGIN
  v := '{code: 1}';
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;`
As far as I can see, it affects only triggers.

**Comment by darold** [comment]
Last commit d0cc9da might fix this issue.

**Comment by dezdechado** [comment]
Yes, it does. Thanks!
