### ISSUE TITLE
DBD::Pg::db pg_putcopyend failed: ERROR:  extra data after last expected column

### ISSUE THREAD

**Issue by suBDavis** [darold/ora2pg#218]
I'm having an issue with the tool telling me I don't have enough columns in the recipient table.  The recipient table is created as so:

```
<redacted>=# \d+ redacted_audit
 identifier      | character varying(32)       |           | extended |              |
 last_mod_on     | timestamp without time zone |           | plain    |              |
 bug_last_mod_on | timestamp without time zone |           | plain    |              |
 audit_rid       | character varying(32)       |           | extended |              |
 catchall1       | character varying(32)       |           | extended |              |
 catchall2       | character varying(32)       |           | extended |              |
 catchall3       | character varying(32)       |           | extended |              |

```
Obviously the first 4 columns are supposed to be used, and I've added 3 more catchalls incase the first and second parts of my datetime have been interpreted as different columns.

Everything redacted from the data is a single word (no spaces).
```
Ora2Pg version: 17.4
Trying to connect to database: <REDACTED>
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
Retrieving table information...
[1] Scanning table<REDACTED> (226435265 rows)...
Trying to connect to database: <REDACTED>
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
Retrieving partitions information...


        Replacing table <REDACTED> as <REDACTED>...
        Replacing table<REDACTED> as <REDACTED>...
Truncating table <REDACTED>...
        Replacing table <REDACTED> as <REDACTED>...
Looking how to retrieve data from <REDACTED>...
Fetching all data from<REDACTED> tuples...
Dumping data from table<REDACTED> into PostgreSQL...
Setting client_encoding to UTF8...
Disabling synchronous commit when writing to PostgreSQL...
DEBUG: Formatting bulk of 500000 data for PostgreSQL.
DEBUG: Creating output for 500000 tuples
DEBUG: Sending COPY bulk output directly to PostgreSQL backend
DBD::Pg::db pg_putcopyend failed: ERROR:  extra data after last expected column
CONTEXT:  COPY redacted_audit, line 1: "redacted       2004-10-22 04:00:12     2015-05-20 18:24:33     redacted" at /usr/local/share/perl/5.18.2/Ora2Pg.pm line 10616.
ERROR (log error enabled): ERROR:  extra data after last expected column
CONTEXT:  COPY redacted_audit, line 1: "redacted       2004-10-22 04:00:12     2015-05-20 18:24:33     redacted"
Extracted records from table <REDACTED> total_records = 500000 (avg: 5319 recs/sec)
```
I'm sure there will be other things to check, but I don't quite know what that is.  I have issues frequently where using replace_query returns the specified columns in reverse or jumbled order, so I have to re-create my table to accept the returned columns in the random jumbled order.

I don't know how to specify the mapping between replace_query and the recipient table.

**Comment by suBDavis** [comment]
I recognize this looks like a problem with pg_putcopyend, but I was not able to find any related bugs, and something this catastrophically bad would have been brought up somewhere.  So I figured it might involve the interaction with ora2pg.

**Comment by darold** [comment]
What is the value of the ora2pg.conf directive REPLACE_COLS and the description of the table in the Oracle side?

**Comment by suBDavis** [comment]
Unfortunately I can't give you the oracle table description.
REPLACE_COLS is unset.  I'll set the correct mappings with that and update this issue.

**Comment by darold** [comment]
I ask that because I've though that you do not have the same number of column on both side, am I wrong? If they are the same you don't have to use REPLACE_COLS.

**Comment by suBDavis** [comment]
I've determined that this is perhaps not an issue, and my understanding of the tool is incorrect.  I was trying to do a REPLACE_QUERY that involved a join to another table in oracle, which returned columns from both the original table and the join.  I don't think this is supported behavior, because the columns I got from the join were the ones being complained about as "extra", and getting rid of them made everything work again.

However, I really need those join columns.  I have read-only access to oracle, so creating a view or something on the oracle side is out of the question.

Is there a quick and dirty way to do this?

Thank you

**Comment by darold** [comment]
This is something that can effectively be done using the REPLACE_QUERY directive. The only thing is that the resulting fields must match the columns in the PostgreSQL destination table. If you need more help and want privacy you can send a message to my private email gilles AT darold DOT net and join your query in REPLACE_QUERY and PostgreSQL table definition. I'll take a look on what's wrong on your Ora2Pg use.

**Comment by suBDavis** [comment]
Thanks very much.  I'll give it a go myself, and message you if it doesn't work out.

**Comment by jacksparrow414** [comment]
I had the same problem, I set REPLACE_COLS, but it didn't work.Could you guys give a simple example?
