### ISSUE TITLE
Error in converting pl/sql

### ISSUE THREAD

**Issue by dezdechado** [darold/ora2pg#219]
Regular expression `while ($str =~ s/(UPDATE.*)\s+IS NULL(\s*(?!WHERE)([^;]+))/$1 = NULL$2/is) {};` in plsql.pm should be mo strict ( eg `(\bUPDATE\b[^;]+)\s+IS NULL(\s*(?!WHERE)([^;]+))` ). Check it on `REC.UPDATE_CODE := 100;
 IF ( data_source is NULL ) then
   ...
 end if;` or ` UPDATE MY_TABLE SET CODE = 1 WHERE CODE = 1;
 IF ( data_source is NULL ) then
   ...
 end if;`

**Comment by darold** [comment]
Right, commit 9d740dc fix this issue.

**Comment by dezdechado** [comment]
Thanks!
