### ISSUE TITLE
Ora2pg support for different languages

### ISSUE THREAD

**Issue by venkatabn** [darold/ora2pg#220]
Hi,

I would like to know if there is any restriction on languages supported by ora2pg ?

If i have tables in Oracle with data in Japanese or Chinese characters, the data migration would fail ?

Please help !

Regards,
Ven.B

**Comment by darold** [comment]
Hi,

No it should not fail. If you use the default encoding (aka do not set NLS_* and CLIENT_ENCODING configuration directives in ora2pg.conf) everything will be exported and imported using UTF8. You will just need to set client_encoding in your application to the corresponding Japanese or Chinese character encoding.

Best regards,

**Comment by venkatabn** [comment]
Thank you very much for confirmation.
