### ISSUE TITLE
ora2pg using non-root 

### ISSUE THREAD

**Issue by mansijatin** [darold/ora2pg#222]
Using a normal account (non-root) in  RHEL Server release 6.8, we are getting the below exception

Can't locate Ora2Pg.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./ora2pg line 30.
BEGIN failed--compilation aborted at ./ora2pg line 30.

But, when we execute it using root, its runs fine. Please could you advice what could we be missing in our configuration / setup.

**Comment by josephelcid** [comment]
Hi,
Facing the same issue here. 
Can someone look into it?

**Comment by darold** [comment]
Hi,

Can you report here the result of the following command: `ls -la /usr/local/share/perl5/Ora2Pg.pm`

**Comment by mansijatin** [comment]
-r--r--r-- 1 root root 481235 Apr 21 14:40 /usr/local/share/perl5/Ora2Pg.pm

**Comment by darold** [comment]
I see that you are executing an ora2pg scrip locally (./ora2pg) how about using /usr/local/bin/ora2pg ? Does it still return the same error?

**Comment by mansijatin** [comment]
Yes same error. 

I think I found the missing configuration. The folder /usr/local/share/perl5 itself was missing the rights. It was set as below (output of getfacl perl5)

# file: perl5
# owner: root
# group: root
user::rwx
group::---
other::---

Aster we granted rights to others for read/execute recursively for this folder, the problem is now fixed. 

Thank you!

**Comment by darold** [comment]
Ok, unless this is a local configuration, I supposed that CentOs/RH do there best to prevent users to use Perl directly. I guess this is the same for other interpreters.

**Comment by josephelcid** [comment]
Thanks. Works for me too.
