### ISSUE TITLE
In Oracle Failover configuration: Infinite loop on ora_lob_read with ORA-25408: can not safely replay call

### ISSUE THREAD

**Issue by mzko** [darold/ora2pg#223]
In Oracle Failover configuration Infinite loop on ora_lob_read with ORA-25408: can not safely replay call
							while (1) {
								my $lobdata = $dbh->ora_lob_read($row[$j], $offset, $self->{chunk_size} );
								last unless (defined $lobdata && length $lobdata);
								$offset += $self->{chunk_size};
								$lob_content .= $lobdata;
							}

**Comment by darold** [comment]
Last commit 9fed49d should solve this issue.

**Comment by mzko** [comment]
Unfortunately it looks like it hangs inside ora_lob_read method. In my environment connection to Oracle from ora2pg very unstable.

**Comment by darold** [comment]
I'm afraid I can't do anything to stabilized your environment :-) Please set NO_LOB_LOCATOR to 0 and try to find the right value for LONGREADLEN you will not use this loop.

**Comment by mzko** [comment]
I'll try NO_LOB_LOCAOR=0 but it's difficult to look for right LONGREADLEN for many-tables and terabyte database.
Now I try to use TAF (http://search.cpan.org/~pythian/DBD-Oracle-1.74/lib/DBD/Oracle.pm) and it helps me to go farther. Also I'll try to do something with Oracle connection to keep it alive.

**Comment by darold** [comment]
I encourage you to see if TAF can be the solution an send me a patch, unfortunately I don't have an Oracle Failover environment to help on this part.

**Comment by mzko** [comment]
TAF is very unstable solution, so NO_LOB_LOCAOR=0 is the best way for me.

Best regards

**Comment by mzko** [comment]
I have found issue with NO_LOB_LOCAOR=1. According to (http://search.cpan.org/~pythian/DBD-Oracle-1.74/lib/DBD/Oracle.pm) for ora_pers_lob and CLOBs and NCLOBs the limit is 64k chars.
So my current situation:
1. NO_LOB_LOCAOR=0 - ora2pg hangs inside ora_lob_read because of connection lost (TAF is doubtful solution for this)
2. NO_LOB_LOCAOR=1 - ora2pg truncates CLOB fields with 64k (too early to rejoice)
3. Custom NO_LOB_LOCATOR=1 - I have changed ora_pers_lob to ora_piece_lob and try export data. As yet it looks like there is no connection lost and CLOB fields are Ok.

**Comment by darold** [comment]
The third solution generate a core dump during BLOB data export. I think that you need to use NO_LOB_LOCATOR = 1 and to set/increase LONGREADLEN in ora2pg.conf, that should solves the truncate.

**Comment by mzko** [comment]
- The third solution generate a core dump during BLOB data export.

In my case all works fine and I successfully used this solution. (CentOS 7, DBD-Oracle-1.75_2, perl-5.18.2)

In ora2pg:
			`if ($self->{no_lob_locator}) {
				$sth = $dbh->prepare($query,{ora_piece_lob => 1, ora_piece_size => 5*1024*1024, ora_exe_mode=>OCI_STMT_SCROLLABLE_READONLY, ora_check_sql => 1}) or $self->logit("FATAL: " . $dbh->errstr . "\n", 0, 1);
			} else {
				$sth = $dbh->prepare($query,{ora_auto_lob => 0, ora_exe_mode=>OCI_STMT_SCROLLABLE_READONLY, ora_check_sql => 1}) or $self->logit("FATAL: " . $dbh->errstr . "\n", 0, 1);
			}`

- I think that you need to use NO_LOB_LOCATOR = 1 and to set/increase LONGREADLEN in ora2pg.conf, that should solves the truncate.

No, this is not works for CLOB fields. As described in  (http://search.cpan.org/~pythian/DBD-Oracle-1.74/lib/DBD/Oracle.pm):
_For CLOBs and NCLOBs the limit is 64k chars if there is no truncation, this is an internal OCI limit complain to them if you want it changed. However if you CLOB is longer than this and also larger than the 'LongReadLen' than the 'LongReadLen' in chars is returned.

It seems with BLOBs you are not limited by the 64k._

**Comment by darold** [comment]
Hi Paul,

I was able to reproduce this issue. I have rewritten and applied your pull request to current development code. Changes are in commit  e911ea9 together with a fix on parallel table data export. Thanks a lot for your help.

Best regards,
