### ISSUE TITLE
Got fatal error on COPY BLOB not null and empty column

### ISSUE THREAD

**Issue by Akvel** [darold/ora2pg#226]
Hi 

Steps
1. Create Oracle's table with column BLOB NOT NULL 
2. Insert empty BLOB
3. Export a scheme - you will got the  table with bytea NOT NULL column
4. Run COPY process and got the error

**Comment by darold** [comment]
There is a configuration directive for that since v17.4. If you want your empty BLOB to be exported as empty string to not break your not null constraints enable EMPTY_LOB_NULL. Please use latest development code and let me know if you have any issue.

**Comment by Akvel** [comment]
17.4 same error with any values of EMPTY_LOB_NULL (EMPTY_LOB_NULL 0, EMPTY_LOB_NULL 1)

**Comment by darold** [comment]
In a Oracle 12 I see that an empty_blob() column effectively returns NULL through DBD::Oracle, so EMPTY_LOB_NULL will not help. I will add a check to NOT NULL constraint on LOB columns and change empty lob to empty string or bytea in this case.

**Comment by darold** [comment]
Hi,

Last commit 099f7a9 will force ora2pg to export empty lob as string when the source column has a NOT NULL constraint and that EMPTY_LOB_NULL is not activated. Please use latest development code from github and let me know if that solves your issue.

Regards,
