### ISSUE TITLE
Characters modified when all things seem to indicate everything is UTF-8

### ISSUE THREAD

**Issue by garyevans** [darold/ora2pg#227]
Hi,

Not sure if this is the correct place to raise this (apologies if it's not).......

I have a utf-8 encoded file dumped from oracle (just insert statements) containing Korean characters called odata.sql.  The characters look fine when editing the file.  When I try and use ora2pg with type query, the Korean characters appear something similar to 'ì <84>ì<9e><90>ì <95>ë¶<80> í<94><84>ë <88>ì<9e>' in the output file.

Looking at the same character sequence in the input and then output file the hex values are:
input file: a084 ec9e 90ec a095 ebb6 8020 ed94 84eb
output file: 27c3 acc2 a0c2 84c3 acc2 9ec2 90c3 acc2

So there appears to be some sort of encoding issue.  The nls_lang and client_encoding settings in ora2pg.conf are commented out and not overridden in the environment and I'm using the following command:
**ora2pg -i 'all_sht_data_pg_by odata.sql' -t query -o test1.out**

I'm not sure why it's changing the encoding when everything is utf-8?

Thanks

**Comment by darold** [comment]
What is the result of command `locale` from the terminal where you are executing ora2pg?

**Comment by garyevans** [comment]
LANG=en_AU.UTF-8
LANGUAGE=en_AU:en_GB:en
LC_CTYPE="en_AU.UTF-8"
LC_NUMERIC=en_AU.UTF-8
LC_TIME=en_AU.UTF-8
LC_COLLATE="en_AU.UTF-8"
LC_MONETARY=en_AU.UTF-8
LC_MESSAGES="en_AU.UTF-8"
LC_PAPER=en_AU.UTF-8
LC_NAME=en_AU.UTF-8
LC_ADDRESS=en_AU.UTF-8
LC_TELEPHONE=en_AU.UTF-8
LC_MEASUREMENT=en_AU.UTF-8
LC_IDENTIFICATION=en_AU.UTF-8
LC_ALL=

**Comment by darold** [comment]
By default we force Perl to use utf8 output encoding by setting binmode to :utf8
What is result of command: `file -i all_sht_data_pg_by odata.sql` and the Perl version?

**Comment by garyevans** [comment]
Hi,

all_sht_data_pg_by odata.sql: text/plain; charset=utf-8

This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi

Thanks

**Comment by darold** [comment]
Please download latest development code from github and give it a try. Last commit babaa48 force the use of UTF8 at open call. Let me know.

**Comment by garyevans** [comment]
Downloaded and built version 17.4, noticed the language settings in the config file were not commented out (forced to utf8), but still getting the same result.

**Comment by darold** [comment]
If you have downloaded from the release page, please use git clone instead or the following command:

    wget   https://github.com/darold/ora2pg/archive/master.zip

install it and leave the language settings in configuration file commented.

Sorry if I misunderstood what you said and have already done that.

**Comment by garyevans** [comment]
Yes, I did a git clone.  Sorry, should have said 'commented out' not 'not commented out'.

**Comment by darold** [comment]
Ok, I was thinking that not all Perl IO, especially input, used UTF8 but this is not the case. Can you send to my private email gilles AT darold DOT net a representing part of the input file as gzipped attachment  to be able to reproduce the issue?

**Comment by garyevans** [comment]
I have sent a compressed file to you.

Thanks
Gary

**Comment by darold** [comment]
Thanks a lot Gary. Commit 276b7ab Fix Perl I/O encoding using open pragma instead of calling binmode.

Please make a git pull and give it a try.

**Comment by garyevans** [comment]
Great stuff,  that fixed the issue.  Thank you very much for resolving this so quickly.

**Comment by yafeishi** [comment]
Hi,darold:
   this question come again, the comment like this：user_group_id IS E'ç¨æ·ç¾¤ç»ID';
then i    git checkout 276b7ab. the comment is ok : user_group_id IS E'用户群组ID';

**Comment by darold** [comment]
I have removed the changes from head, it might works as expected now. Please use latest code and let me know.

Regards,

**Comment by yafeishi** [comment]
latest code is ok, Thank you very much
