### ISSUE TITLE
Ora2pg doesn't export schema ForeignKey constraint when connected as different DBA user

### ISSUE THREAD

**Issue by mzko** [darold/ora2pg#228]
In my config (cto - dba user, escto - common user):
ORACLE_USER	cto
# Oracle schema/owner to use
SCHEMA		escto

No any foreign key constraint are exported because of _foreign_key function use USER_CONSTRAINTS, USER_CONS_COLUMNS tables. These tables contains data only for cto user.

**Comment by darold** [comment]
In this case you have to connect as a DBA user and set USER_GRANTS to 0.

Keep SCHEMA to escto to only export this schema.

**Comment by mzko** [comment]
Of course I have used USER_GRANTS	0
_Set this to 1 if you connect as simple user and can not extract things
# from the DBA_... tables. It will use tables ALL_..._ 
But instead ALL_... you have used USER_... tables. And this is mistake.

**Comment by darold** [comment]
Ah ok, I understand now :-) YOur pull request has been applied.
