### ISSUE TITLE
Fatal: Crash when copy from oracle to file $self->{dbhdest} not defined line 2864

### ISSUE THREAD

**Issue by mzko** [darold/ora2pg#231]
# Set search path
		my $search_path = $self->set_search_path();
		if ($search_path) {
			$self->{dbhdest}->do($search_path) or $self->logit("FATAL: " . $self->{dbhdest}->errstr . "\n", 0, 1);
		}

**Comment by darold** [comment]
Last two commit, 61ff078 and a483c5a, solve this issue.
