### ISSUE TITLE
Schema name used in function index

### ISSUE THREAD

**Issue by tstiemerling** [darold/ora2pg#232]
I have a function defined in oracle which i use in an index, like so:

CREATE INDEX function_idx ON column(function(id,state));

when I export the schema without using the oracle schema name in postgres (ie, public schema),
I get the following in the indexs file:

CREATE INDEX function_idx ON column(schema.function(id,state));

Is there a way to turn this off (so I dont have to manually edit the file)?

**Comment by darold** [comment]
Hi,

I think you have enabled EXPORT_SCHEMA in the configuration file, if you don't want your function and tableand other object definition to be prefixed with their schema name, disable it.

Regards,

**Comment by tstiemerling** [comment]
hi, export_schema is 0, and this is the only place schema name still appears.
Thx

**Comment by darold** [comment]
Ok, in this case the index is defined like that in Oracle, ora2pg is just exporting his exact definition. If you have not reproduced the same schema architecture in PostgreSQL your only solution is to remove those prefixes by hand. A simple perl command can do the job easily after the ora2pg export:

```
perl -p -i -e 's/\bschema\.//g' schema/tables/INDEXES_table.sql
```

Regards,
