### ISSUE TITLE
mysql_fdw foreign table option error

### ISSUE THREAD

**Issue by yafeishi** [darold/ora2pg#233]
when i use export mysql table with type fdw, the create foreign table () option is incorret,like this:
 OPTIONS(schema 'weian', table 'wa_workplace');

config:
ORACLE_HOME //usr/local/mysql-5.6.17-linux-glibc2.5-x86_64/ 
ORACLE_DSN  dbi:mysql:host=localhost;port=31306;database=weian;
ORACLE_USER root  
ORACLE_PWD  root 
TYPE FDW

execute command:
ora2pg -m mysql -c ora2pg_fdw_ddl_weian.conf -o fdw_ddl_weian.sql

**Comment by yafeishi** [comment]
i change the source code in lib/Ora2pg.pm :
			#} elsif ($self->{is_mysql} && $self->{tables}{$table}{table_info}{connection}) {
		  } elsif ($self->{is_mysql}) {		

then the result is corret

**Comment by darold** [comment]
Hi,

Thanks for the report, commit 9973246 applied your patch.

Best regards,
