### ISSUE TITLE
Oracle spatial to Postgis

### ISSUE THREAD

**Issue by Martyxy** [darold/ora2pg#234]
Hello,
 could you please some of us help me?
I have a functional SQL query which works in Oracle Spatial, but does not work in PostGis.
What works in Oracle spatial:
CREATE TABLE mestske_komunikace AS
SELECT r.*
FROM lt_cze_5_0_points_sjtsk r, moravskoslezsky_kraj u
WHERE
 (SDO_GEOM.SDO_INTERSECTION(r.geom,u.geom,0.05) IS NOT NULL)
 AND
 (r.urban='1');
This returns me 
![image](https://cloud.githubusercontent.com/assets/23242280/19974586/445c54b0-a1e9-11e6-92a5-c3b9491098ac.png)

I have to change SDO_Interesection to ST_Intersection in Postgis.
But the script below does not works as should be. It shows me metropolitan road even in another region. Do you know why intersection doen not work in the Postgis?
And another question is, it show me roads in points and i would like to have the roads in lines, is it possible?
CREATE TABLE mestske_komunikace AS
SELECT r.*
FROM lt_cze_5_0_points_sjtsk r, moravskoslezsky_kraj u
WHERE
 (ST_Intersection(r.geom, u.geom) IS NOT NULL)
 AND
 (r.urban='1');

![image](https://cloud.githubusercontent.com/assets/23242280/19974515/0d3c5e6c-a1e9-11e6-8b2e-af94e1871683.png)

Thank you all for your answers.
PS: sorry for my english

**Comment by darold** [comment]
Hi, sorry but I can't help on this kind of question, this is more related to Postgis use than a issue of Ora2Pg. I guess you will have more chance to obtain an answer on a Postgis dedicated mailing list.

Best regards,
