### ISSUE TITLE
Database name should be given to psql

### ISSUE THREAD

**Issue by gleu** [darold/ora2pg#236]
When one use the -U command line option, the import_all.sh script uses it when it calls psql to check if the schema's owner exists. Unfortunately, it doesn't specify the database name. So, psql will use the username as the database name and if a database of that name doesn't exist, it will exit with an error.

This is on line 209 of the import_all.sh script.

**Comment by gleu** [comment]
BTW, this report comes from a thread on the french web forum: http://forums.postgresql.fr/viewtopic.php?pid=24261#p24261

**Comment by darold** [comment]
In this case I think the -U option need to be removed. The owner of the database must be set using the -o option and if the script is run as postgres user the problem will not appears. The other solution is to create the default database for the connection user. But here I think there is a confusion between the connection user and the owner of the database. There is no parameter to set a different connection database.

I will answer to the french forum.

Thanks.

**Comment by gleu** [comment]
Well, if you offer those options, they should work whatever happens or at least have a more adequate error message. What he tries to do looks sane to me.

**Comment by SebAlbert** [comment]
Maybe the environment variables PGDATABASE and PGUSER can help here. See https://www.postgresql.org/docs/9.6/static/libpq-envars.html
