### ISSUE TITLE
Add "Download" link somewhere on "http://ora2pg.darold.net/"

### ISSUE THREAD

**Issue by swvanlinge** [darold/ora2pg#239]
This seems to be the only place to put this...  It's really difficult to find where to download your tool when you first see it here:

http://ora2pg.darold.net/

Can you add a "Download" tab or a link to the download site somewhere under "Links"?

**Comment by darold** [comment]
The link to download is under the "get started..." button. I agree that it is not really visible so I have added a download link int the menu.

Thanks for the report.
