### ISSUE TITLE
mysql2pg char length is not correct

### ISSUE THREAD

**Issue by yafeishi** [darold/ora2pg#240]
in the mysql.pm , i found this:
	while (my $row = $sth->fetch) {
		$row->[2] = $row->[7] if $row->[1] =~ /char/i;

mysql:
+--------------+------------+-------------+-----------+--------------------------+------------------------+
| table_schema | table_name | COLUMN_NAME | DATA_TYPE | CHARACTER_MAXIMUM_LENGTH | CHARACTER_OCTET_LENGTH |
+--------------+------------+-------------+-----------+--------------------------+------------------------+
| trial        | test_dang  | tag         | char      |                        1 |                      3 |
+--------------+------------+-------------+-----------+--------------------------+------------------------+
1 row in set (0.00 sec)

at pg, length of the tag is  3.

**Comment by darold** [comment]
Hi,
I do not understand, for what I've tested a char(3) in mysql is exported as char(3) by ora2pg. Also the line you are pointing defined the lengh from column CHARACTER_OCTET_LENGTH, which is  `$row->[7]` in the ora2pg query.

Can you explain more what issue you are facing?

**Comment by yafeishi** [comment]
Hi darold
sorry for long time
i see this issue again:
in my mysql  env: the character_maximum_length is not equal character_octet_length:
```
+--------------+----------------------+-----------------+-----------+--------------------------+------------------------+--------------+------------+
| table_schema | table_name           | column_name     | data_type | character_maximum_length | character_octet_length | COLUMN_TYPE  | COLUMN_KEY |
+--------------+----------------------+-----------------+-----------+--------------------------+------------------------+--------------+------------+
| base         | bs_busi_access_param | ACCESS_PARAM_ID | bigint    |                     NULL |                   NULL | bigint(12)   | PRI        |
| base         | bs_busi_access_param | BUSI_ACCESS_ID  | bigint    |                     NULL |                   NULL | bigint(12)   |            |
| base         | bs_busi_access_param | PARAM_TYPE      | bigint    |                     NULL |                   NULL | bigint(1)    |            |
| base         | bs_busi_access_param | PARAM_NAME      | varchar   |                       60 |                    180 | varchar(60)  |            |
| base         | bs_busi_access_param | PARAM_CODE      | varchar   |                      256 |                    768 | varchar(256) |            |
| base         | bs_busi_access_param | PARAM_VALUE     | varchar   |                      512 |                   1536 | varchar(512) |            |
| base         | bs_busi_access_param | PARAM_VALUE_DEF | varchar   |                      512 |                   1536 | varchar(512) |            |
| base         | bs_busi_access_param | IS_NULL         | char      |                        1 |                      3 | char(1)      |            |
| base         | bs_busi_access_param | SORT            | bigint    |                     NULL |                   NULL | bigint(3)    |            |
| base         | bs_busi_access_param | CREATE_DATE     | datetime  |                     NULL |                   NULL | datetime     |            |
| base         | bs_busi_access_param | STATE_DATE      | datetime  |                     NULL |                   NULL | datetime     |            |
| base         | bs_busi_access_param | STATE           | char      |                        1 |                      3 | char(1)      |            |
| base         | bs_busi_access_param | REMARKS         | varchar   |                      512 |                   1536 | varchar(512) |            |
+--------------+----------------------+-----------------+-----------+--------------------------+------------------------+--------------+------------+
13 rows in set (0.06 sec)
```
because  the code : "$row->[2] = $row->[7] if $row->[1] =~ /char/i;"   , in pg env, char length is equal character_octet_length。 mysql  character  is utf8,   so i think  the code if need to judge the  mysql character?   

"CHARACTER_OCTET_LENGTH should be the same as CHARACTER_MAXIMUM_LENGTH, _except for multibyte character sets._" from https://dev.mysql.com/doc/refman/8.0/en/columns-table.html

**Comment by darold** [comment]
Thanks for the explanation, last commit c1844a4 might solve the issue.
