### ISSUE TITLE
ora2pg install : migrate mysql to postgres

### ISSUE THREAD

**Issue by zevenements** [darold/ora2pg#241]
Hello, is there a way to install ora2pg without the dependancy DBD::Oracle in the case of migration mysql to postgres ? thanks a lot

**Comment by darold** [comment]
Hum, I think you don't need to install DBD::Oracle in this case, just proceed directly to the normal ora2pg installation.

```
perl Makefile.PL
make
sudo make install
```

You will obtain a warning: `Warning: prerequisite DBD::Oracle  not found.` but this is just a warning.

Then using ora2pg justs works provides that you have DBD::MySQL intalled.

```
$ ora2pg -c config/ora2pg.conf -t SHOW_VERSION
WARNING: setting SCHEMA to MySQL database name sakila.
5.5.53-...
```
Of course the ORACLE_DSN must call the mysql DBI driver:

    ORACLE_DSN      dbi:mysql:host=localhost;database=sakila;port=3306

Regards,

**Comment by zevenements** [comment]
yes, that's work fine ! 

Now i have to check if the transform of blog image to bytea postgres have done a good job.
In postgres i have something like GIF89a\\266\\0035\\002\\367\\000\\000\\011\\012\\002\\005\\026&\\006\\0351\\015,\\025\\0316##\\034\\00 .....
but i don't know yet how to proove that's the good data.. 
bye !

**Comment by darold** [comment]
Using a Perl script it can be done easily:

```
#!/usr/bin/perl
use strict;

use DBI;
use DBD::Pg;

my $dbh = DBI->connect("dbi:Pg:dbname=dbtest", 'gilles', 'gilles');
my $sth = $dbh->prepare('SELECT byteadata_col from table_example WHERE id=1;');
$sth->execute();

my $image = '';
while (my @row = $sth->fetchrow()) {
        $image = $row[0];
}
$dbh->disconnect();

open(OUT, ">my_img.gif") or die "FATAL: $!\n";
print OUT $image;
close(OUT);
```

then look at my_img.gif

regards,

**Comment by zevenements** [comment]
yes, it's a good way to test !

Also, I tried  : 
copy (SELECT encode(image, 'hex') FROM matable WHERE id=5) TO '/repertoire/image.hex'
then on the serveur : xxd -p -r image.hex > image.gif

The result is ok : ora2pg has done a good job again :-)
