### ISSUE TITLE
Spelling fixes

### ISSUE THREAD

**Issue by gfa** [darold/ora2pg#242]
Hello

I'm packaging ora2pg for Debian, i found some spelling errors on Ora2Pg.pod, i'm attaching a patch that fixes most of them

thanks
[spelling-fixes.patch.txt](https://github.com/darold/ora2pg/files/623825/spelling-fixes.patch.txt)

**Comment by gfa** [comment]
thanks for applying the patch, here are some more (sorry my editor didn't catch them first)


[spelling-fixes.patch2.txt](https://github.com/darold/ora2pg/files/624116/spelling-fixes.patch2.txt)

**Comment by darold** [comment]
Applied too in commit a160972, don't worry there must still be some others miss-spelling issues, my english is pretty bad.
