### ISSUE TITLE
Make Oracle.pm optional

### ISSUE THREAD

**Issue by gfa** [darold/ora2pg#243]
Hello

If i want to use ora2pg with a mysql to pgsql db i shouldn't need to have DBD/Oracle.pm installed.

My main driver for this issue is to move ora2pg out of Debian's contrib to main, as libdbd-oracle-perl is the only non-free dependency it has,

if you make the load of Ora2Pg and/or DBD/Oracle.pm optional i could ship ora2pg in Debian main :)

thanks!

**Comment by darold** [comment]
Ok, I will change the default behavior of Ora2Pg to use input file instead of a connection to an Oracle database. I will update this issue when the work will be done.

**Comment by gfa** [comment]
Hi
I don't mean to push you, but can I ask for an ETA? 
debian freeze is tightening, if your update is close i'll wait for it, otherwise i'll publish to contrib as previous releases.

thanks

**Comment by darold** [comment]
Hi,

I've started to work on it yesterday. I think the work will be terminated this weekend.

**Comment by gfa** [comment]
You're awesome 😃

On December 14, 2016 5:37:36 PM GMT+08:00, Darold <notifications@github.com> wrote:
>Hi,
>
>I've started to work on it yesterday. I think the work will be
>terminated this weekend.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/darold/ora2pg/issues/243#issuecomment-266987699

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by darold** [comment]
Hi Gustavo,

Commit f2d48fd makes DBD::Oracle optional. Let me know if I miss something. I still have some patch to apply and I will get out a new release asap.

Regards,

**Comment by darold** [comment]
Release v18.0 has been published.
