### ISSUE TITLE
NLS_LANG=JAPANESE_JAPAN.JA16SJIS does not work?

### ISSUE THREAD

**Issue by bocap** [darold/ora2pg#244]
Hi,

This can be a missed of using but can have comments?

I am trying to convert data from Oracle encoding SJIS to PostgreSQL UTF-8 encoding .
The below is my related encoding environments.
when import to postgresql from output file of ora2pg, i get the an error.

while i comment out NLS_LANG in ora2pg.conf, it work fine.
But i wonder if NLS_NCHAR is JA16SJIS, so why NLS_LANG is set to JAPANESE_JAPAN.JA16SJIS, it did not work?
I want set client_encoding to SJIS when import to PostgreSQL, so the conversion to UTF-8 will operating in PostgreSQL.

import ERROR:

     psql:AA_output.sql:13: ERROR:  invalid byte sequence for encoding "SJIS": 0xa0 0
     CONTEXT:  COPY aa, line 1

Client Environments:

     # ora2pg -t SHOW_ENCODING
     Ora2Pg version: 17.6b
     Trying to connect to database: dbi:Oracle:host=oracle;sid=orcl
     Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
     Current encoding settings that will be used by Ora2Pg:
             Oracle NLS_LANG Japanese_Japan.JA16SJIS
             Oracle NLS_NCHAR JA16SJIS
             Oracle NLS_TIMESTAMP_FORMAT YYYY-MM-DD HH24:MI:SS.FF
             Oracle NLS_DATE_FORMAT YYYY-MM-DD HH24:MI:SS
             PostgreSQL CLIENT_ENCODING SJIS
             Perl output encoding ':utf8'
     Showing current Oracle encoding and possible PostgreSQL client encoding:
             Oracle NLS_LANG JAPANESE_JAPAN.JA16SJIS
             Oracle NLS_NCHAR JA16SJIS
             Oracle NLS_TIMESTAMP_FORMAT YYYY-MM-DD HH24:MI:SS.FF
             Oracle NLS_DATE_FORMAT YYYY-MM-DD HH24:MI:SS
             PostgreSQL CLIENT_ENCODING EUC_JIS_2004

     # env | grep LANG
     NLS_LANG=Japanese_Japan.JA16SJIS
     LANG=ja_JP.SJIS
     # grep -e ENCODING -e LANG /etc/ora2pg/ora2pg.conf | grep -v "#"
     NLS_LANG       Japanese_Japan.JA16SJIS
     CLIENT_ENCODING SJIS
     
     # cat AA_output.sql
     -- Generated by Ora2Pg, the Oracle database Schema converter, version 17.6b
     -- Copyright 2000-2016 Gilles DAROLD. All rights reserved.
     -- DATASOURCE: dbi:Oracle:host=172.16.4.249;sid=orcl
     
     SET client_encoding TO 'SJIS';
     
     TRUNCATE TABLE aa;
     
     COPY aa (id,name) FROM STDIN;
     1       ﾂつ
     1       ﾂ～
     1       \N
     \.

thanks,

**Comment by darold** [comment]
If you have encoding issues using output to file to export your data, just unset NLS_LANG and CLIENT_ENCODING to use default encoding (UTF8) and proceed to direct import to PostgreSQL by setting PG_DSN. The encoding issues are related to Perl file output, forcing UTF8 with open pragma doesn't seem to solve the problem. Direct import of data into PostgreSQL doesn't suffer of this problem, it is also much more speediest.

**Comment by bocap** [comment]
Many thanks for promptly response, sir

As your advise,  unset  NLS_LANG and CLIENT_ENCODING in ora2pg.conf could fix my problem now.
But does this mean that the conversion from SJIS (in Oracle database) to UTF8 is depend on Perl module?
I wonder if Perl module could not convert successfull some charaters (which does not include in conversion mapping of that module), so it could make interrupt in ora2pg conversion (in data extraction phase), is that right sir?

**Comment by darold** [comment]
I think that when you proceed to direct data import you don't have any encoding issue because Perl does not interact with the locale on the system. When using file export Perl might use the local environment to find output encoding. I've not taken too much time on this issue because direct import is the best way to migrate data, but I don't think it need additional Perl module to fix that we just have to force Perl to write data without any local conversion, Oracle have right done the work and produce data with utf8 encoding, this is Perl that is using wrong encoding when writing data to file.

**Comment by bocap** [comment]
Thanks for reply sir,

I will consider to direct data import method.
But i think like PostgreSQL, some characters Oracle might not convert successful from SJIS to UTF-8.
I will confirm when have time.

Thanks for your kindly support.
Best regards,
