### ISSUE TITLE
 ora2pg - Java Message Service (JMS) Type

### ISSUE THREAD

**Issue by joanna-xu** [darold/ora2pg#245]
Hello,

We plan to use ora2pg tool to migrate Oracle to PostgreSQL.  During the testing, while importing the content of the output.sql generated by ora2pg into PostgrSQL database, it terminated with the following error `ERROR:  type "aq$_jms_text_message" does not exist” for “user_data”` column with “AQ$_JMS_TEXT_MESSAGE” as type which couldn't be migrated to PostgreSQL.  My questions would be:  does it mean ora2pg miss to migrate this type for some reason?  what would be the solution to resolve it? 
```
psql -d wsp -U staging -W < /database/postgres/outputSTAGING.sql
Password for user staging:
SET
CREATE TABLE
CREATE TABLE
ALTER TABLE
CREATE INDEX
ERROR:  type "aq$_jms_text_message" does not exist
LINE 29:  user_data AQ$_JMS_TEXT_MESSAGE,
```

Thanks,
Joanna

**Comment by darold** [comment]
Hello joanna,

As said by Julien on pgsql-general last commit might solve this problem by excluding type starting with `aq$_`. If this is not the case, you can set the EXCLUDE directive as follow:
```
EXCLUDE        AQ\$_.*
```
and execute ora2pg again, that should help to not export these objects.

To answer to your question, the Oracle Stream objects must not be exported, they have no direct equivalent into PostgreSQL. To have the same feature with PostgreSQL I use replication slot and logical decoding but it depends on your Oracle Stream use.

**Comment by joanna-xu** [comment]
Hello Darold,

As suggested, I’ve tried and made both changes to ora2pg-17.6/lib/Ora2Pg.pm as the following:

Replace:

-    if (!$self->{is_mysql} && !$has_limitation && ($arr_type[$i] =~ /TABLE|SEQUENCE|VIEW|TRIGGER/)) {
With:
+  if (!$self->{is_mysql} && !$has_limitation && ($arr_type[$i] =~ /TABLE|SEQUENCE|VIEW|TRIGGER|TYPE/)) {

And …  Add:   EXCLUDE        AQ\$_.*

but still see the same output for the column “user_data AQ$_JMS_TEXT_MESSAGE” is included in the export file “outputR6_test.sql after executing ora2pg.

% ora2pg -u R6 -w R6 -o /u01/app/oracle/outputR6_test.sql
[========================>] 211/211 tables (100.0%) end of scanning.
[========================>] 211/211 tables (100.0%) end of table export.

CREATE TABLE ces_jms_queue_table (
        q_name varchar(30),
        msgid bytea NOT NULL,
        corrid varchar(128),
        priority bigint,
        state bigint,
        delay timestamp,
        expiration bigint,
        time_manager_info timestamp,
        local_order_no bigint,
        chain_no bigint,
        cscn bigint,
        dscn bigint,
        enq_time timestamp,
        enq_uid varchar(30),
        enq_tid varchar(30),
        deq_time timestamp,
        deq_uid varchar(30),
        deq_tid varchar(30),
        retry_count bigint,
        exception_qschema varchar(30),
        exception_queue varchar(30),
        step_no bigint,
        recipient_key bigint,
        dequeue_msgid bytea,
        sender_name varchar(30),
        sender_address varchar(1024),
        sender_protocol bigint,
        user_data AQ$_JMS_TEXT_MESSAGE,
        user_prop ANYDATA
) ;

I’ve attached the updated Ora2Pg.pm for your reference.  Please advise if there is something that I have missed.

Thanks,

Joanna Xu
Senior Oracle DBA
Data Experience Solution BU

+1 613 595 5234

AMDOCS | EMBRACE CHALLENGE EXPERIENCE SUCCESS

POLICY CONTROL IN THE FAST LANE
What’s making policy control strategic in 2015 and beyond? Check out the top ten factors<http://www.policycontrolinthefastlane.com/> driving change…

**Comment by joanna-xu** [comment]
Hi Darold,

I made the change to ora2pg.conf to exclude table “ces_jms_queue_table” where contains the column “user_data AQ$_JMS_TEXT_MESSAGE”, it seems working by excluding it without showing the error seen previously.  But another error showed up when executing the following:

ALTER TABLE epc_prices_to_svc_data_2 ADD CONSTRAINT epc_prc_to_sd_svc_data_fk_2 FOREIGN KEY (svc_data_id) REFERENCES svc_data_2(id) ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ERROR:  foreign key constraint "epc_prc_to_sd_svc_data_fk_2" cannot be implemented
DETAIL:  Key columns "svc_data_id" and "id" are of incompatible types: numeric and bigint.

From the descriptions of the tables shown below, we can see "svc_data_id" with NUMBER(38)and "id" with NUMBER. It seems they are converted to numeric and bigint during the migration.  How can we get around and resolve this type of incompatible types error?  Please advise.

SQL> desc epc_prices_to_svc_data_2
Name                                      Null?    Type
----------------------------------------- -------- ----------------------------
EPC_PRICE_ID                              NOT NULL NUMBER(38)
SVC_DATA_ID                               NOT NULL NUMBER(38)
LASTMOD                                   NOT NULL TIMESTAMP(6)
MOD_BY                                    NOT NULL VARCHAR2(161)

SQL> desc svc_data_2
Name                                      Null?    Type
----------------------------------------- -------- ----------------------------
ID                                        NOT NULL NUMBER
SVC_PRF_ID                                NOT NULL NUMBER
ENTITY_ID                                 NOT NULL NUMBER
CONTEXT                                   NOT NULL NUMBER
ATTR_NAME                                 NOT NULL VARCHAR2(64)
VALUE                                              VARCHAR2(255)
SUBSCRIPT                                          NUMBER
LASTMOD                                   NOT NULL DATE
VERSION                                            NUMBER


Thanks,
Joanna


From: Joanna Xu
Sent: Tuesday, December 13, 2016 10:50 AM
To: 'darold/ora2pg' <reply@reply.github.com>; darold/ora2pg <ora2pg@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [darold/ora2pg] ora2pg - Java Message Service (JMS) Type (#245)

Hello Darold,

As suggested, I’ve tried and made both changes to ora2pg-17.6/lib/Ora2Pg.pm as the following:

Replace:

-    if (!$self->{is_mysql} && !$has_limitation && ($arr_type[$i] =~ /TABLE|SEQUENCE|VIEW|TRIGGER/)) {
With:
+  if (!$self->{is_mysql} && !$has_limitation && ($arr_type[$i] =~ /TABLE|SEQUENCE|VIEW|TRIGGER|TYPE/)) {

And …  Add:   EXCLUDE        AQ\$_.*

but still see the same output for the column “user_data AQ$_JMS_TEXT_MESSAGE” is included in the export file “outputR6_test.sql after executing ora2pg.

% ora2pg -u R6 -w R6 -o /u01/app/oracle/outputR6_test.sql
[========================>] 211/211 tables (100.0%) end of scanning.
[========================>] 211/211 tables (100.0%) end of table export.

CREATE TABLE ces_jms_queue_table (
        q_name varchar(30),
        msgid bytea NOT NULL,
        corrid varchar(128),
        priority bigint,
        state bigint,
        delay timestamp,
        expiration bigint,
        time_manager_info timestamp,
        local_order_no bigint,
        chain_no bigint,
        cscn bigint,
        dscn bigint,
        enq_time timestamp,
        enq_uid varchar(30),
        enq_tid varchar(30),
        deq_time timestamp,
        deq_uid varchar(30),
        deq_tid varchar(30),
        retry_count bigint,
        exception_qschema varchar(30),
        exception_queue varchar(30),
        step_no bigint,
        recipient_key bigint,
        dequeue_msgid bytea,
        sender_name varchar(30),
        sender_address varchar(1024),
        sender_protocol bigint,
        user_data AQ$_JMS_TEXT_MESSAGE,
        user_prop ANYDATA
) ;

I’ve attached the updated Ora2Pg.pm for your reference.  Please advise if there is something that I have missed.

Thanks,

Joanna Xu
Senior Oracle DBA
Data Experience Solution BU

+1 613 595 5234

AMDOCS | EMBRACE CHALLENGE EXPERIENCE SUCCESS

POLICY CONTROL IN THE FAST LANE
What’s making policy control strategic in 2015 and beyond? Check out the top ten factors<http://www.policycontrolinthefastlane.com/> driving change…

**Comment by darold** [comment]
NUMBER without precision are exported as bigint by default because this type is often used in key column and using numeric in this case is not the best thing for performances. You have to choose what to do in this case, perform an ALTER to change the numeric type or the opposite.

Or if you want you can change the default behaviour of ora2pg by changing the value of the  DEFAULT_NUMERIC configuration directive to export NUMBER() as numeric too.

Also take care that all fields requiring high precision might be typed as numeric.
