### ISSUE TITLE
Converting Oracle VARCHAR2(32) to PostgreSQL uuid

### ISSUE THREAD

**Issue by sjimmerson** [darold/ora2pg#247]
I would like to convert columns in Oracle that are of type VARCHAR2(32) to the PostgreSQL type uuid.  I tried setting the DATA_TYPE in the ora2pg.conf file, but it is not converting.  Should this work?  Is there a way I can get this to work?  I am using ora2pg 17.6.

`DATA_TYPE	DATE:timestamp,LONG:text,LONG RAW:bytea,CLOB:text,NCLOB:text,BLOB:bytea,BFILE:bytea,RAW:bytea,ROWID:oid,FLOAT:double precision,DEC:decimal,DECIMAL:decimal,DOUBLE PRECISION:double precision,INT:numeric,INTEGER:numeric,REAL:real,SMALLINT:smallint,BINARY_FLOAT:double precision,BINARY_DOUBLE:double precision,TIMESTAMP:timestamp,XMLTYPE:xml,BINARY_INTEGER:integer,PLS_INTEGER:integer,TIMESTAMP WITH TIME ZONE:timestamp with time zone,TIMESTAMP WITH LOCAL TIME ZONE:timestamp with time zone,VARCHAR2(32):uuid
`

Thanks,
Shane

**Comment by darold** [comment]
Hi,

Sorry for the response delay. You can not do that with Ora2Pg, the DATA_TYPE directive can only be use to redefine generic types, not a type with a precision. In this case you have to used MODIFY_TYPE and set the type per table/column. A better way might be to replace all varchar(32) after migration into uuid:

    perl -p -i -e 's/varchar\(32\)/uuid/' schema/tables/table.sql

this is probably what you have done.

Regards,

**Comment by sjimmerson** [comment]
I tried doing this based on the information provided at https://sourceforge.net/projects/ora2pg/files/17.5/ which stated precision could be specified.  Is this information incorrect?
Thanks,
Shane

**Comment by darold** [comment]
This information is correct but incomplete, actually it can only be used to replace NUMBER(P) or NUMBER(P,S) into a custom type, but not VARCHAR2.

**Comment by darold** [comment]
Well recent commit 48a9551 add this feature, you can now use:

     DATA_TYPE       VARCHAR2(32):uuid

Note that you don't have to redefine all other types, this form is enough.

**Comment by sjimmerson** [comment]
Thanks!  I used this update and it converted VARCHAR(32) to uuid beautifully.  It is nice not having to do the extra step each time I generate the script.  In regard to migrating data, the uuids are exported as numeric values as follows (content_set_sid is a uuid).  However, PostgreSQL doesn't like this.
`INSERT INTO p_content_sets (content_set_sid,changed,is_deleted,transaction_sid,content_set) VALUES (843D20B7C3654AD384351CD4B573D8BB,'2016-11-08 16:14:07.000000','f',965AA793C58840A298185604EB30F286,decode(E'6e61', 'hex'));
`

PostgreSQL wants the value to be a string as follows.  This works.
`INSERT INTO p_content_sets (content_set_sid,changed,is_deleted,transaction_sid,content_set) VALUES ('843D20B7C3654AD384351CD4B573D8BB','2016-11-08 16:14:07.000000','f',965AA793C58840A298185604EB30F286,decode(E'6e61', 'hex'));
`

How do I get ora2pg to output the uuids as strings which are typed as varchar2(32) in Oracle and uuid in PostgreSQL?

Thanks,
Shane

**Comment by darold** [comment]
Please give a try to last development code, commit 2a27d18 might solves this issue.

**Comment by sjimmerson** [comment]
This did correct the issue migrating the data, but just replacing the Ora2pg.pm file caused other errors creating the scripts for the DDL.  I get the following error which appears due to other changes in the Ora2pg.pm.  I am not sure how to resolve this.  Would you help me get this working with the latest Ora2pg.pm file?  

NOTE: convert_plsql_code is definitely not called from the previous versions of Ora2pg.pm on my system, so I imagine something else needs to be updated, but I am not sure what that something else is.

Undefined subroutine &Ora2Pg::PLSQL::convert_plsql_code called at C:/StrawberryPerl/perl/site/lib/Ora2Pg.pm line 5722.

Thanks for all your help!!!!

**Comment by darold** [comment]
Yes when upgrading you have to copy other .pm files from the lib/Ora2Pg/ directory, those libraries may have been modified too. You can proceed as follow:
```
copy lib/Ora2Pg C:/StrawberryPerl/perl/site/lib/Ora2Pg.pm
copy lib/Ora2Pg/*.pm C:/StrawberryPerl/perl/site/lib/Ora2Pg/
```
or something like that.

**Comment by sjimmerson** [comment]
That did the trick.  It is working great again!
