### ISSUE TITLE
Cannot change client_encoding in export output file

### ISSUE THREAD

**Issue by JuanM-117** [darold/ora2pg#248]
Hi darold,

I can´t change the client encoding in export file output executing the following command:

**-bash-4.2$ ora2pg --client_encoding WIN1252 -o archivo.sql -c ora2pg.conf.copy.file**

**-bash-4.2$ cat ora2pg.conf.copy.file**
ORACLE_HOME     /opt/oracle/instantclient_12_1
ORACLE_DSN      dbi:Oracle:sid=CGBCC_DEV
ORACLE_USER     system
ORACLE_PWD      Welcome1
#PG_DSN         dbi:Pg:dbname=datamart;host=postgres;port=5432
#PG_USER                scott
#PG_PWD         tiger
SCHEMA          GPAFILIACION
TYPE            COPY
#TYPE           TABLE
ALLOW           CDC_CREDITO
SKIP            fkeys,pkeys,ukeys,indexes,checks
EXPORT_SCHEMA   1
PG_SCHEMA       scott
DATA_LIMIT      500000
CLIENT_ENCODING WIN1252

**-bash-4.2$ head -5 archivo.sql**
-- Generated by Ora2Pg, the Oracle database Schema converter, version 17.5b
-- Copyright 2000-2016 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:sid=CGBCC_DEV

SET client_encoding TO 'UTF8';

How can I change the SET command in order to configure client encoding to WIN1252?

Thanks in advance.

Regards,
Juan M

**Comment by darold** [comment]
Hi Juan,

The --client_encoding is not working because your NLS_LANG confuration directive is UTF8 based., default to  AMERICAN_AMERICA.AL32UTF8. You need to change the value of NLS_LANG to AMERICAN_AMERICA.WE8MSWIN1252 if you want to use the WIN1252 encoding during export.

You can not just set the PostgreSQL client encoding to the encoding you want, it must correspond to the Oracle client encoding.

**Comment by JuanM-117** [comment]
Thanks Darold,

Done with the following...
**-bash-4.2$ ora2pg --nls_lang AMERICAN_AMERICA.WE8MSWIN1252 --client_encoding WIN1252 -o archivo.sql -c ora2pg.conf.copy.file**
[========================>] 1/1 tables (100.0%) end of scanning.
[========================>] 128563/128563 rows (100.0%) Table CDC_CREDITO (4591 recs/sec)
[========================>] 128563/128563 total rows (100.0%) - (28 sec., avg: 4591 recs/sec).
[========================>] 128563/128563 rows (100.0%) on total estimated data (28 sec., avg: 4591 recs/sec)

**-bash-4.2$ head -5 archivo.sql**
-- Generated by Ora2Pg, the Oracle database Schema converter, version 17.5b
-- Copyright 2000-2016 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:sid=CGBCC_DEV

SET client_encoding TO 'WIN1252';
