### ISSUE TITLE
Speed export file creation ora2pg

### ISSUE THREAD

**Issue by JuanM-117** [darold/ora2pg#249]
**Hi Darold,**

Currently I'am exporting a table 120GB size.
This is the statistic shown by ora2pg
4500000/410131882 rows (1.1%) Table CC_TP_CDC_CREDITO_201611 (2762 recs/sec)

According with above statistics, the final elapsed time would be
2762 rows           = 1 sec
410131882 rows = x secs

410131882 / 2762 = 148,490 secs = 2,474 mins = 41 hrs

In my opinion it would take too much time to complete the export.

Can you advise or give me any tip in order to speed the export process?

**Ora2PG command:**
ora2pg --nls_lang AMERICAN_AMERICA.WE8MSWIN1252 --client_encoding WIN1252 -o CREDITO_201611.sql -c conf.credito.201611

**Below the conf file:**
ORACLE_HOME     /opt/oracle/client/11.2
ORACLE_DSN      dbi:Oracle:sid=datamart
ORACLE_USER     ***
ORACLE_PWD      ***
SCHEMA          ***
TYPE            COPY
ALLOW           CC_TP_CDC_CREDITO_201611
SKIP            fkeys,pkeys,ukeys,indexes,checks
EXPORT_SCHEMA   1
PG_SCHEMA       cc_datamart
DATA_LIMIT      500000

**[postgres@cronos dumps]$ free -m**
             total       used       free     shared    buffers     cached
Mem:         64511      54424      10086          0       1426      31690
-/+ buffers/cache:      21308      43202
Swap:        32255          0      32255

**[postgres@cronos dumps]$ cat /etc/redhat-release**
Red Hat Enterprise Linux Server release 6.3 (Santiago)

**Oracle version:**
Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
PL/SQL Release 11.2.0.3.0 - Production
"CORE	11.2.0.3.0	Production"
TNS for Linux: Version 11.2.0.3.0 - Production
NLSRTL Version 11.2.0.3.0 - Production

Thanks in advance.

**Comment by darold** [comment]
Hi, 

If you want to migrate data at high speed you might don't use file output because you will have to import them after output. Use direct import into PostgreSQL instead by setting PG_DSN in the configuration file.

Your setting value of DATA_LIMIT is far too high, keep it to the default value, 10000 or better to 3000 following the actual speed on one core. If you just want to speed up this table export and you have at least 4 cores on the server, use -J 4 on you command line. This will use 4 process to export data in parallel from a single table.

Regards,

**Comment by darold** [comment]
Note that if you use direct import do not change the encoding and use the default, you will save some performances lost.

**Comment by JuanM-117** [comment]
Hi Darold

>>>>If you want to migrate data at high speed you might don't use file output because you will have to import them after output.

Unfortunatelly this is to cloud migration. Cloud and our server do not have direct connection.
That's why I have to create files.

>>>>>This will use 4 process to export data in parallel from a single table.

When I use the -J parameter, I get the following error:
-------------------------------
Can't set DBI::db=HASH(0x29dafe8)->{AutoInactiveDestroy}: unrecognised attribute name or invalid value at /usr/lib64/perl5/DBI.pm line 708.
Can't get DBI::db=HASH(0x29dafe8)->{AutoInactiveDestroy}: unrecognised attribute name at /usr/lib64/perl5/DBI.pm line 708.
[========================>] 1/1 tables (100.0%) end of scanning.
Can't set DBI::db=HASH(0x2ae0e88)->{AutoInactiveDestroy}: unrecognised attribute name or invalid value at /usr/lib64/perl5/DBI.pm line 708.
Can't get DBI::db=HASH(0x2ae0e88)->{AutoInactiveDestroy}: unrecognised attribute name at /usr/lib64/perl5/DBI.pm line 708.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle datamart at /usr/local/share/perl5/Ora2Pg.pm line 348.
DBD::Oracle::st fetchall_arrayref failed: ORA-03113: end-of-file on communication channel
 at /usr/local/share/perl5/Ora2Pg.pm line 10539.
ERROR: ORA-03113: end-of-file on communication channel
Process ID: 6570
Session ID: 900 Serial number: 43745 (DBD ERROR: OCIStmtFetch)
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle datamart at /usr/local/share/perl5/Ora2Pg.pm line 348.
DBD::Oracle::db DESTROY failed: ORA-03135: connection lost contact
-------------------------------

I'am facing face issue like "https://github.com/darold/ora2pg/issues/140"?

Is the upgrade advisible?

Thanks in advance.

**Comment by darold** [comment]
Yes this is the same issue, please upgrade DBI to a version greater than 1.614.

**Comment by JuanM-117** [comment]
>Yes this is the same issue, please upgrade DBI to a version greater than 1.614.

Currently I have the following software versions:

```
[postgres@cronos dumps]$ ora2pg -v
Ora2Pg v17.5

[postgres@cronos dumps]$ perl -MCPAN -e 'install DBD::Oracle'
Going to read '/root/.cpan/Metadata'
  Database was generated on Wed, 28 Dec 2016 17:41:02 GMT
DBD::Oracle is up to date (1.74).
```
Should be above versions enough?

**Comment by JuanM-117** [comment]
Sorry I was confusing DBI::Oracle with DBI component.
I upgrade DBI from 1.614 to 1.636.

Now I can run the commads with out any other undesired messages:

```
ora2pg --nls_lang AMERICAN_AMERICA.WE8MSWIN1252 --client_encoding WIN1252 -o CREDITO_201611.sql -c conf.credito.201611 -J 4
[========================>] 1/1 tables (100.0%) end of scanning.
[>                        ]    228000/410131882 total rows (0.1%) - (100 sec., avg: 2280 recs/sec), CC_TP_CDC_CREDITO_201611 in progress[>                        ]    234000/410131882 total rows (0.1%) - (103 sec., avg: 2271 recs/sec), CC_TP_CDC_CREDITO_201611 in progress[>                        ]    240000/410131882 total rows (0.1%) - (106 sec., avg: 2264 recs/sec), CC_TP_CDC_CREDITO_201611 in progress[>                        ]    246000/410131882 total rows (0.1%) - (109 sec., avg: 2256 recs/sec), CC_TP_CDC_CREDITO_201611 in progress[>                        ]    252000/410131882 total rows (0.1%) - (112 sec., avg: 2250 recs/sec), CC_TP_CDC_CREDITO_201611 in progress
```

Thanks for your support!

**Comment by JuanM-117** [comment]
I'am seeing the explain plan for export process but the parallel clause used in ora2pg it seems it is not used:
Below the explain plan got it from oracle database
```
----------------------------------------------------------------------------------------------
| Id  | Operation         | Name                     | Rows  | Bytes | Cost (%CPU)| Time     |
----------------------------------------------------------------------------------------------
|   0 | SELECT STATEMENT  |                          |       |       |  1234K(100)|          |
|   1 |  TABLE ACCESS FULL| CC_TP_CDC_CREDITO_201611 |   410M|   114G|  1234K  (3)| 04:06:59 |
----------------------------------------------------------------------------------------------
```


Do am I missing some parameter in ora2pg command?
`ora2pg --nls_lang AMERICAN_AMERICA.WE8MSWIN1252 --client_encoding WIN1252 -o CREDITO_201611.sql -c conf.credito.201611 -J 4`

Thanks in advance

**Comment by darold** [comment]
Please look at documentation about ORACLE_COPIES and DEFINED_PK. It seems that here Ora2Pg is not able to find a numeric column to split the data over parallel queries. What is the DESC of the table?

Also take care that PARALLEL_TABLE is set to 0 or 1 in the configuration file otherwise it has precedence on the ORACLE_COPIES or -J option.

**Comment by JuanM-117** [comment]
I am reading the doc,
ORACLE_COPIES 4
no parameter DEFINED_PK defined
no parameter PARALLEL_TABLE(S) defined

Below the DESCRIBE
```
Name                     Null     Type           
------------------------ -------- -------------- 
PAISID                            NUMBER(10)     
NAVALCVE                          NUMBER(15)     
NCREDVALACTVAL                    NUMBER(12,2)   
NCREDNUMPAGOS                     NUMBER(10)     
NCREDNUMPAGREP                    NUMBER(10)     
DCREDMONTOPAGAR          NOT NULL NUMBER(12,2)   
DCREDFAPERTURACTA                 DATE           
DCREDFULTPAGO                     DATE           
DCREDFULTCOMPRA                   DATE           
DCREDFCIERRECTA                   DATE           
DCREDFULTCEROS           NOT NULL DATE           
NCREDGTIA                         VARCHAR2(200)  
NCREDMONTOMAX            NOT NULL NUMBER(12,2)   
NCREDSDOACT              NOT NULL NUMBER(15,2)   
NCREDLIMITE                       NUMBER(12,2)   
NCREDSDOVENCIDO                   NUMBER(15,2)   
NCREDNUMPGOSVENC                  NUMBER(10)     
CCREDMOPACT              NOT NULL VARCHAR2(2)    
CCREDMOPHIST                      VARCHAR2(168)  
NCREDESTATUS             NOT NULL NUMBER(2)      
DCREDFFINRESTRUC                  DATE           
VCCREDOBS                         VARCHAR2(80)   
CCREDOTORGANTCVE                  VARCHAR2(10)   
CCREDOTORGANTNOMB                 VARCHAR2(40)   
CCREDNUMCTAANT                    VARCHAR2(25)   
DCREDFPROCESOCTE                  DATE           
DCREDFALTABC             NOT NULL DATE           
DCREDFACT                NOT NULL DATE           
C_PAISID                          VARCHAR2(2)    
CTIPOCONTRACVE           NOT NULL VARCHAR2(4)    <<<<<<<<PK
CUNIMONCVE                        VARCHAR2(3)    
CFORMPAGOCVE                      VARCHAR2(2)    
CTIPORESPCVE                      VARCHAR2(1)    
CTIPOOBSCVE                       VARCHAR2(2)    
CFRECPAGOCVE                      VARCHAR2(1)    
CTIPOCTACVE                       VARCHAR2(1)    
LOTECARGA                NOT NULL NUMBER(10)     
NUSUARIOACT              NOT NULL NUMBER(10)     
NDUENIOCVE               NOT NULL NUMBER(15)     
ESTATUS_ACTIVIDAD                 VARCHAR2(2)    
NUMERO_OTORGANTE         NOT NULL VARCHAR2(6)    <<<<<<<<PK    
CCREDNUMCTA              NOT NULL VARCHAR2(25)   <<<<<<<<PK
TIPO_NEGOCIO             NOT NULL VARCHAR2(4)    
TIPO_ACTUALIZACION                VARCHAR2(2)    
USUARIO_INS_CREDITO      NOT NULL NUMBER(10)     
FECHA_INS_CREDITO        NOT NULL DATE           
USUARIO_ACT_CREDITO      NOT NULL NUMBER(10)     
FECHA_ACT_CREDITO        NOT NULL DATE           
PEOR_ATRASO                       NUMBER(2)      
FECHA_PEOR_ATRASO                 DATE           
SALDO_VENC_PEOR_ATRASO            NUMBER(10)     
COMPORTAMIENTO_HISTORICO          VARCHAR2(1000) 
TIPO_PERSONALIDAD        NOT NULL VARCHAR2(2)    
DCREDPRIMINC                      DATE           
CAN_SDO_INSOLUTO                  NUMBER(12,2)   
IND_FPI_CDC                       NUMBER(1)      
CAN_MTO_ULT_PAGO                  NUMBER(12,2)   
CAN_PLAZO_MESES                   NUMBER(5)      
CAN_MTO_CRED_ORI                  NUMBER(12,2)   
IND_CTA_GRUPAL                    NUMBER(2)      
FEC_CARTERA_VEN                   DATE           
CAN_MTO_INTERES                   NUMBER(12)     
CVE_MOP_INTERES                   VARCHAR2(2)    
NUM_DIAS_VENCIDOS                 NUMBER(5)      
```

**Comment by darold** [comment]
For example you can set DEFINED_PK to

    DEFINED_PK    CC_TP_CDC_CREDITO_201611:PAISID

if you think it could help Ora2Pg to split the data in balanced parts.

If you have more cores you can also set -j 2 to parallelise the write into the dump files. With -J 4 it will use 4x2=8 cores.

**Comment by JuanM-117** [comment]
Thanks Darold,
Currently I chose DEFINED_PK ...NDIENIOCVE column, using -J4 -j8, extracting 34,000 rows/s regarding initially 2,500 rows/s.

Now, the estimated elapsed time for all 410 millions of rows would be aprox in 3.5 hours. A good time for now.

Thanks for your all support.

Good job done for this exelent ora2pg tool. Donate is comming! :P

**Comment by darold** [comment]
Thanks for the donation Juan, it is much appreciated.
