### ISSUE TITLE
Convert NUMBER(*, 0) to bigint instead of numeric(38, 0) by default

### ISSUE THREAD

**Issue by kuzmaka** [darold/ora2pg#251]
Hi,
The issue is related to #200 but differs a bit. I agree NUMBER() to bigint conversion is a good default heuristic. Along with that I think it would be better to convert NUMBER(*, 0) to bigint instead of numeric(38, 0) by default.

**Comment by darold** [comment]
Hi,

I'm not sure of that, but I guess that if a DBA create a field with NUMBER(*, 0) this is to use numbers with more than the 19 digit of a bigint, otherwise he often use NUMBER(22) or NUMBER.

**Comment by kuzmaka** [comment]
I'm not an Oracle guy so I also don't know real statistic of such usage. I've just met table for conversion with columns like following:
```
ID NUMBER(*, 0) NOT NULL
HUISNR NUMBER(*, 0)   -- house number
INW NUMBER(*, 0)  -- inhabitants
WVO NUMBER(*, 0)  -- surface
```
And these are mixed with
`UNITID NUMBER`
without precision and scale parameters.
All of the above are usual integers and not worth NUMERIC(38, 0).
You decide :)

**Comment by darold** [comment]
Ok, I will add a way to force Ora2Pg to convert NUMBER(.*, 0) into bigint to be able to automatically correct such bad design in the Oracle database.

**Comment by darold** [comment]
Commit 5cbc857 allow this type rewriting using:

    DATA_TYPE    NUMBER(*\,0):bigint

Thanks
