### ISSUE TITLE
Out of memory during data export of more that 1 table on Windows

### ISSUE THREAD

**Issue by AlexKart86** [darold/ora2pg#252]
I'm trying to create scripts for transfering data of 2 small (111 and 12 rows) oracle tables without blobs. I use --allow option to filter table names:
`ora2pg -b ./data -t COPY --allow table1,table2`
But after creation of the script for the first table, I received an error "Out of memory"

When I tried to export exactly one table (much bigger, 50000 rows with blobs) all worked fine 

OS: Windows 7 x64

Full error log:

c:\ora2pg\Test\test>ora2pg -b ./data -t COPY --allow table1,table2
[========================>] 2/2 tables (100.0%) scanning table TABLE2
[========================>] 2/2 tables (100.0%) end of scanning.
[========================>] 111/111 rows (100.0%) Table TABLE1 (111 recs/sec)
[=====================>   ] 111/123 total rows (90.2%) - (0 sec., avg: 111 recs/sec).
[=====================>   ] 111/123 rows (90.2%) on total estimated data (1 sec.Out of memory!s/sec)
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::
db handle (DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=192.168.0.105)
(PORT=1526))(ADDRESS=(PROTOCOL=tcp)(HOST=192.168.0.105)(PORT=1521)))(CONNECT_DAT
A=(SID=XE))) at C:/Perl/lib/DBD/Oracle.pm line 348.

**Comment by darold** [comment]
Strange. What is your value of DATA_LIMIT? and does it still crash if you add `-L 100` to the ora2pf command line?

What is the amount of memory o this computer?

**Comment by AlexKart86** [comment]
Computer has 10G RAM. During execution it used only ~50 mb ram
DATA_LIMIT had default value 10000. When I changed this option to 100 or to 2000 error disappeared! Thanks!
