### ISSUE TITLE
Incorrect output file names when used option FILE_PER_TABLE on Windows

### ISSUE THREAD

**Issue by AlexKart86** [darold/ora2pg#253]
I use FILE_PER_TABLE 1 in .conf file to split export script into several files. I use this command to make export:
`ora2pg -b ./data -o data.sql -t INSERT --allow dict_12_200,dict_osvita_level`
After finishing export in folder "data" the following files are created:
data.sql
tmp_DICT_12_200_data.sql
tmp_DICT_OSVITA_LEVEL_data.sql

1. I expected that file names should be without prefix tmp_
2. Commands in file data.sql
\i ./data/DICT_12_200_data.sql
\i ./data/DICT_OSVITA_LEVEL_data.sql
will work only if data.sql was moved into parent directory

I looked through code and added some debug information in sub export_table_data in file Ora2Pg.pm:
`rename("${dirprefix}tmp_${table}_$self->{output}", "${dirprefix}${table}_$self->{output}")` **or die $!**;

and received an error:
Permission denied at C:/Perl/site/lib/Ora2Pg.pm line 2969.
I think the problem is that the temporary file is not closed before renaming

**Comment by darold** [comment]
Commit 32f8435 might solve this issue, please download latest development code and give it a try.

Best regards,

**Comment by AlexKart86** [comment]
Something wrong with this fix! I have downloaded fixed files, but there are no data in the output files now
I used this command
`ora2pg -b ./data -o data.sql -t COPY --allow dict_12_200,dict_osvita_level`
and files DICT_12_200_data.sql and DICT_OSVITA_LEVEL_data.sql were created without data:

> -- Generated by Ora2Pg, the Oracle database Schema converter, version 17.6b
> -- Copyright 2000-2017 Gilles DAROLD. All rights reserved.
> -- DATASOURCE: dbi:Oracle:host=192.168.0.105;sid=XE
> SET client_encoding TO 'UTF8';
> SET search_path = dk, pg_catalog;

table dict_osvita_level has 12 rows

**Comment by darold** [comment]
Commit removed.

**Comment by ahsanullahkhn** [comment]
Still getting this issue with generating data files with names tmp_xxxxx.sql.
Using version 18.2 on Windows 2008 Server R2.
Do we have any resolution for this?

**Comment by darold** [comment]
Commit 3f373f8 might fix this issue.

**Comment by JerryKwon** [comment]
@darold 
I've suffered same issue in ora2pg 20.0 version.
Could you check this issue one more?

**Comment by darold** [comment]
Are you using latest development code?
```
wget https://github.com/darold/ora2pg/archive/master.zip
unzip master.zip
cd ora2pg-master/
perl Makefile.PL
dmake
dmake install
```

**Comment by JerryKwon** [comment]
@darold 
Yes, I downloaded the one what you said.
v.20 Ora2pg
I tried twice in different PC environments.
One is in RHEL 7 Linux, the other is in Windows Server 2012R2.
That problem occurs the latter one unlike linux. In linux, the prefix "tmp" didn't be shown.
So, Is there parameter option turn on/off tmp prefix??? Or not what is your opinion about it?

**Comment by darold** [comment]
Files `tmp_*` are removed once a table is fully exported, they must not be visible unless there is a crash of ora2pg. I will try to check that on a Windows machine. If I understand well the problem doesn't occurs on Linux.

**Comment by JerryKwon** [comment]
@darold 
The symptom could be right.

These days, I'm trying to migrate using ora2pg, awesome tool i think.
but there are "tmp_" prefix occurs in the other trials in windows even there were no errors during data export!! In other words, NO ERRORS WHEN I CHECK LOG AFTER THAT

So, I have done using FILE_PER_TABLE 0 in config file because of it. I think I'm better than me who was at 10 days ago to handle ora2pg tool.

I hope this error will be fixed soon!!
