### ISSUE TITLE
FOR r IN SELECT

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#255]
ora2pg doesn't declare necessary record variable R

**Comment by darold** [comment]
Hi Pavel,

I need the context. Do you have the source PL/SQL to paste here or does r is a global variable in a package?

Regards,

**Comment by okbob** [comment]
<pre>
CREATE OR REPLACE function IDES_PRAHA22.CISKOLUR_SEZNAM_REZIM(mID_KOLURC IN NUMBER)
return varchar2 is
  Result varchar2(255);
begin
  Result := NULL;
  BEGIN
    FOR qOBPVOMOB IN
    (  SELECT B2.BYT_NEBYT,B2.J1_NAZEV 
       FROM CVTYPSKUPR B1 , CISTYPPR B2
        WHERE B1.ID_KOLURC = mID_KOLURC
         AND B1.ID_TYPPRS = B2.ID_TYPPRS
     )
     LOOP
       Result := Result ||qOBPVOMOB.BYT_NEBYT||'-'||qOBPVOMOB.J1_NAZEV || ',';
     END LOOP;    
     Result := SUBSTR( Result , 1 , length(Result) -1 );
  EXCEPTION
    WHEN OTHERS THEN
      Result := 'VETSI POCET NEZ LZE ZOBRAZIT';
  END;
  return(Result);
  

end CISKOLUR_SEZNAM_REZIM;
</pre>
PLpgSQL fails, because variable `qOBPVOMOB` is undeclared - solution: `DECLARE qOBPVOMOB RECORD`

**Comment by darold** [comment]
Fixed in multiple-bug-fix commit 11536f9 Ora2Pg will always look in the DECLARE section if a variable used inside  a FOR ... IN statement is present in the DECLARE bloc and add it if it is not found.

**Comment by okbob** [comment]
Quick work - it is important for me - Thank you very much - I'll check it next week. Thank you again
