### ISSUE TITLE
Unwanted `SELECT ` to `PERFORM` transformation inside string literal

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#256]
The PL/SQL code

     IF  mWhere IS NOT NULL  THEN
          mSqlCISNAJZAKC := ' SELECT ID_CISNAJZAKC FROM CISNAJZAKC WHERE 1=1 AND ID_CISNAJLOK =' || mWhere||' ORDER BY PLATNOST_OD DESC';
        ELSE
           mSqlCISNAJZAKC := ' SELECT ID_CISNAJZAKC FROM CISNAJZAKC WHERE 1=1 AND ID_CISNAJLOK = -1 ' ;
        END IF;
    
        OPEN qCISNAJZAKC FOR mSqlCISNAJZAKC ;
        LOOP

Is translated to:

        IF  mWhere IS NOT NULL  THEN
          mSqlCISNAJZAKC := ' PERFORM ID_CISNAJZAKC FROM CISNAJZAKC WHERE 1=1 AND ID_CISNAJLOK =' || mWhere||' ORDER BY PLATNOST_OD DESC';
        ELSE
          mSqlCISNAJZAKC := ' PERFORM ID_CISNAJZAKC FROM CISNAJZAKC WHERE 1=1 AND ID_CISNAJLOK = -1 ' ;
        END IF;

There should to be `SELECT`. Using `PERFORM` in string - and possible dynamic SQL is always wrong in Postgres.

**Comment by darold** [comment]
Fixed in multiple-bug-fix commit 11536f9 .
