### ISSUE TITLE
`DEFAULT` for char(1) is not correctly translated

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#258]
Some default expressions are badly formatted - Oracle shows default value in parenthesis like `('A')`, ora2pg transforms it to `'('A')'`.

**Comment by darold** [comment]
Fixed in multiple-bug-fix commit 11536f9

**Comment by okbob** [comment]
It was not fixed

**Comment by darold** [comment]
I have fixed the issue in the function code but I see that you are talking about the issue in table declaration.

**Comment by darold** [comment]
Commit 4a8cdae might fix it in table declaration.
