### ISSUE TITLE
Oracle novalidate constraints

### ISSUE THREAD

**Issue by AlexKart86** [darold/ora2pg#259]
Oracle novalidate constraints are converted in ordinary postgres constraints. 
Suggestion: convert such constraints into constraints with "not valid" option.

Such constraints have Validated=NOT VALID in *_constraints oracle views

**Comment by okbob** [comment]
Good idea - actually I have to clean it manually.

**Comment by darold** [comment]
Commit 77f81ca export Oracle FK and CHECK constraint as NOT VALID when they are marked NOT VALIDATED or NOVALIDATE in Oracle.

Thanks for the feature request.
