### ISSUE TITLE
Oracle virtual columns

### ISSUE THREAD

**Issue by AlexKart86** [darold/ora2pg#260]
Oracle virtual columns are converted into ordinary postgreSQL columns with default clause. But postgreSQL cannot use another columns in default clause.
Suggestion: [create function, view or trigger](https://www.enterprisedb.com/creating-virtual-columns) to emulate virtual columns (IMHO, trigger is the most useful solution)

**Comment by darold** [comment]
Commit adds export of Oracle's virtual column as trigger. It works as follow, for example, the Oracle table:

```
CREATE TABLE VIRT_COL_TABLE (
  id          NUMBER,
  first_name  VARCHAR2(10),
  last_name   VARCHAR2(10),
  salary      NUMBER(9,2),
  comm1       NUMBER(3),
  comm2       NUMBER(3),
  salary1     AS (ROUND(salary*(1+comm1/100),2)),
  salary2     NUMBER GENERATED ALWAYS AS (ROUND(salary*(1+comm2/100),2)) VIRTUAL,
);
```
is converted as a PostgreSQL table:
```
CREATE TABLE virt_col_table (
        id bigint NOT NULL,
        first_name varchar(10),
        last_name varchar(10),
        salary double precision,
        comm1 smallint,
        comm2 smallint,
        salary1 bigint,
        salary2 bigint
) ;
```

an additional export file named `VIRTUAL_COLUMNS_(...).sql` contains the trigger definition to apply the default values of the original virtual columns:
```
DROP TRIGGER IF EXISTS virt_col_VIRT_COL_TABLE_trigger ON VIRT_COL_TABLE CASCADE;

CREATE OR REPLACE FUNCTION fct_virt_col_VIRT_COL_TABLE_trigger() RETURNS trigger AS $BODY$
BEGIN
        NEW.SALARY2 = ROUND(NEW.SALARY*(1+NEW.COMM2/100),2);
        NEW.SALARY1 = ROUND(NEW.SALARY*(1+NEW.COMM1/100),2);

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;

CREATE TRIGGER virt_col_VIRT_COL_TABLE_trigger
        BEFORE INSERT OR UPDATE ON VIRT_COL_TABLE FOR EACH ROW
        EXECUTE PROCEDURE fct_virt_col_VIRT_COL_TABLE_trigger();

```
Let me know if that's what is expected.

**Comment by darold** [comment]
Commit is 472774c.

**Comment by AlexKart86** [comment]
Hello! Sorry for long reply. I downloaded latest version of code, but there are no any changes of virtual column processing. It's seems that this changes were accidentally removed in next commit  https://github.com/darold/ora2pg/commit/d5866c99d7a4cb4f1f2246f4517b7b63740823bf

**Comment by darold** [comment]
Hello Alexey,

Damned, that's right, I guess I need some holidays :-( Last commit 030bafe reapply this feature.

Thanks.

**Comment by darold** [comment]
And now commit a318fdf allow export of virtual column from a DDL input file but most of all it allow inclusion of virtual column export in the regression test so the patch won't be lost again.
