### ISSUE TITLE
replace in SELECT without INTO should be PERFORM section for CHECK on TABLE

### ISSUE THREAD

**Issue by BernardBielecki** [darold/ora2pg#261]
Hello.
I suggest to exclude TABLE for this replace:

```
	# SELECT without INTO should be PERFORM. Exclude select of view when prefixed with AS or IS
	if ( ($class->{type} ne 'QUERY') && ($class->{type} ne 'VIEW') && ($class->{type} ne 'TABLE') ) {
		my @text_values = ();
		my $j = 0;
		while ($str =~ s/'([^']+)'/\%TEXTVALUE-$j\%/s) {
			push(@text_values, $1);
			$j++;
		}
```
Example - CHECK in my table:
`(typ_zasobu = 'ZN' AND REGEXP_REPLACE(WYKL_UZYTEK_IDS,'^([0-9])+(,[0-9]+)*$','') IS NULL) OR (typ_zasobu <> 'ZN' AND WYKL_UZYTEK_IDS IS NULL)
`
After:
`(typ_zasobu = 'ZN' AND REGEXP_REPLACE(WYKL_UZYTEK_IDS,'^([0-9])+(,[0-9]+)*$','%TEXTVALUE-2%ZN' AND WYKL_UZYTEK_IDS IS NULL)`

**Comment by darold** [comment]
Thanks for the report Bernard, commit 6a7f8da might solves the issue.

**Comment by BernardBielecki** [comment]
Thanks. It works.
