### ISSUE TITLE
INSTR in case of REGEXP_INSTR

### ISSUE THREAD

**Issue by BernardBielecki** [darold/ora2pg#263]
Hello.

My CHECK:

`REGEXP_INSTR(KONT_ID,'^[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12}$') = 1`
is changed to 
`REGEXP_POSITION('^[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12}$' in KONT_ID`

I suggest adding \b before INSTR in two places: sub replace_oracle_function and sub plsql_to_plpgsql:

`	$str =~ s/INSTR\s*\(\s*([^,]+),\s*('[^']+')\s*\)/POSITION($2 in $1)/igs;`
to 
`	$str =~ s/\bINSTR\s*\(\s*([^,]+),\s*('[^']+')\s*\)/POSITION($2 in $1)/igs;`

**Comment by darold** [comment]
Last commit f7a09c8 remove the substitution call from the plsql_to_plpgsql() function and fix the call in the replace_oracle_function() method. Thanks

**Comment by BernardBielecki** [comment]
Thanks. It Works.
