### ISSUE TITLE
local types are not supported by PLpgSQL

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#264]
PL/SQL declaration

    TYPE TqCISNAJZAKC IS REF CURSOR;
    qCISNAJZAKC   TqCISNAJZAKC;

Is translated to:

    TYPE TqCISNAJZAKC REFCURSOR;
    qCISNAJZAKC   TqCISNAJZAKC;

But it is not valid in PostgreSQL - it should be translated to directly

     qCISNAJZAKC REFCURSOR

**Comment by darold** [comment]
Commit 3e3167b might adds translation of local type ref cursor.

**Comment by okbob** [comment]
This issue was fixed.
