### ISSUE TITLE
PL/pgSQL statement `OPEN` requires `EXECUTE` keyword when dynamic SQL is used

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#265]
PL/SQL `OPEN` command directly supports dynamic SQL:

    OPEN qCISNAJZAKC FOR mSqlCISNAJZAKC ;

The syntax is:

    OPEN cursorvar FOR query | variable | expression -- last two are dynamic SQL

PL/pgSQL requires `EXECUTE` keyword:

    OPEN qCISNAJZAKC FOR EXECUTE mSqlCISNAJZAKC;

**Comment by darold** [comment]
Lastest commit 64af76d might solves this issue.  Code like:

    OPEN v_emp_cursor FOR v_stmt_str USING 'MANAGER';

or

    OPEN v_emp_cursor FOR 'SELECT * FROM employees WHERE job_id = ' || v_e_job;

will be appended with EXECUTE after the FOR keyword.

Thanks

**Comment by okbob** [comment]
2017-01-18 18:22 GMT+01:00 Darold <notifications@github.com>:

> Lastest commit 64af76d
> <https://github.com/darold/ora2pg/commit/64af76d6de27f4addcc362c52c08e48bf305f886>
> might solves this issue. Code like:
>
> OPEN v_emp_cursor FOR v_stmt_str USING 'MANAGER';
>
> or
>
> OPEN v_emp_cursor FOR 'SELECT * FROM employees WHERE job_id = ' || v_e_job;
>
> will be appended with EXECUTE after the FOR keyword.
>
The most often use case what I have now (only this case - these developers
doesn't know USING) is

OPEN var1 FOR var2;

Doesn't break static cursor? OPEN FOR SELECT.. ?

**Comment by darold** [comment]
Commit fe05028 adds rewrite of the form `OPEN var1 FOR var2;`

It should not break the static cursor declaration at least in my tests it does not.

**Comment by okbob** [comment]
It is working well in last version
