### ISSUE TITLE
missing support for OUT arguments

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#267]
The code:

      Result DATE ;
      mDatum_pom DATE;
    begin
      mDatum_pom := mDatum;
      SET_DALSI_MESIC( mDatum_pom , mKoef  ); 
      Result := mDatum_pom ;
      return(Result);
    end FSET_DALSI_MESIC;
    /* CREATE OR REPLACE procedure IDES_PRAHA22.SET_DALSI_MESIC( mDatum IN OUT DATE ,
                                                                                                                           mKoef IN NUMBER ) */

Should be translated to:

    BEGIN
      mDatum_pom := mDatum;
      mDatum_pom := SET_DALSI_MESIC( mDatum_pom , mKoef  );.
      Result := mDatum_pom ;
      return(Result);
    END

**Comment by darold** [comment]
There is a parser problem here, can you send me the entire function code with the comment. If it is defined in a package I also need the context in the package. Note if you don't want to post here the code even obfuscated you can send it to my private email.

**Comment by okbob** [comment]
PL/SQL code:
<pre>
CREATE OR REPLACE procedure IDES_PRAHA22.SET_DALSI_MESIC( mDatum IN OUT DATE , mKoef IN NUMBER )
is
  mMesic NUMBER; 
  mRok NUMBER;
  mDen NUMBER ;
begin
   
   mDen := TO_NUMBER(TO_CHAR( mDatum , 'DD' )); 
   mRok := TO_NUMBER(TO_CHAR( mDatum , 'YYYY' )); 
   mMesic := TO_NUMBER(TO_CHAR( mDatum , 'MM' )); 
   IF mMesic < 12 THEN
     mMesic := mMesic + 1;
   ELSE
     mMesic := 1;
     mRok := mRok + 1 ;
   END IF;
   
      
   IF mKoef = RRRUTIL.NEMENIT_DEN THEN  
     FOR mI IN 1..4 
     LOOP
       BEGIN
         mDatum := TO_DATE( mDen || '.' || mMesic || '.' || mRok , 'DD.MM.YYYY' )  ;     
         EXIT;
       EXCEPTION
         WHEN OTHERS THEN
           mDen := mDen - 1;  
       END ;
     END LOOP;
   ELSE
      mDatum := TO_DATE( '01.' || mMesic || '.' || mRok , 'DD.MM.YYYY' ) + mKoef ;     
   END IF;
end ;
CREATE OR REPLACE function IDES_PRAHA22.POM_GET_OSTRAHA_VOL( mDATUM_OD IN OUT  DATE , mDATUM_DO IN DATE ) 
   return number is
   Result number;
   mMESIC NUMBER;
   mDATUM_KONEC_MES DATE;
   mHodnota NUMBER;
   mDATUM_SKUT_DO DATE;
   mCELY_MESIC NUMBER;
   mCAST_MESICE NUMBER;
begin
  mHodnota := 0;  

  WHILE mDATUM_OD < mDATUM_DO
  LOOP
    mMESIC := TO_CHAR( mDATUM_OD , 'MM' );  
    mDATUM_KONEC_MES := mDATUM_OD;
    SET_DALSI_MESIC( mDATUM_KONEC_MES , -1 ); --- MISSING SELECT INTO
    mDATUM_SKUT_DO := mDATUM_KONEC_MES;
    IF mDATUM_SKUT_DO > mDATUM_DO THEN
       mDATUM_SKUT_DO := mDATUM_DO;
    END IF;  
    
    IF ( TO_CHAR(mDATUM_OD,'DD') = '01' ) AND ( mDATUM_SKUT_DO = mDATUM_KONEC_MES ) THEN 
      mHodnota :=  mHodnota + 41;  
    ELSE
       mCELY_MESIC := ( mDATUM_KONEC_MES - TO_DATE( '01.' || TO_CHAR(mDATUM_KONEC_MES,'MM.YYYY')) + 1 );
       mCAST_MESICE := ( mDATUM_SKUT_DO - mDATUM_OD + 1 );
       mHodnota :=  mHodnota + ROUND((41/mCELY_MESIC * mCAST_MESICE ),0);
    END IF;  
    
    mDATUM_OD := mDATUM_KONEC_MES + 1;
  
  END LOOP;      

  
   RETURN   mHodnota;
end POM_GET_OSTRAHA_VOL;

</pre>

**Comment by darold** [comment]
Hi Pavel,

Commit 0c44169 might solve this issue. It probably need more work but the main code is written.

Regards,

**Comment by darold** [comment]
There was still issues with this previous commit, last one, 46f9da7, might fix all pending problems.
