### ISSUE TITLE
Injected cast to number is broken

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#268]
a PL/SQL code:

    akt:=akt+TO_NUMBER(mSLOUPEC); 

is translated to PL/pgSQL:

    akt:=akt+(mSLOUPEC):integer;

There one colon is missing

**Comment by darold** [comment]
Sorry one of the previous commit has broken this replacement. Latest commit 863201d might solves the issue.

**Comment by okbob** [comment]
No problem

**Comment by okbob** [comment]
it was fixed
