### ISSUE TITLE
`DECODE` and NULL test substitution produce invalid query

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#269]
The PL/SQL part:
<pre>
    SELECT  DECODE(SUM(MT.EPREDEPSANO) , NULL , 0 , SUM(MT.EPREDEPSANO)  )  ,
             SUM(( SELECT DECODE( SUM(B1.ROZ_CASTKA) , NULL , 0 ,SUM(B1.ROZ_CASTKA) )
                 FROM NAJVPLAPRE B1
                 WHERE B1.ID_NAJDATSPLT =  A1.ID_NAJDATSPLT
                   AND B1.DAT_STORNA IS NULL ))  INTO mEPREDEPSANO ,  mEZAPLACENO 
         FROM NAJKAUHYB MT , NAJDATSPLT A1
         WHERE MT.ID_NAJKAUCE = mID_NAJKAUCE
           AND MT.TYP = 'P' 
           AND MT.EPREDEPSANO > 0
           AND MT.ID_NAJDATSPLT = A1.ID_NAJDATSPLT
           AND MT.DATUM_SPLATNOSTI < mKDATU
           AND NVL(GET_STRP_NAJDATSPLT(MT.ID_NAJDATSPLT),'N') <> 'S'
</pre>
The PL/pgSQL:
<pre>
     SELECT  CASE WHEN coalesce(SUM(MT.EPREDEPSANO)::text, '') = '' THEN 0  ELSE SUM(MT.EPREDEPSANO)   END  ,
             coalesce(SUM(( SELECT CASE WHEN  SUM(B1.ROZ_CASTKA)::text, '') = '' THEN 0  ELSE SUM(B1.ROZ_CASTKA)  END
                 FROM NAJVPLAPRE B1
                 WHERE B1.ID_NAJDATSPLT =  A1.ID_NAJDATSPLT
                   AND coalesce(B1.DAT_STORNA::text, '') = '' ))  INTO mEPREDEPSANO ,  mEZAPLACENO.
         FROM NAJKAUHYB MT , NAJDATSPLT A1
         WHERE MT.ID_NAJKAUCE = mID_NAJKAUCE
           AND MT.TYP = 'P'.
           AND MT.EPREDEPSANO > 0
           AND MT.ID_NAJDATSPLT = A1.ID_NAJDATSPLT
           AND MT.DATUM_SPLATNOSTI < mKDATU
           AND coalesce(GET_STRP_NAJDATSPLT(MT.ID_NAJDATSPLT),'N') <> 'S' 
</pre>
Error:
<pre>
psql:function.sql:2908: ERROR:  syntax error at or near ","
LINE 37: ...e(SUM(( SELECT CASE WHEN  SUM(B1.ROZ_CASTKA)::text, '') = ''...
                                                              ^
</pre>

**Comment by darold** [comment]
This is because you have enabled the NULL_EQUAL_EMPTY configuration directive. In this case it must not be enabled.

**Comment by okbob** [comment]
I understand to dependency - but with any configuration it should to produce valid expression.

**Comment by darold** [comment]
I agree, it just need some time to be fixed.

**Comment by okbob** [comment]
I understand well

**Comment by darold** [comment]
Fixed in commit a3b481d.
