### ISSUE TITLE
Wrong result type of function with more OUT arguments

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#270]
The PL/SQL function:
<pre>
CREATE OR REPLACE function IDES_PRAHA22.GET_FAK_DPH( mID_UCEHLAFAK IN UCEHLAFAK.ID_UCEHLAFAK%TYPE ,
 mPROCENT OUT UCEHLAFAK.DPH_PROC_1%TYPE , mEZAKLAD OUT UCEHLAFAK.EZAKLAD_1%TYPE , 
 mEDPH_CASTKA OUT UCEHLAFAK.EDPH_CASTKA_1%TYPE  ) return NUMBER is
</pre>
is translated to:
<pre>
CREATE OR REPLACE FUNCTION get_fak_dph ( mID_UCEHLAFAK UCEHLAFAK.ID_UCEHLAFAK%TYPE , mPROCENT OUT UCEHLAFAK.DPH_PROC_1%TYPE , mEZAKLAD OUT UCEHLAFAK.EZAKLAD_1%TYPE , mEDPH_CASTKA OUT UCEHLAFAK.EDPH_CASTKA_1%TYPE ) RETURNS bigint AS
</pre>
It fails:
<pre>
psql:function.sql:3407: ERROR:  function result type must be record because of OUT parameters
</pre>

**Comment by darold** [comment]
Commit b2c8a94 fixes this issue.

**Comment by okbob** [comment]
fixed
