### ISSUE TITLE
wrong placing of LIMIT clause

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#273]
`LIMIT` clause should be last clause:

PL/SQL code:
<pre>
    SELECT NAJPOC INTO Result 
    FROM NAJPREDP 
    WHERE ID_NAJVZTAH = mID_NAJVZTAH
    AND NAJPOC > 0
    AND PLATNY = 'A'
    AND ROWNUM < 2
    ORDER BY ID_PREDPIS DESC;
</pre>
Wrog plpgsql:
<pre>
    SELECT NAJPOC INTO Result 
    FROM NAJPREDP 
    WHERE ID_NAJVZTAH = mID_NAJVZTAH
    AND NAJPOC > 0
    AND PLATNY = 'A'
    LIMIT 1
    ORDER BY ID_PREDPIS DESC;
</pre>

**Comment by darold** [comment]
Might be fixed in commit cfbffcf. Thanks

**Comment by okbob** [comment]
partially fixed, maybe related to #276

**Comment by darold** [comment]
Commit bbc12f6 might fix rownum replacement with sub select, more nested sub select is not supported yet with this patch.

**Comment by okbob** [comment]
fixed
