### ISSUE TITLE
wrong subtitution `FOR` in substring function

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#274]
PL/SQL
<pre>
    OPEN qNajplatby FOR mSqlNajplatby USING  mID_NAJDATSPLT ;
    LOOP
        FETCH qNajplatby INTO  mZALOBCISLO  ;
        EXIT WHEN qNajplatby%NOTFOUND;
        mADRA:=substr(mZALOBCISLO,1,255);
        EXIT;
    END LOOP;
</pre>
PL/pgSQL:
<pre>
        FETCH qNajplatby INTO  mZALOBCISLO  ;
        IF NOT FOUND THEN EXIT; END IF; -- apply on qNajplatby
        mADRA:=substring(mZALOBCISLO from 1 for EXECUTE 255);
        EXIT;
</pre>

**Comment by darold** [comment]
Arrrg, commit d94dd6e might fixes this issue by removing the replacement of substr() by substring() as PostgreSQL have the substr() function too.

**Comment by okbob** [comment]
fixed
