### ISSUE TITLE
Broken SQL query after migration to PostgreSQL - missing `WHERE`

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#276]
PL/SQL:
<pre>
  select trim(typ) into mTYP from ssshledej_a 
  where rownum<2 and trim(typ) in ('L','P') and id_prostor = (select id_prostor from ssshledej_a where 
  id_najvztah = mID_NAJVZTAH and trim(typ) ='N' and  trim(hlavni)='H' and rownum<2) ;
</pre>
PLpgSQL:
<pre>
  select btrim(typ) into STRICT  mTYP from ssshledej_a and btrim(typ) in ('L','P') and id_prostor = (SELECT id_prostor from ssshledej
  id_najvztah = mID_NAJVZTAH and btrim(typ) ='N' and  btrim(hlavni)='H' and rownum<2)  LIMIT 1;
</pre>

Or - another break
PL/SQL:
<pre>
      select  ID_BUCET into  mID_BUCET from
       parvbuabo where id_najvztah=mID_NAJVZTAH
          AND ROWNUM < 2;
</pre>
PL/pgSQL - ROWNUM is not removed
<pre>
      select  ID_BUCET into STRICT   mID_BUCET from
       parvbuabo where id_najvztah=mID_NAJVZTAH
          AND ROWNUM < 2;
</pre>

Or
Pl/SQL
<pre>
        select id_ccle into mID_CCLE
        from ssshledej_a
        where rownum<2 and typ='N' and id_najvztah =mid_najvztah;
</pre>
PL/pgSQL - missing `WHERE`
<pre>
        select id_ccle into STRICT  mID_CCLE
        from ssshledej_a and typ='N' and id_najvztah =mid_najvztah LIMIT 1;
</pre>

**Comment by darold** [comment]
Commit 9670232 fix the missing where clause and other wrong rewriting with ROWNUM replacement.

**Comment by okbob** [comment]
looks fixed
