### ISSUE TITLE
SYS_GUID() conversion

### ISSUE THREAD

**Issue by NicolasMartin69** [darold/ora2pg#277]
Hi, currently we work on a migration of an Oracle Database with the following table definition (generated by ora2pg) : 

```
CREATE TABLE olga.ora_aspnet_applications (
        applicationname varchar(256) NOT NULL,
        loweredapplicationname varchar(256) NOT NULL,
        applicationid bytea NOT NULL DEFAULT SYS_GUID(),
        description varchar(256)
) ;

```
The problem is that the function SYS_GUID() is not a PostgreSQL function, could it be possible to convert it or should we create a function that return the same format (ex : `select md5(clock_timestamp()::text||random()::text||nextval('seq_new_val'))`) ?

Regards.
Nicolas

**Comment by darold** [comment]
Commit c27e525 add replacement of SYS_GUID() by uuid_generate_v4().
