### ISSUE TITLE
error, warning: Number found where operator expected at (eval 14) line 1, near "LIMIT 1"

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#278]
or Number found where operator expected at (eval 14) line 1, near "OFFSET 0"

Number found where operator expected at (eval 14) line 1, near "LIMIT 1"
	(Do you need to predeclare LIMIT?)
Bareword found where operator expected at (eval 14) line 1, near "1 OFFSET"
	(Missing operator before OFFSET?)
Number found where operator expected at (eval 14) line 1, near "OFFSET 0"
	(Do you need to predeclare OFFSET?)

Source PL/SQL:
<pre>
CREATE OR REPLACE function IDES_PRAHA22.GET_POLONAJ_UCET
(mID_NAJDATSPLT IN NAJDATSPLT.ID_NAJDATSPLT%TYPE, mID_POL_PRED IN NAJPOLOZ.ID_POL_PRED%TYPE, mTYP in CHAR  ) return VARCHAR2 
is
  Result VARCHAR2(50) ;
  mUCET_MD VARCHAR2(20);
  mUCET_D VARCHAR2(20);
begin
 
 begin
   select trim(A2.KOD_CISUCET) AS UCET_MD,  trim(A3.KOD_CISUCET) AS UCET_D 
     into mUCET_MD, mUCET_D   
   from 
       ucevpohdspl MT , UCEPOHYB A1, 
       CISUUCET A2, CISUUCET A3
   where  MT.ID_POL_PRED = mID_POL_PRED
     and  MT.ID_NAJDATSPLT=mID_NAJDATSPLT
     and  MT.ID_UCEPOHYB= A1.ID_UCEPOHYB(+) 
     and  trim(A1.typ_pol) in ('A','B')    
     and  A1.ID_CISUUCET_MD =A2.ID_CISUUCET(+)
     and  A1.ID_CISUUCET_D =A3.ID_CISUUCET(+)
     and  rownum=1;
     
     if trim(mTYP) ='M' and mUCET_MD is not null then
       Result:=mUCET_MD;
     end if;  
     
     if trim(mTYP) ='D' and mUCET_D is not null then
       Result:=mUCET_D;
     end if;  
      
     EXCEPTION
       WHEN NO_DATA_FOUND THEN             
        Result:=NULL;
  end;
 
  
   
  return(Result);
end GET_POLONAJ_UCET;
</pre>

Postgres - note (oracle outer joins symbols (+) was manually removed
<pre>
CREATE OR REPLACE FUNCTION public.get_polonaj_ucet(mid_najdatsplt bigint, mid_pol_pred bigint, mtyp character)
 RETURNS character varying
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE

  Result varchar(50) ;
  mUCET_MD varchar(20);
  mUCET_D varchar(20);

BEGIN
 
 begin
   select btrim(A2.KOD_CISUCET) AS UCET_MD,  btrim(A3.KOD_CISUCET) AS UCET_D 
     into STRICT  mUCET_MD, mUCET_D   
   from 
       ucevpohdspl MT , UCEPOHYB A1, 
       CISUUCET A2, CISUUCET A3
   where  MT.ID_POL_PRED = mID_POL_PRED
     and  MT.ID_NAJDATSPLT=mID_NAJDATSPLT
     and  MT.ID_UCEPOHYB= A1.ID_UCEPOHYB 
     and  btrim(A1.typ_pol) in ('A','B')    
     and  A1.ID_CISUUCET_MD =A2.ID_CISUUCET
     and  A1.ID_CISUUCET_D =A3.ID_CISUUCET;
     
     if btrim(mTYP) ='M' and mUCET_MD is not null then
       Result:=mUCET_MD;
     end if;  
     
     if btrim(mTYP) ='D' and mUCET_D is not null then
       Result:=mUCET_D;
     end if;  
      
      EXCEPTION
       WHEN NO_DATA_FOUND THEN             
        Result:=NULL;
  end;
 
  
   
  return(Result);
END
$function$
</pre>

**Comment by darold** [comment]
Sorry this was a typo that commit e04eca0 might fix. Rewrite of RIGHT OUTER JOIN are not supported yet, I'm currently working on it.

**Comment by darold** [comment]
Commit 7c3a4ea adds rewrite of LEFT OUTER JOIN Oracle's obsolete syntax into ANSI join syntax.
