### ISSUE TITLE
How do you change default values for columns with Ora2pg?

### ISSUE THREAD

**Issue by sjimmerson** [darold/ora2pg#279]
I would like to change the default value that is used in Oracle to a different default value in PostgreSQL.  In particular I would like to change the default value for GUID columns.  In Oracle the GUID column values are of type Varchar2(32) with a default value of SYS_GUID().  In PostgreSQL the GUID column values are of type uuid and I would like for them to have a default value of gen_random_uuid() (really any UUID generator function).  I know I could do a find and replace in the scripts after they are generated by Ora2pg, but since we will have to generate the scripts many times it would be great if Ora2pg could handle changing the default values.  I have tried to find a way to do this, but may be overlooking something.  If this capability is not there, please consider this a request to add the capability.  If the capability is already there, please help me understand how to configure this in Ora2pg.

Thanks again for adding the capability to convert Varchar2(32) to uuid.  This was another case where I could have used find and replace in the script after the fact, but it is really convenient now that Ora2pg can do this.

Shane

**Comment by darold** [comment]
Hi,

Recent commit c27e525 replace default value od SYS_GUID() with a call to uuid_generate_v4() from uuid-ossp extension. I agree that it would be useful to be able to use the function gen_random_uuid() from pgcrypto extension. I will add a configuration directive for that.

**Comment by darold** [comment]
Last commit 0786b44 add the UUID_FUNCTION configuration directive. By default Ora2Pg will convert call to SYS_GUID() into a call to uuid_generate_v4() from the uuid-ossp extension. You can redefined it to use the gen_random_uuid() function from pgcrypto extension by changing the function name

    UUID_FUNCTION    gen_random_uuid

in ora2pg.conf

**Comment by sjimmerson** [comment]
Works great!  Thanks!

**Comment by traxverlis** [comment]
it is possible to auto add CREATE EXTENSION pgcrypto; when gen_random_uuid() is used ?
