### ISSUE TITLE
Removing constraints for boolean columns

### ISSUE THREAD

**Issue by sjimmerson** [darold/ora2pg#280]
All of our columns in Oracle used as Boolean values are defined as Number(1) with a constraint <Column Name> in (0,1).  These columns are being successfully converted to the Boolean type in PostgreSQL.  I have found though that the constraint is not being removed.  All my Boolean columns in the generated DDL scripts still have a constraint like the following.

ALTER TABLE c_fq_actions ADD CONSTRAINT sys_c00111304 CHECK (IS_DELETED IN (0, 1));

Is there a way to configure Ora2pg to remove these constraints without removing constraints for other types of columns?  Notice the column name in this constraint is also in all caps even though the column name in the CREATE TABLE statement is in lower case.  If my understanding of PostgreSQL is correct, the column name in all caps in the constraint should not be an issue, but I thought I would call it out in case you wanted to change it to match the case of column name in the CREATE TABLE statement.

Thanks,
Shane

**Comment by darold** [comment]
Commit b8347f9 adds this feature.

For example, if you set:

    REPLACE_AS_BOOLEAN       NUMBER:1 CHAR:1

all columns of type NUMBER(1) and CHAR(1) will be exported as boolean in PostgreSQL and any CHECK constraints on the column will not be exported outside NOT NULL constraints.

**Comment by sjimmerson** [comment]
This is working well!  Thanks for implementing this so quickly!
