### ISSUE TITLE
Export privileges only for DB objects being exported

### ISSUE THREAD

**Issue by sjimmerson** [darold/ora2pg#281]
Is there a way to only export privileges/grants only for the DB objects that are configured to be exported?  For example, if I am only exporting the tables (specifying TABLE and GRANT) privileges for all DB objects are being exported, can Ora2pg be configured to only export privileges for the tables?

Similarly if I am exporting procedures/functions/packages (specifying PROCEDURE, FUNCTION,PACKAGE,GRANT) could privileges only for the objects being exported be set?

Thanks,
Shane

**Comment by darold** [comment]
Last commit e1af57c adds the GRANT_OBJECT configuration directive.
  When exporting GRANTs you can specify a comma separated list of
  objects for which privilege will be exported. Default is export for
  all objects. Here are the possibles values TABLE, VIEW, MATERIALIZED
  VIEW, SEQUENCE, PROCEDURE, FUNCTION, PACKAGE BODY, TYPE, SYNONYM,
  DIRECTORY. Only one object type is allowed at a time. For example
  set it to TABLE if you just want to export privilege on tables. You
  can use the -g option to overwrite it.

  When used this directive prevent the export of users unless it is
  set to USER. In this case only users definitions are exported.

Add the -g | --grant_object command line option to ora2pg to be able 
to extract privilege from the given object type. See possible values
with GRANT_OBJECT configuration directive.

**Comment by sjimmerson** [comment]
Thanks for adding this so quickly.  I have found it works great when GRANT_OBJECT is defined in the configuration file.  However, using -g cannot be used if unless the export TYPE (-t) is only set to GRANT.  Defining GRANT_OBJECT in the configuration file does not have this limitation.  When it is defined in the configuration file I can export TABLE,GRANT and specify GRANT_OBJECT as TABLE.   This will output the table definitions and the grants just for the tables which is what I was hoping for.  This is not possible using a command line like the following because ora2pg does not allow you to use -g unless -t is only set to GRANT.  Could this be changed so the command line functions similarly to the configuration file settings?

"C:\StrawberryPerl\perl\site\bin\ora2pg"  -n SPAO_SPA -t TYPE,TABLE,GRANT -g TABLE -c c:\ora2pg\ora2pg.conf -o "C:\ora2pg\SPAO Migration\SPAO_SPA Schema Migration Script.sql"

**Comment by darold** [comment]
Commit fae8943 might remove this limitation.
