### ISSUE TITLE
Oracle outer JOIN syntax is not replaced in some cases

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#282]
SELECT FROM *X* UNION ALL SELECT *Y* -- *X* -- is not translated:
The translation doesn't work in subselects too.
<pre>
select * 
from ucepohyb mt, CISUJEDN A1,
     UCEOBDOBI A2 , UDRPROVO A3,
     UDRSPRVC A4, CISUSTRD A5,
     CISUUCET A6, UCEUDUCT A7
   where MT.ID_CISUJEDN = A1.ID_CISUJEDN(+)
     AND MT.ID_UCEOBDOBI = A2.ID_UCEOBDOBI(+)
     AND MT.ID_APROVOZNA = A3.ID_PROVOZNA(+)
     AND MT.ID_ASPRAVCE= A4.ID_ASPRAVCE(+)
     AND MT.ID_CISUSTRD = A5.ID_CISUSTRD(+)
     AND MT.id_cisuucet_d = A6.id_cisuucet(+)
     AND A6.ID_CISUUCET = A7.ID_CISUUCET(+)
union all
select * 
from ucepohyb mt, CISUJEDN A1,
     UCEOBDOBI A2 , UDRPROVO A3,
     UDRSPRVC A4, CISUSTRD A5,
     CISUUCET A6, UCEUDUCT A7
   where MT.ID_CISUJEDN = A1.ID_CISUJEDN(+)
     AND MT.ID_UCEOBDOBI = A2.ID_UCEOBDOBI(+)
     AND MT.ID_APROVOZNA = A3.ID_PROVOZNA(+)
     AND MT.ID_ASPRAVCE= A4.ID_ASPRAVCE(+)
     AND MT.ID_CISUSTRD = A5.ID_CISUSTRD(+)
     AND MT.id_cisuucet_d = A6.id_cisuucet(+)
     AND A6.ID_CISUUCET = A7.ID_CISUUCET(+)
</pre>
or
<pre>
  SELECT x,
   (SELECT B3.KOD_CNAJVYPPOL
    FROM NAJPOLOZ B1,
      CISPOLPRE B2,
      CNAJVYPPOL B3
    WHERE B1.ID_PREDPIS     =A2.ID_PREDPIS
    AND B1.ID_POLONAJ       = B2.ID_POLONAJ(+)
    AND B1.ID_CNAJVYPPOL    = B3.ID_CNAJVYPPOL(+)
    AND btrim(B2.KOD_POLONAJ)='NAJ'.
     LIMIT 1) AS KOD_CNAJVYPPOL_NAJ,
  FROM y
</pre>

**Comment by darold** [comment]
Issue on UNION statement is fixed in commit 89f60fe , fix on sub-select issue will come later.

**Comment by darold** [comment]
Seem that sub query issue is fixed too, at least in the case of Oracle:
```
SELECT x,
   (SELECT B3.KOD_CNAJVYPPOL
    FROM NAJPOLOZ B1,
      CISPOLPRE B2,
      CNAJVYPPOL B3
    WHERE B1.ID_PREDPIS     =A2.ID_PREDPIS
    AND B1.ID_POLONAJ       = B2.ID_POLONAJ(+)
    AND B1.ID_CNAJVYPPOL    = B3.ID_CNAJVYPPOL(+)
    AND trim(B2.KOD_POLONAJ)='NAJ'
    AND ROWNUM = 1) AS KOD_CNAJVYPPOL_NAJ
  FROM y;
```
Converted into
```
SELECT x,
    (
        SELECT
            B3.KOD_CNAJVYPPOL
        FROM
            najpoloz b1
        LEFT OUTER JOIN cispolpre b2 ON (b1.id_polonaj = b2.id_polonaj)
        LEFT OUTER JOIN cnajvyppol b3 ON (b1.id_cnajvyppol = b3.id_cnajvyppol)
    WHERE
        B1.ID_PREDPIS = A2.ID_PREDPIS
        AND btrim (B2.KOD_POLONAJ)
        = 'NAJ'
    LIMIT 1 OFFSET 0) AS KOD_CNAJVYPPOL_NAJ
FROM y;
```

**Comment by okbob** [comment]
fixed

**Comment by darold** [comment]
There's still issue on join translation in more complex sub queries, I'm working on solving it.

**Comment by darold** [comment]
Commit  e0ab8c2 might add full support of outer join translation in sub queries.

**Comment by okbob** [comment]
it is fixed
