### ISSUE TITLE
translation to left outer join is not correct

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#283]
Oracle:
<pre>
  SELECT *
  FROM NAJDATSPLT MT ,    NAJPREDP A2 ,
    CISPREDVZT A3,    CISDPLAT A4 ,
    CISDOPLA A5 ,     CISDRPRE A6 ,
    CTYPPRED A7,      SSSHLEDEJ_A A8,
    NAJVZTAH A9,      CISMENA A10 ,
    OBPVLAST A11,     CISREKLAM A12,
    CISVYMAH A13 ,    CISTYPPR A14 ,
    CISUJEDN A15,     OBPPRSTR A16,
    CISKOLUR A17,     SSSLOGIN A18,
    SSSLOGIN A19,     CISMENA A20 ,
    CLEOSOBY A21,     PAROPAR A22,
    NAJUDAJE A23,     CISUSTRD A24 ,
    NAJSIPOCIS A25,   CISDRUHPRA A26,
    CNAJSTAV A27 ,    UCEVFAKLOK A28,
    UCEPOLFAK A29,    UCEHLAFAK A30,
    CISKATUZ A31,     CISPOPPR A32 ,
    NAJDATSPLT A33 ,  UCEDOKLAD A34,
    CISUOPER A35,     PAROSOBA A36,
    UCEDOKLAD A37
  WHERE MT.ID_PREDPIS  = A2.ID_PREDPIS(+)
  AND MT.ID_CISREKLAM  = A12.ID_CISREKLAM(+)
  AND MT.ID_CISVYMAH   = A13.ID_CISVYMAH(+)
  AND A2.ID_CISPREDVZT = A3.ID_CISPREDVZT(+)
  AND A2.ID_DPLA       = A4.ID_DPLA(+)
  AND A2.ID_DOBAPLAT   = A5.ID_DOBAPLAT(+)
  AND MT.ID_DRUPRE     = A6.ID_DRUPRE(+)
  AND A2.ID_CTYPPRED   = A7.ID_CTYPPRED(+)
  AND MT.ID_NAJVZTAH   = A8.ID_NAJVZTAH(+)
  AND A8.TYP           = 'N'
  AND A8.HLAVNI        = 'H'
  AND MT.ID_NAJVZTAH   = A9.ID_NAJVZTAH(+)
  AND A2.ID_MENA       = A10.ID_MENA(+)
  AND A8.ID_VLASTOBJ   = A11.ID_VLASTNIK(+)
  AND A8.ID_TYPPRS     = A14.ID_TYPPRS(+)
  AND A9.ID_CISUJEDN   = A15.ID_CISUJEDN(+)
  AND A8.ID_PROSTOR    = A16.ID_PROSTOR(+)
  AND A8.ID_CCLE       = A21.ID_CCLE(+)
  AND A21.ID_PAR       = A22.ID_PAR(+)
  AND A21.ID_OSOB      = A36.ID_OSOB(+)
  AND A16.ID_KOLURC    = A17.ID_KOLURC(+)
  AND MT.LIDENT        = A18.ID_SSSLOGIN(+)
  AND MT.LIDENT_ZMENA  = A19.ID_SSSLOGIN(+)
  AND A2.ID_MENA       = A20.ID_MENA(+)
  AND MT.ID_NAJUDAJE   = A23.ID_NAJUDAJE(+)
  AND MT.ID_CISUSTRD   = A24.ID_CISUSTRD(+)
  AND A2.ID_NAJSIPOCIS = A25.ID_NAJSIPOCIS(+)
  AND A2.ID_CISDRUHPRA = A26.ID_CISDRUHPRA(+)
  AND A23.ID_CNAJSTAV  = A27.ID_CNAJSTAV(+)
  AND MT.ID_NAJDATSPLT = A28.ID_NAJDATSPLT(+)
  AND A28.ID_UCEPOLFAK = A29.ID_UCEPOLFAK(+)
  AND A29.ID_UCEHLAFAK = A30.ID_UCEHLAFAK(+)
  AND A8.ID_UZEMI      = A31.ID_UZEMI(+)
  AND A16.ID_POPIPR    = A32.ID_POPIPR(+)
  AND A2.ID_NAJDATSPLT = A33.ID_NAJDATSPLT(+)
  AND MT.ID_UCEDOKLAD_DANDOK = A34.ID_UCEDOKLAD(+)
  AND MT.ID_CISUOPER =A35.ID_CISUOPER(+)
  AND A33.ID_UCEDOKLAD_DANDOK = A37.ID_UCEDOKLAD(+)
</pre>
Ora2pg Result:
<pre>
SELECT *
FROM najdatsplt mt 
LEFT OUTER JOIN najpredp a2 ON (mt.id_predpis = a2.id_predpis) 
LEFT OUTER JOIN najdatsplt mt ON (mt.id_cisreklam = a12.id_cisreklam) 
LEFT OUTER JOIN najdatsplt mt ON (mt.id_cisvymah = a13.id_cisvymah) 
LEFT OUTER JOIN najpredp a2 ON (a2.id_cispredvzt = a3.id_cispredvzt)
LEFT OUTER JOIN najpredp a2 ON (a2.id_dpla = a4.id_dpla) 
LEFT OUTER JOIN najpredp a2 ON (a2.id_dobaplat = a5.id_dobaplat) 
LEFT OUTER JOIN najdatsplt mt ON (mt.id_drupre = a6.id_drupre)
LEFT OUTER JOIN najpredp a2 ON (a2.id_ctyppred = a7.id_ctyppred) 
LEFT OUTER JOIN najdatsplt mt ON (mt.id_najvztah = a8.id_najvztah) 
LEFT OUTER JOIN najdatsplt mt ON (mt.id_najvztah = a9.id_najvztah) 
LEFT OUTER JOIN najpredp a2 ON (a2.id_mena = a10.id_mena) 
LEFT OUTER JOIN ssshledej_a a8 ON (a8.id_vlastobj = a11.id_vlastnik) 
LEFT OUTER JOIN ssshledej_a a8 ON (a8.id_typprs = a14.id_typprs) 
LEFT OUTER JOIN najvztah a9 ON (a9.id_cisujedn = a15.id_cisujedn) 
LEFT OUTER JOIN ssshledej_a a8 ON (a8.id_prostor = a16.id_prostor) 
LEFT OUTER JOIN ssshledej_a a8 ON (a8.id_ccle = a21.id_ccle)
LEFT OUTER JOIN cleosoby a21 ON (a21.id_par = a22.id_par) 
LEFT OUTER JOIN cleosoby a21 ON (a21.id_osob = a36.id_osob) 
LEFT OUTER JOIN obpprstr a16 ON (a16.id_kolurc = a17.id_kolurc) 
LEFT OUTER JOIN najdatsplt mt ON (mt.lident = a18.id_ssslogin)
LEFT OUTER JOIN najdatsplt mt ON (mt.lident_zmena = a19.id_ssslogin) 
LEFT OUTER JOIN najpredp a2 ON (a2.id_mena = a20.id_mena) 
LEFT OUTER JOIN najdatsplt mt ON (mt.id_najudaje = a23.id_najudaje) 
LEFT OUTER JOIN najdatsplt mt ON (mt.id_cisustrd = a24.id_cisustrd) 
LEFT OUTER JOIN najpredp a2 ON (a2.id_najsipocis = a25.id_najsipocis)
LEFT OUTER JOIN najpredp a2 ON (a2.id_cisdruhpra = a26.id_cisdruhpra) 
LEFT OUTER JOIN najudaje a23 ON (a23.id_cnajstav = a27.id_cnajstav) 
LEFT OUTER JOIN najdatsplt mt ON (mt.id_najdatsplt = a28.id_najdatsplt) 
LEFT OUTER JOIN ucevfaklok a28 ON (a28.id_ucepolfak = a29.id_ucepolfak) 
LEFT OUTER JOIN ucepolfak a29 ON (a29.id_ucehlafak = a30.id_ucehlafak) 
LEFT OUTER JOIN ssshledej_a a8 ON (a8.id_uzemi = a31.id_uzemi)
LEFT OUTER JOIN obpprstr a16 ON (a16.id_popipr = a32.id_popipr) 
LEFT OUTER JOIN najpredp a2 ON (a2.id_najdatsplt = a33.id_najdatsplt) 
LEFT OUTER JOIN najdatsplt mt ON (mt.id_ucedoklad_dandok = a34.id_ucedoklad) 
LEFT OUTER JOIN najdatsplt mt ON (mt.id_cisuoper = a35.id_cisuoper) 
LEFT OUTER JOIN najdatsplt a33 ON (a33.id_ucedoklad_dandok = a37.id_ucedoklad) 
WHERE A8.TYP           = 'N' AND A8.HLAVNI        = 'H';;
</pre>
 najdatsplt mt  is badly repeated.

Expected:
<pre>
FROM NAJDATSPLT MT
LEFT JOIN NAJPREDP A2 ON MT.ID_PREDPIS = A2.ID_PREDPIS
LEFT JOIN CISPREDVZT A3 ON A2.ID_CISPREDVZT = A3.ID_CISPREDVZT
LEFT JOIN CISDPLAT A4 ON A2.ID_DPLA = A4.ID_DPLA
LEFT JOIN CISDOPLA A5 ON A2.ID_DOBAPLAT = A5.ID_DOBAPLAT
LEFT JOIN CISDRPRE A6 ON MT.ID_DRUPRE = A6.ID_DRUPRE
LEFT JOIN CTYPPRED A7 ON A2.ID_CTYPPRED = A7.ID_CTYPPRED
LEFT JOIN SSSHLEDEJ_A A8 ON MT.ID_NAJVZTAH = A8.ID_NAJVZTAH
LEFT JOIN NAJVZTAH A9 ON MT.ID_NAJVZTAH = A9.ID_NAJVZTAH
LEFT JOIN CISMENA A10 ON A2.ID_MENA = A10.ID_MENA
LEFT JOIN OBPVLAST A11 ON A8.ID_VLASTOBJ = A11.ID_VLASTNIK
LEFT JOIN CISREKLAM A12 ON MT.ID_CISREKLAM = A12.ID_CISREKLAM
LEFT JOIN CISVYMAH A13 ON MT.ID_CISVYMAH = A13.ID_CISVYMAH
LEFT JOIN CISTYPPR A14 ON A8.ID_TYPPRS = A14.ID_TYPPRS
LEFT JOIN CISUJEDN A15 ON A9.ID_CISUJEDN = A15.ID_CISUJEDN
LEFT JOIN OBPPRSTR A16 ON A8.ID_PROSTOR = A16.ID_PROSTOR
LEFT JOIN CISKOLUR A17 ON A16.ID_KOLURC = A17.ID_KOLURC
LEFT JOIN SSSLOGIN A18 ON MT.LIDENT = A18.ID_SSSLOGIN
LEFT JOIN SSSLOGIN A19 ON MT.LIDENT_ZMENA = A19.ID_SSSLOGIN
LEFT JOIN CISMENA A20 ON A2.ID_MENA = A20.ID_MENA
LEFT JOIN CLEOSOBY A21 ON A8.ID_CCLE = A21.ID_CCLE
LEFT JOIN PAROPAR A22 ON A21.ID_PAR = A22.ID_PAR
LEFT JOIN NAJUDAJE A23 ON MT.ID_NAJUDAJE = A23.ID_NAJUDAJE
LEFT JOIN CISUSTRD A24 ON MT.ID_CISUSTRD = A24.ID_CISUSTRD
LEFT JOIN NAJSIPOCIS A25 ON A2.ID_NAJSIPOCIS = A25.ID_NAJSIPOCIS
LEFT JOIN CISDRUHPRA A26 ON A2.ID_CISDRUHPRA = A26.ID_CISDRUHPRA
LEFT JOIN CNAJSTAV A27 ON A23.ID_CNAJSTAV = A27.ID_CNAJSTAV
LEFT JOIN UCEVFAKLOK A28 ON MT.ID_NAJDATSPLT = A28.ID_NAJDATSPLT
LEFT JOIN UCEPOLFAK A29 ON A28.ID_UCEPOLFAK = A29.ID_UCEPOLFAK
LEFT JOIN UCEHLAFAK A30 ON A29.ID_UCEHLAFAK = A30.ID_UCEHLAFAK
LEFT JOIN CISKATUZ A31 ON A8.ID_UZEMI = A31.ID_UZEMI
LEFT JOIN CISPOPPR A32 ON A16.ID_POPIPR = A32.ID_POPIPR
LEFT JOIN NAJDATSPLT A33 ON A2.ID_NAJDATSPLT = A33.ID_NAJDATSPLT
LEFT JOIN UCEDOKLAD A34 ON MT.ID_UCEDOKLAD_DANDOK = A34.ID_UCEDOKLAD
LEFT JOIN CISUOPER A35 ON MT.ID_CISUOPER = A35.ID_CISUOPER
LEFT JOIN PAROSOBA A36 ON A21.ID_OSOB = A36.ID_OSOB
LEFT JOIN UCEDOKLAD A37 ON A33.ID_UCEDOKLAD_DANDOK = A37.ID_UCEDOKLAD
WHERE A8.HLAVNI            = 'H'
AND A8.TYP                 = 'N';
</pre>

**Comment by darold** [comment]
Fixed in commit 89f60fe.

**Comment by okbob** [comment]
fixed
