### ISSUE TITLE
Missing space between keyword AS and label

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#284]
transformation produces wrong expression **ENDAS**

     CASE WHEN  A18.ID_SSSLOGIN IS NULL THEN MT.IDENT  ELSE A18.JMENO ENDAS LIDENT_JMENO,

Original:

    DECODE(A18.ID_SSSLOGIN, NULL, MT.IDENT, A18.JMENO) AS LIDENT_JMENO,

**Comment by darold** [comment]
Fixed in commit dab20f2

**Comment by okbob** [comment]
fixed
