### ISSUE TITLE
Mix inner join and Oracle outer join is not well translated

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#285]
Oracle view:
<pre>
CREATE OR REPLACE VIEW V_NAJVZPLAT AS
SELECT MT.ID_NAJVZTAH , A2.ID_NAJPLATBY ,
         A1.ROZ_CASTKA , MT.ZA_OBDOBI ,
         A2.OBDOBI_OD ,
         A2.OBDOBI_DO ,A2.DATUM_ZAPLACENI,
         A2.DATUM_BANKVYPIS ,
         A2.UCE_DOKLAD ,A2.CASTKACELKEM , 
         A2.VARS, 
         A1.DAT_URCENI, A1.DAT_STORNA , A2.SPECS,
         A2.DAVKA , A2.NEURCENO , A2.ECASTKACELKEM , 
         A2.KURS ,A2.KURS_DATUM , A2.ENEURCENO ,
         A2.ROK AS ROK_ZAPL , MT.ROK AS ROK_OBDOBI ,
         MT.ID_NAJDATSPLT , A1.PLATNOST_OD,
         A2.PLATNOST_DO  , A1.ID_NAJPROS , A1.ID_NAJVPLAPRE,
         A2.POZNAMKA , MT.ID_DRUPRE, 
         A3.KOD_DRUPRE, A3.J1_NAZEV AS DRUPRE,
         MT.ROK , MT.MESIC, A2.ID_MENA,
         A4.J1_nazev as NAZEV_CISMENA,
         MT.PLATNOST_DO AS NAJDATSPLT_PLATNOST_DO
     FROM NAJDATSPLT MT , NAJVPLAPRE A1 , 
         NAJPLATBY A2, CISDRPRE A3,
         CISMENA A4
     WHERE MT.ID_NAJDATSPLT = A1.ID_NAJDATSPLT
        AND  A1.ID_NAJPLATBY = A2.ID_NAJPLATBY
        AND MT.ID_DRUPRE = A3.ID_DRUPRE(+)
        AND A2.ID_MENA= A4.ID_MENA(+);
</pre>

Ora2pg
<pre>
CREATE OR REPLACE VIEW v_najvzplat (id_najvztah, id_najplatby, roz_castka, za_obdobi, obdobi_od, obdobi_do, datum_zaplaceni, datum_bankvypis, uce_doklad, castkacelkem, vars, dat_urceni, dat_storna, specs, davka, neurceno, ecastkacelkem, kurs, kurs_datum, eneurceno, rok_zapl, rok_obdobi, id_najdatsplt, platnost_od, platnost_do, id_najpros, id_najvplapre, poznamka, id_drupre, kod_drupre, drupre, rok, mesic, id_mena, nazev_cismena, najdatsplt_platnost_do) AS SELECT  MT.ID_NAJVZTAH , A2.ID_NAJPLATBY ,
         A1.ROZ_CASTKA , MT.ZA_OBDOBI ,
         A2.OBDOBI_OD ,
         A2.OBDOBI_DO ,A2.DATUM_ZAPLACENI,
         A2.DATUM_BANKVYPIS ,
         A2.UCE_DOKLAD ,A2.CASTKACELKEM , 
         A2.VARS, 
         A1.DAT_URCENI, A1.DAT_STORNA , A2.SPECS,
         A2.DAVKA , A2.NEURCENO , A2.ECASTKACELKEM , 
         A2.KURS ,A2.KURS_DATUM , A2.ENEURCENO ,
         A2.ROK AS ROK_ZAPL , MT.ROK AS ROK_OBDOBI ,
         MT.ID_NAJDATSPLT , A1.PLATNOST_OD,
         A2.PLATNOST_DO  , A1.ID_NAJPROS , A1.ID_NAJVPLAPRE,
         A2.POZNAMKA , MT.ID_DRUPRE, 
         A3.KOD_DRUPRE, A3.J1_NAZEV AS DRUPRE,
         MT.ROK , MT.MESIC, A2.ID_MENA,
         A4.J1_nazev as NAZEV_CISMENA,
         MT.PLATNOST_DO AS NAJDATSPLT_PLATNOST_DO
      FROM najdatsplt mt LEFT OUTER JOIN cisdrpre a3 ON (mt.id_drupre = a3.id_drupre) LEFT OUTER JOIN cismena a4 ON (a2.id_mena = a4.id_mena) WHERE MT.ID_NAJDATSPLT = A1.ID_NAJDATSPLT AND A1.ID_NAJPLATBY = A2.ID_NAJPLATBY   ;;
</pre>

Expected:
<pre>
CREATE OR REPLACE VIEW v_najvzplat (id_najvztah, id_najplatby, roz_castka, za_obdobi, obdobi_od, obdobi_do, datum_zaplaceni, datum_bankvypis, uce_doklad, castkacelkem, vars, dat_urceni, dat_storna, specs, davka, neurceno, ecastkacelkem, kurs, kurs_datum, eneurceno, rok_zapl, rok_obdobi, id_najdatsplt, platnost_od, platnost_do, id_najpros, id_najvplapre, poznamka, id_drupre, kod_drupre, drupre, rok, mesic, id_mena, nazev_cismena, najdatsplt_platnost_do) AS SELECT  MT.ID_NAJVZTAH , A2.ID_NAJPLATBY ,
         A1.ROZ_CASTKA , MT.ZA_OBDOBI ,
         A2.OBDOBI_OD ,
         A2.OBDOBI_DO ,A2.DATUM_ZAPLACENI,
         A2.DATUM_BANKVYPIS ,
         A2.UCE_DOKLAD ,A2.CASTKACELKEM , 
         A2.VARS, 
         A1.DAT_URCENI, A1.DAT_STORNA , A2.SPECS,
         A2.DAVKA , A2.NEURCENO , A2.ECASTKACELKEM , 
         A2.KURS ,A2.KURS_DATUM , A2.ENEURCENO ,
         A2.ROK AS ROK_ZAPL , MT.ROK AS ROK_OBDOBI ,
         MT.ID_NAJDATSPLT , A1.PLATNOST_OD,
         A2.PLATNOST_DO  , A1.ID_NAJPROS , A1.ID_NAJVPLAPRE,
         A2.POZNAMKA , MT.ID_DRUPRE, 
         A3.KOD_DRUPRE, A3.J1_NAZEV AS DRUPRE,
         MT.ROK , MT.MESIC, A2.ID_MENA,
         A4.J1_nazev as NAZEV_CISMENA,
         MT.PLATNOST_DO AS NAJDATSPLT_PLATNOST_DO
      FROM najdatsplt mt 
      LEFT OUTER JOIN cisdrpre a3 ON (mt.id_drupre = a3.id_drupre),
      NAJVPLAPRE A1 , 
      NAJPLATBY A2
      LEFT OUTER JOIN cismena a4 ON (a2.id_mena = a4.id_mena) 
      WHERE MT.ID_NAJDATSPLT = A1.ID_NAJDATSPLT 
        AND A1.ID_NAJPLATBY = A2.ID_NAJPLATBY ;
</pre>
Note: Outer joins are generated to one long line. Is possible to break line after every JOIN x ON y?

**Comment by darold** [comment]
Commit 681f835 might fix that.

I've also added a newline before the JOIN and WHERE clause for easiest reading. Note that next major release will include an SQL / PLPGSQL beautifier, I'm working on adding PLPGSQL support to pgFormatter in parallel.

Also about JOIN rewrite there will be huge limitation on the translation following the join complexity, regex is not an efficient way to solves all syntax possibility. We plan to use a parser to bypass those limitation, but until there I'm doing my best to provide the maximum of automatic conversion :-)

**Comment by okbob** [comment]
I am really surprised so regexp based design can do this work. Sure - the parser based design should be ultimate.

**Comment by okbob** [comment]
Some last commits does breaks the translation - I am working on test case.

**Comment by okbob** [comment]
it is fixed
