### ISSUE TITLE
Wrong ROWNUM replacement in subselect

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#287]
Oracle:
<pre>
CREATE OR REPLACE VIEW V_OBPPLOCH AS
SELECT MT.ID_PLOCHA , MT.ID_PROSTOR ,MT.ID_SEGMENT ,
         MT.ID_MISTNOST ,MT.ID_OBJEKT , MT.ID_STAVOBJ ,
         MT.ID_PRINALOBJ,MT.ID_ODBMISTO,MT.ID_PARCELA,
         MT.PLOCHA ,MT.VYPOCTENO ,MT.KOEFICIENT , MT.PLATNOST_OD ,
         MT.PLATNOST_DO ,MT.IDENT , MT.POZNAMKA ,MT.ID_TYP_PLOCHY ,
         MT.PLOCHAZDROJ ,MT.VIDET ,MT.ID_NAJVYH176 ,MT.CVZNIKRADK ,
         MT.ID_ASPRAVCE , A1.J1_NAZEV AS TYPPLOCHY,
         A1.GRUPPA , A1.KOEFICIENT AS TYPPLKOEF ,
         A1.KOD_TYP_PLOCHY,MT.POSLEDNI,MT.ID_APROVOZNA,
         (case
           when mt.id_mistnost is not null then
                       (select j1_nazev from cisujedn B1, obpvlast B2, ssshledej B3
                         where B1.id_cisujedn=B2.id_cisujedn and
                         B2.id_vlastnik = B3.id_vlastobj and trim(B3.typ)='M'
                         and B3.id_mistnost= mt.id_mistnost and rownum=1)
           when mt.id_prostor is not null then
                       (select j1_nazev from cisujedn B1, obpvlast B2, ssshledej_a B3
                         where B1.id_cisujedn=B2.id_cisujedn and
                         B2.id_vlastnik = B3.id_vlastobj and trim(B3.typ)='P'
                         and B3.id_prostor= mt.id_prostor and rownum=1)
          when mt.id_stavobj is not null then
                       (select j1_nazev from cisujedn B1, obpvlast B2, ssshledej_a B3
                         where B1.id_cisujedn=B2.id_cisujedn and
                         B2.id_vlastnik = B3.id_vlastnik and trim(B3.typ)='B'
                         and B3.id_stavobj= mt.id_stavobj and rownum=1)
         when mt.id_segment is not null then
                       (select j1_nazev from cisujedn B1, obpvlast B2, ssshledej_a B3
                         where B1.id_cisujedn=B2.id_cisujedn and
                         B2.id_vlastnik = B3.id_vlastnik and trim(B3.typ)='S'
                         and B3.id_segment= mt.id_segment and rownum=1)
         when mt.id_objekt is not null then
                       (select j1_nazev from cisujedn B1, obpvlast B2, ssshledej_a B3
                         where B1.id_cisujedn=B2.id_cisujedn and
                         B2.id_vlastnik = B3.id_vlastnik and trim(B3.typ)='O'
                         and B3.id_objekt= mt.id_objekt and rownum=1)
          else ''
          end ) AS NAZEV_CISUJEDN
     FROM OBPPLOCH MT , CISTYPPL A1
         WHERE MT.ID_TYP_PLOCHY = A1.ID_TYP_PLOCHY(+)
               AND MT.ID_SKUTPRS IS NULL;
</pre>
Ora2pg result:
<pre>
CREATE OR REPLACE VIEW v_obpploch (id_plocha, id_prostor, id_segment, id_mistnost, id_objekt, id_stavobj, id_prinalobj, id_odbmisto, id_parcela, plocha, vypocteno, koeficient, platnost_od, platnost_do, ident, poznamka, id_typ_plochy, plochazdroj, videt, id_najvyh176, cvznikradk, id_aspravce, typplochy, gruppa, typplkoef, kod_typ_plochy, posledni, id_aprovozna, nazev_cisujedn) AS SELECT  MT.ID_PLOCHA , MT.ID_PROSTOR ,MT.ID_SEGMENT ,
         MT.ID_MISTNOST ,MT.ID_OBJEKT , MT.ID_STAVOBJ ,
         MT.ID_PRINALOBJ,MT.ID_ODBMISTO,MT.ID_PARCELA,
         MT.PLOCHA ,MT.VYPOCTENO ,MT.KOEFICIENT , MT.PLATNOST_OD ,
         MT.PLATNOST_DO ,MT.IDENT , MT.POZNAMKA ,MT.ID_TYP_PLOCHY ,
         MT.PLOCHAZDROJ ,MT.VIDET ,MT.ID_NAJVYH176 ,MT.CVZNIKRADK ,
         MT.ID_ASPRAVCE , A1.J1_NAZEV AS TYPPLOCHY,
         A1.GRUPPA , A1.KOEFICIENT AS TYPPLKOEF ,
         A1.KOD_TYP_PLOCHY,MT.POSLEDNI,MT.ID_APROVOZNA,
         (case
           when mt.id_mistnost is not null then(select j1_nazev  FROM cisujedn B1, obpvlast B2, ssshledej B3
                         where B1.id_cisujedn=B2.id_cisujedn and
                         B2.id_vlastnik = B3.id_vlastobj and btrim(B3.typ)='M'
                         and B3.id_mistnost= mt.id_mistnost )
           when mt.id_prostor is not null then(select j1_nazev from cisujedn B1, obpvlast B2, ssshledej_a B3
                         where B1.id_cisujedn=B2.id_cisujedn and
                         B2.id_vlastnik = B3.id_vlastobj and btrim(B3.typ)='P'
                         and B3.id_prostor= mt.id_prostor and rownum=1)
          when mt.id_stavobj is not null then(select j1_nazev from cisujedn B1, obpvlast B2, ssshledej_a B3
                         where B1.id_cisujedn=B2.id_cisujedn and
                         B2.id_vlastnik = B3.id_vlastnik and btrim(B3.typ)='B'
                         and B3.id_stavobj= mt.id_stavobj and rownum=1)
         when mt.id_segment is not null then(select j1_nazev from cisujedn B1, obpvlast B2, ssshledej_a B3
                         where B1.id_cisujedn=B2.id_cisujedn and
                         B2.id_vlastnik = B3.id_vlastnik and btrim(B3.typ)='S'
                         and B3.id_segment= mt.id_segment and rownum=1)
         when mt.id_objekt is not null then(select j1_nazev from cisujedn B1, obpvlast B2, ssshledej_a B3
                         where B1.id_cisujedn=B2.id_cisujedn and
                         B2.id_vlastnik = B3.id_vlastnik and btrim(B3.typ)='O'
                         and B3.id_objekt= mt.id_objekt and rownum=1)
          else ''
          end  LIMIT 1 OFFSET 0) AS NAZEV_CISUJEDN
     FROM obpploch mt
LEFT OUTER JOIN cistyppl a1 ON (mt.id_typ_plochy = a1.id_typ_plochy)
WHERE MT.ID_SKUTPRS IS NULL ;
</pre>

**Comment by darold** [comment]
Might be fixed too with commit 51ee9a4

**Comment by okbob** [comment]
fixed
