### ISSUE TITLE
Mix of inner join and outer join is not translated correctly

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#288]
Oracle:
<pre>
SELECT *
FROM SSSHLEDEJ_A MT , NAJPROS A1 ,
          NAJUDAJE A2 , NAJVZTAH A3 ,
          NAJPREDP A4 , CISPREDVZT A5 ,
          NAJPREDP A6 , CLEOSOBY A7 ,
          PARADR A8,
          CODDNAJVZT A9 , CNAJPEN A10 ,
          CISUJEDN A11, CISDOPLA A12,
          CISDPLAT A13,OBPPRSTR A14,
          CISKOLUR A15,
          SSSLOGIN A16, SSSLOGIN A17,
          UCEVSTRDVZT A18, CISUSTRD A19,
          PAROPAR A20 , CISMENA A21,
          CISMENA A22 , CLEOSOBY A23,
          PAROPAR A24, CNAJVZTAH A25,
          CNAJSTAV A26, OBPBLK A27 ,
          CISKATUZ A28, CISDOPLA A29 ,
          PAROPAR A30, OBPVLAST A31,
          NAJVSDRUVZT A32, NAJSDRUZENI A33,
          CNAJDUVOD A34, OBPDUM A35,
          CISSTAPR A36, OBPVLAST A37,
          OBPKATUD A38, PAROSOBA A39,
          CLEINSREJ A40, CISPOPPR A41,
          CISUOPER A42
     WHERE
           MT.TYP = 'N' AND
           MT.HLAVNI = 'H' AND
           MT.ID_NAJPROS = A1.ID_NAJPROS(+) AND
           A1.ID_NAJUDAJE = A2.ID_NAJUDAJE AND
           A2.ID_NAJVZTAH = A3.ID_NAJVZTAH AND
           A3.ID_PREDPIS = A4.ID_PREDPIS(+) AND
           A3.ID_CISPREDVZT = A5.ID_CISPREDVZT(+) AND
           A3.ID_CODDNAJVZT = A9.ID_CODDNAJVZT(+) AND
           A4.ID_PREDPIS = A6.ID_PREDPIS_ZAHRNUJE(+) AND
           A4.ID_DPLA = A13.ID_DPLA(+) AND
           MT.ID_CCLE = A7.ID_CCLE(+) AND
           MT.ID_ADR = A8.ID_ADR(+) AND
           A2.ID_CNAJPEN = A10.ID_CNAJPEN(+) AND
           A3.ID_CISUJEDN = A11.ID_CISUJEDN(+) AND
           A4.ID_DOBAPLAT = A12.ID_DOBAPLAT(+) AND
           A6.ID_DOBAPLAT = A29.ID_DOBAPLAT(+) AND
           MT.ID_PROSTOR = A14.ID_PROSTOR(+) AND
           A14.ID_KOLURC = A15.ID_KOLURC(+)
           AND A3.LIDENT = A16.ID_SSSLOGIN(+)
           AND A3.LIDENT_ZMENA = A17.ID_SSSLOGIN(+)
           AND A3.ID_NAJVZTAH = A18.ID_NAJVZTAH(+)
           AND A18.ID_CISUSTRD = A19.ID_CISUSTRD(+)
           AND A7.ID_PAR = A20.ID_PAR(+)
           AND A4.ID_MENA = A21.ID_MENA(+)
           AND A6.ID_MENA = A22.ID_MENA(+)
           AND A11.ID_CCLE =  A23.ID_CCLE(+)
           AND A23.ID_PAR = A24.ID_PAR(+)
           AND A2.ID_CNAJSTAV=A26.ID_CNAJSTAV(+)
           AND A2.ID_CNAJVZTAH=A25.ID_CNAJVZTAH(+)
           AND MT.ID_OBJEKT = A27.ID_OBJEKT(+)
           AND MT.ID_UZEMI = A28.ID_UZEMI(+)
           AND A7.ID_PAR = A30.ID_PAR(+)
           AND MT.ID_VLASTOBJ=A31.ID_VLASTNIK(+)
           AND A3.ID_NAJVZTAH=A32.ID_NAJVZTAH(+)
           AND A32.ID_NAJSDRUZENI= A33.ID_NAJSDRUZENI(+)
           AND A2.ID_CNAJDUVOD = A34.ID_CNAJDUVOD(+)
           AND MT.ID_SEGMENT =A35.ID_SEGMENT(+)
           AND A14.ID_STAVPR = A36.ID_STAVPR(+)
           AND MT.ID_VLASTNIK=A37.ID_VLASTNIK(+)
           AND A37.ID_VLASTNIK=A38.ID_VLASTNIK(+)
           AND A7.ID_OSOB=A39.ID_OSOB(+)
           AND A7.ID_CLEINSREJ_IMP=A40.ID_CLEINSREJ(+)
           AND A14.ID_POPIPR=A41.ID_POPIPR(+)
           AND A2.ID_CISUOPER =A42.ID_CISUOPER(+)
</pre>
Postgres:
<pre>
      FROM ssshledej_a mt
LEFT OUTER JOIN najpros a1 ON (mt.id_najpros = a1.id_najpros)
,najvztah a3
LEFT OUTER JOIN najpredp a4 ON (a3.id_predpis = a4.id_predpis)
LEFT OUTER JOIN cispredvzt a5 ON (a3.id_cispredvzt = a5.id_cispredvzt)
LEFT OUTER JOIN coddnajvzt a9 ON (a3.id_coddnajvzt = a9.id_coddnajvzt)
LEFT OUTER JOIN najpredp a6 ON (a4.id_predpis = a6.id_predpis_zahrnuje)
LEFT OUTER JOIN cisdplat a13 ON (a4.id_dpla = a13.id_dpla)
LEFT OUTER JOIN cleosoby a7 ON (mt.id_ccle = a7.id_ccle)
LEFT OUTER JOIN paradr a8 ON (mt.id_adr = a8.id_adr)
,najudaje a2
LEFT OUTER JOIN cnajpen a10 ON (a2.id_cnajpen = a10.id_cnajpen)
LEFT OUTER JOIN cisujedn a11 ON (a3.id_cisujedn = a11.id_cisujedn)
LEFT OUTER JOIN cisdopla a12 ON (a4.id_dobaplat = a12.id_dobaplat)
LEFT OUTER JOIN cisdopla a29 ON (a6.id_dobaplat = a29.id_dobaplat)
LEFT OUTER JOIN obpprstr a14 ON (mt.id_prostor = a14.id_prostor)
LEFT OUTER JOIN ciskolur a15 ON (a14.id_kolurc = a15.id_kolurc)
LEFT OUTER JOIN ssslogin a16 ON (a3.lident = a16.id_ssslogin)
LEFT OUTER JOIN ssslogin a17 ON (a3.lident_zmena = a17.id_ssslogin)
LEFT OUTER JOIN ucevstrdvzt a18 ON (a3.id_najvztah = a18.id_najvztah)
LEFT OUTER JOIN cisustrd a19 ON (a18.id_cisustrd = a19.id_cisustrd)
LEFT OUTER JOIN paropar a20 ON (a7.id_par = a20.id_par)
LEFT OUTER JOIN cismena a21 ON (a4.id_mena = a21.id_mena)
LEFT OUTER JOIN cismena a22 ON (a6.id_mena = a22.id_mena)
LEFT OUTER JOIN cleosoby a23 ON (a11.id_ccle = a23.id_ccle)
LEFT OUTER JOIN paropar a24 ON (a23.id_par = a24.id_par)
LEFT OUTER JOIN cnajstav a26 ON (a2.id_cnajstav = a26.id_cnajstav)
LEFT OUTER JOIN cnajvztah a25 ON (a2.id_cnajvztah = a25.id_cnajvztah)
LEFT OUTER JOIN obpblk a27 ON (mt.id_objekt = a27.id_objekt)
LEFT OUTER JOIN ciskatuz a28 ON (mt.id_uzemi = a28.id_uzemi)
LEFT OUTER JOIN paropar a30 ON (a7.id_par = a30.id_par)
LEFT OUTER JOIN obpvlast a31 ON (mt.id_vlastobj = a31.id_vlastnik)
LEFT OUTER JOIN najvsdruvzt a32 ON (a3.id_najvztah = a32.id_najvztah)
LEFT OUTER JOIN najsdruzeni a33 ON (a32.id_najsdruzeni = a33.id_najsdruzeni)
LEFT OUTER JOIN cnajduvod a34 ON (a2.id_cnajduvod = a34.id_cnajduvod)
LEFT OUTER JOIN obpdum a35 ON (mt.id_segment = a35.id_segment)
LEFT OUTER JOIN cisstapr a36 ON (a14.id_stavpr = a36.id_stavpr)
LEFT OUTER JOIN obpvlast a37 ON (mt.id_vlastnik = a37.id_vlastnik)
LEFT OUTER JOIN obpkatud a38 ON (a37.id_vlastnik = a38.id_vlastnik)
LEFT OUTER JOIN parosoba a39 ON (a7.id_osob = a39.id_osob)
LEFT OUTER JOIN cleinsrej a40 ON (a7.id_cleinsrej_imp = a40.id_cleinsrej)
LEFT OUTER JOIN cispoppr a41 ON (a14.id_popipr = a41.id_popipr)
LEFT OUTER JOIN cisuoper a42 ON (a2.id_cisuoper = a42.id_cisuoper)
WHERE MT.TYP = 'N' AND MT.HLAVNI = 'H'  AND A1.ID_NAJUDAJE = A2.ID_NAJUDAJE AND A2.ID_NAJVZTAH = A3.ID_NAJVZTAH  
</pre>

Expected:
<pre>
FROM
SSSHLEDEJ_A MT
LEFT OUTER JOIN NAJPROS  A1 ON  MT.ID_NAJPROS=A1.ID_NAJPROS
LEFT OUTER JOIN CLEOSOBY  A7 ON  MT.ID_CCLE=A7.ID_CCLE
LEFT OUTER JOIN PARADR  A8 ON  MT.ID_ADR=A8.ID_ADR
LEFT OUTER JOIN OBPPRSTR  A14 ON  MT.ID_PROSTOR=A14.ID_PROSTOR
LEFT OUTER JOIN CISKOLUR  A15 ON  A14.ID_KOLURC=A15.ID_KOLURC
LEFT OUTER JOIN PAROPAR  A20 ON  A7.ID_PAR=A20.ID_PAR
LEFT OUTER JOIN OBPBLK  A27 ON  MT.ID_OBJEKT=A27.ID_OBJEKT
LEFT OUTER JOIN CISKATUZ  A28 ON  MT.ID_UZEMI=A28.ID_UZEMI
LEFT OUTER JOIN PAROPAR  A30 ON  A7.ID_PAR=A30.ID_PAR
LEFT OUTER JOIN OBPVLAST  A31 ON  MT.ID_VLASTOBJ=A31.ID_VLASTNIK
LEFT OUTER JOIN OBPDUM  A35 ON  MT.ID_SEGMENT=A35.ID_SEGMENT
LEFT OUTER JOIN CISSTAPR  A36 ON  A14.ID_STAVPR=A36.ID_STAVPR
LEFT OUTER JOIN OBPVLAST  A37 ON  MT.ID_VLASTNIK=A37.ID_VLASTNIK
LEFT OUTER JOIN OBPKATUD  A38 ON  A37.ID_VLASTNIK=A38.ID_VLASTNIK
LEFT OUTER JOIN PAROSOBA  A39 ON  A7.ID_OSOB=A39.ID_OSOB
LEFT OUTER JOIN CLEINSREJ  A40 ON A7.ID_CLEINSREJ_IMP=A40.ID_CLEINSREJ
LEFT OUTER JOIN CISPOPPR  A41 ON  A14.ID_POPIPR=A41.ID_POPIPR
,NAJUDAJE A2
LEFT OUTER JOIN CNAJPEN  A10 ON  A2.ID_CNAJPEN=A10.ID_CNAJPEN
LEFT OUTER JOIN CNAJSTAV  A26 ON  A2.ID_CNAJSTAV=A26.ID_CNAJSTAV
LEFT OUTER JOIN CNAJVZTAH  A25 ON A2.ID_CNAJVZTAH=A25.ID_CNAJVZTAH
LEFT OUTER JOIN CNAJDUVOD  A34 ON A2.ID_CNAJDUVOD=A34.ID_CNAJDUVOD
LEFT OUTER JOIN CISUOPER  A42 ON  A2.ID_CISUOPER=A42.ID_CISUOPER
,NAJVZTAH A3
LEFT OUTER JOIN NAJPREDP  A4 ON  A3.ID_PREDPIS=A4.ID_PREDPIS
LEFT OUTER JOIN CISPREDVZT  A5 ON A3.ID_CISPREDVZT=A5.ID_CISPREDVZT
LEFT OUTER JOIN CODDNAJVZT  A9 ON A3.ID_CODDNAJVZT=A9.ID_CODDNAJVZT
LEFT OUTER JOIN NAJPREDP  A6 ON A4.ID_PREDPIS=A6.ID_PREDPIS_ZAHRNUJE
LEFT OUTER JOIN CISDPLAT  A13 ON  A4.ID_DPLA=A13.ID_DPLA
LEFT OUTER JOIN CISUJEDN  A11 ON  A3.ID_CISUJEDN=A11.ID_CISUJEDN
LEFT OUTER JOIN CISDOPLA  A12 ON  A4.ID_DOBAPLAT=A12.ID_DOBAPLAT
LEFT OUTER JOIN CISDOPLA  A29 ON  A6.ID_DOBAPLAT=A29.ID_DOBAPLAT
LEFT OUTER JOIN SSSLOGIN  A16 ON  A3.LIDENT=A16.ID_SSSLOGIN
LEFT OUTER JOIN SSSLOGIN  A17 ON  A3.LIDENT_ZMENA=A17.ID_SSSLOGIN
LEFT OUTER JOIN UCEVSTRDVZT  A18 ON A3.ID_NAJVZTAH=A18.ID_NAJVZTAH
LEFT OUTER JOIN CISUSTRD  A19 ON  A18.ID_CISUSTRD=A19.ID_CISUSTRD
LEFT OUTER JOIN CISMENA  A21 ON  A4.ID_MENA=A21.ID_MENA
LEFT OUTER JOIN CISMENA  A22 ON  A6.ID_MENA=A22.ID_MENA
LEFT OUTER JOIN CLEOSOBY  A23 ON  A11.ID_CCLE=A23.ID_CCLE
LEFT OUTER JOIN PAROPAR  A24 ON  A23.ID_PAR=A24.ID_PAR
LEFT OUTER JOIN NAJVSDRUVZT  A32 ON A3.ID_NAJVZTAH=A32.ID_NAJVZTAH
LEFT OUTER JOIN NAJSDRUZENI  A33 ON A32.ID_NAJSDRUZENI=A33.ID_NAJSDRUZENI
WHERE
MT.TYP = 'N'
AND MT.HLAVNI = 'H'
AND A1.ID_NAJUDAJE = A2.ID_NAJUDAJE
AND A2.ID_NAJVZTAH = A3.ID_NAJVZTAH;
</pre>
</pre>

**Comment by darold** [comment]
Not fixed yet I will look at it tomorrow.

**Comment by darold** [comment]
I think I've found the way to solve this issue. Commit d4a22f5 might do the right job for left outer join but I've not heavily tested right outer join translation. Let me know.

Regards,

**Comment by okbob** [comment]
Looks so some issue is there still

Original:
<pre>
FROM CLEVON MT , CLEOSOBY A1 , CISTON A2 ,
         NAJADRESA A3 , PARADR A4,CISOBCE A5 ,
         CISOKRES A6, CISKRAJ A7, CISZEME A8,
         CISCASTOB A9,
         SSSLOGIN A10, SSSLOGIN A11,
         SSSHLEDEJ_A A12, NAJVZTAH A13,
         NAJUDAJE A14, PARKOM A15,
         CISKKOM A16 ,
         ---CLEOSOBY A17,
         PAROSOBA A18
    WHERE MT.ID_CCLE = A1.ID_CCLE AND
          MT.ID_CISTON = A2.ID_CISTON AND
          A2.KOD_CISTON = 'KONTAKT' AND
          MT.ID_CLEVON = A3.ID_CLEVON(+) AND
          A3.ID_ADR = A4.ID_ADR(+) AND
          A4.ID_CISOBCE = A5.ID_CISOBCE(+) AND
          A4.ID_OKR=A6.ID_OKR(+) AND
          A4.ID_CISKRAJ=A7.ID_CISKRAJ(+) AND
          A4.ID_ZEME=A8.ID_ZEME(+) AND
          A4.ID_CISCASTOB = A9.ID_CISCASTOB(+) AND
          MT.LIDENT = A10.ID_SSSLOGIN(+) AND
          MT.LIDENT_ZMENA = A11.ID_SSSLOGIN(+) AND
          MT.ID_NAJVZTAH =A12.ID_NAJVZTAH(+)
          AND A12.TYP = 'N' AND A12.HLAVNI = 'H'
          AND MT.ID_NAJVZTAH = A13.ID_NAJVZTAH(+)
          AND MT.ID_NAJVZTAH =A14.ID_NAJVZTAH(+)
          AND A1.ID_KOM_IMP = A15.ID_KOM(+)
          AND A15.ID_KKOM=A16.ID_KKOM(+)
          ---AND A3.ID_CCLE_OSO=A17.ID_CCLE(+)
          AND A1.ID_OSOB=A18.ID_OSOB(+)
</pre>

Translation:
<pre>
     FROM ciskkom a16, ciston a2,          ---CLEOSOBY A17,
         parosoba a18, clevon mt
LEFT OUTER JOIN najadresa a3 ON (MT.ID_CLEVON = A3.ID_CLEVON)
LEFT OUTER JOIN paradr a4 ON (A3.ID_ADR = A4.ID_ADR)
LEFT OUTER JOIN cisobce a5 ON (A4.ID_CISOBCE = A5.ID_CISOBCE)
LEFT OUTER JOIN cisokres a6 ON (A4.ID_OKR = A6.ID_OKR)
LEFT OUTER JOIN ciskraj a7 ON (A4.ID_CISKRAJ = A7.ID_CISKRAJ)
LEFT OUTER JOIN ciszeme a8 ON (A4.ID_ZEME = A8.ID_ZEME)
LEFT OUTER JOIN ciscastob a9 ON (A4.ID_CISCASTOB = A9.ID_CISCASTOB)
LEFT OUTER JOIN ssslogin a10 ON (MT.LIDENT = A10.ID_SSSLOGIN)
LEFT OUTER JOIN ssslogin a11 ON (MT.LIDENT_ZMENA = A11.ID_SSSLOGIN)
LEFT OUTER JOIN ssshledej_a a12 ON (MT.ID_NAJVZTAH = A12.ID_NAJVZTAH)
LEFT OUTER JOIN najvztah a13 ON (MT.ID_NAJVZTAH = A13.ID_NAJVZTAH)
LEFT OUTER JOIN najudaje a14 ON (MT.ID_NAJVZTAH = A14.ID_NAJVZTAH)
, cleosoby a1
LEFT OUTER JOIN parkom a15 ON (A1.ID_KOM_IMP = A15.ID_KOM)
LEFT OUTER JOIN parosoba a18 ON (A1.ID_OSOB = A18.ID_OSOB)
WHERE MT.ID_CCLE = A1.ID_CCLE AND MT.ID_CISTON = A2.ID_CISTON AND A2.KOD_CISTON = 'KONTAKT'           AND A12.TYP = 'N' AND A12.HLAVNI = 'H'    AND  A15.ID_KKOM = A16.ID_KKOM
          ---AND A3.ID_CCLE_OSO=A17.ID_CCLE(+)
</pre>

Error
<pre>
ERROR: table name "a18" specified more than once
Stav SQL: 42712
</pre>
* a18 should be only once as LEFT OTER JOIN table
* for join a15-a16 should be used outer JOIN - instead inner join is used

**Comment by darold** [comment]
The problem comes from the comments inside the query, removing them reports the expected translation. I will look at translation code to see if I can preserve comments.

**Comment by darold** [comment]
Commit 7cc1fa6 must fix this last reported issue.

**Comment by okbob** [comment]
fixed, thank you
