### ISSUE TITLE
Is possible to disable some translations

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#289]
We use orafce and using these functions from extension does less problems than translated code

Current add_months translations fails when Oracle:date->PostgreSQL:date transformation.
<pre>
psql:yyy.sql:239: ERROR:  operator does not exist: integer + interval
ŘÁDKA 33:          ( A3.OBDOBI_DO-A2.DATUZA + '1 month'::interval) AS ...
                                            ^
</pre>

**Comment by darold** [comment]
Here the problem seems to come from the column not the translation. The add_month Oracle's function is declared to be used as follow:
```
ADD_MONTHS(date,integer)
```
So it looks like that Ora2Pg is doing the right translation here? A3.OBDOBI_DO-A2.DATUZ is an integer not a date and looking at the orafce add_month() function you will have the same issue.

**Comment by okbob** [comment]
The translated expression is `(OBDOBI_DO - DATUZA + '1 month'::interval) AS URDOB`. `OBDOBI_DO` is `date`, `DATUZA` is date. When I write this expression to psql
<pre>
ides_jmmaj=# select ('2017-01-01'::date - '2017-02-01'::date + '1month'::interval);
ERROR:  operator does not exist: integer + interval
LINE 2: select ('2017-01-01'::date - '2017-02-01'::date + '1month'::...
                                                        ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
</pre>
Minimally, there are missing necessary brackets
<pre>
ides_jmmaj=# select ('2017-01-01'::date - ('2017-02-01'::date + '1month'::interval));
┌──────────┐
│ ?column? │
╞══════════╡
│ -59 days │
└──────────┘
(1 řádka)
</pre>
The another question is a result type - expected is a number - not a interval 
So correct translation can be:
<pre>
select extract(epoch from ('2017-01-01'::date - ('2017-02-01'::date + '1month'::interval)))/86400;
</pre>
I understand so optimal solution can depend on context - so better is possible to disable this translation, and the user can do own implementation - a source code of add_month is trivial - and can be effective in SQL language.

**Comment by darold** [comment]
Ok, I've not seen the minus character but the result is the same, the add_month() function from orafce or Oracle still want a date as first argument so you will still have to rewrite the function call. In Oracle a date minus an other date returns an integer so maybe ora2pg have rewritten more code than expected. On Oracle:
```
SQL> select add_months(col2-col1, 6) from test_date;
select add_months(col2-col1, 6) from test_date
                      *
ERREUR a la ligne 1 :
ORA-00932: types de donnees incoherents ; attendu : DATE ; obtenu : DATE JULIAN
```
of course the error message does not reflect the real problem.

But if you tell me that you can use this code without rewriting it with the orafce function, ok I will add a configuration directive to disable the replacement of add_month() and add_year().

**Comment by okbob** [comment]
This case is working with Orafce without any touch.

**Comment by darold** [comment]
OK, commit 636fe72 adds DATE_FUNCTION_REWRITE configuration directive. By default Ora2pg rewrite add_months(), add_years() and trunc() functions set it to 0 to force Ora2Pg to not translate those functions if it breaks code. Just set 
```
DATE_FUNCTION_REWRITE     0
```
to disable this translation. I've tested it yet but the patch should work.

Yes, add_years() is not a build in Oracle function but it is sometime found in PL/SQL code as a "tool" function.

**Comment by okbob** [comment]
checked, thank you
