### ISSUE TITLE
Another issue of Oracle jouns to ANSI Joins

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#290]
There is really lot of combinations - but current result of Ora2pg is interesting:

Oracle
<pre>
CREATE OR REPLACE VIEW IDES_PRAHA22.V_SKUPPRVKU_BEZVYZ AS
SELECT A2.ID_NAZEVPR , 
         A6.ID_CISSKPRV,A6.KOD_SKUNPRV, A6.J1_NAZEV as SKUPINA,
         A2.J1_NAZEV AS NAZEV_PR , A2.KOD_NAZEVRP
    FROM CISNAZPR A2 ,   CVAZKPSKP A5 , CISSKPRV A6 
     WHERE A2.ID_NAZEVPR = A5.ID_NAZEVPR(+)
       AND(( A5.PLATNOST_OD <= sysdate 
       AND A5.PLATNOST_DO >= sysdate) 
        or a5.ID_NAZEVPR is null )
       AND A5.ID_CISSKPRV = A6.ID_CISSKPRV(+)
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE VIEW v_skupprvku_bezvyz (id_nazevpr, id_cisskprv, kod_skunprv, skupina, nazev_pr, kod_nazevrp) AS SELECT  A2.ID_NAZEVPR ,.
         A6.ID_CISSKPRV,A6.KOD_SKUNPRV, A6.J1_NAZEV as SKUPINA,
         A2.J1_NAZEV AS NAZEV_PR , A2.KOD_NAZEVRP
     FROM cisnazpr a2, cvazkpskp a5
LEFT OUTER JOIN cisskprv a6 ON (a5.id_cisskprv = a6.id_cisskprv)
WHERE a2.id_nazevpr = a5.id_nazevpr
       and(%subquery1%)  ;
</pre>

**Comment by darold** [comment]
Yes, my fault I've missed some obvious combination like upper/lower case or no space after AND/OR, commit  51ee9a4 might solves this issue.

**Comment by okbob** [comment]
fixed
