### ISSUE TITLE
problem with (+) => left outer join

### ISSUE THREAD

**Issue by Saberth** [darold/ora2pg#292]
I have oracle views with many (+) with this perspective:
selelect  from (select  from  where (+) , (+)) alias1, (select  from  where (+) , (+)) alias2 
    where  (+) and (+) and alias1 (+)

In this case I got wrong left outer joins ....

**Comment by darold** [comment]
Are you using latest development code or the current 18.0 release? It might have been fixed if not please post the original Oracle query.

**Comment by Saberth** [comment]
Using the latest development , I get (%subquery%) in the from clause and I don't find the code of this subquery.

Thank you

**Comment by darold** [comment]
please post the full SQL code of the original query, if you need privacy send it to my private email < gilles AT darold DOT net >

**Comment by Saberth** [comment]
check your private email.
Thank you in advance

**Comment by darold** [comment]
Thanks for the query and the report, last commit a98a238 might solves this issue.

**Comment by Saberth** [comment]
Thank you! nice improvement
but I got duplicated "subqueries" in the from clause. I sent u the result in private.

**Comment by darold** [comment]
Please give a try to latest development code, commit 9bca9c3 might solves this new issue.

**Comment by Saberth** [comment]
Thanks again.
The subquery code must be in the left outer join itself and not in the begining of the from.

it must be like that: 

 from table1 left outer join ( select .........'subquery code'...) subquery1.

**Comment by darold** [comment]
Sorry for the misunderstanding, commit e1846a9 might fix this issue.

**Comment by Saberth** [comment]
well done bro!!
thank you 

Don't forget to add an alias for any from clause in the subqueries even if it is not called.


Concerning ( SYS_CONNECT_BY_PATH ....START WITH ...CONNECT BY PRIOR ...) .
Will it be treated for a new commit later or the next version ?

Thank you again for the effort you are making.

**Comment by darold** [comment]
Concerning CONNECT BY rewriting I've not  started to look on it and I don't know when I will be able to work on it.

**Comment by darold** [comment]
Last commits add CONNECT BY translation as well as related SYS_CONNECT_BY_PATH and LEVEL code.
