### ISSUE TITLE
ERROR when ORACLE_COPIES >1 during export 'INSERT"

### ISSUE THREAD

**Issue by Saberth** [darold/ora2pg#293]
When I want to export the data using the "INSERT" and setting the ORACLE_COPIES to 2 or 3 ...
I got this error: 

 Serial number: 215 (DBD ERROR: OCIStmtExecute/Describe) [for Statement "SELECT A.COLUMN_NAME, A.NULLABLE, A.DATA_DEFAULT, A.TABLE_NAME,...) FROM DBA_TAB_COLUMNS A, ALL_OBJECTS O WHERE A.OWNER=O.OWNER and A.TABLE_NAME=O.OBJECT_NAME and O.OBJECT_TYPE='TABLE' AND A.TABLE_NAME='AD_HP_CMN_O' AND A.OWNER='MYOWNER' ORDER BY A.COLUMN_ID
"] at /usr/lib/perl5/site_perl/5.8.8/Ora2Pg.pm line 7494.

Any idea about that ?

**Comment by darold** [comment]
Do you have the same issue with the COPY mode?

**Comment by darold** [comment]
I've tested it on a very small database and I'm not able to reproduce the issue with both export INSERT/COPY.

**Comment by Saberth** [comment]
Yes I got the same problem with "COPY"

**Comment by darold** [comment]
What is your OS and the version of DBI and DBD::Oracle perl modules?

**Comment by Saberth** [comment]
Linux CentOS 6 , DBD::Oracle version 1.75_2.

I got another error using COPY  and specifing the PG_DSN => "Can't locate object method "pg_putcopydata" via package "DBI::db" at /usr/lib/perl5/site_perl/5.8.8/Ora2Pg.pm line 11405.
Issuing rollback() for database handle being DESTROY'd without explicit disconnect()"


using INSERT and specifing PG_DSN => "FATAL: ERROR:  insert or update on table "table" violates foreign key constraint "fk_ad_hp_avl_o_id""

Thank you for your help

**Comment by Saberth** [comment]
I got the same errors after installing DBI version 1.636

**Comment by darold** [comment]
You need a modern Perl distribution, Perl 5.10 at least, and a more recent version of DBI (> 1.614) and DBD::Pg.

**Comment by Saberth** [comment]
Ok Thank you
