### ISSUE TITLE
some comments inside FROM clause breaks translation to ANSI outer joins

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#294]
Oracle:
<pre>
    FROM CLEVON MT , CLEOSOBY A1 , CISTON A2 ,
         NAJADRESA A3 , PARADR A4,CISOBCE A5 ,
         CISOKRES A6, CISKRAJ A7, CISZEME A8,
         CISCASTOB A9,
         SSSLOGIN A10, SSSLOGIN A11,
         SSSHLEDEJ_A A12, NAJVZTAH A13,
         NAJUDAJE A14, PARKOM A15,
         CISKKOM A16 ,
         ---CLEOSOBY A17,
         PAROSOBA A18
    WHERE MT.ID_CCLE = A1.ID_CCLE AND
          MT.ID_CISTON = A2.ID_CISTON AND
          A2.KOD_CISTON = 'KONTAKT' AND
          MT.ID_CLEVON = A3.ID_CLEVON(+) AND
          A3.ID_ADR = A4.ID_ADR(+) AND
          A4.ID_CISOBCE = A5.ID_CISOBCE(+) AND
          A4.ID_OKR=A6.ID_OKR(+) AND
          A4.ID_CISKRAJ=A7.ID_CISKRAJ(+) AND
          A4.ID_ZEME=A8.ID_ZEME(+) AND
          A4.ID_CISCASTOB = A9.ID_CISCASTOB(+) AND
          MT.LIDENT = A10.ID_SSSLOGIN(+) AND
          MT.LIDENT_ZMENA = A11.ID_SSSLOGIN(+) AND
          MT.ID_NAJVZTAH =A12.ID_NAJVZTAH(+)
          AND A12.TYP = 'N' AND A12.HLAVNI = 'H'
          AND MT.ID_NAJVZTAH = A13.ID_NAJVZTAH(+)
          AND MT.ID_NAJVZTAH =A14.ID_NAJVZTAH(+)
          AND A1.ID_KOM_IMP = A15.ID_KOM(+)
          AND A15.ID_KKOM=A16.ID_KKOM(+)
          ---AND A3.ID_CCLE_OSO=A17.ID_CCLE(+)
          AND A1.ID_OSOB=A18.ID_OSOB(+)
</pre>

Ora2pg result:
<pre>
      FROM ciskkom a16, ---cleosoby a17, ciston a2, clevon mt
LEFT OUTER JOIN najadresa a3 ON (MT.ID_CLEVON = A3.ID_CLEVON)
LEFT OUTER JOIN paradr a4 ON (A3.ID_ADR = A4.ID_ADR)
LEFT OUTER JOIN cisobce a5 ON (A4.ID_CISOBCE = A5.ID_CISOBCE)
LEFT OUTER JOIN cisokres a6 ON (A4.ID_OKR = A6.ID_OKR)
LEFT OUTER JOIN ciskraj a7 ON (A4.ID_CISKRAJ = A7.ID_CISKRAJ)
LEFT OUTER JOIN ciszeme a8 ON (A4.ID_ZEME = A8.ID_ZEME)
LEFT OUTER JOIN ciscastob a9 ON (A4.ID_CISCASTOB = A9.ID_CISCASTOB)
LEFT OUTER JOIN ssslogin a10 ON (MT.LIDENT = A10.ID_SSSLOGIN)
LEFT OUTER JOIN ssslogin a11 ON (MT.LIDENT_ZMENA = A11.ID_SSSLOGIN)
LEFT OUTER JOIN ssshledej_a a12 ON (MT.ID_NAJVZTAH = A12.ID_NAJVZTAH)
LEFT OUTER JOIN najvztah a13 ON (MT.ID_NAJVZTAH = A13.ID_NAJVZTAH)
LEFT OUTER JOIN najudaje a14 ON (MT.ID_NAJVZTAH = A14.ID_NAJVZTAH)
,cleosoby a1
LEFT OUTER JOIN parkom a15 ON (A1.ID_KOM_IMP = A15.ID_KOM)
LEFT OUTER JOIN ---cleosoby a17 ON (A3.ID_CCLE_OSO = A17.ID_CCLE)
LEFT OUTER JOIN parosoba a18 ON (A1.ID_OSOB = A18.ID_OSOB)
WHERE MT.ID_CCLE = A1.ID_CCLE AND MT.ID_CISTON = A2.ID_CISTON AND A2.KOD_CISTON = 'KONTAKT'
     AND A12.TYP = 'N' AND A12.HLAVNI = 'H'    AND  A15.ID_KKOM = A16.ID_KKOM
</pre>

**Comment by darold** [comment]
Might be fixed with last commits. This will break the output format with appending additional new line characters in the from clause but this will be fixed when the code beautifier will be included.

**Comment by okbob** [comment]
It is not correct still

Ora2pg result
<pre>
LEFT OUTER JOIN ssslogin a11 ON (MT.LIDENT_ZMENA = A11.ID_SSSLOGIN)
LEFT OUTER JOIN ssshledej_a a12 ON (MT.ID_NAJVZTAH = A12.ID_NAJVZTAH)
LEFT OUTER JOIN najvztah a13 ON (MT.ID_NAJVZTAH = A13.ID_NAJVZTAH)
LEFT OUTER JOIN najudaje a14 ON (MT.ID_NAJVZTAH = A14.ID_NAJVZTAH)
,cleosoby a1
LEFT OUTER JOIN parkom a15 ON (A1.ID_KOM_IMP = A15.ID_KOM)
LEFT OUTER JOIN ---cleosoby a17 ON (A3.ID_CCLE_OSO = A17.ID_CCLE)
LEFT OUTER JOIN parosoba a18 ON (A1.ID_OSOB = A18.ID_OSOB)
</pre>

The keywords `LEFT OUTER JOIN` should be commented too.

**Comment by darold** [comment]
Commit 6b1851c is a rewriting for better support of comment in the from clauses with outer join.
Thanks.

**Comment by okbob** [comment]
fixed, thank you

**Comment by amoltarte** [comment]
/******************************** Actual Oracle View.... **************************************************/

CREATE OR REPLACE FORCE VIEW MEP.V_SCHEDULEM
(
   FORMATTED_CURRENT_MONTH,
   FORMATTED_PRECEDING_MONTH,
   FORMATTED_CORRESPONDING_MONTH,
   CURRENTMONTH,
   CURRENTYEAR,
   CORRESPONDING_PREVIOUS_MONTH,
   PRECEDING_MONTH,
   SUBCLASS_CODE,
   SUBCLASS_NAME,
   PAYMENTMODE_CODE,
   PAYMENTMODE_NAME,
   CURRENT_MONTH,
   MOP_CODE_TO_DISPLAY,
   SUBPAYMENTMODE_CODE,
   SUBPAYMENTMODE_NAME,
   SUBCLASS_RATE,
   CURRENT_MONTH_TRAFFICCOUNT,
   CURRENT_MONTH_COLLECTION,
   PRECEDING_MONTH_TRAFFICCOUNT,
   PRECEDING_MONTH_COLLECTION,
   CORRESPONDING_TRAFFICCOUNT,
   CORRESPONDING_COLLECTION,
   CURRENTWEIGHT_AMOUNT,
   CORRESPONDWEIGHT_AMOUNT,
   PRECEDINGWEIGHT_AMOUNT
)
AS
     SELECT TO_CHAR (TO_DATE (Current_Month, 'MMYYYY'), 'MON YYYY')
               AS Formatted_Current_Month,
            TO_CHAR (TO_DATE (Preceding_Month, 'MMYYYY'), 'MON YYYY')
               AS Formatted_Preceding_Month,
            TO_CHAR (TO_DATE (Corresponding_Previous_Month, 'MMYYYY'),
                     'MON YYYY')
               AS Formatted_Corresponding_Month,
            TO_CHAR (TO_DATE (Current_Month, 'MMYYYY'), 'MM') AS CurrentMonth,
            TO_CHAR (TO_DATE (Current_Month, 'MMYYYY'), 'YYYY') AS CurrentYear,
            Corresponding_Previous_Month,
            Preceding_Month,
            VCD.Subclass_Code,
            SubClass_Name,
            PM.PaymentMode_Code,
            PaymentMode_Name,
            Current_Month,
            MOP_Code_To_Display,
            NVL (R.SubPaymentMode_Code, 0) AS SubPaymentMode_Code,
            PMD.SubPaymentMode_Name,
            DECODE (PM.Issue_Type,
                    0, F_GetFareAmount (PM.PaymentMode_Code,
                                        VCD.SubClass_Code,
                                        TO_DATE (Current_Month, 'MMYYYY'),
                                        R.SubPaymentMode_Code),
                    0)
               AS SubClass_Rate,
            SUM (NVL (Current_Month_TrafficCount, 0))
               AS Current_Month_TrafficCount,
            SUM (NVL (Current_Month_Collection, 0)) AS Current_Month_Collection,
            SUM (NVL (Preceding_Month_TrafficCount, 0))
               AS Preceding_Month_TrafficCount,
            SUM (NVL (Preceding_Month_Collection, 0))
               AS Preceding_Month_Collection,
            SUM (NVL (Corresponding_TrafficCount, 0))
               AS Corresponding_TrafficCount,
            SUM (NVL (Corresponding_Collection, 0)) AS Corresponding_Collection,
            SUM (NVL (CurrentWeight_Amount, 0)) AS CurrentWeight_Amount,
            SUM (NVL (CorrespondWeight_Amount, 0)) AS CorrespondWeight_Amount,
            SUM (NVL (PrecedingWeight_Amount, 0)) AS PrecedingWeight_Amount
       FROM Rpt_ScheduleM R,
            Tbl_VehicleClass_Detail VCD,
            Tbl_PaymentMode PM,
            Tbl_PaymentMode_Detail PMD
      WHERE     R.Subclass_Code = VCD.Subclass_Code
            AND R.PaymentMode_Code = PM.PaymentMode_Code
            AND R.SubPaymentMode_code = PMD.SubPaymentMode_code(+)
   GROUP BY PMD.SubPaymentMode_Name,
            TO_CHAR (TO_DATE (Current_Month, 'MMYYYY'), 'MON YYYY'),
            TO_CHAR (TO_DATE (Preceding_Month, 'MMYYYY'), 'MON YYYY'),
            TO_CHAR (TO_DATE (Corresponding_Previous_Month, 'MMYYYY'),
                     'MON YYYY'),
            TO_CHAR (TO_DATE (Current_Month, 'MMYYYY'), 'MM'),
            TO_CHAR (TO_DATE (Current_Month, 'MMYYYY'), 'YYYY'),
            Corresponding_Previous_Month,
            Preceding_Month,
            VCD.SubClass_Code,
            SubClass_Name,
            PM.PaymentMode_Code,
            PMD.SubPaymentmode_Name,
            PaymentMode_Name,
            Current_Month,
            MOP_Code_To_Display,
            NVL (R.SubPaymentMode_Code, 0),
            DECODE (PM.Issue_Type,
                    0, F_GetFareAmount (PM.PaymentMode_Code,
                                        VCD.SubClass_Code,
                                        TO_DATE (Current_Month, 'MMYYYY'),
                                        R.SubPaymentMode_Code),
                    0);


DROP SYNONYM TMS.V_SCHEDULEM;

CREATE OR REPLACE SYNONYM TMS.V_SCHEDULEM FOR MEP.V_SCHEDULEM;


GRANT SELECT ON MEP.V_SCHEDULEM TO TMS;

/******************** Ora2PG Created View***************************************/
CREATE OR REPLACE VIEW v_schedulem (formatted_current_month, formatted_current_month, formatted_current_month, formatted_current_month, formatted_current_month, formatted_current_month, formatted_current_month, formatted_current_month, formatted_current_month, formatted_current_month, formatted_current_month, formatted_current_month, formatted_preceding_month, formatted_preceding_month, formatted_preceding_month, formatted_preceding_month, formatted_preceding_month, formatted_preceding_month, formatted_preceding_month, formatted_preceding_month, formatted_preceding_month, formatted_preceding_month, formatted_preceding_month, formatted_preceding_month, formatted_corresponding_month, formatted_corresponding_month, formatted_corresponding_month, formatted_corresponding_month, formatted_corresponding_month, formatted_corresponding_month, formatted_corresponding_month, formatted_corresponding_month, formatted_corresponding_month, formatted_corresponding_month, formatted_corresponding_month, formatted_corresponding_month, currentmonth, currentmonth, currentmonth, currentmonth, currentmonth, currentmonth, currentmonth, currentmonth, currentmonth, currentmonth, currentmonth, currentmonth, currentyear, currentyear, currentyear, currentyear, currentyear, currentyear, currentyear, currentyear, currentyear, currentyear, currentyear, currentyear, corresponding_previous_month, corresponding_previous_month, corresponding_previous_month, subclass_code, corresponding_previous_month, corresponding_previous_month, corresponding_previous_month, corresponding_previous_month, corresponding_previous_month, corresponding_previous_month, corresponding_previous_month, corresponding_previous_month, preceding_month, preceding_month, preceding_month, subclass_name, preceding_month, preceding_month, preceding_month, preceding_month, preceding_month, preceding_month, preceding_month, preceding_month, subclass_code, subclass_code, subclass_code, paymentmode_code, subclass_code, subclass_code, subclass_code, subclass_code, subclass_code, subclass_code, subclass_code, subclass_code, subclass_name, subclass_name, subclass_name, paymentmode_name, subclass_name, subclass_name, subclass_name, subclass_name, subclass_name, subclass_name, subclass_name, subclass_name, paymentmode_code, paymentmode_code, paymentmode_code, current_month, paymentmode_code, paymentmode_code, paymentmode_code, paymentmode_code, paymentmode_code, paymentmode_code, paymentmode_code, paymentmode_code, paymentmode_name, paymentmode_name, paymentmode_name, current_month_trafficcount, paymentmode_name, paymentmode_name, paymentmode_name, paymentmode_name, paymentmode_name, paymentmode_name, paymentmode_name, paymentmode_name, current_month, current_month, current_month, current_month_collection, current_month, current_month, current_month, current_month, current_month, current_month, current_month, current_month, mop_code_to_display, mop_code_to_display, mop_code_to_display, preceding_month, mop_code_to_display, mop_code_to_display, mop_code_to_display, mop_code_to_display, mop_code_to_display, mop_code_to_display, mop_code_to_display, mop_code_to_display, subpaymentmode_code, subpaymentmode_code, subpaymentmode_code, preceding_month_trafficcount, subpaymentmode_code, subpaymentmode_code, subpaymentmode_code, subpaymentmode_code, subpaymentmode_code, subpaymentmode_code, subpaymentmode_code, subpaymentmode_code, subpaymentmode_name, subpaymentmode_name, subpaymentmode_name, preceding_month_collection, subpaymentmode_name, subpaymentmode_name, subpaymentmode_name, subpaymentmode_name, subpaymentmode_name, subpaymentmode_name, subpaymentmode_name, subpaymentmode_name, subclass_rate, subclass_rate, subclass_rate, corresponding_previous_month, subclass_rate, subclass_rate, subclass_rate, subclass_rate, subclass_rate, subclass_rate, subclass_rate, subclass_rate, current_month_trafficcount, current_month_trafficcount, current_month_trafficcount, corresponding_trafficcount, current_month_trafficcount, current_month_trafficcount, current_month_trafficcount, current_month_trafficcount, current_month_trafficcount, current_month_trafficcount, current_month_trafficcount, current_month_trafficcount, current_month_collection, current_month_collection, current_month_collection, corresponding_collection, current_month_collection, current_month_collection, current_month_collection, current_month_collection, current_month_collection, current_month_collection, current_month_collection, current_month_collection, preceding_month_trafficcount, preceding_month_trafficcount, preceding_month_trafficcount, mop_code_to_display, preceding_month_trafficcount, preceding_month_trafficcount, preceding_month_trafficcount, preceding_month_trafficcount, preceding_month_trafficcount, preceding_month_trafficcount, preceding_month_trafficcount, preceding_month_trafficcount, preceding_month_collection, preceding_month_collection, preceding_month_collection, subclass_rate, preceding_month_collection, preceding_month_collection, preceding_month_collection, preceding_month_collection, preceding_month_collection, preceding_month_collection, preceding_month_collection, preceding_month_collection, corresponding_trafficcount, corresponding_trafficcount, corresponding_trafficcount, corresponding_trafficcount, corresponding_trafficcount, corresponding_trafficcount, corresponding_trafficcount, corresponding_trafficcount, corresponding_trafficcount, corresponding_trafficcount, corresponding_trafficcount, corresponding_collection, corresponding_collection, corresponding_collection, corresponding_collection, corresponding_collection, corresponding_collection, corresponding_collection, corresponding_collection, corresponding_collection, corresponding_collection, corresponding_collection, currentweight_amount, currentweight_amount, currentweight_amount, currentweight_amount, currentweight_amount, currentweight_amount, currentweight_amount, currentweight_amount, currentweight_amount, currentweight_amount, currentweight_amount, correspondweight_amount, correspondweight_amount, correspondweight_amount, correspondweight_amount, correspondweight_amount, correspondweight_amount, correspondweight_amount, correspondweight_amount, correspondweight_amount, correspondweight_amount, correspondweight_amount, precedingweight_amount, precedingweight_amount, precedingweight_amount, precedingweight_amount, precedingweight_amount, precedingweight_amount, precedingweight_amount, precedingweight_amount, precedingweight_amount, precedingweight_amount, precedingweight_amount) AS SELECT 
	    TO_CHAR(TO_DATE(Current_Month,'MMYYYY'),'MON YYYY') AS Formatted_Current_Month
	,	TO_CHAR(TO_DATE(Preceding_Month,'MMYYYY'),'MON YYYY') AS Formatted_Preceding_Month
	,	TO_CHAR(TO_DATE(Corresponding_Previous_Month,'MMYYYY'),'MON YYYY') AS Formatted_Corresponding_Month
	,	TO_CHAR(TO_DATE(Current_Month,'MMYYYY'),'MM')  AS CurrentMonth
	,	TO_CHAR(TO_DATE(Current_Month,'MMYYYY'),'YYYY')  AS CurrentYear
	,	Corresponding_Previous_Month
	,	Preceding_Month
	,	VCD.Subclass_Code
	,	SubClass_Name
	,	PM.PaymentMode_Code
	,	PaymentMode_Name
	,	Current_Month
	,   MOP_Code_To_Display
	,	coalesce(R.SubPaymentMode_Code,0) AS SubPaymentMode_Code
	,	PMD.SubPaymentMode_Name
	,	CASE WHEN PM.Issue_Type=0 THEN F_GetFareAmount(PM.PaymentMode_Code,VCD.SubClass_Code,TO_DATE(Current_Month,'MMYYYY'),R.SubPaymentMode_Code)  ELSE 0 END SubClass_Rate
	,	SUM(coalesce(Current_Month_TrafficCount,0)) AS Current_Month_TrafficCount
	,	SUM(coalesce(Current_Month_Collection,0)) AS Current_Month_Collection
	,	SUM(coalesce(Preceding_Month_TrafficCount,0)) AS Preceding_Month_TrafficCount
	,	SUM(coalesce(Preceding_Month_Collection,0)) AS Preceding_Month_Collection
	,	SUM(coalesce(Corresponding_TrafficCount,0)) AS  Corresponding_TrafficCount
	,	SUM(coalesce(Corresponding_Collection,0)) AS	Corresponding_Collection
	,	SUM(coalesce(CurrentWeight_Amount,0)) AS CurrentWeight_Amount
	,	SUM(coalesce(CorrespondWeight_Amount,0)) AS CorrespondWeight_Amount
	,	SUM(coalesce(PrecedingWeight_Amount,0)) AS PrecedingWeight_Amount
	 FROM tbl_paymentmode pm, tbl_vehicleclass_detail vcd, rpt_schedulem r
LEFT OUTER JOIN tbl_paymentmode_detail pmd ON (R.SubPaymentMode_code = PMD.SubPaymentMode_code)
WHERE R.Subclass_Code = VCD.Subclass_Code AND R.PaymentMode_Code = PM.PaymentMode_Code  GROUP BY
	    PMD.SubPaymentMode_Name
    ,	TO_CHAR(TO_DATE(Current_Month,'MMYYYY'),'MON YYYY')
	,	TO_CHAR(TO_DATE(Preceding_Month,'MMYYYY'),'MON YYYY')
	,	TO_CHAR(TO_DATE(Corresponding_Previous_Month,'MMYYYY'),'MON YYYY')
	,	TO_CHAR(TO_DATE(Current_Month,'MMYYYY'),'MM')
	,	TO_CHAR(TO_DATE(Current_Month,'MMYYYY'),'YYYY')
	,	Corresponding_Previous_Month
	,	Preceding_Month
	,	VCD.SubClass_Code
	,	SubClass_Name
	,	PM.PaymentMode_Code
	,	PMD.SubPaymentmode_Name
	,	PaymentMode_Name
	,	Current_Month
	,   MOP_Code_To_Display
	,	coalesce(R.SubPaymentMode_Code,0)
	,	CASE WHEN PM.Issue_Type=0 THEN F_GetFareAmount(PM.PaymentMode_Code,VCD.SubClass_Code,TO_DATE(Current_Month,'MMYYYY'),R.SubPaymentMode_Code)  ELSE 0 END;
/***********************************************************************************************************/

Repeated almost all columns badly...

**Comment by darold** [comment]
Please do not use other closed and unrelated issue, to report your own open a new issue, this is already hard enough to follow.

To solve your issue, use latest development code from github, this was fixed.
