### ISSUE TITLE
SDO_GEOMETRIES are not converted in functions

### ISSUE THREAD

**Issue by Saberth** [darold/ora2pg#295]
I use SDO of oracle in a procedures and functions , they are not well exported:
Example Oracle : 

CREATE OR REPLACE FUNCTION "F1" () return SDO_GEOMETRY is

CURSOR .....;
geom SDO_GEOMETRY;

Begin
  l_elem := MDSYS.SDO_ELEM_INFO_ARRAY();
  l_ord := MDSYS.SDO_ORDINATE_ARRAY();
  l_elem.EXTEND(3);
geom := sdo_geometry (
      2006, -- multiline
      4326, -- SDO_SRID
      null, -- SDO_POINT
      l_elem,
      l_ord);
END;

in Posgres nothing has been converted:
CREATE OR REPLACE FUNCTION "F1" () RETURNS geomtry AS $body$
DECLARE
Cursor ......;
geom SDO_GEOMETRY;

Begin
l_elem := SDO_ELEM_INFO_ARRAY();
  l_ord := SDO_ORDINATE_ARRAY();
  l_elem.EXTEND(3);
geom := sdo_geometry(
      2006, -- multiline
      4326, -- SDO_SRID
      null, -- SDO_POINT
      l_elem,
      l_ord);
End;
$body$
LANGUAGE PLPGSQL
 STABLE;

Any idea ?

**Comment by darold** [comment]
I have fixed the translation of the SDO_GEOMETRY type in the declare section but the call to other SDO_* functions will not be replaced automatically by Ora2Pg. Unfortunately I don't know of to do that,  you have to rewrite it manually. Please send me privately the original and rewritten code once it is done, I will check if things can be done automatically.
