### ISSUE TITLE
DBD::Pg::db pg_putcopyend failed: ERROR:  unrecognized configuration parameter "xxxxx"

### ISSUE THREAD

**Issue by sxullf** [darold/ora2pg#296]
The above error occurred due to a trigger that is testing for a session parameter. I can do something like
the following: "set session "xxxxx" = 'yyy';" when I run ora2pg in two steps (i.e. export and import). I have
not found a way to do this (i.e. set up a session parameter) when I run ora2pg direct from source DB to target DB in one step. Is this possible? Thanks.

**Comment by darold** [comment]
Why not setting the session parameter at user connection level? Just use something like that in the PostgreSQL destination database supposing that user1 is the user used to import data:

    ALTER ROLE user1 SET session_param = 'value';

and reset the setting after data import:

    ALTER ROLE user1 RESET session_param;

**Comment by sxullf** [comment]
Thanks for the quick response! 

Please note my parameter is a custom one and when I tried to run
  ALTER ROLE user1 SET custom.para = 'value';
I got: ERROR:  permission denied to set parameter "custom.para".

[Note I was able to set the session parameter via
          set session "custom.para" = 'value';
 when I run the export and import separately]

Even if ALTER ROLE set worked, how will this setting affect the ora2pg session I will start?

Thanks!

**Comment by sxullf** [comment]
I found a solution:

$ export PGOPTIONS="-c custom.para=value"
$ ora2pg ...

Thanks for your help!

**Comment by darold** [comment]
Yes this can works too but I don't know what you are trying to do by setting a custom variable for ora2pg, 
are you calling some triggers that use this variable?

> Even if ALTER ROLE set worked, how will this setting affect the ora2pg session I will start?

If you set a default setting to a specific user with ALTER ROLE, when the user connect to the database the settings it automatically set for this user in his current session. You can do the same thing for a database and any user who connect to the database using ALTER DATABASE instead.

Regards,

**Comment by sxullf** [comment]
Many of my Oracle tables have fairly complex default clauses which I manually created triggers for in PostgresSQL. Part of the conditions inside the triggers depends on the session variable setting. 
Thanks again.

**Comment by darold** [comment]
Ok and if I understand well the default values change following the connected user, otherwise you can set the default value of the custom variable in the postgresql.conf file. Thanks for the precision.
