### ISSUE TITLE
$$ symbols in conf file are converted to PID during installation

### ISSUE THREAD

**Issue by kuzmaka** [darold/ora2pg#298]
Hi,
It's rather minor issue in config file comments. I noticed following in ora2pg.conf.dist after installation:
```
# CREATE FUNCTION tsv_t_document_title() RETURNS trigger AS 9061
# BEGIN
#        IF TG_OP = 'INSERT' OR new.title != old.title THEN
#                new.tsv_title :=
#                to_tsvector('french', coalesce(new.title,''));
#        END IF;
#        return new;
# END
# 9061 LANGUAGE plpgsql;
```
Pay attention to those 90961 numbers around function body instead of $$. The same in two other places in config file. It looks like bash makes substitution.
Thanks!

**Comment by darold** [comment]
Thanks for the report, commit 8f2901d solves this issue.

**Comment by kuzmaka** [comment]
Hi Darold,
I noticed similar issue in configuration file comments with `\,` (backslash and comma) where backslash disappears after installation:
* `#MODIFY_TYPE     TABLE1:COL3:varchar,TABLE1:COL4:decimal(9\,6)`
* `# 	DATA_TYPE	NUMBER(*\,0):bigint`

Thanks for the great work!

**Comment by darold** [comment]
Thanks again for the report, commit 0573bd1 fixes this issue.
