### ISSUE TITLE
Empty output.sql is created when copying data directly to postgresql

### ISSUE THREAD

**Issue by kuzmaka** [darold/ora2pg#299]
Hi,
I call ora2pg with configured postgresql connection and with `-t COPY` key. It successfully copies data from oracle to postgresql but nevertheless creates an empty output.sql file in current directory. It is somewhat unexpected and inconvenient when directory permissions are restricted.
Thanks!

**Comment by darold** [comment]
With commit 7d9d4f8 the file might never been created again with direct data export. Thanks for the report.
