### ISSUE TITLE
PostgreSQL requires alias for subquery in FROM

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#300]
Translated view:
<pre>
select Id_objekt, kod_objekt,
         ( SELECT COUNT(*)
            FROM SSSHLEDEJ_A B1
            WHERE B1.ID_OBJEKT = MT.ID_OBJEKT
            AND B1.TYP = 'V' AND HLAVNI='O' ) AS poc_s,
         ( SELECT COUNT(*)
            FROM obpvvlalok B2
            WHERE B2.ID_OBJEKT = MT.ID_OBJEKT
            ) AS poc_v
         from obpblk mt where id_objekt is not null
             )  where poc_s<>poc_v;
</pre>
The alias after subquery is necessary
<pre>
select Id_objekt, kod_objekt,
         ( SELECT COUNT(*)
            FROM SSSHLEDEJ_A B1
            WHERE B1.ID_OBJEKT = MT.ID_OBJEKT
            AND B1.TYP = 'V' AND HLAVNI='O' ) AS poc_s,
         ( SELECT COUNT(*)
            FROM obpvvlalok B2
            WHERE B2.ID_OBJEKT = MT.ID_OBJEKT
            ) AS poc_v
         from obpblk mt where id_objekt is not null
             )  ___xxx where poc_s<>poc_v;
</pre>

**Comment by darold** [comment]
Commit 7422537 adds an automatic alias name to subqueries in the FROM clause that do not have one. The alias is named `aliasN` where N is the indice of the subquery in the main query.

**Comment by darold** [comment]
This patch add aliases to using() in join clause, I will fix that.

**Comment by darold** [comment]
Fixed with commit 14a449e

**Comment by okbob** [comment]
I found still some cases where alias was not used
Oracle
<pre>
SELECT ID_CVTYPSKUPR AS ID_ROW , ID_CVTYPSKUPR ,MT.ID_KOLURC ,MT.ID_TYPPRS,
       ( SELECT B1.J1_NAZEV
	    FROM CISKOLUR B1
	    WHERE B1.ID_KOLURC = MT.ID_KOLURC ) AS NAZEV_KOLURC ,
	    TO_DATE('01.01.1980','DD.MM.YYYY' ) AS PLATNOST_OD ,
	    TO_DATE('01.01.4000','DD.MM.YYYY' ) AS PLATNOST_DO	,
	    A1.J1_NAZEV AS TYPPR
 FROM cvtypskupr MT , CISTYPPR A1
   WHERE MT.ID_TYPPRS  = A1.ID_TYPPRS AND
    MT.ID_TYPPRS IS NOT NULL AND ID_KOLURC IN
 (   SELECT ID_KOLURC  FROM (
     select ID_KOLURC ,COUNT(*) AS POCET
      from cvtypskupr
      WHERE ID_TYPPRS IS NOT NULL
	AND PLATNOST_DO = '01.01.4000'
	GROUP BY ID_KOLURC)
       WHERE POCET > 1 )
</pre>

Translated:
<pre>
CREATE OR REPLACE VIEW v_kolur_dupl (id_row, id_cvtypskupr, id_kolurc, id_typprs, nazev_kolurc, platnost_od, platnost_
       ( SELECT B1.J1_NAZEV
             FROM CISKOLUR B1.
            WHERE B1.ID_KOLURC = MT.ID_KOLURC ) AS NAZEV_KOLURC ,
            to_date('01.01.1980','DD.MM.YYYY') AS PLATNOST_OD ,
            to_date('01.01.4000','DD.MM.YYYY') AS PLATNOST_DO  ,
            A1.J1_NAZEV AS TYPPR.
 FROM cvtypskupr MT , CISTYPPR A1.
   WHERE MT.ID_TYPPRS  = A1.ID_TYPPRS AND.
    MT.ID_TYPPRS IS NOT NULL AND ID_KOLURC IN (   SELECT ID_KOLURC  FROM (
     select ID_KOLURC ,COUNT(*) AS POCET
      from cvtypskupr
      WHERE ID_TYPPRS IS NOT NULL
        AND PLATNOST_DO = '01.01.4000'
        GROUP BY ID_KOLURC) --- <<<< missing alias
       WHERE POCET > 1 );
</pre>

**Comment by darold** [comment]
Commit dcac710 might fix this issue, some sub-queries was not translated.

**Comment by okbob** [comment]
one case was fixed, second not
Original:
<pre>
select "ID_RGRID","ID_UPAPOHYB","ID_CISUJEDN","ID_UCEOBDOBI","ID_CISUSTRD","ID_U
DRCISRAD",
	  "ID_CISUUCET","ID_UPAPUCET","UCEKOD","UCEDOK","UCEMES","UCEPOL","DTDPH
","ANAJMENO",
	  "ABYT_NEBYT","ACISPOP","AULICE","ACISORI","EPOL_CASTKA","VARS","POZNAM
KA","NAZEV_CISUJEDN",
	  "NAZEV_UCEOBDOBI","STREDISKO","UCET","UCET_PAP","UZ_UCR","ORG_UCR","ST
RANA",
	  "ID_SKUP_CISEL","ID_APROVOZNA","ID_ASPRAVCE","PLATNOST_OD","PLATNOST_D
O",
	  DECODE (STRANA,'D',-1*EPOL_CASTKA, EPOL_CASTKA)AS "HOD"
from
(
select 0 AS ID_RGRID, MT.ID_UPAPOHYB,
A1.ID_CISUJEDN, A1.ID_UCEOBDOBI ,
A1.ID_CISUSTRD, A1.ID_UDRCISRAD,
A1.ID_CISUUCET_MD AS ID_CISUUCET,
MT.ID_UPAPUCET_M AS ID_UPAPUCET,
trim(A1.UCEKOD) AS UCEKOD , A1.UCEDOK,
A1.UCEMES, A1.UCEPOL,
A1.DTDPH,
A1.ANAJMENO,A1.ABYT_NEBYT,
A1.ACISPOP,A1.AULICE,A1.ACISORI,
A1.EPOL_CASTKA, A1.VARS,
A1.POZNAMKA,
A2.J1_NAZEV AS NAZEV_CISUJEDN,
A4.J1_NAZEV AS NAZEV_UCEOBDOBI,
A3.J1_NAZEV AS STREDISKO,
trim(A5.KOD_CISUCET) AS UCET,
trim(A6.KOD_UPAPUCET) AS UCET_PAP,
MT.UZ_UCR_M as UZ_UCR,
MT.ORG_UCR_M as ORG_UCR,
'M' AS STRANA,
A6.ID_SKUP_CISEL, MT.ID_APROVOZNA, MT.ID_ASPRAVCE,
MT.PLATNOST_OD, MT.PLATNOST_DO,
0 AS HOD
from upapohyb MT,
  ucepohyb A1, cisujedn A2,
  CISUSTRD A3, uceobdobi A4,
  CISUUCET A5, UPAPUCET A6
where MT.ID_UCEPOHYB= A1.ID_UCEPOHYB(+)
  And A1.ID_CISUJEDN=A2.ID_CISUJEDN(+)
  and A1.ID_CISUJEDN =A2.ID_CISUJEDN(+)
  and A1.ID_CISUSTRD =A3.ID_CISUSTRD(+)
  and A1.ID_UCEOBDOBI=A4.ID_UCEOBDOBI(+)
  and A1.ID_CISUUCET_MD = A5.ID_CISUUCET(+)
  and MT.ID_UPAPUCET_M	= A6.ID_UPAPUCET(+)
 union all
select 0 AS ID_RGRID, MT.ID_UPAPOHYB,
A1.ID_CISUJEDN, A1.ID_UCEOBDOBI ,
A1.ID_CISUSTRD, A1.ID_UDRCISRAD,
A1.ID_CISUUCET_D AS ID_CISUUCET,
MT.ID_UPAPUCET_D AS ID_UPAPUCET,
trim(A1.UCEKOD) AS UCEDOK, A1.UCEDOK,
A1.UCEMES, A1.UCEPOL,
A1.DTDPH,
A1.ANAJMENO,A1.ABYT_NEBYT,
A1.ACISPOP,A1.AULICE,A1.ACISORI,
A1.EPOL_CASTKA, A1.VARS,
A1.POZNAMKA,
A2.J1_NAZEV AS NAZEV_CISUJEDN,
A4.J1_NAZEV AS NAZEV_UCEOBDOBI,
A3.J1_NAZEV AS STREDISKO,
trim(A5.KOD_CISUCET) AS UCET,
trim(A6.KOD_UPAPUCET) AS UCET_PAP,
MT.UZ_UCR_D as UZ_UCR,
MT.ORG_UCR_D as ORG_UCR,
'D' AS STRANA,
A6.ID_SKUP_CISEL, MT.ID_APROVOZNA, MT.ID_ASPRAVCE,
MT.PLATNOST_OD, MT.PLATNOST_DO,
0 AS HOD
from upapohyb MT,
  ucepohyb A1, cisujedn A2,
  CISUSTRD A3, uceobdobi A4,
  CISUUCET A5, UPAPUCET A6
where MT.ID_UCEPOHYB= A1.ID_UCEPOHYB(+)
  And A1.ID_CISUJEDN=A2.ID_CISUJEDN(+)
  and A1.ID_CISUJEDN =A2.ID_CISUJEDN(+)
  and A1.ID_CISUSTRD =A3.ID_CISUSTRD(+)
  and A1.ID_UCEOBDOBI=A4.ID_UCEOBDOBI(+)
  and A1.ID_CISUUCET_D = A5.ID_CISUUCET(+)
  and MT.ID_UPAPUCET_D	= A6.ID_UPAPUCET(+)
) order by id_cisujedn,id_uceobdobi,ucekod,ucedok,ucepol
</pre>


Translated:
<pre>
SELECT  "id_rgrid","id_upapohyb","id_cisujedn","id_uceobdobi","id_cisustrd","id_udrcisrad",
          "id_cisuucet","id_upapucet","ucekod","ucedok","ucemes","ucepol","dtdph","anajmeno",
          "abyt_nebyt","acispop","aulice","acisori","epol_castka","vars","poznamka","nazev_cisujedn",
          "nazev_uceobdobi","stredisko","ucet","ucet_pap","uz_ucr","org_ucr","strana",
          "id_skup_cisel","id_aprovozna","id_aspravce","platnost_od","platnost_do",
          CASE WHEN STRANA='D' THEN -1*EPOL_CASTKA  ELSE EPOL_CASTKA END "hod"
 FROM (
select 0 AS ID_RGRID, MT.ID_UPAPOHYB,
A1.ID_CISUJEDN, A1.ID_UCEOBDOBI ,
A1.ID_CISUSTRD, A1.ID_UDRCISRAD,
A1.ID_CISUUCET_MD AS ID_CISUUCET,
MT.ID_UPAPUCET_M AS ID_UPAPUCET,
btrim(A1.UCEKOD) AS UCEKOD , A1.UCEDOK,
A1.UCEMES, A1.UCEPOL,
A1.DTDPH,
A1.ANAJMENO,A1.ABYT_NEBYT,
A1.ACISPOP,A1.AULICE,A1.ACISORI,
A1.EPOL_CASTKA, A1.VARS,
A1.POZNAMKA,
A2.J1_NAZEV AS NAZEV_CISUJEDN,
A4.J1_NAZEV AS NAZEV_UCEOBDOBI,
A3.J1_NAZEV AS STREDISKO,
btrim(A5.KOD_CISUCET) AS UCET,
btrim(A6.KOD_UPAPUCET) AS UCET_PAP,
MT.UZ_UCR_M as UZ_UCR,
MT.ORG_UCR_M as ORG_UCR,
'M' AS STRANA,
A6.ID_SKUP_CISEL, MT.ID_APROVOZNA, MT.ID_ASPRAVCE,
MT.PLATNOST_OD, MT.PLATNOST_DO,
0 AS HOD
FROM upapohyb mt
LEFT OUTER JOIN ucepohyb a1 ON (MT.ID_UCEPOHYB = A1.ID_UCEPOHYB)
LEFT OUTER JOIN cisujedn a2 ON (A1.ID_CISUJEDN = A2.ID_CISUJEDN AND A1.ID_CISUJEDN = A2.ID_CISUJEDN)
LEFT OUTER JOIN cisustrd a3 ON (A1.ID_CISUSTRD = A3.ID_CISUSTRD)
LEFT OUTER JOIN uceobdobi a4 ON (A1.ID_UCEOBDOBI = A4.ID_UCEOBDOBI)
LEFT OUTER JOIN cisuucet a5 ON (A1.ID_CISUUCET_MD = A5.ID_CISUUCET)
LEFT OUTER JOIN upapucet a6 ON (MT.ID_UPAPUCET_M = A6.ID_UPAPUCET)
union all

select 0 AS ID_RGRID, MT.ID_UPAPOHYB,
A1.ID_CISUJEDN, A1.ID_UCEOBDOBI ,
A1.ID_CISUSTRD, A1.ID_UDRCISRAD,
A1.ID_CISUUCET_D AS ID_CISUUCET,
MT.ID_UPAPUCET_D AS ID_UPAPUCET,
btrim(A1.UCEKOD) AS UCEDOK, A1.UCEDOK,
A1.UCEMES, A1.UCEPOL,
A1.DTDPH,
A1.ANAJMENO,A1.ABYT_NEBYT,
A1.ACISPOP,A1.AULICE,A1.ACISORI,
A1.EPOL_CASTKA, A1.VARS,
A1.POZNAMKA,
A2.J1_NAZEV AS NAZEV_CISUJEDN,
A4.J1_NAZEV AS NAZEV_UCEOBDOBI,
A3.J1_NAZEV AS STREDISKO,
btrim(A5.KOD_CISUCET) AS UCET,
btrim(A6.KOD_UPAPUCET) AS UCET_PAP,
MT.UZ_UCR_D as UZ_UCR,
MT.ORG_UCR_D as ORG_UCR,
'D' AS STRANA,
A6.ID_SKUP_CISEL, MT.ID_APROVOZNA, MT.ID_ASPRAVCE,
MT.PLATNOST_OD, MT.PLATNOST_DO,
0 AS HOD
FROM upapucet a6, upapohyb mt
LEFT OUTER JOIN ucepohyb a1 ON (MT.ID_UCEPOHYB = A1.ID_UCEPOHYB)
LEFT OUTER JOIN cisujedn a2 ON (A1.ID_CISUJEDN = A2.ID_CISUJEDN AND A1.ID_CISUJEDN = A2.ID_CISUJEDN)
LEFT OUTER JOIN cisustrd a3 ON (A1.ID_CISUSTRD = A3.ID_CISUSTRD)
LEFT OUTER JOIN uceobdobi a4 ON (A1.ID_UCEOBDOBI = A4.ID_UCEOBDOBI)
LEFT OUTER JOIN cisuucet a5 ON (A1.ID_CISUUCET_D = A5.ID_CISUUCET)
WHERE MT.ID_UPAPUCET_D = A6.ID_UPAPUCET
)  order by id_cisujedn,id_uceobdobi,ucekod,ucedok,ucepol;
</pre>

**Comment by darold** [comment]
Last commit 0b14fba might fix it.

**Comment by okbob** [comment]
fixed in my tests

**Comment by darold** [comment]
Good news.
