### ISSUE TITLE
The nested decode replacement produce invalid CASE expression

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#301]
Original:
<pre>
DECODE(A8.ID_NAJZALOBCE,'', DECODE(A6.ID_NAJZALOBCE,'',MT.ID_NAJZALOBCE,A6.ID_NAJZALOBCE), A8.ID_NAJZALOBCE) AS ID_NAJZALOBCE
</pre>

Translation:
<pre>
CASE WHEN A8.ID_NAJZALOBCE='' THEN CASE WHEN A6.ID_NAJZALOBCE='' THEN MT.ID_NAJZALOBCE  ELSE A6.ID_NAJZALOBCE END A8.ID_NAJZALOBCE END ID_NAJZALOBCE</pre>

Result:
<pre>
psql:views-20170217.sql:8013: ERROR:  syntax error at or near "A8"
ŘÁDKA 2: ... THEN MT.ID_NAJZALOBCE  ELSE A6.ID_NAJZALOBCE END A8.ID_NAJZ...
                                                              ^
</pre>

**Comment by darold** [comment]
Commit aee49ed used recursive call to decode replacement function for better used but the bug that was replacing  END followed by ELSE keyword with just END is fixed too, it was used in the PL/SQL code rewriter.

**Comment by okbob** [comment]
fixed
