### ISSUE TITLE
Translation of Oracle outer join to ANSI SQL fails

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#302]
almost all cases works perfect, but I found one:

Oracle:
<pre>
select	MT.ID_SSS_VSESP_MO, A2.J1_NAZEV as NAZEV_SSSSEGM
, MT.ID_SEGM, A2.KOD_SEGM, A2.ZAKLAD
, MT.ID_SPRAVCE, A6.ID_ASPRAVCE, MT.PLATNOST_OD
, MT.PLATNOST_DO, MT.POZNAMKA, MT.IDENT
, MT.CVZNIKRADK, MT.BLOKOVANO, A7.ID_APROVOZNA
, DECODE(A3.ID_SSSLOGIN,NULL,MT.IDENT,A3.JMENO ) as LIDENT_JMENO
, MT.LIDENT
, TO_CHAR(MT.DATZMENY,'HH24:MI:SS') as CAS_DATZMENY
, TO_CHAR(MT.DATVYR,'HH24:MI:SS') as CAS_DATVYR
, MT.DATZMENY, MT.DATVYR
, A4.JMENO as LIDENT_ZMENA_JMENO
, MT.LIDENT_ZMENA
, A5.J1_NAZEV as NAZEV_CSKUPINA, A7.ID_SKUP_CISEL
, MT.SYS_VER, A6.NAZEV, A2.KOD_SKUPINA
, A2.NAZEV_SKUPINA, A2.PORADI_SKUPINA
, A2.PORADI_MODUL, A2.ODEBER
 from SSS_VSESP_MO MT
, SSSSEGM_SSSUZI A1
, SSSSEGM A2, SSSLOGIN A3
, SSSLOGIN A4, CSKUPINA A5
, UDRSPRVC A6, UDRPROVO A7
 where MT.ID_SEGM= A1.ID_SEGM(+)
 AND MT.ID_SEGM= A2.ID_SEGM(+)
 AND MT.LIDENT= A3.ID_SSSLOGIN(+)
 AND MT.LIDENT_ZMENA= A4.ID_SSSLOGIN(+)
 AND A7.ID_SKUP_CISEL= A5.ID_SKUP_CISEL(+)
 AND MT.ID_ASPRAVCE =  A6.ID_ASPRAVCE(+)
 AND A6.ID_ASPRAVCE =  A7.ID_ASPRAVCE(+)
</pre>

Ora2pg
<pre>
CREATE OR REPLACE VIEW v_sss_vsesp_mo_skup_cisel (id_sss_vsesp_mo, nazev_ssssegm, id_segm, kod_segm, zaklad, id_spravc
, MT.ID_SEGM, A2.KOD_SEGM, A2.ZAKLAD
, MT.ID_SPRAVCE, A6.ID_ASPRAVCE, MT.PLATNOST_OD
, MT.PLATNOST_DO, MT.POZNAMKA, MT.IDENT
, MT.CVZNIKRADK, MT.BLOKOVANO, A7.ID_APROVOZNA
, CASE WHEN A3.ID_SSSLOGIN IS NULL THEN MT.IDENT  ELSE A3.JMENO  END LIDENT_JMENO
, MT.LIDENT
, TO_CHAR(MT.DATZMENY,'HH24:MI:SS') as CAS_DATZMENY
, TO_CHAR(MT.DATVYR,'HH24:MI:SS') as CAS_DATVYR
, MT.DATZMENY, MT.DATVYR
, A4.JMENO as LIDENT_ZMENA_JMENO
, MT.LIDENT_ZMENA
, A5.J1_NAZEV as NAZEV_CSKUPINA, A7.ID_SKUP_CISEL
, MT.SYS_VER, A6.NAZEV, A2.KOD_SKUPINA
, A2.NAZEV_SKUPINA, A2.PORADI_SKUPINA
, A2.PORADI_MODUL, A2.ODEBER
  FROM sss_vsesp_mo mt
LEFT OUTER JOIN ssssegm_sssuzi a1 ON (MT.ID_SEGM = A1.ID_SEGM)
LEFT OUTER JOIN ssssegm a2 ON (MT.ID_SEGM = A2.ID_SEGM)
LEFT OUTER JOIN ssslogin a3 ON (MT.LIDENT = A3.ID_SSSLOGIN)
LEFT OUTER JOIN ssslogin a4 ON (MT.LIDENT_ZMENA = A4.ID_SSSLOGIN)
LEFT OUTER JOIN cskupina a5 ON (A7.ID_SKUP_CISEL = A5.ID_SKUP_CISEL)
LEFT OUTER JOIN udrsprvc a6 ON (MT.ID_ASPRAVCE = A6.ID_ASPRAVCE)
LEFT OUTER JOIN udrprovo a7 ON (A6.ID_ASPRAVCE = A7.ID_ASPRAVCE)
, udrprovo a7; --- <<<< ???
</pre>

or another case:
Oracle:
<pre>
SELECT *
  FROM NAJVPLAPRE MT ,
    NAJPLATBY A3,
    CISDPLAT A4 ,
    CISTYPPLAT A5 ,
    CISMENA A6 ,
    NAJPREDP A7,
    CISDRPRE A8 ,
    CTYPPRED A9 ,
    NAJDATSPLT A10 ,
    SSSHLEDEJ_A A11,
    CISDRUPLAT A12,
    NAJPOKPLA A13,
    CISUJEDN A14 ,
    NAJVZTAH A15,
    OBPPRSTR A16,
    CISKOLUR A17,
    SSSLOGIN A18,
    SSSLOGIN A19,
    NAJUDAJE A20,
    CNAJPEN A21,
    CISUSTRD A22,
    CLEOSOBY A23,
    PAROPAR A24,
    CISPREDVZT A25, CISKATUZ A26,
    CISUOPER A27, NAJVPLAUCE A28,
    UCEUZA A29
  WHERE MT.ID_NAJPLATBY = A3.ID_NAJPLATBY
  AND A3.ID_DPLA	= A4.ID_DPLA(+)
  AND A3.ID_CISTYPPLAT	= A5.ID_CISTYPPLAT(+)
  AND A3.ID_CISDRUPLAT	= A12.ID_CISDRUPLAT(+)
  AND A3.ID_MENA	= A6.ID_MENA(+)
  AND MT.ID_PREDPIS	= A7.ID_PREDPIS(+)
  AND A10.ID_DRUPRE	= A8.ID_DRUPRE(+)
  AND A7.ID_CTYPPRED	= A9.ID_CTYPPRED(+)
  AND MT.ID_NAJDATSPLT	= A10.ID_NAJDATSPLT(+)
  AND MT.ID_NAJPROS	= A11.ID_NAJPROS(+)
  AND A3.ID_NAJVZTAH	= A15.ID_NAJVZTAH(+)
  AND A15.ID_CISUJEDN	= A14.ID_CISUJEDN(+)
  AND MT.ID_NAJPOKPLA	= A13.ID_NAJPOKPLA(+)
  AND A11.ID_PROSTOR	= A16.ID_PROSTOR(+)
  AND A16.ID_KOLURC	= A17.ID_KOLURC(+)
  AND MT.LIDENT 	= A18.ID_SSSLOGIN(+)
  AND MT.LIDENT_ZMENA	= A19.ID_SSSLOGIN(+)
  AND A10.ID_NAJUDAJE	= A20.ID_NAJUDAJE(+)
  AND A20.ID_CNAJPEN	= A21.ID_CNAJPEN(+)
  AND A20.ID_CISUSTRD	= A22.ID_CISUSTRD(+)
  AND MT.ID_CCLE	= A23.ID_CCLE(+)
  AND A23.ID_PAR	= A24.ID_PAR(+)
  AND A15.ID_CISPREDVZT = A25.ID_CISPREDVZT(+)
  AND A11.ID_UZEMI	= A26.ID_UZEMI(+)
  AND A10.ID_CISUOPER	= A27.ID_CISUOPER(+)
  AND MT.ID_NAJVPLAPRE	= A28.ID_NAJVPLAPRE(+)
  AND A28.ID_UCEUZA	= A29.ID_UCEUZA(+)
</pre>

Ora2pg:
<pre>
SELECT *
  FROM najvplapre mt
LEFT OUTER JOIN najpredp a7 ON (MT.ID_PREDPIS = A7.ID_PREDPIS)
LEFT OUTER JOIN cisdrpre a8 ON (A10.ID_DRUPRE = A8.ID_DRUPRE) --<< too early reference to a10
LEFT OUTER JOIN ctyppred a9 ON (A7.ID_CTYPPRED = A9.ID_CTYPPRED)
LEFT OUTER JOIN najdatsplt a10 ON (MT.ID_NAJDATSPLT = A10.ID_NAJDATSPLT)
LEFT OUTER JOIN ssshledej_a a11 ON (MT.ID_NAJPROS = A11.ID_NAJPROS)
LEFT OUTER JOIN najpokpla a13 ON (MT.ID_NAJPOKPLA = A13.ID_NAJPOKPLA)
LEFT OUTER JOIN obpprstr a16 ON (A11.ID_PROSTOR = A16.ID_PROSTOR)
LEFT OUTER JOIN ciskolur a17 ON (A16.ID_KOLURC = A17.ID_KOLURC)
LEFT OUTER JOIN ssslogin a18 ON (MT.LIDENT = A18.ID_SSSLOGIN)
LEFT OUTER JOIN ssslogin a19 ON (MT.LIDENT_ZMENA = A19.ID_SSSLOGIN)
LEFT OUTER JOIN najudaje a20 ON (A10.ID_NAJUDAJE = A20.ID_NAJUDAJE)
LEFT OUTER JOIN cnajpen a21 ON (A20.ID_CNAJPEN = A21.ID_CNAJPEN)
LEFT OUTER JOIN cisustrd a22 ON (A20.ID_CISUSTRD = A22.ID_CISUSTRD)
LEFT OUTER JOIN cleosoby a23 ON (MT.ID_CCLE = A23.ID_CCLE)
LEFT OUTER JOIN paropar a24 ON (A23.ID_PAR = A24.ID_PAR)
LEFT OUTER JOIN ciskatuz a26 ON (A11.ID_UZEMI = A26.ID_UZEMI)
LEFT OUTER JOIN cisuoper a27 ON (A10.ID_CISUOPER = A27.ID_CISUOPER)
LEFT OUTER JOIN najvplauce a28 ON (MT.ID_NAJVPLAPRE = A28.ID_NAJVPLAPRE)
LEFT OUTER JOIN uceuza a29 ON (A28.ID_UCEUZA = A29.ID_UCEUZA)
, najplatby a3
LEFT OUTER JOIN cisdplat a4 ON (A3.ID_DPLA = A4.ID_DPLA)
LEFT OUTER JOIN cistypplat a5 ON (A3.ID_CISTYPPLAT = A5.ID_CISTYPPLAT)
LEFT OUTER JOIN cisdruplat a12 ON (A3.ID_CISDRUPLAT = A12.ID_CISDRUPLAT)
LEFT OUTER JOIN cismena a6 ON (A3.ID_MENA = A6.ID_MENA)
LEFT OUTER JOIN najvztah a15 ON (A3.ID_NAJVZTAH = A15.ID_NAJVZTAH)
LEFT OUTER JOIN cisujedn a14 ON (A15.ID_CISUJEDN = A14.ID_CISUJEDN)
LEFT OUTER JOIN cispredvzt a25 ON (A15.ID_CISPREDVZT = A25.ID_CISPREDVZT)
, najdatsplt a10 -- <<< second def of a10
WHERE MT.ID_NAJPLATBY = A3.ID_NAJPLATBY;
</pre>

**Comment by darold** [comment]
Commit 736a2a3 takes care of the outer join order.

**Comment by okbob** [comment]
looks fixed
