### ISSUE TITLE
lost left parenthesis in query

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#303]
Oracle:
<pre>
select ( SELECT COUNT(*)
	   FROM NAJADRESA B1
	   WHERE MT.ID_ADR = B1.ID_ADR ) AS POC_KONTAKT ,
( SELECT COUNT(*)
	   FROM OBPVOMAD B2
	   WHERE MT.ID_ADR = B2.ID_ADR ) AS POC_FM,
( SELECT COUNT(*)
	   FROM OBPVBADR B3
	   WHERE MT.ID_ADR = B3.ID_ADR ) AS POC_BUD,
( SELECT COUNT(*)
	   FROM NAJVOSADR B4
	   WHERE MT.ID_ADR = B4.ID_ADR ) AS POC_OSO,
( SELECT COUNT(*)
	   FROM UDRVPRAD B5
	   WHERE MT.ID_ADR = B5.ID_ADR ) AS POC_PROVO
 from paradr mt
</pre>

Translated query:
<pre>
CREATE OR REPLACE VIEW v_poc_adresa (poc_kontakt, poc_fm, poc_bud, poc_oso, poc_provo) AS
 SELECT SELECT COUNT(*)    ----- <<<< SELECT SELECT
            FROM NAJADRESA B1
           WHERE MT.ID_ADR = B1.ID_ADR ) AS POC_KONTAKT ,
( SELECT COUNT(*)
           FROM OBPVOMAD B2
           WHERE MT.ID_ADR = B2.ID_ADR ) AS POC_FM,
( SELECT COUNT(*)
           FROM OBPVBADR B3
           WHERE MT.ID_ADR = B3.ID_ADR ) AS POC_BUD,
( SELECT COUNT(*)
           FROM NAJVOSADR B4
           WHERE MT.ID_ADR = B4.ID_ADR ) AS POC_OSO,
( SELECT COUNT(*)
           FROM UDRVPRAD B5
           WHERE MT.ID_ADR = B5.ID_ADR ) AS POC_PROVO
 from paradr mt;
</pre>

**Comment by darold** [comment]
Current code do not reproduce this issue but I have added this query to my regression test.

**Comment by okbob** [comment]
Maybe similar issue:

Oracle:
<pre>
CREATE OR REPLACE VIEW IDES_PRAHA22.V_SUMPLOCHPRSTROLD AS
select MT.ID_SEGMENT , MT.ATYP_PROSTORU , MT.ABYT_NEBYT ,
       SUM(( SELECT  A1.PLOCHA  FROM OBPPLOCH A1 , CISTYPPL A2
              WHERE MT.ID_PROSTOR = A1.ID_PROSTOR
                    AND A1.ID_TYP_PLOCHY = A2.ID_TYP_PLOCHY 
                    AND A2.KOD_TYP_PLOCHY = 'PLOUZ' )) AS PLOUZ,
       SUM(( SELECT  A1.PLOCHA  FROM OBPPLOCH A1 , CISTYPPL A2
              WHERE MT.ID_PROSTOR = A1.ID_PROSTOR
                    AND A1.ID_TYP_PLOCHY = A2.ID_TYP_PLOCHY 
                    AND A2.KOD_TYP_PLOCHY = 'PLOUZUPR' )) AS PLOUZUPR,
       SUM(( SELECT  A1.PLOCHA  FROM OBPPLOCH A1 , CISTYPPL A2
              WHERE MT.ID_PROSTOR = A1.ID_PROSTOR
                    AND A1.ID_TYP_PLOCHY = A2.ID_TYP_PLOCHY 
                    AND A2.KOD_TYP_PLOCHY = 'PLOBYT' )) AS PLOPRE,
       SUM(( SELECT  A1.PLOCHA  FROM OBPPLOCH A1 , CISTYPPL A2
              WHERE MT.ID_PROSTOR = A1.ID_PROSTOR
                    AND A1.ID_TYP_PLOCHY = A2.ID_TYP_PLOCHY 
                    AND A2.KOD_TYP_PLOCHY = 'PLOANUITA' )) AS PLOANUITA
  from SSSHLEDEJ_A MT  
  WHERE  TYP = 'P'
    GROUP BY  MT.ID_SEGMENT , MT.ATYP_PROSTORU , MT.ABYT_NEBYT
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE VIEW v_sumplochprstrold (id_segment, atyp_prostoru, abyt_nebyt, plouz, plouzupr, plopre, ploanuita) AS SELECT  MT.ID_SEGMENT , MT.ATYP_PROSTORU , MT.ABYT_NEBYT ,
       SUM( SELECT  A1.PLOCHA   FROM OBPPLOCH A1 , CISTYPPL A2
              WHERE MT.ID_PROSTOR = A1.ID_PROSTOR
                    AND A1.ID_TYP_PLOCHY = A2.ID_TYP_PLOCHY
                    AND A2.KOD_TYP_PLOCHY = 'PLOUZ' ) AS PLOUZ,
       SUM( SELECT  A1.PLOCHA  FROM OBPPLOCH A1 , CISTYPPL A2
              WHERE MT.ID_PROSTOR = A1.ID_PROSTOR
                    AND A1.ID_TYP_PLOCHY = A2.ID_TYP_PLOCHY 
                    AND A2.KOD_TYP_PLOCHY = 'PLOUZUPR' ) AS PLOUZUPR,
       SUM( SELECT  A1.PLOCHA  FROM OBPPLOCH A1 , CISTYPPL A2
              WHERE MT.ID_PROSTOR = A1.ID_PROSTOR
                    AND A1.ID_TYP_PLOCHY = A2.ID_TYP_PLOCHY 
                    AND A2.KOD_TYP_PLOCHY = 'PLOBYT' ) AS PLOPRE,
       SUM( SELECT  A1.PLOCHA  FROM OBPPLOCH A1 , CISTYPPL A2
              WHERE MT.ID_PROSTOR = A1.ID_PROSTOR
                    AND A1.ID_TYP_PLOCHY = A2.ID_TYP_PLOCHY 
                    AND A2.KOD_TYP_PLOCHY = 'PLOANUITA' ) AS PLOANUITA
  from SSSHLEDEJ_A MT  
  WHERE  TYP = 'P'
    GROUP BY  MT.ID_SEGMENT , MT.ATYP_PROSTORU , MT.ABYT_NEBYT;
</pre>

**Comment by darold** [comment]
Ok, double parenthesis might not be removed, this is what commit aecaf28 might fix.

**Comment by okbob** [comment]
looks fixed
