### ISSUE TITLE
ROWNUM to LIMIT breaks subselects

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#304]
Oracle subselect
<pre>
INS_RIZ,EXEKUCE,
(  SELECT COUNT(*)  FROM NAJVNESTROZ B1
     WHERE B1.ID_NAJVPLAPRE = MT.ID_NAJVPLAPRE
        AND ROWNUM < 2 ) AS POCET_NE_STORNO,
A16.KOD_PROSTOR_KU
</pre>

Ora2pg 
<pre>
EXEKUCE,
(  SELECT COUNT(*) AS -- AS keyword should not be here
     FROM NAJVNESTROZ B1
     WHERE B1.ID_NAJVPLAPRE = MT.ID_NAJVPLAPRE   LIMIT 1) AS POCET_NE_STORNO,
A16.KOD_PROSTOR_KU
</pre>

**Comment by darold** [comment]
Can you post the entire Oracle code, using the following I'm not able to reproduce the issue:
```
SELECT INS_RIZ,EXEKUCE,
(  SELECT COUNT(*)  FROM NAJVNESTROZ B1
     WHERE B1.ID_NAJVPLAPRE = MT.ID_NAJVPLAPRE
        AND ROWNUM < 2 ) AS POCET_NE_STORNO,
A16.KOD_PROSTOR_KU
FROM MYTABLE A16;
```

**Comment by okbob** [comment]
<pre>
CREATE OR REPLACE VIEW IDES_PRAHA22.V_NAJPLATBY AS
SELECT MT.ID_NAJVPLAPRE,
    MT.ID_NAJVZTAH ,
    MT.ID_ASPRAVCE ,
    MT.ID_NAJDATSPLT,
    MT.AKOD_BUDOVY ,
    MT.AKOD_PROSTOR ,
    MT.AULICE ,
    MT.ACISORI ,
    MT.ACISPOP ,
    MT.ID_PREDPIS,
    MT.ID_NAJPLATBY ,
    A3.ID_CODDNAJVZT ,
    A3.ID_CISTYPPLAT ,
    A3.ID_MENA ,
    A3.ID_DPLA ,
    A3.OBDOBI_OD ,
    A3.OBDOBI_DO ,
    MT.DAT_URCENI,
    MT.DAT_STORNA,
    A3.NEURCENO ,
    A3.ENEURCENO,
    MT.DATUM_ZAPLACENI ,
    A3.DATUM_BANKVYPIS ,
    MT.UCE_DOKLAD ,
    MT.CASTKACELKEM ,
    MT.VARS ,
    A3.SPECS ,
    A3.ZIV_EVIDENCE,
    A3.DAVKA,
    A3.DATUM_DAVKY ,
    A3.PLATNOST_OD,
    A3.PLATNOST_DO ,
    A3.POZNAMKA ,
    A3.CVZNIKRADK ,
    MT.ROZ_CASTKA,
    A4.J1_NAZEV  AS DPLAT ,
    A5.J1_NAZEV  AS TYPPLAT ,
    A12.J1_NAZEV AS J1_NAZEV_CISDRUPLAT,
    A6.J1_NAZEV  AS MENA ,
    A3.DEFARAJ ,
    MT.ID_CCLE ,
    MT.ID_VLASTNIK ,
    MT.ID_VLASTOBJ ,
    MT.ZIV_EVIDENCE AS ZIV_NAJVPLAPRE ,
    MT.OBDOBI_OD    AS OBOD_PLAPRE ,
    MT.OBDOBI_DO    AS OBDO_PLAPRE,
    A8.J1_NAZEV     AS DRUPRE,
    A8.KOD_DRUPRE,
    A10.ID_DRUPRE,
    A3.ROK  AS ROK_ZAPL,
    A10.ROK AS ROK_OBDOBI,
    MT.ID_APROVOZNA ,
    MT.NAZSPRAVCE ,
    MT.NAZPROVOZNA ,
    MT.NAJMENO,
    MT.ANAJMENO,
    MT.ULICE,
    MT.ABYT_NEBYT,
    MT.ZIV_POM,
    (SELECT COUNT(*)
    FROM NAJVPLAPRE B1
    WHERE B1.ID_NAJPLATBY   = MT.ID_NAJPLATBY
    AND B1.DAT_STORNA      IS NULL
    AND b1.ZIV_EVIDENCE    <> '5'
    AND B1.ID_NAJVPLAPRE_A IS NULL
    ) AS PLT_OBDOBI_POC,
    A10.PREDEPSANO ,
    A10.UZAVERKA ,
    A9.J1_NAZEV AS CTYPPRED ,
    A10.DATUM_SPLATNOSTI,
    A10.ROK,
    A10.MESIC,
    A10.ZA_OBDOBI                      AS OBDOBI_ZA1,
    ( FUPRAV_ZA_OBDOBI(A10.ZA_OBDOBI)) AS ZA_OBDOBI,
    A10.PLATNOST_DO                    AS PLATNOST_DO_SPLT ,
    A3.DEFARAJ_STR ,
    A13.KOD_NAJPOKPLA,
    A13.NAZEV AS NAZEV_NAJPOKPLA,
    (SELECT DECODE(SUM(C1.EPOL_CASTKA) , NULL , 0 , SUM(C1.EPOL_CASTKA))
    FROM NAJPLAPOL C1 ,
      CISPOLPRE C2
    WHERE C1.ID_POLONAJ  = C2.ID_POLONAJ
    AND C2.DEFVYNOS      = 'V'
    AND C1.ID_NAJVPLAPRE = MT.ID_NAJVPLAPRE
    ) AS EVYNOS,
    (SELECT DECODE(SUM(C1.EPOL_CASTKA) , NULL , 0 , SUM(C1.EPOL_CASTKA))
    FROM NAJPLAPOL C1 ,
      CISPOLPRE C2
    WHERE C1.ID_POLONAJ  = C2.ID_POLONAJ
    AND C2.DEFVYNOS      = 'S'
    AND C1.ID_NAJVPLAPRE = MT.ID_NAJVPLAPRE
    ) AS ESLUZBY,
    (SELECT DECODE(SUM(C1.EPOL_CASTKA) , NULL , 0 , SUM(C1.EPOL_CASTKA))
    FROM NAJPLAPOL C1 ,
      CISPOLPRE C2
    WHERE C1.ID_POLONAJ  = C2.ID_POLONAJ
    AND C2.DEFVYNOS      = 'Z'
    AND C1.ID_NAJVPLAPRE = MT.ID_NAJVPLAPRE
    ) AS EZALOHA,
    (SELECT DECODE(SUM(C1.EPOL_CASTKA) , NULL , 0 , SUM(C1.EPOL_CASTKA))
    FROM NAJPLAPOL C1 ,
      CISPOLPRE C2
    WHERE C1.ID_POLONAJ  = C2.ID_POLONAJ
    AND C2.DEFVYNOS      = 'A'
    AND C1.ID_NAJVPLAPRE = MT.ID_NAJVPLAPRE
    ) AS ESPLATKA,
    (SELECT DECODE(SUM(C1.EPOL_CASTKA) , NULL , 0 , SUM(C1.EPOL_CASTKA))
    FROM NAJPLAPOL C1 ,
      CISPOLPRE C2
    WHERE C1.ID_POLONAJ   = C2.ID_POLONAJ
    AND((C2.DEFVYNOS NOT IN ('V','Z','S','A'))
    OR (C2.DEFVYNOS      IS NULL))
    AND C1.ID_NAJVPLAPRE  = MT.ID_NAJVPLAPRE
    ) AS EOSTATNI,
    (SELECT SUM(EROZ_CASTKA)
    FROM NAJVPLAPRE B1
    WHERE B1.ID_NAJDATSPLT = MT.ID_NAJDATSPLT
    AND B1.DAT_STORNA     IS NULL
    ) AS ZAPLPRED_CELKEM ,
    ( A10.PREDEPSANO -
    (SELECT SUM(EROZ_CASTKA)
    FROM NAJVPLAPRE B1
    WHERE B1.ID_NAJDATSPLT = MT.ID_NAJDATSPLT
    AND B1.DAT_STORNA     IS NULL
    ))                                    AS ROZDIL,
    (NAJPLATBY_TEST_UCE(MT.ID_NAJPLATBY)) AS TEST_UCE,
    MT.TYP ,
    A3.UCE_DOKLAD_KOD ,
    A3.UCE_DOKLAD_CISLO,
    A3.UCE_DOKLAD_POL,
    A14.ID_CISUJEDN  AS ID_CISUJEDN_NAJ,
    A14.J1_NAZEV     AS UCEJED_NAJ,
    A14.KOD_CISUJEDN AS KOD_UCEJED_NAJ,
    A11.AKOD_OBJEKT,
    A11.ID_SEGMENT,
    A11.ID_STAVOBJ,
    A16.ID_KOLURC,
    NVL(TRIM(A17.J1_NAZEV),A11.ATYP_PROSTORU) AS NAZEV_KOLUR ,
    MT.IDENT,
    TO_CHAR(MT.DATVYR,'HH24:MI:SS')   AS CAS_DATVYR,
    TO_CHAR(MT.DATZMENY,'HH24:MI:SS') AS CAS_DATZMENY,
    MT.DATVYR,
    MT.LIDENT,
    DECODE( A18.ID_SSSLOGIN,NULL,MT.IDENT,A18.JMENO)AS LIDENT_JMENO,
    MT.DATZMENY,
    MT.LIDENT_ZMENA ,
    A19.JMENO    AS LIDENT_ZMENA_JMENO,
    A21.J1_NAZEV AS CNAJPEN,
    A11.ID_ADR,
    DECODE( A15.PLATNY,'A', '!' , '-' ) AS HOM,
    MT.UCEUZA ,
    A20.CISLO_SMLOUVY,
    A22.KOD_CISUSTRD,
    A22.J1_NAZEV                                AS CISUSTRD_NAZEV ,
    TRIM(TO_CHAR(A3.datum_bankvypis,'YYYY/MM')) AS MES_BANKVYPIS,
    TRIM(TO_CHAR(A3.datum_zaplaceni,'YYYY/MM')) AS MES_ZAPLACENI,
    A24.PLATCE_DPH,
    A24.DPHDATUM ,
    (A3.DATUM_ZAPLACENI-A10.DATUM_SPLATNOSTI ) AS DEND ,
    A25.KOD_CISPREDVZT,
    A25.J1_NAZEV AS CISPREDVZT_NAZEV,
    A14.ID_CCLE  AS ID_CCLE_VLASTOBJ,
    ( SELECT B3.DAT_ODVODU
          FROM UCEVPOKLOK B1, UCEPOLPOK B2,UCEHLAPOK B3
          WHERE B1.ID_NAJPLATBY = MT.ID_NAJPLATBY
             AND B1.ID_UCEPOLPOK = B2.ID_UCEPOLPOK
             AND B2.ID_UCEHLAPOK = B3.ID_UCEHLAPOK
             AND ROWNUM < 2 ) AS DAT_ODVODU,
     MT.UCEUZA_STORNO, MT.ID_CCLE AS CIN,
     A10.UZAVERKA AS UCEMES_NAJDATSPLT,
( MT.ROZ_CASTKA -
(  select nvl(sum(epol_castka),0) from najplapol b1
   where b1.id_najvplapre=MT.ID_najvplapre ) ) AS ROZPOL,
ICO_PAP(MT.ID_CCLE) AS ICO_PAP,
A11.APARCELA, A11.ID_UZEMI,
A26.UZEMI,INS_RIZ,EXEKUCE,
(  SELECT COUNT(*) AS
     FROM NAJVNESTROZ B1
     WHERE B1.ID_NAJVPLAPRE = MT.ID_NAJVPLAPRE
        AND ROWNUM < 2 ) AS POCET_NE_STORNO,
A16.KOD_PROSTOR_KU , A10.ID_CISUOPER,
A27.KOD_CISUOPER, A27.J1_NAZEV AS NAZEV_CISUOPER,
MT.CISLO_ZAVERKY, A28.ID_NAJVPLAUCE,
A28.ID_UCEUZA, A29.NAZEV AS NAZEV_UPREHOZ,
A29.OBDOBI_UCE AS OBDOBI_UCE_UREHOZ, A28.DO_UCE AS DO_UCE_UPREHOZ,
A10.DTDPH AS DTDPH_PREDPIS
  FROM NAJVPLAPRE MT ,
    NAJPLATBY A3,
    CISDPLAT A4 ,
    CISTYPPLAT A5 ,
    CISMENA A6 ,
    NAJPREDP A7,
    CISDRPRE A8 ,
    CTYPPRED A9 ,
    NAJDATSPLT A10 ,
    SSSHLEDEJ_A A11,
    CISDRUPLAT A12,
    NAJPOKPLA A13,
    CISUJEDN A14 ,
    NAJVZTAH A15,
    OBPPRSTR A16,
    CISKOLUR A17,
    SSSLOGIN A18,
    SSSLOGIN A19,
    NAJUDAJE A20,
    CNAJPEN A21,
    CISUSTRD A22,
    CLEOSOBY A23,
    PAROPAR A24,
    CISPREDVZT A25, CISKATUZ A26,
    CISUOPER A27, NAJVPLAUCE A28,
    UCEUZA A29
  WHERE MT.ID_NAJPLATBY = A3.ID_NAJPLATBY
  AND A3.ID_DPLA        = A4.ID_DPLA(+)
  AND A3.ID_CISTYPPLAT  = A5.ID_CISTYPPLAT(+)
  AND A3.ID_CISDRUPLAT  = A12.ID_CISDRUPLAT(+)
  AND A3.ID_MENA        = A6.ID_MENA(+)
  AND MT.ID_PREDPIS     = A7.ID_PREDPIS(+)
  AND A10.ID_DRUPRE     = A8.ID_DRUPRE(+)
  AND A7.ID_CTYPPRED    = A9.ID_CTYPPRED(+)
  AND MT.ID_NAJDATSPLT  = A10.ID_NAJDATSPLT(+)
  AND MT.ID_NAJPROS     = A11.ID_NAJPROS(+)
  AND A3.ID_NAJVZTAH    = A15.ID_NAJVZTAH(+)
  AND A15.ID_CISUJEDN   = A14.ID_CISUJEDN(+)
  AND MT.ID_NAJPOKPLA   = A13.ID_NAJPOKPLA(+)
  AND A11.ID_PROSTOR    = A16.ID_PROSTOR(+)
  AND A16.ID_KOLURC     = A17.ID_KOLURC(+)
  AND MT.LIDENT         = A18.ID_SSSLOGIN(+)
  AND MT.LIDENT_ZMENA   = A19.ID_SSSLOGIN(+)
  AND A10.ID_NAJUDAJE   = A20.ID_NAJUDAJE(+)
  AND A20.ID_CNAJPEN    = A21.ID_CNAJPEN(+)
  AND A20.ID_CISUSTRD   = A22.ID_CISUSTRD(+)
  AND MT.ID_CCLE        = A23.ID_CCLE(+)
  AND A23.ID_PAR        = A24.ID_PAR(+)
  AND A15.ID_CISPREDVZT = A25.ID_CISPREDVZT(+)
  AND A11.ID_UZEMI      = A26.ID_UZEMI(+)
  AND A10.ID_CISUOPER   = A27.ID_CISUOPER(+)
  AND MT.ID_NAJVPLAPRE  = A28.ID_NAJVPLAPRE(+)
  AND A28.ID_UCEUZA     = A29.ID_UCEUZA(+)
</pre>

**Comment by okbob** [comment]
I see this issue - probably we have broken sources - it is not a bug
