### ISSUE TITLE
Translation of OUTER join produce invalid expressions

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#305]
We are near the end - 90% from our thousands views are translated - but there are still few errors:

Oracle:
<pre>
CREATE OR REPLACE VIEW IDES_PRAHA22.V_NAJUDAJE AS
SELECT MT.ID_NAJUDAJE, MT.ID_NAJVZTAH ,MT.ID_ASPRAVCE,
       MT.DATUM_UZI_VZTAHU, MT.IDENT,
      MT.DATUM_NAJEM_OD,MT.VYP_LHUTA,MT.CISLO_SMLOUVY,
      MT.DATUM_PLATNOSTI_OD,
      MT.DATUM_DOBA_URCITA,
      MT.DATUM_UKONCENI_NAJMU,MT.DATUM_PRIDELENI,
      MT.CISLO_PRIDELENI,
      MT.DATUM_INFLACE,MT.DATUM_PODPIS_NAJEMCE,
      MT.DATUM_PODPIS_PRONAJIMATEL,
      MT.DATUM_PRAVNI_ODDELENI,MT.DATUM_PROLONGACE,
      MT.DATUM_VYBEROVE_RIZENI,
      MT.CISLO_VYBEROVE_RIZENI,MT.DATUM_ROZHODNUTI,
      MT.ORGAN_ROZHODL,
      MT.EXT_CISLO_SMLOUVY,MT.TYP_SMLOUVY,
      MT.MIRA_UTAJENI,MT.MISTO_ULOZENI_SMLOUVY,
      A1.J1_NAZEV AS CNAJDUVOD_NAZ ,
      A2.J1_NAZEV AS CNAJSTAV_NAZ,
      A3.J1_NAZEV AS CISMENA_NAZ,MT.DATUM_PODANI_VYPOVEDI,
      MT.DATUM_MOZNE_VYPOVEDI,
      A4.J1_NAZEV AS CISDOPLA_NAZ ,
      MT.VARS,MT.SPLATNOSTTXT , MT.INTERCISLO , MT.ZIV,MT.POZNAMKA ,
      MT.PLATNOST_OD , MT.PLATNOST_DO,MT.SPLATNOSTDAT,MT.DATVYR ,
      MT.DATUZA , MT.BLOKOVANO , MT.CVZNIKRADK ,
      A6.J1_NAZEV AS CNAJVZTAH_NAZ,
      MT.ID_CNAJDUVOD ,MT.ID_CNAJSTAV ,MT.ID_DOBAPLAT ,
      MT.ID_MENA, MT.ID_CNAJPEN ,MT.ID_CNAJVZTAH ,
      A7.J1_NAZEV AS CNAJPEN , MT.VICE_LOK,
      A9.ID_CISPREDVZT , A9.KOD_CISPREDVZT,
      A9.J1_NAZEV AS NAZEV_CISPREDVZT,
      A8.OBDOBI_OD , A8.OBDOBI_DO , MT.GEN_PREDPIS ,MT.NAJPOC ,
      MT.ID_APROVOZNA , MT.LIDENT , MT.ID_DPLA , MT.ID_CSIPOPOPL ,
      A8.ID_NAJVZTAH_A , A8.EDIT , A10.KOD_DPLA, MT.ID_SKUP_CISEL,
      A8.VOLNA_LOKALIZACE ,MT.ID_NAJSIPOCIS,MT.DEN_SPLAT,
      A8.ID_CISUJEDN,   MT.SIPO_POPL_PRED_VZOR ,
      MT.DOD_PRED_OLD_UZI ,MT.DOD_PRED_NEW_OSOBY ,
      MT.PAR711_2B ,
      '' AS OBDOBIVZT_TXT, MT.DPREVZETI,
      NAJUDAJE_SPOL_VLAST(MT.ID_NAJVZTAH) AS SPOL_VLAST,
      A11.J1_NAZEV AS NAZEV_CISUJEDN,
      A13.NAJMENO , A15.J1_NAZEV AS NAZEV_CISUSTRD,
      '' AS ZMENA, A13.ID_PROSTOR, MT.HRANICE_INFLA,
      MT.DAT_BEZ_PRAVA_OD, MT.POSUN_MES_ZAV,
      MT.EXP_INTERCISLO,MT.DATUM_PROGRAM_BYDLENI,
      MT.DATUM_KUPNI_SMLOUVA , MT.ID_CISUOPER,
      A16.KOD_CISUOPER, A16.J1_NAZEV AS NAZEV_CISUOPER,
      MT.DTDPH, MT.DEN_DTDPH,MT.VARS_PLATBA,
      A8.NEPOCITAT_NEPL
 FROM NAJUDAJE MT,CNAJDUVOD A1,CNAJSTAV A2,
      CISMENA A3,CISDOPLA A4,
      CNAJVZTAH A6 , CNAJPEN A7 , NAJVZTAH A8,
      CISPREDVZT A9 , CISDPLAT A10,
      CISUJEDN A11, SSSHLEDEJ_A A13,
      UCEVSTRDVZT A14, CISUSTRD A15,
      CISUOPER A16
 WHERE (MT.ID_CNAJDUVOD=A1.ID_CNAJDUVOD(+)) AND
       (MT.ID_CNAJSTAV=A2.ID_CNAJSTAV(+)) AND
       (MT.ID_MENA=A3.ID_MENA(+)) AND
       (MT.ID_DOBAPLAT=A4.ID_DOBAPLAT(+)) AND
       (MT.ID_CNAJPEN=A7.ID_CNAJPEN(+)) AND
       (MT.ID_CNAJVZTAH=A6.ID_CNAJVZTAH(+)) AND
       (MT.ID_NAJVZTAH = A8.ID_NAJVZTAH) AND
       (A8.ID_CISPREDVZT = A9.ID_CISPREDVZT(+)) AND
        MT.ID_DPLA = A10.ID_DPLA(+) AND
        A8.ID_CISUJEDN =A11.ID_CISUJEDN(+) AND
        MT.ID_NAJVZTAH= A13.ID_NAJVZTAH(+) AND A13.TYP='N' and A13.HLAVNI='H'
        AND MT.ID_NAJVZTAH=A14.ID_NAJVZTAH(+)
        AND A14.ID_CISUSTRD =A15.ID_CISUSTRD(+)
        AND MT.ID_CISUOPER=A16.ID_CISUOPER(+)
</pre>

Ora2pg result:
<pre>
ERROR:  syntax error at or near ")"
ŘÁDKA 55:  WHERE(  ) AND (  ) AND (  ) AND (  ) AND (  ) AND (  ) AND ...
                   ^
STATEMENT:  CREATE OR REPLACE VIEW v_najudaje (id_najudaje, id_najvztah, id_aspravce, datum_uzi_vztahu, ident, datum_najem_od, vyp_lhuta, cislo_smlouvy, datum_platnosti_od, datum_doba_urcita, datum_ukonceni_najmu, 
       MT.DATUM_UZI_VZTAHU, MT.IDENT,
      MT.DATUM_NAJEM_OD,MT.VYP_LHUTA,MT.CISLO_SMLOUVY,
      MT.DATUM_PLATNOSTI_OD,
      MT.DATUM_DOBA_URCITA,
      MT.DATUM_UKONCENI_NAJMU,MT.DATUM_PRIDELENI,
      MT.CISLO_PRIDELENI,
      MT.DATUM_INFLACE,MT.DATUM_PODPIS_NAJEMCE,
      MT.DATUM_PODPIS_PRONAJIMATEL,
      MT.DATUM_PRAVNI_ODDELENI,MT.DATUM_PROLONGACE,
      MT.DATUM_VYBEROVE_RIZENI,
      MT.CISLO_VYBEROVE_RIZENI,MT.DATUM_ROZHODNUTI,
      MT.ORGAN_ROZHODL,
      MT.EXT_CISLO_SMLOUVY,MT.TYP_SMLOUVY,
      MT.MIRA_UTAJENI,MT.MISTO_ULOZENI_SMLOUVY,
      A1.J1_NAZEV AS CNAJDUVOD_NAZ ,
      A2.J1_NAZEV AS CNAJSTAV_NAZ,
      A3.J1_NAZEV AS CISMENA_NAZ,MT.DATUM_PODANI_VYPOVEDI,
      MT.DATUM_MOZNE_VYPOVEDI,
      A4.J1_NAZEV AS CISDOPLA_NAZ ,
      MT.VARS,MT.SPLATNOSTTXT , MT.INTERCISLO , MT.ZIV,MT.POZNAMKA ,
      MT.PLATNOST_OD , MT.PLATNOST_DO,MT.SPLATNOSTDAT,MT.DATVYR ,
      MT.DATUZA , MT.BLOKOVANO , MT.CVZNIKRADK ,
      A6.J1_NAZEV AS CNAJVZTAH_NAZ,
      MT.ID_CNAJDUVOD ,MT.ID_CNAJSTAV ,MT.ID_DOBAPLAT ,
      MT.ID_MENA, MT.ID_CNAJPEN ,MT.ID_CNAJVZTAH ,
      A7.J1_NAZEV AS CNAJPEN , MT.VICE_LOK,
      A9.ID_CISPREDVZT , A9.KOD_CISPREDVZT,
      A9.J1_NAZEV AS NAZEV_CISPREDVZT,
      A8.OBDOBI_OD , A8.OBDOBI_DO , MT.GEN_PREDPIS ,MT.NAJPOC ,
      MT.ID_APROVOZNA , MT.LIDENT , MT.ID_DPLA , MT.ID_CSIPOPOPL ,
      A8.ID_NAJVZTAH_A , A8.EDIT , A10.KOD_DPLA, MT.ID_SKUP_CISEL,
      A8.VOLNA_LOKALIZACE ,MT.ID_NAJSIPOCIS,MT.DEN_SPLAT,
      A8.ID_CISUJEDN,   MT.SIPO_POPL_PRED_VZOR ,
      MT.DOD_PRED_OLD_UZI ,MT.DOD_PRED_NEW_OSOBY ,
      MT.PAR711_2B ,
      '' AS OBDOBIVZT_TXT, MT.DPREVZETI,
      NAJUDAJE_SPOL_VLAST(MT.ID_NAJVZTAH) AS SPOL_VLAST,
      A11.J1_NAZEV AS NAZEV_CISUJEDN,
      A13.NAJMENO , A15.J1_NAZEV AS NAZEV_CISUSTRD,
      '' AS ZMENA, A13.ID_PROSTOR, MT.HRANICE_INFLA,
      MT.DAT_BEZ_PRAVA_OD, MT.POSUN_MES_ZAV,
      MT.EXP_INTERCISLO,MT.DATUM_PROGRAM_BYDLENI,
      MT.DATUM_KUPNI_SMLOUVA , MT.ID_CISUOPER,
      A16.KOD_CISUOPER, A16.J1_NAZEV AS NAZEV_CISUOPER,
      MT.DTDPH, MT.DEN_DTDPH,MT.VARS_PLATBA,
      A8.NEPOCITAT_NEPL
  FROM NAJUDAJE MT,CNAJDUVOD A1,CNAJSTAV A2,
      CISMENA A3,CISDOPLA A4,
      CNAJVZTAH A6 , CNAJPEN A7 , NAJVZTAH A8,
      CISPREDVZT A9 , CISDPLAT A10,
      CISUJEDN A11, SSSHLEDEJ_A A13,
      UCEVSTRDVZT A14, CISUSTRD A15,
      CISUOPER A16
 WHERE(  ) AND (  ) AND (  ) AND (  ) AND (  ) AND (  ) AND (MT.ID_NAJVZTAH = A8.ID_NAJVZTAH) AND (  )    AND A13.TYP='N' and A13.HLAVNI='H';
</pre>

**Comment by darold** [comment]
Last two commits 8ac180c and 6723220, especially the last one will fix this issue.

**Comment by okbob** [comment]
fixed
