### ISSUE TITLE
Wrong order of OUTER join clauses

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#308]
Oracle
<pre>
CREATE OR REPLACE VIEW IDES_PRAHA22.V_UDRVRAJRAD AS
SELECT MT.ID_UDRVRAJRAD , MT.ID_SSSRAJON , MT.ID_UDRCISRAD ,
          MT.PLATNOST_OD , MT.PLATNOST_DO , MT.POZNAMKA ,
          MT.IDENT , MT.BLOKOVANO , 
          MT.DATVYR ,MT.NAZEV,
          MT.CVZNIKRADK , MT.ID_ASPRAVCE , MT.ID_APROVOZNA ,
          MT.LIDENT , MT.DATZMENY , MT.LIDENT_ZMENA ,
          TO_CHAR(MT.DATVYR,'HH24:MI:SS') AS CAS_DATVYR,
          TO_CHAR(MT.DATZMENY,'HH24:MI:SS') AS CAS_DATZMENY,  
          DECODE( A10.ID_SSSLOGIN,NULL,MT.IDENT,A10.JMENO)AS LIDENT_JMENO,    
          A11.JMENO AS LIDENT_ZMENA_JMENO,
          MT.ID_COPY_CIS , MT.ID_SKUP_CISEL ,
          A2.NAZEV AS SSSRAJON , A2.KOD_RAJ ,
          A3.J1_NAZEV AS UDRCISRAD , A3.KOD_UDRCISRAD ,
          A7.J1_NAZEV AS CSKUPINA , A7.KOD_SKUP_CISL ,
          A8.NAJMENO, A3.ID_UCEPOKLADNA, 
          A13.KOD_UCEPOKLADNA, A13.J1_NAZEV AS UCEPOKLADNA,
          A3.ID_UCEOBDOBI, A12.KOD_UCEOBDOBI, 
          A12.J1_NAZEV AS NAZEV_UCEOBDOBI, A12.ID_CISUJEDN, 
          A14.KOD_CISUJEDN, A14.J1_NAZEV AS NAZEV_CISUJEDN,
          A2.ID_ROLE , A15.KOD_ROLE , 
          A15.J1_NAZEV AS NAZEV_SSSROLE ,    
          A16.KOD_CISTYPDEF, A16.J1_NAZEV AS NAZE_CISTYPDEF,
          A17.KOD_UCEOBDOBI as KOD_UCEOBDOBI_IMP, 
          A17.J1_NAZEV AS NAZEV_UCEOBDOBI_IMP,  
          A14.ID_UCEOBDOBI_IMP 
       FROM UDRVRAJRAD MT, SSSRAJON A2 ,
           SSSVRAJOSO A9,
           UDRCISRAD A3 , CSKUPINA A7 ,
           CLEOSOBY A8,
           SSSLOGIN A10, SSSLOGIN A11,
           UCEPOKLADNA A13, UCEOBDOBI A12,
           CISUJEDN A14, SSSROLE A15,
           CISTYPDEF A16, UCEOBDOBI A17
      WHERE  MT.ID_SSSRAJON = A2.ID_SSSRAJON  AND
             MT.ID_UDRCISRAD = A3.ID_UDRCISRAD(+)  AND
             MT.ID_SKUP_CISEL = A7.ID_SKUP_CISEL(+)  AND
             A2.ID_SSSRAJON = A9.ID_SSSRAJON AND
             MT.LIDENT = A10.ID_SSSLOGIN(+) AND
             MT.LIDENT_ZMENA = A11.ID_SSSLOGIN(+) AND 
             A3.ID_UCEPOKLADNA = A13.ID_UCEPOKLADNA(+) AND
             A3.ID_UCEOBDOBI = A12.ID_UCEOBDOBI(+) AND  
             A14.ID_UCEOBDOBI_IMP=A17.ID_UCEOBDOBI(+) AND
             A12.ID_CISUJEDN = A14.ID_CISUJEDN(+) AND 
             A3.ID_CISTYPDEF =A16.ID_CISTYPDEF(+) AND
             A2.ID_ROLE = A15.ID_ROLE(+) AND
            ( A9.DALSI IS NULL
             OR A9.DALSI = 'N' ) AND
             A9.ID_CCLE = A8.ID_CCLE AND
             A9.PLATNOST_OD <= sysdate AND
             A9.PLATNOST_Do >= sysdate
</pre>

Ora2Pg
<pre>
ERROR:  invalid reference to FROM-clause entry for table "a14"
ŘÁDKA 37: LEFT OUTER JOIN uceobdobi a17 ON (A14.ID_UCEOBDOBI_IMP = A17...
                                            ^
DOPORUČENÍ:  There is an entry for table "a14", but it cannot be referenced from this part of the query.
STATEMENT:  CREATE OR REPLACE VIEW v_udrvrajrad (id_udrvrajrad, id_sssrajon, id_udrcisrad, platnost_od, platnost_do, poznamka, ident, blokovano, datvyr, nazev, cvznikradk, id_aspravce, id_aprovozna, lident, datzmeny, lident_zmena, cas_datvyr, cas_datzmeny, lident_jmeno, lident_zmena_jmeno, id_copy_cis, id_skup_cisel, sssrajon, kod_raj, udrcisrad, kod_udrcisrad, cskupina, kod_skup_cisl, najmeno, id_ucepokladna, kod_ucepokladna, ucepokladna, id_uceobdobi, kod_uceobdobi, nazev_uceobdobi, id_cisujedn, kod_cisuj
          MT.PLATNOST_OD , MT.PLATNOST_DO , MT.POZNAMKA ,
          MT.IDENT , MT.BLOKOVANO ,
          MT.DATVYR ,MT.NAZEV,
          MT.CVZNIKRADK , MT.ID_ASPRAVCE , MT.ID_APROVOZNA ,
          MT.LIDENT , MT.DATZMENY , MT.LIDENT_ZMENA ,
          TO_CHAR(MT.DATVYR,'HH24:MI:SS') AS CAS_DATVYR,
          TO_CHAR(MT.DATZMENY,'HH24:MI:SS') AS CAS_DATZMENY,..
          CASE WHEN  A10.ID_SSSLOGIN IS NULL THEN MT.IDENT  ELSE A10.JMENO END LIDENT_JMENO,....
          A11.JMENO AS LIDENT_ZMENA_JMENO,
          MT.ID_COPY_CIS , MT.ID_SKUP_CISEL ,
          A2.NAZEV AS SSSRAJON , A2.KOD_RAJ ,
          A3.J1_NAZEV AS UDRCISRAD , A3.KOD_UDRCISRAD ,
          A7.J1_NAZEV AS CSKUPINA , A7.KOD_SKUP_CISL ,
          A8.NAJMENO, A3.ID_UCEPOKLADNA,.
          A13.KOD_UCEPOKLADNA, A13.J1_NAZEV AS UCEPOKLADNA,
          A3.ID_UCEOBDOBI, A12.KOD_UCEOBDOBI,.
          A12.J1_NAZEV AS NAZEV_UCEOBDOBI, A12.ID_CISUJEDN,.
          A14.KOD_CISUJEDN, A14.J1_NAZEV AS NAZEV_CISUJEDN,
          A2.ID_ROLE , A15.KOD_ROLE ,.
          A15.J1_NAZEV AS NAZEV_SSSROLE ,....
          A16.KOD_CISTYPDEF, A16.J1_NAZEV AS NAZE_CISTYPDEF,
          A17.KOD_UCEOBDOBI as KOD_UCEOBDOBI_IMP,.
          A17.J1_NAZEV AS NAZEV_UCEOBDOBI_IMP,..
          A14.ID_UCEOBDOBI_IMP.
        FROM cleosoby a8, sssvrajoso a9, udrvrajrad mt
LEFT OUTER JOIN udrcisrad a3 ON (MT.ID_UDRCISRAD = A3.ID_UDRCISRAD)
LEFT OUTER JOIN cskupina a7 ON (MT.ID_SKUP_CISEL = A7.ID_SKUP_CISEL)
LEFT OUTER JOIN ssslogin a10 ON (MT.LIDENT = A10.ID_SSSLOGIN)
LEFT OUTER JOIN ssslogin a11 ON (MT.LIDENT_ZMENA = A11.ID_SSSLOGIN)
LEFT OUTER JOIN ucepokladna a13 ON (A3.ID_UCEPOKLADNA = A13.ID_UCEPOKLADNA)
LEFT OUTER JOIN uceobdobi a12 ON (A3.ID_UCEOBDOBI = A12.ID_UCEOBDOBI)
LEFT OUTER JOIN cistypdef a16 ON (A3.ID_CISTYPDEF = A16.ID_CISTYPDEF)
LEFT OUTER JOIN cisujedn a14 ON (A12.ID_CISUJEDN = A14.ID_CISUJEDN)
, sssrajon a2
LEFT OUTER JOIN sssrole a15 ON (A2.ID_ROLE = A15.ID_ROLE)
LEFT OUTER JOIN uceobdobi a17 ON (A14.ID_UCEOBDOBI_IMP = A17.ID_UCEOBDOBI)
WHERE MT.ID_SSSRAJON = A2.ID_SSSRAJON   AND A2.ID_SSSRAJON = A9.ID_SSSRAJON         AND ( A9.DALSI IS NULL
             OR A9.DALSI = 'N' ) AND A9.ID_CCLE = A8.ID_CCLE AND A9.PLATNOST_OD <= LOCALTIMESTAMP AND A9.PLATNOST_Do >= LOCALTIMESTAMP;
</pre>

**Comment by darold** [comment]
Might be fixed with last commit too.

**Comment by okbob** [comment]
This error was not fixed. The outer join a17 should be fore inner join:
<pre>
 LEFT OUTER JOIN cisujedn a14 ON (A12.ID_CISUJEDN = A14.ID_CISUJEDN)
LEFT OUTER JOIN uceobdobi a17 ON (A14.ID_UCEOBDOBI_IMP = A17.ID_UCEOBDOBI)
, sssrajon a2
LEFT OUTER JOIN sssrole a15 ON (A2.ID_ROLE = A15.ID_ROLE)
</pre>

**Comment by darold** [comment]
Last commit 461fe46 might solve this issue.

**Comment by okbob** [comment]
fixed
