### ISSUE TITLE
Syntax error in expression - missing AND

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#310]
I hope so it is last error from our batch of views migrations - now we are on 97% of successfully migrated views - 1250 views in 45K lines.

Oracle:
<pre>
CREATE OR REPLACE VIEW IDES_PRAHA22.V_HOSPODAR_106 AS
select ID_PROSTOR,KATASTR, CP, ADRESA, ABYT_NEBYT, AKOD_PROSTOR, MPLOCHA, NAJPL, NAZSPRAVCE AS SPRAVCE, VOLNY
, DECODE(VOLNY,'!',(
  select ANAJMENO from V_NAJVZTAH 
  where id_prostor=PRT.ID_PROSTOR and PLATNY = 'A' AND VOLNA_LOKALIZACE IS NULL 
  AND ( (PLATNOST_OD <= sysdate AND PLATNOST_DO >= '1.1.4000') OR (PLATNOST_OD <= '1.1.4000' AND PLATNOST_DO >= sysdate) )
  and rownum<2
  ),null) AS NAJEMCE
, DECODE(VOLNY,'!',(
  select to_char(OBDOBI_OD,'DD.MM.YYYY') from V_NAJVZTAH 
  where id_prostor=PRT.ID_PROSTOR and PLATNY = 'A' AND VOLNA_LOKALIZACE IS NULL 
  AND ( (PLATNOST_OD <= sysdate AND PLATNOST_DO >= '1.1.4000') OR (PLATNOST_OD <= '1.1.4000' AND PLATNOST_DO >= sysdate) )
  and rownum<2
  ),null) AS OD
, DECODE(VOLNY,'!',(
  select to_char(DATUM_DOBA_URCITA,'DD.MM.YYYY') from V_NAJVZTAH 
  where id_prostor=PRT.ID_PROSTOR and PLATNY = 'A' AND VOLNA_LOKALIZACE IS NULL 
  AND ( (PLATNOST_OD <= sysdate AND PLATNOST_DO >= '1.1.4000') OR (PLATNOST_OD <= '1.1.4000' AND PLATNOST_DO >= sysdate) )
  and rownum<2
  ),null) AS DO
, DECODE(VOLNY,'!',(
  select P2.VYNOS_NEW from V_NAJVZTAH P1, V_NAJPREDP_AKT P2 
  where P1.id_prostor=PRT.ID_PROSTOR and P1.PLATNY = 'A' AND P1.VOLNA_LOKALIZACE IS NULL 
  AND ( (P1.PLATNOST_OD <= sysdate AND P1.PLATNOST_DO >= '1.1.4000') OR (P1.PLATNOST_OD <= '1.1.4000' AND P1.PLATNOST_DO >= sysdate) )
  AND P1.ID_NAJVZTAH=P2.ID_NAJVZTAH
  AND to_date('01'||to_char(P2.OBDOBI_OD,'MMYYYY'),'DDMMYYYY') <= P1.DATUZA 
  AND to_date('01'||to_char(P2.OBDOBI_DO,'MMYYYY'),'DDMMYYYY')>= P1.DATUZA and trim(P2.KOD_DRUPRE) = 'N' and trim(P2.KOD_CTYPPRED) = 'B'
  and rownum<2
  ),null) AS NAJEM, PLATNOST_OD, PLATNOST_DO, ID_ASPRAVCE, ID_APROVOZNA,ANAZEV_VLAST,CISUJEDN,ID_SKUP_CISEL,
  DECODE(VOLNY,'!',(
  select NAJVZTAH_SAZBA(id_najvztah) from V_NAJVZTAH 
  where id_prostor=PRT.ID_PROSTOR and PLATNY = 'A' AND VOLNA_LOKALIZACE IS NULL 
  AND ( (PLATNOST_OD <= sysdate AND PLATNOST_DO >= '1.1.4000') OR (PLATNOST_OD <= '1.1.4000' AND PLATNOST_DO >= sysdate) )
  and rownum<2
  ),null) AS INFO_SAZBA, SEZNAM_PARCEL

from (
Select ID_PROSTOR, KOD_UZEMI AS KATASTR, ACISPOP AS CP, PARADR_ADRA(ID_ADR) AS ADRESA, ABYT_NEBYT, AKOD_PROSTOR
, ( SELECT DECODE( SUM(PLOCHA) , NULL , 0 , SUM(PLOCHA )) FROM V_OBPPLOCH B1 WHERE B1.ID_PROSTOR = MT.ID_PROSTOR AND TRIM(B1.KOD_TYP_PLOCHY) = 'MPLOCHA'
     AND B1.PLATNOST_OD <= '1.1.4000' AND B1.PLATNOST_DO >= '1.1.4000' and B1.POSLEDNI='A' AND ROWNUM < 2 ) AS MPLOCHA
, ( SELECT DECODE( SUM(PLOCHA) , NULL , 0 , SUM(PLOCHA )) FROM V_OBPPLOCH B1 WHERE B1.ID_PROSTOR = MT.ID_PROSTOR AND TRIM(B1.KOD_TYP_PLOCHY) =
    DECODE( MT.ABYT_NEBYT,'B','NAJPL', 'MPLN' )
    AND B1.PLATNOST_OD <= '1.1.4000' AND B1.PLATNOST_DO >= '1.1.4000' and B1.POSLEDNI='A' AND ROWNUM < 2 ) AS NAJPL
, CASE 
  WHEN(((ID_PROSTOR NOT IN (SELECT ID_PROSTOR FROM V_NAJVZTAHLOK B1 WHERE MT.ID_PROSTOR = B1.ID_PROSTOR AND VOLNA_LOKALIZACE IS NULL AND 
         OBDOBI_OD <= sysdate AND OBDOBI_DO >= sysdate  AND KOD_CISPREDVZT = 'N' )) 
        AND ( ID_PROSTOR IN (SELECT C1.ID_PROSTOR FROM V_OBPVLASTLOK C1 WHERE C1.ID_PROSTOR = MT.ID_PROSTOR AND C1.ID_CISUJEDN IS NOT NULL 
           AND VLAST_OD <= sysdate    AND VLAST_DO >= sysdate ))) OR 
     ( ID_PROSTOR NOT IN (SELECT ID_PROSTOR FROM V_NAJVZTAHLOK B1 WHERE MT.ID_PROSTOR = B1.ID_PROSTOR AND VOLNA_LOKALIZACE IS NULL 
       AND OBDOBI_OD <= sysdate AND OBDOBI_DO >= sysdate ))) 
  THEN '-' ELSE '!' END AS VOLNY
, NAZSPRAVCE ,PLATNOST_OD,PLATNOST_DO,ID_ASPRAVCE, ID_APROVOZNA,ANAZEV_VLAST,CISUJEDN,ID_SKUP_CISEL,
''  AS INFO_SAZBA, GET_SEZNAM_PARCEL(ID_SEGMENT,'D') AS SEZNAM_PARCEL
from V_OBPPRSTR MT 
where MT.platnost_od <= sysdate and MT.platnost_do >= '1.1.4000' 
order by KOD_UZEMI, ACISPOP, ID_SEGMENT, AKOD_PROSTOR
) PRT
</pre>

Ora2pg:
<pre>
ERROR:  syntax error at or near "B1"
ŘÁDKA 35: ... MT.ABYT_NEBYT='B' THEN 'NAJPL'  ELSE 'MPLN'  END B1.PLATNOS...
                                                               ^
STATEMENT:  CREATE OR REPLACE VIEW v_hospodar_106 (id_prostor, katastr, cp, adresa, abyt_nebyt, akod_prostor, mplocha, najpl, spravce, volny, najemce, od, "DO", najem, platnost_od, platnost_do, id_aspravce, id_aprovozna, anazev_vlast, cisujedn, id_skup_cisel, info_sazba, seznam_parcel) AS SELECT  ID_PROSTOR,KATASTR, CP, ADRESA, ABYT_NEBYT, AKOD_PROSTOR, MPLOCHA, NAJPL, NAZSPRAVCE AS SPRAVCE, VOLNY
, DECODE(VOLNY,'!',(
  select ANAJMENO  FROM V_NAJVZTAH
  where id_prostor=PRT.ID_PROSTOR and PLATNY = 'A' AND VOLNA_LOKALIZACE IS NULL.
  AND ( (PLATNOST_OD <= LOCALTIMESTAMP AND PLATNOST_DO >= '1.1.4000') OR (PLATNOST_OD <= '1.1.4000' AND PLATNOST_DO >= LOCALTIMESTAMP) ).
   LIMIT 1),null) AS NAJEMCE
, DECODE(VOLNY,'!',(
  select to_char(OBDOBI_OD,'DD.MM.YYYY') from V_NAJVZTAH.
  where id_prostor=PRT.ID_PROSTOR and PLATNY = 'A' AND VOLNA_LOKALIZACE IS NULL.
  AND ( (PLATNOST_OD <= LOCALTIMESTAMP AND PLATNOST_DO >= '1.1.4000') OR (PLATNOST_OD <= '1.1.4000' AND PLATNOST_DO >= LOCALTIMESTAMP) ).
   LIMIT 1),null) AS OD
, DECODE(VOLNY,'!',(
  select to_char(DATUM_DOBA_URCITA,'DD.MM.YYYY') from V_NAJVZTAH.
  where id_prostor=PRT.ID_PROSTOR and PLATNY = 'A' AND VOLNA_LOKALIZACE IS NULL.
  AND ( (PLATNOST_OD <= LOCALTIMESTAMP AND PLATNOST_DO >= '1.1.4000') OR (PLATNOST_OD <= '1.1.4000' AND PLATNOST_DO >= LOCALTIMESTAMP) ).
   LIMIT 1),null) AS "DO"
, DECODE(VOLNY,'!',(
  select P2.VYNOS_NEW from V_NAJVZTAH P1, V_NAJPREDP_AKT P2.
  where P1.id_prostor=PRT.ID_PROSTOR and P1.PLATNY = 'A' AND P1.VOLNA_LOKALIZACE IS NULL.
  AND ( (P1.PLATNOST_OD <= LOCALTIMESTAMP AND P1.PLATNOST_DO >= '1.1.4000') OR (P1.PLATNOST_OD <= '1.1.4000' AND P1.PLATNOST_DO >= LOCALTIMESTAMP) )
  AND P1.ID_NAJVZTAH=P2.ID_NAJVZTAH
  AND to_date('01'||to_char(P2.OBDOBI_OD,'MMYYYY'),'DDMMYYYY') <= P1.DATUZA.
  AND to_date('01'||to_char(P2.OBDOBI_DO,'MMYYYY'),'DDMMYYYY')>= P1.DATUZA and btrim(P2.KOD_DRUPRE) = 'N' and btrim(P2.KOD_CTYPPRED) = 'B'.
   LIMIT 1),null) AS NAJEM, PLATNOST_OD, PLATNOST_DO, ID_ASPRAVCE, ID_APROVOZNA,ANAZEV_VLAST,CISUJEDN,ID_SKUP_CISEL,
  DECODE(VOLNY,'!',(
  select NAJVZTAH_SAZBA(id_najvztah) from V_NAJVZTAH.
  where id_prostor=PRT.ID_PROSTOR and PLATNY = 'A' AND VOLNA_LOKALIZACE IS NULL.
  AND ( (PLATNOST_OD <= LOCALTIMESTAMP AND PLATNOST_DO >= '1.1.4000') OR (PLATNOST_OD <= '1.1.4000' AND PLATNOST_DO >= LOCALTIMESTAMP) ).
   LIMIT 1),null) AS INFO_SAZBA, SEZNAM_PARCEL
from (
Select ID_PROSTOR, KOD_UZEMI AS KATASTR, ACISPOP AS CP, PARADR_ADRA(ID_ADR) AS ADRESA, ABYT_NEBYT, AKOD_PROSTOR
, ( SELECT DECODE( SUM(PLOCHA) , NULL , 0 , SUM(PLOCHA )) FROM V_OBPPLOCH B1 WHERE B1.ID_PROSTOR = MT.ID_PROSTOR AND btrim(B1.KOD_TYP_PLOCHY) = 'MPLOCHA'
     AND B1.PLATNOST_OD <= '1.1.4000' AND B1.PLATNOST_DO >= '1.1.4000' and B1.POSLEDNI='A'   LIMIT 1) AS MPLOCHA
, ( SELECT DECODE( SUM(PLOCHA) , NULL , 0 , SUM(PLOCHA )) FROM V_OBPPLOCH B1 WHERE B1.ID_PROSTOR = MT.ID_PROSTOR AND btrim(B1.KOD_TYP_PLOCHY) =
    CASE WHEN  MT.ABYT_NEBYT='B' THEN 'NAJPL'  ELSE 'MPLN'  END B1.PLATNOST_OD <= '1.1.4000' AND B1.PLATNOST_DO >= '1.1.4000' and B1.POSLEDNI='A'   LIMIT 1) AS NAJPL
, CASE.
  WHEN(((ID_PROSTOR NOT IN (SELECT ID_PROSTOR FROM V_NAJVZTAHLOK B1 WHERE MT.ID_PROSTOR = B1.ID_PROSTOR AND VOLNA_LOKALIZACE IS NULL AND.
         OBDOBI_OD <= LOCALTIMESTAMP AND OBDOBI_DO >= LOCALTIMESTAMP  AND KOD_CISPREDVZT = 'N' )).
        AND ( ID_PROSTOR IN (SELECT C1.ID_PROSTOR FROM V_OBPVLASTLOK C1 WHERE C1.ID_PROSTOR = MT.ID_PROSTOR AND C1.ID_CISUJEDN IS NOT NULL.
           AND VLAST_OD <= LOCALTIMESTAMP    AND VLAST_DO >= LOCALTIMESTAMP ))) OR ( ID_PROSTOR NOT IN (SELECT ID_PROSTOR FROM V_NAJVZTAHLOK B1 WHERE MT.ID_PROSTOR = B1.ID_PROSTOR AND VOLNA_LOKALIZACE IS NULL.
       AND OBDOBI_OD <= LOCALTIMESTAMP AND OBDOBI_DO >= LOCALTIMESTAMP ))).
  THEN '-' ELSE '!' END VOLNY
, NAZSPRAVCE ,PLATNOST_OD,PLATNOST_DO,ID_ASPRAVCE, ID_APROVOZNA,ANAZEV_VLAST,CISUJEDN,ID_SKUP_CISEL,
''  AS INFO_SAZBA, GET_SEZNAM_PARCEL(ID_SEGMENT,'D') AS SEZNAM_PARCEL
from V_OBPPRSTR MT.
where MT.platnost_od <= LOCALTIMESTAMP and MT.platnost_do >= '1.1.4000'.
order by KOD_UZEMI, ACISPOP, ID_SEGMENT, AKOD_PROSTOR
) PRT;
</pre>

**Comment by darold** [comment]
Fixed on commit 891358b. All decode() translation are now proceed in a single call before any other translation.

**Comment by okbob** [comment]
fixed
