### ISSUE TITLE
Should Oracle functions be marked as stable by default ?

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#311]
Hello,

In version 18.1 release note, I read
"Oracle function are now marked as stable by default as they can not modify data".
Coming from Oracle's world, I can tell that Oracle functions can modify data or not, depending on the calling context:
- when used in a select/insert/update/delete statement ("genuine SQL"), they can not modify data
- when used in PL/SQL with variable assignment or as conditional expression, they can indeed modify data

Therefore, marking functions as stable by default might not be universal enough, and before I install version 18.1 on my platform, I would like to know if I can configure making all functions volatile indtead of stable.

Thanks for your answer, if you have some time...
Best regards,
edelanoe

**Comment by darold** [comment]
Hi,

Thanks for this explanation on Oracle behavior with function. Last commit 456c655 adds a new FUNCTION_STABLE configuration directive. It is enabled by default so you will have to disable it in the configuration file.

Best regards,

**Comment by edelanoe** [comment]
Thanks a lot for your quick answer.
The configuration directive will be much appreciated.

Just to understand, as I’im new in GitHub : the « last commit » you are telling about… Is it later than version 18.1 or included in it ?  (I cannot see the commit Id in the commit list)

Best regards,
E.Delanoë

De : Darold [mailto:notifications@github.com]
Envoyé : lundi 27 février 2017 16:46
À : darold/ora2pg
Cc : Delanoe Eric; Author
Objet : Re: [darold/ora2pg] Should Oracle functions be marked as stable by default ? (#311)


Hi,

Thanks for this explanation on Oracle behavior with function. Last commit 456c655 adds a new FUNCTION_STABLE configuration directive. It is enabled by default so you will have to disable it in the configuration file.

Best regards,

**Comment by darold** [comment]
Sorry, I mean that you can download latest development code and override your Ora2Pg installation with it. You can download the latest code by using the git command:

    git clone https://github.com/darold/ora2pg.git

or you can download the current code and unzipped it as follow:
```
wget https://github.com/darold/ora2pg/archive/master.zip
unzip master.zip
```

**Comment by darold** [comment]
Note that it was normal that you can't see the commit, I've forgotten to push the changes. Done now.

**Comment by edelanoe** [comment]
OK, cool & understood, thanks again for your 2 mails.

De : Darold [mailto:notifications@github.com]
Envoyé : lundi 27 février 2017 17:11
À : darold/ora2pg
Cc : Delanoe Eric; Author
Objet : Re: [darold/ora2pg] Should Oracle functions be marked as stable by default ? (#311)


Note that it was normal that you can't see the commit, I've forgotten to push the changes. Done now.
