### ISSUE TITLE
Argument types with %ROWTYPE should be translated

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#313]
Hello,

In PL/SQL function prototypes, argument types with %ROWTYPE are left as-is, but, in spite of its promises, PostgreSQL cannot compile them as-is: the %ROWTYPE must be removed.
A workaround could be easily found. If I'm not mistaking, you just have to change:
 "myArgument myTable%ROWTYPE" to "myArgument myTable" when translating function arguments.

Best regards

**Comment by darold** [comment]
Commit 1339b9d remove %ROWTYPE in function that have not been replaced with RECORD for cursor declaration.

**Comment by okbob** [comment]
It can be removed from function result declaration
CREATE OR REPLACE FUNCTION xx() RETURNS composite_type%ROWTYPE --<<

**Comment by darold** [comment]
Fixed in commit 240e801

**Comment by okbob** [comment]
fixed
