### ISSUE TITLE
Unexpected ";" in some function declarations and post-body END

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#314]
Hi again,

I'm having a little trouble in function definitions while using version 18.1.
-1- In declarations (before BEGIN):
--- In version 17.6b: -----------------------------------
CREATE OR REPLACE FUNCTION bqc_get_all_trx_details (argMsgID bigint) RETURNS varchar AS $body$
DECLARE
  vNB bigint := 0;
  cNewLine constant char(1) := CHR(10);
  --cNewLine constant char(2) := CHR(13)||CHR(10);

BEGIN

--- In version 18.1: -----------------------------------
CREATE OR REPLACE FUNCTION bqc_get_all_trx_details (argMsgID bigint) RETURNS varchar AS $body$
DECLARE
  vNB bigint := 0;
  cNewLine constant char(1) := CHR(10);
  --cNewLine constant char(2) := CHR(13)||CHR(10);
;
BEGIN

-2- At end of bodies:
--- In version 17.6b: ------
END; -- app_log_error
$body$
LANGUAGE PLPGSQL
--- In version 18.1: --------
END; -- app_log_error
;
$body$
LANGUAGE PLPGSQL

Best regards

**Comment by darold** [comment]
Last two commits might fix this issue.

**Comment by darold** [comment]
And last commit 782e6c9
