### ISSUE TITLE
dubled `AND` in expression

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#315]
Oracle:
<pre>
CREATE OR REPLACE VIEW IDES_LADENI_JMMAJ.V_OBPREVIZE AS
SELECT MT.ID_OBPREVIZE , MT.ID_CISDRUREV ,
          MT.ID_SPRAVCE , MT.ID_OBPREVIZE_A ,
          MT.ID_OSOB , MT.ID_PAR ,  MT.NAZEV_REVIZE ,
          MT.PLATNOST_OD ,MT.PLATNOST_DO ,
          MT.CISLO_REVIZE,
          MT.IDENT , MT.POZNAMKA , MT.POCET ,
          MT.VYCH_PERIOD, MT.REV_TECHNIK, MT.NEZPRISTUP,
          MT.DAT_ODSTRCHYBY,
          OBPREVIZE_NAKLAD(MT.ID_OBPREVIZE,'REVIZE') AS NAKLAD_REVIZE,
          OBPREVIZE_NAKLAD(MT.ID_OBPREVIZE,'ZAVADA') AS NAKLAD_CHYBA,
          (select count(*) from ucevfakrev B1
                 where B1.id_obprevize=MT.ID_Obprevize and
                   B1.Platnost_do='01.01.4000' and
                   B1.nak_revchyb='R') AS POCET_FSR,
          (select count(*) from ucevfakrev B1
                 where B1.id_obprevize=MT.ID_Obprevize and
                   B1.Platnost_do='01.01.4000' and
                   B1.nak_revchyb='Z') AS POCET_FSZ,
          MT.OBJ_SML, MT.DAT_PREVZETI, MT.POPIS_REV,
          MT.DATVYR ,MT.ID_OBPHLAOBJ,MT.ID_UDRSPRSML,
         ( SELECT COUNT(*) FROM OBPVREVLOK B1
             WHERE B1.ID_OBPREVIZE = MT.ID_OBPREVIZE )  AS POCET_POLOZEK,
          MT.ID_CCLE, MT.ID_CCLE_ODB,
          TO_CHAR(MT.DATVYR,'HH24:MI:SS') AS CAS_DATVYR,
          TO_CHAR(MT.DATZMENY,'HH24:MI:SS') AS CAS_DATZMENY,
          MT.LIDENT,  DECODE( A11.ID_SSSLOGIN,NULL,MT.IDENT,A11.JMENO)AS LIDENT_JMENO,
          MT.DATZMENY,
          MT.LIDENT_ZMENA, A12.JMENO AS LIDENT_ZMENA_JMENO,
          MT.CVZNIKRADK , MT.ID_ASPRAVCE ,
          MT.HINDEX ,MT.REVIZ_PROH , MT.TEXTREVIZE,
          MT.DATREVIZE , MT.UCEDOKLAD ,
          MT.DOPOCROK , MT.PERIODA ,
          MT.VYSLED_REV , MT.ZAVADA_ODSTR,
          MT.STAV_REVIZE  ,A1.J1_NAZEV AS DRUREV ,
          A2.NAZEV AS SPRAVCE ,  A4.NAJMENO AS NAZEV_DL ,
          A5.NAZEV_REVIZE AS NAZEV_REVIZE_NAD , MT.DEFARAJ,
          A2.NAZEV AS NAZSPRAVCE ,
          A6.NAZEV AS NAZPROVOZNA,
          ADD_MONTHS(MT.DATREVIZE,MT.PERIODA) AS DATUM_ZIVOTNOSTI1 ,
          OBPREVIZE_DATUM_ZIVOTNOSTI( MT.ID_OBPREVIZE ) AS DATUM_ZIVOTNOSTI ,
          MT.ID_APROVOZNA , A7.NAJMENO AS TECHNIK ,
          A9.ID_SEGMENT, A1.ID_SKUP_CISEL,
          A10.AKOD_OBJEKT AS AKOD_OBJEKT,
          A10.AMISTO AS AMISTO,
          A10.AULICE AS AULICE,
          A10.ACISORI AS ACISORI,
          A10.ACISPOP AS ACISPOP,
          A10.AZNAKCISORI AS AZNAKCISORI,
          A10.ANAZEV_VLAST AS ANAZEV_VLAST,
          0 as POCDEN,
          0 as POCMES,
          0 as POCROK,
          DECODE( A10.DEFARAJ_STR ,NULL , ',1,' ,A10.DEFARAJ_STR) AS DEFARAJ_STR ,
         ( select j1_nazev from cisujedn B1, obpvlast b2, ssshledej_a b3
           where B1.id_cisujedn=b2.id_cisujedn
           and b2.id_vlastnik = b3.id_vlastobj
           and b3.typ='S' and B3.id_segment=A9.id_segment )  as CISUJEDN,A9.ID_PRVKU,
          A8.CHYBA_ODSTRANENI_DO AS CHYBA_ODSTRANENI_DO_POL , A8.ZAVADA_ODSTR AS ZAVADA_ODSTR_POL,
          A8.DAT_ODSTRANENI AS DAT_ODSTRANENI_POL , A8.VYSLED_REV AS VYSLED_REV_POL
          FROM OBPREVIZE MT , CISDRUREV A1 ,
                UDRSPRVC A2 , CLEOSOBY A4,
                OBPREVIZE A5 , UDRPROVO A6 ,
                CLEOSOBY A7 , OBPVREVLOK A8,
           V_MAXLOKREVIZE A9 ,SSSHLEDEJ_A A10,
           SSSLOGIN A11, SSSLOGIN A12
                 WHERE MT.ID_CISDRUREV  = A1.ID_CISDRUREV(+)
               AND  MT.ID_ASPRAVCE = A2.ID_ASPRAVCE(+)
               AND MT.ID_CCLE_ODB = A4.ID_CCLE(+)
               AND MT.ID_OBPREVIZE_A = A5.ID_OBPREVIZE_A(+)
               AND MT.ID_APROVOZNA = A6.ID_APROVOZNA(+)
               AND MT.ID_CCLE = A7.ID_CCLE(+)
               AND MT.ID_OBPREVIZE = A9.ID_OBPREVIZE(+)
               AND ( A9.ID_SEGMENT= A10.ID_SEGMENT(+)
               AND ( (A10.TYP = 'S') OR (A10.TYP IS NULL )))
               AND MT.LIDENT= A11.ID_SSSLOGIN(+)
               AND MT.LIDENT_ZMENA= A12.ID_SSSLOGIN(+)
               AND A9.ID_OBPVREVLOK=A8.ID_OBPVREVLOK(+)
</pre>

Ora2pg
<pre>
CREATE OR REPLACE VIEW v_obprevize (id_obprevize, id_cisdrurev, id_spravce, id_obprevize_a, id_osob, id_par, nazev_revize, platnost_od, platnost_do, cislo_revize, ident, poznamka, pocet, vych_period, rev_technik, nezpristup, dat_odstrchyby, naklad_revize, naklad_chyba, pocet_fsr, pocet_fsz, obj_sml, dat_prevzeti, popis_rev, datvyr, id_obphlaobj, id_udrsprsml, pocet_polozek, id_ccle, id_ccle_odb, cas_datvyr, cas_datzmeny, lident, lident_jmeno, datzmeny, lident_zmena, lident_zmena_jmeno, cvznikradk, id_asprav
          MT.ID_SPRAVCE , MT.ID_OBPREVIZE_A ,
          MT.ID_OSOB , MT.ID_PAR ,  MT.NAZEV_REVIZE ,
          MT.PLATNOST_OD ,MT.PLATNOST_DO ,
          MT.CISLO_REVIZE,
          MT.IDENT , MT.POZNAMKA , MT.POCET ,
          MT.VYCH_PERIOD, MT.REV_TECHNIK, MT.NEZPRISTUP,
          MT.DAT_ODSTRCHYBY,
          OBPREVIZE_NAKLAD(MT.ID_OBPREVIZE,'REVIZE') AS NAKLAD_REVIZE,
          OBPREVIZE_NAKLAD(MT.ID_OBPREVIZE,'ZAVADA') AS NAKLAD_CHYBA,
          (select count(*)  FROM ucevfakrev B1
                 where B1.id_obprevize=MT.ID_Obprevize and
                   B1.Platnost_do='01.01.4000' and
                   B1.nak_revchyb='R') AS POCET_FSR,
          (select count(*) from ucevfakrev B1
                 where B1.id_obprevize=MT.ID_Obprevize and
                   B1.Platnost_do='01.01.4000' and
                   B1.nak_revchyb='Z') AS POCET_FSZ,
          MT.OBJ_SML, MT.DAT_PREVZETI, MT.POPIS_REV,
          MT.DATVYR ,MT.ID_OBPHLAOBJ,MT.ID_UDRSPRSML,
         ( SELECT COUNT(*) FROM OBPVREVLOK B1
             WHERE B1.ID_OBPREVIZE = MT.ID_OBPREVIZE )  AS POCET_POLOZEK,
          MT.ID_CCLE, MT.ID_CCLE_ODB,
          TO_CHAR(MT.DATVYR,'HH24:MI:SS') AS CAS_DATVYR,
          TO_CHAR(MT.DATZMENY,'HH24:MI:SS') AS CAS_DATZMENY,
          MT.LIDENT,  CASE WHEN  A11.ID_SSSLOGIN IS NULL THEN MT.IDENT  ELSE A11.JMENO END LIDENT_JMENO,
          MT.DATZMENY,
          MT.LIDENT_ZMENA, A12.JMENO AS LIDENT_ZMENA_JMENO,
          MT.CVZNIKRADK , MT.ID_ASPRAVCE ,
          MT.HINDEX ,MT.REVIZ_PROH , MT.TEXTREVIZE,
          MT.DATREVIZE , MT.UCEDOKLAD ,
          MT.DOPOCROK , MT.PERIODA ,
          MT.VYSLED_REV , MT.ZAVADA_ODSTR,
          MT.STAV_REVIZE  ,A1.J1_NAZEV AS DRUREV ,
          A2.NAZEV AS SPRAVCE ,  A4.NAJMENO AS NAZEV_DL ,
          A5.NAZEV_REVIZE AS NAZEV_REVIZE_NAD , MT.DEFARAJ,
          A2.NAZEV AS NAZSPRAVCE ,
          A6.NAZEV AS NAZPROVOZNA,
          ADD_MONTHS(MT.DATREVIZE,MT.PERIODA) AS DATUM_ZIVOTNOSTI1 ,
          OBPREVIZE_DATUM_ZIVOTNOSTI( MT.ID_OBPREVIZE ) AS DATUM_ZIVOTNOSTI ,
          MT.ID_APROVOZNA , A7.NAJMENO AS TECHNIK ,
          A9.ID_SEGMENT, A1.ID_SKUP_CISEL,
          A10.AKOD_OBJEKT AS AKOD_OBJEKT,
          A10.AMISTO AS AMISTO,
          A10.AULICE AS AULICE,
          A10.ACISORI AS ACISORI,
          A10.ACISPOP AS ACISPOP,
          A10.AZNAKCISORI AS AZNAKCISORI,
          A10.ANAZEV_VLAST AS ANAZEV_VLAST,
          0 as POCDEN,
          0 as POCMES,
          0 as POCROK,
          CASE WHEN  A10.DEFARAJ_STR  IS NULL  THEN  ',1,'   ELSE A10.DEFARAJ_STR END DEFARAJ_STR ,
         ( select j1_nazev from cisujedn B1, obpvlast b2, ssshledej_a b3
           where B1.id_cisujedn=b2.id_cisujedn
           and b2.id_vlastnik = b3.id_vlastobj
           and b3.typ='S' and B3.id_segment=A9.id_segment )  as CISUJEDN,A9.ID_PRVKU,
          A8.CHYBA_ODSTRANENI_DO AS CHYBA_ODSTRANENI_DO_POL , A8.ZAVADA_ODSTR AS ZAVADA_ODSTR_POL,
          A8.DAT_ODSTRANENI AS DAT_ODSTRANENI_POL , A8.VYSLED_REV AS VYSLED_REV_POL
          FROM ssshledej_a a10, obprevize mt
LEFT OUTER JOIN cisdrurev a1 ON (MT.ID_CISDRUREV = A1.ID_CISDRUREV)
LEFT OUTER JOIN udrsprvc a2 ON (MT.ID_ASPRAVCE = A2.ID_ASPRAVCE)
LEFT OUTER JOIN cleosoby a4 ON (MT.ID_CCLE_ODB = A4.ID_CCLE)
LEFT OUTER JOIN obprevize a5 ON (MT.ID_OBPREVIZE_A = A5.ID_OBPREVIZE_A)
LEFT OUTER JOIN udrprovo a6 ON (MT.ID_APROVOZNA = A6.ID_APROVOZNA)
LEFT OUTER JOIN cleosoby a7 ON (MT.ID_CCLE = A7.ID_CCLE)
LEFT OUTER JOIN v_maxlokrevize a9 ON (MT.ID_OBPREVIZE = A9.ID_OBPREVIZE)
LEFT OUTER JOIN ssslogin a11 ON (MT.LIDENT = A11.ID_SSSLOGIN)
LEFT OUTER JOIN ssslogin a12 ON (MT.LIDENT_ZMENA = A12.ID_SSSLOGIN)
LEFT OUTER JOIN obpvrevlok a8 ON (A9.ID_OBPVREVLOK = A8.ID_OBPVREVLOK)
WHERE (  AND ( (A10.TYP = 'S') OR (A10.TYP IS NULL )) );
</pre>

**Comment by darold** [comment]
Commit 35f7097 might fix this issue and remove extra parenthesis.

**Comment by okbob** [comment]
it is fixed
