### ISSUE TITLE
Derived table is pasted two times

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#316]
Oracle:
<pre>
CREATE OR REPLACE VIEW IDES_LADENI_JMMAJ.V_NAJUPOMCEL_AKT AS
SELECT 
  A2.ID_NAJUPOMCEL AS ID_NAJUPOMCEL_PK,
  A2.ID_NAJUPOMCEL_A AS ID_NAJUPOMCEL,
  MT.ID_NAJVZTAH, MT.ID_ASPRAVCE,
  MT.DEFARAJ,MT.ID_VLASTOBJ,
  MT.HLAVNI, MT.AKOD_OBJEKT, MT.AKOD_SEGMENT,
  MT.AKOD_BUDOVY, MT.AKOD_PROSTOR, MT.AZNAKPROSTOR,
  MT.ATYP_PROSTORU, MT.AKOD_MISTNOST, MT.AZNAKMIST,
  MT.AKOD_TYPMSTN, MT.ANAZEV_PRVKU, MT.AKOD_PRVKU,
  MT.ASKUPINA_PRVKU, MT.ACIS_VYROBNI, MT.APARCELA,
  MT.AMISTO, MT.AULICE, MT.ACISORI,MT.ACISPOP,
  MT.AZNAKCISORI, MT.ABYT_NEBYT,
  MT.ULICE, MT.NAJMENO, A2.ID_CISPREDVZT,
  MT.ID_ADR,
  A2.TYP,
  A2.ID_DOBAPLAT, A2.ID_CTYPPRED,
  A2.ID_CISDRUUPO,A2.ID_CISDRUZAS,
  A2.ID_CISZPUSUHRA,A2.ID_CODDNAJVZT,
  A2.ID_POLONAJ, A2.ID_MENA, A2.ID_DPLA, A2.ID_DRUPRE, A2.ID_PAR,
  A2.ID_NAJUPOMCEL_A,
  A2.ID_NAJVUPOUCT,A2.TYPUPDH,A2.TYPPARA, A2.STAV_UPOM,A2.CISLO_UPOM,
  A2.PLATNOST_OD,
  A2.PLATNOST_DO,
  A2.IDENT,A2.POZN,A2.VARSYMBOL,A2.SPESYMBOL,
  A2.CASTKACEL,
  A2.CISLOJEDNACI,A2.DATFIRSTSPL,A2.SPLATNOST,A2.DRUHUPOM,
  A2.CISLOPOST,A2.POCET_CHYB,
  A2.DLUVYNOS,A2.DLUSLUZBY,A2.DLUPEN,
  A2.VYPPEN,A2.PNS,
  A2.NAKUPO,A2.DATZAS,
  A2.DATDORU,A2.ROZPADPOL,A2.VYP_KDATU,
  A2.DATVYR,  DECODE( A22.ID_SSSLOGIN,NULL,A2.IDENT,A22.JMENO)AS LIDENT_JMENO,
  A2.DATZMENY,
  TO_CHAR(A2.DATVYR,'HH24:MI:SS') AS CAS_DATVYR,
  TO_CHAR(A2.DATZMENY,'HH24:MI:SS') AS CAS_DATZMENY,  
  A23.JMENO AS LIDENT_ZMENA_JMENO,  
  A2.LIDENT, A2.LIDENT_ZMENA, 
  A2.ID_VLASTNIK, A2.NAZEV_VLAST,
  A2.ID_VYP_KDATU_POM,
  A8.J1_NAZEV AS ODDELENI,
  A3.J1_NAZEV AS TYP_PREDPISU, A4.J1_NAZEV AS DOBA_PLATBY,
  A5.J1_NAZEV AS TYP_DRUH_PLATBY, A6.J1_NAZEV AS MENA,
  A7.J1_NAZEV AS DRUH_PREDPISU, A9.J1_NAZEV AS DRUHUPO,
  A9.KOD_CISDRUUPO,
  A10.J1_NAZEV AS DRUZAS, A11.J1_NAZEV AS ZPUSUHRA,
  A2.OBDOBI_OD,A2.OBDOBI_DO,
  A2.PREDEPSANO, A2.CASTKA_UPOM,A2.CASTKAZAPL,
  A2.POCUPO, A2.ID_UPOM_UPOM, A2.KROK_MIS,
  MT.NAZSPRAVCE, MT.NAZPROVOZNA, MT.ID_APROVOZNA,
  A13.NAJMENO AS CLEVLAST,
  A9.GRUPPA AS TYP_UPO, A2.ID_CCLE_VLAST,
  MT.DEFARAJ_STR, A14.J1_NAZEV AS CNAJPEN,
  A2.NEROZ_CASTKA,A2.PREDPIS_PEN,A2.VYPPEN_PREDPIS,
  A2.ID_SKUP_CISEL, A2.ID_NAJPROS,A2.ID_SKUTPRS,
  A15.KROK_MIS AS DEF_KROK_MIS, 
  MT.ID_CCLE, A2.VRAT_CASTKA_DALSI_OBDOBI,  
  ( SELECT SUM(EZAPL_AKT)
    FROM V_NAJUPOMPRE B1
    WHERE A2.ID_NAJUPOMCEL = B1.ID_NAJUPOMCEL_PK
    AND B1.NEPOCITAT = 'N' 
  ) AS EZAPL_AKT,
  ( SELECT DECODE( SUM( B3.EROZ_CASTKA ), NULL, 0, SUM( B3.EROZ_CASTKA ))
    FROM NAJVUPOSPL B1, NAJDATSPLT B2, NAJVPLAPRE B3, CISDRPRE B4
    WHERE A2.ID_NAJUPOMCEL = B1.ID_NAJUPOMCEL
    AND B1.ID_NAJDATSPLT = B2.ID_NAJDATSPLT
    AND B2.ID_NAJDATSPLT = B3.ID_NAJDATSPLT
    AND B2.STRP IS NULL
    AND B3.DAT_STORNA IS NULL
    AND B2.ID_DRUPRE = B4.ID_DRUPRE
    AND TRIM(KOD_DRUPRE) = 'P' 
  ) AS EZAPL_PEN,
  A15.NAZEV AS NAZEV_INDEX, A2.ID_NAJUPOMCEL_INDEX,
  A2.BEZ_EVIDENCE,A16.J1_NAZEV AS SKUTPRS,
  A17.J1_NAZEV AS CISUJEDN,A18.J1_NAZEV AS CISPREDVZT,
  A19.VARS,A2.VRAT_CASTKA,A2.PAR711_2B,  
  ( SELECT  SUM(DECODE( COUNT(*), 0, 0, 1 ))
    FROM NAJUPOMPRE B1
    WHERE B1.ID_NAJUPOMCEL = A2.ID_NAJUPOMCEL
    AND B1.CASTKAZAPL = 0
    AND B1.CASTKAPRED > 0
    GROUP BY B1.ID_DRUPRE, B1.ROK, B1.MESIC ) AS POC_NEZAPL,
    A20.ID_KOLURC, A21.J1_NAZEV AS NAZEV_KOLUR,
    A2.VYPPEN_UCE_OLD, A2.ZAPL_PENALE,A2.PENALE_ODPIS,
    A2.GEN_PREDPIS,
  ( SELECT SUM(CASTKA)
    FROM NAJVUPOPLA B1
    WHERE A2.ID_NAJUPOMCEL =  B1.ID_NAJUPOMCEL 
    AND B1.ID_NAJDATSPLT IS NOT NULL 
  ) AS PEN_PREDEPSANO,
  ( SELECT SUM(CASTKA)
    FROM NAJVUPOPLA B1
    WHERE A2.ID_NAJUPOMCEL =  B1.ID_NAJUPOMCEL 
    AND B1.ID_NAJVPLAPRE IS NOT NULL 
  ) AS PEN_ZAPLACENO,
  A2.PREV_VYP_KDATU
FROM 
  SSSHLEDEJ_A MT, NAJVUPOLOK A1, 
  (
    SELECT PT.*,
      LAG(VYP_KDATU) OVER (PARTITION BY ID_NAJUPOMCEL_A, ID_NAJVZTAH ORDER BY VYP_KDATU) AS PREV_VYP_KDATU,  
      ROW_NUMBER() OVER (PARTITION BY ID_NAJUPOMCEL_A, ID_NAJVZTAH ORDER BY VYP_KDATU DESC) AS RN 
    FROM NAJUPOMCEL PT
  ) A2,
  CTYPPRED A3, CISDOPLA A4, CISDPLAT A5,
  CISMENA A6, CISDRPRE A7,  CODDNAJVZT A8,
  CISDRUUPO A9, CISDRUZAS A10, CISZPUSUHR A11,
  NAJVUPOUCT A12, CLEOSOBY A13, CNAJPEN A14,
  NAJUPOMCEL A15,CISSTYPR A16,CISUJEDN A17,
  CISPREDVZT A18,NAJUDAJE A19,
  OBPPRSTR A20, CISKOLUR A21,
  SSSLOGIN A22, SSSLOGIN A23  
WHERE MT.TYP = 'N' AND MT.HLAVNI = 'H' 
AND A2.RN < 2
AND MT.ID_NAJVZTAH = A1.ID_NAJVZTAH  
AND A1.ID_NAJUPOMCEL = A2.ID_NAJUPOMCEL 
AND A2.ID_CODDNAJVZT = A8.ID_CODDNAJVZT(+) 
AND A2.ID_CTYPPRED = A3.ID_CTYPPRED(+) 
AND A2.ID_DOBAPLAT = A4.ID_DOBAPLAT(+) 
AND A2.ID_DPLA = A5.ID_DPLA(+) 
AND A2.ID_MENA = A6.ID_MENA(+) 
AND A2.ID_DRUPRE = A7.ID_DRUPRE(+) 
AND A2.ID_CISDRUUPO = A9.ID_CISDRUUPO(+) 
AND A2.ID_CISDRUZAS = A10.ID_CISDRUZAS(+) 
AND A2.ID_CISZPUSUHRA = A11.ID_CISZPUSUHRA(+) 
AND A2.ID_NAJVUPOUCT = A12.ID_NAJVUPOUCT(+) 
AND A2.ID_CCLE_VLAST = A13.ID_CCLE(+) 
AND A2.ID_CNAJPEN = A14.ID_CNAJPEN(+) 
AND A2.ID_NAJUPOMCEL_A = A15.ID_NAJUPOMCEL(+) 
AND A2.ID_SKUTPRS = A16.ID_SKUTPRS(+) 
AND A2.ID_CISUJEDN = A17.ID_CISUJEDN(+) 
AND A2.ID_CISPREDVZT = A18.ID_CISPREDVZT(+) 
AND MT.ID_NAJVZTAH = A19.ID_NAJVZTAH(+) 
AND MT.ID_PROSTOR  =A20.ID_PROSTOR(+) 
AND A20.ID_KOLURC = A21.ID_KOLURC(+) 
AND A19.PLATNOST_DO = '01.01.4000'
AND A2.LIDENT = A22.ID_SSSLOGIN(+)
AND A2.LIDENT_ZMENA = A23.ID_SSSLOGIN(+)
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE VIEW v_najupomcel_akt (id_najupomcel_pk, id_najupomcel, id_najvztah, id_aspravce, defaraj, id_vlastobj, hlavni, akod_objekt, akod_segment, akod_budovy, akod_prostor, aznakprostor, atyp_prostoru, akod_mistnost, aznakmist, akod_typmstn, anazev_prvku, akod_prvku, askupina_prvku,
  A2.ID_NAJUPOMCEL AS ID_NAJUPOMCEL_PK,
  A2.ID_NAJUPOMCEL_A AS ID_NAJUPOMCEL,
  MT.ID_NAJVZTAH, MT.ID_ASPRAVCE,
  MT.DEFARAJ,MT.ID_VLASTOBJ,
  MT.HLAVNI, MT.AKOD_OBJEKT, MT.AKOD_SEGMENT,
  MT.AKOD_BUDOVY, MT.AKOD_PROSTOR, MT.AZNAKPROSTOR,
  MT.ATYP_PROSTORU, MT.AKOD_MISTNOST, MT.AZNAKMIST,
  MT.AKOD_TYPMSTN, MT.ANAZEV_PRVKU, MT.AKOD_PRVKU,
  MT.ASKUPINA_PRVKU, MT.ACIS_VYROBNI, MT.APARCELA,
  MT.AMISTO, MT.AULICE, MT.ACISORI,MT.ACISPOP,
  MT.AZNAKCISORI, MT.ABYT_NEBYT,
  MT.ULICE, MT.NAJMENO, A2.ID_CISPREDVZT,
  MT.ID_ADR,
  A2.TYP,
  A2.ID_DOBAPLAT, A2.ID_CTYPPRED,
  A2.ID_CISDRUUPO,A2.ID_CISDRUZAS,
  A2.ID_CISZPUSUHRA,A2.ID_CODDNAJVZT,
  A2.ID_POLONAJ, A2.ID_MENA, A2.ID_DPLA, A2.ID_DRUPRE, A2.ID_PAR,
  A2.ID_NAJUPOMCEL_A,
  A2.ID_NAJVUPOUCT,A2.TYPUPDH,A2.TYPPARA, A2.STAV_UPOM,A2.CISLO_UPOM,
  A2.PLATNOST_OD,
  A2.PLATNOST_DO,
  A2.IDENT,A2.POZN,A2.VARSYMBOL,A2.SPESYMBOL,
  A2.CASTKACEL,
  A2.CISLOJEDNACI,A2.DATFIRSTSPL,A2.SPLATNOST,A2.DRUHUPOM,
  A2.CISLOPOST,A2.POCET_CHYB,
  A2.DLUVYNOS,A2.DLUSLUZBY,A2.DLUPEN,
  A2.VYPPEN,A2.PNS,
  A2.NAKUPO,A2.DATZAS,
  A2.DATDORU,A2.ROZPADPOL,A2.VYP_KDATU,
  A2.DATVYR,  CASE WHEN  A22.ID_SSSLOGIN IS NULL THEN A2.IDENT  ELSE A22.JMENO END LIDENT_JMENO,
  A2.DATZMENY,
  TO_CHAR(A2.DATVYR,'HH24:MI:SS') AS CAS_DATVYR,
  TO_CHAR(A2.DATZMENY,'HH24:MI:SS') AS CAS_DATZMENY,
  A23.JMENO AS LIDENT_ZMENA_JMENO,
  A2.LIDENT, A2.LIDENT_ZMENA,
  A2.ID_VLASTNIK, A2.NAZEV_VLAST,
  A2.ID_VYP_KDATU_POM,
  A8.J1_NAZEV AS ODDELENI,
  A3.J1_NAZEV AS TYP_PREDPISU, A4.J1_NAZEV AS DOBA_PLATBY,
  A5.J1_NAZEV AS TYP_DRUH_PLATBY, A6.J1_NAZEV AS MENA,
  A7.J1_NAZEV AS DRUH_PREDPISU, A9.J1_NAZEV AS DRUHUPO,
  A9.KOD_CISDRUUPO,
  A10.J1_NAZEV AS DRUZAS, A11.J1_NAZEV AS ZPUSUHRA,
  A2.OBDOBI_OD,A2.OBDOBI_DO,
  A2.PREDEPSANO, A2.CASTKA_UPOM,A2.CASTKAZAPL,
  A2.POCUPO, A2.ID_UPOM_UPOM, A2.KROK_MIS,
  MT.NAZSPRAVCE, MT.NAZPROVOZNA, MT.ID_APROVOZNA,
  A13.NAJMENO AS CLEVLAST,
  A9.GRUPPA AS TYP_UPO, A2.ID_CCLE_VLAST,
  MT.DEFARAJ_STR, A14.J1_NAZEV AS CNAJPEN,
  A2.NEROZ_CASTKA,A2.PREDPIS_PEN,A2.VYPPEN_PREDPIS,
  A2.ID_SKUP_CISEL, A2.ID_NAJPROS,A2.ID_SKUTPRS,
  A15.KROK_MIS AS DEF_KROK_MIS,
  MT.ID_CCLE, A2.VRAT_CASTKA_DALSI_OBDOBI,
  ( SELECT SUM(EZAPL_AKT)
     FROM V_NAJUPOMPRE B1
    WHERE A2.ID_NAJUPOMCEL = B1.ID_NAJUPOMCEL_PK
    AND B1.NEPOCITAT = 'N'
  ) AS EZAPL_AKT,
  ( SELECT CASE WHEN  SUM( B3.EROZ_CASTKA ) IS NULL THEN  0  ELSE  SUM( B3.EROZ_CASTKA ) END
    FROM NAJVUPOSPL B1, NAJDATSPLT B2, NAJVPLAPRE B3, CISDRPRE B4
    WHERE A2.ID_NAJUPOMCEL = B1.ID_NAJUPOMCEL
    AND B1.ID_NAJDATSPLT = B2.ID_NAJDATSPLT
    AND B2.ID_NAJDATSPLT = B3.ID_NAJDATSPLT
    AND B2.STRP IS NULL
    AND B3.DAT_STORNA IS NULL
    AND B2.ID_DRUPRE = B4.ID_DRUPRE
    AND btrim(KOD_DRUPRE) = 'P'
  ) AS EZAPL_PEN,
  A15.NAZEV AS NAZEV_INDEX, A2.ID_NAJUPOMCEL_INDEX,
  A2.BEZ_EVIDENCE,A16.J1_NAZEV AS SKUTPRS,
  A17.J1_NAZEV AS CISUJEDN,A18.J1_NAZEV AS CISPREDVZT,
  A19.VARS,A2.VRAT_CASTKA,A2.PAR711_2B,
   /*
  ( SELECT  SUM(DECODE( COUNT(*), 0, 0, 1 ))
    FROM NAJUPOMPRE B1
    WHERE B1.ID_NAJUPOMCEL = A2.ID_NAJUPOMCEL
    AND B1.CASTKAZAPL = 0
    AND B1.CASTKAPRED > 0
    GROUP BY B1.ID_DRUPRE, B1.ROK, B1.MESIC ) AS POC_NEZAPL,
    */
    CASE WHEN btrim(A9.KOD_CISDRUUPO) = 'UCEDLUH' THEN 0 ELSE GET_POCNEZAPL_UPOMPRE(A2.ID_NAJUPOMCEL ) END POC_NEZAPL,
    A20.ID_KOLURC, A21.J1_NAZEV AS NAZEV_KOLUR,
    A2.VYPPEN_UCE_OLD, A2.ZAPL_PENALE,A2.PENALE_ODPIS,
    A2.GEN_PREDPIS,
  ( SELECT SUM(CASTKA)
    FROM NAJVUPOPLA B1
    WHERE A2.ID_NAJUPOMCEL =  B1.ID_NAJUPOMCEL
    AND B1.ID_NAJDATSPLT IS NOT NULL
  ) AS PEN_PREDEPSANO,
  ( SELECT SUM(CASTKA)
    FROM NAJVUPOPLA B1
    WHERE A2.ID_NAJUPOMCEL =  B1.ID_NAJUPOMCEL
    AND B1.ID_NAJVPLAPRE IS NOT NULL
  ) AS PEN_ZAPLACENO,
  A2.PREV_VYP_KDATU
FROM najvupolok a1, (
    SELECT PT.*,
      LAG(VYP_KDATU) OVER (PARTITION BY ID_NAJUPOMCEL_A, ID_NAJVZTAH ORDER BY VYP_KDATU) AS PREV_VYP_KDATU,
      ROW_NUMBER() OVER (PARTITION BY ID_NAJUPOMCEL_A, ID_NAJVZTAH ORDER BY VYP_KDATU DESC) AS RN
    FROM NAJUPOMCEL PT
  ) a2, ssshledej_a mt
LEFT OUTER JOIN najudaje a19 ON (MT.ID_NAJVZTAH = A19.ID_NAJVZTAH)
LEFT OUTER JOIN obpprstr a20 ON (MT.ID_PROSTOR = A20.ID_PROSTOR)
LEFT OUTER JOIN ciskolur a21 ON (A20.ID_KOLURC = A21.ID_KOLURC)
, (
    SELECT PT.*,
      LAG(VYP_KDATU) OVER (PARTITION BY ID_NAJUPOMCEL_A, ID_NAJVZTAH ORDER BY VYP_KDATU) AS PREV_VYP_KDATU,
      ROW_NUMBER() OVER (PARTITION BY ID_NAJUPOMCEL_A, ID_NAJVZTAH ORDER BY VYP_KDATU DESC) AS RN
    FROM NAJUPOMCEL PT
  ) a2
LEFT OUTER JOIN coddnajvzt a8 ON (A2.ID_CODDNAJVZT = A8.ID_CODDNAJVZT)
LEFT OUTER JOIN ctyppred a3 ON (A2.ID_CTYPPRED = A3.ID_CTYPPRED)
LEFT OUTER JOIN cisdopla a4 ON (A2.ID_DOBAPLAT = A4.ID_DOBAPLAT)
LEFT OUTER JOIN cisdplat a5 ON (A2.ID_DPLA = A5.ID_DPLA)
LEFT OUTER JOIN cismena a6 ON (A2.ID_MENA = A6.ID_MENA)
LEFT OUTER JOIN cisdrpre a7 ON (A2.ID_DRUPRE = A7.ID_DRUPRE)
LEFT OUTER JOIN cisdruupo a9 ON (A2.ID_CISDRUUPO = A9.ID_CISDRUUPO)
LEFT OUTER JOIN cisdruzas a10 ON (A2.ID_CISDRUZAS = A10.ID_CISDRUZAS)
LEFT OUTER JOIN ciszpusuhr a11 ON (A2.ID_CISZPUSUHRA = A11.ID_CISZPUSUHRA)
LEFT OUTER JOIN najvupouct a12 ON (A2.ID_NAJVUPOUCT = A12.ID_NAJVUPOUCT)
LEFT OUTER JOIN cleosoby a13 ON (A2.ID_CCLE_VLAST = A13.ID_CCLE)
LEFT OUTER JOIN cnajpen a14 ON (A2.ID_CNAJPEN = A14.ID_CNAJPEN)
LEFT OUTER JOIN najupomcel a15 ON (A2.ID_NAJUPOMCEL_A = A15.ID_NAJUPOMCEL)
LEFT OUTER JOIN cisstypr a16 ON (A2.ID_SKUTPRS = A16.ID_SKUTPRS)
LEFT OUTER JOIN cisujedn a17 ON (A2.ID_CISUJEDN = A17.ID_CISUJEDN)
LEFT OUTER JOIN cispredvzt a18 ON (A2.ID_CISPREDVZT = A18.ID_CISPREDVZT)
LEFT OUTER JOIN ssslogin a22 ON (A2.LIDENT = A22.ID_SSSLOGIN)
LEFT OUTER JOIN ssslogin a23 ON (A2.LIDENT_ZMENA = A23.ID_SSSLOGIN)
WHERE MT.TYP = 'N' AND MT.HLAVNI = 'H' AND A2.RN < 2 AND MT.ID_NAJVZTAH = A1.ID_NAJVZTAH AND A1.ID_NAJUPOMCEL = A2.ID_NAJUPOMCEL                    AND A19.PLATNOST_DO = '01.01.4000';
</pre>

Error:
<pre>
ERROR:  table name "a2" specified more than once
</pre>

**Comment by darold** [comment]
Commit 3022fae might solves this issue and may not break previous fixes but as I can not run my regression test before the end of the week I can not certified it.

**Comment by okbob** [comment]
it is fixed, thank you

**Comment by darold** [comment]
Good news,  regression tests passed successfully as well as with the new commits on CONNECT BY translation. Nothing might be broken.
