### ISSUE TITLE
some double semicolons in translated plpgsql code

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#317]
Oracle:
<pre>
CREATE OR REPLACE function IDES_JMMAJ.DEFARAJ_UPRAV( mDefarajStr IN VARCHAR2  ) 
 return VARCHAR2 is
 mDefarajStr_result VARCHAR2(4000); 
begin
  
  mDefarajStr_result := SUBSTR( mDefarajStr , 2 , LENGTH( mDefarajStr ) - 1 );   
  return(mDefarajStr_result);
end ;
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE FUNCTION defaraj_uprav ( mDefarajStr text ) RETURNS varchar AS $body$
DECLARE

 mDefarajStr_result varchar(4000);;
BEGIN

  mDefarajStr_result := SUBSTR( mDefarajStr , 2 , LENGTH( mDefarajStr ) - 1 );
  return(mDefarajStr_result);
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION defaraj_uprav ( mDefarajStr text ) FROM PUBLIC;
</pre>

**Comment by okbob** [comment]
Another example on code end:

Oracle:
<pre>
CREATE OR REPLACE function IDES_JMMAJ.GET_DOPLATI_KAUCE_AKT(mID_NAJKAUCE NAJKAUCE.ID_NAJKAUCE%TYPE , mKDATU  IN DATE  ) return NUMBER is
  Result NUMBER;
  mEPREDEPSANO NAJKAUCE.EPREDEPSANO%TYPE;
  mEZAPLACENO NUMBER;
  mPRED_SPLATNOSTI NUMBER;
  mPRIZ_VRACENO NAJKAUCE.PRIZ_VRACENO%TYPE;
begin
  
  /*
  SELECT SUM(EPREDEPSANO) INTO mEPREDEPSANO
     FROM NAJKAUHYB
     WHERE ID_NAJKAUCE = mID_NAJKAUCE  
      AND TYP IN ( 'P' );

  SELECT DECODE( SUM(EPREDEPSANO) , NULL , 0 ,  SUM(EPREDEPSANO) )
    INTO mEZAPLACENO
    FROM NAJKAUHYB
    WHERE ID_NAJKAUCE = mID_NAJKAUCE
      AND TYP IN ( 'Z' , 'K' , 'V' ) ;
 
  SELECT DECODE( SUM(EPREDEPSANO) , NULL , 0 ,  SUM(EPREDEPSANO) )
    INTO mPRED_SPLATNOSTI
    FROM NAJKAUHYB
    WHERE ID_NAJKAUCE = mID_NAJKAUCE
      AND (( TYP = 'K' ) OR (( TYP = 'P' ) AND (EPREDEPSANO > 0)))  
      AND DATUM_SPLATNOSTI > mKDATU ;
   */
   SELECT PRIZ_VRACENO INTO mPRIZ_VRACENO
     FROM NAJKAUCE
     WHERE ID_NAJKAUCE = mID_NAJKAUCE; 
   
   IF mPRIZ_VRACENO IS NULL THEN     
     SELECT  DECODE(SUM(MT.EPREDEPSANO) , NULL , 0 , SUM(MT.EPREDEPSANO)  )  ,
             SUM(( SELECT DECODE( SUM(B1.ROZ_CASTKA) , NULL , 0 ,SUM(B1.ROZ_CASTKA) )
                 FROM NAJVPLAPRE B1
                 WHERE B1.ID_NAJDATSPLT =  A1.ID_NAJDATSPLT
                   AND B1.DAT_STORNA IS NULL ))  INTO mEPREDEPSANO ,  mEZAPLACENO 
         FROM NAJKAUHYB MT , NAJDATSPLT A1
         WHERE MT.ID_NAJKAUCE = mID_NAJKAUCE
           AND MT.TYP = 'P' 
           AND MT.EPREDEPSANO > 0
           AND MT.ID_NAJDATSPLT = A1.ID_NAJDATSPLT
           AND MT.DATUM_SPLATNOSTI < mKDATU
           AND NVL(GET_STRP_NAJDATSPLT(MT.ID_NAJDATSPLT),'N') <> 'S'  ;
      Result := mEPREDEPSANO - mEZAPLACENO ;
   ELSE
     Result := 0;
   END IF;   
  IF Result < 0 THEN
    Result := 0;
  END IF;
      
  return(Result);

end GET_DOPLATI_KAUCE_AKT;
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE FUNCTION get_doplati_kauce_akt (mID_NAJKAUCE NAJKAUCE.ID_NAJKAUCE%TYPE , mKDATU timestamp ) RETURNS bigint AS $body$
DECLARE

  Result bigint;
  mEPREDEPSANO NAJKAUCE.EPREDEPSANO%TYPE;
  mEZAPLACENO bigint;
  mPRED_SPLATNOSTI bigint;
  mPRIZ_VRACENO NAJKAUCE.PRIZ_VRACENO%TYPE;
BEGIN

  /*
  SELECT SUM(EPREDEPSANO) INTO mEPREDEPSANO
     FROM NAJKAUHYB
     WHERE ID_NAJKAUCE = mID_NAJKAUCE
      AND TYP IN ( 'P' );

  SELECT DECODE( SUM(EPREDEPSANO) , NULL , 0 ,  SUM(EPREDEPSANO) )
    INTO mEZAPLACENO
    FROM NAJKAUHYB
    WHERE ID_NAJKAUCE = mID_NAJKAUCE
      AND TYP IN ( 'Z' , 'K' , 'V' ) ;

  SELECT DECODE( SUM(EPREDEPSANO) , NULL , 0 ,  SUM(EPREDEPSANO) )
    INTO mPRED_SPLATNOSTI
    FROM NAJKAUHYB
    WHERE ID_NAJKAUCE = mID_NAJKAUCE
      AND (( TYP = 'K' ) OR (( TYP = 'P' ) AND (EPREDEPSANO > 0)))
      AND DATUM_SPLATNOSTI > mKDATU ;
   */
   SELECT PRIZ_VRACENO INTO mPRIZ_VRACENO
     FROM NAJKAUCE
     WHERE ID_NAJKAUCE = mID_NAJKAUCE;

   IF mPRIZ_VRACENO IS NULL THEN
     SELECT  CASE WHEN SUM(MT.EPREDEPSANO)  IS NULL  THEN  0   ELSE  SUM(MT.EPREDEPSANO)   END   ,
             SUM(( SELECT CASE WHEN  SUM(B1.ROZ_CASTKA)  IS NULL  THEN  0   ELSE SUM(B1.ROZ_CASTKA)  END
                 FROM NAJVPLAPRE B1
                 WHERE B1.ID_NAJDATSPLT =  A1.ID_NAJDATSPLT
                   AND B1.DAT_STORNA IS NULL ))  INTO mEPREDEPSANO ,  mEZAPLACENO
         FROM NAJKAUHYB MT , NAJDATSPLT A1
         WHERE MT.ID_NAJKAUCE = mID_NAJKAUCE
           AND MT.TYP = 'P'
           AND MT.EPREDEPSANO > 0
           AND MT.ID_NAJDATSPLT = A1.ID_NAJDATSPLT
           AND MT.DATUM_SPLATNOSTI < mKDATU
           AND coalesce(GET_STRP_NAJDATSPLT(MT.ID_NAJDATSPLT),'N') <> 'S';
      Result := mEPREDEPSANO - mEZAPLACENO;
   ELSE
     Result := 0;
   END IF;
  IF Result < 0 THEN
    Result := 0;
  END IF;

  return(Result);

END;

;;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
</pre>

**Comment by edelanoe** [comment]
Hello,

This, and your previous one, is identical to issue # 314

Best regards,
E.Delanoë

De : Pavel Stehule [mailto:notifications@github.com]
Envoyé : jeudi 2 mars 2017 11:30
À : darold/ora2pg
Cc : Subscribed
Objet : Re: [darold/ora2pg] some double semicolons in translated plpgsql code (#317)


Another example on code end:

Oracle:

CREATE OR REPLACE function IDES_JMMAJ.GET_DOPLATI_KAUCE_AKT(mID_NAJKAUCE NAJKAUCE.ID_NAJKAUCE%TYPE , mKDATU  IN DATE  ) return NUMBER is

  Result NUMBER;

  mEPREDEPSANO NAJKAUCE.EPREDEPSANO%TYPE;

  mEZAPLACENO NUMBER;

  mPRED_SPLATNOSTI NUMBER;

  mPRIZ_VRACENO NAJKAUCE.PRIZ_VRACENO%TYPE;

begin



  /*

  SELECT SUM(EPREDEPSANO) INTO mEPREDEPSANO

     FROM NAJKAUHYB

     WHERE ID_NAJKAUCE = mID_NAJKAUCE

      AND TYP IN ( 'P' );



  SELECT DECODE( SUM(EPREDEPSANO) , NULL , 0 ,  SUM(EPREDEPSANO) )

    INTO mEZAPLACENO

    FROM NAJKAUHYB

    WHERE ID_NAJKAUCE = mID_NAJKAUCE

      AND TYP IN ( 'Z' , 'K' , 'V' ) ;



  SELECT DECODE( SUM(EPREDEPSANO) , NULL , 0 ,  SUM(EPREDEPSANO) )

    INTO mPRED_SPLATNOSTI

    FROM NAJKAUHYB

    WHERE ID_NAJKAUCE = mID_NAJKAUCE

      AND (( TYP = 'K' ) OR (( TYP = 'P' ) AND (EPREDEPSANO > 0)))

      AND DATUM_SPLATNOSTI > mKDATU ;

   */

   SELECT PRIZ_VRACENO INTO mPRIZ_VRACENO

     FROM NAJKAUCE

     WHERE ID_NAJKAUCE = mID_NAJKAUCE;



   IF mPRIZ_VRACENO IS NULL THEN

     SELECT  DECODE(SUM(MT.EPREDEPSANO) , NULL , 0 , SUM(MT.EPREDEPSANO)  )  ,

             SUM(( SELECT DECODE( SUM(B1.ROZ_CASTKA) , NULL , 0 ,SUM(B1.ROZ_CASTKA) )

                 FROM NAJVPLAPRE B1

                 WHERE B1.ID_NAJDATSPLT =  A1.ID_NAJDATSPLT

                   AND B1.DAT_STORNA IS NULL ))  INTO mEPREDEPSANO ,  mEZAPLACENO

         FROM NAJKAUHYB MT , NAJDATSPLT A1

         WHERE MT.ID_NAJKAUCE = mID_NAJKAUCE

           AND MT.TYP = 'P'

           AND MT.EPREDEPSANO > 0

           AND MT.ID_NAJDATSPLT = A1.ID_NAJDATSPLT

           AND MT.DATUM_SPLATNOSTI < mKDATU

           AND NVL(GET_STRP_NAJDATSPLT(MT.ID_NAJDATSPLT),'N') <> 'S'  ;

      Result := mEPREDEPSANO - mEZAPLACENO ;

   ELSE

     Result := 0;

   END IF;

  IF Result < 0 THEN

    Result := 0;

  END IF;



  return(Result);



end GET_DOPLATI_KAUCE_AKT;

Ora2pg:

CREATE OR REPLACE FUNCTION get_doplati_kauce_akt (mID_NAJKAUCE NAJKAUCE.ID_NAJKAUCE%TYPE , mKDATU timestamp ) RETURNS bigint AS $body$

DECLARE



  Result bigint;

  mEPREDEPSANO NAJKAUCE.EPREDEPSANO%TYPE;

  mEZAPLACENO bigint;

  mPRED_SPLATNOSTI bigint;

  mPRIZ_VRACENO NAJKAUCE.PRIZ_VRACENO%TYPE;

BEGIN



  /*

  SELECT SUM(EPREDEPSANO) INTO mEPREDEPSANO

     FROM NAJKAUHYB

     WHERE ID_NAJKAUCE = mID_NAJKAUCE

      AND TYP IN ( 'P' );



  SELECT DECODE( SUM(EPREDEPSANO) , NULL , 0 ,  SUM(EPREDEPSANO) )

    INTO mEZAPLACENO

    FROM NAJKAUHYB

    WHERE ID_NAJKAUCE = mID_NAJKAUCE

      AND TYP IN ( 'Z' , 'K' , 'V' ) ;



  SELECT DECODE( SUM(EPREDEPSANO) , NULL , 0 ,  SUM(EPREDEPSANO) )

    INTO mPRED_SPLATNOSTI

    FROM NAJKAUHYB

    WHERE ID_NAJKAUCE = mID_NAJKAUCE

      AND (( TYP = 'K' ) OR (( TYP = 'P' ) AND (EPREDEPSANO > 0)))

      AND DATUM_SPLATNOSTI > mKDATU ;

   */

   SELECT PRIZ_VRACENO INTO mPRIZ_VRACENO

     FROM NAJKAUCE

     WHERE ID_NAJKAUCE = mID_NAJKAUCE;



   IF mPRIZ_VRACENO IS NULL THEN

     SELECT  CASE WHEN SUM(MT.EPREDEPSANO)  IS NULL  THEN  0   ELSE  SUM(MT.EPREDEPSANO)   END   ,

             SUM(( SELECT CASE WHEN  SUM(B1.ROZ_CASTKA)  IS NULL  THEN  0   ELSE SUM(B1.ROZ_CASTKA)  END

                 FROM NAJVPLAPRE B1

                 WHERE B1.ID_NAJDATSPLT =  A1.ID_NAJDATSPLT

                   AND B1.DAT_STORNA IS NULL ))  INTO mEPREDEPSANO ,  mEZAPLACENO

         FROM NAJKAUHYB MT , NAJDATSPLT A1

         WHERE MT.ID_NAJKAUCE = mID_NAJKAUCE

           AND MT.TYP = 'P'

           AND MT.EPREDEPSANO > 0

           AND MT.ID_NAJDATSPLT = A1.ID_NAJDATSPLT

           AND MT.DATUM_SPLATNOSTI < mKDATU

           AND coalesce(GET_STRP_NAJDATSPLT(MT.ID_NAJDATSPLT),'N') <> 'S';

      Result := mEPREDEPSANO - mEZAPLACENO;

   ELSE

     Result := 0;

   END IF;

  IF Result < 0 THEN

    Result := 0;

  END IF;



  return(Result);



END;



;;

$body$

LANGUAGE PLPGSQL

SECURITY DEFINER

 STABLE;

**Comment by darold** [comment]
That's right, this last commit 782e6c9 might solves both issues.

**Comment by okbob** [comment]
it is fixed
