### ISSUE TITLE
When declaring implicit cursor: non-cursor for loops are taken

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#318]
Symptom:
in Oracle I have:
              for j in 1..U_LIST.count loop -- a comment
                  if U_LIST(j).date_validity_end <= R.date_validity_begin then
                      v_nb_ech := v_nb_ech + 1;
                  end if;
              end loop;
in Pg function declaration, ora2pg generates : "j RECORD;" which should be "j numeric;" or "j bigint;"

Implicit cursors can be distinguished by their global enclosing brackets "(" and ")".
Explicit cursors are already declared.
"Interval" for loops can be distinguished by "..", which has higher priority than "(" / ")" .
That should cover some more cases...

Best regards and again thanks for your active work :)

**Comment by okbob** [comment]
This is range cycle - the J variable is a index and should be integer, - maybe bigint in this time.

**Comment by edelanoe** [comment]
My suggestion to declare index j as bigint is just a precaution to adapt to most projects, although "integer" is more economic.
I had some more thoughts about this issue: in fact, you have more use cases around the "for X in ... " syntax: (my numbers below try to suggest a regexp priority order)

1) for j in A..B  ### with A and B simple variables (no "(" in the syntax) ==> declare j as bigint or integer
2) for R in (  select  ### with "(" and "select" 
       ==> declare a "R RECORD;" if not already done with "R" of an Oracle record type
3) for j in A(x)..B(y)  ## with A and B functions and x not beginning by /select/i  ==> declare "j bigint;"

Looks consistent ?

**Comment by okbob** [comment]
What I know, these variables are automatic (should not to depend on explicit declaration) and has cycle body scope only. But external declaration should be almost enough. 
The economic depends on later usage - bigint is on 64bit servers effective - but if index is compared with int32 or casted to int32 you lost some time. But real performance difference between int32 and int64 will not be significant in plpgsql.

**Comment by edelanoe** [comment]
That’s it, and declaring these variables out of the cycle scope may have more benefits than drawbacks.
I am not worried about being perfectly “economic” at this point, rather “universal” (knowing that some PostgreSQL built-ins require integers - unfortunately).

Therefore, I let the experienced ora2pg or PostgreSQL developers choose the most appropriate/portable variable type of loop index.

Best regards,
E.Delanoë

De : Pavel Stehule [mailto:notifications@github.com]
Envoyé : lundi 6 mars 2017 10:59
À : darold/ora2pg
Cc : Delanoe Eric; Author
Objet : Re: [darold/ora2pg] When declaring implicit cursor: non-cursor for loops are taken (#318)


What I know, these variables are automatic (should not to depend on explicit declaration) and has cycle body scope only. But external declaration should be almost enough.
The economic depends on later usage - bigint is on 64bit servers effective - but if index is compared with int32 or casted to int32 you lost some time. But real performance difference between int32 and int64 will not be significant in plpgsql.

**Comment by okbob** [comment]
probably int is good enough - it can be changed manually, when it will be required.

**Comment by edelanoe** [comment]
Perfectly ok ☺

Best regards,
E.Delanoë

De : Pavel Stehule [mailto:notifications@github.com]
Envoyé : lundi 6 mars 2017 11:13
À : darold/ora2pg
Cc : Delanoe Eric; Author
Objet : Re: [darold/ora2pg] When declaring implicit cursor: non-cursor for loops are taken (#318)


probably int is good enough - it can be changed manually, when it will be required.

**Comment by darold** [comment]
Commit a87ff7a apply changes discussed in this issue. For example the following Oracle code:
```
CREATE OR REPLACE procedure TEST_INPLICITCURSOR( toogle IN NUMBER )
is
  mMesic NUMBER; 
  mRok NUMBER;
  mDen NUMBER ;
begin
   
   IF toogle = RRRUTIL.NEMENIT_DEN THEN  
     FOR mI IN 1..4 
     LOOP
       BEGIN
         mDatum := TO_DATE( mDen || '.' || mMesic || '.' || mRok , 'DD.MM.YYYY' )  ;     
         EXIT;
       EXCEPTION
         WHEN OTHERS THEN
           mDen := mDen - 1;  
       END ;
     END LOOP;
   ELSE
	 FOR item IN (
	    SELECT last_name, job_id
	    FROM employees
	    WHERE job_id LIKE '%CLERK%'
	    AND manager_id > 120
	    ORDER BY last_name
	  )
	  LOOP
	    DBMS_OUTPUT.PUT_LINE
	      ('Name = ' || item.last_name || ', Job = ' || item.job_id);
	  END LOOP;

      mDatum := TO_DATE( '01.' || mMesic || '.' || mRok , 'DD.MM.YYYY' ) + mKoef ;     
   END IF;
end ;
```

will be exported as plpgsql code:
```
CREATE OR REPLACE FUNCTION test_inplicitcursor ( toogle bigint ) RETURNS VOID AS $body$
DECLARE

  mMesic bigint;
  mRok bigint;
  mDen bigint;
  mI int;
  item RECORD;

BEGIN
   IF toogle = RRRUTIL.NEMENIT_DEN THEN
     FOR mI IN 1..4 
     LOOP
       BEGIN
         mDatum := TO_DATE( mDen || '.' || mMesic || '.' || mRok , 'DD.MM.YYYY' );
         EXIT;
       EXCEPTION
         WHEN OTHERS THEN
           mDen := mDen - 1;
       END;
     END LOOP;
   ELSE
	 FOR item IN (
	    SELECT last_name, job_id
	    FROM employees
	    WHERE job_id LIKE '%CLERK%'
	    AND manager_id > 120
	    ORDER BY last_name
	  )
	  LOOP
	    RAISE NOTICE 'Name = %, Job = %', item.last_name, item.job_id;
	  END LOOP;
      mDatum := TO_DATE( '01.' || mMesic || '.' || mRok , 'DD.MM.YYYY' ) + mKoef;
   END IF;
end;
$body$
LANGUAGE PLPGSQL
;
```

`mI` is declared as int and `item` as RECORD.

**Comment by okbob** [comment]
I am idiot. PostgreSQL don't need a variable in this case (range cursor) - doesn't use it ever. So don't do any declaration.

**Comment by darold** [comment]
Removed in commit b55c822. My bad, I knew that it don't needed to be declared but I was thinking that the variable would be used outside the loop in Oracle code but it is the same behavior I guess, when not declared it can only be used in the loop scope.

**Comment by edelanoe** [comment]
I confirm: in Oracle, an undeclared numeric loop index is in the private loop scope.
… And learnt that it is the same in PostgreSQL.

Best regards,
E.Delanoë

De : Darold [mailto:notifications@github.com]
Envoyé : lundi 6 mars 2017 12:00
À : darold/ora2pg
Cc : Delanoe Eric; Author
Objet : Re: [darold/ora2pg] When declaring implicit cursor: non-cursor for loops are taken (#318)


Removed in commit b55c822<https://github.com/darold/ora2pg/commit/b55c822fabb8bed12cd680a7e7176dcf4701db07>. My bad, I knew that it don't needed to be declared but I was thinking that the variable would be used outside the loop in Oracle code but it is the same behavior I guess, when not declared it can only be used in the loop scope.

**Comment by edelanoe** [comment]
#318 is fixed
