### ISSUE TITLE
Missing right parenthese in function

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#319]
Ora2pg are too hungry

Oracle:
<pre>
CREATE OR REPLACE function IDES_PRAHA22.PARABOKPC_PROUCT(mPROUCT PARABOKPC.Prouct%TYPE)
 return varchar2 is
 mUCET PARABOKPC.Prouct%TYPE;
 Result varchar2(17);
 i NUMBER;
 pocet NUMBER;
 posun NUMBER;
 mZnak CHAR(1);
 mSTAV CHAR(1);
 m1 CHAR(6);
 m2 CHAR(10);
begin
  mUCET :=trim(mPROUCT);
  pocet:=LENGTH(trim(mUCET));
  if mUCET IS NULL THEN
   Result := NULL;
  end if;

  if mUCET is not null then
       mSTAV :=NULL;
       FOR i IN 1..LENGTH(trim(mUCET))
       LOOP
         mZnak := SUBSTR( trim(mUCET) , i,1 );
         if mZnak not in ('0','1','2','3','4','5','6','7','8','9') then
         if mSTAV is null THEN mSTAV :='E'; end if;
         end if;
        END LOOP;

        --- ok ucet - Doplnim pomlcku PREDCISLI-UCET
        if mSTAV is null and LENGTH(trim(mUCET))= 16 then
          m1:= substr(trim(mUCET),1,6);
          m2:= substr(trim(mUCET),7,10);
          result :=m1||'-'||m2;
         end if;
         ---bez pomlcky - doplnit na 16 a rozdelit
        if mSTAV is null and LENGTH(trim(mUCET))< 16 then
          mUCET := LPAD(trim(mUCET),16,'0');
          pocet:=LENGTH(trim(mUCET));
          m1:= substr(trim(mUCET),1,6);
          m2:= substr(trim(mUCET),7,10);
          result :=m1||'-'||m2;
        end if;
         ---problematicky ucet
        if mSTAV ='E' then
          --- 1. krok  nahradit / pomlckou
          mUCET :=replace(mUCET,'/','-');
          mUCET :=replace(mUCET,'\','-');
          mUCET :=replace(mUCET,',','-');
          mUCET :=replace(mUCET,'.','-');

          FOR i IN 1..LENGTH(trim(mUCET))
          LOOP
             mZnak := NULL;
             mZnak := SUBSTR( trim(mUCET) ,LENGTH(trim(mUCET))+1-i,1 );
             if mZnak in ('0','1','2','3','4','5','6','7','8','9') then
               begin
                m2:=TRIM(mZnak)||''||TRIM(m2);
                exception
                 when others THEN
                  raise_application_error( -20038 ,  ' UCET - PODIVNY FORMAT UCTU - ' || mPROUCT ) ;
               end;
             end if;
            if mZnak not in ('0','1','2','3','4','5','6','7','8','9') then
               pocet:=i;
               exit;
             end if;

        END LOOP;

            m2 := LPAD(trim(m2),10,'0');

             ---stanoveni m1 - predcisli max 6 znaku
             begin
             m1 := SUBSTR( trim(mUCET) ,1,LENGTH(trim(mUCET))-pocet );
             exception
             when others THEN

             FOR i IN 1..LENGTH(trim(mUCET))
             LOOP
             mZnak := NULL;
             posun := LENGTH(trim(mUCET))-pocet+1-i;
             mZnak := SUBSTR( trim(mUCET) ,LENGTH(trim(mUCET))-pocet+1-i,1 );
             if mZnak in ('0','1','2','3','4','5','6','7','8','9') then
               begin
               m1:=TRIM(mZnak)||''||TRIM(m1);
               exception
                 when others THEN
                  raise_application_error( -20038 ,  ' PREDCISLI - PODIVNY FORMAT UCTU - ' || mPROUCT ) ;
               end;
             end if;
             if i=6 then exit; end if;
             END LOOP;
             end;

             /*
            begin
            m1 := SUBSTR( trim(mUCET) ,1,LENGTH(trim(mUCET))-pocet );
            exception
            when others THEN
             raise_application_error( -20010 ,  ' PODIVNY FORMAT UCTU - ' || mPROUCT ) ;
            end;
            */
            m1 := LPAD(trim(m1),6,'0');
            result :=TRIM(m1)||'-'||TRIM(m2);
        end if;
        ---chybne stavy m1,m2
        if m1 like '%-%' or m2 like '%-%' then
           result := NULL;
        end if;
  end if;

  return(Result);

end PARABOKPC_PROUCT;
</pre>

Ora2pg
<pre>
CREATE OR REPLACE FUNCTION parabokpc_prouct (mPROUCT PARABOKPC.Prouct%TYPE) RETURNS varchar AS $body$
DECLARE

 mUCET PARABOKPC.Prouct%TYPE;
 Result varchar(17);
 i numeric;
 pocet numeric;
 posun numeric;
 mZnak char(1);
 mSTAV char(1);
 m1 char(6);
 m2 char(10);
BEGIN
  mUCET :=btrim(mPROUCT);
  pocet:=LENGTH(btrim(mUCET));
  if mUCET IS NULL THEN
   Result := NULL;
  end if;

  if mUCET is not null then
       mSTAV :=NULL;
       FOR i IN 1..LENGTH(btrim(mUCET))
       LOOP
         mZnak := SUBSTR( btrim(mUCET) , i,1 );
         if mZnak not in ('0','1','2','3','4','5','6','7','8','9') then
         if mSTAV is null THEN mSTAV :='E'; end if;
         end if;
        END LOOP;

        --- ok ucet - Doplnim pomlcku PREDCISLI-UCET
        if mSTAV is null and LENGTH(btrim(mUCET))= 16 then
          m1:= substr(btrim(mUCET),1,6);
          m2:= substr(btrim(mUCET),7,10);
          result :=m1||'-'||m2;
         end if;
         ---bez pomlcky - doplnit na 16 a rozdelit
        if mSTAV is null and LENGTH(btrim(mUCET))< 16 then
          mUCET := LPAD(btrim(mUCET),16,'0');
          pocet:=LENGTH(btrim(mUCET));
          m1:= substr(btrim(mUCET),1,6);
          m2:= substr(btrim(mUCET),7,10);
          result :=m1||'-'||m2;
        end if;
         ---problematicky ucet
        if mSTAV ='E' then
          --- 1. krok  nahradit / pomlckou
          mUCET :=replace(mUCET,'/','-');
          mUCET :=replace(mUCET,'\','-');
          mUCET :=replace(mUCET,',','-');
          mUCET :=replace(mUCET,'.','-');

          FOR i IN 1..LENGTH(btrim(mUCET))
          LOOP
             mZnak := NULL;
             mZnak := SUBSTR( btrim(mUCET) ,LENGTH(btrim(mUCET))+1-i,1 );
             if mZnak in ('0','1','2','3','4','5','6','7','8','9') then
               begin
                m2:=btrim(mZnak)||''||btrim(m2);
                exception
                 when others THEN
                  RAISE EXCEPTION '%', ' UCET - PODIVNY FORMAT UCTU - ' || mPROUCT );
               end;
             end if;
            if mZnak not in ('0','1','2','3','4','5','6','7','8','9') then
               pocet:=i;
               exit;
             end if;

        END LOOP;

            m2 := LPAD(btrim(m2),10,'0';

             ---stanoveni m1 - predcisli max 6 znaku
             begin
             m1 := SUBSTR( btrim(mUCET) ,1,LENGTH(btrim(mUCET))-pocet );
             exception
             when others THEN

             FOR i IN 1..LENGTH(btrim(mUCET))
             LOOP
             mZnak := NULL;
             posun := LENGTH(btrim(mUCET))-pocet+1-i;
             mZnak := SUBSTR( btrim(mUCET) ,LENGTH(btrim(mUCET))-pocet+1-i,1 );
             if mZnak in ('0','1','2','3','4','5','6','7','8','9') then
               begin
               m1:=btrim(mZnak)||''||btrim(m1);
               exception
                 when others THEN
                  RAISE EXCEPTION '%', ' PREDCISLI - PODIVNY FORMAT UCTU - ' || mPROUCT );
               end;
             end if;
             if i=6 then exit; end if;
             END LOOP;
             end;

             /*
            begin
            m1 := SUBSTR( trim(mUCET) ,1,LENGTH(trim(mUCET))-pocet );
            exception
            when others THEN
             raise_application_error( -20010 ,  ' PODIVNY FORMAT UCTU - ' || mPROUCT ) ;
            end;
            */
            m1 := LPAD(btrim(m1),6,'0';
            result :=btrim(m1)||'-'||btrim(m2);
        end if;
        ---chybne stavy m1,m2
        if m1 like '%-%' or m2 like '%-%' then
           result := NULL;
        end if;
  end if;

  return(Result);

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION parabokpc_prouct (mPROUCT PARABOKPC.Prouct%TYPE) FROM PUBLIC;
</pre>

Error:
<pre>
 m2 := LPAD(btrim(m2),10,'0';
</pre>

**Comment by darold** [comment]
Fixed in commit 8f4339e

**Comment by okbob** [comment]
it is fixed
