### ISSUE TITLE
more issues in one function

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#320]
In this function is a) useless coma in `FROM` b) wrong translation of Oracle outer joins

Oracle:
<pre>
CREATE OR REPLACE function IDES_PRAHA22.NAJVZTAH_PUVODNI_PREDPIS(mID_NAJVZTAH in NAJVZTAH.ID_NAJVZTAH%TYPE) 
return number is
  Result number;
begin
 select  
  DECODE( A3.POCUZA , 0 , NULL ,(SELECT SUM(B1.EPOL_CASTKA  )
              FROM V_NAJPOLOZ B1 WHERE B1.ID_PREDPIS = A4.ID_PREDPIS) ) 
  INTO Result              
  FROM  
   --SSSHLEDEJ_A MT , NAJPROS A1 ,  NAJUDAJE A2 , 
    NAJVZTAH A3 ,  NAJPREDP A4  
    WHERE  
         --- MT.TYP = 'N' AND  MT.HLAVNI = 'H' AND
         --- MT.ID_NAJPROS = A1.ID_NAJPROS(+) AND
         --- A1.ID_NAJUDAJE = A2.ID_NAJUDAJE AND
         --- A2.ID_NAJVZTAH = A3.ID_NAJVZTAH AND
          A3.ID_PREDPIS = A4.ID_PREDPIS(+) AND                   
          A3.ID_NAJVZTAH = mID_NAJVZTAH ;
  
  return(Result);
end NAJVZTAH_PUVODNI_PREDPIS;
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE FUNCTION najvztah_puvodni_predpis (mID_NAJVZTAH NAJVZTAH.ID_NAJVZTAH%TYPE) RETURNS numeric AS $body$
DECLARE

  Result numeric;
BEGIN
 select
  CASE WHEN  A3.POCUZA = 0  THEN  NULL   ELSE(SELECT SUM(B1.EPOL_CASTKA  )
              FROM V_NAJPOLOZ B1 WHERE B1.ID_PREDPIS = A4.ID_PREDPIS)  END  
  INTO Result              
  FROM    --SSSHLEDEJ_A MT , NAJPROS A1 ,  NAJUDAJE A2 , 
    najvztah a3, najpredp a4, 
WHERE          --- A2.ID_NAJVZTAH = A3.ID_NAJVZTAH AND
   A3.ID_NAJVZTAH = mID_NAJVZTAH;

  return(Result);
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION najvztah_puvodni_predpis (mID_NAJVZTAH NAJVZTAH.ID_NAJVZTAH%TYPE) FROM PUBLIC;
</pre>

**Comment by darold** [comment]
Fixed with commit 2766353 on comment rewrite.

**Comment by okbob** [comment]
it is fixed
