### ISSUE TITLE
messy substitution of decode function

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#321]
Oracle:
<pre>
CREATE OR REPLACE function IDES_PRAHA22.GET_SEZNAM_NAJVZTAH(mID_CCLE in CLEOSOBY.ID_CCLE%TYPE)
return varchar2 is
  Result varchar2(4000);
begin
  Result := NULL;
  BEGIN
    FOR qOBPVOMOB IN
    (  SELECT 'Dům '||trim(ACISPOP)||''||
       decode(trim(acisori),'','','\'||ACISORI)||' '|| 
       decode(trim(akod_prostor),'','',' '||
       trim(ABYT_NEBYT)||' '||
       trim(AKOD_PROSTOR))||' '
      AS LOK
       FROM V_NAJVZTAHOSO MT
       WHERE ID_CCLE=mID_CCLE
       order by obdobi_od desc,obdobi_do desc
     ) 
     LOOP
       Result := Result || qOBPVOMOB.LOK || ',';
     END LOOP;    
     Result := SUBSTR( Result , 1 , length(Result) -1 );

  EXCEPTION
    WHEN OTHERS THEN
      Result := 'VETSI POCET NEZ LZE ZOBRAZIT';
  END;
  return(Result);
  
end GET_SEZNAM_NAJVZTAH;
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE FUNCTION get_seznam_najvztah (mID_CCLE CLEOSOBY.ID_CCLE%TYPE) RETURNS varchar AS $body$
DECLARE

  Result varchar(4000);
  qOBPVOMOB RECORD;

BEGIN
  Result := NULL;
  BEGIN
    FOR qOBPVOMOB IN (  SELECT 'Dům '||btrim(ACISPOP)||''||
       CASE WHEN btrim(acisori)='' THEN '' WHEN btrim(acisori)='\'||ACISORI)||' '||
       decode(btrim(akod_prostor),'','',' '||
       btrim(ABYT_NEBYT)||' '||
       btrim(AKOD_PROSTOR))||' '
      AS LOK
       FROM V_NAJVZTAHOSO MT
       WHERE ID_CCLE=mID_CCLE
       order by obdobi_od desc,obdobi_do desc
     ).
     LOOP
       Result := Result || qOBPVOMOB.LOK || ' THEN ';
     END LOOP;
     Result := SUBSTR( Result , 1 , length(Result) -1 );

  EXCEPTION
    WHEN OTHERS THEN
      Result := 'VETSI POCET NEZ LZE ZOBRAZIT';
  END;
  return(Result);

END;
</pre>

errors: `CASE` is not closed. ',' is replaced by `THEN`

**Comment by darold** [comment]
Fixed too by commit 2766353.

**Comment by okbob** [comment]
it is fixed
