### ISSUE TITLE
Regression in dbms_output.put_line translation

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#322]
In version 17.6b:
Oracle:
dbms_output.put_line('done insert into msg_log (date_log, pck_name, msg) values ('||v_ref_date||', '||p_pck_name||', '||substr(p_errmsg, instr(p_errmsg,':') + 2)||')');

became:
RAISE NOTICE 'done insert into msg_log (date_log, pck_name, msg) values (%, %, %)', v_ref_date, p_pck_name, substr(p_errmsg, POSITION(':' in p_errmsg) + 2);

But since 18.1,  it becomes:
RAISE NOTICE 'done insert into msg_log(date_log, pck_name, msg) values ('||v_ref_date||', '||p_pck_name||', '||substr(p_errmsg, POSITION(':' in p_errmsg) + 2)||')';

... which makes an error in Pg.

Rgds,

**Comment by darold** [comment]
Right and especially DBMS_OUTPUT that use function in their arguments. Might be fixed with last commit 177275d

**Comment by edelanoe** [comment]
This is fixed, thanks.
