### ISSUE TITLE
Unwanted alias in an join syntax

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#324]
In Oracle I have:
    SELECT COUNT(*) INTO vSubscCount
    FROM T_TICKET_SUBSCRIPTION TS inner join M_VEHICLE MV on (TS.VEHICLE_GENERIC_ID = MV.VEHICLE_GENERIC_ID)
    WHERE  TS.ZONE_ID = vZone_id;

ora2pg translates to
    SELECT COUNT(*) INTO vSubscCount
    FROM T_TICKET_SUBSCRIPTION TS inner join M_VEHICLE MV on(TS.VEHICLE_GENERIC_ID = MV.VEHICLE_GENERIC_ID) alias1
    WHERE  TS.ZONE_ID = vZone_id;

I have a compilation error about the added " alias1".
And I see 1 optional enhancement: "on(" --> "on (".

Rgds

**Comment by darold** [comment]
Commit 4ba17f7 might fix this issue.

**Comment by edelanoe** [comment]
#324 is fixed
