### ISSUE TITLE
Function with PRAGMA AUTONOMOUS_TRANSACTION and no arg: wrong dblink query string

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#326]
Oracle:
FUNCTION COUNT_DEQUEUE RETURN NUMBER is
	PRAGMA AUTONOMOUS_TRANSACTION;
	-- effectue réellement le comptage et supprime ensuite les données de la table de QUEUE
	v_ERROR_CODE vt_type_catalog.error_type_info%TYPE;
	v_err_context VARCHAR2(200);
	resProc NUMBER;
begin

ora2pg--> FUNCTION PCK_CPT.count_dequeue ()  RETURNS bigint AS $body$
BEGIN
	v_query := 'SELECT * FROM PCK_CPT.count_dequeue_atx ( ' || quote_nullable()) || ' )';
	SELECT * INTO v_ret FROM dblink(v_conn_str, v_query) AS p (ret bigint);
	RETURN v_ret;
---- see the "quote_nullable()) "

Rgds.

**Comment by darold** [comment]
Can you post the code of the function? If you can't anonymized it please send it to my private email gilles AT darold DOT net.

**Comment by edelanoe** [comment]
Here is the full Oracle function (in Package named PCK_CPT)
FUNCTION COUNT_DEQUEUE RETURN NUMBER is
	PRAGMA AUTONOMOUS_TRANSACTION;
	-- effectue réellement le comptage et supprime ensuite les données de la table de QUEUE
	v_ERROR_CODE vt_type_catalog.error_type_info%TYPE;
	v_err_context VARCHAR2(200);
	resProc NUMBER;
begin
    for cur_loop in (select INCR, ZONE_ID, TYPE_OF_VEHICLE_ID, PRODUCT_ID, EQUIPMENT_ID, rowid r
                    from T_CPT_QUEUE
                    order by insert_date
                    )
    loop
        begin
            v_err_context := 'dans COUNT_DEQUEUE ( incr = '|| cur_loop.incr
                                        ||', zone_id = '|| cur_loop.zone_id
                                        || ', TYPE_OF_VEHICLE_ID = '|| cur_loop.TYPE_OF_VEHICLE_ID
                                        || ', PRODUCT_ID = '|| cur_loop.PRODUCT_ID
                                        || ', equipment_id = '|| cur_loop.equipment_id||')';

            if cur_loop.incr = 1
            then -- incrément
                v_err_context := 'COUNT_INCRv2 '||v_err_context ;
                resProc := COUNT_INCRv2(cur_loop.zone_id, cur_loop.TYPE_OF_VEHICLE_ID, cur_loop.PRODUCT_ID);
            else
                v_err_context := 'COUNT_DECRv2 '||v_err_context ;
                resProc := COUNT_DECRv2(1,cur_loop.zone_id, cur_loop.equipment_id, cur_loop.TYPE_OF_VEHICLE_ID, cur_loop.PRODUCT_ID);
            end if;

            delete from T_CPT_QUEUE where rowid = cur_loop.r;

            commit;

		exception when others then
			-- Sans transaction autonome: Continuer la boucle après avoir traité l'erreur (rollb+LOG+commit)
            v_ERROR_CODE := local_log_error(SQLCODE, SQLERRM()||' '||v_err_context);
        end;
    end loop;

    RETURN(resProc);

-- Bloc exception d'une proc du niveau le plus haut, appelée par un scheduler => erreur tracée mais silencieuse
EXCEPTION
	-- ici plus de propagation de l'erreur, mais simple traçage MSG_LOG
	WHEN OTHERS THEN
        -- Le traitement final = rollb+LOG+commit
        v_ERROR_CODE := local_log_error(SQLCODE, SQLERRM()||' '||v_err_context);
        -- Si l'erreur doit rester silencieuse ou si appel scheduler job, n'appeler que local_log_error
        RETURN(v_ERROR_CODE);
end COUNT_DEQUEUE;

**Comment by edelanoe** [comment]
... And here is the code generated by ora2pg with this morning's download:
CREATE OR REPLACE FUNCTION PCK_CPT.count_dequeue ()  RETURNS bigint AS $body$

DECLARE
	-- Change this to reflect the dblink connection string
	v_conn_str  text := 'port=5432 dbname=testdb host=localhost user=pguser password=pgpass';
	v_query     text;

	v_ret	bigint;
BEGIN
	v_query := 'SELECT * FROM PCK_CPT.count_dequeue_atx ( ' || quote_nullable()) || ' )';
	SELECT * INTO v_ret FROM dblink(v_conn_str, v_query) AS p (ret bigint);
	RETURN v_ret;

END;
$body$ LANGUAGE plpgsql SECURITY DEFINER;

**Comment by darold** [comment]
Ok, I understand. Commit 1e4e00e might solve this issue.

**Comment by edelanoe** [comment]
I have tested this morning's download. I have 2 functions with autonomous_transaction. The 1st has 3 arguments and the 2nd has no argument. Here is how they are translated:
CREATE OR REPLACE FUNCTION PCK_COMMON.insert_log (p_pck_name text, p_msg text, p_ref_date timestamp default systimestamp ) RETURNS VOID AS $body$
DECLARE
	-- Change this to reflect the dblink connection string
	v_conn_str  text := 'port=5432 dbname=... host=localhost user= password=';
	v_query     text;

BEGIN
	v_query := 'SELECT true FROM PCK_COMMON.insert_log_atx ( ' || quote_nullable(p_pck_name) || ',' || quote_nullable(p_msg) || ',' || quote_nullable(p_ref_date) || ' )';
	PERFORM * FROM dblink(v_conn_str, v_query) AS p (ret boolean);

END;
$body$ LANGUAGE plpgsql SECURITY DEFINER;
------------------------( ... )--------------------------
CREATE OR REPLACE FUNCTION PCK_CPT.count_dequeue ()  RETURNS bigint AS $body$

DECLARE
	-- Change this to reflect the dblink connection string
	v_conn_str  text := 'port=5432 dbname=... host=localhost user= password=';
	v_query     text;

	v_ret	bigint;
BEGIN
	v_query := 'SELECT * FROM PCK_CPT.count_dequeue_atx ( ' || quote_nullable(p_pck_name) || ',' || quote_nullable(p_msg) || ',' || quote_nullable(p_ref_date) || ' )';
	SELECT * INTO v_ret FROM dblink(v_conn_str, v_query) AS p (ret bigint);
	RETURN v_ret;

END;
$body$ LANGUAGE plpgsql SECURITY DEFINER;
----------------------------------
-- The arguments of the 1st function are taken while translating the 2nd funcion
----------------------------------

**Comment by darold** [comment]
My bad, typo in variable declaration fixed in commit fcf40a9

**Comment by edelanoe** [comment]
#326 is fixed, thank you.
