### ISSUE TITLE
Function with PRAGMA AUTONOMOUS_TRANSACTION: dblink connection string

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#327]
Is it possible to take the dblink connection string parameters from the .conf file ?
By default, it should be the target PostgreSQL database, but I guess you wish to keep the semantics of PG_DSN, PG_USER, PG_PWD, so I let you decide how to do (other parameters?).

Moreover, why not create a generic function like this:
CREATE OR REPLACE FUNCTION persist(myFuncCall text)
    RETURNS void
    LANGUAGE 'plpgsql'
    COST 100.0
    VOLATILE NOT LEAKPROOF SECURITY DEFINER 
AS $function$
DECLARE
	-- Change this to reflect the dblink connection string
	v_conn_str  text := 'port=5432 dbname=testdb host=localhost user=pguser password=pgpass';
	v_query     text;
BEGIN
	v_query := 'SELECT true FROM '||myFuncCall;
	PERFORM * FROM dblink(v_conn_str, v_query) AS p (ret boolean);
END;
$function$;
--- and the connection string does not have to be duplicated

**Comment by darold** [comment]
Commit 0fe5e1e adds DBLINK_CONN configuration directive. By default Ora2Pg will use the values set with PG_DSN, PG_USER and PG_PWD. But if you want to fully override the connection string use this directive as follow:
```
DBLINK_CONN    port=5432 dbname=pgdb host=localhost user=pguser password=pgpass
```

**Comment by edelanoe** [comment]
This is fixed, thanks.
