### ISSUE TITLE
Data types in functions are not translated

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#328]
Ora2pg doesn't translate types inside functions

Is possible to apply mapping table from Oracle types to PostgreSQL types use inside functions too?

We translate Oracle timestamp to PostgreSQL date. Now we should to manually change variable types to date.

**Comment by darold** [comment]
Can you provide an example? Do you mean replacement in cast function call?

**Comment by okbob** [comment]
In `DATA_TYPE` clause (ora2pg.conf) we have `DATE:date`

Oracle function:
<pre>
CREATE OR REPLACE function IDES_JMMAJ.FUPRAV_DATUZA_PLATBY( mDATUZA IN DATE ) return DATE is
  Result DATE;
begin
  IF  mDATUZA <= TO_DATE('01.01.1980' , 'DD.MM.YYYY' )  THEN
    result := NULL; 
  ELSE
    result := mDATUZA; 
  END IF;  

  return(Result);
end FUPRAV_DATUZA_PLATBY;
</pre>

But it is translated to:
<pre>
CREATE OR REPLACE FUNCTION fuprav_datuza_platby ( mDATUZA timestamp ) RETURNS date AS $body$
DECLARE

  Result timestamp;

BEGIN
  IF  mDATUZA <= TO_DATE('01.01.1980' , 'DD.MM.YYYY' )  THEN
    result := NULL;
  ELSE
    result := mDATUZA;
  END IF;

  return(Result);
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
</pre>

**Comment by darold** [comment]
Ok, commit b66430a might fix this issue.

**Comment by okbob** [comment]
no change :(

**Comment by darold** [comment]
It works with input from a file, I test from a live database and get back.

**Comment by darold** [comment]
Works well too, using the following command:

    ora2pg -p -c config/ora2pg.conf -t FUNCTION -b tmp/ -D 'DATE:date'

I have the following resulting code from your original function:
```
CREATE OR REPLACE FUNCTION fuprav_datuza_platby ( mDATUZA date ) RETURNS date AS $body$
DECLARE

  Result date;

BEGIN
  IF  mDATUZA <= TO_DATE('01.01.1980' , 'DD.MM.YYYY' )  THEN
    result := NULL;
  ELSE
    result := mDATUZA;
  END IF;

  return(Result);
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
```

**Comment by okbob** [comment]
I'll recheck it

**Comment by okbob** [comment]
looks ok, I checked wrong file probably in previous test.
ok, thank you for super fast reply. Now, there is only one issue - OUT parameters.

**Comment by darold** [comment]
I will try to work on it next week if possible.

**Comment by okbob** [comment]
Next week or next two weeks be great. If you visit Prague, you have all beers what you can drink from me.

**Comment by darold** [comment]
Prague is one of the place in the world that must be visited and probably one day I will be there. I will be very pleased to meet you, in Prague or other places.

**Comment by okbob** [comment]
What next p2d2? PostgreSQL Prague Developer Days. It is little bit could because February - but it can be gratis for you if you do a presentation there.

**Comment by darold** [comment]
Well, why not, I've put a reminder in january 2018.
