### ISSUE TITLE
to_timestamp_tz Oracle function is not translated

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#329]
In a script as in a Package function or procedure, I have such syntax (Oracle being too tolerant!):
to_timestamp_tz('01/01/14 00:00:00,000000000 +01:00','DD/MM/RR HH24:MI:SSXFF TZR')
to_timestamp_tz('26/08/15 00:00 EUROPE/PARIS','DD/MM/YY HH24:MI TZR')
to_timestamp_tz('2014-05-15 EUROPE/PARIS','YYYY-MM-DD TZR')
to_timestamp_tz(p_CLOSURE_DATE,'YYYYMMDD') at time zone 'Europe/Paris';
TO_TIMESTAMP_TZ( vDateLimitUse, 'YYYYMMDD"T"HH24MISSTZHTZM');  -- see value next line
TO_TIMESTAMP_TZ( '20170604T192505+0200', 'YYYYMMDD"T"HH24MISSTZHTZM');

The postgreSQL target function is well identified: to_timestamp , but there is a work around timezone and offset expression, and below-microsecond truncation too...
Here is what I already had to change manually: 
to_timestamp_tz('01/01/14 00:00:00,000000000 +01:00','DD/MM/RR HH24:MI:SSXFF TZR')  -- becomes:
to_timestamp('01/01/14 00:00:00,000000','DD/MM/YY HH24:MI:SS,US')  -- with remarks below
-- I'm not sure "YY" in PostgreSQL is equivalent to "RR" in Oracle
-- the GMT offset is "lost" and "automatically re-built" by the to_timestamp which returns with time zone

**Comment by darold** [comment]
Here are the translation done with last commit 7248595 
```
select to_timestamp_tz('01/01/14 00:00:00,000000000 +01:00','DD/MM/RR HH24:MI:SSXFF TZR') from dual;
TO_TIMESTAMP_TZ('01/01/1400:00:00,000000000+01:00','DD/MM/RRHH24:MI:SSXFFTZ
---------------------------------------------------------------------------
01/01/14 00:00:00,000000000 +01:00
```
is translated into
```
SELECT to_timestamp('01/01/14 00:00:00,000000 +01:00','DD/MM/YY HH24:MI:SSXUS ');
      to_timestamp      
------------------------
 2014-01-01 00:00:00+01
```
both return the "same" value.
```
SQL> ALTER SESSION SET NLS_TIMESTAMP_FORMAT='YYYY-MM-DD HH24:MI:SS.FF';
SQL> SELECT CREATE_DATE FROM TEST_TZ;
CREATE_DATE
---------------------------------------
2014-01-01 00:00:00.000000
```
but this it more complex, `RR` is equal to `YY` when the year value is lower or equal than 49 , years above appears as 20th century dates, with PostgreSQL they are all in the 21th.

Here are all transformation done by Ora2Pg on the date formatting:
```
sub convert_date_format
{
        my $fields = shift;

        # Truncate time to microsecond
        $fields =~ s/(\d{2}:\d{2}:\d{2}[,\.]\d{6})\d{3}/$1/s;

        # Replace round year with two digit year format.
        $fields =~ s/RR/YY/sg;

        # Convert fractional seconds to milli (MS) or micro seconds (US)
        $fields =~ s/FF[123]/MS/s;
        $fields =~ s/FF\d*/US/s;

        # Remove any timezone format
        $fields =~ s/TZ[DHMR]//gs;

        return $fields;
}
```
From lib/Ora2Pg/PLSQL.pm at line 851.

Commit 8d6c721 limit the timestamp microsecond to 6 digit (FF6) as supported by PostgreSQL. Format in Oracle can use FF[0..9]. This is effective when ENABLE_MICROSECOND is enabled in ora2pg.conf.

**Comment by edelanoe** [comment]
All this is sufficient, thank you. Test OK on my side.
# 329 is fixed
