### ISSUE TITLE
PARTITION

### ISSUE THREAD

**Issue by ssayyadi** [darold/ora2pg#330]
1. OTHER table name always is OTHER (even in ora2pg.conf:  PREFIX_PARTITION        1)  and it makes problem in multi partition migration.

2. In insert_triggers Missing ';' for last ELSEIF ... THEN statements before END IF and for INSERT INTO OTHER VALUES (NEW.*) before END IF

**Comment by darold** [comment]
1. Fixed with commit c8721d2

2. Not reproduced, please post the context of the issue here, I mean few lines before and after the issue. For example with latest development code I have:
```
CREATE OR REPLACE FUNCTION SALES_LIST_insert_trigger()
RETURNS TRIGGER AS $$
BEGIN
        IF ( NEW.SALES_STATE IN ('California', 'Hawaii') ) THEN INSERT INTO SALES_LIST_SALES_WEST VALUES (NEW.*);
        ELSIF ( NEW.SALES_STATE IN ('New York', 'Virginia', 'Florida') ) THEN INSERT INTO SALES_LIST_SALES_EAST VALUES (NEW.*);
        ELSIF ( NEW.SALES_STATE IN ('Texas', 'Illinois') ) THEN INSERT INTO SALES_LIST_SALES_CENTRAL VALUES (NEW.*);
        ELSE
                INSERT INTO SALES_LIST_SALES_OTHER VALUES (NEW.*);
        END IF;
        RETURN NULL;
END;
$$
LANGUAGE plpgsql;
```

**Comment by ssayyadi** [comment]
You can see it as below:

```
CREATE OR REPLACE FUNCTION T_USER_GRANTS_FOR_BI_insert_trigger()
RETURNS TRIGGER AS $$
BEGIN
        IF( NEW.NOVELL_ID < 'c' ) THEN INSERT INTO P1 VALUES (NEW.*);
        ELSIF( NEW.NOVELL_ID < 'g' ) THEN INSERT INTO P2 VALUES (NEW.*);
        ELSIF( NEW.NOVELL_ID < 'k' ) THEN INSERT INTO P3 VALUES (NEW.*);
        ELSIF( NEW.NOVELL_ID < 'm' ) THEN INSERT INTO P4 VALUES (NEW.*);
        ELSIF( NEW.NOVELL_ID < 'r' ) THEN INSERT INTO P5 VALUES (NEW.*);
        ELSIF( NEW.NOVELL_ID < 's' ) THEN INSERT INTO P6 VALUES (NEW.*);
        ELSIF( NEW.NOVELL_ID < 'v' ) THEN INSERT INTO P7 VALUES (NEW.*);
        ELSIF( NEW.NOVELL_ID < 'w' ) THEN INSERT INTO P8 VALUES (NEW.*);
        ELSIF( NEW.NOVELL_ID < 'z' ) THEN INSERT INTO P9 VALUES (NEW.*);
        ELSE
                INSERT INTO OTHER VALUES (NEW.*)
        END IF;
        RETURN NULL;
END;
$$
LANGUAGE plpgsql; 
```

**Comment by darold** [comment]
Please use latest development code, this might have been solved t I can not reproduce it.

**Comment by ssayyadi** [comment]
Thanks for your support.
Actually, I don't know how to use the development code.
Would you please explain me?

**Comment by darold** [comment]
You can download and install it using:
 ```
wget https://github.com/darold/ora2pg/archive/master.zip
unzip master.zip
cd  ora2pg-master/
perl Makefile.PL
make
sudo make install
```

**Comment by ssayyadi** [comment]
Thanks for your help but after doing that I'm getting below error:
Can't find string terminator '"' anywhere before EOF at /usr/local/bin/ora2pg line 491.

**Comment by darold** [comment]
Not reproducible, there is something wrong. Please download code again and proceed to a new installation. The sudo use can be omitted if you are root. If the error appears again please check that the line 491 given in the error message is the same as this one: 
```
print "Creating script export_schema.sh to automate all exports.\n";
```

**Comment by ssayyadi** [comment]
You are gr8!
That's worked and now the missed ';'  and OTHER partition name plus sub-partitions definition problems solved.
I appreciate you.
