### ISSUE TITLE
Tables with same name as materialized view

### ISSUE THREAD

**Issue by ssayyadi** [darold/ora2pg#331]
In our oracle database schema we have some tables which are named as same as materialized view,
for example MV_PLANT_DIVISION (Object_TYPE=TABLE) and with same name but (Object_TYPE=materialized view), such tables will not be migrated.

I have used a trick for that as below:
1- in Oracle: create table NV_PLANT_DIVISION as (select * from MV_PLANT_DIVISION)
2- in ora2pg.conf   REPLACE_TABLES NV_PLANT_DIVISION:MV_PLANT_DIVISION
3- ora2pg

**Comment by darold** [comment]
It seems not possible to create materialized view with same name as a table, how to create a test case? Or perhaps you are exporting froim multiple schema?

**Comment by ssayyadi** [comment]
to reproduce : Create a table in your oracle schema and name it MV_ABC then create a materialize view with same name under same schema.
Try to migrate just table MV_ABC to postgresql (-t TABLE) then you will see that ora2pg will not detect it.

**Comment by darold** [comment]
It is not possible to create a materialized view with the same name as an existing table.
```
SQL> CREATE TABLE MV_A (id NUMBER);

Table created.

SQL> CREATE MATERIALIZED VIEW MV_A AS SELECT * FROM EMPLOYEE;
CREATE MATERIALIZED VIEW MV_A AS SELECT * FROM EMPLOYEE
                                               *
ERREUR a la ligne 1 :
ORA-00955: name is already used by an existing object

```

which version of Oracle database are you using?

**Comment by darold** [comment]
Oh I understand your mistake. When you create a MATERIALIZED VIEW Oracle automatically create an "hidden" TABLE, so if you look at the ALL_OBJECTS table you will find both entries but only the materialized view must be exported. Example:
```
SQL> CREATE MATERIALIZED VIEW MV_A AS SELECT * FROM EMPLOYEE;

SQL> SELECT OBJECT_NAME,Object_TYPE FROM ALL_OBJECTS WHERE OBJECT_NAME='MV_A';

OBJECT_NAME | OBJECT_TYPE
-----------------------------------------------
MV_A                  | TABLE
MV_A                  | MATERIALIZED VIEW
```

**Comment by ssayyadi** [comment]
Yes, exactly I did same mistake :)
