### ISSUE TITLE
Out of memory when using INSERT mode with 2 tables

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#332]
I try to send data directly to PostgreSQL server: 2 tables of 8 and 2 rows,
 and I get "Out of memory!".
I have it too if I switch to file-output mode :(
Note that in both cases, the first table is processed successfully: I get my 8 rows or my 8 INSERT in .sql

I attach the output file produced with only 1 table: it includes sequence reinit orders...

I am using the master download of 2017-03-13 (morning).

Should I enhance a priority or memory limit param of my cmd.exe? Surprising for so few rows...
(and I don't know how to change such limit on windows)

### here is my windows cmd session:

C:\ora2pg\DataScripts>ora2pg -c ora2pg_DATA_INIT.conf
Ora2Pg version: 18.1
Trying to connect to database: dbi:Oracle:host=myHost;sid=mySID
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
Retrieving table information...
[1] Scanning table T_VAT_RATE (8 rows)...
[2] Scanning table T_VAT_VERSION (2 rows)...
Trying to connect to database: dbi:Oracle:host=myHost;sid=mySID
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
Retrieving partitions information...

Dropping foreign keys of table T_VAT_RATE...
Dropping foreign keys of table T_VAT_VERSION...
Looking how to retrieve data from T_VAT_RATE...
Fetching all data from T_VAT_RATE tuples...
Dumping data from table T_VAT_RATE into PostgreSQL...
Setting client_encoding to UTF8...
Disabling synchronous commit when writing to PostgreSQL...
DEBUG: Creating output for 10000 tuples
DEBUG: Sending INSERT bulk output directly to PostgreSQL backend
Extracted records from table T_VAT_RATE: total_records = 8 (avg: 8 recs/sec)

[===================>     ]  8/10 total rows (80.0%) - (0 sec., avg: 8 recs/sec).
Out of memory!
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(HOST=myHost)(PROTOCOL=tcp)(PORT
=1526))(ADDRESS=(HOST=myHost)(PROTOCOL=tcp)(PORT=1521)))(CONNECT_DATA=(SID=mySID))) at C:/Perl/site/lib/DBD/Oracle.pm line 348.

[DataInitNonConfig.txt](https://github.com/darold/ora2pg/files/842096/DataInitNonConfig.txt)

**Comment by darold** [comment]
How many memory do you have on this computer? PLease try to use `-L 100` at your ora2pg command line to see if that solves the issue.

**Comment by edelanoe** [comment]
I have 8Gb, and more than 4Gb free at the time of the test.
-L 100 solves the problem. 
Should I also try to configure the memory accessible to a cmd window?

**Comment by darold** [comment]
I can't help on windows, I don't know how to tune this operating system. Can you please try with -L 500, -L 1000 and -L 5000 to find at what level we the out of memory is reached, I will change the default valur for Windows. Also give a try to the cmd windows configuration to see if that could change the behavior, in this case I will drop a line in documentation about this trick.

**Comment by edelanoe** [comment]
I could not find out if windows 7 can show or increase the memory available to a prog called from the command line.
The INSERT mode seems to work with -L 2000, not 3000.
Rgds,
