### ISSUE TITLE
EXCLUDE clause cannot be combined with ALLOW clause

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#333]
When the ALLOW clause is used, the EXCLUDE clause seems to have no effect.
In some other systems, exclude clauses can filter-out things in the context of already selected items.
For instance, in TABLE or INSERT mode, if I ALLOW  T.* and add an EXCLUDE TRA.* clause, I was expecting to export TITLES but not TRANS_ON_BOOKS.
Could this feature be added in ora2pg ? (a new directive ? for backward compatibility)

**Comment by darold** [comment]
When the ALLOW directive is used, the EXCLUDE clause is not used, in other terms both definition are not combined. I was thinking that regexp can cover all needs but it seems unfortunately that Oracle regexp doesn't allow lookahead:
```
ALLOW    T(?!RA)
```
don't works.

I will give a solution to that kind of selection.

**Comment by edelanoe** [comment]
Trop bien, merci ☺

Cdlt,
Eric D (poste 427)

De : Darold [mailto:notifications@github.com]
Envoyé : mercredi 15 mars 2017 14:38
À : darold/ora2pg
Cc : Delanoe Eric; Author
Objet : Re: [darold/ora2pg] EXCLUDE clause cannot be combined with ALLOW clause (#333)


When the ALLOW directive is used, the EXCLUDE clause is not used, in other terms both definition are not combined. I was thinking that regexp can cover all needs but it seems unfortunately that Oracle regexp doesn't allow lookahead:

ALLOW    T(?!RA)

don't works.

I will give a solution to that kind of selection.

**Comment by darold** [comment]
Last commit bc218a4 allow you to exclude some tables from your selection. With your example, proceed as follow:

    ALLOW    T.* !TRA.*

this will include all tables starting with T excluding all tables starting with TRA.

**Comment by edelanoe** [comment]
#333 is fixed, thank you.
