### ISSUE TITLE
list/list subpartitions wrongly translated

### ISSUE THREAD

**Issue by 3kkani** [darold/ora2pg#334]
Hello Darold,

first of all thanks for your great work and for ora2pg that is providing a significant help in our migration project.

We have a table defined in oracle as follow:

`  CREATE TABLE "MYSCHEMA"."XREF" 
   (	"DBID" NUMBER(3,0) NOT NULL ENABLE, 
	"CREATED" NUMBER(6,0) NOT NULL ENABLE, 
	"LAST" NUMBER(6,0) NOT NULL ENABLE, 
	"UPI" NVARCHAR2(13) NOT NULL ENABLE, 
	"VERSION_I" NUMBER(6,0) NOT NULL ENABLE, 
	"DELETED" CHAR(1 BYTE) NOT NULL ENABLE, 
	"TIMESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"USERSTAMP" NVARCHAR2(10) DEFAULT USER NOT NULL ENABLE, 
	"AC" NVARCHAR2(150) NOT NULL ENABLE, 
	"VERSION" NUMBER(6,0), 
	"TAXID" NUMBER, 
	"ID" NUMBER, 
	 CONSTRAINT "CK_XREF$DELETED" CHECK (deleted IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "FK_XREF$CREATED" FOREIGN KEY ("CREATED")
	  REFERENCES "MYSCHEMA"."RNC_RELEASE" ("ID") ENABLE, 
	 CONSTRAINT "FK_XREF$DBID" FOREIGN KEY ("DBID")
	  REFERENCES "MYSCHEMA"."RNC_DATABASE" ("ID") ENABLE, 
	 CONSTRAINT "FK_XREF$LAST" FOREIGN KEY ("LAST")
	  REFERENCES "MYSCHEMA"."RNC_RELEASE" ("ID") ENABLE, 
	 CONSTRAINT "FK_XREF$UPI" FOREIGN KEY ("UPI")
	  REFERENCES "MYSCHEMA"."RNA" ("UPI") ENABLE
   ) 
  PARTITION BY LIST ("DBID") 
  SUBPARTITION BY LIST ("DELETED") 
  SUBPARTITION TEMPLATE ( 
    SUBPARTITION "DELETED" VALUES ( 'Y' ), 
    SUBPARTITION "NOT_DELETED" VALUES ( 'N' ) );`

Basically it has two sub-partitions (deleted Y/N) for each DBID partition (there are 23 of them).

Partition names are XREF_P1, XREF_P2, ..., XREF_P23.
Subpartition names are XREF_P1_DELETED, XREF_P1_NOT_DELETED, XREF_P2_DELETED, XREF_P2_NOT_DELETED, ..., XREF_P23_DELETED, XREF_P23_NOT_DELETED.

I was expecting ora2pg to define two tables for each DBID while instead it is defining 46 tables for each DBID (23 for deleted=Y and 23 for deleted=N) as follow:

`CREATE TABLE XREF_P1 ( CHECK (
        DBID IN (1)
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P11_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P23_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P9_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P7_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P18_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P19_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P21_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P5_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P10_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P1_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P6_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P17_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P15_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P12_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P13_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P2_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P3_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P14_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P16_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P22_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P8_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P4_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P20_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('Y')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P20_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P14_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P18_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P22_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P12_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P1_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P3_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P5_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P13_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P15_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P4_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P17_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P16_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P10_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P21_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P11_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P2_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P7_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P6_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P23_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P8_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P9_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);
CREATE TABLE XREF_P1_XREF_P19_NOT_DELETED ( CHECK (
        DBID IN (1) AND DELETED IN ('N')
) ) INHERITS (XREF);`

It looks like ora2pg is looping through all the sub-partitions definitions instead of just two for each DBID.

Many thanks for your help.
Maurizio.

**Comment by darold** [comment]
I've rewritten the way Ora2Pg is exporting sub partition and the issue might be fixed with commit 4686867. Please let me know if there's any other issue with partition export.

**Comment by 3kkani** [comment]
Ok. Thanks a lot. I will try to test it and let you know.

**Comment by darold** [comment]
Last two commits bac9082 and 970092b fix some pending issues on this partition export rewriting.

**Comment by 3kkani** [comment]
Hello Darold,

it took some time because I had to install in a brand new VM to avoid any possible issue with our current "production" configuration for the ongoing migration project but I have managed to install the commits that you kindly listed and it seems to be properly fixed! 

Thanks a lot!

Do you have plan to publish a new packeted ora2pg release soon?
Maurizio.

**Comment by darold** [comment]
Hi Maurizio,

Yes probably at the end of next week I will publish a new release. Thanks for the feedback.

 Best regards,

**Comment by 3kkani** [comment]
Hello Darold,

one last addition, you might want to know that in our case the indexes on the inherited tables generated in ./schema/partitions/PARTITION_INDEXES_partition.sql appear not useful as the tables are meant to contain only one pair of dbid, deleted values:

`CREATE INDEX XREF_P1_DELETED_DELETED ON XREF_P1_DELETED (DBID,DELETED);
CREATE INDEX XREF_P1_NOT_DELETED_DELETED ON XREF_P1_NOT_DELETED (DBID,DELETED);
CREATE INDEX XREF_P2_DELETED_DELETED ON XREF_P2_DELETED (DBID,DELETED);
CREATE INDEX XREF_P2_NOT_DELETED_DELETED ON XREF_P2_NOT_DELETED (DBID,DELETED);
CREATE INDEX XREF_P3_DELETED_DELETED ON XREF_P3_DELETED (DBID,DELETED);
CREATE INDEX XREF_P3_NOT_DELETED_DELETED ON XREF_P3_NOT_DELETED (DBID,DELETED);
CREATE INDEX XREF_P4_DELETED_DELETED ON XREF_P4_DELETED (DBID,DELETED);
CREATE INDEX XREF_P4_NOT_DELETED_DELETED ON XREF_P4_NOT_DELETED (DBID,DELETED);
CREATE INDEX XREF_P5_DELETED_DELETED ON XREF_P5_DELETED (DBID,DELETED);
CREATE INDEX XREF_P5_NOT_DELETED_DELETED ON XREF_P5_NOT_DELETED (DBID,DELETED);
CREATE INDEX XREF_P6_DELETED_DELETED ON XREF_P6_DELETED (DBID,DELETED);
CREATE INDEX XREF_P6_NOT_DELETED_DELETED ON XREF_P6_NOT_DELETED (DBID,DELETED);
...
`
Thanks again for your great work.
Maurizio.

**Comment by darold** [comment]
Thanks for the feedback, Ora2Pg is doing generic work so it generates DDL to create indexes on columns involved in the partition key.

**Comment by 3kkani** [comment]
Hi Darold,

you mentioned that you were probably going to publish a new release soon which includes this fix. Do you have any estimated/planned date when this is likely to happen?

Many thanks.
Maurizio.

Thanks.
Maurizio.

**Comment by darold** [comment]
Unfortunately not, I can just say that it will be published after the pgCluu release that is delayed for too long time now. So probably at the end of the month, but don't take too much attention of this date, I don't have enough spare time to do all I have to do.

Sorry.

**Comment by 3kkani** [comment]
I understand. Thanks for your answer Darold.
