### ISSUE TITLE
Can't call method "close" Error when calling in INSERT mode (script generation)

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#335]
Hello,
When calling
    ora2pg -c ora2pg_Data.conf -a T_VAT_RATE
I have the following error message on windows cmd stderr:
Can't call method "close" on an undefined value at C:/Perl/site/lib/Ora2Pg.pm line 5253.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=............................................

I get the same if I include ALLOW and remove -a, and the same too if I remove DISABLE_SEQUENCE redef.

Attachment: my 2 levels of .conf files + the full command output.
[CloseMethodError_files.zip](https://github.com/darold/ora2pg/files/847737/CloseMethodError_files.zip)

Rgds,
Eric

**Comment by darold** [comment]
Commit 1ec2439 might solves this issue

**Comment by edelanoe** [comment]
#335 is fixed, thank you
