### ISSUE TITLE
Unexpected EXECUTE before a "SELECT" in "OPEN <cursor> FOR SELECT..."

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#336]
When I try to translate:
        OPEN CUR_ZONE_COUNTING FOR SELECT PRODUCT_ID, COUNTING
            FROM T_COUNTING_IST_ZONE
            WHERE ZONE_ID = vZone_id
I get:
        OPEN CUR_ZONE_COUNTING FOR EXECUTE SELECT PRODUCT_ID, COUNTING
            FROM T_COUNTING_IST_ZONE
            WHERE ZONE_ID = vZone_id

...(does not compile)
Rgds,
Eric

**Comment by darold** [comment]
I'm not able to reproduce the issue, please send me the full code of the function/procedure.

**Comment by edelanoe** [comment]
Hello,
The complete code is attached, but I give you the local code layout too, suspecting it will help by itself...
[UPDATE_COUNTING_ZONEv2.txt](https://github.com/darold/ora2pg/files/857578/UPDATE_COUNTING_ZONEv2.txt)

---------------------------------- local code layout ------------------------------------
        OPEN CUR_ZONE_COUNTING FOR 
            SELECT PRODUCT_ID, COUNTING
            FROM T_COUNTING_IST_ZONE
            WHERE ZONE_ID = vZone_id
            AND TYPE_OF_VEHICLE_ID = vType_Of_Vehicule_Id
            AND PRODUCT_ID NOT IN (CST.PROD_SUBSCRIPTION,
								   CST.PROD_BOOKING) -- les résas et abos sont recalés automatiquement, cf traitement ci dessus
            ORDER BY PRODUCT_ID;

**Comment by darold** [comment]
Thanks, commit 1fde969 solves the issue.

**Comment by edelanoe** [comment]
#336 is fixed, thanks
