### ISSUE TITLE
Erro convert the data from Oracle to PostgrSQL

### ISSUE THREAD

**Issue by FredericoG** [darold/ora2pg#337]
Hi,

When I try to perform the data conversion, it returns the error below:

Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle orclEducacao at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 4892.

What can I do to solve it?

My file is configmented like this:

Set Oracle database connection (datasource, user, password)
ORACLE_DSN	dbi:Oracle:host=localhost;sid=orclEducacao
ORACLE_USER	system
ORACLE_PWD	password

Thank you!

**Comment by darold** [comment]
What is the output of the following command:

    ora2pg -t SHOW_VERSION

and your version of ora2pg?

**Comment by FredericoG** [comment]
Hi,

Thank's for return.

This is the version from Oracle:
Oracle Database 11g Enterprise Edition Release 11.2.0.1.0

**Comment by darold** [comment]
You may have encountered an other error just before, probably an OOM, please set DATA_LIMIT value to 1000 in ora2pg.conf and run ora2pg again. Let me know.

How many RAM do you have?

**Comment by FredericoG** [comment]
I work on a windows server with 32 GB of memory. And return other erro.
Can't call method "do" on an undefined value at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 4892.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(HOST=localhost)(PROTOCOL=tcp)(PORT=1526))(ADDRESS=(HOST=localhost)(PROTOCOL=tcp)(PORT=1521)))(CONNECT_DATA=(SID=orclEducacao))) at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 4892.

And now?
Thank you for help.

**Comment by darold** [comment]
I've tried an export on a Windows server using ora2pg 18.1 and direct import into a PostgreSQL database but I'm not able to reproduce the issue. Can you send me the output of the ora2pg command using the -d command line option. If you need privacy send it to my private email gilles AT darold DOT net. Please join the ora2pg.conf file too.

**Comment by darold** [comment]
Any news on this issue?

**Comment by Bulva** [comment]
The same problem here on Windows 7 64bit with Strawberry Perl and also on Ubuntu 16.04. Exported finished but there is not INSERTS in a file (only create table and alter table statements).
