### ISSUE TITLE
Some Package function calls are not fully qualified when translated

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#338]
Hello,

When I translate my PCK_CPT package, the calls to PCK_CPT functions  fnc_aff_type_of_vehicle or MAJ_CPT are well translated, but not the calls to COUNT_INCRv2 and COUNT_DECRv2. Would it be an issue with mixing lower and uppercase ?

My test is done on build 1fde969 or later (download done 2017/03/22 10:42)

Best Rgds,

**Comment by darold** [comment]
This is not an issue, PostgreSQL is case insensitive unless you force the case sensitivity using double quote. Name of the functions are always converted to lower case at create statement unless you enable PRESERVE_CASE, which is a bad idea unless your application always double quote object's name in the code.

Regards,

**Comment by edelanoe** [comment]
So the issue has another cause. Can you have a look to the code received, searching for the function names above ?
Thanks in advance,
Eric

**Comment by darold** [comment]
Ok I've found the issue, commit 22aaa0d might solve it.

**Comment by edelanoe** [comment]
I have a small regression: two dots appeared where the translation was correct
Oracle (in package PCK_CPT)
BEGIN
	
    --vType_Of_Vehicule_Id := vType_Of_Vehicule;
	vType_Of_Vehicule_Id := fnc_Aff_Type_Of_Vehicle(vType_Of_Vehicule);

Previous builds (03/22):
BEGIN
	
    --vType_Of_Vehicule_Id := vType_Of_Vehicule;
	vType_Of_Vehicule_Id := pck_cpt.fnc_aff_type_of_vehicle(vType_Of_Vehicule);

New build (03/24):
BEGIN
	
    --vType_Of_Vehicule_Id := vType_Of_Vehicule;
	vType_Of_Vehicule_Id := ..pck_cpt.fnc_aff_type_of_vehicle(vType_Of_Vehicule);

Have a good weekend anyway :)
Eric

**Comment by edelanoe** [comment]
... and the translation of the ones that were not fully qualified is not ok:
v_ERROR_CODE := COUNT_DECRv2(vRecurs+1, vZone_Id, vEquipment_Id, vType_Of_Vehicule_Id, vProduct_Id);
Becomes:
v_ERROR_CODE := .pck_cpt.count_decrv2(vRecurs+1, vZone_Id, vEquipment_Id, vType_Of_Vehicule_Id, vProduct_Id);

**Comment by darold** [comment]
Using test files it is not reproducible, I load your example into an Oracle database and let you know.

**Comment by darold** [comment]
Issue reproduced with a database export and solved with commit 7542b4f.

**Comment by edelanoe** [comment]
#338 is fixed, thank you.
