### ISSUE TITLE
Escaping tabs in citext columns

### ISSUE THREAD

**Issue by twr** [darold/ora2pg#339]
Hi,

I run into an issue when exporting data (COPY mode) for columns for which target type is set to be `citext`. Tabs are not escaped for these columns.

Would it be possible to treat columns that have target type as `citext` as text so that they can be subject for escaping.
Not sure if there is anything more to it but the following change https://github.com/twr/ora2pg/commit/1c3e843321379197cdb33f374184af14294109fd
did work for me.

Thanks

**Comment by darold** [comment]
Hi Tomasz,

Yes your fix might be enough, can you send it as a pull request?

Regards
