### ISSUE TITLE
Missing CREATE SCHEMA when exporting a schema with CREATE_SCHEMA = 1

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#340]
Hello,

It seems the CREATE_SCHEMA configuration parameter has no effect when export TYPE is FUNCTION, even if the EXPORT_SCHEMA option is 1.
To my mind, the generation of a CREATE SCHEMA (or create schema if not exist ...) should not be linked to the export type (a comment says "TABLE"), but mainly to the CREATE_SCHEMA option.

Let's say it should be generated if CREATE_SCHEMA is 1 or if the TYPE is TABLE or PACKAGE, because it is required in the latter case.

Of course, the final choice is yours, depending on the functional backwards compatibility, but it seems feasible, thanks to the "if not exists" option of create schema.

Rgds,
Eric

**Comment by darold** [comment]
Hi Eric,

Yes CREATE_SCHEMA configuration parameter is only used when export type is TABLE. With the addition of IF EXISTS in pg 9.3 I agree that it could be include in all export. I will think about it.

Regards,

**Comment by edelanoe** [comment]
It is not actually needed, because the CREATE_SCHEMA is working on PACKAGE type.
