### ISSUE TITLE
ORA-24345: A Truncation or null fetch error occurred

### ISSUE THREAD

**Issue by 3kkani** [darold/ora2pg#342]
Hello Darold,

I am encountering issues when migrating NVARCHAR2 columns as reported below. 

The affected columns are mapped in pg with a size which is double of what is defined in oracle, for example RNA.UPI is defined in pg as varchar(26) instead of nvarchar2(13) but it look like the buffer/memory allocated during the copy is not large enough to accommodate the fetched values.

Any clue?

Error examples:

a) 
-- in oracle
  CREATE TABLE "RNACEN"."RNA" 
   (	"ID" NUMBER(15,0), 
	"UPI" NVARCHAR2(13) NOT NULL DISABLE, 
	"TIMESTAMP" DATE, 
	"USERSTAMP" NVARCHAR2(30), 
	"CRC64" CHAR(16 BYTE), 
	"LEN" NUMBER(6,0), 
	"SEQ_SHORT" VARCHAR2(4000 BYTE), 
	"SEQ_LONG" CLOB, 
	"MD5" NVARCHAR2(32), 
	 CONSTRAINT "RNA$UPI" PRIMARY KEY ("UPI")
  USING INDEX 
   ) 
 LOB ("SEQ_LONG") STORE AS BASICFILE (
  TABLESPACE "RNACEN_TAB" ENABLE STORAGE IN ROW CHUNK 16384 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

-- in pg
CREATE TABLE rna (
        id bigint,
        upi varchar(26) NOT NULL,
        timestamp timestamp,
        userstamp varchar(60),
        crc64 char(16),
        len integer,
        seq_short varchar(4000),
        seq_long text,
        md5 varchar(64)
) ;

DBD::Oracle::st fetchrow_array failed: ORA-24345: A Truncation or null fetch error occurred (DBD ERROR: ORA-01406 error on field 2 of 9, ora_type 1)
ORA-24345: A Truncation or null fetch error occurred (DBD ERROR: ORA-01406 error on field 9 of 9, ora_type 1) [for Statement "SELECT "ID","UPI","TIMESTAMP","USERSTAMP","CRC64","LEN","SEQ_SHORT",CASE WHEN dbms_lob.getlength("SEQ_LONG") = 0 THEN NULL ELSE "SEQ_LONG" END,"MD5" FROM "RNACEN"."RNA" a"] at /usr/share/perl5/vendor_perl/Ora2Pg.pm line 11187.

b)
-- in oracle
  CREATE TABLE "RNACEN"."RNC_ACCESSIONS" 
   (	"ID" NUMBER(15,0), 
	"ACCESSION" NVARCHAR2(100) NOT NULL ENABLE, 
	"PARENT_AC" NVARCHAR2(100), 
	"SEQ_VERSION" NUMBER, 
	"FEATURE_START" NUMBER, 
	"FEATURE_END" NUMBER, 
	"FEATURE_NAME" NVARCHAR2(40), 
	"ORDINAL" NUMBER, 
	"DIVISION" NVARCHAR2(3), 
	"KEYWORDS" NVARCHAR2(100), 
	"DESCRIPTION" NVARCHAR2(250), 
	"SPECIES" NVARCHAR2(150), 
	"ORGANELLE" NVARCHAR2(100), 
	"CLASSIFICATION" NVARCHAR2(500), 
	"PROJECT" NVARCHAR2(50), 
	"IS_COMPOSITE" NVARCHAR2(1), 
	"NON_CODING_ID" NVARCHAR2(100), 
	"DATABASE" NVARCHAR2(20), 
	"EXTERNAL_ID" NVARCHAR2(150), 
	"OPTIONAL_ID" NVARCHAR2(100), 
	"COMMON_NAME" NVARCHAR2(100), 
	"ALLELE" NVARCHAR2(50), 
	"ANTICODON" NVARCHAR2(100), 
	"CHROMOSOME" NVARCHAR2(100), 
	"EXPERIMENT" NVARCHAR2(500), 
	"FUNCTION" NVARCHAR2(2000), 
	"GENE" NVARCHAR2(100), 
	"GENE_SYNONYM" NVARCHAR2(400), 
	"INFERENCE" NVARCHAR2(300), 
	"LOCUS_TAG" NVARCHAR2(50), 
	"MAP" NVARCHAR2(200), 
	"MOL_TYPE" NVARCHAR2(50), 
	"NCRNA_CLASS" NVARCHAR2(50), 
	"NOTE" NVARCHAR2(1500), 
	"OLD_LOCUS_TAG" NVARCHAR2(100), 
	"OPERON" NVARCHAR2(50), 
	"PRODUCT" NVARCHAR2(300), 
	"PSEUDOGENE" NVARCHAR2(50), 
	"STANDARD_NAME" NVARCHAR2(100), 
	"DB_XREF" NVARCHAR2(100), 
	 CONSTRAINT "RNC_ACCESSIONS$ACCESSION$PK" PRIMARY KEY ("ACCESSION")
  USING INDEX
   );

-- in pg
CREATE TABLE rnc_accessions (
        id bigint,
        accession varchar(200) NOT NULL,
        parent_ac varchar(200),
        seq_version bigint,
        feature_start bigint,
        feature_end bigint,
        feature_name varchar(80),
        ordinal bigint,
        division varchar(6),
        keywords varchar(200),
        description varchar(500),
        species varchar(300),
        organelle varchar(200),
        classification varchar(1000),
        project varchar(100),
        is_composite varchar(2),
        non_coding_id varchar(200),
        database varchar(40),
        external_id varchar(300),
        optional_id varchar(200),
        common_name varchar(200),
        allele varchar(100),
        anticodon varchar(200),
        chromosome varchar(200),
        experiment varchar(1000),
        function varchar(4000),
        gene varchar(200),
        gene_synonym varchar(800),
        inference varchar(600),
        locus_tag varchar(100),
        map varchar(400),
        mol_type varchar(100),
        ncrna_class varchar(100),
        note varchar(3000),
        old_locus_tag varchar(200),
        operon varchar(100),
        product varchar(600),
        pseudogene varchar(100),
        standard_name varchar(200),
        db_xref varchar(200)
) ;

DBD::Oracle::st fetchall_arrayref failed: ORA-24345: A Truncation or null fetch error occurred (DBD ERROR: ORA-01406 error on field 9 of 40, ora_type 1)
ORA-24345: A Truncation or null fetch error occurred (DBD ERROR: ORA-01406 error on field 16 of 40, ora_type 1) [for Statement "SELECT "ID","ACCESSION","PARENT_AC","SEQ_VERSION","FEATURE_START","FEATURE_END","FEATURE_NAME","ORDINAL","DIVISION","KEYWORDS","DESCRIPTION","SPECIES","ORGANELLE","CLASSIFICATION","PROJECT","IS_COMPOSITE","NON_CODING_ID","DATABASE","EXTERNAL_ID","OPTIONAL_ID","COMMON_NAME","ALLELE","ANTICODON","CHROMOSOME","EXPERIMENT","FUNCTION","GENE","GENE_SYNONYM","INFERENCE","LOCUS_TAG","MAP","MOL_TYPE","NCRNA_CLASS","NOTE","OLD_LOCUS_TAG","OPERON","PRODUCT","PSEUDOGENE","STANDARD_NAME","DB_XREF" FROM "RNACEN"."RNC_ACCESSIONS" a"] at /usr/share/perl5/vendor_perl/Ora2Pg.pm line 11149.

Oracle NLS settings are as follow:

PARAMETER,VALUE
NLS_LANGUAGE,ENGLISH
NLS_TERRITORY,UNITED KINGDOM
NLS_CURRENCY,#
NLS_ISO_CURRENCY,UNITED KINGDOM
NLS_NUMERIC_CHARACTERS,.,
NLS_CHARACTERSET,AL32UTF8
NLS_CALENDAR,GREGORIAN
NLS_DATE_FORMAT,DD-MON-RR
NLS_DATE_LANGUAGE,ENGLISH
NLS_SORT,BINARY
NLS_TIME_FORMAT,HH24.MI.SSXFF
NLS_TIMESTAMP_FORMAT,DD-MON-RR HH24.MI.SSXFF
NLS_TIME_TZ_FORMAT,HH24.MI.SSXFF TZR
NLS_TIMESTAMP_TZ_FORMAT,DD-MON-RR HH24.MI.SSXFF TZR
NLS_DUAL_CURRENCY,?
NLS_COMP,BINARY
NLS_LENGTH_SEMANTICS,BYTE
NLS_NCHAR_CONV_EXCP,FALSE
NLS_NCHAR_CHARACTERSET,AL16UTF16
NLS_RDBMS_VERSION,11.2.0.3.0

ora2pg NLS config is:
NLS_LANG        AMERICAN_AMERICA.AL32UTF8
NLS_NCHAR       AL16UTF16
CLIENT_ENCODING UTF8

Many thanks.
Maurizio.

**Comment by darold** [comment]
Hi Maurizio,

As the error shows the issue is an Oracle problem, it is not related to Ora2Pg or the size of the destination field in PostgreSQL.
```
 DBD::Oracle::st fetchall_arrayref failed: ORA-24345: A Truncation or null fetch error occurred (DBD ERROR: ORA-01406 error on field 9 of 40, ora_type 1)
```

Most of the time this issue is due to change in the length of a column (for table RNC_ACCESSIONS this is column 9: `"DIVISION" NVARCHAR2(3)`),  the column underlying had data more than 3 characters resulting in this error.

I don't know how it is possible, but this is Oracle. As a solution you might try to increase the column size to the previous value or an higher value if you don't know.

Please give a try to this solution and let me know. You can limit the export to the related table by using option `-a RNC_ACCESSIONS` to the ora2pg command.

Regards,

**Comment by darold** [comment]
And Maurizio, are you sure you need to double the size of the PostgreSQL field? In your example you transform nvarchar2(13) to varchar(26) in PostgreSQL but I don't see any reason to do that, all of our varchar or text data types are multibyte-capable in PostgreSQL.

**Comment by 3kkani** [comment]
Hi Darold,

thanks for the quick answers. The column size in pg has been determined by ora2pg. I tried already as you were suggesting to increase it by 10% with no success. 

I can see in oracle the content of the column is actually 26 bytes long which as far as I know is compliant with NLS_NCHAR_CHARACTERSET,AL16UTF16 (fixed length, two bytes for each character)

For example:

`select 
        upi, dump(upi), lengthb (upi), length (upi), upi_2, dump(upi_2), lengthb (upi_2), length (upi_2)
  from (
  select upi, userstamp, md5, 
         cast (upi as varchar2 (15)) upi_2, cast (userstamp as varchar2 (30)) userstamp_2, cast (md5 as varchar2 (32)) md5_2
    from (SELECT distinct upi, userstamp, md5 FROM rnacen.rna)
   where rownum <= 5
  );
`

is returning:

"UPI","DUMP(UPI)","LENGTHB(UPI)","LENGTH(UPI)","UPI_2","DUMP(UPI_2)","LENGTHB(UPI_2)","LENGTH(UPI_2)"
"URS0000000001","Typ=1 Len=26: 0,85,0,82,0,83,0,48,0,48,0,48,0,48,0,48,0,48,0,48,0,48,0,48,0,49",26,13,"URS0000000001","Typ=1 Len=13: 85,82,83,48,48,48,48,48,48,48,48,48,49",13,13
"URS0000000002","Typ=1 Len=26: 0,85,0,82,0,83,0,48,0,48,0,48,0,48,0,48,0,48,0,48,0,48,0,48,0,50",26,13,"URS0000000002","Typ=1 Len=13: 85,82,83,48,48,48,48,48,48,48,48,48,50",13,13
"URS0000000003","Typ=1 Len=26: 0,85,0,82,0,83,0,48,0,48,0,48,0,48,0,48,0,48,0,48,0,48,0,48,0,51",26,13,"URS0000000003","Typ=1 Len=13: 85,82,83,48,48,48,48,48,48,48,48,48,51",13,13
"URS0000000004","Typ=1 Len=26: 0,85,0,82,0,83,0,48,0,48,0,48,0,48,0,48,0,48,0,48,0,48,0,48,0,52",26,13,"URS0000000004","Typ=1 Len=13: 85,82,83,48,48,48,48,48,48,48,48,48,52",13,13
"URS0000000005","Typ=1 Len=26: 0,85,0,82,0,83,0,48,0,48,0,48,0,48,0,48,0,48,0,48,0,48,0,48,0,53",26,13,"URS0000000005","Typ=1 Len=13: 85,82,83,48,48,48,48,48,48,48,48,48,53",13,13


Regards.
Maurizio.

**Comment by darold** [comment]
Ok, I've forgotten the UTF16 case, ora2pg use the internal char length returned by Oracle.

About error ORA-24345 I have no really solution. Have you tried to set LONGREADLEN to a higher value in ora2Pg.conf?

**Comment by darold** [comment]
Can you give me the result of the following command:
```
ora2pg -c config/ora2pg.conf -t SHOW_ENCODING
```
Can you also try the export by disabling NLS_LANG and NLS_NCHAR in the ora2pg.conf file?

**Comment by 3kkani** [comment]
The export w/o NLS setting seems to be working (at least so far) but it will take time to complete. 

As far as I can see both ora2pg and perl are using NLS_NCHAR AL32UTF8 with this configuration.

Might be the issue is related with perl using NLS_NCHAR AL32UTF8 instead of NLS_NCHAR AL16UTF16 with NLS settings enabled in ora2pg?

**Comment by darold** [comment]
If you don't change NLS_LANG and/or NLS_NCHAR Ora2Pg will use the default settings in your Oracle database which seems to be:
```
NLS_LANG AMERICAN_AMERICA.AL32UTF8
NLS_NCHAR AL32UTF8
```

The fact that you have forced NLS_NCHAR to AL32UTF8 seems to be the source of this issue. 

I will think about removing these configuration directives as many user think it must be set but this not recommended at all unless you want to use a specific encoding.

**Comment by 3kkani** [comment]
Hello Darold,

the export w/o any NLS setting in ora2pg config finished w/o any error but I have not checked the data yet. 

As I mentioned initially I have configured NLS in ora2pg as they were reported by:

`select * from nls_database_parameters where parameter in ('NLS_CHARACTERSET', 'NLS_NCHAR_CHARACTERSET');`

i.e.

"PARAMETER","VALUE"
"NLS_CHARACTERSET","AL32UTF8"
"NLS_NCHAR_CHARACTERSET","AL16UTF16"

with those settings SHOW_ENCODE reported for ora2pg

Oracle NLS_NCHAR AL16UTF16

and for perl

Oracle NLS_NCHAR AL32UTF8

while all the remaining parameters were identical. This mismatch (like perl not sensing the ora2pg NLS_NCHAR setting) might be the cause of the errors?

I think NLS settings in ora2pg have been useful for us when migrating from non-default character sets.

Regards.
Maurizio.

**Comment by 3kkani** [comment]
Hello Darold,

we have not yet finished the checking of those NVARCHAR2 columns were it would be more likely to have national characters but so far the migrated data seems ok.

It is not completely clear to me why we should not specify the NLS settings of the oracle DB but thanks for looking into this and helping us solving the issue.

Regards.
Maurizio.
