### ISSUE TITLE
strange comma formatting

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#343]
Hi, I don't know if it is feature or bug

Ora2pg result:
<pre>
, A10.NAZEV AS NAZSPRAVCE,
  A3.NAJMENO , A3.POZNAMKA AS POZNAMKA_CCLE
, MT.ID_OSOB, MT.PLATNOST_OD, MT.PLATNOST_DO
, MT.IDENT, MT.POZNAMKA, MT.BLOKOVANO
, MT.NAZEV, TO_CHAR(MT.DATVYR,'HH24:MI:SS') as CAS_DATVYR, MT.DATVYR
, MT.CVZNIKRADK, MT.ID_ASPRAVCE, A3.ID_CCLE
, MT.ID_SSSLOGIN, MT.ID_APROVOZNA, CASE WHEN A5.ID_SSSLOGIN IS NULL THEN MT.IDENT  ELSE A5.JMENO  END LIDENT_JMENO
, MT.LIDENT, TO_CHAR(MT.DATZMENY,'HH24:MI:SS') as CAS_DATZMENY, MT.DATZMENY
, A6.JMENO as LIDENT_ZMENA_JMENO, MT.LIDENT_ZMENA, A7.J1_NAZEV as NAZEV_CSKUPINA
, A8.ULICE , A8.CISPOP , A8.CISORI ,
  A8.ZNAKCISORI , A9.OBEC AS MISTO,.
</pre>

What is strange - a space around comma, and begin line with comma.

Expected:
<pre>
  xxx, xxxx, xxxx, xxx,
  yyyyy, xxxx, xxxxx, xxxx,
  xxx
</pre>

**Comment by darold** [comment]
Hi Pavel,

Ora2Pg doesn't pay any attention to code formatting, this is an other complex work that I don't want to include in the translation work, actual Ora2Pg code is dirty enough :-D

I'm currently working on adding plpgsql code formatting to pgFormatter ( http://sqlformat.darold.net/ ) , the goal is to include call to pgFormatter into ora2pg to format all code generated by ora2pg.

I hope to terminate the job this week.

**Comment by okbob** [comment]
ok, understand
