### ISSUE TITLE
type in CAST clause is not translated to PostgreSQL type

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#344]
The expression `CAST(MT.JMENO_OKNO AS NUMBER(20) )) AS ID_SSSSLEDUJ` is not correctly translated to Postgres: got `CAST(MT.JMENO_OKNO AS NUMBER(20)`, expected `CAST(MT.JMENO_OKNO AS NUMERIC(20)`.

Original view:
<pre>
CREATE OR REPLACE VIEW IDES_JMMAJ.V_SSSFUNEV AS
select  MT.ID_SSSFUNEV, MT.PID_FCE,
  COALESCE(MT.ID_SSSSLEDUJ,CAST(MT.JMENO_OKNO AS NUMBER(20) )) AS ID_SSSSLEDUJ
, MT.ID_SSSLOGIN, A2.JMENO AS STARTER
, MT.ID_SSSRAJON
, A3.KOD_RAJ , A3.NAZEV AS NAZEV_RAJON
, MT.ID_STROM
, MT.TYP_FCE, MT.SKUP_FCE, MT.STAV_FCE
, MT.PRIOR_FCE, MT.STOP_FCE, MT.KOD_FCE
, MT.NAZEV_FCE, MT.PODM_FCE, MT.PARAM_FCE
, MT.ERROR_FCE, MT.POCZAZ_FCE
, MT.DAT_START AS DAT_START_FCE
, TO_DATE(MT.DAT_KONEC_FCE , 'DD.MM.YYYY') AS DAT_KONEC_FCE
, TO_CHAR(MT.DAT_START_FCE,'DD.MM.YYYY HH24:MI:SS') AS SDAT_START_FCE
, MT.DAT_START_FCE_HOD
, MT.DAT_START_FCE_MIN
, MT.DAT_START_FCE_SS
, TO_CHAR(MT.DAT_KONEC_FCE,'DD.MM.YYYY HH24:MI:SS') AS SDAT_KONEC_FCE
, MT.DAT_KONEC_FCE_HOD
, MT.DAT_KONEC_FCE_MIN
, MT.DAT_KONEC_FCE_SS
, MT.DOBA_FCE, MT.DOBA_FCE_HOD
, MT.DOBA_FCE_MIN,MT.DOBA_FCE_SEK, MT.POZNAMKA, MT.ZOBRAZOVAT
, MT.BLOKOVANO, MT.CVZNIKRADK, MT.GRUPPA
, MT.IDENT, MT.PLATNOST_OD, MT.PLATNOST_DO
, TO_CHAR(MT.DATVYR,'HH24:MI:SS') as CAS_DATVYR, MT.DATVYR
, DECODE(A5.ID_SSSLOGIN,NULL,MT.IDENT,A5.JMENO ) as LIDENT_JMENO
, MT.LIDENT, A6.JMENO as LIDENT_ZMENA_JMENO, MT.LIDENT_ZMENA
, TO_CHAR(MT.DATZMENY,'HH24:MI:SS') as CAS_DATZMENY
, MT.DATZMENY, MT.A1
, MT.PRENOS_SUMA, MT.IP_ADRESA, MT.IP_ADRESA_PROXY
, MT.HTTP_USER_AGENT, MT.JMENO_OKNO AS JMENO_OKNO_LOGIN, MT.ID_ASPRAVCE
, MT.ID_APROVOZNA, A7.J1_NAZEV as NAZEV_CSKUPINA
, MT.ID_SKUP_CISEL
, A9.NAZEV AS NAZSPRAVCE,  A8.NAZEV AS NAZPROVO,
LOAD1,LOAD5,LOAD15,MEM_FREE,SWAP_FREE
 from SSSFUNEV MT , SSSSLEDUJ A1
    , SSSLOGIN A2, SSSRAJON A3
    , SSS_STROM A4, SSSLOGIN A5
    , SSSLOGIN A6, CSKUPINA A7
    , UDRPROVO A8 , UDRSPRVC A9
 where MT.ID_SSSSLEDUJ= A1.ID_SSSSLEDUJ(+)
 AND MT.ID_SSSLOGIN= A2.ID_SSSLOGIN(+)
 AND MT.ID_SSSRAJON= A3.ID_SSSRAJON(+)
 AND MT.ID_STROM= A4.ID_STROM(+)
 AND MT.LIDENT= A5.ID_SSSLOGIN(+)
 AND MT.LIDENT_ZMENA= A6.ID_SSSLOGIN(+)
 AND MT.ID_SKUP_CISEL= A7.ID_SKUP_CISEL(+)
 AND MT.ID_APROVOZNA = A8.ID_PROVOZNA(+)
 AND MT.ID_ASPRAVCE = A9.ID_SPRAVCE(+)
</pre>

**Comment by darold** [comment]
Might be solved by commit f1413ce.

**Comment by okbob** [comment]
it is fixed
