### ISSUE TITLE
DECODE is translated to CASE and keyword `AS` is lost

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#345]
Ora2pg is too hungry and don't pass `AS` keyword before column name in this case. Usually it is not a problem, but the `AS` keyword is missing when column name is unreserved PostgreSQL keyword - see:

<pre>
streda_0329=# select 1 text;
ERROR:  syntax error at or near "text"
ŘÁDKA 2: select 1 text;
                  ^
Čas: 0,218 ms
streda_0329=# select 1 as text;
┌──────┐
│ text │
╞══════╡
│    1 │
└──────┘
(1 řádka)

Čas: 0,598 ms
</pre>

Original:
<pre>
CREATE OR REPLACE VIEW IDES_JMMAJ.V_NAJPARZAV AS
SELECT MT.ID_NAJPARZAV , MT.ID_NAJPARNAJ , MT.PLATNOST_OD , 
            MT.PLATNOST_DO , MT.POZNAMKA , 
            MT.IDENT , MT.BLOKOVANO , 
            MT.STAVFUNKCE , MT.AKTUAL_DEMON , MT.ZIV , MT.NAZEVFUN , 
            MT.ZDROJFUN , 
            MT.DATVYR , MT.PORADI , 
            MT.FUNRUN , MT.CVZNIKRADK , 
            MT.ID_ASPRAVCE , MT.ID_APROVOZNA , 
            MT.LIDENT ,  DECODE( A1.ID_SSSLOGIN,NULL,MT.IDENT,A1.JMENO)AS LIDENT_JMENO,
            MT.DATZMENY , 
            TO_CHAR(MT.DATVYR,'HH24:MI:SS') AS CAS_DATVYR,
            TO_CHAR(MT.DATZMENY,'HH24:MI:SS') AS CAS_DATZMENY,  
            MT.LIDENT_ZMENA ,A2.JMENO AS LIDENT_ZMENA_JMENO,
            MT.ID_APROVOZNA AS ID_PROVOZNA
       FROM NAJPARZAV MT ,
            SSSLOGIN A1,SSSLOGIN A2
    WHERE MT.LIDENT= A1.ID_SSSLOGIN(+)
    AND MT.LIDENT_ZMENA = A2.ID_SSSLOGIN(+)
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE VIEW v_najparzav (id_najparzav, id_najparnaj, platnost_od, platnost_do, poznamka, ident, blokovano, stavfunkce, aktual_demon, ziv, nazevfun, zdrojfun, datvyr, poradi, funrun, cvznikradk, id_aspravce, id_aprovozna, lident, lident_jmeno, datzmeny, cas_datvyr, cas_datzmeny, lident_zmena, lident_zmena_jmeno, id_provozna) AS SELECT  MT.ID_NAJPARZAV , MT.ID_NAJPARNAJ , MT.PLATNOST_OD ,
            MT.PLATNOST_DO , MT.POZNAMKA ,
            MT.IDENT , MT.BLOKOVANO ,
            MT.STAVFUNKCE , MT.AKTUAL_DEMON , MT.ZIV , MT.NAZEVFUN ,
            MT.ZDROJFUN ,
            MT.DATVYR , MT.PORADI ,
            MT.FUNRUN , MT.CVZNIKRADK ,
            MT.ID_ASPRAVCE , MT.ID_APROVOZNA ,
            MT.LIDENT ,  CASE WHEN  A1.ID_SSSLOGIN IS NULL THEN MT.IDENT  ELSE A1.JMENO END LIDENT_JMENO,
            MT.DATZMENY ,
            TO_CHAR(MT.DATVYR,'HH24:MI:SS') AS CAS_DATVYR,
            TO_CHAR(MT.DATZMENY,'HH24:MI:SS') AS CAS_DATZMENY,
            MT.LIDENT_ZMENA ,A2.JMENO AS LIDENT_ZMENA_JMENO,
            MT.ID_APROVOZNA AS ID_PROVOZNA
        FROM najparzav mt
LEFT OUTER JOIN ssslogin a1 ON (MT.LIDENT = A1.ID_SSSLOGIN)
LEFT OUTER JOIN ssslogin a2 ON (MT.LIDENT_ZMENA = A2.ID_SSSLOGIN);
</pre>

**Comment by darold** [comment]
Solved in commit 6117e07

**Comment by okbob** [comment]
it is fixed
