### ISSUE TITLE
missing subselect

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#346]
Oracle:
<pre>
CREATE OR REPLACE VIEW IDES_JMMAJ.V_UCEOBDOBI_UPAPOHYB_56 AS
SELECT
     "ID_RGRID",
    "ID_CISUJEDN",
    "ID_UCEOBDOBI",
    "ID_UPAPUCET",
    "ID_UCEPOHYB",
    "ID_UPAPOHYB",
    "ID_UPAPOBRT",
    "KOD_UPAPUCET",
    "AKT_PAS",
    "RAD",
    "UCEKOD",
    "UCEDOK",
    "UCEPOL",
    "UCEMES",
    "UTEXT",
    "ID_CCLE_PAR_TR",
     case
       when KVYK_PAP='A' and PAR_444='A' and icopap is not null AND ICOPAP_KV=0 then 444
       when KVYK_PAP='A' and PAR_444='A' and icopap is not null AND ICOPAP_KV=1 then ICOPAP
      else ICOPAP
     end AS ICOPAP,
    "EPOL_CASTKA",
    "STRANA",
    "KOD_CISUJEDN",
    "NAZEV_CISUJEDN",
    "UCEROK",
    "NAZSPRAVCE",
    "NAZPROVOZNA",
    "ID_ASPRAVCE",
    "ID_APROVOZNA",
    "PLATNOST_OD",
    "PLATNOST_DO",
    "KVYK_PAP",
    "PAR_444",
    "ICOPAP_KV"
  FROM
    (
    SELECT 0 AS ID_RGRID,
      A8.ID_CISUJEDN,
      A8.ID_UCEOBDOBI,
      MT.ID_UPAPUCET_M AS ID_UPAPUCET,
      MT.ID_UCEPOHYB AS ID_UCEPOHYB,
      MT.ID_UPAPOHYB AS ID_UPAPOHYB,
      0 AS ID_UPAPOBRT,
      trim(A1.KOD_UPAPUCET) AS KOD_UPAPUCET,
      UPAPUCET_AKT_PAS(MT.ID_UPAPUCET_M,A8.ID_UCEOBDOBI) AS AKT_PAS,
      '2' AS RAD,
      trim(A8.UCEKOD) AS UCEKOD,
      A8.UCEDOK,
      A8.UCEPOL,
      A8.UCEMES,
      A8.POZNAMKA AS UTEXT,
      MT.ID_CCLE_M_PAR_TR AS ID_CCLE_PAR_TR,
      DECODE(A2.osobfirm,'O',111,A2.rodcisico) AS ICOPAP,
      (
      CASE
        WHEN UPAPUCET_AKT_PAS(MT.ID_UPAPUCET_M,A8.ID_UCEOBDOBI) = 'A'
        THEN NVL(A8.epol_castka, 0)
        ELSE NVL(A8.epol_castka, 0)
      END ) AS epol_castka,
      'M' AS strana,
      trim(A3.KOD_CISUJEDN) AS KOD_CISUJEDN ,
      trim(A3.J1_nazev) AS NAZEV_CISUJEDN,
      TO_NUMBER(TO_CHAR(A8.UCEMES,'YYYY')) AS UCEROK,
      trim(A6.NAZEV) AS NAZSPRAVCE ,
      trim(A7.NAZEV) AS NAZPROVOZNA ,
      MT.ID_ASPRAVCE,
      MT.ID_APROVOZNA,
      MT.PLATNOST_OD,
      MT.PLATNOST_DO,
      A3.KVYK_PAP , GET_PAR_444(A1.ID_UPAPUCET) AS PAR_444,
      --(SELECT count(1) FROM UPAPICOKV b1 WHERE rownum<2 and to_number(trim(b1.ICO))=to_number(trim(DECODE(A2.osobfirm,'O','',A2.rodcisico)))) as ICOPAP_KV
      (SELECT count(1) FROM UPAPICOKV b1 WHERE rownum<2 and to_number(trim(b1.ICO))=to_number(trim(DECODE(A2.osobfirm,'O',NULL,A2.rodcisico)))) as ICOPAP_KV
    FROM UPAPOHYB MT,
      UPAPUCET A1,
      CLEOSOBY A2,
      UCEPOHYB A8,
      CISUJEDN A3,
      UCEOBDOBI A4,
      UDRSPRVC A6,
      UDRPROVO A7
    WHERE MT.ID_UPAPUCET_M =A1.ID_UPAPUCET(+)
    AND A8.ID_CISUJEDN = A3.ID_CISUJEDN(+)
    AND A8.ID_UCEOBDOBI = A4.ID_UCEOBDOBI(+)
    AND MT.ID_ASPRAVCE = A6.ID_SPRAVCE(+)
    AND MT.ID_APROVOZNA = A7.ID_PROVOZNA(+)
    AND MT.ID_CCLE_M_PAR_TR =A2.ID_CCLE(+)
    AND MT.ID_UCEPOHYB =A8.ID_UCEPOHYB(+)
    AND substr(trim(A1.kod_upapucet),1,1) in('5','6')
    UNION ALL
    SELECT 0 AS ID_RGRID,
      A8.ID_CISUJEDN,
      A8.ID_UCEOBDOBI,
      MT.ID_UPAPUCET_D AS ID_UPAPUCET,
      MT.ID_UCEPOHYB AS ID_UCEPOHYB,
      MT.ID_UPAPOHYB AS ID_UPAPOHYB,
      0 AS ID_UPAPOBRT,
      trim(A1.KOD_UPAPUCET) AS KOD_UPAPUCET,
      UPAPUCET_AKT_PAS(MT.ID_UPAPUCET_D,A8.ID_UCEOBDOBI) AS AKT_PAS,
      '2' AS RAD,
      trim(A8.UCEKOD) AS UCEKOD,
      A8.UCEDOK,
      A8.UCEPOL,
      A8.UCEMES,
      A8.POZNAMKA AS UTEXT,
      MT.ID_CCLE_D_PAR_TR AS ID_CCLE_PAR_TR,
      DECODE(A2.osobfirm,'O',111,A2.rodcisico) AS ICOPAP,
      (
      CASE
        WHEN UPAPUCET_AKT_PAS(MT.ID_UPAPUCET_D,A8.ID_UCEOBDOBI) = 'P'
        THEN NVL(A8.epol_castka, 0)
        ELSE NVL(A8.epol_castka, 0)
      END ) AS epol_castka,
      'D' AS strana,
      trim(A3.KOD_CISUJEDN) AS KOD_CISUJEDN ,
      trim(A3.J1_nazev) AS NAZEV_CISUJEDN,
      TO_NUMBER(TO_CHAR(A8.UCEMES,'YYYY')) AS UCEROK,
      trim(A6.NAZEV) AS NAZSPRAVCE ,
      trim(A7.NAZEV) AS NAZPROVOZNA ,
      MT.ID_ASPRAVCE,
      MT.ID_APROVOZNA,
      MT.PLATNOST_OD,
      MT.PLATNOST_DO,
      A3.KVYK_PAP, GET_PAR_444(A1.ID_UPAPUCET) AS PAR_444,
      ---(SELECT count(1) FROM UPAPICOKV b1 WHERE rownum<2 and to_number(trim(b1.ICO))=to_number(trim(DECODE(A2.osobfirm,'O','',A2.rodcisico)))) as ICOPAP_KV
      (SELECT count(1) FROM UPAPICOKV b1 WHERE rownum<2 and to_number(trim(b1.ICO))=to_number(trim(DECODE(A2.osobfirm,'O',NULL,A2.rodcisico)))) as ICOPAP_KV
    FROM UPAPOHYB MT,
      UPAPUCET A1,
      CLEOSOBY A2,
      UCEPOHYB A8,
      CISUJEDN A3,
      UCEOBDOBI A4,
      UDRSPRVC A6,
      UDRPROVO A7
    WHERE MT.ID_UPAPUCET_D =A1.ID_UPAPUCET(+)
    AND A8.ID_CISUJEDN = A3.ID_CISUJEDN(+)
    AND A8.ID_UCEOBDOBI = A4.ID_UCEOBDOBI(+)
    AND MT.ID_ASPRAVCE = A6.ID_SPRAVCE(+)
    AND MT.ID_APROVOZNA = A7.ID_PROVOZNA(+)
    AND MT.ID_CCLE_D_PAR_TR =A2.ID_CCLE(+)
    AND MT.ID_UCEPOHYB =A8.ID_UCEPOHYB(+)
    AND substr(trim(A1.kod_upapucet),1,1) in('5','6')
    )
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE VIEW v_uceobdobi_upapohyb_56 (id_rgrid, id_cisujedn, id_uceobdobi, id_upapucet, id_ucepohyb, id_upapohyb, id_upapobrt, kod_upapucet, akt_pas, rad, ucekod, ucedok, ucepol, ucemes, utext, id_ccle_par_tr, icopap, epol_castka, strana, kod_cisujedn, nazev_cisujedn, ucerok, nazspravce, nazprovozna, id_aspravce, id_aprovozna, platnost_od, platnost_do, kvyk_pap, par_444, icopap_kv) AS SELECT.
     "id_rgrid",
    "id_cisujedn",
    "id_uceobdobi",
    "id_upapucet",
    "id_ucepohyb",
    "id_upapohyb",
    "id_upapobrt",
    "kod_upapucet",
    "akt_pas",
    "rad",
    "ucekod",
    "ucedok",
    "ucepol",
    "ucemes",
    "utext",
    "id_ccle_par_tr",
     case
       when KVYK_PAP='A' and PAR_444='A' and icopap is not null AND ICOPAP_KV=0 then 444
       when KVYK_PAP='A' and PAR_444='A' and icopap is not null AND ICOPAP_KV=1 then ICOPAP
      else ICOPAP
     END ICOPAP,
    "epol_castka",
    "strana",
    "kod_cisujedn",
    "nazev_cisujedn",
    "ucerok",
    "nazspravce",
    "nazprovozna",
    "id_aspravce",
    "id_aprovozna",
    "platnost_od",
    "platnost_do",
    "kvyk_pap",
    "par_444",
    "icopap_kv"
   FROM
    (
    SELECT 0 AS ID_RGRID,
      A8.ID_CISUJEDN,
      A8.ID_UCEOBDOBI,
      MT.ID_UPAPUCET_M AS ID_UPAPUCET,
      MT.ID_UCEPOHYB AS ID_UCEPOHYB,
      MT.ID_UPAPOHYB AS ID_UPAPOHYB,
      0 AS ID_UPAPOBRT,
      btrim(A1.KOD_UPAPUCET) AS KOD_UPAPUCET,
      UPAPUCET_AKT_PAS(MT.ID_UPAPUCET_M,A8.ID_UCEOBDOBI) AS AKT_PAS,
      '2' AS RAD,
      btrim(A8.UCEKOD) AS UCEKOD,
      A8.UCEDOK,
      A8.UCEPOL,
      A8.UCEMES,
      A8.POZNAMKA AS UTEXT,
      MT.ID_CCLE_M_PAR_TR AS ID_CCLE_PAR_TR,
      CASE WHEN A2.osobfirm='O' THEN '111'  ELSE A2.rodcisico END ICOPAP,
      (
      CASE
        WHEN UPAPUCET_AKT_PAS(MT.ID_UPAPUCET_M,A8.ID_UCEOBDOBI) = 'A'
        THEN coalesce(A8.epol_castka, 0)
        ELSE coalesce(A8.epol_castka, 0)
      END ) AS epol_castka,
      'M' AS strana,
      btrim(A3.KOD_CISUJEDN) AS KOD_CISUJEDN ,
      btrim(A3.J1_nazev) AS NAZEV_CISUJEDN,
      (TO_CHAR(A8.UCEMES,'YYYY'))::integer AS UCEROK,
      btrim(A6.NAZEV) AS NAZSPRAVCE ,
      btrim(A7.NAZEV) AS NAZPROVOZNA ,
      MT.ID_ASPRAVCE,
      MT.ID_APROVOZNA,
      MT.PLATNOST_OD,
      MT.PLATNOST_DO,
      A3.KVYK_PAP , GET_PAR_444(A1.ID_UPAPUCET) AS PAR_444,
      --(SELECT count(1) FROM UPAPICOKV b1 WHERE (btrim(b1.ICO))::integer=(btrim(CASE WHEN A2.osobfirm='O' THEN ''  ELSE A2.rodcisico END ))::integer LIMIT 1) as ICOPAP_KV(SELECT count(1) FROM UPAPICOKV b1 WHERE (btrim(b1.ICO))::integer=(btrim(CASE WHEN A2.osobfirm='O' THEN NULL  ELSE A2.rodcisico END ))::integer LIMIT 1) as ICOPAP_KV
    FROM upapohyb mt
LEFT OUTER JOIN upapucet a1 ON (MT.ID_UPAPUCET_M = A1.ID_UPAPUCET)
LEFT OUTER JOIN udrsprvc a6 ON (MT.ID_ASPRAVCE = A6.ID_SPRAVCE)
LEFT OUTER JOIN udrprovo a7 ON (MT.ID_APROVOZNA = A7.ID_PROVOZNA)
LEFT OUTER JOIN cleosoby a2 ON (MT.ID_CCLE_M_PAR_TR = A2.ID_CCLE)
LEFT OUTER JOIN ucepohyb a8 ON (MT.ID_UCEPOHYB = A8.ID_UCEPOHYB)
LEFT OUTER JOIN cisujedn a3 ON (A8.ID_CISUJEDN = A3.ID_CISUJEDN)
LEFT OUTER JOIN uceobdobi a4 ON (A8.ID_UCEOBDOBI = A4.ID_UCEOBDOBI)
WHERE substr(btrim(A1.kod_upapucet),1,1) in ('5','6')

UNION ALL

    SELECT 0 AS ID_RGRID,
      A8.ID_CISUJEDN,
      A8.ID_UCEOBDOBI,
      MT.ID_UPAPUCET_D AS ID_UPAPUCET,
      MT.ID_UCEPOHYB AS ID_UCEPOHYB,
      MT.ID_UPAPOHYB AS ID_UPAPOHYB,
      0 AS ID_UPAPOBRT,
      btrim(A1.KOD_UPAPUCET) AS KOD_UPAPUCET,
      UPAPUCET_AKT_PAS(MT.ID_UPAPUCET_D,A8.ID_UCEOBDOBI) AS AKT_PAS,
      '2' AS RAD,
      btrim(A8.UCEKOD) AS UCEKOD,
      A8.UCEDOK,
      A8.UCEPOL,
      A8.UCEMES,
      A8.POZNAMKA AS UTEXT,
      MT.ID_CCLE_D_PAR_TR AS ID_CCLE_PAR_TR,
      CASE WHEN A2.osobfirm='O' THEN '111'  ELSE A2.rodcisico END ICOPAP,
      (
      CASE
        WHEN UPAPUCET_AKT_PAS(MT.ID_UPAPUCET_D,A8.ID_UCEOBDOBI) = 'P'
        THEN coalesce(A8.epol_castka, 0)
        ELSE coalesce(A8.epol_castka, 0)
      END ) AS epol_castka,
      'D' AS strana,
      btrim(A3.KOD_CISUJEDN) AS KOD_CISUJEDN ,
      btrim(A3.J1_nazev) AS NAZEV_CISUJEDN,
      (TO_CHAR(A8.UCEMES,'YYYY'))::integer AS UCEROK,
      btrim(A6.NAZEV) AS NAZSPRAVCE ,
      btrim(A7.NAZEV) AS NAZPROVOZNA ,
      MT.ID_ASPRAVCE,
      MT.ID_APROVOZNA,
      MT.PLATNOST_OD,
      MT.PLATNOST_DO,
      A3.KVYK_PAP, GET_PAR_444(A1.ID_UPAPUCET) AS PAR_444,
      ---(SELECT count(1) FROM UPAPICOKV b1 WHERE (btrim(b1.ICO))::integer=(btrim(CASE WHEN A2.osobfirm='O' THEN ''  ELSE A2.rodcisico END ))::integer LIMIT 1) as ICOPAP_KV(SELECT count(1) FROM UPAPICOKV b1 WHERE (btrim(b1.ICO))::integer=(btrim(CASE WHEN A2.osobfirm='O' THEN NULL  ELSE A2.rodcisico END ))::integer LIMIT 1) as ICOPAP_KV
    FROM upapohyb mt
LEFT OUTER JOIN upapucet a1 ON (MT.ID_UPAPUCET_D = A1.ID_UPAPUCET)
LEFT OUTER JOIN udrsprvc a6 ON (MT.ID_ASPRAVCE = A6.ID_SPRAVCE)
LEFT OUTER JOIN udrprovo a7 ON (MT.ID_APROVOZNA = A7.ID_PROVOZNA)
LEFT OUTER JOIN cleosoby a2 ON (MT.ID_CCLE_D_PAR_TR = A2.ID_CCLE)
LEFT OUTER JOIN ucepohyb a8 ON (MT.ID_UCEPOHYB = A8.ID_UCEPOHYB)
LEFT OUTER JOIN cisujedn a3 ON (A8.ID_CISUJEDN = A3.ID_CISUJEDN)
LEFT OUTER JOIN uceobdobi a4 ON (A8.ID_UCEOBDOBI = A4.ID_UCEOBDOBI)
WHERE substr(btrim(A1.kod_upapucet),1,1) in ('5','6')
     ) alias58;
</pre>

Subselect 
<pre>
(SELECT count(1) FROM UPAPICOKV b1 WHERE rownum<2 and to_number(trim(b1.ICO))=to_number(trim(DECODE(A2.osobfirm,'O',NULL,A2.rodcisico)))) as ICOPAP_KV
</pre> is missing

**Comment by darold** [comment]
Last commit 902c21e might fix this issue and allow export of comments defined in views.

**Comment by okbob** [comment]
it is fixed
