### ISSUE TITLE
missing space between integer and `AS` keyword

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#348]
Oracle:
<pre>
CREATE OR REPLACE VIEW IDES_JMMAJ.V_NAJHPPEPO AS
SELECT MT.ID_NAJHPPEPO ,
    MT.ID_NAJHPPORG ,
    MT.ID_NAJHPPVST ,
    MT.ID_NAJHPPEPR ,
    MT.PLATNOST_OD ,
    MT.PLATNOST_DO ,
    MT.IDENT ,
    MT.POZNAMKA ,
    MT.CASTKA ,
    MT.VARSYM ,
    MT.SPESYM ,
    MT.SAZBA ,
    MT.SAZBA_DOPLN,
    MT.STAV ,
    MT.DATUMPRE ,
    MT.CISLOSUM ,
    MT.UCET_PLAT ,
    MT.KOD_PLAB ,
    MT.CISORG ,
    MT.PORADVDS ,
    MT.KONSYPLAT ,
    MT.OKRESRAZ ,
    MT.UCET_SAZ ,
    MT.KOD_SAZB ,
    MT.KONSYSAZ ,
    MT.PORADI ,
    MT.SPECIFIKACE ,
    MT.DATPOS ,
    MT.TEXTPO ,
    MT.VYPPODM ,
    MT.TERMIN_VYPLATY,
    MT.PRIJEMCE ,
    MT.ULICE_PRIJ ,
    MT.CISPOP_PRIJ ,
    TO_NUMBER(NVL(KOD_TXT_NUMBER(MT.CISPOP_PRIJ),'0'))AS CISPOP_PRIJ1,
    MT.CISORI_PRIJ ,
    TO_NUMBER(NVL(KOD_TXT_NUMBER(MT.CISORI_PRIJ),'0'))AS CISORI_PRIJ1,
    MT.PSC_PRIJ ,
    MT.MESTO_PRIJ ,
    MT.AKOD_OBJEKT ,
    MT.AKOD_SEGMENT ,
    MT.AKOD_BUDOVY ,
    MT.AKOD_PROSTOR ,
    --TO_NUMBER(NVL(MT.AKOD_PROSTOR,0))AS AKOD_PROSTOR1,
    A9.AKOD_PROSTOR AS AKOD_PROSTOR1,
    MT.ABYT_NEBYT,
    A9.ABYT_NEBYT AS ABYT_NEBYT1,
    MT.PRIJEMCE_HL ,
    MT.DATVYR ,
    MT.NAZEV ,
    MT.ID_ASPRAVCE ,
    MT.ID_APROVOZNA ,
    MT.LIDENT ,
    MT.DATZMENY ,
    MT.LIDENT_ZMENA ,
    MT.ID_SKUP_CISEL ,
    MT.ID_NAJPLATBY ,
    A1.NAZEV AS NAZEVORG ,
    A1.CISLOPOD ,
    A2.NAZEV AS NAJHPPEPR ,
    A2.DATPLA,
    A3.UCE_DOKLAD ,
    A4.J1_NAZEV        AS DRUPRE ,
    A5.UCE_DOKLAD      AS UCE_DOKLAD_PUV ,
    A5.DATUM_ZAPLACENI AS DATUM_ZAPLACENI_PUV ,
    MT.ID_NAJVZTAH ,
    MT.ID_CCLE_KON ,
    DECODE(
    (SELECT COUNT(*) FROM NAJVHPPEPO B1 WHERE B1.ID_NAJHPPEPO_A = MT.ID_NAJHPPEPO
    ), 0 , NULL , 'V' ) AS POL_VYS ,
    A6.NAZEV_VYSTUPU ,
    MT.DRUH ,
    MT.OBEC,
    MT.CASTOBCE,
    A2.DATVDS ,
    A2.PORVDS ,
    TO_CHAR(MT.DATVYR,'HH24:MI:SS')                AS CAS_DATVYR,
    TO_CHAR(MT.DATZMENY,'HH24:MI:SS')              AS CAS_DATZMENY,
    DECODE(A7.ID_SSSLOGIN,NULL,MT.IDENT,A7.JMENO ) AS LIDENT_JMENO,
    A8.JMENO                                       AS LIDENT_ZMENA_JMENO,
    A9.ACISPOP                                     AS ACISPOP_DUM,
    A9.ID_ADR,
    A9.ID_CCLE,
    ( SELECT COUNT(*)
     FROM V_NAJVHPPEPO B1
     WHERE B1.ID_NAJHPPEPO=MT.ID_NAJHPPEPO ) AS POC_PLATEB,
     A1.ID_BUCET, A1.ID_BUCET_SAZ,A1.ID_BUCET_POSTA,
     PARBU_UCET(A1.ID_BUCET_POSTA,'PRE') AS UCET_POSTA,
     PARBU_UCET(A1.ID_BUCET,'PRE') AS UCET_PREPL,
     (case
      when A1.ID_BUCET_SAZ IS NOT NULL THEN  PARBU_UCET(A1.ID_BUCET_SAZ,'PRE')
      else PARBU_UCET(A1.ID_BUCET,'PRE')
      end ) AS UCET_SAZBA
  FROM NAJHPPEPO MT ,
    NAJHPPORG A1 , NAJHPPEPR A2 , NAJPLATBY A3 ,
    CISDRPRE A4 , NAJPLATBY A5 ,NAJHPPVYS A6 ,
    SSSLOGIN A7, SSSLOGIN A8 , SSSHLEDEJ_A A9,
    PARBU A51, PARBU A61, PARBU A71
  WHERE MT.ID_NAJHPPORG = A1.ID_NAJHPPORG(+)
  AND MT.ID_NAJHPPEPR   = A2.ID_NAJHPPEPR(+)
  AND MT.ID_NAJPLATBY   = A3.ID_NAJPLATBY(+)
  AND A3.ID_DRUPRE_NEUR = A4.ID_DRUPRE(+)
  AND A3.ID_NAJPLATBY_A = A5.ID_NAJPLATBY(+)
  AND A2.ID_NAJHPPVYS   = A6.ID_NAJHPPVYS(+)
  AND MT.LIDENT         = A7.ID_SSSLOGIN(+)
  AND MT.LIDENT_ZMENA   = A8.ID_SSSLOGIN(+)
  AND MT.ID_NAJVZTAH    = A9.ID_NAJVZTAH(+)
  AND ((A9.TYP            = 'N' ) OR (A9.ID_NAJVZTAH IS NULL))
  AND (( A9.HLAVNI         = 'H' ) OR (A9.ID_NAJVZTAH IS NULL))
  AND A1.ID_BUCET=A51.ID_BUCET(+)
  AND A1.ID_BUCET_SAZ= A61.ID_BUCET(+)
  AND A1.ID_BUCET_POSTA=A71.ID_BUCET(+)
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE VIEW v_najhppepo (id_najhppepo, id_najhpporg, id_najhppvst, id_najhppepr, platnost_od, platnost_do, ident, poznamka, castka, varsym, spesym, sazba, sazba_dopln, stav, datumpre, cislosum, ucet_plat, kod_plab, cisorg, poradvds, konsyplat, okresraz, ucet_saz, kod_sazb, konsysaz, poradi, specifikace, datpos, textpo, vyppodm, termin_vyplaty, prijemce, ulice_prij, cispop_prij, cispop_prij1, cisori_prij, cisori_prij1, psc_prij, mesto_prij, akod_objekt, akod_segment, akod_budovy, akod_prostor, ako
    MT.ID_NAJHPPORG ,
    MT.ID_NAJHPPVST ,
    MT.ID_NAJHPPEPR ,
    MT.PLATNOST_OD ,
    MT.PLATNOST_DO ,
    MT.IDENT ,
    MT.POZNAMKA ,
    MT.CASTKA ,
    MT.VARSYM ,
    MT.SPESYM ,
    MT.SAZBA ,
    MT.SAZBA_DOPLN,
    MT.STAV ,
    MT.DATUMPRE ,
    MT.CISLOSUM ,
    MT.UCET_PLAT ,
    MT.KOD_PLAB ,
    MT.CISORG ,
    MT.PORADVDS ,
    MT.KONSYPLAT ,
    MT.OKRESRAZ ,
    MT.UCET_SAZ ,
    MT.KOD_SAZB ,
    MT.KONSYSAZ ,
    MT.PORADI ,
    MT.SPECIFIKACE ,
    MT.DATPOS ,
    MT.TEXTPO ,
    MT.VYPPODM ,
    MT.TERMIN_VYPLATY,
    MT.PRIJEMCE ,
    MT.ULICE_PRIJ ,
    MT.CISPOP_PRIJ ,
    (coalesce(KOD_TXT_NUMBER(MT.CISPOP_PRIJ),'0'))::integerAS CISPOP_PRIJ1,
    MT.CISORI_PRIJ ,
    (coalesce(KOD_TXT_NUMBER(MT.CISORI_PRIJ),'0'))::integerAS CISORI_PRIJ1, --<<<<<<
    MT.PSC_PRIJ ,
    MT.MESTO_PRIJ ,
    MT.AKOD_OBJEKT ,
    MT.AKOD_SEGMENT ,
    MT.AKOD_BUDOVY ,
    MT.AKOD_PROSTOR ,
    --(coalesce(MT.AKOD_PROSTOR,0))::integerAS AKOD_PROSTOR1,
    A9.AKOD_PROSTOR AS AKOD_PROSTOR1,
    MT.ABYT_NEBYT,
    A9.ABYT_NEBYT AS ABYT_NEBYT1,
    MT.PRIJEMCE_HL ,
    MT.DATVYR ,
    MT.NAZEV ,
    MT.ID_ASPRAVCE ,
    MT.ID_APROVOZNA ,
    MT.LIDENT ,
    MT.DATZMENY ,
    MT.LIDENT_ZMENA ,
    MT.ID_SKUP_CISEL ,
    MT.ID_NAJPLATBY ,
    A1.NAZEV AS NAZEVORG ,
    A1.CISLOPOD ,
    A2.NAZEV AS NAJHPPEPR ,
    A2.DATPLA,
    A3.UCE_DOKLAD ,
    A4.J1_NAZEV        AS DRUPRE ,
    A5.UCE_DOKLAD      AS UCE_DOKLAD_PUV ,
    A5.DATUM_ZAPLACENI AS DATUM_ZAPLACENI_PUV ,
    MT.ID_NAJVZTAH ,
    MT.ID_CCLE_KON ,
    CASE WHEN(SELECT COUNT(*)  FROM NAJVHPPEPO B1 WHERE B1.ID_NAJHPPEPO_A = MT.ID_NAJHPPEPO
    )= 0  THEN  NULL   ELSE  'V'  END  AS POL_VYS ,
    A6.NAZEV_VYSTUPU ,
    MT.DRUH ,
    MT.OBEC,
    MT.CASTOBCE,
    A2.DATVDS ,
    A2.PORVDS ,
    TO_CHAR(MT.DATVYR,'HH24:MI:SS')                AS CAS_DATVYR,
    TO_CHAR(MT.DATZMENY,'HH24:MI:SS')              AS CAS_DATZMENY,
    CASE WHEN A7.ID_SSSLOGIN IS NULL THEN MT.IDENT  ELSE A7.JMENO  END  AS LIDENT_JMENO,
    A8.JMENO                                       AS LIDENT_ZMENA_JMENO,
    A9.ACISPOP                                     AS ACISPOP_DUM,
    A9.ID_ADR,
    A9.ID_CCLE,
    ( SELECT COUNT(*)
     FROM V_NAJVHPPEPO B1
     WHERE B1.ID_NAJHPPEPO=MT.ID_NAJHPPEPO ) AS POC_PLATEB,
     A1.ID_BUCET, A1.ID_BUCET_SAZ,A1.ID_BUCET_POSTA,
     PARBU_UCET(A1.ID_BUCET_POSTA,'PRE') AS UCET_POSTA,
     PARBU_UCET(A1.ID_BUCET,'PRE') AS UCET_PREPL,
     (case
      when A1.ID_BUCET_SAZ IS NOT NULL THEN  PARBU_UCET(A1.ID_BUCET_SAZ,'PRE')
      else PARBU_UCET(A1.ID_BUCET,'PRE')
      end ) AS UCET_SAZBA
  FROM najhppepo mt
LEFT OUTER JOIN najhpporg a1 ON (MT.ID_NAJHPPORG = A1.ID_NAJHPPORG)
LEFT OUTER JOIN najhppepr a2 ON (MT.ID_NAJHPPEPR = A2.ID_NAJHPPEPR)
LEFT OUTER JOIN najplatby a3 ON (MT.ID_NAJPLATBY = A3.ID_NAJPLATBY)
LEFT OUTER JOIN ssslogin a7 ON (MT.LIDENT = A7.ID_SSSLOGIN)
LEFT OUTER JOIN ssslogin a8 ON (MT.LIDENT_ZMENA = A8.ID_SSSLOGIN)
LEFT OUTER JOIN ssshledej_a a9 ON (MT.ID_NAJVZTAH = A9.ID_NAJVZTAH)
LEFT OUTER JOIN parbu a51 ON (A1.ID_BUCET = A51.ID_BUCET)
LEFT OUTER JOIN parbu a61 ON (A1.ID_BUCET_SAZ = A61.ID_BUCET)
LEFT OUTER JOIN parbu a71 ON (A1.ID_BUCET_POSTA = A71.ID_BUCET)
LEFT OUTER JOIN najhppvys a6 ON (A2.ID_NAJHPPVYS = A6.ID_NAJHPPVYS)
LEFT OUTER JOIN cisdrpre a4 ON (A3.ID_DRUPRE_NEUR = A4.ID_DRUPRE)
LEFT OUTER JOIN najplatby a5 ON (A3.ID_NAJPLATBY_A = A5.ID_NAJPLATBY)
WHERE ((A9.TYP            = 'N' ) OR (A9.ID_NAJVZTAH IS NULL)) AND (( A9.HLAVNI         = 'H' ) OR (A9.ID_NAJVZTAH IS NULL));
</pre>

**Comment by darold** [comment]
Fixed by commit 32d523a.

**Comment by okbob** [comment]
it is fixed
