### ISSUE TITLE
Missing "perform" in old PL/SQL procedure translation

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#349]
When I have a procedure in the Oracle source in a PL/SQL package, the calls to its translated function are not yet translated like "perform myPackage.myFunc(myParams);". The "perform" is missing.

Example: in an Oracle package:
PROCEDURE MAJ_CPT is
(...)
FUNCTION UPDATE_COUNTER (some params)  RETURN VARCHAR2 is
BEGIN
    (...)
    MAJ_CPT();
END UPDATE_COUNTER;
------------------------------------------------------------------------------------------
In the translation:
CREATE OR REPLACE FUNCTION PCK_CPT.maj_cpt () RETURNS VOID AS $body$
(...)
CREATE OR REPLACE FUNCTION PCK_CPT.update_counter(some params)  RETURNS varchar AS $body$
(some declarations)
BEGIN
        -- Lancement d'une mise à jour des compteurs hors planificateur
        pck_cpt.maj_cpt();
	RETURN('0');
EXCEPTION
    (some instructions)
END;

I know this is not a light issue, because you have to detect a bare function call (without ":=" or conditional or query expression) and then to know if the called function returns void within all the existing functions.
Wouldn't there be some conditions, eventually restrictions, that make this feature feasible ? For example: the procedure call is the first syntaxic element of the instruction.

Best regards,
E.Delanoe

**Comment by darold** [comment]
The job was already done but not working, commit 46f9da7 might solve most of direct function call cases.

The PERFORMl rewrite is done on all direct call that follow `(BEGIN|THEN|LOOP|;)` there must exists other cases to fix, I will need the context of the call to find the right preceding keyword. Comment between the preceding keyword and the direct call is supported.

**Comment by edelanoe** [comment]
Thanks, I will check your commit.
About my previous comment, I might have lead you to a wrong path when talking about "conditional or query expression", because a procedure call cannot be done in those contexts: it cannot be inside an expression. I wonder if, in PL/SQL, any non-keyword instruction that is not an affectation (:=) would be a procedure call... At least it can be suspected so, and checked deeper.
Your opinion or experience anyone ?
Rgds,
E.Delanoe

**Comment by darold** [comment]
To detect direct call to procedure, Ora2Pg first look at all functions/procedures declared in the Oracle database or the file given as input. Functions/procedures in package are also listed/ Then for each function/procedure, Ora2Pg check if it has out parameters or not to add PERFORM in front of function names detected in the code or use a SELECT ... INTO syntax. This seems to be enough to do the expected replacement.

**Comment by darold** [comment]
To be more precise, when the function/procedure has only one out parameter, Ora2Pg  replace a direct call using `:=` instead of a SELECT INTO.
