### ISSUE TITLE
ROWNUM is not replaced in query inside function

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#350]
Oracle:
<pre>
CREATE OR REPLACE FUNCTION IDES_JMMAJ.CLEOSOBY_KONTAKTY(mID_CCLE CLEOSOBY.ID_CCLE%TYPE, mPOCET IN NUMBER DEFAULT 1, mKOD IN VARCHAR2 DEFAULT NULL)
RETURN VARCHAR2 IS
temp VARCHAR2(4000);
RESULT VARCHAR2(4000);
BEGIN
/*
** fce vrati pro ID_CCLE kontakty v pozadovanem poctu a pozadovaneho typu, implicitne 1 tel a 1 email
*/
-- mPOCET ... max. pocet kontaktu ktere chci vratit
-- mKOD ... kod typu kontaktu, ktery chci vratit; kdyz je null tak chci emaily, telefony a mobily

if (mKOD is NULL) THEN BEGIN
  --emaily
  BEGIN
    SELECT wm_concat(cislo_orig) AS INFO
    INTO TEMP
    FROM V_OSOBAKOMUNIKACE
    WHERE ID_CCLE=mID_CCLE
    AND PLATNOST_DO>=SYSDATE
    AND KOD_KKOM='EMAIL'
    and ROWNUM<=mPOCET
    GROUP BY ID_CCLE;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN TEMP := NULL;
  END;
  --telefony
  BEGIN
    SELECT wm_concat(cislo_orig) AS INFO
    INTO RESULT
    FROM V_OSOBAKOMUNIKACE
    WHERE ID_CCLE=mID_CCLE
    AND PLATNOST_DO>=SYSDATE
    AND (KOD_KKOM='MOBIL' or KOD_KKOM like 'TEL%')
    and ROWNUM<=mPOCET
    GROUP BY ID_CCLE;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN RESULT := NULL;
  END;
  if (TEMP is NOT NULL) THEN
    if (RESULT is NULL) THEN
    RESULT := TEMP;
    ELSE RESULT := RESULT || ',' || TEMP;
    END IF;
  END IF;
END;
ELSE BEGIN
  --dle mKOD
  BEGIN
    SELECT wm_concat(cislo_orig) AS INFO
    INTO RESULT
    FROM V_OSOBAKOMUNIKACE
    WHERE ID_CCLE=mID_CCLE
    AND PLATNOST_DO>=SYSDATE
    AND trim(KOD_KKOM)=mKOD
    and ROWNUM<=mPOCET
    GROUP BY ID_CCLE;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN RESULT := mKOD;
  END;
END;
END IF;

  return RESULT;
END CLEOSOBY_KONTAKTY;
</pre>

PostgreSQL:
<pre>
CREATE OR REPLACE FUNCTION cleosoby_kontakty (mID_CCLE CLEOSOBY.ID_CCLE%TYPE, mPOCET numeric DEFAULT 1, mKOD text DEFAULT NULL) RETURNS varchar AS $body$
DECLARE

temp varchar(4000);
RESULT varchar(4000);

BEGIN
/*
** fce vrati pro ID_CCLE kontakty v pozadovanem poctu a pozadovaneho typu, implicitne 1 tel a 1 email
*/
-- mPOCET ... max. pocet kontaktu ktere chci vratit
-- mKOD ... kod typu kontaktu, ktery chci vratit; kdyz je null tak chci emaily, telefony a mobily
if (mKOD is NULL) THEN BEGIN
  --emaily
  BEGIN
    SELECT wm_concat(cislo_orig) AS INFO
    INTO STRICT  TEMP
    FROM V_OSOBAKOMUNIKACE
    WHERE ID_CCLE=mID_CCLE
    AND PLATNOST_DO>=clock_timestamp()
    AND KOD_KKOM='EMAIL'
    and ROWNUM<=mPOCET
    GROUP BY ID_CCLE;
   EXCEPTION
    WHEN NO_DATA_FOUND THEN TEMP := NULL;
  END;
  --telefony
  BEGIN
    SELECT wm_concat(cislo_orig) AS INFO
    INTO STRICT  RESULT
    FROM V_OSOBAKOMUNIKACE
    WHERE ID_CCLE=mID_CCLE
    AND PLATNOST_DO>=clock_timestamp()
    AND (KOD_KKOM='MOBIL' or KOD_KKOM like 'TEL%')
    and ROWNUM<=mPOCET
    GROUP BY ID_CCLE;
   EXCEPTION
    WHEN NO_DATA_FOUND THEN RESULT := NULL;
  END;
  if (TEMP is NOT NULL) THEN
    if (RESULT is NULL) THEN
    RESULT := TEMP;
    ELSE RESULT := RESULT || ',' || TEMP;
    END IF;
  END IF;
END;
ELSE BEGIN
  --dle mKOD
  BEGIN
    SELECT wm_concat(cislo_orig) AS INFO
    INTO STRICT  RESULT
    FROM V_OSOBAKOMUNIKACE
    WHERE ID_CCLE=mID_CCLE
    AND PLATNOST_DO>=clock_timestamp()
    AND btrim(KOD_KKOM)=mKOD
    and ROWNUM<=mPOCET
    GROUP BY ID_CCLE;
   EXCEPTION
    WHEN NO_DATA_FOUND THEN RESULT := mKOD;
  END;
END;
END IF;

  return RESULT;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION cleosoby_kontakty (mID_CCLE CLEOSOBY.ID_CCLE%TYPE, mPOCET numeric DEFAULT 1, mKOD text DEFAULT NULL) FROM PUBLIC;
</pre>

**Comment by darold** [comment]
Right, Ora2Pg was not replacing ROWNUM if the value was not a number. Commit cae0d6a fix that behavior.

**Comment by okbob** [comment]
it is fixed, thank you
