### ISSUE TITLE
missing semicolon after RAISE statement

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#351]
The command 

    raise_application_error( -20010 ,mID_CCLE || '/' || mUCET ); 

was correctly transformed to

    RAISE EXCEPTION '%', mID_CCLE || '/' || mUCET  USING ERRCODE = '45010'

but ending semicolon is missing

**Comment by darold** [comment]
Sorry, commit e13ba64 fix it.

**Comment by okbob** [comment]
It is fixed, thank you
