### ISSUE TITLE
The `PEFORM` was used in wrong context

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#352]
The PERFORM keyword should not be used ever inside SQL expression

Oracle:
<pre>
CREATE OR REPLACE function IDES_JMMAJ.NAJPOLOZ_EPOL_CASTKA(mID_POL_PRED in NAJPOLOZ.ID_POL_PRED%TYPE)
return number is
  Result number;
begin
 select 
  DECODE( MT.DPH_DOP , 'B' , 
            GET_ZAKLAD_DPH_CASTKA( MT.ID_POL_PRED , A1.KOD_CNAJVYPPOL , MT.DPH_PROC  , MT.ZAKRDPH , MT.ZAOKR_CELKEM , MT.EPOL_CASTKA , 'CASTKA' , TRIM(A12.KOD_CTYPPRED) , A6.ZIV  ) ,(  
            DECODE( A6.ZIV , '1' , MT.EPOL_CASTKA ,
            DECODE( TRIM(A12.KOD_CTYPPRED) , 'S', MT.EPOL_CASTKA ,
            DECODE( (SELECT PODPOLOZKY
                     FROM CNAJVYPPOL B1
                    WHERE B1.ID_CNAJVYPPOL = MT.ID_CNAJVYPPOL ) , 'N' , MT.EPOL_CASTKA ,
                    DECODE( TRIM(A1.KOD_CNAJVYPPOL) , 'VYPO' ,
                   (SELECT  SUM(B1.EPOL_CASTKA  )
                       FROM NAJPODPOL B1
                       WHERE B1.ID_POL_PRED = MT.ID_POL_PRED ) ,
                   (SELECT DECODE( A15.ZAOKR_NAJEM_NE_VYHL
                         , 'A' , 
                         ROUND(SUM(B1.EPOL_CASTKA ) , A15.POC_MIST_NAJEM_NE_VYHL ) ,
                        DECODE( GET_NE_OREZ( TRIM(A1.KOD_CNAJVYPPOL)  , MT.ZAOKR_CELKEM ) ,'A', 
                         SUM(B1.EPOL_CASTKA ),TRUNC(SUM(B1.EPOL_CASTKA ) , A1.OREZ )))
                       FROM NAJPODPOL B1
                       WHERE B1.ID_POL_PRED = MT.ID_POL_PRED )  )))))) 
      into Result                    
  from NAJPOLOZ MT , CNAJVYPPOL A1 , NAJPREDP A6 ,
        CTYPPRED A12, UDRPROVO A15  WHERE  
       MT.ID_POL_PRED= mID_POL_PRED 
       and MT.ID_CNAJVYPPOL = A1.ID_CNAJVYPPOL(+)
       and MT.ID_PREDPIS = A6.ID_PREDPIS(+)
       and A6.ID_CTYPPRED = A12.ID_CTYPPRED(+)
       and MT.ID_APROVOZNA = A15.ID_APROVOZNA(+);

  return(Result);
end NAJPOLOZ_EPOL_CASTKA;
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE FUNCTION najpoloz_epol_castka (mID_POL_PRED NAJPOLOZ.ID_POL_PRED%TYPE) RETURNS numeric AS $body$
DECLARE

  Result numeric;

BEGIN
 select
  CASE WHEN  MT.DPH_DOP ='B' THEN
PERFORM GET_ZAKLAD_DPH_CASTKA( MT.ID_POL_PRED , A1.KOD_CNAJVYPPOL , MT.DPH_PROC  , MT.ZAKRDPH , MT.ZAOKR_CELKEM , MT.EPOL_CASTKA , 'CASTKA' , btrim(A12.KOD_CTYPPRED) , A6.ZIV  )
ELSE (              CASE WHEN  A6.ZIV ='1' THEN  MT.EPOL_CASTKA   ELSE CASE WHEN  btrim(A12.KOD_CTYPPRED) ='S' THEN  MT.EPOL_CASTKA   ELSE CASE WHEN(SELECT PODPOLOZKY
     FROM CNAJVYPPOL B1                    WHERE B1.ID_CNAJVYPPOL = MT.ID_CNAJVYPPOL ) ='N' THEN  MT.EPOL_CASTKA   ELSE CASE WHEN  btrim(A1.KOD_CNAJVYPPOL) ='VYPO' THEN (SELECT  SUM(B1.EPOL_CASTKA  )
WHERE B1.ID_POL_PRED = MT.ID_POL_PRED ) END  END  END  END ) END
      into Result
  FROM najpoloz mt
LEFT OUTER JOIN cnajvyppol a1 ON (MT.ID_CNAJVYPPOL = A1.ID_CNAJVYPPOL)
LEFT OUTER JOIN najpredp a6 ON (MT.ID_PREDPIS = A6.ID_PREDPIS)
LEFT OUTER JOIN udrprovo a15 ON (MT.ID_APROVOZNA = A15.ID_APROVOZNA)
LEFT OUTER JOIN ctyppred a12 ON (A6.ID_CTYPPRED = A12.ID_CTYPPRED)
WHERE MT.ID_POL_PRED= mID_POL_PRED;
  
  return(Result);
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION najpoloz_epol_castka (mID_POL_PRED NAJPOLOZ.ID_POL_PRED%TYPE) FROM PUBLIC;
</pre>

**Comment by edelanoe** [comment]
Indication evocated in issue #349: 
The code between "select" and the subsequent ";" is what I call a "Keyword instruction", that is, either a SQL query/DML query, or a PL/SQL construct like "IF...THEN...". Inside such piece of code, if I'm not mistaking, there cannot be a "procedure call", that is, there cannot be a "perform".
In Pavel's case, the "Keyword instruction" is delimited by "select" and ";". 

Hoping it helps:)

**Comment by darold** [comment]
OK, commit 935324 add PERFORM only after a BEGIN and a ; in the code that must cover most of the replacement.

**Comment by okbob** [comment]
It can be after THEN :( too 

    IF x THEN
      PERFORM fx();
    END IF;

**Comment by edelanoe** [comment]
Or after a ELSE :)

**Comment by darold** [comment]
Yes I have to detect the kind of statement, I will work on it later today because I have to use more complex regex than the one used to write perform after a ; or a BEGIN.

**Comment by edelanoe** [comment]
Just an question to which the answer could be valuable:
To decide if an instruction should be preceded by "perform" (<=> was a procedure call), is it better to consider the list of existing procedures (void-returning functions) or negate the list of SQL+PL/SQL keywords ? (may be not all keywords)

**Comment by darold** [comment]
Strangely Ora2Pg is performing all this great work without having any SQL keyword list, it only use regexp.

And the regexp to handle most of the case where PERFORM should be happen was not so easy to find but I am confident that commit 802863b could solve the issue. At least it solves the following cases:
```
CREATE OR REPLACE function GET_ZAKLAD_DPH_CASTKA(mID_POL_PRED in NAJPOLOZ.ID_POL_PRED%TYPE)
RETURN NUMBER IS
  Result NUMBER;
BEGIN
  SELECT 
      DECODE( MT.DPH_DOP , 'B' , GET_ZAKLAD_DPH_CASTKA( MT.ID_POL_PRED, A6.ZIV  )) INTO Result                    
  FROM NAJPOLOZ MT;
  IF MT.DPH_DOP = 'B' THEN
        DECODE( MT.DPH_DOP , 'B' , GET_ZAKLAD_DPH_CASTKA( MT.ID_POL_PRED, A6.ZIV  )) INTO Result                    
  ELSIF MT.DPH_DOP = 'A' THEN
	GET_ZAKLAD_DPH_CASTKA( MT.ID_POL_PRED, A6.ZIV  );
  ELSIF MT.DPH_DOP = 'U' THEN
	GET_ZAKLAD_DPH_CASTKA( MT.ID_POL_PRED, A6.ZIV  );
  ELSE
        DECODE( MT.DPH_DOP , 'B' , GET_ZAKLAD_DPH_CASTKA( MT.ID_POL_PRED, A6.ZIV  )) INTO Result                    
	GET_ZAKLAD_DPH_CASTKA( MT.ID_POL_PRED, A6.ZIV  );
  END IF;
  LOOP
	GET_ZAKLAD_DPH_CASTKA( MT.ID_POL_PRED, A6.ZIV  );
	x := x + 1;
	EXIT WHEN x > 3;
  END LOOP;
  RETURN(Result);
END GET_ZAKLAD_DPH_CASTKA;
```
Using `ora2pg -q -t FUNCTION -i test_code.sql` reports:
```
CREATE OR REPLACE FUNCTION get_zaklad_dph_castka (mID_POL_PRED NAJPOLOZ.ID_POL_PRED%TYPE) RETURNS bigint AS $body$
DECLARE
  Result bigint;
BEGIN
  SELECT
      CASE WHEN  MT.DPH_DOP ='B' THEN  GET_ZAKLAD_DPH_CASTKA( MT.ID_POL_PRED, A6.ZIV  ) END  INTO Result                    
  FROM NAJPOLOZ MT;
  IF MT.DPH_DOP = 'B' THEN
        CASE WHEN  MT.DPH_DOP ='B' THEN  GET_ZAKLAD_DPH_CASTKA( MT.ID_POL_PRED, A6.ZIV  ) END  INTO Result
  ELSIF MT.DPH_DOP = 'A' THEN
	PERFORM GET_ZAKLAD_DPH_CASTKA( MT.ID_POL_PRED, A6.ZIV  );
  ELSIF MT.DPH_DOP = 'U' THEN
	PERFORM GET_ZAKLAD_DPH_CASTKA( MT.ID_POL_PRED, A6.ZIV  );
  ELSE
        CASE WHEN  MT.DPH_DOP ='B' THEN  GET_ZAKLAD_DPH_CASTKA( MT.ID_POL_PRED, A6.ZIV  ) END  INTO Result
	GET_ZAKLAD_DPH_CASTKA( MT.ID_POL_PRED, A6.ZIV  );
  END IF;
  LOOP
	PERFORM GET_ZAKLAD_DPH_CASTKA( MT.ID_POL_PRED, A6.ZIV  );
	x := x + 1;
	EXIT WHEN x > 3;
  END LOOP;
  RETURN(Result);
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
```

**Comment by okbob** [comment]
Yes, regular expressions are deadly strong weapon :).
This issue is fixed - but the dumping (transformations) is last two days.
