### ISSUE TITLE
Procedures with OUT parameters are not processed in triggers

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#354]
Oracle:
<pre>
TRIGGER "IDES_JMMAJ".CAVPDISTR_BI BEFORE INSERT
ON  CAVPDISTR
FOR EACH ROW

BEGIN

----  ZACATEK DEFAULT CAST 

:new.CVZNIKRADK := NULL;
RRRUTIL.DEFA_BEFORE_INSERT( :new.ID_CAVPDISTR , :new.PLATNOST_OD , :new.PLATNOST_DO ,:new.IDENT , :new.ID_ASPRAVCE , :new.CVZNIKRADK ) ;

----  KONEC DEFAULT CAST

END ;
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE FUNCTION trigger_fct_cavpdistr_bi() RETURNS trigger AS $BODY$
BEGIN

----  ZACATEK DEFAULT CAST

NEW.CVZNIKRADK := NULL;
RRRUTIL.DEFA_BEFORE_INSERT( NEW.ID_CAVPDISTR , NEW.PLATNOST_OD , NEW.PLATNOST_DO ,NEW.IDENT , NEW.ID_ASPRAVCE , NEW.CVZNIKRADK );

----  KONEC DEFAULT CAST

RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_cavpdistr_bi() FROM PUBLIC;
</pre>

Expected:
<pre>
  SELECT RRRUTIL.DEFA_BEFORE_INSERT(NEW.ID_CAVPDISTR , NEW.PLATNOST_OD , NEW.PLATNOST_DO ,NEW.IDENT , NEW.ID_ASPRAVCE , NEW.CVZNIKRADK) INTO NEW.ID_CAVPDISTR , NEW.PLATNOST_OD , NEW.PLATNOST_DO ,NEW.IDENT , NEW.ID_ASPRAVCE , NEW.CVZNIKRADK;
</pre>

**Comment by darold** [comment]
Commit 6cca639 might fix this issue.

**Comment by okbob** [comment]
This commit didn't help

**Comment by darold** [comment]
Hum, it should help, with this Oracle test trigger and function:
```
CREATE OR REPLACE PROCEDURE get_salary(empnr IN NUMBER, amnt OUT NUMBER)
AS BEGIN
        SELECT CURR_SALARY INTO amnt FROM EMPLOYEE WHERE EMPNO = empnr;
END;

CREATE OR REPLACE TRIGGER INVOICE_AMOUNT
    BEFORE INSERT ON EMPLOYEE
    FOR EACH ROW
    DECLARE
        v_amount NUMBER(6);
    BEGIN
        get_salary(:old.EMPNO,:new.CURR_SALARY);
        INSERT INTO archive_employee (EMPNO,CURR_SALARY) VALUES (old.EMPNO,:new.CURR_SALARY);
    END;
```

I have the right replacement:
```
CREATE OR REPLACE FUNCTION trigger_fct_invoice_amount() RETURNS trigger AS $BODY$
DECLARE
        v_amount numeric;
    BEGIN
        NEW.CURR_SALARY := get_salary(OLD.EMPNO,NEW.CURR_SALARY);
        INSERT INTO archive_employee(CURR_SALARY) VALUES (NEW.CURR_SALARY);
    RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
```

I test with multiple INOUT parameters to see if the problem still occurs like in your example.

**Comment by darold** [comment]
Everything works fine for me, using Oracle test code:
```
CREATE OR REPLACE PROCEDURE get_salary(empnr IN NUMBER, amnt OUT NUMBER, aname OUT VARCHAR2(15))
AS BEGIN
	SELECT CURR_SALARY,ENAME INTO amnt,aname FROM EMPLOYEE WHERE EMPNO = empnr AND ENAME = aname;
END;

CREATE OR REPLACE TRIGGER INVOICE_AMOUNT
    BEFORE INSERT ON EMPLOYEE
    FOR EACH ROW
    DECLARE 
        v_amount NUMBER(6);
    BEGIN
        get_salary(:old.EMPNO,:new.CURR_SALARY,:old.ENAME);
        INSERT INTO archive_employee (CURR_SALARY,ENAME) VALUES (:new.CURR_SALARY,:old.ENAME);
    END;
```
I get the expected translation:
```
CREATE OR REPLACE FUNCTION trigger_fct_invoice_amount() RETURNS trigger AS $BODY$
DECLARE
        v_amount numeric;
    BEGIN
        SELECT get_salary(OLD.EMPNO,NEW.CURR_SALARY,OLD.ENAME) INTO (NEW.CURR_SALARY,OLD.ENAME);
        INSERT INTO archive_employee(CURR_SALARY,ENAME) VALUES (NEW.CURR_SALARY,OLD.ENAME);
    RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
```

If you still have the issue after refreshing the Ora2Pg code, please post the trigger + the function code that are not translated.

**Comment by okbob** [comment]
we reading schema from db directly, not from files - maybe there can be a issue

**Comment by darold** [comment]
No, this export is from a test database.

**Comment by darold** [comment]
I think this issue is related to the fact that Ora2Pg doesn't know anything about the RRRUTIL.DEFA_BEFORE_INSERT function because you are exporting schema IDES_JMMAJ. I don't see  an easy solution for that because Ora2Pg can't reasonably look at all schema to extract function definition. Maybe I can add a directive like SCHEMA_FUNCTION to set a list of schema where all function meta information should be loaded.

**Comment by okbob** [comment]
The list of related packages (on Oracle side) can be good solution.

**Comment by darold** [comment]
Commit 49cdc68 says:
```
Add LOOK_FORWARD_FUNCTION configuration directive which takes a list of schema
to get functions/procedures meta information that are used in the current
schema export. When replacing call to function with OUT or INOUT parameters,
if a function is declared in an other package then the function call rewriting
can not be done because Ora2Pg only know about functions declared in the
current schema. By setting a comma separated list of schema as value of this
directive, Ora2Pg will look forward in these packages for all functions,
procedures and packages declaration before proceeding to current schema export.
```

Please test it and let me know, with the example above set:

    LOOK_FORWARD_FUNCTION    RRRUTIL

in your ora2pg.conf file then export again triggers of schema IDES_JMMAJ, the function call RRRUTIL.DEFA_BEFORE_INSERT might be revritten.

**Comment by okbob** [comment]
It is better than before, but it is not good still.
Oracle:
<pre>
TRIGGER "IDES_JMMAJ".CAVPDISTR_BI BEFORE INSERT
ON  CAVPDISTR
FOR EACH ROW




BEGIN

----  ZACATEK DEFAULT CAST 

:new.CVZNIKRADK := NULL;
RRRUTIL.DEFA_BEFORE_INSERT( :new.ID_CAVPDISTR , :new.PLATNOST_OD , :new.PLATNOST_DO ,:new.IDENT , :new.ID_ASPRAVCE , :new.CVZNIKRADK ) ;

----  KONEC DEFAULT CAST

END ;
</pre>

Function DEFA_BEFORE_INSERT
<pre>
  PROCEDURE DEFA_BEFORE_INSERT( mPK IN OUT NUMERIC , mPLATNOST_OD IN OUT DATE ,
                                mPLATNOST_DO IN OUT DATE , mIDENT IN OUT CHAR ,
                                mID_SPRAVCE IN OUT NUMERIC , mCVZNIKRADK IN OUT CHAR)
  IS
</pre>

Translation:
<pre>
CREATE OR REPLACE FUNCTION trigger_fct_cavpdistr_bi() RETURNS trigger AS $BODY$
BEGIN

----  ZACATEK DEFAULT CAST.
NEW.CVZNIKRADK := NULL;
SELECT * FROM RRRUTIL.defa_before_insert( NEW.ID_CAVPDISTR , NEW.PLATNOST_OD , NEW.PLATNOST_DO ,NEW.IDENT , NEW.ID_ASPRAVCE , NEW.CVZNIKRADK ) 
INTO  NEW.ID_CAVPDISTR,NEW.PLATNOST_OD,NEW.IDENT,NEW.ID_ASPRAVCE,,;

----  KONEC DEFAULT CAST
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
</pre>

Expected:
<pre>
SELECT * FROM RRRUTIL.defa_before_insert( NEW.ID_CAVPDISTR , NEW.PLATNOST_OD , NEW.PLATNOST_DO ,NEW.IDENT , NEW.ID_ASPRAVCE , NEW.CVZNIKRADK ) 
INTO  NEW.ID_CAVPDISTR , NEW.PLATNOST_OD , NEW.PLATNOST_DO ,NEW.IDENT , NEW.ID_ASPRAVCE , NEW.CVZNIKRADK;
</pre>

**Comment by darold** [comment]
Commit e18a71e might solve this issue too.

**Comment by okbob** [comment]
It is not better
<pre>
SELECT * FROM RRRUTIL.defa_before_insert( NEW.ID_CAVPDISTR, NEW.PLATNOST_OD, NEW.PLATNOST_DO, NEW.IDENT, NEW.ID_ASPRAVCE, NEW.CVZNIKRADK , , ).                         
INTO  NEW.ID_CAVPDISTR, NEW.PLATNOST_OD, NEW.IDENT, NEW.ID_ASPRAVCE, ,; 
</pre>

**Comment by darold** [comment]
Maybe this is because the function is overloaded in an other schema. Commit 04f1682 associate each function to its original schema to avoid such situation and fix this issue.

**Comment by okbob** [comment]
It is strange - there are not any change. The result is exactly same.

**Comment by darold** [comment]
Can you post the full source code of function RRRUTIL.DEFA_BEFORE_INSERT() and do you confirm that RRRUTIL is a schema not a package?

**Comment by okbob** [comment]
RRRUTIL is a package - not schema.
<pre>
CREATE OR REPLACE PACKAGE BODY IDES_JMMAJ.RRRUTIL AS

  --- ZAPISE DO LOGU ( TABULKY ) TEXT
  PROCEDURE RRRERRORLOG ( KOD IN CHAR , TEXT IN VARCHAR )
  IS
  BEGIN
    INSERT INTO RRRLOG ( KOD_LOG , TEXT , ID_ASPRAVCE )
      VALUES ( KOD , TEXT , G_ID_SPRAVCE ) ;
  END;


  ---  SPOUSTI SE Z TRIGRU BEFORE INSERT U VSECH TABULEK
  PROCEDURE DEFA_BEFORE_INSERT( mPK IN OUT NUMERIC , mPLATNOST_OD IN OUT DATE ,
                                mPLATNOST_DO IN OUT DATE , mIDENT IN OUT CHAR ,
                                mID_SPRAVCE IN OUT NUMERIC , mCVZNIKRADK IN OUT CHAR)
  IS
  BEGIN

     ----  VLOZI ID DO PK

     IF mPK IS NULL THEN
       Select SEAPP.nextval into mPK from dual;
     END IF ;


     ----  VLOZI PLATNOST OD

     IF mPLATNOST_OD IS NULL THEN
       mPLATNOST_OD := TO_DATE(TO_CHAR(SYSDATE,'DDMMYYYY'),'DDMMYYYY');
     END IF ;

     ----  VLOZI PLATNOST DO

     IF mPLATNOST_DO IS NULL THEN
       mPLATNOST_DO := RRRUTIL.MAXDATE ;
     END IF ;


     ---- VLOZI IDENT
     IF mIDENT IS NULL THEN
       mIDENT := SUBSTR(USER,1,16) || ' 1.0' ;
     END IF ;


     ---- VLOZI ID SPRAVCE
     /*
     IF mID_SPRAVCE IS NULL THEN
       mID_SPRAVCE := RRRUTIL.G_ID_SPRAVCE;
     END IF ;
     */

     ---- VLOZI DRUH VZNIKU RADKU

     IF mCVZNIKRADK IS NULL THEN
       mCVZNIKRADK := RUCNE_PORIZENO ;
     END IF;

  END;
END;
</pte>

**Comment by darold** [comment]
Using this code I'm not able to reproduce the issue there must exists an other function/procedure with similar name but different parameters declaration.  Perhaps commit 4f13fac has helped to fix that, can you try try again and let me know.

**Comment by okbob** [comment]
No change. Tomorrow I'll try do some research. I don't understand, why Ora2pg generates "empty" identifiers `,,;` ?

**Comment by darold** [comment]
I've been able to reproduce this issue, I'm trying to fix it know.

**Comment by darold** [comment]
Last commit 38f5d91 might solves this issue, the problem was that function parameters was doubled with the PACKAGE and PACKAGE BODY definition when extracting sources.

**Comment by okbob** [comment]
Looks fixed. Perfect :)
Thank you
