### ISSUE TITLE
cycle variable is not generated for LOOP IN SELECT in trigger

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#355]
Oracle:
<pre>
TRIGGER "IDES_JMMAJ".CISPOLPRE_AI
  after insert on CISPOLPRE
  for each row

declare
  -- local variables here
begin
  IF 
     (:new.CVZNIKRADK <>'P') 
      THEN
     --- 21.2.2014 generovat pouze metody , ktere se netykaji polozky najem a vybaveni prostoru 
     FOR qBudo IN
      (
      SELECT ID_CNAJVYPPOL,ID_SKUP_CISEL
      FROM CNAJVYPPOL WHERE ID_SKUP_CISEL = :new.ID_SKUP_CISEL
      and trim(kod_cnajvyppol) not 
      in ('S','A','C','D','F','G','H','K','PL','RN','SLEVA107','VYPO','ZP')
       )

    LOOP
         Insert into CISVPOLVYP (ID_POLONAJ,ID_CNAJVYPPOL,ID_SKUP_CISEL,LIDENT)
         Values (:new.ID_POLONAJ,qBudo.ID_CNAJVYPPOL,qBudo.ID_SKUP_CISEL,:new.LIDENT);   
    
    END LOOP;
      
   END IF;
end CISPOLPRE_AI;
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE FUNCTION trigger_fct_cispolpre_ai() RETURNS trigger AS $BODY$
declare
  -- local variables here
BEGIN
  IF (NEW.CVZNIKRADK <>'P')
      THEN
     --- 21.2.2014 generovat pouze metody , ktere se netykaji polozky najem a vybaveni prostoru.
     FOR qBudo IN (
      SELECT ID_CNAJVYPPOL,ID_SKUP_CISEL
      FROM CNAJVYPPOL WHERE ID_SKUP_CISEL = NEW.ID_SKUP_CISEL
      and btrim(kod_cnajvyppol) not.
      in ('S','A','C','D','F','G','H','K','PL','RN','SLEVA107','VYPO','ZP')
       )
       
    LOOP
         Insert into CISVPOLVYP(ID_POLONAJ,ID_CNAJVYPPOL,ID_SKUP_CISEL,LIDENT)
         Values (NEW.ID_POLONAJ,qBudo.ID_CNAJVYPPOL,qBudo.ID_SKUP_CISEL,NEW.LIDENT);
....
    END LOOP;

   END IF;
RETURN NEW;
END;
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
</pre>

Missing
<pre>
DECLARE qBudo RECORD
</pre>

**Comment by darold** [comment]
Commit 03b6d94 might fix this issue.

**Comment by okbob** [comment]
It is fixed
