### ISSUE TITLE
Few times raise_application_error was not replaced

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#356]
<pre>
function F_GET_NAJPARPRE( mRecNAJPARPRE_VSTUP IN  RRRUTIL.T_PAR_GET_NAJPARPRE) RETURN RRRUTIL.T_PAR_GET_NAJPARPRE is

  result RRRUTIL.T_PAR_GET_NAJPARPRE;
  mKOD_DRUPRE CISDRPRE.KOD_DRUPRE%TYPE;
  mNAJPARPRE_CISUJEDN UDRPROVO.NAJPARPRE_UCEJEDN%TYPE;
  mID_PROSTOR NAJPROS.ID_PROSTOR%TYPE;
  mID_SEGMENT NAJPROS.ID_SEGMENT%TYPE;
  mID_STAVOBJ NAJPROS.ID_STAVOBJ%TYPE;
  mRecNAJPARPRE RRRUTIL.T_PAR_GET_NAJPARPRE;
begin

	      ---raise_application_error( -20010 , mRecNAJPARPRE.mId_Najpros ||'  ' || mRecNAJPARPRE.mID_DRUPRE || '  ' || mRecNAJPARPRE.mID_CISPREDVZT || '  ' || mRecNAJPARPRE.mOBDOBI_OD );

	       mRecNAJPARPRE := mRecNAJPARPRE_VSTUP;

	       BEGIN
		 BEGIN

		   SELECT ID_PROSTOR , ID_SEGMENT INTO
			 mID_PROSTOR  , mID_SEGMENT
		     FROM NAJPROS
		     WHERE ID_NAJPROS = mRecNAJPARPRE.mId_Najpros;

		    IF mID_PROSTOR IS NOT NULL THEN
			SELECT ID_SKUTPRS , NAJPARPRE_UCEJEDN INTO mRecNAJPARPRE.mId_SKUTPRS , mNAJPARPRE_CISUJEDN

			FROM V_VZTAHPRSTR
			  WHERE ID_NAJPROS =  mRecNAJPARPRE.mId_Najpros;
		    ELSE
		       SELECT A3.ID_SKUTPRS,A2.NAJPARPRE_UCEJEDN INTO mRecNAJPARPRE.mId_SKUTPRS , mNAJPARPRE_CISUJEDN

			 FROM SSSHLEDEJ_A MT , CVTYPSKUPR A1 , UDRPROVO A2 , CVTYPSKUPR A3

			   WHERE MT.ID_TYPPRS =  A1.ID_TYPPRS
			     AND A1.ID_KOLURC =  A3.ID_KOLURC
			     AND A3.ID_SKUTPRS IS NOT NULL
			     AND MT.ID_NAJPROS =  mRecNAJPARPRE.mId_Najpros
			     AND MT.ID_APROVOZNA = A2.ID_APROVOZNA;
		    END IF;

		  EXCEPTION
		      WHEN OTHERS THEN

			raise_application_error( -20011 , ' GET_NAJPARPRE --  V_VZTAHPRSTR ID_NAJPROS ' || mRecNAJPARPRE.mId_Najpros || ' ' || SQLERRM ) ;

		 END;

		  IF mRecNAJPARPRE.mKOD_DRUPRE IS NULL THEN
		    IF mNAJPARPRE_CISUJEDN = 'A' THEN
		       IF mRecNAJPARPRE.mID_CISUJEDN IS NULL THEN
			 SELECT ID_CISUJEDN INTO mRecNAJPARPRE.mID_CISUJEDN
			   FROM NAJPROS MT , NAJVZTAH A1
			   WHERE MT.ID_NAJVZTAH = A1.ID_NAJVZTAH
			     AND MT.ID_NAJPROS = mRecNAJPARPRE.mId_Najpros;
		       END IF;
		       IF mRecNAJPARPRE.mID_CISUJEDN = -1 THEN
			 mRecNAJPARPRE.mID_CISUJEDN := NULL;
		       END IF;
		       IF mRecNAJPARPRE.mID_CISUJEDN IS NOT NULL THEN
			  SELECT  /*+ ORDERED */ * INTO RRRUTIL.G_PARAMETRY_PREDPIS

			    FROM V_PARAM_PREDPIS MT
			    WHERE ID_NAJPROS = mRecNAJPARPRE.mId_Najpros
			      AND ID_CISUJEDN = mRecNAJPARPRE.mID_CISUJEDN
			      ---AND ID_SKUTPRS = mRecNAJPARPRE.mId_SKUTPRS
			      ---AND ID_CTYPPRED = mRecNAJPARPRE.mID_CTYPPRED
			      AND ID_DRUPRE = mRecNAJPARPRE.mID_DRUPRE
			      AND ID_CISPREDVZT = mRecNAJPARPRE.mID_CISPREDVZT
			      ---AND ( NAJVPARPRL_OD <= mRecNAJPARPRE.mOBDOBI_OD AND NAJVPARPRL_DO >= mRecNAJPARPRE.mOBDOBI_OD )

			      ---AND ( NAJVPARVZT_OD <= mRecNAJPARPRE.mOBDOBI_OD AND NAJVPARVZT_DO >= mRecNAJPARPRE.mOBDOBI_OD )

			      ---AND ( NAJVPREPSK_OD <= mRecNAJPARPRE.mOBDOBI_OD AND NAJVPREPSK_DO >= mRecNAJPARPRE.mOBDOBI_OD )

			      AND ( PLATNOST_OD <= mRecNAJPARPRE.mOBDOBI_OD ANDPLATNOST_DO >= mRecNAJPARPRE.mOBDOBI_OD ) ;

			 ELSE
			  SELECT  /*+ ORDERED */ * INTO RRRUTIL.G_PARAMETRY_PREDPIS

			    FROM V_PARAM_PREDPIS MT
			    WHERE ID_NAJPROS = mRecNAJPARPRE.mId_Najpros
			      AND ID_CISUJEDN IS NULL
			      ---AND ID_SKUTPRS = mRecNAJPARPRE.mId_SKUTPRS
			      ---AND ID_CTYPPRED = mRecNAJPARPRE.mID_CTYPPRED
			      AND ID_DRUPRE = mRecNAJPARPRE.mID_DRUPRE
			      AND ID_CISPREDVZT = mRecNAJPARPRE.mID_CISPREDVZT
			      ---AND ( NAJVPARPRL_OD <= mRecNAJPARPRE.mOBDOBI_OD AND NAJVPARPRL_DO >= mRecNAJPARPRE.mOBDOBI_OD )

			      ---AND ( NAJVPARVZT_OD <= mRecNAJPARPRE.mOBDOBI_OD AND NAJVPARVZT_DO >= mRecNAJPARPRE.mOBDOBI_OD )

			      ---AND ( NAJVPREPSK_OD <= mRecNAJPARPRE.mOBDOBI_OD AND NAJVPREPSK_DO >= mRecNAJPARPRE.mOBDOBI_OD )

			      AND ( PLATNOST_OD <= mRecNAJPARPRE.mOBDOBI_OD ANDPLATNOST_DO >= mRecNAJPARPRE.mOBDOBI_OD ) ;

			 END IF;
		     ELSE
			IF mID_PROSTOR IS NOT NULL THEN
			  ---raise_application_error( -20010 , mRecNAJPARPRE.mId_Najpros || '  ' || mRecNAJPARPRE.mID_DRUPRE || '  ' || mRecNAJPARPRE.mID_CISPREDVZT || '  ' || mRecNAJPARPRE.mOBDOBI_OD );

			  SELECT  /*+ ORDERED */ * INTO RRRUTIL.G_PARAMETRY_PREDPIS

			      FROM V_PARAM_PREDPIS MT
			      WHERE ID_NAJPROS = mRecNAJPARPRE.mId_Najpros
				---AND ID_SKUTPRS = mRecNAJPARPRE.mId_SKUTPRS
				---AND ID_CTYPPRED = mRecNAJPARPRE.mID_CTYPPRED
				AND ID_DRUPRE = mRecNAJPARPRE.mID_DRUPRE
				AND ID_CISPREDVZT = mRecNAJPARPRE.mID_CISPREDVZT

				---AND ( NAJVPARPRL_OD <= mRecNAJPARPRE.mOBDOBI_OD AND NAJVPARPRL_DO >= mRecNAJPARPRE.mOBDOBI_OD )

				---AND ( NAJVPARVZT_OD <= mRecNAJPARPRE.mOBDOBI_OD AND NAJVPARVZT_DO >= mRecNAJPARPRE.mOBDOBI_OD )

				---AND ( NAJVPREPSK_OD <= mRecNAJPARPRE.mOBDOBI_OD AND NAJVPREPSK_DO >= mRecNAJPARPRE.mOBDOBI_OD )

				AND ( PLATNOST_OD <= mRecNAJPARPRE.mOBDOBI_OD AND PLATNOST_DO >= mRecNAJPARPRE.mOBDOBI_OD ) ;

			ELSE
			  IF mID_SEGMENT IS NOT NULL THEN
			    SELECT ID_STAVOBJ INTO mID_STAVOBJ
			      FROM OBPBUDO
			      WHERE ID_SEGMENT = mID_SEGMENT
				AND ROZLISENI = 'H';

			  END IF;

			  ----raise_application_error( -20010 , mRecNAJPARPRE.mId_Najpros || '	' || mRecNAJPARPRE.mID_DRUPRE || '  ' || mRecNAJPARPRE.mID_CISPREDVZT || '  ' || mRecNAJPARPRE.mOBDOBI_OD  || '  ' ||  mRecNAJPARPRE.mId_SKUTPRS
 );

			  SELECT /*+ ORDERED */ * INTO RRRUTIL.G_PARAMETRY_PREDPIS

			    FROM V_PARAM_PREDPIS_JINY
			    WHERE ID_STAVOBJ = mID_STAVOBJ
				AND ID_DRUPRE = mRecNAJPARPRE.mID_DRUPRE
				AND ID_CISPREDVZT = mRecNAJPARPRE.mID_CISPREDVZT

				AND ID_SKUTPRS = mRecNAJPARPRE.mId_SKUTPRS
				---AND ( NAJVPARPRL_OD <= mRecNAJPARPRE.mOBDOBI_OD AND NAJVPARPRL_DO >= mRecNAJPARPRE.mOBDOBI_OD )

				---AND ( NAJVPARVZT_OD <= mRecNAJPARPRE.mOBDOBI_OD AND NAJVPARVZT_DO >= mRecNAJPARPRE.mOBDOBI_OD )

				---AND ( NAJVPREPSK_OD <= mRecNAJPARPRE.mOBDOBI_OD AND NAJVPREPSK_DO >= mRecNAJPARPRE.mOBDOBI_OD )

				AND ( PLATNOST_OD <= mRecNAJPARPRE.mOBDOBI_OD AND PLATNOST_DO >= mRecNAJPARPRE.mOBDOBI_OD ) ;

			END IF;

		    END IF;

		  END IF;
		  IF mRecNAJPARPRE.mKOD_DRUPRE = 'UP' THEN

		    SELECT ID_NAJPARPRE INTO RRRUTIL.G_PARAMETRY_PREDPIS.ID_NAJPARPRE

		      FROM NAJPARPRE
		      WHERE ID_DRUPRE = mRecNAJPARPRE.mID_DRUPRE
			AND ID_APROVOZNA = mRecNAJPARPRE.mID_APROVOZNA
			AND ROWNUM < 2;
		    ---raise_application_error( -20011 , ' UPOMINKA ' || SQLERRM ) ;

		  END IF;

	       EXCEPTION
		 WHEN OTHERS THEN
		    ---raise_application_error( -20011 , ' GET_NAJPARPRE --  V_PARAM_PREDPIS ' || SQLERRM ) ;

		    raise_application_error( -20011 ,'GET_NAJPARPRE --	V_PARAM_PREDPIS '|| mRecNAJPARPRE.mId_Najpros || '  ' || mRecNAJPARPRE.mID_DRUPRE || '' ||  mRecNAJPARPRE.mID_CISPREDVZT  || '  ' || mRecNAJPARPRE.mOBDOBI_OD  ) ;

		  /*

		  SELECT TRIM(KOD_DRUPRE) INTO mKOD_DRUPRE
		    FROM CISDRPRE
		    WHERE ID_DRUPRE = mRecNAJPARPRE.mID_DRUPRE

		  IF mKOD_DRUPRE <> 'UP' THEN
		  ---raise_application_error( -20011 , mRecNAJPARPRE.mId_Najpros || '  ' || mRecNAJPARPRE.mID_DRUPRE || '  ' ||  mRecNAJPARPRE.mID_CISPREDVZT  || '  ' || mRecNAJPARPRE.mOBDOBI_OD  ) ;

		  ELSE

		  END IF;
		  */
	       END;

    result := mRecNAJPARPRE;
    RETURN(result);

end F_GET_NAJPARPRE;
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE FUNCTION f_get_najparpre ( mRecNAJPARPRE_VSTUP RRRUTIL.T_PAR_GET_NAJPARPRE) RETURNS RRRUTIL.T_PAR_GET_NAJPARPRE AS $body$
DECLARE
  
  result RRRUTIL.T_PAR_GET_NAJPARPRE;
  mKOD_DRUPRE CISDRPRE.KOD_DRUPRE%TYPE;
  mNAJPARPRE_CISUJEDN UDRPROVO.NAJPARPRE_UCEJEDN%TYPE;
  mID_PROSTOR NAJPROS.ID_PROSTOR%TYPE;
  mID_SEGMENT NAJPROS.ID_SEGMENT%TYPE;
  mID_STAVOBJ NAJPROS.ID_STAVOBJ%TYPE;
  mRecNAJPARPRE RRRUTIL.T_PAR_GET_NAJPARPRE;
               
BEGIN

              ---raise_application_error( -20010 , mRecNAJPARPRE.mId_Najpros || '  ' || mRecNAJPARPRE.mID_DRUPRE || '  ' || mRecNAJPARPRE.mID_CISPREDVZT || '  ' || mRecNAJPARPRE.mOBDOBI_OD );
               mRecNAJPARPRE := mRecNAJPARPRE_VSTUP;
                 
               BEGIN     
                 BEGIN
                         
                   SELECT ID_PROSTOR , ID_SEGMENT INTO
                         mID_PROSTOR  , mID_SEGMENT
                     FROM NAJPROS
                     WHERE ID_NAJPROS = mRecNAJPARPRE.mId_Najpros;
                        
                    IF mID_PROSTOR IS NOT NULL THEN
                        SELECT ID_SKUTPRS , NAJPARPRE_UCEJEDN INTO mRecNAJPARPRE.mId_SKUTPRS , mNAJPARPRE_CISUJEDN
                        FROM V_VZTAHPRSTR
                          WHERE ID_NAJPROS =  mRecNAJPARPRE.mId_Najpros;
                    ELSE
                       SELECT A3.ID_SKUTPRS,A2.NAJPARPRE_UCEJEDN INTO mRecNAJPARPRE.mId_SKUTPRS , mNAJPARPRE_CISUJEDN
                         FROM SSSHLEDEJ_A MT , CVTYPSKUPR A1 , UDRPROVO A2 , CVTYPSKUPR A3
                           WHERE MT.ID_TYPPRS =  A1.ID_TYPPRS
                             AND A1.ID_KOLURC =  A3.ID_KOLURC
                             AND A3.ID_SKUTPRS IS NOT NULL
                             AND MT.ID_NAJPROS =  mRecNAJPARPRE.mId_Najpros
                             AND MT.ID_APROVOZNA = A2.ID_APROVOZNA;
                    END IF;

                  EXCEPTION
                      WHEN OTHERS THEN
    
      
                        raise_application_error( -20011 , ' GET_NAJPARPRE --  V_VZTAHPRSTR ID_NAJPROS ' || mRecNAJPARPRE.mId_Najpros || ' ' || SQLERRM ) ;
                 END;

</pre>

**Comment by darold** [comment]
Commit 81339c1 might fix this issue as well as rewriting of package function call in dynamic queries.

**Comment by okbob** [comment]
It is fixed, thank you
