### ISSUE TITLE
raw bytea uuid  and uuid_generate_v4()

### ISSUE THREAD

**Issue by jpcarayo** [darold/ora2pg#358]
1 - Having a table defined in Oracle with one column in RAW(16) and default value  set to sys_guid()
```
SQL> l
  1* select column_name, DATA_TYPE,DATA_DEFAULT from dba_tab_columns where column_name like upper ('id_pmsi_load')
SQL> /

COLUMN_NAME                    DATA_TYPE  DATA_DEFAULT
------------------------------ ----------     --------------------
ID_PMSI_LOAD                       RAW            sys_guid()
```
2 - ora2pg provides the following create table statement :
```
CREATE TABLE pmsi_load (
	id_pmsi_load **bytea** NOT NULL DEFAULT **uuid_generate_v4()**,
	prefix varchar(10),
	annee bigint,
	datealimentation timestamp
) ;
```
which fails with the following error :
ERREUR:  la colonne « idrec » est de type bytea alors que l'expression par défaut est de type uuid
ASTUCE : Vous devez réécrire l'expression ou lui appliquer une transformation de type.
_(sorry I got the error message in french)_

please note,
```
CREATE TABLE pmsi_load (
	id_pmsi_load **uuid** NOT NULL DEFAULT uuid_generate_v4(),
	prefix varchar(10),
	annee bigint,
	datealimentation timestamp
) ;
```
works well and seems to me more logical to use.

3 - When uuid_generate_v4() is defined as default, is it a good idea ora2pg fixes the column type to uuid  ?

Many thanks for your help.
Jean-Pierre

**Comment by darold** [comment]
Hi,

Last commit 11574a7 forces RAW(N) type with default value set to sys_guid() as UUID on PostgreSQL.

Merci pour la suggestion ;-)

**Comment by jpcarayo** [comment]
Many thanks  for this very quick help.
... A bientôt, ;-)
Jean-Pierre
