### ISSUE TITLE
Ora2PG test migration: Null constraints

### ISSUE THREAD

**Issue by liemdt1811** [darold/ora2pg#359]
Hi,
     If I have two tables with the same name in different schema and import to postgresql, then the test report will display the total constraints of 2 table.

Regards,
Liem

**Comment by darold** [comment]
Hi,

Can you precise where the wrong count is done, at Oracle or PostgreSQL side?

**Comment by liemdt1811** [comment]
It's at PostgreSQL side.
I got 5 not null constraints in table A of schema A and 6 on schema B.
The test results show that I have 11 on schema A and 11 on schema B.

**Comment by darold** [comment]
Ok, what is the value of he ora2pg.conf configuration directives: PG_SCHEMA, SCHEMA and EXPORT_SCHEMA? You can change the name of the values, this is not important, I just want to know how they are set.

**Comment by liemdt1811** [comment]
Hi Darold,
My configuration values were:
EXPORT_SCHEMA 1
SCHEMA
PG_SCHEMA

I left SCHEMA & PG_SCHEMA to blank

**Comment by darold** [comment]
Ok, this is what I expected. The test between Oracle and PostgreSQL content must be done per schema, multiple schema check at same time is not supported yet. I will update the documentation, where I don't think it is explained.

**Comment by liemdt1811** [comment]
Thanks, so I think it's better to migrate per schema than all at once.
