### ISSUE TITLE
On-the-fly migration to Postgresql

### ISSUE THREAD

**Issue by Narayanamoorthys** [darold/ora2pg#361]
I am using Ora2pg 18.1

I am trying to migrate a small sample Oracle DB to Postgresql. I can export to output.sql and import it in Postgresql without any issues. But on-the-fly option is not working although I specified PG_DSN, PG_USER and PG_PWD in the configuration file as well as in command line. Have verified all dependencies and also test the connectivity to Postgresql with a sample perl script.
Not sure why on-the-fly migration is not working. Debug option doesn't show any error. Any pointers to troubleshoot?

**Comment by darold** [comment]
On the fly migration only works with data migration, DDL are only dumped to file so be able to process the output in case there is some adaptation to apply. "On the fly" action type is COPY.

**Comment by Narayanamoorthys** [comment]
Thanks. That helps.
