### ISSUE TITLE
"Perform" still missing when translating procedures

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#364]
Hello,

I still cannot get the "perform" prefix when ora2pg translates an Oracle Procedure.
The procedure has no OUT parameter or has no parameter at all.
I have the same result if all procedures are declared in the package header or not.
Moreover, one of the calls is not even prefixed by the package-schema name.

See the calls to maj_cpt, pck_common.INSERT_LOG and count_incrv2 in the .zip I will send you.

Best regards,
Eric

**Comment by darold** [comment]
Thanks for the example, it help a lot. Commit c6e3838 might solve these issues.

**Comment by edelanoe** [comment]
Sorry, with your last commit, I still generate no "perform" from the sample code I sent on friday.
Download done this morning 2017/04/10 09:21.
Best regards,
Eric

**Comment by darold** [comment]
Right this was only working with file input. Commit  d0f446b might solve this pending problem.

**Comment by edelanoe** [comment]
Thanks for the commit, I see a great progress.
Still, a procedure call directly following "THEN" does not get its "PERFORM".

Best rgds,
Eric

**Comment by darold** [comment]
Which one? The only one I see is a call to a DBMS_SCHEDULER procedure which must be manually rewritten.

**Comment by edelanoe** [comment]
Sorry, my correlation was wrong. I miss PERFORM when the called procedure is out of current package AND the "outside" package is not in the script input.
This might be more complicated to solve, because of this external dependance.

Example:

Oracle:
create or replace package body TEST_PCK_CPT AS
    PROCEDURE LOCAL_TEST_PROC(p_err boolean default null) IS
    BEGIN
        if p_err = TRUE then
            raise_application_error(-20000,'Error generated in LOCAL_TEST_PROC');
        end if;
    EXCEPTION WHEN OTHERS THEN
            pck_common.insert_log('TEST_PCK', 'there was an error in LOCAL_TEST_PROC');
    END;
    
    FUNCTION TEST_INSERT_LOG RETURN VARCHAR2 IS
    BEGIN
        pck_common.insert_log('this trace is just after BEGIN','TEST_PCK');
        LOCAL_TEST_PROC();
        TEST_PCK_CPT.LOCAL_TEST_PROC();
        if 1 = 1 then
            pck_common.insert_log('TEST_PCK', 'the "IF" test has passed');
            LOCAL_TEST_PROC();
            TEST_PCK_CPT.LOCAL_TEST_PROC();
        else
            pck_common.insert_log('TEST_PCK', 'the "IF" test has failed');
            LOCAL_TEST_PROC();
            TEST_PCK_CPT.LOCAL_TEST_PROC();
        end if;
        pck_common.insert_log('TEST_PCK', 'this trace is just after ";"');
        RETURN('0');
    EXCEPTION WHEN OTHERS THEN LOCAL_TEST_PROC(TRUE);
    END;

END TEST_PCK_CPT;
/
------------------------------------------------------------------------------
-- in the .conf: ALLOW TEST_PCK_CPT
------------------------------------------------------------------------------
-- ora2pg:
CREATE OR REPLACE FUNCTION test_pck_cpt.local_test_proc (p_err boolean default null) RETURNS VOID AS $body$
BEGIN
        if p_err = TRUE then
            RAISE EXCEPTION '%', 'Error generated in LOCAL_TEST_PROC' USING ERRCODE = '45000';
        end if;
    EXCEPTION WHEN OTHERS THEN
            pck_common.insert_log('TEST_PCK', 'there was an error in LOCAL_TEST_PROC');
    END;


$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION test_pck_cpt.local_test_proc (p_err boolean default null) FROM PUBLIC;

CREATE OR REPLACE FUNCTION test_pck_cpt.test_insert_log () RETURNS varchar AS $body$
BEGIN
        pck_common.insert_log('this trace is just after BEGIN','TEST_PCK');
        PERFORM test_pck_cpt.local_test_proc();
        PERFORM test_pck_cpt.local_test_proc();
        if 1 = 1 then
            pck_common.insert_log('TEST_PCK', 'the "IF" test has passed');
            PERFORM test_pck_cpt.local_test_proc();
            PERFORM test_pck_cpt.local_test_proc();
        else
            pck_common.insert_log('TEST_PCK', 'the "IF" test has failed');
            PERFORM test_pck_cpt.local_test_proc();
            PERFORM test_pck_cpt.local_test_proc();
        end if;
        pck_common.insert_log('TEST_PCK', 'this trace is just after ";"');
        RETURN('0');
    EXCEPTION WHEN OTHERS THEN PERFORM test_pck_cpt.local_test_proc(TRUE);
    END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;

**Comment by darold** [comment]
Yes, this can not be solved, the package function must be registered by Ora2Pg to be replaced in the plpgsql code otherwise Ora2Pg as no way to know that this is a function name. When using Ora2Pg to export from an Oracle database it scan all package and function/procedure before parsing the PL/SQL code to gather all functions names.

**Comment by edelanoe** [comment]
Ok I give up.
For tracing purpose, let me suggest the following assertion, which is only a supposed starting point:
In an Oracle program unit, a procedure call is found after a BEGIN, THEN, ELSE, LOOP or ";" , never before a ":=" (in the same instruction ending by ";"), and it can be recognized because it is not a keyword of SQL or PL/SQL.

Rgds,
Eric
