### ISSUE TITLE
The translation procedures with OUT parameters to PostgreSQL is not correct

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#365]
Currently Ora2pg produces invalid command:
<pre>
SELECT INS_VOL_KRIT_MESIC(   mLIDENT , mTransakce, mChybaText ,  mPocOK  , mPocError  ,  mID_APROVOZNA  , mPoradiUza  ) INTO (mChybaText,mPocOK,mPocError,mPoradiUza  );
</pre>

This should be translated to:
<pre>
SELECT * FROM INS_VOL_KRIT_MESIC(   mLIDENT , mTransakce, mChybaText ,  mPocOK  , mPocError  ,  mID_APROVOZNA  , mPoradiUza  ) INTO mChybaText,mPocOK,mPocError,mPoradiUza  ;
</pre>

PLpgSQL doesn't have some simple command for record to variable assignment

Example:
<pre>
create or replace function pro(int, out a int, out b int) as $$
begin a := $1; b := $1; end 
$$ language plpgsql;

do $$ declare x int; y int; 
begin 
  select aux.a, aux.b from pro(10) aux into x, y; 
raise notice '<<% %>>', x, y; 
end $$;
</pre>

**Comment by darold** [comment]
Right, invalid translated code might now be solved by commit 3349a26. Thank for the report.

**Comment by okbob** [comment]
I found few functions with OUT params, where ora2pg uses `RETURNS void` still
<pre>
CREATE EXTENSION IF NOT EXISTS dblink;

CREATE OR REPLACE FUNCTION get_abo_dupl_spec ( mID_PARABOK PARABOK.ID_PARABOK%TYPE , mTypPOLOZKY PARABOKPC.TYP_POLOZKY%TYPE , mTYP_FP PARABOKPC.TYP_FP%TYPE , mVarsym PARABOKPC.VARSYM%TYPE , mSPESYM OUT PARABOKPC.SPESYM%TYPE , mPoradi OUT PARABOKPC.PORADI%TYPE , mSPESYMPOM OUT PARABOKPC.SPESYMPOM%TYPE ) RETURNS VOID AS $body$
DECLARE
        -- Change this to reflect the dblink connection string
        v_conn_str  text := 'port=5432 dbname=testdb host=localhost user=pguser password=pgpwd';
        v_query     text;

BEGIN
        v_query := 'SELECT true FROM get_abo_dupl_spec_atx ( ' || quote_nullable(mID_PARABOK) || ',' || quote_nullable(mTypPOLOZKY) || ',' || quote_nullable(mTYP_FP) || ',' || quote_nullable(mVarsym) || ',' || quote_nullable(mSPESYM) || ',' || quote_nullable(mPoradi) || ',' || quote_nullable(mSPESYMPOM) || ' )';
        PERFORM * FROM dblink(v_conn_str, v_query) AS p (ret boolean);

END;
$body$ LANGUAGE plpgsql SECURITY DEFINER;
</pre>

Probably related to using autonomous transaction.

**Comment by darold** [comment]
Right, will be fixed tomorrow.

**Comment by okbob** [comment]
It is fixed, Thank you
