### ISSUE TITLE
PG_SCHEMA parameter bug?

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#368]
The documentation for PG_SCHEMA indicates that this field is used to specify the PG search path.   But when I set it to a comma-delimited list, it actually tries to create a schema with the entire comma-delimited list!

For instance, if PG_SCHEMA = **scott,pg_catalog**
it creates a schema called scott,pg_catalog!

Is this a bug or am I missing something here?

Here is the DDL snippet generated by ora2pg:
```
-- Generated by Ora2Pg, the Oracle database Schema converter, version 18.1
-- Copyright 2000-2017 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;sid=orcl

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE SCHEMA "scott,pg_catalog";
ALTER SCHEMA "scott,pg_catalog" OWNER TO scott;

SET search_path = "scott,pg_catalog";

CREATE TABLE dept (

```

**Comment by darold** [comment]
It depends of the context, PG_SCHEMA can take a comma separated list of schema name when using an export type different fromTABLE or when CREATE_SCHEMA is not enabled. I will add a note to documentation.

**Comment by MichaelDBA** [comment]
Thanks, I will let you close it then.  Perhaps you want to keep it open as a documentation reminder.

**Comment by darold** [comment]
Documentation updated with commit ea14cda
