### ISSUE TITLE
Slow Oracle response time

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#369]
I am doing a simple export of SCOTT schema tables from oracle using ora2pg, and it spends a lot of time, about 10-15 minutes at the step below (**Retrieving table information...**).  Any idea what is the holdup?

```
/usr/local/bin/ora2pg -d -c /etc/ora2pg/ora2pg.conf.tiger   -t TABLE   -o tables.sql
Ora2Pg version: 18.1
Trying to connect to database: dbi:Oracle:host=localhost;sid=orcl
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
DEBUG: executing initial command to Oracle
Retrieving table information...

```
Upon further investigation, it is hanging on this statement (note: end is truncated)
`SELECT CONSTRAINT_NAME,R_CONSTRAINT_NAME,SEARCH_CONDITION,DELETE_RULE,DEFERRABLE,DEFERRED,R_OWNER,TABLE_NAME,OWNER,VALIDATED FROM DBA_CONSTRAINTS WHERE CONSTRAINT_TYPE='C' AND OWNER = 'SCOTT'  AND (  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^USLOG\$_.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^MLOG\$_.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^RUPD\$_.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^MDXT_.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^MDRT_.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^MDRS_.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^DR\$.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^CLI_SWP\$.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^LOGMNR\$.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^REPCAT\$.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^JAVA\$.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^AQ\$.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^BIN\$.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SDO_GR_.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^.*\$JAVA\$.*$') AN`

**Comment by darold** [comment]
Looking at Oracle catalog is very slow there is no indexes help on the catalog. Most of the time the second time ora2pg is executed it takes less time to complete because some collected information are still in cache. Can you confirm this last affirmation?

**Comment by MichaelDBA** [comment]
I have run it multiple times in a row with the same slow response time, so probably not cached.

**Comment by darold** [comment]
So this is probably that Ora2Pg is user friendly, it keep you the time to drink a coffee :-) Seriously extracting information from the catalog take time, this is Oracle that it is slow on this part, I've rewritten all queries to extract all information at a time following the object type and not querying columns information per table per example. But clearly the exclusion of tons of unwanted objects using REGEXP_LIKE doesn't help. Let's keep this issue open I will look if something can be done to improve again the catalog querying.

**Comment by MichaelDBA** [comment]
So here is an update....
I ran this to make sure stats are up to date:
```
begin
DBMS_STATS.GATHER_SCHEMA_STATS
DBMS_STATS.GATHER_DATABASE_STATS 
DBMS_STATS.GATHER_DICTIONARY_STATS
end;
/
```
Still no improvement, but here is the catcher,  some other person was doing some big time loads and such regarding oracle at the time, and the load was about 850% on a small EC2 instance.

So I will update you later if this is still a problem, betcha it isn't but will let you know in this issue later today.

**Comment by MichaelDBA** [comment]
Let's close this since most of my delay was due to the load, although the system table query is a wee bit slow.  Perhaps note in documentation somewhere that performance might be improved by updating stats on oracle.
```
begin
DBMS_STATS.GATHER_SCHEMA_STATS
DBMS_STATS.GATHER_DATABASE_STATS 
DBMS_STATS.GATHER_DICTIONARY_STATS
end;
/
```

**Comment by darold** [comment]
Note added to documentation in commit c12409c, thanks.
