### ISSUE TITLE
Could the $VERSION indicator be more precise

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#372]
Very small issue, but useful regarding the great progress since version 18.1:
Could the build number be included in the $VERSION string, like "18.1 build xxxx" for example ?
... So that we have the trace of it in generated files.

Rgds,
edelanoe

**Comment by darold** [comment]
Unfortunately there's no way to do that with git.

**Comment by edelanoe** [comment]
Git cannot trace a revision number or a full Header that includes a date ? 
For example, with my old-fashion CVS, I can put dollar+header+dollar in a comment or in the value of a string variable. Thus I have the revision number + timestamp in the compiled or SGBD code (after commit)

**Comment by darold** [comment]
Yes this is what I mean, you can not do that with git.

**Comment by edelanoe** [comment]
OK. What are your criteria to publish a release ? (18.2?)

**Comment by darold** [comment]
Usually a major version is used when there is new features or backward incompatibilities with previous release. Otherwise minor version are maintenance release but often they can include some minor features.
