### ISSUE TITLE
TYPE conversion error?

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#373]
I get fine past types like this:
`CREATE TYPE t_claim_action_rec AS (`
But I get errors when it tries to do it like this
`CREATE OR REPLACE TYPE       "STRING_AGG_TYPE"                                          AS OBJECT(`

Two errors on that line, the first is there is no CREATE OR REPLACE, it's only CREATE in PG 9.6.
Then it barfs on the "AS OBJECT" syntax:
`CREATE TYPE       "STRING_AGG_TYPE"                                          AS OBJECT(`

**Comment by MichaelDBA** [comment]
This is the exact body of the function in oracle:
```
create or replace TYPE         "TMR_T"                                          AS OBJECT (
   starttime INTEGER,
   endtime INTEGER,
   startcputime INTEGER,
   endcputime INTEGER,
   repetitions INTEGER,
   NAME VARCHAR2 (2000),
   MEMBER PROCEDURE go,
   MEMBER PROCEDURE stop (show_timing IN BOOLEAN := TRUE),
   MEMBER FUNCTION timing RETURN INTEGER,
   MEMBER FUNCTION cputiming RETURN INTEGER,
   MEMBER FUNCTION timing_desc RETURN VARCHAR2,
   MEMBER PROCEDURE reset (name IN VARCHAR2 := NULL),
   STATIC FUNCTION make (name IN VARCHAR2, repetitions IN INTEGER := 1) RETURN tmr_t,
   CONSTRUCTOR FUNCTION tmr_t (self IN OUT tmr_t, name IN VARCHAR2, repetitions IN INTEGER) RETURN self AS result
);
```

**Comment by darold** [comment]
Hi Michael,

You should have a comment before the type output like that:
```
-- Unsupported, please edit to match PostgreSQL syntax
```
meaning that you have to proceed to a manual rewrite of this custom type, this is why the exported type is simply the Oracle source code.

**Comment by MichaelDBA** [comment]
ahh gotcha, missed that line, thanks!
