### ISSUE TITLE
question: Can I override any config parameter on the command line?

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#375]
And if so, what is the syntax?

For instance if EXPORT_SCHEMA 1,
then search_path will be set to $SCHEMA, pg_catalog

But I want public to be in the mix, so how do i do that with PG_SCHEMA?
$SCHEMA, public, pg_catalog

where $SCHEMA is a substitution variable not a hard coded value

**Comment by MichaelDBA** [comment]
Let me give the big picture about what I am trying to do...

goal: I want to use one config file for all my objects.

and override conf file parameters on the command line.

**Comment by darold** [comment]
Some configuration directives can be overridden by command line parameters, have a look to `ora2pg --help` to get the ora2pg usage.

For example, ALLOW directive is overridden by `-a` and SCHEMA by `-n`.

**Comment by MichaelDBA** [comment]
What I really wanted to do was append "public, pg_catalog" to the oracle owner I was connecting to so that the resulting search_path would be myoracleschema, public, pg_catalog in sql output files.

**Comment by darold** [comment]
I understand, please upgrade to latest development code, commit 1982056 adds `-N | --pg_schema` command line option to be able to override the PG_SCHEMA configuration directive. When this option is set at command line, EXPORT_SCHEMA is automatically activated. For example:
```
 ora2pg -c config/ora2pg.conf -t VIEW -b tmp/ -o views.sql -N "myoracleschema,public"
```
will append `SET search_path = "myoracleschema,public";` to each view export file.

**Comment by MichaelDBA** [comment]
oh my gosh, did you just do that? Thank u!
