### ISSUE TITLE
compile schema '1'

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#376]
Maybe this is not a bug, but I am not sure. Now, I am debugging all queries used to get data from Oracle. One strange is:
<pre>
Force Oracle to compile schema before code extraction
-- Sat Apr 29 21:16:49 2017
-- do /usr/local/share/perl5/Ora2Pg.pm 13960
-- _compile_schema /usr/local/share/perl5/Ora2Pg.pm 1285
-- _init /usr/local/share/perl5/Ora2Pg.pm 392
-- new /usr/local/bin/ora2pg 250
begin
DBMS_UTILITY.compile_schema(schema => '1');
end;
</pre>
I have not any schema '1'. Our config value is '1', and I expect `sys_context('USERENV', 'SESSION_USER')`. But this doesn't work, not work like it is documented.

**Comment by darold** [comment]
Right there was an errata in the operator used in the conditonal block in _compile_schema() method. Commit 0b4f024 might fix it.

**Comment by okbob** [comment]
looks so this is not supported by Oracle:
<pre>
Force Oracle to compile schema before code extraction
-- Sun Apr 30 06:41:57 2017
-- do /usr/local/share/perl5/Ora2Pg.pm 13935
-- _compile_schema /usr/local/share/perl5/Ora2Pg.pm 1287
-- _init /usr/local/share/perl5/Ora2Pg.pm 392
-- new /usr/local/bin/ora2pg 252
EXEC DBMS_UTILITY.compile_schema(schema => sys_context('USERENV', 'SESSION_USER'));

DBD::Oracle::db do failed: ORA-00900: invalid SQL statement (DBD ERROR: OCIStmtExecute) [for Statement "EXEC DBMS_UTILITY.compile_schema(schema => sys_context('USERENV', 'SESSION_USER'));"] at /usr/local/share/perl5/DBI/Log.pm line 75.
FATAL: ORA-00900: invalid SQL statement (DBD ERROR: OCIStmtExecute)
Aborting export...
</pre>

**Comment by darold** [comment]
Right, the code in the _compile_schema() method was cleary obsolete, I've rewritten all in commit  353f7fa.

Here is the new behavior of the COMPILE_SCHEMA directive updated in documentation:
```
    COMPILE_SCHEMA
        By default Ora2Pg will only export valid PL/SQL code. You can force
        Oracle to compile again the invalidated code to get a chance to have
        it obtain the valid status and then be able to export it.

        Enable this directive to force Oracle to compile schema before
        exporting code. When this directive is enabled and SCHEMA is set to
        a specific schema name, only invalid objects in this schema will be
        recompiled. If SCHEMA is not set then all schema will be recompiled.
        To force recompile invalid object in a specific schema, set
        COMPILE_SCHEMA to the schema name you want to recompile.

        This will ask to Oracle to validate the PL/SQL that could have been
        invalidate after a export/import for example. The 'VALID' or
        'INVALID' status applies to functions, procedures, packages and user
        defined types.
```

**Comment by okbob** [comment]
looks fixed, thank you.
