### ISSUE TITLE
comments inside function header are not correctly placed

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#377]
I know so the code, that I transform is suck code, but it is reality :(

The  original header:
<pre>
CREATE OR REPLACE procedure IDES_JMMAJ.UCEHLAFAK_ZALOHA_LOKALIZACE
(mID_UCEDOKLAD in NUMBER, 
mID_ODBMISTO in out NUMBER, 
mID_SEGMENT in out NUMBER,
mID_PROSTOR in out NUMBER,
mAKOD_OBJEKT in OUT ucepohyb.Akod_Objekt%type ,
mAKOD_BUDOVY in OUT ucepohyb.akod_budovy%type, 
mAKOD_SEGMENT in OUT ucepohyb.akod_segment%type ,
mAKOD_PROSTOR in OUT ucepohyb.akod_prostor%type ,
mANAJMENO in OUT ucepohyb.anajmeno%type, 
mAULICE in OUT ucepohyb.aulice%type,
mACISPOP in OUT ucepohyb.acispop%type, 
mACISORI in OUT ucepohyb.acisori%type, 
mAKOD_PRVKU in OUT ucepohyb.akod_prvku%type,
mABYT_NEBYT in OUT ucepohyb.abyt_nebyt%type,
mID_CISUSTRD in OUT NUMBER )
  
/*
  AKOD_OBJEKT, AKOD_BUDOVY, AKOD_SEGMENT,
    AKOD_PROSTOR,ANAJMENO, AULICE,
    ACISPOP, ACISORI, AKOD_PRVKU,
    ABYT_NEBYT

    mAKOD_OBJEKT, mAKOD_BUDOVY, mAKOD_SEGMENT,
    mAKOD_PROSTOR,mANAJMENO, mAULICE,
    mACISPOP, mACISORI, mAKOD_PRVKU,
    mABYT_NEBYT

*/

is
</pre>

The translated header:
<pre>
CREATE OR REPLACE FUNCTION ucehlafak_zaloha_lokalizace (mID_UCEDOKLAD numeric, mID_ODBMISTO INOUT numeric, mID_SEGMENT INOUT numeric,
mID_PROSTOR INOUT numeric,
mAKOD_OBJEKT INOUT ucepohyb.Akod_Objekt%type,
mAKOD_BUDOVY INOUT ucepohyb.akod_budovy%type,
mAKOD_SEGMENT INOUT ucepohyb.akod_segment%type ,
mAKOD_PROSTOR INOUT ucepohyb.akod_prostor%type ,
mANAJMENO INOUT ucepohyb.anajmeno%type,
mAULICE INOUT ucepohyb.aulice%type,
mACISPOP INOUT ucepohyb.acispop%type,
mACISORI INOUT ucepohyb.acisori%type,
mAKOD_PRVKU INOUT ucepohyb.akod_prvku%type,
mABYT_NEBYT INOUT ucepohyb.abyt_nebyt%type,
mID_CISUSTRD INOUT numeric ) /*
  AKOD_OBJEKT, AKOD_BUDOVY, AKOD_SEGMENT,
    AKOD_PROSTOR,ANAJMENO, AULICE,
    ACISPOP, ACISORI, AKOD_PRVKU,
    ABYT_NEBYT

    mAKOD_OBJEKT, mAKOD_BUDOVY, mAKOD_SEGMENT,
    mAKOD_PROSTOR,mANAJMENO, mAULICE,
    mACISPOP, mACISORI, mAKOD_PRVKU,
    mABYT_NEBYT

*/
 ) AS $body$
DECLARE
</pre>

There is right parenthesis 2x

**Comment by darold** [comment]
Commit dc22575 might solve this issue.

**Comment by okbob** [comment]
It is fixed, thank you
