### ISSUE TITLE
-N enforce using original schema

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#378]
I am not sure if it is bug. Maybe I don't understand to sense of this option.

When I used a option -N pgschema - I expected so pgschema will be used in exported procedures. It was not - There was SET SEARCH_PATH to pgschema. Procedures was exported with Oracle schema. is it expected? 
Is there way, how to store exported objects in some specific PostgreSQL schema? We need to separate original Oracle procedures and functions. We would to use PostgreSQL schemas.

**Comment by darold** [comment]
The -N parameter force EXPORT_SCHEMA to be enabled, this is why the function names are prefixed with their schema. I will improve this patch to not prefix functions with their schema  when PG_SCHEMA is enabled.

**Comment by darold** [comment]
Commits cb94dfa and f824b9a might solve this problem. When PG_SCHEMA is defined, always set search_path to its value.

**Comment by okbob** [comment]
Now, search_path is specified and qualified name is not used. 
<pre>
SET search_path = ides_procs,public;                                                                                   
\set ON_ERROR_STOP ON                                                                                                  
                                                                                                                                                                                                                                                                                                                                                         
CREATE OR REPLACE FUNCTION tvorba_vyrpod_odecty ( mID_VYROK VYROK.ID_VYROK%TYPE , mID_ODBMISTO OBPODBMI.ID_ODBMISTO%TYP
DECLARE   
</pre>
If it is expected, then this issue can be closed.

**Comment by darold** [comment]
Yes if you want the function to be prefixed with the schema name you need to enable EXPORT_SCHEMA, this is the expected behavior. Thanks for the feedback.
