### ISSUE TITLE
OUT parameter is not removed from argument list 

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#379]
I have a procedure with `IN`, `INOUT` and `OUT` parameters. Now, ora2pg uses correct pattern for calling procedures with `OUT` parameters, but `OUT` parameters are not removed from parameters list.

Oracle procedure:
<pre>
CREATE OR REPLACE procedure IDES_JMMAJ.KONTROLA_NAJVOKRIT( mWhere IN VARCHAR2 , mID_CKRITNAR IN NUMBER , mID_POLONAJ  IN NUMBER ,  mOBDOBI_OD IN OUT  DATE ,  mOBDOBI_DO IN OUT DATE , mLIDENT IN NUMBER , mTransakce IN CHAR , mPocetChyb OUT NUMBER ) 
</pre>
It is correctly translated to Postgres:
<pre>
CREATE OR REPLACE FUNCTION ides_procs.kontrola_najvokrit(mwhere text, mid_ckritnar numeric, mid_polonaj numeric, INOUT mobdobi_od date, INOUT mobdobi_do date, mlident numeric, mtransakce character, OUT mpocetchyb numeric)
 RETURNS record
 LANGUAGE plpgsql
 SECURITY DEFINER
</pre>
In another function I'll try to call this function:

Oracle:
<pre>
    KONTROLA_NAJVOKRIT( ' ID_NAJVZTAH = ' || mID_NAJVZTAH , mID_CKRITNAR , mID_POLONAJ_KONTROLA  , mOBDOBI_OD_VLAST_KON ,   mOBDOBI_DO_VLAST_KON  , mLIDENT  , 'N' , mPocetChyb  );
</pre>

PostgreSQL:
<pre>
        SELECT * FROM KONTROLA_NAJVOKRIT( ' ID_NAJVZTAH = ' || mID_NAJVZTAH_NAJEMNIK , mID_CKRITNAR , mID_POLONAJ_KONTROLA  , mOBDOBI_OD_VLAST_KON ,   mOBDOBI_DO_VLAST_KON  , mLIDENT  , 'N' , mPocetChyb  )
         INTO mOBDOBI_OD_VLAST_KON,mOBDOBI_DO_VLAST_KON,mPocetChyb;
</pre>
It is wrong, because `mPocetChyb` is OUT parameter, and should be used only like target.

The correct usage should be:
<pre>
        SELECT * FROM KONTROLA_NAJVOKRIT( ' ID_NAJVZTAH = ' || mID_NAJVZTAH_NAJEMNIK , mID_CKRITNAR , mID_POLONAJ_KONTROLA  , mOBDOBI_OD_VLAST_KON ,   mOBDOBI_DO_VLAST_KON  , mLIDENT  , 'N')
         INTO mOBDOBI_OD_VLAST_KON,mOBDOBI_DO_VLAST_KON,mPocetChyb;
</pre>

**Comment by darold** [comment]
Commit e18a71e might solve this issue.

**Comment by okbob** [comment]
It is fixed, Thank you

**Comment by darold** [comment]
Please check that last commit 04f1682 doesn't break this fix.

**Comment by okbob** [comment]
looks correct

**Comment by darold** [comment]
Good news
