### ISSUE TITLE
missing parenthesis after VALUES keyword

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#380]
Oracle doesn't require parenthesis after VALUES -  this is proprietary syntax for inserting composite value to table https://www.macro.com.ar/PortalMacro/content/conn/macro/path/Contribution%20Folders/Revision/MacroEnLosMedios/PLLes06.pdf.

Oracle:
<pre>
uobjlok  OBPVOBJLOK%ROWTYPE;
BEGIN
  INSERT INTO OBPVOBJLOK VALUES uobjlok;
  ...
</pre>

Ora2pg now doesn't recognize this pattern and produce invalid statement.

The fix should not be hard, because PostgreSQL has similar proprietary syntax
<pre>
uobjlok  OBPVOBJLOK%ROWTYPE;
BEGIN
  INSERT INTO OBPVOBJLOK VALUES (uobjlok.*);
  ...
</pre>

**Comment by darold** [comment]
I don't know about that, commit bcbcb60 might translate this proprietary syntax.

**Comment by okbob** [comment]
It is perfect now :). Thank you
