### ISSUE TITLE
Unordered lines when `FOR` with nested exception handling is used (outer exception handling is used too)

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#381]
Oracle: see attachment 
[zmena_predpisu.sql.txt](https://github.com/darold/ora2pg/files/969946/zmena_predpisu.sql.txt)

The nested exception handling is badly placed and cycle FOR syntax is invalid too.

Broken part in translated code:
<pre>
                IF mZiv_zpet = '0' THEN
                  IF mID_predpis_zpet IS NOT NULL THEN
                     INSERT INTO RRRNAJUZA_ERR( COLUMN_NAME ,AKCE , TEXT , CHYBA , INFO , ID_AKCE)
                            VALUES ( 'ID_POL_PRED ' , 'ZMENA_PREDPISU_' || mTypAkce || 'PODPOLOZKA_22' , mRecNajpoloz.ID_POL_PRED , 'Nenašel položku' , '' , mID_AKCE );
                    BEGIN
                       SELECT * INTO mRecNajpoloz
                            FROM NAJPOLOZ WHERE ID_PREDPIS = mAktPredpis
                                          AND ID_POLONAJ = mID_POLONAJ;
                    EXCEPTION    
                       WHEN OTHERS THEN 
         
                         INSERT INTO RRRNAJUZA_ERR( COLUMN_NAME ,AKCE , TEXT , CHYBA , INFO , ID_AKCE)
                            VALUES ( 'ID_POL_PRED ' , 'ZMENA_PREDPISU_' || mTypAkce || 'PODPOLOZKA' , mRecNajpoloz.ID_POL_PRED , 'Nenašel položku' , '' , mID_AKCE );
                            mPocError := mPocError + 1;

                    END;
               
                    INSERT INTO RRRNAJUZA_ERR( COLUMN_NAME ,AKCE , TEXT , CHYBA , INFO , ID_AKCE)
                            VALUES ( 'ID_POL_PRED ' , 'ZMENA_PREDPISU_' || mTypAkce || 'PODPOLOZKA_33' , mRecNajpoloz.ID_POL_PRED , 'Nenašel položku' , '' , mID_AKCE );

                    DELETE FROM NAJPODPOL WHERE ID_POL_PRED = mRecNajpoloz.Id_Pol_Pred
                                            AND ID_CPODPOL = mID_CPODPOL;
                    FOR EXECUTE qNajpoloz IN ( SELECT * FROM NAJPODPOL
                         WHERE ID_POL_PRED = mRecNajpoloz.Id_Pol_Pred
                           AND ID_CPODPOL = mID_CPODPOL )
                    LOOP

                       INSERT INTO RRRNAJUZA_ERR( COLUMN_NAME ,AKCE , TEXT , CHYBA , INFO , ID_AKCE)
                            VALUES ( 'ID_POL_PRED ' , 'ZMENA_PREDPISU_' || mTypAkce || 'PODPOLOZKA_B' , mRecNajpoloz.ID_POL_PRED , 'Nenašel položku' , '' , mID_AKCE );

                      INSERT INTO NAJPODPOL( ID_CNAJVYPPOL , ID_CPODPOL , ID_POL_PRED , JED_CASTKA , ZIV, NAJPOC, ID_ASPRAVCE , ID_APROVOZNA , LIDENT  , GEN_PREDPIS , OBDOBI_DO , PLATNOST_OD , KRAT_MES , OBDOBI_OD , CVZNIKRADK , POC_OSO , ID_AKCE )
                        VALUES ( qNajpoloz.ID_CNAJVYPPOL , qNajpoloz.ID_CPODPOL , mRecNajpoloz.ID_POL_PRED , qNajpoloz.JED_CASTKA , qNajpoloz.ZIV , qNajpoloz.NAJPOC , qNajpoloz.ID_ASPRAVCE , qNajpoloz.ID_APROVOZNA , qNajpoloz.LIDENT , 'B' , mRecNajpoloz.OBDOBI_DO , mRecNajpoloz.PLATNOST_OD , qNajpoloz.KRAT_MES , mRecNajpoloz.OBDOBI_OD ,RRRUTIL.HROMADNA_ZMENA , qNajpoloz.POC_OSO , mID_AKCE  );
                   
                    END LOOP;
                  ELSE
                  
                    DELETE FROM NAJPODPOL WHERE ID_POL_PRED = mRecNajpoloz.Id_Pol_Pred
                                            AND ID_CPODPOL = mID_CPODPOL 
                                            AND CVZNIKRADK = RRRUTIL.HROMADNA_ZMENA;

                  END IF;

  
                END IF;

             END IF;

            END IF;
           END IF;
</pre>

**Comment by darold** [comment]
Can you post the full Oracle source function code, here it is truncated so it is not possible for me to reproduce the issue.

**Comment by okbob** [comment]
see attachment zmena_predpisu.sql.txt

**Comment by darold** [comment]
Thanks, commit 41d818a fix the issue on FOR ... IN loop but I don't see what is the problem with the nested exception.

**Comment by okbob** [comment]
You have true - this code is too complex and I seen something wrong. So this issue is fixed. Thank you again.
