### ISSUE TITLE
The translation of Oracle OUTER joins to ANSI SQL is broken by parenthesis

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#382]
We found a query, where translation of oracle outer joins doesn't work correctly. Probably it is related to using parenthesis in predicate
<pre>
WHERE ...
  AND (A9.ID_SEGMENT= A10.ID_SEGMENT(+)
  AND ((A10.TYP = 'S') OR (A10.TYP IS NULL )))
</pre>
This expression is same like:
<pre>
WHERE ...
  AND A9.ID_SEGMENT= A10.ID_SEGMENT(+)
  AND (A10.TYP = 'S') OR (A10.TYP IS NULL ))
</pre>

Oracle:
<pre>
CREATE OR REPLACE VIEW V_OBPREVIZE_CHYBA AS
SELECT MT.ID_OBPREVIZE
          FROM OBPREVIZE MT , CISDRUREV A1 ,
                UDRSPRVC A2 , CLEOSOBY A4,
                OBPREVIZE A5 , UDRPROVO A6 ,
                CLEOSOBY A7 , OBPVREVLOK A8,
           V_MAXLOKREVIZE A9 ,SSSHLEDEJ_A A10,
           SSSLOGIN A11, SSSLOGIN A12
                 WHERE MT.ID_CISDRUREV  = A1.ID_CISDRUREV(+)
               AND  MT.ID_ASPRAVCE = A2.ID_ASPRAVCE(+)
               AND MT.ID_CCLE_ODB = A4.ID_CCLE(+)
               AND MT.ID_OBPREVIZE_A = A5.ID_OBPREVIZE_A(+)
               AND MT.ID_APROVOZNA = A6.ID_APROVOZNA(+)
               AND MT.ID_CCLE = A7.ID_CCLE(+)
               AND MT.ID_OBPREVIZE = A9.ID_OBPREVIZE(+)
               AND ( A9.ID_SEGMENT= A10.ID_SEGMENT(+) ----- <<<<<<<<<
               AND ( (A10.TYP = 'S') OR (A10.TYP IS NULL ))) ----- <<<<<<<<<
               AND MT.LIDENT= A11.ID_SSSLOGIN(+)
               AND MT.LIDENT_ZMENA= A12.ID_SSSLOGIN(+)
               AND A9.ID_OBPVREVLOK=A8.ID_OBPVREVLOK(+);
</pre>

Ora2pg result:
<pre>
CREATE OR REPLACE VIEW v_obprevize_chyba (id_obprevize) AS SELECT  MT.ID_OBPREVIZE
           FROM ssshledej_a a10, obprevize mt
LEFT OUTER JOIN cisdrurev a1 ON (MT.ID_CISDRUREV = A1.ID_CISDRUREV)
LEFT OUTER JOIN udrsprvc a2 ON (MT.ID_ASPRAVCE = A2.ID_ASPRAVCE)
LEFT OUTER JOIN cleosoby a4 ON (MT.ID_CCLE_ODB = A4.ID_CCLE)
LEFT OUTER JOIN obprevize a5 ON (MT.ID_OBPREVIZE_A = A5.ID_OBPREVIZE_A)
LEFT OUTER JOIN udrprovo a6 ON (MT.ID_APROVOZNA = A6.ID_APROVOZNA)
LEFT OUTER JOIN cleosoby a7 ON (MT.ID_CCLE = A7.ID_CCLE)
LEFT OUTER JOIN v_maxlokrevize a9 ON (MT.ID_OBPREVIZE = A9.ID_OBPREVIZE)
LEFT OUTER JOIN ssslogin a11 ON (MT.LIDENT = A11.ID_SSSLOGIN)
LEFT OUTER JOIN ssslogin a12 ON (MT.LIDENT_ZMENA = A12.ID_SSSLOGIN)
LEFT OUTER JOIN obpvrevlok a8 ON (A9.ID_OBPVREVLOK = A8.ID_OBPVREVLOK)
WHERE ((A10.TYP = 'S') OR (A10.TYP IS NULL ));
</pre>

Now, the relation between a9 and a10 is lost - but the query is syntax valid (from syntax perspective :().) In this case, better to alert error, if is not possible to do correct translation.

Expected:
<pre>

CREATE OR REPLACE VIEW v_obprevize_chyba (id_obprevize) AS SELECT MT.ID_OBPREVIZE
          FROM  obprevize mt
LEFT OUTER JOIN cisdrurev a1 ON (MT.ID_CISDRUREV = A1.ID_CISDRUREV)

LEFT OUTER JOIN udrsprvc a2 ON (MT.ID_ASPRAVCE = A2.ID_ASPRAVCE)
LEFT OUTER JOIN cleosoby a4 ON (MT.ID_CCLE_ODB = A4.ID_CCLE)
LEFT OUTER JOIN obprevize a5 ON (MT.ID_OBPREVIZE_A = A5.ID_OBPREVIZE_A)
LEFT OUTER JOIN udrprovo a6 ON (MT.ID_APROVOZNA = A6.ID_APROVOZNA)
LEFT OUTER JOIN cleosoby a7 ON (MT.ID_CCLE = A7.ID_CCLE)
LEFT OUTER JOIN v_maxlokrevize a9 ON (MT.ID_OBPREVIZE = A9.ID_OBPREVIZE)
LEFT OUTER JOIN ssslogin a11 ON (MT.LIDENT = A11.ID_SSSLOGIN)
LEFT OUTER JOIN ssslogin a12 ON (MT.LIDENT_ZMENA = A12.ID_SSSLOGIN)
LEFT OUTER JOIN obpvrevlok a8 ON (A9.ID_OBPVREVLOK = A8.ID_OBPVREVLOK)
LEFT JOIN ssshledej_a a10 ON ( a9.ID_SEGMENT = A10.ID_SEGMENT )
WHERE ((A10.TYP = 'S') OR (A10.TYP IS NULL ));
</pre>

**Comment by darold** [comment]
It seems very difficult to fix, I will study this problem some more time to try to find a solution.

**Comment by darold** [comment]
Commit 602261f might fix this issue, at least the join `a10 ON ( a9.ID_SEGMENT = A10.ID_SEGMENT )` is now present as a left outer join.
