### ISSUE TITLE
Unwanted assignment in views (and broken assignment elsewhere)

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#383]
We have a function:
<pre>
CREATE OR REPLACE function IDES_JMMAJ.FUPRAV_ZA_OBDOBI
( mZA_OBDOBI IN VARCHAR2) return varchar2 is
</pre>
and procedure:
<pre>
CREATE OR REPLACE procedure IDES_JMMAJ.UPRAV_ZA_OBDOBI
( mZA_OBDOBI IN VARCHAR2 , mZA_OBDOBI_NEW OUT VARCHAR2) is
</pre>
The function call in view is badly replaced:

Oracle:
<pre>
SELECT FUPRAV_ZA_OBDOBI(A9.ZA_OBDOBI)) AS ZA_OBDOBI FROM ...
</pre>

Ora2pg:
<pre>
SELECT  F := UPRAV_ZA_OBDOBI(A9.ZA_OBDOBI)) AS ZA_OBDOBI FROM ...
</pre>

Expected:
<pre>
SELECT FUPRAV_ZA_OBDOBI(A9.ZA_OBDOBI)) AS ZA_OBDOBI FROM ...
</pre>

**Comment by darold** [comment]
Last commit fa9c827 limits rewrite of function with OUT parameters to PACKAGE, FUNCTION, PROCEDURE and TRIGGER export type, so view may no more suffer of this bug.

**Comment by okbob** [comment]
I found same issue in function:
Oracle:
<pre>
CREATE OR REPLACE function IDES_JMMAJ.GET_ZAKLAD_DPH_CASTKA( mID_POL_PRED IN NAJPOLOZ.ID_POL_PRED%TYPE , mKOD_CNAJVYPPOL IN CNAJVYPPOL.KOD_CNAJVYPPOL%TYPE,mDPH_PROC NAJPOLOZ.DPH_PROC%TYPE ,mDPH_ZAOK IN CISUJEDN.ZAKRDPH%TYPE , mCELKEM_ZAOK IN CHAR , mCASTKA_VSTUP IN NAJPOLOZ.DPH_ZAKLAD%TYPE  ,  mTYP_CASTKA IN CHAR  ,
                                                  mKOD_CTYPPRED IN  CTYPPRED.KOD_CTYPPRED%TYPE , mZIV IN CHAR ) return NUMBER is
  Result NUMBER ;
  mDPH_ZAKLAD NUMBER;
  mCASTKA_BEZZAOK NUMBER;
begin

  IF ( mZIV = '0' ) AND ( trim(mKOD_CTYPPRED) <> 'S' ) THEN

    IF TRIM(mKOD_CNAJVYPPOL) IN ( 'A' , 'C' , 'D' , 'G' , 'S' , 'F' ,'K','H' ) THEN
      SELECT SUM(EPOL_CASTKA) INTO Result
        FROM NAJPODPOL
        WHERE ID_POL_PRED = mID_POL_PRED;
        --- REN ZMENA 19.12.2012 ABY SE NEPREZENTOVALY 3 DESETINNA MISTA
        Result := ROUND(Result,2);
        mDPH_ZAKLAD := Result;
        IF TRIM(mKOD_CNAJVYPPOL) IN ( 'A' , 'C' ) THEN
          mDPH_ZAKLAD := TRUNC( mDPH_ZAKLAD , 0 );
        END IF;
      IF (( mTYP_CASTKA = 'DPH' ) OR ( mTYP_CASTKA = 'CASTKA' ) OR ( mTYP_CASTKA = 'HALVYRO' ))  THEN
        Result := mDPH_ZAKLAD * ( mDPH_PROC/100 );
        Result := F_ZAOKR_OREZ_DPH( Result , mDPH_ZAOK );
      END IF;
      IF (( mTYP_CASTKA = 'CASTKA' ) OR ( mTYP_CASTKA = 'HALVYRO' )) THEN
        Result := mDPH_ZAKLAD + Result;
        mCASTKA_BEZZAOK := Result;
        IF ( mCELKEM_ZAOK IS NOT NULL ) AND ( mCELKEM_ZAOK <> 'N' )  THEN
          Result := F_ZAOKR_OREZ_ROZSIRENE( Result , mCELKEM_ZAOK );
        ELSE
          IF TRIM(mKOD_CNAJVYPPOL) IN ( 'A','F','D','G','K','H' ) THEN
            Result := TRUNC( Result , 0 );
          END IF;
        END IF;
      END IF;
      IF ( mTYP_CASTKA = 'HALVYRO' ) THEN
        --raise_application_error( -20010, Result || '- ' || mCASTKA_BEZZAOK );
        Result := Result - mCASTKA_BEZZAOK;
      END IF;
    ELSE
      --- REN PRIDANO ZAOKROUHLENI NA 2 DESETINNA MISTA
      Result := ROUND(mCASTKA_VSTUP,2);
    END IF;
  ELSE
    Result := mCASTKA_VSTUP;
  END IF;

  return(Result);

end GET_ZAKLAD_DPH_CASTKA ;
</pre>

PostgreSQL:
<pre>
CREATE OR REPLACE FUNCTION get_zaklad_dph_castka ( mID_POL_PRED NAJPOLOZ.ID_POL_PRED%TYPE , mKOD_CNAJVYPPOL CNAJVYPPOL.KOD_CNAJVYPPOL%TYPE,mDPH_PROC NAJPOLOZ.DPH_PROC%TYPE ,mDPH_ZAOK CISUJEDN.ZAKRDPH%TYPE , mCELKEM_ZAOK CHAR , mCASTKA_VSTUP NAJPOLOZ.DPH_ZAKLAD%TYPE , mTYP_CASTKA CHAR , mKOD_CTYPPRED CTYPPRED.KOD_CTYPPRED%TYPE , mZIV CHAR ) RETURNS numeric AS $body$
DECLARE

  Result numeric;
  mDPH_ZAKLAD numeric;
  mCASTKA_BEZZAOK numeric;

BEGIN

  IF ( mZIV = '0' ) AND ( btrim(mKOD_CTYPPRED) <> 'S' ) THEN

    IF btrim(mKOD_CNAJVYPPOL) IN ( 'A' , 'C' , 'D' , 'G' , 'S' , 'F' ,'K','H' ) THEN
      SELECT SUM(EPOL_CASTKA) INTO Result
        FROM NAJPODPOL
        WHERE ID_POL_PRED = mID_POL_PRED;
        --- REN ZMENA 19.12.2012 ABY SE NEPREZENTOVALY 3 DESETINNA MISTA
        Result := round((Result)::numeric,2);
        mDPH_ZAKLAD := Result;
        IF btrim(mKOD_CNAJVYPPOL) IN ( 'A' , 'C' ) THEN
          mDPH_ZAKLAD := TRUNC( mDPH_ZAKLAD , 0 );
        END IF;
      IF (( mTYP_CASTKA = 'DPH' ) OR ( mTYP_CASTKA = 'CASTKA' ) OR ( mTYP_CASTKA = 'HALVYRO' ))  THEN
        Result := mDPH_ZAKLAD * ( mDPH_PROC/100 );
        Result := F_ Result := ZAOKR_OREZ_DPH( Result, mDPH_ZAOK );
      END IF;
      IF (( mTYP_CASTKA = 'CASTKA' ) OR ( mTYP_CASTKA = 'HALVYRO' )) THEN
        Result := mDPH_ZAKLAD + Result;
        mCASTKA_BEZZAOK := Result;
        IF ( mCELKEM_ZAOK IS NOT NULL ) AND ( mCELKEM_ZAOK <> 'N' )  THEN
          Result := F_ Result := ZAOKR_OREZ_ROZSIRENE( Result, mCELKEM_ZAOK );
        ELSE
          IF btrim(mKOD_CNAJVYPPOL) IN ( 'A','F','D','G','K','H' ) THEN
            Result := TRUNC( Result , 0 );
          END IF;
        END IF;
      END IF;
      IF ( mTYP_CASTKA = 'HALVYRO' ) THEN
        --raise_application_error( -20010, Result || '- ' || mCASTKA_BEZZAOK );
        Result := Result - mCASTKA_BEZZAOK;
      END IF;
    ELSE
      --- REN PRIDANO ZAOKROUHLENI NA 2 DESETINNA MISTA
      Result := round((mCASTKA_VSTUP)::numeric,2);
    END IF;
  ELSE
    Result := mCASTKA_VSTUP;
  END IF;

  return(Result);

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
</pre>

The problematic line is:
<pre>
Result := F_ Result := ZAOKR_OREZ_DPH( Result, mDPH_ZAOK );
</pre>

We have function on Oracle:
<pre>
CREATE OR REPLACE function IDES_JMMAJ.F_ZAOKR_OREZ_DPH (mEpol_Castka  IN  NAJPOLOZ.EPOL_CASTKA%TYPE , mTYP IN CHAR  ) return NUMBER is
</pre>

and procedure:
<pre>
CREATE OR REPLACE procedure IDES_JMMAJ.ZAOKR_OREZ_DPH
   ( mEpol_Castka  IN OUT NAJPOLOZ.EPOL_CASTKA%TYPE , mTYP IN CHAR  ) is
   mHalere NUMBER;
</pre>

It is customer crap code again - but this model can be used often (some times out of plan) 
<pre>
  name(xxx) .. procedure
  f_name(xxx) .. function
</pre>

**Comment by darold** [comment]
Got it. Commit 4f13fac might solve these two issue (double assignment and name of function part of an other one).

**Comment by okbob** [comment]
It is fixed, Thank you
