### ISSUE TITLE
to_number is translated as `::integer`, should be `::numeric`

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#384]
The function `to_number(xx)` is translated like `xx::integer`. This transformation is not correct, because Oracle by default doesn't do round or trunc https://www.techonthenet.com/oracle/functions/to_number.php

This transformation can be smarter if mask is defined.

**Comment by edelanoe** [comment]
Hello all,

I have the same issue, especially with a format mask. 
Here is a sample function which is quite classical:
-- ORACLE:
-- CST.MONEY_NUMBER_FORMAT() is a constant function ==> '99999999999999999999.9999999999';
FUNCTION TO_MONEY  (v_STR VARCHAR2) RETURN NUMBER IS
BEGIN
   RETURN TO_NUMBER(SUBSTR(v_STR,1,20) || '.' ||  SUBSTR(v_STR,21,10), CST.MONEY_NUMBER_FORMAT);
END;
--
-- Translated/ora2pg:
CREATE OR REPLACE FUNCTION pck_msg.to_money (v_STR text) RETURNS bigint AS $body$
BEGIN
   RETURN (SUBSTR(v_STR,1,20) || '.' ||  SUBSTR(v_STR,21,10), CST.MONEY_NUMBER_FORMAT)::integer;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;

Best Rgds,
Eric

**Comment by darold** [comment]
Right, commit 8b8ae6c translate with a numeric cast.

**Comment by okbob** [comment]
It is much better.
Is possible to disable this transformation? Postgres has native to_number function, that has better behave, when numbers uses ',' instead '.'. On second hand it is slower than direct cast to numeric.

**Comment by darold** [comment]
The original behavior of Ora2Pg was to replace all to_number() Oracle call with the following:

     to_number($1,'99999999999999999999D99999999999999999999')

Do you think it can handle all cases.

**Comment by okbob** [comment]
This is very realistic emulation. There are three variants.
1. Without transformation (can be covered by Orafce) .. slower, tolerant to locale symbols
2. cast to numeric .. fast and strict
3. to_number($1,'99999999999999999999D99999999999999999999') .. slower, require locale symbol

Any variant has own advantage and disadvantage. Can you have enum in configuration?
* no transformation
* cast to numeric
* using implicit masc

**Comment by darold** [comment]
Ok, I will add new TO_NUMBER_BEHAVIOR configuration directive with 3 possible values (none, cast, locale) with your explanation above.

**Comment by edelanoe** [comment]
May I add a request?
In the mask option, could the mask be explicit?  (a format string)
This would make the mask option very interesting, because each application may have its own convention. Of course, the default format string in sample .conf can be your format suggestion.

**Comment by darold** [comment]
Ok, instead of locale we will allow to directly give a format string this will be much more useful and this is the only part that change in the mask behavior.

**Comment by darold** [comment]
Commit e505c61 add new TO_NUMBER_CONVERSION configuration directive to control TO_NUMBER
translation behavior. By default Oracle call to function TO_NUMBER will be translated as a cast into numeric. For example, `TO_NUMBER('10.1234')` is converted into PostgreSQL call: `to_number('10.1234')::numeric`. If you want you can cast the call to integer or bigint by changing the value of the configuration directive. If you need better control of the format, just set it as value, for example:
       TO_NUMBER_CONVERSION    99999999999999999999D9999999999
will convert the code above as:
      TO_NUMBER('10.1234', '99999999999999999999D9999999999')
Any value of the directive that it is not numeric, integer or bigint will be taken as a mask format. If set to none, no conversion will be done.

**Comment by okbob** [comment]
I tested a variant with none and it works as expected, Thank you
