### ISSUE TITLE
view conversion error: varchar2s

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#385]
VARCHAR2s are not being converted to VARCHAR or CHARACTER VARYING:

```
CREATE OR REPLACE VIEW claim_line (linseq, linno,...) AS SELECT
    h.LINSEQ,
    h.LINNO,
   ...
   CAST (TOOTHNO AS VARCHAR2 (2)) ADJ_TOOTH_NUMBER_1,
   CAST ('' AS VARCHAR2 (2)) TOOTH_NUMBER_2,
   ...
```

**Comment by darold** [comment]
Commit c43a57d fixes this is issue, this bug of missing translation of Oracle type was also found in function  rewriter.

**Comment by MichaelDBA** [comment]
great thanks!  When will the next version be coming out?  Im using 18.1 now.

**Comment by darold** [comment]
You have to use the development code now, I have dropped the idea to get out a v18.2 maintenance release, there is too many major changes. I have no idea when version 19 will get out but not until I fix all current reported issues and pull requests, unfortunately I have sold out all my holidays so it could takes some more weeks.

**Comment by MichaelDBA** [comment]
OK, darold, keep up the good work!
