### ISSUE TITLE
Wrong translation of %ROWTYPE in a package function header (conflict table/function)

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#387]
We have a table A_MSG_HEADER
We have a package PCK_MSG with these 2 functions: header() and dispatch()
Ok, that's unfortunate...
In the function header of pck_msg.dispatch, we declare:
          v_header    A_MSG_HEADER%ROWTYPE;
It is translated
         v_header    A_MSG_pck_msg.header;
Could ora2pg distinguish if it is in a header, and/or priorize the %ROWTYPE on TABLES before functions?
Note that Oracle does not have %ROWTYPE for functions.

Best Rgds,
Eric

**Comment by darold** [comment]
I think commit 04f1682 can solve this issue too, can you give it a try and let me know.

**Comment by edelanoe** [comment]
Yes, this is fixed, thank you
