### ISSUE TITLE
PostgreSQL doesn't support function name label for `END` keyword

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#392]
Oracle supports function name label near `END` keyword
<pre>
CREATE OR REPLACE procedure IDES_JMMAJ.OREZ_PO_ZNAK(mTextVstup IN VARCHAR2 , mTextVystup OUT VARCHAR2  , mZnak IN CHAR  , mZacit IN NUMBER )
is
  i  NUMBER;
begin
  mTextVystup := '' ;
  FOR i in 1..LENGTHB( mTextVstup ) LOOP
    IF  mZacit <= i THEN
      IF mZnak = SUBSTR( mTextVstup , i , 1 ) THEN
        EXIT ;
      END IF ;
    END IF ;
    mTextVystup :=  mTextVystup || SUBSTR( mTextVstup , i , 1 ) ;
  END LOOP ;

end OREZ_PO_ZNAK; ----- <<<<<
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE FUNCTION ides_procs.orez_po_znak(mtextvstup text, OUT mtextvystup text, mznak character, mzacit numeric)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE

  i  numeric;

BEGIN
  mTextVystup := '';
  FOR i in 1..LENGTHB( mTextVstup ) LOOP
    IF  mZacit <= i THEN
      IF mZnak = SUBSTR( mTextVstup , i , 1 ) THEN
        EXIT;
      END IF;
    END IF;
    mTextVystup :=  mTextVystup || SUBSTR( mTextVstup , i , 1 );
  END LOOP;

end OREZ_PO_ZNAK;
$function$
</pre>
PostgreSQL include outer implicit block, so last explicit `END` is not related to function. 

This example fail on Postgres:
<pre>
ides_jmmaj=# create or replace function fx() returns int as $$ begin return 10; end fx; $$ language plpgsql;
ERROR:  end label "fx" specified for unlabelled block
ŘÁDKA 1: ...ction fx() returns int as $$ begin return 10; end fx; $$ lan...
                                                              ^
</pre>

On second hand PostgreSQL allows ending labels when block was explicitly labeled:
<pre>
ides_jmmaj=# create or replace function fx() returns int as $$&lt;&lt;fxx&gt;&gt; begin return 10; end fxx; $$ language plpgsql;
CREATE FUNCTION
</pre>

**Comment by okbob** [comment]
Now, I am looking so Ora2pg implicitly removes ending labels what is probably the best option. So in this function from some reason the ending label was not removed.

**Comment by darold** [comment]
Commit 90397b8 might fix this issue.

**Comment by okbob** [comment]
Unfortunately - no change.
