### ISSUE TITLE
How to handle Oracle Global tables?

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#395]
Is there something in ora2pg to handle Oracle global tables?

**Comment by okbob** [comment]
what do you mean "global tables" ?

**Comment by darold** [comment]
Same question, what do you call "global tables" ?

**Comment by MichaelDBA** [comment]
sorry, global temporary tables.  And I know the reason why you probably don't export them because there is no straightforward way to mimic them in pg.  Not a showstopper here, just curious.

**Comment by okbob** [comment]
I think so it is out of ora2pg scope - minimally in this moment, when PostgreSQL has not adequate structure. I read few interesting articles about this topic: https://github.com/yallie/pg_global_temp_tables https://www.codeproject.com/Articles/1176045/Oracle-style-global-temporary-tables-for-PostgreSQ
