### ISSUE TITLE
View migration very slow

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#396]
Hello,

The VIEW migration type looks very slow because it first scans all the packages ("Looking at package ...").
Why is it parsing all packages ?
Could we skip that when translating views ?

Rgds,
Eric

**Comment by darold** [comment]
Commit 3a378d7 might improve speed of VIEW export.

**Comment by edelanoe** [comment]
Issue fixed, while view export itself is still a bit slow (lot of output?).
