### ISSUE TITLE
Regression in package function calls

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#398]
When a package function calls another, the package schema prefix has been lost:
Output with 2017-04-14 (morning) master code:
v_ERROR_CODE := pck_cpt.local_log_error(SQLSTATE, SQLERRM);

Output with 2017-05-05 (morning) master code:
v_ERROR_CODE := .local_log_error(SQLSTATE, SQLERRM);

Best Rgds.

**Comment by edelanoe** [comment]
In the same time, other function calls have surprisingly changed:
Output with 2017-04-14 (morning) master code:
            PERFORM pck_gcl.debug_trace(C_PROCEDURE_NAME||C_ARGS);
Output with 2017-05-05 (morning) master code:
            DEBUG_TR.ace(C_PROCEDURE_NAME||C_ARGS);

**Comment by darold** [comment]
Ok, I see it will be fixed asap.

**Comment by edelanoe** [comment]
Other indication (other surprising change): in a cross-package call:
PCK_BILLING.GET_VAT_RATE(p_vat_id, p_date_begin)
became:
PCK_BILLING.GET_.vat_rate(p_vat_id, p_date_begin)

**Comment by darold** [comment]
Commit 3a378d7 improving speed of VIEW export also contain a fix on function call replacement. Please give it a try and let me know.

**Comment by darold** [comment]
Sorry found an other issue in package function name extraction, commit f002db3 might solve the issue.

**Comment by darold** [comment]
Last commit 38f5d91 might solves this issue, the problem was that function parameters was doubled with the PACKAGE and PACKAGE BODY definition when extracting sources.

**Comment by edelanoe** [comment]
Ok with master downloaded 2017/05/09 09:30.
