### ISSUE TITLE
PG_SCHEMA doesn't seem to work properly

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#400]
If I have this in my ora2pg con file, 
`PG_SCHEMA zuric, public, pg_catalog`

I get this in output sql files:
`SET search_path = "zuric, public, pg_catalog"`

And this will not work with the double quotes, but I do this, it will work:
`SET search_path = zuric, public, pg_catalog`

**Comment by SebAlbert** [comment]
Actually, there's no way for ora2pg to tell which of the two you actually want (although schema names with commas and spaces may be rare, they are perfectly legal).
Is it necessary to specify more than one schema in the `search_path`? The first schema is obviously the most important, since new objects (tables etc.) will be created there. Couldn't all other things be referenced in a schema-qualified manner when needed?

**Comment by MichaelDBA** [comment]
it is not unusual to have "public" and "pg_catalog" in a search path in addition to the primary schema you are working with.  If fact, ora2pg does this already for "pg_catalog" by appending that to the schema ora2pg is working with.   I just want ora2pg fixed so it doesn't put double-quotes around the search_path arguments which is syntactically incorrect for postgres.

**Comment by SebAlbert** [comment]
It's not syntactically incorrect, it's just meaning something different. I think the PG_SCHEMA config parameter in ora2pg was meant to denote the one single schema that you want your objects to be created in, and that's what ora2pg is making of it by placing the double quotes around it. Somebody could fully legally `CREATE SCHEMA "zuric, public, pg_catalog"` in their Postgres database as one single schema (with a somewhat weird name), and if they want ora2pg to put their objects in this weirdly-named schema, then they would write `PG_SCHEMA zuric, public, pg_catalog` in the configuration.

Maybe it's possible to accomplish this weirdly-named schema use case by `PG_SCHEMA "zuric, public, pg_catalog"`, but that's a potentially breaking change for existing configurations.

**Comment by darold** [comment]
Commit f824b9a fixes quoting of PG_SCHEMA with multiple schema in search path. The definition of the search path now follow the following behavior:

    - when PG_SCHEMA is define, always set search_path to its value.
    - when EXPORT_SCHEMA is enabled and SCHEMA is set, the search_path is set the name of the schema. 

This could change the behavior of some previous use of these variables and the resulting value of the search_path but it seems much better understandable.

Let me know if that's break too much the old behavior.

**Comment by darold** [comment]
I've also removed pg_catalog from the search path, I don't think it is necessary any more.

**Comment by MichaelDBA** [comment]
rats, i liked pg_catalog in the search path, but it makes sense to make this simple and leave out any implications like pg_catalog being implicitly added.

Thanks, Darold!
