### ISSUE TITLE
REPLACE_COLS in CONSTRAINTS

### ISSUE THREAD

**Issue by BernardBielecki** [darold/ora2pg#401]
Hello. 
I've column name 'do' in some table. I define REPLACE_COLS table[do:do_], and ora2pg replace that column, but not replace in UNIQUE constraint definition.

**Comment by darold** [comment]
Thanks for the report, last commit 124ac4c might solve the issue.

**Comment by BernardBielecki** [comment]
Solved, thanks very much.
