### ISSUE TITLE
data question

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#402]
How do I pull out data for one table?  I see exclude list but not include list.  I also see where clauses for a table but not how to specify everything in that table.  Should I do something like:

`WHERE  mytable[1=1]`

**Comment by SebAlbert** [comment]
Set `TYPE INSERT` or `TYPE COPY` to get data (or use the -t switch on the commandline accordingly).
By default, no filtering is applied, so you do not need to apply `WHERE 1=1` (although you can, of course).
The tables/views where data is to be extracted from are defined by the `ALLOW` configuration or -a switch on the command line.

**Comment by MichaelDBA** [comment]
Gotcha, now what about the sequences file generated.  Do I run the sequences after I load the data or before?

**Comment by MichaelDBA** [comment]
WHooops, answered my own question, it invokes the other file.  THanks!

**Comment by SebAlbert** [comment]
Another option is to set `DISABLE_SEQUENCES 1` in the data export configuration, if the sequences have already been migrated and set to the correct values before the data migration.
