### ISSUE TITLE
Migrate to quote_object_name in MySQL

### ISSUE THREAD

**Issue by SebAlbert** [darold/ora2pg#403]
dffe6e82fa9012b1dc66e41a4c6d48a526b480e4 replaced `quote_reserved_words` by `quote_object_name`, but the MySQL module still tries to call the former on line 362: https://github.com/darold/ora2pg/blob/master/lib/Ora2Pg/MySQL.pm#L362
which obviously fails ungracefully:

> Can't locate object method "quote_reserved_words" via package "Ora2Pg" at /usr/local/share/perl5/Ora2Pg/MySQL.pm line 362.

**Comment by darold** [comment]
Commit 61d5568 fixes this issue. Note that there must be some other issue with mysql migration, I've not tested it since last release and there is lot of changes.

**Comment by SebAlbert** [comment]
Thanks, I will report more issues as I encounter them. For the moment, the MySQL seems to work with this fix (at least on my fork, which is behind and thus probably does not incorporate other critical refactorings yet).
