### ISSUE TITLE
timstamp with time zone?

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#404]
How do you make ora2pg use timestamp with time zone instead of without it?

**Comment by darold** [comment]
By default:

  * DATE is translated in timestamp
  * TIMESTAMP is translated in timestamp
  * TIMESTAMP WITH TIME ZONE is translated in timestamp with time zone
  * TIMESTAMP WITH LOCAL TIME ZONE  is translated in timestamp with time zone

By default PostgreSQL use 'timestamp without time zone' when 'timestamp' only is used.

**Comment by SebAlbert** [comment]
@MichaelDBA Have a closer look at the `DATA_TYPE` configuration opportunity (and maybe a short glimpse on the others, too).

**Comment by MichaelDBA** [comment]
Thanks!!!!!!!
