### ISSUE TITLE
broken variable declaration - probably due name "mDEFAULT"

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#405]
Oracle:
<pre>
CREATE OR REPLACE procedure IDES_JMMAJ.COPY_RECORD_VZOR
( mID_VZOR IN NUMBER , 
  mNaz_pol IN VARCHAR2 , 
  mTable_Name IN VARCHAR2 , 
  mID_NADR_UROVNE IN NUMBER  , 
  mNazev_NADR_UROVNE  IN VARCHAR2 , 
  mNewId_PK OUT NUMBER ,
  mPlatnost_od IN DATE , 
  mLIdent IN NUMBER  ) 
  is
mSql VARCHAR2(4000);
mSqlIns VARCHAR2(4000);
mSqlInsVal VARCHAR2(4000);
mSqlInsPOM VARCHAR2(4000);
mDefault boolean;  
mPrvni boolean ;
mPlatnost_od_pom DATE; 
mChyba boolean;
mChybaText VARCHAR2(4000);

begin

  mSql := ' ';
  mSqlIns := ' INSERT INTO ' || mTable_Name || ' (  '  ;
  mSqlInsVal := ' SELECT  ' ;
        
  mPrvni := True;

  FOR qSLOUPCE IN 
    ( SELECT COLUMN_NAME   
        FROM USER_TAB_COLUMNS MT 
        WHERE TABLE_NAME = mTable_Name and COLUMN_NAME <> 'DATVYR' ORDER BY COLUMN_ID )
  LOOP

    mDefault := true;  
    IF mPrvni = false THEN
      mSqlIns := mSqlIns || ' , ';
      mSqlInsVal := mSqlInsVal || ' , ';
    END IF;

    mSqlIns :=  mSqlIns || qSLOUPCE.COLUMN_NAME;

    IF mNaz_pol = qSLOUPCE.COLUMN_NAME THEN
      mDefault := false;  
      SELECT SEAPP.NEXTVAL  INTO mNewId_PK
        FROM DUAL; 
      mSqlInsVal :=  mSqlInsVal || mNewId_PK;
        
    END IF;
    IF 'PLATNOST_OD' = qSLOUPCE.COLUMN_NAME THEN
      mDefault := false;  
      IF mPlatnost_od IS NOT NULL THEN
        mPlatnost_od_pom := mPlatnost_od;
      ELSE
        mPlatnost_od_pom := TO_DATE( SYSDATE , 'DD.MM.YYYY' );
      END IF;
      mSqlInsVal :=  mSqlInsVal || '''' || mPlatnost_od_pom || '''' ;

    END IF;

    IF 'LIDENT' =  qSLOUPCE.COLUMN_NAME THEN 
      IF mLIdent IS NOT NULL THEN
        mDefault := false;  
        mSqlInsVal :=  mSqlInsVal || mLIdent ;
      END IF;
    END IF;
    
    IF 'CVZNIKRADK' =  qSLOUPCE.COLUMN_NAME THEN 
        mDefault := false;  
        IF mNaz_pol = 'ID_CISUUCET' THEN
          mSqlInsVal :=  mSqlInsVal || '''C'''  ;
        ELSE
          mSqlInsVal :=  mSqlInsVal || 'NULL'  ;
        END IF;  

    END IF;

    IF (( mTable_Name = 'CISUUCET' ) AND (  qSLOUPCE.COLUMN_NAME = 'ID_CISUSYNT' )) THEN
       mSqlInsVal :=  mSqlInsVal || 'NULL'  ;
       mDefault := false;  
    END IF;         

    --- REN PRIDANO 25.02.2016 JINAK SE VZTVAREJI PLOCHZ 
    IF (( mTable_Name = 'OBPMISTN' ) AND (  qSLOUPCE.COLUMN_NAME = 'PLOCHA_CEL' )) THEN
       mSqlInsVal :=  mSqlInsVal || 'NULL'  ;
       mDefault := false;  
    END IF;         

    
    IF mNazev_NADR_UROVNE = qSLOUPCE.COLUMN_NAME THEN
      IF mID_NADR_UROVNE IS NOT NULL THEN
        mDefault := false;  
        mSqlInsVal :=  mSqlInsVal || mID_NADR_UROVNE;
      END IF ;  
    END IF;

 
    IF mDefault = True THEN
      mSqlInsVal :=  mSqlInsVal || qSLOUPCE.COLUMN_NAME ;
    END IF;
    
    mPrvni := false;

  END LOOP;
  mSqlIns := mSqlIns || ' ) ';
  mSqlInsVal := mSqlInsVal || ' FROM ' || mTable_Name || '  WHERE  ' || mNaz_pol || ' = ' || mID_VZOR ;
  
  ---mSqlIns := mSqlIns || mSqlInsVal;
  --mSqlInsPOM := mSqlIns || mSqlInsVal;
  -- raise_application_error( -20010 , length(mSqlIns) || '--- ' || length(mSqlInsVal) );
  BEGIN

    ---EXECUTE IMMEDIATE mSqlInsPOM  ;
    EXECUTE IMMEDIATE mSqlIns || mSqlInsVal;

  EXCEPTION
    WHEN OTHERS THEN
      mChyba := true;
      mChybaText := SQLERRM;
       INSERT INTO RRRNAJUZA_ERR ( AKCE , TEXT , CHYBA )
            VALUES ( 'COPY_RECORD_VZOR' , mNaz_pol , mChybaText );
       IF mTable_Name = 'VYTOPDEN' THEN
          raise_application_error(-20015 , mChybaText );
       END IF;       

      ---raise_application_error(-20020, 'rrrrrrrrrrrrr' );  

  END;
  --mSqlIns := mSqlIns ;
  
  
end ;
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE FUNCTION copy_record_vzor ( mID_VZOR numeric , mNaz_pol text , mTable_Name text , mID_NADR_UROVNE numeric , mNazev_NADR_UROVNE text , mNewId_PK OUT numeric , mPlatnost_od date , mLIdent numeric ) AS $body$
DECLARE

mSql varchar(4000);
mSqlIns varchar(4000);
mSqlInsVal varchar(4000);
mSqlInsPOM varchar(4000);
m:= boolean; ---- <<<<<<<<<<<<<
mPrvni boolean;
mPlatnost_od_pom date;
mChyba boolean;
mChybaText varchar(4000);

  qSLOUPCE RECORD;

BEGIN

  mSql := ' ';
  mSqlIns := ' INSERT INTO ' || mTable_Name || ' (  ';
  mSqlInsVal := ' SELECT  ';

  mPrvni := True;
  ...
</pre>

**Comment by darold** [comment]
Commit e313f39 solves this issue.

**Comment by okbob** [comment]
It is fixed. Thank you
