### ISSUE TITLE
untranslated procedure call

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#406]
Oracle: attachment - vypocet_penale_new.txt
The call of `VYPOCET_PENALE_PLATBA_NEW` procedure untranslated.
<pre>
CREATE OR REPLACE procedure IDES_JMMAJ.VYPOCET_PENALE_PLATBA_NEW(  mID_najdatsplt IN NAJDATSPLT.ID_NAJDATSPLT%TYPE  ,
       mID_CNAJPEN IN CNAJPEN.ID_CNAJPEN%TYPE , mKod_cnajpen IN CNAJPEN.KOD_CNAJPEN%TYPE ,
      mID_APROVOZNA UDRPROVO.ID_PROVOZNA%TYPE ,mID_ASPRAVCE UDRSPRVC.ID_ASPRAVCE%TYPE , mkDatu IN DATE , mPenaleCelkem OUT NUMBER ,
      mRozpis IN CHAR , mID_NAJUPOMCEL NAJUPOMCEL.ID_NAJUPOMCEL%TYPE ,
      mPenale_Od IN DATE , mPenale_do IN DATE , mPenalCastka IN NUMBER ,
      mDatumsplat IN NAJDATSPLT.DATUM_SPLATNOSTI%TYPE ,
      mID_najvplapre IN NAJVPLAPRE.ID_NAJVPLAPRE%TYPE,
      mDatm_zaplaceni NAJPLATBY.DATUM_ZAPLACENI%TYPE ,
      mObdobi_Od_SPLT IN DATE , mObdobi_do_SPLT IN DATE,
      mMINIMUM OUT CNAJPEN.MINIMUM%TYPE , mPOCDEN   OUT CNAJPEN.POCDEN%TYPE , mBANDEN OUT  CNAJPEN.BANDEN%TYPE ,
      mPROCENTO OUT NAJPENDET.PROC%TYPE , mNasobek OUT NAJPENDET.NASOBEK%TYPE,
      mID_NAJUPOMPRE NAJUPOMPRE.ID_NAJUPOMPRE%TYPE , mDatumPosZapis IN DATE ,
      mDnyPenale OUT NUMBER ,
      mZA_OBDOBI IN NAJDATSPLT.ZA_OBDOBI%TYPE ,mRok IN NAJDATSPLT.ROK%TYPE , mMesic IN NAJDATSPLT.MESIC%TYPE , mLIDENT IN NUMBER ,
      mTextNazev IN VARCHAR2 , mKod IN VARCHAR2 , mPEN_SLEVA IN NAJUPOMCEL.PEN_SLEVA%TYPE,
      mPENALE_ZAKON IN CHAR , mRokZakon IN NUMBER ,mNEPOCITAT IN CHAR , mPocetZalob IN NUMBER ,
      mPozn VARCHAR2, mID_SKUPINA_VYP IN NAJPENDET.ID_SKUPINA_VYP%TYPE
 ) is
</pre>

Ora2pg:
<pre>
        IF (( btrim(mKOD_METODA) IN ('POPLATEK','P67') ) AND ( qNajpendet.DATUM >= TO_DATE('01.08.1994' , 'DD.MM.YYYY')  )) THEN
            
          IF mPenale_Od < mDATUM_PLATBA_MINULA  THEN

            VYPOCET_PENALE_PLATBA_NEW(  mID_najdatsplt , mID_CNAJPEN , mKod_cnajpen ,
                 mID_APROVOZNA ,mID_ASPRAVCE  , mkDatu ,  mPenale_pom_platba  ,
                 mRozpis , mID_NAJUPOMCEL , (mDATUM_PLATBA_MINULA - 1) , mPenale_Do , qNajpendet.CASTKA ,
                 mDatumsplat , null , qNajpendet.DATUM ,
                 mOBDOBI_OD_NAJDATSPLT , mOBDOBI_DO_NAJDATSPLT , mMINIMUM , mPOCDEN , mBANDEN ,
                 mPROCENTO , mNasobek  , mID_NAJUPOMPRE , mDatumPosZapis , mDnyPenale_pom_platba ,
                 mZA_OBDOBI ,mRok , mMesic , mLIDENT , qNajpendet.NAZEV  , qNajpendet.KOD , mPEN_SLEVA,
                 mPENALE_ZAKON, mRokZakon,mNEPOCITAT,mPocetZalob , mPozn ,mID_SKUPINA_VYP);
          ELSE                                     
            mPenale_pom_platba := mPenaleCelkem;
            mDnyPenale_pom_platba := mDnyPenale;
          END IF;
        END IF;
                      
</pre>

Sometimes in this function this called procedure was called correctly.
[vypocet_penale_new.txt](https://github.com/darold/ora2pg/files/986450/vypocet_penale_new.txt)

**Comment by darold** [comment]
Might be fixed by commit 6cc3e16.

**Comment by okbob** [comment]
It is fixed, thank you
