### ISSUE TITLE
too much semicolons on end of function

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#407]
Oracle:
<pre>
CREATE OR REPLACE procedure IDES_JMMAJ.DEL_VYROK
  (  mWhere IN VARCHAR2 , mTransakce IN CHAR , 
     mLIDENT IN NUMBER  , mSmazat IN CHAR  , 
     mUkon_plat IN CHAR  ,
     mNeprfak IN CHAR , mPrifak IN CHAR, mPlatnost_do IN DATE, 
     mZamekvyu IN CHAR, mNeZamekvyu IN CHAR  ) is
  mID_VYROK VYROK.ID_VYROK%TYPE;
  mSqlVyrok VARCHAR2(4000);
  TYPE TqVyrok IS REF CURSOR;
  qVyrok TqVyrok;
  mChyba boolean;
begin

  IF TRIM(mWhere) IS NOT NULL  THEN
    mSqlVyrok := ' SELECT ID_VYROK FROM V_VYROK   MT  WHERE ' || mWhere ;
  ELSE 
    mSqlVyrok := ' SELECT ID_VYROK V_VYROK MT  WHERE ID_VYROK = -1 ' ;
  END IF;

  IF mTransakce = 'A' THEN
    SET TRANSACTION READ WRITE ;  
    
  END IF; 

 ---raise_application_error( -20010 ,mSqlVyrok ) ;

 OPEN qVyrok FOR mSqlVyrok ;
 LOOP

   FETCH qVyrok INTO mID_VYROK;  
   EXIT WHEN qVyrok%NOTFOUND;  
   BEGIN
     IF mSmazat = 'A' THEN
       DELETE FROM VYROK WHERE ID_VYROK = mID_VYROK;
     ELSE
       IF (  mUkon_plat = 'A' ) AND ( mPlatnost_do IS NOT NULL ) THEN
         UPDATE VYROK
           SET PLATNOST_DO = mPlatnost_do,
           LIDENT_ZMENA = mLIDENT
           WHERE ID_VYROK = mID_VYROK;          
       END IF;     
       IF mNeprfak = 'A' THEN
         UPDATE VYROK
           SET NEPRI_FAK = mNeprfak,
           LIDENT_ZMENA = mLIDENT
           WHERE ID_VYROK = mID_VYROK;          
       END IF;
       IF mPrifak = 'A' THEN
         UPDATE VYROK
           SET NEPRI_FAK = 'N',
           LIDENT_ZMENA = mLIDENT
           WHERE ID_VYROK = mID_VYROK;          
       END IF;
       ---- nastavit zamek na vyuctovani
       if mZamekvyu ='A' then 
         UPDATE VYROK
           SET ZAMEK_VYU = 'A',
               NEPRI_FAK = 'A',
               LIDENT_ZMENA = mLIDENT
           WHERE ID_VYROK = mID_VYROK;   
        end if;          
         
       ---- nastavit zamek na vyuctovani
       if mNeZamekvyu ='A' then 
         UPDATE VYROK
           SET ZAMEK_VYU = 'N',
               LIDENT_ZMENA = mLIDENT
           WHERE ID_VYROK = mID_VYROK;          

       end if;  
       
     END IF;
     
       
   EXCEPTION
     WHEN OTHERS THEN
       mChyba := true;
   END ;
    
 END LOOP  ;

 IF mTransakce = 'A' THEN
    COMMIT;  
 END IF; 

end DEL_VYROK ; 
</pre>

Ora2pg:
<pre>
        CREATE OR REPLACE FUNCTION ides_procs.del_vyrok(mwhere text, mtransakce character, mlident numeric, msmazat
         RETURNS void
         LANGUAGE plpgsql
         SECURITY DEFINER
1       AS $function$
2       DECLARE
3
4         mID_VYROK VYROK.ID_VYROK%TYPE;
5         mSqlVyrok varchar(4000);
6
7         qVyrok REFCURSOR;
8         mChyba boolean;
9
10      BEGIN
11
12        IF btrim(mWhere) IS NOT NULL  THEN
13          mSqlVyrok := ' SELECT ID_VYROK FROM V_VYROK   MT  WHERE ' || mWhere;
14        ELSE
15          mSqlVyrok := ' SELECT ID_VYROK V_VYROK MT  WHERE ID_VYROK = -1 ';
16        END IF;
17
18        IF mTransakce = 'A' THEN
19          SET TRANSACTION READ WRITE;
20
21        END IF;
22
23       ---raise_application_error( -20010 ,mSqlVyrok ) ;
24       OPEN qVyrok FOR EXECUTE mSqlVyrok;
25       LOOP
26
27         FETCH qVyrok INTO mID_VYROK;
28         EXIT WHEN NOT FOUND; /* apply on qVyrok */
29         BEGIN
30           IF mSmazat = 'A' THEN
31             DELETE FROM VYROK WHERE ID_VYROK = mID_VYROK;
32           ELSE
33             IF (  mUkon_plat = 'A' ) AND ( mPlatnost_do IS NOT NULL ) THEN
34               UPDATE VYROK
35                 SET PLATNOST_DO = mPlatnost_do,
36                 LIDENT_ZMENA = mLIDENT
37                 WHERE ID_VYROK = mID_VYROK;
38             END IF;
39             IF mNeprfak = 'A' THEN
40               UPDATE VYROK
41                 SET NEPRI_FAK = mNeprfak,
42                 LIDENT_ZMENA = mLIDENT
43                 WHERE ID_VYROK = mID_VYROK;
44             END IF;
45             IF mPrifak = 'A' THEN
46               UPDATE VYROK
47                 SET NEPRI_FAK = 'N',
48                 LIDENT_ZMENA = mLIDENT
49                 WHERE ID_VYROK = mID_VYROK;
50             END IF;
51             ---- nastavit zamek na vyuctovani
52             if mZamekvyu ='A' then
53               UPDATE VYROK
54                 SET ZAMEK_VYU = 'A',
55                     NEPRI_FAK = 'A',
56                     LIDENT_ZMENA = mLIDENT
57                 WHERE ID_VYROK = mID_VYROK;
58              end if;
59
60             ---- nastavit zamek na vyuctovani
61             if mNeZamekvyu ='A' then
62               UPDATE VYROK
63                 SET ZAMEK_VYU = 'N',
64                     LIDENT_ZMENA = mLIDENT
65                 WHERE ID_VYROK = mID_VYROK;
66
67             end if;
68
69           END IF;
70
71
72         EXCEPTION
73           WHEN OTHERS THEN
74             mChyba := true;
75         END;
76
77       END LOOP;
78
79       IF mTransakce = 'A' THEN
80          -- COMMIT;
81       END IF;
82
83      end;;; --------<<<<<<<<<<<<<<<<<<<<<<
84      $function$
</pre>

**Comment by darold** [comment]
Not reproducible with current code.

**Comment by okbob** [comment]
I run it again with same result. Maybe there are some invisible chars lost when I used clipboard. I'll recheck it.

**Comment by okbob** [comment]
I can repeat this issue with attached file 
[test.sql.txt](https://github.com/darold/ora2pg/files/995827/test.sql.txt)

**Comment by darold** [comment]
Might be fixed by commit 2a6611c

**Comment by okbob** [comment]
It is fixed, thank you
