### ISSUE TITLE
Procedure declaration not completely translated

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#408]
This issue is the result of scission of issue #399. I analyzed 2 of the examples further and I suspect a different cause. The 2 affected procedures have their declarations incompletely translated by ora2pg.

Here is the first one:

Oracle:
  PROCEDURE UPD_NB_OF_PARK_SPACES( p_subscription_id IN T_SUBSCRIPTION.subscription_id%TYPE
                                  , p_nb_of_park_space IN T_SUBSCRIPTION.max_total_park_spaces%TYPE default null
                                  , p_date_start T_SUBSCRIPTION.date_validity_begin%TYPE default null
                                  , p_date_end T_SUBSCRIPTION.date_validity_end%TYPE default null
                                  -- Modif-2015-08-31-1 EDe: ajout d'un mode forcé pour assurer les annulations des paniers de création
                                  , p_force NUMBER default 0 -- 1 <=> toujours accepter le transfert même s'il est payant
                                  , v_result OUT NUMBER -- 0 ou code erreur -20100 à -20199
                                 ) IS

Ora2pg output:
  PROCEDURE UPD_NB_OF_PARK_SPACES( p_subscription_id IN T_SUBSCRIPTION.subscription_id%TYPE
                                  , p_nb_of_park_space IN T_SUBSCRIPTION.max_total_park_spaces%TYPE default null
                                  , p_date_start T_SUBSCRIPTION.date_validity_begin%TYPE default null
                                  , p_date_end T_SUBSCRIPTION.date_validity_end%TYPE default null
                                  -- Modif-2015-08-31-1 EDe: ajout d'un mode forcé pour assurer les annulations des paniers de création
                                  , p_force NUMBER default 0 -- 1 <=> toujours accepter le transfert même s'il est payant
                                  , v_result OUT NUMBER -- 0 ou code erreur -20100 à -20199
                                 ) IS

**Comment by edelanoe** [comment]
Here is the second example:

Oracle declaration:
  PROCEDURE TRANSFER_SUBSCRIBER(p_subscriber_id IN T_SUBSCRIBER.subscriber_id%TYPE
                              , p_subscription_id_to IN T_SUBSCRIBER.subscription_id_transfer%TYPE
                              , p_date_start T_SUBSCRIBER.date_validity_begin%TYPE default null
                              , p_date_end T_SUBSCRIBER.date_validity_end%TYPE default null
                              , p_reason_tr_subsr_id T_SUBSCRIBER.reason_tr_subsr_id%TYPE default null
                              -- Modif-2015-08-31-1 EDe: ajout d'un mode forcé pour assurer les annulations
                              , p_force NUMBER default 0 -- 1 <=> toujours accepter le transfert même payant
                              , v_result OUT NUMBER -- 0 ou code erreur -20100 à -20199
                              ) IS

Ora2pg translation:
CREATE OR REPLACE FUNCTION pck_gcl.transfer_subscriber (p_subscriber_id T_SUBSCRIBER.subscriber_id%TYPE , p_subscription_id_to T_SUBSCRIBER.subscription_id_transfer%TYPE , v_result OUT numeric  -- 0 ou code erreur -20100 à -20199
 , p_date_start T_SUBSCRIBER.date_validity_begin%TYPE default null , p_date_end T_SUBSCRIBER.date_validity_end%TYPE default null , p_reason_tr_subsr_id T_SUBSCRIBER.reason_tr_subsr_id%TYPE default null                               -- Modif-2015-08-31-1 EDe: ajout d'un mode forcé pour assurer les annulations
 , p_force numeric default 0 -- 1 <=> toujours accepter le transfert même payant
 ) AS $body$

**Comment by edelanoe** [comment]
... and here is the translation of their calls inside the code:

v_result => v_result  := pck_gcl.upd_nb_of_park_spaces( p_subscription_id => R_SUB_FROM.subscription_id, p_nb_of_park_space => null, p_date_start => p_date_start, p_date_end => p_date_end, p_force => p_force      -- Modif-2015-08-31-1 EDe: ajout d'un mode (forcé)
);

      for R in (SELECT * from t_subscriber where ... )
      loop
           := pck_gcl.transfer_subscriber( p_subscriber_id => R.subscriber_id, p_subscription_id_to => R.subscription_id, p_date_start => null, p_date_end => null, p_force => p_force, v_result => v_result
                              );
      end loop;


In Oracle it was:
      UPD_NB_OF_PARK_SPACES( p_subscription_id => p_subscription_id_to
                            , p_nb_of_park_space => null
                            , p_date_start => p_date_start
                            , p_date_end => p_date_end
                            , p_force => p_force      -- Modif-2015-08-31-1 EDe: ajout d'un mode (forcé)
                            , v_result => v_result );

          TRANSFER_SUBSCRIBER ( p_subscriber_id => R.subscriber_id
                              , p_subscription_id_to => R.subscription_id
                              , p_date_start => null
                              , p_date_end => null
                              , p_force => p_force
                              , v_result => v_result
                              );

**Comment by darold** [comment]
Please send the full Oracle original code to my private email, I will spent too much time to create a workable code to try to reproduce the issue. Thanks Eric.

**Comment by edelanoe** [comment]
Hello,

I have sent you the full Oracle code of the concerned package.
Rgds,
Eric

**Comment by edelanoe** [comment]
On 06/27 master version, I still have
- PROCEDURE pck_gcl.upd_nb_of_park_spaces is not changed into a function
- FUNCTION pck_gcl.transfer_subscriber has a change in parameter order, and no RETURN type
- Wrong calls to the untranslated procedures:
"v_result => v_result  := pck_gcl.upd_nb_of_park_spaces( p_subscription_id => p_subscription_id_to"  (...)
"perform  pck_gcl.transfer_subscriber( p_subscriber_id => R.subscriber_id, p_subscription_id_to => R.subscription_id, p_date_start => null, p_date_end => null, p_force => p_force, v_result => v_result
                                );"
Should I totally avoid named parameter calls ?

Thanks again and best regards,
Eric

**Comment by darold** [comment]
Yes, named parameter are not supported yet in Ora2Pg, it need some days of work and I don't have the time right now. Sorry for the delay, this is not technically untranslatable, this is just a question of spare time.

**Comment by edelanoe** [comment]
Hello Gilles,

Ok, I will cope with my named parameter calls for the moment.
... but I still have a lot of declaration issues:
- Functions (from procedures) without RETURN VOID clause (first one: transfer_ticket)
- PROCEDUREs not changed into FUNCTIONs: all procs or functions that follow one of my biggest ones (sub_ren_manage_vars)
Examples are in the code I will re-provide to you in a minute (PCK_GCL) with its output (processed by today's ora2pg download)
Can you reproduce these ?

**Comment by darold** [comment]
Hi Eric,

The function transfer_ticket() doesn't have a RETURNS VOID because there is one OUT parameter, this is expected. I can reproduce the second problem and I'm investigating the reason.

**Comment by darold** [comment]
Commit 3eace65 might solve the second issue.
