### ISSUE TITLE
Replace "close()" calls on filehandles by close_export_file

### ISSUE THREAD

**Issue by SebAlbert** [darold/ora2pg#409]
There are still some places left where the object method `close()` is called on filehandles that may be Gzip-Filehandles, so should be calling `$self->close_export_file(...)`, my current problem being line 5593, but there are more if you simply search for `->close()` (some of them may be correct)

Resulting error message is

> Can't locate object method "close" via package "Compress::Zlib::gzFile" at /usr/local/share/perl5/Ora2Pg.pm line 5593.

**Comment by darold** [comment]
Commit 84c166e might solve this issue. All call to `->close()` have been replaced with call to `->close_export_file()`. Thanks.

**Comment by SebAlbert** [comment]
Looks good, thank you
