### ISSUE TITLE
Option to exclude individual columns 

### ISSUE THREAD

**Issue by bjornbak** [darold/ora2pg#41]
As far as I can see the only way not to migrate unused columns is to drop them before migration?

I have a rather large table in Oracle 130+ million total 6+ GB where I have some unused columns and it takes a very long time to remove the unused columns before migration.

It would be nice if a could exclude some columns with a syntax similar to the REPLACE_COLS option.

**Comment by C-h-e-r-r-y** [comment]
So in total there is not way to exclude columns? I am using `TABLE` migration type and when I deifned:

MODIFY_STRUCT	my_table(col1, col3)

The `col2` is still here after migration. So only reordering is supported?

**Comment by darold** [comment]
The MODIFY_STRUCT is only available with data export to adapt to any schema transformation. But I think that with some additional work it could be available for tables/indexes/constraints export.

**Comment by C-h-e-r-r-y** [comment]
So could I create new task for this or reopen current task?

**Comment by darold** [comment]
I've reopen it, thanks.

**Comment by darold** [comment]
Commit 2315983 allow use of MODIFY_STRUCT with TABLE export. Table creation DDL will respect the new list of columns and all indexes or foreign key pointing to or from a column removed will not be exported.

> Another question: can this option be used to rearrange the order of columns in postgresql? I learned during migration that I get a more efficient storage if small columns (like boolean columns) are next to each other.

I've forgotten to answer to this question, for automatic reordering by ora2pg you just have to enable the REORDERING_COLUMNS configuration directive in ora2pg.conf. It must be a bit too late, but can be useful for later use and other users.
