### ISSUE TITLE
Error while importing schema

### ISSUE THREAD

**Issue by Narayanamoorthys** [darold/ora2pg#410]
I am trying to migrate an Oracle database to PostgreSQL.  While doing './import_all.sh' received following error message:

CREATE TABLE
ALTER TABLE
CREATE FOREIGN TABLE
psql:./schema/tables/table.sql:117: ERROR:  "iptest" is a foreign table
HINT:  Use ALTER FOREIGN TABLE instead.
ERROR: an error occurs when importing file ./schema/tables/table.sql.

in schema/tables/tables.sql, i see

CREATE FOREIGN TABLE iptest (
        ipadd varchar(15),
        username varchar(20),
        password varchar(20)
) SERVER data_pump_dir OPTIONS(filename 'c:\apps\oracle/admin/pro/dpdump/\ipsheet.csv', format 'csv', delimiter ',');
ALTER TABLE iptest OWNER TO postgres;

Here the table creation command uses "FOREIGN TABLE"where alter table uses "ALTER TABLE".

All parameters are default except ORACLE_HOME, ORACLE_DSN, ORACLE_USER, ORACLE_PWD and SCHEMA

**Comment by darold** [comment]
Thanks for the report. Commit db7b6b1 might fix this issue.

**Comment by Narayanamoorthys** [comment]
Thanks. The patch fixed the issue.
