### ISSUE TITLE
Missing STRICT for SELECT INTO

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#411]
Oracle:
<pre>
CREATE OR REPLACE function IDES_JMMAJ.GET_DUPL_VYU_ZALOHA( mID_VYZAH IN VYZAH.ID_VYZAH%TYPE  ) return SMALLINT is
  Result SMALLINT ;
begin
    ---SAB PGsql determinovana tabulka vnoreny select za FROM
    BEGIN
      SELECT POCET INTO Result
          FROM (
          SELECT B2.ID_POL_PRED , COUNT(*) AS POCET
          FROM VYSPOL B1 , VYVDATVYS B2
          WHERE B1.ID_VYZAH = mID_VYZAH
          AND B1.ID_VYSPOL = B2.ID_VYSPOL
          AND B2.ID_NAJDATSPLT IS NOT NULL
          AND B2.PLATNOST_DO = RRRUTIL.R_MAXDATE()
          AND B1.PLATNOST_DO = RRRUTIL.R_MAXDATE()
          --AND B2.ID_POL_PRED IS NOT NULL GROUP BY B1.ID_POLONAJ , B2.ID_NAJDATSPLT ) WHERE POCET > 1 AND ROWNUM < 2;
          AND B2.ID_POL_PRED IS NOT NULL GROUP BY B2.ID_POL_PRED , B2.ID_NAJDATSPLT ) MT
           WHERE POCET > 1 AND ROWNUM < 2;
      EXCEPTION
        WHEN NO_DATA_FOUND THEN
          Result := 0;
        WHEN OTHERS THEN
          Result := 0;
      END;

  return(Result);
end GET_DUPL_VYU_ZALOHA;
</pre>
Oracle can handle no_data exception

Ora2pg result:
<pre>
CREATE OR REPLACE FUNCTION get_dupl_vyu_zaloha(mid_vyzah bigint)
  RETURNS smallint AS
$BODY$
DECLARE

  Result smallint;

BEGIN
    ---SAB PGsql determinovana tabulka vnoreny select za FROM
    BEGIN
      SELECT POCET INTO Result
          FROM (
          SELECT B2.ID_POL_PRED , COUNT(*) AS POCET
          FROM VYSPOL B1 , VYVDATVYS B2
          WHERE B1.ID_VYZAH = mID_VYZAH
          AND B1.ID_VYSPOL = B2.ID_VYSPOL
          AND B2.ID_NAJDATSPLT IS NOT NULL
          AND B2.PLATNOST_DO = RRRUTIL.R_MAXDATE()
          AND B1.PLATNOST_DO = RRRUTIL.R_MAXDATE()
          --AND B2.ID_POL_PRED IS NOT NULL GROUP BY B1.ID_POLONAJ , B2.ID_NAJDATSPLT ) WHERE POCET > 1 AND ROWNUM < 2;
          AND B2.ID_POL_PRED IS NOT NULL GROUP BY B2.ID_POL_PRED , B2.ID_NAJDATSPLT ) MT
           WHERE POCET > 1  LIMIT 1;
      EXCEPTION
        WHEN OTHERS THEN
          Result := 0;
      END;

  return(Result);
END;
$BODY$
  LANGUAGE plpgsql STABLE SECURITY DEFINER
  COST 100;
ALTER FUNCTION get_dupl_vyu_zaloha(bigint)
  OWNER TO ides;
</pre>

**Comment by darold** [comment]
Not reproducible, here is what I have with latest code:

```
CREATE OR REPLACE FUNCTION get_dupl_vyu_zaloha ( mID_VYZAH VYZAH.ID_VYZAH%TYPE ) RETURNS smallint AS $body$
DECLARE

  Result smallint;

BEGIN
    ---SAB PGsql determinovana tabulka vnoreny select za FROM
    BEGIN
      SELECT POCET INTO STRICT  Result
          FROM (
          SELECT B2.ID_POL_PRED , COUNT(*) AS POCET
          FROM VYSPOL B1 , VYVDATVYS B2
          WHERE B1.ID_VYZAH = mID_VYZAH
          AND B1.ID_VYSPOL = B2.ID_VYSPOL
          AND B2.ID_NAJDATSPLT IS NOT NULL
          AND B2.PLATNOST_DO = RRRUTIL.R_MAXDATE()
          AND B1.PLATNOST_DO = RRRUTIL.R_MAXDATE()
          --AND B2.ID_POL_PRED IS NOT NULL GROUP BY B1.ID_POLONAJ , B2.ID_NAJDATSPLT ) WHERE POCET > 1 AND ROWNUM < 2;
          AND B2.ID_POL_PRED IS NOT NULL GROUP BY B2.ID_POL_PRED , B2.ID_NAJDATSPLT ) MT
           WHERE POCET > 1  LIMIT 1;
       EXCEPTION
        WHEN NO_DATA_FOUND THEN
          Result := 0;
        WHEN OTHERS THEN
          Result := 0;
      END;


  return(Result);
end;
$body$
LANGUAGE PLPGSQL
 STABLE;
```

**Comment by okbob** [comment]
It is fixed. I am sorry for noise.
