### ISSUE TITLE
missing explicitly declared variable for cycle in trigger

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#413]
Oracle:
<pre>
TRIGGER "IDES_JMMAJ".NAJPENALCE_AI AFTER INSERT
ON  NAJPENALCE
FOR EACH ROW

BEGIN

IF ( :new.TYPPARA = 'A'  ) THEN
 
  IF :new.ID_NAJPENALCE_ZAHRNUJE IS NULL THEN
    IF :new.TYP_UZI = 'P'  THEN
      FOR qLokBudo IN 
        ( SELECT ID_STAVOBJ , ID_ASPRAVCE ,ID_APROVOZNA 
               FROM OBPBUDO
               WHERE ID_APROVOZNA = :new.ID_APROVOZNA  ) 
      LOOP
         INSERT INTO NAJVPENVZT( ID_NAJPENALCE , ID_STAVOBJ ,ID_ASPRAVCE ,ID_APROVOZNA )
            VALUES( :new.ID_NAJPENALCE , qLokBudo.ID_STAVOBJ , qLokBudo.ID_ASPRAVCE , qLokBudo.ID_APROVOZNA );
     
      END LOOP ;          
    
    ELSE
    
      IF :new.TYP_UZI = 'R'  THEN
        FOR qLokBudo IN 
        ( SELECT ID_STAVOBJ , ID_ASPRAVCE  , ID_APROVOZNA
               FROM OBPBUDO
               WHERE ID_ASPRAVCE = :new.ID_ASPRAVCE  ) 
        LOOP
         INSERT INTO NAJVPENVZT( ID_NAJPENALCE , ID_STAVOBJ ,ID_ASPRAVCE , ID_APROVOZNA )
            VALUES( :new.ID_NAJPENALCE , qLokBudo.ID_STAVOBJ , qLokBudo.ID_ASPRAVCE , qLokBudo.ID_APROVOZNA );
     
        END LOOP ;          
    
      END IF;
    
      IF :new.TYP_UZI = 'V'  THEN
          
        FOR qLokBudo IN 
        ( SELECT ID_STAVOBJ , ID_ASPRAVCE , ID_APROVOZNA 
            FROM V_LOGIN_VLASTNIK_PRSTR   
             WHERE ID_SSSLOGIN = :new.ID_SSSLOGIN
             GROUP BY ID_STAVOBJ , ID_ASPRAVCE , ID_APROVOZNA ) 
        LOOP
         INSERT INTO NAJVPENVZT( ID_NAJPENALCE , ID_STAVOBJ ,ID_ASPRAVCE , ID_APROVOZNA  )
            VALUES( :new.ID_NAJPENALCE , qLokBudo.ID_STAVOBJ , qLokBudo.ID_ASPRAVCE , qLokBudo.ID_APROVOZNA );
     
        END LOOP ;          
    
      END IF;
    
      
    END IF; 
  ELSE
      FOR qLokUpo IN
      ( SELECT * 
           FROM NAJVPENVZT
           WHERE ID_NAJPENALCE = :new.ID_NAJPENALCE_ZAHRNUJE )  
    LOOP
      INSERT INTO NAJVPENVZT ( ID_NAJPENALCE,ID_ASPRAVCE,ID_APROVOZNA,ID_STAVOBJ,LIDENT, CVZNIKRADK , PLATNY )
        VALUES( :new.ID_NAJPENALCE , qLokUpo.ID_ASPRAVCE,qLokUpo.ID_APROVOZNA,qLokUpo.ID_STAVOBJ,:new.LIDENT , RRRUTIL.HROMADNA_ZMENA, qLokUpo.PLATNY);
      
    END LOOP; 

  END IF;
END IF;

END ;
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE FUNCTION public.trigger_fct_najpenalce_ai()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN

IF ( NEW.TYPPARA = 'A'  ) THEN

  IF NEW.ID_NAJPENALCE_ZAHRNUJE IS NULL THEN
    IF NEW.TYP_UZI = 'P'  THEN
      FOR qLokBudo IN ( SELECT ID_STAVOBJ , ID_ASPRAVCE ,ID_APROVOZNA 
               FROM OBPBUDO
               WHERE ID_APROVOZNA = NEW.ID_APROVOZNA  ) 
      LOOP
         INSERT INTO NAJVPENVZT( ID_NAJPENALCE , ID_STAVOBJ ,ID_ASPRAVCE ,ID_APROVOZNA )
            VALUES ( NEW.ID_NAJPENALCE , qLokBudo.ID_STAVOBJ , qLokBudo.ID_ASPRAVCE , qLokBudo.ID_APROVOZNA );

      END LOOP;
    
    ELSE
    
      IF NEW.TYP_UZI = 'R'  THEN
        FOR qLokBudo IN ( SELECT ID_STAVOBJ , ID_ASPRAVCE  , ID_APROVOZNA
               FROM OBPBUDO
               WHERE ID_ASPRAVCE = NEW.ID_ASPRAVCE  ) 
        LOOP
         INSERT INTO NAJVPENVZT( ID_NAJPENALCE , ID_STAVOBJ ,ID_ASPRAVCE , ID_APROVOZNA )
            VALUES ( NEW.ID_NAJPENALCE , qLokBudo.ID_STAVOBJ , qLokBudo.ID_ASPRAVCE , qLokBudo.ID_APROVOZNA );

        END LOOP;
    
      END IF;

      IF NEW.TYP_UZI = 'V'  THEN
          
        FOR qLokBudo IN ( SELECT ID_STAVOBJ , ID_ASPRAVCE , ID_APROVOZNA 
            FROM V_LOGIN_VLASTNIK_PRSTR   
             WHERE ID_SSSLOGIN = NEW.ID_SSSLOGIN
             GROUP BY ID_STAVOBJ , ID_ASPRAVCE , ID_APROVOZNA ) 
        LOOP
         INSERT INTO NAJVPENVZT( ID_NAJPENALCE , ID_STAVOBJ ,ID_ASPRAVCE , ID_APROVOZNA  )
            VALUES ( NEW.ID_NAJPENALCE , qLokBudo.ID_STAVOBJ , qLokBudo.ID_ASPRAVCE , qLokBudo.ID_APROVOZNA );

        END LOOP;
    
      END IF;

      
    END IF;
  ELSE
      FOR qLokUpo IN ( SELECT * 
           FROM NAJVPENVZT
           WHERE ID_NAJPENALCE = NEW.ID_NAJPENALCE_ZAHRNUJE )  
    LOOP
      INSERT INTO NAJVPENVZT( ID_NAJPENALCE,ID_ASPRAVCE,ID_APROVOZNA,ID_STAVOBJ,LIDENT, CVZNIKRADK , PLATNY )
        VALUES ( NEW.ID_NAJPENALCE , qLokUpo.ID_ASPRAVCE,qLokUpo.ID_APROVOZNA,qLokUpo.ID_STAVOBJ,NEW.LIDENT , RRRUTIL.HROMADNA_ZMENA, qLokUpo.PLATNY);

    END LOOP;

  END IF;
END IF;

RETURN NEW;
END
$function$
</pre>

Error:
<pre>
error:42601:loop variable of loop over rows must be a record or row variable or list of scalar variables
Query: 
       BEGIN
       
       IF ( NEW.TYPPARA = 'A'  ) THEN
       
         IF NEW.ID_NAJPENALCE_ZAHRNUJE IS NULL THEN
           IF NEW.TYP_UZI = 'P'  THEN
             FOR qLokBudo IN ( SELECT ID_STAVOBJ , ID_ASPRAVCE ,ID_APROVOZNA 
--               ^
</pre>

**Comment by darold** [comment]
Might be fixed with commit 9bb39fe

**Comment by okbob** [comment]
It is fixed. Thank you
