### ISSUE TITLE
WARNING: Skipping dumping data to file

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#415]
Is there someway to override this directive when dumping data to file?  I don't want to have to clean out my location where previous data was dumped.  the other types appear not to skip if file exists.

**Comment by darold** [comment]
When you have huge amount of data to be exported again, you will appreciate this feature :-) I don't think calling an rm command before is more complicated than looking for a configuration directive.

**Comment by MichaelDBA** [comment]
It should probably be noted in the documentation somewhere that using ora2pg for INSERT or COPY will fail if the file already exists.  Since it is only these 2 TYPES that are handled differently from all the other TYPES, as far as I know.

We run a lot of scripted batch files for ora2pg over and over again to refresh our environments since we have a moving Oracle source target, and we almost missed the fact the we were not getting our data files updated.

**Comment by MichaelDBA** [comment]
Feel free to close this ticket once you have considered my documentation request, and man you do one bang up job with this stuff!

**Comment by darold** [comment]
Commit 9b08ccd add the following information to documentation:
```
    When using Ora2Pg export type INSERT or COPY to dump data to file and
    that FILE_PER_TABLE is enabled, you will be warned that Ora2Pg will not
    export data again if the file already exists. This is to prevent
    downloading twice table with huge amount of data. To force the download
    of data from these tables you have to remove the existing output file
    first.
```
