### ISSUE TITLE
FTS_INDEXES_xxxx_tables.sql files

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#416]
Ora2pg generates a non empty FTS_INDEXES... files that only have SET commands if there is no FDW to be created:
```
-- Generated by Ora2Pg, the Oracle database Schema converter, version 18.1
-- Copyright 2000-2017 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;sid=orcl
SET client_encoding TO 'UTF8';
SET search_path = icw,public,pg_catalog;
```
Would it be possible to not generate this file if there is nothing to do?  It makes it easier to search for FDWs in ora2pg output files.  Or just generate this file as empty, 0 bytes.  That way at least I can find the valid FTS files.

**Comment by MichaelDBA** [comment]
Also, another thing with FTS indexes while we are at it.

Can you add the IF NOT EXISTS syntax to creating extensions.  This is supported for extensions since at least 9.2.

**Comment by darold** [comment]
Commit 07ef196 might fix this issue.

**Comment by MichaelDBA** [comment]
thanks
