### ISSUE TITLE
pg keywords

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#417]
Can you fix ora2pg so that when it creates tables it will enclose column names in double quotes if it is a pg keyword like "primary"?

**Comment by darold** [comment]
That should already be the case if you enable USE_RESERVED_WORDS in ora2pg.conf

**Comment by MichaelDBA** [comment]
ahhhh coooool!

**Comment by MichaelDBA** [comment]
I have a column named, constraint, and it is not automatically being enclosed with double-quotes even though I have USE_RESERVED_WORDS 1

**Comment by MichaelDBA** [comment]
found another keyword not enclosed in double quotes, user

**Comment by darold** [comment]
Damn right, this feature was totally broken. Commit e2041d0 reintroduce this feature.

**Comment by MichaelDBA** [comment]
So does that mean it is fixed now?

**Comment by darold** [comment]
At least it might be :-)

**Comment by MichaelDBA** [comment]
Yes, it is fixed now.  Thank you.
