### ISSUE TITLE
Separate PKEYS from FKEYS

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#418]
Once common thing that DBAs do is disable/enable FKEYS, drop, recreate them etc.  Such being the case, it would be nice to separate out the PKEYS from FKEYS in the tables folder, file:
CONSTRAINTS_xxx.sql

Would that be not too hard to implement and perhaps add a directive to cause this separation so we could have 2 files in the output tables folder instead of one for PKEYS, FKEYS, CHECKS.

Still keep the PKEYS and CHECKs in one file, just separate out the FKEYS.

**Comment by darold** [comment]
Commit 56297c7 adds this feature:
```
Add FILE_PER_FKEYS configuration directive to Allow foreign key declaration
to be saved in a separate file during schema export. By default foreign keys
are exported into the main output file or in the CONSTRAINT_output.sql file.
If enabled foreign keys will be exported into a file named FKEYS_output.sql
```

**Comment by MichaelDBA** [comment]
Thank uuuuuuuuuuuuuuuuuu!!!!!!!!!!!!
