### ISSUE TITLE
Empty string is replaced with '%TEXTVALUE-...%'

### ISSUE THREAD

**Issue by dommi22m** [darold/ora2pg#421]
Version: v18.1

Example:
- Issue: 
-- update ELEITAB SET ELA_IDKN1 = '{00000000-0000-0000-0000-000000000000}', ELA_NRKN1 = '%TEXTVALUE-1%',ELA_ARTKN1 = '%TEXTVALUE-3%KV');
- right syntax from oracle: 
--  update ELEITAB SET ELA_IDKN1 = '{00000000-0000-0000-0000-000000000000}', ELA_NRKN1 = '',ELA_BEZKN1 = '',ELA_ARTKN1 = '' where (ELA_IDKN1 = :old.EMU_ID) and (ELA_ARTKN1 = 'Mu');

Do I something wrong or is it a bug?

Also i found FIX in the changelog:
- Fix replacement of placeholder %TEXTVALUE-d% to hide text string
    in query during function call rewrite. Thanks to Lorena Figueredo
    for the report.

It really looks like my problem...

Regards Tommy

**Comment by darold** [comment]
Please use latest development code, it might be fixed yet.
