### ISSUE TITLE
problem with duplicate subpartition names

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#422]
ora2pg tries to create the same child table in the same schema because there are multiple parents that have the same subpartition name.  How can we fix this?  It tries to create the same table multiple times in the provider schema, P_20110317_OTHERS.

Below is a snippet from oracle using SQL:
`select table_owner, table_name, partition_name, subpartition_name, logging from dba_tab_subpartitions where table_owner = 'PROVIDER' and subpartition_name = 'P_20110317_OTHERS' order by subpartition_name;
`
Here is the result:
```
TABLE_OWNER	TABLE_NAME			PARTITION_NAME	SUBPARTITION_NAME	LOGGING
PROVIDER	STATS_BILLING_SPIKE		P_20110317	P_20110317_OTHERS	YES
PROVIDER	STAT S_EM_CODES			P_20110317	P_20110317_OTHERS	YES
PROVIDER	STATS_OUT_OF_AREA		P_20110317	P_20110317_OTHERS	YES
PROVIDER	STATS_PROVIDER_MOD25		P_20110317	P_20110317_OTHERS	YES
PROVIDER	STATS_PROVIDER_MODS		P_20110317	P_20110317_OTHERS	YES
PROVIDER	STATS_PROVIDER_PROCS		P_20110317	P_20110317_OTHERS	NO
PROVIDER	STATS_PROVIDER_PROCS_OLD	P_20110317	P_20110317_OTHERS	YES
PROVIDER	STATS_SPECIALTY_RATIOS		P_20110317	P_20110317_OTHERS	YES

```

**Comment by MichaelDBA** [comment]
perhaps a new child naming convention?

table_name_subpartition_name?

Of course the insert triggers would have to change accordingly.

Only problem I can think of is if applications where referencing child tables directly.  They would have to modify their SQL.

**Comment by darold** [comment]
Hum, that should already be the case if you enable PREFIX_PARTITION configuration directive.

**Comment by MichaelDBA** [comment]
dag i missed that parm!  Thanks
