### ISSUE TITLE
output is empty for some procedures

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#423]
Some of my oracle procedures only have this in them:

```
-- Generated by Ora2Pg, the Oracle database Schema converter, version 18.1
-- Copyright 2000-2017 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;sid=orcl
SET client_encoding TO 'UTF8';
SET
SET search_path = gmacm,public,pg_catalog;

```
But when I look in Oracle, I see a complete procedure body.  For example, P_AMD_EXPORT_PROCESS

```
\i /var/lib/pgsql/stage/gmacm/procedures/P_AMD_EXPORT_PROCESS_gmacm_procedures.sql
-- Generated by Ora2Pg, the Oracle database Schema converter, version 18.1
-- Copyright 2000-2017 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;sid=orcl
SET client_encoding TO 'UTF8';
SET
SET search_path = gmacm,public,pg_catalog;
SET
\i /var/lib/pgsql/stage/gmacm/procedures/P_POST_SETCLAIMTYPE_gmacm_procedures.sql

```

**Comment by MichaelDBA** [comment]
Upon further investigation I see a pattern:

Procs that have comment lines between the CREATE OR REPLACE PROCEDURE and the "IS" line
only have the 2 SET commands in the ora2pg output files.

Procs that have the "IS" line immediately following the CREATE OR REPLACE PROCEDURE line do have the procedural body.

**Comment by darold** [comment]
Commit 22d2c5a might solve this issue.

**Comment by MichaelDBA** [comment]
I will update this later today to let you know.

**Comment by MichaelDBA** [comment]
Sorry it took so long to get back to you.  It appears to be fixed now.  Thank you.
