### ISSUE TITLE
Data COPY Error

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#424]
I get this error when attempting to COPY data:

```
DBD::Oracle::st execute failed: ORA-00932: inconsistent datatypes: expected BINARY got FILE (DBD ERROR: error possibly near <*> indicator at char 67 in 'SELECT "ID","FILENAME","CLIENT_ID","TIMESTAMP","IMAGE" FROM "ACEG".<*>"IMAGE_BFILE" a') [for Statement "SELECT "ID","FILENAME","CLIENT_ID","TIMESTAMP","IMAGE" FROM "ACEG"."IMAGE_BFILE" a"] at /usr/local/share/perl5/Ora2Pg.pm line 11814.
Aborting export...
```

Here is table DDL:

```
 CREATE TABLE "ACEG"."IMAGE_BFILE" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CLIENT_ID" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"TIMESTAMP" DATE NOT NULL ENABLE, 
	"IMAGE" BFILE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 COMPRESS BASIC LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
```

**Comment by darold** [comment]
Have you overridden the DATA_TYPE configuration directive? By default BFILE are exported as bytea, but you can change the behavior by changing the destination data type.  See README file at DATA_TYPE section and especially the chapter about BFILE.

**Comment by MichaelDBA** [comment]
Unfortunately, our target is RDS PG so we cannot take advantage of your EFILE method, although I like your work in this regard.

So it looks like we need to do this:
`BFILE:varchar(255)`

Is that going to be a problem when using ora2pg for COPY and subsequent imports into PG?  Or is there a way I can alter ora2pg configuration to handle PG varchar target for BFILE from Oracle?

**Comment by darold** [comment]
You have to convert it to text, not varchar: `BFILE:text` In this case Ora2Pg will just extract the filename.

**Comment by MichaelDBA** [comment]
whoops, saw that a bit late, rats gotta run em again, I used varchar, will close this ticket if it runs ok with text instead.

**Comment by MichaelDBA** [comment]
Got a different error this time:
```
[>                        ]    10224/39136119 total rows (0.0%) - (24 sec., avg: 426 recs/sec).

[>                        ]    10224/39136119 total rows (0.0%) - (24 sec., avg: 426 recs/sec).
DBD::Oracle::db prepare failed: ORA-00904: "ORA2PG_GET_BFILENAME": invalid identifier (DBD ERROR: error possibly near <*> indicator at char 47 in 'SELECT "ID","FILENAME","CLIENT_ID","TIMESTAMP",<*>ora2pg_get_bfilename("IMAGE") FROM "CNTRY"."IMAGE_BFILE" a') at /usr/local/share/perl5/Ora2Pg.pm line 11819.
Aborting export...
```

**Comment by darold** [comment]
Fixed in last commit be9f5a1

**Comment by MichaelDBA** [comment]
Still got an error.  Also note that it tries to connect again and then has userid/password problems.

```
FATAL: ORA-00932: inconsistent datatypes: expected BINARY got FILE (DBD ERROR: error possibly near <*> indicator at char 67 in 'SELECT "ID","FILENAME","CLIENT_ID","TIMESTAMP","IMAGE" FROM "ACEG".<*>"IMAGE_BFILE" a')
Ora2Pg version: 18.1
Trying to connect to database: dbi:Oracle:host=localhost;sid=orcl
FATAL: 1017 ... ORA-01017: invalid username/password; logon denied (DBD ERROR: OCISessionBegin)
```

**Comment by darold** [comment]
You are not using latest development code or your ora2pg.conf doesn't containt:
```
DATA_TYPE    BFILE:text
```
in the other case the query use `ora2pg_get_bfilename("IMAGE_BFILE")` to extract data which is.not the case here.

**Comment by MichaelDBA** [comment]
My ora2pg config file does have BFILE:text, so let's address the latest code issue.  I downloaded vi zip and git clone, did the perl thang, and the make and make install and the date on the ora2pg binary is still May 22 before the commit mentioned it was implemented.

**Comment by MichaelDBA** [comment]
further look shows that the make install does not update the path, /usr/local/bin/ora2pg

```
# ls /root/ora2pg-git/blib/script/ora2pg -l
-rwxr-xr-x. 1 root root 37517 May 26 17:47 /root/ora2pg-git/blib/script/ora2pg
# ls /root/ora2pg-git/scripts/ora2pg -l
-rw-r--r--. 1 root root 37432 May 26 17:47 /root/ora2pg-git/scripts/ora2pg
# ls /root/ora2pg-master/scripts/ora2pg -l
-rw-r--r--. 1 root root 37432 May 26 17:47 /root/ora2pg-master/scripts/ora2pg
# ls /usr/local/bin/ora2pg -l
-r-xr-xr-x. 1 root root 37517 May 22 08:20 /usr/local/bin/ora2pg
```

**Comment by darold** [comment]
The problem doesn't come from the ora2pg script but either from the .pm files or your configuration file.

**Comment by MichaelDBA** [comment]
Thanks, problem was I was installing it in 2 ways, git and zip file, and lost track of them.
