### ISSUE TITLE
Oracle aggregate function LISTAGG not translated

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#425]
The Oracle keyword "listagg" is not translated, although the PostgreSQL documentation makes some kind of promises about a very similar syntax. Actually, I see that the Oracle-like syntax of "string_agg" is not well working: it doesn't work with "WITHIN GROUP" clause. Could ora2pg help doing the job ?

An example is provided in the attachment.
Best Rgds,
Eric
[Listagg_T_VAT_RATE.txt](https://github.com/darold/ora2pg/files/1018908/Listagg_T_VAT_RATE.txt)

**Comment by slardiere** [comment]
You could use the PostgreSQL extension Orafce , which provide listagg

**Comment by darold** [comment]
As Sebastien says, Orafce, thanks to Pavel, provide lot of Oracle functions that can be used without manual rewrite, this is especially useful when Ora2Pg fails at automatic rewriting. Here it seems that it could be done automatically but I've not already taken the time to work on it. I keep this issue open as a reminder.

**Comment by darold** [comment]
Commit d847810 adds this translation.
