### ISSUE TITLE
triggers and data

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#427]
When I attempt import data after the ora2pg runs, it fails for a table that has a trigger that tries to populate a table that was already loaded so I get a PKEY dup index violation:

`psql mydb < ./myschema_data.sql`

which invokes all the data files in that same directory.

**Comment by darold** [comment]
The best practice is to load all indexes, constraints and triggers at end of the migration, after data import. If you still want to be able to import your data after trigger creation enable DISABLE_TRIGGERS with value ALL to disable RI constraints. The restriction is that data must be loaded with a superuser.

**Comment by MichaelDBA** [comment]
Thanks!
