### ISSUE TITLE
error when creating a report over Oracle 12c database

### ISSUE THREAD

**Issue by adrianboangiu** [darold/ora2pg#428]
Hello,

I have the following error when I try to generate a report:

D:\PostgreSQL\migration\coswin8i>ora2pg -t SHOW_REPORT -c .\config\ora2pg.conf --dump_as_html --estimate_cost > .\reports\report.html
Unmatched ) in regex; marked by <-- HERE in m/^) <-- HERE $/ at D:/__siv608/Perl64/site/lib/Ora2Pg/PLSQL.pm line 2139.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(HOST=localhost)(PROTOCOL=tcp)(POR
T=1526))(ADDRESS=(HOST=localhost)(PROTOCOL=tcp)(PORT=1521)))(CONNECT_DATA=(SID=MARKET))) at D:/__siv608/Perl64/site/lib/Ora2Pg/PLSQL.pm line 2139.

I am using Ora2Pg 18.1 with ActiveState Perl 5.24.1

**Comment by darold** [comment]
Hi,

Seem that you have some parenthesis in the outer join clause, commit bdbbf94 might solve this issue. Please download and install latest development code and let me know.

Regards
