### ISSUE TITLE
Broken INSERT by STRICT keyword

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#429]
Original Oracle

[zmena_predpisu.txt](https://github.com/darold/ora2pg/files/1033333/zmena_predpisu.txt)

Wrong result:
<pre>
767                           LOOP
768                             IF qNAJPROS.TYP_NAJ IN ( 'D' , 'H' ) THEN
769                                /*
770                                UPDATE NAJPROS
771                                  SET SAZBA = ( SAZBA * mCastkaKrat )
772                                  WHERE ID_NAJPROS = qNAJPROS.ID_NAJPROS;
773
774                                */
775                                INSERT INTO STRICT RRRNAJUZA_ERR( AKCE , TEXT , INFO )
776                                  VALUES ( 'ZMENAKOEFNAJEMM2' , ( qNAJPROS.SAZBA * mCastkaKrat ) , qNAJPROS.ID_NAJPROS );
777
778                                mUpdatePolozky := mUpdatePolozky  || ' , JED_CASTKA = ( JED_CASTKA * ''' || mCastkaKrat || ''' ) ';
779                                mUpdatePolozky := mUpdatePolozky  || ' , SAZBA_POL = ( SAZBA_POL * ''' || mCastkaKrat || ''' ) ';
780                                EXIT;
781                             END IF;
782
783                           END LOOP;
</pre>

**Comment by darold** [comment]
Sorry, commit b8c7b0b fix this issue.

**Comment by okbob** [comment]
No sorry :).
It is fixed. thank you
