### ISSUE TITLE
Transformation of TYPE x IS REF CURSOR is not stable

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#430]
Oracle:
<pre>
CREATE OR REPLACE PROCEDURE px(mWhere varchar)
IS
  TYPE TqUcejedn IS REF CURSOR;
  qUcejedn TqUcejedn;
  TYPE TqUcecisrad IS REF CURSOR;
  qUcecisrad TqUcecisrad;
</pre>

Custom types are not supported in variable declaration in plpgsql. Should be replaced by ora2pg

**Comment by darold** [comment]
It seems complicated, replaced by what? How do you see this replacement?

**Comment by okbob** [comment]
When declared type is REF CURSOR, then transformation is not too complex - theoretically there can be a problem with nesting due nested block, but when the type is declared on procedure level, then it is visible all time - (usually types are not shadowed).
<pre>
  ... declaration part ...
  TYPE T1 IS REF CURSOR [...]
  var1 T1

  can be evaluated in postgres like
  var1 REFCURSOR 
</pre>

PostgreSQL has not strong typed cursor variables, so any other information should be truncated.

**Comment by okbob** [comment]
I recheck this issue. Now Ora2pg does the transformation of fragment:
<pre>
  TYPE TqOBPVOMOB IS REF CURSOR;
  qOBPVOMOB TqOBPVOMOB;
</pre>

Translated:
<pre>
  
  qOBPVOMOB REFCURSOR;
</pre>

It doesn't work, when TYPE x is not created more lines before usage:
<pre>
TYPE TUceparhla IS REF CURSOR;
   qUceparhla TUceparhla;
   mRowUceparhla UCEPARHLA%ROWTYPE;
   mSqlUceparhla VARCHAR(4000);
   mID_UCEPARHLA UCEPARHLA.ID_UCEPARHLA%TYPE;


   --TYPE TUceparhla_new IS REF CURSOR;
   qUceparhla_new TUceparhla; -----<<< TUceparhla is used 2x
</pre>

PLpgSQL reports error:
<pre>
│ 884231 │ gen_ucecisrad             │           qUceparhla_new TUceparhla;
│ 884231 │ gen_ucecisrad             │ --                       ^
error:42704:type "tuceparhla" does not exist
</pre>
[gen_ucisrad.txt](https://github.com/darold/ora2pg/files/1047316/gen_ucisrad.txt)

**Comment by darold** [comment]
Ok much clear with this example. Commit a29ae79 might solve this issue.

**Comment by okbob** [comment]
It is fixed, thank you

**Comment by okbob** [comment]
I found another issues in triggers
<pre>
TRIGGER "IDES_JMMAJ".najpredp_AI
  after insert  on  najpredp 
  for each row



declare 
  mSqPolozky VARCHAR2( 4000 ) ;
  mNewPolozka NAJPOLOZ%ROWTYPE;
  TYPE TqPolozky IS REF CURSOR;
  qPolozky   TqPolozky;
  A1 CHAR(1);
  mDefLok    NAJPOLPAR.DEFLOK%TYPE; 
  mPouzito   NAJPOLPAR.POUZITO%TYPE;
  mMnozstvi  NAJPOLOZ.NAJPOC%TYPE;
  mUPRAV_HODNOTU_NAJPOC  RRRUTIL.T_UPRAV_HODNOTU_NAJPOC;
  mTYP CHAR(1);
 ...
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE FUNCTION public.trigger_fct_najpredp_ai()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  qPol RECORD;
  mSqPolozky varchar(4000 );
  mNewPolozka NAJPOLOZ;
  TYPE TqPolozky REFCURSOR;
  qPolozky   TqPolozky;
  A1 char(1);
  mDefLok    NAJPOLPAR.DEFLOK%TYPE;
  mPouzito   NAJPOLPAR.POUZITO%TYPE;
  mMnozstvi  NAJPOLOZ.NAJPOC%TYPE;
  mUPRAV_HODNOTU_NAJPOC  RRRUTIL.T_UPRAV_HODNOTU_NAJPOC;
  mTYP char(1);
</pre>

**Comment by darold** [comment]
Might be fixed with commit d72e64f.

**Comment by okbob** [comment]
It is fixed. Thank you
