### ISSUE TITLE
Broken query - DECODE

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#431]
Oracle:
<pre>
   --- pozor nutno korektne vyhodnotit saldo_NE (strana MD) saldo_ne_D (strana D)
      SELECT COUNT(*) INTO mPOCET_SALDO_NE
        FROM UCEVSALDOPOH MT, UCESALDOPOL A1 , UCEPOHYB A2
        WHERE MT.ID_UCESALDOPOH = qUCESALDOPOH.ID_UCESALDOPOH
          AND MT.ID_UCESALDOPOL = A1.ID_UCESALDOPOL
          AND A1.ID_UCEPOHYB = A2.ID_UCEPOHYB
          AND DECODE(A1.ID_CISUUCET,A2.ID_CISUUCET_MD,A2.SALDO_NE ,A2.SALDO_NE_D) = 'A' ;
</pre>

Ora2pg result:
<pre>
      --- pozor nutno korektne vyhodnotit saldo_NE (strana MD) saldo_ne_D (strana D)
      SELECT COUNT(*) INTO STRICT mPOCET_SALDO_NE
        FROM UCEVSALDOPOH MT, UCESALDOPOL A1 , UCEPOHYB A2
        WHERE MT.ID_UCESALDOPOH = qUCESALDOPOH.ID_UCESALDOPOH
          AND MT.ID_UCESALDOPOL = A1.ID_UCESALDOPOL
          AND A1.ID_UCEPOHYB = A2.ID_UCEPOHYB
          AND CASE WHEN A1.ID_CISUUCET=A2.ID_CISUUCET_MD THEN A2.SALDO_NE   ELSE A2.SALDO_NE_D END;'A';
</pre>

**Comment by darold** [comment]
Commit 04f9355 might fix this issue.

**Comment by okbob** [comment]
It is fixed. Thank you
