### ISSUE TITLE
Broken UPDATE (due DECODE) - missing WHERE keyword

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#432]
Oracle:
<pre>
CREATE OR REPLACE procedure IDES_JMMAJ.DEL_UCEUZA( mWhere IN VARCHAR2 , mLIDENT IN NUMBER , mTransakce IN CHAR  ) is
 TYPE TqUCEUZA IS REF CURSOR;
  qUCEUZA   TqUCEUZA;
  mSqlUceuza VARCHAR2( 4000 );
  mID_UCEUZA UCEUZA.ID_UCEUZA%TYPE;
  mUCEDOK_MAX UCEPOHYB.UCEDOK%TYPE;
  mAKT_CISLO UDRCISRAD.CISLO%TYPE;
  mUCEDOK_MIN UCEPOHYB.UCEKOD%TYPE;
  mID_UDRCISRAD UDRCISRAD.ID_UDRCISRAD%TYPE;
  mError VARCHAR2( 4000 );
  mTYP_ZAVERKY  UCEUZA.TYP_ZAVERKY%TYPE;
  mWhere_DEL VARCHAR2(4000);
  mPOCET_DOKLAD NUMBER;
  mID_CISUJEDN CISUJEDN.ID_CISUJEDN%TYPE;
  mOBDOBI_UCE UCEUZA.OBDOBI_UCE%TYPE;
  mID_UCEOBDOBI UCEOBDOBI.ID_UCEOBDOBI%TYPE;
  mPocet NUMBER;
  mProvest boolean;
  mPOCET_UCEUZA NUMBER;
  mDATVYR UCEUZA.DATVYR%TYPE;
  mPOCET_UZA_PREHOZ_STARSI NUMBER;
  mPOCET_UCEPOHYB NUMBER;
  mOK CHAR(1);
begin

  IF mWhere IS NOT NULL THEN
    mSqlUceuza := ' SELECT ID_UCEUZA , TYP_ZAVERKY , ID_CISUJEDN , OBDOBI_UCE FROM V_UCEUZA MT WHERE ' || mWhere ;
  ELSE
    mSqlUceuza := ' SELECT ID_UCEUZA , TYP_ZAVERKY , ID_CISUJEDN , OBDOBI_UCE FROM V_UCEUZA MT WHERE ID_UCEUZA  = -1 ';
  END IF;

  IF mTransakce = 'A' THEN
   SET TRANSACTION READ WRITE;
  END IF;

  OPEN qUCEUZA FOR mSqlUceuza ;
  LOOP
    FETCH qUCEUZA INTO mID_UCEUZA,mTYP_ZAVERKY,mID_CISUJEDN,mOBDOBI_UCE ;
    EXIT WHEN qUCEUZA%NOTFOUND;

      mPocet := 0;

      IF mID_CISUJEDN IS NOT NULL THEN
        BEGIN

          SELECT ID_UCEOBDOBI INTO mID_UCEOBDOBI
            FROM UCEOBDOBI
            WHERE ID_CISUJEDN = mID_CISUJEDN
              AND OBDOBI_OD <= mOBDOBI_UCE
              AND OBDOBI_DO >= mOBDOBI_UCE ;

          SELECT COUNT(*) INTO mPocet
             FROM UCEZAMOBO
             WHERE ID_UCEOBDOBI = mID_UCEOBDOBI
               AND ZAMEK_OD <= mOBDOBI_UCE
               AND ZAMEK_DO >= mOBDOBI_UCE;

        EXCEPTION
          WHEN OTHERS THEN
            mPocet := 1;
            IF mTYP_ZAVERKY = 'PREHOZY' THEN
              IF mOBDOBI_UCE = '01.01.1970' THEN
                mPocet := 0;
              END IF;
            END IF;
        END;
      END IF;

    IF mPocet > 0 THEN
      UPDATE UCEUZA
       SET POZNAMKA = 'OBDOBI JE UZAMCENE'
       WHERE ID_UCEUZA = mID_UCEUZA;
    END IF;

    IF mPocet = 0 THEN

      IF mTYP_ZAVERKY IS NULL THEN

        BEGIN
        SELECT MAX(UCEDOK) ,MIN(UCEDOK), MAX(ID_UDRCISRAD)
          INTO mUCEDOK_MAX , mUCEDOK_MIN , mID_UDRCISRAD
          FROM UCEPOHYB
          WHERE ID_UCEUZA = mID_UCEUZA;
          EXCEPTION
          WHEN NO_DATA_FOUND THEN
            mUCEDOK_MAX := NULL;
            mUCEDOK_MIN := NULL;
            mID_UDRCISRAD := NULL;
        END ;

        BEGIN
        SELECT CISLO INTO mAKT_CISLO
          FROM UDRCISRAD
          WHERE ID_UDRCISRAD = mID_UDRCISRAD;
          EXCEPTION
          WHEN NO_DATA_FOUND THEN
            mAKT_CISLO := NULL;
        END ;

        IF ( mUCEDOK_MAX + 1 ) = mAKT_CISLO THEN
          UPDATE UDRCISRAD
            SET CISLO = mUCEDOK_MIN
            WHERE ID_UDRCISRAD = mID_UDRCISRAD;
          DELETE FROM UCEUZA WHERE ID_UCEUZA = mID_UCEUZA;

        ELSE
          SELECT COUNT(*) INTO mPOCET_UCEUZA
            FROM UCEPOHYB WHERE ID_UCEUZA = mID_UCEUZA;
          IF mPOCET_UCEUZA = 0 THEN
             DELETE FROM UCEUZA WHERE ID_UCEUZA = mID_UCEUZA;
          END IF;
        END IF;

        IF mAKT_CISLO is NULL and  mID_UDRCISRAD is NULL
           and mUCEDOK_MIN is NULL and  mID_UDRCISRAD is NULL  THEN
                DELETE FROM UCEUZA WHERE ID_UCEUZA = mID_UCEUZA;
        END IF;

        IF mTransakce = 'A' THEN
          COMMIT;
          SET TRANSACTION READ WRITE;
        END IF;
      ELSE
        IF mTYP_ZAVERKY = 'VYNAKUCE' THEN
           UPDATE VYNAKUCE
             SET UCEMES = NULL,
                 ID_UCEUZA = NULL
             WHERE ID_UCEUZA = mID_UCEUZA;
           DELETE FROM UCEUZA WHERE ID_UCEUZA = mID_UCEUZA;
        END IF;

        IF mTYP_ZAVERKY = 'PREHOZY' THEN
         SELECT DATVYR INTO mDATVYR
           FROM UCEUZA
           WHERE ID_UCEUZA = mID_UCEUZA;

          SELECT COUNT(*) INTO mPOCET_UZA_PREHOZ_STARSI
           FROM UCEUZA
            WHERE ID_CISUJEDN = mID_CISUJEDN
              AND TYP_ZAVERKY = 'PREHOZY'
              AND DATVYR > mDATVYR
              AND ROWNUM < 2;

          IF mPOCET_UZA_PREHOZ_STARSI = 0 THEN

            SELECT COUNT(*) INTO mPOCET_UCEPOHYB
              FROM UCEPOHYB
              WHERE ID_UCEUZA = mID_UCEUZA;

            IF mPOCET_UCEPOHYB = 0 THEN
              UPDATE NAJPLATBY
                SET ID_UCEUZA = NULL,
                    UCEUZA = DECODE(UCEUZA,TO_DATE('01.01.1970','DD.MM.YYYY'), NULL , UCEUZA )
                WHERE ID_UCEUZA = mID_UCEUZA;
              UPDATE NAJVPLAPRE
                SET ID_UCEUZA = NULL,
                    ID_UCEUZA_STORNO = NULL,
                    UCEUZA = DECODE(UCEUZA,TO_DATE('01.01.1970','DD.MM.YYYY'), NULL , UCEUZA ),
                    UCEUZA_STORNO = DECODE(UCEUZA_STORNO,TO_DATE('01.01.1970','DD.MM.YYYY'), NULL , UCEUZA_STORNO )
                WHERE ID_UCEUZA = mID_UCEUZA;
              UPDATE NAJVPLAPRE
                SET ID_UCEUZA_STORNO = NULL,
                    UCEUZA_STORNO = DECODE(UCEUZA_STORNO,TO_DATE('01.01.1970','DD.MM.YYYY'), NULL , UCEUZA_STORNO )
                WHERE ID_UCEUZA_STORNO = mID_UCEUZA;

                DELETE FROM UCEUZA WHERE ID_UCEUZA = mID_UCEUZA;
              ELSE
                raise_application_error( -20010,'EXISTUJE UCETNI ZAPIS' );

              END IF;

           ELSE
            raise_application_error( -20010,'EXISTUJI STARSI PREHOZY' );

           END IF;

        ELSE
          IF mTYP_ZAVERKY = 'VYNAKUCE' THEN
            mOK := 'A';
          ELSE
            IF mTYP_ZAVERKY = 'POKLADNA' THEN
              mWhere_DEL := ' EXISTS ( SELECT  A1.ID_UCEHLAPOK FROM UCEDOKLAD A1 WHERE MT.ID_UCEHLAPOK = A1.ID_UCEHLAPOK AND  A1.ID_UCEUZA = ' || mID_UCEUZA || ' ) ' ;
            END IF;

            IF mTYP_ZAVERKY = 'BANKA' THEN
              mWhere_DEL := ' EXISTS ( SELECT  A1.ID_UCEHLABAN FROM UCEDOKLAD A1 WHERE MT.ID_UCEHLABAN = A1.ID_UCEHLABAN AND  A1.ID_UCEUZA = ' || mID_UCEUZA || ' ) ' ;
            END IF;

            IF mTYP_ZAVERKY = 'FAKTURY' THEN
              mWhere_DEL := ' MT.ID_UCEHLAFAK IN  ( SELECT  A1.ID_UCEHLAFAK FROM UCEDOKLAD A1 WHERE  A1.ID_UCEUZA = ' || mID_UCEUZA || ' ) ' ;
            END IF;

            ZRUS_NEW_UCEPOLOZKY_FAK(  mWhere_DEL   , 'N'  , mError  , mLIDENT , mTYP_ZAVERKY  );
            SELECT COUNT(*) INTO mPOCET_DOKLAD
                FROM UCEDOKLAD
                WHERE ID_UCEUZA = mID_UCEUZA;
            IF mPOCET_DOKLAD = 0 THEN
              DELETE FROM UCEUZA WHERE ID_UCEUZA = mID_UCEUZA;
            END IF;
          END IF;
        END IF;
      END IF;
      IF mTransakce = 'A' THEN
        COMMIT;
        SET TRANSACTION READ WRITE;
      END IF;
    END IF;

  END LOOP;

  IF mTransakce = 'A' THEN
   COMMIT;
  END IF;

end DEL_UCEUZA;
</pre>

Broken PLpgSQL part:
<pre>
163                 IF mPOCET_UCEPOHYB = 0 THEN
164                   UPDATE NAJPLATBY
165                     SET ID_UCEUZA  = NULL,
166                         UCEUZA = CASE WHEN UCEUZA=TO_DATE('01.01.1970','DD.MM.YYYY') THEN  NULL   ELSE UCEUZA END
167     ;ID_UCEUZA = mID_UCEUZA;
168                   UPDATE NAJVPLAPRE
169                     SET ID_UCEUZA  = NULL,
170                         ID_UCEUZA_STORNO  = NULL,
171                         UCEUZA = CASE WHEN UCEUZA=TO_DATE('01.01.1970','DD.MM.YYYY') THEN  NULL   ELSE UCEUZA END ,
172                         UCEUZA_STORNO = CASE WHEN UCEUZA_STORNO=TO_DATE('01.01.1970','DD.MM.YYYY') THEN  NULL   ELSE UCEUZA_STORNO END
173     ;ID_UCEUZA = mID_UCEUZA;
174                   UPDATE NAJVPLAPRE
175                     SET ID_UCEUZA_STORNO  = NULL,
176                         UCEUZA_STORNO = CASE WHEN UCEUZA_STORNO=TO_DATE('01.01.1970','DD.MM.YYYY') THEN  NULL   ELSE UCEUZA_STORNO END
177     ;ID_UCEUZA_STORNO = mID_UCEUZA;
178     
179                     DELETE FROM UCEUZA WHERE ID_UCEUZA = mID_UCEUZA;
180                   ELSE
181                     RAISE EXCEPTION '%', 'EXISTUJE UCETNI ZAPIS'  USING ERRCODE = -20010;
182     
183     
184                   END IF;
</pre>

**Comment by darold** [comment]
Fixed by commit e2cf22a.

**Comment by okbob** [comment]
It is fixed. Thank you
