### ISSUE TITLE
Strange EXIT WHEN command

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#433]
Original:
<pre>
    OPEN qNajdatsplt FOR mSql ;
    LOOP
      FETCH qNajdatsplt INTO mID_NAJDATSPLT , mID_PREDPIS ,  mOBDOBI_OD, mOBDOBI_DO, mPORADI , mPREDEPSANO,mZAPLACENO,mPOCET_SPLAT,mPORADI_SPLAT,mPOHL_VE_SPLATKACI,mROZEPIS_PLATBU , mID_NAJDATSPLT_POHL ;
      EXIT WHEN qNajdatsplt%NOTFOUND;
      EXIT WHEN mRecNajplatby.ENEURCENO = 0 ;
</pre>

Translation:
<pre>
    OPEN qNajdatsplt FOR EXECUTE mSql;
    LOOP
      FETCH qNajdatsplt INTO mID_NAJDATSPLT , mID_PREDPIS ,  mOBDOBI_OD, mOBDOBI_DO, mPORADI , mPREDEPSANO,mZAPLACENO,mPOCET_SPLAT,mPORADI_SPLAT,
mPOHL_VE_SPLATKACI,mROZEPIS_PLATBU , mID_NAJDATSPLT_POHL;
      EXIT WHEN NOT FOUND; /* apply on qNajdatsplt */
      EXIT WHEN NOT FOUND; /* apply on mRecNajplatby.ENEURCENO = 0;
</pre>
Last row is wrong. There was not reason be modified, more broken comment is there

Another fragment from same procedure:
<pre>
      OPEN qNajpoloz FOR mSqlPolozky ;
      LOOP
        FETCH qNajpoloz INTO mID_POL_PRED ,  mID_NAJPROS , mID_POLONAJ , mPredepsanoPol , mZNAMENKO , mZaplacenoPol ;
        EXIT WHEN qNajpoloz%NOTFOUND;
</pre>

Translation:
<pre>
      OPEN qNajpoloz FOR EXECUTE mSqlPolozky;
      LOOP
        FETCH qNajpoloz INTO mID_POL_PRED ,  mID_NAJPROS , mID_POLONAJ , mPredepsanoPol , mZNAMENKO , mZaplacenoPol;
        EXIT WHEN qNajpoloz */
</pre>

Original source code attached
[rozpis_platby.txt](https://github.com/darold/ora2pg/files/1034295/rozpis_platby.txt)

**Comment by darold** [comment]
Commit 891835d might fix the issue.

**Comment by okbob** [comment]
It is fixed. Thank you
