### ISSUE TITLE
DBD::Oracle::db prepare failed: ORA-00942 error

### ISSUE THREAD

**Issue by karurmohan** [darold/ora2pg#434]
Hi,
         I am facing the following error, i could able to successfully connect schema "X" & migrating postgres script from oracle. When i tried to point to another schema "Y" (both "X & Y" having same DSN) using the same configuration plan shows following error. I have done change 1) user name & password under "# Set Oracle database connection::", 2) Schema Name of Oracle Source  # Oracle schema/owner to use::  SCHEMA ". Please, do clarify or give suggestion to fix it. Thanks!

DBD::Oracle::db prepare failed: ORA-00942: table or view does not exist (DBD ERR
OR: error possibly near <*> indicator at char 51 in 'SELECT DISTINCT OBJECT_NAME
,OWNER,OBJECT_TYPE FROM <*>DBA_OBJECTS WHERE (OBJECT_TYPE = 'FUNCTION' OR OBJECT
_TYPE = 'PROCEDURE' OR  OBJECT_TYPE = 'PACKAGE BODY') AND STATUS='VALID' AND OWN
ER = 'PEDM_DEV' ORDER BY OBJECT_NAME') at C:/Perl64/site/lib/Ora2Pg.pm line 9258
.
FATAL: ORA-00942: table or view does not exist (DBD ERROR: error possibly near <
*> indicator at char 51 in 'SELECT DISTINCT OBJECT_NAME,OWNER,OBJECT_TYPE FROM <
*>DBA_OBJECTS WHERE (OBJECT_TYPE = 'FUNCTION' OR OBJECT_TYPE = 'PROCEDURE' OR  O
BJECT_TYPE = 'PACKAGE BODY') AND STATUS='VALID' AND OWNER = 'PEDM_DEV' ORDER BY
OBJECT_NAME')
Aborting export...

**Comment by darold** [comment]
Hi,

The problem is that the login user doesn't have DBA privilege. You need to enable USER_GRANTS in ora2pg.conf.

**Comment by karurmohan** [comment]
Excellent! It Works now after enabling "USER_GRANTS". Thanks for quick response.
