### ISSUE TITLE
Error when generating report

### ISSUE THREAD

**Issue by adrianboangiu** [darold/ora2pg#435]
Hello,

I am trying to do a report with the usual command line:
ora2pg -t SHOW_REPORT -c .\config\ora2pg.conf --dump_as_html --estimate_cost > .\reports\report.html
The version Oracle database is 12.1.0.2
After several hours I get this error:
DBD::Oracle::db prepare failed: ORA-00604: error occurred at recursive SQL level 1
FATAL: ORA-00604: error occurred at recursive SQL level 1 ORA-08177: can't serialize access for this transaction (DBD ERROR: error possibly near <*> indicator at char 57 in 'SELECT A.TABLE_NAME,A.COMMENTS,A.TABLE_TYPE,A.OWNER FROM <*>ALL_TAB_COMMENTS A, ALL_OBJECTS O WHERE A.OWNER=O.OWNER and A.TABLE_NAME=O.OBJECT_NAME and O.OBJECT_TYPE='VIEW' AND A.OWNER='COSWIN' AND ( NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^USLOG\$_.*$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^MLOG\$_.*$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^RUPD\$_.*$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^MDXT_.*$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^MDRT_.*$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^MDRS_.*$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^DR\$.*$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^CLI_SWP\$.*$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^LOGMNR\$.*$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^REPCAT\$.*$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^JAVA\$.*$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^AQ\$.*$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^BIN\$.*$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SDO_GR_.*$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^.*\$JAVA\$.*$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^PROF\$.*$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^TOAD_PLAN_.*$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SYS_.*\$$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^EVT_CARRIER_CONFIGURATION$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^EVT_DEST_PROFILE$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^EVT_HISTORY$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^EVT_INSTANCE$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^EVT_MAIL_CONFIGURATION$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^EVT_MONITOR_NODE$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^EVT_NOTIFY_STATUS$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^EVT_OPERATORS$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^EVT_OPERATORS_ADDITIONAL$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^EVT_OPERATORS_SYSTEMS$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^EVT_OUTSTANDING$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^EVT_PROFILE$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^EVT_PROFILE_EVENTS$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^EVT_REGISTRY$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^EVT_REGISTRY_BACKLOG$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^OLS_DIR_BUSINESSE$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^OLS_DIR_BUSINESSES$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SDO_COORD_REF_SYS$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SDO_CS_SRS$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SDO_INDEX_METADATA_TABLE$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SDO_INDEX_METADATA_TABLES$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SDO_PC_BLK_TABLE$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SDO_STYLES_TABLE$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SDO_TIN_BLK_TABLE$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMACTUALPARAMETER_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMGLOBALCONFIGURATION_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMFORMALPARAMETER_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMFOLDER_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMDISTRIBUTIONSET_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMDEPENDENTLINKS$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMDEPENDENTINDEX$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMDEPENDEEINDEX$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMDEFAUTH_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMDBAUTH_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMPARALLELJOB_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMPACKAGE_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMOWNERLINKS$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMOWNERINDEX$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMOWNEEINDEX$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMOSNAMES_X$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMOMSTRING_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMMOWNERLINKS$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMMOWNERINDEX$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMPACKAGE_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMPARALLELJOB_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMPARALLELOPERATION_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMPARALLELSTATEMENT_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMPRODUCT_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_AD_ADDRESSES_$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_AD_DISCOVERED_NODES_$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_AD_NODES_$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_AD_PARMS_$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_AUTO_DISCOVERY_ITEM_$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_AUTO_DISCOVERY_PARMS_$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_BLOB_$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_CREDENTIALS\$$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_JOB_$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_JOB_EVENTLIST_$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_JOB_HISTORY_$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_JOB_INSTANCE_$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_JOB_LIBRARY_$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_JOB_TASK_INSTANCE_$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_LONG_TEXT_$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_REP_VERSION$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_SERVICES$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_SERVICE_GROUP_DEFN_$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_SERVICE_GROUP_ITEM_$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_SERVICE_ITEM_$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_UPDATESERVICES_CALLED_$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMAGENTJOB_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMARCHIVE_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMBREAKABLELINKS$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMCLIQUE$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMCONFIGURATION$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMCONSOLESOSETTING_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMDATABASE_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMHOSTAUTH_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMHOST_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMINSTALLATION_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMLOGMESSAGE_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMMONTHLYENTRY_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMMONTHWEEKENTRY_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMP_USER_DETAILS$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMRELEASE_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMRUN_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMSCHEDULE_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMSHAREDORACLECLIENT_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMSHAREDORACLECONFIGURATION_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMTABLESPACE_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMVCENDPOINT_S$') AND NOT REGEXP_LIKE(UPPER(A.TABLE_NAME),'^SMWEEKLYENTRY_S$'))')

**Comment by darold** [comment]
Try to set TRANSACTION to readonly in your ora2pg.conf file. The default serializable can be used only with data export.
