### ISSUE TITLE
Question:  Why is everything soooo much faster, especially packages.

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#437]
Packages that used to take 2-3 hours finish in a few minutes now.

**Comment by darold** [comment]
I don't know if the translation output is the same as before and from which time/commit it was taking 2/3 hours to perform the package export but there was several improvement the last weeks especially with Pavel's reports. But you have also reported slow performances on view export, is it still the same?

**Comment by MichaelDBA** [comment]
The views screamed by as well.

**Comment by MichaelDBA** [comment]
oh boy, I got too excited.  some of them still take a couple hours, but other ones seem faster.

**Comment by MichaelDBA** [comment]
I got a schema with 51 packages and it took 8.5 hours to complete.  Can package manipulation be optimized for performance in any way?  I gathererd stats at the database and schema level before I commenced, and I got 6GB RAM devoted to sga_target.

**Comment by darold** [comment]
If you have enough cpu at your disposition you can use multiprocess by using -j option or JOBS configuration directive.

**Comment by MichaelDBA** [comment]
OK thanks.
