### ISSUE TITLE
COPY command returns non zero exit code

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#438]
I am running a copy command and it always returns an exitcode of 2.  What does that mean?

The only error I get is this:
`WARNING: an error occurs during data export. Please check what's happen.`

Interesting...  This seems to happen only when I have multiple ora2pg jobs running at the same time.  It does not happen if I execute ora2pg sequentially not concurrently.  We have multiple schemas and we attempt to run ora2pg at the same time for a few of the schemas.

**Comment by darold** [comment]
Maybe you have one parallel process that is killed by the OOM killer, have a look to the dmesg output.

**Comment by MichaelDBA** [comment]
Ok, let me keep this open til I investigate that,
