### ISSUE TITLE
Tool to automate schema discovery

### ISSUE THREAD

**Issue by frost242** [darold/ora2pg#439]
Hello,

ora2pg_scanner is quite handy is the schema to explore are known. Sometimes it's not the case and one has to run ora2pg first to discover the schema of an Oracle instance, then build the CSV file with the collected informations.
It would be interesting to add a tool like ora2pg_discover that will automate this part. You provide a CSV file with the following content : SID, server, port, user, password, audit_user
Then ora2pg_discover builds the schema list and runs ora2pg in report mode.

Thoughts ?

**Comment by frost242** [comment]
Of course, I have some code on my machine now, don't write anything. I'll send it to you if you feel the need for it.

**Comment by darold** [comment]
Hi Thomas,

Yes this is one of the things I wanted to do. My thought was to use the same syntax as usual in server list file but keep empty the schema field. In this case ora2pg_scanner will first extract all schema of the instance and then perform a migration assessment of all schema found. In test mode (-t) with an output file ora2pg_scanner  will generate a new server list file with one line by schema found.

If you can implement it that way I will be please to apply the pull request.

**Comment by frost242** [comment]
Thanks for your answer Gilles. I'll do it this way.

**Comment by frost242** [comment]
PR #486 should do the job.

**Comment by darold** [comment]
Thanks a lot Thomas, commit 7f6558d fixes some issues in your PR.
