### ISSUE TITLE
Unwanted new line breaks syntax

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#441]
The fragment:
<pre>
                       IF mRecNAJPARPRE.mID_CISUJEDN IS NOT NULL THEN
                          ---SELECT  /*+ ORDERED */ * INTO RRRUTIL.G_PARAMETRY_PREDPIS
                          SELECT  /*+ ORDERED */ * INTO mG_PARAMETRY_PREDPIS
                            FROM V_PARAM_PREDPIS MT
                            WHERE ID_NAJPROS = mRecNAJPARPRE.mId_Najpros
                              AND ID_CISUJEDN = mRecNAJPARPRE.mID_CISUJEDN
                              ---AND ID_SKUTPRS = mRecNAJPARPRE.mId_SKUTPRS
                              ---AND ID_CTYPPRED = mRecNAJPARPRE.mID_CTYPPRED
                              AND ID_DRUPRE = mRecNAJPARPRE.mID_DRUPRE
                              AND ID_CISPREDVZT = mRecNAJPARPRE.mID_CISPREDVZT
                              ---AND ( NAJVPARPRL_OD <= mRecNAJPARPRE.mOBDOBI_OD AND NAJVPARPRL_DO >= mRecNAJPARPRE.mOBDOBI_OD )
                              ---AND ( NAJVPARVZT_OD <= mRecNAJPARPRE.mOBDOBI_OD AND NAJVPARVZT_DO >= mRecNAJPARPRE.mOBDOBI_OD )
                              ---AND ( NAJVPREPSK_OD <= mRecNAJPARPRE.mOBDOBI_OD AND NAJVPREPSK_DO >= mRecNAJPARPRE.mOBDOBI_OD )
                              AND ( PLATNOST_OD <= mRecNAJPARPRE.mOBDOBI_OD AND PLATNOST_DO >= mRecNAJPARPRE.mOBDOBI_OD ) ;
                         ELSE
</pre>
Is unhappily translated to
<pre>
                       IF mRecNAJPARPRE.mID_CISUJEDN IS NOT NULL THEN
                          ---SELECT  /*+ ORDERED */
 * INTO RRRUTIL.G_PARAMETRY_PREDPIS
                          SELECT  /*+ ORDERED */
 * INTO STRICT mG_PARAMETRY_PREDPIS
                            FROM V_PARAM_PREDPIS MT
                            WHERE ID_NAJPROS = mRecNAJPARPRE.mId_Najpros
                              AND ID_CISUJEDN = mRecNAJPARPRE.mID_CISUJEDN
                              ---AND ID_SKUTPRS = mRecNAJPARPRE.mId_SKUTPRS
                              ---AND ID_CTYPPRED = mRecNAJPARPRE.mID_CTYPPRED
                              AND ID_DRUPRE = mRecNAJPARPRE.mID_DRUPRE
                              AND ID_CISPREDVZT = mRecNAJPARPRE.mID_CISPREDVZT
                              ---AND ( NAJVPARPRL_OD <= mRecNAJPARPRE.mOBDOBI_OD AND NAJVPARPRL_DO >= mRecNAJPARPRE.mOBDOBI_OD )
                              ---AND ( NAJVPARVZT_OD <= mRecNAJPARPRE.mOBDOBI_OD AND NAJVPARVZT_DO >= mRecNAJPARPRE.mOBDOBI_OD )
                              ---AND ( NAJVPREPSK_OD <= mRecNAJPARPRE.mOBDOBI_OD AND NAJVPREPSK_DO >= mRecNAJPARPRE.mOBDOBI_OD )
                              AND ( PLATNOST_OD <= mRecNAJPARPRE.mOBDOBI_OD AND PLATNOST_DO >= mRecNAJPARPRE.mOBDOBI_OD );
</pre>

**Comment by darold** [comment]
Commit 4c3c113 fixes this issue in this particular case by removing all hints before parsing the query.

**Comment by okbob** [comment]
There can be any comment - not only hints - we used similar technique for assignment of slow queries and some process data.

**Comment by okbob** [comment]
It is fixed, thank you
