### ISSUE TITLE
Unwanted semicolon instead comma breaks query

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#442]
<pre>
CREATE OR REPLACE function IDES_JMMAJ.UCEVFAKVYU_PREDKONTACE
 (
  mID_UCEPOLFAK IN UCEPOLFAK.ID_UCEPOLFAK%TYPE,
  mID_UCEPOLBAN IN UCEPOLBAN.ID_UCEPOLBAN%TYPE,
  mID_UCEPOLPOK IN UCEPOLPOK.ID_UCEPOLPOK%TYPE,
  mID_UCEPOHYB IN UCEPOHYB.ID_UCEPOHYB%TYPE,
  ZN IN CHAR
  )

  return varchar2 is
  Result varchar2(200);

  mID_UCEPARPOL UCEPARPOL.ID_UCEPARPOL%TYPE;
  mNAZEV VARCHAR2(200);
  mUCET_D CISUUCET.KOD_CISUCET%TYPE;
  mUCET_MD CISUUCET.KOD_CISUCET%TYPE;
  mUCET_ZAKDPH_D CISUUCET.KOD_CISUCET%TYPE;
  mUCET_ZAKDPH_MD CISUUCET.KOD_CISUCET%TYPE;
  mUCET_DPH_D CISUUCET.KOD_CISUCET%TYPE;
  mUCET_DPH_MD CISUUCET.KOD_CISUCET%TYPE;
  mKOD_CISDRUHPRA CISDRUHPRA.KOD_POPIPR%TYPE;

begin
  RESULT := NULL;
  mID_UCEPARPOL := NULL;
  --- faktura
  if mID_UCEPOLFAK is not NULL then
    SELECT ID_UCEPARPOL INTO mID_UCEPARPOL
    FROM UCEPOLFAK MT
    WHERE MT.ID_UCEPOLFAK = mID_UCEPOLFAK
    AND rownum < 2;
  end if;
  --- pokladna
  if mID_UCEPOLPOK is not NULL then
    SELECT ID_UCEPARPOL INTO mID_UCEPARPOL
    FROM UCEPOLPOK MT
    WHERE MT.ID_UCEPOLPOK = mID_UCEPOLPOK
    AND rownum < 2;
  end if;
  --- banka
  if mID_UCEPOLBAN is not NULL then
    SELECT ID_UCEPARPOL INTO mID_UCEPARPOL
    FROM UCEPOLBAN MT
    WHERE MT.ID_UCEPOLBAN = mID_UCEPOLBAN
    AND rownum < 2;
  end if;

  --- ucepohyb
  if mID_UCEPOHYB is not NULL then
    SELECT ID_UCEPARPOL INTO mID_UCEPARPOL
    FROM UCEPOHYB MT
    WHERE MT.ID_UCEPOHYB = mID_UCEPOHYB
    AND rownum < 2;
  end if;
  IF mID_UCEPARPOL IS NOT NULL THEN
      select
             --DECODE(A31.ID_CISDPH,'',A25.KOD_CISUCET ,'DPH') AS UCET_D,
             CASE WHEN A31.ID_CISDPH IS NULL THEN A25.KOD_CISUCET   ELSE 'DPH' END UCET_D,
             --DECODE(A31.ID_CISDPH,'',A26.KOD_CISUCET ,'DPH') AS UCET_MD,
             CASE WHEN A31.ID_CISDPH IS NULL THEN A26.KOD_CISUCET   ELSE 'DPH' END UCET_MD,
             A27.KOD_CISUCET AS UCET_ZAKDPH_D,
             A28.KOD_CISUCET AS UCET_ZAKDPH_MD,
             A29.KOD_CISUCET AS UCET_DPH_D,
             A30.KOD_CISUCET AS UCET_DPH_MD,
             A32.J1_NAZEV,
             A32.KOD_POPIPR AS KOD_CISDRUHPRA
             into
             mUCET_D,
             mUCET_MD,
             mUCET_ZAKDPH_D,
             mUCET_ZAKDPH_MD,
             mUCET_DPH_D,
             mUCET_DPH_MD,
             mNAZEV,
             mKOD_CISDRUHPRA
          from
             UCEPARPOL  A31,
             CISUUCET   A25, CISUUCET A26,
             CISUUCET   A27, CISUUCET A28,
             CISUUCET   A29, CISUUCET A30,
             CISDRUHPRA A32
      where  A31.ID_UCEPARPOL=mID_UCEPARPOL AND
             A31.ID_CISUUCET_D = A25.ID_CISUUCET(+) AND
             A31.ID_CISUUCET_MD = A26.ID_CISUUCET(+) AND
             A31.ID_CISUUCET_D0 = A27.ID_CISUUCET(+) AND
             A31.ID_CISUUCET_MD0 = A28.ID_CISUUCET(+) AND
             A31.ID_CISUUCET_D5 = A29.ID_CISUUCET(+) AND
             A31.ID_CISUUCET_MD5 = A30.ID_CISUUCET(+) AND
             A31.ID_CISDRUHPRA = A32.ID_CISDRUHPRa(+) ;
  -- zn='P' --- popis predkontace
       if Trim(ZN) = 'P' and  mNAZEV is not null then
           Result:=mNAZEV;
       end if;
  -- zn='M' --- Ucet MD
       if Trim(ZN) = 'M' and  mUCET_MD is not null and TRIM(mUCET_MD)<>'DPH' then
            Result:=mUCET_MD;
       end if;
       if Trim(ZN) = 'M' and  mUCET_MD is not null and TRIM(mUCET_MD)='DPH' and mUCET_ZAKDPH_MD is not null then
            Result:=mUCET_ZAKDPH_MD;
       end if;
      if Trim(ZN) = 'M' and  mUCET_MD is null and mUCET_ZAKDPH_MD is not null then
            Result:=mUCET_ZAKDPH_MD;
       end if;
  -- zn='D' --- Ucet D
       if Trim(ZN) = 'D' and  mUCET_D is not null and TRIM(mUCET_D)<>'DPH' then
            Result:=mUCET_D;
       end if;
       if Trim(ZN) = 'D' and  mUCET_D is not null and TRIM(mUCET_D)='DPH' and mUCET_ZAKDPH_D is not null then
            Result:=mUCET_ZAKDPH_D;
       end if;
      if Trim(ZN) = 'D' and  mUCET_D is null and mUCET_ZAKDPH_D is not null then
            Result:=mUCET_ZAKDPH_D;
       end if;
  END IF; ---- mID_UCEPARPOL

    --- UCEPOHYB - skutecny ucty
    if mID_UCEPOHYB IS NOT NULL  THEN
       select TRIM(B1.kod_cisucet) AS UCET_MD ,
              TRIM(B2.kod_cisucet)AS UCET_D,
              'ZAUCTOVANO' AS PREDKONTACE
        into
             mUCET_MD,
             mUCET_D,
             mNAZEV
       from ucepohyb MT ,cisuucet B1, cisuucet B2
       where MT.ID_CISUUCET_MD =B1.ID_CiSUUCET(+)
        and  MT.ID_CISUUCET_D =B2.ID_CiSUUCET(+)
        and  MT.ID_UCEPOHYB = mID_UCEPOHYB;

       -- zn='P' --- popis predkontace
       if Trim(ZN) = 'P' and  mNAZEV is not null then
           Result:=mNAZEV;
       end if;
       -- zn='M' --- Ucet MD
       if Trim(ZN) = 'M' and  mUCET_MD is not null  then
            Result:=mUCET_MD;
       end if;
       -- zn='D' --- Ucet D
       if Trim(ZN) = 'D' and  mUCET_D is not null then
            Result:=mUCET_D;
       end if;
    end if;--- mid_ucepohyb<>0

  return(Result);
end UCEVFAKVYU_PREDKONTACE;
</pre>

The query:
<pre>
      select
             --DECODE(A31.ID_CISDPH,'',A25.KOD_CISUCET ,'DPH') AS UCET_D,
             CASE WHEN A31.ID_CISDPH IS NULL THEN A25.KOD_CISUCET   ELSE 'DPH' END UCET_D,
             --DECODE(A31.ID_CISDPH,'',A26.KOD_CISUCET ,'DPH') AS UCET_MD,
             CASE WHEN A31.ID_CISDPH IS NULL THEN A26.KOD_CISUCET   ELSE 'DPH' END UCET_MD,
             A27.KOD_CISUCET AS UCET_ZAKDPH_D,
</pre>
is translated to:
<pre>
      select
             --DECODE(A31.ID_CISDPH,'',A25.KOD_CISUCET ,'DPH') AS UCET_D,
             CASE WHEN A31.ID_CISDPH IS NULL THEN A25.KOD_CISUCET   ELSE 'DPH' END;             --DECODE(A31.ID_CISDPH,'',A26.KOD_CISUCET ,'DPH') AS UCET_MD,
             CASE WHEN A31.ID_CISDPH IS NULL THEN A26.KOD_CISUCET   ELSE 'DPH' END;A27.KOD_CISUCET AS UCET_ZAKDPH_D,
</pre>

**Comment by darold** [comment]
Fixed in commit 2f468ce.

**Comment by okbob** [comment]
It is fixed, thank you
