### ISSUE TITLE
ERROR:  invalid input syntax for integer: ""

### ISSUE THREAD

**Issue by ricdba** [darold/ora2pg#443]
HI,

  I'm converting an Oracle 11g database to postgresql 9.6 and I get the following error when I export only the structure of the tables:

   ERROR:  invalid input syntax for integer: ""

   This error occurs when it tries to create a table with the following command:

   CREATE TABLE he_headend (
rmaintst(#         id bigint,
rmaintst(#         adminregion_id smallint,
rmaintst(#         headend varchar(1020),
rmaintst(#         facility varchar(1020) DEFAULT '',
rmaintst(#         f_comments varchar(4000) DEFAULT '',
rmaintst(#         addressid bigint DEFAULT 0,
rmaintst(#         f_techid bigint,
rmaintst(#         sop integer DEFAULT '',
rmaintst(#         dateserver timestamp DEFAULT CURRENT_TIMESTAMP,
rmaintst(#         rpatcodeassignment char(4),
rmaintst(#         user_id bigint,
rmaintst(#         deleted smallint DEFAULT 0,
rmaintst(#         dateclient timestamp
rmaintst(# ) ;
ERROR:  invalid input syntax for integer: ""
rmaintst=# 

     Any idea how to solve this problem?

  Thanks,

  Ricardo

**Comment by darold** [comment]
Please post the DDL of the original table in Oracle, the problem comes from `sop integer DEFAULT '',` but I need to know what is original declaration of this column.

**Comment by ricdba** [comment]
Hi Darold,

    The original DDL in oracle is :

   CREATE TABLE ADMIN_.HE_HEADEND
(
  ID                  NUMBER(10),
  ADMINREGION_ID      NUMBER(3),
  HEADEND             VARCHAR2(255 CHAR),
  FACILITY            VARCHAR2(255 CHAR)        DEFAULT '',
  F_COMMENTS          VARCHAR2(4000 BYTE)       DEFAULT '',
  ADDRESSID           NUMBER(10)                DEFAULT 0,
  F_TECHID            NUMBER(10),
  SOP                 NUMBER(5)                 DEFAULT '',
  DATESERVER          TIMESTAMP(6)              DEFAULT CURRENT_TIMESTAMP,
  RPATCODEASSIGNMENT  CHAR(1 CHAR),
  USER_ID             NUMBER(10),
  DELETED             NUMBER(1)                 DEFAULT 0,
  DATECLIENT          TIMESTAMP(6)
)

   Thanks,

  Ricardo

**Comment by okbob** [comment]
There are some places where NULL and '' is equal inside Oracle. This is not true in PostgreSQL. Probably all '' strings for not string types can be safely replaced by NULL - what is not too hard in CREATE TABLE command, but can be difficult in any expressions. We had to fix this issue too. And we fixed it on Oracle side 
Original:
<pre>
xxx int DEFAULT ''
</pre>
after fix
<pre>
xxx int DEFAULT NULL
</pre>
This has better semantics - the number cannot be string - and using NULL is more correct. This doesn't change any behave on Oracle and it it is translateable to Postgres. Using this replacement on strings has risk of unwanted NULL results - there empty string should be preserved.

**Comment by darold** [comment]
Yes, Oracle allow empty string as a default value for a numeric: `SOP NUMBER(5) DEFAULT ''`.

Well I don't know what to do with this great feature, I can translate it automatically to DEFAULT NULL but I guess that Oracle allow this to not have NULL in the column. I agree that it is better to fix it on Oracle side before export.

**Comment by ricdba** [comment]
Ok I'll fix it in the Oracle database. 
Thanks for the answers.

**Comment by darold** [comment]
Commit 2525081 replaces the empty string by NULL as default value.
