### ISSUE TITLE
wrong parameters order on schema when export using fdw type

### ISSUE THREAD

**Issue by ramirio** [darold/ora2pg#446]
I'm using ora2pg to export a group of tables to use as dblink in a postgres database.
The link is working fine, but the parameters order of the export is wrong compared with the oracle schema of the tables.  
So, when I do a query in the postgres database, wrong fields are returned than the specified in the query.
This is my ora2pg configuration file:
```
ORACLE_HOME     /usr/lib/oracle/12.1/client64/
ORACLE_DSN      dbi:Oracle:host=xxx.com;sid=XE
ORACLE_USER     userxxx
ORACLE_PWD      passxxx
ALLOW           ONE_TABLE,ANOTHER_TABLE
REPLACE_TABLES  ONE_TABLE:ORA_ONE_TABLE,ANOTHER_TABLE:ORA_ANOTHER_TABLE
SKIP            fkeys,pkeys,ukeys,indexes,checks
TYPE            FDW
OUTPUT          fdw_link.sql
FDW_SERVER      fdw_link
```

**Comment by ramirio** [comment]
@darold was my question ok?  I don't know if I was clear enough.

**Comment by darold** [comment]
Sorry for the response delay. Columns might be exported in the exact order of the Oracle table, can you post here or send to my private email gilles _at_ darold _dot_ net the DDL that create theses tables?

**Comment by darold** [comment]
Post the query too.

**Comment by ramirio** [comment]
Thanks for your reply @darold
I've discovered that the problem was in our database, not in your tool. :sweat_smile:
We fixed the problem and the export worked just fine.
So, I'm closing the issue. Thanks again for your time.
