### ISSUE TITLE
Exclude tablespace duing import_all.sh

### ISSUE THREAD

**Issue by Narayanamoorthys** [darold/ora2pg#447]
I am trying to exclude Tablepspace import using "-t TABLE,PACKAGE,VIEW,GRANT,SEQUENCE,TRIGGER,FUNCTION,PROCEDURE,PARTITION,TYPE,MVIEW,DBLINK,SYNONYM,DIRECTORY" in import_all.sh command. But still the Tablespace is getting imported.

**Comment by darold** [comment]
If you have exported all your object with USE_TABLESPACE disabled in ora2pg.conf you don't have to care about tablespace. Otherwise you need to export TABLE again with this configuration directive disabled.
