### ISSUE TITLE
Error while importing views that uses 'alias'

### ISSUE THREAD

**Issue by Narayanamoorthys** [darold/ora2pg#448]
Received following error while trying to import.

_Error: 
Running: psql --single-transaction  -h x.x.x.x -U postgres -d testora2pg -f ./schema/views/view.sql
SET
SET
psql:./schema/views/JOBLIST_view.sql:44: ERROR:  syntax error at or near "alias11"
LINE 21:     WHEN extract(DAY FROM (ms.end_dt - ms.sch_dt) alias11) >...
                                                           ^
ERROR: an error occurs when importing file ./schema/views/view.sql._

and here is the complete query:

__CREATE OR REPLACE VIEW joblist (migid, status, s_host, s_db, s_ver, t_host, t_db, t_ver, start_date, complete_date, time_left, "% completion", time_taken, userid, statusnumber) AS SELECT  ms.migid MIGID,
  case when ms.status='4' then
  '10px'
  else
  '20px' end as "Status",
  ms.sipaddr "S_Host",
  ms.s_dbs "S_DB",
  cd.s_db_version "S_Ver",
  ms.tipaddr "T_Host",
  ms.t_dbs "T_DB",
  cd.t_db_version "T_Ver",
   TO_CHAR(ms.sch_dt,'DD-MON-RR HH24:MI:SS') "Start_Date",
  coalesce(TO_CHAR(ms.end_dt,'DD-MON-RR HH24:MI:SS'),'NotCompleted') "Complete_Date",
  ( SELECT
    to_char(date_trunc('day', timereq/3600),'FM9999') || 'Hr:' ||
    to_char(TRUNC(MOD(timereq,3600)/60),'FM99') || 'Min'
   FROM time_req tr where tr.migid=ms.migid
  ) "Time_Left",
  to_char(calc_comp(migid),999) || '%' "% Completion",
  CASE
    WHEN extract(DAY FROM (ms.end_dt - ms.sch_dt) alias11) > 0
    THEN extract(DAY FROM (ms.end_dt - ms.sch_dt) alias13) || 'Days '
  END ||
  CASE
    WHEN extract(HOUR FROM (ms.end_dt - ms.sch_dt) alias15) > 0
    THEN extract(HOUR FROM (ms.end_dt - ms.sch_dt) alias17) || 'Hrs '
  END ||
  CASE
    WHEN extract(Minute FROM (ms.end_dt - ms.sch_dt) alias19) > 0
    THEN extract(Minute FROM (ms.end_dt - ms.sch_dt) alias21) || 'Min '
  END AS "Time_Taken",
  ms.userid,
  ms.status as "STATUSNUMBER"
FROM MIG_SCH ms,
  checkdb cd
WHERE ms.migid=cd.checkid;__

**Comment by darold** [comment]
Commit abc74ad fixes this issue.

**Comment by Narayanamoorthys** [comment]
Thanks. It helped.
