### ISSUE TITLE
Inconsistent export

### ISSUE THREAD

**Issue by lpenet** [darold/ora2pg#45]
I have a problem of coherency when replicating an oracle database in a postgresql database.

Some new records are inserted in the database while replication is performed, as this is a live, production, database. Often, the replication fails because "table a" was replicated at t1 and "table b" was replicated at t2 and an integrit constraint is invalid.

I can use a workaround : filter out the 

\set ON_ERROR_STOP ON
BEGIN;
COMMIT;

lines in the insertion script, so that insertion keeps on excepted for the newest incoherent value. However, the database would not be always be coherent (which is not a problem to me in my current use of ora2pg) and the insertion would be slow like hell.

Would it be possible to have a mode where all data table export is performed in a single transaction ?

I already tried to use

TRANSACTION committed

but with no success.

**Comment by console-beaver** [comment]
I believe we are hitting the same issue when doing parallel extraction from oracle (`ora2pg -P 32`) with the most recent ora2pg code (`wget https://github.com/darold/ora2pg/archive/master.zip` as of two days ago). Some of the records are missed during extraction as evidenced by errrors when creating FK constraints. The source oracle database doesn't have any transactional activity (all apps are down) during  extraction. Anything specifically we need to check in our ora2pg.conf file for the parallel extraction to work correctly? Please let us know.

**Comment by console-beaver** [comment]
Just to add to the comment above - the source oracle database has the same FK constrainsts enabled and the missing  records are in there. However, they never makes it into extraction output file. So I assume there might be some issues with parallel extraction logic or our config file.Any suggestion where to start looking at is greatly appreciated!

**Comment by darold** [comment]
It is best to open a new issue than awake a dead one. I think you are missing some errors reported by Ora2Pg or some OOM, you might reduce the number of process or reduce DATA_LIMIT value.

**Comment by console-beaver** [comment]
Created a new issue #766, thanks! We don't have any OOM errors, the system has plenty of memory.
