### ISSUE TITLE
better logic for create or replace

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#451]
Right now, function objects (package, procedures, functions) have a hard-coded REPLACE OR CREATE before the object to be created.  Also, there is no directive to stop import of objects if they do not compile since there is no **SET check_function_bodies = false;** statement in the generated sql files.

What I would like is a directive or directives that specify use CREATE instead of CREATE OR REPLACE and another directive to turn off compile bodies (SET check_function_bodies = false) at the top of the script with the normal ones like SET search_path.

Can we do this?

This allows us to create all objects that were in oracle even if they don't compile.

**Comment by darold** [comment]
Commit 5903d59 adds FUNCTION_CHECK configuration directive. Disable this directive if you want to disable check_function_bodies.

**Comment by MichaelDBA** [comment]
But what about CREATE instead of CREATE OR REPLACE option?

The purpose is to not import objects if they already exist in combination with the do not comple option?

We have a moving target for DDL changes, so we want to import only newer objects.

**Comment by darold** [comment]
Ok thanks for the explanation, I will add a configuration directive to toggle between simple CREATE and CREATE OR REPLACE.

**Comment by MichaelDBA** [comment]
Thank you!  Please close this issue when it is done, or let me know and I will close it, thanks again!

**Comment by darold** [comment]
Commit 99ece60 adds the feature.
```
    Add CREATE_OR_REPLACE configuration directive. By default Ora2Pg use CREATE
    OR REPLACE in function DDL, if you need not to override existing functions
    disable this configuration directive, DDL will not include OR REPLACE. 
```

**Comment by MichaelDBA** [comment]
Thank u
