### ISSUE TITLE
Allow both REPLACE_AS_BOOLEAN and REPLACE_COLS

### ISSUE THREAD

**Issue by numero-six** [darold/ora2pg#453]
I would like to configure a migration to make it rename a column of a table but also change its type to boolean and convert as specified by REPLACE_AS_BOOLEAN.

**Comment by darold** [comment]
Renaming a column only works when exporting data with the REPLACE_COLS configuration directive. You just have to first manually change in output files the column name during the TABLE export and import those files into PostgreSQL. With REPLACE_COLS ora2pg will take care to change the column names during data export.

**Comment by numero-six** [comment]
I don't understand: I know that I can use REPLACE_COLS but the problem use I want to use both REPLACE_COLS and REPLACE_AS_BOOLEAN.

Let's say I have a Oracle table with a `my_old_column NUMBER(1,0)` column i want to rename and convert to boolean. I have to

```
REPLACE_COLS my_table(my_old_column:my_new_column)
```

OK, but should I add

```
REPLACE_AS_BOOLEAN my_old_column
```

or

```
REPLACE_AS_BOOLEAN my_new_column
```
?

**Comment by darold** [comment]
Sorry for the noise I've totaly forgotten that I have patched ora2pg to allow column renaming at table export. I still need to patch explanation of the REPLACE_COLS directive configuration file.

About your issue just configure as follow:
```
REPLACE_COLS        my_table(my_old_column:my_new_column)
REPLACE_AS_BOOLEAN     my_table:my_old_column
```
it should work.

**Comment by numero-six** [comment]
Thanks @darold I'm glad it is already supported so the current issue is more about fixing the ora2pg documentation to show that this configuration is possible.

**Comment by darold** [comment]
Commit 8506119 update the documentation.
