### ISSUE TITLE
OH NO!  Im in perl module hell

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#454]
ora2pg  -d -t TABLE -n DBMAN -N dbman,public,pg_catalog -o dbman_tables.sql -c /u02/app/oracle/oradata/DATASTORE/postgres/migration/ora2pg.conf -b /u02/app/oracle/oradata/DATASTORE/postgres
Ora2Pg version: 18.1
Trying to connect to database: dbi:Oracle:host=localhost;sid=VERSIKDB
install_driver(Oracle) failed: Can't locate DBD/Oracle.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at (eval 14) line 3.
Perhaps the DBD::Oracle perl module hasn't been fully installed,
or perhaps the capitalisation of 'Oracle' isn't right.
Available drivers: DBM, ExampleP, File, Gofer, Proxy, Sponge.
 at /usr/local/share/perl5/Ora2Pg.pm line 1453

**Comment by MichaelDBA** [comment]
so i went back and ran this which failed:
  ```
         export LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client64/lib
            export ORACLE_HOME=/usr/lib/oracle/11.2/client64/
            perl -MCPAN -e 'install DBD::Oracle'
```

Then I went and did this:
```
            #perl -MCPAN -e shell
            cpan> get DBD::Oracle
            cpan> quit
            **cd ~/.cpan/build/DBD-Oracle***
            export LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client64/lib
            export ORACLE_HOME=/usr/lib/oracle/11.2/client64/
            perl Makefile.PL
            make
            make install
```
NOTE there was no **DBD-Oracle** directory when I went cd'd to the directory, ~/.cpan/build.
There were multiple directories there:
```
DBD-Oracle-1.74-2P8BYw
DBD-Oracle-1.74-G6l1D6
DBD-Oracle-1.74-h201C7
DBD-Oracle-1.74-mFGbcy
DBD-Oracle-1.74-P1qi2S
DBD-Oracle-1.74-TlxyPJ
DBD-Pg-3.6.2-gzQ6Oj
DBD-Pg-3.6.2-ieqZsP
DBD-Pg-3.6.2-wPUXtu
```
So I went to the most recent directory to do the compiles and installs.  Then I got this when i tried to run ora2pg:
```
[oracle@oak-nd1 ~]$  ora2pg  -d -t TABLE -n DBMAN -N dbman,public,pg_catalog -o dbman_tables.sql -c /u02/app/oracle/oradata/DATASTORE/postgres/migration/ora2pg.conf -b /u02/app/oracle/oradata/DATASTORE/postgres
Ora2Pg version: 18.1
Trying to connect to database: dbi:Oracle:host=localhost;sid=VERSIKDB
install_driver(Oracle) failed: Can't load '/usr/local/lib64/perl5/auto/DBD/Oracle/Oracle.so' for module DBD::Oracle: libclntsh.so.12.1: cannot open shared object file: No such file or directory at /usr/lib64/perl5/DynaLoader.pm line 200.
 at (eval 14) line 3
Compilation failed in require at (eval 14) line 3.
Perhaps a required shared library or dll isn't installed where expected
 at /usr/local/share/perl5/Ora2Pg.pm line 1453
```

**Comment by MichaelDBA** [comment]
I then did the ldconfig thing:
` echo "/u01/app/oracle/product/12.1.0.2/dbhome_1/lib" >> /etc/ld.so.conf.d/oracle-x86_64.conf && ldconfig`

and this time it seems i got closer when I ran ora2pg:
```
POSTMAN9.6:>ora2pg  -d -t TABLE -n DBMAN -N dbman,public,pg_catalog -o dbman_tables.sql -c /u02/app/oracle/oradata/DATASTORE/postgres/migration/ora2pg.conf -b /u02/app/oracle/oradata/DATASTORE/postgres
Ora2Pg version: 18.1
Trying to connect to database: dbi:Oracle:host=localhost;sid=VERSIKDB
DBI connect('host=localhost;sid=VERSIKDB','dbman',...) failed: ORA-12541: TNS:no listener (DBD ERROR: OCIServerAttach) at /usr/local/share/perl5/Ora2Pg.pm line 1453
FATAL: 12541 ... ORA-12541: TNS:no listener (DBD ERROR: OCIServerAttach)
Aborting export...
POSTMAN9.6:>exit
logout
```

**Comment by MichaelDBA** [comment]
but with the same linux user i can sqlplus with the same credentials in ora2pg.conf
`sqlplus  me/mypass@myorcl`

**Comment by darold** [comment]
Does `sqlplus me/mypass@VERSIKDB` or `sqlplus me/mypass@localhost/VERSIKDB` work?

**Comment by darold** [comment]
And have you recompiled DBD::Oracle after running lfconfig?

**Comment by MichaelDBA** [comment]
no I did not recompile,should I have?

**Comment by MichaelDBA** [comment]
I also wrote a little perl program that ran under the oracle user and it worked!
```
#!/usr/bin/perl
use DBI;
use DBD::Oracle;
#### Setting the ORATAB Location
$otab="/etc/oratab";
#### Setting ORACLE SID
$dbname="VERSIKDB";
my $dbh = DBI->connect("dbi:Oracle:VERSIKDB","dbman","mypass")
                       or die "$DBI::errstr";
my $sth = $dbh->prepare("select sysdate from dual") or die "$DBI::errstr";
$sth->execute() or die "couldn't execute statement";
while (my $row = $sth->fetchrow_array())
     {
      print "Database $ENV{ORACLE_SID}-> sysdate: $row n";
     }

```
here is the output:
Database VERSIKDB-> sysdate: 13-JUN-17 n

**Comment by MichaelDBA** [comment]
found the problem:
```
BAD:  ORACLE_DSN      dbi:Oracle:host=localhost;sid=MYSID
OK:    ORACLE_DSN      dbi:Oracle:host=192.168.30.18;sid=MYSID
```

**Comment by pepevo** [comment]
I have the same issue when launch the second time.
1st launch, ora2pg run with 65 tables 100% scanning and the server timeout.

reconnect the server,  I tried to launch the second time and reset the LD_LIBRARY_PATH and ORACLE_HOME from command prompt and I rerun ora2pg with background and I get and error below:

FATAL: can not remove old temporary file /tmp/tmp_ora2pgdhwbrz
install_driver(oracle) failed: Can't load '/usr/local/lib64/perl5/auto/DBD/Oracle/Oracle.so' for module DBD::Oracle: libclntsh.so.12.1: cannot open shared object file: No suck file or directory at /usr/lib64/perl5/DynaLoader.pm line 190
at (evel 13) line 3.
complication failed in require at (eval 13) line 3.
Perhaps a required share library or ddl isn't installed where expected at /usr/local/share/perl5/Ora3Pg.pm line 1570
 
I removed /tmp/tmp_ora2pgdhwbrz and the error is still the same when I run "ora2pg"

what is the error and how to fix it?  Also, when I run ora2pg, where is the output. Sorry, I'm totally new to this product.

thank you.

v/r,
Bach Nga

**Comment by pepevo** [comment]
I did remove and rerun the ora2pg and again the error is still occurred.I reset the LD_LIBRARY_PATH AND ORACLE_HOME for new fresh login.  I haven't put on root's profile yet.
Still error.  Bach-Nga

No one in this world is pure and perfect.  If you avoid people for their mistakes you will be alone. So judge less, love and forgive more.To call him a dog hardly seems to do him justice though in as much as he had four legs, a tail, and barked, I admit he was, to all outward appearances. But to those who knew him well, he was a perfect gentleman (Hermione Gingold)
**Live simply **Love generously **Care deeply **Speak kindly.*** Genuinely rich *** Faithful talent *** Sharing success 

    On Wednesday, January 23, 2019 2:51 PM, Gilles Darold <notifications@github.com> wrote:
 

 Why do you reset the LD_LIBRARY_PATH and ORACLE_HOME? The /tmp/tmp_ora2pg* files are normally removed by Ora2Pg but they may persist when it is kill violently like in your case. Just remove them an rerun ora2pg.You must run ora2pg using screen to prevent server disconnections.—

**Comment by pepevo** [comment]
may I ask how come ora2pg output didn't create on the output directory I specified.  Turned out it's filled up my root (/) partition and terminate my session and closed it out.

**Comment by pepevo** [comment]
the ora2pg runs and I didn't see the output file generated.  According to the nohup.out I see "can't locate object method "gzclose" via package "IO::File" at /usr/local/share/perl5/Ora2Pg.pm line 623.

on usr/local/share/perl5/Ora2Pg.pm:
sub close_export_file
{
my ($self,$filehdl) = @_;
return if (!defined $filehdl):
if ($self->{output} =~ /\.gz$/) {
    **$filehdl->gzclose();**     -- this line 623
} else {
   $filehdl->close();

is something I did wrong here?

v/r,

Bach Nga

**Comment by pepevo** [comment]
thank you for fixing the issue in Ora2pg.pm
the job was failed again and in the middle somewhere when I run on the current directory with plenty of space (250G). The ssh, telnet and rlogin client has stopped working.  
Question, 
1. how much  physical memory is required to run ora2pg?
2. Can I run the export with multiple schemas?  How do I specify it on ora2pg.conf with comma or semicolon?   
               SCHEMAS   CIDRDB1, CIDRDB2,  etc....???
3. I don't see output as "output.sql" but something automatically generated name with dot data (.data) even if the job failed.
4. Do I need the perl-cpan module installed?

thank you,
v/r,
Bach Nga

**Comment by darold** [comment]
Please open a new issue with your questions, using a closed issue to post all sort of question is useless.
