### ISSUE TITLE
null values for clob/blob/long migrate as empty string

### ISSUE THREAD

**Issue by alicemaz** [darold/ora2pg#455]
this is actually a bug in DBD::Oracle (which I've submitted a patch for, https://github.com/pythian/DBD-Oracle/pull/46) but their repo's latest commit was six months ago so I dunno how long it will take to land and wanted to give you a heads up

there is a bug with the `ora_piece_lob` DBD option which causes the DBI `prepare` call in `_extract_data` made when `no_lob_locator` is enabled to return empty string for nulls, resulting in output like `INSERT INTO testalice.lolmaztest (id,txt,clb,blb,lng) VALUES (1,NULL,E'',decode(E'', 'hex'),E'');` where all should be null for a table typed like
```
SQL> desc lolmaztest
 Name                            Null?    Type
 ------------------------------- -------- ----------------------
 ID                              NOT NULL NUMBER(38)
 TXT                                      VARCHAR2(64 CHAR)
 CLB                                      CLOB
 BLB                                      BLOB
 LNG                                      LONG
```

this could be fixed by setting them to undef before $rows goes to `_dump_to_pg`. I didn't know if you wanted to just wait on DBD rather than working around the issue though, if you'd like me to submit a patch lmk

**Comment by darold** [comment]
Hi Alice,

Thanks for the report , I will be pleased if you submit a patch because lot of installation use old release  of DBD::Oracle.

Regards
