### ISSUE TITLE
Terminated with 'Killed' message without any explanation while 35 column

### ISSUE THREAD

**Issue by ykartal** [darold/ora2pg#456]
I have tried to migrate below TEST table from Oracle to PostgreSQL. if TABLE has 34 columns there is no problem, but if TEST table has 35 columns the output message ending with "Killed" as seen on output sample. 

> Ora2Pg version: 18.1
> Trying to connect to database: dbi:Oracle:host=192.168.1.2;port=1521;sid=EJD
> Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
> Retrieving table information...
> [1] Scanning table TEST (1 rows)...
> Trying to connect to database: dbi:Oracle:host=192.168.1.2;port=1521;sid=EJD
> Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
> Retrieving partitions information...
> 
> 
> Truncating table TEST...
> Looking how to retrieve data from TEST...
> Fetching all data from TEST tuples...
> **Killed**

```
create table TEST
(
  T_C1      VARCHAR2(20) not null,
  T_C2      VARCHAR2(20),
  T_C3      VARCHAR2(20),
  T_C4      VARCHAR2(200),
  T_C5      NUMBER(1) default 0,
  T_C6      NUMBER(15,2) default 0,
  T_C7      NUMBER(15,2) default 0,
  T_C8      NUMBER(15,2) default 0,
  T_C9      NUMBER(15,2) default 0,
  T_C10    NUMBER(15,2) default 0,
  T_C11    NUMBER(15,2) default 0,
  T_C12    NUMBER(15,2) default 0,
  T_C13    NUMBER(15,2) default 0,
  T_C14    NUMBER(15,2) default 0,
  T_C15    NUMBER(15,2) default 0,
  T_C16    NUMBER(15,2) default 0,
  T_C17    NUMBER(15,2) default 0,
  T_C18    NUMBER(15,2) default 0,
  T_C19    NUMBER(15,2) default 0,
  T_C20    NUMBER(15,2) default 0,
  T_C21    NUMBER(15,2) default 0,
  T_C22    NUMBER(15,2) default 0,
  T_C23    NUMBER(15,2) default 0,
  T_C24    NUMBER(15,2) default 0,
  T_C25    NUMBER(15,2) default 0,
  T_C26    NUMBER(15,2) default 0,
  T_C27    NUMBER(15,2) default 0,
  T_C28    NUMBER(15,2) default 0,
  T_C29    NUMBER(15,2) default 0,
  T_C30    NUMBER(15,2) default 0,
  T_C31    NUMBER(15,2) default 0,
  T_C32    NUMBER(15,2) default 0,
  T_C33    NUMBER(15,2) default 0,
  T_C34    NUMBER(15,2) default 0,
  T_C35    NUMBER(15,2) default 0

  
)
tablespace DATALAR
  pctfree 5
  initrans 1
  maxtrans 255
  storage
  (
    initial 1M
    next 1M
    minextents 1
    maxextents unlimited
  );

```

**Comment by darold** [comment]
Hi,

I guess that you don't have enough memory and an OOM killer happened. Set DATA_LIMIT to 2500 or 1000 following the quantity of RAM you have may help.

Regards,

**Comment by ykartal** [comment]
Hi,
Thanks, I checked the DATA_LIMIT parameter.
its value is defined as;
DATA_LIMIT	100000000

After changed it to 2500, worked as expected 
Then, I had reverted it to 100000000 and tried again problem is gone. 

I think the first problem was about computer's empty RAM.

Thank you,
Regards.
