### ISSUE TITLE
data export fails

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#457]
Get this error when exporting data from a schema:
`ora2pg  -d -t COPY -n AMD_CONTROL -N amd_control,public,pg_catalog -o amd_control.sql -c /u02/app/oracle/oradata/DATASTORE/postgres/migration/ora2pg.conf -b /u02/app/oracle/oradata/DATASTORE/postgres`

```
[==========>              ]  6123728/14590146 total rows (42.0%) - (178 sec., avg: 34402 recs/sec).
DBD::Oracle::db prepare failed: ORA-00604: error occurred at recursive SQL level 1
ORA-08177: can't serialize access for this transaction (DBD ERROR: OCIStmtExecute/Describe) at /usr/local/share/perl5/Ora2Pg.pm line 8091.
FATAL: ORA-00604: error occurred at recursive SQL level 1
ORA-08177: can't serialize access for this transaction (DBD ERROR: OCIStmtExecute/Describe)
Aborting export...
```

**Comment by darold** [comment]
Data are exported in serialized transaction mode to have a consistent snapshot of the data, see Oracle documentation about what parameter to increase to not have this issue. Or if you are sure that no modification are done in the Oracle database you can force Ora2Pg to use a readonly transaction instead, see TRANSACTION directive in ora2pg.conf

**Comment by MichaelDBA** [comment]
Thanks
