### ISSUE TITLE
After Installation of Ora2pg, didn't get /usr/local/ora2pg was not created. Not able to connect to oracle database.

### ISSUE THREAD

**Issue by infyravihyd** [darold/ora2pg#46]
As per README installed Ora2Pg software. After Installation didn't get /usr/local/bin/ora2pg file. 

When I tried to connect to oracle by using ora2pg by using the following command, getting below error:

/Ora2Pg/scripts> ./ora2pg -u username -w pass -o /home/ABC8477/Migration/test.sql
Trying to connect to database: dbi:Oracle:host=...t;sid=102
DBI connect('host=...;sid=102','username',...) failed: ORA-12541: TNS:no listener (DBD ERROR: OCIServerAttach) at /usr/lib/perl5/site_perl/5.10.0/Ora2Pg.pm line 907
Can't call method "begin_work" on unblessed reference at /usr/lib/perl5/site_perl/5.10.0/Ora2Pg.pm line 919.

How do I know OR Crosscheck Ora2Pg installation was successful?

Regards
Ravi

**Comment by chetan2211** [comment]
I also facing same problem of ORA-12514 TNS LISTENER, i run the following command when i get the listener error:

E:\ora2pg-23.0>ora2pg -t copy -c ora2pg_employee.dist -l employee.log
WARNING: NO_LOB_LOCATOR is deprecated, use USE_LOB_LOCATOR instead see documentation about the logic change.
WARNING: NO_BLOB_EXPORT is deprecated, use ENABLE_BLOB_EXPORT instead see documentation about the logic change.
[========================>] 1/1 tables (100.0%) end of scanning.
NOTICE:  user mapping for "employee" already exists for server "orcl", skipping
[========================>] 1/1 tables (100.0%) end of table export.
NOTICE:  drop cascades to foreign table ora2pg_fdw_import.employee_details
DBD::Pg::db do failed: ERROR:  connection for foreign table "employee_details" cannot be established
DETAIL:  ORA-12541: TNS:no listener at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 9352.
[========================>] 71/71 rows (100.0%) on total estimated data (1 sec., avg: 71 recs/sec)


I tried every solution which is available on internet but not able to resolve this issue. Please let me know if you know the solution.
Thank you in advance.

**Comment by chetan2211** [comment]
> Please look at the documentation and this presentation for more information: http://ora2pg.darold.net/ora2pg-best-practices.pdf
Hi @darold 
Document is not available on this link.

**Comment by darold** [comment]
The link is available at  http://ora2pg.darold.net/slides/ora2pg-best-practices.pdf
