### ISSUE TITLE
Unterminated comment in trigger

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#462]
Oracle:
<pre>
TRIGGER CISUUCET_BI BEFORE INSERT
 ON CISUUCET
 FOR EACH ROW

DECLARE
  mID_CISUTRID CISUTRID.ID_CISUTRID%TYPE;
  mID_CISUSKUP CISUSKUP.ID_CISUSKUP%TYPE;
  mID_UCEUDUCT UCEUDUCT.ID_UCEUDUCT%TYPE;
  mID_UCEUDGOR UCEUDGOR.ID_UCEUDGOR%TYPE;

  mSql VARCHAR2(4000);
  mSqlend VARCHAR2(4000);
  mDupl boolean ;

BEGIN
 ----  ZACATEK DEFAULT CAST
 RRRUTIL.DEFA_BEFORE_INSERT( :new.ID_CISUUCET , :new.PLATNOST_OD , :new.PLATNOST_DO ,:new.IDENT , :new.ID_ASPRAVCE , :new.CVZNIKRADK ) ;
 ---  KONEC DEFAULT CAST
  --------- C - KOPIROVANI RAD POMOCI FUNKCE COPY_RECORD , VZNIKA DUPLICITA
  IF :new.CVZNIKRADK <> 'C' THEN

    mSql := ' SELECT COUNT(*) FROM CISUUCET
               WHERE ID_UCEOBDOBI = ' || :new.ID_UCEOBDOBI  ||  ' AND SUBSTR(TRIM(KOD_CISUCET) ,1,7 ) = ''' || SUBSTR(TRIM(:new.KOD_CISUCET) ,1,7 ) || '''' ;
    --- raise_application_error( -20017 , mSql  ) ;
    mSqlend := '';
    TEST_DUPL_VAZBA( mSql , mSqlend , mDupl , :new.PLATNOST_OD , :new.PLATNOST_DO  );

    IF mDupl = True THEN
       raise_application_error( -20017 ,' KOD_CISUCET  '||SUBSTR(TRIM(:new.KOD_CISUCET) ,1,7 )||' ID_UCEOBDOBI  '||:new.ID_UCEOBDOBI || 'DUPLICITNI ZAZNAM'  ) ;
    END IF;
  END IF;

   IF (:new.ID_UCEOBDOBI IS NOT NULL )  THEN
    BEGIN
      SELECT ID_CISUJEDN INTO :new.ID_CISUJEDN
        FROM UCEOBDOBI
        WHERE ID_UCEOBDOBI = :new.ID_UCEOBDOBI;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        :new.ID_CISUJEDN := NULL ;
    END;
   END IF;

  :new.ID_UCEUDUCT_IMP:=:new.ID_CISUUCET;
  :new.ID_UCEUDGOR_IMP:=:new.ID_CISUUCET;

   IF (:new.ID_CISUSYNT IS NULL )  THEN
    ---cisusynt
    BEGIN
      SELECT ID_CISUSYNT INTO :new.ID_CISUSYNT
        FROM CISUSYNT
        WHERE TRIM(KOD_CISUSYNT) = SUBSTR(TRIM(:new.KOD_CISUCET),1,3)
          AND ID_UCEOBDOBI  = :new.ID_UCEOBDOBI and rownum<2;

    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        :new.ID_CISUSYNT := NULL ;

   END;

  ---raise_application_error( -20010 ,:new.ID_CISUUCET||'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'|| :new.ID_CISUSYNT );
   ---cisuskup
    BEGIN
      SELECT ID_CISUSKUP INTO mID_CISUSKUP
        FROM CISUSKUP
        WHERE TRIM(KOD_CISUSKUP) = SUBSTR(TRIM(:new.KOD_CISUCET),1,2)
          AND ID_UCEOBDOBI  = :new.ID_UCEOBDOBI AND ROWNUM=1;

    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        mID_CISUSKUP := NULL ;
    END;
    ---cisutrid
    BEGIN
      SELECT ID_CISUTRID INTO mID_CISUTRID
        FROM CISUTRID
        WHERE TRIM(KOD_CISUTRID) = SUBSTR(TRIM(:new.KOD_CISUCET),1,1)
          AND ID_UCEOBDOBI  = :new.ID_UCEOBDOBI AND ROWNUM=1;

    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        mID_CISUTRID := NULL ;
    END;

    ---tvorba cisutrid
    IF mID_CISUTRID IS NULL THEN
     SELECT SEAPP.NEXTVAL INTO mID_CISUTRID  FROM DUAL ;
     INSERT INTO CISUTRID
           ( ID_CISUTRID,
             KOD_CISUTRID,
             J1_NAZEV,
             POZNAMKA,
             ID_CISUJEDN,
             ID_UCEOBDOBI,
             ID_ASPRAVCE,
             ID_APROVOZNA,
             ID_SKUP_CISEL,
             PLATNOST_OD,
             PLATNOST_DO,
             LIDENT)
    VALUES  ( mID_CISUTRID,
             SUBSTR(TRIM(:new.KOD_CISUCET),1,1),
             SUBSTR(TRIM(:new.KOD_CISUCET),1,1),
             'Generovano z uctu'||SUBSTR(TRIM(:new.KOD_CISUCET),1,6),
             :new.ID_CISUJEDN,
             :new.ID_UCEOBDOBI,
             :new.ID_ASPRAVCE,
             :new.ID_APROVOZNA,
             :new.ID_SKUP_CISEL,
             :new.PLATNOST_OD,
             :new.PLATNOST_DO,
             :new.LIDENT);
    END IF; ---cisutrid
    ---tvorba cisuskup
    IF mID_CISUSKUP IS NULL THEN
     SELECT SEAPP.NEXTVAL INTO mID_CISUSKUP  FROM DUAL ;
     INSERT INTO CISUSKUP
           ( ID_CISUSKUP,
             ID_CISUTRID,
             KOD_CISUSKUP,
             J1_NAZEV,
             POZNAMKA,
             ID_CISUJEDN,
             ID_UCEOBDOBI,
             ID_ASPRAVCE,
             ID_APROVOZNA,
             ID_SKUP_CISEL,
             PLATNOST_OD,
             PLATNOST_DO,
             LIDENT)
    VALUES  (mID_CISUSKUP,
             mID_CISUTRID,
             SUBSTR(TRIM(:new.KOD_CISUCET),1,2),
             SUBSTR(TRIM(:new.KOD_CISUCET),1,2),
             'Generovano z uctu'||SUBSTR(TRIM(:new.KOD_CISUCET),1,6),
             :new.ID_CISUJEDN,
             :new.ID_UCEOBDOBI,
             :new.ID_ASPRAVCE,
             :new.ID_APROVOZNA,
             :new.ID_SKUP_CISEL,
             :new.PLATNOST_OD,
             :new.PLATNOST_DO,
             :new.LIDENT);
    END IF; ---cisuskup

    ---tvorba cisuynt
    IF :new.ID_CISUSYNT IS NULL THEN
     SELECT SEAPP.NEXTVAL INTO :new.ID_CISUSYNT  FROM DUAL ;
     INSERT INTO CISUSYNT
           ( ID_CISUSYNT,
             ID_CISUSKUP,
             KOD_CISUSYNT,
             J1_NAZEV,
             POZNAMKA,
             ID_CISUJEDN,
             ID_UCEOBDOBI,
             ID_ASPRAVCE,
             ID_APROVOZNA,
             ID_SKUP_CISEL,
             PLATNOST_OD,
             PLATNOST_DO,
             LIDENT)
    VALUES  (:new.ID_CISUSYNT,
             mID_CISUSKUP,
             SUBSTR(TRIM(:new.KOD_CISUCET),1,3),
             SUBSTR(TRIM(:new.KOD_CISUCET),1,3),
             'Generovano z uctu'||SUBSTR(TRIM(:new.KOD_CISUCET),1,6),
             :new.ID_CISUJEDN,
             :new.ID_UCEOBDOBI,
             :new.ID_ASPRAVCE,
             :new.ID_APROVOZNA,
             :new.ID_SKUP_CISEL,
             :new.PLATNOST_OD,
             :new.PLATNOST_DO,
             :new.LIDENT);
    END IF; ---cisuskup

  END IF; ---

 END ;

/*
      IF  :new.ID_CISUSYNT is NULL THEN
           ---zjisteni noveho idecka a insert
          SELECT SEAPP.NEXTVAL INTO :new.ID_CISUSYNT  FROM DUAL ;
     END IF;
*/
</pre>

Ora2pg (see last line):
<pre>
        CREATE OR REPLACE FUNCTION public.trigger_fct_cisuucet_bi()
         RETURNS trigger
         LANGUAGE plpgsql
         SECURITY DEFINER
1       AS $function$
2       DECLARE
3         mID_CISUTRID CISUTRID.ID_CISUTRID%TYPE;
4         mID_CISUSKUP CISUSKUP.ID_CISUSKUP%TYPE;
5         mID_UCEUDUCT UCEUDUCT.ID_UCEUDUCT%TYPE;
6         mID_UCEUDGOR UCEUDGOR.ID_UCEUDGOR%TYPE;
7       
8         mSql varchar(4000);
9         mSqlend varchar(4000);
10        mDupl boolean;
11      
12      
13      
14      BEGIN
15       ----  ZACATEK DEFAULT CAST
16       SELECT * FROM rrrutil.defa_before_insert( NEW.ID_CISUUCET, NEW.PLATNOST_OD, NEW.PLATNOST_DO, NEW.IDENT, NEW.ID_
17       ---  KONEC DEFAULT CAST
18        --------- C - KOPIROVANI RAD POMOCI FUNKCE COPY_RECORD , VZNIKA DUPLICITA
19        IF NEW.CVZNIKRADK <> 'C' THEN
20      
21          mSql := ' SELECT COUNT(*) FROM CISUUCET
22                     WHERE ID_UCEOBDOBI = ' || NEW.ID_UCEOBDOBI  ||  ' AND SUBSTR(TRIM(KOD_CISUCET) ,1,7 ) = ''' || SU
23          --- raise_application_error( -20017 , mSql  ) ;
24          mSqlend := '';
25          SELECT * FROM TEST_DUPL_VAZBA( mSql, mSqlend, NEW.PLATNOST_OD, NEW.PLATNOST_DO  ) INTO STRICT  mSql, mSqlend
26      
27          IF mDupl = True THEN
28             RAISE EXCEPTION '%', ' KOD_CISUCET  '||SUBSTR(btrim(NEW.KOD_CISUCET) ,1,7 )||' ID_UCEOBDOBI  '||NEW.ID_UC
29          END IF;
30        END IF;
31      
32      
33      
34         IF (NEW.ID_UCEOBDOBI IS NOT NULL )  THEN
35          BEGIN
36            SELECT ID_CISUJEDN INTO STRICT NEW.ID_CISUJEDN
37              FROM UCEOBDOBI
38              WHERE ID_UCEOBDOBI = NEW.ID_UCEOBDOBI;
39          EXCEPTION
40            WHEN NO_DATA_FOUND THEN
41              NEW.ID_CISUJEDN := NULL;
42          END;
43         END IF;
44      
45        NEW.ID_UCEUDUCT_IMP:=NEW.ID_CISUUCET;
46        NEW.ID_UCEUDGOR_IMP:=NEW.ID_CISUUCET;
47      
48         IF (NEW.ID_CISUSYNT IS NULL )  THEN
49          ---cisusynt
50          BEGIN
51            SELECT ID_CISUSYNT INTO STRICT NEW.ID_CISUSYNT
52              FROM CISUSYNT
53              WHERE btrim(KOD_CISUSYNT) = SUBSTR(btrim(NEW.KOD_CISUCET),1,3)
54                AND ID_UCEOBDOBI  = NEW.ID_UCEOBDOBI  LIMIT 1;
55      
56          EXCEPTION
57            WHEN NO_DATA_FOUND THEN
58              NEW.ID_CISUSYNT := NULL;
59      
60      
61         END;
62      
63        ---raise_application_error( -20010 ,:new.ID_CISUUCET||'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'|| :new.ID_CISUSYNT )
64         ---cisuskup
65          BEGIN
66            SELECT ID_CISUSKUP INTO STRICT mID_CISUSKUP
67              FROM CISUSKUP
68              WHERE btrim(KOD_CISUSKUP) = SUBSTR(btrim(NEW.KOD_CISUCET),1,2)
69                AND ID_UCEOBDOBI  = NEW.ID_UCEOBDOBI  LIMIT 1;
70      
71          EXCEPTION
72            WHEN NO_DATA_FOUND THEN
73              mID_CISUSKUP := NULL;
74          END;
75          ---cisutrid
76          BEGIN
77            SELECT ID_CISUTRID INTO STRICT mID_CISUTRID
78              FROM CISUTRID
79              WHERE btrim(KOD_CISUTRID) = SUBSTR(btrim(NEW.KOD_CISUCET),1,1)
80                AND ID_UCEOBDOBI  = NEW.ID_UCEOBDOBI  LIMIT 1;
81      
82          EXCEPTION
83            WHEN NO_DATA_FOUND THEN
84              mID_CISUTRID := NULL;
85          END;
86      
87          ---tvorba cisutrid
88          IF mID_CISUTRID IS NULL THEN
89           SELECT nextval('seapp') INTO STRICT mID_CISUTRID;
90           INSERT INTO CISUTRID( ID_CISUTRID,
91                   KOD_CISUTRID,
92                   J1_NAZEV,
93                   POZNAMKA,
94                   ID_CISUJEDN,
95                   ID_UCEOBDOBI,
96                   ID_ASPRAVCE,
97                   ID_APROVOZNA,
98                   ID_SKUP_CISEL,
99                   PLATNOST_OD,
100                  PLATNOST_DO,
101                  LIDENT)
102         VALUES ( mID_CISUTRID,
103                  SUBSTR(btrim(NEW.KOD_CISUCET),1,1),
104                  SUBSTR(btrim(NEW.KOD_CISUCET),1,1),
105                  'Generovano z uctu'||SUBSTR(btrim(NEW.KOD_CISUCET),1,6),
106                  NEW.ID_CISUJEDN,
107                  NEW.ID_UCEOBDOBI,
108                  NEW.ID_ASPRAVCE,
109                  NEW.ID_APROVOZNA,
110                  NEW.ID_SKUP_CISEL,
111                  NEW.PLATNOST_OD,
112                  NEW.PLATNOST_DO,
113                  NEW.LIDENT);
114         END IF; ---cisutrid
115         ---tvorba cisuskup
116         IF mID_CISUSKUP IS NULL THEN
117          SELECT nextval('seapp') INTO STRICT mID_CISUSKUP;
118          INSERT INTO CISUSKUP( ID_CISUSKUP,
119                  ID_CISUTRID,
120                  KOD_CISUSKUP,
121                  J1_NAZEV,
122                  POZNAMKA,
123                  ID_CISUJEDN,
124                  ID_UCEOBDOBI,
125                  ID_ASPRAVCE,
126                  ID_APROVOZNA,
127                  ID_SKUP_CISEL,
128                  PLATNOST_OD,
129                  PLATNOST_DO,
130                  LIDENT)
131         VALUES (mID_CISUSKUP,
132                  mID_CISUTRID,
133                  SUBSTR(btrim(NEW.KOD_CISUCET),1,2),
134                  SUBSTR(btrim(NEW.KOD_CISUCET),1,2),
135                  'Generovano z uctu'||SUBSTR(btrim(NEW.KOD_CISUCET),1,6),
136                  NEW.ID_CISUJEDN,
137                  NEW.ID_UCEOBDOBI,
138                  NEW.ID_ASPRAVCE,
139                  NEW.ID_APROVOZNA,
140                  NEW.ID_SKUP_CISEL,
141                  NEW.PLATNOST_OD,
142                  NEW.PLATNOST_DO,
143                  NEW.LIDENT);
144         END IF; ---cisuskup
145         ---tvorba cisuynt
146         IF NEW.ID_CISUSYNT IS NULL THEN
147          SELECT nextval('seapp') INTO STRICT NEW.ID_CISUSYNT;
148          INSERT INTO CISUSYNT( ID_CISUSYNT,
149                  ID_CISUSKUP,
150                  KOD_CISUSYNT,
151                  J1_NAZEV,
152                  POZNAMKA,
153                  ID_CISUJEDN,
154                  ID_UCEOBDOBI,
155                  ID_ASPRAVCE,
156                  ID_APROVOZNA,
157                  ID_SKUP_CISEL,
158                  PLATNOST_OD,
159                  PLATNOST_DO,
160                  LIDENT)
161         VALUES (NEW.ID_CISUSYNT,
162                  mID_CISUSKUP,
163                  SUBSTR(btrim(NEW.KOD_CISUCET),1,3),
164                  SUBSTR(btrim(NEW.KOD_CISUCET),1,3),
165                  'Generovano z uctu'||SUBSTR(btrim(NEW.KOD_CISUCET),1,6),
166                  NEW.ID_CISUJEDN,
167                  NEW.ID_UCEOBDOBI,
168                  NEW.ID_ASPRAVCE,
169                  NEW.ID_APROVOZNA,
170                  NEW.ID_SKUP_CISEL,
171                  NEW.PLATNOST_OD,
172                  NEW.PLATNOST_DO,
173                  NEW.LIDENT);
174         END IF; ---cisuskup
175       END IF; ---
176      END;
177     
178     /*
179           IF  NEW.ID_CISUSYNT is NULL THEN
180                ---zjisteni noveho idecka a insert
181               SELECT nextval('seapp') INTO STRICT NEW.ID_CISUSYNT;
182          END IF;
183     *
184     $function$
</pre>

**Comment by darold** [comment]
Commit a814665 fixes this issue.

**Comment by okbob** [comment]
It is fixed
