### ISSUE TITLE
Serious COPY rows error

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#463]
We encountered a problem copying data.  It was not clearly consistent, but many tables had rowcounts exported in multiples of 100,000, when we specified different values for DATA_LIMIT.

When we specified 100,000, we had table rowcounts where many were either 100,000 or 200,000 exactly!  But the target Oracle database had more rows.  When we specified the default, 10,000, we got row counts mostly in multiple of 10,000.  We tried various changes to the PARALLEL_TABLES  option as well to no avail.

We are using the recent commits from about 8 days ago.

**Comment by darold** [comment]
Hi Michael,

Don't rely on row count, Ora2Pg use Oracle statistics. You have to run statistic on Oracle before export  to have a more realistic row count. However, if you have no error during data import and ora2pg return code is 0 all your rows have been migrated. You can use TEST action with `--count_rows` to verify you import. Ex:
```
ora2pg -c config/ora2pg.conf -t TEST --count_rows > result.txt
```
of course minus application changes during import and test time.

**Comment by MichaelDBA** [comment]
I am talking about row counts in pg after the copy.  What does oracle statistics have to do with that?

**Comment by darold** [comment]
Ok, I was thinking that you are talking about the stats displayed in the progress bar.

Then you are saying that the row count available in the PostgreSQL database are always a multiple of DATA_LIMIT? Just like if the last rows < to DATA_LIMIT are not exported? Do you have the same behavior when not using -P option or PARALLEL_TABLES directive?

**Comment by MichaelDBA** [comment]
Yes, even with PARALLEL_TABLES is 1.  So we have to set DATA_LIMIT higher than the number of rows to get the full number of rows.

**Comment by greasypragma** [comment]
Our latest data load we set PARALLEL_TABLES to 1 and we set the DATA_LIMIT to 10,000 (default) and we still had exact limits set on the imports.  For example one table had over 300+k rows but only imported exactly 100,000 rows and then in another case a table that had 187,000 rows only brought in exactly 10,000 rows. 

Something is odd about the import limit that we're getting these exact row counts and not full table loads.

**Comment by darold** [comment]
What is the return code of the ora2pg command?

I'm not able to reproduce the issue but I have less rows in my test database. Please post the value of the JOB, ORACLE_COPIES, PARALLEL_TABLES and DATA_LIMIT configuration directive. I will load a bulk of data and try to reproduce. Please post the ora2pg command line that is used.

**Comment by darold** [comment]
Just tried with a high amount of data in several table exported with `-P 3` but your issue is not reproducible. I think you have some out of memory or something else that crashes some ora2pg process. Or perhaps there is a WHERE clause defined in your ora2pg.conf file.

Data export in ora2pg is stable for a long time, I think you must investigate more on your side on what is interrupting the data export. Can you try to dump data of some tables with option `-d` and post the output?

**Comment by MichaelDBA** [comment]
We will try to reproduce the problem.  Please leave this issue open.  Thank you.

**Comment by darold** [comment]
I was able to reproduce the issue, I will try to fix this problem tomorrow.

**Comment by MichaelDBA** [comment]
Thanks, Gilles!
