### ISSUE TITLE
PG_DSN in Ora2PG config file and PG_DSN in command line

### ISSUE THREAD

**Issue by fguiet** [darold/ora2pg#464]
Hello,

My PostgreSQL instance is listening on port 1525 (instead of default 5432)

Every works great if I use the following PG_DSN in ora2pg config file:

PG_DSN         dbi:Pg:dbname=XXX;host=localhost;port=1525

But if I use the following instruction (with PG_DSN=dbi:Pg:dbname=XXX;host=localhost;port=1525)

ora2pg  -c ${ORA2PG_CONF} -t COPY -u ${ORA_SCHEMA} -w ${ORA_PWD} --source ${ORA_DSN} --pg_dsn ${PG_DSN} --pg_user ${PG_USER} --pg_pwd ${PG_PWD}

ora2pg won't connect to PG (problem with the port ??)

[========================>] 336/336 tables (100.0%) end of scanning.
DBI connect('dbname=XXX','XXX',...) failed: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"? at /usr/local/share/perl5/Ora2Pg.pm line 1554.
FATAL: 1 ... could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Aborting export...

Frederic from BRGM (I have met u at Toulouse PG Day (Meteo France))

**Comment by darold** [comment]
Hi Frederic,

How do you defined the PG_DSN environment variable? What the output of command `echo $PG_DSN`?

If you do not enclose the DSN between double quote at declaration time the DSN will be truncated at the first semi-comma. Ex:
```
$ export PG_DSN=dbi:Pg:dbname=XXX;host=localhost;port=1525
$ echo $PG_DSN
dbi:Pg:dbname=XXX
```

**Comment by fguiet** [comment]
Yeah! right what an idiot! thank u! 
Problem solved!
Keep the good job going!
Fred
