### ISSUE TITLE
BFILE:EFILE

### ISSUE THREAD

**Issue by fguiet** [darold/ora2pg#465]
Hi again,

In my config file I have the following:

DATA_TYPE BFILE:EFILE

But when it comes to copy Oracle data (with bfile column) to PG (with efile column), here is what is happening:

DBD::Oracle::db prepare failed: ORA-00904: "ORA2PG_GET_EFILE": invalid identifier (DBD ERROR: error possibly near <*> indicato                 r at char 183 in 'SELECT "CODE_BSS","NOM_SCAN","TYPE_IMAGE","VOLUME","ORIENTATION","NOMUTIL","DATMAJ",ora2pg_get_efile("SCAN")                 ,"NOM_DIRECTORY","POUBELLE_DATE","POUBELLE_AUTEUR","CONFIDENTIEL","DATCRE",<*>ora2pg_get_efile("IMAGETTE"),"REFERENCES","COMME                 NTAIRE","EXTENSION","IMAGE","AUTEUR_CREATION","DATE_CREATION","AUTEUR_MODIFICATION","DATE_MODIFICATION" FROM "BSS_EAU_P"."PE_S                 CAN" a') [for Statement "SELECT "CODE_BSS","NOM_SCAN","TYPE_IMAGE","VOLUME","ORIENTATION","NOMUTIL","DATMAJ",ora2pg_get_efile(                 "SCAN"),"NOM_DIRECTORY","POUBELLE_DATE","POUBELLE_AUTEUR","CONFIDENTIEL","DATCRE",ora2pg_get_efile("IMAGETTE"),"REFERENCES","C                 OMMENTAIRE","EXTENSION","IMAGE","AUTEUR_CREATION","DATE_CREATION","AUTEUR_MODIFICATION","DATE_MODIFICATION" FROM "BSS_EAU_P"."                 PE_SCAN" a"] at /usr/local/share/perl5/Ora2Pg.pm line 11096.
FATAL: ORA-00904: "ORA2PG_GET_EFILE": invalid identifier (DBD ERROR: error possibly near <*> indicator at char 183 in 'SELECT                  "CODE_BSS","NOM_SCAN","TYPE_IMAGE","VOLUME","ORIENTATION","NOMUTIL","DATMAJ",ora2pg_get_efile("SCAN"),"NOM_DIRECTORY","POUBELL                 E_DATE","POUBELLE_AUTEUR","CONFIDENTIEL","DATCRE",<*>ora2pg_get_efile("IMAGETTE"),"REFERENCES","COMMENTAIRE","EXTENSION","IMAG                 E","AUTEUR_CREATION","DATE_CREATION","AUTEUR_MODIFICATION","DATE_MODIFICATION" FROM "BSS_EAU_P"."PE_SCAN" a')
Aborting export...

It was working with another version of ora2pg for sure, I've already used it before.

Bye
Fred

**Comment by darold** [comment]
Please use latest development code it must be fixed, at least I'm not able to reproduce the issue.

**Comment by fguiet** [comment]
Hi Darold,

I am going to make some tests today. I'll let u you.
For information, I am using v18.1 which is the latest release.

Merci!
Frederic

**Comment by fguiet** [comment]
Hi Darold,

Back to version 17.4, it's working no problem at all.
I am gonna try last master branch...

**Comment by darold** [comment]
Ok, good news, it need a new maintenance release asap.
