### ISSUE TITLE
Invalid RAISE command

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#467]
Oracle:
<pre>
                   IF qPredpis.OBDOBI_DO < mObdobi_do THEN
                     RAISE EXCEPT_NENI_PREDPIS;
                   END IF;
</pre>

Ora2pg:
<pre>
                           IF qPredpis.OBDOBI_DO < mObdobi_do THEN                                               
                             RAISE EXCEPTION 'except_neni_predpis' USING ERRCODE '50004';                        
 --                                                                              ^                               
                           END IF;     
</pre>
Should be 
<pre>
RAISE EXCEPTION 'xxxx' USING ERRCODE='50004';
</pre?

**Comment by darold** [comment]
Fixed in commit dde7dde.

**Comment by okbob** [comment]
looks fixed. Thank you
