### ISSUE TITLE
Broken function header (missing space before OUT)

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#468]
Oracle:
<pre>
CREATE OR REPLACE procedure IDES_JMMAJ.GET_ID_SSSLOGIN_CRON( mID_SKUP_CISEL IN NUMBER , mID_SSSLOGIN OUT NUMBER ) IS
  mId PAROSOBA.ID_OSOB%TYPE;
  mID_CCLE CLEOSOBY.ID_CCLE%TYPE;
  mID_ASPRAVCE UDRPROVO.ID_ASPRAVCE%TYPE;
begin
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE FUNCTION get_id_ssslogin_cron ( mID_SKUP_CISEL numeric , mID_SSSLOGINOUT numeric ) RETURNS VOID AS $body$
DECLARE
  
  mId PAROSOBA.ID_OSOB%TYPE;
  mID_CCLE CLEOSOBY.ID_CCLE%TYPE;
  mID_ASPRAVCE UDRPROVO.ID_ASPRAVCE%TYPE;

BEGIN
</pre>

**Comment by darold** [comment]
Must be fixed in commit 2ffc3c6

**Comment by okbob** [comment]
It is fixed. Thank you
