### ISSUE TITLE
COMMIT keyword is not correctly commented

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#469]
Oracle:
<pre>
     IF  mTansakce = 'A' THEN
        COMMIT  ;
     END IF ;
</pre>

Ora2pg:
<pre>
     IF  mTansakce = 'A' THEN
        COMMIT  ;
     END IF ;
</pre>

**Comment by darold** [comment]
You have to set `COMMENT_COMMIT_ROLLBACK         1` in ora2pg.conf

**Comment by okbob** [comment]
COMMENT_COMMIT_ROLLBACK is 1 already

**Comment by darold** [comment]
OK, in this case I guess that the problem is related to issue #466
