### ISSUE TITLE
Missing space between EXCEPTION and WHEN

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#470]
Oracle:
<pre>
CREATE OR REPLACE procedure IDES_JMMAJ.ZMENA_VAZBY ( mVAZTAB_REC IN  RRRUTIL.T_VAZTAB_REC , mAkce IN CHAR , mTransakce IN CHAR , mChybaText IN OUT VARCHAR2 )
          is
  /*  PROCEDURA PROVEDE ZMENU CASOVE PLATNOSTI
      VE VAZEBNI TABULCE .
      POKUD JE AKCE I - JE PROVEDEN POUZE INSERT
                    U - POKUD DATUM PLATNOST_OD OLD_ZAZNAMU
                        JE MENSI NEZ DATUM ZMENY PROVEDE SE
                        UKONCENI TOHOTO ZAZNAMU A VYTVORENI
                        NOVEHO
                        POKUD DATUM PLATNOST_OD OLD_ZAZNAMU
                        JE STEJNA NEBO VETSI JAKO DATUM ZMENY
                        POUZE SE AKTUALIZUJE STAVAJICI
                        ZAZNAM.

      POZOR VZDY MUSI BYT ZADANA POLOZKA Pol_ID1_FIL
      A POLOZKA  ZmenaK_Datu - ZDE SE JINAK NAPLNI SYSDATE )
  */

  EXCEPT_CHYBA_ID EXCEPTION;

  mUpSql      VARCHAR2(4000);
  mUpSqlStDat VARCHAR2(4000);
  mInsSql     VARCHAR2(4000);
  mInsSqlVal  VARCHAR2(4000);
  mSelectSql  VARCHAR2(4000);
  mZmenakDatu DATE ;
  mDat_1 DATE ;
  mPl_od_old DATE ;
  mStejnyDen BOOLEAN;
  mNeniZaznam BOOLEAN;
begin

  mNeniZaznam := False ;
  mChybaText := NULL ;
  IF  mTransakce = 'A' THEN
    SET TRANSACTION READ WRITE  ;
  END IF ;

 BEGIN
    IF mVAZTAB_REC.Pol_ID1_Val IS NULL THEN
      RAISE EXCEPT_CHYBA_ID ;
    END IF;
    mStejnyDen := False ;
    mZmenakDatu := mVAZTAB_REC.ZmenaK_Datu;
    IF mZmenakDatu IS NULL THEN
      mZmenakDatu := SYSDATE ;
    END IF ;
    UPRAV_DATUM( mZmenakDatu );
    mDat_1 := mZmenakDatu;
    ZMENA_DATUMU( mDat_1 , '-' , 1 );

    IF mAkce = 'U' THEN
      mSelectSql := ' SELECT PLATNOST_OD INTO :mPl_od_old ' ||
                    '  FROM  ' || mVAZTAB_REC.TableName ||
                    '  WHERE ' || mVAZTAB_REC.Pol_ID1_FIL || ' = ' || mVAZTAB_REC.Pol_ID1_Val ||
                    '  AND PLATNOST_DO = :MaxDate' ;

      BEGIN
        EXECUTE IMMEDIATE mSelectSql INTO mPl_od_old USING RRRUTIL.R_MAXDATE() ;

        IF mZmenakDatu < mPl_od_old THEN
          mStejnyDen := True ;
        END IF ;
      EXCEPTION
        WHEN NO_DATA_FOUND THEN
          mNeniZaznam := True ;
      END ;
    END IF  ;

    mUpSql := ' UPDATE ' || mVAZTAB_REC.TableName ||
                ' SET PLATNOST_DO = :mDat_1 ' ||
                ' WHERE ' || mVAZTAB_REC.Pol_ID1_FIL || ' = ' || mVAZTAB_REC.Pol_ID1_Val ||
                '  AND PLATNOST_DO = :MaxDate' ;

    mInsSql     := ' INSERT INTO ' || mVAZTAB_REC.TableName ;
    mInsSqlVal  := '  VALUES ' ;
    mUpSqlStDat := ' UPDATE '  || mVAZTAB_REC.TableName ;

    -- POZOR tato polozka musi byt vzdy vyplnena
    IF mVAZTAB_REC.Pol_ID1_Val IS NOT NULL THEN
        mInsSql := mInsSql || ' ( ' || mVAZTAB_REC.Pol_ID1_FIL ;
        mInsSqlVal :=  mInsSqlVal || ' ( ' ||  mVAZTAB_REC.Pol_ID1_Val  ;
        mUpSqlStDat := mUpSqlStDat || ' SET ' || mVAZTAB_REC.Pol_ID1_FIL || ' = ' || mVAZTAB_REC.Pol_ID1_Val ;
    END IF;

    IF mVAZTAB_REC.Pol_ID1_VaL IS NOT NULL THEN
      mInsSql := mInsSql || ' , ' || mVAZTAB_REC.Pol_ID2 ;
      mInsSqlVal :=  mInsSqlVal || ' ,' || mVAZTAB_REC.Pol_ID2_Val;
      mUpSqlStDat := mUpSqlStDat || ' , ' || mVAZTAB_REC.Pol_ID2 || ' = ' || mVAZTAB_REC.Pol_ID2_Val ;
    END IF;

    IF mZmenakDatu IS NOT NULL THEN
      mInsSql := mInsSql || ' , PLATNOST_OD ';
      mInsSqlVal :=  mInsSqlVal || ' , ''' || mZmenakDatu || '''' ;
      mUpSqlStDat := mUpSqlStDat || ' , PLATNOST_OD = ''' || mZmenakDatu || '''' ;
    END IF;

    IF mVAZTAB_REC.Ident IS NOT NULL THEN
      mInsSql := mInsSql || ' , IDENT ';
      mInsSqlVal :=  mInsSqlVal || ' , ''' || mVAZTAB_REC.Ident || '''' ;
      mUpSqlStDat := mUpSqlStDat || ' , IDENT  = ''' || mVAZTAB_REC.Ident || '''' ;
    END IF;

    IF mVAZTAB_REC.LIdent IS NOT NULL THEN
      mInsSql := mInsSql || ' , LIDENT ';
      mInsSqlVal :=  mInsSqlVal || ' , ''' || mVAZTAB_REC.LIdent || '''' ;
      mUpSqlStDat := mUpSqlStDat || ' , LIDENT  = ''' || mVAZTAB_REC.LIdent || '''' ;
    END IF;

    IF mVAZTAB_REC.Id_ASpravce IS NOT NULL THEN
      mInsSql := mInsSql || ' , ID_ASPRAVCE ' ;
      mInsSqlVal :=  mInsSqlVal || ' , ' ||  mVAZTAB_REC.Id_ASpravce  ;
    END IF;

    IF mVAZTAB_REC.Id_AProvozna IS NOT NULL THEN
      mInsSql := mInsSql || ' , ID_APROVOZNA ' ;
      mInsSqlVal :=  mInsSqlVal || ' , ' ||  mVAZTAB_REC.Id_AProvozna  ;
    END IF;

    mInsSql := mInsSql || ' ) ';
    mInsSqlVal :=  mInsSqlVal || ' ) ';

    mInsSql := mInsSql || mInsSqlVal ;

    mUpSqlStDat := mUpSqlStDat ||
            '  WHERE ' || mVAZTAB_REC.Pol_ID1_FIL || ' = ' || mVAZTAB_REC.Pol_ID1_Val ||
            '  AND PLATNOST_DO = :MaxDate' ;

    --UPDATE
    IF ( mAkce = 'U' ) and ( mStejnyDen = False ) and (  mNeniZaznam = False ) THEN
      EXECUTE IMMEDIATE mUpSql USING mDat_1,RRRUTIL.R_MAXDATE() ;
    END IF ;

    IF ( mStejnyDen = False ) or (  mNeniZaznam = True ) THEN
      EXECUTE IMMEDIATE mInsSql  ;
    ELSE
      EXECUTE IMMEDIATE mUpSqlStDat USING RRRUTIL.R_MAXDATE() ;
    END IF;

    IF  mTransakce = 'A' THEN
      COMMIT  ;
    END IF ;

 EXCEPTION
   WHEN EXCEPT_CHYBA_ID THEN
      mChybaText := ' Nevyplněné hledaci ID ' ;
      IF  mTransakce = 'A' THEN
        ROLLBACK ;
      END IF  ;
  /*
   WHEN OTHERS THEN
      mChybaText := SQLERRM ;
      IF  mTransakce = 'A' THEN
        ROLLBACK ;
      END IF  ;
  */
 END ;

end ;
</pre>

Broken translated part:
<pre>
 EXCEPTIONWHEN SQLSTATE '50005' THEN
      mChybaText := ' Nevyplněné hledaci ID ';
      IF  mTransakce = 'A' THEN
        -- ROLLBACK;
      END IF;
</pre>

**Comment by darold** [comment]
Commit c5f6148 might solve the issue.

**Comment by okbob** [comment]
It is fixed, thank you
