### ISSUE TITLE
raise_application_error is not translated

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#471]
<pre>
      ----IF SUBSTR(mDIC,1,2) = 'CZ' THEN
      IF mDIC IS NOT NULL THEN
        mDIC_OK := SUBSTR( TRIM(mDIC) ,  3, LENGTH(TRIM(mDIC)) - 2 );
        mK_STAT := SUBSTR(mDIC,1,2);
        IF GET_STAT_DIC( mK_STAT ) = 'N' THEN
           mCHYBA_TEXT := mCHYBA_TEXT || ' NESPRAVNE DIC,';
           mCHYBA_OZP := 'A';
        END IF;
        IF LENGTH(mDIC_OK) > 10  THEN
          raise_application_error( -20010 , ' NESPRAVNE DIC >' || mDIC || '<' );
        END IF;
      END IF;
</pre>

Ora2pg:
<pre>
      ----IF SUBSTR(mDIC,1,2) = 'CZ' THEN
      IF mDIC IS NOT NULL THEN
        mDIC_OK := SUBSTR( TRIM(mDIC) ,  3, LENGTH(TRIM(mDIC)) - 2 );
        mK_STAT := SUBSTR(mDIC,1,2);
        IF GET_STAT_DIC( mK_STAT ) = 'N' THEN
           mCHYBA_TEXT := mCHYBA_TEXT || ' NESPRAVNE DIC,';
           mCHYBA_OZP := 'A';
        END IF;
        IF LENGTH(mDIC_OK) > 10  THEN
          raise_application_error( -20010 , ' NESPRAVNE DIC >' || mDIC || '<' );
        END IF;
      END IF;
</pre>

**Comment by darold** [comment]
Same as in 472, the origin of the problem is explained in issue #466
