### ISSUE TITLE
sequence is not translated

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#472]
Oracle:
<pre>
             SELECT SEAPP.NEXTVAL INTO mID_HL_DPHABC_B3
                FROM DUAL;
</pre>

Ora2pg:
<pre>
             SELECT SEAPP.NEXTVAL INTO mID_HL_DPHABC_B3
                    FROM DUAL;
</pre>

Should be:
<pre>
  SELECT nextval('seapp') INTO mID_HL_DPHABC_B3 FROM dual;
</pre>

**Comment by darold** [comment]
There's no such issue, I see that the query come from the procedure in file TVORBA_KONT_HL_DPH.txt The origin of the problem is explained in issue #466
