### ISSUE TITLE
Custom exception is not translated in trigger

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#473]
Oracle:
<pre>
TRIGGER "IDES_JMMAJ".UCEPOHYB_BU BEFORE UPDATE
ON  UCEPOHYB
FOR EACH ROW

 
Declare
 mRowSSSHLEDEJ_A  SSSHLEDEJ_A%ROWTYPE;
 mULICE      PARADR.ULICE%TYPE ;
 mCISPOP     PARADR.CISPOP%TYPE ;
 mCISORI     PARADR.CISORI%TYPE ;
 mID_ADR     PARADR.ID_ADR%TYPE ;
 mCISLO      OBPODBMI.CISLO%TYPE ;
 mNAZEV      OBPODBMI.NAZEV%TYPE ;
 mDEFARAJ    OBPODBMI.DEFARAJ%TYPE ;
 mDopln      boolean ;
 mProvozna  RRRUTIL.T_PROVOZNA;
 mChyba boolean; 
 NEVIDIM_TABULKU EXCEPTION;
 PRAGMA EXCEPTION_INIT( NEVIDIM_TABULKU, -04091 );
</pre>

Ora2pg:
<pre>
        CREATE OR REPLACE FUNCTION public.trigger_fct_ucepohyb_bu()
         RETURNS trigger
         LANGUAGE plpgsql
         SECURITY DEFINER
1       AS $function$
2       DECLARE
3         qSumaPlat RECORD;
4        mRowSSSHLEDEJ_A  SSSHLEDEJ_A;
5        mULICE      PARADR.ULICE%TYPE;
6        mCISPOP     PARADR.CISPOP%TYPE;
7        mCISORI     PARADR.CISORI%TYPE;
8        mID_ADR     PARADR.ID_ADR%TYPE;
9        mCISLO      OBPODBMI.CISLO%TYPE;
10       mNAZEV      OBPODBMI.NAZEV%TYPE;
11       mDEFARAJ    OBPODBMI.DEFARAJ%TYPE;
12       mDopln      boolean;
13       mProvozna  RRRUTIL.T_PROVOZNA;
14       mChyba boolean;
15       NEVIDIM_TABULKU EXCEPTION;
16       PRAGMA EXCEPTION_INIT( NEVIDIM_TABULKU, -04091 );
17        micAULICE  PARADR.ULICE%TYPE;
</pre>

**Comment by darold** [comment]
Commit e07286d remove call to `PRAGMA EXCEPTION_INIT()`.

**Comment by okbob** [comment]
no change. Not sure if only PRAGMA removing is correct. The line 15 is problem too.

**Comment by darold** [comment]
Sorry, it might be fixed in function but not in trigger.

**Comment by okbob** [comment]
looks well, thank you
