### ISSUE TITLE
Broken Oracle to ANSI outer JOIN in FOR IN SELECT inside trigger

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#474]
Oracle:
<pre>
 if :new.ID_UCEPOLBAN IS not null THEN
   FOR qSumaPlat IN (
    SELECT A1.DBANV_POL,
           A2.DBANV
    FROM UCEPOLBAN A1, 
         UCEHLABAN A2
   WHERE 
       :new.ID_UCEPOLBAN= A1.ID_UCEPOLBAN(+) AND
       A1.ID_UCEHLABAN= A2.ID_UCEHLABAN(+)
      )
  LOOP
    :new.DATUM_OST :=:new.UCEDAT;
    
    
    --- banka  polozka 
    IF  qSumaPlat.DBANV_POL is not null
    THEN
    :new.DATUM_OST := qSumaPlat.DBANV_POL;
    :new.UCEDAT   :=qSumaPlat.DBANV_POL;
    END IF;
    --- banka hlavicka
    IF  qSumaPlat.DBANV_POL is null
    and qSumaPlat.DBANV is not null
    THEN
    :new.DATUM_OST := qSumaPlat.DBANV;
    END IF;

  END LOOP;     
  
 END IF; ---banka polozka
</pre>

Ora2pg:
<pre>
 if NEW.ID_UCEPOLBAN IS not null THEN
   FOR qSumaPlat IN (
    SELECT A1.DBANV_POL,
           A2.DBANV
    FROM ucepolban a1, ucehlaban a2, ) ---<<<<<<<<
  LOOP
    NEW.DATUM_OST :=NEW.UCEDAT;

....
    --- banka  polozka.
    IF  qSumaPlat.DBANV_POL is not null
    THEN
    NEW.DATUM_OST := qSumaPlat.DBANV_POL;
    NEW.UCEDAT   :=qSumaPlat.DBANV_POL;
    END IF;
    --- banka hlavicka
    IF  qSumaPlat.DBANV_POL is null
    and qSumaPlat.DBANV is not null
    THEN
    NEW.DATUM_OST := qSumaPlat.DBANV;
    END IF;

  END LOOP;
..
 END IF; ---banka polozka
</pre>

**Comment by darold** [comment]
Can you post the full DDL of the Oracle trigger? It will save me some times.

**Comment by okbob** [comment]
yes
[ucepohub.txt](https://github.com/darold/ora2pg/files/1092979/ucepohub.txt)

**Comment by darold** [comment]
Commit d07aa19 might fix this issue. I'm not really sure that I've taken the right solution, let me know if there is something wrong.

**Comment by okbob** [comment]
It is not correct - the variable NEW cannot be used as relation. More, has not sense do left join against one line relation.

**Comment by darold** [comment]
Yes, this was what I was thinking too, I will have more time to work on this issue tomorrow and try to find a solution.

**Comment by darold** [comment]
Hi Pavel,

I'm a bit confused on how this outer join trigger code might be converted to plpgsql:
```
 if :new.ID_UCEPOLBAN IS not null THEN
   FOR qSumaPlat IN (
    SELECT A1.DBANV_POL,
           A2.DBANV
    FROM UCEPOLBAN A1,
         UCEHLABAN A2
   WHERE
       :new.ID_UCEPOLBAN= A1.ID_UCEPOLBAN(+) AND
       A1.ID_UCEHLABAN= A2.ID_UCEHLABAN(+)
      )
  LOOP
 END IF;
```
do you have an idea of the expected SELECT statement?

**Comment by okbob** [comment]
I am thinking so (+) is ignored in first line and it is used just like filter - so expected result is
    
    SELECT A1.DBANV_POL, A2.DBANV
      FROM UCEPOLBAN A1 LEFT JOIN UCEHLABAN A2 ON A1.ID_UCEHLABAN= A2.ID_UCEHLABAN
   WHERE new.ID_UCEPOLBAN= A1.ID_UCEPOLBAN;

Oracle usually ignore useless symbols by default.

**Comment by darold** [comment]
I came to the same understanding, I will simply put any predicate with OLD/NEW in the where clause.

**Comment by darold** [comment]
Commit 3439910 might fix this issue.

**Comment by okbob** [comment]
It is fixed. The transformation is correct - I am thinking.
