### ISSUE TITLE
Missing PERFORM

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#476]
Oracle:
<pre>
CREATE OR REPLACE PROCEDURE IDES_JMMAJ."ZMENA_SMLCES_P10" (
  mID_NAJVZTAH NAJVZTAH.ID_NAJVZTAH%TYPE,
  mID_EXT_NAP IN NAJVZTAH.ID_EXT_NAP%TYPE,
  mID_EXT_NAP2 IN NAJVZTAH.ID_EXT_NAP2%TYPE, -- (pc_subjekt)
  mOBDOBI_OD IN NAJVZTAH.OBDOBI_OD%TYPE,
  mOBDOBI_DO IN NAJVZTAH.OBDOBI_DO%TYPE,
  mDATUM_PLATNOSTI_OD IN NAJUDAJE.DATUM_PLATNOSTI_OD%TYPE,
  mDATUM_DOBA_URCITA IN NAJUDAJE.DATUM_DOBA_URCITA%TYPE,
  mCISLO_SMLOUVY IN NAJUDAJE.CISLO_SMLOUVY%TYPE,
  mPc_subjekt  IN NUMBER ,
  mCislo_popisne IN NUMBER,
  mCislo_popisne_znak  IN VARCHAR2,
  mCislo_orientacni  IN NUMBER,
  mCislo_orientacni_znak IN VARCHAR2,
  mDatum_narozeni IN DATE,
  mDic IN VARCHAR2,
  mE_mail IN VARCHAR2,
  mFax IN VARCHAR2,
  mIc IN VARCHAR2,
  mId_adresa IN PARADR.ID_ADR%TYPE,
  mJmeno1 IN VARCHAR2,
  mJmeno2 IN VARCHAR2,
  mNazev IN VARCHAR2,
  mNazev_castobce IN VARCHAR2,
  mNazev_kraj IN VARCHAR2,
  mNazev_mestcast IN VARCHAR2,
  mNazev_obec IN VARCHAR2,
  mNazev_okres IN VARCHAR2,
  mNazev_stat IN VARCHAR2,
  mNositel_pripad CHAR,
  mPrijmeni1 IN VARCHAR2,
  mPrijmeni2 IN VARCHAR2,
  mPsc IN VARCHAR2,
  mRodne_cislo IN VARCHAR2,
  mTelefon IN VARCHAR2,
  mTitlprjm IN VARCHAR2,
  mTitlzajm IN VARCHAR2,
  mID_CCLE IN OUT CLEOSOBY.ID_CCLE%TYPE,
  mLIDENT IN CLEOSOBY.LIDENT%TYPE,
  mTransakce IN CHAR,
  mTYP_OF_P1 IN VARCHAR2,
  mNazev_ulicevp VARCHAR2,
  mCislo_partner IN cleosoby.cislo_partner%TYPE,
  mId_partner IN cleosoby.id_ext_nap%TYPE,
  mChyba_TEXT OUT VARCHAR2
 ) is
  mID_ADR PARADR.ID_ADR%TYPE;
  mID_OSOB PAROSOBA.ID_OSOB%TYPE;
  mID_PAR PAROPAR.ID_PAR%TYPE;
  mHodnotaValue VARCHAR2(63);
  mTYP_OF CHAR(1);
  mJmenoOK CLEOSOBY.NAJMENO%TYPE;
  mID_APROVOZNA  UDRPROVO.ID_PROVOZNA%TYPE;
  mID_ASPRAVCE  UDRPROVO.ID_ASPRAVCE%TYPE;
  mID_SKUP_CISEL  UDRPROVO.ID_SKUP_CISEL%TYPE;
  mID_CCLE_PUV CLEOSOBY.ID_CCLE%TYPE;
  mID_EXT_NAP_PUV  NAJVZTAH.ID_EXT_NAP%TYPE;
  mID_EXT_NAP2_PUV NAJVZTAH.ID_EXT_NAP2%TYPE;
  mCISLO_SMLOUVY_PUV NAJUDAJE.CISLO_SMLOUVY%TYPE;
  mCISLO_PARTNER_PUV CLEOSOBY.CISLO_PARTNER%TYPE;
  mZMENA_OD DATE;
  mID_EXT_NAP_CCLE_PUV CLEOSOBY.ID_EXT_NAP%TYPE;
  mOBDOBI_OD_PUV NAJVZTAH.OBDOBI_OD%TYPE;
  mOBDOBI_DO_PUV NAJVZTAH.OBDOBI_DO%TYPE;
  mDATUM_DOBA_URCITA_PUV NAJUDAJE.DATUM_DOBA_URCITA%TYPE;
  mDATUM_PLATNOSTI_OD_PUV NAJUDAJE.DATUM_PLATNOSTI_OD%TYPE;
begin

   IF mTransakce = 'A' THEN
     SET TRANSACTION READ WRITE;
   END IF;

   mChyba_TEXT := NULL;
   mZMENA_OD := TRUNC(SYSDATE);

   SELECT ID_APROVOZNA,ID_ASPRAVCE , ID_EXT_NAP , ID_EXT_NAP2,
          OBDOBI_OD, OBDOBI_DO
     INTO mID_APROVOZNA, mID_ASPRAVCE,mID_EXT_NAP_PUV , mID_EXT_NAP2_PUV,
          mOBDOBI_OD_PUV, mOBDOBI_DO_PUV
     FROM NAJVZTAH
     WHERE ID_NAJVZTAH = mID_NAJVZTAH;

   SELECT CISLO_SMLOUVY,DATUM_DOBA_URCITA,DATUM_PLATNOSTI_OD
     INTO mCISLO_SMLOUVY_PUV ,mDATUM_DOBA_URCITA_PUV,mDATUM_PLATNOSTI_OD_PUV
     FROM NAJUDAJE
     WHERE ID_NAJVZTAH = mID_NAJVZTAH
       AND PLATNOST_DO = RRRUTIL.R_MAXDATE();

   SELECT ID_SKUP_CISEL INTO mID_SKUP_CISEL
     FROM UDRPROVO
     WHERE ID_APROVOZNA = mID_APROVOZNA;

   EXISTS_OSOBAFIR( mId_partner , 'ID_EXT_NAP' , mID_CCLE , mID_ADR , 'N' , NULL );

   --- POKUD NEEXISTUJE OSOBA TAK VYTVOR
   IF mID_CCLE IS NULL THEN
     BEGIN
       TVORBA_NEW_OSOBY_P1( mPc_subjekt  , mCislo_popisne ,mCislo_popisne_znak  ,mCislo_orientacni ,
                           mCislo_orientacni_znak ,mDatum_narozeni ,mDic ,mE_mail ,mFax ,mIc ,mId_adresa ,mJmeno1 ,mJmeno2 ,mNazev ,mNazev_castobce ,
                           mNazev_kraj ,mNazev_mestcast ,mNazev_obec ,mNazev_okres ,mNazev_stat ,mNositel_pripad ,
                           mPrijmeni1 ,mPrijmeni2 ,mPsc ,mRodne_cislo ,mTelefon ,mTitlprjm ,mTitlzajm ,mID_CCLE ,mLIDENT ,mID_APROVOZNA ,mID_ASPRAVCE ,mID_SKUP_CISEL ,
                           'A' , 'N' , 'N' , mTYP_OF_P1 ,mNazev_ulicevp ,mCislo_partner ,mId_partner );
     EXCEPTION
       WHEN OTHERS THEN
         mID_CCLE := NULL;
         mChyba_TEXT := SUBSTR( mChyba_TEXT || ' TVORBA_NEW_OSOBY_P1 ' || SQLERRM , 1 ,4000 ) ;
     END;
   END IF;

   IF mID_CCLE IS NOT NULL THEN
     SELECT ID_CCLE INTO mID_CCLE_PUV
      FROM V_CLEVON_AKT_HLAVA
      WHERE ID_NAJVZTAH = mID_NAJVZTAH;

     UPDATE NAJVZTAH
       SET ID_EXT_NAP = mID_EXT_NAP,
           ID_EXT_NAP2 = mID_EXT_NAP2,
           OBDOBI_DO = mOBDOBI_DO
       WHERE ID_NAJVZTAH = mID_NAJVZTAH;

     UPDATE NAJUDAJE
       SET DATUM_NAJEM_OD = mDATUM_PLATNOSTI_OD,
           DATUM_DOBA_URCITA = mDATUM_DOBA_URCITA,
           CISLO_SMLOUVY = mCISLO_SMLOUVY
       WHERE ID_NAJVZTAH = mID_NAJVZTAH
         AND PLATNOST_DO = RRRUTIL.R_MAXDATE() ;

    SELECT CISLO_PARTNER , ID_EXT_NAP
       INTO mCISLO_PARTNER_PUV , mID_EXT_NAP_CCLE_PUV
       FROM CLEOSOBY
       WHERE ID_CCLE = mID_CCLE_PUV;
     IF mID_CCLE <> mID_CCLE_PUV THEN
        BEGIN
          ZMENA_CLEVON_HL_OSOBA( mID_NAJVZTAH ,mZMENA_OD , mID_CCLE , 'N' );
        EXCEPTION
          WHEN OTHERS THEN
            mChyba_TEXT := SUBSTR( mChyba_TEXT || ' ZMENA_CLEVON_HL_OSOBA ' || SQLERRM , 1 ,4000 ) ;

        END;
     END IF;

     INSERT INTO NAJCESEVI ( ID_NAJVZTAH, CISLO_SMLOUVY,OBDOBI_OD, OBDOBI_DO,
                             DATUM_DOBA_URCITA, ID_EXT_NAP ,ID_EXT_NAP2, VARSCES,
                             ID_CCLE,ID_EXT_NAP_CCLE, CISLO_PARTNER,
                             ID_ASPRAVCE, ID_APROVOZNA,LIDENT , DATUM_PLATNOSTI_OD )
         VALUES( mID_NAJVZTAH, mCISLO_SMLOUVY_PUV,mOBDOBI_OD_PUV, mOBDOBI_DO_PUV,
                             mDATUM_DOBA_URCITA_PUV, mID_EXT_NAP_PUV ,mID_EXT_NAP2_PUV, NULL,
                             mID_CCLE_PUV,mID_EXT_NAP_CCLE_PUV, mCISLO_PARTNER_PUV,
                             mID_ASPRAVCE, mID_APROVOZNA,mLIDENT, mDATUM_PLATNOSTI_OD_PUV );
   END IF;

   IF mTransakce = 'A' THEN
     IF mChyba_TEXT IS NULL THEN
       COMMIT;
     ELSE
       ROLLBACK;
     END IF;
   END IF;

end ZMENA_SMLCES_P10;
</pre>

One from last bugs on my source base - missing PERFORM for  TVORBA_NEW_OSOBY_P1

**Comment by darold** [comment]
This doesn't look to be a bug, but it seems that PERFORM is missing just because Ora2Pg has not registered the TVORBA_NEW_OSOBY_P1 function before so it don't know that this is a function. Does this function exists in the same schema?

**Comment by okbob** [comment]
It is exists:
<pre>
CREATE OR REPLACE PROCEDURE IDES_JMMAJ."TVORBA_NEW_OSOBY_P1" (
  mPc_subjekt  IN NUMBER ,
  mCislo_popisne IN NUMBER,
  mCislo_popisne_znak  IN VARCHAR2,
  mCislo_orientacni  IN NUMBER,
  mCislo_orientacni_znak IN VARCHAR2,
  mDatum_narozeni IN DATE,
  mDic IN VARCHAR2,
  mE_mail IN VARCHAR2,
  mFax IN VARCHAR2,
  mIc IN VARCHAR2,
  mId_adresa IN NUMBER,
  mJmeno1 IN VARCHAR2,
  mJmeno2 IN VARCHAR2,
  mNazev IN VARCHAR2,
  mNazev_castobce IN VARCHAR2,
  mNazev_kraj IN VARCHAR2,
  mNazev_mestcast IN VARCHAR2,
  mNazev_obec IN VARCHAR2,
  mNazev_okres IN VARCHAR2,
  mNazev_stat IN VARCHAR2,
  mNositel_pripad CHAR,
  mPrijmeni1 IN VARCHAR2,
  mPrijmeni2 IN VARCHAR2,
  mPsc IN VARCHAR2,
  mRodne_cislo IN VARCHAR2,
  mTelefon IN VARCHAR2,
  mTitlprjm IN VARCHAR2,
  mTitlzajm IN VARCHAR2,
  mID_CCLE IN OUT CLEOSOBY.ID_CCLE%TYPE,
  mLIDENT IN CLEOSOBY.LIDENT%TYPE,
  mID_APROVOZNA IN UDRPROVO.ID_PROVOZNA%TYPE,
  mID_ASPRAVCE IN UDRPROVO.ID_ASPRAVCE%TYPE,
  mID_SKUP_CISEL IN UDRPROVO.ID_SKUP_CISEL%TYPE,
  mInser IN CHAR,
  mUpdate IN CHAR,
  mTransakce IN CHAR,
  mTYP_OF_P1 IN VARCHAR2,
  mNazev_ulicevp VARCHAR2,
  mCislo_partner IN cleosoby.cislo_partner%TYPE,
  mId_partner IN cleosoby.id_ext_nap%TYPE
 ) is
  mID_ADR PARADR.ID_ADR%TYPE;
  --mID_OSOB PAROSOBA.ID_OSOB%TYPE;
  --mID_PAR PAROPAR.ID_PAR%TYPE;
  --mHodnotaValue VARCHAR2(63);
  mTYP_OF CHAR(1);
  mJmenoOK CLEOSOBY.NAJMENO%TYPE;
begin

</pre>

**Comment by darold** [comment]
Commit b0eea21 might fix this issue.

**Comment by okbob** [comment]
Sorry for delay - One cycle needs 2hours. I am starting new cycle against last commit. The function TVORBA_NEW_OSOBY_P1 is correct and translated to Postgres.

**Comment by darold** [comment]
Don't worry it is fixed in my test environment but I prefer to have your confirmation on the fix because there is lot of use case with Oracle.

**Comment by okbob** [comment]
It is fixed. Thank you
