### ISSUE TITLE
Broken translation of dbms_output

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#477]
Oracle:
<pre>
     IF POC_ZAZ > 1 THEN
       DBMS_OUTPUT.PUT_LINE( ' POC_ZAZ' || POC_ZAZ  ) ;
     END IF;
</pre>

Ora2pg:
<pre>
     IF POC_ZAZ > 1 THEN
       RAISE NOTICE '%%',  ' POC_ZAZ', POC_ZAZ;
     END IF;
</pre>

%% means %

**Comment by darold** [comment]
Might be fixed with commit 0ba669e.

**Comment by okbob** [comment]
It is fixed:

New transformation:
<pre>
RAISE NOTICE ' POC_ZAZ%', POC_ZAZ;
</pre>
Thank you
