### ISSUE TITLE
Typo-PLPGSQL instead of PLPSQL

### ISSUE THREAD

**Issue by vinpokale** [darold/ora2pg#478]
Hi,

There are some places where PLPSQL is used. I think it should be PLPGSQL. No?
I might be wrong. If it needs to change as PLPGSQL then I will send pull request.
Example:
PLSQL to PLPSQL conversion.
it should be 
PLSQL to PLPGSQL conversion.

Regards,
Vinayak

**Comment by darold** [comment]
Thanks for the report, commit eb4d76e fix the typo.

**Comment by vinpokale** [comment]
Thank you
