### ISSUE TITLE
Error when dumping .sql file into postgres

### ISSUE THREAD

**Issue by asoong-94** [darold/ora2pg#480]
ERROR: function sys_context(unknown, unknown) does not exist
HINT: No function matches the given name and argument types. You might need to add explicit type casts.

This error is getting thrown after i dump my oracle db into 'tables.sql' 

CREATE TABLE ZZZZZ(
	partition_key varchar(12) NOT NULL DEFAULT SYS_CONTEXT('XXXX',ABCDABCDABCD'),
	scenario_id bigint,
	pool_name varchar(30),
	recoverable bigint,
	recoverable_spot bigint,
	scenario_code varchar(30),
	family varchar(12)
) ;

This is the chunk of code that is trying to execute when the error happens, in a previous issue raised, you mentioned that there was code pushed to call the psql equivalent of SYS_CONTEXT(), i used the latest ora2pg.pm, however the error still persists

**Comment by darold** [comment]
This is because the SYS_CONTEXT() is not fully supported. I don't know what is the variable name used but currently Ora2Pg only call to  SYS_CONTEXT('USERENV', ...) on some values. You can find the translation work in file lib/Ora2Pg/PSQL.pm search for: `sub replace_sys_context`
