### ISSUE TITLE
Not correctly transformed queries in trigger

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#481]
<pre>
  if :new.ID_UCEPOLBAN IS null  and  :new.ID_UCEHLABAN IS NOT null THEN
   FOR qSumaPlat IN (
    SELECT  A2.DBANV
    FROM  UCEHLABAN A2
   WHERE :new.ID_UCEHLABAN= A2.ID_UCEHLABAN(+)
      )
  LOOP
</pre>
Produces invalid query

Oracle:
<pre>
TRIGGER "IDES_JMMAJ".UCEPOHYB_BU BEFORE UPDATE
ON  UCEPOHYB
FOR EACH ROW

 
Declare
 mRowSSSHLEDEJ_A  SSSHLEDEJ_A%ROWTYPE;
 mULICE      PARADR.ULICE%TYPE ;
 mCISPOP     PARADR.CISPOP%TYPE ;
 mCISORI     PARADR.CISORI%TYPE ;
 mID_ADR     PARADR.ID_ADR%TYPE ;
 mCISLO      OBPODBMI.CISLO%TYPE ;
 mNAZEV      OBPODBMI.NAZEV%TYPE ;
 mDEFARAJ    OBPODBMI.DEFARAJ%TYPE ;
 mDopln      boolean ;
 mProvozna  RRRUTIL.T_PROVOZNA;
 mChyba boolean; 
 NEVIDIM_TABULKU EXCEPTION;
 PRAGMA EXCEPTION_INIT( NEVIDIM_TABULKU, -04091 );
  micAULICE  PARADR.ULICE%TYPE ;
 micACISPOP PARADR.CISPOP%TYPE ;
 micACISORI PARADR.CISORI%TYPE ;
 mMAZAT_ZJ CISUUCET.MAZAT_ZJ%TYPE; 
 mOK_STAV CHAR(1);
 mPOCET_ORG_STRED NUMBER;
BEGIN

----  ZACATEK DEFAULT CAST

 :new.DATZMENY := SYSDATE;

----  KONEC DEFAULT CAST

  IF :new.pol_castka is null THEN
  
   :new.pol_castka:=:new.epol_castka;
  end if;

  ---UCEDOKLAD_A,UCEPOHYB_A
  ----- TATO VYJIMKA NAHOVNO ALE PROZADIM MUSI BYT
  
if :new.id_UCEDOKLAD_A is NULL then 
   BEGIN
   select id_UCEDOKLAD_A into :new.ID_UCEDOKLAD_A
   from ucedoklad where id_ucedoklad=:new.id_ucedoklad;
   EXCEPTION
        WHEN NO_DATA_FOUND THEN
         :new.ID_UCEDOKLAD_A :=NULL;
        WHEN NEVIDIM_TABULKU THEN
         mChyba :=true;
           
   END;                     
end if;

if :new.id_ucepohyb_a is NULL then 
   BEGIN
   select id_ucepohyb_a into :new.id_ucepohyb_a
   from ucedoklad where id_ucedoklad=:new.id_ucedoklad;
   EXCEPTION
        WHEN NO_DATA_FOUND THEN
         :new.id_ucepohyb_a :=NULL;
        WHEN NEVIDIM_TABULKU THEN
         mChyba :=true;
   END;                     
end if;

---Pokladna
if :new.id_ucehlapok is NULL then 
   BEGIN
   select id_ucehlapok into :new.id_ucehlapok
   from ucedoklad where id_ucedoklad=:new.id_ucedoklad;
   EXCEPTION
        WHEN NO_DATA_FOUND THEN
         :new.id_ucehlapok :=NULL;
        WHEN NEVIDIM_TABULKU THEN
         mChyba :=true;

   END;                     
end if;

if :new.id_ucepolpok is NULL then 
   BEGIN
   select id_ucepolpok into :new.id_ucepolpok
   from ucedoklad where id_ucedoklad=:new.id_ucedoklad;
   EXCEPTION
        WHEN NO_DATA_FOUND THEN
         :new.id_ucepolpok :=NULL;
        WHEN NEVIDIM_TABULKU THEN
         mChyba :=true;
         
   END;                     
end if;

---BANKA
if :new.id_ucehlaban is NULL then 
   BEGIN
   select id_ucehlaban into :new.id_ucehlaban
   from ucedoklad where id_ucedoklad=:new.id_ucedoklad;
   EXCEPTION
        WHEN NO_DATA_FOUND THEN
         :new.id_ucehlaban :=NULL;
        WHEN NEVIDIM_TABULKU THEN
         mChyba :=true;

   END;                     
end if;

if :new.id_ucepolban is NULL then 
   BEGIN
   select id_ucepolban into :new.id_ucepolban
   from ucedoklad where id_ucedoklad=:new.id_ucedoklad;
   EXCEPTION
        WHEN NO_DATA_FOUND THEN
         :new.id_ucepolban :=NULL;
        WHEN NEVIDIM_TABULKU THEN
         mChyba :=true;

   END;                     
end if;

---Faktury
if :new.id_ucehlafak is NULL then 
   BEGIN
   select id_ucehlafak into :new.id_ucehlafak
   from ucedoklad where id_ucedoklad=:new.id_ucedoklad;
   EXCEPTION
        WHEN NO_DATA_FOUND THEN
         :new.id_ucehlafak :=NULL;
        WHEN NEVIDIM_TABULKU THEN
         mChyba :=true;
   END;                     
end if;

if :new.id_ucepolfak is NULL then 
   BEGIN
   select id_ucepolfak into :new.id_ucepolfak
   from ucedoklad where id_ucedoklad=:new.id_ucedoklad;
   EXCEPTION
        WHEN NO_DATA_FOUND THEN
         :new.id_ucepolfak :=NULL;
        WHEN NEVIDIM_TABULKU THEN
         mChyba :=true;
   END;                     
end if;

 ---- lokalizacni udaje 
  -------if :new.ziv is  null or :new.ziv ='A' then 
  --- REN ZNEMNA 21.01.2014
 if :new.ziv is  null or :new.ziv IN ('A','N') then 
  
  mDopln := True;

  ---FAKTURACNI MISTO 
  IF( :new.ID_ODBMISTO IS NOT NULL ) AND ( mDopln = True ) THEN
    BEGIN   
       SELECT ULICE,CISPOP,CISORI , CISLO , NAZEV , ID_ADR , DEFARAJ INTO
              mULICE,mCISPOP,mCISORI , mCISLO , mNAZEV, mID_ADR , mDEFARAJ 
         FROM V_OBPODBMI
         WHERE ID_ODBMISTO = :new.ID_ODBMISTO;
       mRowSSSHLEDEJ_A.AULICE := mULICE;
       mRowSSSHLEDEJ_A.ACISPOP := mCISPOP;
       mRowSSSHLEDEJ_A.ACISORI := mCISORI;
       mRowSSSHLEDEJ_A.ID_ADR := mID_ADR ;
       mRowSSSHLEDEJ_A.DEFARAJ := mDEFARAJ ;
       
       
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
       SELECT  DEFARAJ INTO
               mRowSSSHLEDEJ_A.DEFARAJ 
         FROM OBPODBMI
         WHERE ID_ODBMISTO = :new.ID_ODBMISTO;
          
    END ;
   mDopln := False;

  END IF ;

 --- NAJEMNI VZTAH
  IF( :new.ID_NAJVZTAH IS NOT NULL ) AND ( mDopln = True ) THEN
   SELECT * INTO mRowSSSHLEDEJ_A
     FROM SSSHLEDEJ_A
     WHERE ID_NAJVZTAH = :new.ID_NAJVZTAH
       AND TYP = 'N' ;
   mDopln := False;
  END IF ;

 --- PRVKY
  IF( :new.ID_PRVKU IS NOT NULL ) AND ( mDopln = True ) THEN
   SELECT * INTO mRowSSSHLEDEJ_A
     FROM SSSHLEDEJ
     WHERE ID_PRVKU = :new.ID_PRVKU
       AND TYP = 'K' ;
   mDopln := False;
  END IF ;

 ---- PROSTOR
  IF ( :new.ID_PROSTOR IS NOT NULL ) AND ( mDopln = True ) THEN

   SELECT * INTO mRowSSSHLEDEJ_A
     FROM SSSHLEDEJ_A
     WHERE ID_PROSTOR = :new.ID_PROSTOR
       AND TYP = 'P' ;
   mDopln := False;
  END IF ;

 --- BUDOVA
  IF( :new.ID_STAVOBJ IS NOT NULL ) AND ( mDopln = True ) THEN
   SELECT * INTO mRowSSSHLEDEJ_A
     FROM SSSHLEDEJ_A
     WHERE ID_STAVOBJ = :new.ID_STAVOBJ
       AND TYP = 'B' ;
   mDopln := False;
  END IF ;
 ---- DUM 
  IF( :new.ID_SEGMENT IS NOT NULL ) AND ( mDopln = True ) THEN
   SELECT * INTO mRowSSSHLEDEJ_A
     FROM SSSHLEDEJ_A
     WHERE ID_SEGMENT = :new.ID_SEGMENT
       AND TYP = 'S' ;
   mDopln := False;
  END IF ;

 --- BLOK
  IF( :new.ID_OBJEKT IS NOT NULL ) AND ( mDopln = True ) THEN
   SELECT * INTO mRowSSSHLEDEJ_A
     FROM SSSHLEDEJ_A
     WHERE ID_OBJEKT = :new.ID_OBJEKT
       AND TYP = 'O' ;
   mDopln := False;
  END IF ;

  --- ZAPIS DO TABULKY 
  
   IF :new.ID_ODBMISTO IS NULL THEN  
     :new.ID_OBJEKT := mRowSSSHLEDEJ_A.ID_OBJEKT;
     :new.ID_SEGMENT := mRowSSSHLEDEJ_A.ID_SEGMENT;
     :new.ID_STAVOBJ := mRowSSSHLEDEJ_A.ID_STAVOBJ;
     :new.ID_PROSTOR  := mRowSSSHLEDEJ_A.ID_PROSTOR;
    
     :new.ID_PRVKU := mRowSSSHLEDEJ_A.ID_PRVKU;
     :NEW.ID_NAJVZTAH:= mRowSSSHLEDEJ_A.ID_NAJVZTAH;
   END IF;
   
  :new.AKOD_OBJEKT := mRowSSSHLEDEJ_A.AKOD_OBJEKT;
  :new.AKOD_SEGMENT := mRowSSSHLEDEJ_A.AKOD_SEGMENT ;
  :new.AKOD_BUDOVY := mRowSSSHLEDEJ_A.AKOD_BUDOVY;
  :new.AKOD_PROSTOR := mRowSSSHLEDEJ_A.AKOD_PROSTOR;
  :new.ANAJMENO := mRowSSSHLEDEJ_A.ANAJMENO;
  ---:new.AZNAKPROSTOR := mRowSSSHLEDEJ_A.AZNAKPROSTOR ;
  ---:new.ID_VLASTOBJ := mRowSSSHLEDEJ_A.ID_VLASTOBJ;
  :new.ABYT_NEBYT := mRowSSSHLEDEJ_A.ABYT_NEBYT;
  ---:new.ATYP_PROSTORU := mRowSSSHLEDEJ_A.ATYP_PROSTORU;
  ---:new.AKOD_MISTNOST := mRowSSSHLEDEJ_A.AKOD_MISTNOST  ;
  ---:new.AKOD_TYPMSTN := mRowSSSHLEDEJ_A.AKOD_TYPMSTN ;
  ---:new.AZNAKMIST := mRowSSSHLEDEJ_A.AZNAKMIST ;
  ---:new.ID_ADR := mRowSSSHLEDEJ_A.ID_ADR ;
  :new.AULICE := mRowSSSHLEDEJ_A.AULICE ;
  :new.ACISPOP := mRowSSSHLEDEJ_A.ACISPOP ;
  :new.ACISORI := mRowSSSHLEDEJ_A.ACISORI ;
  ---:new.AZNAKCISORI := mRowSSSHLEDEJ_A.AZNAKCISORI ;
  ---:new.AMISTO := mRowSSSHLEDEJ_A.AMISTO ;
  ---:new.ANAZEV_VLAST := mRowSSSHLEDEJ_A.ANAZEV_VLAST ;
  ---:new.HLAVNI := mRowSSSHLEDEJ_A.HLAVNI;
  ---:new.ID_TYPPRS := mRowSSSHLEDEJ_A.ID_TYPPRS ;
  ---:new.ID_NAZEVPR := mRowSSSHLEDEJ_A.ID_NAZEVPR;
  ---:new.TYP := mRowSSSHLEDEJ_A.TYP ;
  ---:new.DEFARAJ := mRowSSSHLEDEJ_A.DEFARAJ ;
  ---:new.ANAZEV_PRVKU := mRowSSSHLEDEJ_A.ANAZEV_PRVKU ;
  :new.AKOD_PRVKU := mRowSSSHLEDEJ_A.AKOD_PRVKU ;
  ---:new.ASKUPINA_PRVKU := mRowSSSHLEDEJ_A.ASKUPINA_PRVKU ;
  
  ---raise_application_error( -20010 , ' jedu jedu jedu !!! '||:New.ID_APROVOZNA );
  ---GET_PROVOZNA( :New.ID_APROVOZNA , mProvozna ) ; 
  ---:new.NAZSPRAVCE := mProvozna.NAZSPRAVCE ;
  ---:new.NAZPROVOZNA := mProvozna.NAZPROVO ;       
 
   if :new.id_CCLE_DIC is not null then 
   begin
     select trim(dic), trim(rodcisico), trim(najmeno) , trim(ulice), cispop, cisori
     into 
        :new.DIC , :new.ICO , :new.anajmeno , micAULICE , micACISPOP , micACISORI
     from v_cleosoby 
      where id_ccle = :new.id_CCLE_DIC;
      mDopln := False;
     EXCEPTION 
     WHEN NO_DATA_FOUND THEN

     mDopln :=true;
     /*
     if :new.ACISPOP IS NULL THEN
      :new.AULICE  :=micAULICE ;
      :new.ACISPOP :=micACISPOP;
      :new.ACISORI :=micACISORI;
     end if; 
     */
     
   end; 
   
   end if; ---ic_ccle_dic 
  
   if :new.id_CCLE is not null then 
   begin
     select trim(dic), trim(rodcisico), trim(najmeno) , trim(ulice), cispop, cisori
     into 
        :new.DIC , :new.ICO , :new.anajmeno , micAULICE , micACISPOP , micACISORI
     from v_cleosoby 
      where id_ccle = :new.id_CCLE;
      mDopln := False;
     EXCEPTION 
     WHEN NO_DATA_FOUND THEN

     mDopln :=true;

     
   end; 
     if :new.TYP_SUMPOL =  'C' THEN
      :new.AULICE  :=micAULICE ;
      :new.ACISPOP :=micACISPOP;
      :new.ACISORI :=micACISORI;
     end if; 

   
   end if; ---ic_ccle

  end if;

 :new.VARS := trim(:new.VARS);

 :new.DATUM_OST :=:new.UCEDAT;
 
 ---:new.DATUM_OST :=UCEPOHYB_DATUM_OST(:new.ID_UCEPOHYB);
 if :new.ID_UCEPOLBAN IS not null THEN
   FOR qSumaPlat IN (
    SELECT A1.DBANV_POL,
           A2.DBANV
    FROM UCEPOLBAN A1, 
         UCEHLABAN A2
   WHERE 
       :new.ID_UCEPOLBAN= A1.ID_UCEPOLBAN(+) AND
       A1.ID_UCEHLABAN= A2.ID_UCEHLABAN(+)
      )
  LOOP
    :new.DATUM_OST :=:new.UCEDAT;
    --- banka  polozka 
    IF  qSumaPlat.DBANV_POL is not null
    THEN
    :new.DATUM_OST := qSumaPlat.DBANV_POL;
    END IF;
    --- banka hlavicka
    IF  qSumaPlat.DBANV_POL is null
    and qSumaPlat.DBANV is not null
    THEN
    :new.DATUM_OST := qSumaPlat.DBANV;
    END IF;

  END LOOP;     
  
 END IF; ---banka polozka

  if :new.ID_UCEPOLBAN IS null  and  :new.ID_UCEHLABAN IS NOT null THEN
   FOR qSumaPlat IN (
    SELECT  A2.DBANV
    FROM  UCEHLABAN A2
   WHERE :new.ID_UCEHLABAN= A2.ID_UCEHLABAN(+)
      )
  LOOP
    :new.DATUM_OST :=:new.UCEDAT;
    IF  qSumaPlat.DBANV is not null
    THEN
    :new.DATUM_OST := qSumaPlat.DBANV;
    END IF;

  END LOOP;     
  
 END IF; ---banka 
 
 
 IF :new.ID_UCEPOLPOK is not null THEN
 
   FOR qSumaPlat IN (
    SELECT P1.DTDPH, P2.DAT_VYSTAVENI, P2.DAT_PRIJETI 
    FROM  UCEPOLPOK P1,
         UCEHLAPOK P2 
    WHERE 
      :new.ID_UCEPOLPOK= P1.ID_UCEPOLPOK(+) AND
       P1.ID_UCEHLAPOK= P2.ID_UCEHLAPOK(+)

      )
  LOOP
  
    :new.DATUM_OST :=:new.UCEDAT;
   
    --- pokladna  polozka 
    IF  qSumaPlat.DTDPH is not null
    THEN
    :new.DATUM_OST := qSumaPlat.DTDPH;
    END IF;
    --- pokladna hlavicka
    IF  qSumaPlat.DTDPH is null
    and qSumaPlat.DAT_VYSTAVENI is not null
    THEN
    :new.DATUM_OST := qSumaPlat.DAT_VYSTAVENI;
    END IF;

    IF  qSumaPlat.DTDPH is null
    and qSumaPlat.DAT_PRIJETI is not null
    THEN
    :new.DATUM_OST := qSumaPlat.DAT_PRIJETI;
    END IF;
  END LOOP;     

 END IF; 

  IF :new.ID_UCEPOLPOK is null and  :new.ID_UCEHLAPOK IS NOT NULL THEN
 
   FOR qSumaPlat IN (
    SELECT P2.DAT_VYSTAVENI, P2.DAT_PRIJETI 
    FROM  UCEHLAPOK P2 
    WHERE :new.ID_UCEHLAPOK= P2.ID_UCEHLAPOK(+)

      )
  LOOP
  
    :new.DATUM_OST :=:new.UCEDAT;
   
    --- pokladna hlavicka
    IF  qSumaPlat.DAT_VYSTAVENI is not null
    THEN
    :new.DATUM_OST := qSumaPlat.DAT_VYSTAVENI;
    END IF;

    IF qSumaPlat.DAT_PRIJETI is not null
    THEN
    :new.DATUM_OST := qSumaPlat.DAT_PRIJETI;
    END IF;
  END LOOP;     

 END IF; ---pokladna hlavicka

 
 IF :new.ID_UCEPOLFAK is not null THEN
    FOR qSumaPlat IN (
    SELECT P2.DTDPH, P2.DOSLO, P2.DATVYDAN
    FROM  UCEPOLFAK P1,
         UCEHLAFAK P2 
    WHERE 
      :new.ID_UCEPOLFAK= P1.ID_UCEPOLFAK(+) AND
       P1.ID_UCEHLAFAK= P2.ID_UCEHLAFAK(+)

      )
  LOOP
  
    :new.DATUM_OST :=:new.UCEDAT;
  
    --- faktura  polozka 
    IF  qSumaPlat.DTDPH is not null
    THEN
    :new.DATUM_OST := qSumaPlat.DTDPH;
    END IF;

    IF  qSumaPlat.DTDPH is null
    and qSumaPlat.DATVYDAN is not null
    THEN
    :new.DATUM_OST := qSumaPlat.DATVYDAN;
    END IF;

    IF  qSumaPlat.DTDPH is null
    and qSumaPlat.DOSLO is not null
    THEN
    :new.DATUM_OST := qSumaPlat.DOSLO;
    END IF;

  END LOOP;     

 END IF; ---polozka faktury

IF :new.ID_UCEPOLFAK is null and :new.ID_UCEHLAFAK IS NOT NULL THEN
    FOR qSumaPlat IN (
    SELECT P2.DTDPH, P2.DOSLO, P2.DATVYDAN
    FROM  UCEHLAFAK P2 
    WHERE 
       :new.ID_UCEHLAFAK= P2.ID_UCEHLAFAK(+)

      )
  LOOP
  
    :new.DATUM_OST :=:new.UCEDAT;
  
    --- faktura  polozka 
    IF  qSumaPlat.DTDPH is not null
    THEN
    :new.DATUM_OST := qSumaPlat.DTDPH;
    END IF;

    IF  qSumaPlat.DTDPH is null
    and qSumaPlat.DATVYDAN is not null
    THEN
    :new.DATUM_OST := qSumaPlat.DATVYDAN;
    END IF;

    IF  qSumaPlat.DTDPH is null
    and qSumaPlat.DOSLO is not null
    THEN
    :new.DATUM_OST := qSumaPlat.DOSLO;
    END IF;

  END LOOP;     

 END IF; ---polozka faktury
 
 
  --- REN 19.12.2011  POKUD U UCTU NASTAVENO MAZAT ZJ
   IF :new.ID_CISUUCET_MD IS NOT NULL THEN
     SELECT MAZAT_ZJ INTO mMAZAT_ZJ
     FROM CISUUCET    
     WHERE ID_CISUUCET = :new.ID_CISUUCET_MD;
    
     IF mMAZAT_ZJ = 'A' THEN
       :new.ZJ_M := NULL;
       :new.SAP_VST := NULL;
     END IF;  
   END IF;

   IF :new.ID_CISUUCET_D IS NOT NULL THEN
     SELECT MAZAT_ZJ INTO mMAZAT_ZJ
     FROM CISUUCET    
     WHERE ID_CISUUCET = :new.ID_CISUUCET_D;
    
     IF mMAZAT_ZJ = 'A' THEN
       :new.ZJ := NULL;
       :new.SAP_VYS := NULL;
     END IF;  
    END IF;

 
    -- REN PRIDANO 29.11.2012  dodatecne danove priznani 
    ---nove ZJ 3 od 1.1.2015
    IF :new.DTDPH IS NOT NULL THEN
       IF SUBSTR(TRIM(:new.ZJ),1,1) = '3' THEN
          IF :new.UZDROJ IS NULL THEN
             :new.UZDROJ := '0000' || TO_CHAR(:new.DTDPH,'YYMM' );
          END IF;  
       END IF;       
       IF SUBSTR(TRIM(:new.ZJ_M),1,1) = '3' THEN
          IF :new.UZDROJ_M IS NULL THEN
             :new.UZDROJ_M := '0000' || TO_CHAR(:new.DTDPH,'YYMM' );
          END IF;  
       END IF;       
       IF (( SUBSTR(TRIM(:old.ZJ),1,1) = '3' ) AND ( SUBSTR(NVL(TRIM(:new.ZJ),0),1,1) <> '3' )) THEN
         :new.UZDROJ := NULL;
       END IF;

       IF (( SUBSTR(TRIM(:old.ZJ_M),1,1) = '3' ) AND ( SUBSTR(NVL(TRIM(:new.ZJ_M),0),1,1) <> '3' )) THEN
         :new.UZDROJ_M := NULL;
       END IF;
       
       
    END IF;         

  --- doplneni ze strediska ORG_STRD    
    IF :new.ID_CISUSTRD IS NOT NULL THEN

      IF :old.ID_CISUSTRD  IS NOT NULL THEN
         select COUNT(*) INTO mPOCET_ORG_STRED FROM cisustrd
           where id_cisustrd= :old.ID_CISUSTRD and org_strd is not null;
         IF mPOCET_ORG_STRED > 0 THEN
            :new.organizace := NULL;
            :new.organizace_m := NULL;
         END IF;    
      END IF;  

      begin
      select org_strd into :new.organizace_m from cisustrd
      where id_cisustrd= :new.ID_CISUSTRD and org_strd is not null;
      EXCEPTION
           WHEN OTHERS THEN
           mOK_STAV:='';       
      end;
      
      begin
      select org_strd into :new.organizace from cisustrd
      where id_cisustrd= :new.ID_CISUSTRD and org_strd is not null;     
      EXCEPTION
           WHEN OTHERS THEN
           mOK_STAV:='';       
      end;
    
    ELSE
      IF :old.ID_CISUSTRD  IS NOT NULL THEN
         select COUNT(*) INTO mPOCET_ORG_STRED FROM cisustrd
           where id_cisustrd= :old.ID_CISUSTRD and org_strd is not null;
         IF mPOCET_ORG_STRED > 0 THEN
            :new.organizace := NULL;
            :new.organizace_m := NULL;
         END IF;    
      END IF;  
    END IF;
 
 
END ;
</pre>

**Comment by darold** [comment]
Current translation of this part is:
```
  if NEW.ID_UCEPOLBAN IS null  and  NEW.ID_UCEHLABAN IS NOT null THEN
   FOR qSumaPlat IN (
    SELECT  A2.DBANV
    FROM ucehlaban a2,
WHERE NEW.ID_UCEHLABAN = A2.ID_UCEHLABAN  )
  LOOP
```
there is an extra comma at end of the FROM clause. If this is what you've reported commit 533ae4b might solve the issue.

**Comment by okbob** [comment]
looks fixed. Thank you
