### ISSUE TITLE
Invalid translation of instr function

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#482]
Oracle:
<pre>
   --- do prvniho vyskytu - vnazvu VOD-vodne_Najpred
   mKOD:= substr(:new.nazev,1,instr(:new.nazev,'-',1)-1);
</pre>

Ora2pg:
<pre>
288        --- do prvniho vyskytu - vnazvu VOD-vodne_Najpred
289        mKOD:= substr(NEW.nazev,1,POSITION('-',1 in NEW.nazev)-1);
</pre>

Should be:
<pre>
 ... POSITION('-' IN NEW.nazev)
</pre>
Three, Four parametric instr function cannot be translated to Postgres simply see https://www.postgresql.org/docs/9.5/static/plpgsql-porting.html . This transformation can be disabled too, when Orafce is installed. It has good support of instr function.

**Comment by darold** [comment]
Commit 0daeadc fixes this issue when the start position is 1. I will work on other cases later.

**Comment by okbob** [comment]
yes, this case is fixed. Thank you
