### ISSUE TITLE
Missing feature - SQL%ROWCOUNT

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#483]
In this moment Ora2pg doesn't support `SQL%ROWCOUNT`. 
The implementation is not simple, because PLpgSQL equivalent is plpgsql statement `GET DIAGNOSTICS`.
Oracle:
<pre>
      UPDATE NAJVZTAH
        SET PORADI = NULL,
           PLATNY = 'A',
           POCUZA = POCUZA - 1 ,
           UZAVRIT = NULL
        WHERE ID_NAJVZTAH = :old.ID_NAJVZTAH
         AND  PORADI = :old.PORADI ;

       IF SQL%ROWCOUNT = 1 THEN
          SELECT POCUZA INTO mPOCUZA
            FROM NAJVZTAH
            WHERE ID_NAJVZTAH = :old.ID_NAJVZTAH ;
</pre>

Postgres:
<pre>
DECLARE rowcount int;
...
UPDATE ...
GET DIAGNOSTICS rowcount = ROW_COUNT;
IF rowcount = 1 THEN
  ...
</pre>

**Comment by okbob** [comment]
Partial replacement can be support of SQL%FOUND, that can be simply translated like `FOUND`

**Comment by darold** [comment]
Commits 6fff7e1 and f98da42 add these translation.

**Comment by okbob** [comment]
looks well
