### ISSUE TITLE
regression - storing procedure call

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#484]
Again there is useless using record variable for CALL procedure with OUT variables.
<pre>
>   _ora2pg_r RECORD;
> a boolean;
27389c28210
<      mRecGET_UNI_RECORD  := GET_UNI_RECORD_OTHER_TRANS( mSql, mRecGET_UNI_RECORD );
---
>      SELECT * FROM GET_UNI_RECORD_OTHER_TRANS( mSql, mRecGET_UNI_RECORD ) INTO STRICT _ora2pg_r; mRecGET_UNI_RECORD  := _ora2pg_r.mRecGET_UNI_RECORD;
</pre>

This issue was fixed in code from Friday.

**Comment by darold** [comment]
Right, I have reapplied all friday's patches :-(

**Comment by okbob** [comment]
It is fixed. Thank you
