### ISSUE TITLE
Problem with Configuration

### ISSUE THREAD

**Issue by KhosaYousuf** [darold/ora2pg#485]
Trying to connect to database: dbi:Oracle:host=xxxxxx;sid=xxxxx;port=xxxx
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
Retrieving partitions information...
....
Looking how to retrieve data from ACCTGLOANDATA...
Fetching all data from ACCTGLOANDATA tuples...
Dumping data from table ACCTGLOANDATA into PostgreSQL...
Setting client_encoding to UTF8...
Disabling synchronous commit when writing to PostgreSQL...
DEBUG: Formatting bulk of 10000 data for PostgreSQL.
DEBUG: Creating output for 10000 tuples
DEBUG: Sending COPY bulk output directly to PostgreSQL backend
DBD::Pg::db do failed: ERROR:  relation "acctgloandata" does not exist at /usr/local/share/perl5/Ora2Pg.pm line 11492.
FATAL: ERROR:  relation "acctgloandata" does not exist
Aborting export...

**Comment by darold** [comment]
You have to import all tables into PostgreSQL before proceeding to data import. Commands:
```
mkdir mig_tables
ora2pg -t TABLE -c config/ora2pg.conf -b mig_tables -o table.sql
```
will give you all DDL to do so.

**Comment by KhosaYousuf** [comment]
Thanks

**Comment by KhosaYousuf** [comment]
Hello,

I have created tables on postgres, now I am facing this issue,
can you please help me on this


[>                        ]  17/444 total rows (3.8%) - (5 sec., avg: 3 recs/sec).
Looking how to retrieve data from COMPOSITEMODEL...
Fetching all data from COMPOSITEMODEL tuples...
Dumping data from table COMPOSITEMODEL into PostgreSQL...
Setting client_encoding to UTF8...
Disabling synchronous commit when writing to PostgreSQL...
DEBUG: Formatting bulk of 10000 data for PostgreSQL.
DEBUG: Creating output for 10000 tuples
DEBUG: Sending COPY bulk output directly to PostgreSQL backend
Extracted records from table COMPOSITEMODEL: total_records = 0 (avg: 0 recs/sec)

[>                        ]  17/444 total rows (3.8%) - (5 sec., avg: 3 recs/sec).
Dumping partition table COMPUTEBATCH...
Looking how to retrieve data from COMPUTEBATCH partition R0...
Fetching all data from R0 tuples...
Dumping data from table R0 into PostgreSQL...
Setting client_encoding to UTF8...
Disabling synchronous commit when writing to PostgreSQL...
DEBUG: Formatting bulk of 10000 data for PostgreSQL.
DEBUG: Creating output for 10000 tuples
DEBUG: Sending COPY bulk output directly to PostgreSQL backend
DBD::Pg::db do failed: ERROR:  column "batchnumber" of relation "r0" does not exist at /usr/local/share/perl5/Ora2Pg.pm line 11492.
FATAL: ERROR:  column "batchnumber" of relation "r0" does not exist
Aborting export...

**Comment by darold** [comment]
Hi,

Sorry for the response delay, have you found the reason of this failure? I seem that you had a difference between the Oracle and PostgreSQL schema. HAve you fixed it?

Regards,
