### ISSUE TITLE
substr to substring

### ISSUE THREAD

**Issue by nitinmverma** [darold/ora2pg#488]
Hi,

I know you had a functionality to replace substr to substring and in recent release you had removed it. I am using your utility with Amazon Redshift which is actually build over postgres and your utility is very helpful for us. But in redshift still substring only works and not substr. I request you to keep an option for backward compatibility option since now our product code has started failing since you removed that feature. Please add that and help us.

**Comment by darold** [comment]
Last commit 70070e1 allows the backaward compatibility on substr vs substring but you will have to add the PG_SUPPORTS_SUBSTR in your ora2pg.conf file and set it to 0.

Let me know.

**Comment by nitinmverma** [comment]
Hi,

Thanks this worked, Awesome did not expect such a quick turnaround from
you. May I know your name?

input:

SELECT NVL(SUBSTR('ABC_blah', 0, INSTR('ABC_blah', '_')-1), 'ABC_blah') AS
output
  FROM DUAL;


Got output for redshift:

SELECT coalesce(substring('ABC_blah' from 0 for position('_' in
'ABC_blah')-1), 'ABC_blah') AS
output
;


Regards,
Nitin

**Comment by nitinmverma** [comment]
Worked on Redshift Postgre

input: SELECT NVL(SUBSTR('ABC_blah', 0, INSTR('ABC_blah', '_')-1), 'ABC_blah') AS output FROM DUAL; Got output for redshift: SELECT coalesce(substring('ABC_blah' from 0 for position('_' in 'ABC_blah')-1), 'ABC_blah') AS output ;

**Comment by darold** [comment]
Sorry, I've updated my github profile to set my full name and my location.

**Comment by nitinmverma** [comment]
Thanxs Gilles, good utility
