### ISSUE TITLE
Is it possible setup ORACLE_DSN to use SSL?

### ISSUE THREAD

**Issue by bjornbak** [darold/ora2pg#49]
Hi,

We're migrating from one hosting provider to another and at the same time migrating from Oracle to Postgresql.

I'm running the ora2pg script in the receiving end so I do the conversion at the new and bigger cpu's.

We've setup a SSH tunnel from the new to the old provider like described here: http://osdir.com/ml/lang.perl.modules.dbi.general/2008-01/msg00073.html

But I'm not satisfied with the throughput. It's only running at 2/3 the speed of doing a local oracle to local postgresql conversion.

And at the start of every new table it has a long pause and almost a stand still when migration a CLOB to a TEXT.

Both providers are connected to the same 100's / Mb if not Gb's backbone so the connection should be good enough..

I been advised not to use the SSH tunnel as it might be part of the network latency but I don't want to transfer our data through the internet unencrypted.

Oracle has the possibility to SSL encrypt the database connection: http://docs.oracle.com/html/B10812_06/chapter5.htm#BIICGDGC

I'm waiting for the old hosting provider to set this up but in the meantime I wanted to find out how to setup ora2pg for this..

Look at the source code of Ora2Pg.pm it doesn't seem to be possible?

And I not sure if DBD is up to it either even if ora2pg was patched?

Unless DBD/DBI::Oracle automatically use SSL if connected to an SSL port. Do you know if that is true?

**Comment by sanyamsinghal** [comment]
@darold does ora2pg not support SSL connections to Oracle or its the same?

**Comment by darold** [comment]
I don't know, if this is something that is handled by DBD::Oracle then yes, otherwise no. On my side when I have to encrypt the communication between the Ora2Pg host and the Oracle instance I use SSL tunneling but I have never encountered an Oracle instance with native SSL encryption so I'm not sure if it is possible or not.
