### ISSUE TITLE
Order of parameters not respected with if one of them has a default value

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#490]
Hello,

I have a strange behaviour with procedures having a relatively simple signature: they are not translated with the same order of parameters, and sometimes randomly.

In the full code I am going to send you, let's take the procedure:
```
PROCEDURE SUB_REN_MANAGE_VARS_RDM( v_abo_data IN OUT GEASTRUCT.A_GCL_OP_DATA%ROWTYPE
								, p_mode IN BINARY_INTEGER default null
								, p_type_of_gcl_operation IN T_TYPE_OF_GCL_OPERATION.type_of_gcl_operation_id%TYPE
								) IS
```
it is sometimes translated with args 2 and 3 mixed like this:
```
CREATE OR REPLACE FUNCTION pck_gcl.sub_ren_manage_vars_rdm ( v_abo_data INOUT GEASTRUCT.A_GCL_OP_DATA , p_type_of_gcl_operation T_TYPE_OF_GCL_OPERATION.type_of_gcl_operation_id%TYPE , p_mode integer default null
 ) AS $body$
```
and sometimes translated with the correct order of params: 
```
(v_abo_data, p_mode, p_type_of_gcl_operation)
```

For two others you will see in the sample, the arguments are apparently always mixed:
```
    PROCEDURE SUB_REN_MANAGE_VARS_KO1( p_type_of_gcl_operation IN T_TYPE_OF_GCL_OPERATION.type_of_gcl_operation_id%TYPE
								, p_mode IN BINARY_INTEGER default null
								, v_abo_data IN OUT GEASTRUCT.A_GCL_OP_DATA%ROWTYPE
								) IS
```
```
    PROCEDURE SUB_REN_MANAGE_VARS_KO2( 
								p_type_of_gcl_operation IN T_TYPE_OF_GCL_OPERATION.type_of_gcl_operation_id%TYPE
								, p_mode IN BINARY_INTEGER default null
								, v_abo_data IN OUT GEASTRUCT.A_GCL_OP_DATA%ROWTYPE
								) IS
```

I tried renaming them so that a name is never included in another... no effect.

Solving this issue would be very helpful for us, because at present, we have to check manually a lot of procedure translations that are not as "simple" as these examples..

Best regards,
Eric.

**Comment by darold** [comment]
Hi Eric,

This is normal, unlink in pl/sql all input parameters following a parameter with a default value must have default values as well this is why Ora2Pg is extracting all parameters with default values and put them at end of the parameter list.

I agree that this change must be clearly identified in the export, I will add a comment in the output to signal that the parameter list order have been changed.

**Comment by edelanoe** [comment]
Hello Gilles,
I understand the Postgres rule, but in some cases it can lead to a functional error: the parameter order in the function call is not the argument order in the declaration. This error is technically invisible (no exception thrown) if the parameters are of similar types.
I would perfer a clear error: a bad order of function parameters would be immediately visible at compilation or first execution, with an explicit error message. Then we know we have to change arg order in the Oracle source code.
Could there be a configuration option about that ? (with complete explanation where you may use my text)

Regards,
Eric

**Comment by darold** [comment]
Commit 7967733 add this feature, the warning is sent to stderr but also in the header of the translated function as comments with the original order of the parameters.
