### ISSUE TITLE
Space between operators fails in postgre (redshift and vertica)

### ISSUE THREAD

**Issue by nitinmverma** [darold/ora2pg#493]
Hi,

We have a query such as select a,b from abc where a < = 15; -- Please note space between operator < = cause failure on postgre but works well in oracle. Do we have a property which we can set to solve this or pretty print SQL conversion to handle such issues?

output expected : select a,b from abc where a <= 15; -- space removed between operator

NV

**Comment by darold** [comment]
Last commit c84bb05 might solve this issue, please use latest development code.

**Comment by nitinmverma** [comment]
Thanks Gilles!!! worked closing this.

Again what a speedy turnaround... this tool will make it big soon :)
