### ISSUE TITLE
TRUNC Oracle function should get converted to DATE_TRUNC

### ISSUE THREAD

**Issue by nitinmverma** [darold/ora2pg#494]
The below oracle query:
SELECT TRUNC(TO_DATE('27-05-92','DD-MM-YY'), 'YEAR') "New Year" from dual;
  

Should get converted to postgre as DATE_TRUN and also the YEAR part to be first parameter
SELECT DATE_TRUNC('YEAR',TO_DATE('27-05-92','DD-MM-YY'))"New Year";

Same goes for WEEK, DAY etc with TRUNC

**Comment by darold** [comment]
Does DATE_FUNCTION_REWRITE is enabled in your ora2pg.conf?

**Comment by nitinmverma** [comment]
Hi,

I tried changing it but does not work for TRUNC function which should be
converted DATE_TRUN and parameters swapped positions as given in my example:

# By default Ora2pg rewrite add_month(), add_year() and date_trunc()
functions
# set it to 0 to not translate those functions if it breaks code.
DATE_FUNCTION_REWRITE   0

Please help fix this.

**Comment by darold** [comment]
Commit fdb3f8b might solve some missing translation of trunc() into date_trunc(). Please give a try to latest developement code.

**Comment by nitinmverma** [comment]
Thanks it works now :)
