### ISSUE TITLE
Hardcoded Value in Group By

### ISSUE THREAD

**Issue by nitinmverma** [darold/ora2pg#496]
Hi,

If there is a hardcoded "string" value alone in a GROUP BY function such as show below: The query is valid and runs in Oracle even thought it does not make sense to be part of GROUP By clause. However Postgre Fails this - Invalid operation: non-integer constant in GROUP BY;

SELECT
  'MONTH' PERIODICITY,
  TO_CHAR(DDI.CREATION_DATE,'YYYY-MM') AS PERIOD,
  DDI.LEGAL_ENTITY_ID                  AS ORG,
FROM DEVSFD_SFSD DDI
WHERE DDI.LEGAL_ENTITY_ID           =DISI.LEGAL_ENTITY_ID
AND DDI.INVOICE_ID                  =DISI.INVOICE_ID
GROUP BY 'MONTH',
  TO_CHAR(DDI.CREATION_DATE,'YYYY-MM'),
  DDI.LEGAL_ENTITY_ID;

Solution: Remove out the String Literal from the group by as shown below:

SELECT
  'MONTH' PERIODICITY,
  TO_CHAR(DDI.CREATION_DATE,'YYYY-MM') AS PERIOD,
  DDI.LEGAL_ENTITY_ID                  AS ORG,
FROM DEVSFD_SFSD DDI
WHERE DDI.LEGAL_ENTITY_ID           =DISI.LEGAL_ENTITY_ID
AND DDI.INVOICE_ID                  =DISI.INVOICE_ID
GROUP BY  TO_CHAR(DDI.CREATION_DATE,'YYYY-MM'),
  DDI.LEGAL_ENTITY_ID;

**Comment by nitinmverma** [comment]
Hi, Any updated on this?

**Comment by darold** [comment]
Won't be fixed until we have a parser, now it is impossible to solves using regex. Despite the fact that this might be something not common to introduce a constant into a GROUP BY clause, removing the constant breaks more complex form of GROUP BY clause.
