### ISSUE TITLE
DECODE to CASE corrupting complex query

### ISSUE THREAD

**Issue by nitinmverma** [darold/ora2pg#498]
Hi,

We have a complex query attached below: 

While converting this query the utility is corrupted the entire query:

Following issues:
1. DECODE is converted to CASE but corrupted the query as below:
AND rnii.Region_ID = Decode(129,101,1,102,2,103,2,108,2,109,3,115,1,128,3,129,2,130,2,131,4)
              GROUP BY
              rnii.Snapshot_day
              ,rnii.ASIN
              ,rnii.Order_ID    

GET CONVERTS INTO 
AND rnii.Region_ID = CASE WHEN 129=101 THEN 1 WHEN 129=102 THEN 2 WHEN 129=103 THEN 2 WHEN 129=108 THEN 2 WHEN 129=109 THEN 3 WHEN 129=115 THEN 1 WHEN 129=128 THEN 3 WHEN 129=129 THEN 2 WHEN 129=130 THEN 2 WHEN 129=131 THEN 4 END 
              **;BY**
              rnii.Snapshot_day
              ,rnii.ASIN
              ,rnii.Order_ID

2.  Decode below to wrong case
AND decode(mpa.MARKETPLACE_ID,1,101,3,102,4,103,5,108,6,109,3240,128,7,115,35691,129,44551,130,44571,131) in (129) 

CONVERTS INTO

AND CASE WHEN mpa.MARKETPLACE_ID=1 THEN 101 WHEN mpa.MARKETPLACE_ID=3 THEN 102 WHEN mpa.MARKETPLACE_ID=4 THEN 103 WHEN mpa.MARKETPLACE_ID=5 THEN 108 WHEN mpa.MARKETPLACE_ID=6 THEN 109 WHEN mpa.MARKETPLACE_ID=3240 THEN 128 WHEN mpa.MARKETPLACE_ID=7 THEN 115 WHEN mpa.MARKETPLACE_ID=35691 THEN 129 WHEN mpa.MARKETPLACE_ID=44551 THEN 130 WHEN mpa.MARKETPLACE_ID=44571 THEN 131 END ; (129) 

3. REGEX_SUBSTR converted to REGEX_SUBSTRING -- There is no function as REGEX_SUBSTRING it should have no change and remain as REGEX_SUB

1)	REGEXP_SUBSTR(Shipment_ID,'[0-9]{13}') GET CONVERT INTO REGEXP_substring(Shipment_ID from '[0-9]{13}')

NOTE: Since DECODE works in postgre (redshift) can you share a FLAG To avoid this conversion as QUICK FIX for us. We dont want to convert DECODE to CASE

Please fix this ASAP as this is breaking our prod.

**Comment by nitinmverma** [comment]
[4453257.txt](https://github.com/darold/ora2pg/files/1199691/4453257.txt) -- this is the full sql for your reference

**Comment by darold** [comment]
Commit 6dee62b 6dee62b might solve the issue.

**Comment by nitinmverma** [comment]
I am testing other cases, looks like it might work. However I dont see the REGEXP_SUBSTR() fixed, its converting it to REGEXP_SUBSTRING() there is no function, it should unchanged and stay as REGEXP_SUBSTR(). Please fix it

**Comment by darold** [comment]
It is now fixed in commit 5d2c321

**Comment by nitinmverma** [comment]
REGEXP_SUBSTR() is fixed. I was testing the CASE to DECODE and its not working for another case now as show below: 
input query -- see there is a space between the region_id and comma alias for decode.
select DECODE
(T1.L_ENTITY_ID,'A',1,'B',2) **REGION_ID ,** col2, col3 from table_a;

Ouput is a corrputed query with semi-colon added and alias disappeared as show below: 
select CASE WHEN T1.L_ENTITY_ID='A' THEN 1 WHEN T1.L_ENTITY_ID='B' THEN 2 **END;,** col2, col3 from table_a;

Please fix it.

As stated earlier decoded as oracle are supported in postgre so please provide configuration flag at the ora2pg.conf to stop decode to case conversion. There are lot of issues with this conversion and why convert if its already supported.

**Comment by nitinmverma** [comment]
Thanks for the update. Decode does work in posture Amazon redshift and HP
vertica versions and Sure plz let me know once you fix the case issue with
space after alias name. I will test and confirm on the same.

Regards,
Nitin

**Comment by darold** [comment]
Hi,

Commit ba752bd might solve all issues with decode() translation. Actually the problem doesn't come from the decode() replacement whcih works pretty well in all cases but from the code try to remove a potential function name after a END keyword. This might have been fixed in this commit.

Regards,

**Comment by nitinmverma** [comment]
Works now after new code fix. Closing it
