### ISSUE TITLE
NON ANSCII to ANSCII query conversion corruption

### ISSUE THREAD

**Issue by nitinmverma** [darold/ora2pg#499]
We have a query such as below:
SELECT 'NA' AS REGION_ID,PAYEES.*,TERMS.NAME AS PAYMENT_TERM ,TERMS.DESCRIPTION AS PAYMENT_TERM_DESC
 from **PPL.O_PAYEE_SITES PAYEES**,
**(SELECT DISTINCT PAYEE_SITE_ID FROM PPL.PC_PAYEE_TO_OFA_ORG_MAPPING) PAYEE_MAP,**
**B.O_AP_TERMS TERMS**
WHERE PAYEES.PAYEE_SITE_ID=PAYEE_MAP.PAYEE_SITE_ID
AND PAYEES.TERMS_ID=TERMS.TERM_ID(+)
AND PAYEE_MAP.PAYEE_SITE_ID NOT IN (
5705,1234); 

Above query 3 tables are involved - One join is equi and other is left outer (+) but end query is corrupted and as only 2 tables as LEFT OUTER JOIN ANSII

The entire SUB Query and INNER JOIN went missing

Result:

SELECT 'NA' AS REGION_ID,PAYEES.*,TERMS.NAME AS PAYMENT_TERM ,TERMS.DESCRIPTION AS PAYMENT_TERM_DESC
 FROM ppl.o_payee_sites payees
LEFT OUTER JOIN b.o_ap_terms terms ON (PAYEES.TERMS_ID = TERMS.TERM_ID)
WHERE PAYEES.PAYEE_SITE_ID=PAYEE_MAP.PAYEE_SITE_ID  AND PAYEE_MAP.PAYEE_SITE_ID NOT IN (
5705,1234);

Please help fix this.

**Comment by darold** [comment]
Commit ff0cbda might solve this issue.

**Comment by nitinmverma** [comment]
Did not work, still the same issue output is below:

SELECT 'NA' AS REGION_ID,PAYEES.*,TERMS.NAME AS PAYMENT_TERM ,TERMS.DESCRIPTION AS PAYMENT_TERM_DESC
 FROM ppl.o_payee_sites payees
LEFT OUTER JOIN b.o_ap_terms terms ON (PAYEES.TERMS_ID = TERMS.TERM_ID)
WHERE PAYEES.PAYEE_SITE_ID=PAYEE_MAP.PAYEE_SITE_ID  AND PAYEE_MAP.PAYEE_SITE_ID NOT IN (
5705,1234);

**Comment by darold** [comment]
Please update to and install latest development code, it has been fixed.

**Comment by nitinmverma** [comment]
I have compared the code change from git and I see the code changes are in
my PLSQL file in lib folder but code didnt work for my query.

**Comment by darold** [comment]
You have to install it again:
```
perl Makefile.PL
make
sudo make install
```
then to clean the git repository after that:
```
make clean
rm Makefile.old
```

**Comment by nitinmverma** [comment]
Yes, I do the perl Makefile.pl and make install everytime you I download
new code.

I tried the clean git also but still see the same issues, can you please
send me the output of the query after you ran the latest script?

Regards,
Nitin

**Comment by darold** [comment]
cat test_wrong_alias.sql 
```
SELECT 'NA' AS REGION_ID,PAYEES.*,TERMS.NAME AS PAYMENT_TERM ,TERMS.DESCRIPTION AS PAYMENT_TERM_DESC
from PPL.O_PAYEE_SITES PAYEES,
(SELECT DISTINCT PAYEE_SITE_ID FROM PPL.PC_PAYEE_TO_OFA_ORG_MAPPING) PAYEE_MAP,
B.O_AP_TERMS TERMS
WHERE PAYEES.PAYEE_SITE_ID=PAYEE_MAP.PAYEE_SITE_ID
AND PAYEES.TERMS_ID=TERMS.TERM_ID(+)
AND PAYEE_MAP.PAYEE_SITE_ID NOT IN (
5705,1234);
```

```
gilles@gilles-W230ST:/home/git/test_ora2pg$ ora2pg -t QUERY -i test.sql -o -
-- Generated by Ora2Pg, the Oracle database Schema converter, version 18.1
-- Copyright 2000-2017 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=mydb.mydom.fr;sid=SIDNAME

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;

SELECT 'NA' AS REGION_ID,PAYEES.*,TERMS.NAME AS PAYMENT_TERM ,TERMS.DESCRIPTION AS PAYMENT_TERM_DESC
FROM (SELECT DISTINCT PAYEE_SITE_ID FROM PPL.PC_PAYEE_TO_OFA_ORG_MAPPING) payee_map, ppl.o_payee_sites payees
LEFT OUTER JOIN b.o_ap_terms terms ON (PAYEES.TERMS_ID = TERMS.TERM_ID)
WHERE PAYEES.PAYEE_SITE_ID=PAYEE_MAP.PAYEE_SITE_ID  AND PAYEE_MAP.PAYEE_SITE_ID NOT IN (
5705,1234);
```

Are you using file input (-i) or does the query is taken by Ora2Pg from a function or other code directly from Oracle?

**Comment by nitinmverma** [comment]
I used another server and it worked closing this.
