### ISSUE TITLE
Alias Added to condition which is not a sub query 

### ISSUE THREAD

**Issue by nitinmverma** [darold/ora2pg#500]
Input Query
SELECT   CASE_ID  FROM F.CNTCT_CASES_F A
  INNER JOIN FD.CNTCT_YUMA_DISPUTE_STATUS_MAP B
  ON A.CASE_STATUS_WID = B.ROW_ID  
  AND TRUNC(CASE_CREATION_DT) <= TO_DATE('{RUN_DATE_YYYY/MM/DD}','YYYY/MM/DD')
     AND 
     (
		B.YUMA_CASE_STATUS <> 'RS' and 	B.YUMA_CASE_STATUS == 'X'
     );

Output: It has a Alias name added to a normal query which is not sub-query and hence the query fails to run on database server.

SELECT
  CASE_ID
  FROM F.CNTCT_CASES_F A
  INNER JOIN FD.CNTCT_YUMA_DISPUTE_STATUS_MAP B
  ON A.CASE_STATUS_WID = B.ROW_ID  
  AND TRUNC(CASE_CREATION_DT) <= TO_DATE('{RUN_DATE_YYYY/MM/DD}','YYYY/MM/DD')
     AND (
		B.YUMA_CASE_STATUS <> 'RS' and 	B.YUMA_CASE_STATUS == 'X'
     ) alias2;

Fix: The utility should not added alias as I see there are brackets around AND so it looks to make this as subquery but please check for ( SELECT as keyword at parse time.

**Comment by darold** [comment]
It now might be fixed with commit 33cd7a0.

**Comment by nitinmverma** [comment]
I still see the same issue and is not fixed yet, the converted query output has alias name
SELECT   CASE_ID  FROM F.CNTCT_CASES_F A
  INNER JOIN FD.CNTCT_YUMA_DISPUTE_STATUS_MAP B
  ON A.CASE_STATUS_WID = B.ROW_ID
  AND TRUNC(CASE_CREATION_DT) <= TO_DATE('{RUN_DATE_YYYY/MM/DD}','YYYY/MM/DD')
     AND (
		B.YUMA_CASE_STATUS <> 'RS' and 	B.YUMA_CASE_STATUS == 'X'
     ) alias2;

**Comment by darold** [comment]
Please update to and install latest development code, it has been fixed.

**Comment by nitinmverma** [comment]
I see the code change in my downloaded file and i took it from the commit:
Line 416 in the lib/PLSQL.pm the code snippet has AND and OR. So I am using
the commited code but dont see the query output right yet. please help

[image: Inline image 3]

**Comment by nitinmverma** [comment]
I used another server and it worked closing this.
