### ISSUE TITLE
ora2pg v18.1 very slow on CLOB 

### ISSUE THREAD

**Issue by lpenet** [darold/ora2pg#501]
I recently upgraded to v18.1.

The speed of replication from Oracle to postgres dramatically dropped for tables having CLOB columns.
What I mean by dramatically is a 100 factor when compared to similar tables without CLOB. Without clobs, I can copy 8000-14000 rows per sec. Wit h clobs, it falls to 80-100.

Ex :

Looking how to retrieve data from LECTURE...
Fetching all data from LECTURE tuples...
DEBUG: Formatting bulk of 10000 data for PostgreSQL.
DEBUG: Creating output for 10000 tuples
Dumping data from LECTURE to file: /tmp/insert_data_dosleg.sql
Extracted records from table LECTURE: total_records = 10000 (avg: 10000 recs/sec)
DEBUG: Formatting bulk of 10000 data for PostgreSQL.
DEBUG: Creating output for 10000 tuples
Dumping data from LECTURE to file: /tmp/insert_data_dosleg.sql
Extracted records from table LECTURE: total_records = 14621 (avg: 14621 recs/sec)

[=>                       ]   73495/1049996 total rows (7.0%) - (11 sec., avg: 6681 recs/sec).
Looking how to retrieve data from LOI...
Fetching all data from LOI tuples...

DEBUG: Formatting bulk of 10000 data for PostgreSQL.
DEBUG: Creating output for 10000 tuples
Dumping data from LOI to file: /tmp/insert_data_dosleg.sql
Extracted records from table LOI: total_records = 10000 (avg: 84 recs/sec)
DEBUG: Formatting bulk of 10000 data for PostgreSQL.
DEBUG: Creating output for 10000 tuples
Dumping data from LOI to file: /tmp/insert_data_dosleg.sql
Extracted records from table LOI: total_records = 11083 (avg: 83 recs/sec)

I have CLOB in these tables for a long time - even before starting to use the first versions of ora2pg. So, I wonder which change has occured.
I think I was using v16.2 before, but I am only 90% sure (sorry for not noting the former version).

I read the doc and the changelog and found nothing relevant. I tried to set

NO_LOB_LOCATOR	0

and 

NO_LOB_LOCATOR	1

(setting it to 0 seemed strange to me) but noticed no change

What can I do to get my fast ora2pg back ? Apart from installing an old version, of course.

**Comment by darold** [comment]
Hi Ludovic,

Please use latest development code available here https://github.com/darold/ora2pg/archive/master.zip 

Regards,

**Comment by lpenet** [comment]
Thank you for the quick reply.

I just installed it. I noticed no difference. What input can I give you to help diagnose the pb ?

**Comment by lpenet** [comment]
I just tested with 17.0, and it was still ok. 500 records / sec : that's acceptable with clobs.

**Comment by darold** [comment]
Are you sure that this CLOB and not BLOB in these tables? If not, how many CLOB column are defined in this table? Do you know the mean size of these LOB?

**Comment by lpenet** [comment]
I did a dichotomy search and found that the pb was introduced with 17.5 :

OK with 17.3 (500 recs/sec).
OK with 17.4 (527 recs/sec).
Not ok with 17.5 (81 recs/sec).
Not ok with 17.6 (81 recs/src)
Not ok with 18.0 (80 recs/sec).

(giving results in order for easier reading).

**Comment by darold** [comment]
Ok, thanks for the archaeological research in the old version, I will see what have changed between 17.4 and 17.5 but it might be on escape_copy() function or _escape_lob() as I guess you use the COPY type of action, not INSERT.

**Comment by lpenet** [comment]
Yes, I use the COPY type.

And I use the following client variable :+1: 

export NLS_LANG=FRENCH_FRANCE.WE8ISO8859P1
export CLIENT_ENCODING=LATIN9

Maybe some (unwanted) transcoding ?

**Comment by darold** [comment]
Have you tried without these environment variables?

**Comment by darold** [comment]
Also disable any setting in ora2pg.conf about NLS_LANG and CLIENT_ENCODING.

**Comment by lpenet** [comment]
Le 2017-08-11 15:47, Gilles Darold a écrit :
> Have you tried without these environment variables?
Well, I will do that to help you, but, as you guess, I need them. :-)

Ludovic

**Comment by darold** [comment]
Yes this is just to see if there is an extra workload with those variables, but I don't think so.

If I remember well you need these variables because there was error when dumping to files, this will be the opportunity to see if they have been solved :-)

**Comment by lpenet** [comment]
Well, no, it is to match my Oracle DB instance settings.

I just tried, and it does not make things faster. Alas.

**Comment by darold** [comment]
It seems that the performances lost was introduced by commit e911ea9: `Fix export of CLOBs and NCLOB that was truncated to 64Kb when NO_LOB_LOCATOR=1`

This can be explain if your previous export was not including all data due to this bug. But I guess that this was not the case. Also the default is NO_LOB_LOCATOR disabled so it should only append if you had activate the directive. In this case setting NO_LOB_LOCATOR to 0 might solve the issue but if I understand well you have tried without any performances changes?

**Comment by lpenet** [comment]
All my clobs are smaller than 64kb. So, they were not truncated.

I dit the test again with v18.0.

With NO_LOB_LOCATOR set to 1, I have : 

<pre>
Looking how to retrieve data from LOI...
Fetching all data from LOI tuples...
DEBUG: Formatting bulk of 10000 data for PostgreSQL.
DEBUG: Creating output for 10000 tuples
Dumping data from LOI to file: /tmp/insert_data_dosleg.sql
Extracted records from table LOI: total_records = 10000 (avg: 87 recs/sec)
DEBUG: Formatting bulk of 10000 data for PostgreSQL.
DEBUG: Creating output for 10000 tuples
Dumping data from LOI to file: /tmp/insert_data_dosleg.sql
Extracted records from table LOI: total_records = 11083 (avg: 87 recs/sec)
</pre>

With NO_LOB_LOCATOR set to 0, I have : 
<pre>
Looking how to retrieve data from LOI...
Fetching all data from LOI tuples...
DEBUG: Formatting bulk of 10000 data for PostgreSQL.
DEBUG: Creating output for 10000 tuples
Dumping data from LOI to file: /tmp/insert_data_dosleg.sql
Extracted records from table LOI: total_records = 10001 (avg: 526 recs/sec)
DEBUG: Formatting bulk of 10000 data for PostgreSQL.
DEBUG: Creating output for 10000 tuples
Dumping data from LOI to file: /tmp/insert_data_dosleg.sql
Extracted records from table LOI: total_records = 11083 (avg: 527 recs/sec)
</pre>

So, it seems that I did a mistake in my previous test and that setting NO_LOB_LOCATOR to 0 solves the issue.

**Comment by lpenet** [comment]
If I may add a comment : this is still slow compared to export of rows without clobs.

For 99,99% of my needs, having those clobs columns empty would be alright. Would it be difficult to add an option to create clob and blob columns, but to leave them empty (not extract them) ?

**Comment by darold** [comment]
Ok, thanks for the feeback. I don't know the kind of harware and resources it have but the export speed for CLOB is now what I used to see unless you have hundred of CLOB columns. I meet this kind of speed when exporting BLOB because they need to be fully encoded to be inserted into bytea.

I think you can speed up your CLOB export by first setting DATA_LIMIT to 500 and use -J 4 -j 4 for example. Multiprocess might help a lot in your case.

I don't think I will add a directive to disable LOB export unless some other users ask for this feature too. Note that, as a workaround, you can already do that by using MODIFY_STRUCT at data export time and in removing all CLOB/BLOB columns, in this case nothing will be inserted in those columns.

**Comment by lpenet** [comment]
Using MODIFY_STRUCT seems to be a better solution than a big hammer smashing everything, thank you.

I set -J 4 -j 4 . It has the expected effect for other tables, but not the "LOI" table. Maybe there is something preventing it with lobs ?

**Comment by lpenet** [comment]
One last comment : MODIFY_STRUCT allows to specify columns to include. A similar option to exclude some of them would be great.

**Comment by darold** [comment]
> I set -J 4 -j 4 . It has the expected effect for other tables, but not the "LOI" table. Maybe there is something preventing it with lobs ?

This is probably because Ora2Pg can not find a numeric primary or unique key, in this case you have to set DEFINED_PK to specify the column to use to split the query.
