### ISSUE TITLE
Oracle user defined types problem with inserts

### ISSUE THREAD

**Issue by Bulva** [darold/ora2pg#504]
Hi,

I am migrating structure of database and data to PostgreSQL. I am able to import structure of the database (tables, sequences, types...) but when I want to populate the tables I have a problem with INSERTs where is user defined type. For example, I have a type named `geomext`:

```
CREATE TYPE geomext AS (
   x               DOUBLE PRECISION,
   y               DOUBLE PRECISION,
   font           VARCHAR (255),
   text           VARCHAR (1000)
);
```
INSERT created by ora2pg looks something like that:
`INSERT INTO test_table (id,sdo_geom,geomext) VALUES (1,ST_GeomFromText('POINT (-539696.23 -1155827.79)', 5514),ROW(0,0,1,967/19));`
`INSERT INTO test_table (id,sdo_geom,geomext) VALUES (1,ST_GeomFromText('POINT (-539696.23 -1155827.79)', 5514),ROW(0,0,1,967/-));`

The problem is 967/19 without quotes results in 50 but this should be a VARCHAR. In the second example of INSERT there is not a second number and because it's not a VARCHAR it results in syntax error.

Is there any configuration parameter which uses quotes around the value? Or is it possible to resolve this problem somehow?

Thanks

**Comment by darold** [comment]
Hi

Do you have the same problem when using COPY export type instead of INSERT?

Regards,

**Comment by Bulva** [comment]
Yeah, unfortunately totally same result.

Thank you for you comment

**Comment by darold** [comment]
OK, can you export the content of this table only using the -d option at ora2pg command and post here the output of the command? For example:
```
ora2pg -c config/ora2pg.conf -t INSERT -d -a test_table
```
type CTRL+C when some line have been dumped, this just to have the debug output.

**Comment by Bulva** [comment]
This what ora2pg said in debug mode:
```Ora2Pg version: 18.1
Trying to connect to database: dbi:Oracle:host=my-db1;sid=myuser
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
Retrieving table information...
[1] Scanning table TEST_TABLE (2850328 rows)...
Trying to connect to database: dbi:Oracle:host=my-db1;sid=myuser
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
Retrieving partitions information...


Dropping foreign keys of table TEST_TABLE...
Looking how to retrieve data from TEST_TABLE...
Data type GEOMEXT is not native, searching on custom types.
        Found Type: GEOMEXT
Looking inside custom type GEOMEXT to extract values...
Fetching all data from TEST_TABLE tuples...
DEBUG: Formatting bulk of 10000 data for PostgreSQL.
DEBUG: Creating output for 10000 tuples
Dumping data from TEST_TABLE to file: inserts_geomext_output.sql
Extracted records from table TEST_TABLE: total_records = 10000 (avg: 2500 recs/sec)```

I can't use Linux for this particular migration so I am using Strawberry Perl (5.26.0.1) on Windows 7 now, Could Strawberry Perl cause this problem?

**Comment by darold** [comment]
Ok, this was what I want to see "Data type GEOMEXT is not native, searching on custom types.". When Ora2Pg see a non PostgreSQL native type it tries to look at the user defined type definition and retrieve native types. Here it seems that is not able to detect those native types. I will try yo reproduce the issue.

No, Strawberry Perl should not be the problem, the only limitation to run Ora2Pg on Windows is that multiprocess is disabled, so if you have a huge amount of data it will takes a very long time to export.

**Comment by darold** [comment]
Hi Petr,

Sorry for the delay but last commit 49fe499 might solve this issue.

**Comment by Bulva** [comment]
It looks fine, very nice work Darold. Thanks a lot
