### ISSUE TITLE
data type array migration, wrong inserts

### ISSUE THREAD

**Issue by lupynos** [darold/ora2pg#505]
Hello, we migrate data from oracle array data type to postgres array and find out that the inserts are not properly generated:

Example1 json (using `MODIFY_TYPE            TABLE:symbology_tokens:array`):
`'("{,id_okres_ukazatel2#0(id_okres_ukazatel2_1)}")'` -- there is the extra comma at the beginning

Example2 row:
`ROW(E'id_okres_ukazatel4#0(id_okres_ukazatel4_8)')` -- this code seems to be not functional at all, missing parentheses? -- `ROW(E'{id_okres_ukazatel4#0(id_okres_ukazatel4_8)}')`

type in postgres was created like:
`CREATE TYPE our_array AS (OUR_ARRAY varchar(1000) [500]);`

**Comment by darold** [comment]
Hi,

The export of data stored in a nested user defined type was completely broken. Commit 73e2547 might fix this issue.

Let me know, there must be some not handled cases.

**Comment by lupynos** [comment]
Thanks Darold! Is much better now, I'm testing it and I'll close this issue soon.

**Comment by lupynos** [comment]
Hello, thanks for quick check. Now the situation is a bit different.

We have to use our defined type, not from ora2pg migration. So the type/domain is now like:
`CREATE DOMAIN our_array AS VARCHAR[];`

The master version ora2pg now creates Example1 with MODIFY_TYPE to array:
`ROW('{id_okres_ukazatel4#0(id_okres_ukazatel4_8)}')`

Example2 without MODIFY_TYPE:
`ROW(E'id_okres_ukazatel4#0(id_okres_ukazatel4_8)')`

So not of this is working for us, but the Example1 is closer now, just use it without the ROW() definition.

What do you suggest?
Thank you.

**Comment by darold** [comment]
Please add the original description of the Oracle user defined type and the value of MODIFY_TYPE you are using. Also can you explain why you are using MODIFY_TYPE on a composite type?

**Comment by lupynos** [comment]
In Oracle the type is defined as
```
CREATE OR REPLACE TYPE our_array AS 
  VARRAY (10000) OF VARCHAR2(4000);
```
Value
`MODIFY_TYPE            TABLE:symbology_tokens:array`

Using modify_type simply to get result we can insert into postgres.
But if there is way without using modify_type, it's better.

**Comment by darold** [comment]
If I understand well you have a user defined type in Oracle that you don't want to reproduce as is in PostgreSQL but as a simple varchar array? So you are expecting that changing the destination type into ARRAY transform the output from ROW() to '{....}'. Am I on the right understanding way?

**Comment by lupynos** [comment]
In Oracle it is user defined type, but in fact it is simple varchar array, the user type is just like alias. I think you must recognize varchar array in user defined type and use ARRAY or {}:
```
ARRAY['id_okres_ukazatel4#0(id_okres_ukazatel4_8)']
'{id_okres_ukazatel4#0(id_okres_ukazatel4_8)}'
```
but I think ARRAY is better for future use in composite types like (ARRAY[ROW(1,2)]).
We have also example of use composite type. Types were created by postgres native script:
```
CREATE TYPE geomtype AS (
   TYPE          NUMERIC (6),
   source_type   NUMERIC (4)
);
CREATE DOMAIN geomtype_array AS _geomtype;
```
Working insert:
`Insert into test values (ARRAY[ROW(1003,1)]::geomtype_array);`

**Comment by darold** [comment]
Ok, this is more a data transformation feature than a simple column data type change. Ora2Pg doesn't have build in data transformation support yet unless using REPLACE_QUERY. But for this dedicated case I think it could be possible to add this ARRAY destination type.

**Comment by darold** [comment]
Commit 82b18c8 add this feature. You need to use text[] instead of ARRAY in the MODIFY_TYPE directive, here is the documentation of this feature:

```
MODIFY_TYPE
[...]

        If the column's type is a user defined type Ora2Pg will autodetect
        the composite type and will export its data using ROW(). Some Oracle
        user defined types are just array of a native type, in this case you
        may want to transform this column in simple array of a PostgreSQL
        native type. To do so, just redefine the destination type as wanted
        and Ora2Pg will also transform the data as an array. For example,
        with the following definition in Oracle:

                CREATE OR REPLACE TYPE mem_type IS VARRAY(10) of VARCHAR2(15);
                CREATE TABLE club (Name VARCHAR2(10),
                        Address VARCHAR2(20),
                        City VARCHAR2(20),
                        Phone VARCHAR2(8),
                        Members mem_type
                );

        custom type "mem_type" is just a string array and can be translated
        into the following in PostgreSQL:

                CREATE TABLE club (
                        name varchar(10),
                        address varchar(20),
                        city varchar(20),
                        phone varchar(8),
                        members text[]
                ) ;

        To do so, just use the directive as follow:

                MODIFY_TYPE     CLUB:MEMBERS:text[]

        Ora2Pg will take care to transform all data of this column in the
        correct format. Only arrays of characters and numerics types are
        supported.
```

I hope this will fill your needs.

**Comment by lupynos** [comment]
Working. Darold, many thanks for your improvements and time.
