### ISSUE TITLE
Escape character \ was not supported in Redshift

### ISSUE THREAD

**Issue by bhoot929** [darold/ora2pg#509]
Original Query:
```
select * from table_name oat where oat.name like '%\%%' ESCAPE '\'
```
Converted query:
```
select * from table_name oat where oat.name like '%\%%' ESCAPE '\';
```
For above query to work in Redshift it should be:
```
select * from table_name oat where oat.name like '%\%%' ESCAPE '\'';
```
Please update

**Comment by darold** [comment]
It seems that the default is two backslashes ('\\'), if I understand well your last query must be written:
```
select * from table_name oat where oat.name like '%\\%%' ESCAPE '\\';
```
PostgreSQL just allow a single character as escape string and again this is very specific to RedShift.

**Comment by bhoot929** [comment]
yes you are right.
Can you please let me know if it is possible for you to resolve using ora2pg?

**Comment by darold** [comment]
As I've said this is very specific to RedShift this mean that I should add a configuration directive to specify the destination database type. This is possible but I will not take on my spare time to develop specific code for commercial database.
