### ISSUE TITLE
Substrb  & to_char without format not supported in Redshift

### ISSUE THREAD

**Issue by bhoot929** [darold/ora2pg#510]
Query:
select substrb('abcdef,1,2);

Converted query:
select substrb('abcdef,1,2);

Working Query:
select substring('abcdef',1,2) 

------------------
To_Char : Query having to_char without any format will not work in Redshift.
Example:

Query:
select to_char(1234234) 
Converted query:
select to_char(1234234) 
But working query:
select 1234234::varchar
So this should be casted as varchar

**Comment by darold** [comment]
Translation of SUBSTRB() have been added in commit 8d81eb8, thanks for the report.

I will look want can be done for the to_chart() translation but I agree that a simple cast could be done.

**Comment by bhoot929** [comment]
Thanks for SUBSTRB()  solution.
It's working fine. 
Can you please provide solution for to_Char please asap.

**Comment by darold** [comment]
Commit 0afe7c6 translate to_char() without format into a simple cast to varchar.

**Comment by bhoot929** [comment]
Working fine.
Thanks . Closing the issue.
