### ISSUE TITLE
line comment doesn't disable multiline comment

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#511]
I found some untranslated code due wrong interpretation of commented comments:
<pre>
                                   ---/* REN 16.12.2010 ZKOUSKA TEST NA KOLURC
                                   BEGIN
                                      SELECT MT.ID_UCEPARPOL , MT.ID_CISUUCET_MD5 , MT.ID_CISUUCET_D5 ,MT.ID_CISUUCET_MD22 ,
                                             MT.ID_CISUUCET_D22 ,MT.ID_CISUUCET_MD0 ,MT.ID_CISUUCET_D0 ,
                                             MT.ID_CISUUCET_MD ,MT.ID_CISUUCET_D , A1.KOEFICIENT  ,
                                             MT.ID_CISDPH,A1.ZJ ,A1.ZJD ,A1.PROCENT ,
                                             MT.ID_CISUUCET_HZMD,MT.ID_CISUUCET_HZD ,
                                             MT.ID_CISUDAN , A2.KOD_POPIPR , A1.SAP_VST ,A1.SAP_VYS
                                        INTO mID_UCEPARPOL, mID_CISUUCET_MD5 , mID_CISUUCET_D5 ,mID_CISUUCET_MD22 ,
                                             mID_CISUUCET_D22 ,mID_CISUUCET_MD0 ,mID_CISUUCET_D0 ,
                                             mID_CISUUCET_MD ,mID_CISUUCET_D , mKOEF_DPH ,
                                             mID_CISDPH ,mZJ ,mZJD , mPROCENT,
                                             mID_CISUUCET_HZMD,mID_CISUUCET_HZD,
                                             mID_CISUDAN ,mKOD_POPIPR , mSAP_VST , mSAP_VYS
                                       FROM UCEPARPOL MT, CISDPH A1 , CISDRUHPRA A2
                                       WHERE MT.ID_UCEPARHLA = mID_UCEPARHLA
                                         AND MT.ID_CISDPH = A1.ID_CISDPH(+)
                                         AND MT.ID_CISDRUHPRA = A2.ID_CISDRUHPRA(+)
                                         AND MT.ID_KOLURC = mID_KOLURC
                                         AND ROWNUM < 2;
                                    EXCEPTION
                                      WHEN NO_DATA_FOUND THEN
                                        mID_UCEPARPOL := NULL;
                                    END;
</pre>
The problem is in wrong interpretation of line
<pre>
---/*
</pre>
It should be just line comment, but Ora2pg find multiline comment and don't translate following code.

**Comment by darold** [comment]
Commit 77014fc might solve this issue.

**Comment by okbob** [comment]
Now, all one line comments are removed. This issue is fixed, but users, probably, should not want to lost lot of comments :).

**Comment by darold** [comment]
Damned, sorry commit b56432f terminate the patch. I must be tired, I don't understand why I have left this patch incomplete :-)

**Comment by darold** [comment]
Second error in this patch and fixed in commit c4fc24d.

**Comment by okbob** [comment]
It is fixed. Thank you. 

I am not sure which commit does it. But now, the procedure transformation needs 2x more time. The Saturday run needed about 100 minutes and now it needed about 150 minutes.
