### ISSUE TITLE
date_Trunc not working

### ISSUE THREAD

**Issue by bhoot929** [darold/ora2pg#512]
Input 
select trunc(sysdate-84,'IW')

Converted
**select date_trunc('IW', LOCALTIMESTAMP - interval '84 days')** 

In redshift, there is no parameter like **'IW' but it should be 'W' only**

Working query:
select date_trunc(**'W'**, LOCALTIMESTAMP - interval '84 days') 

Please update.

**Comment by darold** [comment]
Commit b712ee6 might fix the date_trunc conversion.

**Comment by bhoot929** [comment]
Working fine. Closing issue. 
Thanks
