### ISSUE TITLE
Install_driver<oracle> failed

### ISSUE THREAD

**Issue by MeriemBo** [darold/ora2pg#514]
I'm trying to install Ora2pg on a virtual machine , but when I try the command : 

ora2pg -t SHOW_VERSION -c config/ora2pg.conf , I keep getting this error. Any ideas on how to fix it ? thank you 

![image](https://user-images.githubusercontent.com/20017065/29864327-37529a0a-8d6a-11e7-8fb6-5eeb4ec5c57d.png)

**Comment by darold** [comment]
Hi,

I'm not a Windows expert but it seems that you have a 32bit windows VM and perhaps you have installed a 64bit Instant client? Also take care to define the PATH, LD_LIBRARY_PATH and ORACLE_HOME in your environment variables.

If you use a VM why not using a Linux one? This will work better and you will have more help I guess.

Regards,

**Comment by MeriemBo** [comment]
Hello , 
Thank you . I don't actually have the choice , I ve been asked to work on this 64bits windows VM . I checked the environment variables , they all seem correct .

**Comment by darold** [comment]
Well in this case there is something wrong in your installation. I can't really help more here, perhaps you can find some solution here http://www.perlmonks.org/?node_id=1072094

**Comment by MeriemBo** [comment]
Thank you sir.
