### ISSUE TITLE
Error when trying to package ora2pg 18.1 into rpm file 

### ISSUE THREAD

**Issue by jpeep44** [darold/ora2pg#515]
Hi,

I'm trying to package ora2pg 18.1 into rpm file on CentOS 7.3  following explanation from https://github.com/darold/ora2pg/blob/master/packaging/README.

So, I downoaded https://sourceforge.net/projects/ora2pg/files/latest/download  (**ora2pg-18.1.tar.bz2**) into /root/rpmbuild/SOURCES.

Then I ran  💯 
  -   "rpmbuild -bb ora2pg.spec" 
             ->  error message "erreur : échec de stat sur /root/rpmbuild/SOURCES/ora2pg.spec: Aucun fichier ou dossier de ce type"
  -  rpmbuild -bb /root/rpmbuild/SOURCES/ora2pg-18.1/packaging/RPM/ora2pg.spec 
            -> erreur : Fichier /root/rpmbuild/SOURCES**/v18.0.tar.gz** : Aucun fichier ou dossier de ce type

Finaly, 
  - I updated file  /root/rpmbuild/SOURCES/ora2pg-18.1/packaging/RPM/ora2pg.spec  changing 18.0 to 18.1 and .gz to .bz2
  - I also moved /root/rpmbuild/SOURCES/**ora2pg-18.1.tar.bz2** to /root/rpmbuild/SOURCES/**v18.1.tar.bz2**
  - cd /root/rpmbuild/SOURCES/ora2pg-18.1/packaging/RPM 
    rpmbuild -bb ora2pg.spec

So I get rpm file  ~/rpmbuild/RPMS/noarch/ora2pg-18.1-1.el7.centos.noarch.rpm

Could you, please, confirm the rpm I get is correct ? 
If yes, is there a way to avoid these manual manipulations by fixing the ora2pg.spec file ? 

Is using rpm file for installing oa2pg the recommended  method ? 
 
Many thanks for your help
Best Regards,
Jean-Pierre

**Comment by darold** [comment]
If you want the RPM for the official release you'd better use the package provided through the PGDG repository at https://yum.postgresql.org/ and install it with a simple `yum ora2pg`.

After installing the package I recommend you to upgrade to v18.2 as soon as possible when it will be available as there is lot of bugs fixes and improvements. Or if you want get the development code from github.

Best regards,

**Comment by JeeIPI** [comment]
Many thanks for your quick answer. 

I fully agree the best way is to use the PGDG repository. 
I must precise, I'm testing  in PostgreSQL 10. 

So, this is what I tried:

 yum install ora2pg
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.crazyfrogs.org
 * extras: centos.mirrors.benatherton.com
 * updates: centos.mirror.ate.info
Resolving Dependencies
--> Running transaction check
---> Package ora2pg.noarch 0:18.1-1.rhel7 will be installed
--> Processing Dependency: perl(String::Random) for package: ora2pg-18.1-1.rhel7.noarch
--> Processing Dependency: perl(DBD::Oracle) for package: ora2pg-18.1-1.rhel7.noarch
--> Finished Dependency Resolution
Error: Package: ora2pg-18.1-1.rhel7.noarch (pgdg10-updates-testing)
           Requires: perl(String::Random)
Error: Package: ora2pg-18.1-1.rhel7.noarch (pgdg10-updates-testing)
           Requires: perl(DBD::Oracle)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

For me, String::Random and DBD::Oracle are already installed  :
<-------------
>find / -name Random.pm -print
/usr/local/share/perl5/String/Random.pm

 >find / -name Oracle.pm -print
/usr/local/lib64/perl5/DBD/Oracle.pm

and  the following perl strict runs fine  :

#!/usr/bin/perl
    use strict;
    use String::Random;
-------------------------------------------------->

So, I'm unsure why 'yum install ora2pg' is failing. 

I tried to do the same on Debian but I didn't find ora2pg package .in PGDG 10 repository ...

apt-get install ora2pg
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ora2pg


(cat /etc/apt/sources.list.d/pgdg.list
deb http://apt.postgresql.org/pub/repos/apt sid-pgdg-testing 10 )

Sorry for this too long post.
Many thanks for your help.
Best regards,
Jean-Pierre

**Comment by darold** [comment]
Does String::Random and DBD::Oracle have been installed manually or using CPAN, not with yum?

Note that String::Random is no more used so you don't need it to be installed.

With yum it seems not possible to disable the dependencies so perhaps you can use the following:
```
wget https://yum.postgresql.org/testing/10/redhat/rhel-7-x86_64/ora2pg-18.1-1.rhel7.noarch.rpm
rpm -Uvh --nodeps ora2pg-18.1-1.rhel7.noarch.rpm
```
If you have the Oracle InstantClient and DBD::Oracle installed this should simply works.

**Comment by JeeIPI** [comment]
Many thanks for this answer. 
I have no time for testing this solution in a immediate way. But, I'll try to do it as soon as possible. For now,  I do a complete manual ora2pg install.  So, I can work with ora2pg 18.2.

Many thanks for your great work.
Jean-Pierre

**Comment by JeeIPI** [comment]
Please, tell me if you prefer I close this issue as I'm unsure when I will be able to work again on it. 

Best Regards,
Jean-Pierre
