### ISSUE TITLE
ERROR:type "number" does not exist;

### ISSUE THREAD

**Issue by Keshavkumbham** [darold/ora2pg#516]
**ORACLE:**  SELECT CAST( column_name AS NUMBER) ; 
AFTER CONVERSION:
SELECT CAST( column_name AS NUMBER);
working solution: SELECT CAST( column_name AS NUMERIC);

Since there is no number datatype in postgreSQL.

**Comment by darold** [comment]
Commit 4ac5b48 might solves this issue.

**Comment by Keshavkumbham** [comment]
Commit 4ac5b48  solves this issue but it failed when there is another function in cast.
For instance, consider below example.
QUERY:
select   CAST(coalesce(2,0) AS NUMBER)       AS Legal_Entity_ID;

Please look into it.
Thanks

**Comment by darold** [comment]
Yes, sorry I would have test this case too. Fixed with commit f41a529.

**Comment by Keshavkumbham** [comment]
Yeah, Thanks.
