### ISSUE TITLE
NESTED TO_DATE ISSUE;

### ISSUE THREAD

**Issue by Keshavkumbham** [darold/ora2pg#517]
**_ORACLE_**:  
SELECT ADD_MONTHS(TO_DATE(TO_DATE(sysdate,'YYYY/MM/DD HH24:MI:SS'),'DD-MON-YY'),-13) FROM DUAL;
**# CONVERTED:** SELECT TO_DATE(TO_DATE(sysdate,'YYYY/MM/DD HH24:MI:SS'),'DD-MON-YY') + -13*'1 month'::interval;
**# CORRECT**: SELECT TO_DATE(TO_DATE(sysdate,'YYYY/MM/DD HH24:MI:SS'),'YYYY/MM/DD') + -13*'1 month'::interval;

Since the outer to_date considers the result of inner to_date as a string, so format change for outer to_date alters the meaning of the query. 

so in these cases we need to make sure that format of todate is same.

**Comment by darold** [comment]
Thanks for this report but I don't think this kind of automatic transformation is possible easily. This will remain something manual. Of course here in this case it is pretty easy but nothing is just simple as that in Oracle.

**Comment by okbob** [comment]
When it is possible, is better to clean Oracle side before migration to Postgres - `TO_DATE(sysdate, 'YYYY/MM/DD HH24:MI:SS')` should be replaced by `trim(sysdate).

**Comment by darold** [comment]
Commit 68ee610 translate call to call to TO_DATE(LOCALTIMESTAMP,...) to TO_DATE(LOCALTIMESTAMP::text,...).

**Comment by darold** [comment]
Note that this will not solves the next issue with the wrong format, it has to be solved on oracle side.
