### ISSUE TITLE
ora2pg -t TEST

### ISSUE THREAD

**Issue by venkatabn** [darold/ora2pg#518]
Hi, 

I am attempting to run ora2pg to compare the object count and the row count across Oracle and PostgreSQL instances which runs into issues. Hope someone can help !

Here are the details - 

I am running : ora2pg -c configfile -t TEST --count_rows >> migration_diff.txt

can i make ora2pg access only those tables listed in the ALLOW parameter ? we are only migrating specific tables from a big list of tables, we would need ora2pg to avoid scanning all the unwanted tables other than the tables listed in the ALLOW parameter - is that possible ?

Also, another issue is that - i get the count of number of indexes and constraints always "0". 
I am using the exact same config i used to do the data migration. 

Thanks !

Regards,
Ven

**Comment by darold** [comment]
You have to upgrade to latest development code or wait tomorrow for the release of v18.2 to solves the second issue. For the first issue, it is already possible to limit tests to the allowed objects but only in the Oracle side. Such filter on the PostgreSQL side still need to be done.

**Comment by venkatabn** [comment]
Thanks for the response. Will test out the version 18.2

**Comment by venkatabn** [comment]
I see the latest release version 18.2 and have installed it. For the second issue reported : to get the accurate count of Indexes and Constraints - do i need to do any changes to the config or the command ?

I just tried  doing the following and i see no difference -

ora2pg -c configfile -t TEST >> migration_diff.txt

I still get indexes and constraints count as "0". Thanks !

**Comment by venkatabn** [comment]
Do not worry about this. This issue is resolved. It seems that EXPORT_SCHEMA parameter needs to be changed.

**Comment by venkatabn** [comment]
I am re-opening this issue - the other problem seems to that the schema name in CAPS in the config. Upon changing this to lower case problem seems to have resolved irrespective of EXPORT_SCHEMA parameter change. I can provide further information on what i have been monitoring on postgresql if required.

**Comment by darold** [comment]
Commit  358513f force to lowercase schema name.

**Comment by venkatabn** [comment]
Ah ok. Will check that out. Thanks !
