### ISSUE TITLE
semicolon required if there are comments at end of the query.

### ISSUE THREAD

**Issue by Keshavkumbham** [darold/ora2pg#519]
query1:
SELECT 'TEST' 
---asedfkhasdlf
----afsdfaf
query2: 
SELECT 'TEST' ;
---asedfkhasdlf
----afsdfaf

query1 doesnot work because there are comments at the end of query.

**Comment by darold** [comment]
If you have the single query1 in a file it should work even if the semicolon is after the comments, but if you have more queries in a file and no semicolon this will never works. Ora2Pg need the statement terminator to distinguish between queries.

**Comment by Keshavkumbham** [comment]
yeah thanks
