### ISSUE TITLE
Reserved words as Alias names in Redshift

### ISSUE THREAD

**Issue by bhoot929** [darold/ora2pg#520]
Original:
select sysdate AUTHORIZATION;
Converted:
Select LOCALTIMESTAMP AUTHORIZATION;

The above converted query will not work since it is using Redshift Reserved key word AUTHORIZATION.

Working Query:
Select LOCALTIMESTAMP  as AUTHORIZATION;

List of all the keywords can be found below:
http://docs.aws.amazon.com/redshift/latest/dg/r_pg_keywords.html

Please let me know if it is possible

**Comment by darold** [comment]
This fail too on a regular PostgreSQL database. Actually there is no ckeck of reserved keywords use in queries or PL/PGSQL code, this check is limited to object name in the DDL. Of course this could be done but I think it will result in lot of performances lost and usually it don't require too much manual rewrite.

The other thing that might be done and can help in this case is to force the use of the AS keyword in the column aliases. This work still have to be done.
