### ISSUE TITLE
problem with TO_TIMESTAMP_TZ conversion.

### ISSUE THREAD

**Issue by Keshavkumbham** [darold/ora2pg#522]
Hi,
### oracle: 
 select TO_TIMESTAMP_TZ ( TO_CHAR (LAST_UPDATED, 'YYYY/MM/DD HH24:MI:SS') || ' GMT', 'YYYY/MM/DD HH24:MI:SS TZR') AT TIME ZONE 'US/PACIFIC' from table_name;
### converted:
select to_timestamp( TO_CHAR(LAST_UPDATED, 'YYYY/MM/DD HH24:MI:SS') || ' GMT', 'YYYY/MM/DD HH24:MI:SS TZR') AT TIME ZONE 'US/PACIFIC' from table_name;

**Comment by darold** [comment]
Commit 535bdcf might fix this issue.

**Comment by Keshavkumbham** [comment]
Thanks @darold Closing this issue.
