### ISSUE TITLE
unwanted replacement = by IS

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#523]
Oracle part:
<pre>
  UPDATE upapicokv
   SET  zav = NULL,
       POHL = NULL;
</pre>
Is translated to:
<pre>
11        UPDATE upapicokv
12         SET  zav  = NULL,
13             POHL  IS NULL;
</pre>
In this case, it is assignment so using `IS` is unwanted

**Comment by darold** [comment]
Fixed in commit 759d169

**Comment by okbob** [comment]
Unfortunately it doesn't help - here is source code:
<pre>
 CREATE OR REPLACE procedure IDES_JMMAJ.PG_RRR_PUSTIT_PRED_MIGRACI is
begin

  UPDATE upapicokv
   SET  zav = NULL,
       POHL = NULL;

  EXECUTE IMMEDIATE 'ALTER TABLE upapicokv MODIFY POHL NUMBER( 30,2)';

  EXECUTE IMMEDIATE  'ALTER TABLE upapicokv MODIFY ZAV NUMBER( 30,2)';

  EXECUTE IMMEDIATE  'ALTER TABLE CISLIMENA DROP COLUMN LIMIT ';

  EXECUTE IMMEDIATE  'ALTER TABLE POMRENE DROP CONSTRAINT POMRENE_CSKUPINA_FK_DES ';


  EXECUTE IMMEDIATE  'DROP INDEX SSSFUNEV_PODM_FCE ';



end ;
</pre>

**Comment by darold** [comment]
Works for me, here is the transaltion:
```
CREATE OR REPLACE FUNCTION pg_rrr_pustit_pred_migraci () RETURNS VOID AS $body$
BEGIN

  UPDATE upapicokv
   SET  zav  = NULL,
       POHL  = NULL;
  EXECUTE 'ALTER TABLE upapicokv MODIFY POHL NUMBER( 30,2)';
  EXECUTE  'ALTER TABLE upapicokv MODIFY ZAV NUMBER( 30,2)';
  EXECUTE  'ALTER TABLE CISLIMENA DROP COLUMN LIMIT ';
  EXECUTE  'ALTER TABLE POMRENE DROP CONSTRAINT POMRENE_CSKUPINA_FK_DES ';
  EXECUTE  'DROP INDEX SSSFUNEV_PODM_FCE ';
end;
$body$
LANGUAGE PLPGSQL
;
```

**Comment by okbob** [comment]
2017-09-07 0:58 GMT+02:00 Gilles Darold <notifications@github.com>:

> Works for me, here is the transaltion:
>
> CREATE OR REPLACE FUNCTION pg_rrr_pustit_pred_migraci () RETURNS VOID AS $body$
> BEGIN
>
>   UPDATE upapicokv
>    SET  zav  = NULL,
>        POHL  = NULL;
>   EXECUTE 'ALTER TABLE upapicokv MODIFY POHL NUMBER( 30,2)';
>   EXECUTE  'ALTER TABLE upapicokv MODIFY ZAV NUMBER( 30,2)';
>   EXECUTE  'ALTER TABLE CISLIMENA DROP COLUMN LIMIT ';
>   EXECUTE  'ALTER TABLE POMRENE DROP CONSTRAINT POMRENE_CSKUPINA_FK_DES ';
>   EXECUTE  'DROP INDEX SSSFUNEV_PODM_FCE ';
> end;
> $body$
> LANGUAGE PLPGSQL
> ;
>
>
I'll recheck it - maybe there is some white space that breaks
transformation - this can be lost when it is copied by clipboard.

**Comment by okbob** [comment]
It is fixed - I didn't do "git pull".
Thank you very much
