### ISSUE TITLE
Encoding of output import file

### ISSUE THREAD

**Issue by Bulva** [darold/ora2pg#525]
Hi Darold,

we are migrating from Oracle to PosgreSQL, unfortunately on Windows. But because of the company network, we can't use Linux here. We are using UTF8 on Oracle and PostgreSQL with special characters for the Czech language. Output import file from ora2pg on Windows has **cp1250** encoding and when we want to import data using psql we need to convert this file to UTF8, then the data are imported good (if we set encoding to the client on UTF8).

I read this [issue](https://github.com/darold/ora2pg/issues/109), but we are able to import data via the console in UTF8. The problem that we are not able to import data in cp1250 via client set on cp1250 to the database with UTF8.

Could it be possible to add settings parameter where it can be the encoding of the output file? **Or it could be possible to set the default value to UTF8 on Windows for output file?** 

Best regards
Bulva

**Comment by darold** [comment]
Hi,

If you proceed to direct data import by setting PG_DSN in ora2pg.conf I guess you don't have to take care of the encoding. I've not tested on Windows but it should works without setting any encoding variables.

**Comment by Bulva** [comment]
Yeah, but unfortunately we cannot import data directly. I thought it would be the good feature for others with minimal effort (setting default encoding on UTF8). If I am wrong I am sorry for that. I am not familiar with Perl. But it is not a such a big problem. We can convert files to the UTF8 manually after export. Thank you for the reply

**Comment by darold** [comment]
You have the NLS_LANG configuration directive in the ora2pg.conf that can be used to force the encoding of the Oracle output. It must be used just like the NLS_LANG Oracle setting.

**Comment by darold** [comment]
Does it helps to solve your encoding issue?

**Comment by Bulva** [comment]
Really sorry for the last answer. The rows from the database were encoded well, NLS_LANG has no influence on it. It was probably some problem with encoding in Sublime (not the output file from ora2pg) or something like that. It looks ok now. 

I appreciate your time. You are doing very good work with the ora2pg.
