### ISSUE TITLE
-l --LOG option not writing to target file

### ISSUE THREAD

**Issue by karurmohan** [darold/ora2pg#527]
while using [-l or --log "Drive:\Filename"]  to write log message into target log file instead of stdout, the error alone is getting appended into the file. **What should i do?  if i want to append the success messages such as following in log file instead of STDOUT** : 
[==============>          ]  6/10 sequences (60.0%) generating PED_MOBL_CANOPI_C
[================>        ]  7/10 sequences (70.0%) generating PED_MOBL_COMN_ID_
[===================>     ]  8/10 sequences (80.0%) generating PED_NAM_IN_SEQ
[=====================>   ]  9/10 sequences (90.0%) generating PED_NAM_LOG_ID_SE
[========================>] 10/10 sequences (100.0%) generating PED_NAM_SEQ
[========================>] 10/10 sequences (100.0%) end of output.

Right now, using -l option, the log is not effected in Target Log file for succeeded migration.

**Comment by darold** [comment]
Hi,

The progress bar information are not printed to stdout but to stderr, this is with it doesn't appears in the log file. If you want to see all "success" messages into the logfile, add the `-d` option to the ora2pg command.
