### ISSUE TITLE
Column doesn't exist on index creation.

### ISSUE THREAD

**Issue by JeeIPI** [darold/ora2pg#528]
ora2pg: 18.2

Issue description:
-------------------

Getting the error "Column doesn't exist" when creating index from ora2Pg
LINE 1 : CREATE INDEX acomzzjof1 ON acomopercl (("acomzzjoi1 desc"));

Index has been created in Oracle database with the "desc" option. This option exists also in PostgreSQL.
The correct SQL creation index statement should be :  
       CREATE INDEX acomzzjof1 ON acomopercl (("acomzzjoi1" desc) ;

Possible solution:
-------------------
 "column_name  desc"  should be  "column_name" desc   ( Best option ) 
                                                 or    column_name  desc  ( without double quote)

Many thanks for your help.
Best Regards,
Jean-Pierre

**Comment by JeeIPI** [comment]
Create index script is generated  from ora2pg following command:
 ora2pg -p -t TABLE -o table.sql -b ${REP_DMP}/schema/tables -c ${PO_FIC_CONFIG}

Thanks again
Best Regards,
Jean-Pierre

**Comment by darold** [comment]
Thanks for the report, commit de2f357 fixes this issue.

**Comment by jpeep44** [comment]
Many Thanks,
I'm not sure when we'll test again this situation. So, the best is you close this issue.
Thanks again for the quick help.
Best Regards
