### ISSUE TITLE
REGEXP_LIKE  not working Redshift

### ISSUE THREAD

**Issue by bhoot929** [darold/ora2pg#529]
Original : 
select 
 REGEXP_LIKE(lower(moi.Product_group_desc),'mobile_electronics|video_games|electronics|home_entertainment|pc|camera|wireless') then 'Y' else 'N' end as is_risky

Converted : 

select lower(moi.Product_group_desc) **~** 'mobile_electronics|video_games|electronics|home_entertainment|pc|camera|wireless' then 'Y' else 'N' end as is_risky;

converted query is not working.
Please provide solution.

**Comment by darold** [comment]
This not the translation of the regexp_like that fail here, this the the missing CASE WHEN. The translation should be:
```
select case when lower(moi.Product_group_desc) ~ 'mobile_electronics|video_games|electronics|home_entertainment|pc|camera|wireless' then 'Y' else 'N' end as is_risky;
```
Do you have the right original Oracle code, the one given here don't seems valid under Oracle too. I've never seen call to THEN+ELSE+END alone outside a CASE statement. Does REGEXP_LIKE can avoid this call to CASE?

**Comment by bhoot929** [comment]
Original query :
select case when REGEXP_LIKE (moi.shipper_id, '\d') then 'N' else 'Y' end as all_char_tracking_num

Converted one:
select case when moi.shipper_id ~ '\d' then 'N' else 'Y' end as all_char_tracking_num;

The meaning of above query is that it will check whether input matches the digital character or not.
But the converted query is totally wrong.
Please update.

**Comment by darold** [comment]
I don't understand, for me everything works well:
```
gilles=# select case when 'test123' ~ '\d' then 'N' else 'Y' end as all_char_tracking_num;
 all_char_tracking_num 
-----------------------
 N
(1 line)

gilles=# select case when 'test' ~ '\d' then 'N' else 'Y' end as all_char_tracking_num;
 all_char_tracking_num 
-----------------------
 Y
(1 line)
```
Can you explain more what you are expecting instead of this result?

**Comment by bhoot929** [comment]
In redshift both of the above statements are giving Y as an output.

that means the converted syntax is not working in Redshift

**Comment by darold** [comment]
Well perhaps they have introduced an other limitation or a change into the PostgreSQL code. I think you can ask them why it not working?

**Comment by bhoot929** [comment]
SO in that case I would not like to convert my REGEXP_LIKE syntax . Is there any way I can avoid conversion & keep REGEXP_LIKE as it is?

**Comment by darold** [comment]
Apart disabling translation no there is no way to do that. But you may prefer to investigate why this is not working under RedShift, I don't think this is the expected behavior. Have you tried by including .* in the regex?
```
gilles=# select case when 'test123' ~ '.*\d.*' then 'N' else 'Y' end as all_char_tracking_num;
 all_char_tracking_num 
-----------------------
 N
(1 line)
```

**Comment by bhoot929** [comment]
Have a look at Oracle function:
https://www.techonthenet.com/oracle/regexp_like.php

The function works differently for each parameters. But ora2pg is converting it into same thing always.

**Comment by Keshavkumbham** [comment]
Hi, 
**Query:** select case when regexp_like('12','\d') then 'Y' else 'N' end
**when converted** : 
select case when '12' ~ '\d' then 'Y' else 'N' end;
**OUTPUT:** N
but 
select case when '12' ~  **'\\\d'** then 'Y' else 'N' end; 
gives the desired output "Y".
Please look into it.

**Comment by darold** [comment]
This escape string is specific to RedShift, in PostgreSQL it returns the right value:
```
gilles=# select case when '12' ~ '\d' then 'Y' else 'N' end;
 case 
------
 Y
```

Call to REGEXP_LIKE with 2 parameters are always converted the same way because this is the right thing to do on my understanding of the Oracle function. Perhaps bhoot929 is talking about REGEXP_LIKE called with 3 parameters, but Ora2Pg doesn't translate these calls. 

For the optional third match parameter, there is an equivalent in PostgreSQL using function regexp_matched() but unlike the Oracle function it returns a set, this is why it is not automatically translated.
