### ISSUE TITLE
Syntax error with ::numeric cast in creating of index

### ISSUE THREAD

**Issue by Bulva** [darold/ora2pg#530]
Hi Darold,

I have some problems with the syntax of creating of indexes. For example:
```
-- Index in Oracle database
CREATE INDEX tblspc.IDX_ADDRESS_AKT_CODE ON tblspc.ADDRESS_AKT (CODE);
```

The **CODE** column is the type of **VARCHAR2(6)**. For PostgreSQL ora2pg creates index with this format:
```
-- Index created via Ora2pg
CREATE INDEX address_akt_code ON address_akt ((code)::numeric);
```
All values in **code** column are numbers (from the human point of view), but from the database point of view, it is a VARCHAR. Ora2pg adds ::numeric cast which is not necessary in this case. Moreover the creating of the index in this style results in syntax error:
```
ERROR:  syntax error at or near "::"
LINE 1: ...akt_code ON address_akt (code)::numeric;
                                       ^
********** Error **********

ERROR: syntax error at or near "::"
SQL state: 42601
Character: 72
```

Index in this case should be probably without **::numeric cast** (for VARCHAR column), or with the right syntax.

Thanks for reply
Best regards

**Comment by darold** [comment]
Hi,

Ora2Pg normally doesn't add such a cast without reason, I think the original Oracle DDL was:
```
CREATE INDEX tblspc.IDX_ADDRESS_AKT_CODE ON tblspc.ADDRESS_AKT (TO_NUMBER(CODE));
```

Is that right?

**Comment by Bulva** [comment]
Probably not, this entire SQL for creating  INDEX from SQL developer:
```
  CREATE INDEX "tblspc"."IDX_ADDRESS_AKT_CODE" ON "tblspc"."ADDRESS_AKT" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "tblspc" ;
```

Is there any SELECT which ora2pg use for getting info about the index? I can try the SELECT. Unfortunately, I am not able to find original DDL, I can use only the version from SQL developer in this case.

Is there any way how to solve this problem?
Bulva

**Comment by darold** [comment]
I'm not able to reproduce this issue even with your test case, please upgrade to latest development code, perhaps you are using an old release.
