### ISSUE TITLE
Partitionning and trigger 

### ISSUE THREAD

**Issue by NicolasMartin69** [darold/ora2pg#531]
Hi Darold, when DDL of partitionning trigger is created, the DDL inclued the SCHEMA name : 

ie : 
```
CREATE TRIGGER PROP_TER.TER_DETAIL_P3_FACTURE_trigger_insert
    BEFORE INSERT ON PROP_TER.TER_DETAIL_P3_FACTURE
    FOR EACH ROW EXECUTE PROCEDURE prop_ter.ter_detail_p3_facture_insert_trigger();
```

But for for trigger, the name cannot be schema-qualified.

Regards,
Nicolas

**Comment by darold** [comment]
Hi Nicolas,

Export of object following their schema has been rewritten some times ago, I think you are using an obsolete code now. Use version 18.2 it might not reproduce this issue.

Regards,
