### ISSUE TITLE
Out of memory error after every table is exported

### ISSUE THREAD

**Issue by nycynik** [darold/ora2pg#533]
when I try to export data, it runs out of memory, regardless of table size (even empty tables.)

```
    Out of memory!            ]    162926/498508267 rows (0.0%) on total estimated data (14 sec., avg: 11637 recs/sec)
    Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(PORT=1521)(HOST=192.168.0.42)
    (PROTOCOL=tcp))(CONNECT_DATA=(SID=orcl))) at 
    /usr/local/lib/perl/5.18.2/DBD/Oracle.pm line 348.
```

**Comment by darold** [comment]
You don't have enough memory. If you can't increase the memory size than reduce the value of DATA_LIMIT in ora2pg.conf. Try with 5000 and if it doesn't works use 2500.

**Comment by nycynik** [comment]
Thank you!  I thought the machine had plenty of RAM, so I was not sure why this would fail.  But after your response, I checked, and it actually only has 4gigs in it.  Reduced the DATA_LIMIT, and it works great!  Thank you!

And, What an awesome product!!
