### ISSUE TITLE
cannot run ora2pg after last update

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#535]
running fails
<pre>
[oracle@ora2pg ora2pg]$ time tom_ora2pg -t PROCEDURE -o procedure-20170911.sql -N "ides_procs,public"
Unrecognized character \xC2 in column 39 at /usr/local/share/perl5/Ora2Pg/PLSQL.pm line 458.
Compilation failed in require at /usr/local/share/perl5/Ora2Pg.pm line 1271.
BEGIN failed--compilation aborted at /usr/local/share/perl5/Ora2Pg.pm line 1271.
Compilation failed in require at /usr/local/bin/ora2pg line 30.
BEGIN failed--compilation aborted at /usr/local/bin/ora2pg line 30.

</pre>

**Comment by okbob** [comment]
it is related to last commit - the problematic line is 
<pre>
if ($code =~ s/-20(\d{2})/'450$1'/ ||  $code =~ s/-20(\d{1})/'4500$1'/) {
</pre>

**Comment by darold** [comment]
Right, I have introduced a non printable special character. Fixed in commit 634f5b2.

**Comment by okbob** [comment]
It is fixed. Thank you
