### ISSUE TITLE
Functions with the same name in different Oracle Package are mixed when translated

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#536]
I have 2 packages (P1, P2)  that need many functions with the same name (across packages), and these functions are often called internally in each package, that is, unqualified ("myFunc" and not "P1.myFunc").

When I process package P1 with ora2pg, I get some calls to myFunc translated to calls to P2.myFunc instead of P1.myFunc.

This is very annoying because this practice is quite widely spread.
I can send code samples if needed.
Best Rgds.

**Comment by edelanoe** [comment]
Let me give another example where the qualifier is, this time, duplicated.
Look at "PCK_MSG.pck_gpar.pck_msg.pck_gpar...".

In Oracle package PCK_MSG:
FUNCTION TO_MONEY  (v_STR VARCHAR2) RETURN NUMBER IS
BEGIN
   RETURN TO_NUMBER(''||SUBSTR(v_STR,1,20)||'.'||SUBSTR(v_STR,21,10)||'', CST.MONEY_NUMBER_FORMAT);  --PG:s/::integer/::numeric/g
EXCEPTION WHEN OTHERS THEN
   pck_bdd.app_raise_error (SQLCODE, ''||SQLERRM||' in PCK_MSG.TO_MONEY('||coalesce(v_str,'')||')');
END;
In Oracle package PCK_GPAR:
FUNCTION TO_MONEY  (v_STR VARCHAR2) RETURN NUMBER IS
BEGIN
   RETURN TO_NUMBER(SUBSTR(v_STR,1,20) || '.' ||  SUBSTR(v_STR,21,10), LOC_NUMBER_FORMAT);
EXCEPTION WHEN OTHERS THEN
   raise_application_error (GENERIC_ERROR_NUMBER,GENERIC_ERROR_TXT||'TO_MONEY',true);
   RAISE;
END TO_MONEY;

------------------------------------------------------
ora2pg:
CREATE OR REPLACE FUNCTION pck_msg.to_money (v_STR text) RETURNS numeric AS $body$
BEGIN
   RETURN TO_NUMBER(''||SUBSTR(v_STR,1,20)||'.'||SUBSTR(v_STR,21,10)||'', CST.MONEY_NUMBER_FORMAT);  --PG:s/::integer/::numeric/g
EXCEPTION WHEN OTHERS THEN
   PERFORM pck_bdd.app_raise_error(SQLSTATE, ''||SQLERRM||' in PCK_MSG.pck_gpar.pck_msg.pck_gpar.pck_msg.pck_gpar.pck_msg.pck_gpar.pck_msg.to_money('||coalesce(v_str,'')||')');
END;

**Comment by darold** [comment]
Commit b1c3164 might solve this issue, please give it a try and let me know.

**Comment by edelanoe** [comment]
No, sorry, it doesn't solve this issue. It only solves #555, after my first check...

**Comment by edelanoe** [comment]
Now the main issue is solved (no more wrong calls), but the error remains inside literals, where it seems the prefixing action is done many times instead of one:

**Comment by edelanoe** [comment]
Now the main issue is solved (no more wrong calls), but the error remains inside literals, where it seems the prefixing action is done many times instead of one, like in this literal:
' in PCK_MSG.pck_gpar.pck_msg.pck_gpar.pck_msg.pck_gpar.pck_msg.pck_gpar.pck_msg.to_money...'

**Comment by darold** [comment]
I'm afraid I can't reproduce the issue even with all oracle code. I think your Ora2Pg installation is not the last one. Please check again.

**Comment by darold** [comment]
Ok, got it.

**Comment by darold** [comment]
Commit f911fcf fixed package function name replacement in constant string.

**Comment by edelanoe** [comment]
Sorry, It makes a little change but does not solve the issue.

Example: I have a function named DISPATCH in 4 packages, and when its name is used in a literal in one of those packages (pck_msg), it is transformed into:

PERFORM PCK_MSG.local_log_raise_error(SQLSTATE, ''||SQLERRM||' - '||v_err_context||' - Erreur dans pck_int.pck_lpm.pck_test_resa_ext.pck_msg.pck_int.pck_lpm.pck_test_resa_ext.pck_msg.pck_int.pck_lpm.pck_test_resa_ext.pck_msg.pck_int.pck_lpm.pck_test_resa_ext.pck_msg.pck_int.pck_lpm.pck_test_resa_ext.pck_msg.dispatch('||substr(v_STRMSG,1,200)||'...)');

... this instruction being inside the DISPATCH function itself (it is just an auto-trace), like in my previous example "to_money" and some others. The problem appears inside the function which name is shared.

**Comment by edelanoe** [comment]
About this issue on function schema prefixing (or "qualifying"), I don't understand why ora2pg makes so many passes trying to qualify and re-qualify function names. Is it because of search_path ?
I first supposed that when a function is called or quoted in an Oracle package, ora2pg has only one thing to do: to qualify it with the name of the package being processed. Why would there be a need to re-qualify an already qualified function call ?
I do not want especially to generate extra work for you, but I need your answer to search a solution that won't generate regression...
Rgds,
Eric

**Comment by edelanoe** [comment]
I realize that a literal can be a dynamic SQL or an inactive text. In my code, it is inactive text, it must not be changed by ora2pg (as it is for the moment).
Could there be an option to deactivate translation inside literals ?
Thanks in advance for your answer.

**Comment by darold** [comment]
Hi Eric,

The problem comes from the implementation that call the re-qualify function names part for each function found in a package. I have given a first try to rewrite this part some weeks ago but this was a fail du to lack of time. I will try to work again on it asap because it is really too much slow now.

Regards,

**Comment by darold** [comment]
I have good news, I was able to fix this issue and reduce the translation time by 10. Ora2Pg is now running the function call normalization one time at end by editing the output files. I still have to apply the change to other export types and cover the case of single file output. I hope to terminate the job at end of the week.

**Comment by darold** [comment]
Last two commit bd3f5f3 and 06d7010 might fix this issue as well as some others. It still need some additional work but it might works with your packages.

**Comment by edelanoe** [comment]
Hello Gilles,

I have downloaded ora2pg this morning. On my 20 000 lines (200 functions) package, I see the processing too long (over 1h).

Rgds,

**Comment by darold** [comment]
Yes, please update to latest commit e85eefd, it fix multiprocess use on second pass.

**Comment by edelanoe** [comment]
It is still too slow. In this development phase, I need to do 2 or 3 translations per hour...

**Comment by darold** [comment]
Ok, last commit f1166e5 might solve the performances issues. There is major behavior change with a full rewrite of function call qualification process. The second pass is now only use to re-qualify calls to pkgname.fctname into pkgname_ftcname when PACKAGE_AS_SCHEMA is disable. The replacement of all function calls using double quote when a non supported character is used or when PRESERVE_CASE is enabled has been completely removed as this takes too much time to process for just very few case. This mean that by default Ora2Pg will not go through the second pass. This can change in the future especially if this is more efficient to process PERFORM replacement.

I have also remove QUALIFY_FUNCTION configuration directive, there is no more reason to use it.

**Comment by edelanoe** [comment]
YES it works ! Thank you so much for all your efforts.
