### ISSUE TITLE
Need to export full schema and data of all tables.

### ISSUE THREAD

**Issue by trPhan** [darold/ora2pg#537]
Hi Darold,

i want to export full schema and data of tables with their indexes, constraints.

Functions, View, Trigger, i will export/import separately.

but, i could not get tables rows after import.

the following is steps i done:
1) .conf
ORACLE_HOME     /u01/app/oracle/product/10.2.0/orcl
ORACLE_DSN	    dbi:Oracle:host=xx.xx.xx.10;sid=TST;port=1521
ORACLE_USER	   test1		
ORACLE_PWD	    test1	
TYPE            TABLE 
USER_GRANTS     1
DEBUG           1
SCHEMA          test1
CREATE_SCHEMA   1
EXPORT_SCHEMA   1
NLS_LANG        AMERICAN_AMERICA.AL32UTF8
NLS_NCHAR       AL32UTF8

2) ora2pg -c file.conf -o tables.sql
3) after import by psql.
4) nothing any row in the tables, although i get structure of table and its index, constraint.

please help to advise me how can export full schema and data of all tables in oracle database.

Thanks and regards,
Trung Phan

**Comment by darold** [comment]
Hi,

Have a look at the TYPE configuration directive and its values, especially COPY.

Best regards,

**Comment by trPhan** [comment]
thanks Darold.

I re-installed ora2pg on a new machine, added DBD-PG, PG Client, to able to connect directly to PG Server for loading.

So far I could move tables to PG Database, however there are a couple of views have not been imported to, i am not sure PG can support the view or not?

ddmpg1=# \i ddm_test4_view.sql
SET
ERROR:  relation "snapshots_orig" does not exist at character 879
STATEMENT:  CREATE OR REPLACE VIEW snapshots (xxx) AS SELECT  recipient_id,
	    xxx
	    COALESCE(GETPACKAGES(company_id,recipient_id,part_number),' ') as package_name,
	    part_number,
	    stage_load_status,
	    COALESCE(stage_part_number,' ') as stage_part_number,
	    ...
	    COALESCE(load_unit_name,' ') as load_unit_name,
	    load_os,
	    COALESCE(load_part_number,' ') as load_part_number,
	    load_status
	   FROM snapshots_orig
	  GROUP BY recipient_id,
	    ..._number,
	    stage_path,
	    ...
	    load_part_number,
	    load_status ORDER BY PART_NUMBER;
psql:ddm_test4_view.sql:44: ERROR:  relation "snapshots_orig" does not exist
LINE 19:    FROM snapshots_orig
                 ^

Could you give me any advice on this? .

Thanks and regards,
TrungPhan

**Comment by trPhan** [comment]
Thanks Darold so much.

please let me close this.
