### ISSUE TITLE
DENSE_RANK KEEP not Converting

### ISSUE THREAD

**Issue by bhoot929** [darold/ora2pg#538]
In Oracle 

https://oracle-base.com/articles/misc/rank-dense-rank-first-last-analytic-functions

Query:
SELECT empno,
       deptno,
       sal,
       MIN(sal) KEEP (DENSE_RANK FIRST ORDER BY sal) OVER (PARTITION BY deptno) "Lowest",
       MAX(sal) KEEP (DENSE_RANK LAST ORDER BY sal) OVER (PARTITION BY deptno) "Highest"
FROM   emp
ORDER BY deptno, sal;

We can use DENSE_RANK with KEEP key word.

But the same thing is not converted while using ora2pg.

Can you suggest alternative ?

**Comment by darold** [comment]
Commit f870da1 translate:
 ```
MIN(sal) KEEP (DENSE_RANK FIRST ORDER BY sal) OVER (PARTITION BY deptno) "Lowest",
MAX(sal) KEEP (DENSE_RANK LAST ORDER BY sal) OVER (PARTITION BY deptno) "Highest"
```
into PostgreSQL equivalent:
```
FIRST_VALUE(sal) OVER (PARTITION BY deptno ORDER BY sal) AS "Lowest",
LAST_VALUE(sal) OVER (PARTITION BY deptno ORDER BY sal) AS "Highest"
```
