### ISSUE TITLE
REGEXP_SUBSTR not working with extra parameter

### ISSUE THREAD

**Issue by bhoot929** [darold/ora2pg#539]
In Oracle, Definition of REGEXP_SUBSTR is on below link:
https://www.techonthenet.com/oracle/functions/regexp_substr.php

In this we can give extra last parameter as no of occurrence. 

Sample query: 
select REGEXP_SUBSTR('sdads', '[^:]+', 1,2) from dual;

Output : 
select REGEXP_SUBSTR('sdads', '[^:]+', 1,2);

The above query will not work in Redshift as this has extra last parameter which is not supported by Redshift.

Thanks,
Swapnil

**Comment by darold** [comment]
Function REGEXP_SUBSTR() doe not exists in PostgreSQL, commit 75907b4 adds this translation.
```
   Translation of REGEX_SUBSTR( string, pattern, [pos], [nth]) converted into
        SELECT array_to_string(a, '')
          FROM regexp_matches(substr(string, pos), pattern, 'g') AS foo(a)
          LIMIT 1 OFFSET (nth - 1);
    Optional fifth parameter of match_parameter is appended to 'g' when present.
```
For example, Oracle query:
```
SELECT REGEXP_SUBSTR ('postgresql.org is a great resource', '(\S*)(\s)', 2, 3, 'm') FROM dual;
Result: 'a '
```
will be translated into:
```
SELECT (SELECT array_to_string(a, '')
    FROM regexp_matches(substr('postgresql.org is a great resource', 2), '(\S*)(\s)', 'gm') AS foo(a)
    LIMIT 1 OFFSET (3 - 1));
```
with the same result.
