### ISSUE TITLE
ERROR:  function from_tz(timestamp without time zone, unknown) does not exist

### ISSUE THREAD

**Issue by trPhan** [darold/ora2pg#540]
Hi Darold and team,

When I tried to import a View from Oracle to PostgreSql, got the error related to function un-support as the following: 

> **ERROR:  function from_tz(timestamp without time zone, unknown) does not exist
> LINE 16:                 Cast(From_Tz(Cast(Gdpa.Stamp As Timestamp), ...
>                               ^
> HINT:  No function matches the given name and argument types. You might need to add explicit type casts.**

as my understanding, PostgreSql does not provide a similar function as FROM_TZ, 
Am i not sure whether Orafce (Oracle’s compatibility functions and packages) can supports my problem.

please help to advise me.

Thanks and regards,
TrungPhan.

**Comment by darold** [comment]
I'm not sure too that Orafce has such compatibility function, however this is very easy to convert. Commit 352dc2f adds a translation for this function in Ora2Pg.

Let us know if that's fills your current code translation needs.

**Comment by trPhan** [comment]
thanks Darold,

I am novice to ora2pg, so I dont know how apply the commit 352dc2f to fix my problem.

could you advise me the procedure how to apply the commit into my ora2pg.

Thanks,
TrungPhan

**Comment by darold** [comment]
Just override your installation using the following commands, this is simple and you don't have to know about git commands.
```
wget https://github.com/darold/ora2pg/archive/master.zip
unzip master.zip
cd ora2pg-master/
perl Makefile.PL
make
sudo make install
```
This will just override the Ora2Pg libraries (*.pm) and the scrip ora2pg. The /etc/ora2pg/ora2pg.conf file will not be overridden.

**Comment by trPhan** [comment]
Hi Darold,

After apply the commit, i tried to re-run the ora2pg to recreate view.sql:

> ora2pg -c ora2pg.conf -t VIEW -o view_applyCommit.sql

and import into postgreSql.

> ddmpg=# \i view_applyCommit.sql
> SET
> psql:view_applyCommit.sql:44: ERROR:  syntax error at or near "America"
> LINE 16: ...           Cast(('Cast(Gdpa.Stamp As Timestamp), 'America/De...

This is partially code part in view_applyCommit.sql:
 
>                 CASE WHEN Dp.Approval_State=0 THEN  'AVAILABLE' WHEN Dp.Approval_State=1 THEN  'PENDING' WHEN Dp.Approval_State=2 THEN  'AVAILABLE' WHEN Dp.Ap
> proval_State=3 THEN  'REJECTED' END  Customer_Pkg_Status, Dp.Approval_State,
>                 Cast(('Cast(Gdpa.Stamp As Timestamp), 'America/Denver'')::timestamp with time zone At Time Zone
>                       'UTC' As Timestamp) As Status_When, Gdpa.Operation,
>                 Cast('Ext Publishing' As varchar(30)) As Package_Step,
>                 Cast('S' As varchar(1)) As Status_Type,
>                 Cast('DDM' As varchar(3)) As System_Name,
>                 Row_Number() Over (Partition By Comp_Info.Company_Code, Pck.Package_Id, Dp.Approval_State Order By Gdpa.Stamp Desc) Rnk,
>                 Pck.Display_Name, Pck.Replaced_Package_Name
>          From   Gt_Delivered_Packages Dp, Gt_Packages Pck,
>                 Gt_Delivered_Packages_Audits Gdpa,
>                 (Select Gt.Company_Id, Gt.Code As Company_Code, Gt.Name
>                   From   Gt_Companies Gt) Comp_Info

coud you help to advise me  for this issue?

Thanks
TrungP

**Comment by darold** [comment]
Can you send me or post here the full DDL of the view?

**Comment by trPhan** [comment]
Hi Darold,

I already sent you the ddl via your email, please help to check and have advice for my issue.

Thanks and regards,
TrungPhan,

**Comment by darold** [comment]
Thanks for the DDL, commit  cb3db80 might solve this issue.

**Comment by trPhan** [comment]
Thank Darold for your valued support.

it works now.

Sorry for late update, because i need be-onsite to apply the commit.

Thanks and regards,
Trung.
P/S: Definitely, i will do a donate soon.
