### ISSUE TITLE
Arrays in PLSQL: Missing changes from (i) to [i] and a consequence on "if...null"

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#541]
There is no translation of array subscript syntax (i) to [i]. This the core of the issue.
Oracle declaration: v_Itr_Product_List Itr_Product_List:=Itr_Product_List();
Oracle function body:
    v_Itr_Product_List(i).Product_Management_Mode  := 0; 
ora2pg: no change
    v_Itr_Product_List(i).Product_Management_Mode  := 0; 

And a consequence is this discrepancy, that might have to be examined too:

Oracle:
    if VAR_LIST(i).SUB_VARIABLE_ID is null then

ora2pg:
    if VAR_LIST(i)coalesce(.SUB_VARIABLE_ID::text, '') = '' then

Expected:
    if coalesce(VAR_LIST[i].SUB_VARIABLE_ID::text, '') = '' then

**Comment by darold** [comment]
Commit 8c94d57 will replace all call of type `VAR_ARR(i).SUB_VAR` into `VAR_ARR[i].SUB_VAR`. Declaration like `v_Itr_Product_List Itr_Product_List:=Itr_Product_List();` will be kept untouched as it is not possible for Ora2Pg to distinct it from a function call.

**Comment by edelanoe** [comment]
Thanks Darold,
I have many right transformations, but some are garbled.
Here are examples:
Oracle
DEBUG_TRACE('SUB_SAVE_VAR('||VAR_LIST(i).subscription_id||', '
DEBUG_TRACE('VAR_LIST('||i||'): '||VAR_LIST(i).subscription_id||', '||VAR_LIST(i).dhm_begin
'{\"SUB_VARIABLE_ID\":'||coalesce(VAR_LIST(i).SUB_VARIABLE_ID, 0)

ora2pg
DEBUG_TRACE['pck_gcl.sub_save_var('||VAR_LIST(i].subscription_id||', '
DEBUG_TRACE['VAR_LIST('||i||'): '||VAR_LIST(i].subscription_id||', '||VAR_LIST[i].dhm_begin
||'{\"SUB_VARIABLE_ID\":'||coalesce[VAR_LIST(i].SUB_VARIABLE_ID, 0)

**Comment by edelanoe** [comment]
Hello Darold,
Here are other garbled transformations of "(i)" to "[i]" in arrays.
The number of "[" is right, but they are not at the right place.

Oracle:
            v_Ict_Rep.Abo_Details :=  v_Ict_Rep.Abo_Details|| to_char(COALESCE(v_Subscription_Data_List(i).Customer_id,0), 'FM000009');
            v_Ict_Rep.Abo_Details :=  v_Ict_Rep.Abo_Details|| rpad   (COALESCE(v_Subscription_Data_List(i).Customer_Name,' '),40);


Ora2pg:
            v_Ict_Rep.Abo_Details :=  v_Ict_Rep.Abo_Details|| to_char[COALESCE(v_Subscription_Data_List(i].Customer_id,0), 'FM000009');
            v_Ict_Rep.Abo_Details :=  v_Ict_Rep.Abo_Details|| rpad(COALESCE[v_Subscription_Data_List(i].Customer_Name,' '),40);

Have fun :)

**Comment by darold** [comment]
Commit f7eae79 might solve this issue.

**Comment by edelanoe** [comment]
This is solved, thank you

**Comment by edelanoe** [comment]
Hi Gilles,
I still have some errors, this time on assignments of composite types :
If I declare this:
    v_ticketsR T_TICKET_SUBSCRIPTION%ROWTYPE;
    v_tickets T_TICKET_SUBSCRIPTION[];  -- I managed to build this from a specific oracle source
-1-
- (ORA->PG) "v_tickets(1) := v_ticketsR;"  is not translated to "v_tickets[1] := v_ticketsR;"  (a function call is not followed by ":=", right ?)
- --> would this be a reason to reopen this issue ?
-2-
- (PG)assignment of a field does not work : v_tickets[1].myField := myValue;  -- fails 
-> Do you have an advice ?

Thanks again for the great work on this great tool,
Eric

**Comment by darold** [comment]
Eric, do you have an example that I can load in Oracle to understand and check the exact problem?

**Comment by edelanoe** [comment]
-- ORACLE
create table emp (empno number(8), name varchar2(40));
CREATE OR REPLACE FUNCTION test (p_emp emp%ROWTYPE) as
declare
    v_empR emp%ROWTYPE;
    type empT is table of emp%ROWTYPE index by binary_integer;
    v_emps empT;
    i binary_integer := 0;
begin
    insert into emp (empno, name) values (p_emp.empno, p_emp.name);
    for v_empR in (select * from emp) loop
        i := i + 1;
        v_emps(i) := v_empR;
        v_emps(i).name := v_empR.name||' modified';
        exit;
    end loop;
end;
/

-- Expected in Postgres:
create table emp (empno numeric,name varchar);
CREATE OR REPLACE FUNCTION test (p_emp emp%ROWTYPE) as $$
declare
    v_empR emp;  -- OR "v_empR emp%ROWTYPE;"
    v_emps emp[];  -- OR "v_emps emp%ROWTYPE[];", which might require 2 steps
    i integer;
begin
    i := 0;
    insert into emp (empno, name) values (p_emp.empno, p_emp.name);
    for v_empR in (select * from emp) loop
        i := i + 1;
        v_emps[i] := v_empR;   -- TRANSLATION NOT YET DONE by ora2pg
        v_emps[i].name := v_empR.name||' modified';  -- STATEMENT DOES NOTHING in PostgreSQL
        exit;
    end loop;
end$$;

**Comment by okbob** [comment]
po 12. 4. 2021 v 13:02 odesílatel Eric Delanoë ***@***.***>
napsal:

> -- ORACLE
> create table emp (empno number(8), name varchar2(40));
> CREATE OR REPLACE FUNCTION test (p_emp emp%ROWTYPE) as
> declare
> v_empR emp%ROWTYPE;
> type empT is table of emp%ROWTYPE index by binary_integer;
> v_emps empT;
> i binary_integer := 0;
> begin
> insert into emp (empno, name) values (p_emp.empno, p_emp.name);
> for v_empR in (select * from emp) loop
> i := i + 1;
> v_emps(i) := v_empR;
> v_emps(i).name := v_empR.name||' modified';
> exit;
> end loop;
> end;
> /
>
> -- Expected in Postgres:
> create table emp (empno numeric,name varchar);
> CREATE OR REPLACE FUNCTION test (p_emp emp%ROWTYPE) as $$
> declare
> v_empR emp; -- OR "v_empR emp%ROWTYPE;"
> v_emps emp[]; -- OR "v_emps emp%ROWTYPE[];", which might require 2 steps
> i integer;
> begin
> i := 0;
> insert into emp (empno, name) values (p_emp.empno, p_emp.name);
> for v_empR in (select * from emp) loop
> i := i + 1;
> v_emps[i] := v_empR; -- TRANSLATION NOT YET DONE by ora2pg
> v_emps[i].name := v_empR.name||' modified'; -- STATEMENT DOES NOTHING in
> PostgreSQL
>

"v_emps[i].name" This syntax is supported from Postgres 14. In older
Postgreses, you cannot to change field of record inside an array

Pavel

**Comment by edelanoe** [comment]
Thanks Pavel. Now remains that translating "v_emps(i) := v_empR;" to "v_emps[i] := v_empR;" would be really useful :)
