### ISSUE TITLE
ora2pg Table

### ISSUE THREAD

**Issue by puneet6006** [darold/ora2pg#544]
Hi,
I am using ora2pg to export oracle table  in  postgresql.
Created table should contains the fields of two different tables of Oracle.
example:- I want to create emp table on PG having the field empid, emp_name, dept_id from Oracle's two table, employee and department.

So anyone can help me to achieve this goal.

**Comment by darold** [comment]
Hi,

Not sure to understand, but if you want to create a table with some columns that will receive data from two tables there is no easy way for that. In this case you will have to create the destination by yourself, Ora2Pg can not do that for you and then to import data you will have to redefine the query used to export data with the REPLACE_TABLES and REPLACE_QUERY configuration directives. For example:
```
REPLACE_TABLES  EMPLOYEE:EMP

REPLACE_QUERY   EMP[SELECT  e.empid, e.emp_name, u.dept_id FROM EMPLOYEE e JOIN EMP_UPDT u ON (e.id=u.id)]
```
This should work.

If I misunderstood, please explain more what you want to do.

**Comment by puneet6006** [comment]
Hi,
I want exactly as you explained.

I am doing the same, but not working..
The problem  with the field in select statement u.dep_id.

On Oracle  EMP columns:
empid,emp_name

On Postgres  EMP columns:
empid,emp_name,dept_id

As you used 
REPLACE_QUERY   EMP[select ......]  
I think, first it checks the structure at oracle end found 2 columns and then execute query and found 3 columns to extract which produce error of column mismatch.

Note: I did not used REPLACE_TABLES as my table name is same on Oracle and Postgres. i.e. EMP

**Comment by darold** [comment]
Please post the error message reported by Ora2Pg.
