### ISSUE TITLE
INSERT data in postgres 

### ISSUE THREAD

**Issue by MeriemBo** [darold/ora2pg#545]
Hello,  I want to migrate my Oracle data base to postgres , when I import all the tables , I don't get the data inserts in my output.sql . I run this command : – ora2pg -c ora2pg.conf  TYPE TABLE  , but I don't get any data , can you please help ? thank you

**Comment by SebAlbert** [comment]
You have to run ora2pg twice: First with TYPE TABLE (to create the tables etc.), and a second time with TYPE INSERT (to migrate the data) (or TYPE COPY, which may be faster in Postgres)

**Comment by SebAlbert** [comment]
Note also that if you're not specifying the TYPE option in the ora2pg.conf file, but rather on the command line, then the option would be `-t INSERT` and not `TYPE INSERT` (which is the syntax for the config file).

**Comment by MeriemBo** [comment]
![image](https://user-images.githubusercontent.com/20017065/30644836-a765ecb4-9e0b-11e7-94d8-a2da0b80b12f.png)

where I run : ora2pg -c ora2pg.conf  -t INSERT , I get this error

**Comment by SebAlbert** [comment]
It seems that the first run (with TYPE TABLE or -t TABLE) has not succeeded, since the error is that the tables are missing in Postgres.

**Comment by SebAlbert** [comment]
Maybe you forgot to apply the output.sql from the first run to your postgres database before?

**Comment by MeriemBo** [comment]
Alright , thank you , one last question please , I want to execute the output.sql script from another server with the psql command , how can I specify the host , username and password ? because I tried this command and it's giving me an error : 
psql -v ON_ERROR_STOP=ON -h hotname -p 5432 -U username -d password -MEDOCDEV -w -f  output.sql

**Comment by SebAlbert** [comment]
Several things:
1. Make sure that you are allowed to connect to the database from the remote client (i.e., settings in the pg_hba.conf file on the server)
2. The psql option -d is for the database name, not the password. The password should not be supplied in the command, but you will be prompted for the password after you enter that command, **unless you use the -w switch (meaning "no password"), which you seem to be doing**
3. I don't understand the -MEDOCDEV parameter, but maybe it's the database name, in which case it should stand directly behind the -d

Note that you can also specify default values for hostname, port, database name, username (role), password by setting environment variables, see https://www.postgresql.org/docs/9.6/static/libpq-envars.html

**Comment by MeriemBo** [comment]
Alright , thank you so much sir . Much appreciated

**Comment by SebAlbert** [comment]
If you set the configuration value PG_DSN (to the connection string for Postgres), then ora2pg will connect to the Postgres database directly and execute the INSERT (or COPY) command. If PG_DSN is not set, then you will get a new output.sql (if it already exists, it would probably be overwritten).

**Comment by MeriemBo** [comment]
Hello and thank you for your help , I did set the PG_DSN , and the connection to the postgres database is established , but I still don't get the data inserted whenever I run the INSERT ( even COPY) command .

**Comment by darold** [comment]
Please execute ora2pg with the -d option and post the output.

**Comment by MeriemBo** [comment]
![image](https://user-images.githubusercontent.com/20017065/30905787-c70b7680-a36d-11e7-9d4d-f49cc5d85797.png)

This is what I get , and no data in the database

**Comment by darold** [comment]
I think you misunderstand the explanation of Sebastian, you can not use TYPE at command line, this is a configuration directive and should stay in the ora2pg.conf file. Here you are just exporting table DDL again and again. Use the following command instead:
```
ora2pg -c ora2pg.conf -d -t COPY
```

**Comment by MeriemBo** [comment]
Alright  thank you , I tried to run the command you suggested and I got this error : 

![image](https://user-images.githubusercontent.com/20017065/30906686-8de93ccc-a370-11e7-9c19-497302613b78.png)

**Comment by darold** [comment]
It seems to me that the error message is explicit, you are trying to connect to a database that do not exists. If you think it should exists try to use lowercase.

**Comment by MeriemBo** [comment]
Thank you so much  , it finally  worked !
