### ISSUE TITLE
Encoding in custom types

### ISSUE THREAD

**Issue by Bulva** [darold/ora2pg#548]
Hi Darold,

a few weeks ago there were problems with user-defined types export (https://github.com/darold/ora2pg/issues/504). We found the next problem with these types related to encoding of the strings in these types.

Encoding of the file is OK, there is not a problem with special characters, but in the custom types, there is a problem with special characters. For example:
`ROW(0,0,0,0,0,0,0,0,0,7,NULL,E'NovÃ½ JiÄÃ­n')`
should be:
`ROW(0,0,0,0,0,0,0,0,0,7,NULL,E'Nový Jičín')`

If we set NLS_LANG code to Czech (CZECH_CZECH REPUBLIC.EE8MSWIN1250). Then special characters in a whole file are bad and the special characters in custom types look different but also bad, e.g.:
`ROW(0,0,0,0,0,0,0,0,0,7,NULL,E'Nový Jièín')`

What do you think about it? Can there be any differences between custom types and standard types in ora2pg export?

**Comment by darold** [comment]
Ora2Pg doesn't apply any encoding transformation and for custom type it simply ask the data to Oracle. It seems that Oracle doesn't apply the right encoding when retrieving the data. I don't know what to do with this issue. I have in plan to allow data transformation during the export so in this case you will be able to call an encoding function. Unfortunately I don't know when this feature will be available.

**Comment by darold** [comment]
I think commit 06d7010 solves this issue.

**Comment by lupynos** [comment]
To test this, do we have to set something in conf? Seems to be not working yet. Thx.

**Comment by darold** [comment]
Yes, please unset NLS_LANG, NLS_NCHAR and CLIENT_ENCODING in your configuration file and environment variables and proceed to export.

**Comment by lupynos** [comment]
It is not working for us yet, but I think it is somehow  coonected with Windows env we're using for migration. We'll investigate more.
