### ISSUE TITLE
Connect by prior issue

### ISSUE THREAD

**Issue by bhoot929** [darold/ora2pg#549]
Hi,

I am trying to convert below query but it is not get converted correctly.

SQL : 

SELECT task_id ,
    LTRIM(MAX(SYS_CONNECT_BY_PATH (attribute_id, ', ')), ',') AS attribute_id
  FROM iwta_{TEMPORARY_TABLE_SEQUENCE} ta
    CONNECT BY task_id = PRIOR task_id
  AND rn               = PRIOR rn+1
  AND LEVEL            < 50
    START WITH rn      = 1
  GROUP BY task_id
Can you please let me know the solution?

Thanks

**Comment by bhoot929** [comment]
Hi ,
Can you please check it once.

**Comment by darold** [comment]
Hi,

Last commit ca3cbee might solve this issue but results must be compared from both side. Let me know.
