### ISSUE TITLE
dynamic configuration of dblink connection string

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#550]
Currently dblink usage is controlled by DBLINK_CONN parameter. It is not practical, when there will be multiple databases. Can be dblink connection string based on expression?
`format('port=%s dbname=%s user=%', current_setting('port'), current_database(), current_user)`
password can be stored in .pgpasswd file

**Comment by darold** [comment]
Looks far better than the default behavior that uses PG_DSN. I will apply your suggestion as the default value and it will still be possible to set a custom connection string using DBLINK_CONN directrive.

**Comment by okbob** [comment]
good idea

**Comment by darold** [comment]
Commit 4287750 add this behavior.

**Comment by okbob** [comment]
There is small bug
format string is `port=%s dbname=%s user=%`, should be `port=%s dbname=%s user=%s`

**Comment by darold** [comment]
Thanks, commit 1c5a142 fixes the typo.

**Comment by okbob** [comment]
It is fixed, thank you
