### ISSUE TITLE
Export multiple objects doesn't work

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#551]
I try to export some selected views and safe it to file

ora2pg ... -t VIEWS -o xxx.sql  -a "VIEW1,VIEW2, ..."
The finish is:
<pre>

[1] Scanning V_NAJVZTAH...
[2] Scanning V_NAJVZTAHUZIVAZBA...
[3] Scanning V_OBPPLOCH...
[4] Scanning V_PARAM_PREDPIS...
</pre>
But on the end there are not any file xxx.sql

Export of one object is working, export of all objects is working too.

**Comment by darold** [comment]
It's working at my side:
```
 ora2pg -c config/ora2pg.conf -t VIEW -b tmp/ -a "V_LEVEL1,V_LEVEL2,V_LEVEL3" -o xxx.sql
[========================>] 3/3 views (100.0%) end of output.                
gilles@devel$ ls tmp/
V_LEVEL1_xxx.sql  V_LEVEL2_xxx.sql  V_LEVEL3_xxx.sql  xxx.sql
```

Do you have any value set to ALLOW/EXCLUDE configuration directive?

**Comment by okbob** [comment]
2017-09-27 21:30 GMT+02:00 Gilles Darold <notifications@github.com>:

> It's working at my side:
>
>  ora2pg -c config/ora2pg.conf -t VIEW -b tmp/ -a "V_LEVEL1,V_LEVEL2,V_LEVEL3" -o xxx.sql
> [========================>] 3/3 views (100.0%) end of output.
> gilles@devel$ ls tmp/
> V_LEVEL1_xxx.sql  V_LEVEL2_xxx.sql  V_LEVEL3_xxx.sql  xxx.sql
>
> Do you have any value set to ALLOW/EXCLUDE configuration directive?
>
no, they are commented

**Comment by darold** [comment]
Then the views you are selecting doesn't exists in the schema you are exporting?

**Comment by okbob** [comment]
2017-09-27 21:47 GMT+02:00 Gilles Darold <notifications@github.com>:

> Then the views you are selecting doesn't exists in the schema you are
> exporting?
>
they exists - when I dump all, then I see they

**Comment by darold** [comment]
Strange, does it works if you set the ALLOW directive as follow in ora2pg.conf?
```
ALLOW                VIEW1,VIEW2,...
```

**Comment by okbob** [comment]
I found a issue - there was wrong -b option in my script - I push it directly as '~/xxx' and Ora2pg doesn't a ~ substitution. So there was wrong final output path, and then there was zero output.
