### ISSUE TITLE
DBD::Pg::db do failed: ERROR:  relation "side" does not exist 

### ISSUE THREAD

**Issue by sangeetmen** [darold/ora2pg#552]
I am trying to migrate the Oracle database to PG using ora2pg. I had done this earlier on the same database 7-8 months back.
But, now when I am doing it even for just one table I get the following error
```
DBD::Pg::db do failed: ERROR:  relation "side" does not exist at C:/Perl/site/li
b/Ora2Pg.pm line 11025.
FATAL: ERROR:  relation "side" does not exist
Aborting export...
```

Attaching the conf file and a screen shot of PG table details and conf file(as txt file)

![pgconf](https://user-images.githubusercontent.com/32362498/30968210-2d1d1226-a47c-11e7-8dab-a1460915e5a4.jpg)
[masters_copy.txt](https://github.com/darold/ora2pg/files/1340950/masters_copy.txt)

**Comment by darold** [comment]
Hi,

Seems that it is on a specific schema (hclive). I see in your master_copy.txt file that PG_SCHEMA is set to hclive which is good but the line before must be removed: `SET search_path = $PG_SCHEMA;`. This is not a valid directive.

There was changes in the export schema behavior since your latest migration:
```
The definition of the search path now follow the following behavior:
      * when PG_SCHEMA is define, always set search_path to its value.
      * when EXPORT_SCHEMA is enabled and SCHEMA is set, the search_path
        is set the name of the schema.
```

**Comment by sangeetmen** [comment]
Thanks for the input. But I tried after removing `SET search_path= $PG_SCHEMA; ` from the conf file. But it still gives me the same error. 

```
DBD::Pg::db do failed: ERROR:  relation "side" does not exist at C:/Perl/site/li
b/Ora2Pg.pm line 11025.
FATAL: ERROR:  relation "side" does not exist
Aborting export...
```
You mentioned export schema behavior,but  I actually not exporting schema. I am only transferring data. The schema and tables at the destination server are set up.  I just need to transfer data.

Do I need to set the search path to a specific value or some configurations at PostgreSQL level before exporting.

**Comment by darold** [comment]
Yes the easiest way to solve this issue it to change the search_path at ora2pg user connection:
```
psql -U db_username db_name -c "ALTER ROLE db_username SET search_path TO hclive,public;"
```
then run ora2pg, it will find any object defined in schema hclive.

**Comment by sangeetmen** [comment]
**Thanks. That did the work.** 
But, I am just curious as I did not do it last time and the data transfer did work at that point.
Has the definition changed in Ora2pg?
