### ISSUE TITLE
COPY export is too slow

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#553]
I try use profiler, but because there are lot processes I am not fully successful. But bottleneck is 100% on ora2pg side in "sending data process"

95% does format_data_row
50% format_data_type
30% escape_copy

**Comment by darold** [comment]
Please post the ora2pg command line options used and/or the values of JOBS, PARALLEL_TABLES, ORACLE_COPY, NO_LOB_LOCATOR and DATA_LIMIT. Do you know if there is lot of CLOB/BLOB columns in the tables?

**Comment by darold** [comment]
And also how many CPUs and RAM do you have at Ora2Pg side? Is it used in the Oracle or PostgreSQL server or on a third machine?

**Comment by okbob** [comment]
2017-09-28 19:59 GMT+02:00 Gilles Darold <notifications@github.com>:

> Please post the ora2pg command line options used and/or the values of
> JOBS, PARALLEL_TABLES, ORACLE_COPY, NO_LOB_LOCATOR and DATA_LIMIT. Do you
> know if there is lot of CLOB/BLOB columns in the tables?
>

perl /usr/local/bin/ora2pg -p -c /etc/ora2pg/ora2pg.conf -b $HOME/migrace
-J 4 -d"

export to file

Blobs, clobs are not used

But there are big tables with lot of columns

50GB file was produced more than 7hours

**Comment by darold** [comment]
If you have some big tables and more CPU and enough memory, for example 12 cores, I think you could try to export your data using:
```
perl /usr/local/bin/ora2pg -p -c /etc/ora2pg/ora2pg.conf -b $HOME/migrace -P 4 -j 3"
```
You might see performances improvement.

If you just have 4 cores, using the following may be better:
```
perl /usr/local/bin/ora2pg -p -c /etc/ora2pg/ora2pg.conf -b $HOME/migrace -P 2 -j 2"
```
Of course direct import to PostgreSQL is mandatory with high data volume.

If you just want to test import, for example to see if all data type have been well translated, you want add the following to ora2pg.conf:
```
WHERE    ROWNUM < 10000
```
this will just import the 10,000 first lines.

**Comment by okbob** [comment]
-j 4 helped
