### ISSUE TITLE
Missing RETURN NEW in BEFORE TRIGGER

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#554]
When some comment is after END kyeword, then Ora2pg doesn't make RETURN NEW.

<pre>

CREATE OR REPLACE TRIGGER "IDES_JMMAJ".UCEPOKLADNA_BI BEFORE INSERT
ON UCEPOKLADNA
FOR EACH ROW
BEGIN
----  ZACATEK DEFAULT CAST
RRRUTIL.DEFA_BEFORE_INSERT( :new.ID_UCEPOKLADNA , :new.PLATNOST_OD , :new.PLATNOST_DO ,:new.IDENT , :new.ID_ASPRAVCE , :new.CVZNIKRADK ) ;
----  KONEC DEFAULT CAST
END ;
----
</pre>

**Comment by darold** [comment]
Reproduced, commit 4dae055 might solve this issue.

**Comment by okbob** [comment]
Thank you. Unfortunately, I can check it at end of next week.

**Comment by okbob** [comment]
it is fixed, thank you
