### ISSUE TITLE
Using extract to local file and ORACLE_COPIES set to 4 results in incomplete data  

### ISSUE THREAD

**Issue by ghavinga** [darold/ora2pg#557]
We are testing a migration of a relatively small table, containing CLOBS, of around 130MBytes. Because of the CLOBS a single instance of Ora2PG takes approximately 80 minutes to extract the data from Oracle to a local SQL file (COPY). We are investigating the best ways speeding the process up. This is running in a VM instance with 8 2.6GHz vCPUs and 64GBytes of internal memory.

When we set ORACLE_COPIES to a value of 4 and specify DEFINED_PK to a column index, the extract takes about 23 minutes. But the resulting data file is only 36Mbytes (approximately a quarter ...). We do indeed see 4 Ora2PG processes starting and during the running time allocate 100% on 4 separate vCPUs. 

Ora2PG is version 18.1. I know there is a new release, but it will be a bit difficult to upgrade as this is a secure environment behind several firewalls and no root access allowed.

My question is does Ora2PG support multiprocessing when extracting data from Oracle to the local file system? If so what could we be doing wrong?

**Comment by darold** [comment]
Yes in your case you should use ORACLE_COPIES = 4 (command line option: -J 4) and JOBS = 2 (command line option: -j 2). Ora2Pg will use 2 process per Oracle connection to write data to file. That also mean that you will use a total of 8 vCPU.

**Comment by darold** [comment]
Now to answer to the missing data issue, if I recall well there was an issue on exporting data that was trunctated to the last DATA_LIMIT lines. Yes, got it, this is commit 104cfd0. If you can't use latest release v18.2 perhaps you can edit the Ora2Pg.pm file on the remotre server and comment lines in function `_get_dml_from_file` like in the patch. 

```
 sub _get_dml_from_file
@@ -10941,10 +10944,10 @@ sub data_dump
        }
 
        # Rename temporary output file
-       if ($self->{file_per_table} && -e "$dirprefix$filename") {
-               $self->logit("Renaming temporary file $dirprefix$filename into ${dirprefix}${rname}_$self->{output}\n", 1);
-               rename("$dirprefix$filename", "${dirprefix}${rname}_$self->{output}");
-       }
+#      if ($self->{file_per_table} && -e "$dirprefix$filename") {
+#              $self->logit("Renaming temporary file $dirprefix$filename into ${dirprefix}${rname}_$self->{output}\n", 1);
+#              rename("$dirprefix$filename", "${dirprefix}${rname}_$self->{output}");
+#      }
 }
```

**Comment by ghavinga** [comment]
Thank you Gilles for your quick response, nice to hear we are on the right track. I will let you know as soon as possible the result of the patch.

**Comment by darold** [comment]
I guess the patch was efficient.

**Comment by ghavinga** [comment]
Apologies for not getting back earlier, we had a particularly difficult migration the last few weeks which has taken all my time and attention. I will be testing the patch today.
