### ISSUE TITLE
ora2pg generates illegal geometries from compound polygons

### ISSUE THREAD

**Issue by ksurell** [darold/ora2pg#558]
It seems that ora2pg (v 18.2) generates illegal geometry definitions. 
I'm quite new to PostGIS, more used to Oracle so I might have got things wrong.

I have the following Oracle geometry (gml output at the end of the post):

MDSYS.SDO_GEOMETRY(3003, 5850, null, MDSYS.SDO_ELEM_INFO_ARRAY(1,1005,2, 1,2,2, 7,2,1), 
MDSYS.SDO_ORDINATE_ARRAY(
148278,13322004038,6583872,5798763279,0,
148278,44264699327,6583869,5368326297,0,
148281,48047341051,6583869,8938629488,0,
148285,4718999615,6583867,0024220664,0,
148289,95886573888,6583873,0363574782,0,
148282,52121831308,6583878,5747243343,0,
148278,13322004038,6583872,5798763279,0)) 

This a compund polygon consisting of an arc and a linestring.

The output from ora2pg is:
CURVEPOLYGONZ 
(
	COMPOUNDCURVEZ (
	(
	148278.13322004 6583872.57987633 0.0, 
	148278.442646993 6583869.53683263 0.0, 
	148281.480473411 6583869.89386295 0.0, 
	148285.471899962 6583867.00242207 0.0), 
	CIRCULARSTRINGZ (
	148281.480473411 6583869.89386295 0.0, 
	148285.471899962 6583867.00242207 0.0, 
	148289.958865739 6583873.03635748 0.0, 
	148282.521218313 6583878.57472433 0.0, 
	148278.13322004 6583872.57987633 0.0)
	)
)
This results in the error during psql import:
ERROR: incontinuous compound curve
SQL state: XX000
Hint: "... 
148278.13322004 6583872.57987633))" <-- parse error at position 382 within geometry

Changing the format like below, work:
select ST_GeomFromText(
'COMPOUNDCURVE ((
148278.13322004 6583872.57987633, 
148278.442646993 6583869.53683263, 
148281.480473411 6583869.89386295), 
CIRCULARSTRING (
148281.480473411 6583869.89386295, 
148285.471899962 6583867.00242207, 
148289.958865739 6583873.03635748, 
148282.521218313 6583878.57472433, 
148278.13322004 6583872.57987633))');

To clearify the Oracle geometry a gml version is supplied:

<gml:Polygon srsName="SDO:5850" xmlns:gml="http://www.opengis.net/gml">
<gml:exterior>
<gml:Ring>
<gml:curveMember><gml:Curve><gml:segments><gml:Arc>
<gml:posList srsDimension="3">
148278.13322004038 6583872.579876328 0.0 
148278.44264699327 6583869.53683263 0.0 
148281.4804734105 6583869.893862949 0.0 </gml:posList>
</gml:Arc></gml:segments></gml:Curve></gml:curveMember>
<gml:curveMember><gml:Curve><gml:segments><gml:LineStringSegment>
<gml:posList srsDimension="3">
148281.4804734105 6583869.893862949 0.0 
148285.4718999615 6583867.002422066 0.0 
148289.95886573888 6583873.036357478 0.0 
148282.52121831308 6583878.574724334 0.0 
148278.13322004038 6583872.579876328 0.0 </gml:posList>
</gml:LineStringSegment></gml:segments></gml:Curve></gml:curveMember>
</gml:Ring>
</gml:exterior>
</gml:Polygon>

**Comment by darold** [comment]
Thanks for the report. Please give a try to latest development code, commit 6c88d3b has fixed some issues on compound geometry export. There is still some issues that need to be fixed but let me know it it solves thisone or if you have any other error.
