### ISSUE TITLE
Foreign table definition for oracle_fdw is wrong

### ISSUE THREAD

**Issue by laurenz** [darold/ora2pg#560]
When I run ora2pg with `TYPE FDW`, it produces statements like

    CREATE FOREIGN TABLE social.email (
            id integer OPTIONS (key 'true') NOT NULL,
            address varchar(100) NOT NULL
    ) SERVER oracle OPTIONS( table 'SOCIAL.EMAIL');

But that is incorrect and will fail.

It should be

    OPTIONS(schema 'SOCIAL', table 'EMAIL')

**Comment by darold** [comment]
Hi Laurenz,

I'm not able to reproduce the issue. What version of Ora2Pg are you using, normally this might have been solved. If this is version 18.2, please send me the ora2pg.conf file.

Thanks for the report.

**Comment by laurenz** [comment]
Thanks for the answer.

I am using version 18.2, and this is my `ora2pg.conf` file:

    ORACLE_HOME     /u01/app/oracle/product/11.2.0/xe
    ORACLE_DSN      dbi:Oracle:
    ORACLE_USER     system
    ORACLE_PWD      changed_of_course
    SYSUSERS        HR
    USER_GRANTS     0
    EXPORT_SCHEMA   1
    NLS_LANG        AMERICAN_AMERICA.AL32UTF8
    CLIENT_ENCODING UTF8
    TYPE            TABLE,FDW
    FDW_SERVER      oracle
    KEEP_PKEY_NAMES 1

**Comment by darold** [comment]
Using your configuration and latest development code I'm not able to reproduce this issue:
```
CREATE FOREIGN TABLE news_docs (
        news_docs_id integer OPTIONS (key 'true') NOT NULL,
        docs_date timestamp NOT NULL,
        docs_subject varchar(100),
        docs_body text,
        active_flag smallint NOT NULL
) SERVER oracle OPTIONS(schema 'TESTDB', table 'NEWS_DOCS');
```
I think it is also fixed in version 18.2, you probably have an old version of the Perl Ora2Pg.pm and others somewhere that are used instead. You can try to override manually those libraries in the Perl library path to see if  this is the reason.

**Comment by laurenz** [comment]
I downloaded 18.2 from Github yesterday, and ora2pg has never been installed on this machine before.

I notice that there is a space between `(` and `table`, so it looks like `$schem` in your code is empty or `undef` and `$table` is `SOCIAL.EMAIL`, but my Perl knowledge is not good enough to debug this.

I'll close the issue as it is not very important for me.

**Comment by darold** [comment]
Oh I understand what can cause this issue. `$schem` is set when a schema is given and reading your configuration I was thinking that you was exporting schema HR but actually this is SYSUSERS. My bad, I will fix that asap but for now as a workaround you can export tables as foreign table for each schema by setting the SCHEMA directive.

**Comment by darold** [comment]
Commit 617f306 might solve this issue.

**Comment by laurenz** [comment]
I tested and that commit solves the problem.

Thank you!
