### ISSUE TITLE
Data Migration to PostgresSql from Oracle without partions and tablespaces

### ISSUE THREAD

**Issue by sangeetmen** [darold/ora2pg#561]
The Oracle database has been partitioned and has tablespaces specified .
But in PostgreSQL DB I don't wish to do the same. I have created the schema without any partitions. Also want to export data in the same format
Which directives should be activated in order to migrate data without the partition.

Currently while migrating data the script searches for `tablename_partitionname` relation which is not created in PostgreSQL.

How can this be tackled?
Thanks.

**Comment by darold** [comment]
You have to enable DISABLE_PARTITION, Ora2Pg will export all data from and into the main table name.

**Comment by sangeetmen** [comment]
That did the trick. Thanks
