### ISSUE TITLE
catch (and log) errors from Oracle DB

### ISSUE THREAD

**Issue by SebAlbert** [darold/ora2pg#562]
While getting the data out of Oracle with ora2pg (mode COPY or INSERT), from time to time I experience an exit code 1 (or 2), but I do not get any error message from ora2pg. Is there a possibility to catch (Database) errors during the export and print them to the specified logfile?

(I suspect the reason in my case could be "serializable transaction" failures, but I'd like to confirm this.)

**Comment by darold** [comment]
Usually any database error are traced by Ora2Pg even if they are not fatal.

Most of the time this kind of problem come from the fact that some data export processes have been interrupted violently and Ora2Pg is not able to dump any error message. Look at dmesg to see if OOM has killed an Ora2Pg process. Do you have such messages?

**Comment by SebAlbert** [comment]
Great hint, there are indeed OOM kills on perl processes. I cannot confirm upon first look whether these were the ora2pg processes, but it seems very likely.

What I observed is that this happens after a "batch" of data (one copy statement) was complete in the output file, not in the middle of a statement. (Maybe even exactly when moving on to the next table.)

Does this mean that there are memory leaks in ora2pg? Can I trace this down further?

**Comment by SebAlbert** [comment]
So, to be precise, the list of processes upon OOM kill say the killed process is called "perl", while there actually is another process with a different process ID called "ora2pg". I don't think I'm using ora2pg in multi-threaded / concurrent mode. The process listed as "ora2pg" is never killed by OOM. It might well be another perl script on that machine having a memory leak. That, then, would mean, that OOM is out of the game as a possible reason, unless ora2pg spawns processes/threads called "perl".

**Comment by darold** [comment]
I think this is the perl interpreter running an Ora2Pg process that was killed. You have two possibility:

  - limit the RAM used by Ora2Pg
  - desactivate the OOM killer

The first solution can be achieved by reducing DATA_LIMIT, if you have 10000 use 5000 instead.

The second solution is to disable the OOM Killer using:
```
sudo sysctl -w vm.overcommit_memory='2'
```
