### ISSUE TITLE
Can network lost issues be handled while migration

### ISSUE THREAD

**Issue by sangeetmen** [darold/ora2pg#564]
This suddenly occurred in the last migration , while migrating a bulk of data the network switch fluctuated for some time and connections to the destination was disturbed and Ora2pg terminated with the following error. 

`FATAL: 1 ... could not connect to server: Connection timed out (0x0000274C/10060)`

So now , I have to redo the process again as I am not able to isolate the records that could not be transferred.

Is there a way to make Ora2pg would wait and retry couple of times before it terminates. 
Any such directives that can do it.

Thanks

**Comment by sangeetmen** [comment]
Alternatively is there a way some ordering can be done in the `QUERY` directive on the records that are being migrated, by which we can determine the record number last migrated and then continue from the same/or next in the iteration.

**Comment by darold** [comment]
If you have an unstable network, I recommand you to import data localy and then perform a pg_dump to send the resulting dump file over the network. To answer to your question, such feature have not been implemented yet.
