### ISSUE TITLE
the sql query for dblink is not correct, when function has OUT parameter 

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#565]
There  are two generated functions on PostgreSQL side:
<pre>
ides_jmmaj=# CREATE OR REPLACE FUNCTION ides_procs.get_storno_najvplapre(mid_najvplapre bigint, OUT mdat_storna date)
 RETURNS date
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
        -- Change this to reflect the dblink connection string
        v_conn_str  text := format('port=%s dbname=%s user=%s', current_setting('port'), current_database(), current_user);
        v_query     text;

BEGIN
        v_query := 'SELECT true FROM get_storno_najvplapre_atx ( ' || quote_nullable(mID_NAJVPLAPRE) || ',' || quote_nullable(mDAT_STORNA) || ' )';
        PERFORM * FROM dblink(v_conn_str, v_query) AS p (ret boolean);

END;
$function$
;
CREATE OR REPLACE FUNCTION ides_procs.get_storno_najvplapre_atx(mid_najvplapre bigint, OUT mdat_storna date)
 RETURNS date
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
          /*
          BEGIN
          */
            SELECT DAT_STORNA INTO STRICT mDAT_STORNA
              FROM NAJVPLAPRE
              WHERE ID_NAJVPLAPRE = mID_NAJVPLAPRE;
          /*
          EXCEPTION
              WHEN OTHERS THEN
                raise_application_error( -20010 , ' UPRAV_HODNOTY_NAJPOLOZ --  NAJPREDP ' || SQLERRM || ' ' || mId_Predpis ) ;
          END;
           */
end;
$function$
</pre>

The query:
<pre>
v_query := 'SELECT true FROM get_storno_najvplapre_atx ( ' || quote_nullable(mID_NAJVPLAPRE) || ',' || quote_nullable(mDAT_STORNA) || ' )';
</pre>

The body should to look like:
<pre>
        v_query := 'SELECT mdat_storna FROM get_storno_najvplapre_atx ( ' || quote_nullable(mID_NAJVPLAPRE) || ',' || quote_nullable(mDAT_STORNA) || ' )';
        SELECT mDatStorna FROM dblink(v_conn_str, v_query) AS p (mDatStorna date) INTO mdat_storna;
</pre>

**Comment by darold** [comment]
Yes, this appears not very easy to fix and need time. I will see how I can fix that.

**Comment by okbob** [comment]
2017-10-11 9:09 GMT+02:00 Gilles Darold <notifications@github.com>:

> Yes, this appears not very easy to fix and need time. I will see how I can
> fix that.
>

sure. Probably some code used for procedure call translation can be used

**Comment by darold** [comment]
Commit 78845d9 solves this issue.
