### ISSUE TITLE
Can Ora2pg skip blob fields while uploading

### ISSUE THREAD

**Issue by sangeetmen** [darold/ora2pg#566]
Can we skip the blob fields or insert them as empty_blob()/empty_clob() or even as null while migrating tables having Blob and Clob contents?

**Comment by darold** [comment]
What is the reason for such feature?

**Comment by sangeetmen** [comment]
Migrating blob/clob consuming greater time and occasionally giving out of memory error.  
The blob/clob content is mostly empty and only in 10% of the entire records migrated.

**Comment by darold** [comment]
In my experiences running Ora2Pg on at least 4 cores and 8 GB is enough to perform a migration. The OOM can be avoid by reducing the DATA_LIMIT value to 5000 or 2500. If this is not enough for the BLOB fields you can set BLOB_LIMIT tu a much lower value, for example 100 or 50.

If you want to migrate terabyte or hundred of gigabytes database of course this is not enough, you need at least 16 (24 is better) cores and at least 64 GB of memory. Generaly I've observed it takes 1 hour / 100 GB to migrate data with such configuration with huge volume of CLOB/BLOB.

Removing CLOB/BLOB doesn't appears to be a solution for me, I don't think it is a good idea to truncate the data to avoid OOM unless you want to drop these data from the database. Importing them later will take the same time and OOM.

Note that I have a feature ("allow custom/user data transformation during export") in my todo list that could be used to set all CLOB/BLOB as NULL or anything else, but its development is not planned for the moment.

If you think an ETL can perform the work better you can use Ora2Pg to generate Kettle script by using `-t KETTLE` and try it.
