### ISSUE TITLE
Conversion function matched incorrectly inside function name

### ISSUE THREAD

**Issue by Torquem** [darold/ora2pg#567]
If user function contains known conversion function name, it is converted even though it is part of another function name.
The function parameter must match the conversion function's parameter.

Steps to reproduce:
CREATE FUNCTION FOO_TO_NUMBER(str IN VARCHAR2) RETURN NUMBER IS
  BEGIN
    RETURN 1;
  END;
/
CREATE VIEW FOO AS
  SELECT FOO_TO_NUMBER('1') TMP FROM DUAL;

ora2pg -t VIEW returns:
CREATE OR REPLACE VIEW foo (tmp) AS SELECT FOO_('1')::numeric  TMP;

Work aroud:
Rename function ;)

**Comment by darold** [comment]
Thanks for the report, commit c3f1706 might fix it.

**Comment by Torquem** [comment]
That was fast!

Verified to work in master [e4437d5](https://github.com/darold/ora2pg/commit/e4437d501fff0da480ac868f55c9664fa48def2a).

Thank you!
