### ISSUE TITLE
Like operator % at end of search string causes ending quote to match quote char in comment

### ISSUE THREAD

**Issue by Torquem** [darold/ora2pg#568]
Seems the % character escapes nect quote character and causes the end quote to be matched from comment at the end of the row.
Anything between is replaced by ?TEXTVALUEXXX?

Reproduce:
`
CREATE table foo_bar_table(
	"FOO" NUMERIC,
	"BAR" VARCHAR(2)
	);

CREATE OR REPLACE VIEW FOO_BAR_view AS
SELECT 
    (SELECT FOO FROM foo_bar_table  WHERE FOO = 1 AND FOO IN (SELECT FOO FROM foo_bar_table WHERE UPPER(BAR) = 'FOOBAR' AND UPPER(BAR) LIKE 'BAR%' AND FOO =  FOO)) TMP,      --  THIS WILL BE MISSING , '') SNAFU,
	FOO
FROM
    foo_bar_table;
`

Results from ora2pg view export:
`
CREATE OR REPLACE VIEW foo_bar_view (tmp, foo) AS SELECT 
    (SELECT FOO  FROM foo_bar_table  WHERE FOO = 1 AND FOO IN (SELECT FOO FROM foo_bar_table WHERE UPPER(BAR) = 'FOOBAR' AND UPPER(BAR) LIKE 'BAR%?TEXTVALUE150?') SNAFU,
	FOO
FROM
    foo_bar_table;
`

**Comment by darold** [comment]
This have already been fixed, please use latest development code and please confirm.

**Comment by Torquem** [comment]
Verified to work in master [e4437d5](https://github.com/darold/ora2pg/commit/e4437d501fff0da480ac868f55c9664fa48def2a).

Thank you!
