### ISSUE TITLE
Postgresql 10 partitioning Script Error

### ISSUE THREAD

**Issue by acmorillas** [darold/ora2pg#569]
Hi,
I´m testing the new feature of postgresql 10, table partitioning. I´m using ora2pg to extract partitions from an oracle database converting them to postgresql partitions.
The sql extracted looks like:
**CREATE TABLE core_hicalcorrelation_p201102 PARTITION OF core_hicalcorrelation
FOR VALUES FROM (MINVALUE) TO (to_date('2011-03-01 00:00:00','YYYY-MM-DD HH24:MI:SS'));**

But when you try to execute the script:

**psql:./schema/partitions/partition.sql:14: ERROR:  error de sintaxis en o cerca de Â«to_dateÂ»
LINE 2: FOR VALUES FROM (MINVALUE) TO (to_date(' 2011-03-01 00:00:00...
                                       ^
ERROR: an error occurs when importing file ./schema/partitions/partition.sql.**

I suspect there is a failure in the script creation or I´m making something wrong.

Regards,
Andrés.

**Comment by darold** [comment]
Hi Andrés,

Ora2Pg do not transform call to function in partition bound and PostgreSQL only accept constant here. You have to set manually the exact value returned by the function call. Here typically the call to `to_date()` might not be used I guess and the code should be:
```
CREATE TABLE core_hicalcorrelation_p201102
PARTITION OF core_hicalcorrelation
FOR VALUES FROM (MINVALUE) TO ('2011-03-01 00:00:00');
```
Ora2Pg doesn't translate this part automatically.

Regards,
