### ISSUE TITLE
How to call an existing Oracle pl/sql before querying the data from Oracle and export the data

### ISSUE THREAD

**Issue by tblackhawks** [darold/ora2pg#570]
Hi @darold: first of all thanks for the tool, we are starting to use this to import our Oracle tables and data.
What we want to do is to bring certain of data from our oracle based on specific context/partition.  This is not really a partition from ORACLE.  It's quite complex.
So before we call query like 'SELECT * FROM Employee' we want to call the existing oracle pl/sql in our case would be similar to the following:

call mypackora.open_context(3333);

How would I do this? Is this something that can be done?

Your responses are greatly appreciated.

**Comment by darold** [comment]
Hi,

There is a configuration directive called ORA_INITIAL_COMMAND. You just have to set it as follow:
```
 ORA_INITIAL_COMMAND      call mypackora.open_context(3333);
```
This command will be executed after each Oracle connection.

If you have more command to pass, you can use the directive multiple time.

Regards,

**Comment by tblackhawks** [comment]
Awesome.  we will try it!
Thank you
