### ISSUE TITLE
Ora2Pg - TEST the migration - verifying columns data.

### ISSUE THREAD

**Issue by subbaraonadendla** [darold/ora2pg#571]
Hi, 

I have used the Ora2Pg for my schema creation and migration. Its really a great tool. 

does the TEST action command only counts the number of rows in source and destination databases ? or does it also verifies the columns data as well ? 

Also i have only migrated few tables into the Postgresql from Oracle. is there a way only to verify the migrated objects only ?

please suggest. 

Regards
Subba.

**Comment by darold** [comment]
Hi,

Sorry for the response delay. The TEST action only count object and rows if `--count_rows-` is given at command line. For the moment you can not exclude/include tables/objects from the TEST action but maybe in the future. If you have exported multiple schema, it is not possible to check all at the same time, you need to execute the TEST action per schema.

Regards,
