### ISSUE TITLE
Still a missing PERFORM before a call to a function returning VOID

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#572]
Hello,

I have an Oracle procedure called DEBUG_TRACE in some of my packages.
Usually, ora2pg translates the calls correctly, adding "PERFORM " before, but when the call follows an "if...then" or "elsif...then", the PERFORM is not added and I get an invalid call, with this error:

psql:PG_PCK_GCL.sql:2084: ERROR:  "debug_trace" is not a known variable
LINE 241:                 DEBUG_TRACE[''||coalesce(C_PROCEDURE_NAME::v...

I am going to send you the package code and its translation too...
Rgds,
Eric

**Comment by darold** [comment]
Hi Eric,

I'm not able to reproduce this issue even with your code. The only calls that are not translated are the one commented so perhaps this have been activated latter or that you have forgot the -p option.

Regards,

**Comment by edelanoe** [comment]
Ok, this was a side effect of issue #541 
This is solved, thank you.
