### ISSUE TITLE
Double processing of function with two OUT parameters

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#573]
Hello,

In Oracle I have the following procedure with two OUT params:
PROCEDURE Fill_Gen_Ticket (p_Card_Id T_CARD.CARD_ID%TYPE, 
                               p_Ticket_Serial_Number M_TICKET.TICKET_SERIAL_NUMBER%TYPE, 
                               p_Type_Equip IN T_EQUIPMENT.TYPE_OF_EQUIPMENT_ID%TYPE, 
                               p_Date_Transaction_Begin T_TRX.DATE_TRANSACTION_BEGIN%TYPE, 
                               p_Generic_Ticket IN OUT GEASTRUCT.Struct_Generic_Ticket%ROWTYPE, 
                               p_result OUT VARCHAR2);

Ora2pg translates it apparently well: 
CREATE OR REPLACE FUNCTION pck_int.fill_gen_ticket (p_Card_Id T_CARD.CARD_ID%TYPE, p_Ticket_Serial_Number M_TICKET.TICKET_SERIAL_NUMBER%TYPE, p_Type_Equip T_EQUIPMENT.TYPE_OF_EQUIPMENT_ID%TYPE, p_Date_Transaction_Begin T_TRX.DATE_TRANSACTION_BEGIN%TYPE, p_Generic_Ticket INOUT GEASTRUCT.Struct_Generic_Ticket, p_result OUT text) AS $body$................

But its calls are wrongly translated, like if processed twice and with an error (";  := _ora2pg_r.p_result") at first processing :
SELECT * FROM SELECT * FROM pck_int.fill_gen_ticket(v_Ict.Card_Id, v_Ict.Ticket_Serial_Number, v_Eqt.Type_Of_Equipment_Id, v_Ict.Date_Transaction_Begin, p_Generic_Ticket) INTO STRICT _ora2pg_r; p_Generic_Ticket := _ora2pg_r.p_Generic_Ticket;  := _ora2pg_r.p_result INTO _ora2pg_r; p_Generic_Ticket := _ora2pg_r.p_Generic_Ticket; v_result_Ict := _ora2pg_r.p_result;

Rgds,
Eric

**Comment by edelanoe** [comment]
An other example with a different "error" part: it behaves like if the first processing is wrong, and the second one would be right...

Oracle:
PROCEDURE Check_Vehicle_Transit_Limit( p_Eqt IN GEASTRUCT.Struct_Eqt%ROWTYPE, 
                                       p_Itr IN GEASTRUCT.Struct_Itr%ROWTYPE, 
                                       p_Generic_Ticket IN OUT GEASTRUCT.Struct_Generic_Ticket%ROWTYPE, 
                                       p_Result_Itr IN OUT VARCHAR2);
Ora2pg definition (ok):
CREATE OR REPLACE FUNCTION pck_int.check_vehicle_transit_limit ( p_Eqt GEASTRUCT.Struct_Eqt, p_Itr GEASTRUCT.Struct_Itr, p_Generic_Ticket INOUT GEASTRUCT.Struct_Generic_Ticket, p_Result_Itr INOUT text) AS $body$

Ora2pg translation of function calls: (the error is "v_Eqt := _ora2pg_r.p_Generic_Ticket")

SELECT * FROM SELECT * FROM pck_int.check_vehicle_transit_limit( v_Eqt, v_Ict, p_Generic_Ticket, v_result_Ict ) INTO STRICT _ora2pg_r;  v_Eqt := _ora2pg_r.p_Generic_Ticket; v_result_Ict  := _ora2pg_r.p_Result_Itr INTO _ora2pg_r; p_Generic_Ticket := _ora2pg_r.p_Generic_Ticket; v_result_Ict  := _ora2pg_r.p_Result_Itr;

Rgds,
Eric

**Comment by darold** [comment]
That was not easy to solve but last commit a6c67a9 might fix this issue.

**Comment by edelanoe** [comment]
This is fixed, thank you
