### ISSUE TITLE
 MySQL VIEW with IF statement is not converted to CASE statement in PostgreSQL

### ISSUE THREAD

**Issue by krasandr** [darold/ora2pg#574]
Hi,
I try to convert many MySQL VIEWs with Ora2Pg to PostgreSQL, but many of them are complex and contains IF statements before and after conversion, not CASE statements. The problem is that PostgreSQL doesn't support IF statements in SQL (it is different from IF statement in PL/PGSQL, so MySQL have two different IF statements/implementations, one in "plain" SQL and another in stored procedure language, PostgreSQL supports only the latest), so VIEWs are incorrect and not possible to create. Is it possible, without manually editing all views one by one, to convert IF statements to CASE statements in VIEW definition with Ora2Pg, with logically right context/expression?

**Comment by darold** [comment]
Hi,

I think it could be done by Ora2Pg. Please send to my private email your MySQL view definition.

Regards,

**Comment by krasandr** [comment]
Hi again,
I just send to yours private email definitions of 4 different VIEWs from MySQL, with IF statements.
VIEWs are a little complex, but problem is not related to complexity, it happens with very simple VIEWs also, if they contains IF statement in definition.
Thank you.

**Comment by krasandr** [comment]
Hi, here is example of MySQL VIEW with IF statement, that PostgreSQL don't
support, but maybe it can be logically converted to CASE with Ora2Pg:

CREATE VIEW
    v_s_transfers
    (
        TransferID,
        TransferDate,
        FromStoreID,
        ToStoreID,
        FromDoctorID,
        ToDoctorID,
        TransferUserID,
        TransferLastUpdateTime,
        TransferDetailID,
        Quantity,
        SLotID,
        SLotNum,
        SLotExpireDate,
        InUnitPrice,
        InAmount,
        SDocID,
        ProductID,
        ProductName,
        ProductCode,
        CastProductCode,
        NzMedicamentID,
        AccountingCode,
        QuantityPerUnitName,
        QuantityInPack,
        StorePackPrice,
        NzPackPrice
    ) AS
SELECT
    `st`.`TransferID`                                                    AS
`TransferID`,
    `st`.`TransferDate`                                                  AS
`TransferDate`,
    `st`.`FromStoreID`                                                   AS
`FromStoreID`,
    `st`.`ToStoreID`                                                     AS
`ToStoreID`,
    `st`.`FromDoctorID`                                                  AS
`FromDoctorID`,
    `st`.`ToDoctorID`                                                    AS
`ToDoctorID`,
    `st`.`UserID`                                                        AS
`TransferUserID`,
    `st`.`LastUpdateTime`                                               AS
`TransferLastUpdateTime`,
    `std`.`TransferDetailID`                                             AS
`TransferDetailID`,
    `std`.`Quantity`                                                     AS
`Quantity`,
    `sl`.`SLotID`                                                        AS
`SLotID`,
    `sl`.`SLotNum`                                                       AS
`SLotNum`,
    `sl`.`SLotExpireDate`                                                AS
`SLotExpireDate`,
    `sl`.`InUnitPrice`                                                   AS
`InUnitPrice`,
    ROUND(`sl`.`InUnitPrice` * `std`.`Quantity`,2)                       AS
`InAmount`,
    `sl`.`SDocID`                                                        AS
`SDocID`,
    `sp`.`ProductID`                                                     AS
`ProductID`,
    `sp`.`ProductName`                                                   AS
`ProductName`,
    `sp`.`ProductCode`                                                   AS
`ProductCode`,
    IF(`sp`.`NzMedicamentID` IS NULL,`sp`.`ProductCode`,`nm`.`NzokCode`) AS
`CastProductCode`,
    `sp`.`NzMedicamentID`                                                AS
`NzMedicamentID`,
    `sp`.`AccountingCode`                                                AS
`AccountingCode`,
    `scqpu`.`QuantityPerUnitName`                                        AS
`QuantityPerUnitName`,
    ifnull(`nm`.`QuantityInPack`,1)                                      AS
`QuantityInPack`,
    `sl`.`InUnitPrice` * ifnull(`nm`.`QuantityInPack`,1)                 AS
`StorePackPrice`,
    IF(`nm`.`NzMedicamentID` IS
NULL,NULL,ROUND(`F_NzMedPackPrice`(`nm`.`NzMedicamentID`,
    `st`.`TransferDate`,`nm`.`QuantityInPack`),2)) AS `NzPackPrice`
FROM
    (((((`s_transfers` `st`
JOIN
    `s_transfer_details` `std`
ON
    (
        `st`.`TransferID` = `std`.`TransferID`))
JOIN
    `s_lots` `sl`
ON
    (
        `std`.`SLotID` = `sl`.`SLotID`))
JOIN
    `s_products` `sp`
ON
    (
        `sl`.`ProductID` = `sp`.`ProductID`))
JOIN
    `s_const_quantity_per_units` `scqpu`
ON
    (
        `sp`.`QuantityPerUnitID` = `scqpu`.`QuantityPerUnitID`))
LEFT JOIN
    `nz_medicaments` `nm`
ON
    (
        `sp`.`NzMedicamentID` = `nm`.`NzMedicamentID`));

2017-10-25 16:36 GMT+03:00 Gilles Darold <notifications@github.com>:

**Comment by darold** [comment]
Hi,

Commit b9a2b5c might solve this issue, please update to latest development code. The translation will only be applied to VIEW and QUERY export action type, let me know if it must be extended to other export like TRIGGER

**Comment by krasandr** [comment]
Everything is working fine, thank you (nested many "IF"s also are working fine).
I am now closing bug - there is no need to translate "IF" in TRIGGER, because it is another (second) type of "IF" and it is supported (it is same as in PL/PGSQL IF...THEN...END IF), so this translation is needed only for VIEW and QUERY.
