### ISSUE TITLE
missing paranthesis after migration to Postgres

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#575]
Oracle:
<pre>
TRIGGER "IDES_JMMAJ_AKT".NAJPLATBY_BU BEFORE UPDATE
ON  NAJPLATBY
FOR EACH ROW

DECLARE
  mRecNajplatby  NAJPLATBY%ROWTYPE;
  mWhere VARCHAR2(4000);
  mPomDefaraj NAJPLATBY.DEFARAJ%TYPE;
  --mPomDefaraj_str NAJPLATBY.DEFARAJ_STR%TYPE;
  mOldDEFARAJ_STR VARCHAR2(4000);
  mID_NAJUPOMCEL NAJUPOMCEL.ID_NAJUPOMCEL%TYPE;
  mChyba boolean;
  mRozpis_max boolean;
  mRozdil_max_neur NUMBER;
BEGIN

--- vypnout triger pro funkci zmena_id_najvztah_evidence 
--if  RRRUTIL.G_VYPNOUT_NAJPLATBY_TRIGER is NULL then
if  RRRUTIL.R_G_VYPNOUT_NAJPLATBY_TRIGER() is NULL then

    ----  ZACATEK DEFAULT CAST

     :new.DATZMENY := SYSDATE;

    ----  KONEC DEFAULT CAST

      --- REN PRIDANO 07.12.2012 KVULI PREVOD DES
      IF LENGTH(:new.OBDOBI_OD) = 10 THEN
        :new.OBDOBI_OD := SUBSTR(:new.OBDOBI_OD,4,7);
      END IF;
      IF LENGTH(:new.OBDOBI_DO) = 10 THEN
        :new.OBDOBI_DO := SUBSTR(:new.OBDOBI_DO,4,7);
      END IF;

      IF (( :new.UCE_DOKLAD_KOD IS NOT NULL OR 
         :new.UCE_DOKLAD_CISLO IS NOT NULL )
         AND ((( :new.UCE_DOKLAD_KOD <> :old.UCE_DOKLAD_KOD )
          OR ( :new.UCE_DOKLAD_CISLO <> :old.UCE_DOKLAD_CISLO ))
          OR (( :new.UCE_DOKLAD_KOD IS NOT NULL AND :old.UCE_DOKLAD_KOD IS NULL )
             OR ( :new.UCE_DOKLAD_CISLO IS NOT NULL AND :old.UCE_DOKLAD_CISLO IS NULL ))))
      THEN
         ---raise_application_error(-20010, 'ddddddddddddddddd' );
        :new.UCE_DOKLAD:= ides_concat(Trim(:new.UCE_DOKLAD_KOD) , ' ' , TO_CHAR(:new.UCE_DOKLAD_CISLO));
      END IF ;

      IF :new.DATUM_ZAPLACENI IS NOT NULL THEN
        :new.ROK := EXTRACT( YEAR FROM :new.DATUM_ZAPLACENI  );
        :new.MESIC := EXTRACT( MONTH FROM :new.DATUM_ZAPLACENI  );
      END IF ;

      IF ( :new.ECASTKACELKEM <> :old.ECASTKACELKEM ) THEN
        :new.ENEURCENO := :new.ECASTKACELKEM;
        :new.CASTKACELKEM := :new.ECASTKACELKEM;
        IF :new.ROZEPIS_PLATBU = 'O' THEN
          :new.ENEURCENO := 0;
        END IF;
      END IF;

      
      IF :new.FAKTURA_NAJVZTAH IS NULL THEN
        IF :new.ID_NAJVZTAH IS NOT NULL THEN
          :new.FAKTURA_NAJVZTAH := 'N';
        END IF; 
      END IF;  

      IF :new.FAKTURA_NAJVZTAH = 'N' THEN
        :new.ID_UCEHLAFAK := NULL ;
      END IF;

      IF :new.FAKTURA_NAJVZTAH = 'F' THEN
        :new.ID_NAJVZTAH := NULL ;
      END IF;

      IF :new.EVRACENO IS NULL THEN
        :new.EVRACENO := 0;
      END IF;
      
      IF :new.VRATKA IS  NULL THEN
        :new.VRATKA := 'N';
      END IF;
      /*
      INSERT INTO RRRNAJUZA_ERR ( AKCE , TEXT , CHYBA )
               VALUES ( 'NAJPLATBY_BU_A' , :new.FAKTURA_NAJVZTAH || ' ID_UCEHLAFAK ' || :new.ID_UCEHLAFAK  , NULL );
      */

      IF :new.ROZEPIS_PLATBU = 'A' THEN
        mRecNajplatby.Obdobi_Od := :new.OBDOBI_OD;
        mRecNajplatby.Obdobi_Do := :new.OBDOBI_DO;
        mRecNajplatby.Datum_Zaplaceni := :new.Datum_Zaplaceni;
        mRecNajplatby.Datum_Bankvypis := :new.Datum_Bankvypis;
        mRecNajplatby.Uce_Doklad := :new.Uce_Doklad;
        mRecNajplatby.Vars := :new.Vars;
        mRecNajplatby.ECASTKACELKEM := :new.ECASTKACELKEM;
        mRecNajplatby.CASTKACELKEM := :new.CASTKACELKEM;
        mRecNajplatby.ENEURCENO := :new.ENEURCENO;
        mRozpis_max := false;
        IF (( :new.ECASTKA_ROZPIS_MAX IS NOT NULL ) AND ( :new.ECASTKA_ROZPIS_MAX > 0 ) 
           AND ( :new.ECASTKA_ROZPIS_MAX < :new.ENEURCENO )) THEN
          mRecNajplatby.ENEURCENO := :new.ECASTKA_ROZPIS_MAX;
          mRozdil_max_neur := :new.ENEURCENO - :new.ECASTKA_ROZPIS_MAX;
          mRozpis_max := true;
        END IF;
         
        mRecNajplatby.ID_DRUPRE := :new.ID_DRUPRE;
        mRecNajplatby.ID_CTYPPRED := :new.ID_CTYPPRED;
        mRecNajplatby.ID_NAJVZTAH := :new.ID_NAJVZTAH;
        mRecNajplatby.ID_UCEHLAFAK := :new.ID_UCEHLAFAK;
        mRecNajplatby.ID_NAJPLATBY := :new.ID_NAJPLATBY;
        mRecNajplatby.ID_MENA := :new.ID_MENA;
        mRecNajplatby.ID_ASPRAVCE := :new.ID_ASPRAVCE;
        mRecNajplatby.ID_APROVOZNA := :new.ID_APROVOZNA;
        mRecNajplatby.ID_CODDNAJVZT := :new.ID_CODDNAJVZT;
        mRecNajplatby.KURS := :new.KURS;
        mRecNajplatby.KURS_DATUM := :new.KURS_DATUM;
        mRecNajplatby.ID_CODDNAJVZT := :new.ID_CODDNAJVZT;
        mRecNajplatby.Zp_Nahr := :new.Zp_Nahr;
        mRecNajplatby.Id_Nahr := :new.Id_Nahr;
        mRecNajplatby.EVIDENCE_NAJVZTAH  := :new.EVIDENCE_NAJVZTAH ;
        mRecNajplatby.Id_DPLA := :new.Id_DPLA;
        mRecNajplatby.DEFVYNOS := :new.DEFVYNOS;
        mRecNajplatby.DEF_OBDOBIROZ := :new.DEF_OBDOBIROZ;
        mRecNajplatby.ID_NAJPOKPLA := :new.ID_NAJPOKPLA;
        mRecNajplatby.ID_OBDOBIBNEROZ := :new.ID_OBDOBIBNEROZ;
        mRecNajplatby.ID_NAJAKPLATBY := :new.ID_NAJAKPLATBY;
        IF :new.LIDENT_ZMENA IS NOT NULL THEN
          mRecNajplatby.LIDENT := :new.LIDENT_ZMENA;
        ELSE
          mRecNajplatby.LIDENT := :new.LIDENT;
        END IF;
        :new.ID_NAJPOKPLA := NULL;
        :new.ID_OBDOBIBNEROZ := NULL;
        /*
        INSERT INTO RRRNAJUZA_ERR ( AKCE , TEXT , CHYBA )
               VALUES ( 'NAJPLATBY_BU' , NULL , NULL );
        */

        IF :new.FAKTURA_NAJVZTAH <> 'A' THEN

          ROZPIS_PLATBY(mRecNajplatby  , 'I' , '' );
          IF :new.ZP_NAHR = 'I' THEN
             :new.Id_Nahr := NULL;
          END IF;

          --- dalsi rozpis podle definice napr V - upominky
          IF mRecNajplatby.EVIDENCE_NAJVZTAH = 'V' THEN
            BEGIN
              SELECT ID_NAJUPOMCEL INTO mID_NAJUPOMCEL
                FROM V_NAJVAVPEPO_POLOZ
                WHERE ID_NAJAVPEPO_A = mRecNajplatby.ID_NAHR
                 AND ROWNUM < 2;
              IF mID_NAJUPOMCEL IS NOT NULL THEN
                mRecNajplatby.ID_NAHR := mID_NAJUPOMCEL;
                :new.ID_NAHR := mID_NAJUPOMCEL;
                mRecNajplatby.EVIDENCE_NAJVZTAH := 'U' ;
                :new.EVIDENCE_NAJVZTAH := 'U' ;
                mRecNajplatby.ZP_NAHR := 'T' ;
                :new.ZP_NAHR := 'T' ;
              END IF;

            EXCEPTION
              WHEN NO_DATA_FOUND THEN
                mChyba := true;
            END ;

          END IF;
          IF (( :new.EVIDENCE_NAJVZTAH = 'U' )
            AND ( mRecNajplatby.Eneurceno > 0 )) THEN
              ROZPIS_PLATBY_DALSI(mRecNajplatby  , 'I' );
          END IF;
        END IF;

        IF mRozpis_max = false THEN
          :new.ENEURCENO := mRecNajplatby.ENEURCENO ;
        ELSE
          :new.ENEURCENO := mRozdil_max_neur + mRecNajplatby.ENEURCENO ;
        END IF;  
        IF :new.ENEURCENO <> 0 THEN
          IF mRecNajplatby.Zp_Nahr = 'S' THEN
            UPDATE NAJAVPIPO
              SET CHYBA = 'A'
              WHERE ID_NAJAVPIPO = :new.ID_VSTUP;
          END IF;
        END IF;
      END IF;

      IF :new.ENEURCENO <> 0 THEN
        :new.ZIV_EVIDENCE := '2';
      ELSE
        :new.ZIV_EVIDENCE := '1';
      END IF ;

      IF :new.ECASTKACELKEM IS NULL THEN
        :new.ECASTKACELKEM := 0;
      END IF;

      IF( :new.ENEURCENO <> :old.ENEURCENO ) THEN
        :new.NEURCENO := :new.ENEURCENO * :new.KURS;
      END IF;

      IF( :new.EVRACENO <> :old.EVRACENO ) THEN
        :new.VRACENO := :new.EVRACENO * :new.KURS;
      END IF;

      

      /*  stare defaraj

      mWhere := ' AND  (  NAJPLATBY = ''A'' ) ';

      IF  ( :new.ID_NAJVZTAH IS NOT NULL  )  THEN
        mWhere := mWhere || ' AND ( NAJPLATBY_TYP = ''N'' ) ';
      END IF;

      IF  ( :new.ID_UCEHLAFAK IS NOT NULL  )  THEN
        mWhere := mWhere || ' AND ( NAJPLATBY_TYP  = ''F'' ) ';
      END IF;

      IF (( :new.ID_NAJVZTAH IS NULL ) AND
          ( :new.ID_UCEHLAFAK IS NULL ) )  THEN

        :new.DEFARAJ := 1;
        mOldDEFARAJ_STR := ',1,';

        GET_DEFARAJ_PODLE_RAJONU( :new.DEFARAJ  , :new.ID_ASPRAVCE  , :new.ID_APROVOZNA  , mWhere ,  ''    ) ;

      END IF;
      */

      --IF :new.ENEURCENO = 0  THEN

         IF(( :new.DEFARAJ_STR = :old.DEFARAJ_STR )
           OR ( :new.DEFARAJ_STR  IS NULL AND :old.DEFARAJ_STR IS NULL ) ) THEN

           IF (( :new.ID_NAJVZTAH IS NOT NULL  AND :old.ID_NAJVZTAH  IS NULL )
             OR ( :new.ID_NAJVZTAH <> :old.ID_NAJVZTAH ) OR ( :new.ID_NAJVZTAH IS NOT NULL  AND :new.ZMENA_RAJ = 'A' ) )  THEN
             :new.DEFARAJ := 1;
             mOldDEFARAJ_STR := ',1,';
             FOR qNajvztah IN
              ( SELECT DEFARAJ , DEFARAJ_STR
                    FROM SSSHLEDEJ_A
                    WHERE ID_NAJVZTAH = :new.ID_NAJVZTAH
                    AND TYP = 'N' )
             LOOP
               mPomDefaraj := qNajvztah.DEFARAJ;
               PRIDEJ_NEW_DEFARAJ( :new.DEFARAJ , mPomDefaraj );
               :new.DEFARAJ_STR := SUBSTR(qNajvztah.DEFARAJ_STR , 2 , LENGTH(qNajvztah.DEFARAJ_STR) - 1 );
               SET_DEFARAJ_STR_BU( :new.DEFARAJ_STR , mOldDEFARAJ_STR  );
               mOldDEFARAJ_STR := :new.DEFARAJ_STR;
             END LOOP;
           END IF;

           IF  ( :new.ID_UCEHLAFAK IS NOT NULL  )  THEN
             :new.DEFARAJ := 1;
             SELECT DEFARAJ , DEFARAJ_STR INTO :new.DEFARAJ , :new.DEFARAJ_STR
               FROM UCEHLAFAK
               WHERE ID_UCEHLAFAK = :new.ID_UCEHLAFAK;
           END IF;

           IF (( :new.ID_UCEHLAFAK IS NULL AND :new.ID_NAJVZTAH IS NULL )
              AND ( :old.ID_UCEHLAFAK IS NOT NULL OR :old.ID_NAJVZTAH IS NOT NULL )) THEN
             :new.DEFARAJ_STR := ',1,';
             GET_DEFARAJ_PODLE_RAJONU_STR( :new.DEFARAJ_STR  , :new.ID_ASPRAVCE  , :new.ID_APROVOZNA  , mWhere ,  ''    ) ;
            END IF;

         ELSE
           SET_DEFARAJ_STR_BU( :new.DEFARAJ_STR , :old.DEFARAJ_STR  );
         END IF;

       --END IF;

       

       IF :new.FAKTURA_NAJVZTAH <> 'A' THEN
         IF ( :new.ID_UCEHLAFAK IS NULL )
           AND ( :new.ID_NAJVZTAH IS NULL ) THEN
             :new.FAKTURA_NAJVZTAH := NULL ;
         END IF;

       END IF;

      
       

      :new.ROZEPIS_PLATBU := 'N';
      :new.ZMENA_RAJ := 'N';
      :new.ECASTKA_ROZPIS_MAX := NULL;
      
      BEGIN
        IF :new.UCE_DOKLAD_KOD IS NULL AND :new.UCE_DOKLAD_CISLO IS NULL THEN
         UPRAV_UCEDOKLAD( :new.UCE_DOKLAD , :new.UCE_DOKLAD_KOD  , :new.UCE_DOKLAD_CISLO , NULL  );
        END IF;
      EXCEPTION
        WHEN OTHERS THEN
          mChyba := true;
      END;
      
      IF :new.CHYBA_TEXT IS NULL THEN
        :new.CHYBA := 'N';
      ELSE
        :new.CHYBA := 'A';
      END IF;

      :new.ID_NAJAKPLATBY := NULL;
      --  REN  23.07.2009 nulovat protoye pak to dela problem priroyepisovani plateb
      :new.ID_DRUPRE := NULL;
      :new.ID_CTYPPRED := NULL;
      --- REN 08.04.2011 pridan defvynos
      :new.DEFVYNOS := 'A';
      ---- REN 09.12.2011
      IF :new.ZP_NAHR = 'T' THEN
        :new.ZP_NAHR := NULL;
      END IF;
      
end if; --- RRRUTIL.G_VYPNOUT_NAJPLATBY_TRIGER :='A';
  
END ;
</pre>

The problematic part is a expression
<pre>
           IF (( :new.ID_UCEHLAFAK IS NULL AND :new.ID_NAJVZTAH IS NULL )
              AND ( :old.ID_UCEHLAFAK IS NOT NULL OR :old.ID_NAJVZTAH IS NOT NULL )) THEN
             :new.DEFARAJ_STR := ',1,';
             GET_DEFARAJ_PODLE_RAJONU_STR( :new.DEFARAJ_STR  , :new.ID_ASPRAVCE  , :new.ID_APROVOZNA  , mWhere ,  ''    ) ;
            END IF;
</pre>

PostgreSQL:
<pre>
           IF ( NEW.ID_UCEHLAFAK IS NULL AND NEW.ID_NAJVZTAH IS NULL  AND  OLD.ID_UCEHLAFAK IS NOT NULL OR OLD.ID_NAJVZTAH IS NOT NULL ) THEN
             NEW.DEFARAJ_STR := ',1,';
              NEW.DEFARAJ_STR := GET_DEFARAJ_PODLE_RAJONU_STR( NEW.DEFARAJ_STR, NEW.ID_ASPRAVCE, NEW.ID_APROVOZNA, mWhere, ''    );
            END IF;
</pre>
The expression should be:
<pre>
 NEW.ID_UCEHLAFAK IS NULL AND NEW.ID_NAJVZTAH IS NULL  AND  (OLD.ID_UCEHLAFAK IS NOT NULL OR OLD.ID_NAJVZTAH IS NOT NULL)
</pre>

**Comment by darold** [comment]
Fixed with commit 2dc9a95.

**Comment by okbob** [comment]
This issue is fixed. Thank you
