### ISSUE TITLE
missing STRICT for EXECUTE INTO

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#576]
The rules for SELECT INTO should be applied on EXECUTE INTO.

Oracle:
<pre>
              BEGIN

                 EXECUTE IMMEDIATE  mSQLUCEPARPOL_ALL INTO mID_UCEPARPOL, mID_CISDPH;
               EXCEPTION
                 WHEN NO_DATA_FOUND THEN
                   mNenasel := true;
                 WHEN TOO_MANY_ROWS THEN
                   mVice_predkontace := true;
                   raise_application_error( -20035 , 'Vice predkontací !!!!' );
               END ;
</pre>

PostgreSQL:
<pre>
            BEGIN

                 EXECUTE  mSQLUCEPARPOL_ALL INTO mID_UCEPARPOL, mID_CISDPH;
               EXCEPTION
                 WHEN NO_DATA_FOUND THEN
                   mNenasel := true;
                 WHEN TOO_MANY_ROWS THEN
                   mVice_predkontace := true;
                   RAISE EXCEPTION '%', 'Vice predkontací !!!!' USING ERRCODE = '45035';
               END;
</pre>

In this case should be:
<pre>

             BEGIN

                 EXECUTE  mSQLUCEPARPOL_ALL INTO STRICT mID_UCEPARPOL, mID_CISDPH;
               EXCEPTION
                 WHEN NO_DATA_FOUND THEN
                   mNenasel := true;
                 WHEN TOO_MANY_ROWS THEN
                   mVice_predkontace := true;
                   RAISE EXCEPTION '%', 'Vice predkontací !!!!' USING ERRCODE = '45035';
               END;
</pre>

**Comment by darold** [comment]
Fixed with commit 2d1db01.

**Comment by okbob** [comment]
It is working, Thank you
