### ISSUE TITLE
Some different bugs when convert "CREATE TABLE" from MySQL to PostgreSQL with Ora2Pg

### ISSUE THREAD

**Issue by krasandr** [darold/ora2pg#577]
Some different bugs when convert "CREATE TABLE" from MySQL to PostgreSQL with Ora2Pg
(it is very easy to be reproduced).

Original MySQL DDL:

CREATE TABLE
    g_medical
    (
        GMedID INT unsigned NOT NULL AUTO_INCREMENT,
        GMedTypeID INT unsigned NOT NULL,
        GVisitDateTime DATETIME NOT NULL,
        DoctorID INT(10) unsigned NOT NULL,
        PatientID INT(10) unsigned NOT NULL,
        GBlob mediumblob NOT NULL,
        UserID INT(10) unsigned DEFAULT 1 NOT NULL,
        LastUpdateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON
    UPDATE
        CURRENT_TIMESTAMP,
        PRIMARY KEY (GMedID),
        CONSTRAINT FK_g_medical_doctors_DoctorID FOREIGN KEY (DoctorID) REFERENCES `doctors`
        (`DoctorID`) ,
        CONSTRAINT FK_g_medical_g_medical_types_GMedTypeID FOREIGN KEY (GMedTypeID) REFERENCES
        `g_medical_types` (`GMedTypeID`) ,
        CONSTRAINT FK_g_medical_patients_PatientID FOREIGN KEY (PatientID) REFERENCES `patients`
        (`PatientID`) ,
        CONSTRAINT FK_g_medical_users_UserID FOREIGN KEY (UserID) REFERENCES `users` (`UserID`),
        INDEX FK_g_medical_doctors_DoctorID (DoctorID),
        INDEX FK_g_medical_g_medical_types_GMedTypeID (GMedTypeID),
        INDEX FK_g_medical_patients_PatientID (PatientID),
        INDEX FK_g_medical_users_UserID (UserID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;

Issue 1: If you use "preserve case" configuration option, somewhere in Ora2Pg code, all names of columns (no matter of preserve case configuration option) are given with small cases, so names of sequences for primary keys (serial analogue of "auto increment" MySQL option) is different from default pattern and PostgreSQL cannot find sequence names and comments for columns (log is from PostgreSQL 10):

2017-10-19 16:58:36.143 EEST [8463] STATEMENT:  CREATE TABLE g_medical (
		gvisitdatetime timestamp without time zone NOT NULL,
		lastupdatetime timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP::(0)::timestamp without time zone,
		userid integer NOT NULL DEFAULT 1,
		patientid integer NOT NULL,
		doctorid integer NOT NULL,
		gblob bytea NOT NULL,
		gmedtypeid integer NOT NULL,
		gmedid serial
	) ;
2017-10-19 16:58:36.143 EEST [8463] ERROR:  relation "g_medical_gmedid_seq" does not exist
2017-10-19 16:58:36.143 EEST [8463] STATEMENT:  ALTER SEQUENCE g_medical_gmedid_seq RESTART WITH 1;

So, right name of sequence must be g_medical_GMedID_seq (by default pattern from original MySQL code, but in PostgreSQL logs all names are with small letters, the same situation is happened with COMMENT too). After migration of DDL, for same table, in SQL file is written:

CREATE TABLE "g_medical" (
        "UserID" integer NOT NULL DEFAULT 1,
        "PatientID" integer NOT NULL,
        "DoctorID" integer NOT NULL,
        "GVisitDateTime" timestamp without time zone NOT NULL,
        "LastUpdateTime" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP::(0)::timestamp without time zone,
        "GBlob" bytea NOT NULL,
        "GMedTypeID" integer NOT NULL,
        "GMedID" serial
) ;
ALTER SEQUENCE "g_medical_gmedid_seq" RESTART WITH 1;
CREATE INDEX "FK_g_medical_users_UserID" ON "g_medical" ("UserID");
CREATE INDEX "FK_g_medical_patients_PatientID" ON "g_medical" ("PatientID");
CREATE INDEX "FK_g_medical_doctors_DoctorID" ON "g_medical" ("DoctorID");
CREATE INDEX "FK_g_medical_g_medical_types_GMedTypeID" ON "g_medical" ("GMedTypeID");

but, error in PostgreSQL code is:
2017-10-19 16:58:36.143 EEST [8463] ERROR:  relation "g_medical_gmedid_seq" does not exist
2017-10-19 16:58:36.143 EEST [8463] STATEMENT:  ALTER SEQUENCE g_medical_gmedid_seq RESTART WITH 1;
or, with another examples:

2017-10-19 16:58:40.536 EEST [8463] STATEMENT:  CREATE TABLE w_appointment_patients (
		lastupdatetime timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP::(0)::timestamp without time zone,
		reservedatetime timestamp without time zone NOT NULL,
		appotypeid integer NOT NULL DEFAULT 1,
		userid integer NOT NULL,
		patientid integer,
		wpatientname varchar(765) NOT NULL,
		debugnote varchar(765),
		wduration integer NOT NULL DEFAULT 0,
		wpatientmobile varchar(765),
		workappmetaid integer NOT NULL,
		wappointmentpatientid serial,
		wappointmentnote text,
		wpatientidentnumber varchar(765),
		wappointmenttime time without time zone NOT NULL,
		isreserved bit varying(1) NOT NULL DEFAULT b'0',
		iscanceled bit varying(1) NOT NULL DEFAULT b'0',
		isfromsite bit varying(1) NOT NULL
	) ;
2017-10-19 16:58:40.536 EEST [8463] ERROR:  relation "w_appointment_patients_wappointmentpatientid_seq" does not exist
2017-10-19 16:58:40.536 EEST [8463] STATEMENT:  ALTER SEQUENCE w_appointment_patients_wappointmentpatientid_seq RESTART WITH 2622;
2017-10-19 16:58:40.536 EEST [8463] ERROR:  relation "w_appointment_patients" does not exist
2017-10-19 16:58:40.536 EEST [8463] STATEMENT:  COMMENT ON COLUMN w_appointment_patients.debugnote IS E'da se iztrie';
2017-10-19 16:58:40.536 EEST [8463] ERROR:  relation "w_appointment_patients" does not exist
2017-10-19 16:58:40.536 EEST [8463] STATEMENT:  COMMENT ON COLUMN w_appointment_patients.wduration IS E'prodaljitelnost';

Issue 2 (it is not related to "preserve case" configuration option).
From first example, there is problem with column:
LastUpdateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON
    UPDATE
        CURRENT_TIMESTAMP,
After converting from MySQL to PostgreSQL, in SQL file is written:
        "LastUpdateTime" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP::(0)::timestamp without time zone,
but, there is problem with parenthesis and zero parameter ::(0)::
If I manually replace all occurences of ::(0):: with ::, i.e. it must be right:
"LastUpdateTime" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP::timestamp without time zone,
all is O.K. in loading DDL in psql. otherwise error in PostgreSQL log is:

2017-10-19 16:58:36.143 EEST [8463] ERROR:  syntax error at or near "(" at character 160
2017-10-19 16:58:36.143 EEST [8463] STATEMENT:  CREATE TABLE g_medical (
                gvisitdatetime timestamp without time zone NOT NULL,
                lastupdatetime timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP::(0)::timestamp without time zone,
                userid integer NOT NULL DEFAULT 1,
                patientid integer NOT NULL,
                doctorid integer NOT NULL,
                gblob bytea NOT NULL,
                gmedtypeid integer NOT NULL,
                gmedid serial
        ) ;

The bug is general, so it is very easy to be reproduced, no matter of complexity of table DDL.

**Comment by darold** [comment]
Commit b7b7061 fixes the first issue when PRESERVE_CASE is enabled.

**Comment by darold** [comment]
Commit 56f38ce fixes the second issue on current_timestamp() translation. Additionally commit b1027aa fix a bug on auto_increment export and columns export order that was not respecting the creation order.

Please use latest development code and let me know the result at your side.

**Comment by krasandr** [comment]
There is a new bug, after new fixes (it did't exists before, MySQL database and schema is exactly the same as before, unchanged)). 
There is a (old) table with column name "type" (keyword in PostgreSQL). In MySQL DDL is:

CREATE TABLE
    const_location_cities
    (
        CityID bigint unsigned NOT NULL AUTO_INCREMENT,
        StateID INT(10) unsigned NOT NULL,
        type enum('city','town','resort','village','villa','area') COLLATE utf8_unicode_ci DEFAULT
        'city' NOT NULL,
        bg_name VARCHAR(50) NOT NULL,
        en_name VARCHAR(50) NOT NULL,
        RegionID INT(10) unsigned NOT NULL,
        PRIMARY KEY (CityID),
        CONSTRAINT FK_const_location_cities_const_location_states_StateID FOREIGN KEY (StateID)
        REFERENCES `const_location_states` (`StateID`) ,
        CONSTRAINT FK_const_location_cities_const_regions_RegionID FOREIGN KEY (RegionID)
        REFERENCES `const_regions` (`RegionID`),
        INDEX IX_const_location_cities_bg_name (bg_name),
        INDEX FK_const_location_cities_const_location_states_StateID (StateID),
        INDEX FK_const_location_cities_const_regions_RegionID (RegionID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;

 In PostgreSQL, after new fixes, DDL is with error for column "type in alter ... part (I don't know why this alter/check constraint is in main table file for ora2pg -d -m -t TABLE -o table.sql)":

CREATE TABLE "const_location_cities" (
<------>"CityID" bigserial,
<------>"StateID" integer NOT NULL,
<------>"type" text NOT NULL DEFAULT 'city',
<------>"bg_name" varchar(150) NOT NULL,
<------>"en_name" varchar(150) NOT NULL DEFAULT '',
<------>"RegionID" integer NOT NULL
) ;
ALTER SEQUENCE "const_location_cities_CityID_seq" RESTART WITH 4909;
ALTER TABLE "const_location_cities" ADD CONSTRAINT "const_location_cities"_type_chk CHECK (type IN (3));

I use configuration directives (no matter if PRESERVE_CASE is 0 or 1, error is the same):
FILE_PER_CONSTRAINT<--->1
FILE_PER_INDEX<><------>1
FILE_PER_FKEYS<><------>1
FILE_PER_TABLE<>1
(but if I leave default values, result is the same, i.e. bug is not related to separation of files):
CREATE TABLE "const_location_cities" (
<------>"CityID" bigserial,
<------>"StateID" integer NOT NULL,
<------>"type" text NOT NULL DEFAULT 'city',
<------>"bg_name" varchar(150) NOT NULL,
<------>"en_name" varchar(150) NOT NULL DEFAULT '',
<------>"RegionID" integer NOT NULL
) ;
ALTER SEQUENCE "const_location_cities_CityID_seq" RESTART WITH 4909;
ALTER TABLE "const_location_cities" ADD CONSTRAINT "const_location_cities"_type_chk CHECK (type IN (3));
CREATE INDEX "IX_const_location_cities_bg_name" ON "const_location_cities" ("bg_name");
CREATE INDEX "FK_const_location_cities_const_location_states_StateID" ON "const_location_cities" ("StateID");
CREATE INDEX "FK_const_location_cities_const_regions_RegionID" ON "const_location_cities" ("RegionID");
ALTER TABLE "const_location_cities" ADD PRIMARY KEY ("CityID");

Before this fixes, conversion was successful (I also tried now with
USE_RESERVED_WORDS<---->1
but without success):

CREATE TABLE "const_location_cities" (
<------>"StateID" integer NOT NULL,
<------>"type" text NOT NULL DEFAULT 'city',
<------>"bg_name" varchar(150) NOT NULL,
<------>"RegionID" integer NOT NULL,
<------>"CityID" bigserial,
<------>"en_name" varchar(150) NOT NULL DEFAULT ''
) ;
ALTER SEQUENCE "const_location_cities_cityid_seq" RESTART WITH 4909;
ALTER TABLE "const_location_cities" ADD CONSTRAINT "const_location_cities"_type_chk CHECK (type IN ('city','town','resort','village','villa','area'));
CREATE INDEX "IX_const_location_cities_bg_name" ON "const_location_cities" ("bg_name");
CREATE INDEX "FK_const_location_cities_const_location_states_StateID" ON "const_location_cities" ("StateID");
CREATE INDEX "FK_const_location_cities_const_regions_RegionID" ON "const_location_cities" ("RegionID");
ALTER TABLE "const_location_cities" ADD PRIMARY KEY ("CityID");

and (again, before new fixes, with preserve case, also conversion was successfull):

CREATE TABLE "const_location_cities" (
<------>"StateID" integer NOT NULL,
<------>"type" text NOT NULL DEFAULT 'city',
<------>"bg_name" varchar(150) NOT NULL,
<------>"RegionID" integer NOT NULL,
<------>"CityID" bigserial,
<------>"en_name" varchar(150) NOT NULL DEFAULT ''
) ;
ALTER SEQUENCE "const_location_cities_cityid_seq" RESTART WITH 4909;
ALTER TABLE "const_location_cities" ADD CONSTRAINT "const_location_cities"_type_chk CHECK (type IN ('city','town','resort','village','villa','area'));
CREATE INDEX "IX_const_location_cities_bg_name" ON "const_location_cities" ("bg_name");
CREATE INDEX "FK_const_location_cities_const_location_states_StateID" ON "const_location_cities" ("StateID");
CREATE INDEX "FK_const_location_cities_const_regions_RegionID" ON "const_location_cities" ("RegionID");
ALTER TABLE "const_location_cities" ADD PRIMARY KEY ("CityID");

I am not sure what exactly broke in new version column "type" check constraint with enum, but it is broken (I am not exactly sure what mean:
ALTER TABLE "const_location_cities" ADD CONSTRAINT "const_location_cities"_type_chk CHECK (type IN (3));

**Comment by darold** [comment]
Commit f4615ed might fix these new issues as well as some others when the DDL is read from file.

**Comment by krasandr** [comment]
It is not fixed. If I use one file for all (table, indexes, constraints, foreign keys) result is (with preserve case):

CREATE TABLE "const_location_cities" (
        "CityID" bigserial,
        "StateID" integer NOT NULL,
        "type" text NOT NULL DEFAULT 'city',
        "bg_name" varchar(150) NOT NULL,
        "en_name" varchar(150) NOT NULL DEFAULT '',
        "RegionID" integer NOT NULL
) ;
ALTER SEQUENCE "const_location_cities_CityID_seq" RESTART WITH 4909;
ALTER TABLE "const_location_cities" ADD CONSTRAINT "const_location_cities"_type_chk CHECK (type IN (3));
CREATE INDEX "IX_const_location_cities_bg_name" ON "const_location_cities" ("bg_name");
CREATE INDEX "FK_const_location_cities_const_location_states_StateID" ON "const_location_cities" ("StateID");
CREATE INDEX "FK_const_location_cities_const_regions_RegionID" ON "const_location_cities" ("RegionID");
ALTER TABLE "const_location_cities" ADD PRIMARY KEY ("CityID");

Without preserve case, the same result:

CREATE TABLE const_location_cities (
        cityid bigserial,
        stateid integer NOT NULL,
        type text NOT NULL DEFAULT 'city',
        bg_name varchar(150) NOT NULL,
        en_name varchar(150) NOT NULL DEFAULT '',
        regionid integer NOT NULL
) ;
ALTER SEQUENCE const_location_cities_cityid_seq RESTART WITH 4909;
ALTER TABLE const_location_cities ADD CONSTRAINT const_location_cities_type_chk CHECK (type IN (3));
CREATE INDEX ix_const_location_cities_bg_name ON const_location_cities (bg_name);
CREATE INDEX fk_const_location_cities_const_location_states_stateid ON const_location_cities (stateid);
CREATE INDEX fk_const_location_cities_const_regions_regionid ON const_location_cities (regionid);
ALTER TABLE const_location_cities ADD PRIMARY KEY (cityid);

If I use separate files for tables, indexes, constraints, foreign keys (withous preserve case, so it is not important for result), result is the same (i.e. bug is not fixed):

from indexes file:
CREATE INDEX ix_const_location_cities_bg_name ON const_location_cities (bg_name);
CREATE INDEX fk_const_location_cities_const_location_states_stateid ON const_location_cities (stateid);
CREATE INDEX fk_const_location_cities_const_regions_regionid ON const_location_cities (regionid);

from fkeys file:
ALTER TABLE const_location_cities ADD CONSTRAINT fk_const_location_cities_const_location_states_stateid FOREIGN KEY (stateid) REFERENCES const_location_states(stateid) MATCH SIMPLE ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE const_location_cities ADD CONSTRAINT fk_const_location_cities_const_regions_regionid FOREIGN KEY (regionid) REFERENCES const_regions(regionid) MATCH SIMPLE ON DELETE RESTRICT ON UPDATE RESTRICT;

from constraints file:
ALTER TABLE const_location_cities ADD PRIMARY KEY (cityid);

and from main table file (check constraints is here, cmd is ora2pg -d -m -t TABLE -o table.sql):
CREATE TABLE const_location_cities (
        cityid bigserial,
        stateid integer NOT NULL,
        type text NOT NULL DEFAULT 'city',
        bg_name varchar(150) NOT NULL,
        en_name varchar(150) NOT NULL DEFAULT '',
        regionid integer NOT NULL
) ;
ALTER SEQUENCE const_location_cities_cityid_seq RESTART WITH 4909;
ALTER TABLE const_location_cities ADD CONSTRAINT const_location_cities_type_chk CHECK (type IN (3));

In MySQL, DDL is (if I run describe show_location_cities in mysql client):
+----------+-------------------------------------------------------+------+-----+---------+----------------+
| Field    | Type                                                  | Null | Key | Default | Extra          |
+----------+-------------------------------------------------------+------+-----+---------+----------------+
| CityID   | bigint(20) unsigned                                   | NO   | PRI | NULL    | auto_increment |
| StateID  | int(10) unsigned                                      | NO   | MUL | NULL    |                |
| type     | enum('city','town','resort','village','villa','area') | NO   |     | city    |                |
| bg_name  | varchar(50)                                           | NO   | MUL | NULL    |                |
| en_name  | varchar(50)                                           | NO   |     |         |                |
| RegionID | int(10) unsigned                                      | NO   | MUL | NULL    |                |
+----------+-------------------------------------------------------+------+-----+---------+----------------+
6 rows in set (0.00 sec)
and from another GUI client (dbvizualizer):
CREATE TABLE
    const_location_cities
    (
        CityID bigint unsigned NOT NULL AUTO_INCREMENT,
        StateID INT(10) unsigned NOT NULL,
        type enum('city','town','resort','village','villa','area') COLLATE utf8_unicode_ci DEFAULT
        'city' NOT NULL,
        bg_name VARCHAR(50) NOT NULL,
        en_name VARCHAR(50) NOT NULL,
        RegionID INT(10) unsigned NOT NULL,
        PRIMARY KEY (CityID),
        CONSTRAINT FK_const_location_cities_const_location_states_StateID FOREIGN KEY (StateID)
        REFERENCES `const_location_states` (`StateID`) ,
        CONSTRAINT FK_const_location_cities_const_regions_RegionID FOREIGN KEY (RegionID)
        REFERENCES `const_regions` (`RegionID`),
        INDEX IX_const_location_cities_bg_name (bg_name),
        INDEX FK_const_location_cities_const_location_states_StateID (StateID),
        INDEX FK_const_location_cities_const_regions_RegionID (RegionID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;

Also, I read from commit message, that you describe, that it fixes reading DDL from file, but this is not the case - I use every time live MariaDB 10.2. connection, so DDL is not from file (only PostreSQL result is put on file).

Also, thank you for ordering of columns in table - before converted table order (in PostgreSQL) was very strange, so it is not the same as order of column in MySQL, but now order mapping is one to one.

**Comment by darold** [comment]
Yes only file input have been fixed, I do not have time yesterday night to work on database export but I will fix it today.

**Comment by darold** [comment]
Done, last two commits 735c300 and c7fa9bc might solve enum data type export from MySQL database.

**Comment by krasandr** [comment]
It works:

CREATE TABLE const_location_cities (
        cityid bigserial,
        stateid integer NOT NULL,
        type varchar NOT NULL DEFAULT 'city',
        bg_name varchar(150) NOT NULL,
        en_name varchar(150) NOT NULL DEFAULT '',
        regionid integer NOT NULL
) ;
ALTER SEQUENCE const_location_cities_cityid_seq RESTART WITH 4909;
ALTER TABLE const_location_cities ADD CONSTRAINT const_location_cities_type_chk CHECK (type IN ('city','town','resort','village','villa','area'));

I will make some additional checks and after while, when finished them, will close bug.
Thank you for all closed bugs it this topic - with primary keys sequences, with default current_timestamp, with column orderering after conversion and with check constraints with enum.

**Comment by krasandr** [comment]
All tests pass, everything is O.K., thank you.

**Comment by darold** [comment]
I have not really tested the MySQL export so it will be a great help to report all issues you will found, and I think there is lot :-) But it is better to open a new issue for each problem for better understanding so I'm closing this one.
