### ISSUE TITLE
possibility to disable autonomous transaction translation

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#578]
In our application the autonomous transactions are used to take fresh data of other committed applications. This is not necessary in Postgres - so the transformation is useless. Is possible to disable this transformation and just comment the PRAGMA?

**Comment by darold** [comment]
Commit 1d9670a adds a new configuration directive called AUTONOMOUS_TRANSACTION to control this behavior. Enabled by default, set it to 0 to not translate function with the autonomous pragma.

**Comment by okbob** [comment]
It is working, thank you
