### ISSUE TITLE
Direct Migration to Postgres DB - without getting Script Output files

### ISSUE THREAD

**Issue by karurmohan** [darold/ora2pg#579]
Hi Darold,
                I want to migrate an Oracle Schema Directly into PostgreSQL Schema, where i had already created the source schema name in Target Postgres. The directives i used are 1) PG_DSN 2)PG_USER 3)PG_PWD. Firstly i am trying to migrate tables. But, i am unable to see the created tables in target Postgres. Rather, i could see the scripts in command prompt where i run the ORA2PG.PL Program (in windows). Can u please guide me what else needs to be changed to migrate oracle schema directly into postgres.

**Comment by darold** [comment]
Hi,

DDL can not be imported directly into PostgreSQL, you need to export them to file and then load them into you PostgreSQL database using psql. PG_DSN is only used with COPY and TEST action, I mean with data export and migration check.

Regards,

**Comment by karurmohan** [comment]
Thank you
