### ISSUE TITLE
REGEXP_SUBSTR converted wrongly

### ISSUE THREAD

**Issue by bhoot929** [darold/ora2pg#580]
Original Query:

				SELECT
				TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD') - (TO_NUMBER(TO_CHAR(TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD'),'DD')) - 1) AS Snapshot_Day
				,ASIN
				,Order_ID
				,TRIM(Distributor_ID) AS Distributor_ID
				,CASE WHEN REGEXP_SUBSTR(Shipment_ID,'[0-9]{13}') IS NOT NULL THEN REGEXP_SUBSTR(Shipment_ID,'[0-9]{13}')
					WHEN REGEXP_SUBSTR(Shipment_ID,'[0-9]{12}') IS NOT NULL THEN REGEXP_SUBSTR(Shipment_ID,'[0-9]{12}')
					WHEN REGEXP_SUBSTR(Shipment_ID,'[0-9]{11}') IS NOT NULL THEN REGEXP_SUBSTR(Shipment_ID,'[0-9]{11}')
					WHEN REGEXP_SUBSTR(Shipment_ID,'[0-9]{10}') IS NOT NULL THEN REGEXP_SUBSTR(Shipment_ID,'[0-9]{10}')
					WHEN REGEXP_SUBSTR(Shipment_ID,'[0-9]{9}') IS NOT NULL THEN REGEXP_SUBSTR(Shipment_ID,'[0-9]{9}')
					WHEN REGEXP_SUBSTR(Shipment_ID,'[0-9]{8}') IS NOT NULL THEN REGEXP_SUBSTR(Shipment_ID,'[0-9]{8}')
					ELSE REGEXP_SUBSTR(Shipment_ID,'[0-9]{7}') END AS Shipment_ID				
				,CASE WHEN Warehouse_ID1 = Warehouse_ID2 THEN Warehouse_ID1 ELSE Warehouse_ID1 || ',' || Warehouse_ID2 END AS Warehouse_ID
				,Received_Date1
				,Received_Date2
				,Invoice_matched_Quantity
				,ROUND(Cost_FC,2) AS Cost_FC
				,Foreign_Currency_Code
				,CASE WHEN vendor_Invoice_Number1 = vendor_Invoice_Number2 THEN vendor_Invoice_Number1 ELSE vendor_Invoice_Number1 || ',' || vendor_Invoice_Number2 END AS vendor_Invoice_Number
				,Invoices
				,primary_Vendor_code
				FROM
				(
					SELECT /*+ USE_HASH(dmii, ddii9, ddi9) */
					ddii9.ASIN 
					,MIN(ddii9.Foreign_Currency_Code) AS Foreign_Currency_Code
					,dmii.Distributor_Order_ID AS Order_ID
					,MIN(dmii.Distributor_ID) AS Distributor_ID
					,AVG(ddii9.Invoice_cost_FC) AS Cost_FC
					,MIN(dmii.Received_Datetime) AS Received_Date1
					,MAX(dmii.Received_Datetime) AS Received_Date2
					,SUM(dmii.Invoice_matched_Quantity) AS Invoice_matched_Quantity
					,MIN(dmii.Warehouse_ID) AS Warehouse_ID1
					,MAX(dmii.Warehouse_ID) AS Warehouse_ID2
					,MIN(dmii.Distributor_Shipment_ID) AS Shipment_ID
					,COUNT(Distinct ddi9.Invoice_ID) AS Invoices
					,MIN(ddi9.vendor_invoice_Number) AS vendor_Invoice_Number1	
					,MAX(ddi9.vendor_invoice_Number) AS vendor_Invoice_Number2	
					,MIN(ddi9.Primary_Vendor_Code) AS Primary_Vendor_Code
					FROM
					D_Dist_Invoice_Items ddii9
					,D_Distributor_Invoices ddi9
					,D_matched_Invoice_Items dmii
					WHERE
					ddii9.Invoice_ID = ddi9.Invoice_ID
					AND ddii9.Invoice_ID = dmii.Invoice_ID
					AND ddii9.Invoice_item_ID = dmii.Invoice_item_ID
					AND ddi9.Invoice_ID = dmii.Invoice_ID
					AND ddi9.Region_ID = Decode({LEGAL_ENTITY_ID},101,1,102,2,103,2,108,2,109,3,115,1,128,3,129,2,130,2,131,4)
					AND ddi9.Legal_entity_ID = {LEGAL_ENTITY_ID}
					AND ddii9.Region_ID = Decode({LEGAL_ENTITY_ID},101,1,102,2,103,2,108,2,109,3,115,1,128,3,129,2,130,2,131,4)
					AND ddii9.Legal_entity_ID = {LEGAL_ENTITY_ID}
					AND dmii.Region_ID = Decode({LEGAL_ENTITY_ID},101,1,102,2,103,2,108,2,109,3,115,1,128,3,129,2,130,2,131,4)
					AND dmii.Legal_entity_ID = {LEGAL_ENTITY_ID}
					AND ddi9.Invoice_day BETWEEN (TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')- 270) AND TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')
					AND ddii9.Invoice_day BETWEEN (TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')- 270) AND TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')
					AND dmii.Matched_Day BETWEEN (TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')- 270) AND TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')
					AND dmii.Invoice_Day BETWEEN (TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')- 270) AND TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')
					AND dmii.Received_Datetime BETWEEN (TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')- 270) AND TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')
					AND ddi9.Invoice_Source_name Like 'REPT-CLEAR-TOOL'
					AND ddi9.Invoice_Status NOT Like '5'
					AND ddii9.Invoice_item_status Not Like '5'
					GROUP BY
					ddii9.ASIN 
					,dmii.Distributor_Order_ID 
				)	

Converted query:
SELECT
				TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD') - ((TO_CHAR(TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD'),'DD'))::numeric  - 1) AS Snapshot_Day
				,ASIN
				,Order_ID
				,btrim(Distributor_ID) AS Distributor_ID
				,CASE WHEN (SELECT array_to_string(a, '') FROM regexp_matches(hipment_ID, '[0-9]{13}', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1)) IS NOT NULL THEN (SELECT array_to_string(a, '') FROM regexp_matches(hipment_ID, '[0-9]{13}', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1))
					WHEN (SELECT array_to_string(a, '') FROM regexp_matches(hipment_ID, '[0-9]{12}', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1)) IS NOT NULL THEN (SELECT array_to_string(a, '') FROM regexp_matches(hipment_ID, '[0-9]{12}', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1))
					WHEN (SELECT array_to_string(a, '') FROM regexp_matches(hipment_ID, '[0-9]{11}', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1)) IS NOT NULL THEN (SELECT array_to_string(a, '') FROM regexp_matches(hipment_ID, '[0-9]{11}', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1))
					WHEN (SELECT array_to_string(a, '') FROM regexp_matches(hipment_ID, '[0-9]{10}', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1)) IS NOT NULL THEN (SELECT array_to_string(a, '') FROM regexp_matches(hipment_ID, '[0-9]{10}', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1))
					WHEN (SELECT array_to_string(a, '') FROM regexp_matches(hipment_ID, '[0-9]{9}', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1)) IS NOT NULL THEN (SELECT array_to_string(a, '') FROM regexp_matches(hipment_ID, '[0-9]{9}', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1))
					WHEN (SELECT array_to_string(a, '') FROM regexp_matches(hipment_ID, '[0-9]{8}', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1)) IS NOT NULL THEN (SELECT array_to_string(a, '') FROM regexp_matches(hipment_ID, '[0-9]{8}', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1))
					ELSE (SELECT array_to_string(a, '') FROM regexp_matches(hipment_ID, '[0-9]{7}', 'g') AS foo(a) LIMIT 1 OFFSET (1 - 1)) END AS Shipment_ID				
				,CASE WHEN Warehouse_ID1 = Warehouse_ID2 THEN Warehouse_ID1 ELSE Warehouse_ID1 || ',' || Warehouse_ID2 END AS Warehouse_ID
				,Received_Date1
				,Received_Date2
				,Invoice_matched_Quantity
				,round((Cost_FC)::numeric,2) AS Cost_FC
				,Foreign_Currency_Code
				,CASE WHEN vendor_Invoice_Number1 = vendor_Invoice_Number2 THEN vendor_Invoice_Number1 ELSE vendor_Invoice_Number1 || ',' || vendor_Invoice_Number2 END AS vendor_Invoice_Number
				,Invoices
				,primary_Vendor_code
				FROM (
					SELECT
					ddii9.ASIN 
					,MIN(ddii9.Foreign_Currency_Code) AS Foreign_Currency_Code
					,dmii.Distributor_Order_ID AS Order_ID
					,MIN(dmii.Distributor_ID) AS Distributor_ID
					,AVG(ddii9.Invoice_cost_FC) AS Cost_FC
					,MIN(dmii.Received_Datetime) AS Received_Date1
					,MAX(dmii.Received_Datetime) AS Received_Date2
					,SUM(dmii.Invoice_matched_Quantity) AS Invoice_matched_Quantity
					,MIN(dmii.Warehouse_ID) AS Warehouse_ID1
					,MAX(dmii.Warehouse_ID) AS Warehouse_ID2
					,MIN(dmii.Distributor_Shipment_ID) AS Shipment_ID
					,COUNT(Distinct ddi9.Invoice_ID) AS Invoices
					,MIN(ddi9.vendor_invoice_Number) AS vendor_Invoice_Number1	
					,MAX(ddi9.vendor_invoice_Number) AS vendor_Invoice_Number2	
					,MIN(ddi9.Primary_Vendor_Code) AS Primary_Vendor_Code
					FROM
					D_Dist_Invoice_Items ddii9
					,D_Distributor_Invoices ddi9
					,D_matched_Invoice_Items dmii
					WHERE
					ddii9.Invoice_ID = ddi9.Invoice_ID
					AND ddii9.Invoice_ID = dmii.Invoice_ID
					AND ddii9.Invoice_item_ID = dmii.Invoice_item_ID
					AND ddi9.Invoice_ID = dmii.Invoice_ID
					AND ddi9.Region_ID = CASE WHEN {LEGAL_ENTITY_ID}=101 THEN 1 WHEN {LEGAL_ENTITY_ID}=102 THEN 2 WHEN {LEGAL_ENTITY_ID}=103 THEN 2 WHEN {LEGAL_ENTITY_ID}=108 THEN 2 WHEN {LEGAL_ENTITY_ID}=109 THEN 3 WHEN {LEGAL_ENTITY_ID}=115 THEN 1 WHEN {LEGAL_ENTITY_ID}=128 THEN 3 WHEN {LEGAL_ENTITY_ID}=129 THEN 2 WHEN {LEGAL_ENTITY_ID}=130 THEN 2 WHEN {LEGAL_ENTITY_ID}=131 THEN 4 END 
					AND ddi9.Legal_entity_ID = {LEGAL_ENTITY_ID}
					AND ddii9.Region_ID = CASE WHEN {LEGAL_ENTITY_ID}=101 THEN 1 WHEN {LEGAL_ENTITY_ID}=102 THEN 2 WHEN {LEGAL_ENTITY_ID}=103 THEN 2 WHEN {LEGAL_ENTITY_ID}=108 THEN 2 WHEN {LEGAL_ENTITY_ID}=109 THEN 3 WHEN {LEGAL_ENTITY_ID}=115 THEN 1 WHEN {LEGAL_ENTITY_ID}=128 THEN 3 WHEN {LEGAL_ENTITY_ID}=129 THEN 2 WHEN {LEGAL_ENTITY_ID}=130 THEN 2 WHEN {LEGAL_ENTITY_ID}=131 THEN 4 END 
					AND ddii9.Legal_entity_ID = {LEGAL_ENTITY_ID}
					AND dmii.Region_ID = CASE WHEN {LEGAL_ENTITY_ID}=101 THEN 1 WHEN {LEGAL_ENTITY_ID}=102 THEN 2 WHEN {LEGAL_ENTITY_ID}=103 THEN 2 WHEN {LEGAL_ENTITY_ID}=108 THEN 2 WHEN {LEGAL_ENTITY_ID}=109 THEN 3 WHEN {LEGAL_ENTITY_ID}=115 THEN 1 WHEN {LEGAL_ENTITY_ID}=128 THEN 3 WHEN {LEGAL_ENTITY_ID}=129 THEN 2 WHEN {LEGAL_ENTITY_ID}=130 THEN 2 WHEN {LEGAL_ENTITY_ID}=131 THEN 4 END 
					AND dmii.Legal_entity_ID = {LEGAL_ENTITY_ID}
					AND ddi9.Invoice_day BETWEEN(TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')- 270) AND TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')
					AND ddii9.Invoice_day BETWEEN(TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')- 270) AND TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')
					AND dmii.Matched_Day BETWEEN(TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')- 270) AND TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')
					AND dmii.Invoice_Day BETWEEN(TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')- 270) AND TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')
					AND dmii.Received_Datetime BETWEEN(TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')- 270) AND TO_DATE('{RUN_DATE_YYYY/MM/DD}', 'YYYY/MM/DD')
					AND ddi9.Invoice_Source_name Like 'REPT-CLEAR-TOOL'
					AND ddi9.Invoice_Status NOT Like '5'
					AND ddii9.Invoice_item_status Not Like '5'
					GROUP BY
					ddii9.ASIN 
					,dmii.Distributor_Order_ID 
				) alias101	;

here you can see that REGEXP_SUBSTR is converted to regexp_matches . 
In redshift regexp_matches is not available. 

Can you please help me to disable regexp_substr convertion ?

Thanks,
Swapnil

**Comment by darold** [comment]
Ora2Pg is developed on my spare time to migrate Oracle database to PostgreSQL. I do not have enough time to fix and develop Ora2Pg on all features I want, so don't expect me to do anything specific for a commercial service like AWS for free. If someone want to pay me to work on a RedShift adaptation it is welcome.

Additionally I saw in your report there was a bug in the REGEXP_SUBSTR, it is now fixes with commit b3eeaa

**Comment by bhoot929** [comment]
Hi Darold,

I would request you to help me with disabling regexp_substr conversion using some parameter   if you get free time .

Just to inform you that earlier ora2pg was not converting regexp_substr but now with some commit it started converting to different syntax.

Can you please help

**Comment by darold** [comment]
Commit 75907b4 adds this translation, if you want you can disable the translation by commenting line 1339 of file `lib/Ora2Pg/PLSQL.pm` like this:
```
        # REGEX_SUBSTR( string, pattern, pos, num ) translation
        #$str =~ s/REGEXP_SUBSTR\s*\(\s*([^\)]+)\s*\)/convert_regex_substr($class, $1)/iegs;
```
