### ISSUE TITLE
Mixed geometry in one table - export error

### ISSUE THREAD

**Issue by Bulva** [darold/ora2pg#581]
Hi Darold,

we have a table with mixed geometry. There are about 90 % of LINESTRING geometries like:
`MDSYS.SDO_GEOMETRY(2002,NULL,MDSYS.SDO_POINT_TYPE(0,0,0),MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(3456315.438,5487858.31,3456315.746,5487858.139))`

But in the same table are compound geometries like:
`MDSYS.SDO_GEOMETRY(2002,NULL,MDSYS.SDO_POINT_TYPE(0,0,0),MDSYS.SDO_ELEM_INFO_ARRAY(1,4,6,1,2,1,5,2,1,7,2,1,9,2,1,11,2,1,13,2,1),MDSYS.SDO_ORDINATE_ARRAY(3451820.87,5482324.21,3451813.5,5482321.3,3451815.09,5482317.15,3451826.14,5482321.4,3451828.15,5482322.18,3451826.54,5482326.38,3451820.87,5482324.21))`

During the export ora2pg shows this error (probably only for compound geometries):
`ERROR: SDO_ETYPE 4 inconsistent with expected LINESTRING`

When export finished there is a same number of rows so compound geometries were exported, but for the compound geometries exported rows look something like that:
`ST_GeomFromText('COMPOUNDCURVE (LINESTRING (3451820.87 5482324.21, 3451813.5 5482321.3, 3451815.09 5482317.15), LINESTRING (3451815.09 5482317.15, 3451826.14 5482321.4), LINESTRING (3451826.14 5482321.4, 3451828.15 5482322.18), LINESTRING (3451828.15 5482322.18, 3451826.54 5482326.38), LINESTRING (3451826.54 5482326.38, 3451820.87 5482324.21), LINESTRING (3451820.87 5482324.21))', 5514)`

which results in:
```
ERROR:  geometry requires more points
RECOMMENDATION:  "..., 
LINESTRING (3451820.87 5482324.21))" <-- parse error at position 364 within geometry
```

So, in this time I don't know if exporting compound types work as expected and if yes, why I got this error after the export of compound types.

**Comment by darold** [comment]
Hi,

There is still bugs on compound geometries export but some have already been fixed. Are you using latest development code? If this is not the case please give it a try and let me know if the problem persist.

**Comment by Bulva** [comment]
I tried development code from yesterday because I saw some commits related to compound types. So, unfortunately, this error still persists.

Do you want to send some test data?
Thanks for reply

**Comment by Bulva** [comment]
Here are some [test data](https://gist.github.com/Bulva/46ba51655eed4abe77f89c4c8bccb785). There is a compound geometry of different types. 

Thanks a lot for your time

**Comment by darold** [comment]
Commit 364caf7 fixes export of MULTICURVE+COMPOUNDCURVE. In your example the error was generated by export of gid '1716008367677831645770760' as
```
INSERT INTO w__group_gr (gid,sdo_geom) VALUES (1716008367677831645770760,ST_GeomFromText('MULTICURVE ()', 4326));
```
and after fixing it:
```
INSERT INTO w__group_gr (gid,sdo_geom) VALUES 
(1716008367677831645770760,ST_GeomFromText('MULTICURVE (COMPOUNDCURVE
(LINESTRING (3451238.482 5482131.265, 3451236.465 5482130.899, 3451238.096 5482121.055),
LINESTRING (3451238.096 5482121.055)), LINESTRING (3451238.482 5482131.265, 3451236.465
5482130.899, 3451238.096 5482121.055), LINESTRING (3451238.096 5482121.055))', 4326));
```
There is a limit of my reverse engineering work as it still generate an error when import into to PostgreSQL.
```
psql:tmp/W__GROUP_GR_output.sql:12: ERROR:  geometry requires more points
HINT:  "...LINESTRING (3451238.096 5482121.055))" <-- parse error at position 152 within geometry
```
I do not understand because when I export the data from Oracle in WKT format I have the same output:
```
To WKT geometry result = MULTICURVE (COMPOUNDCURVE (LINESTRING (3451238.482
5482131.265, 3451236.465 5482130.899, 3451238.096 5482121.055), LINESTRING (3451238.096
5482121.055)), (3451238.482 5482131.265, 3451236.465 5482130.899), (3451238.096 5482121.055))
WKT validation result = TRUE
```
It seems that PostGis have some WKT differences. If you know what the export should be, please let me know.

I will investigate other issues.

**Comment by darold** [comment]
Found an other bug on exporting gid `268485367662267663798181765600` of your sample where the object was exported as a MULTILINESTRING instead of a MULTICURVE.  Commit 735c300 fix it by replacing MULTILINESTRING with MULTICURVE when a CIRCULARSTRING is found in the geometry. I'm not sure this is the right thing to do but it works.

**Comment by darold** [comment]
In your example, gid 1161093412452500914058248 also reports error:
```
psql:tmp/W__GROUP_GR_output.sql:12: ERROR:  geometry requires more points
HINT:  "...LINESTRING (3451251.803 5482123.491))" <-- parse error at position 264 within geometry
```
The WKT Oracle export return the same value as Ora2PG:
```
To WKT geometry result = COMPOUNDCURVE (LINESTRING (3451288.434 5482130.116,
3451285.728 5482129.732, 3451277.582 5482128.225), LINESTRING (3451277.582
5482128.225, 3451256.65 5482124.394), LINESTRING (3451256.65 5482124.394,
3451251.803 5482123.491), LINESTRING (3451251.803 5482123.491))
WKT validation result = TRUE
```
Ora2Pg:
```
INSERT INTO w__group_gr (gid,sdo_geom) VALUES (1161093412452500914058248,ST_GeomFromText('COMPOUNDCURVE (
LINESTRING (3451288.434 5482130.116, 3451285.728 5482129.732, 3451277.582 5482128.225),
LINESTRING (3451277.582 5482128.225, 3451256.65 5482124.394),
LINESTRING (3451256.65 5482124.394, 3451251.803 5482123.491),
LINESTRING (3451251.803 5482123.491))', 4326));
```

I don't know what to do to have a valid PostGis geometry but I think there is two solutions:

1) Remove last LINESTRING which is only composed of the last coordinates of the previous LINESTRING.
2) Add the first coordinates of the first LINESTRING to close the geometry.

I'm potentially totally wrong on the solution to use, any advice is welcome.

**Comment by Bulva** [comment]
Hi Darold,

we've investigated the geometries and the fact is the geometry is wrong, it is valid from Oracle WKT point of view, but Postgres forbid to insert LINESTRING with only one point, which is right. I'm not sure if Postgis is somehow able to disable these checks and import invalid data and repair the problem later – you know about such solution?

So it is problem of the data source itself and not the migration. The right thing is to do nothing, these data should be cleaned before migration.

We'll check the new build with your commits and let you know about the results.

Thanks again for your time in this.
