### ISSUE TITLE
Explicit type casts for string functions when converting from MySQL

### ISSUE THREAD

**Issue by krasandr** [darold/ora2pg#582]
I am not sure for right solution, so this is only proposal.

Is this possible, when converting with ora2pg from MySQL, for string functions to make explicit casting when needed (MySQL accept for example in functions LPAD, RPAD, LEFT, RIGHT and so on, integer type of columns and converts it automaticly, but PostgreSQL don't convert types automaticly).
For example:

CREATE OR REPLACE VIEW v_const_regions AS select grad.RegionID AS RegionID,lpad(oblast.RegionNumber,2,'0') AS RZOKCastNum,lpad(grad.RegionNumber,2,'0') AS AreaCastNum,concat_ws(' ',lpad(oblast.RegionNumber,2,'0'),lpad(grad.RegionNumber,2,'0')) AS CastNumber,oblast.RegionNumber AS RZOKNumber,grad.RegionNumber AS AreaNumber,oblast.RegionName AS RZOKName,grad.RegionName AS AreaName FROM (const_regions oblast join const_regions grad on (grad.RegionParentID = oblast.RegionID));

In this example, arguments for LPAD are integers, so error is:

11:51:31  FAILED  [CREATE - 0 rows, 0.040 secs]  [Code: , SQL State: 42883]  ERROR: function lpad(integer, integer, unknown) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 76  
12:05:59  FAILED  [CREATE - 0 rows, 0.014 secs]  [Code: , SQL State: 42883]  ERROR: function lpad(integer, integer, unknown) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 375  

After explicit casting (depend on type of first argument of LPAD function, casting is not needed if it is CHAR, VARCHAR and so on), VIEW are created succefully:

CREATE OR REPLACE VIEW v_const_regions AS select grad.RegionID AS RegionID,lpad(oblast.RegionNumber::CHAR,2,'0') AS RZOKCastNum,lpad(grad.RegionNumber::CHAR,2,'0') AS AreaCastNum,concat_ws(' ',lpad(oblast.RegionNumber::CHAR,2,'0'),lpad(grad.RegionNumber::CHAR,2,'0')) AS CastNumber,oblast.RegionNumber AS RZOKNumber,grad.RegionNumber AS AreaNumber,oblast.RegionName AS RZOKName,grad.RegionName AS AreaName FROM (const_regions oblast join const_regions grad on (grad.RegionParentID = oblast.RegionID));

Another example:

CREATE OR REPLACE VIEW v_scells AS select s.IvfSCellID AS IvfSCellID,s.IvfSReadyDate AS IvfSReadyDate,s.IvfArtID AS IvfArtID,s.IsHusband AS IsHusband,s.IvfSCellNum AS IvfSCellNum,s.IsScrab AS IsScrab,s.PatientRecID AS CellPatientRecID,l.IvfSLotID AS IvfSLotID,l.IvfSCountryCode AS IvfSCountryCode,l.IvfSHospitalCode AS IvfSHospitalCode,l.IvfSLotUIN AS IvfSLotUIN,concat('M',lpad(l.IvfSLotUIN,4,'0')) AS DonationNumberFormatted,l.IvfSTakenYear AS IvfSTakenYear,l.TotalLotCells AS TotalLotCells,concat('.',lpad(s.IvfSCellNum,2,'0'),'-',lpad(l.TotalLotCells,2,'0')) AS LotNumber,l.IvfSLotNote AS IvfSLotNote,l.IsCarantine AS IsCarantine,l.HospitalInfoID AS HospitalInfoID,d.DonorID AS DonorID,d.PatientID AS PatientID,d.DonorUIN AS DonorUIN,d.RaceID AS RaceID,d.CountryID AS CountryID,d.EyeID AS EyeID,d.HairID AS HairID,d.BloodID AS BloodID,d.DonorHeight AS DonorHeight,d.DonorWeight AS DonorWeight,d.DonorProfession AS DonorProfession,d.IsEnabled AS IsEnabled,d.DonorNote AS DonorNote,c.IvfSCellID AS CryoIvfSCellID,c.IvfFrozenDate AS IvfFrozenDate,c.IvfFrozenToDate AS IvfFrozenToDate,c.IvfSCryoSRate AS IvfSCryoSRate,c.IvfCryoCanisterID AS IvfCryoCanisterID,c.PatientRecID AS CryoPatientRecID,s.ReceiveSECode AS ReceiveSECode,s.SentSECode AS SentSECode,CASE WHEN s.IvfSReadyDate is null THEN 1 ELSE 0 END  AS StrawsAvailable,concat_ws('-',l.IvfSCountryCode,l.IvfSHospitalCode,right(l.IvfSTakenYear,2),concat('M',lpad(l.IvfSLotUIN,4,'0'))) AS ConcatUIN,concat(lpad(s.IvfSCellNum,2,'0'),'-',lpad(l.TotalLotCells,2,'0')) AS ConcatCellNum FROM (((ivf_s_cells s join ivf_s_lots l on (s.IvfSLotID = l.IvfSLotID)) join ivf_s_donors d on (l.DonorID = d.DonorID)) left join ivf_s_cryo c on (s.IvfSCellID = c.IvfSCellID));

12:07:46  FAILED  [CREATE - 0 rows, 0.012 secs]  [Code: , SQL State: 42883]  ERROR: function right(smallint, integer) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 1396

After manually casting to CHAR where neded, again VIEW are created sucefully:

CREATE OR REPLACE VIEW v_scells AS select s.IvfSCellID AS IvfSCellID,s.IvfSReadyDate AS IvfSReadyDate,s.IvfArtID AS IvfArtID,s.IsHusband AS IsHusband,s.IvfSCellNum AS IvfSCellNum,s.IsScrab AS IsScrab,s.PatientRecID AS CellPatientRecID,l.IvfSLotID AS IvfSLotID,l.IvfSCountryCode AS IvfSCountryCode,l.IvfSHospitalCode AS IvfSHospitalCode,l.IvfSLotUIN AS IvfSLotUIN,concat('M',lpad(l.IvfSLotUIN::CHAR,4,'0')) AS DonationNumberFormatted,l.IvfSTakenYear AS IvfSTakenYear,l.TotalLotCells AS TotalLotCells,concat('.',lpad(s.IvfSCellNum::CHAR,2,'0'),'-',lpad(l.TotalLotCells::CHAR,2,'0')) AS LotNumber,l.IvfSLotNote AS IvfSLotNote,l.IsCarantine AS IsCarantine,l.HospitalInfoID AS HospitalInfoID,d.DonorID AS DonorID,d.PatientID AS PatientID,d.DonorUIN AS DonorUIN,d.RaceID AS RaceID,d.CountryID AS CountryID,d.EyeID AS EyeID,d.HairID AS HairID,d.BloodID AS BloodID,d.DonorHeight AS DonorHeight,d.DonorWeight AS DonorWeight,d.DonorProfession AS DonorProfession,d.IsEnabled AS IsEnabled,d.DonorNote AS DonorNote,c.IvfSCellID AS CryoIvfSCellID,c.IvfFrozenDate AS IvfFrozenDate,c.IvfFrozenToDate AS IvfFrozenToDate,c.IvfSCryoSRate AS IvfSCryoSRate,c.IvfCryoCanisterID AS IvfCryoCanisterID,c.PatientRecID AS CryoPatientRecID,s.ReceiveSECode AS ReceiveSECode,s.SentSECode AS SentSECode,CASE WHEN s.IvfSReadyDate is null THEN 1 ELSE 0 END  AS StrawsAvailable,concat_ws('-',l.IvfSCountryCode,l.IvfSHospitalCode,right(l.IvfSTakenYear::CHAR,2),concat('M',lpad(l.IvfSLotUIN::CHAR,4,'0'))) AS ConcatUIN,concat(lpad(s.IvfSCellNum::CHAR,2,'0'),'-',lpad(l.TotalLotCells::CHAR,2,'0')) AS ConcatCellNum FROM (((ivf_s_cells s join ivf_s_lots l on (s.IvfSLotID = l.IvfSLotID)) join ivf_s_donors d on (l.DonorID = d.DonorID)) left join ivf_s_cryo c on (s.IvfSCellID = c.IvfSCellID));

My question is exactly, is this possible with ora2pg, if you know right context (from MySQL database connection or from database schema for column types), to add explicit type casting, when they are needed? It can be something like MySQL section at the bottom of ora2pg configuration file about MYSQL_PIPES_AS_CONCAT and MYSQL_INTERNAL_EXTRACT_FORMAT, because it is realated to export behavior too.

This is only proposal, because I am not sure, in ora2pg source code, when convert VIEW or PL/PGSQL stored procedure function, do you have access to right data type of columns, to be able to make decisions about is it needed explicit type casting or not (depend on configuration value, maybe - I am not sure, if type casting is on by default and make casts to CHAR for all columns always, no matter is needed or not, how mach will be affected system resources).

I think, this solution is better than to make new UDF , overloading of string functions, for example LPAD(int,int,unknown), so the price of casting will be less than always to check prototype of overloaded UDF at execution time and choose of right function to execute.

**Comment by darold** [comment]
Unfortunately Ora2Pg doesn't keep in memory columns definition for VIEW export type and it not much check their context use. Here I think you have three choice:

1) grep all call to lpad/rpad and cast by hand or script all non character columns.
2) overload the lpad/rpad function to allow parameters of numeric type.
3) remove call to lpad/rpad and process to string formatting upper in your application

Regards,

**Comment by krasandr** [comment]
I was thinking about the above 3 choises, but I don't like them at all. The problem is more general that it seems - MySQL permits (wrong) mixing of types and automatic casts them as needed (again wrong) internaly, when PostreSQL makes (right) type checks and safely don't permit them, unless manually converted.
It is very sad, that ora2pg don't keep in memory columns definition (it is not related only to VIEW, because there is same problem with PL/PGSQL conversion of MySQL string functions). I don't know how much memory expensive it will be or, if there was some kind of dynamic recheck possibility on the fly (when needed, set by configuration option) how much resource expensive it will be. 
The last choice maybe it will be to make such casts every time (compromise), no matter they are needed or not, because it will be possible "live" migrations of MySQL to be much fast process, depend on how much MySQL uses string functions for everything, and finally, when there is working (but not optimal) PostgreSQL database, only to make fine tuning on it, i.e. replace bad solutions used before conversion with poor SQL dialect or restrictions, with all possibilities to compare and replace things with PostgreSQLs rich SQL dialect. I am not sure about performance impact of such explicit cast, but maybe it will be suitable for experimental section in ora2pg, if it is possible at all.

**Comment by darold** [comment]
There is the same problem with migration of Oracle database, it really takes lot of time to fix issue generated by these implicit cast. I would like to have Ora2Pg auto-detect and rewrite some of them but it need lot of time to develop this feature, time that unfortunately I don't have. Get back in few years maybe it will be done :-)

**Comment by krasandr** [comment]
Yes, I understand, it will be not possible to make this explicit conversion of arguments of string functions when needed, unless you have kept them in memory, to be able to find right context for column data types.
Thank you and sorry, it is very often and common to find such problems with every database conversion.
