### ISSUE TITLE
IN (...) nested in MySQL construction IF(a,b,c) is not converted right

### ISSUE THREAD

**Issue by krasandr** [darold/ora2pg#583]
Problem is related again to MySQL IF(a,b,c) construction - it can be used in stored procedures/functions in PL/PGSQL too, but there is problem, when there is nested IN (...) into IF.

For example, this MySQL function:
```
DELIMITER ;;
CREATE DEFINER=`root`@`%` FUNCTION `F_AmbGetVisitType`(pAmbDocumentID int(11)) RETURNS varchar(255) CHARSET utf8
BEGIN

  RETURN (SELECT
      IF(ad.VisitType IN (1, 3), 'Purvichen', 'Vtorichen')
    FROM amb_documents ad
    WHERE ad.AmbDocumentID = pAmbDocumentID
    LIMIT 1);

END ;;
```
Is converted to:
```
CREATE OR REPLACE FUNCTION f_ambgetvisittype (pAmbDocumentID integer(11)) RETURNS VARCHAR(255) AS $body$
BEGINBEGIN

  RETURN(SELECT (CASE WHEN ad.VisitType IN (1 THEN 3) ELSE 'Purvichen', 'Vtorichen' END)
    FROM amb_documents ad
    WHERE ad.AmbDocumentID = pAmbDocumentID
    LIMIT 1);

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
```
(word BEGINBEGIN is very often after conversion, I think that they are put in a beginning of empty blocks, without checks, that is reason why they appears twice).

Another MySQL stored function:
```
DELIMITER ;;
CREATE DEFINER=`root`@`%` FUNCTION `F_AmbGetVisitFor`(pAmbDocumentID INT(11)) RETURNS varchar(255) CHARSET utf8
BEGIN

  RETURN (SELECT
      IF(ad.VisitFor = 1, 'Konsultaciq',
      IF(ad.VisitFor IN (21, 22, 23), 'Profilaktika',
      IF(ad.VisitFor = 2, 'Dispanseren pregled',
      IF(ad.VisitFor IN (3, 4), 'VSD',
      IF(ad.VisitFor = 5, 'Recepta na hospitalizirano ZZOL',
      IF(ad.VisitFor = 6, 'Ekspertiza na rabotosposobnostta',
      IF(ad.VisitFor = 7, 'Po iskane na TELK', ''))))))) AS VisitFor
    FROM amb_documents ad
    WHERE ad.AmbDocumentID = pAmbDocumentID
    LIMIT 1);

END ;;
```
And converted to PostgreSQL, again with same problem:
```
CREATE OR REPLACE FUNCTION f_ambgetvisitfor (pAmbDocumentID integer(11)) RETURNS VARCHAR(255) AS $body$
BEGINBEGIN

  RETURN (SELECT
      (CASE WHEN ad.VisitFor = 1 THEN 'Konsultaciq' ELSE (CASE WHEN ad.VisitFor IN (21 THEN 22 ELSE 23 END END), 'Profilaktika',
      (CASE WHEN ad.VisitFor = 2 THEN 'Dispanseren pregled' ELSE (CASE WHEN ad.VisitFor IN (3 THEN 4 END) ELSE 'VSD',
      (CASE WHEN ad.VisitFor = 5 THEN 'Recepta na hospitalizirano ZZOL' ELSE IF (ad.VisitFor = 6, 'Ekspertiza na rabotosposobnostta',
      IF (ad.VisitFor = 7, 'Po iskane na TELK', '' END END))))))) AS VisitFor
    FROM amb_documents ad
    WHERE ad.AmbDocumentID = pAmbDocumentID
    LIMIT 1);

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
```
I think that problem is related to parenthesis checks (IN (...) also have parenthesis) and conversion around MySQL IF(a,b,c) construction - maybe fix that you made for VIEW and QUERY, must be extended to cover FUNCTION and PROCEDURE too.

**Comment by krasandr** [comment]
The second example did't work correctly without IN (...) also, probably problem is related to nested IF(a,b,c) constructions and converting them only in types VIEW and QUERY. I am not sure if extending IF(a,b,c) fix to cover FUNCTION and PROCEDURE also what will give as result, will try. The bigger question is how to distinguish this form of IF(a,b,c) that is MySQL specific from another IF ... THEN ... ELSE IF ... ELSE, that PostgreSQL supports in PL/PGSQL, so second construction must not be converted, only first form. I am not sure, is this problem is related to IN (...) (and it's parenthesis at all), depend on fact, that conversion did't work without IN (...) also.

**Comment by darold** [comment]
I think last commits 6c4fb20 and 5893cb1 will solve this kind of issues. Let me know if some case are not handled.

**Comment by krasandr** [comment]
You are right, last commits fixes bugs, only with one very small issue - there is blank formatting between every word CASE and ELSE (maybe TAB or some blank spaces).
Again, the same two stored functions from example, conversion of nested IN (...) and IF(a,b,c) is right
(also, twice word BEGINBEGIN is also fixed, thank you):

CREATE OR REPLACE FUNCTION f_ambgetvisittype (pAmbDocumentID integer(11)) RETURNS VARCHAR(255) AS $body$
BEGIN

  RETURN(SELECT
      CASE WHEN ad.VisitType  IN (1, 3) THEN  'Purvichen'  ELSE 'Vtorichen' END 
    FROM amb_documents ad
    WHERE ad.AmbDocumentID = pAmbDocumentID
    LIMIT 1);

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION f_ambgetvisittype (pAmbDocumentID integer(11)) FROM PUBLIC;

CREATE OR REPLACE FUNCTION f_ambgetvisitfor (pAmbDocumentID integer(11)) RETURNS VARCHAR(255) AS $body$
BEGIN

  RETURN(SELECT
      CASE WHEN ad.VisitFor = 1 THEN 'Konsultaciq' ELSE       CASE WHEN ad.VisitFor  IN (21, 22, 23) THEN  'Profilaktika'  ELSE CASE WHEN ad.VisitFor = 2 THEN 'Dispanseren pregled' ELSE       CASE WHEN ad.VisitFor  IN (3, 4) THEN  'VSD'  ELSE CASE WHEN ad.VisitFor = 5 THEN 'Recepta na hospitalizirano ZZOL' ELSE       CASE WHEN ad.VisitFor = 6 THEN 'Ekspertiza na rabotosposobnostta' ELSE       CASE WHEN ad.VisitFor = 7 THEN 'Po iskane na TELK' ELSE  '' END  END  END  END  END  END  END  AS VisitFor
    FROM amb_documents ad
    WHERE ad.AmbDocumentID = pAmbDocumentID
    LIMIT 1);

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION f_ambgetvisitfor (pAmbDocumentID integer(11)) FROM PUBLIC;

**Comment by darold** [comment]
Yes Ora2Pg does not apply any formatting to SQL or PLPGSQL code. If you want to format your function code, got to http://sqlformat.darold.net/ copy/past your code and click on "Format my code" button.

pgFormatter is also available at command line, see https://github.com/darold/pgFormatter/releases for download.

**Comment by krasandr** [comment]
There is still bug (wrong conversion of form IF ... THEN).

MySQL function before conversion:

DELIMITER ;;
CREATE DEFINER=`root`@`%` FUNCTION `F_OncoAppCount`(clinicProcID int, fromDate date, toDate date) RETURNS int(11)
BEGIN

  IF (fromDate IS NOT NULL)
    THEN
                                                                                          
    RETURN (SELECT
        COUNT(*) c
      FROM clinic_procedures_apps cpa
      WHERE cpa.clinicProcID = clinicProcID
      AND cpa.ReportDate BETWEEN DATE(fromDate) AND DATE(toDate));
  END IF;

  RETURN (SELECT
      COUNT(*)
    FROM clinic_procedures_apps cpa
    WHERE cpa.clinicProcID = clinicProcID);

END ;;

After conversion (see CASE END in beginning):

CREATE OR REPLACE FUNCTION f_oncoappcount (clinicProcID integer, fromDate date, toDate date) RETURNS integer AS $body$
BEGIN

  CASE END.
    THEN

    RETURN(SELECT
        COUNT(*) c
      FROM clinic_procedures_apps cpa
      WHERE cpa.clinicProcID = clinicProcID
      AND cpa.ReportDate BETWEEN DATE(fromDate) AND DATE(toDate));
  END IF;

  RETURN(SELECT
      COUNT(*)
    FROM clinic_procedures_apps cpa
    WHERE cpa.clinicProcID = clinicProcID);

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION f_oncoappcount (clinicProcID integer, fromDate date, toDate date) FROM PUBLIC;

**Comment by krasandr** [comment]
And same problem as above with MySQL function:

DELIMITER ;;
CREATE DEFINER=`root`@`%` FUNCTION `F_OnkoIsInTag`(clProcID int, toDate date) RETURNS int(11)
BEGIN


  SET @toDate := toDate;


  SET @IsDisp := (SELECT
      1
    FROM clinic_procedures cp
      INNER JOIN const_clinic_procedures ccp
        ON cp.ProcedureID = ccp.ProcedureID
    WHERE ccp.ProcedureType = 99
    AND cp.ClinicProcID = clProcID);

  IF (@IsDisp IS NOT NULL)
    THEN
    RETURN 0;
  END IF;


  RETURN (
  IF(
  ((SELECT
      MAX(cpa.ToDateTime)
    FROM clinic_procedures_apps cpa
    WHERE cpa.ClinicProcID = clProcID
    AND cpa.ToDateTime < DATE(@toDate)) IS NOT NULL)
  OR ((SELECT
      MAX(v.NzokReportDate)
    FROM v_s_docs v
    WHERE v.ClinicProcID = clProcID
    AND v.NzMedicamentID IS NOT NULL AND v.NzAmount > 0
    AND v.NzokReportDate < DATE(@toDate)) IS NOT NULL), 0, 1));




END ;;

And after conversion (again with CASE END):

CREATE OR REPLACE FUNCTION f_onkoisintag (clProcID integer, toDate date) RETURNS integer AS $body$
BEGIN


  SET @toDate := toDate;


  SET @IsDisp := (SELECT
      1
    FROM clinic_procedures cp
      INNER JOIN const_clinic_procedures ccp
        ON cp.ProcedureID = ccp.ProcedureID
    WHERE ccp.ProcedureType = 99
    AND cp.ClinicProcID = clProcID);

  CASE END
    THEN
    RETURN 0;
  END IF;


  RETURN (
  CASE WHEN   ((SELECT      MAX(cpa.ToDateTime)    FROM clinic_procedures_apps cpa    WHERE cpa.ClinicProcID = clProcID    AND cpa.ToDateTime < DATE(@toDate)) IS NOT NULL)  OR ((SELECT      MAX(v.NzokReportDate)
    FROM v_s_docs v    WHERE v.ClinicProcID = clProcID    AND v.NzMedicamentID IS NOT NULL AND v.NzAmount > 0    AND v.NzokReportDate < DATE(@toDate)) IS NOT NULL) THEN 0 ELSE  1 END );




END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION f_onkoisintag (clProcID integer, toDate date) FROM PUBLIC;

**Comment by darold** [comment]
Fresh commit 8d166cf might handle standard IF block when translating MySQL IF() function. I will check your last note.

**Comment by darold** [comment]
Your last code seems to be correctly translated with last commit.

**Comment by krasandr** [comment]
Yes, both cases are handled right and fixed, thank you.
I will continue with tests, but will close bug for now (Procedures are also converted right).
