### ISSUE TITLE
after last changes the view migration is extra slow

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#584]
The view migration was about 1hour. Now, it is more than 1 day. Last commit 2d1db01868ae2ce0bd8c30987fd0f6a535e6a9bb

**Comment by darold** [comment]
Ok, I will look on how to optimize this code tomorrow.

**Comment by okbob** [comment]
Looks so speed is ok, but the commit 2dc9a95587e19093ff9ae416924639a04bd15b59 enforce endless cycle on some views:

**Comment by darold** [comment]
Commit f4927f1 fixes possible infinite loop introduce with commit 2dc9a95.

**Comment by okbob** [comment]
It is fixed, thank you
