### ISSUE TITLE
Support procedure CALL in MySQL with PERFORM or SELECT p(a,b,c) INTO (d,e)

### ISSUE THREAD

**Issue by krasandr** [darold/ora2pg#586]
This is the same bug as "Support procedures call with OUT, IN OUT parameters #271", but also affects IN parameters in MySQL.

For example:

| P_FinMilachichBase | STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION | CREATE DEFINER=`root`@`%` PROCEDURE `P_FinMilachichBase`(IN FromDate date, IN ToDate date)
BEGIN

  DROP TEMPORARY TABLE IF EXISTS t_base;
  CREATE TEMPORARY TABLE t_base
  SELECT
    vfd.FDocID,
    vfd.FDetailID,
    vfd.FRowID,
    IF(s.IsToDoctor = 1 AND vfd.DoctorID IS NOT NULL, CONCAT('\u2116:', d.DoctorOrderPosition, ' / ', F_GetDoctorName(vfd.DoctorID)),
    CONCAT('No:', va.VirtualAccountPos, ' / ', va.VirtualAccountViewName)) AS AccountName,
    IF(s.IsToDoctor = 1 AND vfd.DoctorID IS NOT NULL, d.DoctorOrderPosition, va.VirtualAccountPos) AS AccountPosition,
    vfd.PatientID,
    vfd.ServiceID,
    vfd.ServiceName,
    vfd.Quantity,
    IFNULL((SELECT
        SUM(j.JAmount)
      FROM jorders j
      WHERE j.JOrderID = vfd.JOrderID
      AND j.JPartnerID = 2),0) AS ServiceAmount,
    vfd.Amount,
    vfd.FDocTypeID,
    vfd.IsOrder,
    vfd.IsAdvance,
    vfd.CashDeskID
  FROM v_f_docs vfd
    LEFT JOIN doctors d
      ON vfd.DoctorID = d.DoctorID
    INNER JOIN services s
      ON vfd.ServiceID = s.ServiceID
    INNER JOIN virtual_accounts va
      ON s.ToAccountID = va.VirtualAccountID
  WHERE vfd.FDocDate BETWEEN FromDate AND ToDate
  AND vfd.IsOrder = 1
  ORDER BY AccountPosition;

END | utf8                 | utf8_general_ci      | utf8_general_ci    |

This stored procedure is called with CALL from another:

| P_FinMilachichDetailedReport | STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION | CREATE DEFINER=`root`@`%` PROCEDURE `P_FinMilachichDetailedReport`(IN FromDate date, IN ToDate date)
    COMMENT 'Finansov otchet - detailna spravka'
BEGIN

  CALL P_FinMilachichBase(FromDate, ToDate);

  SELECT
    CONCAT(DATE_FORMAT(FromDate, '%d-%m-%Y'), ' / ', DATE_FORMAT(
    ToDate, '%d-%m-%Y')) AS DatePeriod,
    SUM(t.Amount) AS CashDeskAmount,
    cd.CashDeskName
  FROM t_base t
    INNER JOIN cash_desks cd
      ON t.CashDeskID = cd.CashDeskID
  WHERE 1 = 1
  GROUP BY t.CashDeskID
  HAVING CashDeskAmount <> 0
  ORDER BY cd.CashDeskPosition;

  SELECT
    *
  FROM t_base t
  WHERE t.ServiceAmount = t.Amount
  ORDER BY t.AccountPosition;

  SELECT
    *
  FROM t_base t
  WHERE t.ServiceAmount != t.Amount
  ORDER BY t.AccountPosition;

SELECT 1 FROM
  dual;

END                                      | utf8                 | utf8_general_ci      | utf8_general_ci    |
+------------------------------+----------------------------------------------------------------+---------------------

In PostgreSQL, when converted with ora2pg, CALL must be translated to PERFORM (if calling stored procedure don't return out results) or with Select p(...) into (v1, v2 ...) if calling stored procedure returns results via OUT or INOUT parameters.

But both of this did't happened, CALL is not translated at all:

CREATE OR REPLACE FUNCTION p_finmilachichbase (IN FromDate date, ToDate date) RETURNS VOID AS $body$
BEGIN

  DROP TEMPORARY TABLE IF EXISTS t_base;
  CREATE TEMPORARY TABLE t_base
  SELECT
    vfd.FDocID,
    vfd.FDetailID,
    vfd.FRowID,
    CASE WHEN s.IsToDoctor = 1 AND vfd.DoctorID IS NOT NULL THEN CONCAT('\u2116:', d.DoctorOrderPosition, ' / ', F_GetDoctorName(vfd.DoctorID)) ELSE     CONCAT('\u2116:', va.VirtualAccountPos, ' / ', va.VirtualAccountViewName) END  AS AccountName,
    CASE WHEN s.IsToDoctor = 1 AND vfd.DoctorID IS NOT NULL THEN d.DoctorOrderPosition ELSE  va.VirtualAccountPos END  AS AccountPosition,
    vfd.PatientID,
    vfd.ServiceID,
    vfd.ServiceName,
    vfd.Quantity,
    COALESCE((SELECT
        SUM(j.JAmount)
      FROM jorders j
      WHERE j.JOrderID = vfd.JOrderID
      AND j.JPartnerID = 2), 0) AS ServiceAmount,
    vfd.Amount,
    vfd.FDocTypeID,
    vfd.IsOrder,
    vfd.IsAdvance,
    vfd.CashDeskID
  FROM v_f_docs vfd
    LEFT JOIN doctors d
      ON vfd.DoctorID = d.DoctorID
    INNER JOIN services s
      ON vfd.ServiceID = s.ServiceID
    INNER JOIN virtual_accounts va
      ON s.ToAccountID = va.VirtualAccountID
  WHERE vfd.FDocDate BETWEEN FromDate AND ToDate
  AND vfd.IsOrder = 1
  ORDER BY AccountPosition;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION p_finmilachichbase (IN FromDate date, ToDate date) FROM PUBLIC;

CREATE OR REPLACE FUNCTION p_finmilachichdetailedreport (IN FromDate date, ToDate date) RETURNS VOID AS $body$
BEGIN

  CALL P_FinMilachichBase(FromDate, ToDate);

  SELECT
    CONCAT(to_char((FromDate)::timestamp, 'DD-MM-YYYY'), ' / ', to_char((ToDate)::timestamp, 'DD-MM-YYYY')) AS DatePeriod,
    SUM(t.Amount) AS CashDeskAmount,
    cd.CashDeskName
  FROM t_base t
    INNER JOIN cash_desks cd
      ON t.CashDeskID = cd.CashDeskID
  WHERE 1 = 1
  GROUP BY t.CashDeskID
  HAVING CashDeskAmount <> 0
  ORDER BY cd.CashDeskPosition;

  SELECT
    *
  FROM t_base t
  WHERE t.ServiceAmount = t.Amount
  ORDER BY t.AccountPosition;

  SELECT
    *
  FROM t_base t
  WHERE t.ServiceAmount != t.Amount
  ORDER BY t.AccountPosition;

SELECT 1 FROM
  dual;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION p_finmilachichdetailedreport (IN FromDate date, ToDate date) FROM PUBLIC;

(also, COMMENT is missing from second procedure).

Also, CALL-ed stored procedure can return with OUT or INOUT parametres:

CREATE OR REPLACE FUNCTION p_patientprinthospitaltalon (IN depPatID integer) RETURNS VOID AS $body$
BEGIN

  SET @PrintOut := 0;
  SELECT
    CASE WHEN w.OutDateTime IS NOT NULL THEN 1 ELSE  0 END  INTO @PrintOut
  FROM department_patients w
  WHERE w.DepartmentPationID = depPatID;

  CALL P_PatientPrintHospitalTalonEx(depPatID, 1, 1, 1, @PrintOut);

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION p_patientprinthospitaltalon (IN depPatID integer) FROM PUBLIC;

in this example, CALL must be translated not to PERFORM, right conversion will be 
(maybe depend of definition - INOUT or OUT parameter)
SELECT P_PatientPrintHospitalTalonEx(depPatID, 1, 1, 1) INTO PrintOut

**Comment by krasandr** [comment]
I think that it is perfectly enough if converting from CALL in stored procedures in MySQL to PERFORM or SELECT ... INTO... in PostgreSQL functions is done for basic scenarios or simply porting working solution for Oracle in ora2pg to cover MySQL too.

**Comment by darold** [comment]
This work have not been done yet for MySQL. I will have a look.

**Comment by krasandr** [comment]
Right now, MySQL CALL in stored procedures is converted in PostgreSQL function again to CALL (which it don't support). I am not sure, if this conversion in code is made in steps, is it correct in beginning to cover only the very simple calling, for example wihout OUT or INOUT parameters, that is converted always to PERFORM.

I am not sure how much calling in procedures in MySQL is different from Oracle, I see that IN, OUT and INOUT parameters in definitions are the same, so in next step maybe, it can cover SELECT ... INTO ... (if it is not so much different), without very complicated situations, in which parse tree and some kind of lexer and grammar will be needed (in the future, maybe). I am not sure also about variable assignments, is it enough to cover only SELECT ... INTO ... or it is important to assign also.

**Comment by darold** [comment]
Commit 296f7ba might rewrite most of the function calls (with or without OUT parameters) into the MySQL call, just like in Oracle. Also the DECLARE variables have been moved to a DECLARE block in PostgreSQL.

**Comment by krasandr** [comment]
It works. I will make some additional checks, but seems it's O.K (but comment of function is missing again)

CREATE OR REPLACE FUNCTION p_finmilachichdetailedreport (IN FromDate date, ToDate date) RETURNS VOID AS $body$
BEGIN

  PERFORM P_FinMilachichBase(FromDate, ToDate);

  SELECT
    CONCAT(DATE_FORMAT(FromDate, '%d-%m-%Y'), ' / ', DATE_FORMAT(
    ToDate, '%d-%m-%Y')) AS DatePeriod,
    SUM(t.Amount) AS CashDeskAmount,
    cd.CashDeskName
  FROM t_base t
    INNER JOIN cash_desks cd
      ON t.CashDeskID = cd.CashDeskID
  WHERE 1 = 1
  GROUP BY t.CashDeskID
  HAVING CashDeskAmount <> 0
  ORDER BY cd.CashDeskPosition;

  SELECT
    *
  FROM t_base t
  WHERE t.ServiceAmount = t.Amount
  ORDER BY t.AccountPosition;

  SELECT
    *
  FROM t_base t
  WHERE t.ServiceAmount != t.Amount
  ORDER BY t.AccountPosition;


SELECT 1 ;

  
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION p_finmilachichdetailedreport (IN FromDate date, ToDate date) FROM PUBLIC;

**Comment by darold** [comment]
Last commit a4b1cf3 restore comment on function using a `COMMENT ON FUNCTION` statement at end of the function declaration.

**Comment by krasandr** [comment]
Yes, COMMENT is restored, thank you.
But the old problem still exists - in this example, comment was written in cyrillic alphabet, so without changing manually in Ora2Pg.pm (in sub _mysql_connection)
from:
my $dbh = DBI->connect("$self->{oracle_dsn}", $self->{oracle_user}, $self->{oracle_pwd}, { 'RaiseError' => 1, AutoInactiveDestroy => 1});
to:
my $dbh = DBI->connect("$self->{oracle_dsn}", $self->{oracle_user}, $self->{oracle_pwd}, { 'RaiseError' => 1, AutoInactiveDestroy => 1, mysql_enable_utf8 => 1}); 
characters are not readable.
But I will close this bug, because problem with unreadable characters is not related to it.

**Comment by darold** [comment]
Oh I've forgotten this last problem, it is now fixed with commit 2c240ed that adds `mysql_enable_utf8 => 1` to each MySQL connection.
