### ISSUE TITLE
START TRANSACTION and COMMIT in MySQL procedure conversion

### ISSUE THREAD

**Issue by krasandr** [darold/ora2pg#587]
I think, that  transactions cannot exists in functions (PostgreSQL don't have autonomous transactions),
so is this converted properly (or I am in mistake). Also, PostgreSQL did't accept INT(11) for example.
I am not sure, is PostgreSQL will ignore definition of transaction, expecially in second example below.

Definition from MySQL (MariaDB 10.2.10): 
```
| P_AppointmentMetaSave | STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION | CREATE DEFINER=`root`@`%` PROCEDURE `P_AppointmentMetaSave`(IN WorkAppMetaID     INT(11),
                                           IN DoctorID          INT(11),
                                           IN WorkKabinetTypeID INT(11),
                                           IN UserID            INT(11),
                                           IN WorkDate          DATE,
                                           IN WFromTime         TIME,
                                           IN WToTime           TIME,
                                           IN WorkStep          INT(11)
                                           )
BEGIN

  START TRANSACTION;

  
  IF (WorkAppMetaID = 0) THEN
    INSERT INTO deva_maria.w_appointment_meta
      (DoctorID, WorkKabinetTypeID, UserID, WorkDate, WFromTime, WToTime, WorkStep)
    SELECT DoctorID
         , WorkKabinetTypeID
         , UserID
         , WorkDate
         , WFromTime
         , WToTime
         , WorkStep
    FROM
      dual
    WHERE
      NOT EXISTS (SELECT 1
                  FROM
                    w_appointment_meta m
                  WHERE
                    m.DoctorID = DoctorID
                    AND m.WorkDate = date(WorkDate)
                    AND WFromTime < m.WToTime
                    AND m.WFromTime < WToTime);
    SELECT LAST_INSERT_ID();
    
  ELSE
    SET @CheckControl := ifnull((SELECT 1
                                 FROM
                                   w_appointment_meta m
                                 WHERE
                                   m.DoctorID = DoctorID
                                   AND m.WorkAppMetaID != WorkAppMetaID
                                   AND m.WorkDate = date(@WorkDate)
                                   AND WToTime < m.WToTime
                                   AND m.WFromTime < WFromTime
                                 LIMIT
                                   1), 0);
    IF @CheckControl != 0 THEN
      SELECT 0;
    END IF;
    UPDATE w_appointment_meta w
    SET
      w.WFromTime = WFromTime, w.WToTime = WToTime, w.WorkStep = WorkStep, w.UserID = UserID
    WHERE
      w.WorkAppMetaID = WorkAppMetaID
      AND @CheckControl = 0;
    SELECT WorkAppMetaID;
  END IF;

  COMMIT;
END | utf8                 | utf8_general_ci      | utf8_general_ci    |
```

And converted function with ora2pg in PostgreSQL:
```
CREATE OR REPLACE FUNCTION p_appointmentmetasave (IN WorkAppMetaID     integer(11), DoctorID          integer(11), WorkKabinetTypeID integer(11), UserID            integer(11), WorkDate          date, WFromTime         time without time zone, WToTime           time without time zone, WorkStep          integer(11)
                                           ) RETURNS VOID AS $body$
BEGIN

  START TRANSACTION;

  
  IF (WorkAppMetaID = 0) THEN
    INSERT INTO deva_maria.w_appointment_meta(DoctorID, WorkKabinetTypeID, UserID, WorkDate, WFromTime, WToTime, WorkStep)
    SELECT DoctorID
         , WorkKabinetTypeID
         , UserID
         , WorkDate
         , WFromTime
         , WToTime
         , WorkStep
    FROM
      dual
    WHERE
      NOT EXISTS (SELECT 1
                  FROM
                    w_appointment_meta m
                  WHERE
                    m.DoctorID = DoctorID
                    AND m.WorkDate = date(WorkDate)
                    AND WFromTime < m.WToTime
                    AND m.WFromTime < WToTime);
    SELECT LAST_INSERT_ID();
    
  ELSE
    SET @CheckControl := COALESCE((SELECT 1
                                 FROM
                                   w_appointment_meta m
                                 WHERE
                                   m.DoctorID = DoctorID
                                   AND m.WorkAppMetaID != WorkAppMetaID
                                   AND m.WorkDate = date(@WorkDate)
                                   AND WToTime < m.WToTime
                                   AND m.WFromTime < WFromTime
                                 LIMIT
                                   1), 0);
    IF @CheckControl != 0 THEN
      SELECT 0;
    END IF;
    UPDATE w_appointment_meta w
    SET
      w.WFromTime = WFromTime, w.WToTime = WToTime, w.WorkStep = WorkStep, w.UserID = UserID
    WHERE
      w.WorkAppMetaID = WorkAppMetaID
      AND @CheckControl = 0;
    SELECT WorkAppMetaID;
  END IF;

  COMMIT;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION p_appointmentmetasave (IN WorkAppMetaID     integer(11), DoctorID          integer(11), WorkKabinetTypeID integer(11), UserID            integer(11), WorkDate          date, WFromTime         time without time zone, WToTime           time without time zone, WorkStep          integer(11) ) FROM PUBLIC;
```

**Comment by krasandr** [comment]
Second example, before conversion, definition in MySQL (I am not sure and I must check, is this transaction definition will be ignored in PostreSQL 10.1):

| P_s_month_avg_min_productsCalc | STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION | CREATE DEFINER=`root`@`%` PROCEDURE `P_s_month_avg_min_productsCalc`(IN immediatelyCalcul TINYINT)
BEGIN

set @frDate:= null; 
set @toDate:=DATE(now());
set @backVal:=(select s.GlobalSettingValue from global_settings s where s.GlobalSettingID=26);
set @frDate:=DATE_ADD(date(DATE_FORMAT(@toDate,'%Y-%m-%01')), interval - @backVal month);
set @toDate:=DATE_ADD(date(DATE_FORMAT(@toDate,'%Y-%m-%01')), interval - 1 day);
set @chekDate:=DATE_ADD(date(DATE_FORMAT(now(),'%Y-%m-%01')), interval - 1 day);

if(immediatelyCalcul=1 or  DATE(@toDate)=date(@chekDate))
then
  start transaction;
set @frDate:= null; 
set @toDate:=DATE(now());
set @backVal:=(select s.GlobalSettingValue from global_settings s where s.GlobalSettingID=26);
set @frDate:=DATE_ADD(date(DATE_FORMAT(@toDate,'%Y-%m-%01')), interval - @backVal month);
set @toDate:=DATE_ADD(date(DATE_FORMAT(@toDate,'%Y-%m-%01')), interval - 1 day);
set @chekDate:=DATE_ADD(date(DATE_FORMAT(now(),'%Y-%m-%01')), interval - 1 day);
DROP TEMPORARY TABLE IF EXISTS t_min;
CREATE temporary TABLE t_min
select t.ProductID,t.StoreID, sum(q)/@backVal qMonthAVG,sum(q)/@backVal as qForSupplay
from
(
SELECT sl.ProductID,sd.StoreID, SUM(sdd.Quantity) AS q
  FROM s_doc_details sdd
  INNER JOIN s_lots sl ON sdd.SLotID = sl.SLotID
  INNER JOIN s_documents sd ON sdd.SDocID = sd.SDocID
  INNER JOIN s_document_types sdt ON sd.SDocTypeID = sdt.SDocTypeID
  WHERE sdt.OrderOrSupply=-1
  AND sd.SDocDate BETWEEN date(@frDate) and date(@toDate)
  GROUP BY sl.ProductID, sd.StoreID
)as t 
group by ProductID,t.StoreID; 

UPDATE t_min m,
  s_products p,
  s_const_product_categories cat
  set m.qForSupplay=round(m.qForSupplay+m.qForSupplay*cat.AdditionalPercentMinQuan/100,2)
  WHERE
  m.ProductID=p.ProductID
  and cat.ProductCategoryID=p.ProductCategoryID;

DELETE from s_st_products_month_avg_costs;
insert into s_st_products_month_avg_costs(ProductID,StoreID,St_productCost)
SELECT t.ProductID,t.StoreID,qMonthAVG  from t_min t;
 insert into events_log(EventLogTime,EventLogDescription) values (now(),'Aktualizaciq na razhodi');

DELETE from s_products_stores_quantity;
insert into s_products_stores_quantity(ProductID,StoreID,Quantity)
SELECT t.ProductID,t.StoreID,qForSupplay  from t_min t;
insert into events_log(EventLogTime,EventLogDescription) values (now(),'Aktualizaciq na razhodi');

COMMIT;
end if;

END | utf8                 | utf8_general_ci      | utf8_general_ci    |

And after conversion with ora2pg for PostgreSQL:

CREATE OR REPLACE FUNCTION p_s_month_avg_min_productscalc (IN immediatelyCalcul smallint) RETURNS VOID AS $body$
BEGIN

@frDate::= null; 
@toDate::=DATE(CURRENT_TIMESTAMP);
@backVal::=(select s.GlobalSettingValue from global_settings s where s.GlobalSettingID=26);
@frDate::=DATE_ADD(date(to_char((@toDate)::timestamp, 'YYYY-MM-%01')), interval - @backVal month);
@toDate::=DATE_ADD(date(to_char((@toDate)::timestamp, 'YYYY-MM-%01')), interval - 1 day);
@chekDate::=DATE_ADD(date(to_char((CURRENT_TIMESTAMP)::timestamp, 'YYYY-MM-%01')), interval - 1 day);

if (immediatelyCalcul=1 or  DATE(@toDate)=date(@chekDate))
then
  start transaction;
@frDate::= null; 
@toDate::=DATE(CURRENT_TIMESTAMP);
@backVal::=(select s.GlobalSettingValue from global_settings s where s.GlobalSettingID=26);
@frDate::=DATE_ADD(date(to_char((@toDate)::timestamp, 'YYYY-MM-%01')), interval - @backVal month);
@toDate::=DATE_ADD(date(to_char((@toDate)::timestamp, 'YYYY-MM-%01')), interval - 1 day);
@chekDate::=DATE_ADD(date(to_char((CURRENT_TIMESTAMP)::timestamp, 'YYYY-MM-%01')), interval - 1 day);
DROP TEMPORARY TABLE IF EXISTS t_min;
CREATE temporary TABLE t_min
select t.ProductID,t.StoreID, sum(q)/@backVal qMonthAVG,sum(q)/@backVal as qForSupplay
from (
SELECT sl.ProductID,sd.StoreID, SUM(sdd.Quantity) AS q
  FROM s_doc_details sdd
  INNER JOIN s_lots sl ON sdd.SLotID = sl.SLotID
  INNER JOIN s_documents sd ON sdd.SDocID = sd.SDocID
  INNER JOIN s_document_types sdt ON sd.SDocTypeID = sdt.SDocTypeID
  WHERE sdt.OrderOrSupply=-1
  AND sd.SDocDate BETWEEN date(@frDate) and date(@toDate)
  GROUP BY sl.ProductID, sd.StoreID
)as t 
group by ProductID,t.StoreID; 

UPDATE t_min m,
  s_products p,
  s_const_product_categories cat
  set m.qForSupplay=round((m.qForSupplay+m.qForSupplay*cat.AdditionalPercentMinQuan/100)::numeric,2)
  WHERE
  m.ProductID=p.ProductID
  and cat.ProductCategoryID=p.ProductCategoryID;

DELETE from s_st_products_month_avg_costs;
insert into s_st_products_month_avg_costs(ProductID,StoreID,St_productCost)
SELECT t.ProductID,t.StoreID,qMonthAVG  from t_min t;
 insert into events_log(EventLogTime,EventLogDescription) values (CURRENT_TIMESTAMP,'Aktualizaciq na razhodi');

DELETE from s_products_stores_quantity;
insert into s_products_stores_quantity(ProductID,StoreID,Quantity)
SELECT t.ProductID,t.StoreID,qForSupplay  from t_min t;
insert into events_log(EventLogTime,EventLogDescription) values (CURRENT_TIMESTAMP,'Aktualizaciq na razhodi');

COMMIT;
end if;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION p_s_month_avg_min_productscalc (IN immediatelyCalcul smallint) FROM PUBLIC;

**Comment by darold** [comment]
Commit f300345 fixes translation of types in MySQL function parameter, int(11) will be translated into bigint.

Commit ae2f684 remove START TRANSACTION from function code, it is useless.

Also looking at variables starting with an `@` I guess they are global variables so I need to fix that too.

**Comment by darold** [comment]
Can you explain me where the following variables from your second example are defined?
```
set @frDate:= null; 
set @toDate:=DATE(now());
set @backVal:=(select s.GlobalSettingValue from global_settings s where s.GlobalSettingID=26);
set @frDate:=DATE_ADD(date(DATE_FORMAT(@toDate,'%Y-%m-%01')), interval - @backVal month);
set @toDate:=DATE_ADD(date(DATE_FORMAT(@toDate,'%Y-%m-%01')), interval - 1 day);
set @chekDate:=DATE_ADD(date(DATE_FORMAT(now(),'%Y-%m-%01')), interval - 1 day);
```
and if these variable are used outside the function?

**Comment by krasandr** [comment]
No, in MySQL, there is no explicit need to define a variables - the type of variable will be suggested (on the fly) automaticly by assignment. So you have in example above, an untyped null, a type date, a type of backVal that is the same of type of selected s.GlobalSettingValue column and so on.

Also, you are right - this variables can be used outside the function, but usually it is avoided, because programmers often uses connection pools/poolers, so session-based variables becomes danger (the same often is happened with temp tables, that is also per session). Usually (as above), variables usage is restricted only to function, it which they are defined/used, also, right now, without external extensions, PostgreSQL don't have support of session-based variables. So, in basic scenarios (without external extensions) and for most often usage, variables are declared (by assignment humself) in functions and are used only in it, not outside and there is no inheritance of them.

**Comment by krasandr** [comment]
Also, after you removed useless START TRANSACTION from function code, you also need to remove useless COMMIT in the end (in the end of function, 5th row above):

CREATE OR REPLACE FUNCTION p_appointmentmetasave (IN WorkAppMetaID bigint, DoctorID bigint, WorkKabinetTypeID bigint, UserID bigint, WorkDate date, WFromTime time without time zone, WToTime time without time zone, WorkStep bigint ) RETURNS VOID AS $body$
BEGIN

  
  IF (WorkAppMetaID = 0) THEN
    INSERT INTO deva_maria.w_appointment_meta(DoctorID, WorkKabinetTypeID, UserID, WorkDate, WFromTime, WToTime, WorkStep)
    SELECT DoctorID
         , WorkKabinetTypeID
         , UserID
         , WorkDate
         , WFromTime
         , WToTime
         , WorkStep
    
    WHERE
      NOT EXISTS (SELECT 1
                  FROM
                    w_appointment_meta m
                  WHERE
                    m.DoctorID = DoctorID
                    AND m.WorkDate = date(WorkDate)
                    AND WFromTime < m.WToTime
                    AND m.WFromTime < WToTime);
    SELECT LAST_INSERT_ID();
    
  ELSE
    SET @CheckControl := COALESCE((SELECT 1
                                 FROM
                                   w_appointment_meta m
                                 WHERE
                                   m.DoctorID = DoctorID
                                   AND m.WorkAppMetaID != WorkAppMetaID
                                   AND m.WorkDate = date(@WorkDate)
                                   AND WToTime < m.WToTime
                                   AND m.WFromTime < WFromTime
                                 LIMIT
                                   1), 0);
    IF @CheckControl != 0 THEN
      SELECT 0;
    END IF;
    UPDATE w_appointment_meta w
    SET
      w.WFromTime = WFromTime, w.WToTime = WToTime, w.WorkStep = WorkStep, w.UserID = UserID
    WHERE
      w.WorkAppMetaID = WorkAppMetaID
      AND @CheckControl = 0;
    SELECT WorkAppMetaID;
  END IF;

  COMMIT;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION p_appointmentmetasave (IN WorkAppMetaID bigint, DoctorID bigint, WorkKabinetTypeID bigint, UserID bigint, WorkDate date, WFromTime time without time zone, WToTime time without time zone, WorkStep bigint ) FROM PUBLIC;

**Comment by darold** [comment]
Commit 1f70e7a applies same behavior with COMMIT in MySQL function code than in Oracle code. It is kept untouched to be able to detect a possible change of code logic. It can be automatically commented if COMMENT_COMMIT_ROLLBACK is enabled. Also I have keep the START TRANSACTION call but it is automatically commented.

Thanks a lot for your explanations about variable. In this case I think they might be transformed in regular function variable and be defined in a DECLARE section. I will see if there is a solution to do this automatically but I'm not very confident and for now it has to be rewritten by hand.

**Comment by krasandr** [comment]
It works, but I think yours solution is better, because next version of PostgreSQL probably will have real procedures and/or autonomous transactions, so, maybe, if you extend COMMENT_COMMIT_ROLLBACK to cover START TRANSACTION also (or rename variable to something, that will point that it's also cover START TRANSACTION), it will be better, when it is set to 1, to comment all of them, that PostgreSQL right now did't support - START TRANSACTION, COMMIT and ROLLBACK, otherwise to keep all of them to default values (uncommented).

**Comment by darold** [comment]
It is already possible to have autonomous transaction in PostgreSQL using dblink and Ora2Pg is able to generate this code. Before applying this code I need to know if START TRANSACTION is always used to cover the full code of a function or it can be used in some part of the code to force a commit on a single insert for example.

**Comment by krasandr** [comment]
O.K., I understand, so I am closing this topic. About MySQL variables, I will open another topic, when there is some possible decision how it can be mitigated.
