### ISSUE TITLE
MySQL GROUP_CONCAT() conversion to array_to_string(array_agg(...),...), string_agg() etc...

### ISSUE THREAD

**Issue by krasandr** [darold/ora2pg#588]
Right now, GROUP_CONCAT in MySQL is not converted to array_to_string(array_agg(...),...) or just string_agg(). MySQL don't have arrays or something like PostgreSQL UNNEST and so, and that is reason why it uses very often GROUP_CONCAT. Maybe there is solution (in most basic scenarios, without ordering and so on), when it can be suceffuly converted with ora2pg? 

SHOW CREATE FUNCTION F_GetPeculiarities:

| F_GetPeculiarities | STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION | CREATE DEFINER=`root`@`%` FUNCTION `F_GetPeculiarities`(pArtID int(11)) RETURNS text CHARSET utf8
BEGIN

  RETURN (SELECT
      GROUP_CONCAT(DISTINCT icp.IvfPecName SEPARATOR ', ')
    FROM ivf_arts_ivf_const_peculiarities ap
      INNER JOIN ivf_const_peculiarities icp
        ON ap.IvfPecID = icp.IvfPecID
    WHERE ap.IvfArtID = pArtID
    ORDER BY icp.IvfPecPosition);

END | utf8                 | utf8_general_ci      | utf8_general_ci    |

SHOW CREATE FUNCTION F_GetSterlitetTypes:

| F_GetSterlitetTypes | STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION | CREATE DEFINER=`root`@`%` FUNCTION `F_GetSterlitetTypes`(artID INT) RETURNS varchar(350) CHARSET utf8
BEGIN

  RETURN

  concat_ws(', ', (SELECT f.SterialitetFormName
                   FROM
                     ivf_arts a
                   INNER JOIN g_const_sterialitet_forms f
                   ON a.SterialitetFormID = f.SterialitetFormID
                   WHERE
                     a.IvfArtID = artID),

  (SELECT group_concat(st.SterialitetTypeName ORDER BY st.SterialitetTypePos)
   FROM
     ivf_arts_g_const_sterialitet_types t
   INNER JOIN g_const_sterialitet_types st
   ON t.SterialitetTypeID = st.SterialitetTypeID
   WHERE
     t.IvfArtID = artID
  ));

END | utf8                 | utf8_general_ci      | utf8_general_ci    |

Conversion that produces now Ora2Pg:

CREATE OR REPLACE FUNCTION f_getpeculiarities (pArtID bigint) RETURNS text AS $body$
BEGIN

  RETURN(SELECT
      GROUP_CONCAT(DISTINCT icp.IvfPecName SEPARATOR ', ')
    FROM ivf_arts_ivf_const_peculiarities ap
      INNER JOIN ivf_const_peculiarities icp
        ON ap.IvfPecID = icp.IvfPecID
    WHERE ap.IvfArtID = pArtID
    ORDER BY icp.IvfPecPosition);

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION f_getpeculiarities (pArtID bigint) FROM PUBLIC;

CREATE OR REPLACE FUNCTION f_getsterlitettypes (artID integer) RETURNS varchar AS $body$
BEGIN

  RETURN

  concat_ws(', ', (SELECT f.SterialitetFormName
                   FROM
                     ivf_arts a
                   INNER JOIN g_const_sterialitet_forms f
                   ON a.SterialitetFormID = f.SterialitetFormID
                   WHERE
                     a.IvfArtID = artID),

  (SELECT group_concat(st.SterialitetTypeName ORDER BY st.SterialitetTypePos)
   FROM
     ivf_arts_g_const_sterialitet_types t
   INNER JOIN g_const_sterialitet_types st
   ON t.SterialitetTypeID = st.SterialitetTypeID
   WHERE
     t.IvfArtID = artID
  ));

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION f_getsterlitettypes (artID integer) FROM PUBLIC;

**Comment by krasandr** [comment]
Maybe some solution like used in topic "Oracle aggregate function LISTAGG not translated #425" will be possible? In simple scenarios, it can be converted probably easy, by using different function and substitution of positional parameters?

**Comment by darold** [comment]
Fixed with commit ￼e79bf03

**Comment by krasandr** [comment]
It works now - I created some different functions and stored procedures, all are successful. Thank you.
