### ISSUE TITLE
Not all Oracle rows were migrated to Postgres

### ISSUE THREAD

**Issue by opusmagnum** [darold/ora2pg#589]
Hi, 
first of all -- thanks for the great tool!
We do a migration with the application shut down, `Isolation level: SET TRANSACTION READ ONLY` and noticed the following effect:
ora2pg exports the number of rows, which are in `statistics` -- `select num_rows from all_tables where table_name = '<mytable>'` and not the result of `select count(*) from <mytable>` . If statistics are not up to date, than not all records were migrated.

Is it possible, or do I miss something in the configuration?

**Comment by darold** [comment]
Hi,

Ora2Pg doesn't care about rows count statistics, it export data using a `SELECT * FROM table`, the row count is only used for the progress bar and not be accurate.

If all rows are not exported you might have an other issue. Are you using latest development code? If not give it a try and let me know.

Regards

**Comment by opusmagnum** [comment]
Thank you for the answer, 

as far as I understood, _ora2pg_ reads and copy Oracle data in `DATA_LIMIT` chunks. How are these chunks selected? 
Is `ROW_NUM` from statistics and [`ROWNUM` pseudocolumn](https://docs.oracle.com/cd/B19306_01/server.102/b14200/pseudocolumns009.htm) somehow involved in this calculation or select-where condition?

We use release 18.2 -- `ora2pg -d -t COPY  -c ora2pg.conf --exclude "..." --jobs 8 --copies 1 --parallel 8` with `DATA_LIMIT: 10000` and `BLOB_LIMIT: 100`.

**Comment by darold** [comment]
Ok, thanks for the feedback.

The chunks are build internally by DBD::Oracle when setting RowCacheSize to DATA_LIMIT value (BLOB_LIMIT for table with BLOB), this mean that each call to fetchrow_array() will returned RowCacheSize record in a single array. This is also why under system with low memory OOM is possible.

If you set PG_DSN you can execute the following command after migrating your data to verify if some rows are missing:
```
ora2pg -t TEST -c ora2pg.conf --count_rows > test_result.txt
```
Best regards
