### ISSUE TITLE
SECURITY DEFINER clause

### ISSUE THREAD

**Issue by jacks33** [darold/ora2pg#591]
Hello,

I'm using ora2pg latest release 18.2 (from pgdg rhel7 repository) 

In the translation of PL/SQL I notice that functions are always  translated with SECURITY DEFINER attribute.
Also, I did not see any setting related to that attribute in ora2pg.conf

I used ora2pg 17.6b release and compare translations. That release did not set SECURITY DEFINER.

So it seems to be a bug.

Thank you.

**Comment by okbob** [comment]
SECURITY DEFINER flag is more correct than SECURITY INVOKER, and should be default. But I agree, so this can be controlled by some flag, because when it is not necessary, then SECURITY INVOKER is preferred by PostgreSQL community.

**Comment by darold** [comment]
Commit 09726e5 adds a new configuration directive: FORCE_SECURITY_INVOKER. Enable it if you want to override security privileges defined on all functions and use SECURITY DEFINER instead of the privileges set in Oracle.
