### ISSUE TITLE
does ora2pg support the import of flashbackscn in oracle？

### ISSUE THREAD

**Issue by jinxiaoxin** [darold/ora2pg#592]

**Comment by darold** [comment]
If I understand well flashbackscn is a expdp parameter so this doesn't concern Ora2Pg as Ora2Pg doesn't read dump file. Ora2Pg need to connect directly to your live Oracle database, if you need you can import your dump into a local Oracle database and connect Ora2Pg to it or you can use Ora2Pg directly on your production Oracle database as it doesn't write anything in Oracle. Data export can might add extra load to your database so take care at the time you are doing this export and the number of parallel processes used.

If I miss interpreted your question, please explain with more words what you want to do.
