### ISSUE TITLE
REPLACE_QUERY

### ISSUE THREAD

**Issue by venkatabn** [darold/ora2pg#594]
Hi,

Ora2pg version 18.2

I am trying to export a subset of the data with the following query -

REPLACE_QUERY  TEST[select * from test where created >to_date('10 JAN 2016')]

and it does not work. ora2pg simply migrates all the rows. I have got a bigger size table with BLOBs.

When i test the same with a small table, it works fine. Any help is appreciated. Thanks !

**Comment by darold** [comment]
Hi,

You should not use the REPLACE_QUERY directive to do what you want to do but WHERE instead:
```
WHERE        TEST[created >to_date('10 JAN 2016')]
```
REPLACE_QUERY must be used with more complex queries redefining the column part.
