### ISSUE TITLE
Ordering package functions in translated script

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#595]
Hello,

Would it be possible to add an option to get the functions of a same source schema always ordered by name in the translated script ?

This is because I have a schema dedicated to CONSTANTS in Oracle DB, therefore 1 FUNCTION per constant, and when I do a new translation, I cannot compare it to the previous translation, because the functions have not been translated in the same order.

Thanks in advance and once again for your great tool :)
E.

**Comment by darold** [comment]
Hello Eric,

All functions, procedures and package's functions are exported from database sorted by named so I guess you are translating an input file?

**Comment by darold** [comment]
Ok I found the Perl statement that was not ordering function by name, commit ac42db8 might solve this issue.
