### ISSUE TITLE
Contradicting defaults for XML_PRETTY

### ISSUE THREAD

**Issue by TWAC** [darold/ora2pg#596]
The [config file](https://github.com/darold/ora2pg/blob/c1c43f9b3135929ab68f55389434aefe5fe011fe/Makefile.PL#L903) and [source](https://github.com/darold/ora2pg/blob/c1c43f9b3135929ab68f55389434aefe5fe011fe/lib/Ora2Pg.pm#L1040) uses different defaults for XML_PRETTY. The documentation refers for the source default, which makes reading the config file a bit confusing.

**Comment by darold** [comment]
Commit eee1688 should clarify the comment.

**Comment by TWAC** [comment]
Thanks!
