### ISSUE TITLE
problem with v18.2 ?

### ISSUE THREAD

**Issue by did16** [darold/ora2pg#597]
Hi
We have installed the ora2pg v 18.2 and we have the following error 
>>
$ ora2pg -t SHOW_REPORT -s "dbi:mysql:host=gate0136;port=3306;database=TESTDB" -u test -w ***** --dump_as_html --estimate_cost --cost_unit_value 10
WARNING: setting SCHEMA to MySQL database name TESTDB.
[========================>] 0/0 tables (100.0%) end of scanning.
Undefined subroutine &Ora2Pg::MySQL::_global_temp_table_info called at /usr/share/perl5/vendor_perl/Ora2Pg.pm line 10029.
<<
The code of tag 18.2 is different from the code of the master branch.
The code in tag 18.2 does not include any changes to the master branch.

**Comment by darold** [comment]
Hi,

Please upgrade to latest development code from github this have already been fixed.

Regards,
