### ISSUE TITLE
Proposal about type Query and named placeholders for different database drivers

### ISSUE THREAD

**Issue by krasandr** [darold/ora2pg#598]
I am thinking about what is the purpose of type Query and right now, I don't find usable answer.
Right now, for me, Ora2Pg translates very good MySQL stored procedures, functions, triggers and views and variables in PL/PGSQL, and I am thinking what can be done next, to easy migration steps to PostgreSQL. And of course, next step can be to easy steps about application migration, because there is not only database, there is some queries hard coded in application also, more or less (when there is no heavy usage of ORM, because of performance issues). So, I have a (stupid) idea, why not make some progress on it. For example, imagine that you have some project source code, located on /project. You can (with regex, but self-made, not part of Ora2Pg) search about some calls to database, located in project files. For example, depend of database driver - if you use Perl, it will be DBI/DBD, if you use PHP, it will be PDO or some native driver implementation, if you use Java, it will be JDBC, if you use .NET, it will be some different thing and so on (I like Golang and it will be pq or pgx driver, by the way). But what is the difference? The difference is what they think about (named) placeholders - some of them uses @name, some ?name, some :name and so on, but there is no much differences about queries, one to other. So, my idea is to make some configuration option, standard placeholder (named value syntax) and replacement syntax, for example for standard it can be taken DBI/DBD (because of code of Ora2Pg) and replacement can be some database language specific syntax.
What next - imagine that you simply search and replace files under /project by reqursion, so you will look for some (specific to database language driver) call to, for example PHP PDO query, exec or some other method. You can label that database query calls with some decoration, for example, with some comment in project source files, before and after (to be enclosed between them) comments. After you made such comments in all project files, before and after every call to database with PDO query or exec DML method (for example), you can extract them, including comments, to SQL text file, and to try to convert it with Ora2Pg. After successful conversion, because you keep all decoration comments before and after every query/DML, you can replace them, but now converted to PostgreSQL SQL dialect - it is easy to be done, if --comments are based on some unique hash or UUID, to be able to find every replacement in original file, based on the same --comment before conversion. So, I think that such (simple) task can be easy done, if Ora2Pg have support of keeping (and position in right places, as it do in source code of stored procedures/functions) of named placeholders and standard replacement of them (depend of needed database driver implementation) and keeping of  original --comment between every SQL query/DML, that encloses it, to be able to easy search and replace it, with some easy UNIX method, as diff and patch, based on unique --comment.

**Comment by darold** [comment]
I have already developed a new feature in Ora2Pg that I've called `interactive mode`. The goal is to use Ora2Pg as a simile "daemon" and  to be able to send to it some Oracle or MySQL code as well as application code where SQL code between snippet easily identified. I have tested it for an application code migration using Cold Fusion form and it works pretty well. I have written a client perl script that was able to extract code from the application file, send it to Ora2Pg and get back the result to replace the code in the application file. By this way any body will be able to write is own client for php, java or others and ask Ora2Pg to translate the code.

The work is near to be ready to be included in Ora2Pg main code but I lack time and I want to finalize all pending major issue before.

**Comment by krasandr** [comment]
My idea is very simple and there is no need to do some major rewrite to reach it. I just want to parse some source code of project, for example under /project. Because I want to extract from code MySQL queries and convert them static with Ora2Pg, I have a need to identify them (with unique label/comment) - for example:
--label(comment1)
MySQL query1; MySQL query2; MySQL query3;
--label(end of the same comment1)
--label(comment 2)
MySQL query4;
--label(end of the same comment2)
--label(comment 3)
MySQL query 5;MySQL query 6;
--label(end of the same comment3)
Labels, i.e. comment are unique generated - it can be some hashing function or UUID. At the end, after conversion with Ora2Pg, you end with:
--label(comment1)
PgSQL query1; PgSQL query2; PgSQL query3;
--label(end of the same comment1)
--label(comment 2)
PgSQL query4;
--label(end of the same comment2)
--label(comment 3)
PgSQL query 5;PgSQL query 6;
--label(end of the same comment3)
Based on fact, that labels/comments before conversion with Ora2Pg are the same, it is easy task to search and replace them with converted PostgreSQL queries. By the way, they are real SELECT queries or DML - they are not CREATE VIEW, PROCEDURE, FUNCTION, TRIGGER and so on.
So, my problem is only 1)to be able to use different placeholders (and keep them) for different database drivers - for example ?name, :name, @name and so on (based on replacement configure file option for standard equivalent placeholder form syntax, maybe standartd must be DBI/DBD format for it). 2)to keep labels/comments, that easy identify position of conversion string(s).
By the way, I have a trouble with type Query and utf8 encoding - input file with queries is with utf8 readable cyrilic, but output file looks like some write in Perl (unreadable) code with pressed shift key.
 (joke). I am not able to follow yours idea about interactive mode without example, but I think, that type Query is enough - it will contain usually only  selects and DML, the key feature is to be able with named placeholders postional variables in queries and encloased labels/comments keeping, to be able to search and replace queries strings (with custom regex) in project source files after conversion with Ora2Pg.

**Comment by darold** [comment]
Well you can already put your MySQL queries in a file `input.sql` as follow:
```
--label(comment1)
MySQL query1;
MySQL query2;
MySQL query3;
--label(end of the same comment1)
--label(comment 2)
MySQL query4;
--label(end of the same comment2)
--label(comment 3)
MySQL query 5;
MySQL query 6;
--label(end of the same comment3)
```

then use ora2pg to convert the queries:
```
ora2pg -c config/ora2pg.conf -t QUERY -i input.sql
```
Everything will be translated into output file `output.sql`.

You can produce the input.sql file with a script that read your application file and read the output.sql file to reintegrate the translated SQL queries in your application file.

**Comment by krasandr** [comment]
There is problem with converting type QUERY from input file - input file is in UTF-8 encoding with Cyrillic texts in some strings or comments, but output file is always with unreadable letters in all Cyrillic texts and comments. When I convert the same data from MySQL database, all texts and comments are readable, problem is only when I try to convert the same from input file - is it something that I miss, or it is a bug? Do you want to send to you some input file to compare Cyrillic texts and comments before and after conversion?

**Comment by krasandr** [comment]
I make some test with open file and write to another file with this example (from links):

https://perlmaven.com/open-and-read-from-files
https://perlmaven.com/writing-to-files-with-perl

With suggestion of last link:
...
Non-latin character?
In case you need to handle characters that are not in the ASCII table, you'll probably want to save them as UTF-8. To do that you need to tell Perl, you are opening the file with UTF-8 encoding.

open(my $fh, '>:encoding(UTF-8)', $filename)
  or die "Could not open file '$filename'";
...

My test perl script is:

use strict;
use warnings;

my $filename1 = 'pg_tteesstt6.sql';
open(my $fh1, '>:encoding(UTF-8)', $filename1)
  or die "Could not open file '$filename1'";
    lock($fh1);

my $filename2 = 'tteesstt6.sql';
if (open(my $fh2, '<:encoding(UTF-8)', $filename2)) {
  while (my $row = <$fh2>) {
    chomp $row;
    print $fh1 "$row\n";
  }
} else {
  warn "Could not open file '$filename2' $!";
}
    close $fh1;

And It works - Cyrillic texts and comments are O.K. 
But with Ora2Pg, it don't work - all Cyrillic texts and comments are broken and unreadable.

**Comment by krasandr** [comment]
Seems my problem is the same as "Characters modified when all things seem to indicate everything is UTF-8 #227", but I have not success. I try with and without CLIENT ENCODING, with and without BINMODE, but without success. My input file have utf8 Cyrillic texts, my output file have all unreadable cyrillic. Ora2Pg is always latest git revision version.

[root@krasiyan test130]# ora2pg -t SHOW_ENCODING
Ora2Pg version: 18.2
Trying to connect to database: dbi:mysql:host=...
Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
Set default encoding to 'utf8' and collate to 'utf8_general_ci'
Current encoding settings that will be used by Ora2Pg:
	MySQL database and client encoding: utf8
	MySQL collation encoding: utf8_general_ci
	PostgreSQL CLIENT_ENCODING UTF8
	Perl output encoding 'utf8'
Showing current MySQL encoding and possible PostgreSQL client encoding:
	MySQL database and client encoding: latin1
	MySQL collation encoding: utf8
	PostgreSQL CLIENT_ENCODING: latin1
MySQL SQL mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

**Comment by darold** [comment]
I have already fixed this issue in my current work on a major change in Ora2Pg, it need to be terminated before being able to push the commit. I hope later today.

**Comment by krasandr** [comment]
Is this will be possible, solution that you have, to keep --comment lines (currently in Cyrillic alphabet), because right now they are ignored (but not always) and don't exists (usually) in converted with -t QUERY file? For me, they are important, to be able to make right positioning of file to search/replace it with regex.

**Comment by darold** [comment]
The problem comes from the fact that the QUERY action of Ora2Pg only works on queries where (SELECT|INSERT|UPDATE|DELETE) is found. In the example you've sent to me, statement like DROP or SET are not taken in account and not returned in the output. This is why you are loosing some comment and of course some statement in the output. I will see what can be done.

**Comment by krasandr** [comment]
Yes, they are actually before CREATE/DROP TEMPORARY TABLE, but you know, sometimes it is very hard to write complex query, especially with not as SQL-rich database as PostgreSQL, without using temp tables.

**Comment by krasandr** [comment]
Maybe right solution is to search with regex for "CREATE TEMP|TEMPORARY" and "DROP TEMP|TEMPORARY", but not for CREATE or DROP without next word of "TEMP|TEMPORARY"?

**Comment by darold** [comment]
I don't think so, my idea is to keep the unused parts of the original file and include them at the right place in the output file. This will handle all the cases. Otherwise the interactive mode already proceed like that, it return the original non relevant content ans only translate parts enclosed between given tag.

**Comment by krasandr** [comment]
You are right, about including all parts, that are not translated - that
will solve most of problems. But is it will be too hard to translate temp
tables also? They don't need of any different manipulation, than you
already have.

На 8.12.2017 г. 5:52 сл.об. "Gilles Darold" <notifications@github.com>
написа:

**Comment by krasandr** [comment]
Good news is that Cyrillic text is O.K., but there is some problems. 
DROP TEMPORARY TABLE IF EXISTS is not converted, nor included in output file untouched, also comment above it is missing. Also, if configuration option BINMODE utf8 is active, output is:

[root@krasiyan test130]# ora2pg -d -m -t QUERY -i tteesstt6.sql -o pg2_tteesstt94.sql 
FATAL: can't use open layer :encoding(utf8)

If I comment BINMODE utf8 in configuration file, output and conversion is O.K.

**Comment by krasandr** [comment]
If there will be support for DROP TEMPORARY TABLE IF EXISTS tablename (without conversion, so it will be untouched), is that will mean, that comment line --comment before it, will be included as well?

**Comment by krasandr** [comment]
By the way, there is something strange at performance point of view - if there is in input type QUERY file some really long blank lines (with spaces and/or tabs, but very long lines), speed of conversion is very slow, only for these queries. If I remove that long blank lines, conversion of queries is very fast (or after long lines are finished, in the last part of input file, conversion speed is very fast also - so, seems speed depends very much from such long lines, as if I completely remove them before conversion, speed of conversion is very fast. Is it right solution to have some kind of checks, that ignores such long blank lines (and blank characters also at the end of line, after last significant character, different than space and tab)?

**Comment by darold** [comment]
Commit f3d2e94 change the behavior of the QUERY export, all untranslated queries will be kept and reported in the output file with all related comments.

About performances issue, yes the size of the file to translate matter.

**Comment by krasandr** [comment]
After last commit, I see in output of type QUERY many blocks like:
SET @N := 0 (i.e. all of SETs is not converted)
SUM(t.CashQuantity)+ CASE WHEN OrStoreID!=@StoreID THEN 0 ELSE  SUM(t.Quantity) END  AS CashQuantity, (But only one occurrence, maybe it is because of some SET conversion missing above).

Before last commit, SET was converted, by yours commit from previously night - could it can be converted again, all other things seems right - DROP of temp tables and --comment before them is also O.K.

**Comment by darold** [comment]
Can you send me an example, the file with cyrillic doesn't have such statement.

**Comment by darold** [comment]
Forget my assertion I found a SET statement in your file.

**Comment by darold** [comment]
I use the following command:
```
ora2pg -m -c test-scripts/ora2pg.conf -t QUERY -i test-scripts/test_cyrillic.sql -o output.sql
```
and it seems to works well. Here, the SET statement are well translated and can be found in the output.sql file.
```
-- cyrillic comment
SET VatDescription = COALESCE((SELECT
    gs.GlobalSettingValue
  FROM global_settings gs
  WHERE gs.GlobalSettingID = 138), 'cyrillic string');
```
Perhaps you forgot to add the `-m` command line option?

**Comment by krasandr** [comment]
No, I will send to you now privately complete example. I have troubles with very simple assignments like:
SET @n := 0
Strange, but more complex example is O.K.:
SET dName = (SELECT
    CONCAT_WS(' ', d.DoctorFirstName, d.DoctorSecondName, d.DoctorLastName)
  FROM doctors d
  WHERE d.DoctorID = DoctorID);

**Comment by krasandr** [comment]
My mistake, simple examples like SET @n := 0 was not converted before last commit - I simply did't see them, because they was not converted and they was not in the output file, untranslated also.

**Comment by krasandr** [comment]
I just see MySQL function LOCATE - there is no PostgreSQL direct equivalent, other than something like:
locate(to_find,str,pos)=strpos(substr(str,pos),to_find)
I will make more testing, to be sure that there is no other big differences.

**Comment by krasandr** [comment]
I think that there is no need to try convert such SET statements like SET @n := 0, because PostgreSQL don't support them in plain SQL, only in stored procedures/functions (yet), so let's they stay untouched (for now). Sorry, I was completely wrong.

My question (in the topic name) was about, when you have some queries extracted from application code or saved predefined in database table (to be able to execute them later with some user-specified parameters, given from interface), how to ease such migration. Right now, most of problems are committed to Ora2Pg code, thank you (problem with utf8 and non-latin characters, problem with comments surrounded untranslated query, problem with  untranslated queries to be kept, especially when they are the same between MySQL and PostgreSQL), but in my opinion, there is one more problem - how to distinguish, that some name in query must be specified by user (so it is not a column name, it is value, that must be given by user), so when you look for query in output file after migration, to be able to give such query, supply to it needed value and execute. Right now, different languages and different database drivers as DBI/DBD, PDO, JDBC and so on, have a different idea, in what form this user supplied value must be - for example, ?name , @name, :name, $name and so on. Let's just you decide what is the most proper form for it, from yours or Perl point of view, and when convert MySQL queries with -t QUERY, simply replace them with a proper form, because if you just remove (as a @variables in stored procedures/functions/triggers) @ from it's name, it will be not possible when you look at translated query, to realize, what is a parameter and where you must put a user-specified value, to be able to execute query.

**Comment by krasandr** [comment]
May I am wrong, but for example:

DROP TEMPORARY TABLE IF EXISTS t_exp;
CREATE TEMPORARY TABLE t_exp
SELECT
  sl.SLotID,
  sl.SLotNum,
  sl.SLotExpireDate,
  sl.ProductID
FROM s_lots sl
WHERE sl.SLotExpireDate BETWEEN DATE(@fromDate) AND DATE(@toDate);

If you just remove @ from parameters, I think that it will be not so easy to understand, where are parameters and which value to which placeholder to bind:

DROP TEMPORARY TABLE IF EXISTS t_exp;
CREATE TEMPORARY TABLE t_exp AS
SELECT
  sl.SLotID,
  sl.SLotNum,
  sl.SLotExpireDate,
  sl.ProductID
FROM s_lots sl
WHERE sl.SLotExpireDate BETWEEN DATE(fromDate) AND DATE(toDate);

Let's assume, that you want to read query from database table (open/fetch a text record, saved in column, search for named placeholders - needed variables), PREPARE it (in user code in application or in database editor - bind user supplied variables (if there is such in query) to right places of placeholders ?name :name $name @name etc...), and EXECUTE query and fetch result.

**Comment by darold** [comment]
Yes I think like you that `@varname` might not be translated in QUERY export mode, this is the simplest, I will remove it.
More generally Ora2Pg doesn't have any intelligence about the application, it only applies translation rules. Saying that there is a way to instruct Ora2Pg that some part must not be translated and taken as constant string. For example to not process `@varname`, add the following to your ora2pg.conf file:
```
STRING_CONSTANT_REGEXP          @[a-zA-Z0-9_]+
```
and if you want to handle all cases: `@name, :name, $name` add the following for QUERY export:
```
STRING_CONSTANT_REGEXP          [@\$:][a-zA-Z0-9_]+
```
You can use any valid Perl regular expression in  STRING_CONSTANT_REGEXP directive. Several regexp can be given in a semi-comma separated list.

**Comment by krasandr** [comment]
I just commented yours commit for SET assignments (maybe for CREATE TABLE also is not needed anymore, after you support keeping unconverted queries in output file in QUERY mode):

# Translate call to CREATE TABLE ... SELECT
$str =~ s/(CREATE(?:\s+TEMPORARY)?\s+TABLE\s+[^\s]+)(\s+SELECT)/$1 AS $2/igs;

# Remove @ from variables and rewrite SET assignement in QUERY mode
#if ($class->{type} eq 'QUERY') {
#          $str =~ s/\@([^\s]+)\b/$1/gs;
#          $str =~ s/:=/=/gs;
#}

Seems solution that you suggest, is what I need, but how I can limit STRING_CONSTANT_REGEXP only for type QUERY? Because, for type PROCEDURE,FUNCTION and TRIGGER @variables must be replaced. Maybe the simple way is to have additional configuration files and to pass -c flag for it?

**Comment by darold** [comment]
You have to use a modified copy of the ora2pg.conf file dedicated to the QUERY exporentt and use it in the `-c` command line argument.

**Comment by krasandr** [comment]
I think, with STRING_CONSTANT_REGEXP with many values with semicolon, it will be easy to convert QUERY, because for each predefined and stored in database query, there is a list with variables names, so if I want to kept them, I will supply list with names of placeholders. I will look for any other problems, but I think, that this last objective will close this topic, with some very small problems like MySQL LOCATE function, for example:

LOCATE(F_ArtGetOCellColumnValue(@OCellDevelopmentColumn, o.IvfOCellDevID), @OCellBadValues)

with something like locate(to_find,str,pos)=strpos(substr(str,pos),to_find)

**Comment by krasandr** [comment]
If I understand you right , is it now possible (with commit that converts @variables and SET assignments in type QUERY) to tell Ora2Pg to make:

1)First, don't converts variables that are in STRING_CONSTANT_REGEXP - for example @name1;@name2;@name3 (by default, none)
2)Next, convert all other @variables (that match all strings, beginning with @, for example @[a-zA-Z0-9_]+

In such case, it will be possible in type QUERY, to convert only these variables, that are needed, based on the exclusion list from point 1), because it is executed before point 2)

If this is so, current situation is very good, so there is no need to revert @variable - maybe, a better solution will be only to be able to tell in Ora2Pg configuration file (or document how into it), how to convert (by default) all @variables or none @variables, and after that, based on STRING_CONSTANT_REGEXP, to make some fine tuning (like in network access lists ACLs with permit/deny from all), what to exactly exclude or exactly permit from/to conversion by config file?

**Comment by krasandr** [comment]
My question is, for example, in the bottom of commit bd3f5f3 there is regex to search for "@":
# Remove @ from variables and rewrite SET assignement in QUERY mode
 +	if ($class->{type} eq 'QUERY') {
 +		$str =~ s/\@([^\s]+)\b/$1/gs;
 +		$str =~ s/:=/=/gs;
 +	}
But, if (for general purpose) placeholders for assignments may looks like ?name, :name, $name, not only @name, how you can configure STRING_CONSTANT_REGEXP (is it will override this definition)?
And also, if you want to convert some (or all) variable placeholders, except what are defined via regexp in STRING_CONSTANT_REGEXP?

**Comment by darold** [comment]
You can configure STRING_CONSTANT_REGEXP with: `[@\?:\$][a-zA-Z0-9_]`

Actually when you set STRING_CONSTANT_REGEXP any string that match the given regexp will be first replaced with the placeholder; `?TEXTVALUEN?` the the statement will be processed. Once it is done, the original value is restored instead of the placeholder.

If you want to convert some variable placeholders, except what are defined via regexp in STRING_CONSTANT_REGEXP, at this time you can not do it. In future version it will be possible to call a custom function written by the user to be able to pre / post process the statement before or after the translation by Ora2Pg.

**Comment by krasandr** [comment]
After yours last commits, conversion of type QUERY is very fast, on the same file that I send to you privately. But, I see
  GROUP_CONCAT(t.ConcatSInDetails) AS ConcatSInDetails,
  GROUP_CONCAT(t.ConcatLots) AS ConcatLots,
in converted file, maybe your transation of GROUP_CONCAT don't cover type QUERY?
Also, if you have time, can you add also translation of MySQL LOCATE() function? There is no direct PostgreSQL equivalent, but (manually tested) it works as
locate(to_find,str,pos)=strpos(substr(str,pos),to_find)
but must be tested (there is example in file) with nested parenthesis on it.

**Comment by darold** [comment]
Commit 34e4119 fixes those remaining issue.

**Comment by krasandr** [comment]
It works, both of yours fixes, thank you. I am closing this topic, everything is O.K. right now.
