### ISSUE TITLE
search_path doesn't seem to be set in sub _dump_to_pg

### ISSUE THREAD

**Issue by pgnickb** [darold/ora2pg#599]
Using last ora2pg on Windows with ActiveState Perl (v5.24.2 built for MSWin32-x64-multi-thread).
I'm migrating only data. Tables and indexes are managed manually to avoid complications related to tablespaces.

Have following lines in the config-file:
```
...
TYPE INSERT
PG_SCHEMA myschema
...
```

Target tables are in `myschema`. When running ora2pg I get an error:
```
BD::Pg::st execute failed: ERROR:  relation "mytable" does not exist
LINE 1: INSERT INTO mytable(col1,col2,col3) V...
```

After `alter database mydb set search_path=myschema;` everything works.

as per title:
search_path doesn't seem to be set in `sub _dump_to_pg` in `ora2pg.pm`

If there is any additional information required to investigate this, please let me know.

**Comment by SebAlbert** [comment]
Are you on the latest ora2pg version? I also once had this issue (#161)

**Comment by pgnickb** [comment]
Ora2pg.pm says:
```
$VERSION = '18.1';
```

**Comment by SebAlbert** [comment]
I see, the code has changed quite a bit since the days when I encountered the same problem.
Do you might trying the configuration line
`PG_INITIAL_COMMAND SET search_path TO myschema`

However, that might also be only another quick fix, but may have less incompatibilities than yours (setting the db's default search path).

**Comment by pgnickb** [comment]
I've just rebuilt with the most current version (18.2) and it indeed works now. I guess I wasn't building from github sources then. Maybe some outdated link on the ora2pg.darold.net.

Thanks @SebAlbert
