### ISSUE TITLE
EXPORT_SCHEMA bug

### ISSUE THREAD

**Issue by jacks33** [darold/ora2pg#602]
Hi,

I noticed a few bug when changing the setting  EXPORT_SCHEMA  from 0 to 1 :
First changes on my configuration file were:
-EXPORT_SCHEMA  0
+EXPORT_SCHEMA  1
-REORDERING_COLUMNS     0
+REORDERING_COLUMNS     1
-DISABLE_SEQUENCE       1
+DISABLE_SEQUENCE       0
-DISABLE_TRIGGERS       1
+DISABLE_TRIGGERS       0

1 - on scripts report/columns.txt and  report/tables.txt, I have the same issues:

 schema name is written twice rather than once or is not written at all:

In "Showing table information..." section, schema is written twice
-[2] TABLE **ABILADM**\.NUMBIL_NUMERIQUE (owner: ABILADM, 111 rows)
-ID_LIASSE : CHAR(25) => char(25)
-NOM_ORIGINE : CHAR(255) => char(255)
-FICHIER_PDF : BLOB(4000) => bytea
-DATE_ENVOI : DATE(7) => timestamp
-ACTION : NUMBER(1) => smallint
-CODE_ERREUR : CHAR(5) => char(5)
+[2] TABLE **ABILADM.ABILADM**\.NUMBIL_NUMERIQUE (owner: ABILADM, 111 rows)
+DATE_ENVOI : DATE(7) => timestamp - typalign: 8
+FICHIER_PDF : BLOB(4000) => bytea - typalign: 4
+ACTION : NUMBER(1) => smallint - typalign: 2
+CODE_ERREUR : CHAR(5) => char(5) - typalign: 0
+ID_LIASSE : CHAR(25) => char(25) - typalign: 0
+NOM_ORIGINE : CHAR(255) => char(255) - typalign: 0

In "Top 10 of largest tables" section, schema is not written anymore this leads to empty estimate of row numbers 
-[1] TABLE **ABILADM**\.CERFA: 128 MB (268 rows)
-[2] TABLE **ABILADM**\.TRANSMISSION: 4 MB (46 rows)
-[3] TABLE **ABILADM**\.NUMBIL_NUMERIQUE: 4 MB (111 rows)
-[4] TABLE **ABILADM**\.PARAM_PART: 0 MB (1 rows)
+[1] TABLE .CERFA: 128 MB ( rows)
+[2] TABLE .TRANSMISSION: 4 MB ( rows)
+[3] TABLE .NUMBIL_NUMERIQUE: 4 MB ( rows)
+[4] TABLE .PARAM_PART: 0 MB ( rows)

Note  : section "Top 10 of tables sorted by number of row" is OK.

2 - Note:  file reports.reports.html seems ok.

3 - On file synonym.sql, for all objects:

-CREATE VIEW **abilweb**.numbil_numerique AS SELECT * FROM **abiladm**.numbil_numerique;
+CREATE VIEW **abilweb.abilweb**.numbil_numerique AS SELECT * FROM **abiladm**.numbil_numerique;
-ALTER VIEW **abilweb**.numbil_numerique OWNER TO bilanadm;
+ALTER VIEW **abilweb.abilweb**.numbil_numerique OWNER TO bilanadm;
-GRANT ALL ON **abilweb**.numbil_numerique TO abilweb;
+GRANT ALL ON **abilweb.abilweb**.numbil_numerique TO abilweb;

I see no bugs in the rest of files.

Thank you

**Comment by darold** [comment]
Please use latest development code this might have been solved.
