### ISSUE TITLE
timestamp with time zone TZR

### ISSUE THREAD

**Issue by ransom85** [darold/ora2pg#604]
I can export time stamp with time with time zone region information (TZR) instead TZH and TZM?
Example - 2012-05-03 10:32:34.022540 Europe/Prague instead 2012-05-03 10:32:34.022540 +02:00

**Comment by darold** [comment]
No you can not, we need a fixed way to get timezone but this is not a problem as PostgreSQL will never report you a timestamp with a litteral timezome 'Europe/Prague'.
```
INSERT INTO test_tz VALUES ('2016-08-12 10:22:31 Europe/Prague');
SELECT  * FROM test_tz;
         ts_tz          
------------------------
 2016-08-12 10:22:31+02
```

The best you can have is a abbreviated form:
```
gilles=# set datestyle to German;
SET
gilles=# select * from test_tz;
          ts_tz           
--------------------------
 12.08.2016 10:22:31 CEST
```
but this `+02` can correspond to lot of other region.
