### ISSUE TITLE
Connect to Postgre Server

### ISSUE THREAD

**Issue by mohammed-a-wadod** [darold/ora2pg#608]
Hey, 
I have installed oracle DB server 11g R2 and PostgreSQL 10.1-2, and i set all configuration in the right way, 
and i can export tables from Oracle in to output file. 
Now i want Ora2Pg to create schema and create structure  in PostgreSQL server, i edit PG_DSN , PG_USER, PG_PWD and after i run 

`ora2pg -c config\ora2pg.conf --pg_dsn "dbi:Pg:dbname=u_reports;host=localhost;port=5432" --pg_user postgres --pg_pwd pwd`

and then check Postgre server nothing happened, 
can you help me ?

**Comment by darold** [comment]
Hi,

You can not import DML directly into PostgreSQL. Ora2Pg may have generated SQL output files that you must load into PostgreSQL using psql by yourself. The default output file is called output.sql and stay in the current directory.

The PG_DSN , PG_USER, PG_PWD  are only used with COPY, INSERT, LOAD, TEST actions.

Regards,
