### ISSUE TITLE
Strange transformation - broken string, unwanted comment

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#610]
Oracle:
<pre>
        IF mPruchodSipo = 1 THEN
          mSQLSipoPred := ' SELECT  MT.ID_PREDPIS ,MT.ID_NAJVZTAH, MT.ID_APROVOZNA  , MT.DATUZA '  ;
        END IF;
        IF mPruchodSipo = 2 THEN
          mSQLSipoPred := ' SELECT /*+RULE */ MT.SPOJOVE_CISLO , MT.KOD_SIPOPOPL , MT.POL_CASTKA , MT.ID_NAJSIPOCIS , MT.ID_CSIPOPOPL , MT.NAJMENO , MT.ID_PREDPIS , MT.ZIV , MT.ID_NAJVZTAH , MT.ID_APROVOZNA , MT.OBDOBI_DO , MT.VYSTUP , MT.ID_POL_PRED , MT.DATUZA ' ;
        END IF;
        IF mPruchodSipo = 1 THEN
           mSQLSipoPred := mSQLSipoPred || ' FROM V_POLPRED_SIPO MT ' ;
        END IF;
        IF mPruchodSipo = 2 THEN
           mSQLSipoPred := mSQLSipoPred || ' FROM V_POLPRED_SIPO MT , NAJDATSPLT A1 ' ;
        END IF;
</pre>

PostgreSQL:
<pre>
        IF mPruchodSipo = 1 THEN
          mSQLSipoPred := ' SELECT  MT.ID_PREDPIS ,MT.ID_NAJVZTAH, MT.ID_APROVOZNA  , MT.DATUZA ';
        END IF;
        IF mPruchodSipo = 2 THEN
          ---mSQLSipoPred := ' SELECT /*+RULE */
 MT.SPOJOVE_CISLO , MT.KOD_SIPOPOPL , MT.POL_CASTKA , MT.ID_NAJSIPOCIS , MT.ID_CSIPOPOPL , MT.NAJMENO , MT.ID_PREDPIS , MT.ZIV , MT.ID_NAJVZTAH , MT.ID_APROVOZNA , MT.OBDOBI_DO , MT.VYSTUP , MT.ID_POL_PRED , MT.DATUZA ' ;
          mSQLSipoPred := ' SELECT  MT.SPOJOVE_CISLO , MT.KOD_SIPOPOPL , MT.POL_CASTKA , MT.ID_NAJSIPOCIS , MT.ID_CSIPOPOPL , MT.NAJMENO , MT.ID_PREDPIS , MT.ZIV , MT.ID_NAJVZTAH , MT.ID_APROVOZNA , MT.OBDOBI_DO , MT.VYSTUP , MT.ID_POL_PRED , MT.DATUZA ';
        END IF;
        IF mPruchodSipo = 1 THEN
           mSQLSipoPred := mSQLSipoPred || ' FROM V_POLPRED_SIPO MT ';
        END IF;
        IF mPruchodSipo = 2 THEN
           mSQLSipoPred := mSQLSipoPred || ' FROM V_POLPRED_SIPO MT , NAJDATSPLT A1 ';
        END IF;
</pre>

**Comment by darold** [comment]
This is solved by the same commits as issue #609

**Comment by okbob** [comment]
It is fixed. Thank you
