### ISSUE TITLE
Can't connect to Oracle dataBase

### ISSUE THREAD

**Issue by smunozeyquem** [darold/ora2pg#611]
I am trying to connect to my Oracle db, but I am unable to do so. I'm using a VPN and I can connect using slqplus but with ora2pg I can't. Another important thing I don't have a SID only the ServiceName. and I'm using the ServiceName instead of the SID.

Well this is my configuration in the ora2pg.conf file:

ORACLE_DSN	dbi:Oracle:host=MYIP;sid=MyServiceName;port=1521
ORACLE_USER	MyUser
ORACLE_PWD	MyPassWord

Also when I run the ora2pg It doesn't do anything and after a while I press the ctr+c it give me the following message

C:\ora2pg>ora2pg -o ora2pg.conf      /*("here I run the program, and after a while I press ctr+c")*/
Received terminating signal (INT).
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=MYIP)(PORT=1521))(CONNECT_DATA=(SID=MYSERVICENAME))) at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 8804.
Received terminating signal (INT).

any help pls!!d

PD: I'm using windows 10 and sorry for my poor english

**Comment by darold** [comment]
Hi,

Have you tried the following?
```
ORACLE_DSN	dbi:Oracle://MYIP:1521/MyServiceName
```

Have a look to `man DBD::Oracle` in "DBI CLASS METHODS" connect section for more information.

Regards,

**Comment by smunozeyquem** [comment]
Hi thanks for the quick response, I tried ORACLE_DNS as you told me, and other methods that are in the "DBI CLASS METHODS"

and i got the following error 

C:\ora2pg>ora2pg -o ora2pg.conf (after I run the command I wait for one hour, so  I press "CTR+C" and got the following message)
Received terminating signal (INT).
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle //MYIP:1521/MYSERVICENAME at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 9497.
¿Desea terminar el trabajo por lotes (S/N)? s

C:\ora2pg>

**Comment by darold** [comment]
What is the result of command: `ora2pg -o ora2pg.conf -t SHOW_VERSION`?

You must have a result in the minute otherwise there is a  connection problem.
