### ISSUE TITLE
Double quotes "" in RETURN clause from MySQL function is not accepted by PostgreSQL

### ISSUE THREAD

**Issue by krasandr** [darold/ora2pg#612]
PostgreSQL don't permit "" in RETURN, but MySQL usually mix single and double quotes and permit both of them:
```
| f_ivf_uin_format | STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION | CREATE DEFINER=`root`@`%` FUNCTION `f_ivf_uin_format`(cellType TINYINT(4), cellUIN VARCHAR(50)) RETURNS varchar(80) CHARSET utf8
BEGIN

  IF (cellType = 1)
  THEN
    RETURN if(length(cellUIN) < 7, concat('M', lpad(cellUIN, 4, '0')), cellUIN);
  END IF;

  IF (cellType = 2)
  THEN
    RETURN if(length(cellUIN) < 7, concat('F', lpad(cellUIN, 4, '0')), cellUIN);
  END IF;

    IF (cellType = 3)
  THEN
    RETURN if(length(cellUIN) < 7, concat('M', lpad(cellUIN, 4, '0')), cellUIN);
  END IF;

  IF (cellType = 4)
  THEN
    RETURN if(length(cellUIN) < 7, concat('M', lpad(cellUIN, 4, '0')), cellUIN);
  END IF;

  RETURN "";
END | utf8                 | utf8_general_ci      | latin1_swedish_ci  |
```
If I replace double quotes with single, function is created in PostgreSQL, but I am not sure, what is a right solution, maybe it is good to convert double quotes to single, as is accepted by PostgreSQL?

**Comment by darold** [comment]
Double quote in PostgreSQL can only be used to enclose object name, text strings, even empty, must use single quote. I do not understand why it is allowed in MySQL and if this is reserved to empty string? I guess not, I need to check that.

**Comment by darold** [comment]
Found about strings literal:
```
'a string'
"another string"
```
Commit 335408c force replacement of double quote into single quote.

**Comment by krasandr** [comment]
Thank you, I am closing this topic. I don't know why MySQL makes so much exceptions from standard and permit so much differences.
