### ISSUE TITLE
Error on export data

### ISSUE THREAD

**Issue by chmanu** [darold/ora2pg#613]
Hello Gilles,

When I try to export data, I encountered the following error : 

DBD::Oracle::db::ora_lob_read: locator is not of type OCILobLocatorPtr at /usr/local/share/perl5/Ora2Pg.pm line 9991.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle ...

And ora2pg stops.

If I exclude the last table, it works.
Here is the definition of this table (the column names have been modified for the report) : 

select TABLE_NAME, COLUMN_NAME, DATA_TYPE,  DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE
from all_tab_columns where table_name like 'SITE_JRN' ;

SITE_JRN	ID	NUMBER	22	19	0	N
SITE_JRN	OLV	NUMBER	22	10	0	N
SITE_JRN	TYPEE	VARCHAR2	255			N
SITE_JRN	MODIF	CLOB	4000			Y
SITE_JRN	MNEMO	VARCHAR2	255			N
SITE_JRN	DATEG	TIMESTAMP(3)	11		3	N
SITE_JRN	CONTFK	NUMBER	22	19	0	Y
SITE_JRN	GSLFK	NUMBER	22	19	0	Y

I use ora2pg 18.2.

Regards,
M. Pavy

**Comment by darold** [comment]
Hello Manuel,

Have you tried with NO_LOB_LOCATOR set to 1? Do you have the same error?

Regards,

**Comment by chmanu** [comment]
It works, Thanks !
Sorry for the disturbance.

**Comment by darold** [comment]
Don't be sorry, there is around 160 configuration directives in ora2pg.conf so I'm not expecting that users know all of them. Sometime I use to forget some of them too :-)
