### ISSUE TITLE
ALTER SEQUENCE IF EXISTS seq_orign_loan_status RESTART WITH

### ISSUE THREAD

**Issue by jinxiaoxin** [darold/ora2pg#615]
how to solve?
psql:/etc/ora2pg/lender_table.sql:2797832: ERROR:  syntax error at or near "EXISTS"
LINE 1: ALTER SEQUENCE IF EXISTS seq_orign_loan_status RESTART WITH ...

**Comment by darold** [comment]
You can use a more recent version of PostgreSQL, at least >= 9.2. The other solution is to disable PG_SUPPORTS_IFEXISTS in your ora2pg.conf file. I recommend the first solution if possible.

**Comment by jinxiaoxin** [comment]
thx
