### ISSUE TITLE
Query file covnert error

### ISSUE THREAD

**Issue by mohammed-a-wadod** [darold/ora2pg#616]
Dear sir, 
I have error converting which when i pass query file to ora2pg to convert queries which contain oracle (**CONNECT BY** ) and outer join **(+)**  it doesn't convert it, and there is other query which contain oracle (**CONNECT BY** ) then it convert it in wrong way.
please find the attached files for queries examples after and before converting.

[After.txt](https://github.com/darold/ora2pg/files/1600807/After.txt)
[before.txt](https://github.com/darold/ora2pg/files/1600809/before.txt)

**Comment by darold** [comment]
Commit cf1d20b fixes the outer join replacement in query like:
```
SELECT *
FROM ROUTE_PLAN_IMPORT_VW VW, VISIT_FREQUENCIES FRIDAY
WHERE UPPER(trim(VW.FRIDAY))= UPPER(trim(FRIDAY.NAME(+)));
```

**Comment by darold** [comment]
Commit 69c0664 might fix the CONNECT BY issue.

**Comment by darold** [comment]
Commit e6fa246 fixes the first CONNECT BY issue when the query contain an UNION.

Thanks for the report and sorry for the response delay.
