### ISSUE TITLE
Missing PERFORM in cross-package call

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#617]
It looks like an Oracle package procedure called from another package does not always get its PERFORM in the translated code. Here is a small extract, I will send you the whole separately:

Oracle:--------------------------------------------------------------------------------
PROCEDURE local_raise_error(p_sgbd_code varchar2, p_errmsg varchar2) is
BEGIN
    -- Appel qui loggue en TRX autonome lors de la génération de l'erreur (niveau le plus bas)
    pck_bdd.app_raise_error(p_sgbd_code, p_errmsg, 'PCK_GPAR');
END;

PostgreSQL/ora2pg:--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pck_gpar.local_raise_error (p_sgbd_code text, p_errmsg text) RETURNS VOID AS $body$
BEGIN
    -- Appel qui loggue en TRX autonome lors de la génération de l'erreur (niveau le plus bas)
    pck_bdd.app_raise_error(p_sgbd_code, p_errmsg, 'PCK_GPAR');
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;

**Comment by darold** [comment]
This should not happen if all packages functions are known by Ora2Pg. Here I think the PCK_BDD package is not in the schema that Ora2Pg is exporting from or that your are translating package PCK_GPAR' from a file, so package PCK_BDD can not be not known.

**Comment by edelanoe** [comment]
This issue has been solved in the master dev code since my last update. I can close, thanks.
