### ISSUE TITLE
Oracle Spatial -> PostGIS, spatial functions migration support

### ISSUE THREAD

**Issue by vpicavet** [darold/ora2pg#62]
While Oracle Spatial and PostGIS are supposed to follow OGC SFS, and ISO specifications ( http://en.wikipedia.org/wiki/Simple_Features ), and therefore be interoperable, the reality is far from it.
- Oracle does not support SQL/MM naming scheme ( ST_ prefix)
- some functions are not standard-compliant in Oracle
- some parts are undefined in the norm
- additions have been done on both sides, not part of the standard

Meanwhile, support for a core set of function migration could be great to ease migration, e.g. of views and stored procedures.

Among them, distance computation, intersection, containment, buffer (Oracle users, complete this list).

**Comment by MarekZajicek** [comment]
Is it possible to replace SDO_JOIN by any Postgre/PostGIS statement?
