### ISSUE TITLE
REPLACE_QUERY for a view

### ISSUE THREAD

**Issue by lielar** [darold/ora2pg#620]
Hi Darold

I'm looking to do a data migration between postgres and oracle. I have created a view in Oracle by which my table in Postgres will be populated by. I have also included the name of the Oracle View in the ALLOW setting. 

The data is not migrated and seems like Ora2Pg does not select the data from the view. It does recognise the view is there because when I have a non-existing column name in the SELECT statement Ora2Pg stops on error. 

What could I be missing?

I have included the ora2pg.conf settings which I think is relevant. 

`REPLACE_QUERY	       TEAMS[SELECT id,first_name,other_name,other_id FROM ibis.CMS_V]`

So table TEAMS in Postgres should get its data from schema ibis and view CMS_V. The table would have the same name and order of the columns as the SELECT query. 

Any ideas?

**Comment by lielar** [comment]
It complains that an old column name (column of the old oracle table ) doesn't exist. 

`
DBD::Pg::db do failed: ERROR:  column "name_list" of relation "collecting_teams" does not exist at /home/patrick/perl5/lib/perl5/Ora2Pg.pm line 12746.
`

**Comment by lielar** [comment]
Changed the _REPLACE_COLS_ config and appears to move to the next table...

**Comment by pgnickb** [comment]
@lielar have you tried using `view_as_table` parameter?

**Comment by lielar** [comment]
Thanks.
