### ISSUE TITLE
Small fixes for support translation of MySQL @ global variables commit

### ISSUE THREAD

**Issue by krasandr** [darold/ora2pg#621]
In commit message for commit dd50ee0 it is written:
Support translation of MySQL global variables. Session variable @@varname are translated to PostgreSQL GUC variable and global variable @varname are translated to local variable
defined in a DECLARE section. Ora2Pg tries to gather the data type by using intger by
default, varchar if there is a constant string ('...') in the value and a timestamp if
the variable name have the keyword date or time inside.

But it is not very good decision, so it will be better:
1)if variable name have time or datetime, it is ok to be timestamp (as it now works),
but if it have only date (without time) it will be better type to be date, not timestamp
2)if name of variable end with "id" (very common practice), it will be better if type is integer, not string by default as now works.

For example, right now it is:

CREATE OR REPLACE FUNCTION f_artcompletiondate (artID integer) RETURNS date AS $body$
DECLARE
ArtStatusID integer;
freseDate timestamp;
transDate timestamp;
IvfArtID varchar;
stimID varchar;
puncID varchar;
IvfFormID varchar;
puncDate timestamp;
artStartDate timestamp;

BEGIN

But more good choice will be:

CREATE OR REPLACE FUNCTION f_artcompletiondate (artID integer) RETURNS date AS $body$
DECLARE
ArtStatusID integer;
freseDate date;
transDate date;
IvfArtID integer;
stimID integer;
puncID integer;
IvfFormID integer;
puncDate date;
artStartDate date;

BEGIN
...

**Comment by krasandr** [comment]
There is another bug, false conversion - original MySQL part of code:

UPDATE ivf_ocells_developments iod
    INNER JOIN t_zz t
      ON iod.IvfOCellDevID = t.IvfOCellDevID
    SET iod.IvfOStatusID = 1;

But conversion with Ora2Pg produces wrong output:

    UPDATE ivf_ocells_developments iod
    INNER JOIN t_zz t
      ON iod.IvfOCellDevID = t.IvfOCellDevID
    iod.IvfOStatusID := 1;

So, it is not a @variable and also, "=" is converted to ":=" and SET clause is missing.

Also, right syntax of PostgreSQL i s a little different, for example:

UPDATE vehicles_vehicle AS v 
SET price = s.price_per_vehicle
FROM shipments_shipment AS s
WHERE v.shipment_id = s.id

**Comment by krasandr** [comment]
I find another problem with conversion - from MySQL stored procedure:
DROP TEMPORARY TABLE IF EXISTS t_zz;
But PostgreSQL didn't support "TEMPORARY" keyword in DROP IF EXISTS.
To be working, PostgreSQL syntax is:
DROP TABLE IF EXISTS t_zz;

**Comment by krasandr** [comment]
I am closing this issue - important parts from it will be reported later, one by one.

**Comment by krasandr** [comment]
I withdraw my first proposal - it is not so important and actually, it is not a bug, it is design decision.
But second issue in this topic actually is a bug, maybe two bugs - false conversion of variable, that must not be converted - seems UPDATE syntax of MySQL is not recognized (it differs from PostgreSQL syntax).

**Comment by darold** [comment]
Commit 4dfd40d change the behavior in the attempt to set MySQL global variable type. Now variable type will be timestamp if the variable name contains datetime, time if the name contains only time and date for date.

About the second issue on update please provide a sample reproduce.
