### ISSUE TITLE
Tables with 'TIMESTAMP' columns have generated code with 'TIMESTAMP' keyword

### ISSUE THREAD

**Issue by markiech** [darold/ora2pg#623]
For conversion to V10 using SUPPORTS_PARITION, when creating the range partitioned tables, it uses the following syntax:

CREATE TABLE job_sys_p397066 PARTITION OF job
FOR VALUES FROM (TIMESTAMP' 1991-08-26 00:00:00') TO (TIMESTAMP' 2014-09-25 00:00:00');

This results in an error - if you simply omit the 'TIMESTAMP' keyword, the table is created.

Here is TABLE DEF:::

CREATE TABLE job (
        job_id numeric(38) NOT NULL,
        job_type_code numeric(38) NOT NULL,
        start_date_time timestamp,
        end_date_time timestamp,
        retry_count numeric(38),
        job_status_code numeric(38) NOT NULL,
        creation_date_time timestamp NOT NULL,
        last_updated_date_time timestamp,
        request_id varchar(4000) NOT NULL,
        dmz_id varchar(4000) NOT NULL,
        api_type numeric(38) NOT NULL,
        msg_size numeric(22),
        data_source varchar(10),
        businessentity_id numeric,
        http_err_code numeric(22),
        request_inputs text
) PARTITION BY RANGE (creation_date_time) ;

**Comment by darold** [comment]
Commit 27c264c might replace the call to TIMESTAMP into a cast like this:
```
FOR VALUES FROM (' 1991-08-26 00:00:00'::timestamp) TO (' 2014-09-25 00:00:00'::timestamp);
```
