### ISSUE TITLE
possible simple implementation replacement of numtodsinterval 

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#624]
I did new function to orafce `numtodsinterval`. I think, so it can be easy transformed to expression by ora2pg (when orafce is not used)

    numtodsinterval(x, y) ->  (x * ('1' || y)::interval)

**Comment by darold** [comment]
Thanks for the report Pavel, commit 110a11c adds this translation. In next commit 6cbdd5d I have extended the translation to NUMTOYMINTERVAL()  which is the same translation.
