### ISSUE TITLE
Expressions from MySQL return and declare are not evaluated and converted to PgSQL

### ISSUE THREAD

**Issue by krasandr** [darold/ora2pg#625]
ora2pg -d -m -t QUERY -i f_mysql.sql -o f_pgsql.sql

cat f_mysql:
```
CREATE DEFINER=`root`@`%` FUNCTION `test`.`F_GetPatientAgeByExam`(birthDay date, toDay date) RETURNS int(11)

    declare CalculatedAge int default TIMESTAMPDIFF(year, birthDay, toDay);

BEGIN

    SELECT TIMESTAMPDIFF(YEAR, birthDay, toDay);
    RETURN TIMESTAMPDIFF(YEAR, birthDay, toDay);
    
END
```
cat f_pgsql:
```
CREATE DEFINER="root"@"%" FUNCTION "test"."F_GetPatientAgeByExam"(birthDay date, toDay date) RETURNS int(11)

    declare CalculatedAge int default TIMESTAMPDIFF(year, birthDay, toDay)
;

BEGIN

    SELECT extract(year from (toDay)::timestamp) - extract(year from (birthDay)::timestamp);

    RETURN TIMESTAMPDIFF(YEAR, birthDay, toDay)
;

END
```

**Comment by darold** [comment]
Might be fixed in commit 22fc81f.

**Comment by krasandr** [comment]
Hi again, seems this is not converted at all:



CREATE DEFINER = 'root'@'%'

FUNCTION destination.F_GetPatientAgeByExam(birthDay date, toDay date)

  RETURNS int(11)

BEGIN

.

  declare CalculatedAge int default TIMESTAMPDIFF(year, birthDay, toDay);

.

  RETURN IF(CalculatedAge < 0, 0, CalculatedAge);

END

[root@krasiyan bugs]# ora2pg -d -m -t QUERY -i test1m.sql -o test1p.sql
Ora2Pg version: 18.2
Parse queries definition...
Reading input code from file test1m.sql...
Dumping query 1...
Dumping query 2...
Dumping query 3...
[root@krasiyan bugs]# 

root@krasiyan bugs]# 
[root@krasiyan bugs]# cat test1m.sql
CREATE DEFINER = 'root'@'%'

FUNCTION destination.F_GetPatientAgeByExam(birthDay date, toDay date)

  RETURNS int(11)

BEGIN

 

  declare CalculatedAge int default TIMESTAMPDIFF(year, birthDay, toDay);

 

  RETURN IF(CalculatedAge < 0, 0, CalculatedAge);

END

[root@krasiyan bugs]# cat test1p.sql
-- Generated by Ora2Pg, the Oracle database Schema converter, version 18.2
-- Copyright 2000-2017 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:mysql:host=192.168.88.135;database=destination;port=3306

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE DEFINER = 'root'@'%'

FUNCTION destination.F_GetPatientAgeByExam(birthDay date, toDay date)

  RETURNS int(11)

BEGIN

 

  declare CalculatedAge int default TIMESTAMPDIFF(year, birthDay, toDay)
;

  RETURN IF(CalculatedAge < 0, 0, CalculatedAge)
;

END
;
[root@krasiyan bugs]#

**Comment by krasandr** [comment]
It works, thank you:

[root@krasiyan bugs]# cat test.F_GetPatientAgeByExam_f_pgsql2.sql
-- Generated by Ora2Pg, the Oracle database Schema converter, version 18.2
-- Copyright 2000-2017 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:mysql:host=192.168.88.135;database=destination;port=3306

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON



CREATE OR REPLACE FUNCTION "'f_getpatientagebyexam'" (birthDay date, toDay date) RETURNS INT(11)
     AS $body$
DECLARE

CalculatedAge int default extract(year from (toDay)::timestamp) - extract(year from (birthDay)::timestamp);
BEGIN

    SELECT extract(year from (toDay)::timestamp) - extract(year from (birthDay)::timestamp);
    RETURN extract(year from (toDay)::timestamp) - extract(year from (birthDay)::timestamp);
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION "'f_getpatientagebyexam'" (birthDay date, toDay date) FROM PUBLIC;

[root@krasiyan bugs]# 

[root@krasiyan bugs]# cat destination.F_GetPatientAgeByExam_test1p2.sql
-- Generated by Ora2Pg, the Oracle database Schema converter, version 18.2
-- Copyright 2000-2017 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:mysql:host=192.168.88.135;database=destination;port=3306

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON



CREATE OR REPLACE FUNCTION f_getpatientagebyexam (birthDay date, toDay date) RETURNS INT(11)
 AS $body$
DECLARE

CalculatedAge int default extract(year from (toDay)::timestamp) - extract(year from (birthDay)::timestamp);
BEGIN
  
  RETURN CASE WHEN CalculatedAge < 0 THEN 0 ELSE  CalculatedAge END ;
END;
$body$
LANGUAGE PLPGSQL
 STABLE;
-- REVOKE ALL ON FUNCTION f_getpatientagebyexam (birthDay date, toDay date) FROM PUBLIC;
