### ISSUE TITLE
DROP TEMPORARY TABLE in PostgreSQL must not contain keyword TEMPORARY

### ISSUE THREAD

**Issue by krasandr** [darold/ora2pg#626]
From MySQL stored procedure (but this issue is not MySQL specific - PostgreSQL don't support keyword TEMPORARY in DROP TABLE):
DROP TEMPORARY TABLE IF EXISTS t_zz;
Because PostgreSQL didn't support "TEMPORARY" keyword in DROP IF EXISTS,
to be working conversion, PostgreSQL syntax must become:
DROP TABLE IF EXISTS t_zz;

**Comment by darold** [comment]
Commit 4cce0be fixes this issue.
