### ISSUE TITLE
No PostgreSQL connection

### ISSUE THREAD

**Issue by deviantdes** [darold/ora2pg#629]
**Hi guys i have configured my config file to**

#PG_DSN		dbi:Pg:dbname=OureaX;host=localhost;port=5432
#PG_USER	postgres
#PG_PWD		123456

**But when i try to test it with**
ora2pg -t TEST -c C:\ora2pg\ora2pg_dist.conf > migration_diff2.txt

**And im getting**

[TEST PARTITION COUNT]
[ERRORS PARTITION COUNT]
No PostgreSQL connection, can not check number of PARTITION.

[TEST TABLE COUNT]
ORACLEDB:TABLE:429
[ERRORS TABLE COUNT]
No PostgreSQL connection, can not check number of TABLE.

[TEST TRIGGER COUNT]
ORACLEDB:TRIGGER:440
[ERRORS TRIGGER COUNT]
No PostgreSQL connection, can not check number of TRIGGER.

**Is my connection credentials wrong?**

Any help is greatly appreciated. Thank you

**Comment by darold** [comment]
Hi,

Removing the front dash could help.

Regards,

**Comment by deviantdes** [comment]
Hi there, thanks fro you reply, may i know what you mean by _the front dash_?

Thanks

**Comment by deviantdes** [comment]
Oh i see what you mean. Thanks alot. This is what i have now. Is the migraton already succesful? Cos i couldnt see the migrated tables in PostgreSQL

PS C:\Perl64\site\bin> ora2pg -c C:\ora2pg\ora2pg_dist.conf > migration_diff2.txt
[========================>] 429/429 tables (100.0%) end of scanning.
[========================>] 429/429 tables (100.0%) end of table export.

**Comment by darold** [comment]
Ora2Pg doesn't import DDL automatically, you need to do it by yourself before.

**Comment by deviantdes** [comment]
Got it thanks @darold  ! Closing issue.
