### ISSUE TITLE
How do i migrate Stored Procedures?

### ISSUE THREAD

**Issue by deviantdes** [darold/ora2pg#630]
Hi guys, i have managed to generate the Output.sql via running the command 
**ora2pg -c C:\ora2pg\ora2pg_dist.conf**

The output.sql contains all the tables but does not have any stored procedures.

Is there a way to include the stored procedures?

Thanks, any help is greatly appreciated.

**Comment by xeranas** [comment]
If you want to export procedures then you need to use `PROCEDURE` as export type on your `ora2pg_dist.conf`, default is `TABLE`.
