### ISSUE TITLE
Wrong conversion oracle-type "DATE" 

### ISSUE THREAD

**Issue by mauryavishal5** [darold/ora2pg#633]
The date in Oracle database is 31-JAN-01(data type DATE) but in the generated script this  is converted as '0000-01-31 00:00:00'

I have also added parameter DATA_TYPE  DATE:date

**Comment by darold** [comment]
Not reproducible for me:
```
COPY datetest (test) FROM STDIN;
2001-01-31 00:00:00
\.
````
I think you may have some data corruption in this column. Date type are extracted from Oracle using  `NLS_DATE_FORMAT = YYYY-MM-DD HH24:MI:SS` and leave untouched by Ora2Pg so if you have a `0000` year you might look at Oracle side.
