### ISSUE TITLE
ORA-03113 Problem. 

### ISSUE THREAD

**Issue by piotrofff** [darold/ora2pg#635]
Hello!

I have a problem with generating a report from ora2pg. Even I try to list tables i get an ERROR:

> 

DBD::Oracle::db prepare failed: ORA-03113: end-of-file on communication channel
Process ID: 0
Session ID: 13 Serial number: 6065 (DBD ERROR: OCIStmtExecute/Describe) [for Statement "SELECT DISTINCT A.INDEX_NAME,A.COLUMN_NAME,B.UNIQUENESS,A.COLUMN_POSITION,B.INDEX_TYPE,B.TABLE_TYPE,B.GENERATED,B.JOIN_INDEX,A.TABLE_NAME,A.INDEX_OWNER,B.TABLESPACE_NAME,B.ITYP_NAME,B.PARAMETERS,A.DESCEND
FROM DBA_IND_COLUMNS A
JOIN DBA_INDEXES B ON (B.INDEX_NAME=A.INDEX_NAME AND B.OWNER=A.INDEX_OWNER)
WHERE B.GENERATED <> 'Y' AND B.TEMPORARY <> 'Y'  AND ( UPPER(A.TABLE_NAME) NOT LIKE 'USLOG$_%' AND UPPER(A.TABLE_NAME) NOT LIKE 'MLOG$_%' AND UPPER(A.TABLE_NAME) NOT LIKE 'RUPD$_%' AND UPPER(A.TABLE_NAME) NOT LIKE 'MDXT_%' AND UPPER(A.TABLE_NAME) NOT LIKE 'MDRT_%' AND UPPER(A.TABLE_NAME) NOT LIKE 'MDRS_%' AND UPPER(A.TABLE_NAME) NOT LIKE 'DR$%' AND UPPER(A.TABLE_NAME) NOT LIKE 'CLI_SWP$%' AND UPPER(A.TABLE_NAME) NOT LIKE 'LOGMNR$%' AND UPPER(A.TABLE_NAME) NOT LIKE 'REPCAT$%' AND UPPER(A.TABLE_NAME) NOT LIKE 'JAVA$%' AND UPPER(A.TABLE_NAME) NOT LIKE 'AQ$%' AND UPPER(A.TABLE_NAME) NOT LIKE 'BIN$%' AND UPPER(A.TABLE_NAME) NOT LIKE '%$JAVA$%' AND UPPER(A.TABLE_NAME) NOT LIKE 'PROF$%' AND UPPER(A.TABLE_NAME) NOT LIKE 'TOAD_PLAN_%' AND UPPER(A.TABLE_NAME) NOT LIKE 'SYS_%$' AND UPPER(A.TABLE_NAME) NOT LIKE 'QUEST_SL_%')
ORDER BY A.COLUMN_POSITION
"] at /usr/local/share/perl5/Ora2Pg.pm line 8786.
Aborting export...

> 

Version of Oracle: 9.2.0.5
Version of Oracle Client 11.2
ora2pg machine OS: linux
Oracle machine OS: aix

Thanks for any help...

**Comment by darold** [comment]
Hi,

Perhaps the problem comes from the Oracle Client version? To access Oracle 8 instant you have to use client 10, perhaps for Oracle 9 this is the same. But if I recall well instant client 11 should works with Oracle 9i.  The issue can also comes from a network disconnection but I don't think that this is an Ora2Pg issue.
