### ISSUE TITLE
broken transformation of procedure call with default parameter

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#636]
Oracle procedure:
<pre>
create or replace procedure TEST_DUPL_VAZBA( mSql IN OUT  VARCHAR2 , mSqlend  IN OUT  VARCHAR2 , mDupl OUT BOOLEAN  , mPlatnost_od IN DATE , mPlatnost_do IN DATE , mBEZ_PLATNOSTI IN VARCHAR2 DEFAULT 'N' ) is
   mPocZaznamu  NUMBER;
   PRAGMA AUTONOMOUS_TRANSACTION;
   mCHYBA_TEXT_PROG VARCHAR2(4000);
   mKOD_CHYBA VARCHAR2(20);

  
begin
 
   mDupl := False ;
   -- REN 05.02.2018 PRIDANA VOLBA BEZ PLATNOSTI , DEFALT S PLATNOSTMA
   if mBEZ_PLATNOSTI = 'N' THEN
     mSql := mSql || ' AND ( ( platnost_od <= ''' || mPlatnost_od || ''' and  platnost_do >= ''' || mPlatnost_do  ||  ''' ) or ( platnost_od <= ''' || mPlatnost_do  || ''' and platnost_do >= ''' || mPlatnost_od || ''' ) ) ' ;
   END IF;

   mSql := ides_concat(mSql , ' '  , mSqlend );
   
   ---raise_application_error( -20010 , mSql );
   EXECUTE IMMEDIATE mSql INTO mPocZaznamu  ;
  
  
   IF mPocZaznamu > 0 THEN 
     mCHYBA_TEXT_PROG := ides_concat('NELZE ULOZIT DUPLICITNI ZAZNAM -- POCET ' , TO_CHAR(mPocZaznamu) ,  ' >> ' ,  mSql , '<<'  );
     mKOD_CHYBA := '4';
     ides_chyba(mKOD_CHYBA , NULL ,mCHYBA_TEXT_PROG  );
     mDupl := True ;
   END IF;

end ;
</pre>
The transformation to PostgreSQL is correct. But the trigger when this procedure is called without default parameter is broken:
Oracle:
<pre>
CREATE OR REPLACE TRIGGER CISVPOLPRE_BI BEFORE INSERT
ON  CISVPOLPRE
FOR EACH ROW

DECLARE
  mSql VARCHAR2(4000);
  mSqlend VARCHAR2(4000);
  mDupl boolean ;

BEGIN

----  ZACATEK DEFAULT CAST

RRRUTIL.DEFA_BEFORE_INSERT( :new.ID_CISVPOLPRE , :new.PLATNOST_OD , :new.PLATNOST_DO ,:new.IDENT , :new.ID_ASPRAVCE , :new.CVZNIKRADK ) ;

----  KONEC DEFAULT CAST

  mSql := ' SELECT COUNT(*) FROM CISVPOLPRE WHERE ID_POLONAJ = ' || :new.ID_POLONAJ  ||  ' AND  ID_DRUPRE  = ' || :new.ID_DRUPRE ; 

  mSqlend := '';
  TEST_DUPL_VAZBA( mSql , mSqlend , mDupl , :new.PLATNOST_OD , :new.PLATNOST_DO  );

  IF mDupl = True THEN
     raise_application_error( -20017 , 'DUPLICITNI ZAZNAM' ) ; 
  END IF;

END ;
</pre>
Translation:
<pre>
CREATE OR REPLACE FUNCTION ides_trigs.trigger_fct_cisvpolpre_bi()
  RETURNS trigger AS
$BODY$
DECLARE
  mSql varchar(4000);
  mSqlend varchar(4000);
  mDupl boolean;
BEGIN
  BEGIN

----  ZACATEK DEFAULT CAST
SELECT * FROM RRRUTIL.DEFA_BEFORE_INSERT( NEW.ID_CISVPOLPRE, NEW.PLATNOST_OD, NEW.PLATNOST_DO, NEW.IDENT, NEW.ID_ASPRAVCE, NEW.CVZNIKRADK ) INTO STRICT  NEW.ID_CISVPOLPRE, NEW.PLATNOST_OD, NEW.PLATNOST_DO, NEW.IDENT, NEW.ID_ASPRAVCE, NEW.CVZNIKRADK;

----  KONEC DEFAULT CAST
  mSql := ' SELECT COUNT(*) FROM CISVPOLPRE WHERE ID_POLONAJ = ' || NEW.ID_POLONAJ  ||  ' AND  ID_DRUPRE  = ' || NEW.ID_DRUPRE;

  mSqlend := '';
  SELECT * FROM TEST_DUPL_VAZBA( mSql, mSqlend, NEW.PLATNOST_OD, NEW.PLATNOST_DO  , ) INTO STRICT  mSql, mSqlend, mDupl; -----<<<<<<<

  IF mDupl = True THEN
     RAISE EXCEPTION '%', 'DUPLICITNI ZAZNAM'  USING ERRCODE = '45017';
  END IF;

  END;
RETURN NEW;
END
$BODY$
  LANGUAGE plpgsql VOLATILE SECURITY DEFINER
  COST 100;
ALTER FUNCTION ides_trigs.trigger_fct_cisvpolpre_bi()
  OWNER TO ides;
</pre>

The command
<pre>
SELECT * FROM TEST_DUPL_VAZBA( mSql, mSqlend, NEW.PLATNOST_OD, NEW.PLATNOST_DO  , ) INTO STRICT  mSql, mSqlend, mDupl;
</pre> 
is broken. There is bad comma.

**Comment by darold** [comment]
Commit 7e26c72 solves this issue.

**Comment by okbob** [comment]
My collogue will test it. Thank you very much.
