### ISSUE TITLE
insert/copy output concatenates values in some rows (whitespace between is removed)

### ISSUE THREAD

**Issue by duane-l** [darold/ora2pg#637]
Hi,  here is the background:

we are using ora2pg 18.2

Source database is 12.2.0.1, with the following nls settings:
```
SQL> select parameter, value from v$nls_parameters where parameter in ('NLS_NCHAR_CHARACTERSET','NLS_CHARACTERSET') order by 1; 
NLS_CHARACTERSET WE8ISO8859P1 
NLS_NCHAR_CHARACTERSET AL16UTF16 
```
Source table ddl is as follows:
```
SQL> desc error_log_3
 Name                                      Null?    Type
 ----------------------------------------- -------- ----------------------------
 ERROR_I                                   NOT NULL NUMBER
 PACKAGE_N                                          VARCHAR2(100)
 ERROR_MESSAGE_X                           NOT NULL VARCHAR2(512)
 CREATE_D                                  NOT NULL DATE
 CREATE_USER_I                             NOT NULL VARCHAR2(8)
```
the following query against the oracle database returns the following:
```
SQL> select error_message_x from error_log_3;

ERROR_MESSAGE_X
--------------------------------------------------------------------------------
I2WE       40092         1702240600QS  71QS  71OUTRUK M999
I2NS       72250         1701150305QX   7QX   7OUTRUK M999
I2SCC      99999         1704120415A  293A  293OUTRUK M999
I2NS       72300         1701301217QHE  5QHE  5OUTRUK M999
```
However, the insert (or copy) statement that is created using ora2pg for that table looks like the following:
```
COPY error_log_3 (error_i,package_n,error_message_x,create_d,create_user_i) FROM STDIN;
1061499 CTM Data        I2WE       400921702240600QS  71QS  71OUTRUK M999                       2017-04-02 22:30:34     CTM
1127898 CTM Data        I2NS       722501701150305QX   7QX   7OUTRUK M999                       2017-04-07 19:28:17     CTM
1926782 CTM Data        I2SCC      999991704120415A  293A  293OUTRUK M999                       2017-06-05 09:59:43     CTM
2078088 CTM Data        I2NS       723001701301217QHE  5QHE  5OUTRUK M999                       2017-06-16 16:07:20     CTM
\.
```
Note that the error_message_x string for the first record in the copy above is
```
    I2WE       400921702240600QS  71QS  71OUTRUK M999
```
But it should actually be:
```
I2WE       40092         1702240600QS  71QS  71OUTRUK M999
```
The second "whitespace" is removed.

Tried a couple of different settings in the ora2pg config file to no avail, thanks!

**Comment by darold** [comment]
I'm not able to reproduce this issue with the 18.2 release or the latest development code. If possible send me a binary dump of this table because even by modify the data in different way I can"t find any problem.

**Comment by duane-l** [comment]
Hi, thank you very much for your reply, I am working on getting a dump file to you (need to go through a couple channels on our end).

**Comment by duane-l** [comment]
Please see attached with dump of the table - the table eot_own.error_log_sample has 6 rows. 

Rows with ERROR_I in (1061499,1127898,1926782,2078088) are the problem rows - ERROR_MESSAGE_X value is different in sqlplus vs ora2pg insert/copy output - second space is concatenated in the string. Rows with ERROR_I in 4987044 and 4987071 are good - I included those as reference. 

Source Oracle database is v 11.2.0.4 
NLS_CHARACTERSET is WE8ISO8859P1 
NLS_NCHAR_CHARACTERSET is AL16UTF16 

Let me know if you need any additional information, thank you.

[error_log_sample.zip](https://github.com/darold/ora2pg/files/1794840/error_log_sample.zip)

**Comment by darold** [comment]
Thanks for the dump it helps a lot to solve the issue. Actually there is NUL character / chr(0) in the string:
```

DUMP(ERROR_MESSAGE_X)
--------------------------------------------------------------------------------
Typ=1 Len=80: 73,50,78,83,32,32,32,32,32,32,32,55,50,51,48,48,0,0,0,0,0,0,0,0,0,
49,55,48,49,51,48,49,50,49,55,81,72,69,32,32,53,81,72,69,32,32,53,79,85,84,82,85
,75,32,77,57,57,57,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,3
2,32
```
The NUL character is not possible in C string, you can see the "right" output in sqlplus because it replace the chr(0) with space but normaly you should not see any character after the first chr(0) in the string.

Unfortunately Oracle doesn't perform this replacement automatically with DBD::Oracle it just remove the chr(0). To obtain the same output than in sqplus you will have to export the table by redefining the extraction query using the REPLACE_QUERY configuration directive like this:
```
REPLACE_QUERY   ERROR_LOG_SAMPLE[SELECT ERROR_I,replace(ERROR_MESSAGE_X,chr(0),' ') FROM HR.ERROR_LOG_SAMPLE]
```

**Comment by duane-l** [comment]
Hi Darold,

Thanks much for the explanation and suggestion, that makes sense given what we are seeing.   As a follow up I will add that the only way we were able to identify this issue is because prior to using ora2pg we simply copied the data from Oracle to Postgres "manually" using foreign data wrappers  - the insert failed on the target error_log_sample table. 

So we were initially keen to see how or if ora2pg handled it.  And as you see it simply generated the insert/copy statements without the null/chr(0).    So had we used ora2pg to begin with, stands to reason we may have never even noticed this issue.

Do you have any thoughts as to how we might be able to identify this condition using ora2pg?  We would be happy if our ora2pg execution errored on insert, at least we would know there is a data issue.  Or are we simply at the mercy of DBD::Oracle for this?

Thanks again.

**Comment by darold** [comment]
The problem is that the OCI library through DBD::Oracle doesn't return any error, it simply strip the char(0) so there is no way to detect the issue with Ora2Pg. I'm afraid that the only way is to detect the issue  is during your migration test or by cheching your data in Oracle database.
