### ISSUE TITLE
DBD::Oracle::db prepare failed: ORA-01062: unable to allocate memory for define buffer (DBD ERROR: OCIDefineByPos)

### ISSUE THREAD

**Issue by christ2112** [darold/ora2pg#640]
Hi,

I am getting this error when trying to migrate BLOB data from an Oracle database (11.2.0.4)  to postgres using ora2pg (version 18.2):

DBD::Oracle::db prepare failed: ORA-01062: unable to allocate memory for define buffer (DBD ERROR: OCIDefineByPos)

The SQL statement is that is flagged in the verbose output is:

SELECT IE.COLUMN_EXPRESSION FROM DBA_IND_EXPRESSIONS IE, DBA_IND_COLUMNS IC
WHERE  IE.INDEX_OWNER = IC.INDEX_OWNER
AND    IE.INDEX_NAME = IC.INDEX_NAME
AND    IE.TABLE_OWNER = IC.TABLE_OWNER
AND    IE.TABLE_NAME = IC.TABLE_NAME
AND    IE.COLUMN_POSITION = IC.COLUMN_POSITION
AND    IC.COLUMN_NAME = ?
AND    IE.TABLE_NAME = ?
AND    IC.TABLE_OWNER = ?

The ora2pg program sits on a client server and has an Oracle instant client 11.2.0.4 setup on the server. It connect to a database server.

In the configuration file I have the parameter LONGREADLEN set to 665600000. This was done because the LOB value being read from the database is about 630000000 bytes in size.
I have traced the error from the client server and see no ORA-01062 errors. I have also traced the issue on the Oracle server and see no ORA-01062 errors. 

On the client side trace I see ORA-01403 errors (no data found).

The client (RHEL 6.7) side server has 32GB of RAM and shows no sign of memory bottlenecks. The same is true on the database server (RHEL 6.7).

Finally everything works without error if the LONGREADLEN is set to 536000000 (or any value below) however I cannot extract the BLOB that is > 536000000 as it will be truncated.

So my questions are: 

1. Is this memory issue with the client side or the Oracle database server side?

2. Is there a limitation of the LONGREADLEN within the program or server memory? Is there a server parameter than can checked?

3. Can I rule out the Oracle database server as a source of the error and possibly just focus on the client side? Are there any database memory structures that may be causing an issue. I am a Oracle DBA and I do not think there are any memory issues with the database server and I also know of no Oracle parameters that can be tweaked.

I have attached a file which includes the entire error message as well as how the ora2pg program users ulimits are set on the server.

[ora2pgIssues.txt](https://github.com/darold/ora2pg/files/1844638/ora2pgIssues.txt)
.

**Comment by darold** [comment]
Hi,

The problem here seems that you can not retrieve the full content of such BLOB in a single chunk. Try to disable NO_LOB_LOCATOR in your ora2pg.conf it will retrieve the BLOB with small chunks.

Let us know the result.

**Comment by christ2112** [comment]
Thanks for the reply Harold! It is running now. I will reply with the result later. Just for my reference would you consider this an issue with the client server or database server? 

Sent from Yahoo Mail on Android 
 
  On Sat, Mar 24, 2018 at 4:46 PM, Gilles Darold<notifications@github.com> wrote:   
Hi,

The problem here seems that you can not retrieve the full content of such BLOB in a single chunk. Try to disable NO_LOB_LOCATOR in your ora2pg.conf it will retrieve the BLOB with small chunks.

Let us know the result.

**Comment by christ2112** [comment]
Hi Darold,

I have run this twice with the NO_LOB_LOCATOR disabled. Both times it terminated with errors. The first time it was a "out of memory error" which I suspect is a client server issue. The second time was a oracle database snapshot to old error:

DBD::Oracle::st execute failed: ORA-01555: snapshot too old: rollback segment number 3 with name ...

Both errors I may be able to deal with, but I need/want to understand a few things. I am running the program again and I am trying to pull out a 465741365 byte BLOB and it is taking quite some time (> 1 hour). However when the NO_LOB_LOCATOR is enabled the export is fairly quick. Is the time taken normal when this parameter is disabled?

This would not even be an issue but I need to pull out one row which contains a LOB with 622576469 bytes. By disabling NO_LOB_LOCATOR will I still get the full content of the BLOB? The description of the parameter sort of says no, but I am not quite sure. I am looking up on cpan for a more in depth description.

Regards,

Chris




--------------------------------------------
On Sat, 3/24/18, Gilles Darold <notifications@github.com> wrote:

 Subject: Re: [darold/ora2pg] DBD::Oracle::db prepare failed: ORA-01062: unable to allocate memory for define buffer (DBD ERROR: OCIDefineByPos) (#640)
 To: "darold/ora2pg" <ora2pg@noreply.github.com>
 Cc: "christ2112" <chris.tabb@ymail.com>, "Author" <author@noreply.github.com>
 Date: Saturday, March 24, 2018, 4:46 PM
 
 Hi,
 The problem here seems that you can not retrieve the full
 content of such BLOB in a single chunk. Try to disable
 NO_LOB_LOCATOR in your ora2pg.conf it will retrieve the BLOB
 with small chunks.
 Let us know the result.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by christ2112** [comment]
It worked! The previous two runs may have been done when there was significant load on the Oracle database server and memory load on the client.

Final thought and/or question ...... I am dying to know whether you think the original issue:

DBD::Oracle::db prepare failed: ORA-01062: unable to allocate memory for define buffer (DBD ERROR: OCIDefineByPos)

was caused by memory issues on the client server? or Database server? or it was a misleading error? It was the prepare statement that contained the READLONGLEN parameter. Also by disabling the NO_LOB_LOCATOR does this cause the READLONGLEN parameter to be ignored?

Thanks for your responses.

Chris

--------------------------------------------
On Sat, 3/24/18, Gilles Darold <notifications@github.com> wrote:

 Subject: Re: [darold/ora2pg] DBD::Oracle::db prepare failed: ORA-01062: unable to allocate memory for define buffer (DBD ERROR: OCIDefineByPos) (#640)
 To: "darold/ora2pg" <ora2pg@noreply.github.com>
 Cc: "christ2112" <chris.tabb@ymail.com>, "Author" <author@noreply.github.com>
 Date: Saturday, March 24, 2018, 4:46 PM
 
 Hi,
 The problem here seems that you can not retrieve the full
 content of such BLOB in a single chunk. Try to disable
 NO_LOB_LOCATOR in your ora2pg.conf it will retrieve the BLOB
 with small chunks.
 Let us know the result.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by darold** [comment]
Yes, when you disable NO_LOB_LOCATOR, the READLONGLEN parameter is forced to 1Mb to retrieve data by 1Mb chunks. This might be slower but this seriously limit the amount of memory used to export the BLOB. 

To answer to your question about the source of the ORA-01062 issue, my understanding is that this is an internal OCI limit, DBD::Oracle use it so the limitation looks to be at client side.
