### ISSUE TITLE
broken procedure call

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#641]
for a procedure with header
<pre>
GET_POCET_SPOLVLAST( mPocet OUT NUMBER  , mKdatu IN OUT DATE , mParSpolVlast IN  RRRUTIL.T_SPOL_VLAST,
                mID_Vlastpod_out OUT OBPVLASPOD.ID_OBPVLASPOD%TYPE , mID_ccle_out OUT OBPVLASPOD.ID_CCLE%TYPE )
</pre>
the transformed procedure call:
<pre>
  GET_POCET_SPOLVLAST( mPocet , mKdatu , mParSpolVlast ,mID_Vlastpod_out  , mID_ccle_out );   
</pre>
is broken:
<pre>
 SELECT * FROM GET_POCET_SPOLVLAST(, mKdatu, mParSpolVlast) INTO STRICT  mPocet, mKdatu, mID_Vlastpod_out, mID_ccle_out;
</pre>
There is unwanted comma on begin of parameter list

**Comment by darold** [comment]
Commit 3442b7b might fix this issue but I've not tested yet.

**Comment by okbob** [comment]
Should be fixed. Thank you
