### ISSUE TITLE
Ora2pg does not export temporary tables

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#642]
Hello,

When exporting with TYPE = TABLES, I do not get the TEMPORARY TABLES, although Postgres accepts the CREATE TEMPORARY TABLE command. Can something be done for that ?

Here is the Oracle code:
CREATE GLOBAL TEMPORARY TABLE TEMP_INTERVAL
(	VAL CHAR(4), 
    ZONE_ID NUMBER(3) NOT NULL ENABLE, 
    TYPE_OF_VEHICLE_ID NUMBER(3) NOT NULL ENABLE, 
    PRODUCT_ID NUMBER(1) NOT NULL ENABLE
) ON COMMIT PRESERVE ROWS ;

**Comment by darold** [comment]
Hi Eric,

Global Temporary Table doesn't exists on PostgreSQL. I'm working on an extension to emulate the Oracle-style GTT, it can be found here: https://github.com/darold/pgtt

Performances must be improved but the actual version is working. I've planed to add automatic partitioning on GTT tables to see if that solves the performances issues. Once it is done I will add export of Global Temporary Table using this extension.

Best regards,

**Comment by glorsh66** [comment]
> Hi Eric,
> 
> Global Temporary Table doesn't exists on PostgreSQL. I'm working on an extension to emulate the Oracle-style GTT, it can be found here: https://github.com/darold/pgtt
> 
> Performances must be improved but the actual version is working. I've planed to add automatic partitioning on GTT tables to see if that solves the performances issues. Once it is done I will add export of Global Temporary Table using this extension.
> 
> Best regards,

Is it ready to use?

**Comment by darold** [comment]
Hi,

It is working but in this version as it is very slow comparing to regular temporary tables. I have abandoned the rewrite using partitioning because it don't work as expected and do not improve performences. I have a work in progress to rewrite the extension using temporary tables but due to lack of time I don't expect to end the work before the summer.

**Comment by sgrinko** [comment]
What is the status for now?

**Comment by sgrinko** [comment]
Thank you, waiting.

**Comment by darold** [comment]
Commit ccf76f1 adds new configuration directive EXPORT_GTT to export Oracle Global Temporary Table using syntax recognized by the pgtt extension. See https://github.com/darold/pgtt for more information. Default is to not export global temporary table as they are not supported natively by PostgreSQL. Enable this directive to have GTT exported with regular table using the TABLE Ora2pg action. Example of an export:
```
CREATE  /*GLOBAL*/ TEMPORARY TABLE temp1 (
        id numeric(38),
        description varchar(100)
) ON COMMIT DELETE ROWS ;
```
