### ISSUE TITLE
pk and uk indexes

### ISSUE THREAD

**Issue by matahav** [darold/ora2pg#643]
Hi,
maybe I will migrate data from ORACLE to Postgre. I search your utility. I propose you one modification.

ORACLE and PostgreSQL create index for primary and unique key automatically. Now ora2pg generate ALTER TABLE ADD CONSTRAINT to file CONSTRAINTS_TABLE.sql and CREATE INDEX to file INDEXES_TABLE.sql. I suggest you do not generate index when index is used in constraint.

For may test I changed row 8790 in Ora2Pg.pm from
WHERE$generated B.TEMPORARY <> 'Y' $condition
to 
WHERE$generated B.TEMPORARY <> 'Y' **AND NOT EXISTS (SELECT 1 FROM $self->{prefix}_CONSTRAINTS C WHERE B.INDEX_NAME=C.INDEX_NAME AND B.OWNER=C.INDEX_OWNER )** $condition

Maybe add next parameter for SKIP to section “CONSTRAINT SECTION”.

Regards,

Martin

**Comment by darold** [comment]
Hi,

Sorry for the response delay. Ora2Pg do not export indexes used by a constraint, they are autogenerated at constraint creation. Your Ora2Pg version is probably old, please use latest development code and let me know if the problem still occurs.

Best regards,
