### ISSUE TITLE
Howto import data when foreign keys are enabled?

### ISSUE THREAD

**Issue by Baitanik** [darold/ora2pg#645]
I have tables with foreign key constraints . Now when I export the data using either TYPE INSERT or TYPE COPY , It should first export the independent table data , then the foreign key dependent table data. But it is not working . It exporting the dependent data first.

**Comment by Baitanik** [comment]
Kindly Please help.

**Comment by darold** [comment]
You should create constraints and indexes after importing data to improve data migration performances. Use COPY not INSERT to export your data.

If you dont want to import your constraint after data import, you can simply enable DROP_FKEY in your ora2pg.conf file, it will start by removing them and then recreate them after the end of import.

**Comment by Baitanik** [comment]
Okay.. Thanks..
