### ISSUE TITLE
export mysql tablespace is very slow when number of table is large

### ISSUE THREAD

**Issue by yafeishi** [darold/ora2pg#646]
when i export mysql table info , in one database  have 3w tables, it almost costs 20hours+,
but when i comment the below code, it cost 2hours.
```
		my $sth2 = $self->{dbh}->prepare("SELECT DISTINCT TABLESPACE_NAME FROM INFORMATION_SCHEMA.FILES WHERE TABLE_NAME = '$row->[0]' AND table_schema = '$self->{schema}'") or $self->logit("FATAL: " . $self->{dbh}->errstr . "\n", 0);
		$sth2->execute or $self->logit("FATAL: " . $self->{dbh}->errstr . "\n", 0, 1);
		while (my $r = $sth2->fetch) {
			$tables_infos{$row->[0]}{tablespace} = $r->[0];
			last;
		}
		$sth2->finish();
```
so i want to know  these code can be optimized?

thank you!

**Comment by darold** [comment]
What do you mean by 3w ? Is this 30, 300 or 3000 ?

**Comment by darold** [comment]
I've rewrite this part to limit the number of nested queries, commit 2f56684 might fix this issue and export should not take 2 hours now too as description of the table to extract the connection part is now only done when engine is set to federated. Let me know the timimg result after these changes.

**Comment by darold** [comment]
Any update on this issue?
