### ISSUE TITLE
To_char + expression in paranthesis

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#647]
While translating to_char( a + b ), the final ::varchar is applied to the last member of the a + b expression, instead of being applied to ( a + b ) as a whole. Same issue with 3 members.

Example:
Oracle:
select to_char(1000 + to_number(DATA)) into v_test_txt from  T_INI_PARAMETERS WHERE API_NAME ='PCK_GPAR' AND API_VAR = 'VALID_PERIOD_TRX';

ora2pg:
select 1000 + (DATA)::numeric ::varchar into STRICT v_test_txt from  T_INI_PARAMETERS WHERE API_NAME ='PCK_GPAR' AND API_VAR = 'VALID_PERIOD_TRX';

... and if I enclose the expression with another pair of parenthesis, the to_char is left unchanged:

Oracle:
select to_char((1000 + to_number(DATA))) into v_test_txt from  T_INI_PARAMETERS WHERE API_NAME ='PCK_GPAR' AND API_VAR = 'VALID_PERIOD_TRX';

ora2pg:
select to_char((1000 + (DATA)::numeric )) into STRICT v_test_txt from  T_INI_PARAMETERS WHERE API_NAME ='PCK_GPAR' AND API_VAR = 'VALID_PERIOD_TRX';

Best regards,
E.D.

**Comment by darold** [comment]
Commit 6bf4372 fixes this issue.
