### ISSUE TITLE
Specifying multiple number definitions to be converted

### ISSUE THREAD

**Issue by ravis912** [darold/ora2pg#649]
Hi,
I need to convert several number data types with different precision and scale to real  in Postgres. Currently I am specifying the same in the DATA_TYPE parameter, the system is recognizing the first combination. Rest are being ignored.
For eg:
Number(10,3):real, Number(22,6):real, float:real like that.
Cases where the data type in Oracle is having a precision greater than 10 and scale greater than 2 Ora2pg is making it as double. I require that to be real.
Appreciate your help and guidance.

**Comment by darold** [comment]
Are you using last development code?

**Comment by ravis912** [comment]
Hi Darold,
I am using version 18.2.  please guide me on how to configure it, possibly
i an not configuring in the right way.
Have a great Weekend !!!
Thanks
Ravi

**Comment by darold** [comment]
```
wget https://github.com/darold/ora2pg/archive/master.zip
unzip master.zip
cd ora2pg-master/
perl Makefile.PL
make
sudo make install
```
then run ora2pg again.

**Comment by ravis912** [comment]
Thanks Darold,
Appreciate your help. I entered the DATA_TYPE parameter as multiple NUMBER
entries, matching the precision and scale.

Thanks
Ravi
