### ISSUE TITLE
missing PERFORM before procedure call

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#650]
We have PL/SQL code:
<pre>

   BEGIN
     SELECT TEXT_AKCE, ID_CLEOSHIS INTO mPSEUDO_TEXT,mID_CLEOSHIS
         FROM CLEOSHIS
         WHERE NAVRAT_PRESUDONYMIZACE IS NULL
           AND ID_CCLE =  mID_CCLE
           AND TYP_AKCE = 'PSEUDONYMIZACE';
   EXCEPTION
     WHEN NO_DATA_FOUND THEN
       IDES_CHYBA( '6' , 'Nenašel záznam s pseudonymizaci v tabulce CLEOSHIS' , ides_concat( 'ID_CCLE = ',TO_CHAR( mID_CCLE )));
     WHEN TOO_MANY_ROWS THEN
       IDES_CHYBA( '6' , 'Více záznamů s pseudonymizaci v tabulce CLEOSHIS' , ides_concat( 'ID_CCLE = ',TO_CHAR( mID_CCLE )));
   END;
</pre>
It is translated to PL/pgSQL:
<pre>

  BEGIN
     SELECT TEXT_AKCE, ID_CLEOSHIS INTO STRICT mPSEUDO_TEXT,mID_CLEOSHIS
         FROM CLEOSHIS
         WHERE NAVRAT_PRESUDONYMIZACE IS NULL
           AND ID_CCLE =  mID_CCLE
           AND TYP_AKCE = 'PSEUDONYMIZACE';
   EXCEPTION
     WHEN NO_DATA_FOUND THEN
       PERFORM IDES_CHYBA( '6' , 'Nenašel záznam s pseudonymizaci v tabulce CLEOSHIS' , ides_concat( 'ID_CCLE = ',TO_CHAR( mID_CCLE )));
     WHEN TOO_MANY_ROWS THEN
       IDES_CHYBA( '6' , 'Více záznamů s pseudonymizaci v tabulce CLEOSHIS' , ides_concat( 'ID_CCLE = ',TO_CHAR( mID_CCLE )));
   END;
</pre>
In `TOO_MANY_ROWS` case there are no `PERFORM` keyword before procedure name `IDES_CHYBA`

**Comment by darold** [comment]
Fixed in commit 4aec8e1.

**Comment by okbob** [comment]
Thank you very much

Pavel

2018-06-19 9:56 GMT+02:00 Gilles Darold <notifications@github.com>:

**Comment by okbob** [comment]
tested, fixed

Thank you again

Pavel

2018-06-19 12:00 GMT+02:00 Pavel Stehule <pavel.stehule@gmail.com>:
