### ISSUE TITLE
How to export IDENTITY columns from an Oracle 12c database?

### ISSUE THREAD

**Issue by swmcguffin-devtech** [darold/ora2pg#651]
My apologies if this is an overly basic question, but I'm brand new to Perl. Where would I modify the code to start pulling metadata from the ALL_TAB_IDENTITY_COLS so that I can port IDENTITY columns from an Oracle 12c database as IDENTITY columns in PostreSQL 10?

Also, is this a feature that anyone is currently working on for the next release?

**Comment by darold** [comment]
I have planned to work on this on Friday or Saturday, if you can wait next week for this feature. I think this is simpler than trying to explain you how to modify Ora2Pg to add such feature. The Ora2Pg code is a bit complicated to stay polite and especially if you are new to Perl.

**Comment by darold** [comment]
Please have a look to latest development code, commit adds export of Oracle 12c identity columns as serial/bigserial if PG_SUPPORTS_IDENTITY is disabled or as PostgreSQL 10 IDENTITY column when enabled. 

Extract from documentation:
```
 Add PG_SUPPORTS_IDENTITY configuration directive.

Enable this directive if you have PostgreSQL >= 10 to use IDENTITY columns
instead of serial or bigserial data type. If PG_SUPPORTS_IDENTITY is disabled
and there is IDENTITY column in the Oracle table, they are exported as serial
or bigserial columns. When it is enabled they are exported as IDENTITY columns
like:

      CREATE TABLE identity_test_tab (
              id bigint GENERATED ALWAYS AS IDENTITY,
              description varchar(30)
      ) ;

If there is non default sequence options set in Oracle, they will be appended
after the IDENTITY keyword.

Additionally in both cases, Ora2Pg will create a file AUTOINCREMENT_output.sql
with a embedded function to update the associated sequences with the restart
value set to "SELECT max(colname)+1 FROM tablename". Of course this file must
be imported after data import otherwise sequence will be kept to start value.
```

**Comment by swmcguffin-devtech** [comment]
Thank you! I'll try this out later today.

**Comment by swmcguffin-devtech** [comment]
The change works well enough that I can quick modify the output.sql file to build the new PostreSQL database, but there is at least one bug. 

foo_id bigint GENERATED ALWAYS AS IDENTITY START WITH 7 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NO CYCLE CACHE 0

should have the sequence options enclosed in parenthesis like this

foo_id bigint GENERATED ALWAYS AS IDENTITY (START WITH 7 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NO CYCLE CACHE 0)

Also, it looks like PostrgeSQL can't take a value of 0 for the CACHE option.

Even so, this was a tremendous help, so thank you again for getting to it so quickly.

**Comment by darold** [comment]
Thanks for the feedback, commit abf087e fixes export of identity columns by enclosing options between parenthesis and replacing CACHE 0 by 1 (PostgreSQL default).
