### ISSUE TITLE
ora2pg JSON data CLOB to TEXT convertion is Adding character E'  '

### ISSUE THREAD

**Issue by lingeshpes** [darold/ora2pg#652]
While trying to migrate data from oracle to postgres ClOB data's are appending with E'  ' characters for jsonobjects.

Oracle column PATH data type CLOB :- /beans/authenticationService

Postgres after migration PATH data type TEXT:- E'/beans/authenticationService'

its appending E'   ' at the beginning. Is it because of converting CLOB data to TEXT in postgres using ora2pg tool?

**Comment by lingeshpes** [comment]
Hi darold,

Thanks for your reply. 

I am executing DDL scripts manually and then using ora2pg to insert tables data from oracle to postgres db on the fly by providing Postgres db details. By using TYPE COPY can the data be inserted directly to postgres tables? Not clear with the usage of INSERT and COPY types. 

Thanks for providing such a Robust tool called 'Ora2pg' for migration activity.

**Comment by darold** [comment]
Yes, the COPY mode will be much more fast for direct (on the fly) data import too. The INSERT action mode is only provided to obtain portable DML if you want to import data into an other RDBMS too or for debugging. Personally I used it to debug export of spatial objects but once it is fixed I go back to COPY mode.

**Comment by lingeshpes** [comment]
Using COPY mode saved my Time. It Inserts data must master.
