### ISSUE TITLE
bug on converting oracle infinity values:  ~ to PostgreSQL infinity value : Infinity

### ISSUE THREAD

**Issue by jacks33** [darold/ora2pg#655]
Hi,

I notice this bug during data migration, it happens during the translation of Oracle "~" value to postgreSQL "Infinity" value.

LOGS :
6968 DBD::Pg::db pg_putcopyend failed: ERROR:  invalid input syntax for type numeric: "inf"
76969 CONTEXT:  COPY referenceprice_aud, line 2227, column tolerance: "inf" at /usr/share/perl5/vendor_perl/Ora2Pg.pm line 12761.
76970 FATAL: ERROR:  invalid input syntax for type numeric: "inf"
76971 CONTEXT:  COPY referenceprice_aud, line 2227, column tolerance: "inf"
76972 DBD::Oracle::db disconnect failed: ORA-03135: contact perdu pour la connexion
76973 ID de processus : 0
76974 ID de session : 294,  NumÃ©ro de sÃ©rie : 181 (DBD ERROR: OCISessionEnd) at /usr/share/perl5/vendor_perl/Ora2Pg.pm line 12001.
76975 Aborting export...

FIELD: is REFERENCEPRICE_AUD.TOLERANCE
Oracle field  type is FLOAT (126)
Postgresql field  type is NUMERIC (77,40)

there is a rule of casting DATA_TYPE parameter in the ora2pg.conf 
DATA_TYPE FLOAT:numeric(77\,40)
MODIFY_TYPE on some fields of the table but *not* on guilty field ("TOLERANCE")

I can provide the ora2pg.conf if needed.

ora2pg release is v18.2

Thank you very much

**Comment by darold** [comment]
`Inf` or `Infinity` is not supported with numeric, you should use float or double precision. I can translate `~` into `NaN` when destination type is numeric but I'm not sure it will be helpful.

**Comment by darold** [comment]
I don't know about `/*PARRALLEL*/` hint, can you explain me how to use it?

**Comment by jacks33** [comment]
maybe ora2pg  could add the hint PARRALLEL in the select queries it adresses to oracle,  it would be some kind of SELECT /*+ PARALLEL */ * FROM Table1;

**Comment by darold** [comment]
Please download and install latest development code and test the hint effect. You will have to set DEFAULT_PARALLEL_DEGREE ora2pg.conf directive to the parallelism degree you want to use. I guess that 8 is a basic value?

**Comment by darold** [comment]
Also if you can tell me by how much it improve the performance it will be great.
