### ISSUE TITLE
Unique constraints are created with different Name in Postgres

### ISSUE THREAD

**Issue by lingeshpes** [darold/ora2pg#656]
Hi,

Am trying to migrate table and its constraints from oracle to postgres, but constraints names are not getting migration to postgres, it is created with a new name 

In below example oracle constraint "AGPNUNIQUE" is created with ""p_privileges_application_version_privilege_name" in postgres.

**oracle:-** 

CREATE TABLE P_PRIVILEGES (
  PRIVILEGE_NAME        VARCHAR2(150 CHAR)      NOT NULL,
  APPLICATION_VERSION      VARCHAR2(255 CHAR)        NOT NULL,
 
);

ALTER TABLE P_PRIVILEGES ADD CONSTRAINT AGPNUNIQUE UNIQUE (APPLICATION_VERSION, PRIVILEGE_NAME, AGL_TENANT_ID);

**Postgres:-** 

CREATE TABLE P_PRIVILEGES (
	privilege_name varchar(150) NOT NULL,
	application_version varchar(255) NOT NULL,
	
) ;

CREATE UNIQUE INDEX p_privileges_application_version_privilege_name ON p_privileges (application_version, privilege_name);
ALTER TABLE p_privileges ADD UNIQUE (application_version,privilege_name);

Thanks in Advance

**Comment by darold** [comment]
What is the interest to keep the constraint's Oracle names?

**Comment by lingeshpes** [comment]
once migration is completed from Oracle. Few Constraints are dropped based on constraints name. Since Oracle constraints are renamed in postres db, we are facing  error. It would be good if the constraints name are kept same in both Oracle and postres after migration from ora2pg tool.

Thank you

**Comment by darold** [comment]
Enabling KEEP_PKEY_NAMES should be what you are looking for.

**Comment by darold** [comment]
Commit c955482 update documentation and configuration file to be less confusing about this directive.

**Comment by lingeshpes** [comment]
Thanks darold.

Tried with enabling KEEP_PKEY_NAMES 1, still its creating new name in postgres db not keeping same as in oracle database.

or2pg version:-  Ora2pg v18.2

**Comment by darold** [comment]
Here a example of constraints export with KEEP_PKEY_NAMES disabled:
```
gilles@gilles-N130BU:/home/git/test_ora2pg/test-db$ cat tmp/CONSTRAINTS_output.sql 
ALTER TABLE countries ADD PRIMARY KEY (country_id);
ALTER TABLE departments ADD PRIMARY KEY (department_id);
ALTER TABLE employees ADD UNIQUE (email);
ALTER TABLE employees ADD PRIMARY KEY (employee_id);
ALTER TABLE employees ADD CONSTRAINT emp_salary_min CHECK (salary > 0);
ALTER TABLE identity_test_tab3 ADD PRIMARY KEY (id);
ALTER TABLE jobs ADD PRIMARY KEY (job_id);
ALTER TABLE job_history ADD PRIMARY KEY (employee_id,start_date);
ALTER TABLE job_history ADD CONSTRAINT jhist_date_interval CHECK (end_date > start_date);
ALTER TABLE locations ADD PRIMARY KEY (location_id);
ALTER TABLE regions ADD PRIMARY KEY (region_id);
```
only check constraint are exported using the original Oracle name because we have to named the constraint.

Now with KEEP_PKEY_NAMES enabled:
```
ALTER TABLE countries ADD CONSTRAINT country_c_id_pk PRIMARY KEY (country_id);
ALTER TABLE departments ADD CONSTRAINT dept_id_pk PRIMARY KEY (department_id);
ALTER TABLE employees ADD CONSTRAINT emp_emp_id_pk PRIMARY KEY (employee_id);
ALTER TABLE employees ADD CONSTRAINT emp_email_uk UNIQUE (email);
ALTER TABLE employees ADD CONSTRAINT emp_salary_min CHECK (salary > 0);
ALTER TABLE identity_test_tab3 ADD PRIMARY KEY (id);
ALTER TABLE jobs ADD CONSTRAINT job_id_pk PRIMARY KEY (job_id);
ALTER TABLE job_history ADD CONSTRAINT jhist_emp_id_st_date_pk PRIMARY KEY (employee_id,start_date);
ALTER TABLE job_history ADD CONSTRAINT jhist_date_interval CHECK (end_date > start_date);
ALTER TABLE locations ADD CONSTRAINT loc_id_pk PRIMARY KEY (location_id);
ALTER TABLE regions ADD CONSTRAINT reg_id_pk PRIMARY KEY (region_id);
```
As you can see they are created using the Oracle name.

**Comment by lingeshpes** [comment]
Thanks. It's working.
