### ISSUE TITLE
new files for code inside autonomous transactions

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#657]
After upgrade to master, the ora2pg produces _atx files. 

Is possible to disable this behave and store all code to one file?

**Comment by darold** [comment]
I can't reproduce this behavior, the wrapper function and the  _atx function are always exported in the same file. They are concatenated into the same variable (lib/Ora2Pg.pm line 12405) before being dumped to file. Do you have a sample to reproduce?

About autonomous transaction when 11 will be out I will add a configuration directive to enable export of autonomous transaction as new procedure calls. This will remove the use of the dblink wrapper workaround.

**Comment by darold** [comment]
In new PROCEDURE object you can call COMMIT inside the code, this can act as an autonomous transaction.

**Comment by okbob** [comment]
2018-06-22 8:40 GMT+02:00 Gilles Darold <notifications@github.com>:

> In new PROCEDURE object you can call COMMIT inside the code, this can act
> as an autonomous transaction.
>
It is available only when there are not any outer transactions - etc when
the procedure was started by CALL command, and when it is not nested to
some command started by SELECT.

The Oracle procedures can be translated to PostgreSQL 11 procedures - but
unfortunately, autonomous transactions not.

**Comment by darold** [comment]
Oh, ok I should have deeper look in this new feature.

**Comment by okbob** [comment]
It is false alarm. My colleague didn't use correct words when he reported internal issue. I am sorry.
