### ISSUE TITLE
Improvement keepalive

### ISSUE THREAD

**Issue by jacks33** [darold/ora2pg#661]
Hello,

During migration I had timeout connections 

Either if I install ora2pg in the oracle server, in a postgresql server or in a dedicated server.

I use direct import.

I found the root cause:

my data_limit is very high 100000 and fetching data from oracle is slow, 

so some connections are dropped by firewall idle timeout because they spend too much time waiting for ora2pg data chunks.

The improvement I propose is to add keepalive parameters to ora2pg configuration:
net.ipv4.tcp_keepalive_intvl = 75
net.ipv4.tcp_keepalive_probes = 9
net.ipv4.tcp_keepalive_time = 600

Normally if application do not set these parameters, system default should be used

*But* this feature is deprecated now linux kernel only take them in account if application (here ora2pg) specify them establishing connections.

The default value I propose are the ones in example.

Thank you.

**Comment by darold** [comment]
Hi,

I don't know why you said that using sysctl is deprecated but there is no way in DBD::Oracle or DBI to set keepalive. Ora2pg doesn't use a low level function to connect to Oracle but it use the connect() function of the DBD::Oracle Perl module instead. This module doesn't have this kind of options at my knowledge.  I'm afraid this can't be done but surely you may want to use a lower for DATA_LIMIT.

Regards,
