### ISSUE TITLE
Convert Oracle subtype to postgresql

### ISSUE THREAD

**Issue by francesco-loreti** [darold/ora2pg#662]
This program not support the Oracle subtypes. Is it possible append this function? One example of [subtype](http://psoug.org/definition/SUBTYPE.htm).

**Comment by darold** [comment]
I will look for more example but they look like DOMAIN in PostgreSQL.

**Comment by francesco-loreti** [comment]
Oh yes it's very similar!!!

**Comment by darold** [comment]
Commit 1903e63 add this feature on TYPE and PACKAGE export.
