### ISSUE TITLE
Update triggers based on columns are not translated with the same feature

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#664]
Hello Darold,

We have Oracle triggers on update of particular columns:
CREATE OR REPLACE TRIGGER TRIG_TICKET_EXIT
AFTER INSERT or UPDATE of  vehicle_generic_id   ON t_ticket_exit     FOR EACH ROW

They are translated as general update triggers:
CREATE TRIGGER trig_ticket_exit
	AFTER INSERT OR UPDATE ON t_ticket_exit FOR EACH ROW

But Postgres allows to define update triggers on column update. Can you do somethig ?
Best Regards,
Eric

**Comment by darold** [comment]
Fixed with commit 7e14a85.
