### ISSUE TITLE
Bug with export oracle function-based index

### ISSUE THREAD

**Issue by apol1234** [darold/ora2pg#666]
Hi!
Thank you for your work!
I find out a bug with the export oracle function-based indexes. 

In Oracle:
```
>select column_expression from user_ind_expressions;
COLUMN_EXPRESSION
-------------------------
CASE  WHEN "M_ACTIVITY"='A' THEN "PARTICIPANT_ID" ELSE NULL END 
```

But after export we have:
```
CREATE UNIQUE INDEX rform_type_code_ui ON rpt_forms (("case when m_activity='a' then participant_id else null end));
```
Problems are  in double quota before case and lower case for 'a' !

In release version 18.2 I have fixed this by change:
```
>>>if (($row->[1] !~ /".*"/) && ($row->[1] !~ /\(.*\)/) ) {
```
to 
```
>>>if (($row->[1] !~ /".*"/) && ($row->[1] !~ /\(.*\)/) && ($row->[4] !~ /FUNCTION-BASED/i)) {
```
in line 8852. 

Thank you!

**Comment by darold** [comment]
Thanks for the report, this is now fixed with commit 3332f9e
