### ISSUE TITLE
Issues with SHOW_TABLE not showing all tables in oracle 

### ISSUE THREAD

**Issue by Zubeyd55** [darold/ora2pg#667]
Hi 
I am trying to migrate Tables from oracle to postgrsql. in the configuration file i use  oracle user and password and i specify the schema i want to export tables from. like this 
![ora2pg](https://user-images.githubusercontent.com/39626504/42635533-f661e338-85ee-11e8-88d9-6cfb485ee78a.GIF)
when i list the tables in oracle using the SHOW_TABLE command  ora2pg -t SHOW_TABLE  -c mig_config/ora2pg.conf it is not showing me all the tables in that schema 
![ora2pg2](https://user-images.githubusercontent.com/39626504/42636418-7142bfe4-85f1-11e8-8049-3870803ebdf5.GIF)
it is recognizing only 4 tables. all the tables in that schema is  showing me as  Top 10 of largest tables.

Any help please?
Thank You!

**Comment by darold** [comment]
Strange, are you using ltest development code? If not, please download and install it and report the new output. To get latest development code use git clone or:
```
wget https://github.com/darold/ora2pg/archive/master.zip
```
then
```
unzip master.zip
cd ora2pg-master/
perl Makefile.PL
make
sudo make install
```

**Comment by darold** [comment]
Also set `USER_GRANTS` to `0` in your ora2pg.conf  file.

**Comment by Zubeyd55** [comment]
I installed  the latest development code but i got some error should i remove the old ora2pg directory?/
the output looks like this
![ora2pg3](https://user-images.githubusercontent.com/39626504/42639731-68e5369e-85f9-11e8-809f-aa1ec0b88651.GIF)

**Comment by darold** [comment]
This is because the user you are using to connect to your ora2pg database is not superuser. If you use a super user (system) then you can set USER_GRANTS to 0 and ora2pg will use the DBA_* table to look for object. Otherwise set USER_GRANTS to 1 to let ora2pg use ALL_* tables.

**Comment by Zubeyd55** [comment]
Here is my configuration file 
![ora2pg4](https://user-images.githubusercontent.com/39626504/42640729-942ee6d6-85fb-11e8-9e66-a65136c4fea7.GIF)

**Comment by darold** [comment]
Sorry I read too fast the error screenshot, the errors complain about identity table. Commit e03ec4b solves this issue.
