### ISSUE TITLE
Broken migration on some older Oracle db

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#670]
My colleague reported error
<pre>
FATAL: ORA-00942: table or view does not exist (DBD ERROR: error possibly near <*> indicator at char 78

SELECT OWNER, TABLE_NAME, COLUMN_NAME, GENERATION_TYPE, IDENTITY_OPTIONS
FROM DBA_TAB_IDENTITY_COLS WHERE OWNER = 'IDES_JMMAJ_AKT' AND ( NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^USLOG\$_.*$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^MLOG\$_.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^RUPD\$_.*$') AND
NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^MDXT_.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^MDRT_.*$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^MDRS_.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^DR\$.*$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^CLI_SWP\$.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^LOGMNR\$.*$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^REPCAT\$.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^JAVA\$.*$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^AQ\$.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^BIN\$.*$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SDO_GR_.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^.*\$JAVA\$.*$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^PROF\$.*$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^TOAD_PLAN_.*$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SYS_.*\$$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^QUEST_SL_.*$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^EVT_CARRIER_CONFIGURATION$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^EVT_DEST_PROFILE$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^EVT_HISTORY$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^EVT_INSTANCE$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^EVT_MAIL_CONFIGURATION$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^EVT_MONITOR_NODE$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^EVT_NOTIFY_STATUS$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^EVT_OPERATORS$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^EVT_OPERATORS_ADDITIONAL$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^EVT_OPERATORS_SYSTEMS$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^EVT_OUTSTANDING$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^EVT_PROFILE$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^EVT_PROFILE_EVENTS$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^EVT_REGISTRY$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^EVT_REGISTRY_BACKLOG$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^OLS_DIR_BUSINESSE$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^OLS_DIR_BUSINESSES$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SDO_COORD_REF_SYS$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SDO_CS_SRS$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SDO_INDEX_METADATA_TABLE$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SDO_INDEX_METADATA_TABLES$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SDO_PC_BLK_TABLE$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SDO_STYLES_TABLE$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SDO_TIN_BLK_TABLE$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMACTUALPARAMETER_S$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMGLOBALCONFIGURATION_S$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMFORMALPARAMETER_S$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMFOLDER_S$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMDISTRIBUTIONSET_S$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMDEPENDENTLINKS$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMDEPENDENTINDEX$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMDEPENDEEINDEX$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMDEFAUTH_S$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMDBAUTH_S$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMPARALLELJOB_S$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMPACKAGE_S$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMOWNERLINKS$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMOWNERINDEX$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMOWNEEINDEX$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMOSNAMES_X$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMOMSTRING_S$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMMOWNERLINKS$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMMOWNERINDEX$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMPACKAGE_S$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMPARALLELJOB_S$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMPARALLELOPERATION_S$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMPARALLELSTATEMENT_S$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMPRODUCT_S$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_AD_ADDRESSES_$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_AD_DISCOVERED_NODES_$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_AD_NODES_$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_AD_PARMS_$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_AUTO_DISCOVERY_ITEM_$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_AUTO_DISCOVERY_PARMS_$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_BLOB_$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_CREDENTIALS\$$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_JOB_$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_JOB_EVENTLIST_$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_JOB_HISTORY_$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_JOB_INSTANCE_$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_JOB_LIBRARY_$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_JOB_TASK_INSTANCE_$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_LONG_TEXT_$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_REP_VERSION$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_SERVICES$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_SERVICE_GROUP_DEFN_$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_SERVICE_GROUP_ITEM_$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_SERVICE_ITEM_$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_UPDATESERVICES_CALLED_$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMAGENTJOB_S$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMARCHIVE_S$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMBREAKABLELINKS$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMCLIQUE$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMCONFIGURATION$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMCONSOLESOSETTING_S$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMDATABASE_S$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMHOSTAUTH_S$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMHOST_S$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMINSTALLATION_S$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMLOGMESSAGE_S$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMMONTHLYENTRY_S$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMMONTHWEEKENTRY_S$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMP_USER_DETAILS$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMRELEASE_S$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMRUN_S$') AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMSCHEDULE_S$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMSHAREDORACLECLIENT_S$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMSHAREDORACLECONFIGURATION_S$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMTABLESPACE_S$') AND NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMVCENDPOINT_S$')
AND  NOT REGEXP_LIKE(UPPER(TABLE_NAME),'^SMWEEKLYENTRY_S$')) ORDER BY OWNER, TABLE_NAME, COLUMN_NAME')
</pre>

Problem is in reference on table DBA_TAB_IDENTITY_COLS. This table is not in Oracle 11 and older.

**Comment by darold** [comment]
This should already been fixed in commit e03ec4b

**Comment by okbob** [comment]
yes, it is fixed. I am sorry for noise
