### ISSUE TITLE
TRUNCATE TABLE with extra clause

### ISSUE THREAD

**Issue by e7e6** [darold/ora2pg#671]
Hi,

Oracle TRUNCATE can have [clauses](https://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_10007.htm#SQLRF01707) not present in PostgreSQL:

- [PRESERVE|PURGE] MATERIALIZED VIEW LOG;
- [DROP|REUSE] STORAGE;

ora2pg does not remove those clauses during code conversion. I tried to change this in `Ora2Pg::PLSQL::plsql_to_plpgsql` (which was in fact not enough) and submit a pull request, but realized changes might be bigger than what I though initially. `TRUNCATE` queries in Ora2Pg.pm are set not to be parsed `$self->{queries}{$q}{to_be_parsed} = 0;` and therefore do not go through `Ora2Pg::PLSQL::convert_plsql_code`.  

I'm afraid changing `if ($self->{queries}{$q}{code} !~ /(SELECT|UPDATE|DELETE|INSERT|DROP)/is)` to `if ($self->{queries}{$q}{code} !~ /(SELECT|UPDATE|DELETE|INSERT|DROP|TRUNCATE)/is)` might break code elsewhere. 

What are your thoughts on this ?
Thanks,

Anthony

**Comment by darold** [comment]
Patch applied, thanks Anthony.
