### ISSUE TITLE
can support PG 10 partition table ?

### ISSUE THREAD

**Issue by yafeishi** [darold/ora2pg#674]
can support PG 10 partition table ?
thank you!

**Comment by darold** [comment]
Yes, use latest development code and enable PG_SUPPORTS_PARTITION in ora2pg.conf.

**Comment by yafeishi** [comment]
OK  but  i find  http://ora2pg.darold.net/documentation.html  have not update ~

**Comment by darold** [comment]
Yes my bad, I have to publish a new release and update documentation. The feature is not available in current release 18.2. I will do that as soon as I find time.

**Comment by yafeishi** [comment]
OK ,i  clone source code,and  make install, this way include  the feature ?

**Comment by darold** [comment]
yes

**Comment by darold** [comment]
Now with commit 974c92c Ora2Pg is able to export Oracle HASH partitioning when PG_SUPPORTS_PARTITION is enabled.  HASH partitioning is a  new feature of PostgreSQL 11.
