### ISSUE TITLE
Ora2Pg v19.0. Parallel data load from Oracle 11.2.0.4 partitioned tables into Postgresql 10

### ISSUE THREAD

**Issue by denoley** [darold/ora2pg#679]
Ora2Pg generates query

`SELECT  /*+ FULL(SYS_P11588) PARALLEL(SYS_P11588, 3) */
       "INFO_ID",
       "BLANK_NUMBER_INT"
  FROM "KBLN_INFO" PARTITION (SYS_P11588)`

but it doesn't  execute in parallel mode. The simplified plan is:

|  Id |  Operation
|   0 |  SELECT STATEMENT
|   1 |    PARTITION RANGE SINGLE
|   2 |       PARTITION HASH ALL
|   3 |          TABLE ACCESS FULL

To execute query in parallel mode Ora2Pg must generate this construction (insert alias SYS_P11588 after `PARTITION (..)`):

`SELECT  /*+ FULL(SYS_P11588) PARALLEL(SYS_P11588, 3) */
       "INFO_ID",
       "BLANK_NUMBER_INT"
  FROM "KBLN_INFO" PARTITION (SYS_P11588)  SYS_P11588`

or this construction (insert new alias `a` after `PARTITION (..)` and replace alias SYS_P11588 in the hint `/*+ FULL(SYS_P11588) PARALLEL(SYS_P11588, 3) */` with new alias `a`):

`SELECT  /*+ FULL(a) PARALLEL(a, 3) */
       "INFO_ID",
       "BLANK_NUMBER_INT"
  FROM "KBLN_INFO" PARTITION (SYS_P11588)  a`

The simplified plan is:
|  Id |  Operation          
|   0 |    SELECT STATEMENT
|   1 |      PX COORDINATOR 
|   2 |         PX SEND QC (RANDOM)QC (RAND) 
|   3 |            PX BLOCK ITERATOR 
|   4 |                TABLE ACCESS FULL

**Comment by darold** [comment]
Commit bcbd76f might fix this issue, I've chosen the second solution with always `a` as alias.

**Comment by denoley** [comment]
Parallel mode worked well, but there is one comlexity.
Parallel mode gratly improve performance if table consists of many rows, but significantly reduce performance if table consts of few rows because of overheads on working of parallel dispatcher.
I propose the following solution.
If default_parallelism_degree  is set to 0/1 - there is no parallel mode (as it done).
If default_parallelism_degree  is set to 2..
We need to create parameter, for example, PARALLEL_TABLE, wich would consist space divided table names for paralel load. If it is empty - the default_parallelism_degree applies for all atable (as it done), but it is not empty, the the default_parallelism_degree applies only to mentioned tables.
PARALLEL_TABLE T1 T2 T3...

**Comment by darold** [comment]
I prefer something more automatic. Do you know the amount of line where Oracle parallelism should be used? In this case I can look at table statistics and disable parallelism if the number of line is bellow the limit.

**Comment by denoley** [comment]
I think it is about 100K lines (in no-partitioned table, or in one partition in partitioned table). But i propouse you to create parameter for this value.

**Comment by darold** [comment]
Commit 2b40281 add the PARALLEL_MIN_ROWS configuration directive to prevent Oracle's parallel mode to be activated during data export if the table have less than a certain amount of rows. Default is 100000 rows.

**Comment by denoley** [comment]
Worked well!
