### ISSUE TITLE
Ora2Pg v19.0. Composite Index from Oracle 11.2.0.4 into Postgresql 10

### ISSUE THREAD

**Issue by denoley** [darold/ora2pg#680]
In Oracle there is and index:

`CREATE INDEX IFK_KBLN_INFO_ACCSTATUS ON KBLN_INFO (ACC_STATUS_ID, 1);`

Ora2Pg generates DDL:

`CREATE INDEX ifk_kbln_info_accstatus ON kbln_info (acc_status_id, 1);`

But DDL terminated with error:

```
ERROR:  syntax error at or near "1"
LINE 1: ...DEX ifk_kbln_info_accstatus ON kbln_info (acc_status_id, 1);

```

In this case i'm propose decision - remove 1 (or another numerical symbol) from constraction

```
CREATE INDEX ifk_kbln_info_accstatus ON kbln_info (acc_status_id);
CREATE INDEX
```

**Comment by denoley** [comment]
Oracle DDL:

```
CREATE TABLE KBLN_INFO
(INFO_ID VARCHAR2(25 CHAR) DEFAULT substr(sys_guid(),1,25),
ACC_STATUS_ID VARCHAR2(7 CHAR));

```

`CREATE INDEX IFK_KBLN_INFO_ACCSTATUS ON KBLN_INFO (ACC_STATUS_ID, 1);`

**Comment by darold** [comment]
What does this number (1) represents? Is this the position of the column in the table used instead of his name?

**Comment by denoley** [comment]
No, it's just a number value. 
This is a feature of Oracle, which allows you to store the null values of fields in the index. Whitout this number rows with ACC_STATUS_ID = null doesn't store in index. Hackers method :)

**Comment by darold** [comment]
Ah ok, it seems that this is not really documented. Also I was able to create these indexes:
```
CREATE INDEX KBLN_INFO_INFO_ID_IDX ON KBLN_INFO(1);
CREATE INDEX KBLN_INFO_INFO_ID_IDX1 ON KBLN_INFO(6);
```
they are created with success and I don't know what these indexes are doing outside comfort me in not use Oracle database :-)

Ora2Pg exports them as:
```
CREATE INDEX ifk_kbln_info_accstatus ON kbln_info (acc_status_id, 1);
CREATE INDEX kbln_info_info_id_idx ON kbln_info (1);
CREATE INDEX kbln_info_info_id_idx1 ON kbln_info (6);
CREATE INDEX kbln_info_info_id_idx2 ON kbln_info (0);
```
I will simply remove simple number in the column name list and completely remove the index in the other examples.

**Comment by denoley** [comment]
Yes, it will be right.

**Comment by denoley** [comment]
Index creation well done!
