### ISSUE TITLE
Wrong username in emulation of dblink (Ora2Pg 18.2/19.0, Oracle 11.2.0.4, Postgresql 10/11b3)

### ISSUE THREAD

**Issue by denoley** [darold/ora2pg#682]
In Oracle there is schema bso_test2 wich consists dblink:
```
CREATE DATABASE LINK DL_BLANK_RSA
 CONNECT TO RSA
 IDENTIFIED BY <password>
 USING '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=H1)(PORT=1521)))(CONNECT_DATA=(SID=TST1)))';
```

In Postgres there is database `bso_test2` and user `bso_test2`.

dblink.sql generated by Ora2Pg consists wrong user mapping (i havn't user `rsa`, i have user `bso_test2`):
```
CREATE SERVER dl_blank_rsa FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=H1)(PORT=1521)))(CONNECT_DATA=(SID=TST1)))');
CREATE USER MAPPING FOR rsa SERVER dl_blank_rsa OPTIONS (user 'rsa' , password 'secret');
```

Must be:
```
CREATE SERVER dl_blank_rsa FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=H1)(PORT=1521)))(CONNECT_DATA=(SID=TST1)))');
CREATE USER MAPPING FOR bso_test2 SERVER dl_blank_rsa OPTIONS (user 'rsa' , password 'secret');
```

**Comment by darold** [comment]
Yes but Ora2Pg has no idea of which user you will used for the dblink connection so by default it uses the Oracle user defined after the `CONNECT TO` keywords. I could set it to PG_USER value but this could be an other user used. In other terms, you have to adjust this username by yourself.

**Comment by denoley** [comment]
It was an Oracle private database link (DDL didn't consist PUBLIC instruction), so only exported oracle user (schema) can access them. Respectively, CREATE USER MAPPING FOR must consist PG_USER. In my example instead of
 `CREATE USER MAPPING FOR rsa SERVER dl_blank_rsa OPTIONS (user 'rsa' , password 'secret');` 
would be 
`CREATE USER MAPPING FOR bso_test2 SERVER dl_blank_rsa OPTIONS (user 'rsa' , password 'secret');`

**Comment by darold** [comment]
Commit 5696340 force the use of PG_USER in `CREATE USER MAPPING FOR ... SERVER ...`when it is defined.

**Comment by darold** [comment]
User 'rsa' is the user used to connect to Oracle, the 'bso_test2' user is the PostgreSQL user taken from PG_DSN. I don't think you have the same user both side?

**Comment by darold** [comment]
Ok I'd not seen the other issue, I'm closing this one and add the answer to issue #685

**Comment by denoley** [comment]
Yes, i can't reopen issue, so I've create another one.
