### ISSUE TITLE
Trying to export all non-DBA user's objects but outputs no DDL

### ISSUE THREAD

**Issue by solokyo** [darold/ora2pg#684]
Hi,
As the title said, I wanna export all non-DBA user's objects.
More specifically, table, data, and functions from different users, the schema is optional.

According to the documentation
>"When no schema name is provided and EXPORT_SCHEMA is enabled, Ora2Pg will export all objects from all schema of the Oracle instance with their names prefixed with the scham name."

My code is like
```
my $schema = new Ora2Pg (
#       ORACLE_HOME => "$1",
        EXPORT_SCHEMA=>1,
        ORACLE_DSN=>"dbi:Oracle:host=$IP_ORA;sid=$SID_ORA;port=$PORT_ORA",
        ORACLE_USER => $USERNAME_ORA,
        ORACLE_PWD => $PASSWORD_ORA,
        SYSUSERS => "SYS,SYSTEM",
        SCHEMA => "$SCHEMA_ORA",
        TYPE=>'TABLE,FUNCTION',
#       NLS_LANG=>'JAPANESE_JAPAN.JA16SJISTILDE',
#       NLS_NCHAR=>'AL16UTF16',
#       CLIENT_ENCODING=>'UTF8',
        FORCE_OWNER=>$USERNAME_PG,
        OUTPUT=>'output.sql',
        LOGFILE=>"logTemp"
);
$schema->export_schema('output.sql');
```
All variables are read from a configuration file and the _SCHEMA_ORA_ was set to `SCHEMA_ORA=""` but here's the message I got from command line

>[========================>] 0/0 tables (100.0%) end of scanning.
[========================>] 0/0 tables (100.0%) end of table export.

When I change the configuration file to `SCHEMA_ORA="TEST"`, I got the output that I expected.
>[========================>] 13/13 tables (100.0%) end of scanning.                         
[========================>] 13/13 tables (100.0%) end of table export.  

I have no idea where did I wrong.

Another question is, as you may noticed that I comment out the `#       ORACLE_HOME => "$1",` and the code worked fine, does it means I don't need to set `$ORACLE_HOME` ? or when should I set the  `$ORACLE_HOME`?
Any help please

**Comment by solokyo** [comment]
I found something in #135 and I tried by comment out this 2 lines
```
#       SCHEMA => "$SCHEMA_ORA",
#       EXPORT_SCHEMA=>1,
```
And I still get **0/0 tables**

**Comment by SebAlbert** [comment]
I would guess taking away the `SCHEMA` entry is correct, but you also took away the `EXPORT_SCHEMA => 1`, which is in contrast to what you quoted from the documentation. Maybe just comment out the `SCHEMA`, but not the `EXPORT_SCHEMA => 1`.

**Comment by darold** [comment]
As Sebastian says you may want to keep EXPORT_SCHEMA if you want to use the same schema in PostgreSQL. Otherwise you have a typo in the SCHEMA variable, the $ sign is doubled and I don't think this is a reference.

Also you may want to set USER_GRANTS to 1, to force ora2Pg to look into ALL_* table instead of DBA_* tables.

**Comment by solokyo** [comment]
Keep `EXPORT_SCHEMA=>1` worked, thanks for the reply.
About my second question, _ORACLE_HOME_ , any advice for me?

**Comment by SebAlbert** [comment]
I usually have to put some Library files (e.g. "instantclient") on the machine on which I run ora2pg and have the _environment variable_ `ORACLE_HOME` point to the directory it is in. I have never tried to supply ora2pg directly with this parameter in its configuration, however.

**Comment by darold** [comment]
Ora2Pg takes the ORACLE_HOME path from your environment variable if it is not overridden in the configuration file.

**Comment by solokyo** [comment]
I removed ``ORACLE_HOME => "$1",`` from my code.
Thank you very much.
