### ISSUE TITLE
Wrong username in emulation of dblink (Ora2Pg 18.2/19.0, Oracle 11.2.0.4, Postgresql 10/11b3)

### ISSUE THREAD

**Issue by denoley** [darold/ora2pg#685]
Not working.

In Oracle:

```
CREATE DATABASE LINK DL_BLANK_RSA
 CONNECT TO RSA
 IDENTIFIED BY <password>
 USING '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=arm3-db.tengry.com)(PORT=1521)))(CONNECT_DATA=(SID=arm3tst)))';
```

Must be in Postgres:

```
CREATE SERVER dl_blank_rsa FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=arm3-db.tengry.com)(PORT
CREATE USER MAPPING FOR bso_test2 SERVER dl_blank_rsa OPTIONS (user 'rsa' , password 'secret');
```

But ora2pg generates:

```
CREATE SERVER dl_blank_rsa FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=arm3-db.tengry.com)(PORT
CREATE USER MAPPING FOR bso_test2 SERVER dl_blank_rsa OPTIONS (user 'bso_test2' , password 'secret');
```

You shouldn't replace OPTIONS (user 'rsa'..) , with PG_USER, but only in `CREATE USER MAPPING FOR %PG_USER% SERVER`

**Comment by darold** [comment]
User 'rsa' is the user used to connect to Oracle, the 'bso_test2' user is the PostgreSQL user taken from PG_DSN. I don't think you have the same user both side?

**Comment by denoley** [comment]
I'll try to explain.
I'm migrating Oracle user bso_test2 to Postgresql base bso_test2 schema bso_test2.
Oracle user bso_test2 has private dblink

```
CREATE DATABASE LINK DL_BLANK_RSA
 CONNECT TO RSA
 IDENTIFIED BY <password>
 USING '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=arm3-db.tengry.com)(PORT=1521)))(CONNECT_DATA=(SID=arm3tst)))';
```
which connects to arm3-db.tengry.com as user RSA.

Ora2Pg generates DDL now:
`CREATE USER MAPPING FOR bso_test2 SERVER dl_blank_rsa OPTIONS (user 'bso_test2' , password 'secret');
`

But it's wrong. Oracle user `bso_test2` doesn't connect to `arm3-db.tengry.com` as user **bso_test2**, but as user **RSA**. So, Ora2Pg should generate DDL:
`CREATE USER MAPPING FOR bso_test2 SERVER dl_blank_rsa OPTIONS (user 'rsa' , password 'secret');`

**Comment by denoley** [comment]
If i leave ora2pd DDL:
`CREATE USER MAPPING FOR bso_test2 SERVER dl_blank_rsa OPTIONS (user 'bso_test2' , password 'secret');`
then i have error during execution of Select-statement:
```
ERROR:  connection for foreign table "blank_log4rsa_dl_blank_rsa" cannot be authenticated
DETAIL:  ORA-01017: invalid username/password; logon denied
```

But if i correct DDL as
`CREATE USER MAPPING FOR bso_test2 SERVER dl_blank_rsa OPTIONS (user 'rsa' , password 'secret');`

Sql executed succefully.

**Comment by darold** [comment]
Got it, commit 5771e4c fix unset oracle username when exporting DBLINK from database.

**Comment by denoley** [comment]
Pull last commit:

```
bash-4.2$ git log -2
commit f3ca5b666c48b238ef9a8fd01bcc8bf4129995eb
Merge: 5771e4c e2249c7
Author: Gilles Darold <gilles@darold.net>
Date:   Fri Sep 7 09:19:56 2018 +0200

    Merge pull request #688 from Maxime2/partitioned_fix

    fix  after commit 974c92c

commit e2249c7242271aa102fb24583f96145ffe365ea3
Author: Maxim Zakharov <dp.maxime@gmail.com>
Date:   Fri Sep 7 12:58:01 2018 +1000
```

```
bash-4.2$ md5sum Ora2Pg.pm
5b4e2305abe28c23867b7c791754e809  Ora2Pg.pm
```
Still not working:

```
CREATE SERVER dl_blank_rsa FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=arm3-db.tengry.com)(PORT=1521)))(CONNECT_DATA=(SID=arm3tst)))');
CREATE USER MAPPING FOR bso_test2 SERVER dl_blank_rsa OPTIONS (user 'bso_test2' , password 'secret');
```

i.e. instead of `FOR bso_test2 SERVER dl_blank_rsa OPTIONS (user 'bso_test2' ,` must be `FOR bso_test2 SERVER dl_blank_rsa OPTIONS (user 'rsa' ,`

**Comment by darold** [comment]
I have created the following DBLINK in Oracle 
```
CREATE DATABASE LINK DL_BLANK_RSA
 CONNECT TO RSA
 IDENTIFIED BY mypass
 USING '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521)))(CONNECT_DATA=(SID=ORCL)))';
```
I connect with Ora2Pg using
```
ORACLE_USER    hr
PG_USER             bso_test2
```
then ora2pg exports the DBLINK as expected:
```
CREATE SERVER dl_blank_rsa FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521)))(CONNECT_DATA=(SID=ORCL)))');
CREATE USER MAPPING FOR bso_test2 SERVER dl_blank_rsa OPTIONS (user 'rsa' , password 'secret');
```
I'm afraid I don't understand what's going wrong with your export. Please check again with latest development code I have fixed a problem with dblink from input file but I don't think it is related to your issue as you are exporting dblink from the database.

**Comment by denoley** [comment]
Please, try to create several db_links with different names and see ora2pg result.
For example:

```
CREATE DATABASE LINK DL_BLANK_EKIS
 CONNECT TO BSO_TEST2
 IDENTIFIED BY mypass
 USING '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521)))(CONNECT_DATA=(SID=ORCL)))';

CREATE DATABASE LINK DL_BLANK_RSA
 CONNECT TO RSA
 IDENTIFIED BY mypass
 USING '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521)))(CONNECT_DATA=(SID=ORCL)))';
```

**Comment by darold** [comment]
I have imported your two examples into Oracle and it looks they are exported correctly. I have PG_USER set to `gilles`:
```
CREATE SERVER dl_blank_ekis FOREIGN DATA WRAPPER oracle_fdw
    OPTIONS (dbserver '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521)))(CONNECT_DATA=(SID=ORCL)))');
CREATE USER MAPPING FOR gilles SERVER dl_blank_ekis
    OPTIONS (user 'bso_test2' , password 'secret');

CREATE SERVER dl_blank_rsa FOREIGN DATA WRAPPER oracle_fdw
    OPTIONS (dbserver '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521)))(CONNECT_DATA=(SID=ORCL)))');
CREATE USER MAPPING FOR gilles SERVER dl_blank_rsa
    OPTIONS (user 'rsa' , password 'secret');
```
What do you think it should export instead of that?

**Comment by denoley** [comment]
Yes, it looks correctly. 
May be it because of my ora2pg.conf? Would you attach your ora2pg.cong to compare?
Or error during make install?
```
# make install
Unknown option: u
Installing /usr/local/share/perl5/Ora2Pg.pm
Installing default configuration file (ora2pg.conf.dist) to /etc/ora2pg
Appending installation info to /usr/lib64/perl5/perllocal.pod
```

**Comment by darold** [comment]
The error about Unknown option: u should be related to pod2manI don't think it is relevant. But to be sure you can simply copy the source .pm files into the /usr/local/share/perl5/ directory:
```
cp -r lib/* /usr/local/share/perl5/
```
