### ISSUE TITLE
Could ora2pg to delta oracle record migration?

### ISSUE THREAD

**Issue by fatfrabbit** [darold/ora2pg#69]
Hi,

My work require do load those oracles table to Greenplum(postgres) 
using "delta" load, not loading a whole table?
Could ora2pg do it or you have any other suggestion for me?

Thanks,

Dominica

**Comment by black-snow** [comment]
Hey @darold, is this true as of 2020?

**Comment by darold** [comment]
The WHERE clause is still available yes if this what you are asking. If you are asking if Ora2Pg can be used in incremental migration, have look to the DATADIFF functionality in documentation and configuration file.

**Comment by SebAlbert** [comment]
Note that actually, it seems the `DATADIFF` functionality I added some years ago is only documented in the comments of the sample configuration file, not in the actual documentation. (This may be fine, given that the feature has never left "experimental" status. I only used it a couple of years, without pushing it through rigorous testing, and I don't know if anybody else ever used it.)

**Comment by darold** [comment]
Thanks for the update @SebAlbert I guess that @black-snow will give us feedback so that the feature could be improved.

**Comment by black-snow** [comment]
Since I cannot find `DATADIFF` documented (like SebAlbert said) and the fact that it's *experimental* I probably won't give it a shot.

**Comment by darold** [comment]
Yes every one is missing time.

**Comment by SebAlbert** [comment]
All the feature does is, it still fetches all the data specified by the WHERE clause from Oracle, but then in Postgres it first inserts it into temporary tables and compares it with the actual tables in Postgres and matches existing records; drops unchanged records from the temporary tables and rewrites changed records to UPDATEs (if there is a primary key), and applies the unmatched rows from actual tables as DELETE and the unmatched rows from the temporary (i.e., newly fetched) tables as INSERTs. The purpose is for slowly changing tables not having so many DELETEs followed by INSERTs of the exact same data in Postgres. Plus, you can "hook" a function to be executed on the "difference", in case you want to historize your data in Postgres or do differential updates to aggregates etc.
