### ISSUE TITLE
Problem when exporting bfile

### ISSUE THREAD

**Issue by RickyTR** [darold/ora2pg#691]
When I try to import datas directly from a table with bfile I have the following error:
FATAL: ORA-00932: inconsistent datatypes: expected BINARY got FILE.
Oracle version is 11.2 and I'm using ora2pg  ver. 19.
I'm using COPY mode on a single table and the destination field is of type bytea.

**Comment by darold** [comment]
I have big problem to test this, I'm keep having this error all the time when exporting data from a table with BFILE:
```
ORA-03106: fatal two-task communication protocol error
```
I have created the test case using:
```
CREATE DIRECTORY media_dir AS '/u01/app/datafiles';

CREATE TABLE print_media (product_id NUMBER, ad_id NUMBER, ad_graphic BFILE);

INSERT INTO print_media (product_id, ad_id, ad_graphic)
   VALUES (3000, 31001,
      BFILENAME('MEDIA_DIR', 'import.log'));
```
I don't know whet this error mean. If you have different SQL script to try to reproduce your issue please post it here.

**Comment by darold** [comment]
Finally I take time to fix that annoying issue. Commit e1f13ba might solve it.
