### ISSUE TITLE
Can't use string ("("{""2001"",""8307"",""(1,1,)"","...) as an ARRAY ref while "strict refs" in use

### ISSUE THREAD

**Issue by threenotrump** [darold/ora2pg#692]
Hi Mr Darold 

I have a problem exporting a table.

Can't use string ("("{""2001"",""8307"",""(1,1,)"","...) as an ARRAY ref while "strict refs" in use at /usr/local/share/perl5/Ora2Pg/GEOM.pm line 163.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(HOST=xxxx)(PROTOCOL=tcp)(PORT=1526))(ADDRESS=(HOST=xxx)(PROTOCOL=tcp)(PORT=1521)))(CONNECT_DATA=(SID=xxx))) at /usr/local/share/perl5/Ora2Pg/GEOM.pm line 163.

ora2pg version is Ora2Pg v19.0

Thank you in advance.

**Comment by darold** [comment]
Hi,

I need a dump with the table DDL and a set of data generating this problem. If you want you can send it to my private email gilles AT darold DOT net.

Regards,

**Comment by threenotrump** [comment]
Ive emailed script and insert statments.

**Comment by darold** [comment]
Got it and useful. Commit 89d20f0 might fix this issue.

**Comment by threenotrump** [comment]
Hi Mr Darold

I updated the ora2pg but still getting the error below.

Best Regards

Burak Yurdakul

[2018-09-19 09:59:56] DEBUG: Formatting bulk of 10000 data (real: 192 rows) for PostgreSQL.
Can't use string ("("{""2001"",""8307"",""(32.79998"...) as an ARRAY ref while "strict refs" in use at /usr/local/share/perl5/Ora2Pg/GEOM.pm line 163.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(HOST=xxx)(PROTOCOL=tcp)(PORT=1526))(ADDRESS=(HOST=xxx)(PROTOCOL=tcp)(PORT=1521)))(CONNECT_DATA=(SID=xxx))) at /usr/local/share/perl5/Ora2Pg/GEOM.pm line 163.

**Comment by darold** [comment]
Please send me your anonymized ora2pg.conf file and the ora2pg command you are using.

**Comment by threenotrump** [comment]
Ive sent conf file and command.

**Comment by darold** [comment]
I can not reproduce the issue using your configuration file, I thinks your Ora2Pg installation have not been fully updated. Proceed as follow:
```
wget https://github.com/darold/ora2pg/archive/master.zip
unzip master.zip
cd ora2pg-master/
perl Makefile.PL
make
sudo make install
```
If this is already done please report the following checksum:
```
md5sum /usr/local/share/perl5/Ora2Pg.pm
md5sum /usr/local/share/perl5/Ora2Pg/GEOM.pm
```
I have the following:
```
91bfad69b7534dc092b9c0dc5ca8c731  /usr/local/share/perl/5.26.1/Ora2Pg.pm
1bb88a83d46166e90f629d2ebe6406c1  /usr/local/share/perl/5.26.1/Ora2Pg/GEOM.pm
```

**Comment by threenotrump** [comment]
Hi Mr Darold 

Ive downloaded the file from https://github.com/darold/ora2pg/archive/v19.0.tar.gz and made a fresh install.

I also proceeded as you instructed and my md5sum s are below.

1eabac6e3913e62c60cb1134a83db534  /usr/local/share/perl5/Ora2Pg.pm

d8b7d575e7e19b3a86cbf9ad311737b0  /usr/local/share/perl5/Ora2Pg/GEOM.pm

**Comment by darold** [comment]
Your are downloading latest release, it is now far from latest development code and most of all does not contains the last fixes. Please download and use the archive at `https://github.com/darold/ora2pg/archive/master.zip`

**Comment by threenotrump** [comment]
Thank you very much. After installing the ora2pg from master.zip I can export these tables.

Best Regards

Burak Yurdakul

**Comment by darold** [comment]
Good news. Thanks for the report.
