### ISSUE TITLE
Problème d'import de package suite à conversion avec ora2pg

### ISSUE THREAD

**Issue by joguess** [darold/ora2pg#696]

**Comment by joguess** [comment]
je n'ai pas l'impression qu'ora2pg ait fonctionné.

**Comment by joguess** [comment]
bonjour je suis désolé j'ai utilisé la version que vous m'avez envoyé via le lien j'ai toujours le même problème avec current_setting.

Je créé un projet : 
 ora2pg --project_base /home/jj771560/Documents/Migration --init_project cracopsql

j'exporte mes objets : 

jj771560@utl42644:~/Documents/Migration/cracopsql$ ./export_schema.sh 
[========================>] 212/212 tables (100.0%) end of scanning.                          
[========================>] 11/11 objects types (100.0%) end of objects auditing.     
Running: ora2pg -p -t TABLE -o table.sql -b ./schema/tables -c ./config/ora2pg.conf
[========================>] 212/212 tables (100.0%) end of scanning.                          
[========================>] 212/212 tables (100.0%) end of table export.                 
Running: ora2pg -p -t PACKAGE -o package.sql -b ./schema/packages -c ./config/ora2pg.conf
[========================>] 6/6 packages (100.0%) end of output.      
Running: ora2pg -p -t VIEW -o view.sql -b ./schema/views -c ./config/ora2pg.conf
[========================>] 36/36 views (100.0%) end of output.                       
Running: ora2pg -p -t GRANT -o grant.sql -b ./schema/grants -c ./config/ora2pg.conf
Running: ora2pg -p -t SEQUENCE -o sequence.sql -b ./schema/sequences -c ./config/ora2pg.conf
[========================>] 0/0 sequences (100.0%) end of output.
Running: ora2pg -p -t TRIGGER -o trigger.sql -b ./schema/triggers -c ./config/ora2pg.conf
[========================>] 265/265 triggers (100.0%) end of output.                          
Running: ora2pg -p -t FUNCTION -o function.sql -b ./schema/functions -c ./config/ora2pg.conf
[========================>] 4/4 functions (100.0%) end of output.         
Running: ora2pg -p -t PROCEDURE -o procedure.sql -b ./schema/procedures -c ./config/ora2pg.conf
[========================>] 9/9 procedures (100.0%) end of output.              
Running: ora2pg -p -t TABLESPACE -o tablespace.sql -b ./schema/tablespaces -c ./config/ora2pg.conf
Running: ora2pg -p -t PARTITION -o partition.sql -b ./schema/partitions -c ./config/ora2pg.conf
[========================>] 0/0 partitions (100.0%) end of output.
Running: ora2pg -p -t TYPE -o type.sql -b ./schema/types -c ./config/ora2pg.conf
[========================>] 0/0 types (100.0%) end of output.
Running: ora2pg -p -t MVIEW -o mview.sql -b ./schema/mviews -c ./config/ora2pg.conf
[========================>] 0/0 materialized views (100.0%) end of output.
Running: ora2pg -p -t DBLINK -o dblink.sql -b ./schema/dblinks -c ./config/ora2pg.conf
[========================>] 0/0 dblink (100.0%) end of output.
Running: ora2pg -p -t SYNONYM -o synonym.sql -b ./schema/synonyms -c ./config/ora2pg.conf
[========================>] 0/0 synonyms (100.0%) end of output.
Running: ora2pg -p -t DIRECTORY -o directorie.sql -b ./schema/directories -c ./config/ora2pg.conf
[========================>] 0/0 directory (100.0%) end of output.
Running: ora2pg -t PACKAGE -o package.sql -b ./sources/packages -c ./config/ora2pg.conf
[========================>] 6/6 packages (100.0%) end of output.      
Running: ora2pg -t VIEW -o view.sql -b ./sources/views -c ./config/ora2pg.conf
[========================>] 36/36 views (100.0%) end of output.                       
Running: ora2pg -t TRIGGER -o trigger.sql -b ./sources/triggers -c ./config/ora2pg.conf
[========================>] 265/265 triggers (100.0%) end of output.                          
Running: ora2pg -t FUNCTION -o function.sql -b ./sources/functions -c ./config/ora2pg.conf
[========================>] 4/4 functions (100.0%) end of output.         
Running: ora2pg -t PROCEDURE -o procedure.sql -b ./sources/procedures -c ./config/ora2pg.conf
[========================>] 9/9 procedures (100.0%) end of output.              
Running: ora2pg -t PARTITION -o partition.sql -b ./sources/partitions -c ./config/ora2pg.conf
[========================>] 0/0 partitions (100.0%) end of output.
Running: ora2pg -t TYPE -o type.sql -b ./sources/types -c ./config/ora2pg.conf
[========================>] 0/0 types (100.0%) end of output.
Running: ora2pg -t MVIEW -o mview.sql -b ./sources/mviews -c ./config/ora2pg.conf
[========================>] 0/0 materialized views (100.0%) end of output.


To extract data use the following command:

ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg.conf

et là j'ai toujours le même problème : 

jj771560@utl42644:~/Documents/Migration/cracopsql/schema/packages/pkg_crayon$ cat longueurfabrice_package.sql 
-- Generated by Ora2Pg, the Oracle database Schema converter, version 18.1
-- Copyright 2000-2017 Gilles DAROLD. All rights reserved.

SET client_encoding TO 'UTF8';
SET search_path = craco,public,dbms_output,utl_file,oracle;


CREATE OR REPLACE FUNCTION PKG_CRAYON.longueurfabrice (crayon CR_CRAYON.nom_crayon%type) RETURNS VOID AS $body$
BEGIN
    select type into current_setting('PKG_CRAYON.TypCray')::TYPE_CRAYON.type%type from type_crayon where nom_crayon = crayon;
    if current_setting('PKG_CRAYON.TypCray')::TYPE_CRAYON.type%type = 'FABRICE' then
     begin
	 select LONG_COL_COMB into current_setting('PKG_CRAYON.long_comb')::CR_CRAYON_CARACTERISE.LONG_COL_COMB_MES%type from CR_FABRICE where nom_fabrice = crayon;
     end;
    end if;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION PKG_CRAYON.longueurfabrice (crayon CR_CRAYON.nom_crayon%type) FROM PUBLIC;

jj771560@utl42644:~/Documents/Migration/cracopsql/schema/packages$ ll
total 32
-rw-r--r-- 1 jj771560 hors-cea 5664 24 sept. 13:40 package.sql
drwxr-xr-x 2 jj771560 hors-cea 4096 24 sept. 13:40 pkg_crayon
drwxr-xr-x 2 jj771560 hors-cea 4096 24 sept. 13:40 pkg_gaine
drwxr-xr-x 2 jj771560 hors-cea 4096 24 sept. 13:40 pkg_gaz
drwxr-xr-x 2 jj771560 hors-cea 4096 24 sept. 13:40 pkg_irrad
drwxr-xr-x 2 jj771560 hors-cea 4096 24 sept. 13:40 pkg_past
drwxr-xr-x 2 jj771560 hors-cea 4096 24 sept. 13:40 pkg_rep

jj771560@utl42644:~/Documents/Migration/cracopsql$ psql -d dev < ./schema/packages/package.sql
SET
SET
DROP SCHEMA
CREATE SCHEMA
SET
SET
psql:./schema/packages/pkg_crayon/longueurfabrice_package.sql:21: NOTICE:  référence de type cr_crayon.nom_crayon%TYPE convertie en character varying
psql:./schema/packages/pkg_crayon/longueurfabrice_package.sql:21: ERREUR:  « current_setting » n'est pas une variable connue
LINE 3:     select type into current_setting('PKG_CRAYON.TypCray')::...
                             ^

**Comment by joguess** [comment]
$ ora2pg -v
Ora2Pg v19.0

**Comment by darold** [comment]
bonjour,

Si vous regardez le fichier de sortie longueurfabrice_package.sql, l'entête montre que vous utilisez une version 18.1 d'Ora2Pg
```
-- Generated by Ora2Pg, the Oracle database Schema converter, version 18.1
```
Il faut que vous réinstalliez Ora2Pg, l'installation par les sources copie le script ora2pg dans /usr/local/bin/ il est possible que vous ayez une version installée par package dans /usr/bin/

**Comment by joguess** [comment]
Bonjour, vous avez raison pour l'en-tête des fichiers, par contre lorsque je tape la commande : 
 ora2pg -v
J'ai : 

Ora2Pg v19.0
par contre je pense que ma variable  : 

PERL5LIB

n'était pas à jour pour la compilation du Makefile en perl de la V19.

**Comment by joguess** [comment]
voici ma procédure : 

$ perl Makefile.PL PREFIX=/home/xxxx/Documents/Ora2pg/install
Checking if your kit is complete...
Looks good
Writing Makefile for Ora2Pg

Done...
------------------------------------------------------------------------------
Please read documentation at http://ora2pg.darold.net/ before asking for help
------------------------------------------------------------------------------
Now type: make && make install
$ make && make install
cp lib/Ora2Pg.pm blib/lib/Ora2Pg.pm
cp lib/Ora2Pg/GEOM.pm blib/lib/Ora2Pg/GEOM.pm
cp lib/Ora2Pg/PLSQL.pm blib/lib/Ora2Pg/PLSQL.pm
cp lib/Ora2Pg/MySQL.pm blib/lib/Ora2Pg/MySQL.pm
cp scripts/ora2pg blib/script/ora2pg
/usr/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/ora2pg
cp scripts/ora2pg_scanner blib/script/ora2pg_scanner
/usr/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/ora2pg_scanner
Manifying blib/man3/ora2pg.3
Installing /home/xx/Documents/Ora2pg/install/usr/local/bin/ora2pg_scanner
Installing /home/xxx/Documents/Ora2pg/install/usr/local/bin/ora2pg
Installing default configuration file (ora2pg.conf.dist) to /home/xxx/Documents/Ora2pg/install/etc/ora2pg
Appending installation info to /home/xxx/Documents/Ora2pg/install/usr/lib64/perl5/perllocal.pod

**Comment by joguess** [comment]
test : 

$ ora2pg -p -t PACKAGE  -o psqlPCK.sql -b ./sources -c ./ora2pg.conf
$ more psqlPCK.sql
-- Generated by Ora2Pg, the Oracle database Schema converter, version 19.0
-- Copyright 2000-2018 Gilles DAROLD. All rights reserved.

ça marche, merci.

**Comment by joguess** [comment]
Est-il possible de vérifier que la variable système PERL5LIB pointe bien vers  la dernière version installée?

**Comment by darold** [comment]
`perl -V | grep PERL5LIB` ?

**Comment by joguess** [comment]
yes now it is  :


PERL5LIB="/home/jj771560/Documents/Ora2pg/ora2pg-v19/lib:/home/jj771560/Documents/Perl/Time/install/lib64/perl5:/export/home/jj771560/Documents/Ora2pg/install/lib64/perl5:"



before it was


PERL5LIB="/home/jj771560/Documents/Ora2pg/ora2pg-v18/lib:/home/jj771560/Documents/Perl/Time/install/lib64/perl5:/export/home/jj771560/Documents/Ora2pg/install/lib64/perl5:"


________________________________
De : Gilles Darold <notifications@github.com>
Envoyé : mardi 25 septembre 2018 10:42:54
À : darold/ora2pg
Cc : joguess; Author
Objet : Re: [darold/ora2pg] Problème d'import de package suite à conversion avec ora2pg (#696)


perl -V | grep PERL5LIB ?

**Comment by joguess** [comment]
il faudrait pouvoir vérifier cela lors de la mise à jour d'ora2pg, c'est ce que je voulais dire.

**Comment by joguess** [comment]
Dans le script perl Makefile.PL, vérifier que PERL5LIB est bien valorisée sinon faire un export vers la nouvelle version, mais je ne sais si c'est possible techniquement de vérifier cela en amont de la mise à jour.

**Comment by darold** [comment]
L'installateur d'Ora2Pg n'a pas vocation à remplacer complètement les taches de l'administrateur système :-) Sinon il faut passer par les packages yum, apt ou autre.

**Comment by joguess** [comment]
Ok.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by joguess** [comment]
Si je peux me permettre je vous suggère d'intervertir les fonctions et les vues dans votre script d'import.

Car bien souvent des vues dépendent de fonctions. Donc les fonctions doivent être créées avant les vues.

EXPORT_TYPE="TYPE TABLE PACKAGE FUNCTION GRANT SEQUENCE TRIGGER VIEW PROCEDURE TABLESPACE PARTITION MVIEW DBLINK SYNONYM DIRECTORY"

Cdlt.


________________________________
De : Josselin JOLY <josselin_joly@hotmail.com>
Envoyé : mardi 25 septembre 2018 11:37:42
À : darold/ora2pg
Objet : Re: [darold/ora2pg] Problème d'import de package suite à conversion avec ora2pg (#696)

Ok.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
