### ISSUE TITLE
Migrate Oracle Package to Postgres

### ISSUE THREAD

**Issue by joguess** [darold/ora2pg#697]
Hello Can you explain me how to use ora2pg with the generation of a project to migrate Oracle package into Postgres functions ?

Pouvez vous me communiquer la procédure pour migrer des packages Oracle en Postgres svp ? 

D'avance merci

**Comment by darold** [comment]
To export package just execute the following command:
```
ora2pg -p -t PACKAGE -o package.sql -b ./schema/packages -c ./config/ora2pg.conf
```
`-p` is responsible of the translation, without this option you will obtain the source code
`-b` is the base directory where generated files will be saved.

**Comment by darold** [comment]
Well yes, command line options override settings in configuration file.

**Comment by joguess** [comment]
Ok, THks !
