### ISSUE TITLE
copy creates multiple records of same row

### ISSUE THREAD

**Issue by seadba** [darold/ora2pg#700]
i have an interesting problem (maybe) - i used latest version to copy oracle to postgres - copy went fine- when creating primary keys got following error:
```
ERROR:  could not create unique index "branch_pkey"
DETAIL:  Key (id)=(122) is duplicated.
```

in oracle
```
SQL> select count(*) from branch;

  COUNT(*)
----------
     34681

SQL> select count(*) from branch
  2  where id = '122';

  COUNT(*)
----------
         1
```

in postgres

```
asysdev=#   select count(*) from branch;
 count
-------
 34681
(1 row)

asysdev=# select count(*) from branch where id =  '122';
 count
-------
     3
(1 row)
```

dropped and reloaded table

```
[root@a]# ./load.sh
[========================>] 1/1 tables (100.0%) end of scanning.     
[======>                  ]  9000/34755 total rows (25.9%) - (3 sec., avg: 3000
[=================>       ] 25000/34755 total rows (71.9%) - (6 sec., avg: 4166
[=======================> ] 34681/34755 rows (99.8%) Table BRANCH (8 sec., 4335 recs/sec)                     
[=======================> ] 34681/34755 total rows (99.8%) - (9 sec., avg: 3853
[=======================> ] 34681/34755 rows (99.8%) on total estimated data (9 sec., avg: 3853 tuples/sec) 
```

**Comment by darold** [comment]
What is the type of the id columns?

Try to dump your data into a file (comment PG_DSN in ora2pg.conf) and see statements in output file.
```
mkdir tmp_outdir/
ora2pg -c ora2pg.conf -t INSERT -a BRANCH -b tmp_outdir/
```
Post here the INSERT statement related to id = 122, some may have extra space.

**Comment by seadba** [comment]
what are the E values?

1st row
VALUES (95016,E'122',

2nd row

VALUES (95018,E'122'

3rd row


 VALUES (95105,E'122'

**Comment by seadba** [comment]
interesting

SQL> select recnum,id,length(id)
  2  from anpesil.branch
  3   where recnum in (95016,95018,95105);

    RECNUM ID                   LENGTH(ID)
---------- -------------------- ----------
     95016 122                           5
     95018 122                           4
     95105 122                           3

**Comment by darold** [comment]
I guess that if you have an unique index defined just on column ID at the oracle side you have to blame Oracle for the arrangement with integrity :-D

**Comment by seadba** [comment]
yes its all good - i wil talk to the devs - thanks very much  great tool
