### ISSUE TITLE
Error while converting a customized default value of a column from Oracle to postgres

### ISSUE THREAD

**Issue by rejo-oommen** [darold/ora2pg#702]
Is there a way to customize the DEFAULT value of a field. With the below example, I am getting an error while it converts into postgres

Ex:
*Oracle Field:*
`"UPDATED_TS" NUMBER DEFAULT (sysdate - to_date('01-Jan-1970', 'dd-Mon-yyyy'))*24*60*60*1000 NOT NULL ENABLE`

*Converted by ora2pg to postgres syntax:*
`updated_ts bigint NOT NULL DEFAULT (LOCALTIMESTAMP - to_date('01-Jan-1970','dd-Mon-yyyy'))*24*60*60*1000`

*Error from postgres : *
`ERROR:  column "updated_ts" is of type bigint but default expression is of type interval`

Would like to have only the DEFAULT updated to:
`updated_ts bigint not null default (extract(epoch from now()) * 1000))`

If there is an alternative please suggest, else  Is there feasibility to add something like 

`REPLACE_COL_DEFAULT TBNAME1:COLNAME:CUR_DEFAULT_VALUE:EXP_DEFAULT_VALUE`

Ex:
`REPLACE_COL_DEFAULT TBNAME1:updated_ts:"(LOCALTIMESTAMP - to_date('01-Jan-1970','dd-Mon-yyyy'))*24*60*60*1000" : "(extract(epoch from now()) * 1000))"`

**Comment by rejo-oommen** [comment]
Yes Darold. I do have a lot of these in my oracle DB. 
Wanted to know if there was any workaround in the tool. Script is something that I could do to replace it.

**Comment by darold** [comment]
Last three commits add this special replacement. Let me know if there is any issue.
