### ISSUE TITLE
Error starting ora2pg first time SLES 10

### ISSUE THREAD

**Issue by sanchedo** [darold/ora2pg#703]
Hi,

sorry if I made something wrong. I tried to follow the documentation, but when I try to start ora2pg (19.1 version and tried 19.0 too), I get the message:

ora2pg -u <user> -w <passwd>
_Backslash found where operator expected at /usr/lib/perl5/site_perl/5.8.8/Ora2Pg/PLSQL.pm line 327, near "while ( $str =~ s/\"
  (Might be a runaway multi-line // string starting on line 326)
        (Do you need to predeclare while?)
Scalar found where operator expected at /usr/lib/perl5/site_perl/5.8.8/Ora2Pg/PLSQL.pm line 327, near "%OUTERJOIN$class"
        (Missing operator before $class?)
syntax error at /usr/lib/perl5/site_perl/5.8.8/Ora2Pg/PLSQL.pm line 327, near "while ( $str =~ s/\"
syntax error at /usr/lib/perl5/site_perl/5.8.8/Ora2Pg/PLSQL.pm line 335, near "# Rewrite all decode()"
  (Might be a runaway multi-line )) string starting on line 327)
Compilation failed in require at /usr/lib/perl5/site_perl/5.8.8/Ora2Pg.pm line 1331.
BEGIN failed--compilation aborted at /usr/lib/perl5/site_perl/5.8.8/Ora2Pg.pm line 1331.
Compilation failed in require at /usr/bin/ora2pg line 27.
BEGIN failed--compilation aborted at /usr/bin/ora2pg line 27._

I use Oracle InstantClient 11.2.0.4, and Perl 5.8.8
Installation of Oracle Client, Perl DBI and Ora2PG seemed to go well. But unfortunatelly (for me) I'm not able to start it.

**Comment by darold** [comment]
I don't know what force you to use Ora2Pg on a more than 10 years old Perl version but I really encourage you to make a jump in the present or at least use Perl v5.10 as explain in the documentation.
```
    You also need a modern Perl distribution (perl 5.10 and more). To
    connect to a database and proceed to his migration you need the DBI Perl
    module > 1.614.
```
Ora2Pg can work on a remote server/computer, you don't need to install it on your old Oracle server if this is what you are trying to do.
