### ISSUE TITLE
ora2pg : PRESERVE_CASE = 1 : Not working for case sensitive db objects

### ISSUE THREAD

**Issue by rishmax** [darold/ora2pg#704]
My oracle database are having tables in capitals and views in Camel Case. There are more than 100 tables and views with same name. Like DB_TAB1 (Table) and Db_Tab1 (view). 
When I am  trying to migrate it to postgres (as postgres in case insensitive), it started failing as it cannot create two objects with same name.
Then I modified the parameter PRESERVE_CASE to 1 in the conf file and re-run the command and I found nothing in the output file. No DDL was captured. We only got following:

\set ON_ERROR_STOP ON

-- Nothing found of type TABLE
...
..
Please let me know how to get the output file with proper case of database object.

**Comment by darold** [comment]
Well its a very bad idea to have tables and views with the same name and fortunately PostgreSQL doesn't allow it. If you want to reproduce this bad practice in PostgreSQL PRESERVE_CASE may help you. Just export tables with PRESERVE_CASE disabled and export views with PRESERVE_CASE enabled.

I don't know what command and configuration file you are using to have the "Nothing found" message, but I'm sure it should works. Post your ora2pg commands line and configuration file. Or does your views are SYNONYM?

Best regards,

**Comment by darold** [comment]
Don't no what to do with this issue. I think it's a miss use, I'm closing it.
