### ISSUE TITLE
REPLACE_QUERY Case sensitivity

### ISSUE THREAD

**Issue by nevzatgul** [darold/ora2pg#705]
Hi 

REPALCE_QUERY EMPLOYEES[ID,NAME,SURNAME,EMAIL FROM EMPLOYEES]  is work 

but following query  does not work 

REPLACE_QUERY "Employees"["Id","Name","Surname","Email" FROM "Employees"]

What can be the problem?

**Comment by darold** [comment]
If you look at the REPLACE_QUERY example in the configuration file you will find your mistake:
```
REPLACE_QUERY  EMPLOYEES[SELECT e.id,e.fisrtname,lastname FROM EMPLOYEES e JOIN EMP_UPDT u ON (e.id=u.id AND u.cdate>'2014-08-01 00:00:00')]
```
You have to enter a full query, in your example the SELECT is missing.
