### ISSUE TITLE
ora2pg 19/19.1 migration issue

### ISSUE THREAD

**Issue by buragaddapavan** [darold/ora2pg#707]
i was using ora2pg 18 and it works fine

now i started using ora2pg 19 and used same config file . Issue is, it exports only first two object types mentioned in config file

in config : 
TYPE    TABLE PARTITION GRANT FUNCTION  PROCEDURE SEQUENCE DBLINK

in my case , ora2pg 19 exports only table and partitions....

can u tell me why ora2pg 19 doesnt export all type objects ?

**Comment by darold** [comment]
Does ora2pg return an error message or just terminate after table and partition export?

**Comment by darold** [comment]
I can't reproduce this issueand I do not recommend the use of multiple export type. Please use `--init_projet` option instead and the auto generated script export_all.sh

**Comment by buragaddapavan** [comment]
No errors... Ora2pg output displays
Dumping package...
Parsing function .....
Add synonym definition..
Add views definition....
...

But in output SQL file , packages/views doesn't exist
