### ISSUE TITLE
Ora2pg generates incorrect table syntax (CURRENT_TIMESTAMP AT TIME ZONE 'US/Pacific')

### ISSUE THREAD

**Issue by buragaddapavan** [darold/ora2pg#715]
Ora2pg 18/19 generates below DDL but it fails while executing in postgres db.

Create table mcall(
Trm varchar(10) not null,
Intercept_time timestamp not null CURRENT_TIMESTAMP AT TIME ZONE 'US/Pacific'
);

I modified it to below and it works fine. Please fix it

Create table mcall(
Trm varchar(10) not null,
Intercept_time timestamp not null (CURRENT_TIMESTAMP AT TIME ZONE 'US/Pacific')
);

**Comment by darold** [comment]
Please upgrade to latest version of Ora2Pg this should be fixed. If not post the DDL of the Oracle table.

**Comment by buragaddapavan** [comment]
![15402957445327393863867300261913](https://user-images.githubusercontent.com/43881608/47358876-b7404780-d6e8-11e8-81c0-9c23855062af.jpg)

**Comment by darold** [comment]
Same as other issue, please don't use screenshot this is not helpful at all.

**Comment by darold** [comment]
Commit bfe114b solves this issue.
