### ISSUE TITLE
Wrong conversion of character classes in regular expressions

### ISSUE THREAD

**Issue by jselbach** [darold/ora2pg#716]
We have a CHECK constraint on a column containing a REGEXP_LIKE with a character class. Something like:

CHECK (some_column IS NULL OR REGEXP_LIKE(some_column, '[[:alpha:]]')

This gets converted to

CHECK (coalesce(some_column::text, '') = '' OR some_column ~ '[[alpha:]]')

Notice the missing colon before alpha. This happens even when PLSQL_PGSQL is set to 0.

After some digging, the offending regex is in Ora2PG/PLSQL.pm (line 645 in V19.1):

        # Remove leading : on Oracle variable
        $str =~ s/([^\w:]+):(\d+)/$1\$$2/igs;
        $str =~ s/([^\w:]+):(\w+)/$1$2/igs; # <-- this one

Is there any way around this? I did not come up with a fix for the regex that covers all cases. We'd be fine with disabling PLSQL_PGSQL but this sadly doesn't work.

**Comment by darold** [comment]
Thanks for the report. Please upgrade to latest development code, last commit b2c1377 solves this issue.

**Comment by jselbach** [comment]
Thanks for the quick response. Your commit fixes my particular problem, but what if someone decided to have a variable named (for example) :cntrl in their PL/SQL code? I'm not sure this can be fixed by a single regex. You'd have to check if both prefix [: and suffix :] are present at the same time and only inside strings.

**Comment by darold** [comment]
Right I forgot the last `:`, commit 99656fc fix it.

**Comment by jselbach** [comment]
Hmm, simpler than I thought. I tried a few test cases and it looks fine to me now. 

Thank you very much for your effort. :+1:
