### ISSUE TITLE
import_ALL.sh

### ISSUE THREAD

**Issue by amadgula** [darold/ora2pg#717]
Hello,
i am using ora2pg 19.1
my conf file contains only these lines:
```
[root@localhost config]# more sma_ora2pg.conf
# Set Oracle database connection (datasource, user, password)
ORACLE_DSN      dbi:Oracle:host=localhost;sid=SIDT;port=1521
ORACLE_USER     system
ORACLE_PWD      system
# Oracle schema/owner to use
SCHEMA          SMA
TYPE            TABLE PACKAGE COPY VIEW GRANT SEQUENCE TRIGGER FUNCTION PROCEDURE TYPE
DROP_KEY        1
OUTPUT          SMA_output.sql
```

i created the test_project and ran export_schema.sh using this sma_ora2pg.conf file successfully.
After that I ran the
```
ora2pg -t COPY -o data.sql -b $namespace/data -c $namespace/config/sma_ora2pg.conf
```
this created the data.sql successfully.

Now I used import_all.sh 
```
[postgres@localhost test_project]$ ./import_all.sh -d sma -o sma -U sma
finally I get this error:
Running: psql -U sma -d sma -f ./data/data.sql
Password for user sma:
SET
SET
BEGIN
COPY 5
COPY 35
psql:./data/data.sql:178: ERROR:  insert or update on table "converts_user" violates foreign key constraint "sys_c004357"
DETAIL:  Key (firm_id)=(0) is not present in table "firm".
ERROR: an error occurs when importing file ./data/data.sql.
```

please help adn yopur input is high;y appreciated.

**Comment by darold** [comment]
You should not import index and constraints before importing data. To skip import of constraints use the `-I` option of the `import_all.sh` command, with you example:
```
./import_all.sh -d sma -o sma -U sma -I
```
and the once it is done, import only indexes and constraints using the `-i` option:
```
./import_all.sh -d sma -o sma -U sma -i
```

Use `./import_all.sh -?` to see all options.

PS: I have obfuscated some information that you've posted, hostname, ip address, login and password must be anonymized.

**Comment by amadgula** [comment]
thank you very much

**Comment by amadgula** [comment]
Hi Darold, i used the following to create data.sql (from export_schema.sh) 
ora2pg -t COPY -o data.sql -b $namespace/data -c $namespace/config/sma_ora2pg.conf

this data.sql included create table statements along with indexes and constraints, that is causing the problem while running the import.

need a switch to create indexes adn constraints files seperately wile generating the data.sql .

any suggestion ? thanks appreciated
Ashwath

**Comment by darold** [comment]
Hi,

The COPY action only dump data there is no create table DDL. If you have enabled DROP_INDEXES and DROP_FKEY you will have drop statements before data import and create statement after import in file data.sql. As explain in the note above the best way is to only create constraints and indexes after data import.
