### ISSUE TITLE
Loading data from temporary table

### ISSUE THREAD

**Issue by denoley** [darold/ora2pg#718]
The abln_transition is Oracle temporary table, so it doesn't transfer to postgres via ora2pg. 
But when i execute 
`ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg.conf`
i've got error:

[========================>] 90/90 tables (100.0%) end of scanning.
DBD::Pg::db do failed: ERROR:  relation "abln_transition" does not exist at /var/lib/pgsql/perl5/lib/perl5/Ora2Pg.pm line 5595.
FATAL: ERROR:  relation "abln_transition" does not exist

**Comment by darold** [comment]
I'm not able to reproduce this problem, when I create a temporary table in Oracle it is not in the exported tables. Do you have the Oracle DDL used to create this temporary table? Maybe I'm missing something.
