### ISSUE TITLE
Index/PK when export partitioned table as nopartitioned.

### ISSUE THREAD

**Issue by denoley** [darold/ora2pg#721]
I set DISABLE_PARTITION=1, didn't shose PARTITION in EXPORT SECTION.
Ora2pg generates DDL for oracle partition table in` table.sql`:
`CREATE TABLE kbln_info (...) PARTITIONED BY ();`
Ora2pg didn't generate PK/Index DDL for this table in `CONSTRAINTS_table.sql INDEXES_table.sql, `
but create scripts `partition.sql` and `PARTITION_INDEXES_partition.sql` in wich present DDL for index/fk/pk for each partitions:
```
CREATE INDEX sys_subp11395_blank_series ON sys_subp11395 (blank_number_int,blank_series);
ALTER TABLE sys_subp11395 ADD PRIMARY KEY (info_id);
```

**Comment by darold** [comment]
Commits 9fcba81 and c6979b5 might fix this issue.
