### ISSUE TITLE
Missing FROM-clause entry from table 

### ISSUE THREAD

**Issue by cloudridercanada** [darold/ora2pg#722]
Hi,
the export went all good,  however, when I am trying to import, I get this error that I have no idea how to fix:
psql:./data/VISIT_ENTITY_data.sql:2504: ERROR:  missing FROM-clause entry for table "visit_entity_id_seq"
LINE 1: SELECT visit_entity_id_seq.NEXTVAL
I have a lot of errors like this. 
Any ideas what could be causing this ? 
Thanks.

**Comment by cloudridercanada** [comment]
Line 2504 in the sql file is actuall \.

**Comment by darold** [comment]
Please send file /data/VISIT_ENTITY_data.sql gzipped to my private email < gilles AT darold DOT net > I need to see exactly what is in this file to understand the problem.  Also join your ora2pg command line and configuration file to try to reproduce the issue.

**Comment by cloudridercanada** [comment]
Well, I tried another export from scratch and the outcome was the same. The conf file I sent you is the best in terms of avoiding ORA errors and memory allocation issues. The export goes well, but a set of specific tables fail to load with the same error. Not all the tables show the error.

**Comment by darold** [comment]
I'm closing this issue, I don't see any ora2pg issue here, this must be the result of a wrong use.
