### ISSUE TITLE
mdsys Error while importing data directly from Oracle

### ISSUE THREAD

**Issue by rejo-oommen** [darold/ora2pg#726]
Getting the following error while carrying out a direct import of data from Oracle to postgres.
I was not able to detect why the **mdsys** schema was being checked as the tool by default skips this schema.

[2018-11-12 09:08:08] Isolation level: SET TRANSACTION READ ONLY
[2018-11-12 09:08:08] Retrieving partitions information...
**DBD::Pg::db do failed: ERROR:  schema "mdsys" does not exist at /usr/local/share/perl5/Ora2Pg.pm line 5595.**
[2018-11-12 09:10:20] FATAL: ERROR:  schema "mdsys" does not exist
Aborting export...
ERROR: an error occurs when importing data.

**Comment by darold** [comment]
What is the value of the SCHEMA directive in your ora2pg.conf and are you connecting using DBA privilege?

**Comment by rejo-oommen** [comment]
Apologies for the delay to reply. The SCHEMA was not specified. Specifying it worked. I was under assumption that it would skip these system schemas by default.

**Comment by darold** [comment]
I found cases where system schemas was not excluded when no schema was provided. Commit 368ad32 fixes them.
