### ISSUE TITLE
CHECK constraints missing

### ISSUE THREAD

**Issue by venkatsusarla** [darold/ora2pg#728]
We have used ora2pg 18.2 to do our migration from Oracle to Postgres,but now we see that all CHECK constraints which begins with name SYS_ are missing when it came to Postgres.

This issue was not captured during the application testing in Dev,UAT and Prod too,issue got highlighted when application had report generation job run and there are duplicate rows reported in their daily jobs.

what could be the reason?

The conf file we used:
------------------------
ORACLE_HOME     
ORACLE_DSN      dbi:Oracle:host=XXX.XXX.XXX.XXX;sid=XXXXX;port=XXXXX
ORACLE_USER   
ORACLE_PWD    
USER_GRANTS     0
EXPORT_SCHEMA   1
CREATE_SCHEMA   1
SCHEMA <username>
PG_SCHEMA <username>
TYPE TABLE PACKAGE INSERT COPY VIEW GRANT SEQUENCE TRIGGER FUNCTION PROCEDURE TABLESPACE TYPE PARTITION FDW MVIEW KETTLE QUERY
EXTERNAL_TO_FDW         1
#SKIP   fkeys pkeys ukeys indexes checks
ORA_RESERVED_WORDS      audit,comment,references
USE_RESERVED_WORDS      1
OUTPUT          test.sql
OUTPUT_DIR      <location>
FILE_PER_CONSTRAINT     1
FILE_PER_INDEX          1
FILE_PER_TABLE  1
FILE_PER_FUNCTION      0
PG_NUMERIC_TYPE 1
PG_INTEGER_TYPE 1
DEFAULT_NUMERIC numeric
ENABLE_MICROSECOND      1
DATA_LIMIT      60000
BLOB_LIMIT      1000
NOESCAPE        0
TRANSACTION     serializable
STANDARD_CONFORMING_STRINGS     1
LOG_ON_ERROR            0
LONGREADLEN     104265600
TRIM_TYPE               BOTH
INTERNAL_DATE_MAX       49
JOBS            1
ORACLE_COPIES   1
PARALLEL_TABLES 1
DROP_INDEXES    0
SYNCHRONOUS_COMMIT      0
EXPORT_INVALID  0
PLSQL_PGSQL     1
NULL_EQUAL_EMPTY        0
EMPTY_LOB_NULL          0
PACKAGE_AS_SCHEMA       1
REWRITE_OUTER_JOIN      1
DATE_FUNCTION_REWRITE   1
ESTIMATE_COST           1
COST_UNIT_VALUE        10
DUMP_AS_HTML            1
#TOP_MAX                10
HUMAN_DAYS_LIMIT        5
PG_SUPPORTS_WHEN        1
PG_SUPPORTS_INSTEADOF   1
PG_SUPPORTS_MVIEW       1
PG_SUPPORTS_CHECKOPTION 1
PG_SUPPORTS_IFEXISTS    1
BITMAP_AS_GIN           1
PG_BACKGROUND           0
AUTODETECT_SPATIAL_TYPE 1
CONVERT_SRID            1
DEFAULT_SRID            4326
GEOMETRY_EXTRACT_TYPE   INTERNAL
FDW_SERVER      orcl
MYSQL_PIPES_AS_CONCAT           0
MYSQL_INTERNAL_EXTRACT_FORMAT   0
TRUNCATE_TABLE  1
DISABLE_PARTITION 1

**Comment by darold** [comment]
Ora2Pg do not export constraint starting with `SYS_NC` it is considered as an internal constraint. If this is not the case in your database, please post a DDL for a table creation with the missing constraint to reproduce the problem.

**Comment by venkatsusarla** [comment]
Hi Darold thanks for the reply...after detailed analysis what we observed is when a column is defined with "not null" condition in Oracle it creates constraints with SYS_ naming convention and is not seen when we pull the ddl of the table as CHECK constraint.....when we migrate to Postgres ora2pg takes care of the not null condition of the column but doesn't define specific constraint as Oracle does, hence we don't see that constraints list of Postgres db... correct me if I am wrong.
