### ISSUE TITLE
Meaning of "Details" in report

### ISSUE THREAD

**Issue by AwdotiaRomanowna** [darold/ora2pg#730]
Hi!
I'm not sure what's in Details column in Migration Report. For instance in my report I've got 221 views as a total number but only few are in Details column: does it mean that the rest will be migrated automatically? 
And about "Details of cost assessment per function" - actually the same question - those function are the functions that have to be migrated manually?

**Comment by darold** [comment]
Hi,

The list in the Details column only reports view where there could have some manual rewrite, other have normally no translation issue.

About "Details of cost assessment per function" it depends of the cost weight, if it just report TEST and SIZE information the function may not need to be manually rewritten. Others might need some rewrite.

Regards,
