### ISSUE TITLE
CREATE sequence instead of ALTER sequence

### ISSUE THREAD

**Issue by dtrecu** [darold/ora2pg#731]
Hello,

I have a little problem during my database export. I need to export `ALTER SEQUENCE` commands for my new database, so I put the `DISABLE_SEQUENCE` parameter to 0, and I set the `TYPE` paramater only to `SEQUENCE`.

But in my output SQL file, I always get `CREATE SEQUENCE` commands, even if I put the `DISABLE_SEQUENCE` parameter to 1... Did I get something wrong?

Thanks in advance for your help!

**Comment by darold** [comment]
Hello,

DISABLE_SEQUENCE is only used with data export to restart sequences after data import, in this case you will have ALTER SEQUENCE statement.
