### ISSUE TITLE
Case-sensitivity for function/procedure parameters

### ISSUE THREAD

**Issue by deastr** [darold/ora2pg#732]
Hi,

Is there a way to convert input parameters for function/procedure parameters with same case as the source? `PRESERVE_CASE=1` value seems to work only for object names but since ora2pg doesn't encapsulate parameter names with double quotes they get created lowercase in Postgre.

**Comment by darold** [comment]
Hi,

No, not at this time, I will look into this. Thanks for the report.

**Comment by darold** [comment]
Actually I do not see any interest of doing that. Ora2Pg keep the original case in the function code so I do not really understand why you want to quote them. Does the variables are already quoted in the oracle code?

**Comment by deastr** [comment]
Our data access layer is case sensitive. Since the function input names that return from Postgre provider are lower case and the names in access layer are upper it can't bind them. 

Variables are not quoted in Oracle.

**Comment by darold** [comment]
Closing as won't be done.
