### ISSUE TITLE
Error in creation of default partition 

### ISSUE THREAD

**Issue by rejo-oommen** [darold/ora2pg#733]
Hi Darold, 
Noticed an error in the DDL for the DEFAULT partition(list) generated by the tool.
Could you please check.

*Oracle DDL* 
PARTITION "ID_UNKNOWN"  VALUES (DEFAULT)

*Ora2pg conversion Postgres equivalent:*
CREATE TABLE xyz_id_unknown PARTITION OF xyz FOR VALUES DEFAULT;

*Edited the DDL to below*
CREATE TABLE xyz_id_unknown PARTITION OF xyz DEFAULT;

**Comment by darold** [comment]
Fixed in commit de4f2ba.

**Comment by buragaddapavan** [comment]
Hi darold,

im getting error with below command on 10.5
CREATE TABLE xyz_id_unknown PARTITION OF xyz DEFAULT;

this works for me on 10.5
CREATE TABLE xyz_id_unknown PARTITION OF ID_UNKNOWN FOR VALUES FROM (' 2018-04-01 00:00:00') to (MAXVALUE);


Please fix it
