### ISSUE TITLE
Error in creation of MAXVALUE partition

### ISSUE THREAD

**Issue by buragaddapavan** [darold/ora2pg#740]
ora2pg didnt generate DDL for below partition table.

CREATE TABLE IVRPROD.IVR_OB_EVENTS
(
  GENERATED_ID       VARCHAR2(96 BYTE)          NOT NULL,
  RETURN_CODE        NUMBER(1),
  SERVICE_NAME       VARCHAR2(64 BYTE),
  SUB_SERVICE_NAME   VARCHAR2(64 BYTE),
  DB_TIMESTAMP       TIMESTAMP(6)               DEFAULT SYSTIMESTAMP          NOT NULL
)
NOCOMPRESS 
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
           )
PARTITION BY RANGE (DB_TIMESTAMP)
(  
  PARTITION P_MAXVALUE VALUES LESS THAN (MAXVALUE)
    LOGGING
    NOCOMPRESS 
    )
NOCACHE
MONITORING;

i manually created table.please fix it

CREATE TABLE ivr_ob_events_maxvalue PARTITION OF ivr_ob_events FOR VALUES FROM (MINVALUE) TO (MAXVALUE);

**Comment by darold** [comment]
Commit f08dcc3 fixes this issue.
