### ISSUE TITLE
Error in creation of default partition

### ISSUE THREAD

**Issue by buragaddapavan** [darold/ora2pg#742]
Hi darold,

im getting error with below command on 10.5
CREATE TABLE xyz_id_unknown PARTITION OF xyz DEFAULT;

this works for me on 10.5
CREATE TABLE xyz_id_unknown PARTITION OF ID_UNKNOWN FOR VALUES FROM (' 2018-04-01 00:00:00') to (MAXVALUE);

Please fix it

**Comment by darold** [comment]
Commit 2bedbb5 might solve this issue. Note that all PG_SUPPORTS_* configuration directives have been removed from ora2pg.conf minus PG_SUPPORTS_SUBSTR. Behavior of Ora2Pg is now controlled by PG_VERSION that must be set to the target PostgreSQL major version. In your case probably: 10

Export of hash partitioning is now also skipped when PG_VERSION is bellow 11. Previously PG_SUPPORTS_PARTITION was not making any differences between 10 and 11 PostgreSQL version.
