### ISSUE TITLE
oracle to PostgreSQL migration verification

### ISSUE THREAD

**Issue by sensuraj92** [darold/ora2pg#743]
Hi,

I have converted oracle schema to postgres using ora2pg tool, now i want to verify that migration was happened properly without any data loss, for that i used below command to get the count of tables,views,indexes, constraints, triggers etc. on both oracle and postgres

Ora2pg –t TEST –c ora2pg.conf > migration_diff.txt 

which is giving me a output file with all the details, but it seams like at postgres side it is scanning complete postgres database instead of specific postgres schema mentioned in config file, please suggest how can i get the exact migration results to get the confirmation migration from oracle to postgres has happened correctly without any data loss

Thanks

**Comment by darold** [comment]
Unfortunately Ora2Pg can not verify a single PostgreSQL schema. This is on my todo list but I can't tell you when it will be implemented. If you want to compare the exact number of rows exported you need to use the `--count_rows` option otherwise we only use row count from statistics.

**Comment by sensuraj92** [comment]
can u please share the full syntax how to share --count_rows is that give how many rows are available each table, index, and views ?

**Comment by darold** [comment]
This is common use of command line option, using your command above just append the real row count option:
```
ora2pg -t TEST --count_rows -c ora2pg.conf > test_migration_diff.txt
```

For row count returned by views this is the real row count so no option has to be appended:
```
ora2pg -t TEST_VIEW --count_rows -c ora2pg.conf > test_migration_view_diff.txt
```

**Comment by sensuraj92** [comment]
One more query,

is there a possibility to check postgres schema after migration, if any incompatible data type column  is still there in  any of the tables ?

Also size of columns defined in oracle are still holds good for postgres after migration ?

**Comment by darold** [comment]
You should not have any problem with size of columns. Concerning incompatible data type column if you do not have error during data import I guess that all data type are correct. The only thing you must check is that columns that require no precision lost like monetary columns should be defined as numeric and not double precision in PostgreSQL.

**Comment by darold** [comment]
Verification now use the PG_SCHEMA configuration directive when set.
