### ISSUE TITLE
mySql view conversion errors

### ISSUE THREAD

**Issue by mrechte** [darold/ora2pg#747]
```
CREATE VIEW `CDPSUPERVISION` AS select `a`.`CDPTYPE` AS `CDPTYPE`, ... ,`b`.`FREQ` AS `freq` from (`SURVCHARGE` `a` join `CDPDISPO` `b`) where (`b`.`CDPTYPE` = `a`.`CDPTYPE`)
```
Is converted to:
```
CREATE OR REPLACE VIEW cdpsupervision AS select a.CDPTYPE AS CDPTYPE, ... ,b.FREQ AS freq FROM SURVCHARGE a join CDPDISPO b where (b.CDPTYPE = a.CDPTYPE);
```

1. Syntax error in the JOIN clause (should be ON and not WHERE)
2. As all tables / views names are converted to lower case, referenced tables should be also in lower case (here SURVCHARGE and CDPDISPO)
3. All column names should also be converted to lower case in views as this already done for tables.

**Comment by darold** [comment]
Commit 88308ca adds rewrite of MySQL JOIN with WHERE clause instead of ON. Thanks Marc.
