### ISSUE TITLE
ORA-03106: fatal two-task communication protocol error (DBD ERROR: OCIStmtFetch)

### ISSUE THREAD

**Issue by Jeewansoori** [darold/ora2pg#749]
Hi,
I am running ora2pg migration with the below versions. 

This is my test environment
Oracle version : 10.2
PG Version : 11.1
Ora2pg version : 19.1

I am encountering below error while running the data migration. Appreciate your inputs to fix this error.

DBD::Oracle::st fetchall_arrayref failed: ORA-03106: fatal two-task communication protocol error (DBD ERROR: OCIStmtFetch) [for Statement "SELECT "TEST_ID","OPS_EXPL","HD_BIN_NO","ST_BIN_NO","INPUT_DATE","MAIN_ID","PURGE" FROM "APP"."TEST_BIN" a"] at /usr/local/share/perl5/Ora2Pg.pm line 13519.
ERROR: ORA-03106: fatal two-task communication protocol error (DBD ERROR: OCIStmtFetch)

Thanks
Jeewan

**Comment by darold** [comment]
Hi,

Please use latest development code and report the new error message if it still occurs, there was lot of changes since version 19.1. If you are not familiar with git you can download it with command:
```
wget https://github.com/darold/ora2pg/archive/master.zip
unzip master.zip
cd ora2pg-master/
perl Makefile.PL
make
sudo make install
```
Also post the Oracle description of table:
```
SQL> DESC ULSD.UNIT_BIN
```

Regards

**Comment by Jeewansoori** [comment]
Thanks Darold for the quick response. I am running the migration again with 18.2 version now and its still in progress. I will test it again for the latest code after that.

Oracle
SQL> desc test_bin;
 Name                                      Null?    Type
 ----------------------------------------- -------- ----------------------------
 TEST_ID                                   NOT NULL VARCHAR2(20)
 OPS_EXPL                                  NOT NULL VARCHAR2(30)
 HD_BIN_NO                                       NUMBER
 ST_BIN_NO                                       NUMBER
 INPUT_DATE                                          DATE
 MAIN_ID                                            VARCHAR2(256)
 PURGE                                              VARCHAR2(1)

SQL>

PostgreSQL
     Column      |            Type             | Collation | Nullable | Default | Storage  | Stats target | Description
-----------------+-----------------------------+-----------+----------+---------+----------+--------------+-------------
 test_id         | character varying(20)       |           | not null |         | extended |              |
 ops_expl        | character varying(30)       |           | not null |         | extended |              |
 hd_bin_no       | bigint                      |           |          |         | plain    |              |
 st_bin_no       | bigint                      |           |          |         | plain    |              |
 input_date       | timestamp without time zone |           |          |         | plain    |              |
 main_id         | character varying(256)      |           |          |         | extended |              |
 purge           | character varying(1)        |           |          |         | extended |              |

Thanks

**Comment by Jeewansoori** [comment]
Hi Darold,
I did the migration using the latest codes as you suggested and it fixed the error ORA-03106. Thank you very much for the support.
Besides that I would like to clarify with you regarding the migration log file. It was ended at 75% stage, however when I compare the row count between oracle and pg it exactly matching. Any reason why it shows higher no of rows compared to actual number ?

[==================>      ] 12567599502/16751395207 rows (75.0%) on total estimated data (62540 sec., avg: 200952 tuples/sec)

Thanks
Jeewan

**Comment by darold** [comment]
Ora2pg use Oracle statistics to obtain a quick row count, I guess that the statistics are not up to date.
