### ISSUE TITLE
Converting DETERMINISTIC functions

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#750]
Hello Darold,

I have an Oracle function with the DETERMINISTIC property, which is equivalent to Postgres IMMUTABLE property. It is especially used for function-based indexes.
Could ora2pg implement this translation ?
Here is an example of function header (in an Oracle Package):
"FUNCTION formatted_serial ( p_card_id t_ticket_subscription.card_id%TYPE, p_serial t_ticket_subscription.ticket_serial_number%TYPE) RETURN VARCHAR2 DETERMINISTIC IS"

Note that it's the same in the package header.

I am currently using plain 19.1 version.
Best regards,
Eric

**Comment by darold** [comment]
This is normally the case, I'll check that.

**Comment by darold** [comment]
I can not reproduce your issue with just published version 20.0. Please use it and let me know.

Note that you need to set PG_VERSION configuration directive to your PostgreSQL major version number in the new configuration file.

**Comment by edelanoe** [comment]
Yes, version 20.0 solves the issue, sorry for this wrong opening.
