### ISSUE TITLE
Unwanted APEX Synonyms exported from Oracle XE

### ISSUE THREAD

**Issue by dtseiler** [darold/ora2pg#752]
Testing with Oracle XE 11.2. I'm testing exporting the HR sample schema but export_schema.sh dumps out about 239 synonyms from APEX. Since I'm not exporting the APEX tables, these synonyms fail on the import.

Even when I add `EXCLUDE APEX.*` I'm still left with these `CREATE VIEW` statements in the synonyms.sql file:

```
CREATE VIEW public.development_service_home AS SELECT * FROM apex_040000.development_service_home;
ALTER VIEW public.development_service_home OWNER TO apex_040000;
GRANT ALL ON public.development_service_home TO public;

CREATE VIEW public.development_service_home_login AS SELECT * FROM apex_040000.development_service_home_login;
ALTER VIEW public.development_service_home_login OWNER TO apex_040000;
GRANT ALL ON public.development_service_home_login TO public;
```

There's about 85 of those.

Yes we can say "N" to importing these synonyms to avoid the import failing. But I feel it's a bug that these synonyms are being exported.

**Comment by darold** [comment]
Hi,

Commit 2e08583 adds schema APEX_040000 to the exclusion list.

You have the SYSUSERS configuration directive that can be used to append any unwanted schema to the exclusion list. Here you could use:
```
SYSUSERS    APEX_040000
```

Regards,

**Comment by dtseiler** [comment]
Ah yes that did work as well.
