### ISSUE TITLE
ora2pg prerequisite and how does it work?

### ISSUE THREAD

**Issue by pepevo** [darold/ora2pg#753]
Hello,
I run the or2pg and  the job was failed in the middle somewhere when I run on the current directory with plenty of space (250G). The error is "ssh, telnet and rlogin client has stopped working." and it hung my session.  Once I close the error window, my session was terminated.

 Question,
1.how much physical memory is required to run ora2pg?
2.Can I run the export with multiple schemas? How do I specify it on ora2pg.conf with comma or semicolon?
 SCHEMAS CIDRDB1, CIDRDB2, etc....???
3.I don't see output as "output.sql" but something automatically generated name with dot data (.data) even if the job failed even I already OUTPUT name as "output.sql" and OUTPUT_DIR configuration directive as "/opt/tmp_postgres" on ora2pg.conf
4.Do I need the perl-cpan module installed to get the output?
5. If, one the export from oracle database is done, how can I import into the specify source database in Postgres or only work to import into the default database, "postgres"?  we wants all Oracle's schemas convert into the new empty postgres DB.
6. Is there a source I can use?

thank you,
 v/r,
 Bach Nga

**Comment by darold** [comment]
1) Usually 4GB is a good minimal sizing for Ora2Pg, but you can use less by reducing the DATA_LIMIT parameter. 
2) No you can not export a list of schema. This is just one schema or all schemas, to export all just unset the SCHEMA configuration directive and use a DBA user in ORACLE_USER.
3) File `.dat` are temporary file, they will be reloaded and removed automatically.
4) no you don't need perl-cpan to be installed, your installation seems to work
5) you can import all `.sql` files exported by Ora2Pg into the PostgreSQL database you want using the `psql` client. Some `.sql` files are generic files used to import all files. For example if FILE_PER_TABLE is enabled you will have one sql file per table and a generic file output.sql which allow you to import all other files.
6) I guess you mean documentation/tutorial by source, there is lot over Internet. You can also find help on most general postgresql forum.

Regards,

**Comment by darold** [comment]
Output files are gzipped only if you give a .gz extension to the output file, for example:
```
OUTPUT      output.sql.gz
```
this has no interest for DDL export but it can be useful with data export if you don't have enough disk space. In your case you have plenty of space so use compressed output is not recommended.

The complain about PG_VERSION is just a warning, if you are migrating to PostgreSQL version 11 do not take care of this message. If you want to migrate to PostgreSQL v10, add the following to your ora2pg.conf configuration file:
```
PG_VERSION    10
```

Ora2Pg is not the only software to help migrating from Oracle to PostgreSQL but this is the most advanced free and open source tool to my knowledge. There is lot of configuration directives because there is lot of things to be considered for a migration but most of them have a default value that can be used for a majority of migration. 

Ora2Pg is free and I try to keep it free in the future as well. Like most of open source software you don't need to pay to have community support but you have to find a PostgreSQL forum where you can be helped. This github account is related to Ora2Pg issues not on migration issues. If you need commercial support for Ora2Pg and professional help for Oracle to PostgreSQL migration, you can choose one of the excellent company near of you listed in the PostgreSQL Professional Services page (https://www.postgresql.org/support/professional_support/). You can also contact me on my private email < gilles@darold.net > to explain me the context of your migration project, I will try to find the right answer to your needs.

Best regards
Best regards
Best regards,

**Comment by darold** [comment]
Please take time to read documentation, if you want to enable Oracle to PostgreSQL translation you have to enable PLSQL_PGSQL in your configuration file.

**Comment by pepevo** [comment]
we looked into configuration file and some of the comments are confused and as I have asked from previous that we see a lot of parameters and not quietly how to set it.  I did enable PLSQL_PGSQL in the configuration file.

here are the parameters we have set in the configuration file:
ORALCLE_DSN dbi:Oracle:host=hostname;sid=CIDR;port=1521
ORACLE_USER system
ORACLE_PWD password
USER_GRANTS 0
DEBUG 0
ORA_INITIAL_COMMAND commit
SCHEMA cidrdba
CREATE_SCHEMA 1
COMPILE_SCHEMA 0
DISABLE_COMMENT 0
EXTERNAL_TO_FDW 1
TRUNCATE_TABLE 0
USER_TABLESPACE 0
REORDERING_COLUMNS 0
CONTEXT_AS_TRGM 0
FTS_INDEX_ONLY 1
USE_UNACCENT 0
USE_LOSWER_UNACCENT 0
DATADIFF_DEL_SUFFIX  _del
DATADIFF_UPD_SUFFIX  _upd
DATADIFF_INS_SUFFIX _ins
DATADIFF_WORK_MEM  256 MB
DATADIFF_TEMP_BUFFERS 512 MB
KEEP_PKEY_NAMES 0
PKEY_IN_CREAT 0
FKEY_ADD_UPDATE never
PKEY_DEFERRABLE 0
DEFER_FKEY 0
DROP_FKEY directive
DROP_FKEY 0
DISABLE_SEQUENCE 1
DISABLE_TRIGGERS 0     ---> should be 1 ???
ORIG_TB_NAME2:NEW_TB_NAME2
PRESERVE_CASE 0
INDEXES_RENAMING 0
USE_INDEX_OPCLASS 0
PREFIX_PARTITION 0
DISABLE_PARTITION 0
WITH_OID 0
USE_RESERVED_WORDS 0
DISABLE_UNLOGGED 0
OUTPUT cidrdba.sql
OUTPUT_DIR /opt/tmp_post
#Path to the bzip2 program. See OUTPUT directive above
GZIP
FILE_PER_CONSTRAINT 0
FILE_PER_INDEX 0
FILE_PER_FKEYS 0
FILE_PER_TABLE 0
FILE_PER_FUNCTION 0
STOP_ON_ERROR 1
COPY_FREEZE 0
CREATE_OR_REPLACE 1
PG_NUMERIC_TYPE 1
PG_INTEGER_TYPE 1
DEFAULT_NUMBERIC bigint
ENABLE_MICROSECOND 1
TB_NAME2:COL_NAME2
TABLE1:COL2:varchar, TABLE1:COL4:decimal (9,6)
TO_NUMBER_CONVERSION numeric
GEN_USR_PWD 0
FORCE_OWNER 0
FORCE_SECURITY_INVOKER 0
DATA_LIMIT 10000
NOESCAPE 0
TRANSACTION serializable
STANDARD_CONFORMING_STRINGS 1
NO_LOB_LOCATOR 1
XML_PRETTY 0
LOG_ON_ERROR 0
TRIM_TYPE BOTH
INTERNAL_DATE_MAX 49
FUNCTION_CHECK 1
JOBS 1
ORACLE_COPIES 1
PARALLEL_TABLES 1
DEFAULT_PRALLELISM_DEGREE 0
PARALLEL_MIN)ROWS 10000
DROP_INDEXES 0
SYNCHRONOUS_COMMIT 0
EX[PRT_INVALID 0
PLSQL_PGSQL 1
EMPTY_LOB_NULL 0
PACKAGE_AS_SCHEMA 1
REWRITE_OUTER_JOIN 1
FUNCTION_STABLE 1
COMMENT_COMMIT_ROLLBACK 0
COMMENT_SAVEPOINT 0
USE_ORAFCE 0
AUTONOMOUS_TRANSACTION 1
ESTIMATE_COST 0
COST_UNIT_VALUE 5
DUMP_AS_HTML 0
TOP_MAX 10
HUMAN_DAYS_LIMIT 5
PG_SUPPORTS_WHEN 1
PS_SUPPORTS_INSTEADOF 1
PG_SUPPORTS_MVIEW 1
PG_SUPPORTS_IFEXISTS 1
PG_SUPPORTS_LATERAL 1
PG_SUPPORTS_PARTITION 1
BITMAP_AS_GIN 1
PG_BACKGROUND 0
PG_SUPPORTS_SUBSTR 1
PG_SUPPORTS_NAMED_OPERATOR 1
PG_SUPPORTS_INDETITY 1
PG_SUPPORTS_PROCEDURE 0
AUTODETECT_SPATIAL_TYPE 1
CONVERT_SRID 1
DEFAULT_SRID 4326
GEOMETRY_EXTRACT_TYPE INTERNAL
FDW_SERVER orcl
MYSQL_PIPES_AS_CONCAT 0
MYSQL_INTERNAL_EXTRACT_FORMAT 0

**Comment by darold** [comment]
I think you must use the generic migration process, have a look to http://ora2pg.darold.net/documentation.html#Generate-a-migration-template this will considerably help you as the only things you will have to change are configuration directives ORACLE_DSN, ORACLE_USER, ORACLE_PWD and SCHEMA.

**Comment by pepevo** [comment]
thank you so much sir.
After the export is done, I saw .dat file and a file called Oracle_home.  Do I need to move these two files over to postgres server and import? Oracle_home is something like create database information from Oracle and .data file is dat.
for import ddl to Postgres, I need to run one by one output scripts, right?  What do I need to do with .dat and oracle_home file?
thank you.

Bach Nga

**Comment by pepevo** [comment]
I have a question about this export.
According to the ora2pg.conf, it exported schema cidrdba.  If I bring the scripts onto postgres, do I need to create a schema, cidrdba?  and how the scripts import?  If I run the import script with the postgres user all will be postgres table not cidrdba, right?
I have 3 more schemas, cidrmgmt, cidrwebapp and cidr_staging on oracle cidr database needed to export.

thank you,

Bach Nga

**Comment by darold** [comment]
Ok, good to see that your Ora2Pg installation is running. I don't doubt that you will be able to resolve the missuses of Ora2Pg to achieve your Oracle to PostgreSQL migration. Github is reserved to Ora2Pg development and bug reports, free support for migration is not included in my spare time, I already have not enough for development of Ora2Pg and other tools :-)
