### ISSUE TITLE
Missing PERFORM in some "procedure" calls (not everywhere)

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#754]
Hello Darold,

I am going to send you 2 files of translated packages with the same issue appearing in SOME of the "old procedure" calls:
Oracle:  msg_raise_error(CST.SGBD_ERRCODE_INIT,...
ora2pg KO: pck_gpar.msg_raise_error(CST.SGBD_ERRCODE_INIT, ...
ora2pg ok: PERFORM pck_gpar.msg_raise_error(CST.SGBD_ERRCODE_INIT, ...

In first file: 10 occurences KO v/s 300 ok
In second file: 2 occurrences KO v/s 35 ok
Can you see a correlation with ora2pg code ?

**Comment by edelanoe** [comment]
It looks like the issue occurs on function calls after a ELSE or the "THEN" of a CASE... WHEN... THEN

Rgds
Eric

**Comment by darold** [comment]
Thanks for the files Eric, I will look at it this weekend.

**Comment by darold** [comment]
Commit 4914356 might solve the issue. Thanks for the report.

**Comment by edelanoe** [comment]
Sorry, some errors remain:

ORACLE:
    FUNCTION ORA_PERIOD(p_unit T_TYPE_OF_UNIT.type_of_unit_id%TYPE) RETURN VARCHAR2 IS
    BEGIN
    -- Pour déterminer la formule d'addition d'intervalle de temps avec NUMTODSINTERVAL en fonction de TYPE_OF_UNIT_ID ou (T_CSTR_TRANSIT_DEF.)TYPE_OF_CSTR_PERIOD_ID
    -- Pourrait servir à faire une fonction APP_ADD_DATE ou APP_ADD_TIME
        CASE p_unit
        WHEN CST.TYPE_OF_UNIT_DAY THEN
            RETURN 'DAY';
        WHEN CST.TYPE_OF_UNIT_HOUR THEN
            RETURN 'HOUR';
        WHEN CST.TYPE_OF_UNIT_MINUTE THEN
            RETURN 'MINUTE';
        ELSE
            PCK_BDD.app_raise_error(CST.SGBD_ERRCODE_INIT, 'Type d''unité ou de période '||p_unit||' non géré dans ce contexte');
			-- formel (jamais atteint car il y a un raise dans app_raise_error)
			RETURN NULL;
        END CASE;
    END ORA_PERIOD;

ora2pg:
CREATE OR REPLACE FUNCTION pck_common.ora_period (p_unit T_TYPE_OF_UNIT.type_of_unit_id%TYPE) RETURNS varchar AS $body$
BEGIN
    -- Pour déterminer la formule d'addition d'intervalle de temps avec NUMTODSINTERVAL en fonction de TYPE_OF_UNIT_ID ou (T_CSTR_TRANSIT_DEF.)TYPE_OF_CSTR_PERIOD_ID
    -- Pourrait servir à faire une fonction APP_ADD_DATE ou APP_ADD_TIME
        CASE p_unit
        WHEN CST.TYPE_OF_UNIT_DAY THEN
            RETURN 'DAY';
        WHEN CST.TYPE_OF_UNIT_HOUR THEN
            RETURN 'HOUR';
        WHEN CST.TYPE_OF_UNIT_MINUTE THEN
            RETURN 'MINUTE';
        ELSE
            PCK_BDD.app_raise_error(CST.SGBD_ERRCODE_INIT, 'Type d''unité ou de période '||p_unit||' non géré dans ce contexte');
			-- formel (jamais atteint car il y a un raise dans app_raise_error)
			RETURN NULL;
        END CASE;
    END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;

Is it possible to reopen the bug ?

**Comment by edelanoe** [comment]
Other "interesting" example:
ORACLE: ==========================================================
        v_err_context := 'Vérif fonctionnelle de V_COUNTING_ZONE_RESTRICTION.is_config';
        case
        when  v_is_config = -1 then -- compteur inexistant
            PCK_BDD.app_raise_error(CST.UNKNOWN_ACCESS_NUMBER(), CST.UNKNOWN_ACCESS_TXT()); -- pas de concaténation (sinon il faudrait concaténer '' avant ET après)

        when  v_is_config = 0 and vIs_Active = 1 then -- le compteur n'est pas configuré et on demande son activation
            PCK_BDD.app_raise_error(CST.COUNTER_NOT_CONFIG_NUMBER(), CST.COUNTER_NOT_CONFIG_TXT());

        else
            v_err_context := 'UPDATE T_COUNTING_ZONE_RESTRIC SET IS_ACTIVE = '||vIs_Active||' where counting_id = '||vCounting_id||' and zone_id = '||vZone_id;
            UPDATE T_COUNTING_ZONE_RESTRIC
                SET IS_ACTIVE = vIs_Active
                WHERE ZONE_ID = vZone_id AND COUNTING_ID = vCounting_id;

             commit;
			pck_common.insert_log ('PCK_CPT', 'T_COUNTING_ZONE_RESTRIC IS_ACTIVE='||vIs_Active||', ZONE_ID='||vZone_id||', COUNTING_ID = '||vCounting_id);
        end case;
		RETURN('0');
========================================================
= ora2pg
======================================
        v_err_context := 'Vérif fonctionnelle de V_COUNTING_ZONE_RESTRICTION.is_config';
        case
        when  v_is_config = -1 then -- compteur inexistant
            PCK_BDD.app_raise_error(CST.UNKNOWN_ACCESS_NUMBER(), CST.UNKNOWN_ACCESS_TXT()); -- pas de concaténation (sinon il faudrait concaténer '' avant ET après)
        when  v_is_config = 0 and vIs_Active = 1 then -- le compteur n'est pas configuré et on demande son activation
            PCK_BDD.app_raise_error(CST.COUNTER_NOT_CONFIG_NUMBER(), CST.COUNTER_NOT_CONFIG_TXT());

        else
            v_err_context := 'UPDATE T_COUNTING_ZONE_RESTRIC SET IS_ACTIVE = '||coalesce(vIs_Active::varchar, '')||' where counting_id = '||coalesce(vCounting_id::varchar, '')||' and zone_id = '||coalesce(vZone_id::varchar, '');

            UPDATE T_COUNTING_ZONE_RESTRIC
                SET IS_ACTIVE = vIs_Active
                WHERE ZONE_ID = vZone_id AND COUNTING_ID = vCounting_id;

             -- commit;
			PERFORM pck_common.insert_log('PCK_CPT', 'T_COUNTING_ZONE_RESTRIC IS_ACTIVE='||coalesce(vIs_Active::varchar, '')||', ZONE_ID='||coalesce(vZone_id::varchar, '')||', COUNTING_ID = '||coalesce(vCounting_id::varchar, ''));

        end case;
		RETURN('0');
======================================

**Comment by edelanoe** [comment]
Other example (looks like there is a correlation with the presence of comments)
ORACLE: ====================================================
                else -- OGA-20150407 : Gestion des anomalies sur configuration des compteurs
                    -- mérite une FK
                    pck_common.INSERT_LOG('PCK_CPT', 'MAJ_CPT : ERROR BAD type_of_step_mgmt FOR CPT id. ' || to_char(cur_loop.counting_id)||'');
                    v_type_of_step_id := cur_loop.type_of_step_id;
                end case;
ora2pg: ==========================================================
                else -- OGA-20150407 : Gestion des anomalies sur configuration des compteurs
                    -- mérite une FK
                    pck_common.INSERT_LOG('PCK_CPT', 'MAJ_CPT : ERROR BAD type_of_step_mgmt FOR CPT id. '||coalesce( cur_loop.counting_id::varchar, '')||'');
                    v_type_of_step_id := cur_loop.type_of_step_id;
                end case;

**Comment by edelanoe** [comment]
Other, simpler example:
ORACLE: ====================================================
			v_err_context := 'v_transit_effective -> if v_TYPE_DATA_ID = CST.TYPE_DATA_ID_NOW then PCK_GPAR_EXT.CONFIRM_EXTERNAL_DATA';
            if v_TYPE_DATA_ID = CST.TYPE_DATA_ID_NOW then --now
                --  external data filled by PCK_INT should NEVER be sent to external system 
				CASE v_TYPE_OF_TRANSIT_ID
					WHEN CST.TTR_ENTRY THEN
					  PCK_GPAR_EXT.CONFIRM_EXTERNAL_DATA (v_DATA_ID, CST.NOTIFY_ENTRY , CST.CONFIRMATION_KO);
					WHEN CST.TTR_EXIT THEN  
					  PCK_GPAR_EXT.CONFIRM_EXTERNAL_DATA (v_DATA_ID, CST.NOTIFY_EXIT , CST.CONFIRMATION_KO);
					ELSE
					  NULL;
				END CASE;
            end if;
ora2pg: ====================================================
			v_err_context := 'v_transit_effective -> if v_TYPE_DATA_ID = CST.TYPE_DATA_ID_NOW then PCK_GPAR_EXT.CONFIRM_EXTERNAL_DATA';
            if v_TYPE_DATA_ID = CST.TYPE_DATA_ID_NOW then --now
                --  external data filled by PCK_INT should NEVER be sent to external system
				CASE v_TYPE_OF_TRANSIT_ID
					WHEN CST.TTR_ENTRY THEN
					  PCK_GPAR_EXT.CONFIRM_EXTERNAL_DATA(v_DATA_ID, CST.NOTIFY_ENTRY , CST.CONFIRMATION_KO);
					WHEN CST.TTR_EXIT THEN
					  PERFORM PCK_GPAR_EXT.CONFIRM_EXTERNAL_DATA(v_DATA_ID, CST.NOTIFY_EXIT , CST.CONFIRMATION_KO);
					ELSE
					  NULL;
				END CASE;
            end if;

**Comment by darold** [comment]
Hi Eric,

Unfortunately it is not possible to Ora2Pg to add PERFORM in from of package.function() call that has not be known by Ora2Pg.  In your last example the definition of package PCK_GPAR_EXT is unknown to Ora2Pg when your are translating the PCK_GPAR package.

I can not simply prepend PERFORM to any call like package.function() there would be too much false positive. But if you set LOOK_FORWARD_FUNCTION to PCK_GPAR_EXT Ora2Pg will extract the function definition from the package and will be able to detect the functions call in the PCK_GPAR package.

Cheers
