### ISSUE TITLE
ora2pg_scanner error on Windows

### ISSUE THREAD

**Issue by mco100** [darold/ora2pg#756]
Hello,
ora2pg on windows (Windows 2016 server) is OK. But with ora2pg_scanner, I got this error
'ora2pg' is not recognized as an internal or external command, operable program or batch file.
Any recommendations for Windows people ?

**Comment by darold** [comment]
Set your PATH environment variable? I've never tested ora2pg_scanner on Windows, I guess there will be some other issues.

**Comment by mco100** [comment]
Hello,

See how are set system variables on Windows VM on which ora2pg is installed and running fine (issue is only with ora2pg_scanner).

OCI_LIB64=F:\oracle_client\instantclient-basic-windows.x64-12.1.0.2.0\instantclient_12_1
ORACLE_HOME=F:\oracle_client\instantclient-basic-windows.x64-12.1.0.2.0\instantclient_12_1
Path=F:\Ora2PG\site\bin;F:\Ora2PG\bin;C:\Program Files\Microsoft MPI\Bin\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft SQL Server Migration Assistant for Oracle\bin\;F:\oracle_client\instantclient-basic-windows.x64-12.1.0.2.0\instantclient_12_1;F:\putty\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;F:\Ora2PG\ora2pg-20.0\ora2pg-20.0\scripts;C:\Users\marie\AppData\Local\Microsoft\WindowsApps;
PERL5LIB=F:\Ora2PG\ora2pg-20.0\ora2pg-20.0\lib

I am ready to do any test with you
I have built test environment in Azure so we could do tests together if you agree of course.
Thanks for your quick answer

Marie

**Comment by mco100** [comment]
Voici le message d’erreur. Quels sont tes conseils ?

[cid:image001.png@01D4B7F8.52C19DE0]

**Comment by darold** [comment]
De ne pas envoyer de réponse par mail à github, l'image n'est pas présente. Il faut utiliser l'interface ou sinon écrire directement à l'adresse ora2pg@darold.net.

**Comment by darold** [comment]
All issues related to ora2pg_scanner use on Windows platform might be fixed. Thanks for the report.

**Comment by chetan2211** [comment]
Hi @darold 
I am also facing same error when i run following command.
Please let me know the solution on it.
 Thank you in advance.

D:\ora2pg-23.0>ora2pg -t table -c ora2pg.dist -l school.log -o school.sql
'ora2pg' is not recognized as an internal or external command,
operable program or batch file.

**Comment by darold** [comment]
You are on Windows, to execute a perl script you should do:
```
D:\ora2pg-23.0> perl script/ora2pg -t table -c ora2pg.dist -l school.log -o school.sql
```
