### ISSUE TITLE
Postgres hostory logs

### ISSUE THREAD

**Issue by sensuraj92** [darold/ora2pg#758]
Hi,

Can you please help in identifying who all connected to postgres schema previously

**Comment by sensuraj92** [comment]
sorry it is not about Ora2pg, it is in general with postgres may it is wrong place to post this question,

it will be helpful if you provide a solution for identifying who all connected to my PostgreSQL schema previously or history of machines/users connected to my schema

Thanks in advance

**Comment by darold** [comment]
There is lot of site where you can find this answer and especially PostgreSQL forum, here is reserved to Ora2Pg issue. You can also have a look at log_connection in postgresql.conf.
