### ISSUE TITLE
ora2pg data export in insert script

### ISSUE THREAD

**Issue by pepevo** [darold/ora2pg#759]
Hello,

When exporting with TYPE = TABLES,  I get the insert.sql output
when I run it and I get the error
ERROR: current transaction is aborted, commands ignored until end of transaction block

I found the code in insert,sql output with " **E'** " in front of the value.
Here is the Oracle code:

INSERT INTO cidrmgmt.search_results( id,scheduled_search_id,people_doc_id,receipt_number,form_number,a_number,first_name,middle_name,last_name,date_of_birth,dod,gender,country_of_birth,country_of_citizenship,country_of_residence,street,street2,city,state,zip,provice,postcal_code,country,res_street,res_city,res_state,res_zip,res_province,res_postal_code,res_country,ssn,tax_number,firm_name,service_center,last_indexed,ds_name,applicant_type,doe,citizenship,agency_code,tap_number,classification,mf_a_number, mf_first_name,mg_middle_name,mf_last_name,mf_agency_code, mf_tape_number,mf_fbi_result,mf_classification,indicator,inserted_date,updated_date,deleted_date) VALUES
(4896,92,E'7fdfcd2a-2da2-4f9f-bee3-4417a56c1a00',E'EAC1390072161','E'l130',NULL,E'JIEMEI',NULL,E'XIE',NULL,'1960-07-21 00:00:00',null,E'CHINA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,E'V','2017-1010 22:43:16',E'C3',E'Beneficiary',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,;2017-12-19 01:32:26','2018-04025 01:31:50','2018-01-11 01:33:44');

ERROR:current transaction is aborted, commands ignored until end of transaction block.  

I also get the trigger issue too.  How do I correct this and export the data from Ora2pg?

thank you.

Bach Nga

**Comment by darold** [comment]
I think you are probably mixing things that can't works together or you are miss understanding the way Ora2Pg is working. If you need commercial support you can contact me I will help you to achieve you migration but it can't be done with github issues as the problem is not related to Ora2Pg but to its use.

Best regards,
