### ISSUE TITLE
question on EXCLUDE parameter

### ISSUE THREAD

**Issue by jacks33** [darold/ora2pg#760]
I'm using ora2pg v19, in v18 it is the same behavior:
I'm using EXCLUDE parameter, but it seems it don't accept schema name:
Example:
EXCLUDE P\$.*, SYS_EXPORT_FULL_01, CRSTS_FOR_DTA, CMP3\$508849

works fine event the regular expression P\$.*

But if I add schemas it doens't work *even* protecting "." with backslashes
Exemple:
EXCLUDE MYSCHEMA,CRSTS_FOR_DTA, MYSCHEMA.CMP3\$508849
doesn't work 
as well as 
EXCLUDE MYSCHEMA\.CRSTS_FOR_DTA, MYSCHEMA\.CMP3\$508849
doesn't work
How can I use EXCLUDE parameter to filter all objects in a specific schema ?

Thank you

Actually there is a bug as well: 
when using EXCLUDE parameter with ora2pg v19 it attemps to migrate tables in Oracle internal schemas:
SYS, SYSTEM, APPQOSSYS,  ....

it didn't in release v18

**Comment by darold** [comment]
Hi,

EXCLUDE is for objects only, not user or schema. You have to use SYSUSERS instead but it doesn't support regexp, the full schema name must be given.

Regards

**Comment by jacks33** [comment]
Thanks for your feedback.

About my last question:

_Actually there is a bug as well:
when using EXCLUDE parameter with ora2pg v19 it attemps to migrate tables in Oracle internal schemas:
SYS, SYSTEM, APPQOSSYS, ...._

In other words:
if a use EXCLUDE (*and* keep SYSUSERS commented) in the configuration file.  ora2pg will exclude objects listed in EXCLUDE parameter =>OK
Also it tries to includes(and so migrate)  objects in schemas : SYS, SYSTEM, APPQOSSYS, .... I face this issue in data migration.

Thank you

**Comment by darold** [comment]
Use v20.0 it has been released last month and fix the issue on SYSUSERS.

**Comment by jacks33** [comment]
Thank you very much you can close the ticket.
