### ISSUE TITLE
Importing data from table with unique constriant and null values on it results in partial copy

### ISSUE THREAD

**Issue by fabianofa** [darold/ora2pg#761]
In Oracle 11g, I have a `TABLE_A` with three columns: 
- columnA number
- columnB number
- columnC number

no primary key
unique constraint on columnA.

I have 1800 rows there, 600 of them have columnA with some value, the others 1200 rows have columnA null.
columnB values are not relevant.
columnC have distinct values for every row.

When I run `ora2pg -t COPY -a TABLE_A`, it only imports 600 rows, even if I use JOBS > 1 and set DEFINED_PK as TABLE_A:columnC.

Is that a bug or is it something wrong with my config file? Apart from `DEFINED_PK` and `JOBS`, (and obvious variables to connect ORACLE and POSTGRESQL), no other config has been changed from the default values.

**Comment by darold** [comment]
Hi,

If you only have 1600 rows why are you using DEFINED_PK? This directive is used when using -J (or ORACLE_COPIES > 1) and it only be used with table with a huge number of rows. When using -j (or JOBS > 1) DEFINED_PK is not used. So here I guess that if you have only 600 rows this is because it is the real rows count for this table (exec a `SELECT count(*) FROM TABLE_A;` on Oracle side to verify). Rows count reported by Ora2Pg is extracted from the Oracle statistics and they may be out of date. Otherwise you may have a WHERE clause defined in ora2pg.conf.

Regards,

**Comment by fabianofa** [comment]
I was not using `DEFINED_PK` until I noticed that not all 1800 rows where being imported, and even I did, it didn't change the result of only 600 rows.

There is no WHERE clause defined.

You were right about JOBS, I'm not using JOBS > 1, but ORACLE_COPIES = 6 and JOBS = 1. Sorry about that.

> it only be used with table with a huge number of rows

This though doesn't seem to be true. I'll paste the result of a `ora2pg -c config/ora2pg.yml -a TABLE_A -t COPY`:

```
[========================>] 1/1 tables (100.0%) end of scanning.                       
[===>                     ]  94/620 rows (15.2%) Table TABLE_A-part-1 (0 sec., 94 recs/sec)
[=====>                   ] 132/620 rows (21.3%) Table TABLE_A-part-0 (0 sec., 132 recs/sec)                      
[====>                    ] 123/620 rows (19.8%) Table TABLE_A-part-2 (0 sec., 123 recs/sec)                      
[====>                    ] 125/620 rows (20.2%) Table TABLE_A-part-3 (0 sec., 125 recs/sec)                      
[====>                    ] 122/620 rows (19.7%) Table TABLE_A-part-4 (0 sec., 122 recs/sec)                      
[====>                    ] 126/620 rows (20.3%) Table TABLE_A-part-5 (0 sec., 126 recs/sec)                      
[========================>] 722/620 rows (116.5%) on total estimated data (1 sec., avg: 722 tuples/sec)  
```

Running `ALTER TABLE TABLE_A DISABLE CONSTRAINT CONST_UNIQUE` and running the same command `ora2pg -c config/ora2pg.yml -a TABLE_A -t COPY` outputs:

```
[========================>] 1/1 tables (100.0%) end of scanning.                       
[========================>] 1802/620 rows (290.6%) Table TABLE_A (1 sec., 1802 recs/sec)
[========================>] 1802/620 rows (290.6%) on total estimated data (1 sec., avg: 1802 tuples/sec)
```

**Comment by darold** [comment]
> it only be used with table with a huge number of rows
Sorry for my poor English speaking, I mean "it should only be used with table with a huge number of rows".

As you can see in the numbers reported by Ora2Pg it exports 1802 rows, the 620 rows are those reported by Oracle statistics. You should instruct your Oracle database to rebuild statistics.

**Comment by fabianofa** [comment]
> Sorry for my poor English speaking, I mean "it should only be used with table with a huge number of rows".

That's ok. Since I'm importing a whole database with some 400 tables, and some of them do have a million or more rows I needed that set otherwise some tables that are not normalised ended up returning an error.

Updating Oracle statistics though did update the total written in the output, but in the end only 722 rows were imported:

```
[========================>] 1/1 tables (100.0%) end of scanning.                       
[=>                       ]   94/1802 rows (5.2%) Table TABLE_A-part-1 (0 sec., 94 recs/sec)
[=>                       ]  125/1802 rows (6.9%) Table TABLE_A-part-3 (0 sec., 125 recs/sec)                      
[=>                       ]  132/1802 rows (7.3%) Table TABLE_A-part-0 (0 sec., 132 recs/sec)                      
[=>                       ]  123/1802 rows (6.8%) Table TABLE_A-part-2 (0 sec., 123 recs/sec)                      
[=>                       ]  122/1802 rows (6.8%) Table TABLE_A-part-4 (0 sec., 122 recs/sec)                      
[=>                       ]  126/1802 rows (7.0%) Table TABLE_A-part-5 (0 sec., 126 recs/sec)                      
[=========>               ]  722/1802 rows (40.1%) on total estimated data (1 sec., avg: 722 tuples/sec)
```

Running `select count(1) from table_a` in postgres' database returned confirmed the output:

```
count|
-----|
  722|
```

**Comment by darold** [comment]
What version of Ora2Pg are you using? It should be 20.0.

**Comment by darold** [comment]
Can you also report the value of the configuration directive DISABLE_PARTITION in your ora2pg.conf file?

**Comment by fabianofa** [comment]
Version:

```
$ ora2pg --version
Ora2Pg v20.0
```

`DISABLE_PARTITION` value: 

```
# If you don't want to reproduce the partitioning like in Oracle and want to
# export all partitionned Oracle data into the main single table in PostgreSQL
# enable this directive. Ora2Pg will export all data into the main table name.
# Default is to use partitionning, Ora2Pg will export data from each partition
# and import them into the PostgreSQL dedicated partition table.
DISABLE_PARTITION       0
```

**Comment by fabianofa** [comment]
I've tried with DISABLE_PARTITION 1, the results were the same. 722 rows of 1802 only, even if it listed 1802. I gathered statistics from table as requested too.

**Comment by darold** [comment]
Ok thanks for the report. I don't have the time to look at this problem right now, I will try to have a look later this night or tomorrow night.

**Comment by darold** [comment]
Commits 2a31142 and 493d6c5 solve issues on progress bar with wrong exported rows count returned. Unfortunately I was not able to reproduce your issue all rows are exported even if the rows count in progress bar was false. I the issue still occurs with latest development code it could be a great help to send to my private email the Oracle dump of the table. Let me know.

**Comment by fabianofa** [comment]
Ok, I'll ask you a couple of days though since I've to fix some applications to work correctly with PostgreSQL.

Thanks.
