### ISSUE TITLE
Oracle number datatype can have decimals and the data copy will fail as Ora2Pg treat number as bigint

### ISSUE THREAD

**Issue by joedbadmin** [darold/ora2pg#767]
Thanks for this terrific utility tool. Thanks and you the man!

Here is one issue (not really, but about convenience).

Oracle number data type when not specified with precision and scale would be translated in bigint in the Ora2Pg schema migration.
when you migrate the data to Pg later, it will error out with error message like " invalid input syntax for integer".
If a ora2pg conf item / option added to scan the records and decide to use float when there's a decimal is stored in number datatype, this could be avoided. Of course, scanning the data for all number data type fields will take time, but would avoid errors if someone is willing to spend extra time for this scan test while making the schema conversion.

A nice to have feature, I think.

select columnNUMBERtype_with_no_precision_or_scale_defined  from MYORCL_TABLE_WITH_NUMBER_COLUMNS where  not regexp_like(columnNUMBERtype_with_no_precision_or_scale_defined  ,'^[0-9]+$') and columnNUMBERtype_with_no_precision_or_scale_defined  >0; 

If returns anything, then make that field as float instead of bigint

**Comment by darold** [comment]
Hi,

Actually once you have created the tables in PostgreSQL you might import a first set of data to verify that all data types have been well translated. You can do that using the WHERE clause in ora2pg.conf file as follow:
```
WHERE        ROWNUM <= 1000
```
This will import the first 1000 rows and reports errors when the data type is not correct.

I's not exactly the feature you are describing but at the result you will be able to identify the columns that need some change. Thanks for the encouragements.

**Comment by joedbadmin** [comment]
Thanks for the rownum tip.

The ROWNUM is indeed a great option.
But in this case, I found 2 records out of 5 or 6 million and it would run until 4 million or so before it errors out. 
But, if the field is holding a lot of decimals and if we use the rownum<1000; it is a great option to avoid this error.

No worries as this scenario may be an odd situation and might not require any update. 
Hitting those errors, I thought if this NUMBER field scan option might be convenient. That was it.

Thanks again. 
I say again, 'you the man' and I meant it as you earned & deserved it.

**Comment by joedbadmin** [comment]
Any idea / suggestions for this error? 
One table copy is throwing the below error.
Error, Oracle DDL  and PgSQL DDL  as below.
Thanks in advance for any tips / solution.

(Source ->AWS's  Oracle RDS 
Destination -> Azure's PostgreSQL DB as Service)

[2019-02-25 06:38:40] ERROR: ORA-22831: Offset or offset+amount does not land on                                                                                                                      character boundary (DBD ERROR: OCILobRead)
DBD::Oracle::db ora_lob_read failed: ORA-22831: Offset or offset+amount does not                                                                                                                      land on character boundary (DBD ERROR: OCILobRead) at /usr/local/share/perl5/Or                                                                                                                     a2Pg.pm line 14227.

Oracle DDL
LOG_ID  NUMBER(10)          NOT NULL,
  F_CODE                VARCHAR2(10 CHAR)   NOT NULL,
  FILE_NAME                 VARCHAR2(150 CHAR)  NOT NULL,
  STATUS                    VARCHAR2(45 CHAR)   NOT NULL,
  FILE_TYPE                 VARCHAR2(45 CHAR)   NOT NULL,
  DESCRIPTION               VARCHAR2(150 CHAR),
  UPLOAD_DATE_TIME          DATE                NOT NULL,
  CONTENT                   CLOB,
  ERROR_CONTENT             CLOB,
  USER_NAME                 VARCHAR2(50 BYTE),
  ERROR_FILE_NAME           VARCHAR2(100 BYTE),
  BATCH_ID                  NUMBER(9)           NOT NULL,
  EMAIL                     VARCHAR2(100 BYTE),
  BATCHRUN_TIMESTAMP        DATE,
  APP_TYPE_ID               NUMBER(1)           DEFAULT 1,
  SOURCE_ID                 NUMBER(1),
  SUBMISSION_FY             VARCHAR2(4 BYTE)

PgSQL DDL

log_id  bigint         NOT NULL,
   f_code                varchar(10)    NOT NULL,
   file_name                 varchar(150)   NOT NULL,
   status                    varchar(45)    NOT NULL,
   file_type                 varchar(45)    NOT NULL,
   description               varchar(150),
   upload_date_time          timestamp      NOT NULL,
   content                   text,
   error_content             text,
   user_name                 varchar(50),
   error_file_name           varchar(100),
   batch_id                  integer        NOT NULL,
   email                     varchar(100),
   batchrun_timestamp        timestamp,
   app_type_id               smallint       DEFAULT 1,
   source_id                 smallint,
   submission_fy             varchar(4)

**Comment by darold** [comment]
Sorry for the response delay I have not received a github notation for this issue update. It is a good practice to open a new issue when the problem is not the same. However I never met this error, I think that if you set NO_LOB_LOCATOR to 1 might fix the problem. I will double check the code that is generating this error, I think there is an offset problem when reading the LOB with a locator.

**Comment by darold** [comment]
Commit d676ff1 might solve the problem.
```
    Avoid displaying error ORA-22831 when exporting LOB. This error can
    appears when LOB chunksize is different from default 8192. The error
    has no incidence on the export so we can just ignore it. This patch
    also use DBD::Oracle ora_lob_chunk_size() method to gather chunk the
    chunk size of the LOB, fallback to 8192 if not available.
```
