### ISSUE TITLE
Duplicated statements in the eported sql files

### ISSUE THREAD

**Issue by realbluehead** [darold/ora2pg#768]
I've exported all the tables of an oracle instance and the file generated contains several duplicated statements as you can see:

CREATE TABLE jbm_user (
        user_id varchar(32) NOT NULL,
        passwd varchar(32) NOT NULL,
        clientid varchar(128)
) ;
ALTER TABLE jbm_user ADD PRIMARY KEY (user_id);
ALTER TABLE jbm_user ADD PRIMARY KEY (user_id);
ALTER TABLE jbm_user ADD PRIMARY KEY (user_id);
ALTER TABLE jbm_user ADD PRIMARY KEY (user_id);

It also happens when I export the sequences:

CREATE SEQUENCE userrptprofile_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 61 CACHE 20;
CREATE SEQUENCE userrptprofile_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 61 CACHE 20;
CREATE SEQUENCE userrptprofile_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 61 CACHE 20;

**Comment by darold** [comment]
What is the value of the SCHEMA configuration directive in ora2pg.conf?

**Comment by realbluehead** [comment]
# SCHEMA SECTION (Oracle schema to export and use of schema in PostgreSQL)
EXPORT_SCHEMA	0
#SCHEMA		SCHEMA_NAME

**Comment by darold** [comment]
Ok, you are exporting multiple schemas which have same table name. Tables are stored in a hash so you just have one table exported but primary keys and sequences are stored in arrays so if they have the same name in different schemas they are exported multiple time. You have to proceed your export schema by schema, the SCHEMA directive must be set to the schema to export.

**Comment by realbluehead** [comment]
Thank you very much! I will try this!
