### ISSUE TITLE
Table DDL extraction from Oracle taking very long time

### ISSUE THREAD

**Issue by RejoOommen** [darold/ora2pg#769]
Trying to execute an export the DDL of TYPE=TABLE and it gets stuck forever. Tried multiple times(more than 1-2 hrs per run) and the same issue.  . Also this is only for TYPE=TABLE. While checked at oracle end, the session always shows INACTIVE.

Running the below
```ora2pg -p -s dbi:Oracle:rcld.xyz.com:1522/IVXB01 -u IVXMGR  -n STGMAMO -t TABLE -o table.sql -b /pg_vol/IVXB01/table```
```[2019-03-07 09:52:22] Ora2Pg version: 20.0
[2019-03-07 09:52:22] Trying to connect to database: dbi:Oracle:rcld.xyz.com:1522/IVXB01
[2019-03-07 09:52:27] Isolation level: SET TRANSACTION READ ONLY
[2019-03-07 09:52:28] Looking forward functions declaration in schema STGMAMO.
[2019-03-07 09:52:52] Retrieving table information...```

**Comment by darold** [comment]
Do you have the same problem with the `-t SHOW_TABLE` and `-t SHOW_COLUMN` action? How many tables and indexes do you have in this schema?

**Comment by rejo-oommen** [comment]
The output of ```-t SHOW_TABLE `` was quick,  but ```-t SHOW_COLUMN ``` was similar to ```-t TABLE``` which is taking a long time.

Counts given below:
Tables - 1907
Indexes - 4019

**Comment by darold** [comment]
Looking at Oracle catalog is very slow. Ora2Pg is retrieving the table information in separate queries (table, columns, indexes, constraints). There is no nested queries unless the type of a column is a geometry. I don't have such a schema to reproduce and try to find the possible bottleneck in Ora2Pg.

**Comment by okbob** [comment]
út 19. 3. 2019 v 17:23 odesílatel Gilles Darold <notifications@github.com>
napsal:

> Looking at Oracle catalog is very slow. Ora2Pg is retrieving the table
> information in separate queries (table, columns, indexes, constraints).
> There is no nested queries unless the type of a column is a geometry. I
> don't have such a schema to reproduce and try to find the possible
> bottleneck in Ora2Pg.
>
We have similar problem. I found workaround - enforcing object compilation.
Sure it is overhead, but next dumping database objects was faster.

**Comment by darold** [comment]
Commit 95e1418 enable schema compilation (COMPILE_SCHEMA set to 1) by default to speed up DDL extraction.

**Comment by okbob** [comment]
Thank you

Pavel

čt 10. 9. 2020 v 13:48 odesílatel Gilles Darold <notifications@github.com>
napsal:
