### ISSUE TITLE
No Table <*>DBA_OBJECTS

### ISSUE THREAD

**Issue by rzhengTO** [darold/ora2pg#770]
Hi,

I got an error with no table <*>DBA_OBJECTS. There is ALL_OBJECTS only from Oracle. Any help is kindly appreciated.

DBD ERROR: error possibly near <*> indicator at char 51 in 'SELECT DISTINCT OBJECT_NAME,OWNER,OBJECT_TYPE FROM <*>DBA_OBJECTS WHERE (OBJECT_TYPE = 'FUNCTION' OR OBJECT_TYPE = 'PROCEDURE' OR  OBJECT_TYPE = 'PACKAGE BODY') AND STATUS='VALID' AND OWNER = 'TEST' ORDER BY OBJECT_NAME')

**Comment by darold** [comment]
Set USER_GRANTS to 1 in ora2pg.conf, see documentation for more explanation.

**Comment by darold** [comment]
This is a problem that is reported too often. Commit f6f1791 will automatically activate USER_GRANTS when the connection user has no DBA privilege. A warning will also be displayed to warn about USER_GRANTS directive.

**Comment by rzhengTO** [comment]
Thanks darold.

There is another issue for ALL_SYNONYMS after USER_GRANTS is set to 1. SYNONYM has to be removed from TYPE to avoid the issue, thus SYNONYMS is not exported.

DBD::Oracle::db prepare failed: ORA-00604: error occurred at recursive SQL level 1
ORA-08177: can't serialize access for this transaction (DBD ERROR: error possibly near <*> indicator at char 62 in 'SELECT OWNER,SYNONYM_NAME,TABLE_OWNER,TABLE_NAME,DB_LINK FROM <*>ALL_SYNONYMS WHERE.....

**Comment by darold** [comment]
No this is not related to table privilege access but to the transaction level. You may want to change TRANSACTION from serializable to readonly. See ora2pg.conf.
