### ISSUE TITLE
Data export Mysql non UTF8

### ISSUE THREAD

**Issue by newbeewan** [darold/ora2pg#771]
Hi,

I'm trying to export a mysql db to pg, it works fine for the structure but for the data, I have some encoding issues...
MySQL data are in Latin1_german_ci and pg is in UTF8...

Is there any conversion trick ?

I found only things for Oracle (NLS_NCHAR) but I don't know how to force it for mysql... Is it possible ?

Best regards

Mourad

**Comment by darold** [comment]
Hi Mourad,

Just setting NLS_LANG in ora2pg.conf to 'utf8' will force MySQL to extract data with UTF8 encoding. Ora2Pg will send `SET NAMES 'utf8';` to the MySQL database.

Let me know if that's solve the issue.

**Comment by darold** [comment]
Also NLS_NCHAR in ora2pg.conf should be `nls_nchar`.

Note that normally this is the default for both so if you comment the configuration directives Ora2Pg will use these values. Can you execute the ora2pg command with the `-t SHOW_ENCODING` option and report here the output?
