### ISSUE TITLE
Escape format issue with COPY

### ISSUE THREAD

**Issue by spacebel** [darold/ora2pg#778]
Congrats for the great work.

I'm exporting from Oracle Database SE 11 to PostgreSQL 8.4. For the blob column, the export lead to the following syntax:
- COPY:  \\x
- INSERT: decode(E'

When importing the SQL exported with COPY, I get the following exception "invalid input syntax for type bytea".

Is this a compatilibility issue ? 

Thanks.

**Comment by darold** [comment]
Hi,

I don't know what force you to use an obsolete and very old version of PostgreSQL but I don't think it is a compatibility issue. Have you tried with at least a 9.4? And which version of Ora2Pg are you using?

regards

**Comment by spacebel** [comment]
I'm using Ora2Pg v20 (I guess the latest).
The reason of using this old version is related to the very strict (and ununderstandable) policies of the customer.

If you tell me this is probably related to the PostGreSQL version, it would make me happy to add this to my argument for moving to a recent PostGreSQL (additionally to security, performance, functionalities, etc.).

Thanks.

**Comment by darold** [comment]
Can you send me a few lines of the export by ora2pg? My private email is gilles AT darold DOT net.

**Comment by darold** [comment]
Thanks for the sample files it helps a lot. Commit 0331abd solves this issue.

**Comment by dwbrock62** [comment]
This did not work for me.  I still get the "invalid input syntax for type bytea" error.

**Comment by darold** [comment]
Can you post the full error message?

**Comment by spacebel** [comment]
For information, I sent the following message to Gilles on 04/06/2019. Sorry for not reporting that on github.
(now my project is finished, and I simply avoided the COPY command in favor of the slower INSERT).

(Translated)

> Hi Gilles,
> I tested the new version with the encoding fix. I now use PostgreSQL 11.
> Unfortunately, I still have the same problem with COPY, even if data seems to be escaped correctly. The error message is the following:
> 
> [2019-06-04 13:47:36] ERROR (log error enabled): ERROR:  invalid byte sequence for encoding "UTF8": 0x89
> CONTEXT:  COPY tb_bgs_bincasts_aphisto_plots, line 1: "2018-02-10 07:48:10.732000       \x89504e470d0a1a0a0000000d49484452000002f8000003d40803000000efe5bd2800000..."
> 
> I don't have the problem with INSERT command.

I hope it helps.

**Comment by darold** [comment]
Yes sorry Christophe, I was very busy and try to get back to my favorite project but this is still difficult to find spare time. I will try to fix all reported/pending issue before summer but I'm not sure at all this will be possible.

**Comment by spacebel** [comment]
No worry. The tool is great and free, your support is regular and helpful... just to mention this didn't work on my side.

**Comment by darold** [comment]
Look like there was a regression in BLOB to bytea export in COPY mode, commit 805f6da might fix this issue.

**Comment by dwbrock62** [comment]
OK, now I see the problem.  The failures are occurring when migrating to columns with a data type of either "oid" or "lo".   Our application runs on both Oracle and PG, and has its own facility for initializing the schema, so I cannot change the target PG column types since these are what application expects.   So I assume that migration to "lo" and "oid" type columns is not supported?

**Comment by darold** [comment]
Oid data type is supported by Ora2Pg. About lo what is the Oracle data type? If you want to have the "same" application behavior as with BLOB you should export BLOB to Bytea, lo requires that you use lo* functions to deal with the data and Ora2Pg do not support it.

**Comment by dwbrock62** [comment]
It seems that for setting columns with data type oid you must also use lo* functions (ora2pg is trying to load with hex value and thus get the error "invalid input syntax for type oid")   The Oracle data types are BLOB.   I do not know why our application developers chose oid and lo data types for some of the BLOBs the PG implementation instead of bytea.  However, I am not able to change that.
