### ISSUE TITLE
Support for Postgresql version 11

### ISSUE THREAD

**Issue by myrach** [darold/ora2pg#779]
Does ora2pg supports for Postgresql V11 features where it converts the Procedures as "Create Procedure" instead of creating them as Function until version 10.x?

**Comment by darold** [comment]
Yes, use latest development code and set PG_VERSION to 11 in ora2pg.conf. Procedure are exported as PROCEDURE DDL.

**Comment by myrach** [comment]
Sounds good..Thanks!
