### ISSUE TITLE
postgresql TEST counts very different

### ISSUE THREAD

**Issue by rklaus** [darold/ora2pg#781]
We have a database that has over 2000 schemas, and some of the tables are in each schema.  I'm trying to compare one schema at at time.

In some cases the counts between oracle and postgres are correct.  However, there are several counts that have a high postgres value. 

Table audit_control_detail doesn't have the same number of column default value in source database (1) and in PostgreSQL (6).
Table pdfforms doesn't have the same number of column default value in source database (5) and in PostgreSQL (11825).
Table cpt doesn't have the same number of column default value in source database (0) and in PostgreSQL (14190).
Table pdffolios doesn't have the same number of column default value in source database (1) and in PostgreSQL (2365).
Table diag_codes doesn't have the same number of column default value in source database (0) and in PostgreSQL (2366).
Table audit_control doesn't have the same number of column default value in source database (4) and in PostgreSQL (24).
Table hcfa_forms doesn't have the same number of column default value in source database (3) and in PostgreSQL (2).

[TEST NOT NULL CONSTRAINTS COUNT]
ORACLEDB:ADDL_FIELD_GROUPS:0
POSTGRES:addl_field_groups:1
ORACLEDB:PDFFORMS:4
POSTGRES:pdfforms:18916

ORACLEDB:EN_RULES_RE_SWEEP:4
POSTGRES:en_rules_re_sweep:4
ORACLEDB:REPORT_SORT_ORDERS:2
POSTGRES:report_sort_orders:4730

ora2pg --type TEST --pg_schema common --conf ./config/ora2pg_TEST.conf
[ACCT.txt](https://github.com/darold/ora2pg/files/3121563/ACCT.txt)

**Comment by rklaus** [comment]
[ora2pg_TEST.conf.txt](https://github.com/darold/ora2pg/files/3121670/ora2pg_TEST.conf.txt)

**Comment by rklaus** [comment]
accidentally closed

**Comment by darold** [comment]
There might be a bug, I will investigate when I will have more time.

**Comment by darold** [comment]
Last release v21.0 fixes several issues on TEST count.
