### ISSUE TITLE
Encoding Problem

### ISSUE THREAD

**Issue by keakarsu** [darold/ora2pg#782]
Hi There,

I have a problem while exporting schema. Exported table characthers has shown incorrect.
Here is the incorrect form of table.

I have worked with last version of ora2pg.

CREATE UNLOGGED TABLE aktaraurun (
	"ÃœrÃœn adi" varchar(150),
	"etken madde/maddeler" varchar(150),
	"fÃrma adi" varchar(150),
	"ÃzÃn no" varchar(150),
	"ÃzÃn tarÃhÃ" varchar(150)
) ;

My locale settings here:

LANG=tr_TR.ISO8859-9
LC_CTYPE="tr_TR.ISO8859-9"
LC_NUMERIC="tr_TR.ISO8859-9"
LC_TIME="tr_TR.ISO8859-9"
LC_COLLATE="tr_TR.ISO8859-9"
LC_MONETARY="tr_TR.ISO8859-9"
LC_MESSAGES="tr_TR.ISO8859-9"
LC_PAPER="tr_TR.ISO8859-9"
LC_NAME="tr_TR.ISO8859-9"
LC_ADDRESS="tr_TR.ISO8859-9"
LC_TELEPHONE="tr_TR.ISO8859-9"
LC_MEASUREMENT="tr_TR.ISO8859-9"
LC_IDENTIFICATION="tr_TR.ISO8859-9"
LC_ALL=

Current encoding settings that will be used by Ora2Pg:
        Oracle NLS_LANG AMERICAN_AMERICA.WE8ISO8859P9
        Oracle NLS_NCHAR WE8ISO8859P9
        Oracle NLS_TIMESTAMP_FORMAT YYYY-MM-DD HH24:MI:SS.FF6
        Oracle NLS_DATE_FORMAT YYYY-MM-DD HH24:MI:SS
        PostgreSQL CLIENT_ENCODING LATIN5
        Perl output encoding ''

Showing current Oracle encoding and possible PostgreSQL client encoding:
        Oracle NLS_LANG AMERICAN_AMERICA.WE8ISO8859P9
        Oracle NLS_NCHAR WE8ISO8859P9
        Oracle NLS_TIMESTAMP_FORMAT YYYY-MM-DD HH24:MI:SS.FF6
        Oracle NLS_DATE_FORMAT YYYY-MM-DD HH24:MI:SS
        PostgreSQL CLIENT_ENCODING LATIN5

Do you have any suggestion for me?

**Comment by keakarsu** [comment]
Is anyone here?

**Comment by darold** [comment]
Have you tried without setting NLS_LANG and NLS_NCHAR in ora2pg.conf? The output should be UTF8 encoded, after that you can use iconv to convert to any other encoding you want. Now you know why it is a very bad idea and practice to use non ANSI C character in object names :-D

**Comment by keakarsu** [comment]
Okey, I will check it with iconv.

**Comment by keakarsu** [comment]
Hi there again,
I try to change binmode parameter to iso-8859-9 and latin5. But it throws me an error which "can't use open layer :encoding ...." while i run export.sh . Are the values of parameter is wrong? Also iconv is not bring me to success.

**Comment by keakarsu** [comment]
I changed some tables manually and I try to copy data. It brings me new error which is "column "▒r▒n adi" of relation "aktaraurun" does not exist" . Is there any way to avoid this issue..

**Comment by darold** [comment]
You can try to use REPLACE_COLS in ora2pg.conf to rename columns on the fly but as you have space in the column name too. I don't think it will works but you can try by double quoting the column name. If it don't work change line 12750 in file lib/Ora2Pg.pm of  current development code. Change:
```
my @rel = split(/[\s,]+/, $fields);
```
into
```
my @rel = split(/[,]+/, $fields);
```
and use comma as separator like in the REPLACE_COLS example.
