### ISSUE TITLE
PLSQL_PGSQL conversion did not removed DEFAULT NULL

### ISSUE THREAD

**Issue by Puttaz** [darold/ora2pg#783]
Hi,
I have a Issue with migrating stored procedures.
target PG is 9.6.1 Ora2PG 20.0
syntax error pops when migrating some procedures because DEFAULT NULL is not removed when conversion happened.

PG_VERSION set to 9.6.1
PLSQL_PGSQL	set to 1

**Comment by darold** [comment]
Hi,

Please post example it will save us lot of time.

Regards,

**Comment by Puttaz** [comment]
Sorry my bad,
and I think it was due to the variable name(TIME) we had.

create or replace PROCEDURE 
ADD_FOO(TIME VARCHAR2 DEFAULT NULL,ATT_TEXT BLOB DEFAULT EMPTY_BLOB()) AS
T_STR VARCHAR2(100);

CREATE OR REPLACE FUNCTION add_FOO (TIME text DEFAULT NULL ,ATT_TEXT bytea DEFAULT EMPTY_BLOB()) RETURNS VOID AS $body$
DECLARE

T_STR varchar(100);

changing the variable name manually, fixed the syntax issue.
Another syntax issue popped at EMPTY_BLOB(), currently looking at how to fix that.

Anyway is there any way to remove keywords , and change the DEFAULT values, like EMPTY_BLOB()

Thanks in Advance
Pubudu

**Comment by darold** [comment]
Commit e5127d8 fixes this issue.
