### ISSUE TITLE
Malformed UTF-8 character (fatal) at /usr/share/perl5/vendor_perl/Ora2Pg.pm line 13005

### ISSUE THREAD

**Issue by bsislow** [darold/ora2pg#785]
Running ora2pg version 20.0 against Oracle 11.2.0.4.

Getting:

```
$ ora2pg -t SHOW_VERSION -c a.conf
Malformed UTF-8 character (fatal) at /usr/share/perl5/vendor_perl/Ora2Pg.pm line 13005.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(HOST=10.244.6.24)(PROTOCOL=tcp)(PORT=44251))(CONNECT_DATA=(SID=COREP))) at /usr/share/perl5/vendor_perl/Ora2Pg.pm line 13005.
```

Conf file; redacted for sensitive details:

```
ORACLE_HOME             /u01/app/oracle/product/11.2.0/db_1
ORACLE_DSN              dbi:Oracle:host=*********;sid=*********;port=*********
ORACLE_USER             *********
ORACLE_PWD              *********

PG_DSN                  dbi:Pg:dbname=*********;host=*********;port=*********
PG_USER                 *********
PG_PWD                  *********
PG_VERSION              9.6.12

# oracle source:
SCHEMA                  *********
CREATE_SCHEMA           0
EXPORT_SCHEMA           0
TABLES                  *********
TYPE                    TABLE
SKIP                    fkeys,pkeys,ukeys
```

**Comment by darold** [comment]
Please use latest code and report the new error message if still present.

**Comment by bsislow** [comment]
Aren't we on the latest?
```
$ ora2pg -v
Ora2Pg v20.0
```

**Comment by darold** [comment]
Install from `wget https://github.com/darold/ora2pg/archive/master.zip` or git clone and you will be on latest.

**Comment by bsislow** [comment]
We are still getting this after installing the latest version today as you can see based on the timestamp below.

```
$ ora2pg -c a.conf
Malformed UTF-8 character (fatal) at /usr/local/share/perl5/Ora2Pg.pm line 13068.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(HOST=10.244.6.24)(PROTOCOL=tcp)(PORT=44251))(CONNECT_DATA=(SID=COREP))) at /usr/local/share/perl5/Ora2Pg.pm line 13068.
$ ora2pg -v
Ora2Pg v20.0
$ which ora2pg
/usr/local/bin/ora2pg
$ ls -l /usr/local/bin/ora2pg
-r-xr-xr-x 1 root root 38341 May 23 08:50 /usr/local/bin/ora2pg
```

Note that we upgraded Oracle from 11.2.0.3 to 11.2.0.4 and this does not work against 11.2.0.4. We used to use ora2pg to connect to the _same_ instance when it was 11.2.0.3 without issue using ora2pg 19.1.

**Comment by tmajjiga** [comment]
Hi Any updates on this request is greatly appreciated... we are still stuck...

**Comment by darold** [comment]
Seems that there is non UTF-8 characters in some of your Oracle code. I don't know what you are trying to export but there is some comment or object names that can not be exported using UTF8 encoding. Please post here the full result of command: `ora2pg -c a.conf -t SHOW_ENCODING`

And what objects are you exporting (value of TYPE configuration directive)?

**Comment by bsislow** [comment]
I still do not believe this is a UTF-8 issue; please see my prior post. This is _only_ happening after the upgrade from 11.2.0.3 to 11.2.0.4; we can't even run SHOW_ENCODING:

```
pgsngv001p.chi:/home/postgres/bsislow(postgres:45221)$ ora2pg -c a.conf -t SHOW_ENCODING
Malformed UTF-8 character (fatal) at /usr/local/share/perl5/Ora2Pg.pm line 13068.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(HOST=******)(PROTOCOL=tcp)(PORT=******))(CONNECT_DATA=(SID=******))) at /usr/local/share/perl5/Ora2Pg.pm line 13068.
```

We are using TYPE TABLE.

**Comment by darold** [comment]
Looks like there is some corruption? Can you create a DDL export using Oracle tool?

**Comment by bsislow** [comment]
No, I don't think that's it. I can change the TABLE to any table in the target schema and I can reproduce the error above with "-t SHOW_ENCODING".

How did you come to this conclusion?

Can we provide any other kind of log or verbose output - perhaps a stack trace - to you?

**Comment by tmajjiga** [comment]
Hi 
Any suggestions as how we can troubleshoot it further..

**Comment by darold** [comment]
I don't know what happen, the error occurs in a function _remove_comment() that is not use with the SHOW_ENCODING action. What you cant try is to add the following before line 13068 IN Ora2Pg.pm:
```
print STDERR "DEBUG: $$content\n";
```
and report the output if it don't fail.

**Comment by bsislow** [comment]
I added the line which produced quite a bit of output. Can I send this directly to you via email?

**Comment by darold** [comment]
Yes please.

**Comment by bsislow** [comment]
Emailed directly to you via gilles@d****d.net.

**Comment by darold** [comment]
Got it. The content is in format: `Non-ISO extended-ASCII text` that mean that you have some non printable character in the code. When running `iconv -f ASCII -t UTF-8 log_report.txt` iconv fail with error:
```
iconv: illegal input sequence at position 66134
```
and looking at this position we have:
```
...Received Ã¢â<82>¬â<80><9c> A...
```
then same problem at offset 197064:
```
...Received <96> A...
```
Once these two problem are fixed the file type is `ASCII text`.

I have no solution for that outside modify the source Oracle code. The non printable characters are in comment so there is no risk at removing them.


```

**Comment by bsislow** [comment]
It appears these issues are stemming from a stored procedure. If we are using TYPE TABLE, why are stored procedures being scanned - and can we skip them? They are not necessary for this exercise. Thanks.

**Comment by darold** [comment]
For type TABLE no, yesterday I have pushed a fix to not look to function metadata with SHOW_* action so you might not have the error using SHOW_ENCODING.

**Comment by darold** [comment]
I've just pushed commit fbf969 that adds the NO_FUNCTION_METADATA configuration directive to ora2pg.conf. When enabled it forces Ora2Pg to not look for function declaration. So just updating to latest development code and adding:
```
NO_FUNCTION_METADATA     1
```
should help you to get ride of this error.

Regards,

**Comment by tmajjiga** [comment]
Hi,
Thanks for the update. Can you please let us know as where we can pick the new compiled or latest version which has this updated code in it.

**Comment by bsislow** [comment]
The new commit fixes the issue. You can close this case. Thank you.
