### ISSUE TITLE
Renaming temporary file

### ISSUE THREAD

**Issue by ayadahm** [darold/ora2pg#786]
Hi
Under my conversion process , I can see in my log file 
Renaming temporary file ./data/tmp_ANSWER_data.sql into ./data/ANSWER_data.sql.
Now it is still on that for many hours . I do not know what is doing ?? can I see what is doing ?

Many thanks

**Comment by darold** [comment]
Hi, I don't think this is this part that is blocking it is just file renaming. Data are exported into a temporary file and renamed into the final name unless there is an error, this prevent partial data write. Some time the connection to Oracle hangs, typing ctrl+c and restarting ora2pg solves the issue.
