### ISSUE TITLE
Invalid quotes in column default

### ISSUE THREAD

**Issue by just-doit** [darold/ora2pg#788]
If the default value of a column is a **text** containing the expression `trunc()`, it will be converted to `date_trunc('day',..)`, which is correct.

However, the quotation marks are not masked correctly.

Example:
`SCHEDULE_INTERVAL              VARCHAR2(500 CHAR) DEFAULT 'trunc(sysdate)+1',`

becomes
`schedule_interval varchar(500) DEFAULT 'date_trunc('day', LOCALTIMESTAMP)+1',`

**Comment by just-doit** [comment]
I found another issues regarding quoting default values.
In one table there's the following row:
`ID_OBJECT               VARCHAR2(24 CHAR)     DEFAULT 'n.a.'                NOT NULL,`
It gets converted to:
`id_object varchar(24) NOT NULL DEFAULT ''n.a.'',`

**Comment by darold** [comment]
Commit e9f4fd0 fixes this issue.
