### ISSUE TITLE
bug on REPLACE_AS_BOOLEAN parametes on ora2pg.conf

### ISSUE THREAD

**Issue by jacks33** [darold/ora2pg#790]
Hello,
I want to convert all number(1) fields from oracle to boolean.
*and* I have two tables with char(1) fields to convert as well

If I set 
REPLACE_AS_BOOLEAN    NUMBER:1
export works fine

If I set NUMBER:1 TABLE1.COLUMN2 TABLE1.COLUMN2
export works for all fields of type NUMBER(1) but not for my two tables fields of type char(1) are not translated.

Also I tried to prefix tables with schema but I have the same behaviour : export don't translate.

**Comment by darold** [comment]
What export type are you using TABLE or COPY/INSERT? If you are exporting data what are the values in these columns?

**Comment by darold** [comment]
Too late but to  give the solution to this issue:
```
REPLACE_AS_BOOLEAN NUMBER:1 CHAR:1
```
The value of REPLACE_AS_BOOLEAN is a space separated list of datatype:precision
