### ISSUE TITLE
ora2pg terminated with error during copy of table data.

### ISSUE THREAD

**Issue by tmajjiga** [darold/ora2pg#795]
DBD::Pg::db pg_putcopyend failed: ERROR:  invalid byte sequence for encoding "UTF8": 0xed 0xb9 0xa2GATIVE_VALUES_1 in progress.
CONTEXT:  COPY negative_values_1, line 4459 at /usr/share/perl5/vendor_perl/Ora2Pg.pm line 14578.
DBI::db=HASH(0x2bee688)->disconnect invalidates 1 active statement handle (either destroy statement handles or call finish on them before disconnecting) at /usr/share/perl5/vendor_perl/Ora2Pg.pm line 13744.
Aborting export...
[=>                       ]  37470000/668150075 rows (5.6%) Table NEGATIVE_VALUES_1 (893 sec., 41959 recs/sec)
DBD::Pg::db do failed: server closed the connection unexpectedly) - (893 sec., avg: 0 recs/sec), NEGATIVE_VALUES_1 in progress.
       This probably means the server terminated abnormally
       before or while processing the request. at /usr/share/perl5/vendor_perl/Ora2Pg.pm line 7526.

**Comment by tmajjiga** [comment]
Getting the above error during copy of non-partitioned single table data.

**Comment by tmajjiga** [comment]
Config file:
ORACLE_HOME             /u01/app/oracle/product/11.2.0.4/db_1
ORACLE_DSN              dbi:Oracle:host=10.244.6.24;sid=corep;port=1521
ORACLE_USER             SYSTEM
ORACLE_PWD              XXXXXX

PG_DSN                  dbi:Pg:dbname=negval;host=pgsngv001p.chi;port=45221
PG_USER                 negval
PG_PWD                  XXXXX
PG_VERSION              9.6.12

# oracle source:
SCHEMA                  CORE
CREATE_SCHEMA           0
EXPORT_SCHEMA           0
TABLES                  NEGATIVE_VALUES_1
#WHERE                   MODIFIED >= to_timestamp('2018-06-01 00:00:00','YYYY-MM-DD HH24:MI:SS') and MODIFIED < to_timestamp('2018-06-07 00:00:00','YYYY-MM-DD HH24:MI:SS')

WHERE                   ID >= 684621 and ID < 5237260007031849593
NO_FUNCTION_METADATA     1


# pg target:
TYPE                    COPY
ORACLE_COPIES           8
JOBS                    16
DATA_LIMIT              10000

**Comment by tmajjiga** [comment]
pgsngv001p.chi:/home/postgres/tmajjiga(negval:45221)$ ora2pg -c copy_neg_val.conf -t SHOW_ENCODING
Current encoding settings that will be used by Ora2Pg:
        Oracle NLS_LANG AMERICAN_AMERICA.AL32UTF8
        Oracle NLS_NCHAR AL32UTF8
        Oracle NLS_TIMESTAMP_FORMAT YYYY-MM-DD HH24:MI:SS
        Oracle NLS_DATE_FORMAT YYYY-MM-DD HH24:MI:SS
        PostgreSQL CLIENT_ENCODING UTF8
        Perl output encoding ''
Showing current Oracle encoding and possible PostgreSQL client encoding:
        Oracle NLS_LANG AMERICAN_AMERICA.AL32UTF8
        Oracle NLS_NCHAR AL32UTF8
        Oracle NLS_TIMESTAMP_FORMAT YYYY-MM-DD HH24:MI:SS
        Oracle NLS_DATE_FORMAT YYYY-MM-DD HH24:MI:SS
        PostgreSQL CLIENT_ENCODING UTF8

**Comment by bsislow** [comment]
oracle:
```
SQL> SELECT value$ FROM sys.props$ WHERE name = 'NLS_CHARACTERSET' ;

VALUE$
--------------------------------------------------------------------------------
AL32UTF8
```

pg:
```
postgres=# show server_encoding ;
 server_encoding
-----------------
 UTF8
```

**Comment by darold** [comment]
@tmajjiga please post a `DESC NEGATIVE_VALUES_1`

**Comment by bsislow** [comment]
```
SQL> desc core.negative_values_1
 Name                                      Null?    Type
 ----------------------------------------- -------- ----------------------------
 ID                                        NOT NULL NUMBER(24)
 SYS_ID                                    NOT NULL NUMBER(38)
 HIERARCHY_ID                              NOT NULL NUMBER(24)
 SHARE_HIERARCHY_ID                        NOT NULL NUMBER(24)
 DATA_HEADER_ID                                     NUMBER(24)
 DATA_TRANSACTION_ID                                VARCHAR2(4000)
 RESOLUTION_ID                                      NUMBER(24)
 RESOLVED_BY                                        VARCHAR2(4000)
 NEGATIVE_TABLE_LOGICAL_ID                 NOT NULL NUMBER(24)
 NEGATIVE_VALUE                            NOT NULL VARCHAR2(750)
 NEGATIVE_VALUE_ORIGINAL                            VARCHAR2(4000)
 IS_ENCRYPTED                              NOT NULL NUMBER(38)
 BUSINESS_TYPE_ID                                   NUMBER(24)
 LOGICAL_TYPE_ID                                    NUMBER(24)
 IS_NEGATIVE                               NOT NULL NUMBER(38)
 STRENGTH_LEVEL                            NOT NULL NUMBER(38)
 TIMES_HIT                                 NOT NULL NUMBER(38)
 LAST_TIME_HIT                                      TIMESTAMP(6) WITH TIME ZONE
 LAST_DATA_HIT                                      NUMBER(24)
 LAST_DATA_TRANSACTION_ID                           VARCHAR2(4000)
 ESTABLISHED                               NOT NULL TIMESTAMP(6) WITH TIME ZONE
 MODIFIED                                  NOT NULL TIMESTAMP(6) WITH TIME ZONE
 ESTABLISHED_BY                            NOT NULL VARCHAR2(4000)
 MODIFIED_BY                               NOT NULL VARCHAR2(4000)
```

**Comment by darold** [comment]
Well it seems that you have some non utf8 chars in one of the varchar2 column. You can try to export this table only by enabling LOG_ON_ERROR with DATA_LIMIT set to 100. Ora2Pg will continue to import data by will register to file all bulk of data in error. See LOG_ON_ERROR in configuration file.
