### ISSUE TITLE
Wrong translation of "where [... and]  myColumnName is NULL " in an UPDATE statement

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#796]
**Oracle:**
update t_customer set DATE_SUSPENDED_BEGIN = v_now, IS_LOCKED = 1, NOTICE = 'Suppr on  '||to_char(v_now,'DD/MM/YYYY HH24:MI')||' '||notice||''
        where DATE_SUSPENDED_BEGIN is null and notice not like 'Suppr on %' and customer_id = v_customer_id and (IS_LOCKED = 0 or IS_LOCKED is null);

**ora2pg:**
update t_customer set DATE_SUSPENDED_BEGIN = v_now, IS_LOCKED = 1, NOTICE = 'Suppr on '||to_char(v_now,'DD/MM/YYYY HH24:MI')||' '||notice||''
        where DATE_SUSPENDED_BEGIN = NULL and notice not like 'Suppr on %' and customer_id = v_customer_id and (IS_LOCKED = 0 or IS_LOCKED = NULL);

__**Should be:**__
update t_customer set DATE_SUSPENDED_BEGIN = v_now, IS_LOCKED = 1, NOTICE = 'Suppr on '||to_char(v_now,'DD/MM/YYYY HH24:MI')||' '||notice||''
        where DATE_SUSPENDED_BEGIN is NULL and notice not like 'Suppr on %' and customer_id = v_customer_id and (IS_LOCKED = 0 or IS_LOCKED is NULL);

Beware it looks like reversing bug #192, but it's **not**: both corrections must coexist. That of #192 concerns assignation of new value while this bug concerns **filtering criteria**.

**Comment by edelanoe** [comment]
FYI, in a workaround script, I have put the following:
	$allCode =~ s/(\s)(where|and|or)(\s)([^;]*?) = NULL(\s+and|\s+or|\s*;|\s*\))/$1$2$3$4 is null$5/igs;
... BUT it did not translate one of my "is null", I had to add this kind of temporary specific substitution:
	$allCode =~ s/and \(DATE_VALIDITY_END = NULL /and (DATE_VALIDITY_END is null /igs;

**Comment by darold** [comment]
Commit 07acca6 fixes this issue.
