### ISSUE TITLE
OF clause is missing in update trigger

### ISSUE THREAD

**Issue by just-doit** [darold/ora2pg#797]
If a trigger is configured to fire on not only updates but inserts as well, the OF clause is missing from the resulting trigger code.

Example:
The oracle trigger is configured like this:
```
CREATE OR REPLACE TRIGGER tr_acc_set_bank_name
   BEFORE INSERT OR UPDATE OF account_bic
   ON accounts
   FOR EACH ROW
```
The postgresSQL code looks like this:
```
CREATE TRIGGER tr_acc_set_bank_name
        BEFORE INSERT OR UPDATE ON accounts FOR EACH ROW
```

I think the problematic part is the following line:
https://github.com/darold/ora2pg/blob/8fb438dde348e3d6cf351d218f52591deca8c2a4/lib/Ora2Pg.pm#L4527
The condition `$trig->[2] eq 'UPDATE'` is false for triggers having more than just a plain UPDATE trigger event.

**Comment by darold** [comment]
Commit cfdbfb5 fixes this issue.
