### ISSUE TITLE
Procedures are called with PERFORM instead of CALL

### ISSUE THREAD

**Issue by just-doit** [darold/ora2pg#798]
Setting `PG_VERSION` to 11 enables `pg_supports_procedure`, which in turn makes oracle procedures become postgreSQL procedures (instead of functions).

But the procedure calls are still translated to `PERFORM <procedure_name>` instead of `CALL <procedure_name>`.

**Comment by darold** [comment]
This might have been fixed I can not reproduce the problem, I'm closing the issue but feel free to reopen it if the issue still happen. I need the Oracle code to reproduce.
