### ISSUE TITLE
USE_UNACCENT = 0 generates index on unaccent_immutable(column)

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#801]
Hello Darold,

I have tried to migrate Oracle TEXT indexes with USE_UNACCENT = 0 (no need to remove accents).
But ora2pg generates the index on unaccent_immutable(myColumnName) instead of bare myColumnName. The behaviour is as if use_unaccent was = 1. Im I configuring wrong ?

Sample:
Oracle -->  CREATE INDEX LP_SEARCH_SUB_IDX ON T_VEHICLE_SUBSCRIPTION (LICENCE_PLATE) 
   INDEXTYPE IS CTXSYS.CTXCAT  PARAMETERS ('wordlist FUZZY_PREF');

ora2pg --> CREATE INDEX lp_search_sub_idx ON t_vehicle_subscription USING gin(unaccent_immutable(licence_plate) gin_trgm_ops);

**Comment by mlechner** [comment]
I can confirm this.

On import_all.sh I get:

Function unaccent_immutable(character varying) does not exist.

**Comment by darold** [comment]
Commit b0a71d1 fixes this issue
