### ISSUE TITLE
rownumber -> ROW_NUMBER()

### ISSUE THREAD

**Issue by black-snow** [darold/ora2pg#803]
When I export my schema Oracle's `rownumber` does not get converted to `ROW_NUMBER()`. The import thus fails.

I wrote a simple replacement that I run after the export but maybe we can add this to ora2pg itself:

```bash
sed -i 's/rownum/ROW_NUMBER() over () AS rownum/g' schema/views/some_view.sql
```

I don't acutally know yet if `ROW_NUMBER() over ()` is requivalent to `ruwnumber`. Will have to review this once I'm done.

**Comment by SebAlbert** [comment]
The difference is that in PostgreSQL, you cannot use a window function (such as `row_number() OVER ()`) in a `WHERE` clause, whereas `ROWNUM` in Oracle can be used inside `WHERE`. You would need a sub-select or CTE in PostgreSQL for that to work.

**Comment by black-snow** [comment]
Good to know. In the select clause however we should be able to use this. Works fine for my view at least.

**Comment by darold** [comment]
Commit a4d945b add translation of ROWNUM in target list into ROW_NUMBER() over (). In the WHERE clause Ora2Pg translate ROWNUM into LIMIT+OFFSET.
