### ISSUE TITLE
Limit via WHERE but fk constraint fails

### ISSUE THREAD

**Issue by black-snow** [darold/ora2pg#804]
In order to test the outcome of the conversion I added `WHERE ROWNUM < 1000` to my ora2pg.conf. This works quite well but fails when foreign keys get recreated for, of course, many of the referenced rows didn't get copied.
Is there any clever solution to this?

I need the foreign keys right away so only reactivating them after a full dump is not an option for me.

Thanks in advance!

**Comment by darold** [comment]
When you want to test data import you must not apply FK. If this is not an option for you might first import data from the referenced table. I don't see other solution.
