### ISSUE TITLE
Procedure Extraction Issue with Ora2pg

### ISSUE THREAD

**Issue by venkatsusarla** [darold/ora2pg#805]
Hello Darold,

In one of my migration project I was trying to extract the database objects (tables,functions and so on). I am able to extract all objects expect "procedures", where i am hitting below error after ora2pg scans 7 out of 12 procedures.

Could you suggest why i am getting this error, especially because it is able to extract all other objects.

Command Used:
-------------------
 ora2pg -t PROCEDURE -o procedure.sql -b <directory> -c <config_file>
[==============>          ]  7/12 procedures (58.3%) generating XX_XX_XX_XX

Error I am Getting:
--------------------
Unmatched ) in regex; marked by <-- HERE in m/^) <-- HERE $/ at /usr/lib/perl5/site_perl/5.8.8/Ora2Pg/PLSQL.pm line 2139.

Let me know if you need anymore information.

Regards,
Venkat

**Comment by darold** [comment]
Please upgrade your Ora2Pg installation.

**Comment by venkatsusarla** [comment]
Thanks a lot, I upgrade to ora2pg 20.0 and it works well.

Regards,
Venkat
