### ISSUE TITLE
DEFINED_PK generating error

### ISSUE THREAD

**Issue by venkatsusarla** [darold/ora2pg#806]
Hi Darold,

I am using ora2pg20.0 version for migrating oracle to postgres. During one of my initiative to speed up extraction of a 79gb table, I wanted to use ORACLE_COPIES and DEFINED_PK so that i can make use of 8 core with 64gb ram server which i have.
However I am getting the below error during the extraction process.
```
DBD::Oracle::st execute failed: ORA-01722: invalid number (DBD ERROR: error possibly near <*>
 indicator at char 547 in 'SELECT <column_list> FROM "<table_owner>"."<table_name>" a WHERE
 ABS(MOD(<*><primary_key_cloumn_name>, 8)) = :p1') [for Statement "SELECT <column_list> 
FROM "<table_owner>"."<table_name>" a WHERE ABS(MOD(<primary_key_cloumn_name>, 8)) =
 ?" with ParamValues: :p1=0] at <location>/ora2pg-20.0/lib/Ora2Pg.pm line 14090.
```
Config File Entry : 
```
-------------------
ORACLE_COPIES       8
DEFINED_PK             <table_name>:<primary_key_column_name>
ALLOW                      <table_name>
```
The extraction works well when I remove DEFINED_PK, but very slow.

Cloud you please suggest us the reason of this problem?

Regards,
Venkat

**Comment by darold** [comment]
It seems that the PK of this table doesn't contains only numbers, perhaps a INF? Have a look and try to fix the problematic number in Oracle. Otherwise if there is some other numeric column you can use:
```
DEFINED_PK     MYTABLE:MYOTHERCOL
```

**Comment by venkatsusarla** [comment]
Hi Darold,

Yes the primary column is defined as varchar2, There are other columns which are number, but the data under that column might not be unique as it is with primary key, Is it fine? and ora2pg would be able to extract all the data?

Regards,
Venkar

**Comment by darold** [comment]
You can not give a non numeric column to DEFINED_PK. You can give a column with datatype NUMBER that is not unique, the only things is that probably MOD 8 could not have an equal partition of rows, but obviously this could be the case with a unique constraint too.
