### ISSUE TITLE
Predefined PL/SQL Exception invalid_number not handle

### ISSUE THREAD

**Issue by CesarChaMal** [darold/ora2pg#810]
Error while traslating 

Exception | Oracle Error | SQLCODE Value
INVALID_CURSOR | ORA-01001 | -1001
INVALID_NUMBER | ORA-01722 | -1722
LOGIN_DENIED | ORA-01017 | -1017
NO_DATA_FOUND | ORA-01403 | +100

### Original code

create or replace function fu_adm_getvar_as_number (ent IN VARCHAR2, ets IN VARCHAR2, var IN VARCHAR2, prg IN VARCHAR2, st IN VARCHAR2) RETURN VARCHAR2
IS
  defval VARCHAR2(200);
  format VARCHAR2(200);
BEGIN
    -- get var
	select REGEXP_REPLACE(fu_adm_getvar(ent, ets, var, prg, st), '\s', '') into defval from dual;
    -- create number format
    select REGEXP_REPLACE(defval, '\d', '9') into format from dual;
    -- convert var to number
    select to_number(defval, format) into defval from dual;

    -- return value
    RETURN defval;

    EXCEPTION
    when invalid_number then
        dbms_output.put_line('*** Exc: invalid number in T_IRC_VAR');
        RAISE;
    when others then
        RAISE;

END;

### Traslated

CREATE OR REPLACE FUNCTION dmsirc0115.fu_adm_getvar_as_number (ent text, ets text, var text, prg text, st text) RETURNS varchar AS $body$
DECLARE

  defval varchar(200);
  format varchar(200);

BEGIN
    -- get var
	select REGEXP_REPLACE(fu_adm_getvar(ent, ets, var, prg, st), '\s', '') into STRICT defval;
    -- create number format
    select REGEXP_REPLACE(defval, '\d', '9') into STRICT format;
    -- convert var to number
    select to_number(defval, format) into STRICT defval;

    -- return value
    RETURN defval;

    EXCEPTION
    when invalid_number then
        RAISE NOTICE '*** Exc: invalid number in T_IRC_VAR';
        RAISE;
    when others then
        RAISE;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION dmsirc0115.fu_adm_getvar_as_number (ent text, ets text, var text, prg text, st text) FROM PUBLIC;

### Error

su - postgres -c "psql -1 rtdms -f /opt/oracle/functions/functions.sql";
SET
SET
CREATE FUNCTION
psql:/opt/oracle/functions/functions.sql:168: ERROR:  unrecognized exception condition "invalid_number"
CONTEXT:  compilation of PL/pgSQL function "fu_adm_getvar_as_number" near line 18

**Comment by darold** [comment]
I have added the following translation for the Oracle exception:

        'VALUE_ERROR' => 'data_exception',
        'INVALID_NUMBER' => 'data_exception',
        'INVALID_CURSOR' => 'invalid_cursor_state',
        'NO_DATA_FOUND' => 'no_data_found',
        'LOGIN_DENIED' => 'connection_exception',

Let me know if that's correspond to the PG exception you have used.
