### ISSUE TITLE
Security problem with ora2pg

### ISSUE THREAD

**Issue by did16** [darold/ora2pg#811]
Hi
In my company we want to carry out a campaign to estimate the complexity of Oracle migration to PostgreSQL. for that we want to use ora2p-scanner. 
The problem is that you have to use a powerful Oracle account: SYSTEM.We want to use an account with the least possible privilege. 
we have determined that the necessary privileges are:
GRANT SELECT ANY DICTIONARY TO dbaesa;
GRANT SELECT_CATALOG_ROLE TO dbaesa;
grant connect to dbaesa ;
grant select any table to dbaesa ;
Why do we need the "select any table" privilege  ?
ora2pg semble interroger les tables applicatives...

**Comment by darold** [comment]
A DBA account should not be necessary, some objects like ROLE will just not be extracted. Use any user without DBA privilege but set USER_GRANTS to 1 in ora2pg.conf.

**Comment by did16** [comment]
Hi Gilles
Thank your for your rapid answer .
But I have made some tests with USER_GRANTS to 1 in ora2pg.conf.
The user must absolutly have these privileges :
<<
grant connect, CREATE SESSION to PERFDBA ;
GRANT SELECT ANY DICTIONARY TO PERFDBA;
GRANT SELECT_CATALOG_ROLE TO PERFDBA;
grant select any table to perfdba ;
<<
the problem is "select any table" which grants the user, the possibility to query data from application tables.
why does ora2pg-scanner make some queries like  : 
select * from <application_table> where 1=0 ; ?
this forces the user to have the privilege SELECT ANY TABLE.
it is a big security problem at EDF. 
is there a way to avoid this?
Thanks in advance

**Comment by did16** [comment]
> but set USER_GRANTS to 1 in ora2pg.conf.
Is there any documentation on the parameter USER_GRANTS ?

**Comment by darold** [comment]
Sorry I don't have enough time right now, for documentation about this directive look at http://ora2pg.darold.net/documentation.html#Oracle-database-connection I will have more time after PgConf Asia that I have to prepare. I have taken two weeks of holidays after that so I might found more time to answer and fix some other Ora2Pg issues. I'm reopening the issue to not forget.

**Comment by darold** [comment]
Query `select * from <application_table> where 1=0 ; ` is used to retrieve the column name and data type at driver level, changing that will take me too much time. I'm closing this issue it won't be done for the moment.
