### ISSUE TITLE
DBD::Oracle::st fetchall_arrayref failed: ORA-01801: date format is too long for internal buffer

### ISSUE THREAD

**Issue by lingeshpes** [darold/ora2pg#812]
Hi,

Facing below issue while doing data migration from oracle to postgres,This is happening for date field.

DBD::Oracle::st fetchall_arrayref failed: ORA-01801: date format is too long for internal buffer (DBD ERROR: ORA-01801 error on field 23 of 42, ora_type 12) [for Statement "SELECT EXTERNAL_ID" FROM "table_name" a"] at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 12404.
ERROR: ORA-01801: date format is too long for internal buffer (DBD ERROR: ORA-01801 error on field 23 of 42, ora_type 12)

Thanks in Advance

**Comment by darold** [comment]
Hi,

This message is usually because you might have corrupted data in Oracle. Ora2Pg can not help in this case, this must be fixed in Oracle. See http://www.dba-oracle.com/t_ora_01801_date_format_is_too_long_for_internal_buffer.htm for example.

Also I don't see the relation between the message and the statement, I doubt that EXTERNAL_ID is a date type, I guess that you have modified the statement and just kept the first column.

**Comment by sensuraj92** [comment]
Hi,

here is the full query for this issue

DBD::Oracle::st fetchall_arrayref failed: ORA-01801: date format is too long for internal buffer (DBD ERROR: ORA-01801 error on field 23 of 42, ora_type 12) [for Statement "SELECT "RECORD_ID","LEVEL_TYPE","LEVEL_ID","SOURCE_ID","SOURCE_TYPE","ISSUE","ISSUE_DESC","CATEGORY_ID","DETECTED_DATE","DETECTED_BY","STATUS_ID","STATUS_DATE","RESOLUTION_REQUIRED","EXPECTED_RESOL_DATE","NOTIFIED_YN","CREATED_ON","CREATED_BY","LAST_MODIFIED_BY","LAST_MODIFIED_ON","CHECKLIST_ID","ASSIGNED_TO","RESOLVED_BY","OCCURRED_ON","RISK_ID","LOCKED_YN","NOTIFY_EMAIL_ADDRESSES","ISSUE_NO","SUBJECT_RELATED_YN","PROTOCOL_NC_YN","GCP_NC_YN","WAIVER_OBTAINED_ID","WAIVER_GRANTED_BY_ID","WAIVER_GRANTED_DATE","EXP_RPT_TO_CLIENT","IRB_NOTIFIED_DATE","NOTIFIED_DATE","IRB_NOTIFY","DATA_ANALYSIS_IMPACT_YN","DEVIATION_YN","SEVERITY_ID","SUBJECT_ID","EXTERNAL_ID" FROM "TCTM_50"."AGC_ISSUES" a"] at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 12404.
ERROR: ORA-01801: date format is too long for internal buffer (DBD ERROR: ORA-01801 error on field 23 of 42, ora_type 12)

**Comment by darold** [comment]
Well you have a corruption in a record of column OCCURRED_ON, you should try to find which one is failing and fix it. If there is not lot of rows in this table you can use `-t INSERT -L 100` to export data with INSERT statements by chunk of 100 rows and enable LOG_ON_ERROR to have the block of line that is failing in file TABLENAME_error.log. Then you can see what is exported, I never do that and don't know what will happen but you can try it.

**Comment by lingeshpes** [comment]
Hi,

Found the cause, its considering to_char() while fetching date field, even though date is having value, while conversion its considering as 0000 and throwing the exception.

select to_char(OCCURRED_ON, 'yyyy-mon-dd') c1, OCCURRED_ON c2 from  AGC_ISSUES where to_char(OCCURRED_ON, 'yyyy-mon-dd') = '0000-000-00'; 

c1                     c2
0000-000-00	06-AUG-07
0000-000-00	27-SEP-16
0000-000-00	08-SEP-73
0000-000-00	12-DEC-17

**Comment by darold** [comment]
Take care that sqlplus lies, it is able to extract date but the data are broken. If you look at the query used by Ora2Pg there is no call to TO_CHAR(), this is a basic `SELECT col1,col1,... FROM TABLE`.
Probably this is because the date format is set by:
```
ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS'
```
In ora2pg.conf there is a directive called ORA_INITIAL_COMMAND, you can try to set it as follow to see if that's solve the issue:
```
ORA_INITIAL_COMMAND
    ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD'
```
or any other that an Oracle expert can suggest you. If this can not help I'm dry on the subject.

**Comment by lingeshpes** [comment]
> Take care that sqlplus lies, it is able to extract date but the data are broken. If you look at the query used by Ora2Pg there is no call to TO_CHAR(), this is a basic `SELECT col1,col1,... FROM TABLE`.
> Probably this is because the date format is set by:
> 
> ```
> ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS'
> ```
> 
> In ora2pg.conf there is a directive called ORA_INITIAL_COMMAND, you can try to set it as follow to see if that's solve the issue:
> 
> ```
> ORA_INITIAL_COMMAND
>     ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD'
> ```
> 
> or any other that an Oracle expert can suggest you. If this can not help I'm dry on the subject.

Thanks for your Inputs.
