### ISSUE TITLE
FDW has no output

### ISSUE THREAD

**Issue by thaala** [darold/ora2pg#813]
Hi,

i found the idea to use PostGres as a frontend before complete migration from Oracle genious.
Therfore i want to use export TYPE FDW to get a script which create fdw wrapper to oracle database. 
Unfortunately no output. In opposite using export Type TABLE is working well.
PostGres V11.5 64 Bit
Oracle Instantclient 12.2. 64 Bit
Perl: This is perl 5, version 24, subversion 3 (v5.24.3) built for MSWin32-x64-multi-thread

**Comment by darold** [comment]
Looks it is broken. I wilt check that.

**Comment by darold** [comment]
Commit b8045ad fix this issue and several other export problem with FDW action.
