### ISSUE TITLE
Malformed UTF-8 character: \xa7 (unexpected continuation byte 0xa7, with no preceding start byte) 

### ISSUE THREAD

**Issue by lingeshpes** [darold/ora2pg#814]
Hi,

Getting below exception while generating Oracle TABLE DDL Statements

Malformed UTF-8 character: \xa7 (unexpected continuation byte 0xa7, with no preceding start byte) in split at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 11411.
Malformed UTF-8 character (fatal) at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 11411.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle //lscmprvl.ckxob8wdhu9v.eu-west-1.rds.amazonaws.com:1521/lscmprvl at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 11411.
panic: POPSTACK

Tried below statement to check oracle database connectivity, it throws same error

C:\ora2pg>ora2pg -t SHOW_VERSION -c tenant_platform_ddl2.conf

WARNING: target PostgreSQL version must be set in PG_VERSION configuration directive. Using default: 11
Malformed UTF-8 character: \xa7 (unexpected continuation byte 0xa7, with no preceding start byte) in split at C:/Strawberry/perl/site/li
Malformed UTF-8 character (fatal) at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 13005.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(PORT=1521)(HOST=lscmprv
PROTOCOL=tcp))(CONNECT_DATA=(SID=lscmprvl))) at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 13005.
panic: POPSTACK

Thanks in Advance

**Comment by darold** [comment]
You might have non utf8 characters in an object name you might first want to try on a Linux box to be sure that it don't come from Windows and after or before that check the object name that will be exported to see if there is such invalid utf8 characters.

**Comment by lingeshpes** [comment]
Hi, 

Thanks for the reply. The problem was in one of the Oracle function utf 8 character was present. We corrected it. It's solved

Thanks
