### ISSUE TITLE
Question on Estimation

### ISSUE THREAD

**Issue by venkatsusarla** [darold/ora2pg#817]
Hi Darold,
Hope you are doing great!!!

I have a question on estimation, suppose I have many procedures/triggers/packages/functions in which there are many lines with SQL queries, but they are commented, like : "-- select * from dual;".
Question : Does ora2pg also considers the commented line for estimation?

Thanks and Regards,
Venkat

**Comment by darold** [comment]
No, Ora2Pg does not expect you to migrate obsolete code too. Comments are not taken in account for estimation.

**Comment by venkatsusarla** [comment]
Thankyou Darold for the response, you may close the issue.
Regards,
Venkat
