### ISSUE TITLE
ORA Exception 01008 while Retrieving table information

### ISSUE THREAD

**Issue by wizaord** [darold/ora2pg#818]
Hi

I have an issue when I run the ora2pg script on my Oracle database. 
Getting below exception while Retrieving table information... step

> [2019-10-03 11:43:31] Ora2Pg version: 20.0
[2019-10-03 11:43:31] Trying to connect to database: dbi:Oracle:host=m5wdev-bdd.xxxxxxxxxxxxxx;sid=xxxxxxxxxxx;port=1523
[2019-10-03 11:43:31] Isolation level: SET TRANSACTION ISOLATION LEVEL READ COMMITTED
[2019-10-03 11:43:31] Force Oracle to compile schema DATAM5W6 before code extraction
[2019-10-03 11:43:34] Looking forward functions declaration in schema DATAM5W6.
[2019-10-03 11:43:35] Looking at package catalog_platform...
......
[2019-10-03 11:43:35] Looking at package rec_tech...
[2019-10-03 11:43:35] Retrieving table information...
DBD::Oracle::st execute failed: ORA-01008: not all variables bound (DBD ERROR: OCIStmtExecute) [for Statement "SELECT A.TABLE_NAME,A.COMMENTS,A.TABLE_TYPE,A.OWNER FROM ALL_TAB_COMMENTS A, ALL_OBJECTS O WHERE A.OWNER=O.OWNER and A.TABLE_NAME=O.OBJECT_NAME and O.OBJECT_TYPE='TABLE' AND A.OWNER='DATAM5W6'  AND (A.OWNER, A.TABLE_NAME) NOT IN (SELECT OWNER, MVIEW_NAME FROM ALL_MVIEWS UNION ALL SELECT LOG_OWNER, LOG_TABLE FROM ALL_MVIEW_LOGS) AND (A.OWNER, A.TABLE_NAME) NOT IN (SELECT OWNER, TABLE_NAME FROM ALL_OBJECT_TABLES) AND (  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?))" with ParamValues: :p1='^USLOG\$_.*$', :p10='^REPCAT\$.*$', :p100='^SMMONTHLYENTRY_S$', :p101='^SMMONTHWEEKENTRY_S$', :p102='^SMP_USER_DETAILS$', :p103='^SMRELEASE_S$', :p104='^SMRUN_S$', :p105='^SMSCHEDULE_S$', :p106='^SMSHAREDORACLECLIENT_S$', :p107='^SMSHAREDORACLECONFIGURATION_S$', :p108='^SMTABLESPACE_S$', :p109='^SMVCENDPOINT_S$', :p11='^JAVA\$.*$', :p110='^SMWEEKLYENTRY_S$', :p12='^AQ\$.*$', :p13='^BIN\$.*$', :p14='^SDO_GR_.*$', :p15='^.*\$JAVA\$.*$', :p16='^PROF\$.*$', :p17='^TOAD_PLAN_.*$', :p18='^SYS_.*\$$', :p19='^QUEST_SL_.*$', :p2='^MLOG\$_.*$', :p20='^EVT_CARRIER_CONFIGURATION$', :p21='^EVT_DEST_PROFILE$', :p22='^EVT_HISTORY$', :p23='^EVT_INSTANCE$', :p24='^EVT_MAIL_CONFIGURATION$', :p25='^EVT_MONITOR_NODE$', :p26='^EVT_NOTIFY_STATUS$', :p27='^EVT_OPERATORS$', :p28='^EVT_OPERATORS_ADDITIONAL$', :p29='^EVT_OPERATORS_SYSTEMS$', :p3='^RUPD\$_.*$', :p30='^EVT_OUTSTANDING$', :p31='^EVT_PROFILE$', :p32='^EVT_PROFILE_EVENTS$', :p33='^EVT_REGISTRY$', :p34='^EVT_REGISTRY_BACKLOG$', :p35='^OLS_DIR_BUSINESSE$', :p36='^OLS_DIR_BUSINESSES$', :p37='^SDO_COORD_REF_SYS$', :p38='^SDO_CS_SRS$', :p39='^SDO_INDEX_METADATA_TABLE$', :p4='^MDXT_.*$', :p40='^SDO_INDEX_METADATA_TABLES$', :p41='^SDO_PC_BLK_TABLE$', :p42='^SDO_STYLES_TABLE$', :p43='^SDO_TIN_BLK_TABLE$', :p44='^SMACTUALPARAMETER_S$', :p45='^SMGLOBALCONFIGURATION_S$', :p46='^SMFORMALPARAMETER_S$', :p47='^SMFOLDER_S$', :p48='^SMDISTRIBUTIONSET_S$', :p49='^SMDEPENDENTLINKS$', :p5='^MDRT_.*$', :p50='^SMDEPENDENTINDEX$', :p51='^SMDEPENDEEINDEX$', :p52='^SMDEFAUTH_S$', :p53='^SMDBAUTH_S$', :p54='^SMPARALLELJOB_S$', :p55='^SMPACKAGE_S$', :p56='^SMOWNERLINKS$', :p57='^SMOWNERINDEX$', :p58='^SMOWNEEINDEX$', :p59='^SMOSNAMES_X$', :p6='^MDRS_.*$', :p60='^SMOMSTRING_S$', :p61='^SMMOWNERLINKS$', :p62='^SMMOWNERINDEX$', :p63='^SMPACKAGE_S$', :p64='^SMPARALLELJOB_S$', :p65='^SMPARALLELOPERATION_S$', :p66='^SMPARALLELSTATEMENT_S$', :p67='^SMPRODUCT_S$', :p68='^SMP_AD_ADDRESSES_$', :p69='^SMP_AD_DISCOVERED_NODES_$', :p7='^DR\$.*$', :p70='^SMP_AD_NODES_$', :p71='^SMP_AD_PARMS_$', :p72='^SMP_AUTO_DISCOVERY_ITEM_$', :p73='^SMP_AUTO_DISCOVERY_PARMS_$', :p74='^SMP_BLOB_$', :p75='^SMP_CREDENTIALS\$$', :p76='^SMP_JOB_$', :p77='^SMP_JOB_EVENTLIST_$', :p78='^SMP_JOB_HISTORY_$', :p79='^SMP_JOB_INSTANCE_$', :p8='^CLI_SWP\$.*$', :p80='^SMP_JOB_LIBRARY_$', :p81='^SMP_JOB_TASK_INSTANCE_$', :p82='^SMP_LONG_TEXT_$', :p83='^SMP_REP_VERSION$', :p84='^SMP_SERVICES$', :p85='^SMP_SERVICE_GROUP_DEFN_$', :p86='^SMP_SERVICE_GROUP_ITEM_$', :p87='^SMP_SERVICE_ITEM_$', :p88='^SMP_UPDATESERVICES_CALLED_$', :p89='^SMAGENTJOB_S$', :p9='^LOGMNR\$.*$', :p90='^SMARCHIVE_S$', :p91='^SMBREAKABLELINKS$', :p92='^SMCLIQUE$', :p93='^SMCONFIGURATION$', :p94='^SMCONSOLESOSETTING_S$', :p95='^SMDATABASE_S$', :p96='^SMHOSTAUTH_S$', :p97='^SMHOST_S$', :p98='^SMINSTALLATION_S$', :p99='^SMLOGMESSAGE_S$'] at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 11353.
[2019-10-03 11:43:35] FATAL: ORA-01008: not all variables bound (DBD ERROR: OCIStmtExecute)

I have formatted the request : 

> SELECT
    a.table_name,
    a.comments,
    a.table_type,
    a.owner
FROM
    all_tab_comments   a,
    all_objects        o
WHERE
    a.owner = o.owner
    AND a.table_name = o.object_name
    AND o.object_type = 'TABLE'
    AND a.owner = 'DATAM5W6'
    AND ( a.owner, a.table_name ) NOT IN (
        SELECT
            owner,
            mview_name
        FROM
            all_mviews
        UNION ALL
        SELECT
            log_owner,
            log_table
        FROM
            all_mview_logs
    )
    AND ( a.owner,
          a.table_name ) NOT IN (
        SELECT
            owner,
            table_name
        FROM
            all_object_tables
    )
    AND ( NOT REGEXP_LIKE ( upper(a.table_name), '^USLOG\$_.*$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^REPCAT\$.*$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMMONTHLYENTRY_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMMONTHWEEKENTRY_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_USER_DETAILS$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMRELEASE_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMRUN_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMSCHEDULE_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMSHAREDORACLECLIENT_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMSHAREDORACLECONFIGURATION_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMTABLESPACE_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMVCENDPOINT_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^JAVA\$.*$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMWEEKLYENTRY_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^AQ\$.*$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^BIN\$.*$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SDO_GR_.*$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^.*\$JAVA\$.*$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^PROF\$.*$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^TOAD_PLAN_.*$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SYS_.*\$$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^QUEST_SL_.*$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^MLOG\$_.*$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^EVT_CARRIER_CONFIGURATION$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^EVT_DEST_PROFILE$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^EVT_HISTORY$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^EVT_INSTANCE$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^EVT_MAIL_CONFIGURATION$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^EVT_MONITOR_NODE$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^EVT_NOTIFY_STATUS$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^EVT_OPERATORS$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^EVT_OPERATORS_ADDITIONAL$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^EVT_OPERATORS_SYSTEMS$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^RUPD\$_.*$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^EVT_OUTSTANDING$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^EVT_PROFILE$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^EVT_PROFILE_EVENTS$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^EVT_REGISTRY$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^EVT_REGISTRY_BACKLOG$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^OLS_DIR_BUSINESSE$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^OLS_DIR_BUSINESSES$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SDO_COORD_REF_SYS$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SDO_CS_SRS$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SDO_INDEX_METADATA_TABLE$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^MDXT_.*$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SDO_INDEX_METADATA_TABLES$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SDO_PC_BLK_TABLE$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SDO_STYLES_TABLE$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SDO_TIN_BLK_TABLE$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMACTUALPARAMETER_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMGLOBALCONFIGURATION_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMFORMALPARAMETER_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMFOLDER_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMDISTRIBUTIONSET_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMDEPENDENTLINKS$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^MDRT_.*$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMDEPENDENTINDEX$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMDEPENDEEINDEX$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMDEFAUTH_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMDBAUTH_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMPARALLELJOB_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMPACKAGE_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMOWNERLINKS$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMOWNERINDEX$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMOWNEEINDEX$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMOSNAMES_X$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^MDRS_.*$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMOMSTRING_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMMOWNERLINKS$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMMOWNERINDEX$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMPACKAGE_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMPARALLELJOB_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMPARALLELOPERATION_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMPARALLELSTATEMENT_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMPRODUCT_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_AD_ADDRESSES_$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_AD_DISCOVERED_NODES_$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^DR\$.*$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_AD_NODES_$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_AD_PARMS_$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_AUTO_DISCOVERY_ITEM_$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_AUTO_DISCOVERY_PARMS_$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_BLOB_$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_CREDENTIALS\$$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_JOB_$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_JOB_EVENTLIST_$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_JOB_HISTORY_$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_JOB_INSTANCE_$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^CLI_SWP\$.*$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_JOB_LIBRARY_$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_JOB_TASK_INSTANCE_$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_LONG_TEXT_$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_REP_VERSION$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_SERVICES$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_SERVICE_GROUP_DEFN_$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_SERVICE_GROUP_ITEM_$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_SERVICE_ITEM_$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMP_UPDATESERVICES_CALLED_$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMAGENTJOB_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^LOGMNR\$.*$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMARCHIVE_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMBREAKABLELINKS$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMCLIQUE$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMCONFIGURATION$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMCONSOLESOSETTING_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMDATABASE_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMHOSTAUTH_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMHOST_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMINSTALLATION_S$' )
                AND NOT REGEXP_LIKE ( upper(a.table_name), '^SMLOGMESSAGE_S$' )
);

The request has a correct syntax. I executed it with sqlplus and there is no issue.

Do you have an idea ? 

Regards
Cédric

**Comment by darold** [comment]
Probably one of these mysterious Oracle behavior, I don't think the explanation comes from Perl DBD::Oracle or Ora2Pg. I have never had this issue and I don't think it has been ever reported in Ora2Pg github issues. If you have an other Oracle DB on an other server you can try to see if the problem can be reproduced elsewhere.

**Comment by wizaord** [comment]
You're right.
I tried with another oracle database and it's work properly. I hate Oracle ^^

Thanks for all.
