### ISSUE TITLE
/N in postgres NULL in Oracle

### ISSUE THREAD

**Issue by sicot** [darold/ora2pg#819]
How can we avoid the /N generated with ora2pg ?

Do we need to edit the data.sql script generated by ora2pg -t COPY -o data.sql and transform /N by null ?

Regards 

Pierre

**Comment by darold** [comment]
I guess you want to talk about the `\N` not `/N`, these are NULL in COPY mode removing them will just insert an empty string instead which may not be what you want.

**Comment by sicot** [comment]
Hello,

I have some problems about \N

I have a created a table named body content and the ora2pg -t copy has generated a data_BODYCONTENT.sql script.

When I run the data_BODYCONTENT.sql script with sql , it runs correctly until the line 9786 and this line corresponds to:

41070 \N 40878 2

and the error message is ERROR 22P04 missing data for column contented which is the second column of the table

Perhaps it is not possible to load data form psql and I have to import with import_all.sh ...

Regards




Pierre SICOT
Senior Consultant

OEM 12c Certified Implementation Specialist


Mobile +41 79 961 29 61
pierre.sicot@dbi-services.com<mailto:pierre.sicot@dbi-services.com>

www.dbi-services.com<http://www.dbi-services.com/>

________________________________

**Comment by sicot** [comment]
Hello,

OK no problem it works fine with import_all.sh

Regards


Pierre SICOT
Senior Consultant

OEM 12c Certified Implementation Specialist


Mobile +41 79 961 29 61
pierre.sicot@dbi-services.com<mailto:pierre.sicot@dbi-services.com>

www.dbi-services.com<http://www.dbi-services.com/>

________________________________

**Comment by darold** [comment]
You can use `psql yourdbname -f data_BODYCONTENT.sql` to import your data.
