### ISSUE TITLE
characters conversion

### ISSUE THREAD

**Issue by sicot** [darold/ora2pg#820]
My source database has NLS_LANG = amaêrican_america.al32utf8, my target Postgres database is UTF8 , when I run ora2pg on Oracle tables , the character imported in postgres are modified ..

oracle: Prêts Intérêts 

postgres: PrÂts IntÂ©Âts

What did I miss ? 
Is is a possible environment problem ?

Regards 
Pierre

**Comment by darold** [comment]
What is the value of NLS_LANG and NLS_NCHAR in your ora2pg.conf? What does `env | grep NLS_LANG` reports?

**Comment by sicot** [comment]
Hello,

The NLS_LANG and NLS_NCHAR are in comment in ora2pg.conf, i.e default values american_america.AL32UTF8 and AL32UTF8

env | grep NLS_LANG reports nothing

Regards


Pierre SICOT
Senior Consultant

OEM 12c Certified Implementation Specialist


Mobile +41 79 961 29 61
pierre.sicot@dbi-services.com<mailto:pierre.sicot@dbi-services.com>

www.dbi-services.com<http://www.dbi-services.com/>

________________________________

**Comment by darold** [comment]
Well I don't know what is transforming the UTF8 requested output into what I think is ISO 8859-1 or similar encoding but it happen. What you might want to do to fix this issue is first try to set NLS_LANG in ora2pg.conf to `american_america.AL32UTF8` to see if this force Oracle to send output in UTF8. If it don't works, still in ora2pg.conf, you can try to set NLS_LANG to `FRENCH_FRANCE.WE8ISO8859P1` and CLIENT_ENCODING to `latin1`. That should fix the issue.

**Comment by sicot** [comment]
Hello,


The first test forcing NLS_LANG to American_america.AL32UTF8  is not good. I will try with we8iso8859p1 and keep you informed.

Thanks



Pierre SICOT
Senior Consultant

OEM 12c Certified Implementation Specialist


Mobile +41 79 961 29 61
pierre.sicot@dbi-services.com<mailto:pierre.sicot@dbi-services.com>

www.dbi-services.com<http://www.dbi-services.com/>

________________________________

**Comment by sicot** [comment]
Hello,

I made the following tests:

with NLS_LANG=american_america.we8iso8859p1 and NLS_NCHAR=WE8ISO8859p1 and CLIENT_ENCODING LATIN1 int ora2pg.conf.draft

I run

ora2pg -t COPY -o data_DRAFT.sql -b ./data -c /etc/ora2pg/ora2pg-conf.draft

The data_DRAFT.sql  has the characters in bad state :=(((

and this is the same behaviour with AL32UTF8 ...

Regards


Pierre SICOT
Senior Consultant

OEM 12c Certified Implementation Specialist


Mobile +41 79 961 29 61
pierre.sicot@dbi-services.com<mailto:pierre.sicot@dbi-services.com>

www.dbi-services.com<http://www.dbi-services.com/>

________________________________

**Comment by darold** [comment]
Well the only solution I see is to export without NLS_LANG set and use `iconv` to convert the output.

**Comment by sicot** [comment]
Hello,

Finally the problem was stupid .... working with putty and modify Settings --> Window --> Translation from ISO8859-1 to UTF-8 and the characters are fine :=))

Regards 
Pierre
