### ISSUE TITLE
i've question of this program

### ISSUE THREAD

**Issue by CHO-Hoon-Yeon** [darold/ora2pg#821]
hi there, i have a little question for this program.

i have 2 systems.
Oracle DB is on  Windows .
and Postgresql is on Centos , also not same places. 
so my question is can i move my Oracle DB data to Postgresql at other machine?
of course they are linked and using different IP addresses.
if this can work, how can i fix my configure file?? i mean there is no ip addresses blank is in there.
how can i link these two Databases ??

**Comment by darold** [comment]
You can migrate your data from Oracle Window to PostgreSQL Centos without problem, you just have to set PG_DSN, PG_USR and PG_PWD in ora2pg.conf to set the connection to PostgreSQL.

About the connection closed unexpectedly you might look at PostgreSQL log, perhaps this si a pg_hba.conf authorization issue? That could also explain too why you can't connect with pgadmin.

**Comment by CHO-Hoon-Yeon** [comment]
THX!!
