### ISSUE TITLE
Migrating MySQL to postgres

### ISSUE THREAD

**Issue by RobinReborn** [darold/ora2pg#822]
I am trying to convert a MySQL data dump to a postgres database.

The command:

`ora2pg -d -u root -w password`

Generates a file but when I run:

`sudo -u postgres psql database < output.sql`

I get format errors

`ERROR:  syntax error at or near "smallint"
LINE 5:  primary smallint NOT NULL,`

So it's not in the right format yet I don't see a place to specify postgres format.

**Comment by darold** [comment]
You should add `-m -p` to your ora2pg command, do you have the same error?

**Comment by RobinReborn** [comment]
I do.

**Comment by darold** [comment]
The problem was related to the name of the column using a reserved keyword in PG. This is fixed.
