### ISSUE TITLE
bytea value output needs a double backslash

### ISSUE THREAD

**Issue by frost242** [darold/ora2pg#824]
Hi,

While migrating some binary data by exporting data to files, ora2pg outputs the following for bytea data :
```
COPY sometable (somebinary) FROM STDIN;
\xDEADBEEF
\.
```
The backslash on `\x` needs to be doubled as `\\xDEADBEEF`

PR will follow soon.

Regards

**Comment by darold** [comment]
Fixed in commit 805f6da, Thomas please next time send a PR the problem would have been fixed in time!
