### ISSUE TITLE
Have a question for data type.

### ISSUE THREAD

**Issue by CHO-Hoon-Yeon** [darold/ora2pg#825]
Hi there, i have a question about data type.
i made some oracle tables belonging data type Number(15,0)
after i started ora2pg.bat,  then that data type Number changed all to BIG INT
so i changed some config file, but it's not completed. 
can anyone help me about don't using biginteger type?? 
and my config is 
thanks.
```
#------------------------------------------------------------------------------
# TYPE SECTION (Control type behaviors and redefinitions)
#------------------------------------------------------------------------------
DATA_TYPE	NUMBER(*\,0):numeric
#DATA_TYPE	DATE:timestamp,LONG:text,LONG RAW:bytea,CLOB:text,NCLOB:text,BLOB:bytea,BFILE:bytea,RAW:bytea,UROWID:oid,ROWID:oid,FLOAT:double precision,DEC:decimal,DECIMAL:decimal,DOUBLE PRECISION:double precision,INT:numeric,INTEGER:numeric,REAL:real,SMALLINT:smallint,BINARY_FLOAT:double precision,BINARY_DOUBLE:double precision,TIMESTAMP:timestamp,XMLTYPE:xml,BINARY_INTEGER:integer,PLS_INTEGER:integer,TIMESTAMP WITH TIME ZONE:timestamp with time zone,TIMESTAMP WITH LOCAL TIME ZONE:timestamp with time zone
PG_NUMERIC_TYPE	1
PG_INTEGER_TYPE	1

DEFAULT_NUMERIC bigint

ENABLE_MICROSECOND      1
```

**Comment by CHO-Hoon-Yeon** [comment]
and also , i have one more question. 
can i make some function?? i mean can i set some cases, like seperate table and migrate just part of them.

**Comment by CHO-Hoon-Yeon** [comment]
my replaced query is
RELPACE_QUERY tablename[SELECT * FROM tablename where tablename[business_cd>100]]

**Comment by darold** [comment]
For the first question do not touch the DATA_TYPE directive, this behavior is controlled by:
```
# If set to 1 replace portable numeric type into PostgreSQL internal type.
# Oracle data type NUMBER(p) or NUMBER are converted to smallint, integer
# or bigint PostgreSQL data type following the length of the precision. If
# NUMBER without precision are set to DEFAULT_NUMERIC (see bellow).
PG_INTEGER_TYPE 1
```
that mean that you just have to disable PG_INTEGER_TYPE:
```
PG_INTEGER_TYPE 0
```

**Comment by darold** [comment]
If you want to export only a part of some tables following a WHERE clause, use directive `WHERE`. If you need to filter exported data with a more complex query using join for example use `REPLACE_QUERY`

**Comment by CHO-Hoon-Yeon** [comment]
Thanks. so i changed my data type. 
and can i use replace query like this?

RELPACE_QUERY tablename[SELECT * FROM tablename where tablename[business_cd>100]]

**Comment by CHO-Hoon-Yeon** [comment]
i just wanna migrate my table seperate them on a bunch. like PK 1-100, 101-200.

**Comment by darold** [comment]
Just use the following might do the job
```
WHERE    u_t_in_out_stock_info[to_number(business_cd)<100]
```

**Comment by CHO-Hoon-Yeon** [comment]
you mean paste that to #where row  sentence??
or paste that to REPLACE_QUERY??

**Comment by CHO-Hoon-Yeon** [comment]
ahh so i can use this code on maybe CMD

**Comment by CHO-Hoon-Yeon** [comment]
i appreciate your comment Darold. but actually still migrates all table's data haha..
