### ISSUE TITLE
ora2pg - big simplication partitioned constraints and indexes from PG11

### ISSUE THREAD

**Issue by jacks33** [darold/ora2pg#826]
Hello,

now that ora2pg directly handles postgres version in ora2pg.conf file:

please 
for partitionned tables : create constrains (PK, ...) and indexes directly on root table, rather than creating them for each partition on file (PARTITION_INDEXES_partition.sql)

It is only possible from postgreSQL 11 

Thank you very much

**Comment by darold** [comment]
Will do when I will find time to work on Ora2Pg. Sorry for the delay.

**Comment by jacks33** [comment]
So sorry I was using version 19.1 , version 20 is ok: when you migrate to PG11 this file is no longer created and partition.sql file is ok.
You can close the ticket.
