### ISSUE TITLE
ORA-01459 error

### ISSUE THREAD

**Issue by markhooper99** [darold/ora2pg#827]
Trying to perform an ora2pg on an Oracle (11.2) table that has a BLOB in it (largest of which is around 150MB).  I'm getting this error ...

`[2019-10-27 18:46:01] FATAL: ORA-01459: invalid length for variable character string (DBD ERROR: error possibly near <*> indicator at char 405 in 'SELECT "FILE_ID","ACTIVE_IND","DIGITAL_FORMAT","EFFECTIVE_DATE","EXPIRY_DATE","FILE_CONTENT","FILE_SIZE","FILE_SIZE_UOM","INFORMATION_ITEM_ID","INFO_ITEM_TYPE","PHYSICAL_ITEM_ID","PPDM_GUID","REMARK","SOURCE","SW_APPLICATION_ID","ROW_CHANGED_BY","ROW_CHANGED_DATE","ROW_CREATED_BY","ROW_CREATED_DATE","ROW_QUALITY","K_OWNER_BA","K_FILE_TYPE","K_ROW_CREATED_PROCESS","K_ROW_CHANGED_PROCESS" FROM "DMASS38".<*>"RM_FILE_CONTENT" a WHERE (K_OWNER_BA IN ('50306','0') )')
`

Where is the<*> coming from? (i.e inserted between DMASS38 and RM_FILE_CONTENT)

snippet from my config file ...

`SCHEMA  DMASS38`
`ALLOW    RM_FILE_CONTENT`

any thoughts ?

**Comment by markhooper99** [comment]
Oddly enough, increasing the LONGREADLEN value resolved this problem - not sure why, though ;-\
Original value for LONGREADLEN... 3300000000
New value for LONGREADLEN... 10000000000

**Comment by SebAlbert** [comment]
The <*> is not part of the query, it was inserted by the Oracle server to show you where it thinks the problem is in the query.
