### ISSUE TITLE
Give me some advice please 

### ISSUE THREAD

**Issue by CHO-Hoon-Yeon** [darold/ora2pg#828]
My question is i wanna separate database and migrate them on 3 times. like 
1st cycle is migrating 1-100, 2nd cycle is migrating 101-200, last cycle is migrating 201-300.
So i thought 3 different ways. but after i start ora2pg and these 3 ways migrate data all.
i think maybe my ora2pg grammar is wrong.

1st one is using WHERE Clause.
WHERE	TABLE_tablename[to_number('column_name')<'100']

2nd one is using row_number
REPLACE_QUERY table_name[SELECT * FROM (select rownum, rnum, num from board order by num desc) where rnum between 1 and 100

last one is using partitioning. after i saw ora2pg's issues, 
partitioning is referred in issues but actually, i don't know well about partitioning section on ora2pg. 
can anybody give me some advice?
p.s Thanks Darold , but i still can't find the answer to my problem

**Comment by SebAlbert** [comment]
I think you are writing very strange things in your configuration.

> WHERE TABLE_tablename[to_number('column_name')<'100']

From what I understand, this is basically what you want, but why are you writing those quotation marks? Also, do you really need to_number as a function? I would rather write it like so:

`WHERE table_name[column_name < 100]`

Note that this is not `WHERE TABLE_`, just `WHERE`. And of course you have to replace `table_name` and `column_name` with the actual names of your table and the column, respectively.

> REPLACE_QUERY table_name[SELECT * FROM (select rownum, rnum, num from board order by num desc) where rnum between 1 and 100

This one looks odd as well. There is at least a missing `]` in the end.

**Comment by CHO-Hoon-Yeon** [comment]
Thanks for your answering SebAlbert. and 
yeah, i need to use To_number . actually, my table's  define is still using varchar2.
and yeah, i used WHERE table_name[cloumn_name < 100] and it is still migrating all data. 
oh and sorry for my miss typing.

**Comment by SebAlbert** [comment]
Please try to write something wrong in your configuration, like this:
`WHERE table_name[hi there this is nonsese]`
or even
`WHERE hi there this is nonsense`
and see if you get an error. If you don't, then ora2pg is not using your configuration file the way you want it to, and you would need to investigate that instead.
If only the second thing produces an error and the first doesn't, then your `table_name` is probably misspelled.

**Comment by CHO-Hoon-Yeon** [comment]
okay. thanks for your mentioning.
and i tried both.
1st one is showing error 14581 error.
2nd one is showing good. 
really thanks Seb. you saved my ass!

**Comment by SebAlbert** [comment]
I was asking because `WHERE table_name[to_number('column_name') < '100']` with the single quotes should also have produced an error rather than exporting the entire table.

So if you get the error and you need to_number, then it's probably correct to do
`WHERE table_name[to_number(column_name) < 100]`
without single quotes.

**Comment by CHO-Hoon-Yeon** [comment]
oh, i see. you really saved my ass. thanks SEB ALBERT.
thanks. !
