### ISSUE TITLE
Problem moving byte data Oracle to PostgreSql

### ISSUE THREAD

**Issue by joemacrep** [darold/ora2pg#830]
I am having trouble moving byte data (MARC21 data)  in a VARCHAR2(990) column in an Oracle table to a bytea column in a postgreSQL table. Whenever a byte with the most significant bit equal 1 is encountered a pair of 0xFD extra bytes are inserted. I am using the MODIFY_TYPE configuration method BIB_DATA_II:RECORD_SEGMENT:bytea

Is there another way to do this mapping. I also tried 'DATA_TYPE'

**Comment by joemacrep** [comment]
Instead of 'a pair of 0xFD extra bytes' it should read 'a 0xFD byte is inserted instead'

**Comment by darold** [comment]
Hi,

Well if your byte data was in a CLOB the problem would not occurs because Ora2Pg will know that the output need to be escaped into bytea. I think that an easy solution shall be a patch to force data escaping when the destination data type is bytea and source data type a varchar2.

**Comment by joemacrep** [comment]
Unfortunately I have no control over the type VARCHAR2(990) for the record_segment column. How are patches created?

**Comment by darold** [comment]
If you are not comfortable with git it is common to send the diff -u of the files modified, otherwise fork+pull request.

**Comment by darold** [comment]
On Oracle side:
```
CREATE TABLE DOCUMENT (ID NUMBER, DATA CLOB);
INSERT INTO DOCUMENT VALUES (1, 'This is a content');
```
Data export without data type transformation, CLOB is exported as `text`:
```
COPY document (id,texte) FROM STDIN;
1       This is a content
\.
```

Export with `MODIFY_TYPE     DOCUMENT:DATA:BYTEA` in ora2pg.conf
```
COPY document (id,texte) FROM STDIN;
1       \\x68656c6c6f2074686973206973206120636f6e74656e74
\.
```

I'm closing this issue at it is working as expected.
