### ISSUE TITLE
I've Question for replace_query 

### ISSUE THREAD

**Issue by CHO-Hoon-Yeon** [darold/ora2pg#831]
Sorry, im back again..
anyway i have some question about replace_query clause.
when i migrate varchar2 attribute on Oracle side to date attribute on Postgres,
there is some error  found. date formal is not correct and DBI::DB=HASH(0x435d7f0)
hmm so i'm wondering, can i use to_date function just on one column. 
cuz my table is including 66 columns, and i'm just trying if postgre side changes date type, how can i migrate all of data.
thank you about you guys.

**Comment by CHO-Hoon-Yeon** [comment]
Or can i use MODIFY_TYPE on Configure??

**Comment by darold** [comment]
Hi,

MODIFY_TYPE will not help. Only REPLACE_QUERY can be used to redefine the query but you have to redefined the entire query and with 66 columns I understand that this is a pain. It could be a great improvement to have a new configuration directive, for example REPLACE_COLUMN, that could be used to redefined data extraction only for some columns.

**Comment by CHO-Hoon-Yeon** [comment]
Yeah. i'm on your side about that problem.. 
if i  redefine all columns, and insert almost 10 Million data, am i must redefine 10M datas for insert to Postgre side?

**Comment by darold** [comment]
You use the right date format you should not have to modify again your data before inserting into PostgreSQL: `TO_DATE(COLN , 'YYYY-MM-DD HH24:MI:SS') `

**Comment by CHO-Hoon-Yeon** [comment]
hmm..
so if i use Replace query clause, on my table 
REPLACE_QUERY using insert clause, how to build a query. 
i mean, using insert query values must be set. so am i must set values almost 10Million of them??

**Comment by darold** [comment]
No the REPLACE_QUERY directive is use to redefined the query used to extract data from the Oracle table. As a result you will have the COPY or INSERT statement to import the data into PostgreSQL. Just like if you do not have used this directive, the only thing is that the output will follow the column name and order you have set in the query.

**Comment by CHO-Hoon-Yeon** [comment]
Ah. so you mean, if i use REPLACE_QUERY for my migration, i only set query for my table and don't need to set insert values query. right?

**Comment by CHO-Hoon-Yeon** [comment]
What if using UPDATE clause, on my REPLACE_QUERY clause am i must set all data's date like 
REPLACE_QUERY table_name[UPDATE table_name SET innerdate=TO_DATE( '2009/06/01 11:00:00', 'YYYY/MM/DD HH:M
I:SS'  )]
for all of data? or just using update all clause
sorry, i'm actually just newbie on Database. not that kind of expert of this field.

**Comment by darold** [comment]
As I've said REPLACE_QUERY is used to retrieve data from Oracle, using an INSERT or UPDATE statements will execute the statement in Oracle database, I'm sure this is what you want.

**Comment by CHO-Hoon-Yeon** [comment]
Thanks for your referring. I think yeah, maybe using some sub Query for changing my query.
And I think this is perfect tool to use. 
I hope I didn't make you annoying.
thanks for your answering.
