### ISSUE TITLE
Could not export function definition

### ISSUE THREAD

**Issue by nguyenxuanluong-luvina** [darold/ora2pg#832]
Hi, 
I'm using ora2pg with following setting to export function
```
SCHEMA          MySchema
ORACLE_HOME D:\oracle\ora12
ORACLE_DSN	dbi:Oracle:host=localhost;sid=myDB;port=1521
ORACLE_USER	system
ORACLE_PWD	MyPassword
TYPE		FUNCTION
```

Have no setting for ALLOW or EXCLUDE objects

And running with command : **ora2pg -d**

Following are debug log : 

```
2019-11-04 11:57:04] Looking at package a...
[2019-11-04 11:57:04] Looking at package b...
[2019-11-04 11:57:04] Looking at package c...
[2019-11-04 11:57:04] Retrieving procedures information...
[2019-11-04 11:57:04] Add procedures definition...
[2019-11-04 11:57:04] Total time to translate all functions with 1 process:  0 wallclock secs ( 0.00 usr +  0.00 sys =  0.00 CPU)

```
And i have no function in output.sql 

```
-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;sid=myDB;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

-- Nothing found of type PROCEDURE 

```
Someone could tell me what's wrong with my setting?
I could export data successfully but not work with FUNCTION

**Comment by nguyenxuanluong-luvina** [comment]
I could export functions
Problem just my oracle package body  is wrapped. I should unwrap before doing ora2pg

**Comment by darold** [comment]
Hi,

Action type FUNCTION will export functions only as well as PROCEDURE will export only procedure object. To export package you have to use PACKAGE action in ora2pg.conf:
```
TYPE    PACKAGE
```
or use ` -t PACKAGE` at ora2pg command line.

Regards,
