### ISSUE TITLE
Little Question

### ISSUE THREAD

**Issue by CHO-Hoon-Yeon** [darold/ora2pg#833]
Little Question. just for my curiosity.
If Ora2pg is just on PostgreSql side, can ora2pg run absolutely??
For Example, A site is running Oracle side. and B site is Postgre side which i wanna migrate. these two DB server are on different city. if i don't have authority to Oracle side, can i install ora2pg on Postgre side and do migration? Of course, i'll  get install all DBD and DBI on Postgre side.

**Comment by darold** [comment]
Yes this is the usual way I'm working. The ORACLE_DSN configuration directive in ora2pg.conf allow to specify the ip address and port of the Oracle server. Of course you need network authorization to connect to the Oracle server on this port. You also have to install Oracle Client on the PostgreSQL server following the Ora2Pg documentation.

**Comment by CHO-Hoon-Yeon** [comment]
So You mean, if i install Oracle Client on Postgresql server, i can approach to other side and make migration. right?? of course set some DSN things

**Comment by darold** [comment]
Exactly, DBD::Oracle require the Oracle Client b.e installed

**Comment by CHO-Hoon-Yeon** [comment]
Copy that sir. thanks for your comment.

**Comment by CHO-Hoon-Yeon** [comment]
Just One more question.
If i install DBD::Oracle on my Postgre server side, am i must install Oracle Database? 
actually, when i install ora2pg and DBD Oracle on my Postgre side, DBD Oracle is vomiting error now. 
if this question is not about ora2pg, really sorry . I'm just newbie on this field

**Comment by darold** [comment]
You  should post the error reported by DBD::Oracle, most of the time this is because you have not set the ORACLE_HOME and PATH correctly with the InstantClient path. You definitively don't need to install an Oracle database on the Ora2Pg machine, instantclient is enoough.

**Comment by CHO-Hoon-Yeon** [comment]
perl Makefile.PL
Using DBI 1.627 (for perl 5.016003 on x86_64-linux-thread-multi) installed in /usr/lib64/perl5/vendor_perl/auto/DBI/
Configuring DBD::Oracle for perl 5.016003 on linux (x86_64-linux-thread-multi)

If you encounter any problem, a collection of troubleshooting
guides are available under lib/DBD/Oracle/Troubleshooting.
'DBD::Oracle::Troubleshooting' is the general troubleshooting
guide, while platform-specific troubleshooting hints
live in their labelled sub-document (e.g., Win32
hints are gathered in 'lib/DBD/Oracle/Troubleshooting/Win32.pod').

Trying to find an ORACLE_HOME
Your LD_LIBRARY_PATH env var is set to ''
Use of uninitialized value $loh in substitution (s///) at Makefile.PL line 982.
Use of uninitialized value $oh[0] in join or string at Makefile.PL line 985.
Found 

      The ORACLE_HOME environment variable is not set and I couldn't guess it.
      It must be set to hold the path to an Oracle installation directory
      on this machine (or a machine with a compatible architecture).
      See the appropriate troubleshooting guide for your OS for more information.
      ABORTED!
  
this is my error code..

**Comment by darold** [comment]
Well the message is explicit, I think that chapter "Installing DBD::Oracle" of Ora2Pg documentation could help you for this installation.
