### ISSUE TITLE
Question for installing on CentOs7

### ISSUE THREAD

**Issue by CHO-Hoon-Yeon** [darold/ora2pg#834]
After i installing DBD, DBI, Ora2pg on my linux vm, and i tried to start ora2pg on command code ./ora2pg
After that, i've got error code, 
install_driver(Oracle) failed: Can't load '/usr/local/lib64/perl5/auto/DBD/Oracl                                     e/Oracle.so' for module DBD::Oracle: libclntsh.so.11.1: cannot open shared objec                                     t file: No such file or directory at /usr/lib64/perl5/DynaLoader.pm line 190.
 at (eval 13) line 3.
Compilation failed in require at (eval 13) line 3.
Perhaps a required shared library or dll isn't installed where expected
 at /usr/local/share/perl5/Ora2Pg.pm

so i tried to find method to solve this problem, but i can't find way.
i installed oracle instantclient for my work, and i've also checked my bash_profile.
but i'm still in error swamp. can any guy make me out of this error swamp?
p.s i've installed DBD oracle on downloading at CPAN and moved to my vm on tcp lines.

**Comment by CHO-Hoon-Yeon** [comment]
My bash_profile set is
export ORACLE_HOME="/usr/lib/oracle/11.2client64"
export TNS_ADMIN=/usr/lib/oracle/11.2/client64.bin
CFLAGS=/usr/lib/oracle/11.2/client64
LD_LIBRARY_PATH=$ORACLE_HOME/lib:$LD_LIBRARY_PATH
#NLS_LANG=KOREAN_KOREA.KO16MSWIN949
PATH=$ORACLE_HOME/bin:$PATH
#export TNS_ADMIN_LD_LIBRARY_PATH PATH CFLAGS NLS_LANG ORACLE_HOME
export LD_LIBRARY_PATH="$ORACLE_HOME/lib"
export PERL5LIB=/usr/lib/perl5
#export PATH
#SQL_PLUS=/root/Downloads/instantclient_11_2/;
#export SQL_PLUS
#PATH=$SQL_PLUS:$PATH;

**Comment by SebAlbert** [comment]
It looks like you have a missing forward slash in your ORACLE_HOME. Also, but that should not be the problem here, in your TNS_ADMIN it looks like you have a dot where you would probably want a slash.

**Comment by CHO-Hoon-Yeon** [comment]
aa... sorry, that code is wrong one. cuz copy paste on command made miss. sorry
 i've changed to 
ORACLE_HOME=/usr/lib/oracle/11.2/client64
TNS_ADMIN=/usr/lib/oracle/11.2/client64/bin
but still on error. so i've used echo clause ,and just blank rises on now.

**Comment by CHO-Hoon-Yeon** [comment]
oh and also i'm pretending use oracle instant client 11.2
is this work well on ora2pg?

**Comment by darold** [comment]
Before running ora2pg you need to set your LD_LIBRARY_PATH:
```
export LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client64
```

TNS_ADMIN don't have to be set, but you have to set the PATH for the user running ora2pg:
```
export PATH="/usr/lib/oracle/11.2/client64/bin:$PATH"
```

**Comment by SebAlbert** [comment]
> so i've used echo clause ,and just blank rises on now.

Are you saying that `echo $ORACLE_HOME` yields an empty line?
Please note that changes to .bash_profile and similar files do not become effective automatically for sessions that are already open. This means that for changes to take effect, you need to either start a new shell or source the file, for example via entering `. ~/.bash_profile` or `source ~/.bash_profile`.

Note also that you can experiment with the variables first via entering `export ORACLE_HOME=.......` in your interactive shell before running `ora2pg`, which may be easier than changing and sourcing the profile file every time you try something different. When you have found out what works you can then still make it permanent via the .bash_profile file for the correct user.

**Comment by CHO-Hoon-Yeon** [comment]
@darold okay, Darold. i've set my LD_PATH right . and now hmm i re installed DBD, DBI
and now i've got new error
DBI connect('host=172.16.7.68;sid=orcl;port=1521','test',...) failed: ORA-12541: TNS:no listener (DBD ERROR: OCIServerAttach) at /usr/local/share/perl5/Ora2Pg.pm line 1619.
FATAL: 12541 ... ORA-12541: TNS:no listener (DBD ERROR: OCIServerAttach)

**Comment by CHO-Hoon-Yeon** [comment]
@SebAlbert and now echo is answering well on my command. thanks @darold @SebAlbert

**Comment by CHO-Hoon-Yeon** [comment]
I think this problem is about Oracle Listener. but hmm i've installed oracle 11.2 instant client. so i can't find way to set Oracle Listener profile. haha

**Comment by CHO-Hoon-Yeon** [comment]
anyway i've done thanks
