### ISSUE TITLE
Have some Question for speed.

### ISSUE THREAD

**Issue by CHO-Hoon-Yeon** [darold/ora2pg#835]
Speed Question. not a Speeding up , but just a speed question.
I migrated 2 tables. 
'A' Table's Row is almost 65000. and column is almost 30.
'B' Table's Row is almost 11Million. and column is almost 66.
When i Operated this Ora2pg, migrating A table took almost 30sec.
After i migrated B table, Took almost 5days. 
Compare these two jobs, What is the reason that migrating B table took that too much time?

**Comment by CHO-Hoon-Yeon** [comment]
Of course if there is a way to speeding up, that'll be helpful, but actually i've read all posts on this Ora2pg .

**Comment by darold** [comment]
I guess that there is some LOB column, their values need to be escaped to be transformed as bytea and this is slow. To improve data export you must use multiprocess, for example ` -J 4` if you have at least 4 cores.

**Comment by CHO-Hoon-Yeon** [comment]
Yeah. in My column, there is maybe too many CLOB is on there. 
-J 4 , Can you do me a favor to showing some examples of your command??
ora2pg -c ora2pg.conf -o -J 4  <--- is this right command?

**Comment by SebAlbert** [comment]
> ora2pg -c ora2pg.conf -o -J 4 <--- is this right command?

`-o` should be followed by a filename.

> And Curious about One thing. If i use little complicated Where clause on Ora2pg, Like using Concat , To_date clause and Slicing Character clause, is this can make my migration speed more slower?

If the Oracle server is slow or at least the bottleneck (and especially if the tables are large), then yes, since most likely Oracle cannot use an index on such conditions and has to compute this for every row in the table (before it can decide whether they match your criteria).

**Comment by CHO-Hoon-Yeon** [comment]
I See. Maybe My table has too many CLOB or BLOB on that. 
Thanks For helping me. I really appreciate that. and i hope, this can be the most powerful migration tool.

**Comment by CHO-Hoon-Yeon** [comment]
Last Question... the speed of migration problem. 
I've used J option on Linux, but still, my migration takes too much time. almost 80hours for 11Million rows. and also Average Speed is almost 38recs/sec. 
Is this can happen?
