### ISSUE TITLE
ora2pg is just dying on one table

### ISSUE THREAD

**Issue by jbscalia** [darold/ora2pg#839]
I'm in the process of migrating three Oracle databases into a single PostgreSQL instance, and I've gotten everything ported except for one table. The table from Oracle contains one attribute that is a BLOB datatype, and I've tried various settings for LONGREADLEN. The only thing that works is if I set LONGREADLEN to no more than 79613952 and set LONGTRUNKOK 1. This is an imperfect setting as a truncated image is simply a broken one, but any other value larger than 76 MB simply either gets killed by the Linux OOM daemon, or fails producing an out of memory error.  Oh, and I'm setting DATA_LIMIT to 1 as well as just having ora2pg output a SQL file for the import. It's not actually trying to write into the PostgreSQL instance. The main problem with my current settings is simply that ora2pg is just dying. No error messages or warnings, just nothing but a return to the shell prompt, and the output suggests that it's only processing 301 rows from the Oracle table. That table, however, contains more than 16K records. Anyone have any suggestions as to what might be wrong here? My suspicion is one of a memory leak somewhere, but I can't imagine that I'm the first one to uncover it. After all, this particular table really isn't that large.

**Comment by darold** [comment]
Yes enabling LONGTRUNKOK is only useful for test unless you can live with truncated data :-)

If you want to export this table without OOM, use the following settings:
```
LONGREADLEN    1047552
LONGTRUNCOK    0
NO_LOB_LOCATOR  0
```
See configuration file for more explanation.

**Comment by jbscalia** [comment]
But really i need the data in the blob column.  Any idea how I can get this accomplished.

**Comment by darold** [comment]
Yes, look at my note above.

**Comment by jbscalia** [comment]
Your settings almost worked, at least ora2pg did not die without a warning, however, I only managed to get 202 records out of 16K+ records from the Oracle table. Ora2pg processed these as 2 blocks of 101 records which is nowhere near what the table contains.

**Comment by darold** [comment]
Does OOM killer still interrupt ora2pg? dmesg should show the OOM killer activity. How many RAM do you have?

**Comment by jbscalia** [comment]
Usually if the OOM killer stops this, I get an on-screen message indicating the process was killed, but in this case, I didn't receive the message, but I am seeing it was killed in dmesg. This particular system only has something like 3.5 GB of RAM. Let em try this again on one of my larger EC2 instances.

**Comment by jbscalia** [comment]
Your settings worked nearly perfectly. Thank you for that. It was still a bit of a problem getting all the data out of Oracle, due to my network connection dying. So, I came into the office and it ran fine there. All 16658 records with their blob data are now installed in the new postgresql instance. Thanks again.
