### ISSUE TITLE
Question. how to delete Ora2pg printing other relations?

### ISSUE THREAD

**Issue by CHO-Hoon-Yeon** [darold/ora2pg#840]
how can i delete ora2pg is printing on CMD?
like 
notice: relation"departments_seq" is not appear...
notice: relation"orders_seq"is not apper
notice: relation"employees_seq" is not appear...
notice: relation"location_seq"is not apper
can i clean this on fixing my ora2pg.CONF file?

**Comment by darold** [comment]
I'm not sure to understand the question but if you want to disable most of messages printed by Ora2Pg and the progress bar you can use `-q`.

About messages: `notice: relation "orders_seq" is not appear` I think they are not generated by Ora2Pg directly. What are you doing when you have these messages? Are you exporting sequences or are you importing a file to PG?

**Comment by CHO-Hoon-Yeon** [comment]
OK. 1st, progress bar is fine. 
and i think this relations are Oracle's Sample data. like HR, OE ... and Scott/tiger one.
and this happens when i importing DSN on PG. 
after i finished inserting all data too PG, and this Notice rises.

**Comment by CHO-Hoon-Yeon** [comment]
![error](https://user-images.githubusercontent.com/50608320/70216863-bac74e80-1783-11ea-88ba-b27031bc1e72.PNG)
Like this one. sorry for using Japanese on cmd

**Comment by darold** [comment]
Well those messages are sent by PostgreSQL, this is just notice and I don't think you have to take care of them. Can you translate fully one message to verify what is about?

**Comment by CHO-Hoon-Yeon** [comment]
Notice Relation "departments_seq" is not exists on. going to skip
is full meaning of these messages.
i just wanna delete them. cuz that can make my client's complain or maybe concerning.

**Comment by darold** [comment]
Those message are generated by "DROP SEQUENCE orders_seq IF EXISTS;" for example, if you don't want them to appears you can set client_min_message to warning, this will prevent them to appears.

```
gilles=# DROP SEQUENCE IF EXISTS departments_seq;
NOTICE:  sequence "departments_seq" does not exist, skipping
DROP SEQUENCE
gilles=# SET client_min_messages TO WARNING;
SET
gilles=# DROP SEQUENCE IF EXISTS departments_seq;
DROP SEQUENCE
```

**Comment by CHO-Hoon-Yeon** [comment]
On Ora2pg.conf side? or on ora2pg.bat side??

**Comment by darold** [comment]
You may try:
```
PG_INITIAL_COMMAND    SET  client_min_messages TO WARNING
```
in ora2pg.conf, the command might be appended to output files.

**Comment by CHO-Hoon-Yeon** [comment]
Ah Okay thanks. and last question.
What if i just Delete my sequences such as Hr and so on?

**Comment by darold** [comment]
No don't delete your sequences just because you don't want the client see NOTICE log level, ora2pg know the job. About selection only 3 table in your batch, see `-a` ora2pg option, it overrides the ALLOW configuration directive.

**Comment by CHO-Hoon-Yeon** [comment]
Ok. but i think maybe on real migration circumstance, DB server don't have HR, Scott, OE and so on... Thanks.
and 2nd one, so you mean doing that on 1 batch is too dangerous? 
if i have almost 30 tables and they are having same columns, am i type their names to allow clause and using where clause on ora2pg conf is fine then?

**Comment by darold** [comment]
Please don't be offended by the following answer.

I just want to explain to users that I don't have the time for individual training or migration support for free. Ora2Pg is well documented and not intrusive on the Oracle database so you can securely test any configuration following what you want to achieve. This github interface it used to report issues on Ora2Pg not how I do that, there is certainly some forum where you can find community help.

Ora2Pg helps to save lot of time and money for Oracle to PostgreSQL migration and boss is very happy with that. Please don't use my spare time for free to gain even more time in your migration. Ora2Pg makes companies saving lot of money over the year but very few have the descent to donate to the project. This is the main reason why this project is in standby now, I have other projects with higher priorities.

Sorry that it goes with you but I must clarify this point :-)

**Comment by CHO-Hoon-Yeon** [comment]
i've truely understood. and thanks for your reply.
And using this makes me also happy to contribute to other people.
You've already shown me the way how to migrate. 
really thank you so much to using your spare time for my question.
