### ISSUE TITLE
Unexplain closed connections

### ISSUE THREAD

**Issue by jauresA** [darold/ora2pg#842]
Hi, 
 i have this issue we met during export from ORACLE 11.2.0.4 to PG11 using  Ora2Pg v20.0.

Here are the updated parameters  in the config file:

USER_GRANTS                          1 
EXPORT_SCHEMA                      1
SCHEMA                                     mymeail
LONGREADLEN                           1047552
NO_LOB_LOCATOR                    0
BITMAP_AS_GIN                         1
DISABLE_TRIGGERS                   1

]0;**TST**postgres@tlstnpgrdb02:/tech/postgres/dba/ora2pg/GRM/MYMEAL_DEV [mymeal] : ora2pg --type=COPY --conf=./config/ora2pg.conf 
[========================>] 70/70 tables (100.0%) end of scanning.                           
[=======================> ] 29/30 rows (96.7%) Table ALLERGEN (29 recs/sec)
[>                        ]      29/6953820 total rows (0.0%) - (0 sec., avg: 29 recs/sec).
[========================>] 786/786 rows (100.0%) Table ALLERGEN_LANGUAGE (786 recs/sec)                  
[>                        ]     815/6953820 total rows (0.0%) - (0 sec., avg: 815 recs/sec).
[========================>] 394/387 rows (101.8%) Table BATCH_REPORT (20 recs/sec)                         
[>                        ]    1209/6953820 total rows (0.0%) - (19 sec., avg: 63 recs/sec).
[========================>] 347/334 rows (103.9%) Table CATERER_SERVICE (347 recs/sec)                     
[>                        ]    1556/6953820 total rows (0.0%) - (19 sec., avg: 81 recs/sec).
[========================>] 208771/201974 rows (103.4%) Table CHANGE_HISTORY (16059 recs/sec)              
[>                        ]  210327/6953820 total rows (3.0%) - (32 sec., avg: 6572 recs/sec).
[========================>] 9/9 rows (100.0%) Table CLASSCODE (9 recs/sec)                                   
[>                        ]  210336/6953820 total rows (3.0%) - (32 sec., avg: 6573 recs/sec).
[========================>] 158/157 rows (100.6%) Table COMPLIANCE_INSPECTION (158 recs/sec)                 
[>                        ]  210494/6953820 total rows (3.0%) - (32 sec., avg: 6577 recs/sec).
[========================>] 850070/841640 rows (101.0%) Table COURSE (13710 recs/sec)                        
[===>                     ] 1060564/6953820 total rows (15.3%) - (95 sec., avg: 11163 recs/sec).
[========================>] 1217/1169 rows (104.1%) Table COURSE_ITEM_CODE (1217 recs/sec)                     
[===>                     ] 1061781/6953820 total rows (15.3%) - (95 sec., avg: 11176 recs/sec).
[========================>] 75/70 rows (107.1%) Table COURSE_LABEL (75 recs/sec)                               
[===>                     ] 1061856/6953820 total rows (15.3%) - (95 sec., avg: 11177 recs/sec).
[========================>] 7/7 rows (100.0%) Table CYCLE_TYPE (7 recs/sec)                                    
[===>                     ] 1061863/6953820 total rows (15.3%) - (95 sec., avg: 11177 recs/sec).
[========================>] 15/15 rows (100.0%) Table DILINKER (15 recs/sec)                                   
[===>                     ] 1061878/6953820 total rows (15.3%) - (95 sec., avg: 11177 recs/sec).
[========================>] 3/3 rows (100.0%) Table DURATION_TYPE (3 recs/sec)                                 
[===>                     ] 1061881/6953820 total rows (15.3%) - (96 sec., avg: 11061 recs/sec).
[========================>] 154698/154440 rows (100.2%) Table FLIGHT_LEG (7734 recs/sec)                       
[====>                    ] 1216579/6953820 total rows (17.5%) - (116 sec., avg: 10487 recs/sec).
[========================>] 2210/2205 rows (100.2%) Table FOOD_CONTROL_FREQUENCY (2210 recs/sec)                
[====>                    ] 1218789/6953820 total rows (17.5%) - (116 sec., avg: 10506 recs/sec).
[========================>] 495/495 rows (100.0%) Table FOOD_CONTROL_FREQ_COURSE (495 recs/sec)                 
[====>                    ] 1219284/6953820 total rows (17.5%) - (116 sec., avg: 10511 recs/sec).
[=======================> ] 3173/3182 rows (99.7%) Table FOOD_SAFETY_CONTROL (3173 recs/sec)                    
[====>                    ] 1222457/6953820 total rows (17.6%) - (117 sec., avg: 10448 recs/sec).
[========================>] 5680/5386 rows (105.5%) Table FOOD_SAFETY_CONTROL_COURSE (5680 recs/sec)            
[====>                    ] 1228137/6953820 total rows (17.7%) - (117 sec., avg: 10496 recs/sec).   
[========================>] 8/8 rows (100.0%) Table FREQUENCY (8 recs/sec)                                      
[====>                    ] 1228145/6953820 total rows (17.7%) - (117 sec., avg: 10496 recs/sec).
DBD::Pg::db pg_putcopyend failed: ERROR:  invalid byte sequence for encoding "UTF8": 0x89., avg: 10361 recs/sec)
CONTEXT:  COPY image, line 1: "54517	\x89504e470d0a1a0a0000000d494844520000015e0000012c08060000008bc1dbd0000080004944415478daecbd05..." at /usr/local/share/perl5/Ora2Pg.pm line 14578.
FATAL: ERROR:  invalid byte sequence for encoding "UTF8": 0x89
CONTEXT:  COPY image, line 1: "54517	\x89504e470d0a1a0a0000000d494844520000015e0000012c08060000008bc1dbd0000080004944415478daecbd05..."
DBI::db=HASH(0x33ffa98)->disconnect invalidates 1 active statement handle (either destroy statement handles or call finish on them before disconnecting) at /usr/local/share/perl5/Ora2Pg.pm line 13744.
Aborting export...

**Comment by darold** [comment]
This is an encoding issue. I'm closing the issue I guess it has been solved.
