### ISSUE TITLE
sequence value appears to belong to wrong oracle schema

### ISSUE THREAD

**Issue by rklaus77** [darold/ora2pg#844]
Our setup has 2500+ schemas, all with the same schema objects.  We migrated 164 of these and all the objects had the correct contents with the exception of the schema start values.

out/migrate_c1015.out:SELECT pg_catalog.setval('c1015.sq_pi_id', 222136286, true);
out/migrate_c1065.out:SELECT pg_catalog.setval('c1065.sq_pi_id', 222136286, true);
out/migrate_c1067.out:SELECT pg_catalog.setval('c1067.sq_pi_id', 222136286, true);
out/migrate_c1091.out:SELECT pg_catalog.setval('c1091.sq_pi_id', 222136286, true);
out/migrate_C1120.out:SELECT pg_catalog.setval('c1120.sq_pi_id', 222136286, true);
out/migrate_c1128.out:SELECT pg_catalog.setval('c1128.sq_pi_id', 222136286, true);

These should match the oracle values but they do not . . .

  1* select sequence_owner, sequence_name, last_number from dba_sequences where sequence_owner in ('C1015', 'C1065', 'C1067', 'C1091', 'C1120', 'C1128') AND sequence_name = 'SQ_PI_ID' order by sequence_owner
SQL>
SQL> /

SEQUENCE_OWNER                 SEQUENCE_NAME                  LAST_NUMBER
------------------------------ ------------------------------ -----------
C1015                          SQ_PI_ID                             98033
C1065                          SQ_PI_ID                            144627
C1067                          SQ_PI_ID                             50381
C1091                          SQ_PI_ID                             56421
C1120                          SQ_PI_ID                             46431
C1128                          SQ_PI_ID                              7621

6 rows selected.

This happened repeatedly, for each schema and for many different sequences.

**Comment by darold** [comment]
I don't know where you get the `SELECT pg_catalog.setval(...)` call but this is not from Ora2Pg. When exporting sequences Ora2Pg set the start value at sequence creation time. For example:
```
CREATE SEQUENCE "DEPARTMENTS_SEQ" INCREMENT 10 MINVALUE 1 MAXVALUE 9990 START 280;
CREATE SEQUENCE "EMPLOYEES_SEQ" INCREMENT 1 MINVALUE 1 NO MAXVALUE START 207;
CREATE SEQUENCE "LOCATIONS_SEQ" INCREMENT 100 MINVALUE 1 MAXVALUE 9900 START 3300;
```
