### ISSUE TITLE
Oracle datatype "Number" equivalent datatype on Postgres bigint problem

### ISSUE THREAD

**Issue by aymanadou** [darold/ora2pg#845]
Hi Darold,
I found a problem when migrating oracle table with column as datatype NUMBER having the precision and scale is null when it converts it to bigint to postgres.
In fact the datatype NUMBER on oracle accept (in case of scale and precision are null) floating numbers which is not the case on begint datatype postgres. 
I think double precision is the best matching type with oracle NUMBER datatype.
"If a precision is not specified, the column stores values as given. If no scale is specified, the scale is zero." doc oracle : 
https://docs.oracle.com/cd/B28359_01/server.111/b28318/datatype.htm#CNCPT1830

Regards

**Comment by darold** [comment]
Hi Aymen,

This is something well known that can be fully controlled with Ora2Pg, please have a look to  http://www.ora2pg.com/documentation.html#Column-tytpe-control

Best regards,
