### ISSUE TITLE
Can't call method "do" on an undefined value at /usr/local/share/perl5/Ora2Pg.pm line 7223.

### ISSUE THREAD

**Issue by sdpdb** [darold/ora2pg#847]
Hi @darold 

We are able to migrate the data using flat files from mysql to postgres using ora2pg. But while migrating on the fly getting below error. can you please help us to resolve this. 

We also set PG_DSN    ,PG_USER  , PG_PWD  in config files.

Error :

ora2pg -c /ora2pg/ora2pg.conf -m -d -b /ora2pg_files -l ora2pg_affinityplusfcu_onFly_Error.log
**Can't call method "do" on an undefined value at /usr/local/share/perl5/Ora2Pg.pm line 7223.**
 
Thanks

**Comment by darold** [comment]
Hi,

Looks like the connection to PostgreSQL can not be established but looks strange that it don't fail before that point. Do you have a related error message in PostgreSQL log file?

**Comment by sdpdb** [comment]
Hi @darold 
Apologies for late update, actually we have set other type as well rather than 'COPY' or 'DATA'. 
This issue was resolved once set type to COPY.

Thanks
