### ISSUE TITLE
Oracle blob export error. Wide character in subsoutine entry

### ISSUE THREAD

**Issue by glorsh66** [darold/ora2pg#849]
When I try to export a table with a blob column (images) 
with command - `ora2pg -t COPY -a 'TABLE[table_with_photos]`
I always get the following error -

```
Wide character in subroutine entry at /usr/local/share/perl/5.26.1/Ora2Pg.pm line 14578
DBD::Pg::db pg_putcopyed failed: ERROR; invalid byte sequence for encoding "UTF8": 0xff
CONTEXT: copy graf_obj.
```
Sorry I can't copy the whole message, but it's the main sting. because I had to type it manually.

Surprisingly `ora2pg -t INSERT -a 'TABLE[table_with_photos]` works just fine, but it creates broken images (can't open in dbforge or datagrid).

I have the following settings for encoding on oracle version 19
```
NLS_NCHAR_CHARACTERSET  = AL16UTF16
NLS_CHARACTERSET = CL8MSWIN1251
NLS_LANGUAGE = RUSSIAN

```

And postgres 9.6 database uses `UTF-8
`

**Comment by darold** [comment]
Please use latest development code, this have been fixed last week. To download and install last code:
```
wget https://github.com/darold/ora2pg/archive/master.zip
unzip master.zip
cd ora2pg-master/
perl Makefile.PL
make
sudo make install
```
