### ISSUE TITLE
Converting Oracle RAW(16) to PostgreSQL uuid

### ISSUE THREAD

**Issue by ValeryVasilev** [darold/ora2pg#851]
I want to convert columns in Oracle that are of type RAW(16) to the PostgreSQL type uuid. I tried setting the DATA_TYPE in the ora2pg.conf file, but it is not converting in hex.

Config i use: DATA_TYPE<----->RAW(16):uuid
Result i want to get: \xa390253e02c842b6b37f656591dc9cbe
Result that i got: \x3143453445453338353736373431423238334434384146304138363531394435

**Comment by darold** [comment]
If the default value of the RAW(16) Oracle column is `sys_guid` then Ora2Pg will automatically use `uuid` for the corresponding PG data type. I mean that you don't need to set DATA_TYPE.

However, are you using Ora2Pg latest development code? There was a bug in BLOB/RAW conversion that has been fixed last week.

**Comment by ValeryVasilev** [comment]
Without using data_type i get uuid in hex but data length is bigger than in oracle
result: \x6465636f64652845274138333345413946313337323437363042303342364541333233443931394630272c20276865782729
result i want to get: \xa390253e02c842b6b37f656591dc9cbe

**Comment by ValeryVasilev** [comment]
Solve this problem by using modify_type

**Comment by darold** [comment]
Can you post the value of MODIFY_TYPE you use?

**Comment by ValeryVasilev** [comment]
MODIFY_TYPE<-->table_name:globalid:bytea

**Comment by darold** [comment]
Do you have a default value on Oracle side for this column?

**Comment by ValeryVasilev** [comment]
Oracle side
![image](https://user-images.githubusercontent.com/36477323/75650997-84a54800-5c68-11ea-8148-c79e62cd2e92.png)

**Comment by darold** [comment]
Please use latest development code, now RAW(16) are automatically transformed into uuid. Of course the PostgreSQL destination column must be of type uuid.

**Comment by dataeratr** [comment]
done
thank you.
