### ISSUE TITLE
Duplicate index created on composite uniq index

### ISSUE THREAD

**Issue by sdpdb** [darold/ora2pg#852]
Hi @darold 

While migrating index , we face some issue. like if source database have composite unique index then on target database it created with duplicate indexes. 

For instance :
Source database :
UNIQUE KEY `name` (`name`,`client_fk`),

Target database :

"CREATE UNIQUE INDEX input_test3_fk ON input_test USING btree (name, client_fk)"
"CREATE UNIQUE INDEX input_test3_fk_key ON input_test USING btree (name, client_fk)" 

later we found that index.sql and constraint.sql both have same DDL. 

Is there any work around to avoid this index duplication ?

Thanks

**Comment by JonBetts** [comment]
I am also getting duplicate unique keys being created in the migration script when exporting my tables. After the table is created, I have both of these statements in the migration script:

`
CREATE UNIQUE INDEX unique_agency_job_reg ON agency_job_reg (job_id, agency_id);
ALTER TABLE agency_job_reg ADD CONSTRAINT unique_agency_job_reg UNIQUE (job_id, agency_id);
`
I am using the latest version of ora2pg.

**Comment by darold** [comment]
Commit 06c8e07 fixes this issue.

**Comment by gp4git** [comment]
I just installed last release of ora2pg (v21) and still experienced what JonBetts described above for composite unique indexes.
Did I miss something in the conf ?

Best regards
