### ISSUE TITLE
import to remote PostgreSQL not working using import_all.sh

### ISSUE THREAD

**Issue by SCI-sksaha** [darold/ora2pg#853]
import_all.sh -d prepd -o pgadmin -U pgadmin -I -l prepd_import_1.log -h <AWS host>

Note1: pgadmin is the admin id for the PG cluster
Note2: prepd database does not exist

Goal: Schema and data will be loaded to the database prepd owned by pgadmin

config file:
PG_DSN  dbi:Pg:dbname=prepd;host=<AWS host>;port=5432
PG_USER pgadmin
PG_PWD  xxxxxxx
PG_SCHEMA prod

Note3:
Export completed with:
SCHEMA PROD
EXPORT_SCHEMA 1

Note 4: Seems like import_all.sh is not using the config file.

Output:
Password for user pgadmin:
psql: FATAL:  database "prepd" does not exist
Would you like to create the owner of the database pgadmin? [y/N/q] N
Password for user pgadmin:
psql: FATAL:  database "prepd" does not exist
Would you like to create the database prepd? [y/N/q] q

**Comment by sdpdb** [comment]
Hi @SCI-sksaha 
Do you have "prepd" postgres database up front ?

**Comment by darold** [comment]
Well the script has detected that destination database does not exists and propose to create it for you, happen if you enter Y instead of q to this question?

**Comment by SCI-sksaha** [comment]
Thanks for your support!
