### ISSUE TITLE
Import procedure and function ora2pg

### ISSUE THREAD

**Issue by Dedy-S** [darold/ora2pg#854]
Hi,

I wanna ask, I was using ora2pg -20 and already export Procedure and Function, and then import into postgresql. Function is imported in function postgresql, and when import Procedure, it is imported into function postgresql too, not in procedure postgresql. Can it be made like oracle condition,?(function imported in function, and procedure imported in procedure)

Thank you before.

**Comment by darold** [comment]
Hi,

You should have `PG_VERSION      11` in your ora2pg.conf file and if it don't work set:
```
PG_SUPPORTS_PROCEDURE        1
```

**Comment by Dedy-S** [comment]
Thank you, it's worked.

I wanna ask again, when I try export packages. It's stuck on process 6,7%, I try waiting untill 3 days and still same. What's wrong with my export pacakages?

**Comment by darold** [comment]
Sometime the export hangs due to some condition on Oracle side, you should ctrl+c and restart export. About jobs, they are not exported. I still have to implement job export with the different job scheduling solution for PostgreSQL but for now this must be done manually.

**Comment by Dedy-S** [comment]
Thank you Darold,

I will ask again if I find a problem.

**Comment by Dedy-S** [comment]
Hello Darold,

I wanna ask something about import procedure, when I import procedure, so many error with 

ERROR:  function result type must be record because of OUT parameters

Shoul I commit something?
