### ISSUE TITLE
Export constrains separately from tables 

### ISSUE THREAD

**Issue by glorsh66** [darold/ora2pg#855]
Is it possible to export constraints and indexes without exporting the tables themselves?

Because now I have to initially export tables using the following command
` ora2pg -t TABLE -o tables.sql` 
After this is complete, I have to manually edit sql file (move foreign keys to a separate file, gladly they are placed in the end of the file).

I have to do it because 
` ora2pg -t COPY `
doesn't work with constraints enabled, because tables as far as I understand are being copied in alphabetical order disregarding dependencies imposed by the foreign keys. 

I have also read that it's advised that the data be copied first, and only having done so, one must create indexes and foreign keys to speed up the migration process. 

is it possible on the current release of ora2pg to achieve this? Or the only possible way is to manually edit sql files? It's not something that can't be done manually, but it would be much more convenient to automate this (we have a lot of tables, several hundreds).

**Comment by darold** [comment]
I would say that there is an option for everything in Ora2Pg :-)

Look at documentation for configuration directive: FILE_PER_CONSTRAINT

**Comment by darold** [comment]
And look also at FILE_PER_INDEX, FILE_PER_FKEYS and all FILE_PER_* directives they all should be set to 1.

**Comment by glorsh66** [comment]
> I would say that there is an option for everything in Ora2Pg :-)
> 
> Look at documentation for configuration directive: FILE_PER_CONSTRAINT

How do I use it? In the manual FILE_PER_CONSTRAINT  resides in the PostgreSQL Import section.
But I want to export it separately..

**Comment by glorsh66** [comment]
I got it. You must edit it in the configuration file 
`/ect/ora2pg/ora2pg.conf`
before the export of tables
