### ISSUE TITLE
Incorrect Export Logs

### ISSUE THREAD

**Issue by skamalj** [darold/ora2pg#857]
Hello Darold, 
I ran into this issue, where logs are incorrect but my export import of data is fine. Below is what export shows. For some reason counting for rows exported stalled at 1112, while actually  it does export everything.

[========================>] 0/0 procedures (100.0%) end of procedures export.
[========================>] 0/0 partitions (100.0%) end of output.
[========================>] 0/0 types (100.0%) end of output.
[========================>] 0/0 materialized views (100.0%) end of output.
[========================>] 0/0 dblink (100.0%) end of output.
[========================>] 0/0 synonyms (100.0%) end of output.
[========================>] 0/0 directory (100.0%) end of output.
[========================>] 0/0 packages (100.0%) end of output.
[========================>] 0/0 views (100.0%) end of output.
[========================>] 0/0 triggers (100.0%) end of output.
[========================>] 0/0 functions (100.0%) end of functions export.
[========================>] 0/0 procedures (100.0%) end of procedures export.
[========================>] 0/0 partitions (100.0%) end of output.
[========================>] 0/0 types (100.0%) end of output.
[========================>] 0/0 materialized views (100.0%) end of output.
[========================>] 12/12 tables (100.0%) end of scanning.                
[========================>] 319/0 rows (100.0%) Table CONTACTS (319 recs/sec)
[======>                  ]  319/1112 total rows (28.7%) - (4 sec., avg: 79 recs/sec).
[========================>] 25/0 rows (100.0%) Table COUNTRIES (25 recs/sec)                       
[=======>                 ]  344/1112 total rows (30.9%) - (6 sec., avg: 57 recs/sec).
[========================>] 319/0 rows (100.0%) Table CUSTOMERS (319 recs/sec)                     
[==============>          ]  663/1112 total rows (59.6%) - (9 sec., avg: 73 recs/sec).
[========================>] 107/0 rows (100.0%) Table EMPLOYEES (107 recs/sec)                     
[================>        ]  770/1112 total rows (69.2%) - (13 sec., avg: 59 recs/sec).
[========================>] 1112/1112 rows (100.0%) Table INVENTORIES (1112 recs/sec)               
[========================>] 1882/1112 total rows (169.2%) - (15 sec., avg: 125 recs/sec).
[========================>] 23/0 rows (100.0%) Table LOCATIONS (23 recs/sec)                           
[========================>] 1905/1112 total rows (171.3%) - (18 sec., avg: 105 recs/sec).
[========================>] 105/0 rows (100.0%) Table ORDERS (105 recs/sec)                            
[========================>] 2010/1112 total rows (180.8%) - (21 sec., avg: 95 recs/sec).
[========================>] 665/0 rows (100.0%) Table ORDER_ITEMS (665 recs/sec)                       
[========================>] 2675/1112 total rows (240.6%) - (24 sec., avg: 111 recs/sec).
[========================>] 288/0 rows (100.0%) Table PRODUCTS (288 recs/sec)                          
[========================>] 2963/1112 total rows (266.5%) - (27 sec., avg: 109 recs/sec).
[========================>] 5/0 rows (100.0%) Table PRODUCT_CATEGORIES (5 recs/sec)                    
[========================>] 2968/1112 total rows (266.9%) - (29 sec., avg: 102 recs/sec).
[========================>] 4/0 rows (100.0%) Table REGIONS (4 recs/sec)                               
[========================>] 2972/1112 total rows (267.3%) - (32 sec., avg: 92 recs/sec).
[========================>] 9/0 rows (100.0%) Table WAREHOUSES (9 recs/sec)                            
[========================>] 2981/1112 total rows (268.1%) - (34 sec., avg: 87 recs/sec).

**Comment by darold** [comment]
The number of rows is based on Oracle statistics, if you want more accurate rows number you must have up to date statistics.

**Comment by skamalj** [comment]
Yes, works. Thanks
