### ISSUE TITLE
Incorrect evaluation of $lob_content when setting data value

### ISSUE THREAD

**Issue by jhollandsworth** [darold/ora2pg#858]
When a clob field contains the value of '0', the resulting postgres field value is incorrectly set to null.

The problem appears to be at line 14282 of Ora2pg.pm. If the value of lob_content is '0' (or '') perl will evaluate the condition as false and the field data will be set to undef.

if ($lob_content) {
    $row[$j] = $lob_content;
} else {
    $row[$j] = undef;
}

**Comment by darold** [comment]
Hi, does this value of 0 for a BLOB is expected or is this the value for an empty BLOB?

**Comment by jhollandsworth** [comment]
Hi,

The value of '0' in the source Oracle clob field is expected. It does not represent an empty clob. It is a valid user entered value.

Thank you.

**Comment by darold** [comment]
Then commit 9594d50 might solve this issue. Thanks for the report.

**Comment by jhollandsworth** [comment]
@darold Thank you. This resolved the issue.
