### ISSUE TITLE
Security definer & invoker ora2pg

### ISSUE THREAD

**Issue by Dedy-S** [darold/ora2pg#859]
Hi Darold,

I got problem with error SECURITY DEFINER, when import procedure. when I use config FORCE_SECURITY_INVOKER 1. Error still appear with SECURITY INVOKER now, what's wrong with my config?

**Comment by darold** [comment]
Hi, reporting the error message could help to respond to your question.

**Comment by Dedy-S** [comment]
psql:/u02/procedure_invoker/DROP_TABLE_PROCEDURE.sql:64: ERROR:  syntax error at or near "SECURITY"
LINE 52: SECURITY INVOKER

Output ora2pg : 
`SET client_encoding TO 'UTF8';

SET search_path = igrsmg;
\set ON_ERROR_STOP ON



CREATE OR REPLACE PROCEDURE igrsmg.drop_table () AS $body$
DECLARE

   v_owner    varchar(10);
   v_qry      varchar(30000);
   v_result   varchar(30000);
  rec RECORD;

BEGIN
   SELECT DISTINCT owner
     INTO STRICT v_owner
     FROM ALL_TABLES
    WHERE TABLE_NAME = 'TBMASTER';


   FOR rec IN (SELECT *
                 FROM unknown_table@igrcrm
                WHERE owner = v_owner AND coalesce(flag_delete, 'z') = 'Y')
   LOOP
      BEGIN
         v_qry := 'drop table ' || rec.table_name;

         EXECUTE(v_qry);

         v_result := 'table ' || rec.table_name || ' dropped';

         UPDATE unknown_table@igrcrm
            SET result = v_result
          WHERE     owner = rec.owner
                AND table_name = rec.table_name
                AND column_name = rec.table_name;

         COMMIT;
      EXCEPTION
         WHEN OTHERS
         THEN
            v_result :=
               'error drop table ' || rec.table_name || ', ' || SQLERRM;

            UPDATE unknown_table@igrcrm
               SET result = v_result
             WHERE     owner = rec.owner
                   AND table_name = rec.table_name
                   AND column_name = rec.table_name;

            COMMIT;
      END;
   END LOOP;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE igrsmg.drop_table () FROM PUBLIC;`

**Comment by Dedy-S** [comment]
psql:/u02/backup_ora2pg_2/procedure_invoker/DROP_TABLE_PROCEDURE_IGRSMG.sql:64: ERROR:  syntax error at or near "SECURITY"
LINE 52: SECURITY INVOKER

Output ora2pg:         
`SET client_encoding TO 'UTF8';

SET search_path = smg;
\set ON_ERROR_STOP ON



CREATE OR REPLACE PROCEDURE igrsmg.drop_table () AS $body$
DECLARE

   v_owner    varchar(10);
   v_qry      varchar(30000);
   v_result   varchar(30000);
  rec RECORD;

BEGIN
   SELECT DISTINCT owner
     INTO STRICT v_owner
     FROM ALL_TABLES
    WHERE TABLE_NAME = 'TBMASTER';


   FOR rec IN (SELECT *
                 FROM unknown_table@igrcrm
                WHERE owner = v_owner AND coalesce(flag_delete, 'z') = 'Y')
   LOOP
      BEGIN
         v_qry := 'drop table ' || rec.table_name;

         EXECUTE(v_qry);

         v_result := 'table ' || rec.table_name || ' dropped';

         UPDATE unknown_table@igrcrm
            SET result = v_result
          WHERE     owner = rec.owner
                AND table_name = rec.table_name
                AND column_name = rec.table_name;

         COMMIT;
      EXCEPTION
         WHEN OTHERS
         THEN
            v_result :=
               'error drop table ' || rec.table_name || ', ' || SQLERRM;

            UPDATE unknown_table@igrcrm
               SET result = v_result
             WHERE     owner = rec.owner
                   AND table_name = rec.table_name
                   AND column_name = rec.table_name;

            COMMIT;
      END;
   END LOOP;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE igrsmg.drop_table () FROM PUBLIC;
`

**Comment by Dedy-S** [comment]
`SET client_encoding TO 'UTF8';

SET search_path = smg;
\set ON_ERROR_STOP ON



CREATE OR REPLACE PROCEDURE igrsmg.drop_table () AS $body$
DECLARE

   v_owner    varchar(10);
   v_qry      varchar(30000);
   v_result   varchar(30000);
  rec RECORD;

BEGIN
   SELECT DISTINCT owner
     INTO STRICT v_owner
     FROM ALL_TABLES
    WHERE TABLE_NAME = 'TBMASTER';


   FOR rec IN (SELECT *
                 FROM unknown_table@igrcrm
                WHERE owner = v_owner AND coalesce(flag_delete, 'z') = 'Y')
   LOOP
      BEGIN
         v_qry := 'drop table ' || rec.table_name;

         EXECUTE(v_qry);

         v_result := 'table ' || rec.table_name || ' dropped';

         UPDATE unknown_table@igrcrm
            SET result = v_result
          WHERE     owner = rec.owner
                AND table_name = rec.table_name
                AND column_name = rec.table_name;

         COMMIT;
      EXCEPTION
         WHEN OTHERS
         THEN
            v_result :=
               'error drop table ' || rec.table_name || ', ' || SQLERRM;

            UPDATE unknown_table@igrcrm
               SET result = v_result
             WHERE     owner = rec.owner
                   AND table_name = rec.table_name
                   AND column_name = rec.table_name;

            COMMIT;
      END;
   END LOOP;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE igrsmg.drop_table () FROM PUBLIC;
`

**Comment by Dedy-S** [comment]
example:
psql:/u02/procedure_invoker/DROP_TABLE_PROCEDURE.sql:64: ERROR:  syntax error at or near "SECURITY"
LINE 52: SECURITY INVOKER

Output ora2pg:
```
SET client_encoding TO 'UTF8';

SET search_path = smg;
\set ON_ERROR_STOP ON



CREATE OR REPLACE PROCEDURE igrsmg.drop_table () AS $body$
DECLARE

   v_owner    varchar(10);
   v_qry      varchar(30000);
   v_result   varchar(30000);
  rec RECORD;

BEGIN
   SELECT DISTINCT owner
     INTO STRICT v_owner
     FROM ALL_TABLES
    WHERE TABLE_NAME = 'TBMASTER';


   FOR rec IN (SELECT *
                 FROM unknown_table@igrcrm
                WHERE owner = v_owner AND coalesce(flag_delete, 'z') = 'Y')
   LOOP
      BEGIN
         v_qry := 'drop table ' || rec.table_name;
`
         EXECUTE(v_qry);

         v_result := 'table ' || rec.table_name || ' dropped';

         UPDATE unknown_table@igrcrm
            SET result = v_result
          WHERE     owner = rec.owner
                AND table_name = rec.table_name
                AND column_name = rec.table_name;

         COMMIT;
      EXCEPTION
         WHEN OTHERS
         THEN
            v_result :=
               'error drop table ' || rec.table_name || ', ' || SQLERRM;

            UPDATE unknown_table@igrcrm
               SET result = v_result
             WHERE     owner = rec.owner
                   AND table_name = rec.table_name
                   AND column_name = rec.table_name;

            COMMIT;
      END;
  END LOOP;
END;
$body$
LANGUAGE PLPGSQL
SECURITY INVOKER
;
-- REVOKE ALL ON PROCEDURE igrsmg.drop_table () FROM PUBLIC;
```

**Comment by darold** [comment]
I do not have the SECURITY syntax error with your code, I just have to remove the single backquote after `v_qry := 'drop table ' || rec.table_name;` but I guess it is a typo. Replacing `unknown_table@crm` with `unknown_table` everything goes as expected:
```
$ psql -f 859.sql
SET
SET
CREATE PROCEDURE
```
with PG 12.

**Comment by Dedy-S** [comment]
Yes, single backquote it's my typo when comment. 
I try replacing `unknown_table@crm` with `unknown_table` but error still appear and it's not happen in just one procedure, but many procedure with SECURITY syntax error.  I try migration data using ora2pg 20.0 and edb PG 8.4, is this the problem from my postgresql version or something in my postgresql?

**Comment by darold** [comment]
I suppose that EDB have more recent version than 8.4. I don't know their implementation of the CREATE PROCEDURE but I'm pretty sure that using a recent version of EDB PG will solve your problem. At least with PG 12 I can tell you that there is no problem. The other solution is to set PG_SUPPORTS_PROCEDURE to 0 or PG_VERSION to 8.4 in your ora2pg.conf, it will force Ora2Pg to use function instead.
