### ISSUE TITLE
Fetching types occasionally causes an oracle exception

### ISSUE THREAD

**Issue by jhollandsworth** [darold/ora2pg#860]
It has been occasionally observed that when fetching custom types an oracle error is encountered. Using a local database handler in the _get_types subroutine appears to take care of this issue:

sub _get_types
{
....
  my $local_dbh = $self->_oracle_connection();
 <replace local uses of $self->{dbh}  with $local_dbh>
...
  $local_dbh->disconnect() if ($local_dbh);
}

**Comment by darold** [comment]
Patch applied in commit 2efdd3c
