### ISSUE TITLE
How to migrate ST_GEOMETRY Type into postgreSQL??

### ISSUE THREAD

**Issue by divsri** [darold/ora2pg#867]
Hi Darold,
                 I have been using Ora2pg Tool for Migration. I have ST_GEOMETRY Type in Oracle, I am not finding a way to migrate this type to PostgreSQL. Could you please help me on this?

**Comment by darold** [comment]
Ora2Pg only supports Oracle SDO Geometry data type. I don't known if ST_GEOMETRY (from ArcGis I guess?) is exactly the same than in PostGis or if there is some proprietary thing but I think that ST_Geometry is normalized so there should be a function that can be used to obtain the right format.

I don't think this is complicated to implement but I don't have such database at my hand and it requires some investigation and implementation time that I don't have for the moment.

**Comment by darold** [comment]
Ora2Pg only supports Oracle SDO Geometry data type. I don't known if ST_GEOMETRY (from ArcGis I guess?) is exactly the same than in PostGis or if there is some proprietary thing but I think that ST_Geometry is normalized so there should be a function that can be used to obtain the right format.

I don't think this is complicated to implement but I don't have such database at my hand and it requires some investigation and implementation time that I don't have for the moment.

**Comment by darold** [comment]
More though. I think that there must be a corresponding function to Oracle `SDO_UTIL.TO_WKTGEOMETRY()` to extract the geometry as text. In this case use it instead in Ora2Pg.pm.
