### ISSUE TITLE
Filters not used in TEST mode

### ISSUE THREAD

**Issue by pigreco33** [darold/ora2pg#868]
Hi, I just migrate a database with a lot of tables (millions of record eone thousand of tables).
Mi ora2pg.conf is filtered with ALLOW parameter (to avoid to migrate any tables) and SKIP parameter.
The problem is when I run in TEST mode these parameters are not used so I've a lot of differences between source and dest according to all tables and indexes that I've decided to not migrate.
Can you help me?

**Comment by darold** [comment]
It is in my todo list as well as limiting the test to a particular schema defined in PG_SCHEMA.

**Comment by darold** [comment]
Should be already fixed since 22.0, closing.
