### ISSUE TITLE
Oracle procedure getting migrated as Postgres Function

### ISSUE THREAD

**Issue by chaluvadi286** [darold/ora2pg#872]
When I try to migrate a simple Oracle procedure to Postgres, it is getting converted as FUNCTION instead of PROCEDURE

CREATE OR REPLACE PROCEDURE "SP_DETAILS" (A In Number,B In Number ,C Out  Number)IS
Begin
DBMS_OUTPUT.PUT_LINE('HI');
END SP_DETAILS;

OUTPUT
===========
CREATE OR REPLACE FUNCTION sp_details (A numeric,B numeric ,C Out numeric) AS $body$
BEGIN
RAISE NOTICE 'HI';
END;
$body$
LANGUAGE PLPGSQL
;

I am currently version 20 of OraPg and have given option PG_VERSION 11/12 in conf file but still converting as FUNCTION, help me in resolving this issue
**PG_VERSION	11**

**Comment by darold** [comment]
You should have `PG_SUPPORTS_PROCEDURE` disabled in the ora2pg.conf, remove the directive or set it to 1.

**Comment by chaluvadi286** [comment]
Thanks for responding, I have tried all options but in all cases it is
converting as FUNCTION only

1. Option # 1 - Enable procedure support tag
PG_VERSION 12
PG_SUPPORTS_PROCEDURE 1

2. Option # 2 - Disable procedure support tag
PG_VERSION 12
PG_SUPPORTS_PROCEDURE 0

3. Option # 3 - Commenting procedure support tag
PG_VERSION 12
#PG_SUPPORTS_PROCEDURE 0

I have even tried with PG_VERSION as 11 as well but no luck. Attaching the
scripts used for reference
*CMD>ora2pg.bat -c PROC2/ora2pg_sp.conf*

**Comment by darold** [comment]
Ok, there might be a bug, I will fix it.

**Comment by darold** [comment]
Not reproducible, please upgrade to latest development code.
