### ISSUE TITLE
Problem with Function on Index and PRESERVE CASE 1

### ISSUE THREAD

**Issue by traxverlis** [darold/ora2pg#876]
Hello

When PRESERVACE CASE is set and there is a function like RTRIM in an Index, there is no Quote in Field.

- translated code

`CREATE INDEX "IX_OPEG_002" ON "OPEG" (RTRIM(COLLCOD), "OPEGBASPREP");`

- source from Oracle SQL dev 

` CREATE INDEX "IX_OPEG_002" ON "OPEG" (RTRIM("COLLCOD"), "OPEGBASPREP") `

is the same with other function like SUBSTR

**Comment by darold** [comment]
Fixed in commit e775179.
