### ISSUE TITLE
Problem with :: and ||  on Index

### ISSUE THREAD

**Issue by traxverlis** [darold/ora2pg#877]
Hi

When I have the || in a field on Index the translation doesn't add the double Quote when  PRESERVE CASE  is SET and doesn't add the brackets

- source Code from Oracle SQL dev 

`  CREATE INDEX"IX_POPM_001" ON "POPM" ("COLLCOD", "OPEGANN", "OPEGNUM", "OBJECODNAT", "OPEILIG", TO_CHAR("BUDGEXE")||"OPPMTYP") `

- Translated Code

`CREATE INDEX "IX_POPM_001" ON "POPM" ("COLLCOD", "OPEGANN", "OPEGNUM", "OBJECODNAT", "OPEILIG", BUDGEXE::varchar||OPPMTYP  );`

**Comment by darold** [comment]
Fixed too with commit e775179
```
CREATE INDEX "EMP_EMPNO_ENAME_MGR" ON "EMP" ("EMPNO", "ENAME", ("MGR"::varchar)||"JOB");
```
