### ISSUE TITLE
Quoting: Postgres DDL for comments

### ISSUE THREAD

**Issue by mkgrgis** [darold/ora2pg#878]
In my case there is quoting of names of Oracle objects. 
`PRESERVE CASE 1`
 There is no errors in DDL for tables, but quoting for comments look like
`COMMENT ON COLUMN "schema.table.column" 'text';`
Correct form with quoting look like 
`COMMENT ON COLUMN "schema"."table"."column" 'text';`
because it can be any white spaces in name of some object in PostgreSQL 8+.

**Comment by darold** [comment]
Commit 7f74071 fixes this issue.

**Comment by mkgrgis** [comment]
Merci beaucoup! Votre diagnostic est précis. Cela fonctionne comme il se doit.
