### ISSUE TITLE
XMLTYPE columns are exported as OCILobLocatorPtr=SCALAR(0x560d3db8ed38)

### ISSUE THREAD

**Issue by smil2k** [darold/ora2pg#879]
In case the table contains a column of "XMLTYPE", then the export does not contain the blob data itself, but a string representation of the "OCILobLocatorPtr".

This is the actual output of the export SQL:
```
COPY schema.afs_log (change_type,xmldata) FROM STDIN;
NRC     OCILobLocatorPtr=SCALAR(0x560d3db8ed38)
```

**Comment by darold** [comment]
I will fix it but have you tried with NO_LOB_LOCATOR set to 1 and does it works as expected?

**Comment by smil2k** [comment]
I'll try it and get back to you. Thanks for the suggestion.

**Comment by darold** [comment]
By the same time let me know if new commit 1b9436a fixes this issue.

**Comment by smil2k** [comment]
It seems that NO_LOG_LOCATOR works, but slow.
Does your commit address the data limiting also for these? The original code used 10k fetch for the table, instead of 1k.

**Comment by smil2k** [comment]
Unfortunately the fix did not help. 
(Speed is very slow at the moment for this table: 22/sec, but maybe it is the VPN)

**Comment by darold** [comment]
Yes sorry I forgot to mark XMLTYPE as having lob locator, done in commit b853340.

**Comment by smil2k** [comment]
Thank you! works fine!

**Comment by darold** [comment]
How about the export speed? Is it better than the 22 tuples/s?

**Comment by smil2k** [comment]
Unfortunately it is now around 1-5 rec/sec. I'll try to do it without VPN, latency is large.

**Comment by smil2k** [comment]
119 recs/sec using a computer near the DB instance. 
(other tables go 29k/sec, probably blob handling is sluggish)
