### ISSUE TITLE
WARNING: can not extract data from SNAPSHOT_XXX no column found...

### ISSUE THREAD

**Issue by smil2k** [darold/ora2pg#880]
During data export some of the tables reported "no columns". 
Checking it in SQL Developer they indeed have. 

How to debug such situation?

**Comment by darold** [comment]
I guess this is this situation? The Oracle error number help usually.
```
ORA-31467: no column found in the source table
Cause: The OBJECT_ID flag was set to “Y” on the call to CREATE_CHANGE_
TABLE and change table belongs to the synchronous change set. The
corresponding object column was not detected in the source table.
Action: Create the change table with the OBJECT_ID flag set to “N” or investigate
why the object column is not in the source table and add it to the source table.
```
Does `SNAPSHOT_XXX` a regular table or an Oracle system table? Or created by CREATE SNAPSHOT?

**Comment by smil2k** [comment]
To be frank I did not even know about this create snapshot possibility.

I’ll try to figure out. It is definitely not a system table. I think it must be a snapshot.

**Comment by smil2k** [comment]
SQL Developer exports just a normal "create table": It seems to be just a regular table, which a trigger which create history records elsewhere.

I've tried to enable --debug, but nothing special is written out about them.

**Comment by darold** [comment]
Can you post the description of the table and the Oracle error number?

**Comment by smil2k** [comment]
Even if running with --debug there is no oracle error message at all. 

I can send the DDL to you over email if it fits you.

**Comment by darold** [comment]
yeah, gilles AT darold DOT net

**Comment by darold** [comment]
Actually I don't know what happen with this table, this seems to be a regular table without special definition. I think you should ask to an Oracle DBA about this error giving the ORA-XXXXX number, maybe this is something known.

**Comment by smil2k** [comment]
I'll wireshark it. ora2pg does not return any ORA error.

**Comment by darold** [comment]
Please post the exact error message from Ora2Pg.

**Comment by smil2k** [comment]
"WARNING: can not extract data from XCREWLOF.SNAPSHOT_XXX, no column found..."

**Comment by smil2k** [comment]
I see nothing else in the log, not even in debug mode

**Comment by smil2k** [comment]
ORA-01403: no data found

**Comment by smil2k** [comment]
This is the select : 
```
SELECT A.COLUMN_NAME, A.NULLABLE, A.DATA_DEFAULT, A.TABLE_NAME, A.OWNER, A.COLUMN_ID

FROM ALL_TAB_COLUMNS A, ALL_OBJECTS O WHERE A.OWNER=O.OWNER and A.TABLE_NAME=O.OBJECT_NAME and O.OBJECT_TYPE='TABLE' 
AND A.TABLE_NAME='SCHEMA.SNAPSHOT_XXX'
AND A.OWNER NOT IN bla bla ORDER BY A.COLUMN_ID
```
returns no columns...

Removing the "schema" prefix fixed the situation (in sql developer). I have no idea why other tables work...

**Comment by darold** [comment]
Hum Ora2Pg should not add the schema name in the TABLE_NAME filter, it is to be used in the OWNER filter. I guess that your are using the ALLOW option -a `XCREWLOF.SNAPSHOT_XXX`? You can not do that, you must use it like that: ` -n XCREWLOF -a SNAPSHOT_XXX`

**Comment by smil2k** [comment]
I was using "ALLOW		SNAPSHOT_XXX" in order to speed things up without any schema qualifications.

**Comment by darold** [comment]
I can not reproduce the issue with latest development code. Can you try with an other table of this schema to see the statement used and see if the schema is also appended to the table name or not?

**Comment by smil2k** [comment]
Fun. It seems that the query I posted is sent using prefix, and no rows returned, in case of a positive example!

I've very bad at interpreting TNS packets by eye, I can send you the packetdumps of both cases per email.

Anyhow, this is the ora error: ORA-01403: no data found

**Comment by smil2k** [comment]
I think I found the answer to the question what this snapshot table is: 
they are materialized views!

as they are proper tables, oracle shows them in the "tables" section also...

**Comment by darold** [comment]
What is your version of Oracle database? Actually Ora2Pg do not export tables that are also registered into table ALL_MVIEWS. The exact filter is:
```
AND (A.OWNER, A.TABLE_NAME) NOT IN (
        SELECT OWNER, MVIEW_NAME FROM ALL_MVIEWS
        UNION ALL SELECT LOG_OWNER, LOG_TABLE FROM ALL_MVIEW_LOGS
)
```
this is true only for Oracle version > 8i or if you are exporting tables as foreign tables (Ora2Pg FDW export type).

**Comment by smil2k** [comment]
We are using 12+. I've executed the selects and returned the given mviews, still export way attempted.

**Comment by darold** [comment]
Commits b021ca and 627e60d remove attempt to dump data from MVIEWs which leads to "no column found" warning and prevent dumping internal indexes from MVIEWs.
