### ISSUE TITLE
CPAN HELL

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#882]
I'm in CPAN hell when trying to install the DBI.pm module since FTP is blocked and proxies are not allowed:
`perl -MCPAN -e 'install DBD::Oracle'`

It get's stuck on this line:
```
Would you like me to automatically choose some CPAN mirror
sites for you? (This means connecting to the Internet) [yes]
Trying to fetch a mirror list from the Internet
Fetching with HTTP::Tiny:
http://www.perl.org/CPAN/MIRRORED.BY
HTTP::Tiny failed with an internal error: HTTPS via proxy is not supported

Fetching with HTTP::Tiny:
http://www.perl.org/CPAN/MIRRORED.BY.gz
HTTP::Tiny failed with an internal error: HTTPS via proxy is not supported

Fetching with Net::FTP:
ftp://ftp.perl.org/pub/CPAN/MIRRORED.BY
```
How do I get around this?  I tried to download DBI module directly and compile it, and then I got a DBI.pm module, but not the Oracle.pm one.

```
wget https://cpan.metacpan.org/authors/id/T/TI/TIMB/DBI-1.643.tar.gz
tar xvzf DBI-1.643.tar.gz
cd DBI-1.643/
perl Makefile.PL
make
```

When I ran make test, got all sorts of errors.

I think I finally got the Oracle.pm after tinkering with the CPAN shell:
```
perl -MCPAN -e shell
cpan[1]>o conf init /proxy/
Your http_proxy? [http://proxy.ebiz.vz.com:80]
cpan> o conf commit
Your CPAN should be ready to access HTTP mirrors via proxy!
```
After this, I have a Oracle.pm file and I copied it to the /usr/lib64/perl5/vendor_perl directory where the DBI.pm module is.

Here is where I am at now:
`ora2pg -c /apps/opt/postgres/ora2pg.conf   -t TABLE      -o tables.sql      -b /apps/opt/postgres/oracle_export -l /apps/opt/postgres/oracle_export/tables.log`

```
install_driver(Oracle) failed: Can't locate DBD/Oracle.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at (eval 13) line 3.
Perhaps the DBD::Oracle perl module hasn't been fully installed,
or perhaps the capitalisation of 'Oracle' isn't right.
Available drivers: DBM, ExampleP, File, Gofer, Proxy, Sponge.
 at /usr/local/share/perl5/Ora2Pg.pm line 1633.

```
Oracle.pm is located at: /usr/lib64/perl5/vendor_perl/Oracle.pm
which is at the @INC locations

**Comment by MichaelDBA** [comment]
jeeesh, after scrounging around, I finally got it working.  I really can't say what fixed it except I finally got this documented section to work:
[#perl -MCPAN -e shell
cpan> get DBD::Oracle
cpan> quit
cd ~/.cpan/build/DBD-Oracle*
export LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client64/lib
export ORACLE_HOME=/usr/lib/oracle/11.2/client64
perl Makefile.PL
make
make install](url)

**Comment by darold** [comment]
Thanks Michael, I will add your command to the documentation for an install using cpan
