### ISSUE TITLE
COPY bug with TRUNCATE_TABLE option

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#884]
If you turn on TRUNCATE_TABLE option, the resulting output file is incorrect because it places the TRUNCATE command BEFORE the SET search_path command.  

```
TRUNCATE TABLE rehome_migration_ord;
SET search_path = localds;

COPY rehome_migration_ord (nbr_order,typ_order,idx_org_order,typ_migration,qty_tnb,flg_exp_tps,dtx_submitted,sys_submitted,dtx_upd_last,sys_upd_last) FROM STDIN;
000000027147    RAM 
```

It should be in this order:
```
SET search_path = localds;
TRUNCATE TABLE rehome_migration_ord;
```

The only way it would work otherwise is if I change the default search_path for the user, which I don't want to do.

**Comment by darold** [comment]
Thanks Michael, commit 4d52e01 fixes this issue.
