### ISSUE TITLE
Data download: Wide Character in print...

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#885]
During data download, I get this message.  Is this an error?

```
Wide character in print at /usr/lib64/perl5/IO/Handle.pm line 417.I_911_VALI_ORDER_COMMENTS (13541 recs/sec)
[====>                    ]  2200000/11209688 rows (19.6%) Table EI_911_VALI_ORDER_COMMENTS (13414 recs/sec)

```

**Comment by darold** [comment]
I assume that you are using latest development code. This is a warning but this mean that an output is not well supporting multibytes. What is the value of BINMODE?

You can try executing ora2pg using the following command:
```
perl -Mutf8 -CS /usr/local/bin/ora2pg ....
```
then verify that your data are well encoded.

**Comment by MichaelDBA** [comment]
BINMODE is commented out in ora2pg.conf  Looks like it defaults to UTF8.
