### ISSUE TITLE
CONSTRAINT bug

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#886]
I have an oracle column def and constraint like this:

```
"IDN_PVD_SRV" VARCHAR2(4) NOT NULL ENABLE,
 CONSTRAINT "SYS_C001286" CHECK (idn_pvd_srv IN (7227, 7228, 7229)) ENABLE,
```
In the conversion to PG, the constraint is messed up because Oracle can handle conversion from int to string implicitly but not PG.

```
idn_pvd_srv | character varying(4)     |           | not null |
ALTER TABLE sdmr_car_ppt ADD CONSTRAINT sdmr_car_ppt_csn01 CHECK (idn_pvd_srv IN (7227, 7228, 7229));
```

The fix can be a cast or enclosing the values in the list with single quotes:
`ALTER TABLE sdmr_car_ppt ADD CONSTRAINT sdmr_car_ppt_csn01 CHECK (idn_pvd_srv IN ('7227', '7228', '7229'));
`

Even though it is a simple fix, it may not be so easily done programmatically.  Good Luck!

**Comment by MichaelDBA** [comment]
I've had second thoughts about this.  I think this is really a coding bug.  Whoever created these CHECK constraints was lazy and used number format (no ticks) instead of string format (ticks) when creating the CHECK CONSTRAINTS in oracle since Oracle is forgiving and will do automatic type casting for you.  

Please confirm and close this as a bug if you think so.  Otherwise, you are adding logic to compensate for bad CHECK CONSTRAINTS coding.

As much as I would like you doing the dirty work for me, I think your time is better spent fixing real ORA2PG bugs and not sloppy ORACLE coding.

**Comment by darold** [comment]
Actually fixing this particular case can be easy but producing a generic code is lot of work for probably not fully fix the problem. Better is to rewrite the generated code by hand (the application will probably have the same problem) or create an implicit cast between both data types in PostgreSQL.
