### ISSUE TITLE
DBD:Oracle installation fails at "make"

### ISSUE THREAD

**Issue by kirandba-hub** [darold/ora2pg#887]
Hi,

I am getting below error while doing "make" as part of DBD:Oracle installation

[root@www DBD-Oracle-1.80-1]# make
rm -f blib/arch/auto/DBD/Oracle/Oracle.so
LD_RUN_PATH="/u01/app/oracle/product/12.1.0/dbhome_1/lib:/lib64" gcc  -lpthread -shared -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -L/usr/local/lib -fstack-protector-strong Oracle.o dbdimp.o oci8.o  -o blib/arch/auto/DBD/Oracle/Oracle.so  \
   -L/u01/app/oracle/product/12.1.0/dbhome_1/lib -lclntsh -ldl -lm -lpthread -lnsl -lirc -limf -lirc -lrt -lsvml   \

/usr/bin/ld: cannot find -lnsl
collect2: error: ld returned 1 exit status
make: *** [Makefile:549: blib/arch/auto/DBD/Oracle/Oracle.so] Error 1

Can let me know where i am missing exactly or any solution for this error

**Comment by darold** [comment]
I guess that package libnsl is not installed.

**Comment by kirandba-hub** [comment]
Thanks darold!!
Issue was solved,i installed the package
