### ISSUE TITLE
Error during data insert

### ISSUE THREAD

**Issue by ddmo** [darold/ora2pg#888]
Hi, I've got an error during data import in postgreSQL 10.
This is a row example:

`6014234 3393669847      P2307201609451CC6014234 \N      soldaini        2016-07-18 09:50:08.733000      2016-07-23 09:55:00.000000      2016-07-23 09:45:00.000000      \N      \N      yuri.soldaini@gmail.com \N      mmorrone        \N      \N      \N      \N      yuri    \N      2       \N      1       \N      2       3691035 1`

and the error is: psql:./data/data.sql:33068: **invalid command \N**

I run the suggested command to extract data: 

`ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg.conf`

Any suggestions?

Thanks a lot!
Stefano

**Comment by darold** [comment]
Are you using latest development code?
```
wget https://github.com/darold/ora2pg/archive/master.zip
unzip master.zip
cd ora2pg-master/
make
sudo make install
```

**Comment by robindabird** [comment]
Hello,

I have the same problem and used the latest development code.

**Comment by robindabird** [comment]
Hello,

My problem was in the file ./data/data.sql.

I just ran this command and just figured what was the errors along the way;
`psql -v ON_ERROR_STOP=1 -h <your_hostname> -U <your_user> -d <your_database> -f ./data/data.sql`

**Comment by darold** [comment]
Closing, not reproducible.
