### ISSUE TITLE
Column names of a view does not get exported 

### ISSUE THREAD

**Issue by smil2k** [darold/ora2pg#891]
In case a view contains a select which contains function calls like this:

select ... , TRUNC(dep_sched_dt) as dep_day_sched, ... from bla

Then the DDL of the view omits the column name and gets exported like this:

select ... , TRUNC(dep_sched_dt), ... from bla

In this case the resulting view will have different column names.

**Comment by mkgrgis** [comment]
Oracle view can have both general aliases and simple aliases in `SELECT`
`CREATE VIEW x  (a1, a2, a3...) AS SELECT b1 AS c3, b2 AS c4, b3 AS c1 ...`
It seems, general aliases (a1, a2...) is first source for export to PostgreSQL, but aliases from `SELECT` (c1, c2...) can be lost. It's secondary source for naming.

**Comment by darold** [comment]
The problem might have been solved as I can not reproduce it. Oracle view:
```
 SQL> CREATE OR REPLACE VIEW test_alias_column3 (a1, a2, a3) AS SELECT trunc(HIRE_DATE) as a1, FIRST_NAME as a2, LAST_NAME as a3 FROM EMPLOYEES;
```
is translated as
```
CREATE OR REPLACE VIEW test_alias_column3 (a1, a2, a3) AS SELECT  date_trunc('day', HIRE_DATE) as a1, FIRST_NAME as a2, LAST_NAME as a3  FROM EMPLOYEES;
```
Closing
