### ISSUE TITLE
Idea usage of \ir instead of \i

### ISSUE THREAD

**Issue by smil2k** [darold/ora2pg#892]
Exports using file_per_table get includes with \i using absolute path. 

eg. my docker container installation exports under /data. This makes the output location specific.

PSQL supports another include command called \ir which includes files relative from the script. This would make such exports portable.

**Comment by SebAlbert** [comment]
I second this; I have already written a postprocessing for this in Perl to rewrite from \i to \ir, since I usually run ora2pg in a temporary directory before persisting the output. Best thing would be to fix this in ora2pg itself.

**Comment by darold** [comment]
Commit  b462819 adds -r | --relative command line option and PSQL_RELATIVE_PATH configuration directive. Enabling use \ir instead of \i
