### ISSUE TITLE
Question for CRLF

### ISSUE THREAD

**Issue by CHO-Hoon-Yeon** [darold/ora2pg#893]
Hi.
I'm curious about CRLF and character type.
If i want to migrate A To B, am i must worry about CRLF Problem??
(A : **Windows Server,** character type is SJIS(japanese))
(B+ **Linux** Cent Os, character type is maybe SJIS)

**Comment by darold** [comment]
Hi,

If you are talking about data migration, no you don't have to take care of that Ora2Pg will not change your data. About character set default is to use UTF8, but you can use NLS_LANG, NLS_CHAR and CLIENT_ENCODING configuration directives in ora2pg.conf to customize your need.

If you are talking about CRLF in PL/SQL to PLPGSQL code conversion it depends where you are using Ora2Pg. Perl adapt the line terminator following the system.

**Comment by CHO-Hoon-Yeon** [comment]
OK. I really appreciate that answer.
1 more question. 
If i use Ora2pg on Windows(SJIS) Side for make SQL query(INSERT query) , 
And Insert to my backup Window system. 
After that, Using Ora2pg for migrate them to Linux Cent Os, am i should worry about CRLF and character problem?

**Comment by darold** [comment]
As I've told you data export is not concerned by CRLF, they are just part of your data and if Ora2PG change them this will be a corruption of data. The only thing is that Ora2Pg escape these characters for insert, your CRLF will be translated into \r\n in the INSERT statement as I guess that you have STANDARD_CONFORMING_STRINGS  enabled corresponding to your postgresql.conf setting. This is mandatory at insert time but internally your data will have the right CRLF.

I would recommend you to use your Linux box for the migration for performances reasons and also the Windows port is probably not as tested as on Linux. Also using COPY export is far more performant than INSERT, you should use it.

**Comment by CHO-Hoon-Yeon** [comment]
Really appreciate your answers.
and that really helps.
