### ISSUE TITLE
Incorrect Table count and Synonyms in Ora2pg Assessment Report

### ISSUE THREAD

**Issue by Swapnil24051992** [darold/ora2pg#894]
Hi,

I am running Ora2pg tool for about 324 oracle schemas to generate assessment export for PostgreSQL.
The issue i am facing is that despite databases having tables in it , report shows 0 tables in every report.
Also other issue is that if in case database does not have any synonyms then too it shows 374 synonyms count by default in every report.

**Comment by darold** [comment]
You are not using the right schema name, see SCHEMA configuration directive.
