### ISSUE TITLE
Two Objects with same name

### ISSUE THREAD

**Issue by egaultier** [darold/ora2pg#897]
Hi

On Oracle database, it possible to have 2 differents objects with same name !!!!!!!!

Example : 
1 table named : test
1 index named : test

On postgres, it's not possible.

can you handle this case.

Thx

Emmanuel

**Comment by darold** [comment]
This case is already handled with configuration directive INDEXES_SUFFIX.

**Comment by egaultier** [comment]
Ok Thank you for you answer.
