### ISSUE TITLE
date conversion error

### ISSUE THREAD

**Issue by egaultier** [darold/ora2pg#898]
Hello 

Database source : Oracle 11.2.0.4
NLS_LANG        AMERICAN_AMERICA.WE8MSWIN1252

In my Oracle database, In table DIM_PRODUCTION, the PROD_DAT_CREAT column is a Date. 
In one record, this date column have 0001-01-01 value. View attach file oracle_table_source.docx to table definition and screenshoot with the record.

[oracle_Table_source.docx] (https://github.com/darold/ora2pg/files/4804376/oracle_Table_source.docx)

When I export data in sql file, This value is convert to 8080-80-80 00:00:00. 
![image](https://user-images.githubusercontent.com/67147948/85139341-9117d580-b244-11ea-9365-8c5c2430784c.png)

I don't understand why ora2pg make this conversion;

Have you an idea to help me ?

Thank you for your help

Emmanuel

**Comment by darold** [comment]
This look to be a corrupted data, Ora2Pg just reports you what Oracle is returning using setting `NLS_DATE_FORMAT YYYY-MM-DD HH24:MI:SS`.

If Ora2Pg reports you `8080-80-80 00:00:00` this is actually what Oracle sent. Some basic tests with Ora2Pg:
```
SQL> CREATE TABLE test_date (
        id NUMBER,
        start_date date
);

INSERT INTO test_date VALUES (1, TO_DATE('0001/01/01 00:00:00', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO test_date VALUES (1, TO_DATE('31.12.9999 23:59:59', 'dd.mm.yyyy hh24:mi:ss'));
```
then data exported by Ora2Pg:
```
COPY test_date (id,start_date) FROM STDIN;
1       0001-01-01 00:00:00
1       9999-12-31 23:59:59
\.
```
The query used internally by Ora2Pg to retrieve the data was:
```
SELECT "ID","START_DATE" FROM "HR"."TEST_DATE" a
```
I can not do more simple. I think you should see the raw content of the column in Oracle to see what's going wrong.

I guess that your tool is using TO_CHAR() to retrieve the date which might transform it at '0001-01-01', sqllplus is also using this magic data transformation to avoid returning an error.

**Comment by darold** [comment]
As an example of Oracle data corruption you can look at issue #812

**Comment by egaultier** [comment]
Hello 

On oracle Database, the value in date column is wrong. The dev team found and fixed the error.

Thank you for your help.
