### ISSUE TITLE
Issue in NOSCALE in table schema

### ISSUE THREAD

**Issue by deepakp555** [darold/ora2pg#899]
In converted table schema if NOSCALE keyword exists,that schema does not runs in postgresql How to resolve this issue.

**Comment by darold** [comment]
Do you have the Oracle source code with the NOSCALE keyword.

**Comment by deepakp555** [comment]
Oracle Schema 
------------------------
 CREATE TABLE "SANDEEP"."CONTACTS" 
   (	"CONTACT_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 320 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(20 BYTE), 
	"CUSTOMER_ID" NUMBER, 
	 PRIMARY KEY ("CONTACT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_CONTACTS_CUSTOMERS" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "SANDEEP"."CUSTOMERS" ("CUSTOMER_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

Ora2PG converted schema :
-------------------------------
CREATE TABLE contacts (
	contact_id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 320 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NO CYCLE CACHE 20  SCALE_FLAG: N EXTEND_FLAG: N SESSION_FLAG: N KEEP_VALUE: N),
	first_name varchar(255) NOT NULL,
	last_name varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	phone varchar(20),
	customer_id bigint
) ;

**Comment by deepakp555** [comment]
The above ora2pg converted schema is not executed in postgresql.

**Comment by darold** [comment]
Ok, I was not aware of that additional keyword, will fix it. What version of Oracle?

**Comment by deepakp555** [comment]
Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production

**Comment by darold** [comment]
Commit 37b6ddd fixe this issue for translation of an input file. For Oracle database export it still need to be tested but I don't have a 18c so I can not test it at the moment.
