### ISSUE TITLE
Mismatch in index counts in assessment report

### ISSUE THREAD

**Issue by deepakp555** [darold/ora2pg#900]
When we have assessed an oracle database,we found total index in assessment report is # but in our database index count is different.
Please suggest the actual reason of differences.

We found the indexes count using below query:

Select count(*) from objects where object_Type = 'INDEX' and OWNER = 'XXXXXX'

**Comment by darold** [comment]
In the report detail, which you might read, the following is written about INDEX:
```
N index(es) are concerned by the export, others are automatically generated and will
do so on PostgreSQL. N bitmap index(es). N b-tree index(es). N reversed b-tree index(es)
Note that bitmap index(es) will be exported as b-tree index(es) if any. Cluster, domain,
bitmap join and IOT indexes will not be exported at all. Reverse indexes are not exported
too, you may use a trigram-based index (see pg_trgm) or a reverse() function based index
and search.
```
There are also indexes that are related to constraints and are automatically generated by PostgreSQL which are not part of the export. But you already know that.

I don't know what other explanation you expect.

**Comment by deepakp555** [comment]
OK, thanks for quick response.
Here i am explaining my scenario.
I have scanned one schema from ora2pg and in the assessment report i found  in  total index count on that schema is 5. When i executed below queries  it is giving 8 index count.

"Select * from all_objects where object_type = 'INDEX' and owner = 'Schema_Name' and generated = 'N' order by object_name"

"select  * from DBA_INDEXES where OWNER='Schema_Name
[UCProj1_SANDEEP_AzurePostgreSQL.zip](https://github.com/darold/ora2pg/files/4814276/UCProj1_SANDEEP_AzurePostgreSQL.zip)

' and index_type = 'NORMAL' and generated = 'N' "

So can you please explain why this difference we are getting.

**Comment by darold** [comment]
What does this query returns?
```
SELECT DISTINCT COUNT(*)
FROM ALL_IND_COLUMNS A
JOIN ALL_INDEXES B ON (B.INDEX_NAME=A.INDEX_NAME AND B.OWNER=A.INDEX_OWNER)
WHERE  B.TEMPORARY <> 'Y' AND A.INDEX_OWNER = 'Schema_Name' AND B.GENERATED = 'N' 
```
Also if you look at the missing index what kind/type of indexes are they?

**Comment by deepakp555** [comment]
The above query returns 11.

Also for moreclarification i have attached the results of  above two queries.
[Queries ResultS.xlsx](https://github.com/darold/ora2pg/files/4814987/Queries.ResultS.xlsx)

Thanks for support.

**Comment by darold** [comment]
Tables that match the following regexp are rejected because they are considered as Oracle internal table.
```
  'USLOG\$_.*', 'MLOG\$_.*', 'RUPD\$_.*', 'MDXT_.*', 'MDRT_.*', 'MDRS_.*', 'DR\$.*', 'CLI_SWP\$.*', 'LOGMNR\$.*', 'REPCAT\$.*', 'JAVA\$.*', 'AQ\$.*', 'BIN\$.*', 'SDO_GR_.*', '.*\$JAVA\$.*', 'PROF\$.*', 'TOAD_PLAN_.*', 'SYS_.*\$', 'QUEST_SL_.*'
```
and so on all indexes related to these tables. In your query results this is all the indexes with the $ sign.
