### ISSUE TITLE
Can we get the line nos. where the issue occurs in oracle procedure.

### ISSUE THREAD

**Issue by deepakp555** [darold/ora2pg#901]
When we assess one database from ora2pg , In "Details of cost assessment per function" section  of the assessment report , we found "CONCAT","TG_OP"  with occurrence and estimation but other details like line number is not there which will be more useful for conversion.

**Comment by darold** [comment]
This is a very limited interest for me, using search when editing the function is faster than having the line number if you have several occurrence of the keyword. However, the line number is an information that I don't have as the search of the problematic code is done through regexp into the whole code not line by line.
