### ISSUE TITLE
MySQL export is failing

### ISSUE THREAD

**Issue by venkatsusarla** [darold/ora2pg#902]
Hi Darold,
I hope you are doing well.

I am contacting you with regards to an issue I am facing using ora2pg for MySQL, where I am trying to export a database of size 1.5tb to migrate it to PostgreSQL.

Issues I am Facing:
- When I try to use oracle_copies, jobs, and defined_pk to fasten the export it fails with below error
   DBD::mysql:: st execute failed: Lost connection to MySQL server during query at <location>/ora2pg-20.0/lib/Ora2Pg/MySQL.pm line 305.
DBD::mysql::st execute failed:Lost connection to MySQL server during query at <location>/ora2pg-20.0/lib/Ora2Pg/MySQL.pm line 305.
.
.
DBD::mysql::st execute failed:Lost connection to MySQL has gone away at <location>/ora2pg-20.0/lib/Ora2Pg/MySQL.pm line 1709.

- When I run the export with parallel options it ran for some time and then failed with the below error.
DBD::mysql::st fetchrow failed:Lost connection to MySQL server during query at <location>/ora2pg-20.0/lib/Ora2Pg.pm line 14269.

- SHOW_VERSION and structure export works well with issues.

I appreciate your help in solving this issue.

Regards,
Venkat

**Comment by darold** [comment]
I don't know what happen, perhaps a statement/session timeout at MySQL level?

**Comment by venkatsusarla** [comment]
Thanks for the reply. Could he a session terminated at MySQL end.
How can we speed up the export?,as it fails when we try to put the job in parallel.Oracle_copies,defined_pk nothing works for MySQL.

**Comment by darold** [comment]
Why Oracle_copies+defined_pk doesn't work? Do you have an error message? Perhaps the SQL syntax is not supported, let me know so I can check that.

For the moment you should use `-P 4 -j 2` to parallelize tables export on 4 cpu and import data to PG using 2 cores per process, which mean that it will use 8 processes/cpu at a total.
