### ISSUE TITLE
Import data Failed with ERROR:  invalid byte sequence for encoding "UTF8"

### ISSUE THREAD

**Issue by egaultier** [darold/ora2pg#903]
Hi

informations : 
Nls information Oracle database : 

![image](https://user-images.githubusercontent.com/67147948/85408220-87ec7880-b564-11ea-968a-a53232cf03b5.png)

Oracle table DIM_SITE 

![image](https://user-images.githubusercontent.com/67147948/85409553-3e049200-b566-11ea-9179-ba3d517b4b0d.png)

show ENCODING :

![image](https://user-images.githubusercontent.com/67147948/85407868-0f85b780-b564-11ea-9543-fc004d295a4e.png)

Pg 12.3 database : 

createdb -E UTF8 --owner sisadm sisadwhp 

Pg DIM_SITE table : 

![image](https://user-images.githubusercontent.com/67147948/85409687-68eee600-b566-11ea-889f-7a73558c9b6a.png)

When I want import data

![image](https://user-images.githubusercontent.com/67147948/85408074-596e9d80-b564-11ea-870a-79e1fa61351a.png)

Thank you for your help.

Emmanuel

**Comment by darold** [comment]
Does your data file `./data/DIM_SITE.data.sql` has the following on top?

```
SET client_encoding TO 'WIN1252';
```

**Comment by egaultier** [comment]
Don't have.

![image](https://user-images.githubusercontent.com/67147948/85412840-51196100-b56a-11ea-8d0d-00cb67b29812.png)

If I add, this OK. 

This line must be added manually in all sql files ?

Emmanuel

**Comment by darold** [comment]
I have remove the image as it contains some information :-)

Yes you shoud add add them but normally it is present in the file, I guess they have been edited or you are using a very old ora2pg version.

**Comment by egaultier** [comment]
I downloaded ora2pg-master.zip last week.

![image](https://user-images.githubusercontent.com/67147948/85415312-78256200-b56d-11ea-80a3-3fa0fba21877.png)

**Comment by egaultier** [comment]
In the schema (tables, views ...) sql file, this line exist.

**Comment by darold** [comment]
Ok, got it, this is a regression I will fix it.

**Comment by egaultier** [comment]
Hello

I Downloaded today, the lastest version of ora2pg.master file
The regression still seems present.

Thank for your help.

**Comment by darold** [comment]
Commit 21e2ae0 should fix this issue, sorry for the delay.

**Comment by egaultier** [comment]
Hello

Thank you for this commit. 
The bug no longer exists.

Thank you for the work done on this wonderful project.

Emmanuel
