### ISSUE TITLE
COPY STDOUT confusion

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#904]
I am confused about the STDOUT of the copy command:

```
[========================>] 18629/18588 rows (100.2%) Table OSSR_DLV_ADR (3 sec., 6209 recs/sec)
[=======================> ] 46588/46624 rows (99.9%) Table OSSR_DIR_NME (4 sec., 11647 recs/sec)
[========================>] 1015/1015 rows (100.0%) Table OSSR_LNE_SVF_PAM (1 sec., 1015 recs/sec)
```
What do the first 2 lines signify?  What do the pair of numbers separated by a forward slash mean?

I am guessing that the first number is how many rows actually returned, and the second number is the exact or approximate estimate of the number of rows in the table.  Otherwise, if the first number is greater than the second number, so that I get a 100.2% return on rows, what the heck does that mean?  Likewise, if the first number is less than the second number does that mean an error occurred?  If so there is nothing in the log to indicate an error, the log file is empty.

**Comment by darold** [comment]
Number of row processed / Total number of row in the table.

In regard to the fact that  "Total number of row in the table" is computed from the statistics cache, so to have an accurate number you need to have fresh statistics computed on the table. Or if you want I think there is a configuration direct to get the total from a count(*) but it is slower. Also perhaps it is only limited to action TEST.

**Comment by MichaelDBA** [comment]
Thanks!
