### ISSUE TITLE
How to run oracle2pg as "SYS as SYSDBA"

### ISSUE THREAD

**Issue by gdimopoulosg** [darold/ora2pg#907]
Hi ,
While running ora2pg as  oracle user SYSTEM, I am getting  the following error:

DBD ERROR: error possibly near <*> indicator at char 49 in 'SELECT DISTINCT c.SHAPE.SDO_GTYPE FROM NRM_CAVES.<*>LOCATIONS c WHERE ROWNUM < 50000') [for Statement "SELECT DISTINCT c.SHAPE.SDO_GTYPE FROM NRM_CAVES.LOCATIONS c WHERE ROWNUM < 50000"] at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 9408.
...
Aborting export...

If I run "SELECT DISTINCT ... "oracle statement  AS SYSTEM in SQL*PLUS it fails, but when I run it as SYS as SYSDBA works OK.
I need to run ora2pg as SYS.    Is any solution on this ?   I need help and I cannot find in anything in Web.
Please help...

**Comment by darold** [comment]
I don't think it is possible to connect  remotely using the SYS user. I guess this is a question of privileges, you should fix that in Oracle to allow SYSTEM to look at this table but I'm surprised normally SYSTEM is not subject to such restriction.

**Comment by gdimopoulosg** [comment]
Thank you very much for your help!
My issue has to do something withOracle VDP policy.

**Comment by gp4git** [comment]
Just for the record, if you need to connect ***remotely*** as sysdba to your Oracle instance,
you should use the following ORACLE_DSN syntax with ora2pg :
dbi:Oracle(Username => sys, Password => <your_pwd>, ora_session_mode => 2):host=<your_host>;sid=<sid>;port=<port>
Note, that you will also need to set the TRANSACTION directive to a value different from serializable.

Regards
