### ISSUE TITLE
Oracle procedure getting migrated as Postgres Function

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#908]
When I try to migrate Oracle procedure to PostgreSQL, it is getting converted as FUNCTION instead of PROCEDURE

I am currently version 20 of OraPg and have given option PG_VERSION 11/12 in conf file but still converting as FUNCTION, please help me in resolving this issue

**Comment by darold** [comment]
Remove any PG_SUPPORTS_PROCEDURE from your ora2pg.conf and upgrade to latest development code.

**Comment by naveenjul29** [comment]
I really appreciate your quick response. I commeneted PG_SUPPORTS_PROCEDURE in ora2pg.conf file. I am attaching you the ora2pg version screenshot and ora2pg.conf file for your reference. Oracle version is 12c and PostgreSQL version is 12. Please help me in resolving the issue.

[ora2pg.conf.txt](https://github.com/darold/ora2pg/files/4852577/ora2pg.conf.txt)
![ora2pg Version](https://user-images.githubusercontent.com/67134199/86139536-7d565400-bb0d-11ea-9a04-9de259e4cd2c.PNG)

**Comment by naveenjul29** [comment]
Issue is still there. Please help me in resolving the issue.

Thanks & Regards
Naveen

**Comment by darold** [comment]
I would like to help more but actually unless upgrading to latest development code and be sure you are using it I have no idea of what happen to your installation. Here is what happen when I migrate the procedure from my test database:
```
SQL> SELECT OBJECT_NAME FROM ALL_OBJECTS WHERE OBJECT_TYPE = 'PROCEDURE' AND OWNER = 'HR';

OBJECT_NAME
------------------------------
SECURE_DML
ADD_JOB_HISTORY
INCREASE_SAL_COMM
GET_TIME
```
exporting the procedures only:
```
$ ora2pg -p -t PROCEDURE -o procedure.sql -b ./schema/procedures -c ./config/ora2pg.conf
[========================>] 4/4 procedures (100.0%) end of procedures export. 
```
and looking at content:
```
$ tree schema/procedures/
schema/procedures/
├── ADD_JOB_HISTORY_procedure.sql
├── GET_TIME_procedure.sql
├── INCREASE_SAL_COMM_procedure.sql
├── procedure.sql
└── SECURE_DML_procedure.sql

$ cat schema/procedures/SECURE_DML_procedure.sql
[...
CREATE OR REPLACE PROCEDURE "HR"."secure_dml" () AS $body$
BEGIN
  IF TO_CHAR(clock_timestamp(), 'HH24:MI') NOT BETWEEN '08:00' AND '18:00'
        OR TO_CHAR(clock_timestamp(), 'DY') IN ('SAT', 'SUN') THEN
	RAISE EXCEPTION '%', 'You may only make changes during normal office hours' USING ERRCODE = '45205';
  END IF;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE "HR"."secure_dml" () FROM PUBLIC;
```
We have a CREATE PROCEDURE statement.

To obtain latest development code, download https://github.com/darold/ora2pg/archive/master.zip then on Windows:
```
unzip master.zip
cd ora2pg-master/
perl Makefile.PL
dmake
dmake install
```

**Comment by naveenjul29** [comment]
sure, I will try and let you know. Thank you for all your help !!

**Comment by NishanthBejgam** [comment]
I got up with the same issue and it got resolved by procuring the master code from above link, thanks daroid.
