### ISSUE TITLE
Support for Generated Columns

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [darold/ora2pg#909]
Recently I tried to migrate an Oracle DB to PostgreSQL. The Oracle database has a generated column. But the ora2pg just `converted this as normal varchar column`. Since **Pg12** we can use generated columns.

It would be great if we have support for this.

And data export from Oracle (via COPY) is also included in the generated column. We can't restore the dump if the dump file has value for generated columns.

```
ERROR:  column "call_status" is a generated column
DETAIL:  Generated columns cannot be used in COPY.
```

**Comment by darold** [comment]
Yes, this problem has already been reported in #862, unfortunately I still not had the time to work on it.

**Comment by BhuviTheDataGuy** [comment]
Ok got it.

While exporting the data from Oracle can I mention specific columns? 
Like if a table has 3 columns (id, name, address) I want to export only id and name columns.

Is this possible?

**Comment by darold** [comment]
Use latest development code (`git clone` or `wget https://github.com/darold/ora2pg/archive/master.zip`), IDENTITY columns are fully supported.

Oracle code:

```
CREATE  TABLE identity_test3  (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 10  INCREMENT BY 10,
    lbl VARCHAR2(100) not null
);
INSERT INTO identity_test3(lbl)
VALUES('Oracle identity column: ON NULL, START WITH and INCREMENT BY option');
```
which is exported by Ora2Pg as:
```
CREATE TABLE identity_test3 (
        id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 10 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20),
        lbl varchar(100) NOT NULL
) ;
```
and data from this table:
```
COPY identity_test3 (id,lbl) FROM STDIN;
10      Oracle identity column: ON NULL, START WITH and INCREMENT BY option
\.
```

**Comment by BhuviTheDataGuy** [comment]
Oh nice. I'll try iti
