### ISSUE TITLE
how to migrate user lobs into PostgreSQL

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#910]
I installed Oracle Sample Schemas HR, OE, PM, IX and SH. I am having issues with lob objects migration to postgreSQL. Can you please help me on this.
![User Lobs](https://user-images.githubusercontent.com/67134199/86533254-781e4e00-beed-11ea-8c4f-b00c0fd7c858.png)

**Comment by darold** [comment]
Don't know what issue you are facing but CLOBs are exported as text and BLOB as bytea.

**Comment by naveenjul29** [comment]
Thank you Darold for your quick response !!
