### ISSUE TITLE
Extract Data from CLOB column with 0 value in oracle to postgresql using ora2pg Tool

### ISSUE THREAD

**Issue by eal-appeleon** [darold/ora2pg#913]
i'm facing a problem by the migration of oracle 11 & 19c to postgresql 11 database using ora2pg Tool. 
wenn i export clob data type with 0 value using ora2pg i get Null value instead of 0 in postgresql.

I treid to set the parameters EMPTY_LOB_NULL and NULL_EQUAL_EMPTY in config file to 1. But i still get the same result.

Can anyone help me?!! thank you in advance

**Comment by darold** [comment]
Upgrade to latest development code, commit 9594d50 solves this issue.

**Comment by eal-appeleon** [comment]
> Upgrade to latest development code, commit [9594d50](https://github.com/darold/ora2pg/commit/9594d50e05fa58c20ebb937e45c52adcff5355c8) solves this issue.

thank you its works
