### ISSUE TITLE
migrate object views into postgresql

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#917]
I am trying to migrate the below view to PostgreSQL

CREATE OR REPLACE FORCE EDITIONABLE VIEW "OT"."EMP_DEPT_VIEW" ("EMPNO", "ENAME", "JOB", "EDEPT") AS 
SELECT  empno, ename, job, MAKE_REF(dept_ext_view, deptno)
FROM    employee;

Ora2pg tool migrated the view as below:
CREATE OR REPLACE VIEW emp_dept_view (empno, ename, job, edept) AS SELECT   empno, ename, job, MAKE_REF(dept_ext_view, deptno)
FROM    employee;

Below are my concerns:

1.	MAKE_REF is built-in function in oracle which is not there in PostgreSQL.
2.	DEPT_EXT_VIEW is a object view.

Below is the view definition of DEPT_EXT_VIEW in Oracle

CREATE OR REPLACE FORCE EDITIONABLE VIEW "OT"."DEPT_EXT_VIEW" OF "OT"."DEPT_T"
WITH OBJECT IDENTIFIER (deptno) AS 
SELECT  d.deptno, d.dname, d.loc
FROM    department d;

Ora2pg tool migrated the view as below:
CREATE OR REPLACE VIEW dept_ext_view (deptno, dname, loc) AS SELECT   d.deptno, d.dname, d.loc
FROM  department d;

I am getting errors while testing these 2 views in PostgreSQL. can you please help me on this?

**Comment by naveenjul29** [comment]
Darold, can you please help me on this?

**Comment by darold** [comment]
`MAKE_REF` and `CREATE VIEW OF typename` are not supported by PostgreSQL. You need to find a workaround.

**Comment by naveenjul29** [comment]
Thank you Dorald. Closing the request !!
