### ISSUE TITLE
ERROR:  column appears twice in primary key constraint

### ISSUE THREAD

**Issue by xpusostomos** [darold/ora2pg#918]
I'm using ora2pg to dump a big schema and it's creating this:

```
CREATE TABLE rank_references (
        rank_id numeric(38) NOT NULL,
        rank_abbrev varchar(25) NOT NULL,
        rank_name varchar(25) NOT NULL,
        rank_char varchar(2),
        rank_cultivar_ind char(1),
        rank_historic_ind char(1),
        rank_mandatory_ind char(1),
        rank_convert_name varchar(15),
        position smallint,
        uninomial_ind char(1),
        rank_visible_ind char(1),
        unranked_ind char(1)
) ;
CREATE INDEX rk_abbr_i ON rank_references (rank_abbrev, rank_abbrev, rank_abbrev, rank_abbrev);
ALTER TABLE rank_references ADD PRIMARY KEY (rank_id,rank_id,rank_id,rank_id);
```

As you can see there are duplicate column names in the index and key clauses. When I run it through psql, it naturally complains:

```
ERROR:  column "rank_id" appears twice in primary key constraint
LINE 1: ALTER TABLE rank_references ADD PRIMARY KEY (rank_id,rank_id...
```

another table also has a problem:

```
CREATE TABLE region (
        region_id bigint NOT NULL,
        country varchar(25),
        taxon_id bigint NOT NULL,
        flora_of varchar(25),
        code varchar(10) NOT NULL,
        region_code varchar(7),
        type varchar(25) NOT NULL,
        state_prov varchar(60),
        description varchar(255),
        district varchar(25),
        region_type varchar(10),
        cap_code varchar(3),
        create_by varchar(8),
        create_date timestamp,
        update_by varchar(8),
        update_date timestamp,
        state_abbreviation varchar(3),
        id integer NOT NULL
) ;
CREATE INDEX region_cap ON region (cap_code);
CREATE INDEX region_region_idx ON region (type, code);
CREATE INDEX region_state_abbrev_i ON region (state_abbreviation);
CREATE INDEX region_taxon_idx ON region (taxon_id);
ALTER TABLE region ADD PRIMARY KEY (id);
ALTER TABLE region ADD UNIQUE (region_code);
ALTER TABLE region ADD PRIMARY KEY (region_id);
```

Here it's adding 2 primary keys. The correct primary key is ID, and in fact region_id doesn't even exist in the table in Oracle.

Here is what seems to be happening... the database is a mess of dozens of schemas and thousands of tables. Because Ora2Pg doesn't allow you to specify multiple schemas, I was relying totally on ALLOW to pick out the tables I want. But it seems that in some other schemas there are some old version of tables, and Ora2Pg must be mashing together the table defintions from multiple schemas and coming up with a Frankenstein mixture of them all that can't work. I suggest Ora2Pg should report this as an error, and even better if it allows the SCHEMA parameter to narrow down what schemas you care about.

**Comment by darold** [comment]
Please post the Oracle description of the table with constraints so that I can reproduce it.

**Comment by xpusostomos** [comment]
Like I said, there are dozens of schemas here, and the only possible explanation for what is happening here are multiple schemas with the same table name. But which tables from which schemas its mashing together, I have no idea, and I have no idea how I'd discover that. But presumably you will reproduce it by having multiple schemas with the same table name. In the first case above, probably the same fields and indexes. In the latter case, probably different tables (same name), different fields with different primary keys.

**Comment by darold** [comment]
Hum, this could be an old problem already solved, are you using latest development code?

**Comment by xpusostomos** [comment]
Am using v20.0

**Comment by darold** [comment]
Lastest code can be obtained using:
```
wget https://github.com/darold/ora2pg/archive/master.zip
unzip master.zip
cd ora2pg-master/
perl Makefile.PL
make
sudo make install
```
let me know if the problem persist.
