### ISSUE TITLE
Can't connect Oracle database

### ISSUE THREAD

**Issue by aj286** [darold/ora2pg#920]
Hi I am running this command from Wwindows 64 bit 2012R2 server where full oracle database 12c, along with ora2pg, postgresql are installed. Here is the error I am getting:
DBI connect('host=10.250.208.58;sid=orclDartDev.PWCS.EDU;port=1521','system',...
) failed: ERROR OCIEnvNlsCreate. Check ORACLE_HOME (Linux) env var or PATH (Wind
ows) and or NLS settings, permissions, etc. at C:/Strawberry/perl/site/lib/Ora2P
g.pm line 1624.
FATAL: -1 ... ERROR OCIEnvNlsCreate. Check ORACLE_HOME (Linux) env var or PATH (
Windows) and or NLS settings, permissions, etc.
Aborting export...

I have the Oracle_home set as follows:
# Set the Oracle home directory
ORACLE_HOME E:\app\Oracle\product\12.1.0\dbhome_dev\BIN
# Set Oracle database connection (datasource, user, password)
ORACLE_DSN     dbi:Oracle:host=local host;sid=orclDartDev;port=1521

Please help where I am doing wrong.
Thanks
AJ

**Comment by darold** [comment]
I think the error message is clear: `ERROR OCIEnvNlsCreate. Check ORACLE_HOME (Linux) env var or PATH (
Windows)`

You have to set env var ORACLE_HOME which could be `E:\app\Oracle\product\12.1.0\dbhome_dev` and the path to the binaries into the PATH env var, which could be `E:\app\Oracle\product\12.1.0\dbhome_dev\bin` but I don't know exactly your pathes.

**Comment by aj286** [comment]
Hi Darold: Thank you so much. It worked. The path was same as you said. I just changed the Oracle_Home without the \bin.
Thank you.
How can I open that outputfile.sql in pgadmin 4 so that it creates all the tables?
Once again Thank you and Have a good weekend!!
Ajay

**Comment by darold** [comment]
Sorry but I can not provide support for pgadmin 4, you should ask to the right mailing list, see https://www.pgadmin.org/support/
