### ISSUE TITLE
Dumps EVERYTHING for TYPE=SEQUENCE or VIEW

### ISSUE THREAD

**Issue by xpusostomos** [darold/ora2pg#921]
if I have:
ALLOW MYTABLE
TYPE TABLE

then it only dumps the schema for MYTABLE. Great.

But if I have:
ALLOW MYTABLE
TYPE TABLE VIEW

then it dumps ALL tables and ALL VIEWS.
same thing if I have TYPE TABLE SEQUENCE.

Surely this must be a bug.

ora2pg --version reports 20.0 and I believe I'm using the version from a git pull.

**Comment by SebAlbert** [comment]
Well, unlike `ALLOW`, the configuration `TYPE` only allows one single value per ora2pg execution.

**Comment by xpusostomos** [comment]
Mmmm, how can that be when if you put multiple values in TYPE, it changes the behavior from creating one output.sql, to then creating a TABLE_output.sql, SEQUENCE_output.sql, VIEW_output.sql ? I mean, that behavior seems an indication that its accepted the values as correct and acting accordingly.

Also, I inherited an ora2pg.conf file someone else who was working on it from a couple of years ago, and that file which apparently worked, and had multiple values in TYPE.

**Comment by darold** [comment]
You can use multiple export type at a time for backward compatibility but it is not well supported as you have experienced and the recommended way is to execute ora2pg separately using the `-t` option to change the export type and `-b` option to move to a different output directory. I often think about removing this capability but it is usable if you don't used advanced filter like ALLOW  or EXCLUDE.

I would recommend you to have a look to the  `--init_project` option as it will generate an export all script that you can use to export an entire database. You can customize this shell script to match your need.
`

**Comment by xpusostomos** [comment]
Well.. all i can say is at the very least you should have massive and prominent warnings output, because i wasted a day trying to figure out what was wrong.

**Comment by darold** [comment]
Contributions are welcome.
