### ISSUE TITLE
Orafce installation issue

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#922]
I am going to through the below URL to install Orafce

https://info.crunchydata.com/blog/migrating-from-oracle-to-postgresql-questions-and-considerations#:~:text=Orafce%20is%20a%20useful%20extension,.com%2Forafce%2Forafce.

when I run the command **make all** in step 4, got the below error

**file.c:22:33: fatal error: access/htup_details.h: No such file or directory
 #include "access/htup_details.h"**

Please do the needful.

**Comment by okbob** [comment]
Hi

po 20. 7. 2020 v 8:50 odesílatel naveenjul29 <notifications@github.com>
napsal:

> I am going to through the below URL to install Orafce
>
>
> https://info.crunchydata.com/blog/migrating-from-oracle-to-postgresql-questions-and-considerations#:~:text=Orafce%20is%20a%20useful%20extension,.com%2Forafce%2Forafce
> .
>
> when I run the command *make all* in step 4, got the below error
>
>
> *file.c:22:33: fatal error: access/htup_details.h: No such file or
> directory #include "access/htup_details.h"*
>
> Please do the needful.
>
What is your version of Postgres? Maybe you have an old unsupported version.

Regards

Pavel

**Comment by naveenjul29** [comment]
PostgreSQL 12.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit

**Comment by okbob** [comment]
po 20. 7. 2020 v 9:18 odesílatel naveenjul29 <notifications@github.com>
napsal:

> PostgreSQL 12.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5
> 20150623 (Red Hat 4.8.5-39), 64-bit
>
Postgres 12 is supported. You should to check installed dev package for
Postgres Server

postgresql-server-devel

you should to run

pg_config

[pavel@nemesis ~]$ pg_config
BINDIR = /usr/local/pgsql/bin
DOCDIR = /usr/local/pgsql/share/doc
HTMLDIR = /usr/local/pgsql/share/doc
INCLUDEDIR = /usr/local/pgsql/include
PKGINCLUDEDIR = /usr/local/pgsql/include
INCLUDEDIR-SERVER = /usr/local/pgsql/include/server
LIBDIR = /usr/local/pgsql/lib
PKGLIBDIR = /usr/local/pgsql/lib
LOCALEDIR = /usr/local/pgsql/share/locale
MANDIR = /usr/local/pgsql/share/man
SHAREDIR = /usr/local/pgsql/share
SYSCONFDIR = /usr/local/pgsql/etc
PGXS = /usr/local/pgsql/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE =  '--enable-tap-tests' '--enable-debug' 'CFLAGS=-Wall
-Wmissing-prototypes -Wdeclaration-after-statement  -Wendif-labels
-Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv
-fexcess-precision=standard -g -O2 -Werror=switch' '--with-libxml'
'--with-python' '--enable-cassert'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith
-Wdeclaration-after-statement -Werror=vla -Wendif-labels
-Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type
-Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
-Wno-format-truncation -Wno-stringop-truncation -g -Wall
-Wmissing-prototypes -Wdeclaration-after-statement  -Wendif-labels
-Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv
-fexcess-precision=standard -g -O2 -Werror=switch
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed
-Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lpthread -lxml2 -lz -lreadline -lrt -ldl -lm
VERSION = PostgreSQL 14devel

Important field is a "INCLUDEDIR" = /usr/local/pgsql/include. Check if
requested header files are there

Pavel

**Comment by naveenjul29** [comment]
Thank you Pavel for quick response.

INCLUDEDIR field path is **/usr/include** in our system. And we do have the file in that location. still we are getting error.

as per the below screenshot, may be it is looking for **access** folder inside /usr/include path which we don't have
**#include "access/htup_details.h"**

Please suggest further on this.

**Comment by darold** [comment]
@naveenjul29 have you tried `sudo yum install orafce12` or `sudo apt install orafce`? Also note that this repository is dedicated to Ora2Pg, orafce is an other project and has a dedicated repository that you can find at https://github.com/orafce/orafce. Please do not mix everything, it is hard enough to maintain. However @okbob thanks for your answers ;-)

**Comment by naveenjul29** [comment]
I am sorry Darold. I will continue with orafce repository going forward.

**Comment by naveenjul29** [comment]
we tried sudo yum install orafce12 and still getting error

**Comment by okbob** [comment]
po 20. 7. 2020 v 10:46 odesílatel naveenjul29 <notifications@github.com>
napsal:

> we tried sudo yum install orafce12 and still getting error
>
What error?

**Comment by naveenjul29** [comment]
when we run **make all** command, got the below error:
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o file.o file.c
file.c:22:33: fatal error: access/htup_details.h: No such file or directory
 #include "access/htup_details.h"
                                 ^
compilation terminated.
make: *** [file.o] Error 1

**Comment by naveenjul29** [comment]
looping Saurabh @Saurabh-704 here ..

**Comment by darold** [comment]
I think that @okbob was talking about the yum install error.

**Comment by Saurabh-704** [comment]
ohh Sorry @okbob ...We didnt got any error while installing orafce12. 
What @naveenjul29 was trying to say that after installing that orafce12 also we are still getting error for that "make all" command.

**Comment by darold** [comment]
Well after installing orafce12 you don't need to reinstall it from source. In other terms when it has been installed using yum you can just start using it.

**Comment by Saurabh-704** [comment]
ok @darold  do I need to run the extension command also in postgresql?

**Comment by darold** [comment]
I think that you have the answer in your question. I'm closing this issue, we are far from an ora2pg issue.

**Comment by okbob** [comment]
po 20. 7. 2020 v 12:05 odesílatel saurabh Gupta <notifications@github.com>
napsal:

> ok @darold <https://github.com/darold> do I need to run the extension
> command also in postgresql?
>
sure. It should be executed every time once per database.
