### ISSUE TITLE
is there any option to generate Migration cost assessment for specific objects instead of all database objects?

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#924]
is there any option to generate Migration cost assessment for specific objects instead of all database objects?

**Comment by darold** [comment]
no

**Comment by naveenjul29** [comment]
I am exporting PROCEDURES and it is stuck. First of all, my Oracle connection is remote one and I have total 148 procedures in it. I executed the below command 4 hours back and still there no output.

call ora2pg -c ora2pg.conf -t PROCEDURE -o proc0724.sql -b schema/procedures/

How can we track the progress?

Thank you
Naveen

**Comment by naveenjul29** [comment]
also I am getting the result quickly when I run the below command

ora2pg -o ora2pg.conf -t SHOW_VERSION

**Result:**
HINT: you should activate USER_GRANTS for a connection without DBA privilege. Continuing with USER privilege.
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0

**Comment by darold** [comment]
Export of 148 procedures should not takes hours, just few minutes, I don't think the problem comes from Ora2Pg. If the value of ora2pg.conf TRANSACTION directive is `serializable` try to set it to `readonly`,

**Comment by naveenjul29** [comment]
sure Darold. Will try that option and let you know the status. Also, I would like to know if there is any option to track the progress?

**Comment by darold** [comment]
normally the progress bar is raised and you can see the progression.

**Comment by naveenjul29** [comment]
Thank you Darold for quick response.

I set theTRANSACTION directive to readonly but no luck. Procedure script is still running longer.

**Comment by darold** [comment]
I don't think the problem is related to Ora2Pg and don't know how to help more. If you can export the procedure as DDL in a SQL file you can give it to ora2pg and convert it localy, I guess it will not hang.  To convert a DDL file from Oracle use the -i option, for example: `ora2pg -c ora2pg.conf -t PROCEDURE -i oracle_proc_def.sql -b procedures/`

**Comment by naveenjul29** [comment]
sure Darold, I will try to export the procedure as DDL and let you know.

**Comment by naveenjul29** [comment]
Darold, I am using Oracle SQL Developer and generated DDL script for Oracle procedures and output is as below:

**C:\ora2pg\vmmig>ora2pg -c ebsora2pg.conf -t PROCEDURE -i export0727.sql  -b schema/procedures/
-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=MYIP;sid=SIDName

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;

[========================>] 0/0 procedures (100.0%) end of procedures export.
-- Nothing found of type PROCEDURE
Fixing function calls in output files...**

There are 100's of procedures but it is saying nothing found of type PROCEDUREs.

Please help  me further to resolve this issue.

Thank you
Naveen

**Comment by darold** [comment]
If possible send file export0727.sql to my private address < gilles AT darold DOT net > or at least one or two procedures from this file.

**Comment by naveenjul29** [comment]
Darold, I emailed you the code. Email subject line is **#924**

**Comment by darold** [comment]
Commit a2c5a42 solves the parsing issue, please use latest development code.

**Comment by naveenjul29** [comment]
sure Darold. I will use the latest development code and let you know the status.

**Comment by naveenjul29** [comment]
Thank you Dorald. Closing the request.
