### ISSUE TITLE
Getting psql authentication error while running the psql command

### ISSUE THREAD

**Issue by Saurabh-704** [darold/ora2pg#926]
Hello All!!
I am running the ora2pg tool in linux environment. I have exported the script using ora2pg tool, now I want to import it in psql database.
For this I have done changes in conf file. I have set PG_SCHEMA to db1
<img width="482" alt="l" src="https://user-images.githubusercontent.com/47383623/88913786-3e87fb00-d27f-11ea-89fe-0f59f645cafc.png">

And this is the screenshot of the command and output which I got :
<img width="749" alt="l2" src="https://user-images.githubusercontent.com/47383623/88914162-d4bc2100-d27f-11ea-93c2-9d34306d0b8b.png">

So can anyone help me like what I am missing or what I am doing wrong?

Thanks in advance!!

**Comment by darold** [comment]
This is a psql use issue, I you need help on using PostgreSQL you should contact the pgsql-general mailing list. Here you are trying to import a SQL script using psql client, the connection/login authorization are given in file pg_hba.conf of the server.

**Comment by Saurabh-704** [comment]
Thank you @darold for your response. I will try to figure out that authentication issue. 
Mean while can you please confirm that the schema name where I defined is the right place to define in conf file.
I have set PG_SCHEMA to db1
<img width="482" alt="l" src="https://user-images.githubusercontent.com/47383623/88918864-d5f14c00-d287-11ea-8cf0-b86b750639f8.png">
Is it the right place where I defined the schema name.

**Comment by darold** [comment]
This configuration directive is only used to generate the SQL command, in the output file applsys_tables.sql.sql table name should be prefixed by the db1 schema.

Note that the psql command doesn't use the ora2pg.conf file.
