### ISSUE TITLE
how to export XML tables from Oracle to PostgreSQL

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#927]
how to export XML tables from Oracle to PostgreSQL

**Comment by darold** [comment]
What do you call XML table? If this is columns defined with XML data type they are just exported in the same data type in PostgreSQL. Globally PG has the same functions than Oracle with some little differences, if I remember well Ora2Pg translate most of them.

**Comment by naveenjul29** [comment]
I am talking about **XMLTYPE** datatype. For Example:

CREATE TABLE EMPLOYEES
(
   id     NUMBER,
   data   XMLTYPE
);

INSERT INTO EMPLOYEES
     VALUES (1, xmltype ('<Employees>
    <Employee emplid="1111" type="admin">
        <firstname>John</firstname>
        <lastname>Watson</lastname>
        <age>30</age>
        <email>johnwatson@sh.com</email>
    </Employee>
    <Employee emplid="2222" type="admin">
        <firstname>Sherlock</firstname>
        <lastname>Homes</lastname>
        <age>32</age>
        <email>sherlock@sh.com</email>
    </Employee>
    <Employee emplid="3333" type="user">
        <firstname>Jim</firstname>
        <lastname>Moriarty</lastname>
        <age>52</age>
        <email>jim@sh.com</email>
    </Employee>
    <Employee emplid="4444" type="user">
        <firstname>Mycroft</firstname>
        <lastname>Holmes</lastname>
        <age>41</age>
        <email>mycroft@sh.com</email>
    </Employee>
</Employees>'));

**Comment by mkgrgis** [comment]
There is good "Example 4-5"  from https://docs.oracle.com/cd/B10501_01/appdev.920/a96620/xdb04cre.htm

**Comment by darold** [comment]
Then this is a very old feature, when you ask how to export, have you tried? This is supported for a long time by Ora2Pg, as I said to you it will be exported as XML PostgreSQL data type which is the equivalent. Just take care that you are not facing the same problem than in issue #889

**Comment by naveenjul29** [comment]
we can close this at this moment. I will open a new request as and when needed.

Darold, as usual thank you so much for all your help !! I really appreciate your quick responses all the times !!
