### ISSUE TITLE
Table's count is not matching after export.

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#928]
Table's count is not matching after export. Assume that In oracle, I have 50 tables, but after export it is showing 45.

Please help me on this.

**Comment by darold** [comment]
I have already explain that several time, the difference is probably because of system table or tables that belong to Oracle software or module, like audit, etc and table owned by some owners. Usually you don't need to export those tables.

**Comment by naveenjul29** [comment]
all the tables are user tables and they are in the same schema and they owned by same owner. Still not all the tables are not exported. 

Can I please have the query which you are using to export the tables so that I can run the same query and cross check(I didn't understand it in PERL script that's why I am asking)

**Comment by darold** [comment]
Please post tables name that you think should be exported and the value of the ALLOW and EXCLUDE configuration directives in ora2pg.conf if they are set.

**Comment by naveenjul29** [comment]
I just found that missing TABLEs are TEMPORARY TABLEs. How can we export them as well?

**Comment by darold** [comment]
I guess that this is global temporary tables, they are not supported in PostgreSQL yet unless you use my extension  https://github.com/darold/pgtt/ I must patch Ora2Pg to export these table and use the extension but unfortunately I still do not find the time to work on it. Your solution now is to rewrite the code to use regular PG temporary table.

**Comment by naveenjul29** [comment]
Thank you Darold. I still have a doubt like what is the command you are using to filter the tables in a schema? like suppose if we have 100 tables in a schema, you might be using some filters while exporting, i am talking about those? I tried to search in source code but no luck. I am sorry for any inconvenience caused.

**Comment by naveenjul29** [comment]
Darold, can you please reply to above query?

**Comment by darold** [comment]
This is something like that:
```
SELECT
        A.OWNER,A.TABLE_NAME, NVL(num_rows,1) NUMBER_ROWS, A.TABLESPACE_NAME, A.NESTED, 
        A.LOGGING, A.PARTITIONED, A.PCT_FREE
FROM ALL_TABLES A, ALL_OBJECTS O
WHERE
        A.OWNER=O.OWNER AND A.TABLE_NAME=O.OBJECT_NAME
        AND O.OBJECT_TYPE='TABLE' AND A.OWNER='<your schema>'
        AND (A.DROPPED IS NULL OR A.DROPPED = 'NO')
        AND (A.OWNER, A.TABLE_NAME) NOT IN (SELECT OWNER, MVIEW_NAME FROM ALL_MVIEWS UNION ALL SELECT LOG_OWNER, LOG_TABLE FROM ALL_MVIEW_LOGS)
        AND (A.OWNER, A.TABLE_NAME) NOT IN (SELECT OWNER, TABLE_NAME FROM ALL_OBJECT_TABLES)
        AND (A.IOT_TYPE IS NULL OR A.IOT_TYPE = 'IOT');
```
Let us know what kind of tables are missing.

**Comment by naveenjul29** [comment]
Thank you so much Darold. I will check and update you.
