### ISSUE TITLE
Help needed: PostgreSQL BYTEA datatype

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#929]
Darold, you are converting BFILE data type into BYTEA in postgreSQL. can you please help me with an example for ByteA data type. I am really sorry if this is not the right place to ask. If it is not the right place to ask, any idea, where I can raise requests for PostgreSQL issues?

Thank you in advance.

**Comment by darold** [comment]
There is tons of example for bytea use on the internet, use your favorite search engine. If you can't find the answer by yourself you should subscribe to the pgsql-general mailing list.
