### ISSUE TITLE
Export types in Ora2pg

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#930]
Darold, I remembered, earlier you said that we can export only 1 type at a time. But the below command worked for me:

ora2pg -c ora2pg.conf -t TABLE,VIEW -n TST -N TST -o tables0801.sql -b schema/tables/

Also,  It created 2 files automatically 

VIEW_tables0801.SQL
TABLE_tables0801.SQL

**Comment by darold** [comment]
I said that you can but this is not the recommended way as I never test it. I always use unitary export type with ora2pg.
