### ISSUE TITLE
PostgreSQL Extensions with Ora2pg tool

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#931]
Darold, we do have extensions(~50) with functions in PostgreSQL.

How can we use these extensions with Ora2pg?

**Comment by luss** [comment]
The combination of migrating your data & stored procs with Ora2pg and then
using OraFCE for runtime built-in packages is very powerful for migrating
to PostgreSQL.  For an idea of all the richness of the PG community
extensions take a look at https://pgsql.io.

--Luss

**Comment by naveenjul29** [comment]
Thank you Luss for your response. My confusion is that only, like, how can I sync OraFCE with ora2pg for runtime built-in packages while migrating to PostgreSQL.

Thanks & Regards
Naveen

**Comment by darold** [comment]
Ora2pg doesn't use the orafce extension at all, if you enable USE_ORAFCE in ora2pg.conf that just mean that ora2pg will not convert Oracle functions/codes that are supported by the orafce extension.

**Comment by naveenjul29** [comment]
Thank you Darold.
