### ISSUE TITLE
Issues with reserved words in PostgreSQL

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#932]
When we import the export script into PostgreSQL, we are seeing issues with reserved words in PostgreSQL. 
Manually we are putting them in double quotes to run.
Is there any way in Ora2pg to do the same?

**Comment by naveenjul29** [comment]
I already set USE_RESERVED_WORDS to 1 but it didn't put the double quotes for table names/column names in PostgreSQL.

Please help me further.

**Comment by darold** [comment]
They are probably missing in the reserved keyword list, what are the tables/columns names that are not automatically double quoted by Ora2Pg?

**Comment by naveenjul29** [comment]
Darold, below are the sample reserved words that we come across: Double quotes are not applied for all these in the script file.

NAME
ROLE
CURRENT_DATE
LANGUAGE
DAY
INTERVAL
VERSION
EXTENSION
POSITION
ZONE
ACTION
TRANSACTION
EVENT
SEQUENCE
COLUMNS
ID
DEFERRED
OWNER
TEXT
TYPE
VALUE
MESSAGE_LENGTH
MESSAGE
TABLE_NAME
METHOD
YEAR 
COMMENTS
XML

**Comment by naveenjul29** [comment]
Darold, can you please help me on this?

**Comment by darold** [comment]
I still not had the time to work on this.

**Comment by naveenjul29** [comment]
ok np :)

**Comment by darold** [comment]
I keep it open because I need to remember to do some work on it.

**Comment by NishanthBejgam** [comment]
Could you please post some sample schema that you encounter these reserved words and would like to maintain as is?

**Comment by darold** [comment]
Closing, in the keyword list above only CURRENT_DATE is refused a column name and when USE_RESERVED_WORDS is enabled it is well double quoted.
