### ISSUE TITLE
ORA2PG repeating column names

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#934]
ORA2PG repeated the column names in view export file. Attaching the export file for your reference.
I didn't see this behaviour in recent times.

What could be the reason?

**Comment by naveenjul29** [comment]
Darold, can you please help me on this?

**Comment by naveenjul29** [comment]
Darold, can you please help me here?

**Comment by darold** [comment]
Does this view is declared in others schema with the same name?

**Comment by naveenjul29** [comment]
no, it is not

**Comment by darold** [comment]
Can you post an Oracle VIEW definition that is in trouble with this export?
