### ISSUE TITLE
How to migrate directly oracle to postgresql without output.sql?

### ISSUE THREAD

**Issue by Pepan7** [darold/ora2pg#936]
When I set in config:
```
EXPORT_SCHEMA	1
CREATE_SCHEMA	1
COMPILE_SCHEMA	0
TYPE TABLE
PG_DSN	dbi:Pg:dbname=db;host=not_localhost;port=5432
PG_USER	postgres
PG_PWD	password
OUTPUT	output.sql #when is this commented so not created file, whis is uncommented create file
```
and I run command
`ora2pg -c ora2pg.conf`
If is parameter OUTPUT uncommented so create file and if is commented so nothing will happen (only x/x tables (100.0%) end of scanning and x/x tables (100.0%) end of table export.), but not any table is created in postgresql and schema too not created.
Why or What I must set in config? Maybe is output.sql bad because I have error in #935 . Thanks for response.

**Comment by darold** [comment]
Only data export can be sent to PG directly so PG_DSN  is only used when export type is COPY or INSERT. Any other export type will write to the output file.

**Comment by Pepan7** [comment]
I dont understand why is this in config file:
```
# Define the following directive to send export directly to a PostgreSQL
# database. This will disable file output.
```
So I think thats work for all (TABLE, PACKAGE...) not only for COPY or INSERT. Plaase change it to in comment because is confusing.

**Comment by darold** [comment]
Thanks for the report, I was thinking that this was the case. Commit ee8fc22 adds a note about this behavior.
```
# Define the following directive to send export directly to a PostgreSQL
# database, this will disable file output. Note that these directives are only
# used for data export, other export need to be imported manually through the
# use og psql or any other PostgreSQL client.
PG_DSN ...
```
