### ISSUE TITLE
ora2pg assessment report is taking time to execute

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#937]
Darold, I ran the below command to run the assessment report, but it seems to be hung. 

**ora2pg -d -t SHOW_REPORT --estimate_cost -c ora2pg.conf --dump_as_html > report.html**

Below is the sample output. 
![ShowReport](https://user-images.githubusercontent.com/67134199/89422540-1c94e980-d753-11ea-8178-af82289316e4.PNG)

Need your help to complete the report.

**Comment by naveenjul29** [comment]
Darold, can you please help me on this?

**Comment by darold** [comment]
Does it really hang or it finally ends after long minutes?

**Comment by naveenjul29** [comment]
I killed it after 2 days

**Comment by darold** [comment]
Looks like there is sometime a real problem with assessment when there is lot of objects, some have also experienced out of memory. Unfortunately I'm not able to reproduce these issues with my test databases so I can not provide a solution until I'm facing the same problem.

**Comment by naveenjul29** [comment]
sure Np Darold. Thank you for the reply ..
