### ISSUE TITLE
Ora2PG Estimate Cost per object

### ISSUE THREAD

**Issue by orenbouni** [darold/ora2pg#938]
Hello, 
I'm running an estimate Cost on a DB (oracle DB) and and when running on Views i'm getting out of memory and it fails.
My Question is can i run the cost assessment report per object, meaning one for the tables, one for the Views, for the Packages ect. 
after that i will create one report out of all the separated reports.

Is is possible?

**Comment by darold** [comment]
You can run the cost assessment per export type if you use `--estimate_cost` at command line, the output files will contain the estimated cost.

**Comment by naveenjul29** [comment]
I am also looking for the same help.

Darold, can you please give an example like how can I run the cost assessment per export type?

**Comment by darold** [comment]
For example if I recall well:
```
mkdir -p schema/functions
ora2pg -p -t FUNCTION --estimate_cost -c ora2pg.conf -b schema/functions -o function.sql`
```
Then look at file function.sql` for a summary and in each function dedicated file.

**Comment by naveenjul29** [comment]
Thank you Dorald

**Comment by orenbouni** [comment]
Thanks A lot for this tip, i will run it today and check it.

**Comment by orenbouni** [comment]
Hi That worked wonderfully for all the objects in the DB except for the Partitions
I'm getting this Error:
**C:\DB1_Cust1>ora2pg -p -t PARTITION -c C:\DB1_Cust1\ora2pg_Part.conf -b C:\DB1_Cust1\Report -o partition.sql
[===>                     ]  23399/148449 partitions (15.8%) end of output.**
Is there an option to do it Per table with partition or by Groups of partitions ?

**Comment by darold** [comment]
I don't see any error here. To filter per table see ALLOW configuration directive or the -a option.
