### ISSUE TITLE
How to pass oracle DSN at the command prompt along with Ora2Pg

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#939]
Darold, below command is not working:

**ora2pg -u system -p manager -t SHOW_VERSION --source dbi:Oracle:host=localhost;sid=XE**

can you please help me on how to pass oracle DSN to ora2pg command at command prompt?

**Comment by orenbouni** [comment]
you will need to edit the ora2pg.conf file.
with in the file you will see this parameters add the right OraHome, DSN, User, Password

# Set the Oracle home directory
ORACLE_HOME	C:\oracle\Path ......

# Set Oracle database connection (data-source, user, password)
ORACLE_DSN	Your_Server_Name;port=1521
ORACLE_USER	User
ORACLE_PWD	Password

Once you did it then the command is :

ora2pg -c c:\ora2pg\ora2pg.conf -t SHOW_VERSION

**Comment by naveenjul29** [comment]
This I am aware of. But I would like to pass Oracle DSN at the command prompt as I shown in my request.

I would like to pass oracle DSN along with Ora2pg command.

**Comment by darold** [comment]
The way you use it is the right one, just set the DSN using double or simple quote. This is necessary due to the semicolon that is interpreted by the shell.
