### ISSUE TITLE
Issue with Synonyms export using Ora2Pg tool

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#940]
Darold, We do have 150+ schemas in our Oracle server. In almost 50+ schemas I don't have synonyms. But when I export the synonyms it is exporting 18 or 20 objects into SQL file. Not really understand, how the export file is generating with objects for empty synonyms.

**Comment by darold** [comment]
I trust you but here is what I obtain when I export a schema without synonym:
```
 $ ora2pg -p -c config/ora2pg.conf -t SYNONYM -b schema/synonyms/
[========================>] 0/0 synonyms (100.0%) end of output.

$ cat schema/synonyms/output.sql
[...]
SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

-- Nothing found of type SYNONYM
```
So at some point if I am not in the place to find what happen, I can not help much more.

**Comment by naveenjul29** [comment]
I really appreciate Darold for your quick response. is there any directive to be set for this?

**Comment by darold** [comment]
No, I note that an ultimate debug mode could help in critic situation like that.
