### ISSUE TITLE
Ora2Pg issues with EDITIONABLE keyword

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#941]
We exported the types(PROCEDURES/FUNCTIONS/PACKAGES etc.,) using Oracle SQL Developer. When we open the export file, we see **CREATE OR REPLACE EDITIONABLE**. When we pass this export file as input parameter to Ora2pg command, it is giving 0/0 conversions. Where as when we delete EDITIONABLE keyword in export file and pass the updated file to ora2pg as a input parameter, it is giving 1/1 count.

Interesting thing here is, as per Ora2pg documentation, "**create or replace editionable|noneditionable**" from input DML files has been taken care. Then I am not sure why it is not working.

**Comment by darold** [comment]
This might have been fixed with commit a2c5a42 on Mon Jul 27, if it still not works after code update, please post Oracle code of a function that has this problem.

**Comment by naveenjul29** [comment]
I am attaching the script for your reference. Actually this file is generated using Oracle SQL Developer Export method. Any idea, how we can exclude EDITIONABLE keyword while exporting using Oracle SQL Developer Export method?

[test.txt](https://github.com/darold/ora2pg/files/5062480/test.txt)

**Comment by darold** [comment]
You should update to latest development code, I can not reproduce the issue, I save your procedure into a file named `editonable.sql` then:
```
$ ora2pg -c ora2pg.conf -p -t PROCEDURE -i editonable.sql -b /tmp/
[========================>] 1/1 procedures (100.0%) end of procedures export.

$cat /tmp/OT.CHECKEMP_output.sql
[...]
CREATE OR REPLACE PROCEDURE checkemp () AS $body$
DECLARE

    my_cursor CURSOR FOR SELECT sal + coalesce(comm, 0) wages, ename
        FROM emp;
    my_rec  RECORD;

BEGIN
    OPEN my_cursor;
    LOOP
        FETCH my_cursor INTO my_rec;
        EXIT WHEN NOT FOUND; /* apply on my_cursor */
        IF my_rec.wages > 2000 THEN
            INSERT INTO temp VALUES (NULL, my_rec.wages,
                my_rec.ename);
        END IF;
    END LOOP;
    CLOSE my_cursor;
END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE checkemp () FROM PUBLIC;
```

**Comment by naveenjul29** [comment]
I do have the latest development code but same code is not working for me :(

**Comment by darold** [comment]
double check your installation

**Comment by naveenjul29** [comment]
sure. Thank you, resolving the incident.
