### ISSUE TITLE
Data export from blob to oid

### ISSUE THREAD

**Issue by rodiq** [darold/ora2pg#943]
I want to convert oracle blob columns to postgresql oid columns, bytea is too slow in my case. I tried the export from blob into bytea and it works fine. If I force DATA_TYPE blob:oid , there are no errors but the converted data is not usable. Could it be a configuration error? Is the direct conversion from blob to oid  supported by ora2pg? I checked and both Oracle and Postgresql databases have UTF8 encoding. I use Oracle Database 12c  12.1.0.2.0, PostgreSQL 12 and ora2pg-20.0

My workaroud: one script changes, before data import, postgresql column types from oid to bytea. Then I import oracle data in bytea column, and I use postgresql function lo_from_bytea to move the data to a new oid column. Then I delete from table structure the bytea column and keep the oid. It would be better to be able to import the data directly from blob to oid.

**Comment by darold** [comment]
If I take literally what you are writing, you can not translate BLOB into oid, data type Oid is an unsigned integer. I guess that what you mean is to migrate BLOB as large object?

**Comment by rodiq** [comment]
yes, I want to migrate BLOB as large object

**Comment by darold** [comment]
This is in my TODO list for a long time at low priority level, I think it is feasible but need lot of work and I never got the time to develop it. I keep this issue open as a reminder.

**Comment by helmichamsi10** [comment]
hi rodiq ,

did this workaround worked with successful for you ?
cause I did the same think but I got wrong data

Cordially,

**Comment by helmichamsi10** [comment]
hi rodiq ,

did this workaround worked with successful for you ?
cause I did the same think but I got wrong data
the data be like that after the migration from bytea to oid using postgresql function lo_from_bytea :
decode(E'3c3f786d6c2076657273696f6e3d27312e302', 'hex')

this is the query : UPDATE table_name SET columnNameoid= lo_from_bytea(0, columnNamebytea_::bytea);

Cordially,

**Comment by helmichamsi10** [comment]
hi all,

rodiq did this workaround worked with successful for you ?
cause I did the same think but I got wrong data
the data be like that after the migration from bytea to oid using postgresql function lo_from_bytea :
decode(E'3c3f786d6c2076657273696f6e3d27312e302', 'hex')

this is the query : UPDATE table_name SET columnNameoid= lo_from_bytea(0, columnNamebytea_::bytea);

Cordially,

**Comment by darold** [comment]
@rodiq perhaps you could shared here your script with others, looks that you are not the only one who want to do that and that could be helpful.

**Comment by madtibo** [comment]
Hello,

I do the same thing as @rodiq 

```sql
CREATE TABLE my_table_lo AS 
  SELECT my_table_id, <other_columns>, 
                lo_from_bytea(0, bytea_column) bytea_column -- lob_oid
  FROM my_table;

DROP TABLE my_table;
ALTER TABLE my_table_lo RENAME TO my_table;
```

It would be much faster to migrate directly to large object... but it works :-)

**Comment by rodiq** [comment]
My solution was the following: I created the postgresql table  with oid column (like I wanted to have). Than I wrote some scripts to import easily a set of test data from Oracle to an empty Postgresql database:

 - I changed temporarely the postgresql column from oid to bytea 
 alter table my_pg_table alter column my_column type bytea using my_column::text::bytea;

 - I imported the oracle data files (exported with ora2pg) to bytea
 
 - I transformed back the bytea column to oid, using a temporary column
ALTER TABLE my_pg_table ADD COLUMN temp_oid OID;
UPDATE my_pg_table SET temp_oid = lo_from_bytea(0, my_column::bytea), my_column = NULL;
ALTER TABLE my_pg_table DROP COLUMN my_column;
ALTER TABLE my_pg_table RENAME COLUMN temp_oid TO my_column;

Thank you @darold for your fast responses, they were very helpful, sorry that I did not have until now the time to answer back.

**Comment by darold** [comment]
Commit 3076f02 adds this feature.

```
    Add new option --blob_to_lo that can be used to export BLOB as large
    objects. It can only be used with action SHOW_COLUMN, TABLE and INSERT.
    When used with TABLE action, the BLOB column will be translated into oid
    PostgreSQL data type. When used with the INSERT export action BLOB data
    will be store as loarge object in the pg_largeobjects table and the oid
    referencing this large object will be stored in the main table instead
    of a bytea.
    
    It is not possible to use id with COPY because this feature use function
    lo_from_bytea() that stores the large object in the external table and
    returns the oid.
    
    This feature works with or without the use of oracle_fdw to import the
    data and ORACLE_COPIES or option -J can be used to improve the speed
    of the INSERT import provide that there is a numeric unique key on the
    table.
```
