### ISSUE TITLE
Database links export in Oracle

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#945]
Darold, we do have 2 database links in my oracle schema

![dblinks](https://user-images.githubusercontent.com/67134199/90242394-92334080-de4a-11ea-8edc-6f0e2fa0dc66.PNG)

I tried to export these database links using ora2pg, I used **FDW** type but when I see the output file it is showing no output. 

Please help me on this.

**Comment by darold** [comment]
To export dblink use export type DBLINK, why FDW? This is not the same thing, FDW export type is used to export Oracle tables as PostgreSQL foreign tables to be able to use oracle_fdw (not very useful since there is IMPORT SCHEMA in PostgreSQL, but it use to be).

**Comment by naveenjul29** [comment]
my bad :( Thank you Darold
