### ISSUE TITLE
Issue with Synonyms export(previous ticket #940)

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#946]
Darold, to the continuation of #940 , below is the screenshot which may help you to troubleshoot and help me further.

![synonym issue](https://user-images.githubusercontent.com/67134199/90265209-db49bb80-de6f-11ea-8b59-610d044aba33.PNG)

same thing is happening for all schemas where we don't have synonyms.

**Comment by naveenjul29** [comment]
below is the screenshot that there are no synonyms in one of the schema
![synonym issue1](https://user-images.githubusercontent.com/67134199/90257886-62ddfd00-de65-11ea-9e10-92556f8b3069.PNG)

**Comment by darold** [comment]
Are you talking about SYNONYME or SEQUENCES? I guess that last screenshot is a mistake :-)

**Comment by darold** [comment]
If Ora2Pg exports SYNONYM this is because you have SYNONYM, maybe you are not looking at the right place.

**Comment by naveenjul29** [comment]
may be a silly question, in my case, how would i know my right place for synonyms?

**Comment by darold** [comment]
Ask to the Oracle DBA?

**Comment by darold** [comment]
Actually looking at the schema used with these Synonym, MGDSYS, I think Ora2Pg should not take care of it because it is part of Oracle E-Business Suite. I will add this schema to the exclusion list, for the moment I  think you should just not take care of these synonyms.

**Comment by naveenjul29** [comment]
Thank you Darold :) please let me know how can I add this schema to the exclusion list at my end?

**Comment by darold** [comment]
With Ora2Pg there is a configuration directive for everything, the one you are looking for is `SYSUSERS`.
