### ISSUE TITLE
running in Parallel in Windows

### ISSUE THREAD

**Issue by orenbouni** [darold/ora2pg#947]
Hi in the documentation it says that -J option is disabled in Windows,

I'm trying to copy a 41M row table directly from Oracle to PG using this command:

ora2pg -t COPY -c c:\ora2pg\ora2pg_dist.conf

Is there an option to run the load in Paralel or to speed up the load?
i'm getting a rate of 46 row/sec

**Comment by darold** [comment]
I guess that there is BLOB in this table, unfortunately I never had the time to port the multi-process for Windows platform. The only way to parallelize would be to run several ora2pg command with each a different predicate to the WHERE configuration directive to filter/group rows per process, for example using modulo on a numeric column, just like -J | ORACLE_COPIES is doing (see documentation).

**Comment by orenbouni** [comment]
Thanks for the prompt answer, 
Can you share a demo on how i should writ it?
meaning how to filter  using the where

**Comment by darold** [comment]
Let's say you will use 2 processes, in ora2pg.conf.1 you will set:
```
WHERE        MOD(COL1, 2) = 0
```
and in ora2pg.conf.2 you will set:
```
WHERE        MOD(COL1, 2) = 1
```
When you run multiple ora2pg command in parallel you have to use a dedicated temporary directory per command, use the `--temp_dir` command line option to set it.

Then call each ora2pg command with the corresponding configuration file.

Adjust the second parameter of the MOD() function to the number of processes you want to run, typically one per core, and the modulo value which is the core number starting at 0.
