### ISSUE TITLE
Problème lors de l'import (direct)

### ISSUE THREAD

**Issue by Blublu6** [darold/ora2pg#948]
Bonjour,

L'import direct depuis le serveur oracle ne traite que 2 tables (sur 254) et partiellement puis s'arrête :

c:\ora2pg>ora2pg
[========================>] 254/254 tables (100.0%) end of scanning.
[========================>] 13312/13312 rows (100.0%) Table **A** (6656 recs/sec)
[=>                       ]  13312/206342 total rows (6.5%) - (2 sec., avg: 6656 recs/sec).
[========================>] 6/6 rows (100.0%) Table **B** (6 recs/sec)
[=>                       ]  13318/206342 total rows (6.5%) - (4 sec., avg: 3329 recs/sec).
[=>                       ]  13318/206342 rows (6.5%) on total estimated data (4 sec., avg: 3329 recs/sec)
c:\ora2pg>

Merci d'avance!

**Comment by darold** [comment]
Probably an OOM, add more memory.

**Comment by Blublu6** [comment]
Ok merci je vais regarder de ce côté.
