### ISSUE TITLE
ERROR:  relation "departments"

### ISSUE THREAD

**Issue by orenbouni** [darold/ora2pg#951]
Hello, I tried to troubleshot  it but out of idea.
when testing on HR Oracle Schema and running a copy ora2pg command i'm getting and error.
What can be the problem?

Command:
ora2pg -t COPY -c C:\Ora2PG_BrownBag\ora2pg_BBHRR.conf

Error:
[=========================>] 6/6 tables (100.0%) end of scanning.
DBD::Pg::db do failed: ERROR:  relation "departments" does not exist at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 14753.
FATAL: ERROR:  relation "departments" does not exist
Aborting export...

**Comment by darold** [comment]
The table must exists in your PG database, you have to import the DDL before importing the data.

**Comment by orenbouni** [comment]
all 7 tables of the Oracle HR Schema are in the PG db.
the table were migrated before trying to upload the data

**Comment by darold** [comment]
Then not in the good schema:
```
DBD::Pg::db do failed: ERROR: relation "departments" does not exist at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 14753.
FATAL: ERROR: relation "departments" does not exist
```
DBD::Pg::db  is the Perl driver to connect to PG and `ERROR: relation "departments" does not exist` is explicit, look at PG_SCHEMA in ora2pg.conf and the schema where you have created the table.
