### ISSUE TITLE
Long line problem

### ISSUE THREAD

**Issue by unrandom123** [darold/ora2pg#952]
I tried to run (using latest ora2pg on Linux machine, oracle db version10)

    ora2pg -c ora2pg.conf  -t TABLE -o tables.sql -b schema/tables/

but it failed (writing out a very long query). I tested the query by hand, and it failed, complaining about 

SP2-0027: Input is too long (> 2499 characters) - line ignored

Here is the query (I replaced a lot of the long line with ....   The long line is 5499 characters long by the way.)
```
SELECT
        A.TABLE_NAME,
        A.PARTITION_POSITION,
        A.PARTITION_NAME,
        A.HIGH_VALUE,
        A.TABLESPACE_NAME,
        B.PARTITIONING_TYPE,
        A.TABLE_OWNER
FROM ALL_TAB_PARTITIONS A, ALL_PART_TABLES B
WHERE A.TABLE_NAME = B.TABLE_NAME
AND A.TABLE_OWNER='XXXYYYZZZ'
 AND (A.TABLE_OWNER, A.TABLE_NAME) NOT IN (SELECT OWNER, .... NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), ?))       AND A.TABLE_OWNER ='XXXYYYZZZ'
ORDER BY A.TABLE_NAME;

```

**Comment by darold** [comment]
Are you using latest development code? This problem should have been fixed a long time ago by the use of bind parameters.

**Comment by unrandom123** [comment]
> Are you using latest development code? This problem should have been fixed a long time ago by the use of bind parameters.

I use v20.0, and now I see that it is quite old. I will try to checkout latest code.

**Comment by unrandom123** [comment]
I downloaded the master branch (I hope) and it failed again with another error

DBD ERROR: error possibly near <*> indicator at char 142 in '

and in the SQL I see...

```
SELECT
        A.TABLE_NAME,
        A.PARTITION_POSITION,
        A.PARTITION_NAME,
        A.HIGH_VALUE,
        A.TABLESPACE_NAME,
        B.PARTITIONING_TYPE,
        A.TABLE_OWNER
FROM <*>ALL_TAB_PARTITIONS 

```
You see the <*> thing...

**Comment by unrandom123** [comment]
In the SQL I see the long line

 `AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p3) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p4) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p5) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p6) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p7) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p8) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p9) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p10) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p11) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p12) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p13) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p14) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p15) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p16) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p17) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p18) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p19) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p20) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p21) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p22) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p23) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p24) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p25) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p26) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p27) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p28) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p29) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p30) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p31) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p32) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p33) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p34) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p35) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p36) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p37) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p38) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p39) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p40) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p41) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p42) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p43) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p44) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p45) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p46) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p47) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p48) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p49) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p50) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p51) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p52) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p53) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p54) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p55) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p56) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p57) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p58) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p59) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p60) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p61) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p62) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p63) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p64) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p65) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p66) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p67) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p68) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p69) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p70) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p71) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p72) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p73) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p74) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p75) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p76) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p77) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p78) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p79) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p80) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p81) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p82) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p83) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p84) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p85) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p86) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p87) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p88) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p89) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p90) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p91) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p92) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p93) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p94) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p95) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p96) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p97) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p98) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p99) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p100) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p101) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p102) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p103) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p104) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p105) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p106) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p107) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p108) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p109) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p110)) AND A.TABLE`

Not sure it is correctly representing what is sent to the server, but if it is, it will probably fail since it is over 2500 chars.

**Comment by unrandom123** [comment]
I've been trying to find where the extra <*> comes from, but no luck so far.
I've edited lib/Ora2Pg.pm at lines around 12160 to check the value of $self->prefix, but it seems to be alright.
I have no idea what is going on. Any idea?

**Comment by darold** [comment]
How about if you set USER_GRANTS to 1 in ora2pg.conf?

**Comment by unrandom123** [comment]
I have that.
These are the options I have

USER_GRANTS     1
EXPORT_SCHEMA   1
SCHEMA  myschema
TRANSACTION     READONLY

The oracle account I'm using is one with complete datapump (expdp/impdp) rights. Can that be an issue?

**Comment by darold** [comment]
Yes sorry I meant 0 to look at DBA_* tables and use a DBA account.

**Comment by unrandom123** [comment]
Great! That solved it. Thanks.
