### ISSUE TITLE
Suggestion: Show shema in output

### ISSUE THREAD

**Issue by unrandom123** [darold/ora2pg#953]
I just ran latest development version with  -d -t TABLE  options and it crashed.
Malformed UTF-8 character: 

I think I know where to look, but just before the error it wrote:

Looking at package XXX

Since I run this without any schema specification (working on entire oracle db), I'd suggest that in the output it should write the schema name (if possible).

**Comment by NishanthBejgam** [comment]
try keep the setting EXPORT_SCHEMA	1 in config file, this displays the scheme name along with

**Comment by unrandom123** [comment]
I have that, it shows no schema name.
Here are the non-connection related settings. (trying to export entire db)

USER_GRANTS     1
EXPORT_SCHEMA   1
TRANSACTION     READONLY

**Comment by unrandom123** [comment]
Issue solved by removing "problematic" characters from oracle packages.
