### ISSUE TITLE
Suggestion: Don't look at things not asked for?

### ISSUE THREAD

**Issue by unrandom123** [darold/ora2pg#954]
I ran ora2pg to get views (-t VIEW )
but it failed on a bad character in a package it seems

Looking at package mypackage
Malformed UTF-8 character: \xe4 ....

Why does it look at packages when I want views? Seems a bit strange. If it is for avoiding name conflicts, then do you really need to look inside the package?

**Comment by darold** [comment]
Nothing strange, it look at packages to try to detect user defined functions call in the views and transform them if necessary. Looking at documentation:
```
    NO_FUNCTION_METADATA
        Force Ora2Pg to not look for function declaration. Note that this
        will prevent Ora2Pg to rewrite function replacement call if needed.
        Do not enable it unless looking forward at function breaks other
        export.
```
When I said that there is a configuration directive for almost everything, I'm not joking, your first reflex should be to look at the documentation or the ora2pg.conf comments :-)

**Comment by unrandom123** [comment]
Issue solved by removing "problematic" characters from oracle packages.
