### ISSUE TITLE
Functions cannot have more than 100 arguments in PostgreSQL

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#955]
My Oracle stored procedure has more than 100 parameters, when i tried to migrate that procedure into PostgreSQL, I got the below error:

ERROR:  functions cannot have more than 100 arguments
SQL state: 54023

**Comment by okbob** [comment]
ne 30. 8. 2020 v 19:41 odesílatel naveenjul29 <notifications@github.com>
napsal:

> My Oracle stored procedure has more than 100 parameters, when i tried to
> migrate that procedure into PostgreSQL, I got the below error:
>
> ERROR: functions cannot have more than 100 arguments
> SQL state: 54023
>
you have to rewrite your code. The number of arguments is a hard limit.

100 arguments of procedure sounds like pretty bad design.

In postgres you can use arrays or composite types.
