### ISSUE TITLE
Everything exports but not the data

### ISSUE THREAD

**Issue by unrandom123** [darold/ora2pg#957]
I have this in ora2pg.conf

USER_GRANTS     0
EXPORT_SCHEMA   1
TRANSACTION     READONLY

and I've manage to run all queries to get packages, procedures, tables, and so on, but it fails with this command

```
ora2pg -d -J 2 -c ora2pg.conf -t VIEW -o views.sql   <-- work
ora2pg -d -J 2 -c ora2pg.conf -t INSERT -o data.sql  <-- does not work

```
The output shows this error, notice the <*>

```
Process ID: 0
Session ID: 153 Serial number: 21917 (DBD ERROR: error possibly near <*> indicator at char 187 in '
SELECT
        A.TABLE_NAME,
        A.PARTITION_POSITION,
        A.PARTITION_NAME,
        A.HIGH_VALUE,
        A.TABLESPACE_NAME,
        B.PARTITIONING_TYPE,
        C.NAME,
        C.COLUMN_NAME,
        C.COLUMN_POSITION,
        A.TABLE_OWNER
FROM <*>DBA_TAB_PARTITIONS A, DBA_PART_TABLES B, DBA_PART_KEY_COLUMNS C
WHERE
        a.table_name = b.table_name AND
        (b.partitioning_type = 'RANGE' OR b.partitioning_type = 'LIST' OR b.partitioning_type = 'HASH')
        AND a.table_name = c.name .......

```

I had similar issue earlier, and that was fixed by using   USER_GRANTS 0
So how to solve it this time? Any suggestion?

**Comment by darold** [comment]
There should be an ORA-NNNNN error, this number is more useful to know what Oracle error is thrown but I guess that your user doesn't have the privilege to look at partitions.
