### ISSUE TITLE
ora2pg ORA-24345: A Truncation or null fetch error occurred

### ISSUE THREAD

**Issue by sagicha** [darold/ora2pg#958]
Hello Darold,

I am working on oracle  to postgresql migration and encountering ORA-24345 issues.

DBD::Oracle::st fetchall_arrayref failed: ORA-24345: A Truncation or null fetch error occurred (DBD SUCCESS_WITH_INFO: OCIStmtFetch, LongReadLen too small and/or LongTruncOk not set)
ERROR no statement executing (perhaps you need to call execute first) [for Statement "SELECT "ITEM_NAME","ITEM_VERSION","STATUS","DESCRIPTION","USER_ID","LASTUPDATED","UPLOADED_FILE","OWNER","UPLOADED_FILENAME" FROM "SCART_APP"."ITEM_TYPE_VERSIONS" a"] at C:/Perl64/site/lib/Ora2Pg.pm line 14110.
ERROR: ORA-24345: A Truncation or null fetch error occurred (DBD SUCCESS_WITH_INFO: OCIStmtFetch, LongReadLen too small and/or LongTruncOk not set)
ERROR no statement executing (perhaps you need to call execute first) 

**Oracle table** 
![image](https://user-images.githubusercontent.com/70625928/91941735-f767ac80-ecf9-11ea-8802-4531cecf2c5a.png)

**postgresql table**
![image](https://user-images.githubusercontent.com/70625928/91941856-38f85780-ecfa-11ea-9021-da5f3c0b1413.png)

**the output of current ora2pg encoding** 
Current encoding settings that will be used by Ora2Pg:
        Oracle NLS_LANG AMERICAN_AMERICA.AL32UTF8
        Oracle NLS_NCHAR AL32UTF8
        Oracle NLS_TIMESTAMP_FORMAT YYYY-MM-DD HH24:MI:SS.FF6
        Oracle NLS_DATE_FORMAT YYYY-MM-DD HH24:MI:SS
        PostgreSQL CLIENT_ENCODING UTF8
        Perl output encoding ''
Showing current Oracle encoding and possible PostgreSQL client encoding:
        Oracle NLS_LANG AMERICAN_AMERICA.AL32UTF8
        Oracle NLS_NCHAR AL32UTF8
        Oracle NLS_TIMESTAMP_FORMAT YYYY-MM-DD HH24:MI:SS.FF6
        Oracle NLS_DATE_FORMAT YYYY-MM-DD HH24:MI:SS
        PostgreSQL CLIENT_ENCODING UTF8

not sure if LongReadLen or LongTruncOk parameters would help here. could you please guide on this issue.

**Comment by darold** [comment]
See  LONGREADLEN, NO_LOB_LOCATOR and LOB_CHUNK_SIZE in ora2pg.conf.
