### ISSUE TITLE
How to migrate numbers

### ISSUE THREAD

**Issue by unrandom123** [darold/ora2pg#961]
A few questions
1) When I export table structures, is there a way to specify that column C in table T in schema S should be of a particular type?

2) If I really don't want to loose any precision, should I then set  `  pg_numeric_type 0` ?  Do I also need to set DEFAULT_NUMERIC to numeric?

3) With pg_numeric_type, will procedures,packages,etc. automatically have numeric type?

4) If some columns should not be numeric but can be int/bigint, is it then best practice to:
  *) export in full precision,
  *)  create tables in Postgresql (and modify individual columns)
  *) import (assuming numeric values will be converted to the acctual column type)

**Comment by darold** [comment]
1) no, usually this is done using ALTER in a post migration script.

2) yes for the first question. For the second it depend if NUMBER() without precision can store decimal number, in this case you will have to set  DEFAULT_NUMERIC to numeric. 

3) it used to apply the data type conversion rules, yes.

4) it depend of the number of change you will have to perform in the post migration. Usually only few cols need high precision so it is best to change them at the post migration but it can be the opposite depending of the application.

I used to create all table using the default translation data type with `pg_numeric_type 0` and identify the columns that need high precision and change the type. After that I import 1000 or 5000 rows of each table to see if there is some errors when inserting decimal into a integer or bigint and adjust the data type if necessary.
