### ISSUE TITLE
CLOB columns that equal to 0 in Oracle are migrated as NULL in PostgreSQL

### ISSUE THREAD

**Issue by Rakutai** [darold/ora2pg#967]
CLOB columns that equal to 0 in Oracle are migrated as NULL values in PostgreSQL. 

Tried EMPTY_LOB_NULL and NULL_EQUAL_EMPTY parameters, but still NULLs in PostgreSQL for those rows that had 0 in CLOB column in Oracle.

Any workaround or solution for this?

**Comment by darold** [comment]
Use latest development code if I recall well this problem have been solved.

**Comment by Rakutai** [comment]
I am using Ora2Pg v20.0, isn't this the latest?

**Comment by darold** [comment]
yes exactly.
