### ISSUE TITLE
Getting Errors while executing the Tables.sql

### ISSUE THREAD

**Issue by kirandba-hub** [darold/ora2pg#969]
Hi,

I have generated the table DDL of Oracle schema,when i am trying to execute it on postgres it is giving an Error "psql:/etc/ora2pg/GDSRM_SDM_Migration/GDSRM_SDM_TABLE.sql:400: ERROR:  syntax error at or near "::""

It is Failing at Create index statement

Can you please help me on this

Best Regards,
Kiran

**Comment by darold** [comment]
If you want help on this please post the DDL statement at line 400 from file etc/ora2pg/GDSRM_SDM_Migration/GDSRM_SDM_TABLE.sql

**Comment by kirandba-hub** [comment]
Hi Darold,

Thanks for the prompt reply,below is the DDL statement with Error

CREATE INDEX "idx$$_1220b0011" ON config_event_of_interest ((pt_code) :=numeric);
ERROR:  syntax error at or near ":="
LINE 1: ...1220b0011" ON config_event_of_interest ((pt_code) :=numeric)...

Regards,
Kiran

**Comment by darold** [comment]
Do you have the DDL on Oracle side? It looks that Ora2Pg is missing a default value.

**Comment by kirandba-hub** [comment]
Hi Darold,

Below is the DDL on Oracle end.

CREATE INDEX "GDSRM_SDM"."IDX$$_1220B0011" ON "GDSRM_SDM"."CONFIG_EVENT_OF_INTEREST" (TO_NUMBER("PT_CODE"))
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GDSRM_SDM"

Regards,
Kiran

**Comment by darold** [comment]
New commit f8df539 fixes this issue, use latest development code. Thanks for the report.

**Comment by kirandba-hub** [comment]
Hi Darold,

Can you help me out with steps to upgrade.

Regards,
Kiran

**Comment by darold** [comment]
```
wget https://github.com/darold/ora2pg/archive/master.zip
unzip master.zip
cd ora2pg-master/
perl Makefile.PL
make
sudo make install
```
