### ISSUE TITLE
Oracle package Global variables migration to postgreSQL

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#970]
HI Darold

Hope you are doing great !!

Oracle allow the use of global variables defined in packages. And these global variables can be used in package methods. I read that ora2pg will export these global variables for PostgreSQL as user defined custom
variables available in a session. But I didn't see them.
Secondly, If the variable is a constant or have a default value assigned at declaration, ora2pg created a file global_variables.conf, not sure how we can deploy the file into PostgreSQL.

can you please help me on these two questions?

**Comment by darold** [comment]
The custom variables are exported in file global_variables.conf, if you want to use it paste its content at end of your postgresql.conf or use the `include` configuration directive in your postgresql.conf to use this file.

**Comment by naveenjul29** [comment]
can I please have an example like how to use this Include directive in my ora2pg configuration file? and also i see that **only constant variables** are exported into global_variables.conf file but not the variables inside the package specification, how can i export them?

**Comment by darold** [comment]
I said "use the include configuration directive in your postgresql.conf" not ora2pg.conf

About global variables that are not constants they should be present in the global_variables.conf. If you can send the code of a package declaration + package body with this problem to my private email I will be able to find what's wrong with this export.

**Comment by darold** [comment]
Thanks for the code to reproduce, commit a5d3004 fixes this regression. Use latest development code.
