### ISSUE TITLE
Create Index failing in Postgres

### ISSUE THREAD

**Issue by kirandba-hub** [darold/ora2pg#971]
Hi Darold,

Create Index is failing with below error

psql:/etc/ora2pg/GDSRM_SDM_Migration/GDSRM_SDM_TABLE.sql:1205: ERROR:  syntax error at or near "::"
LINE 1: ...EATE INDEX xbiidim_case_32 ON dim_case (version_no::varchar|...

DDL : CREATE INDEX xbiidim_case_32 ON dim_case (version_no::varchar||case_version_no::varchar);

Oracle DDL : CREATE BITMAP INDEX "GDSRM_SDM"."XBIIDIM_CASE_32" ON "GDSRM_SDM"."DIM_CASE" (TO_CHAR("VERSION_NO")||TO_CHAR("CASE_VERSION_NO"))
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GDSRM_SDM"

Can you please help me out on this.

Thanks and Regards,
Kiran

**Comment by darold** [comment]
This is the same issue as reported and fixed in #969.

**Comment by darold** [comment]
Actually same problem but with TO_CHAR which is now solved with commit  740205d
