### ISSUE TITLE
Question : Ora2pg not converting total rows in few table

### ISSUE THREAD

**Issue by kirandba-hub** [darold/ora2pg#972]
Hi Darold,

Recently we have migrated one schema from Oracle,we have total 66 tables,out of these tables around 20 tables the count is mismatch when compared from Oracle to Postgres.

Is there any reason for this data not migrating.
Any work around solution to achieve count mismatch?

Thanks,
Kiran.

**Comment by darold** [comment]
Issue #781 reports problem on object count in TEST action, I have planned to work on it in the next days.
