### ISSUE TITLE
ERROR:  invalid input syntax for integer: "64.8"

### ISSUE THREAD

**Issue by kirandba-hub** [darold/ora2pg#973]
HI Darold,

I am getting the error while importing the table.sql in postgres,i attached the output.
[Error_import_table_Postgres.txt](https://github.com/darold/ora2pg/files/5248137/Error_import_table_Postgres.txt)

only 20% of rows inserted.Can you help out how to solve this as this table is important for applications.

Thanks in advance.

Best Regards,
Kiran

**Comment by darold** [comment]
Column height of table DIM_CASE have been migrated into type integer but it should be float or double precision. I guess that the Oracle column was NUMBER without precision and the default is to export into bigint. An ALTER command is necessary to change the data type. Note that if you have columns which require high precision you must also probably change the data type from float or double precision into numeric otherwise you will lost precision. This is almost the case with monetary columns.

**Comment by luss** [comment]
Is there an option to round when an Integer data type gets chosen for the
pg destination schema?
.

**Comment by kirandba-hub** [comment]
@darold So,i need to alter the column which is having  NUMBER data type to bigint data type.Is that right?

**Comment by darold** [comment]
See ora2pg.conf and PG_NUMERIC_TYPE to keep precision or DEFAULT_NUMERIC that can be set to numeric to replace NUMBER without precision.

**Comment by darold** [comment]
@luss unfortunately there is no way yet to round data when exporting data. I have this feature (on the fly data modification through function call) in my todo list for a long time but still not had time to develop it.

**Comment by kirandba-hub** [comment]
@darold , Thanks for the suggestion,i will change these parameters in configurations and extract the data.I have one question,oracle database NLS_CHARACTERSET is AL32UTF8 and Postgres database UFT8,
Should i change the characterset in postgres same as in Oracle database.

Thanks,
Kiran

**Comment by darold** [comment]
These parameters are not used when exporting data, they are used for DDL export (type = TABLE) so you will have to recreate your tables with the output. You can limit the DDL override to the tables where you have this problem.

About encoding if Oracle and PostgreSQL are using utf8 encoding you have nothing to change to the default ora2pg.conf.

**Comment by kirandba-hub** [comment]
@darold ,Thanks a lot for the inputs,i have exported the DDL of Table as suggested and imported the data without any issues.

Regards,
Kiran
