### ISSUE TITLE
export data --out of memory

### ISSUE THREAD

**Issue by hotsmile** [darold/ora2pg#976]
WARNING: target PostgreSQL version must be set in PG_VERSION configuration directive. Using default: 11
[========================>] 775/775 tables (100.0%) end of scanning.                            
[>                        ]   0/775 tables (0.0%) end of scanning.                             
[========================>] 775/775 tables (100.0%) end of table export.                   
[========================>] 17/17 views (100.0%) end of output.                         
[========================>] 229/229 sequences (100.0%) end of output.                          
[========================>] 19/19 functions (100.0%) end of functions export.   
[========================>] 13/13 procedures (100.0%) end of procedures export.      
[========================>] 11/11 packages (100.0%) end of output.                          
[========================>] 0/0 rows (100.0%) Table AAS_ALL_USERGROUP_MAP_BAK0821 (0 recs/sec)
[>                        ]        0/11857680 total rows (0.0%) - (1 sec., avg: 0 recs/sec).  
Out of memory!            ]        0/11857680 rows (0.0%) on total estimated data (1 sec., avg: 0 recs/sec)
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=xxxxx)(PORT=1526))(ADDRESS=(PROTOCOL=tcp)(HOST=xxx)(PORT=1521)))(CONNECT_DATA=(SID=orcl))) at /usr/local/lib64/perl5/DBD/Oracle.pm line 364.

**Comment by darold** [comment]
I guess you are running a migration assessment? I is know to have OOM on some condition but unfortunately I was still not able to reproduce this issue to fix it.

**Comment by darold** [comment]
Also be sure to run latest development code from `git clone` or `wget https://github.com/darold/ora2pg/archive/master.zip`
