### ISSUE TITLE
estimated  cost in Days

### ISSUE THREAD

**Issue by orenbouni** [darold/ora2pg#978]
When i see the estimated cost in Days, it is considered as a working day of 8 hours and a full day 24 hours?

-- Total estimated cost: 57.5 units, 1 man-day(s). 

8 H or 24 H

**Comment by darold** [comment]
This is 8 hours, humans are still humans :-) Here with a total estimated cost of 57.5 default units it will take (57.5×5 min)/60 min = 4,8 hours but Ora2Pg always reports a minimum of 1 man-day. The default time for a unit is 5 minutes but you can adjust the unit value with option `--cost_unit_value`
