### ISSUE TITLE
Ora2pg is not converting record variables into PostgreSQL

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#979]
Ora2pg is not converting record variables into PostgreSQL. For example, below is the record type variable in Oracle:

TYPE emp_det is RECORD
(
EMP_NO NUMBER := 1,
EMP_NAME VARCHAR2(150):='aa',
MANAGER NUMBER:= 3,
SALARY NUMBER :=100
);

Ora2pg is converted as below:

CREATE TYPE employee_pkg.emp_det AS (
EMP_NO bigint := 1,
EMP_NAME varchar(150):='aa',
MANAGER bigint:= 3,
SALARY bigint :=100
);

Ora2pg is converting record type variables to user defined type. Also, In PostgreSQL, we cannot initialize the variable values at the time of creation, so when I deploy the above script, I got the error.

**Comment by darold** [comment]
Thanks Naveen.

**Comment by darold** [comment]
Commit 2024898 fixes this issue.
