### ISSUE TITLE
FDW Export

### ISSUE THREAD

**Issue by kirandba-hub** [darold/ora2pg#980]
Hi Darold,

I have created the extension oracle_fdw in Postgres database,and i created server and user mapping. Before the link to the remote database can be used, it is necessary to create the remote tables in the local database for this i am using

ora2pg -c ora2pg.conf -t FDW -a <table_name>

I am getting no output,should i enable/update any parameter in ora2pg.conf file,also can i get the FDW type for schema instead of each table.

Thanks and Regards,
Kiran

**Comment by darold** [comment]
Please upgrade to latest development code this issue has been solved in commit b8045ad past weekend.

**Comment by kirandba-hub** [comment]
Hi Darold,

Thank you for the steps, but still i am not able see the output.

Below is the Oracle_fdw_master installation steps

![image](https://user-images.githubusercontent.com/65154051/93822582-716ebf80-fc2e-11ea-8e46-78dd5fd13db3.png)

After that i used below commands to get the output

ora2pg -c ora2pg.conf -t FDW
[========================>] 92/92 tables (100.0%) end of scanning.

  0 Sep 21 17:06 output.sql

Can you please help me where i am missing,should i need to update parameter FDW_SERVER in confg file

Thanks and Regards,
Kiran
