### ISSUE TITLE
How you are exporting the package variables in oracle into global_variables.conf file

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#982]
Darold, I just want to know How you are exporting the package variables in oracle into global_variables.conf file?

What is the logic behind this? are you running a query?

**Comment by darold** [comment]
There is a chapter on Ora2Pg documentation about this topic: http://ora2pg.darold.net/documentation.html#Global-variables

**Comment by naveenjul29** [comment]
**_sorry Darold, my question is, how you are checking that If the variable is a constant or have a default value assigned at declaration. For example, below is my package specification code:_**

Create or replace PACKAGE Employee_pkg  as
	g_phone varchar2(50) := '12345' ;
	c_Hiredate constant date := '20-JAN-20';

	CURSOR employees_cursor IS  -- declaring a cursor
		SELECT
			EMPLOYEE_ID,
			FIRST_NAME,
			SALARY
		FROM
			EMPLOYEES;

	CURSOR c_salary (low_salary NUMBER, high_salary NUMBER) IS
        	SELECT *
        	FROM EMPLOYEES
        	WHERE SALARY BETWEEN low_salary AND high_salary;

	TYPE emp_det is RECORD
	(
		EMP_NO NUMBER := 1,
		EMP_NAME VARCHAR2(150):='aa',
		MANAGER NUMBER:= 3,
	SALARY NUMBER :=100 
	);

	TYPE emp_id IS TABLE OF number;

	Procedure Get_emp_rec (Emp_number  IN  OT.EMPLOYEES.EMPLOYEE_ID%TYPE, Emp_ret    OUT OT.EMPLOYEES%ROWTYPE) ;

	Function update_emp_record(Emp_number  IN  OT.EMPLOYEES.EMPLOYEE_ID%TYPE) RETURN VARCHAR2;

END Employee_pkg;

**_Now, my question is, how can I extract the variables defined in this package into a separate file?  that means, my new file should have the below content:_**

	g_phone varchar2(50) := '12345' ;
	c_Hiredate constant date := '20-JAN-20';

	CURSOR employees_cursor IS  -- declaring a cursor
		SELECT
			EMPLOYEE_ID,
			FIRST_NAME,
			SALARY
		FROM
			EMPLOYEES;

	CURSOR c_salary (low_salary NUMBER, high_salary NUMBER) IS
        	SELECT *
        	FROM EMPLOYEES
        	WHERE SALARY BETWEEN low_salary AND high_salary;

	TYPE emp_det is RECORD
	(
		EMP_NO NUMBER := 1,
		EMP_NAME VARCHAR2(150):='aa',
		MANAGER NUMBER:= 3,
	SALARY NUMBER :=100 
	);

	TYPE emp_id IS TABLE OF number;

_**Any idea, how we can do this?**_
