### ISSUE TITLE
BLOB Table not generating DDL and data copy

### ISSUE THREAD

**Issue by kirandba-hub** [darold/ora2pg#983]
Hi Darold,

I have one table with below columns, this table is not getting extracted using,Can you suggest how i need to proceed with below approach. 

NAME                                               VARCHAR2(700)
 LOB                                                BLOB
 LOADTIME                                           DATE

Thanks and Regards,
Kiran

**Comment by NishanthBejgam** [comment]
Hey, I tried generating the DDL for BLOB with default settings it will convert the DDL type to bytea, and following I attached the type conversion that you get with default - 

CREATE TABLE ot.datatypes (
	bfile BFILE 3001,
	binary_float double precision,
	binary_double double precision,
	blob bytea,
	char char(10),
	character char(10),
	clob text,
	nclob text,
	date timestamp,
	decimal real,
	dec real,
	double_precision double precision,
	float double precision,
	integer numeric(38),
	int numeric(38),
	interval_year INTERVAL YEAR TO MONTH,
	interval_day INTERVAL DAY TO SECOND(4),
	long text,
	nchar char(10),
	nchar_varying varchar(10),
	number double precision,
	number1 integer,
	"number(*)" bigint,
	numeric double precision,
	nvarchar2 varchar(10),
	raw bytea,
	real double precision,
	row_id CHARACTER(255)
/* [ 3005 - Severity LOW - PostgreSQL doesn't have a data type ROWID , converted to CHARACTER instead.] */,
	smallint numeric(38),
	timestamp timestamp,
	timestamp_with_time_zone timestamp with time zone,
	urowid CHARACTER VARYING(255)
/* [ 3006 - Severity LOW - PostgreSQL doesn't have a data type UROWID , converted to CHARACTER instead.] */,
	varchar varchar(10),
	varchar2 varchar(10),
	xmltype xml
) ;

**Comment by kirandba-hub** [comment]
Thanks for replying...I am also using default settings.can you please share your parameters configured at your end.

Regards,
Kiran

**Comment by NishanthBejgam** [comment]
I used the configuration under latest- Please check if you using the same - 
https://github.com/darold/ora2pg/archive/master.zip

Or could try by changing config setting as following- 
DATA_TYPE BLOB:bytea;

the possible settings for DATA_TYPE as follows - 
        DATA_TYPE       DATE:timestamp,LONG:text,LONG RAW:bytea,CLOB:text,NCLOB:text,BLOB:bytea,BFILE:bytea,RAW:bytea,UROWID:oid,ROWID:oid,FLOAT:double precision,DEC:decimal,DECIMAL:decimal,DOUBLE PRECISION:double precision,INT:numeric,INTEGER:numeric,REAL:real,SMALLINT:smallint,BINARY_FLOAT:double precision,BINARY_DOUBLE:double precision,TIMESTAMP:timestamp,XMLTYPE:xml,BINARY_INTEGER:integer,PLS_INTEGER:integer,TIMESTAMP WITH TIME ZONE:timestamp with time zone,TIMESTAMP WITH LOCAL TIME ZONE:timestamp with time zone

**Comment by kirandba-hub** [comment]
Thank you...I will check that
