### ISSUE TITLE
%ROWTYPE is removed in Source Code extraction for Packages, Functions and Procedures

### ISSUE THREAD

**Issue by jagmohankaintura-tl** [darold/ora2pg#986]
All the variable declarations which were done using %ROWTYPE have issues while extracting to PostgreSQL equivalent.
ROWTYPE is  completely Removed.

Example :
v_rec_master TMS_CNTR_GRP1**%ROWTYPE;** <-- Oracle

v_rec_master TMS_CNTR_GRP1;   <- POstgreSQL

Am  i missing some configuration setting that it happened for all the source code.

**Comment by darold** [comment]
Yes this is normal, %ROWTYPE doesn't exist in PostgreSQL and is useless so it is removed except for cursors where it is replaced by RECORD.

**Comment by jagmohankaintura-tl** [comment]
I raised it because we faced some issues in one of the Package procedure as %ROWTYPE was changed to RECORD . We move d that to %ROWTYPE and it worked.

%ROWTYPE we have used multiple places in PostgreSQL and its working fine.

Example : PostgreSQL 12.



tms_owner_cz1qa@zdcq12c2:5436=> create table emp (empno numeric,name varchar);
CREATE TABLE
tms_owner_cz1qa@zdcq12c2:5436=> insert into emp values (1,'Jagmohan'),(2,'darold');
INSERT 0 2
tms_owner_cz1qa@zdcq12c2:5436=>
tms_owner_cz1qa@zdcq12c2:5436=> select * from emp;
 empno |   name
-------+----------
     1 | Jagmohan
     2 | darold
(2 rows)

tms_owner_cz1qa@zdcq12c2:5436=> DO
zdcq12c2-> $$
zdcq12c2$> DECLARE
zdcq12c2$>   EMP_REC emp%rowtype;
zdcq12c2$>   emp_cur cursor for
zdcq12c2$> select * from emp;
zdcq12c2$> BEGIN
zdcq12c2$>   open emp_cur;
zdcq12c2$>   loop
zdcq12c2$> fetch emp_cur into EMP_REC;
zdcq12c2$> exit when not found;
zdcq12c2$> raise info 'Emp Name Id : % , Emp No : %',EMP_REC.name,EMP_REC.empno;
zdcq12c2$>   end loop;
zdcq12c2$>   close emp_cur;
zdcq12c2$> END$$;
INFO:  Emp Name Id : Jagmohan , Emp No : 1
INFO:  Emp Name Id : darold , Emp No : 2
DO

**Comment by darold** [comment]
You are right, I don't know where this mistake come from, removing of %ROWTYPE should be only limited to TYPE REF CURSOR declaration. Commit d970f1b might fix this issue.

**Comment by edelanoe** [comment]
Hello Darold,
Unfortunately, this does not work in function declarations, so it makes a regression. Can you reopen ?
Best Regards,
E.D.

**Comment by darold** [comment]
Hi Eric,

What doesn't work on function declarations? Can you provide an example please?

**Comment by edelanoe** [comment]
psql (12.4, server 13.1)
WARNING: psql major version 12, server major version 13.
         Some psql features might not work.
Type "help" for help.

myPostgresDB=#  create table emp (empno numeric,name varchar);
CREATE TABLE
myPostgresDB=# CREATE OR REPLACE FUNCTION test (p_emp emp%ROWTYPE) as $$
myPostgresDB$# begin
myPostgresDB$#      insert into emp (empno, name) values (p_emp.empno, p_emp.name);
myPostgresDB$# end$$;
ERROR:  syntax error at or near "%"
LINE 1: CREATE OR REPLACE FUNCTION test (p_emp emp%ROWTYPE) as $$
                                                  ^
STATEMENT:  CREATE OR REPLACE FUNCTION test (p_emp emp%ROWTYPE) as $$
begin
        insert into emp (empno, name) values (p_emp.empno, p_emp.name);
end$$;
myPostgresDB=#

**Comment by darold** [comment]
ah ok I see, thanks.

**Comment by darold** [comment]
Commit 30f966e might fix this regression.

**Comment by edelanoe** [comment]
Hello Gilles,
Regression is still present in ora2pg master downloaded june 3 2022. Could you reopen please ?
Rgds,
Eric

**Comment by darold** [comment]
Commit 64a170f might fix the regression.

**Comment by edelanoe** [comment]
Still there with latest master. Example:
Oracle
    FUNCTION SUB_REN_MANAGE_VARS( p_abo_data IN W_STRUCT_GCL_OP_DATA%ROWTYPE
                                , p_type_of_gcl_operation IN T_TYPE_OF_GCL_OPERATION.type_of_gcl_operation_id%TYPE
                                , p_mode IN BINARY_INTEGER default null
                                ) RETURN W_STRUCT_GCL_OP_DATA%ROWTYPE IS
Postgres:
CREATE OR REPLACE FUNCTION pck_gcl.sub_ren_manage_vars ( p_abo_data W_STRUCT_GCL_OP_DATA%ROWTYPE , p_type_of_gcl_operation T_TYPE_OF_GCL_OPERATION.type_of_gcl_operation_id%TYPE , p_mode integer default null) RETURNS W_STRUCT_GCL_OP_DATA%ROWTYPE AS $body$

**Comment by darold** [comment]
Sorry Eric, I had not well understood the problem. Commit 9c152cc might be the right fix.
