### ISSUE TITLE
Can we call functions with FDW,Like Create Foreign Tables

### ISSUE THREAD

**Issue by kirandba-hub** [darold/ora2pg#988]
Hi Darolad,

I have a MVIEW,in that one function is calling remotely (from Oracle),We are using Create Foreign Tables using "ora2pg -c ora2pg.conf -t FDW is there any similar option for Functions?

Thanks and Regards,
Kiran

**Comment by darold** [comment]
No you can not call a remote function through FDW, what you are looking for can be achieve using plperlu extension and a Perl function using DBD::Oracle to connect to the remote database and execute the function.

**Comment by kirandba-hub** [comment]
Thanks Darold for infromation
