### ISSUE TITLE
Loading data from Oracle to PostgreSQL in parallel mode

### ISSUE THREAD

**Issue by Rakutai** [darold/ora2pg#989]
Hi, 

I've been trying to load data of 2 tables from Oracle to PostgreSQL in parallel mode and used "-j", "-J", "-P" options of ora2pg:
ora2pg -j 4 -J 4 -P 4 -c config/ora2pg.conf -t COPY --pg_dsn "dbi:Pg:dbname=testdb;host=abc;port=5432" --pg_user myuser--pg_pwd mypassword

But according to the list of processes and the number of sessions it created in Oracle and PostgreSQL, it seems like 
1) it is loading data of table ENTRY_AUDIT into PostgreSQL in 4 parallel sessions, but not exporting data from Oracle in 4 sessions/processes
2) it hasn't started loading data of table FEATURE_AUDIT into PostgreSQL, although it shows that it is querying data from Oracle.

root     58356     1  0 11:35 pts/0    00:00:00 ora2pg logger
root     58357     1 23 11:35 pts/0    00:01:18 ora2pg - querying table ENTRY_AUDIT
root     58358     1  0 11:35 pts/0    00:00:03 ora2pg - querying table FEATURE_AUDIT
root     59112 58357 44 11:40 pts/0    00:00:12 ora2pg - sending data from table ENTRY_AUDIT to table ENTRY_AUDIT
root     59113 58357 49 11:40 pts/0    00:00:09 ora2pg - sending data from table ENTRY_AUDIT to table ENTRY_AUDIT
root     59114 58357 43 11:40 pts/0    00:00:06 ora2pg - sending data from table ENTRY_AUDIT to table ENTRY_AUDIT
root     59224 58357 34 11:40 pts/0    00:00:00 ora2pg - sending data from table ENTRY_AUDIT to table ENTRY_AUDIT

Is this how it is supposed to load data in parallel or am I using the options incorrecly? Currenly, the load speed is only 12500 recs/sec.

**Comment by darold** [comment]
Hi,

The problem here is that you are using both options `-J` and `-P`, they are not compatible. Actually when you use parallel table (-P) processing this disable the parallel Oracle single table (-J) processing. You have to make a choice.

**Comment by darold** [comment]
Forgot to mention that if you want to use the `-J` option you have to set DEFINED_PK unless there is a primary key or a unique constraint on a numeric column.
