### ISSUE TITLE
Export is taking lot of time

### ISSUE THREAD

**Issue by chaluvadi286** [darold/ora2pg#990]
Hi Darold,

I have installed Strawberry Perl and latest version of Ora2pg-master from GitHub today. With this the export is taking good amount of time, earlier it used to completed very fast. I observed that below query is running for last 40 mins (still running) and
no progress reported at command prompt, looks it is at first step itself. I am running it on Windows 10 OS. 

SELECT A.OWNER,A.TABLE_NAME,NVL(num_rows,1) NUMBER_ROWS,A.TABLESPACE_NAME,A.NESTED,A.LOGGING,A.PARTITIONED,A.PCT_FREE FROM DBA_TABLES A, ALL_OBJECTS O WHERE A.OWNER=O.OWNER AND A.TABLE_NAME=O.OBJECT_NAME AND O.OBJECT_TYPE='TABLE' AND A.OWNER='K1Q220'  AND A.TEMPORARY='N' AND (A.NESTED != 'YES' OR A.LOGGING != 'YES') AND A.SECONDARY = 'N' AND (A.DROPPED IS NULL OR A.DROPPED = 'NO') AND (A.OWNER, A.TABLE_NAME) NOT IN (SELECT OWNER, MVIEW_NAME FROM ALL_MVIEWS UNION ALL SELECT LOG_OWNER, LOG_TABLE FROM ALL_MVIEW_LOGS) AND (A.OWNER, A.TABLE_NAME) NOT IN (SELECT OWNER, TABLE_NAME FROM ALL_OBJECT_TABLES) AND (  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p1) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p2) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p3) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p4) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p5) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p6) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p7) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p8) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p9) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p10) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p11) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p12) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p13) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p14) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p15) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p16) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p17) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p18) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p19) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p20) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p21) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p22) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p23) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p24) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p25) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p26) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p27) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p28) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p29) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p30) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p31) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p32) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p33) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p34) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p35) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p36) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p37) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p38) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p39) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p40) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p41) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p42) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p43) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p44) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p45) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p46) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p47) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p48) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p49) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p50) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p51) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p52) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p53) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p54) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p55) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p56) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p57) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p58) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p59) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p60) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p61) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p62) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p63) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p64) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p65) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p66) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p67) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p68) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p69) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p70) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p71) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p72) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p73) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p74) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p75) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p76) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p77) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p78) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p79) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p80) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p81) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p82) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p83) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p84) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p85) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p86) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p87) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p88) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p89) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p90) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p91) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p92) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p93) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p94) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p95) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p96) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p97) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p98) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p99) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p100) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p101) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p102) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p103) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p104) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p105) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p106) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p107) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p108) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p109) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p110)) AND (A.IOT_TYPE IS NULL OR A.IOT_TYPE = 'IOT');

Attached the configuration I am using, command **ora2pg.bat -c k1q220.conf**
[k1q220.zip](https://github.com/darold/ora2pg/files/5306073/k1q220.zip)

**Comment by chaluvadi286** [comment]
After executing for 70 minutes, it has failed with temp tablespace error, looks query requires tuning

D:\work\ICC\strawberry\perl\site\bin>ora2pg.bat -c k1q220.conf
FATAL: ORA-01652: unable to extend temp segment by 128 in tablespace TEMP (DBD ERROR: error possibly near <*> indicator at char 2773 in 'SELECT A.OWNER,A.TABLE_NAME,NVL(num_rows,1) NUMBER_ROWS,A.TABLESPACE_NAME,A.NESTED,A.LOGGING,A.PARTITIONED,A.PCT_FREE FROM DBA_TABLES A, ALL_OBJECTS O WHERE A.OWNER=O.OWNER AND A.TABLE_NAME=O.OBJECT_NAME AND O.OBJECT_TYPE='TABLE' AND A.OWNER='K1Q220'  AND A.TEMPORARY='N' AND (A.NESTED != 'YES' OR A.LOGGING != 'YES') AND A.SECONDARY = 'N' AND (A.DROPPED IS NULL OR A.DROPPED = 'NO') AND (A.OWNER, A.TABLE_NAME) NOT IN (SELECT OWNER, MVIEW_NAME FROM ALL_MVIEWS UNION ALL SELECT LOG_OWNER, LOG_TABLE FROM ALL_MVIEW_LOGS) AND (A.OWNER, A.TABLE_NAME) NOT IN (SELECT OWNER, TABLE_NAME FROM ALL_OBJECT_TABLES) AND (  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p1) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p2) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p3) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p4) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p5) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p6) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p7) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p8) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p9) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p10) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p11) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p12) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p13) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p14) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p15) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p16) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p17) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p18) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p19) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p20) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p21) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p22) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p23) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p24) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p25) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p26) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p27) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p28) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p29) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p30) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p31) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p32) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p33) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p34) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p35) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p36) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p37) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p38) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p39) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p40) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p41) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p42) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p43) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p44) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p45) AND  NOT REGEXP<*>_LIKE(UPPER(A.TABLE_NAME), :p46) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p47) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p48) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p49) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p50) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p51) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p52) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p53) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p54) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p55) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p56) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p57) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p58) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p59) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p60) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p61) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p62) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p63) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p64) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p65) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p66) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p67) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p68) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p69) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p70) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p71) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p72) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p73) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p74) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p75) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p76) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p77) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p78) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p79) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p80) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p81) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p82) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p83) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p84) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p85) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p86) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p87) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p88) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p89) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p90) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p91) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p92) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p93) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p94) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p95) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p96) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p97) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p98) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p99) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p100) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p101) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p102) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p103) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p104) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p105) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p106) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p107) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p108) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p109) AND  NOT REGEXP_LIKE(UPPER(A.TABLE_NAME), :p110)) AND (A.IOT_TYPE IS NULL OR A.IOT_TYPE = 'IOT')')
Aborting export...

D:\work\ICC\strawberry\perl\site\bin>

**Comment by darold** [comment]
You should contact your Oracle DBA, this is an ORACLE error that could be fixed by increasing the TEMP tablespace.

**Comment by chaluvadi286** [comment]
Thanks Darold, after gathering stats for entire database export is working

EXEC DBMS_STATS.gather_database_stats;
