### ISSUE TITLE
modulus and a remainder for each partition is coming twice

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#991]
modulus and a remainder for each partition is coming twice. Attaching the sample output file for your reference.

Also, in the script file, I am getting the error at below highlighted line:

CREATE TABLE "aw$fpapjp_ptn1" PARTITION OF aw$fpapjp
FOR VALUES FROM (MINVALUE) TO (1)
**PARTITION BY HASH (ps#,extnum);**

[partitions1.txt](https://github.com/darold/ora2pg/files/5309866/partitions1.txt)

**Comment by darold** [comment]
I'm not able to reproduce the issue with test partitions, if you can post the Oracle DLL of the table and its partitioning I will give it a try.
