### ISSUE TITLE
I'm not getting standard output and standard error file while executing import_all.sh

### ISSUE THREAD

**Issue by murthylspace** [darold/ora2pg#992]
[root@localhost ~]# ora2pg --version
Ora2Pg v20.0

./import_all.sh -d postgres -h hostname -U postgres -o postgres -l output.all

After executing above command, it didn't create  any output file in the current directory.  Is it creating somewhere else?

**Comment by darold** [comment]
Commit f667faa remove this option from the autogenerated script import_all.sh as you notice it is useless and not used at all in the script. This script is interactive unless you use the `-y` option so log file for stdout is not possible, with the `-y` option you just have to redirect the output to a file as follow:
```
./import_all.sh -d postgres -h hostname -U postgres -o postgres -y > output.all 2>&1
```

**Comment by murthylspace** [comment]
Thanks for your response.

With out -y option, I did it with the below command.

current_time=$(date "+%Y.%m.%d-%H.%M.%S")
./import_all.sh -d postgres -h hostname -U postgres -o postgres 2>&1 | tee output_$current_time.all

It is more useful if we have timestamp with it.

Thanks
Murthy
