### ISSUE TITLE
Not getting test rows count from postgresql schema.

### ISSUE THREAD

**Issue by murthylspace** [darold/ora2pg#993]
Hi Team,

[root@localhost ~]#  ora2pg --version
Ora2Pg v20.0

 ora2pg -t TEST --count_rows --pg_schema hr  -c config/ora2pg.conf
After executing above, getting below error. 

ORACLEDB:COUNTRIES:25
DBD::Pg::st execute failed: ERROR:  relation "countries" does not exist
LINE 1: SELECT count(*) FROM countries;
                             ^ at /usr/lib/perl5/site_perl/5.32.0/Ora2Pg.pm line 15629.

Tables exist with hr schema in postgres, but it is not looking at schema level when it comes to test rows count.

Thanks
Murthy

**Comment by darold** [comment]
What does `\d hr.countries` command in psql reports?

**Comment by murthylspace** [comment]
postgres@[local]:5432 postgres# \d hr.countries
                         Table "hr.countries"
    Column    |         Type          | Collation | Nullable | Default
--------------+-----------------------+-----------+----------+---------
 country_id   | character(2)          |           | not null |
 country_name | character varying(40) |           |          |
 region_id    | bigint                |           |          |
Indexes:
    "countries_pkey" PRIMARY KEY, btree (country_id)
Foreign-key constraints:
    "countr_reg_fk" FOREIGN KEY (region_id) REFERENCES hr.regions(region_id)
Referenced by:
    TABLE "hr.locations" CONSTRAINT "loc_c_id_fk" FOREIGN KEY (country_id) REFERENCES hr.countries(country_id)


This problem didn't happen when I used public schema. Only occurs when you choose the below directories.

EXPORT_SCHEMA   1
SCHEMA  HR

Thanks
Murthy

**Comment by darold** [comment]
Does latest development code still have this issue? I have pushed several commit to solve issue with the TEST action.

**Comment by murthylspace** [comment]
I uninstalled and reinstalled ora2pg with latest commits.

To uninstall ora2pg:

make uninstall -- it shows you some files to delete 

I deleted those files to uninstall ora2pg and reinstalled again with make command.

I also found the latest commit or modified line in /usr/lib/perl5/site_perl/5.32.0/Ora2Pg/PLSQL.pm to make sure it is latest.

Unfortunately, still getting the same error.

ORACLEDB:COUNTRIES:23
POSTGRES:hr.countries:25
ORACLEDB:CUSTOMERS:55500
DBD::Pg::st execute failed: ERROR:  relation "hr.customers" does not exist
LINE 1: SELECT count(*) FROM hr.customers;
                             ^ at /usr/lib/perl5/site_perl/5.32.0/Ora2Pg.pm line 16285.

You see the Error code is different. Can you please take a look at it.

Thanks
Murthy

Thanks
Murthy

**Comment by darold** [comment]
Good news, thanks for your help to improve this project.
