### ISSUE TITLE
Ora2pg Particular Partition Table 

### ISSUE THREAD

**Issue by balagaa** [darold/ora2pg#997]
The volume of data is very large in Oracle database
 . In this case, is it possible to export or import directly particular partition in a particular table using ora2pg . 
For example table name is TF_M_PROMO partition name is P202009  . 
I tried several options but unfortunately it is not working .

**Comment by darold** [comment]
I don't think it is possible to filter to a specific partition directly using ALLOW directive but a simple way is to use a WHERE clause that use the key partition that match the one you want to export. If you want to change the destination table using the REPLACE_TABLES directive.
